### ISSUE TITLE
Implement RHESSys resource step 1

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#10]
This involves
1. Settle the resource content model. This implies specification of the name for the resource type and documentation of the storage format. This may simply be listing of all the files needed by RHESSys and their hierarchical structure.  Specify the scientific metadata. This does not need to be the full content of the files.  It should just be that content we want to store separately to support discovery of the resource.  Initially this can be short, with the ability to expand later.
2. Add capability to upload and download resource files that are already in the specified storage format through web interface.  This may involve identifying a folder or individual files in the RHESSys folder hierarchy. Edit metadata through web interface. Serialize metadata.

The step 2 capability handles that raw files used by RHESSys and may parse metadata out of them but does not support loading of entire resources in the bagit packaging format.

Phase 2 and beyond are not part of this step and include the following that should be incrementally added later
- Add capability to upload and download resource files already is specified storage format through API. Set and get metadata through API.
-  Execute a RHESSys model
-  Generate RHESSys inputs from other HydroShare resources (EcoHydroLib functionality)
-  Export RHESSys outputs to another HydroShare resource
- Visualize RHESSys files
- Tool to import resource packages as a complete resource data model bag. This involves a reflector function to generate the metadata in Django from the XML format metadata and will support direct exchange of this resource type with iRODS and with other clients.

**Comment by hyi** [comment]
@dtarb Reassign to you to re-delegate this issue.

**Comment by aphelionz** [comment]
@dtarb @mjstealey Should we close this? Alternatively we can make a "deferred" or "bikeshed" label and stick them there.

**Comment by mjstealey** [comment]
> Should we close this?

Added Backburner to it, but I'd vote to close it since much has changed since Dec of 2014. A fresh start based on existing Jupyterhub work might be best.

**Comment by dtarb** [comment]
OK Closing
