### ISSUE TITLE
Raster Resource Band Information box too small

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#1009]
The box holding band content for raster resource specific metadata is too small.  This seems to be a new problem with the recent release.
![untitled](https://cloud.githubusercontent.com/assets/3456833/13328781/d2b9be4e-dbad-11e5-9c11-9a1f3eb53a19.png)

**Comment by mauriel133** [comment]
The PR containing this fix has been merged.

**Comment by hyi** [comment]
@dtarb Can you verify and close if it has been fixed?

**Comment by dtarb** [comment]
OK
