### ISSUE TITLE
Raster Resource Viewer fails to render a raster resource that is in geographic coordinates

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#1010]
The resource https://www.hydroshare.org/resource/a94af692e2d1442cad3797d23ed7cdf8/ is natively in geographic coordinates.  Raster viewer triggers the following error
![untitled](https://cloud.githubusercontent.com/assets/3456833/13329517/8bf7c3c6-dbb1-11e5-94fb-0dcc67525476.png)

**Comment by zhiyuli** [comment]
@dtarb 
A quick test shows the error occurred at GeoServer side. Looks like this tiff is incompatible to GeoServer. I tried to manually load it from GeoServer interface and got an error:
![image](https://cloud.githubusercontent.com/assets/10070599/13330114/839cd39e-dbb4-11e5-8346-cd6c9d7a2843.png)

**Comment by zhiyuli** [comment]
@dtarb @gantian127 
Can any of you tiff experts have a look at this file, is it well formatted? thanks

**Comment by dtarb** [comment]
I produced this as a subset from the national elevation dataset using ArcGIS.  You should be able to look at it in ArcGIS (I can).

**Comment by zhiyuli** [comment]
@dtarb 
Yes I can open it with ArcGIS. Is it possible to send me the original tiff? thanks

**Comment by dtarb** [comment]
The raw data I obtained from ftp://rockyftp.cr.usgs.gov/vdelivery/Datasets/Staged/NED/13/IMG/.  This is not in tiff format, it is IMG format.  I used ArcGIS to mosaic the various files that I wanted together.  I then clipped out the part that I want and exported from arcGIS as a tiff file.  What you have is the "raw" tiff file that is the end of this process.  You could download some of the USGS IMG files from the ftp site above if you want, but I do not think that will be helpful tracking this problem.  I think the difference between this tiff file and some others is that the coordinate system is actually geographic (i.e. latitude and longitude).  It has not been projected as is common with some raster files.

**Comment by zhiyuli** [comment]
@dtarb @selimnairb 
This is the info exacted by gdalinfo. Do you find anything wrong?

Driver: GTiff/GeoTIFF
Files: Onion.tif
Size is 6910, 2870
Coordinate System is:
GEOGCS["GCS_North_American_1983",
    DATUM["D_North_American_1983",
        SPHEROID["GRS_1980",6378137.0,298.257222101]],
    PRIMEM["Greenwich",0.0],
    UNIT["Degree",0.0174532925199433],
    VERTCS["Unknown VCS",
        VDATUM["Unknown"],
        PARAMETER["Vertical_Shift",0.0],
        PARAMETER["Direction",1.0],
        UNIT["Meter",1.0]]]
Origin = (-98.312407407408841,30.273425925922695)
Pixel Size = (0.000092592592593,-0.000092592592593)
Metadata:
  AREA_OR_POINT=Area
  DataType=Generic
Image Structure Metadata:
  COMPRESSION=LZW
  INTERLEAVE=BAND
Corner Coordinates:
Upper Left  ( -98.3124074,  30.2734259) ( 98d18'44.67"W, 30d16'24.33"N)
Lower Left  ( -98.3124074,  30.0076852) ( 98d18'44.67"W, 30d 0'27.67"N)
Upper Right ( -97.6725926,  30.2734259) ( 97d40'21.33"W, 30d16'24.33"N)
Lower Right ( -97.6725926,  30.0076852) ( 97d40'21.33"W, 30d 0'27.67"N)
Center      ( -97.9925000,  30.1405556) ( 97d59'33.00"W, 30d 8'26.00"N)
Band 1 Block=128x128 Type=Float32, ColorInterp=Gray
  NoData Value=-3.4028230607370965e+038
  Metadata:
    SourceBandIndex=0

**Comment by selimnairb** [comment]
@zhiyuli No off-hand.  Out of curiosity, if you re-project from NAD83 to WGS84 will GeoServer accept it?  You can do this easily with gdalwarp: `gdalwarp -t_srs EPSG:4326 src.tif dest.tif`.

**Comment by pkdash** [comment]
@zhiyuli Is this still an issue?

**Comment by dtarb** [comment]
Fixed.
