### ISSUE TITLE
Raster Viewer, allow for external WMS

### ISSUE THREAD

**Issue by selimnairb** [hydroshare/hydroshare#1025]
For large raster files it is not possible to download the entire resource and create WMS/tile visualization layers.  However, it is likely for such large data that someone has already gone to the trouble of creating WMS tiles.  We should take advantage of this and allow a raster resource to provide a JSON-formatted visualization configuration, stored in the *visualization* directory of the resource, to refer to pre-existing WMS URL for visualizing a raster.  If this file is present, the downloading and tiling of the raster should be skipped.

**Comment by zhiyuli** [comment]
@shawncrawley Shawn, I am re-assigning this to you. See if you could plan to implement this in the HydroShare GIS APP. thanks

**Comment by shawncrawley** [comment]
@gantian127, has this already been incorporated into the Raster resource? I can definitely incorporate a check for a visualization file into the HydroShare GIS app, but I cannot make much progress without an example raster resource to work with.

**Comment by gantian127** [comment]
@shawncrawley I think to create a JSON-formatted visualization configuration, stored in the visualization directory of the resource is not implemented.

**Comment by mjstealey** [comment]
@shawncrawley Is this still a thing?

**Comment by danames** [comment]
This visualization file would need to be implemented by @gantian127 before it can be implemented in HydroShare GIS. I am closing this issue as it is a bit out of scope and we should focus on the general implementation of all geospatial resources as OGC services.
