### ISSUE TITLE
bug in Model Program resource page_processors.py after updating to Django 1.89

### ISSUE THREAD

**Issue by mohamedmorsy** [hydroshare/hydroshare#1026]
I got this bug during creating new Model Program resource type 

![image](https://cloud.githubusercontent.com/assets/5543781/13433799/6e1d70f0-dfa1-11e5-94c8-07d3833c1a36.png)

**Comment by mjstealey** [comment]
Context:

Updates for hs_model_program: https://github.com/hydroshare/hydroshare/pull/1012/files#diff-42f0e0c5e10238a378bb3c2147aab8d8

In debug mode, the error will get generated when encountering the last item:

![screen shot 2016-03-01 at 2 06 06 pm](https://cloud.githubusercontent.com/assets/5332509/13438747/5434c1d6-dfb8-11e5-8cb0-9aae0c183dfa.png)

**Comment by mjstealey** [comment]
resolved
