### ISSUE TITLE
Add capability to copy a resource

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#1029]
I think we need a button to allow a user to copy a resource that is shareable. This would allow them to copy the content then start working on it, say if they want to adjust it for inputs to their model or workflow.

Note that this is different from versioning, in that versioning is available only to resource owners and specifically holds forwards and backwards version pointers that establish and obsolescence chain.  

When a copy is made, a relationship "Copied from" should be added to point back to the original resource.

This functionality would add to the existing resource manipulation functionality that we have, comprised of Create, Edit, Delete, and Create a New Version Version.

**Comment by horsburgh** [comment]
@dtarb - this is described by the workflow for creating derived resources in our Google doc. The Google doc specifies a "Derive Copy" button of some sort. I suggested in the comments using the term "isDerivedFrom" to capture the relationship between the source resource and the newer copy.

**Comment by hyi** [comment]
@horsburgh @dtarb I only see section 3.5 with a very brief (5 bullets) description for creating a derived resource for a published resource in google doc here: https://docs.google.com/document/d/1ixma0MlIiUjEEQ807kKLM9PfcMlqN7Yqv2AK1HEHlP4/edit. Is there another document I can reference for resource copy implementation? A specific question to clarify: Is the criterion for a user to be able to copy a resource is that the user has at least view permission to the resource and the resource is shareable? I believe if a resource is public, it must be shareable, right? So the condition for checking whether a resource can be copied could be ```resource is shareable and user has privilege of view or above over the resource```. I will use "isDerivedFrom" relation metadata element for the copied resource.

**Comment by dtarb** [comment]
A resource that is public is not necessarily shareable.  I think we should consider two options.
1. A user can copy any resource they can see.  This is the simplest and least restrictive.  It is de facto possible anyway because a user can always download the files then upload them again (breaking metadata) so allowing copying is not giving anything more, but it retains metadata better.
2  A user can copy any resource they can see that is shareable.  This overloads/extends the role of the shareable flag to include copy.  There is a logic to this, in that it does not make it easy for copying that an owner has not permitted by making the resource shareable, but we run the risk of disabling copying by mistake where owners have unset sharing and do not realize that this impacts copying.  The owner could always be contacted to ask to set the sharing flag, but that builds additional friction in the system.  Also if the resource is published then the owner can no longer change the sharing flag.  If we go with this option, I think we would also want to enable copying of published resources (regardless of sharing).

Given that option 2 seems to add a number of complexities, I favor option 1.

I agree that the isDerivedFrom relation should be used.

**Comment by hyi** [comment]
@dtarb I favor option 1 as well. So I'll go with option 1 for now.

**Comment by horsburgh** [comment]
@hyi and @dtarb - what is to keep someone from copying a resource, changing the author information, and then re-publishing?

I know there's use cases for copying resources, but I'm not sure we've fully thought this through.

**Comment by hyi** [comment]
@horsburgh Good point. Probably we need some kind of "agreement" language to at least inform users of our policy for copying a resource from others such as keeping original authors of the resource, etc. At a minimum, we have this "isDerivedFrom" source metadata element that is attached to the copied resource, so we could trace these kinds of misuse of copied resources if we need to. For now, I'll just implement it in the way that allows anybody to copy a resource he or she can see with an informational message to inform users of our copy policy. @horsburgh @dtarb I'll need you to come up with a formal policy to display to the users when they try to make a copy of a resource, though. Also let me know if you think I should hold up on implementation of this copy functionality until we spend some more time to think it through.

**Comment by dtarb** [comment]
@hyi @horsburgh lets be efficient and try not hold up implementation by extended debate or complexity or generation of a new policy.  

I recognize that it is almost impossible to protect against unethical copying.  It is possible for a user to download the files and do with them what they like, including re-uploading them into a new resource, losing isDerivedFrom metadata unless they specifically create a relationship.  

Our policy is that we expect users to respect the license agreements that other users set for resources when they share them.  I would prefer not to have to have a new policy on copying, and hope that it is already covered by our terms of use https://www.hydroshare.org/terms-of-use/ that require ethical and legal behavior.  Copying something counter to a license agreement is unethical and illegal so if we find abuse we could act according to our current policy.

When a user asks to make copy of a resource, I suggest a pop up that says: "This resource has been provided with a <name of license>.  In copying this resource you are ethically bound to respect the terms of this license."  If it is a creative commons license (which most will be as that is the default), then provide a link to the creative commons website describing the terms.  If it is one of the creative commons no derivs licenses (CC BY-ND or CC BY-NC-ND), the ND indicating no derivatives, then automated HydroShare copying should be disallowed.  The best implementation of this would be for the copy button to never be enabled for resources with these licenses.  Alternatively, the pop up should point out that the license on this resource does not allow derivative works, so HydroShare will not make a copy.  For all other licenses, allow a copy after a user has clicked Agree to seeing the license terms.  

In making the copy all science metadata properties of the resource are copied (authors, abstract, keywords, resource specific metadata etc).  An isDerivedFrom relationship is created.  System metadata (comments, ratings, owners and access control information) is not copied.  Instead the resource defaults to private (just as any resource creation action), and the user performing the copy becomes the owner.  The user/owner is then responsible for further changes/sharing of the resource.

We also need a help page that explains copying @christinabandaragoda.  This should explain these rules.

**Comment by horsburgh** [comment]
@dtarb - by defining the "rules," you defined the policy. My comment above was simply to address the fact that we should not program a system that allows users to violate licenses specified when other users share resources. I think your ideas above cover it.

I personally like the idea of having a pop up that explains why something can't be copied because it would hopefully serve to increase awareness of these issues within the community of users.

**Comment by hyi** [comment]
I agree with @horsburgh that it has merit to show a pop up that explains why something cannot be copied even though this would involve a bit of more work on my part as opposed to not showing copy button at all if the resource's license does not allow derivation. @dtarb Want to confirm with you again which way you prefer. I have implemented not showing copy button at all if the resource cannot be copied, but if you agree it is better to have a popup that explains why it cannot be copied, I will change the user interface to achieve that, and if so, could you also suggest a language that explains why it cannot be copied in the popup?

**Comment by dtarb** [comment]
I am willing to be practical in the implementation, but for me the ideal solution is to have the copy button greyed out/inactive when a user is not allowed to make a copy, with a hover over that explains that "The license for this resource does not permit copying."  This gets the message across, while at the same time not giving them a button followed by "You can not copy because the license for this resource does not permit copying."  Having a button that is active that results in a warning/error is not something I like.  This is probably more work than the solution you had in mind, but you did ask.

**Comment by hyi** [comment]
@dtarb OK, have implemented it in the way you describe above with a minor tweak: instead of show the hover over tooltip ```The license for this resource does not permit copying```, it shows the tooltip as ```You cannot copy because the license for this resource does not permit copying```.

**Comment by dtarb** [comment]
Super.  Thanks.

**Comment by hyi** [comment]
@dtarb @horsburgh I have deployed this to playground for your testing. Please test resource copy functionality on playground and let me know any changes you want to make. I will finish adding unit tests and create a PR tomorrow.

**Comment by horsburgh** [comment]
@hyi - I tested on playground. It mostly looks OK. I made a copy of a resource. That worked fine. The "Source" element gets set correctly to point at the resource that the copy was derived from. I then changed the license to the "no derivitives" license, and I cannot make a copy. When I hover over the copy button, I get the correct message. This all looks good.

My only complaint is that when I can't make a copy, the copy button looks just like it did when it was active. It just doesn't do anything when I click on it.  And, if I don't hover over it just right or for the right amount of time, I don't get the hover text. So, can we have a gray version of the same icon that is displayed when copying is not an option to indicate that it is disabled?

**Comment by hyi** [comment]
@horsburgh Have updated playground to make the copy icon look grayed out when copy action is not allowed. Can you test on playground again to see if it looks good now?

**Comment by dtarb** [comment]
If I am the owner of a resource that has a ND license, I should still be able to copy it.  

I would prefer to soften the language that appears when a resource is copied to:
"Your new copy of the resource has been created. A Derived From Source metadata element has been added to this resource in the Related Resources tab below that links to the original resource. Please respect the terms of the license of the original resource and recognize the original authors as authors or contributors as appropriate in this derived resource. Note that this new copy is created as a private resource by default. If you want the new resource to be discoverable, you need to make it public or discoverable or publish it. "

The rationale may be that the changes may be sufficiently big that it is no longer appropriate or needed to retain the original author.  One use case is that I share a resource that is a DEM for a watershed.  I list myself as the author and indicate it was derived from the national elevation dataset.  I then share this with students in my class and ask them to delineate the watershed.  They make a copy then open the resource with CyberGIS that results in a large number of watershed delineation files in the resource.  I am not an author of any of these files, rather I just contributed the original DEM and they did the delineation work.  The best practice would be for them to leave me as a contributor and to enter their own names as authors.

**Comment by hyi** [comment]
@dtarb @horsburgh Playground has been updated with latest code changes that addressed all your testing comments. Feel free to take a look and let me know if you have any further comments to be addressed.

**Comment by dtarb** [comment]
Testing today on candidate release 1.9.4 beta this looks to be all satisfactory, so closing.
