### ISSUE TITLE
Script file extensions should not be limited to .r .py and .m only

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#1030]
The create resource page indicates that for a script resource only files with extensions .r, .py and .m files are allowed.  I think we should allow other scripts, e.g. .sh, .bat.  In fact, for this resource I question whether we should rely on extension typing as scripts do often not follow consistent extension naming conventions.

**Comment by mjstealey** [comment]
@shawncrawley Is this still relevant?

**Comment by danames** [comment]
This is still relevant. @shawncrawley please remove the restriction on script resource file extensions. We should allow any text file to be uploaded as a script. The extensions will only matter when a specific app is trying to open the script - so type checking can happen on the app.

**Comment by Castronova** [comment]
No longer relevant
