### ISSUE TITLE
File metadata for resources

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#1034]
See #965 for beginning of these discussions. @ironfroggy @selimnairb 

On 3/7 in the face to face meeting, we covered the issue of how apps can bind to and do things with specific files from a resource. We evaluated several possible options and settled upon a "metadata harvesting" option for each file in a resource, separately. In this option, at the time a file is uploaded, the **validator** for the resource harvests metadata on the file, including
- its MIME type
- its FILE type as determined by its magic number. 
- as applicable, embedded metadata about its contents. 
  - variable names in GeoTiff
  - variable names in NetCDF 
  - time series metadata in WaterML2
  - whether database resources in SQLite conform to common schemas, 
    including ODM1.1 and ODM2. 

This metadata is then made part of resource metadata and is made available to apps, which can then act on this type information. 

The whole solution contains two parts, one for the app side and one for the "app resource" side. 
- In the app resource, there is a representation of what file types are expected for the app. This allows the HydroShare resource landing page to put up a list of apps that can process the resource. At the beginning, this will be a list of type information and qualifications, treated as logical "or". Geotiff.inundation might mean a Geotiff type file containing an inundation map, etc. 
- In the app itself, metadata describes the attributes of each file. The app can then choose which files to process. 

This mechanism has several strengths: 
1. it occurs as part of resource validation, so there is a natural place for it in resource upload. 
2. it doesn't require human categorization of files; they are categorized according to their content. There is thus no extra user work in this categorization; just extra programming. 

This fits into the resource type hierarchy in an easily explainable way: the resource type describes the intent of the resource, i;e., why data was collected. This metadata instead enables visualization of specific files in the resource. An app might use both in determining the best visualization.

**Comment by alvacouch** [comment]
The app resource needs at least a list of tuples (Resource Type, MIME type, variable name) to inform the resource landing page that the app handles files with this metadata. This is used in hs_core to construct the resource landing page with buttons for the appropriate apps.

**Comment by ironfroggy** [comment]
Proposed Roadmap:

- [ ] Refactor existing resource creation validation into utilities separate from the models
- [ ] Registry utility to configure dependencies for validators and run on a resource
- [ ] Celery tasks based execution of validation
- [ ] Identification from applications of validators that would be valuable
- [ ] Implementation of deeper content validators
- [ ] Documentation and API exposure of resource validation results
- [ ] Expansion of application configuration with validators
- [ ] Expansion of application APIs to target individual resource files or file sets
- [ ] Implementation of Application launch UI that is informed by validators including inner-file binding.

**Comment by hyi** [comment]
@pkdash I am putting this on your plate iniitally since it is related to file type work you have been doing.

**Comment by pkdash** [comment]
@alvacouch If you have made any progress in implementing a prototype for raster resource type, let me know. I may have time to implement it.

**Comment by pkdash** [comment]
@dtarb Is there any requirement type document for implementing file type metadata?

**Comment by dtarb** [comment]
@gantian127 developed a design powerpoint in www.hydroshare.org/resource/e8cd813e376347c5b617deb321227a36 that I commented on.  I do not think this was ever put into a design doc, but @gantian127 could confirm if it was.  I also listed suggestions in #1126.  These were in the context of a composite resource as a separate resource type.  Based on comments in that issue, rather than establishing a separate composite resource type I am happy with the approach to have types be associated with logical files in a generic resource to meet the same functionality.

**Comment by gantian127** [comment]
@pkdash @dtarb There isn't a specific design doc currently. The resource listed above contains the recent discussion of the file type metadata design.

**Comment by pkdash** [comment]
As it relates to having folders in a resource in particular in generic resource, we need more information on the folder management (CRUD operations) by the user. Here are my assumptions:

- There is a logical file grouping at least for some file types which needs to be preserved during folder and file operations by the user.
- The logical file group to be presented as a folder to the user. System to generate a default folder for the logical file which the user can change later.
- A logical file group (folder) can't contain another logical file group (another folder). Though normal folder nesting is allowed.
- Each logical file type will determine the allowed physical file types.

**Comment by pkdash** [comment]
As it relates to resource level metadata and file type metadata for a generic resource,  here are my assumptions:

- For supported file types, the 'format' core metadata element will be part of the file metadata
- For unsupported file types, the 'format' core element will be part of the resource metadata
- The 'coverage' core element will remain as part of the resource level metadata and the coverage data needs to be computed from the known file types within the resource.
- In the case of ODM2 SQLite file (file type) currently in timeseries resource as part of the metadata extraction we extract metadata for core metadata elements such as 'title', 'abstract' and 'keywords'. However, timeseries as a supported file type in a generic resource, we should not be  generating  'title', 'abstract' and 'keywords' from the extracted metadata.

**Comment by pkdash** [comment]
As it relates to existing generic resources that contain supported file types, I assume we don't have to worry about migrating those to make them enhanced generic resource type.

**Comment by dtarb** [comment]
Some documents and slides related to this issue have been posted by @gantian127 in [Google Drive](https://drive.google.com/folderview?id=0B0l1a655y5oTbGd3bVFfak5IWDQ&usp=sharing).

Addressing @pkdash questions above I agree with not migrating supported file types in existing resources.  Rather I suggest we add a button next to each logical file (a logical file may be a folder in case of multiple files such as shapefiles and vrt grids) that says "File Type" that allows a user to set the file type.  Changing this should trigger harvesting and enabling editing of File type specific metadata.

I think that elements such as title, abstract and keywords that are harvested from time series and multidimensional files should be saved at the resource metadata level for the first file added to the resource upon resource creation when these fields are empty, however if there is already content for these fields, they should be saved as extended metadata associated with that file.

**Comment by horsburgh** [comment]
First, given the use case described in Tian's slides - we need to be **sure** that the answer to this use case is **not** to use our existing functionality to just create two resources, one for the watershed DEM and one for the Snow Water Equivalent data and then group them together using a collection resource. This functionality exists and can support the use case as stated.

If we decide to go down this road, here are some thoughts on the suggested approach:

* We need to be clear about what is resource-level metadata and what is file-level metadata. HydroShare's resource data model allows for both.  The resource data model says this:

> Each content file within a resource may be separately described by a “science” metadata document that is considered to be part of the resource content (i.e., content level metadata). Relationships between content-level metadata documents and the content file(s) (e.g., data) that they describe will be stored in the Resource Map (as described below). HydroShare will not limit the content or format of content-level metadata files.

So, the resource should always have a science metadata document that describes the resource as a whole (as we have now). This is required for the way our system works now and for compatibility with other systems like DataONE. 

Then, each content file or set of content files within a resource may have a separate science metadata document that should be considered part of the content of the resource.  The resource map document should store the fact that these file-level metadata documents exist and the relationships between file-level metadata documents and the content files they describe.

I suggest the following:

* Format information for specific files or groups of files should be stored in a file-level metadata document and not in the resource-level metadata document.
* HydroShare functionality should traverse the resource map to learn that file-level metadata exist (or not) and which files are described by which file level metadata. 
* File-based operations should only be allowed for files that have file-level metadata. This probably means that if we want file operations on our existing resource types, we should add file-level metadata to them so they can be operated on.
* For generic resources, do not try to extract resource-level metadata (title, abstract, keywords) from uploaded files. Instead, where appropriate, extract file-level metadata from individual files. 
* I would not get rid of individual resource types and replace them with one generic resource type. I think it would require a huge amount of work to move all of the logic and validation we already have done for individual resources to conditional validation on one massive generic resource type.

Some unsolved complexities:

* For a generic resource, how will HydroShare know whether the user wants to store file-level metadata or not (e.g., how will HydroShare know whether to do automated metadata extraction).
* How would we reconcile file-level metadata automatically created by HydroShare with file-level metadata uploaded by a user (e.g., what if the user gives us a PDF document containing file-level metadata?)
* How is HydroShare going to distinguish "logical files" - for example, if a user uploads a group of files, how does HydroShare know that they are a logical group that should be described by a file-level metadata document? Only if the user puts the files in a folder? What if they put a file in a folder that is not part of a "logical file"?
* Will the file browser on the resource landing page allow or prevent moving files from one folder (i.e., assuming a folder contains a logical file group) to another?

**Comment by alvacouch** [comment]
I am looking at this as an enhancement to all resources, not just generic ones (though the generic ones will benefit the most).

**Comment by alvacouch** [comment]
I think it is easy to decide what is science metadata and what is file metadata. The file metadata is mainly to benefit apps that need to interact at the file level. It is OK to have duplication between science metadata and app metadata. They serve different use cases.

**Comment by alvacouch** [comment]
I've discussed this problem in detail with @dtarb while he is here at CUAHSI. I have a proposed architecture for the file metadata. I need to check some things out via prototyping to ensure that the design is practical. The design allows us to pull code out of the one-file resources to feed the file metadata for multi-file resources. It relies upon generic relations in Django; file metadata has a foreign key to BaseResource. The actual syntax needs to be tested. Will try to validate the approach tomorrow. Then I can describe it to everyone. Too early for fruitful discussion; there are a small number of syntactic details to work out.

**Comment by alvacouch** [comment]
@pkdash I have started a branch 1034-file-metadata. In this branch, you might want to check out hs_app_netCDF/models.py for my basic approach to reusing single-file resource metadata code. I convert the metadata class methods to a mixin, and mix that mixin into both a Resource Metadata class and a File Metadata class. Comments welcome.

**Comment by alvacouch** [comment]
@pkdash @dtarb In creating AbstractFileMetaData, I find I have an implicit decision to make. The class CoreMetaData generates XML to library standards, with RDF tuple instantiation and references. 

I think -- but need some assurance -- that this is not what I want to do for file metadata. I think the generated XML and JSON should be as simple as possible. Do you agree?

**Comment by pkdash** [comment]
@alvacouch The mixin approach looks good. I assume this won't create any migration issues for existing NetCDF resources.

**Comment by alvacouch** [comment]
I’m staying away from any code motion that moves data around. Moving methods around shouldn’t cause migrations.
.

**Comment by pkdash** [comment]
> I think -- but need some assurance -- that this is not what I want to do for file metadata. I think the generated XML and JSON should be as simple as possible. Do you agree? 

@alvacouch I am not sure on this. Probably this is a question for @horsburgh . If the purpose of having file metadata is to meet the need for HydrpShare apps only then I would prefer JSON over XML. for file metadata.

**Comment by dtarb** [comment]
Is it possible to give an example of what the metadata would look like.  It is hard to venture an opinion based on just this discussion.  Also, while I recognize the efficiency of JSON, I worry that having some metadata XML and other JSON may be confusing.

**Comment by pkdash** [comment]
@alvacouch Should this be closed as we now have individual issues for various file types?

**Comment by pkdash** [comment]
@alvacouch Is this issue still relevant? If not it would be good to close.

**Comment by alvacouch** [comment]
@cuahsimarko This is in essence an obsolete issue, as the whole mechanism discussed herein has been **replaced** with the CompositeResource mechanism for file metadata.
