### ISSUE TITLE
Improve Logging Handling

### ISSUE THREAD

**Issue by ironfroggy** [hydroshare/hydroshare#1037]
Going to use a Papertrailapp trial account to archive week's worth of logs from all services and machines to an easy to use web-based log analyzer. Can filter, search, and configure alerts based on logs. Will evaluate value in the future to expand to a paid account.

**Comment by hyi** [comment]
@jbradberry Assigning this to you for initial investigation to evaluate what the next action should be. YOu can consult @ironfroggy for details. Looping in @mjstealey and @dtarb as well since they were involved in the discussion that triggered this issue during March all hands meeting.

**Comment by mjstealey** [comment]
no longer relevant
