### ISSUE TITLE
Update help template to display Mezzanine content

### ISSUE THREAD

**Issue by selimnairb** [hydroshare/hydroshare#1038]
Current help template (hs_core/templates/pages/help.html) does not read content from Mezzanine.  This needs to be updated to allow display of help content from one or more Mezzanine help pages.

**Comment by hyi** [comment]
@mjstealey I am assigning this to you for initial investigation to see what the next action should be for this.

**Comment by pkdash** [comment]
@mjstealey Is this issue any more relevant as we now have pages.hydroshare.org? If not close it.

**Comment by mjstealey** [comment]
closing due to pages that is now used for this
