### ISSUE TITLE
Learn how to create "my first tethys app"

### ISSUE THREAD

**Issue by danames** [hydroshare/hydroshare#1039]
Download the 7GB image and install it in Virtual Box before Wednesday.

email Dan Ames for the FTP credentials.

**Comment by mohamedmorsy** [comment]
@danames Could you please provide the link to download the VM?

**Comment by danames** [comment]
I just emailed it to you (rather than posting the password on github...)

**Comment by pkdash** [comment]
@danames Should this be closed?

**Comment by danames** [comment]
Yes
