### ISSUE TITLE
Resource landing page warning about identity information

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#1043]
Resource landing pages show the following warning about HydroShare not providing identity information when accessed using the Firefox browser on Windows.

![capture](https://cloud.githubusercontent.com/assets/3456833/13649490/3233b6ca-e5fb-11e5-8c40-dcfefd374f2e.JPG)

This is cosmetic at this stage.

**Comment by horsburgh** [comment]
I don't think this is an appearance issue.  It's likely something to do with the security certificate and providing content over HTTPS. It may also be because there is content on the page that is referenced via HTTP.

I don't see this behavior in Firefox, Chrome, or Safari on my Mac.

**Comment by mjstealey** [comment]
> I don't see this behavior in Firefox, Chrome, or Safari on my Mac

This will be a browser dependent warning based on how your system is setup.

The warning refers to some element in the page referring to an external http source which is in turn being displayed within our https framework. This could be a map, an image, and external link, anything that makes reference to the web via http.

The "fix" is to only allow external references to land on https endpoints, but this may not be realistic as not everything in the world that we wish to refer to is https...

**Comment by dtarb** [comment]
I was hesitant to raise this as it is cosmetic.  I don't want these issues to suck up a lot of team time.  But I did notice this when we were in the meeting and asked what it was and why we got it and @mauriel133 said to record it as an issue.  @horsburgh If this does not fit the appearance category, then what category does it belong to.  As we incorporate, through reference, elements from other systems we need a strategy that recognizes the implications of these choices on the messages that they generate for users.  This message may raise flags for some users about the safety/security of the site, and that is not a message we want to give to our users.  I see this as part of front end appearance. I do not think my browser settings (Firefox on PC) are that unusual.  It seems like all those who commented on not getting this were on Macs.

**Comment by horsburgh** [comment]
If it is as @mjstealey describes - insecure content being displayed in a secure environment - @mauriel133 may be able to fix it.  I agree about being careful about messages users are getting. I don't know that there's a better label for it at the moment.

**Comment by mauriel133** [comment]
A fix for this has been deployed to www.
