### ISSUE TITLE
Failing download when using Nginx / uWSGI

### ISSUE THREAD

**Issue by mjstealey** [hydroshare/hydroshare#1044]
Under current develop branch the file download handoff between Django and Nginx / uWSGI fails.
This issue is not present when using the included Django development server.

**Comment by selimnairb** [comment]
@mjstealey I assume gunicorn fixes the problem?

**Comment by mjstealey** [comment]
> I assume gunicorn fixes the problem

Yes, the file download handoff appears to be working as expected.
The branch is deployed to https://beta.hydroshare.org for testing.

**Comment by mjstealey** [comment]
fixed with unicorn
