### ISSUE TITLE
All "public" resources are not actually public

### ISSUE THREAD

**Issue by shawncrawley** [hydroshare/hydroshare#1045]
This was discovered when using the REST API. I did the following:

```python
hs = HydroShare()  # any methods now invoked on hs should only return public resource
for resource in hs.getResourceList():
    res_id = resource('resource_id')
    res_size = 0
    for res_file in hs.getResourceFileList(res_id):
        res_size += res_file['size']
```
Though `getResourceList()` should have only returned public resources, `getResourceFileList(res_id)` failed with the error: `Not authorized to perform GET on https://www.hydroshare.org/hsapi/resource/res_id/file_list`. 
I tested these same resources in the "Discover" search, and though they came up in the search (as public resources) when I clicked on them I got a 403 Forbidden error.

Here are the two resources it happened with:
Cedar Creek DEM: https://www.hydroshare.org/resource/2ff97b97fcb14c95a5ee3d2814e5d34e
Test - Logan DEM - www: https://www.hydroshare.org/resource/27c329b95d9646e593b75bd10ab71132

**Comment by pkdash** [comment]
In case of anonymous user, ```getResourceList()``` includes both public and discoverable resources. Resource content file can be accessed for public resources only.

**Comment by shawncrawley** [comment]
Oh interesting... Okay. Good to know. Issue solved.
