### ISSUE TITLE
1.4GB file upload on Alpha failed

### ISSUE THREAD

**Issue by rayi113** [hydroshare/hydroshare#105]
In Release 1.3.0.rc0, tried to upload 1.4GB file (located here on beta: http://beta.hydroshare.org/r/2f49df41c89b401389a023db70563ac4/ ).  Failed with the following error:

IOError at /hsapi/_internal/create-resource/do/
[Errno 2] No such file or directory: '/tmp/hydroshare/5074c7c520a84e6a884ba44a40a4b4ac.zip'
Request Method:	POST
Request URL:	http://alpha.hydroshare.org/hsapi/_internal/create-resource/do/
Django Version:	1.7.1
Exception Type:	IOError
Exception Value:	
[Errno 2] No such file or directory: '/tmp/hydroshare/5074c7c520a84e6a884ba44a40a4b4ac.zip'
Exception Location:	/home/docker/hydroshare/hs_core/hydroshare/hs_bagit.py in create_bag, line 148
Python Executable:	/usr/bin/python
Python Version:	2.7.6
Python Path:	
['/home/docker/hydroshare',
 '/usr/lib/python2.7/dist-packages',
 '/home/docker/hydroshare',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages/PILcompat',
 '/home/docker/hydroshare']
Server time:	Wed, 4 Feb 2015 17:38:40 +0000
Traceback Switch to copy-and-paste view

/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py in get_response
                    response = wrapped_callback(request, *callback_args, **callback_kwargs) ...
▶ Local vars
/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py in _wrapped_view
                return view_func(request, *args, **kwargs) ...
▶ Local vars
/home/docker/hydroshare/hs_core/views/__init__.py in create_resource_new_workflow
            content=res_title ...
▶ Local vars
/home/docker/hydroshare/hs_core/hydroshare/resource.py in create_resource
    hs_bagit.create_bag(resource) ...
▶ Local vars
/home/docker/hydroshare/hs_core/hydroshare/hs_bagit.py in create_bag
        bag=File(open(zf)), ...
▶ Local vars
Request information

GET
No GET data
POST
Variable	Value
csrfmiddlewaretoken	
u'wCj13lN77EyDyHoLuxpDPBTf78iRkfUP'
resource-type	
u'GenericResource'
title	
u'NHD Catchments West test 01'
FILES
Variable	Value
files	
<TemporaryUploadedFile: NHD_Catchments_West.zip (application/x-zip-compressed)>
COOKIES
Variable	Value
__utmz	
'194297597.1423071312.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none)'
__utmt	
'1'
sessionid	
'ulk9p6nfn5cfq23hi47gohh6wzpzfm6r'
csrftoken	
'wCj13lN77EyDyHoLuxpDPBTf78iRkfUP'
__utma	
'194297597.1781018396.1423071312.1423071312.1423071312.1'
__utmb	
'194297597.5.10.1423071312'
__utmc	
'194297597'
META
Variable	Value
HYDROSHARE_POSTGIS_1_ENV_SCHEMA	
'postgres'
POSTGIS_NAME	
'/hydroshare_hydroshare_1/postgis'
wsgi.multiprocess	
False
RUN_MAIN	
'true'
HTTP_REFERER	
'http://alpha.hydroshare.org/hsapi/_internal/create-resource/'
RABBITMQ_1_PORT_5672_TCP_PORT	
'5672'
POSTGIS_1_PORT_5432_TCP_PORT	
'5432'
POSTGIS_DB	
'postgres'
POSTGIS_1_PORT	
'tcp://172.17.1.54:5432'
RABBITMQ_1_PORT_15672_TCP_PROTO	
'tcp'
HYDROSHARE_RABBITMQ_1_PORT_5672_TCP_ADDR	
'172.17.1.58'
POSTGIS_HOST	
'postgis'
REDIS_PORT_6379_TCP_ADDR	
'172.17.1.56'
HOME	
'/root'
POSTGIS_1_PORT_5432_TCP_ADDR	
'172.17.1.54'
HYDROSHARE_RABBITMQ_1_PORT_15672_TCP_ADDR	
'172.17.1.58'
HYDROSHARE_RABBITMQ_1_PORT_15672_TCP_PROTO	
'tcp'
RABBITMQ_PORT_15672_TCP_PROTO	
'tcp'
RABBITMQ_PORT_15672_TCP_ADDR	
'172.17.1.58'
POSTGIS_ENV_PASSWORD	
'postgres'
HYDROSHARE_REDIS_1_PORT_6379_TCP_PORT	
'6379'
RABBITMQ_PORT_15672_TCP_PORT	
'15672'
POSTGIS_USER	
'postgres'
HYDROSHARE_POSTGIS_1_PORT	
'tcp://172.17.1.54:5432'
SERVER_PORT	
'8000'
RABBITMQ_PORT_5672_TCP_PROTO	
'tcp'
SERVER_PROTOCOL	
'HTTP/1.1'
RABBITMQ_PORT	
'tcp://172.17.1.58:5672'
HYDROSHARE_REDIS_1_PORT_6379_TCP	
'tcp://172.17.1.56:6379'
POSTGIS_ENV_SCHEMA	
'postgres'
POSTGIS_PORT_5432_TCP	
'tcp://172.17.1.54:5432'
RABBITMQ_1_PORT_15672_TCP_PORT	
'15672'
POSTGIS_ENV_USER	
'postgres'
REDIS_PORT_6379_TCP	
'tcp://172.17.1.56:6379'
HYDROSHARE_RABBITMQ_1_PORT_5672_TCP_PORT	
'5672'
PYTHONPATH	
'/home/docker/hydroshare'
POSTGIS_1_PORT_5432_TCP	
'tcp://172.17.1.54:5432'
HTTP_CACHE_CONTROL	
'max-age=0'
RABBITMQ_1_NAME	
'/hydroshare_hydroshare_1/rabbitmq_1'
HTTP_HOST	
'alpha.hydroshare.org'
POSTGIS_1_ENV_SCHEMA	
'postgres'
REDIS_PORT	
'6379'
POSTGIS_PORT_5432_TCP_ADDR	
'172.17.1.54'
HYDROSHARE_POSTGIS_1_PORT_5432_TCP_ADDR	
'172.17.1.54'
HYDROSHARE_RABBITMQ_1_PORT	
'tcp://172.17.1.58:5672'
wsgi.version	
(1, 0)
SERVER_NAME	
'28cdf6e7eb68'
wsgi.run_once	
False
POSTGIS_PORT_5432_TCP_PROTO	
'tcp'
wsgi.errors	
<open file '<stderr>', mode 'w' at 0x7f28bec1a1e0>
RABBITMQ_1_PORT_15672_TCP	
'tcp://172.17.1.58:15672'
HTTP_ACCEPT_LANGUAGE	
'en-US,en;q=0.8'
PGPASSWORD	
'postgres'
POSTGIS_ENV_POSTGIS	
'false'
HYDROSHARE_RABBITMQ_1_PORT_5672_TCP	
'tcp://172.17.1.58:5672'
REQUEST_METHOD	
'POST'
POSTGIS_1_ENV_POSTGIS	
'false'
HYDROSHARE_RABBITMQ_1_PORT_15672_TCP_PORT	
'15672'
REDIS_PORT_6379_TCP_PROTO	
'tcp'
REDIS_1_PORT	
'tcp://172.17.1.56:6379'
PATH_INFO	
u'/hsapi/_internal/create-resource/do/'
HYDROSHARE_RABBITMQ_1_NAME	
'/hydroshare_hydroshare_1/hydroshare_rabbitmq_1'
HOSTNAME	
'28cdf6e7eb68'
HTTP_ORIGIN	
'http://alpha.hydroshare.org'
HTTP_COOKIE	
'__utmt=1; sessionid=ulk9p6nfn5cfq23hi47gohh6wzpzfm6r; csrftoken=wCj13lN77EyDyHoLuxpDPBTf78iRkfUP; __utma=194297597.1781018396.1423071312.1423071312.1423071312.1; __utmb=194297597.5.10.1423071312; __utmc=194297597; __utmz=194297597.1423071312.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none)'
REDIS_1_PORT_6379_TCP_PORT	
'6379'
HTTP_ACCEPT	
'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8'
RABBITMQ_1_PORT_15672_TCP_ADDR	
'172.17.1.58'
REDIS_1_PORT_6379_TCP_ADDR	
'172.17.1.56'
POSTGIS_PORT	
'5432'
HYDROSHARE_REDIS_1_PORT_6379_TCP_ADDR	
'172.17.1.56'
HYDROSHARE_POSTGIS_1_ENV_PASSWORD	
'postgres'
HYDROSHARE_POSTGIS_1_NAME	
'/hydroshare_hydroshare_1/hydroshare_postgis_1'
QUERY_STRING	
''
PATH	
'/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
RABBITMQ_PORT_5672_TCP	
'tcp://172.17.1.58:5672'
REDIS_1_PORT_6379_TCP	
'tcp://172.17.1.56:6379'
REMOTE_ADDR	
'152.54.9.147'
SERVER_SOFTWARE	
'WSGIServer/0.1 Python/2.7.6'
RABBITMQ_1_PORT_5672_TCP	
'tcp://172.17.1.58:5672'
HYDROSHARE_RABBITMQ_1_PORT_5672_TCP_PROTO	
'tcp'
RABBITMQ_PORT_5672_TCP_ADDR	
'172.17.1.58'
HYDROSHARE_POSTGIS_1_ENV_POSTGIS	
'false'
RABBITMQ_1_PORT_5672_TCP_PROTO	
'tcp'
HYDROSHARE_POSTGIS_1_PORT_5432_TCP_PROTO	
'tcp'
POSTGIS_1_NAME	
'/hydroshare_hydroshare_1/postgis_1'
SHLVL	
'1'
RABBITMQ_1_PORT	
'tcp://172.17.1.58:5672'
wsgi.url_scheme	
'http'
POSTGIS_PORT_5432_TCP_PORT	
'5432'
POSTGIS_1_PORT_5432_TCP_PROTO	
'tcp'
CONTENT_LENGTH	
'1476748660'
RABBITMQ_1_PORT_5672_TCP_ADDR	
'172.17.1.58'
RABBITMQ_PORT_5672_TCP_PORT	
'5672'
HYDROSHARE_REDIS_1_PORT	
'tcp://172.17.1.56:6379'
POSTGIS_1_ENV_PASSWORD	
'postgres'
HYDROSHARE_REDIS_1_PORT_6379_TCP_PROTO	
'tcp'
POSTGIS_PASSWORD	
'postgres'
HYDROSHARE_RABBITMQ_1_PORT_15672_TCP	
'tcp://172.17.1.58:15672'
RABBITMQ_NAME	
'/hydroshare_hydroshare_1/rabbitmq'
HTTP_CONNECTION	
'keep-alive'
REDIS_NAME	
'/hydroshare_hydroshare_1/redis'
REDIS_HOST	
'redis'
wsgi.input	
<socket._fileobject object at 0x7f2897ae72d0>
HTTP_USER_AGENT	
'Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.91 Safari/537.36'
wsgi.multithread	
True
TZ	
'Etc/UTC'
HYDROSHARE_POSTGIS_1_PORT_5432_TCP_PORT	
'5432'
REDIS_1_PORT_6379_TCP_PROTO	
'tcp'
_	
'/usr/bin/python'
HYDROSHARE_REDIS_1_NAME	
'/hydroshare_hydroshare_1/hydroshare_redis_1'
REDIS_PORT_6379_TCP_PORT	
'6379'
REDIS_1_NAME	
'/hydroshare_hydroshare_1/redis_1'
GATEWAY_INTERFACE	
'CGI/1.1'
CSRF_COOKIE	
u'wCj13lN77EyDyHoLuxpDPBTf78iRkfUP'
SCRIPT_NAME	
u''
POSTGIS_1_ENV_USER	
'postgres'
HYDROSHARE_POSTGIS_1_PORT_5432_TCP	
'tcp://172.17.1.54:5432'
PWD	
'/home/docker/hydroshare'
DJANGO_SETTINGS_MODULE	
'hydroshare.settings'
RABBITMQ_PORT_15672_TCP	
'tcp://172.17.1.58:15672'
CONTENT_TYPE	
'multipart/form-data; boundary=----WebKitFormBoundarylu9Is00me0MI6vwg'
HYDROSHARE_POSTGIS_1_ENV_USER	
'postgres'
wsgi.file_wrapper	
''
REMOTE_HOST	
''
HTTP_ACCEPT_ENCODING	
'gzip, deflate'
Settings
Using settings module hydroshare.settings
Setting	Value
TESTING	
False
DEV_SERVER	
True
POSTGIS_VERSION	
(2, 1, 1)
TIME_ZONE	
'Etc/UTC'
IRODS_ROOT	
'/tmp'
CSRF_COOKIE_SECURE	
False
CELERY_DEFAULT_QUEUE	
'default'
LANGUAGE_CODE	
u'en'
ROOT_URLCONF	
u'hydroshare.urls'
MANAGERS	
()
BROKER_URL	
'amqp://guest:guest@172.17.1.58:5672//'
TEST_NON_SERIALIZED_APPS	
[]
DEFAULT_CHARSET	
'utf-8'
CELERY_DEFAULT_EXCHANGE_TYPE	
'topic'
SESSION_SERIALIZER	
'django.contrib.sessions.serializers.JSONSerializer'
STATIC_ROOT	
u'/home/docker/hydroshare/hydroshare/static'
USE_THOUSAND_SEPARATOR	
False
ALLOWED_HOSTS	
'*'
MESSAGE_STORAGE	
u'django.contrib.messages.storage.cookie.CookieStorage'
RABBITMQ_PORT	
'5672'
EMAIL_SUBJECT_PREFIX	
'[Django] '
IPYTHON_SETTINGS	
[]
REDIS_PORT	
6379
RABBITMQ_HOST	
'172.17.1.58'
SESSION_CACHE_ALIAS	
'default'
IPYTHON_HOST	
'127.0.0.1'
SESSION_COOKIE_DOMAIN	
None
SESSION_COOKIE_NAME	
'sessionid'
PACKAGE_NAME_GRAPPELLI	
u'grappelli_safe'
ADMIN_FOR	
()
TIME_INPUT_FORMATS	
('%H:%M:%S', '%H:%M:%S.%f', '%H:%M')
IRODS_ZONE	
'hydroZone'
DATABASES	
{'default': {'ATOMIC_REQUESTS': False,
             'AUTOCOMMIT': True,
             'CONN_MAX_AGE': 0,
             'ENGINE': 'django.contrib.gis.db.backends.postgis',
             'HOST': '172.17.1.54',
             'NAME': 'postgres',
             'OPTIONS': {},
             'PASSWORD': u'********************',
             'PORT': 5432,
             'TEST': {'CHARSET': None,
                      'COLLATION': None,
                      'MIRROR': None,
                      'NAME': None},
             'TIME_ZONE': 'UTC',
             'USER': 'postgres'}}
TEMPLATE_DEBUG	
True
FILE_UPLOAD_DIRECTORY_PERMISSIONS	
None
FILE_UPLOAD_PERMISSIONS	
420
POSTGIS_DB	
'postgres'
FILE_UPLOAD_HANDLERS	
('django.core.files.uploadhandler.MemoryFileUploadHandler',
 'django.core.files.uploadhandler.TemporaryFileUploadHandler')
TEMPLATE_CONTEXT_PROCESSORS	
(u'django.contrib.auth.context_processors.auth',
 u'django.contrib.messages.context_processors.messages',
 u'django.core.context_processors.debug',
 u'django.core.context_processors.i18n',
 u'django.core.context_processors.static',
 u'django.core.context_processors.media',
 u'django.core.context_processors.request',
 u'django.core.context_processors.tz',
 u'mezzanine.conf.context_processors.settings',
 u'mezzanine.pages.context_processors.page')
DEFAULT_CONTENT_TYPE	
'text/html'
IRODS_CWD	
'/hydroZone/home/hsalpha'
CARTO_HOME	
'/home/docker/node_modules/carto'
TEST_RUNNER	
u'django_nose.NoseTestSuiteRunner'
DEFAULT_EXCHANGE	
<unbound Exchange default(topic)>
APPEND_SLASH	
True
FIRST_DAY_OF_WEEK	
0
DATABASE_ROUTERS	
[]
DEFAULT_TABLESPACE	
''
POSTGIS_PASSWORD	
u'********************'
STATICFILES_STORAGE	
'django.contrib.staticfiles.storage.StaticFilesStorage'
CACHES	
{'default': {'BACKEND': 'django.core.cache.backends.locmem.LocMemCache'}}
CELERY_DEFAULT_ROUTING_KEY	
u'********************'
SERVER_EMAIL	
'root@localhost'
SESSION_COOKIE_PATH	
'/'
YEAR_MONTH_FORMAT	
'F Y'
USE_X_FORWARDED_HOST	
False
POSTGIS_PORT	
5432
SILENCED_SYSTEM_CHECKS	
[]
MIDDLEWARE_CLASSES	
(u'django.contrib.sessions.middleware.SessionMiddleware',
 u'django.middleware.locale.LocaleMiddleware',
 u'django.contrib.auth.middleware.AuthenticationMiddleware',
 u'django.middleware.common.CommonMiddleware',
 u'django.middleware.csrf.CsrfViewMiddleware',
 u'django.contrib.messages.middleware.MessageMiddleware',
 u'mezzanine.core.request.CurrentRequestMiddleware',
 u'mezzanine.core.middleware.RedirectFallbackMiddleware',
 u'mezzanine.core.middleware.TemplateForDeviceMiddleware',
 u'mezzanine.core.middleware.TemplateForHostMiddleware',
 u'mezzanine.core.middleware.AdminLoginInterfaceSelectorMiddleware',
 u'mezzanine.core.middleware.SitePermissionMiddleware',
 u'mezzanine.pages.middleware.PageMiddleware',
 u'ga_resources.middleware.PagePermissionsViewableMiddleware',
 u'debug_toolbar.middleware.DebugToolbarMiddleware')
USE_I18N	
False
THOUSAND_SEPARATOR	
','
IRODS_AUTH	
'alphawater1'
LANGUAGE_COOKIE_NAME	
'django_language'
FILE_UPLOAD_TEMP_DIR	
None
TRANSACTIONS_MANAGED	
False
LOGGING_CONFIG	
'logging.config.dictConfig'
INPLACE_SAVE_URL	
u'/hsapi/save_inline/'
CELERY_ROUTES	
('django_docker_processes.router.DockerRouter',)
TEMPLATE_LOADERS	
(u'django.template.loaders.filesystem.Loader',
 u'django.template.loaders.app_directories.Loader')
WSGI_APPLICATION	
None
SETTINGS_MODULE	
'hydroshare.settings'
REDIS_CONNECTION	
Redis<ConnectionPool<Connection<host=172.17.1.56,port=6379,db=4>>>
X_FRAME_OPTIONS	
'SAMEORIGIN'
CSRF_COOKIE_NAME	
'csrftoken'
CELERY_DEFAULT_EXCHANGE	
'tasks'
FORCE_SCRIPT_NAME	
None
IRODS_DEFAULT_RESOURCE	
'hydroResource'
SIGNING_BACKEND	
'django.core.signing.TimestampSigner'
SESSION_COOKIE_SECURE	
False
PROJECT_DIRNAME	
'hydroshare'
USE_SOUTH	
False
REDIS_HOST	
'172.17.1.56'
CSRF_COOKIE_DOMAIN	
None
FILE_CHARSET	
'utf-8'
DEBUG	
True
COMMENTS_APP	
u'mezzanine.generic'
LANGUAGE_COOKIE_DOMAIN	
None
DEFAULT_FILE_STORAGE	
'django.core.files.storage.FileSystemStorage'
INSTALLED_APPS	
(u'mezzanine.boot',
 u'django.contrib.auth',
 u'django.contrib.contenttypes',
 u'django.contrib.redirects',
 u'django.contrib.sessions',
 u'django.contrib.sites',
 u'django.contrib.sitemaps',
 u'django.contrib.gis',
 u'inplaceeditform',
 u'django_nose',
 u'django_irods',
 u'theme',
 u'theme.blog_mods',
 u'mezzanine.conf',
 u'mezzanine.core',
 u'mezzanine.generic',
 u'mezzanine.blog',
 u'mezzanine.forms',
 u'mezzanine.pages',
 u'mezzanine.galleries',
 u'crispy_forms',
 u'mezzanine.accounts',
 u'mezzanine.mobile',
 u'autocomplete_light',
 u'jquery_ui',
 u'tastypie',
 u'ga_ows',
 u'ga_resources',
 u'dublincore',
 u'hs_core',
 u'hs_metrics',
 u'hs_rhessys_inst_resource',
 u'django_docker_processes',
 u'djcelery',
 u'ref_ts',
 u'widget_tweaks',
 u'debug_toolbar',
 u'django_extensions',
 u'filebrowser_safe',
 u'grappelli_safe',
 u'django.contrib.admin',
 u'django.contrib.staticfiles',
 u'django.contrib.comments')
LANGUAGES_BIDI	
('he', 'ar', 'fa', 'ur')
USE_L10N	
False
COMMENTS_ALLOW_PROFANITIES	
False
STATICFILES_DIRS	
()
PREPEND_WWW	
False
SECURE_PROXY_SSL_HEADER	
None
PASSWORD_RESET_TIMEOUT_DAYS	
u'********************'
LANGUAGE_COOKIE_AGE	
None
IPYTHON_BASE	
'/home/docker/hydroshare/static/media/ipython-notebook'
DEBUG_PROPAGATE_EXCEPTIONS	
False
CSRF_COOKIE_AGE	
31449600
MONTH_DAY_FORMAT	
'F j'
LOGIN_URL	
'/accounts/login/'
SESSION_EXPIRE_AT_BROWSER_CLOSE	
True
IRODS_HOST	
'data.hydroshare.org'
TASTYPIE_SWAGGER_API_MODULE	
u'********************'
TIME_FORMAT	
'P'
SITE_TITLE	
'Hydroshare'
POSTGIS_HOST	
'172.17.1.54'
AUTH_USER_MODEL	
'auth.User'
DATE_INPUT_FORMATS	
('%Y-%m-%d',
 '%m/%d/%Y',
 '%m/%d/%y',
 '%b %d %Y',
 '%b %d, %Y',
 '%d %b %Y',
 '%d %b, %Y',
 '%B %d %Y',
 '%B %d, %Y',
 '%d %B %Y',
 '%d %B, %Y')
AUTHENTICATION_BACKENDS	
(u'mezzanine.core.auth_backends.MezzanineBackend',)
EMAIL_HOST_PASSWORD	
u'********************'
IRODS_GLOBAL_SESSION	
True
PACKAGE_NAME_FILEBROWSER	
u'filebrowser_safe'
AUTH_PROFILE_MODULE	
u'theme.UserProfile'
SESSION_FILE_PATH	
None
CACHE_MIDDLEWARE_ALIAS	
'default'
PERMISSIONS_DB	
Redis<ConnectionPool<Connection<host=172.17.1.56,port=6379,db=6>>>
SESSION_SAVE_EVERY_REQUEST	
False
WMS_CACHE_DB	
Redis<ConnectionPool<Connection<host=172.17.1.56,port=6379,db=5>>>
NUMBER_GROUPING	
0
SESSION_ENGINE	
'django.contrib.sessions.backends.db'
CSRF_FAILURE_VIEW	
'django.views.csrf.csrf_failure'
CSRF_COOKIE_PATH	
'/'
GRAPPELLI_INSTALLED	
True
PROJECT_ROOT	
'/home/docker/hydroshare/hydroshare'
DECIMAL_SEPARATOR	
'.'
IGNORABLE_404_URLS	
()
LOCALE_PATHS	
()
TEMPLATE_STRING_IF_INVALID	
''
LOGOUT_URL	
'/accounts/logout/'
EMAIL_USE_TLS	
True
LOGIN_REDIRECT_URL	
'/accounts/profile/'
FIXTURE_DIRS	
()
EMAIL_HOST	
'gator3038.hostgator.com'
DATE_FORMAT	
'N j, Y'
IRODS_USERNAME	
'hsalpha'
OPTIONAL_APPS	
(u'debug_toolbar',
 u'django_extensions',
 u'filebrowser_safe',
 u'grappelli_safe')
MEDIA_ROOT	
u'/home/docker/hydroshare/hydroshare/static/media'
LANGUAGE_COOKIE_PATH	
'/'
DEFAULT_EXCEPTION_REPORTER_FILTER	
'django.views.debug.SafeExceptionReporterFilter'
ADMINS	
()
FORMAT_MODULE_PATH	
None
DEFAULT_FROM_EMAIL	
'hydroshare@hydroshare.org'
MEDIA_URL	
u'/static/media/'
DATETIME_FORMAT	
'N j, Y, P'
TEMPLATE_DIRS	
(u'/home/docker/hydroshare/hydroshare/templates',)
CELERY_ACCEPT_CONTENT	
['pickle', 'json', 'msgpack', 'yaml']
IRODS_ICOMMANDS_PATH	
'/usr/bin'
SITE_ID	
1
DISALLOWED_USER_AGENTS	
()
ALLOWED_INCLUDE_ROOTS	
()
DOCKER_API_VERSION	
u'********************'
LOGGING	
{}
SHORT_DATE_FORMAT	
'm/d/Y'
SECRET_KEY	
u'********************'
STATICFILES_FINDERS	
(u'django.contrib.staticfiles.finders.FileSystemFinder',
 u'django.contrib.staticfiles.finders.AppDirectoriesFinder')
CACHE_MIDDLEWARE_KEY_PREFIX	
u'********************'
IRODS_PORT	
'1247'
FILE_UPLOAD_MAX_MEMORY_SIZE	
0
EMAIL_BACKEND	
'django.core.mail.backends.smtp.EmailBackend'
POSTGIS_USER	
'postgres'
DOCKER_EXCHANGE	
<unbound Exchange docker(direct)>
EMAIL_USE_SSL	
False
DATETIME_INPUT_FORMATS	
('%Y-%m-%d %H:%M:%S',
 '%Y-%m-%d %H:%M:%S.%f',
 '%Y-%m-%d %H:%M',
 '%Y-%m-%d',
 '%m/%d/%Y %H:%M:%S',
 '%m/%d/%Y %H:%M:%S.%f',
 '%m/%d/%Y %H:%M',
 '%m/%d/%Y',
 '%m/%d/%y %H:%M:%S',
 '%m/%d/%y %H:%M:%S.%f',
 '%m/%d/%y %H:%M',
 '%m/%d/%y')
CELERY_QUEUES	
(<unbound Queue default -> <unbound Exchange ''(direct)> -> task.#>,
 <unbound Queue docker_container_tasks -> <unbound Exchange docker(direct)> -> docker.container>,
 <unbound Queue Exchange docker(direct) -> <unbound Exchange docker_broadcast_tasks(fanout)> -> docker.broadcast>)
MIGRATION_MODULES	
{}
SESSION_COOKIE_AGE	
1209600
DOCKER_URL	
'unix://docker.sock/'
NEVERCACHE_KEY	
u'********************'
USE_ETAGS	
False
LANGUAGES	
((u'en', u'English'),)
DEFAULT_INDEX_TABLESPACE	
''
INTERNAL_IPS	
(u'127.0.0.1',)
STATIC_URL	
u'/static/'
USE_IRODS	
True
IRODS_HOME_COLLECTION	
'/hydroZone/home/hsalpha'
EMAIL_PORT	
'26'
USE_TZ	
True
SHORT_DATETIME_FORMAT	
'm/d/Y P'
PASSWORD_HASHERS	
u'********************'
SESSION_COOKIE_HTTPONLY	
True
ABSOLUTE_URL_OVERRIDES	
{}
ADAPTOR_INPLACEEDIT_EDIT	
u'hs_core.models.HSAdaptorEditInline'
SEND_BROKEN_LINK_EMAILS	
False
CACHE_MIDDLEWARE_SECONDS	
600
DEBUG_TOOLBAR_CONFIG	
{u'INTERCEPT_REDIRECTS': False}
CSRF_COOKIE_HTTPONLY	
False
CRISPY_TEMPLATE_PACK	
u'bootstrap'
EMAIL_HOST_USER	
'hydroshare@hydroshare.org'
PROFANITIES_LIST	
u'********************'
You're seeing this error because you have DEBUG = True in your Django settings file. Change that to False, and Django will display a standard 500 page.

**Comment by rayi113** [comment]
Related to #109

**Comment by mjstealey** [comment]
Files of this size do upload, however there is a separate issue with bagit file creation and handling. Closing as this is unrelated to this release.
