### ISSUE TITLE
We should merge "My Resources" and "Discover"

### ISSUE THREAD

**Issue by danames** [hydroshare/hydroshare#1053]
These two pages perform extremely similar functions but behave very differently. We should merge them into a single "Resources" page with a consistent set of filters, search methods etc. 

My Resources could become this single page if there was a check box for "All resources" instead of just "viewable by me" "shared with me" etc. 

However the filtering options seem to be better on "Discover".

Can we merge??

**Comment by horsburgh** [comment]
I vote against this one.  I want a My Resources page and a Discover page.

My Resources = My stuff
Discover = Other people's stuff + a way for unauthenticated users to interact with the system

I want a place where I can manage all of my content separately from everyone else's.  I don't want to have to filter out all of the cruft all of the time to get to to my content.

In my opinion, this would be taking a big step backward to where we were before.

**Comment by danames** [comment]
What do you think about the fact that the filtering/searching methods are quite different on both pages? Is there a way to harmonize them?

**Comment by horsburgh** [comment]
It may be worth a look.  But, they are targeted at different users.  The filters on the My Resources page (including the labels that show up when I create and apply them) are for me to organize and narrow my own content (and I should already have some idea of what I've got), whereas the facets on the discover page include more comprehensive facets to help users (who may not know already what they are looking for) browse through the entire content of the catalog. I'm not sure we need the same facets on both pages.

**Comment by dtarb** [comment]
I think that this is an issue where it is "been there, done that".  The boat has sailed.  We have vacillated on this issue enough.  You may recall endless earlier discussions on this.  I would vote that we truncate discussion on this issue and just get the pages working.   We have hydro value added functionality to serve our use cases to work on rather than this redesign.
