### ISSUE TITLE
Anonymous users cannot open discoverable resource landing page on current dev branch

### ISSUE THREAD

**Issue by zhiyuli** [hydroshare/hydroshare#1055]
I set a res discoverable, but other users or anonymous users cannot open its landing page (got 403). Only owner and admin can open it.
![image](https://cloud.githubusercontent.com/assets/10070599/13762704/68f8350a-ea06-11e5-996a-4552f02cf682.png)

![image](https://cloud.githubusercontent.com/assets/10070599/13762715/77ee4086-ea06-11e5-976a-b6c706ed75d7.png)

**Comment by pkdash** [comment]
@zhiyuli See if this can be closed.

**Comment by zhiyuli** [comment]
closed
