### ISSUE TITLE
On demand update for netCDF resources to feed to Hyrax server

### ISSUE THREAD

**Issue by hyi** [hydroshare/hydroshare#1059]
When a private netCDF resource is made public, my script to expose public netCDF resources from iRODS vault to Hyrax server will be triggered on-demand to run on Hyrax server from HydroShare using ssh-based approach. The cron job to run that script every midnight will still be scheduled on Hyrax server to do clean up as needed in cases when a public netCDF resource is made private or deleted.

**Comment by hyi** [comment]
@gantian127 Now that on-demand update code for netCDF resources to feed to Hyrax server has been included on www in the latest deployment, could you test it and close this issue if it works correctly? Thanks!

**Comment by gantian127** [comment]
@hyi I tested on WWW site. It works when I set a private netcdf resource as a public resource. But when I set the public resource back as a private resource, it seems the OPeNDAP link still works. 
I think after a resource is set as private or discoverable  again, its corresponding OPeNDAP link should not work. Would you please test it and make sure what I tested is correct? Thank you.

**Comment by hyi** [comment]
@gantian127 Yes, it works as expected. As I commented above for this issue, on-demand update is only triggered when a private netCDF resource is made public. The cron job on Hyrax server is still scheduled to run each midnight for clean up to handle the cases when public netCDF resources are made private or public netCDF resources are deleted. Since hyrax service is only available for public netCDF resources, those nightly clean-up should be sufficient. Hyrax service links do not show up for private netCDF resources anyway and on-demand update takes a bit time which I think should only be implemented when it is really needed. Let me know if this makes sense. If you have use cases in mind that requires on-demand update for the cases when private netCDF resources are made public or deleted, I can implement on-demand update for those cases as well; otherwise, I think this issue can be closed. Thanks for testing it out.

**Comment by gantian127** [comment]
@hyi If there is a nightly clean-up, I think current implementation is sufficient. Thanks for your information and work on this function! I will close this issue. If there is a new use case in the future, I think we can create another issue for it. Thank you.
