### ISSUE TITLE
Collection Resource: Collected Resources Should be Stored in Resource Map

### ISSUE THREAD

**Issue by horsburgh** [hydroshare/hydroshare#1063]
Within a collection resource, the pointers to the collected resources should be stored in the resource map document and not in the resource metadata document. The purpose of the resource map document is to store the list objects aggregated within the resource.

**Comment by zhiyuli** [comment]
@horsburgh  are there any existing resource types already using the  "aggregation" term in "resource map" document? I need an example...

**Comment by horsburgh** [comment]
@zhiyuli - see this generic resource for example - https://www.hydroshare.org/resource/bc611bca276f40fd8c7f8a5a704236e0/. Download it and look at the resource map. It has multiple files and I just checked the resource map to make sure it's complete.  The aggregation in the resource map points at all of the files in the resource. 

Basically, for the collection resource, you are doing the same thing except you are not aggregating files within the bag of the resource - you are aggregating resources within HydroShare. So, for each aggregated resource, you wouldn't point at the URL of an individual file, but rather you would point to the URL of a resource.

@pkdash may be able to help you more with this.

**Comment by zhiyuli** [comment]
@horsburgh thanks for giving me an example. 
@pkdash In term of implementing it, I think all hs_core functions that manipulate resource map doc are currently triggered by actions on resource files; all functions that manipulate resource metadata doc are triggered by actions on metadata. 
In the case of collection, since relationship between a collection and its contained resources is stored in metadata, the challenge would be how to bridge between actions on metadata and manipulation on resource map doc by re-using existing hs_core functions. Any suggestions? thanks

**Comment by pkdash** [comment]
@zhiyuli I am not sure I fully understand your question. I am guessing, the create_bag_files(resource) function needs to be modified so that for a collection resource we write the url for the individual resources in the 'resourcemap.xml'

**Comment by pkdash** [comment]
@horsburgh The url that needs to be written to the resourcemap for each of the resources in the collection resource is that url for the resource bag or resource landing page?

**Comment by horsburgh** [comment]
@zhiyuli and @pkdash - Here's what the resource data model document  says about this (https://docs.google.com/document/d/1_XY7J8hXQl-w24FWyuWs7YfRHw68px1ZOB_dQOU7sCQ/edit): 

1. All aggregated objects in the resource map must be expressed as a URI
2. When referencing another HydroShare resource, the URI of the resource being referenced must resolve to a resource map.

The point is that the resource map documents essentially make resources linked data. If I am referencing another resource to make it part of the collection resource, if I point at it's resource map document in the aggregation of the collection resource, I can access the resource map document directly and traverse the contents of the referenced resource all the way out to the individual content files (for all of the collected resources). If you point only at the landing pages, you get stuck there and have no idea what the content of the collected resource is.

The resource map document contains a lot of really useful information for composing collections, including the URI encoded identifier (i.e., the landing page), the resource title, the list of aggregated content files (including the pointer to the science metadata document), etc.

**Comment by zhiyuli** [comment]
@horsburgh 
An example collection:
https://playground.hydroshare.org/resource/c83fa6b047bc411395e5d7f1ec79bf39/
we added the "Download" button back, you could download the bag on the landing page.

**Comment by pkdash** [comment]
@horsburgh See if this issue can be closed.

**Comment by horsburgh** [comment]
I just created a new collection on beta.hydroshare.org and had a look at the resource map.  This one is resolved on beta.
