### ISSUE TITLE
Collection Resource:  How to handle a Collected Resource Deletion

### ISSUE THREAD

**Issue by horsburgh** [hydroshare/hydroshare#1064]
There is a question about what to do when a user who has delete access to a resource that is part of a collection chooses to delete it - when the user does not have edit permission on the collection resource. Options include:

1. We let the user delete the resource that is part of a collection and cascade deletes to the collection resource. Doing this violates our access control rules if the user doing the deleting does not have permission to modify the collection resource.

2. We let the user delete the resource that is part of a collection, but we first give them a warning message that states that if they delete the resource it will break any collections that reference that resource. If they have permission to delete, we let them delete. This leaves a broken link in the collection.

3. We do not let a user delete a resource that is part of a collection. Doing this seems to violate our access control policy because a user's ability to delete a resource can essentially be revoked by another user adding that resource to a collection.

I think we probably need to do number 2. But, I think that we could notify owners of the collection resource when a resource in the collection is deleted by someone that does not have at least edit permissions on the collection resource. That notification could alert them that they need to go in and remove the reference to the resource that has been deleted.

**Comment by horsburgh** [comment]
From @zhiyuli - comment on (2): we are using ManyToMany relationship to associate a collection with its contained resources (rather than storing their res_ids in collection), which is recommend by the developer team. Say, collectionA holds resB, that means collectionA object is referencing resB obj. if resB obj gets removed, the tie between colletionA and resB will be gone automatically...so there is no broken link in collection A at all....

**Comment by horsburgh** [comment]
OK - technically that may be true, but the point is that a user who doesn't have access to the collection shouldn't be able to modify it. And, deleting a resource (and thus removing it from the collection) would modify the collection. @zhiyuli - can you point me at an example collection resource? I would like to look at what's in the bag.

**Comment by horsburgh** [comment]
From @zhiyuli - @horsburgh the only "broken link" is in collectionA's bag, because every we update collectionA, we write the res_ids of all its contained resources into collectionA's bag

**Comment by horsburgh** [comment]
From @zhiyuli - @horsburgh I just realize there is no way to get the bag from the landing page!!! because in the new UI design we took over the whole "Content" block that contains "download" button and replaced it with "Contained resource list" (you suggested it I remembered....
The bag is on irods and it is getting updated as usual....

A public collection res on playground is here
https://playground.hydroshare.org/resource/7cfafdb649f54eb1a39b3c7a0d6cc10e/

I will try to find the url to the bag and let you know....

**Comment by horsburgh** [comment]
From @zhiyuli - @horsburgh 
landing page is here: 
https://playground.hydroshare.org/resource/7cfafdb649f54eb1a39b3c7a0d6cc10e/

bag is here:
https://playground.hydroshare.org/django_irods/download/bags/7cfafdb649f54eb1a39b3c7a0d6cc10e.zip

**Comment by horsburgh** [comment]
@zhiyuli - I'm hoping in this issue we could get some people to weigh in on what to do about the permissions issue related to deletion of a resource in a collection.

FYI - I created a separate issue for the need to store the list of aggregated resources in a collection object within the resource map document. See #1063.

**Comment by zhiyuli** [comment]
a related situation: Public or discoverable collections can only hold public or discoverable resources. Say, public collectionA holds public resB. If the owner of resB downgrades resB to private, in current implementation the system downgrades collectionA to private automatically.

**Comment by horsburgh** [comment]
@zhiyuli - yes, it's really the same issue. Should a user who may not have any permissions at all on a collection resource be able to make a change to a resource within the collection that results in a modification to the collection (in this case changing its sharing status).

**Comment by zhiyuli** [comment]
tested on www
