### ISSUE TITLE
Beta site resource creation page can't show correct file validation information

### ISSUE THREAD

**Issue by gantian127** [hydroshare/hydroshare#1065]
When a specific resource type is selected, the page shows the error info as following:
![image](https://cloud.githubusercontent.com/assets/5016511/13937238/055f5950-ef89-11e5-8c5b-d5b7610a3c39.png)

When a wrong file type is uploaded for a resource type, the page shows the error info which should not show an object but the resource name:
![image](https://cloud.githubusercontent.com/assets/5016511/13937274/4b713512-ef89-11e5-8fd7-aa1cfe7453be.png)

**Comment by mjstealey** [comment]
@gantian127 Is this still relevant?

**Comment by gantian127** [comment]
@mjstealey This has been fixed. I will close it thanks.
