### ISSUE TITLE
Invalid form shows up when the requried account sign up information is not completed

### ISSUE THREAD

**Issue by gantian127** [hydroshare/hydroshare#1066]
@mauriel133 @pkdash I test the sign up process and found out that if I didn't enter all the required account information and click on "Join HydroShare & Start collaborating" button, it will show the following invalid form. (Testing on chrome, firefox and Microsoft Edge  )

The expected response after a user doesn't enter all the information should refresh the page and keep the original sign up form layout. 
![image](https://cloud.githubusercontent.com/assets/5016511/13993873/cee12222-f0e7-11e5-9613-ecdb086ffe91.png)

**Comment by dtarb** [comment]
OK.
