### ISSUE TITLE
Resource list table needs to be set with a fixed table height

### ISSUE THREAD

**Issue by gantian127** [hydroshare/hydroshare#1068]
On WWW site, the resource list table shows all the resources on one page. This will be a long table list when there are many resources. It would be better to set a fixed table height and show a fixed number of resources on one page.

![image](https://cloud.githubusercontent.com/assets/5016511/14003832/31e9d34a-f11b-11e5-93a1-badc73c26ea8.png)

**Comment by horsburgh** [comment]
@gantian127 - I'm assuming this is on the My Resources page. We had tried a fixed height table that started scrolling when the list got long.  But, Dave didn't like the fact that this added an additional scroll bar to the page - you could scroll the page and the list of resource.  So, we reverted it back to just show the full list.

I was just on another website today where I had to click through 4 pages of resources and it was driving me nuts trying to find anything. I'm definitely not satisfied with paging as a solution for this.  For now, I think we should leave it as is, but as lists start getting longer and if it starts to be a problem, I would vote for trying some sort of infinite scrolling solution for the page. But, the filters are there to help users narrow the list if it becomes unmanageable.

**Comment by gantian127** [comment]
@horsburgh If it has been decided to keep all the resources in one page as a long list. I will just close it. Thanks.
