### ISSUE TITLE
Dialogue says my resource is ready to be made 'Public and Discoverable' when it isn't

### ISSUE THREAD

**Issue by jsadler2** [hydroshare/hydroshare#1073]
The dialogue said that my resource was ready to be made discoverable and public after I added an abstract and key words but when I tried to make it public it said I needed to upload a content file. The logic should check to make sure the required files are satisfied not just the required metadata elements.

**Comment by pkdash** [comment]
@jsadler2 What resource type you used?

**Comment by jsadler2** [comment]
Model Instance

**Comment by jsadler2** [comment]
@pkdash  I just tried with a raster resource and it behaved the same

**Comment by pkdash** [comment]
@jsadler2 I think the message can be made bit clearer. But I think it says the right thing. When you complete all metadata the message says "Metadata status: "Sufficient to make publish or public". Which means metadata requirement has been met. It does not say all requirements have been met to make the resource publish or public.

**Comment by hyi** [comment]
@pkdash I am assigning to you initially to determine the next action, whether to make changes to make the message a bit more clear, or justify that it works reasonably well and can be closed.

**Comment by pkdash** [comment]
@horsburgh and @dtarb Any suggestion how to make this message more clear?

**Comment by horsburgh** [comment]
I think the existing message is fine. The issue where you try to make it public before having content files is handled well. But, you could reword the text in question as follows:

> "**Metadata status**: sufficient to make public or to publish your resource. If you haven't already, you may still need to add content files before making your resource public or publishing it."

**Comment by dtarb** [comment]
"may still need to add content files" seems insufficiently specific.  Either they do need to add files or they do not.  There is no "may".  So if they "do" need to add files can we just say: "Content files need to be added to this resource before it can be made public, discoverable or published." and if they do not need to add files then just say "The content and metadata of this resource is sufficient for it to be made public, discoverable or published."

**Comment by mauriel133** [comment]
@pkdash, the main ajax used to submit most of the metadata elements is the one that returns the flag variable used to display this message. Can you add a check for content files to this flag?

See https://github.com/hydroshare/hydroshare/blob/develop/theme/static/js/resourceLandingAjax.js#L334

**Comment by pkdash** [comment]
@mauriel133 Will do.

**Comment by mauriel133** [comment]
@pkdash, has this check been implemented?

**Comment by pkdash** [comment]
@mauriel133 Not yet.

**Comment by dtarb** [comment]
Seems OK.  @jsadler2 feel free to re-open if it does not satisfy you.
