### ISSUE TITLE
Required content files should be at same level in req'd element dialogue

### ISSUE THREAD

**Issue by jsadler2** [hydroshare/hydroshare#1074]
Related to #1073 
For clarity, the "Content files are required..." statement at the bottom should be one of the bullet points and the "Now that yoru resource has been created..." should have more generic language than "metadata" but maybe just say "...the following elements are required..." 
![reqd_elements](https://cloud.githubusercontent.com/assets/6943441/14025996/168be208-f1c7-11e5-8934-6f92a1de25aa.PNG)

**Comment by hyi** [comment]
@pkdash I am assigning to you for initial investigation. Feel free to reassign as needed.

**Comment by pkdash** [comment]
@horsburgh and @dtarb Do you agree for this change suggested by @jsadler2 ?

**Comment by horsburgh** [comment]
I think this is a pretty minor thing and the text is pretty clear as is.  But, maybe the following would be better:

> **Congratulations!** Now that your resource has been created, the following metadata elements are required to make it public or discoverable:
> * Abstract
> * Keywords

> You must also add content files to your resource before you can publish your resource or make it public or discoverable.

**Comment by mauriel133** [comment]
The text has now been adjusted according to the suggestions above.

**Comment by horsburgh** [comment]
I think this is OK. Closing.
