### ISSUE TITLE
'Manage access' icon more available

### ISSUE THREAD

**Issue by jsadler2** [hydroshare/hydroshare#1075]
Since this is Hydro _Share_ can we make the manage access button a  _sharing_ button and make it more visible like putting up with the other icons at the top of the page? something like this?
![share](https://cloud.githubusercontent.com/assets/6943441/14026193/19b8c152-f1c8-11e5-8d7b-6cc2e32f660b.png)

**Comment by horsburgh** [comment]
This makes sense - and consolidates actions for resources in one place on the page.

**Comment by mauriel133** [comment]
I agree. This should be an easy change too. I'm assuming we are moving it and not just adding this as an extra one.

**Comment by horsburgh** [comment]
Yes - move. There should be only one button.

**Comment by jsadler2** [comment]
Right. that's what i had in mind.

**Comment by hyi** [comment]
This has been resolved. Closing.
