### ISSUE TITLE
Should say what is req'd for public/discoverable in "Edit" mode

### ISSUE THREAD

**Issue by jsadler2** [hydroshare/hydroshare#1076]
Since the user will actually be adding what is required to make a resource public and/or discoverable in "edit" mode, can we put those requirements on that page and not just the "view" mode of the resource landing page?

**Comment by mjstealey** [comment]
@jsadler2 - Can this be closed?

**Comment by dtarb** [comment]
Messages are appearing in edit mode so closing.
