### ISSUE TITLE
Creation of map project file for HydroShare GIS app

### ISSUE THREAD

**Issue by shawncrawley** [hydroshare/hydroshare#1079]
This issue is mainly the for the purpose of documenting what has already been done to create a map project file for the HydroShare GIS app. However, if there are any suggested changes or questions, please let me know.

I have created a map project file that stores the current state of a HydroShare GIS session. The idea is that a user could, at any point, click a "save" button, which would either create a new HydroShare resource that stores the map project file, or (if the resource already exists) updates the map project file within the resource. This resource could then be opened in the HydroShare GIS app directly from resource's HydroShare landing page, upon which it would load exactly as it was left upon it being "saved".

This map project file is currently being implement in JSON format. However, rather than just giving it a '.json' extension, a more descriptive, "unique" extension will be used. The current idea is to give it a '.map' extension.

Here is an example of the contents of an actual map project file that the HydroShare GIS app generates:
```json
{
   "map":{
      "zoomLevel":7,
      "baseMap":"Aerial",
      "center":[
         -12183450.812430814,
         4790461.436688567
      ],
      "geoserverUrl":"http://127.0.0.1:8181/geoserver",
      "layers":{
         "3":{
            "geomType":"point",
            "index":3,
            "extents":[
               -19912541.08242471,
               -1615275.2821098042,
               16227999.52055631,
               11494640.162756963
            ],
            "name":"US Major Cities",
            "listOrder":1,
            "resType":"GeographicFeatureResource",
            "visible":true,
            "cssStyles":{
               "layer-id":"hydroshare_gis:res_205ebfe9fd2e458badabc47c3fa5488a",
               "font-size":"12",
               "stroke-opacity":"0",
               "fill-opacity":"1",
               "font-fill-opacity":"1",
               "labels":true,
               "font-fill":"#0000ff",
               "point-shape":"triangle",
               "stroke":"#FFFFFF",
               "label-field":"NAME",
               "stroke-width":"0",
               "point-size":"3",
               "fill":"#000000"
            },
            "attributes":"ST_FIPS,SFIPS,COUNTY_FIP,CFIPS,PL_FIPS,ID,NAME,ELEVATION,POP_1990,POPULATION,ST,STATE,WARNGENLEV,WARNGENTYP,WATCH_WARN,ZWATCH_WAR,PROG_DISC,ZPROG_DISC,COMBOFLAG,LAND_WATER,RECNUM,LON,LAT",
            "id":"hydroshare_gis:res_205ebfe9fd2e458badabc47c3fa5488a"
         },
         "4":{
            "geomType":"polygon",
            "index":4,
            "extents":[
               -19942590.527065367,
               -1617132.8440411827,
               20012848.849188723,
               11536823.23405008
            ],
            "name":"US States",
            "listOrder":2,
            "resType":"GeographicFeatureResource",
            "visible":true,
            "cssStyles":{
               "stroke-opacity":"1",
               "fill-opacity":"1",
               "labels":false,
               "layer-id":"hydroshare_gis:res_9b1d9d540f8e44238b3d5c2648a1d178",
               "stroke":"#000000",
               "stroke-width":"3",
               "fill":"#ffffff"
            },
            "attributes":"STATE,NAME,FIPS,LON,LAT",
            "id":"hydroshare_gis:res_9b1d9d540f8e44238b3d5c2648a1d178"
         }
      },
   }
}
```

**Comment by danames** [comment]
Looks like a great start, Shawn. Is this format extensible? I.e. is it easy
enough to add more information to the file format JSON code later without
breaking apps that aren't expecting the new bits?

**Comment by shawncrawley** [comment]
@danames In hoping that I understand your question I'll say yes. This format should be very extensible. If other apps were to rely on this format, there would be no issue if there were a key-value pair stored that they did not need. There would only be a problem if multiple apps were depending on the format and then one person decided to either delete a key-value pair or rename a key.

**Comment by dtarb** [comment]
Please touch base with @pkdash.  He has been investigating use of Hstore to increase flexibility.  I do not know the details, other than that a discussion with him would, I think, be worthwhile.

**Comment by shawncrawley** [comment]
@pkdash Could you expand on this Hstore topic? I have never heard of it. How does it relate to what I am attempting to do here? Should we have this conversation elsewhere, or is here fine?

**Comment by pkdash** [comment]
@shawncrawley If my understanding of the purpose of the map project file (json data) is correct, then I don't see HStore being relevant here. I am also quite new to HStore.  In Django HStore is a model field that allows storing data as a dictionary (key/value). Django provides a nice query interface to query the data stored using the HStore field.  Since the map project file is a json file, I don't see any issue in extending it with additional attributes.

**Comment by pkdash** [comment]
@shawncrawley Should this be closed?

**Comment by shawncrawley** [comment]
@pkdash I think it can be. We moved ahead a long time ago with the JSON file implementation.
