### ISSUE TITLE
Creation of a "Map Project Resource" that stores a map project file generated by the HydroShare GIS app

### ISSUE THREAD

**Issue by shawncrawley** [hydroshare/hydroshare#1080]
As discussed briefly in the weekly HydroShare call yesterday, the HydroShare GIS app has now been programmed to generate a map project file that essentially saves the current state of the app (this is documented in Issue #1079). Now, it is necessary to come up with the best way to enable this map project file to be stored as or connected to an official HydroShare resource type.

Some ideas that were presented yesterday are:
- Create a new Map Project Resource
  - Stores the map project file
  - Stores as metadata a reference to the resources that the map project consists of
- Create a Map Project Resource that essentially "implements" the Collection Resource
  - This is essentially the same as a collection, but with the additional, required map project file
- Just leave it as a Generic Resource
  - Either: It can then be added to a collection whose current resources are part of the map project
  - Or: It can be made to stand alone as a Generic Resource

What would be the best implementation? This is now open to discussion. I'm calling out a few people specifically to get the discussion going. Please reference others who may have useful and/or authoritative input. @danames @zhiyuli @horsburgh @dtarb @selimnairb

**Comment by danames** [comment]
I'd suggest going with the Map Project resource type. We can use it for
this app and for other apps that need a group of data resources with
symbology.

**Comment by shawncrawley** [comment]
I have not received any feedback other than from Dr. Ames, so I have decided to move forward with what both him and I have discussed. I am going to create the Map Project Resource based off of the Generic Resource. Though I will create it to only hold a '.map' file, I have decided that I will not add the Map Project Resource to the "Create New" options, since it doesn't make sense that someone creates a '.map' file themselves and generates the resource themselves. This will protect the creation of a Map Project Resource by limiting its creation solely to the HydroShare GIS app.
For metadata, I will start off by having only a list of the resources that are part of the map project, likely made into a link that redirects to each resource's landing page.

**Comment by hyi** [comment]
@shawncrawley I am a little confused with "Map Project Resource based off of the Generic Resource." Do you mean you create a different resource type like MapProjectResource or just create a Generic Resource which holds the .map file? Note that you cannot add additional metadata elements as of now for generic resource type, so you probably meant the former, i.e., create a different resource type. @pkdash I am thinking if we can add a HStore field to BaseResource class which could hold some arbitrary key-value pair attributes for the resource, Generic Resource can probably serve this Map Project Resource use case well without requiring creation of a new resource type.

**Comment by shawncrawley** [comment]
@hyi Sorry for the confusion. I guess I mean just created a completely resource type called MapProjectResource. I guess I just meant that it will be most similar to a Generic Resource, since there will not be much resource specific metadata associated with it, but there will be some. So yeah, creating a new resource type. But if we can all come to agreement on the HStore stuff, then I suppose I will not move forward in creating a new resource type quite yet.

**Comment by hyi** [comment]
@shawncrawley Got it. Thanks for the explanation. @pkdash @zhiyuli As part of collection resource type implementation, a collections ManyToManyField is added into BaseResource class. I think this collections field can be leveraged here for this MapProjectResource to hold a collection of all existing resources. Since collection resource type does not contain any content files, this MapProjectResource can be implemented as a GenericResource so it can contain the .map file while in the meantime use the collections field that was already added into BaseResource class as part of collection resource type work. This way, no new resource type is needed for this map project resource. What do you think?

**Comment by pkdash** [comment]
Would the MapProjectResource contain any other files besides the .map file?

**Comment by shawncrawley** [comment]
@pkdash No. At least not as we are currently envisioning this resource.

**Comment by pkdash** [comment]
Since GenericResource takes any file, how we going to prevent someone adding other files to MapProjectResource?

**Comment by pkdash** [comment]
If there as any additional metadata requirements or special file type requirements then may have to create a new resource type

**Comment by hyi** [comment]
@shawncrawley Is there requirement that this map project resource has to include only one .map file? If the map project resource can only be created programatically as part of HydroShare GIS app, this .map file will be included in the resource, and which can be consulted and used by GIS apps. Perhaps if owners of this resource want to add additional files such as a readme file, etc., into this resource, it is a good thing if we allow it.

**Comment by shawncrawley** [comment]
@hyi Actually that is a good point. In fact, one feature that will likely soon be added to the HydroShare GIS app is the ability to export the map to a PDF or png image. It would be nice if that file could also be stored in the resource.

**Comment by shawncrawley** [comment]
So I was just talking to @zhiyuli in person, and he was showing me how he leverages the ManyToMany field that was added to the BaseResource in the Collection Resource. Yet, in his case, he is leveraging that capability from his non-generic resource. That enables him to modify the landing page to display the associated resources as he dictates. If I understand correctly, @hyi, you are suggesting that I leverage the ManyToMany field, but not from a new resource type, but as a generic resource. How would that implementation look? I couldn't modify the landing page to reflect the associated resource types, could I? Does that make sense? Am I understanding this correctly?

**Comment by hyi** [comment]
@shawncrawley Yes, that was what I meant, to leverage that field as a generic resource. You map project generic resource model will have that collections/resources field which you can use to add all resources you want to include in this map project resource. Then you can modify resource landing page to check if this collections/resources field for generic resources is not empty, then you show the links to those contained resources. I think this should be doable without much issue.

**Comment by shawncrawley** [comment]
@hyi Alright, that makes sense. I am thankful for the ideas and discussion. At this point, it would be good to hear any thoughts from @danames. However, since I believe he is out of town until Monday we can postpone this discussion until then.

**Comment by pkdash** [comment]
If there is no need to list the map file within Hydroshare, one could store the json data in Hstore field once we add the HStore to BaseResource

**Comment by danames** [comment]
The present approach for apps associates an app with a resource type. We
need to be able to launch the GIS App from a GIS Map resource. Hence we
need to create a new resource type (not just use Generic).

Also, let's consider if we can override the  "Create New" button to launch
the GIS app so a user can still create a new map in a natural way (hit
create new, get a blank map, add data to it, save it to a resource.)

**Comment by pkdash** [comment]
Soon apps can be associated with file types. I am working with @zhiyuli on this.

**Comment by danames** [comment]
In the mean time, let's go with a new resource type for Map Projects.

**Comment by dtarb** [comment]
It seems like this functionality is already in place with Generic Resource holding map project.  So @shawncrawley please close if you agree.

**Comment by shawncrawley** [comment]
@dtarb Agreed. Though as you pointed out in our meeting, it might be best to implement the "Map Project Resource" as a Composite resource once that functionality is integrated into the hs_restclient. But for all current intents and purposes, this issue can be closed.
