### ISSUE TITLE
The option to extract metadata is no more available for timeseries resource

### ISSUE THREAD

**Issue by pkdash** [hydroshare/hydroshare#1088]
While testing timeseries resource on beta.hydroshare.org, noticed the option to extract metadata in the file add modal dialog box is no more available. This problem also exists on www. This might have been a result of the refactoring of html associated with the resource landing page that was done a while ago.

**Comment by mauriel133** [comment]
Do you have a screenshot of the missing option or could you be more specific?

**Comment by pkdash** [comment]
@mauriel133 Don't have a screenshot. For timeseries resource, there used to be a checkbox with text something like "Check to extract metadata" on the add file dialogbox.

**Comment by hyi** [comment]
@pkdash Please close this issue if it has been resolved.

**Comment by pkdash** [comment]
@hyi and @mauriel133 This is still a problem on www.

**Comment by mauriel133** [comment]
@pkdash, this fix has been pushed to www. Could you confirm and close?

**Comment by pkdash** [comment]
Closing.
