### ISSUE TITLE
Metadata update takes for ever when the resource has a large file

### ISSUE THREAD

**Issue by pkdash** [hydroshare/hydroshare#109]
I uploaded a file of size 1.4 GB. Then in resource editing page when I tried to update any metadata fields it felt like nothing is happening. It took quite a long time for the update success message to show up.

**Comment by rayi113** [comment]
Related to #105

**Comment by pkdash** [comment]
In the current workflow, a bag for a resource is created any time there is an update to the resource. The bag creation process can be very time consuming process when the resource has large amount of data. We need to optimize the bag creation workflow.
