### ISSUE TITLE
bag download failing on recent 1.6.8 www deploy

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#1092]
When I try download all contents as zipped archive for https://www.hydroshare.org/resource/b7822782896143ca8712395f6814c44b/ I get "Sorry an error occurred".  Unclear yet whether this is all bags, or just this resource or just this resource type.

**Comment by gantian127** [comment]
@mjstealey I just tested this resource https://www.hydroshare.org/resource/b7822782896143ca8712395f6814c44b/ on Beta the download works fine. Would you please check if the www is deployed the same as Beta? Thanks.

**Comment by mjstealey** [comment]
So, this is an interesting one...

The error is as follows (from hydroshare.log on www)

```python
[30/Mar/2016 19:43:55] ERROR [django.request:256] Internal Server Error: /django_irods/download/bags/b7822782896143ca8712395f6814c44b.zip
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 53, in handler
    return func(*args, **kwargs)
  File "/home/docker/hydroshare/django_irods/views.py", line 66, in download
    stdout = session.run("ils", None, "-l", path)[0].split()
  File "/home/docker/hydroshare/django_irods/icommands.py", line 171, in run
    raise SessionException(proc.returncode, stdout, stderr)
SessionException: (SessionException(...), 'Error processing IRODS request: 4. stderr follows:\n\nERROR: lsUtil: srcPath /hydroshareZone/home/wwwHydroProxy/bags/b7822782896143ca8712395f6814c44b.zip does not exist or user lacks access permission\n')
```

Viewing this from the iRODS point of view:

```bash
[stealey@build scripts]$ IRODS_ENVIRONMENT_FILE=~/.irods/www.json imeta ls -C b7822782896143ca8712395f6814c44b
AVUs defined for collection b7822782896143ca8712395f6814c44b:
attribute: isPublic
value: False
units:
----
attribute: resourceType
value: RasterResource
units:
----
attribute: bag_modified
value: false
units:
```
Manually set the bag_modified variable to be **true**, and then verify:

```bash
[stealey@build scripts]$ IRODS_ENVIRONMENT_FILE=~/.irods/www.json imeta set -C b7822782896143ca8712395f6814c44b bag_modified true
[stealey@build scripts]$ IRODS_ENVIRONMENT_FILE=~/.irods/www.json imeta ls -C b7822782896143ca8712395f6814c44b
AVUs defined for collection b7822782896143ca8712395f6814c44b:
attribute: isPublic
value: False
units:
----
attribute: bag_modified
value: true
units:
----
attribute: resourceType
value: RasterResource
units:
```

Then, go to the website and try to download the bag. 
Again, same error?

```python
[30/Mar/2016 19:48:18] ERROR [django.request:256] Internal Server Error: /django_irods/download/bags/b7822782896143ca8712395f6814c44b.zip
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/decorators.py", line 53, in handler
    return func(*args, **kwargs)
  File "/home/docker/hydroshare/django_irods/views.py", line 66, in download
    stdout = session.run("ils", None, "-l", path)[0].split()
  File "/home/docker/hydroshare/django_irods/icommands.py", line 171, in run
    raise SessionException(proc.returncode, stdout, stderr)
SessionException: (SessionException(...), 'Error processing IRODS request: 4. stderr follows:\n\nERROR: lsUtil: srcPath /hydroshareZone/home/wwwHydroProxy/bags/b7822782896143ca8712395f6814c44b.zip does not exist or user lacks access permission\n')
```
Upon looking in iRODS, the bag_modified AVU is now **false**

```bash
[stealey@build scripts]$ IRODS_ENVIRONMENT_FILE=~/.irods/www.json imeta ls -C b7822782896143ca8712395f6814c44b
AVUs defined for collection b7822782896143ca8712395f6814c44b:
attribute: isPublic
value: False
units:
----
attribute: resourceType
value: RasterResource
units:
----
attribute: bag_modified
value: false
units:
```

Somehow, something is failing and the bag is not being regenerated, though the AVU for bag_modified is getting set to false...

**Comment by dtarb** [comment]
This may be related to when the resource was created.  To raster resources I have created on June 5, 2015 exhibit this problem, but raster resources I have created after August 15, 2015 do not have this problem.

**Comment by dtarb** [comment]
This cropped up again in #1156.  @mjstealey can you please make an assessment of how prevalent this problem is and what the strategy for resolving this is, then we can identify who on the team to assign this to, and its priority.  If it is just a few resources we could fix it by identifying the resources and manually recreating.  If it is systemic we need to fix the system issue.  Perhaps we need a script to loop over all resources to try download the bags and identify the problem ones. If the API is used it may be something @jbradberry can help with.  If recreating resources from the bag is part of the solution, then we may need to prioritize an API function for this.  If it is related to iRODS, then we may need help from the iRODS team.

**Comment by hyi** [comment]
Info from issue #1156 to consolidate two issues into one:

Received status 500 Internal Server Error when accessing https://www.hydroshare.org/hsapi/resource/b7822782896143ca8712395f6814c44b/ with method GET and params None.
This was discovered when trying to retrieve the Zipped BagIt contents through the REST API, however the "Download" link itself on the resource landing page yields the same error. The resource in question is Public and Shareable. See it here: https://www.hydroshare.org/resource/b7822782896143ca8712395f6814c44b.

**Comment by hyi** [comment]
@mjstealey I am putting this issue on your plate for now. I can help with debugging and diagnosis if needed.

**Comment by mjstealey** [comment]
@hyi - Using iRODS to set the **bag_modified** flag to **true**, a request is made to download the bag file and the following error is captured by **system.log**. After which **bag_modifed** is again **false**, but no zip file has been generated.

```bash
[23/May/2016 15:53:28] ERROR Internal Server Error: /django_irods/download/bags/b7822782896143ca8712395f6814c44b.zip
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/rest_framework/views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/site-packages/rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/rest_framework/decorators.py", line 53, in handler
    return func(*args, **kwargs)
  File "/home/docker/hydroshare/django_irods/views.py", line 66, in download
    stdout = session.run("ils", None, "-l", path)[0].split()
  File "/home/docker/hydroshare/django_irods/icommands.py", line 171, in run
    raise SessionException(proc.returncode, stdout, stderr)
SessionException: (SessionException(...), 'Error processing IRODS request: 4. stderr follows:\n\nERROR: lsUtil: srcPath /hydroshareZone/home/wwwHydroProxy/bags/b7822782896143ca8712395f6814c44b.zip does not exist or user lacks access permission\n')
```

**Comment by hyi** [comment]
@mjstealey Yes, currently bag_modified uses lower-case true/false string as metadata values. I just created a PR that will fix the bug that bag_modified got reset to false after download failed, to make sure bag_modified AVU pair is only reset to false when on-demand bagging operation succeeds when downloading. However, for this specific resource, there is an issue with any data objects/file stored in iRODS for this resource. For example, I cannot iget any file for this resource successfully even though ils lists files successfully. I got ```UNIX_FILE_CREATE_ERR: no such file or directory``` error when iget any file for this resource. I don't have this issue for other resources. irule and ibun operation also fail with SYS_RESC_DOES_NOT_EXIST iRODS error, which is why the bag operation fails for this resource. I don't know what happens, but the error might be caused by the vrt custom migration that somehow messed up this resource file storage on iRODS side. If this issue only occurs for this specific resource, deleting it, then recreating it might be an option?

**Comment by hyi** [comment]
@mjstealey @dtarb @gantian127 After further investigation, I found I can actually iget resource content files such as logan.vrt and logan.tif, but cannot iget bagit.txt and manifest files generated by iRODS bagit rule. After looking into the physical vault, these bagit files don't exist in the vault, but somehow are listed in ils. After deleting these three "corrupt" non-physically-existent bag files and set bag_modified to true, this resource bag can be downloaded successfully. Not sure how the "corrupt" bag files were generated in the first place. Currently in our code base, bag files are only generated when users download a bag with bag_modified set to True implemented as on-demand bagging. So the issue might be caused by initial failure to create bags after custom raster resource migration, which left behind some corrupt files which prevents any further irods bagit operation to run successfully. Will try to fix or work around this issue by deleting any bagit files if bagit operation does not succeed. Will create a PR soon for this.

**Comment by dtarb** [comment]
Closing as this appears to be fixed with recent upgrades.
