### ISSUE TITLE
Web App - Edit page enhancements

### ISSUE THREAD

**Issue by Castronova** [hydroshare/hydroshare#1093]
Yan Liu requested that the Web App interface be refined to make its usage clear to users.
1. Parameters that can be in the URL value need to be specified somewhere on the App resource instance editing page.  These are currently only available by digging through the source code.
2. There needs to be validation of the URL.

**Comment by zhiyuli** [comment]
Help pages serve the purpose for (1);
User is responsible for the validity of the url they created, HS just does some simple checks to make sure the general syntax/format of the url is correct.
Closing
