### ISSUE TITLE
Web App - OAuth Clarification

### ISSUE THREAD

**Issue by Castronova** [hydroshare/hydroshare#1094]
The process of registering and using a Web App and OAuth is not clear.  The following should be implemented.
1. Add a button to the Web App landing page to redirect the user to the Oauth app registration (and use the standard Oauth app registration information)
2. The Oauth request page needs clarification and branding.  
   - redesign content 
   - include description and access requirements
3. When using a Web App, the user should be prompted with a message stating that this action will allow the app to read, write, and modify, their resources.  Do they wish to continue?

**Comment by zhiyuli** [comment]
@Castronova 
Regarding (1): setting up oauth is a one-time process that should be done by the Admin of App Server (Tethys, CyberGIS, SWATShare and...), not by app developers or webapp res owners. So I think maybe it is unnecessary to display any "OAuth" setting on a webapp landing page.  

Further, currently any hs user can go to "/o/applications/" to register a new OAuth client. Is it what we want? Is there any potential security issue? What is the worst thing that can happen if a user unintentionally or intentionally leak his oauth client_id and client_secret to others? @selimnairb @ironfroggy @mjstealey

**Comment by selimnairb** [comment]
@zhiyuli This is a policy decision to be made by the PIs.  Google, and others, allow arbitrary developers to register applications and obtain OAuth client IDs.

**Comment by dtarb** [comment]
I'd like to make any policy decision needed, but I do not understand the issues and consequences fully.  Can one of you @Castronova, @zhiyuli please explain in a bit more detail how this works, what the question is, and what options there are.  Alternatively, I'd be happy to listen to the recommendation of @alvacouch since it pertains to security.

**Comment by cuahsimarko** [comment]
@hyi I believe you have done some work on this since the year 2017

**Comment by hyi** [comment]
@cuahsimarko I have not involved with Web App - OAuth work for HydroShare.

**Comment by dtarb** [comment]
I am in favor of closing this.  While I am uncertain where it is documented, I know that we have had web app developers connect successfully using Oauth.  Thus in the spirit of #3289 I am closing. If new Oauth questions arise, they can get their new issues.
