### ISSUE TITLE
Uploaded data names split incorrectly

### ISSUE THREAD

**Issue by Castronova** [hydroshare/hydroshare#1098]
When a file containing spaces in the name is uploaded to the Model Program resource and selected as either **Computational Engine**, **Software**, **Documentation**, or **Release Notes**, the value displayed on the resource landing page contains only the first word of the name.  This is most likely a result of the name being split at space characters.

**Comment by mjstealey** [comment]
@Castronova Fixed? or not yet?

**Comment by jsadler2** [comment]
This looks good to me. Closing
