### ISSUE TITLE
Initial implementation of use tracking 

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#11]
The use tracking specification is in Alfresco at https://my.alfresco.com/share/s/qg6hiagfQpuNnYW34Dyvng.

**Comment by dtarb** [comment]
The specifications have been migrated to Google Drive and this is assigned to @ironfroggy

**Comment by alexlemann** [comment]
Initial tracking finalized with adding tracking of download events in issue #1531 and PR #1612
