### ISSUE TITLE
Collection Res Type and Versioning

### ISSUE THREAD

**Issue by zhiyuli** [hydroshare/hydroshare#1102]
This issue may include two sub-issues: 
(1) How to make a new version of a collection resource? 
We decided to take NO account of issue (1) in current PR #1083. So it disabled the "versioning " button on collection landing page, 

(2) How to handle contained resources that have different versions? Can Res A and its newer version Res A' be in the same collection? 
Issue (2) was just brought up during the code review on PR #1083.

A comprehensive solution that can address both issues in one shot is needed.  @dtarb @horsburgh @danames @hyi @pkdash

**Comment by dtarb** [comment]
My recommendation is to keep things simple and leave this up to the person managing the collection.  Think of a collection as simply a list of resources.  If the person who is editing it wants to list both versions in it they can.  If they want to edit the resource to remove the old version and add a new version they can.  Once a collection resource gets published it is immutable, i.e. the list is fixed.  So no more adding or removing from the list by anyone except by creating a new version of the collection resource.  So if a new version of one of the contained resources comes out, for it to be in the collection, someone with authority to create a new version would have to create a new version of the collection then edit it as they deemed fit, keeping say the latest version, or both versions depending on their needs.   This simple and flexible approach, I think will allow us to get experience with what users do and address any questions that come up based on experience, not hypothetical considerations.

**Comment by pkdash** [comment]
I do not see any relation between issue (1) and issue (2). I agree with @dtarb recommendation to leave it up to the collection owners/editors to decide what resources to put in a collection. In creating a version of collection the existing resource versioning code will be used with additional code needed to add the resources to the new collection.

**Comment by hyi** [comment]
I also agree with @dtarb 's suggestion to leave it up to the users to decide what resources to put in a collection without versioning constraint. This also makes coding easier, but I do think we should only present latest versions of resources for users to pick to add to their collections to make the behavior consistent across HydroShare since we remove obsoleted resources from my resources page and from discovery.

**Comment by zhiyuli** [comment]
tested on www
