### ISSUE TITLE
how should map interface to discovery work?

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#1106]
Zhaokun and I are thinking about how the map view and the listing view should interact. 

My suggestion: 
- Selecting a subregion of the map makes that the active area: 
- *On the non-map (listing) view*, coordinates of that box are listed, 
   along with a "use all locations" button that clears it.
- On the non-map (listing)  view, we see only things that overlap with that region. 
  - for coverages, overlap means that at least one corner is in the viewable area.   
  - for points, the point has to be in the viewable area. 
- pressing "use all locations" blanks out the location filter and shows everything. 

@dtarb @danames @horsburgh Does this seem reasonable?

**Comment by alvacouch** [comment]
Some sub-notes: 
- label the search term box with 'search for;' or some similar annotation. 
- put the north, east, south, west boxes beneath the search term and above the listing. Label them as such. 
- put the 'use all locations' button to right of these.

**Comment by horsburgh** [comment]
Seems like a reasonable first approach to me.

**Comment by dtarb** [comment]
I agree this seems reasonable.  I have a small concern that switching back and forth between a map and tab view will be cumbersome.  Also it may be good to have the corner coordinates for the list view tab be user editable in case a user wants to specify specific coordinates.

However, getting this deployed is higher priority than any of these refinements, which I would be happy to see come later.  I suspect that once we deploy we will get other feedback that can be responded to.

**Comment by hyi** [comment]
@alvacouch Now that map interface has been implemented and deployed, can this issue be closed?

**Comment by mjstealey** [comment]
Open new issues based on deployed work as reference point if required
