### ISSUE TITLE
Alpha release suggestions

### ISSUE THREAD

**Issue by jsadler2** [hydroshare/hydroshare#112]
* If your metadata is insufficient it should list why. I know it's highlighted when the page first loads but the missing elements should be listed next to the 'Incomplete' status.

* The user shouldn't have to refresh the page to end the 'editing' session. I think that having a 'Finish Edits' or 'Save Edits' would be better

**Comment by shaunjl** [comment]
On your first bullet by "when the page first loads" do you mean the first redirect after clicking on "create resource?" If so I agree. Maybe a quick fix would be to add some logic next to that status that says something like {% if not keywords %) ...

**Comment by mjstealey** [comment]
Requires discussion

**Comment by dtarb** [comment]
Closing for now.  @jsadler2  and @shaunjl see the 1.4 release candidate and re-raise issues if needed.
