### ISSUE TITLE
Proposal for composite resource type

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#1126]
I would like to propose a new composite resource type to move HydroShare towards the model of file types separate from resource types.  Separate file and resource types have been discussed in #965 and #1034, but these are complex and intimidating (and in my opinion slowing development).  I think that a composite resource type can circumvent the difficulties and get us functionality that we need quickly.

The need for apps to act on individual files within a resource has come from both RHESSys and CyberGIS use cases and discussions related to the HydroShare GIS app.

I suggest we define a composite resource as a resource holding one or more files of **a recognized type**. For the first implementation this could be identical to a generic resource with the added metadata of an identifier giving the file type for each file.  There would need to be a table in HydroShare that lists acceptable file types.  For simplicity I suggest we start with just raster, shapefile and netcdf, then add others late.  The table would need to also list mime type and possibly a file type description.  It may be that mime type can be file type.  Then we can incrementally add functionality such as
- Ability of HydroShare GIS app to look at the files in this resource type and load them based on type
- Ability to have additional metadata such as is currently associated with a typed resource with the corresponding typed file.  This would reuse code already in place for raster, feature and netcdf resources (but without having to touch those resource types)
- Ability to associate an app with a recognized file type just as we do now for a resource.  Extend the app linkage model for this.
- Ability to move files from an existing resource into a composite resource. 

While a composite resource has elements similar to collections, it is distinct from a collection.  A collection is comprised of fully formed resources, while a composite resource just holds files of a known type.  A collection could hold composite resources (composite resource just being a new resource type).  A composite resource could not hold a collection (or any other resource for that matter).  It holds files, not fully formed resources.

By building this functionality in the context of a new resource type I think we can defer refactoring existing resource functionality.  I do not think we need complex validation for the initial implementations, nor the celery tasks and registry for validators mentioned in #1034, at least initially.  I think that considerable functionality can be implemented just relying on mime type.  HydroShare would thus not protect users from misleadingly named files that have an extension (mime type) that does not match the content.  

Files that are held in composite resources may need to be generalized to include "folders of content" to accommodate shapefiles and rasters, because for both of these there are multiple files involved in a single object.  The functionality for this should be identical to how multiple files are handled for geographic feature and raster resources.

**Comment by horsburgh** [comment]
Not sure how this is different than what we have already with generic resource? Each generic resource already has a set of files - some of which have recognized types. Mime types for files can already be recorded in the metadata for the generic resource. What's missing is the ability for an app to look inside a resource and pull out an individual file (or set of files).  Not sure how a new resource type would solve that problem.

I also think it would be somewhat confusing for users - e.g., you can view a file of this type in this app, but only if it is part of a "composite" resource and not any other kind of resource.  And - it seems like it needs to be consistent. If I can open a raster file from a generic resource in the GIS App, I should also be able to open a raster file from a raster resource or a model instance resource, or any other type of resource that contains a raster file of the right type.

**Comment by dtarb** [comment]
This is proposed as an incremental solution to avoid what seems to be big refactoring of existing resources to achieve this.  If we can achieve this for generic/all resources without an incremental approach I would support that, but this is an attempt to unbog what seems to be bogged down.

**Comment by danames** [comment]
I tend to agree with Jeff on this. We need to articulate the use case for a
composite resource a bit better. In fact, in our current system, we can
write apps to read files out of resources and act on them. Shawn is
currently working to extend HydroShare GIS to open any resource type,
inspect it's contents, and load any known layer types. This will all work
with our current resources - just requires a clever app. Other apps could
behave similarly. So let's think about what use case would not be supported
by our current model.  I'm sure there is one, but I'm not quite seeing it
yet. - Dan

**Comment by dtarb** [comment]
If we can get this done with existing resources I am all for it.  The immediate use case I want to support is that CyberGIS returns multiple TauDEM results in a single generic resource.  I want to be able to visualize these.  We could have CyberGIS return individual resources, but that requires an abstract and keyword for each - which seems overkill and loses the grouping of them together.

Also we have designed resource specific metadata for things like rasters and shapefiles.  This adds value to the files.  I'd like this metadata to be able to be associated with individual files in a resource, rather than held at the resource level.  This would support the CyberGIS TauDEM use case allowing metadata to say what the rasters are (elevation, contributing area etc, and give the units).

An App should be able to get a list of files in a resource and could infer type from its extension.  This is not robust, but probably OK.  An App resource should be able to declare the file extensions it can work with (small extension to the app resource model), and then any resource landing page could enable an open with that app button next to that file in the resource (an extension to the resource landing page model).  Complications arise for logical files that are comprised of multiple physical files (such as shapefiles and .vrt raster files that we are already using).  We could accommodate this perhaps by requiring these all be encapsulated in directories so they are logically together.  The resource data model already lists file and mime types for the files in a resource, but as currently implemented this listing does not map to specific files.  I do not know how complicated changing this would be, or if it is necessary if we just use file extensions.

**Comment by danames** [comment]
Perhaps CyberGIS could output a single generic resource with all the
generated rasters AND a HydroShare GIS project file with the symbology,
ready for viewing in HydroShare GIS. - Dan

**Comment by dtarb** [comment]
That would be cool.  It is certainly well within the realm of possibility once you get the GIS project figures out.

**Comment by hyi** [comment]
@pkdash I am putting this on your plate initially with a lower priority milestone. This needs more discussion before implementation.

**Comment by pkdash** [comment]
@dtarb Does this issue need to stay open until we implement all file types?

**Comment by dtarb** [comment]
I am happy to close and handle additional types, or additional issues associated with this separately.
