### ISSUE TITLE
Manage access button not triggering on latest release

### ISSUE THREAD

**Issue by mauriel133** [hydroshare/hydroshare#1129]

**Comment by mjstealey** [comment]
@mauriel133 This is not working on beta either. If you want to try some direct changes to the code we can do that on beta for testing purposes.

Unsure if it's related, but there have been issues in the past with **http** references being used in the **https** environment. In general best to let the server figure out what to use and not hard code it to one or the other.

**Comment by zhiyuli** [comment]
@mauriel133 @mjstealey I am not sure whether it is only happening on my end. I have a private generic res and only the "EDIT" btn is working...all other btns are not....
![image](https://cloud.githubusercontent.com/assets/10070599/14566130/7324fa9c-02eb-11e6-97e0-51de71e55053.png)

**Comment by mjstealey** [comment]
> I am not sure whether it is only happening on my end

Happens to me as well, and the same is observable on beta, so at least it is uniformly broken, and not just an anomaly on www. This should hopefully make it easier to track down the specifics.

**Comment by mjstealey** [comment]
@mauriel133 If it's useful for testing you can use both Nginx and SSL in your local environment. You just need to update some of the settings in `config/hydroshare-config.yaml`.

This:
```yaml
FQDN_OR_IP: 192.168.56.101 # or whatever your VMs IP is
```

And this:
```yaml
### Deployment Options ###
USE_NGINX: true
USE_SSL: true
```

Then issue `./hsctl restart` and you'll be able to test the UI at **https://192.168.56.101**

**Comment by mauriel133** [comment]
I found the issue. I will make a PR and tag it as hotfix.

It was caused by "hydroshare_tags" not being included in the load tag of modals.html

**Comment by mjstealey** [comment]
Have updated this manually on both www and beta.
Looks to be working as expected.
Will apply hotfix to both develop and master and re-tag the 1.6.9 deploy.

**Comment by mauriel133** [comment]
Confirmed working on https://riverdev.hydroshare.org/ as well. Will merge PR once tests pass.
