### ISSUE TITLE
Strange new App for Time Series

### ISSUE THREAD

**Issue by horsburgh** [hydroshare/hydroshare#1132]
When I view my time series resource, I can open it with a strange new app:

![image](https://cloud.githubusercontent.com/assets/3485902/14590953/0540aa4a-04c5-11e6-9d8d-83a37950c024.png)

The link takes me to www.danames.com. I know we've had this conversation before, but does there need to be some sort of review of Apps before they start showing up on the landing page for resources?

**Comment by mjstealey** [comment]
@horsburgh, Doh no! You've been **Ames'd**!!
This is definitely the next big internet meme.

I seem to recall this as one of the first Tool demos long ago for the time series resource. It pre-dated the "App" naming scheme if I remember correctly. Nonetheless, the fact that it made it to production means we overlooked something fairly big and need to address it. 

I suspect we'll want to strip the reference for this App from the time series resource and also relegate the Ames app to something less production oriented.

This made my night btw ;-)

**Comment by horsburgh** [comment]
Ha ha - "Ames'd"

**Comment by dtarb** [comment]
@danames @zhiyuli you guys need to take care of this.

**Comment by danames** [comment]
I removed the offending app resource. By the way, this does raise some
questions. Right now we allow any user to create an app resource with any
name and associate it with any resource type and make it public which means
it shows up for everyone. I propose that we NOT allow them to make app
resources public until they have been reviewed by some HydroShare content
gatekeeper.

**Comment by horsburgh** [comment]
I second the need for an apps gatekeeper.  It would actually be cool if there was a different designation for apps that enabled them to be approved for showing up on the landing pages for resources. Sort of like how one has to get an app approved by Apple before it's available in the App store.  I think anyone should be able to create and app and share it (potentially even publicly).  But, when it shows up under "Open with" on my resource's landing page it would be good if there was some assurance that it is going to do something useful.

**Comment by dtarb** [comment]
I suggest using a mechanism similar to star on my resources for a user to mark apps that they want to activate.  We could overload "star" or "favorite" for this purpose if we want to stick with existing functionality on My Resources, or we could add another almost identical property for a user to mark apps they want to use.  This way there can be many apps shared publicly without restriction, but a user gets to choose which apps they want to use.  This does mean that one has to be logged in to use apps, but I do not see this as a big shortcoming.  

There is also the web apps tab on each resource landing page and I would not object to listing all apps here under a heading such as "Community apps you may choose to use with this resource" and then have with each app an info link that goes to the app landing page and run link that launches the app.  The app landing page should have a button similar to "favorite" to select the app.  That way users have a way of discovering what apps are available for their resources, learning about them, marking them, and running them when not logged in (if the app permits this) as this tab is available when not signed in.

**Comment by dtarb** [comment]
I am closing this as this specific issue has been addressed.  I am opening #1161 that describes the enhanced functionality to address app gatekeeping.
