### ISSUE TITLE
Session exception on 1.6.10 pre-release deploy

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#1134]
Go to Discover.  Enter search term "Hand", click on the single resource found.  A session Exception results.  Note this is while not logged in.  This does not occur in www.

![untitled](https://cloud.githubusercontent.com/assets/3456833/14693242/617f87fc-071a-11e6-8f23-97f023d8f0c3.png)

**Comment by dtarb** [comment]
@hyi assigned to you as suspect an iRODS issue, but if not, assign to @xuezhaokun

**Comment by hyi** [comment]
@dtarb @mjstealey Just checked and found this resource exists on iRODS backend for www proxy account, but does not exist on iRODS backend for alpha proxy account, exactly as reported by the iRODS error. So it looks like a irsync issue when syncing www resources from www to alpha. I am reassigning it to @mjstealey for now.

**Comment by mjstealey** [comment]
> but does not exist on iRODS backend for alpha proxy account

This is correct. This has also been mentioned in at least 3 of our team meetings. The irsync call from our www vault does not pull in all resources for reasons that are still unknown.

I suspect there is some clash between older resources and newer ones, and things somehow getting caught in-between. Our code long ago did not properly cleanup after itself when a resource was deleted, but instead left an orphaned GUID directory with metatdata files behind and this causes some confusion when the scripts try to pull all resources from the www vault into a local store.

I've not yet been able to address why this occurs, but it is the current state of things. Also as mentioned in our team meetings, this can be observed in the weekly console output from Jenkins.

Example: [http://ci.hydroshare.org:8080/view/3.%20Housekeeping/job/datasync-irods-to-local/24/console](http://ci.hydroshare.org:8080/view/3.%20Housekeeping/job/datasync-irods-to-local/24/console)

**Comment by dtarb** [comment]
@mjstealey  if you are confident this is a quirk of the alpha and www iRODS differences and hence will not manifest when we deploy, then this can be taken as a non deploy blocking issue and closed once we deploy and validate this to not be a problem.

**Comment by mjstealey** [comment]
> if you are confident this is a quirk of the alpha and www iRODS differences

@dtarb - Yes, confident this is a quirk. It's occurred before and has been noted by other users as well in prior deploys (via HipChat conversations)

**Comment by dtarb** [comment]
Closing as this is a staging platform quirk.
