### ISSUE TITLE
Page not found error in alpha pre-release

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#1136]
The following sequence when not logged in results in a page not found error in alpha pre release.

1. Discover
2. Expand Filter by availability.
3. Click on the word private (not the check box)

This appear to occur any time a word is clicked in the filter facets prior to selecting any check box.

**Comment by dtarb** [comment]
@mjstealey @xuezhaokun @alvacouch this bug still exists in the pre-release that was deployed today.  This is more general than the sequence above and can be created by opening Discover and immediately clicking on the top persons name link there.  It is thus in my mind a deploy blocking bug that needs to be fixed.

**Comment by mjstealey** [comment]
> this bug still exists in the pre-release

@xuezhaokun, @alvacouch - Is it possible that PR #1152 resolves this?

If the PR can be vetted by someone prior to the team call we can deploy and check against the release candidate.

**Comment by mjstealey** [comment]
> This is more general than the sequence above

What is interesting about the existing deploy is that clicking the linked Name will work after any check boxed item has been checked, and then unchecked.
There seems to be some kind of initialization that takes place where the links work as expected following a check / uncheck sequence. (Safari browser)

**Comment by alvacouch** [comment]
@mjstealey The behavior above is due to session caching. 

The private button no longer exists in PR #1152

**Comment by xuezhaokun** [comment]
@dtarb It has been fixed in PR #1152 . Can anyone review that PR?

**Comment by dtarb** [comment]
@alvacouch I cleared my cache and the bug persists.  It is more general than first described.  It occurs whenever a Name link is first clicked prior to any check boxes.  (Sorry if this is expanding the issue, but my initial description was a bit focused).

**Comment by alvacouch** [comment]
@xuezhaokun See @dtarb 's explanation above. Is that fixed. I think so.....

**Comment by xuezhaokun** [comment]
@alvacouch I fixed this issue in PR #1152.

**Comment by mjstealey** [comment]
@dtarb, @alvacouch, @xuezhaokun - Branch in question has been deployed to: https://park.hydroshare.org

Please verify

**Comment by dtarb** [comment]
Fixed in 1.6.10 Candidate release.
