### ISSUE TITLE
SWATShare apps linked to the  generic Model Instance resource type

### ISSUE THREAD

**Issue by mohamedmorsy** [hydroshare/hydroshare#1138]
This app should be linked to the specific Model Instance resource type: SWAT Model Instance resource type only. As an example, for the Model Instance resource: https://alpha.hydroshare.org/resource/12d195906f2c41918cb24e11a5c3ab60/, there is a tab called "open with.." that has a drop list contains the SWATShare apps (see below)
![image](https://cloud.githubusercontent.com/assets/5543781/14694410/32d1a9fa-0736-11e6-829a-cb35950f98c3.png)
 Also the "web apps" that contains all the SWATShare apps should show only for the SWAT Model Instance resource (see below)
![image](https://cloud.githubusercontent.com/assets/5543781/14694448/7e4c919c-0736-11e6-9461-fb00f7107ad7.png)

**Comment by zhiyuli** [comment]
@mohamedmorsy 

It was caused by partially matching the supported res type names with other res types names.
In this particular failing case, "ModelInstance" was mistakenly considered to match with "SWATModelInstance" because the common text "ModelInstance" in both.

Thanks for reporting this.

**Comment by zhiyuli** [comment]
@mohamedmorsy  The bug should be fixed on www. Will you double check and close this issue? thanks

**Comment by mohamedmorsy** [comment]
I checked the issue and it has been solved on www
