### ISSUE TITLE
The "Filter By Author" table on the discover page does not align with the other filter tables

### ISSUE THREAD

**Issue by mohamedmorsy** [hydroshare/hydroshare#1139]
![image](https://cloud.githubusercontent.com/assets/5543781/14694738/6689d2d8-0739-11e6-8844-4d5e92a78fad.png)

**Comment by xuezhaokun** [comment]
@mohamedmorsy what browser are you using?

**Comment by mohamedmorsy** [comment]
@xuezhaokun  Google Chrome

**Comment by xuezhaokun** [comment]
@mohamedmorsy I don't have this problem in my chrome. I will double check the html layout. Thanks!

**Comment by mohamedmorsy** [comment]
@xuezhaokun I found the problem. On my chrome, my default zoom is 125% (see below)

![image](https://cloud.githubusercontent.com/assets/5543781/14695352/492654ea-073f-11e6-8858-b71071a30a69.png)

Once I change it to 100% it works as expected (see below)

![image](https://cloud.githubusercontent.com/assets/5543781/14695376/7e0eb0ee-073f-11e6-98c9-fbf488a0b539.png)

**Comment by xuezhaokun** [comment]
@mohamedmorsy I see. I think it should work for zoom 125%. It is working well on my firefox for any zoom level. I am checking it on chrome.

**Comment by dtarb** [comment]
@mohamedmorsy please check if this is still an issue in the current release candidate.

**Comment by mohamedmorsy** [comment]
@dtarb it looks good to me now.

**Comment by dtarb** [comment]
Closing as @mohamedmorsy has OK'd
