### ISSUE TITLE
Add to my resource icon appears on resource landing page when not logged in

### ISSUE THREAD

**Issue by pkdash** [hydroshare/hydroshare#1145]
This icon should not appear on a resource landing page if the user is not logged in.

![image](https://cloud.githubusercontent.com/assets/2523434/14698342/0c1a7188-074b-11e6-943d-7340d64013f6.png)

**Comment by dtarb** [comment]
Instead of removing the Add to My resources button for users not signed in, consider having the behavior when it is clicked be a message that pops up saying "You need to be signed in to use this functionality" and take them to the sign in page.

**Comment by mauriel133** [comment]
The icon is now hidden if the user is not signed in. Please confirm and close if it works as desired.

**Comment by pkdash** [comment]
This has been resolved.
