### ISSUE TITLE
Unsharing self in manage access for resource shows error

### ISSUE THREAD

**Issue by pkdash** [hydroshare/hydroshare#1146]
When trying to remove access permission of self (pkdash) in manage access control, shows error even though the unsharing actually successful (tested on alpha). 

![image](https://cloud.githubusercontent.com/assets/2523434/14698581/6fc591d4-074d-11e6-9714-200732733459.png)

**Comment by hyi** [comment]
@alvacouch Assigning to you for initial investigation since it seems to be caused by access control. You can reassign as needed.

**Comment by alvacouch** [comment]
May be fixed by PR #1576 .... please test ...

**Comment by pkdash** [comment]
@alvacouch I will test it and let you know.

**Comment by pkdash** [comment]
@alvacouch This error still exists.

**Comment by pkdash** [comment]
When did the test locally with the latest develop, did not see this anymore.  Will close this after testing again on beta when 1.9.0 is ready for testing.

**Comment by pkdash** [comment]
When self unsharing of a resource is successful, the user should be redirected to the 'my resources' page.

**Comment by pkdash** [comment]
This has been fixed. So closing.
