### ISSUE TITLE
Access control - self demoting to a lower access privilege shows error

### ISSUE THREAD

**Issue by pkdash** [hydroshare/hydroshare#1147]
On alpha, when tried to change access permission for self from edit to view permission in Manage Access control panel, it showed the following error:

![image](https://cloud.githubusercontent.com/assets/2523434/14698839/d5d8da9c-074f-11e6-88aa-23544f5334a6.png)

**Comment by alvacouch** [comment]
Should be fixed by PR #1576. Someone please test this.

**Comment by pkdash** [comment]
@alvacouch I will test it.

**Comment by pkdash** [comment]
@alvacouch This error still exists.

**Comment by pkdash** [comment]
When did the test locally with the latest develop, did not see this anymore.  Will close this after testing again on beta when 1.9.0 is ready for testing.

**Comment by dtarb** [comment]
Seems to be fixed on beta.
