### ISSUE TITLE
Discover on Alpha not finding all owners

### ISSUE THREAD

**Issue by rayi113** [hydroshare/hydroshare#1148]
I'm not able to sign-off on the #1133 manual pre-deploy checklist.  When I perform the Discovery operation "Filter by Owner" by selecting the checkbox next to my last name in the +Filter by Owner area on the Discover page on Alpha, it should discover this resource that I am an owner of, but it does not: https://alpha.hydroshare.org/resource/31acb0c0a66f4de08f541077bdf3e1d2/ 

Rather it appears to be producing the same results as +Filter by Author.

**Comment by mjstealey** [comment]
@rayi113 - There is seemingly a rank/order in search by author vs owner which is not necessarily as we expect.

You'll readily find this resource if you first search by "Jiri" in the Search box (Who is the Author of this resource). Then once that search completes, look down at the facets and expand the one for "Owner", lo and behold the resource owned by "Ray" appears.

**Comment by rayi113** [comment]
@mjstealey Thanks, this thread helped me find the real bug which is more nuanced.  If I go to the Discovery page and select "Show All" and then scroll to find my last name in the +Filter by Owner (without selecting any other Filter by criteria), it correctly finds all resources I am an owner of.  Then I select "Show All" to reset the search.  Then I type my last name into the search box at the bottom which refines the "Filter by Owner" choices to only myself and @dtarb.  I then select only my name from these two choices in +Filter by Owner, and it does not find https://alpha.hydroshare.org/resource/31acb0c0a66f4de08f541077bdf3e1d2/

**Comment by dtarb** [comment]
@rayi113 please see if this is still an issue.

**Comment by rayi113** [comment]
@dtarb This works on Alpha now.  Closing.
