### ISSUE TITLE
NetCDF resource ncdump command doesn't work

### ISSUE THREAD

**Issue by gantian127** [hydroshare/hydroshare#1149]
After a file is uploaded into HydroShare, the system should run "ncdump" command to generate the metadata header information text file. Currently, the backup python code is used to generate the text file.  Need to recover the ncdump command call.

**Comment by mjstealey** [comment]
> the system should run "ncdump"

@gantian127 try adding this to the [Dockerfile](https://github.com/hydroshare/hydroshare/blob/develop/Dockerfile) and verify that it does what you want on a rebuild.

```yaml
RUN apt-get update && apt-get install -y netcdf-bin
```

**Comment by gantian127** [comment]
@mjstealey Thanks for commenting on this issue. I will try to do it.

**Comment by gantian127** [comment]
@mjstealey I just tested the code and it works to call the ncdump command. Do you want me to add this line of code in the Docker file and merge it to develop branch or you want to update it directly in the hs_docker_base image? Thanks

**Comment by mjstealey** [comment]
> Do you want me to add this line of code in the Docker file and merge it to develop branch

Yes, please do.
When it's time to release 1.6.10 I'll migrate your code, as well as any other new Dockerfile code, into the base image. But until that time it should be in the Dockerfile so that anyone who pulls the develop branch has it.
