### ISSUE TITLE
Map search doesn't show the correct resource names

### ISSUE THREAD

**Issue by gantian127** [hydroshare/hydroshare#1150]
I did the search and got the results in the graph below. The map doesn't show the resource names correctly. The "untitled resource" actually has a resource title.
![n6 eysxr5 a2b gado _mky](https://cloud.githubusercontent.com/assets/5016511/14718073/bd9e0896-07b1-11e6-9ff2-deb28851214b.png)
![image](https://cloud.githubusercontent.com/assets/5016511/14718079/c7241392-07b1-11e6-97f6-c99e95cc5584.png)

**Comment by xuezhaokun** [comment]
@gantian127 fixed. Thanks for reporting!

**Comment by dtarb** [comment]
@gantian127 please check if this is still an issue in the current candidate release and if not, close.  I am unable to reproduce this on the current candidate release.
