### ISSUE TITLE
Time Series: Metadata (Re)Extraction Not Working Correctly

### ISSUE THREAD

**Issue by horsburgh** [hydroshare/hydroshare#1151]
Testing on alpha.hydroshare.org for release 1.6.10:

Previously when I deleted the SQLite file from the time series resource and then uploaded a new one the dialog asked me if I wanted it to re-extract metadata. This no longer happens, but should.  Not sure how it got lost.

**Comment by pkdash** [comment]
@mauriel133 Not sure how this functionality disappeared again.

**Comment by mauriel133** [comment]
This fix has been deployed to www. Please verify and close.

**Comment by pkdash** [comment]
@mauriel133 This option has been removed for next release (1.7.4).

**Comment by horsburgh** [comment]
Given that this option has been removed for the next release, I'm going to close this one.
