### ISSUE TITLE
Invalid File Message is not Very Helpful

### ISSUE THREAD

**Issue by horsburgh** [hydroshare/hydroshare#1153]
Testing on alpha.hydroshare.org for release 1.6.10:

When I try to upload a non-valid file for a time series resource, it notifies me that the file is invalid, but doesn't tell me what file type is valid.  

![image](https://cloud.githubusercontent.com/assets/3485902/14723305/95616b40-07cd-11e6-997a-15567883e007.png)

I suggest the text should instead be something like:

Invalid file type: '.xxx'. Time series files must be SQLite files with extension '.sqlite'.

**Comment by pkdash** [comment]
@horsburgh It says under the "Choose File'' button "Only the listed file types can be uploaded: ('.sqlite')".

**Comment by horsburgh** [comment]
Fair enough. Thanks for pointing that out. I was transfixed by the very large red letters of the error message!  I think this is ok then.
