### ISSUE TITLE
limit webapp icon size

### ISSUE THREAD

**Issue by zhiyuli** [hydroshare/hydroshare#1155]
In some cases the webapp displays a very large icon. The css code used to limit the icon size is not applied due to recent re-arrangement of the html template structure in hs_core.

![image](https://cloud.githubusercontent.com/assets/10070599/14724146/a29ec9de-07d1-11e6-85e0-56118fda7355.png)

**Comment by dtarb** [comment]
@zhiyuli please check if this is fixed, and if it is close.

**Comment by zhiyuli** [comment]
resolved on www. closed
