### ISSUE TITLE
HydroShare GIS Suggestions

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#1157]
@shawncrawley and @danames following are suggestions for the HydroShare GIS App resource based on current deployment at appsdev.  
- [x] In modify symbology for a raster show the minimum and maximum data values to help in selecting colors.  (Unless this information can be found from the .tif or .vrt file this may require extending the raster resource data model to include minimum and maximum with help from @gantian127).  
- [x] In raster legend have the option to show the variable name and variable unit to help a user see what this is.  This is part of raster resource specific metadata.
- [x] In modify symbology for a raster provide capability for classified colors with range values defining classes.
- [x] in modify symbology for a raster provide capability for unique colors for integer data.  
- [x] In modify symbology for a raster keep the no data value out of the range that is initially symbolized and default no data symbolization to transparent (though there should be the option to set a specific color for no data).
- [x] Provide the capability to add individual GIS type files from within other resources.  This is one of the functionalities driving file type functionality (#965, #1034, #1126)
- [x] Enhance the Load HydroShare resource functionality to make it easier to find a resource within the long list.  Perhaps this needs coordination with the Discover and MyResources functionality.
- [ ] Fill out the spatial coverage metadata associated with the Map Project Resource. 
- [ ] Fill out the related resources metadata associated with the map project to include the relationship "has part" (see http://dublincore.org/documents/2000/07/11/dcmes-qualifiers/) for each resource/file that is part of the map project.  This will require extending the relations that hydroshare supports to include "has part".  @hyi or @pkdash could do this when you get to it.
- [ ] Provide an option for users  to add the relation "Part of" to resources included in the map project.  This has to be an option as you may not have write privileges on the resource being included, and may also not want to change the resource being included if the map project is temporary. 
- [x] Let a user manage where files that are uploaded are saved.  I suggest they be saved as part of the map project resource in HydroShare (taking advantage of the functionality to have individual files that are part of any resource be part of the map project).  Right now it is unclear where  a file uploaded is saved.
- [ ] Identify resources/files that are part of the map project in the json file by their unique HydroShare GUIDs perhaps suffixed by filename (e.g. GUID/data/contents/filename.tif) when referencing a specific file.  (As currently implemented I could not see in the json map project file where the specific resources in HydroShare are referenced.  Names of geoserver layers seem to be mentioned, but these may not be persistent)
- [x] Limit the open with HydroShare GIS functionality to resources that have a file type that HydroShare GIS can handle (such as raster, shapefile or map project json right now).  At present open with HydroShare GIS is enabled for all generic resources but does not work if the generic resource is something else.  (This again gets back to file type specific functionality).

**Comment by mjstealey** [comment]
@shawncrawley is this still a thing?

**Comment by shawncrawley** [comment]
@mjstealey Yeah. I have been slowly getting through these checklist items.

**Comment by shawncrawley** [comment]
Some on this checklist require functionality from the hs_restclient that does not currently exist - namely, the ability to update a resource's metadata. That would be required if when saving (updating, not a "Save as" fresh save) the project, the resource's coverage is updated to reflect the map project's extents.

**Comment by danames** [comment]
Shawn, for the sake of progress, let's close the checklist issue and move
the remaining items to a new issue that we can link to the restclient
issues...

**Comment by dtarb** [comment]
I support closing this after transferring outstanding issues to a new issue.  Also please alert @alvacouch (REST API) and @pkdash (REST client) about additional needs to support these uses.

**Comment by gantian127** [comment]
@shawncrawley would you please close this issue if the testing works? Thanks

**Comment by shawncrawley** [comment]
I have moved any outstanding items to a new issue where more specific discussion can take place. This will now be closed.
