### ISSUE TITLE
login and password reset broken

### ISSUE THREAD

**Issue by mtpain** [hydroshare/hydroshare#1160]
I went to log in to hydroshare and got this error message in the link below after I entered my credentials. I thought maybe this was just a bad error message for a wrong password, so I requested a change of password, and when I clicked on the link to reset my password, I arrived at a page with the same error message.

https://www.dropbox.com/s/rpklwlg46tkor8m/Screenshot%202016-04-22%2017.35.23.png?dl=0

**Comment by hyi** [comment]
Closing since it should be working now.
