### ISSUE TITLE
All buttons (except for Edit button) do not work on beta

### ISSUE THREAD

**Issue by hyi** [hydroshare/hydroshare#1165]
Just found an issue with our latest develop branch in my local dev env as well as beta as currently deployed with the latest develop branch that all buttons do not work except for Edit button. Tooltips show up and all buttons are enabled as expected, but once click one of those buttons, nothing happens. @mauriel133 Any idea what could have caused this issue?

**Comment by mjstealey** [comment]
@hyi - That sounds like the issue that should have been resolved by this: https://github.com/hydroshare/hydroshare/pull/1130

Please verify that your local copy of `theme/templates/resource-landing-page/modals.html` has the **hydroshare_tags** in it.

If not, then that is the issue.

**Comment by hyi** [comment]
@mjstealey Yes, you are exactly right. Adding hydroshare_tags in it fixed the issue in my local dev env. Now I remembered I actually +1'ed this PR. Thanks for the reminder. I am closing this issue now.
