### ISSUE TITLE
Enhancements to discovery SOLR harvesting

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#1183]
@xuezhaokun @dtarb @rayi113 @jbradberry 

Now that real-time discovery harvesting works, we can start thinking about how it **should** work. I am putting this into a new ticket so that we can close the other one. 

Here are some immediate thoughts. First I propose the following easy performance fixes: 
1. don't index things at all that are neither public nor discoverable. 
2. add a resource to the index only when it becomes discoverable or public.  
3. delete a resource from the index when it goes from discoverable or public to private. 

**This will save an enormous amount of processing time.** Normally people don't make things public until they're presentable. Thus we can save a lot of time by not indexing things that people aren't finished with. 

Also, there are several other fixes that will slightly improve performance and make the code simpler. Notably: 
1. change the signal registration to invoke a **pre-delete action** rather than a post-delete action.  This will make managing deletes easier by giving us a complete view of what is going to be deleted rather than a partially deleted view like we have now with the delete "in progress" before we get the signal...!

**Comment by alvacouch** [comment]
I also **think** that it is possible to refine our signal registration to only receive updates for resources. I am not absolutely sure how, and this will take a little trial and error. 

Note that we should also omit some of the massive logger.debug() postings that we added to understand the signal system, for performance reasons.

**Comment by alvacouch** [comment]
If we do the above, I am not sure we even need queueing. The processing will only be slow if someone changes a public resource.

**Comment by hyi** [comment]
@alvacouch Not sure whether this issue can be covered by [#1187] or you want to do more enhancements for solr harvesting in this issue.

**Comment by jbradberry** [comment]
@alvacouch @hyi @dtarb @rayi113 I strongly suggest that Hydroshare does not need real-time updates of the search engine.  A queuing system where writes to Solr happen every 5 or 10 minutes would be, I think, reasonable and would cut down on the churn of writes to the Solr server.

That said, points 1 through 3 seem to be reasonable and correct criteria.

**Comment by dtarb** [comment]
From a user perspective I agree with @jbradberry.  Resources do not need to be immediately discoverable.   I do not have a basis for opining on whether it is more efficient to just add to Solr when the public action is taken, or have a queue do writes every 10 min.  That is an implementation detail I am happy to leave to the Discovery coders.

**Comment by pkdash** [comment]
@alvacouch @xuezhaokun  Should this be closed?

**Comment by alvacouch** [comment]
This has been addressed. (Users absolutely demanded real-time updates.)
