### ISSUE TITLE
Public and Publish button interface

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#1184]
It seems inconsistent to me that the "Publish" button in HydroShare is top right all the time on a resource landing page, but that the control to make a resource "Public" is only accessible in editing mode (buried).  It seem to me that the act of publishing (which is irreversible) needs to be more deliberate than just setting public access, so perhaps should be hidden a bit more and the ability to make public available without having to edit.

**Comment by mauriel133** [comment]
@dtarb, I agree with exposing more the ability to change the resource access. However, I think the act of publishing is already deliberate enough since the user is shown a popup window with a message and a checkbox to confirm before they can submit the action.

**Comment by dtarb** [comment]
@mauriel133 I am OK for you to just take my comment as point for consideration.  It you think things are good the way they are this could be closed.  This comment may have come up in a discussion with @christinab so it would be good to have her thoughts on this too, from a user experience perspective.

**Comment by hyi** [comment]
@christinab Can you chime in on this from a user experience perspective? If you think the way the user interface for publishing a resource is currently implemented is sufficient, please close this issue.

**Comment by mauriel133** [comment]
The button to share resources is now exposed to the top of the page.

**Comment by dtarb** [comment]
This is good.
