### ISSUE TITLE
Fewer clicks to add and remove keywords

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#1186]
When adding a subject keyword on a resource landing page it seems unnecessary to have to click add to add the keyword to the keyword list AND click save changes for this to take effect.  Clicking "Add" should be sufficient.  Similarly removing a keyword could be simplified to one click (with perhaps an undo to fix mistake) rather than having to "Save changes".  These are just part of an overall awkwardness in editing content that requires more clicks than seem necessary and is not natural.  This is probably low priority, but if there is an opportunity to simplify this editing we should.

**Comment by hyi** [comment]
@dtarb Can you verify and close this issue if it works now?

**Comment by dtarb** [comment]
This is fixed.
