### ISSUE TITLE
Tuning SOLR indexing for discovery

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#1187]
Most of #1164 and #1183 are addressed in #1152. One issue remains

Change the signal registration to invoke a pre-delete action rather than a post-delete action. This will make managing deletes easier by giving us a complete view of what is going to be deleted rather than a partially deleted view like we have now with the delete "in progress" before we get the signal...!

Right now, handle_delete is very much dependent on how delete_resource is implemented. This change decouples the two methods.

**Comment by pkdash** [comment]
@xuezhaokun Should this be closed?

**Comment by pkdash** [comment]
@alvacouch Should be closed?
