### ISSUE TITLE
Improve add author or contributer entry form

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#1190]
Better guidance and automated entry is needed for the fields in the Add Author or Add Contributor form in resource editing.  There should be a place to choose an existing HydroShare user (similar to manage access) that will fill in information from an identified users profile.  This should be the only way that  the field "HydroShare User Identifier (URL)" can be filled in, as right now it is unclear what to put here and this field is only meaningful for an existing HydroShare user.  Other fields automatically filled in should be editable in case information from the identified user's profile is incomplete or incorrect.  

I also suggest changing the name of the field "Homepage" to "Webpage" as technically the homepage is the top page on a website, not necessarily the page associated with an author/contributor.  Consistent with this I also suggest changing the label on the user profile contact information from "Website" to "Webpage".

**Comment by pkdash** [comment]
@mauriel133 Wondering if the new view function that I added, meets your need for adding existing users as creator/contributor?

**Comment by mauriel133** [comment]
Yes, it worked. I'm setting up the front end and will have a PR soon.

**Comment by hyi** [comment]
@dtarb Can you verify to see whether this issue is resolved?

**Comment by dtarb** [comment]
OK.  Closing.
