### ISSUE TITLE
Discovery on alpha not finding all authors

### ISSUE THREAD

**Issue by rayi113** [hydroshare/hydroshare#1192]
I am an author (but not lead author) on this HydroShare resource: https://alpha.hydroshare.org/resource/dc52e6aa93154521af08522de27ec276/ .  When I type my last name in the Search box a the top of the Discover page on alpha, it apparently finds my name as one of the authors (actually the Discover operation is finding my name associated with the resource in any supported searchable capacity).  Then I select "Show All" to reset the page & search parameters.  Then I go the "+Filter by Author" and select my name, but the search does not produce the aforementioned resource as a result even though I am an author.  I note that while I am an author on that resource, I don't appear to be a linked author, i.e. the lead author has not entered my HydroShare User Identifier (URL) when adding me as an author.

**Comment by alvacouch** [comment]
@xuezhaokun Check that all authors are indexed. If so, check that search phrase is appropriate for author......

**Comment by xuezhaokun** [comment]
@rayi113 @alvacouch For the "author" field, we just index the "first_creator" of the resource. Therefore, in the "Filter by Author" panel, it only lists all "lead authors". The reason you can find this resource by entering your last name in search box is that we index all "creators" in SOLR. Your name should be one of the creators for this resource. On the resource page, I am not why your name is not linked with your URL. @alvacouch For "Filter by Author", should we index all "creators" instead of only indexing "first_creators"?

**Comment by rayi113** [comment]
@xuezhaokun re:  am not why your name is not linked with your URL - per the screen cap below, one can enter an additional author to a HydroShare resource with, or without, a HydroShare User Identifier (URL) (i.e. HydroShare User Identifier not a required field in adding an author).  I believe this is properly acknowledge and credit co-authors of HydroShare resources who are not registered in HydroShare.  Cc:'ing @alvacouch .

![hs_add_author_screencap](https://cloud.githubusercontent.com/assets/2846017/14991825/4844e504-1131-11e6-8e71-48f065357412.png)

**Comment by alvacouch** [comment]
@xuezhaokun @rayi113 We should be indexing all authors whether or not they have HydroShare login names. Since this might cause duplication we'll need to be a bit careful; the author name is filled in even if the login is blank.

**Comment by horsburgh** [comment]
Agreed. In HydroShare, "Author" and "Creator" are the same thing.  All Authors/Creators should be indexed.

**Comment by xuezhaokun** [comment]
@alvacouch @rayi113  I did some tests on faceting on all "creators". I found two main problems. First, we can only facet on creator names with URLs. Second we should have a way to formalize the format of names when we list creators on resource page. If you take a look at the example given by @rayi113,  we could notice those creators' names are not their actual full names. For example, Ray Idaszak is written as  R. Idaszak in that resource. Then in our "Filter by Author" panel, we will have two options: one is " R. Idaszak" and the other is "Ray Idaszak", which could be confused for users. I think we should find a way to fix these creators' names in database first or we can change "Filter by Author" to "Filter by First Author" for now.

**Comment by rayi113** [comment]
@xuezhaokun @alvacouch @horsburgh @dtarb What if we alphabetize the "+Filter by Author" list by last name such that "Jane Smith" would show up as both "Smith, Jane" and "Smith, J."  The idea is to get the user nicely zero'ed in on what they're searching for even if an exact match must remain necessarily ambiguous (i.e. if there is a "Joe Smith" also listed as "Smith, J." ... i.e. it would be difficult to resolve that if they are not registered in HydroShare nor using a HydroShare User Identifier).

**Comment by xuezhaokun** [comment]
@rayi113 @alvacouch @horsburgh @dtarb I do not think this is something easy to resolve. "Creator" class is a subclass of "Party". Creator's name is stored in the name field of "Party". If we split the name based on "space" in names and group them by last names, we cannot know which short names and full names should be grouped together in "Filter by Author". For example, if we have full names "Jane Smith" and "James Smith", they could both have short name "J. Smith". If we have a creator named "J. Smith", should we assign it to "Jane Smith" or "James Smith"?

**Comment by horsburgh** [comment]
The FULL name should be stored in the resource metadata, and IF it is shortened, it should only be shortened for display on the resource landing page.  It should be indexed as the FULL name. We can't stop people from entering their FULL name as "J. Smith".  If they do that, just list them as "J. Smith".  But, if their full name is "James Smith", list the full name, don't shorten. 

If someone clicks on any name in the facet, they might get multiple results back if there is more than one person with the same FULL name in the system.

I think we should try splitting by space and reorganizing by last name.  It shouldn't be that hard to get a distinct list of full names.

**Comment by alvacouch** [comment]
@xuezhaokun My suggestion is to:
1. facet all creators. 
2. use the user fullname when a real HydroShare user exists. 
3. use the fullname in the metadata -- whatever that is -- if no HydroShare user exists. 
4. allow user full names to collide. This will happen. 
5. allow user full names to differ for the same user. This is inevitable. 

This solution: 
1. encourages recall. 
2. at the expense of precision. 
and we can't be responsible for what silliness is put into the creator field for a non-user.

**Comment by mjstealey** [comment]
open new issues based on existing functionality if required
