### ISSUE TITLE
On alpha, resource counter at bottom of Discover page remains "Showing 1 to 20 of 20 entries"

### ISSUE THREAD

**Issue by rayi113** [hydroshare/hydroshare#1194]
At the bottom of the Discover page on alpha, the resource counter remains "Showing 1 to 20 of 20 entries" regardless of where at.  

![hs_discover_example_01](https://cloud.githubusercontent.com/assets/2846017/14992204/e897afcc-1132-11e6-84cd-b1e616fafd6a.png)

Should this instead be, for example, "Showing 21 to 40 of 452 entries" ?

Or another option, this is how Amazon does it:

![hs_discover_example_02](https://cloud.githubusercontent.com/assets/2846017/14992211/f49216f0-1132-11e6-9a8f-4bf2b953f432.png)

**Comment by xuezhaokun** [comment]
@rayi113 This is an information provided by "DataTable" which is a library also used in "my-resource" page. I notice on "my-resource" page this information is just disabled. I disabled this information on Discover page as well for now. I will take a look whether the amazon pagination style is doable in haystack template.

**Comment by alvacouch** [comment]
This has been disabled. Please verify that this is acceptable.

**Comment by dtarb** [comment]
Closing.  This is now acceptable, but please keep open the opportunity to improve in the future.
