### ISSUE TITLE
SWATShare apps not working on alpha

### ISSUE THREAD

**Issue by vmmerwade** [hydroshare/hydroshare#1197]
@yirugi @lanzh @dtarb  The "open with" SWATShare apps that are working on www do not work on alpha for some reason. I am not sure if this is deploy blocking or not.

**Comment by yirugi** [comment]
@vmmerwade 'alpha' means 'alpha.hydroshare.org'?
When we fetch data from Hydroshare, we use 'www.hydroshare.org'. If a resource only stored in alpha, not www, then it would not work.

**Comment by hyi** [comment]
this appears to be an issue that only happens on alpha as commented above. Closing it.
