### ISSUE TITLE
Discover page sometimes shows the blank page Discovery

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#1203]
If I go to Discover, then click Next a few times at the bottom, then click on a name in a facet, I get the following page 
![capture](https://cloud.githubusercontent.com/assets/3456833/15111479/848c6f60-15a4-11e6-9718-d4ffc941bc41.JPG)

**Comment by xuezhaokun** [comment]
@dtarb I  am taking a look at it.

**Comment by xuezhaokun** [comment]
@dtarb fixed in PR #1204

**Comment by dtarb** [comment]
Thanks.
