### ISSUE TITLE
make pylint an effective substitute for human style review

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#1205]
@dtarb @mjstealey @hyi @pkdash 

As discussed yesterday, it is possible to tune pylint output so that it automatically reviews many quality aspects of code. At present, pylint is configured in a totally fascist mode; it enforces all of the PEP standards and overwhelms the programmer. It is possible to instruct pylint to concentrate on the important issues only. Then we can fix those issues in the code and any new issues will be caught as a result of a pull request. 

1. Things pylint should catch: 

  a. unused variables (these are often evidence of bugs) 
  b. unused imports (these can cause unexpected problems later)
  c. basic stylistic guidelines: no more than 1 blank line between code blocks, 2 blank lines between classes. 

2. Things that we could probably benefit from **not** having pylint catch: 

  a. inconsistent indent on continuation lines. This is a matter of personal taste. I find that I often strongly disagree with PEP on the most readable options. 
  b. stylistic differences in declaring dicts.  

The things in category 1 can lead to broken code. 

The things in category 2 influence readability, but cannot lead to broken code.

**Comment by dtarb** [comment]
I am supportive of having pylint configured to flag the first group of issues as soon as is non disruptively possible.

**Comment by jbradberry** [comment]
Commenting here to put this on my radar.

**Comment by jbradberry** [comment]
My thoughts:

Code flagged by the linter should not be reaching the stage of code
review.  The linter should be something that the programmer runs
along with the test suite, and deals with as they would a failing
test.

Looking through the output of pylint, I see a great many things in
here that I think _should_ be cleaned up.  Even many of these things
that can be described as personal taste issues aren't onerous to
deal with individually.  It's only once the style issues have
accumulated to reach the current state that the programmer becomes
overwhelmed by all of the flags being raised.

Proposal:

- Switch to flake8.  It's less strict, and can be configured to
  disable linting based on file path pattern matching.
- Disable linting for all packages
- As programmers work in some area, re-enable the package and do
  clean-up as part of the work.
- Much of the clean-up can be automated using autopep8 and autoflake
- Add linting as an additional command run in the ``run-tests`` script.
- Going forwards, consider _any_ flags raised by the linter as a
  build fail.  I think pylint's score concept perhaps tempts people
  into not caring about individual flags raised, leading to a
  build-up of issues.  flake8 is less strict, but flags are either
  raised or not, there is no threshold.

**Comment by hyi** [comment]
@jbradberry I am assigning this issue to you to put it on your plate initially. You can work with @mjstealey as needed and reassign as appropriate as the work progresses.

**Comment by jbradberry** [comment]
@hyi Sounds good.  I have a reasonable idea of how to do most of what I've outlined.

**Comment by jbradberry** [comment]
#1226 was merged on June 10, making it in to release 1.7.2 if I'm not mistaken.  I believe we can close this ticket.
