### ISSUE TITLE
fail on building development environment

### ISSUE THREAD

**Issue by xuezhaokun** [hydroshare/hydroshare#1206]
@mjstealey @alvacouch 
When I pulled the latest version from `develop` and merged it into my branch, I got this programming error:

> Exception Type: ProgrammingError at /
> Exception Value: column hs_core_genericresource.extra_metadata does not exist
> LINE 1: ...id", "hs_core_genericresource"."content_type_id", "hs_core_g...

And I retried to do `./hsctl rebuild`, it still gave me the same error from terminal.

**Comment by mjstealey** [comment]
@xuezhaokun - On merges you might want to allow the database to rebuild as well, otherwise you can run into migration issues.

```bash
$ ./hsctl rebuild --db
```

**Comment by xuezhaokun** [comment]
@mjstealey @alvacouch `./hsctl rebuild --db` solved the problem. Thanks!
