### ISSUE TITLE
Alpha Release Suggestions

### ISSUE THREAD

**Issue by shaunjl** [hydroshare/hydroshare#121]
It's strange that there is a placeholder for the Coverage metadata term. Not all have this, and it's optional so maybe it shouldn't have any.

I feel less strongly about this one, but the language one might benefit from being the same way. I just threw up some python code as my resource to play around and realized that it's not really language specific. So I put "No linguistic content: not applicable" but I donno maybe it shouldn't have one to start out with.

**Comment by mjstealey** [comment]
Requires discussion

**Comment by dtarb** [comment]
@shaunjl closing for now.  See new layout in 1.4 release candidate when it is deployed and re-raise if still a concern.
