### ISSUE TITLE
Map not displaying on www

### ISSUE THREAD

**Issue by mjstealey** [hydroshare/hydroshare#1210]
Ideas?

![screen shot 2016-05-12 at 4 19 03 pm](https://cloud.githubusercontent.com/assets/5332509/15229083/627e46a8-185d-11e6-9be8-38c9a701775e.png)

**Comment by xuezhaokun** [comment]
@mjstealey it seems the library stops working...

**Comment by mauriel133** [comment]
The following script is not loading:
https://google-maps-utility-library-v3.googlecode.com/svn/tags/keydragzoom/2.0.8/src/keydragzoom_packed.js

**Comment by xuezhaokun** [comment]
It seems all google map utility libraries on svn are broken.
https://code.google.com/p/google-maps-utility-library-v3/wiki/Libraries

**Comment by xuezhaokun** [comment]
Should we disable key draggable feature for now?

**Comment by mauriel133** [comment]
Another option would be to serve the script ourselves.

**Comment by xuezhaokun** [comment]
@mauriel133 But we cannot get the source code now.

**Comment by mjstealey** [comment]
@xuezhaokun, @mauriel133 - Once the google map utilities are back online we should grab a copy and serve what we require locally.

Might be a good time to see what else we depend on third party's for and migrate to using local copies if at all possible.

**Comment by xuezhaokun** [comment]
@mjstealey agree. I just disabled key draggable feature on my local, but the markers cluster library still has some feature depends on Google `svn`. We need to wait for Google `svn` back.
![screenshot_2016-05-12_16-51-38](https://cloud.githubusercontent.com/assets/6678333/15230046/dba27460-1861-11e6-8f45-df73a34d4836.png)

**Comment by xuezhaokun** [comment]
@mjstealey @mauriel133 Made a possible solution in PR #1211
