### ISSUE TITLE
Can I really delete a public resource?

### ISSUE THREAD

**Issue by ChristinaB** [hydroshare/hydroshare#1212]
This resource is public and someone else than me is the author. 
https://www.hydroshare.org/resource/99a170544d2741ac983a1f25b2f38451/

When I click on edit, it gives me a trash can and edit permissions. HydroSahre let's me delete it and it's not mine!!
Aaaaahhhhhh!

**Comment by mjstealey** [comment]
> When I click on edit, it gives me a trash can and edit permissions

Out of curiosity, does it also give you the "manage access" option? (looks like a small blue lock)
It's possible that you may have been granted edit or owner access by the original author of the resource which would enable the options you mention.

**Comment by dtarb** [comment]
@ChristinaB, I too am curious as to what you are seeing.  The fact that you see the edit button means you must have edit permissions that the owner assigned.  You should be seeing the trash can next to files because editing allows you to delete files.  You should not be seeing the trash can top right next to the resource as a whole because editing should not allow you to delete the entire resource.  If you were an owner you would be able to do everything, but when I look at that resource it does not show you as an owner.  Feel free to paste in screen shots of what you are seeing so we can explain or look into what is going on.

**Comment by hyi** [comment]
@ChristinaB When you get a chance, can you verify whether this is still an issue or not? Please refer to comments above from @dtarb and @mjstealey while you are verifying. If it is not an issue any more, please close this issue. If it is still an issue, please add a bit more details so that we can reproduce and look into the issue. Thanks.

**Comment by ChristinaB** [comment]
This is still an issue. 
I am not an  owner of Turbidity and Sediment Monitoring
https://www.hydroshare.org/resource/99a170544d2741ac983a1f25b2f38451/
This is a generic public shareable resource. 
I can click on it to edit.  I can see the contents and am offered a red trash can.
I can click on the trash can and can delete. 
You should be able to test this out as well and see the issue, since it is public.  

Thanks for your help and work!
C

**Comment by mjstealey** [comment]
> I can click on it to edit.

@ChristinaB - Do you also see an icon that looks like this?
<img width="169" alt="screen shot 2016-06-02 at 12 45 57 pm" src="https://cloud.githubusercontent.com/assets/5332509/15753242/10e119a6-28c0-11e6-8395-f3dc4af8ebb9.png">

If so, please click it and post the corresponding dialogue box to this thread.

**Comment by hyi** [comment]
@ChristinaB Weird, I only have view privilege over this resource as expected, so I don't see edit or delete icons at all on resource landing page for this resource. Not sure why you can edit and delete this resource even when you are not listed as the owner. As @mjstealey suggested above, pasting the dialog box to this thread would be a great help to see the access control settings for this resource.

**Comment by ChristinaB** [comment]
Ok. I do see the lock so it seems I was given additional permissions. How
do I know my permissions for a particular resource.  I wasn't emailed this
info. If I "can edit" then I can delete?
Thanks! Mystery is getting closer to solved.
The author is out of the office this week, and she may not even remember
what permissions she gave me when she invited me to the resource.

I think the fundamental concern remains that if I am not the owner or
author I should not be able to delete it, even if I can edit. Right?

Christina

On Thursday, June 2, 2016, Hong Yi <notifications@github.com> wrote:

> @ChristinaB <https://github.com/ChristinaB> Weird, I only have view
> privilege over this resource as expected, so I don't see edit or delete
> icons at all on resource landing page for this resource. Not sure why you
> can edit and delete this resource even when you are not listed as the
> owner. As @mjstealey <https://github.com/mjstealey> suggested above,
> pasting the dialog box to this thread would be a great help to see the
> access control settings for this resource.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/hydroshare/hydroshare/issues/1212#issuecomment-223351925>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AD6wUfx78x2kpjvUsxjYRhhPCsBvaJPtks5qHwmhgaJpZM4IedsP>
> .
>


-- 
Christina Bandaragoda
Civil & Environmental Engineering
University of Washington

**Comment by mjstealey** [comment]
> How do I know my permissions for a particular resource

@ChristinaB - If you click that icon it should pop-up a dialogue with the kind of access that has been granted to you and/or other users.

Example:
<img width="593" alt="screen shot 2016-06-02 at 1 36 14 pm" src="https://cloud.githubusercontent.com/assets/5332509/15754647/25c96114-28c7-11e6-8d60-433e362547a5.png">

**Comment by hyi** [comment]
@ChristinaB Right, if you are only given a edit permission, you will not be able to delete it and should not see the trashcan icon. As detailed by @mjstealey above, if you paste the popup dialog after you click on the "lock" icon, it should show who has access to this resource with what kind of permission.

**Comment by ChristinaB** [comment]
The pop says I can edit. (Attached) But I am not owner or author.
(Attached)  I can delete it.

So my current understanding of the issue is that I am only given owner
permission but i should not be able to delete it.

Maybe the design is that if I can edit then I can delete?
C

On Thursday, June 2, 2016, Hong Yi <notifications@github.com> wrote:

> @ChristinaB <https://github.com/ChristinaB> Right, if you are only given
> a edit permission, you will not be able to delete it and should not see the
> trashcan icon. As detailed by @mjstealey <https://github.com/mjstealey>
> above, if you paste the popup dialog after you click on the "lock" icon, it
> should show who has access to this resource with what kind of permission.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/hydroshare/hydroshare/issues/1212#issuecomment-223365796>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AD6wUQYxKi57KB3IWbevA__3aKGW4nRcks5qHxVTgaJpZM4IedsP>
> .
>


-- 
Christina Bandaragoda
Civil & Environmental Engineering
University of Washington

**Comment by mjstealey** [comment]
> The pop says I can edit. (Attached) But I am not owner or author.
> (Attached)  I can delete it.

Looks like you are responding via email and Github does not post your attached images to the thread. You can follow the "view it on Github" link at the bottom of the email to add screenshots to your post.

Access options are:
- Can view - view only
- Can edit - modify content, cannot delete
- Is owner - all powerful do whatever you want

<img width="162" alt="screen shot 2016-06-02 at 2 03 00 pm" src="https://cloud.githubusercontent.com/assets/5332509/15755479/fc88b102-28ca-11e6-95f1-ba3c42161d3b.png">

If you have "Is owner", then you should be listed as an "Owner" on the landing page.
Some of what you're observing may be an artifact from release 1.6.10. 
A new release (1.7.0) is landing before COB today.
Will be interesting to see if anything changes once the new release is published.

**Comment by ChristinaB** [comment]
Hi Michael and Hong,
It seems that the issue is still there and we can summarize it as "someone with 'can edit' permission should not be allowed to permanently delete a resource.  Correct? is that the design?  If you want people who 'can edit' to be able to delete resources, then there is no issue.  

Do you want me to make a test resource as an owner and give you edit permissions so you can test it?
Christina

**Comment by hyi** [comment]
@ChristinaB Correct, only owners can delete a resource. It'd be very useful to get to the bottom of the issue if you can make a test resource as an owner and give us the edit permissions so we can look into it.

**Comment by mjstealey** [comment]
@ChristinaB, @hyi - Created a test generic resource in which you both were given "can edit" rights.
Please try to break the resource and report back if anything goes awry.

[https://www.hydroshare.org/resource/648be70b3e5649ec960b4825cc4e6712/](https://www.hydroshare.org/resource/648be70b3e5649ec960b4825cc4e6712/)

![screen shot 2016-06-06 at 9 20 19 pm](https://cloud.githubusercontent.com/assets/5332509/15843043/b3a877e6-2c2c-11e6-8090-c62f3ca5e61c.png)

**Comment by hyi** [comment]
@mjstealey @ChristinaB I tested this resource and I don't see the trashcan icon that allows me to delete this resource since I only have edit permission to this resource. Everything works as expected based on my testing on this resource. @ChristinaB Can you test also and let me know whether you see any unexpected behavior?

**Comment by hyi** [comment]
@ChristinaB Just to clarify, I see the trashcan for deleting a content file included in the resource, but I don't see the trashcan that allows me to delete the whole resource. Deleting a content file is expected for a user with edit permission as part of editing content for the resource, but only owners are allowed to delete the whole resource.

**Comment by ChristinaB** [comment]
I was not expecting to delete CONTENT of a resource. No, I can not delete the resource.
