### ISSUE TITLE
Report Inappropriate Comment

### ISSUE THREAD

**Issue by ChristinaB** [hydroshare/hydroshare#1213]
Provide process for users to report inappropriate comments and allow owners/admins? to delete.

**Comment by hyi** [comment]
A user who makes a comment can delete or edit it later. No one else can edit a comment, except system administrator who can delete an inappropriate comment. - copying comments for the duplicate issue [#228] which was closed. This issue will be used to keep track of the problem.

**Comment by dtarb** [comment]
It seems that we need the following functionality

- The commentor can delete their own comment
- If an owner or anyone else does not like that comment they can not delete it but they can comment back
- If a comment is inappropriate a user (any user) can click a "report inappropriate" button that administrators will then review and act on.

**Comment by ChristinaB** [comment]
Please let me know if/when you would like me to test this. Thanks!

**Comment by cuahsimarko** [comment]
Related Issue: Edit/Delete Comments https://github.com/hydroshare/hydroshare/issues/1369

**Comment by cuahsimarko** [comment]
Related: Report this Resource https://github.com/hydroshare/hydroshare/issues/2489

**Comment by eclark-cuahsi** [comment]
closing per discussion in backlog review meeting on 6/9/22. resource owners can delete comments if needed, and comments can also be reported to help@hydroshare.org. additional functionality to report comments will not be prioritized at this time as the comments are not a highly used feature.
