### ISSUE TITLE
Comment email is unclear - needs to be sent from HydroShare Support

### ISSUE THREAD

**Issue by ChristinaB** [hydroshare/hydroshare#1214]
I think it's great to get emails when comments happen, but not when I am the one who makes the comment, I already know I made it.  Only the authors should receive notification.  
when it comes from someone else rather than themselves.  

I was confused by the email sender 'Support'  - New Comment by....   it should say 'HydroShare Support' otherwise it will junk up inboxes.  

Wonderful! Amazing! I love HydroShare!  Go Team!

**Comment by hyi** [comment]
@dtarb @ChristinaB brought up a good point: do we want to send the commenter the email? I seem to recall we decided to email both the commenter and the resource owners the comments at the time, but do see @ChristinaB has a point here. @dtarb want to confirm with you that it is better we don't send the commenter the notification email as @ChristinaB suggested before changing the behavior.

**Comment by dtarb** [comment]
I think that the email to the commenter should be retained.  It serves as a record for the commenter, of the comment being written and confirmation that it occurred.  It can be easily deleted if they want.  It also provides a check in case someone else has broken into your account and started commenting in your name, then you learn about it.

I agree that it would be better to come from 'HydroShare Support'

**Comment by ChristinaB** [comment]
This may be personal opinion, but I would consider making it Hydroshare that users see in the inbox versus lower case hydroshare.   In lower case I think it is spam automatically, even though I know it's Hydroshare!

**Comment by hyi** [comment]
@ChristinaB Could you verify on beta.hydroshare.org that comment email subject now indicates HydroShare support? We are still sending comment emails to commenter as determined in the thread above, just add HydroShare support in the email subject that it comes from HydroShare support. Let me know further issues if any. Otherwise, you can close this issue. Thanks.

**Comment by ChristinaB** [comment]
thanks Hong.  I'm closing this issue now, but as a note, I wonder if an email about a comment should come from Hydroshare Comments:  blah blah...  but we can stick with 'support' as a standard.

**Comment by dtarb** [comment]
@ChristinaB you are in charge of user experience and project messaging.  If you think comment messages are better coming from "HydroShare Comments", or even from the user making the comment, you should say specifically what you suggest based on an overall clear experience for the user strategy.  If it turns out to be too hard to implement, then it may get deferred, but implementing most of the emails so far has been easy (Hong may correct me), but agreeing what they should say is where we have lacked someone considering the tenor of the messages holistically.

**Comment by ChristinaB** [comment]
OK, holistically speaking, who can users expect to hear from in their inbox?   Let's consider:
Hydroshare Updates - emails about new functionality and news
Hydroshare Comments - emails when someone comments on the user's resource
Hydroshare Help - email from another Hydroshare user when another needs their help ( future functionality of a Help resource or linking up users to help each other via the help page)
Hydroshare Support  - if they log a bug or have an issue outside of Github about HS software issues
Hydroshare Events - like a calendar or news update on when users have events they want the community to know about (AGU, workshops, hackathons, etc.)

Are there others we can imagine? Is this the way we want it to go? Or should everything just be from 'Hydroshare' plain and simple? 

I like denoting the message content based on who the Hydroshare email is from. Any other opinions?

**Comment by hyi** [comment]
@ChristinaB I like the HydroShare categories you came up with, but since all emails in HydroShare came from support@hydroshare.org, having ```[HydroShare Support]``` in the subject seem to also align with standard indicating/denoting where the email message came from, so this may be simple and acceptable also. @dtarb

**Comment by horsburgh** [comment]
@ChristinaB - don't forget about notifications for group membership requests and approvals. And, if we ever have group forums or conversations, there might be notifications of other things in groups as well. 

Other **_potential_** social messaging down the line (but not implemented in any way yet):
* User follows another user
* User follows a group
* User shares a resource with a user
* User shares a resource with a group
* System alerts user of views, downloads, citations, or other use statistics

And, if we implement all of this - we need to allow users to control what emails/notifications they want to receive so we don't over-spam.
