### ISSUE TITLE
Lower the barrier for creating new specific Model Instance resource types

### ISSUE THREAD

**Issue by mohamedmorsy** [hydroshare/hydroshare#1216]
Since there are so many hydrological models, and since currently it is very difficult to create a specific model instance resource type, we would like to do an easy methodology to implement a new specific Model Instance resource type. This way a HydroShare user could create a specific model instance type for their specific model in a simplified way. This could be implemented as the following:
1. The user submit an Excel file that includes the required metadata elements for the new resource type based on defined Control Vocabulary through HydroShare. The user should indicate which of the metadata elements are repeatable and which are non repeatable.
2. This Excel sheet should be revised by a HS team member, then after the approval, it should be implemented automatically.

**Comment by pkdash** [comment]
@mohamedmorsy Would like to discuss this issue with you on HipChat.

**Comment by mohamedmorsy** [comment]
@pkdash Sure. We can do that.

**Comment by alvacouch** [comment]
@mohamedmorsy @pkdash 
Could we delve into more details about this? 
Could you give a sample spreadsheet and/or append it to this thread?

**Comment by pkdash** [comment]
@alvacouch From my discussion with @mohamedmorsy it seems developers like @mohamedmorsy find it most difficult as it relates to client side coding for developing a new resource type. I am not sure how we can make that easier.

**Comment by alvacouch** [comment]
@pkdash @mohamedmorsy Let me think about this a bit. Is the issue that there is substantive client-side code that it is necessary to write in order to fetch a specific metadata attribute on the client? Or is it that the catalog of available attributes is difficult to manage and remember?

**Comment by pkdash** [comment]
@alvacouch @mohamedmorsy  I don't think the difficulty is with fetching a metadata attribute. That's very simple to do. The difficulty is creating the form with necessary css and js for proper layout of metadata elements on the web page, dealing with repeatable metadata elements and making the UI elements responsive via js code. Now as I think about it, I think it can be made easier if snippets consisting of html, css and js are developed (this is how tethys platform does) which developers who are not comfortable writing client-side can easily glue together to create necessary UI functionalities.

**Comment by alvacouch** [comment]
@pkdash Where is the client? In Tethys? Elsewhere?

**Comment by pkdash** [comment]
@alvacouch In Tethys

**Comment by Castronova** [comment]
No longer relevant
