### ISSUE TITLE
Time Series: Add support for uploading ODM2 SQLite file with multiple timeseries

### ISSUE THREAD

**Issue by pkdash** [hydroshare/hydroshare#1220]
The timeseries resource currently supports SQLite file upload with only one timeseries in it. We need to support uploading SQLite file with multiple timeseries. 

This would require changes to the extended metadata storage models in order to relate the set of extended metadata elements to a specific timeseries. Currently we have only one set of extended metadata elements for a timeseries resource. With this change we will have multiple set of extended metadata elements one for each timeseries in the uploaded SQLite file.

As part of this issue, edited metadata also needs to be written back to the SQLite file. Instead of automatically updating the SQLite file each time the user updates any of the metadata elements, it would be better to provide an option for the user to update the file at the end of all metadata updates.

**Comment by pkdash** [comment]
@horsburgh I think I should asks the questions here so it would be easier for me track. 

1. How we should be encoding extended metadata for each series? I assume there has to be a parent level 'series' element.
2. It seems from the example SQLite files, not all metadata elements will be repeated for each timeseries. For example, there can be one 'Site' element but more than one 'Variable' element representing each timeseries for a single site. Is this assumption correct?

**Comment by horsburgh** [comment]
@pkdash - answers to your questions below:

> How we should be encoding extended metadata for each series? I assume there has to be a parent level 'series' element.

I think the right thing to do is to embed each time series within a "timeSeriesResult" element in the resourcemetadata.xml document and identify each one with the ResultUUID from the SQLite Results table.  This requires a little reorganization of a few elements we already had in the file, and addition of a couple of others that are now necessary because we will now be allowing multiple time series (and potentially multiple sites) in a single resource. See below for an example of these modifications for a single time series.  If there were multiple time series, each one would be described within a separate "timeSeriesResult" element in resourcemetadata.xml.

```xml
<rdf:RDF xmlns:dcterms="http://purl.org/dc/terms/" xmlns:hsterms="http://hydroshare.org/terms/" xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:rdfs1="http://www.w3.org/2001/01/rdf-schema#" xmlns:dc="http://purl.org/dc/elements/1.1/">
  <rdf:Description rdf:about="http://www.hydroshare.org/resource/1a25b11fa1354773b6edb9495e754f4e">
    <dc:title>Water Temperature in the Little Bear River at Mendon Road near Mendon, UT</dc:title>
    <dc:type rdf:resource="http://www.hydroshare.org/terms/TimeSeriesResource"/>
    <dc:description>
      <rdf:Description>
        <dcterms:abstract>This dataset contains observations of water temperature in the Little Bear River at Mendon Road near Mendon, UT. Data were recorded every 30 minutes and represent the average values over the preceeding time interval. The values were recorded using a HydroLab MS5 multi-parameter water quality sonde connected to a Campbell Scientific datalogger. Values represent quality controlled data that have undergone quality control to remove obviously bad data.</dcterms:abstract>
      </rdf:Description>
    </dc:description>
    <dc:creator>
      <rdf:Description rdf:about="http://www.hydroshare.org/user/10/">
        <hsterms:name>Jeff Horsburgh</hsterms:name>
        <hsterms:creatorOrder>1</hsterms:creatorOrder>
        <hsterms:organization>Utah State University</hsterms:organization>
        <hsterms:email>jeff.horsburgh@usu.edu</hsterms:email>
        <hsterms:address>8200 Old Main Hill, Logan, UT 84322-8200</hsterms:address>
        <hsterms:phone rdf:resource="tel:(435) 797-2946"/>
        <hsterms:homepage rdf:resource="http://jeffh.usu.edu/"/>
      </rdf:Description>
    </dc:creator>
    <dc:creator>
      <rdf:Description>
        <hsterms:name>Amber Jones</hsterms:name>
        <hsterms:creatorOrder>2</hsterms:creatorOrder>
        <hsterms:organization>Utah State University</hsterms:organization>
        <hsterms:email>amber.jones@usu.edu</hsterms:email>
        <hsterms:address>8200 Old Main Hill, Logan, UT 84322</hsterms:address>
        <hsterms:phone rdf:resource="tel:(435) 797-7147"/>
      </rdf:Description>
    </dc:creator>
    <dc:coverage>
      <dcterms:period>
        <rdf:value>name=None; start=2007-08-16T00:00:00; end=2009-01-16T00:00:00; scheme=W3C-DTF</rdf:value>
      </dcterms:period>
    </dc:coverage>
    <dc:coverage>
      <dcterms:point>
        <rdf:value>name=Little Bear River at Mendon Road near Mendon, UT; east=-111.946402; north=41.718473; units=Decimal degrees; elevation=None; zunits=None; projection=WGS 84 EPSG:4326</rdf:value>
      </dcterms:point>
    </dc:coverage>
    <dc:date>
      <dcterms:created>
        <rdf:value>2015-06-06T03:57:35.028903+00:00</rdf:value>
      </dcterms:created>
    </dc:date>
    <dc:date>
      <dcterms:modified>
        <rdf:value>2015-06-06T04:25:06.064823+00:00</rdf:value>
      </dcterms:modified>
    </dc:date>
    <dc:format>application/sqlite</dc:format>
    <dc:identifier>
      <rdf:Description>
        <hsterms:hydroShareIdentifier>http://www.hydroshare.org/resource/1a25b11fa1354773b6edb9495e754f4e</hsterms:hydroShareIdentifier>
      </rdf:Description>
    </dc:identifier>
    <dc:language>eng</dc:language>
    <dc:rights>
      <rdf:Description>
        <hsterms:rightsStatement>This resource is shared under the Creative Commons Attribution CC BY.</hsterms:rightsStatement>
        <hsterms:URL rdf:resource="http://creativecommons.org/licenses/by/4.0/"/>
      </rdf:Description>
    </dc:rights>
    <dc:subject>Temperature</dc:subject>
    <dc:subject>Water</dc:subject>
    <dc:subject>Water quality</dc:subject>
    <dc:subject>Little Bear River</dc:subject>
    <dc:subject>Utah</dc:subject>
    <hsterms:timeSeriesResult>
      <rdf:Description>
        <hsterms:timeSeriesResultUUID>0a160073-0c00-11e5-a472-6c4008bf018e</hsterms:timeSeriesResultUUID>
        <hsterms:Status>Ongoing</hsterms:Status>
        <hsterms:SampleMedium>Surface Water</hsterms:SampleMedium>
        <hsterms:ValueCount>24206</hsterms:ValueCount>
        <hsterms:AggregationStatistic>Average</hsterms:AggregationStatistic>
        <hsterms:site>
          <rdf:Description>
            <hsterms:SiteCode>USU-LBR-Mendon</hsterms:SiteCode>
            <hsterms:SiteName>Little Bear River at Mendon Road near Mendon, Utah</hsterms:SiteName>
            <hsterms:Latitude>41.718473</hsterms:Latitude>
            <hsterms:Longitude>-111.946402</hsterms:Longitude>
            <hsterms:SRSName>Unknown</hsterms:SRSName>
            <hsterms:Elevation_m>1345</hsterms:Elevation_m>
            <hsterms:ElevationDatum>NGVD29</hsterms:ElevationDatum>
            <hsterms:SiteType>10</hsterms:SiteType>
          </rdf:Description>
        </hsterms:site>
        <hsterms:variable>
          <rdf:Description>
            <hsterms:VariableCode>USU36</hsterms:VariableCode>
            <hsterms:VariableName>Temperature</hsterms:VariableName>
            <hsterms:VariableType>Water Quality</hsterms:VariableType>
            <hsterms:NoDataValue>-9999</hsterms:NoDataValue>
            <hsterms:Speciation>Not Applicable</hsterms:Speciation>
          </rdf:Description>
        </hsterms:variable>
        <hsterms:units>
          <rdf:Description>
            <hsterms:UnitsType>Temperature</hsterms:UnitsType>
            <hsterms:UnitsName>degree celsius</hsterms:UnitsName>
            <hsterms:UnitsAbbreviation>degC</hsterms:UnitsAbbreviation>
          </rdf:Description>
        </hsterms:units>
        <hsterms:method>
          <rdf:Description>
            <hsterms:MethodCode>28</hsterms:MethodCode>
            <hsterms:MethodName>Quality Control Level 1 Data Series created from raw QC Level 0 data using ODM Tools.</hsterms:MethodName>
            <hsterms:MethodType>Derivation</hsterms:MethodType>
            <hsterms:MethodDescription>Originally measured using a Hydrolab MS5 multi-parameter water quality sonde.  Data have been quality controlled.</hsterms:MethodDescription>
          </rdf:Description>
        </hsterms:method>
        <hsterms:processingLevel>
          <rdf:Description>
            <hsterms:ProcessingLevelCode>1</hsterms:ProcessingLevelCode>
            <hsterms:Definition>Quality controlled data</hsterms:Definition>
            <hsterms:Explanation>Quality controlled data that have passed quality assurance procedures such as routine estimation of timing and sensor calibration or visual inspection and removal of obvious errors. An example is USGS published streamflow records following parsing through USGS quality control procedures.</hsterms:Explanation>
          </rdf:Description>
        </hsterms:processingLevel>
      </rdf:Description>
    </hsterms:timeSeriesResult>
  </rdf:Description>
  <rdf:Description rdf:about="http://www.hydroshare.org/terms/TimeSeriesResource">
    <rdfs1:label>Time Series</rdfs1:label>
    <rdfs1:isDefinedBy>http://www.hydroshare.org/terms</rdfs1:isDefinedBy>
  </rdf:Description>
</rdf:RDF>
```

> It seems from the example SQLite files, not all metadata elements will be repeated for each timeseries. For example, there can be one 'Site' element but more than one 'Variable' element representing each timeseries for a single site. Is this assumption correct?

The SQLite file is relational and normalized.  So, it is possible to have one site "record" in the Sites table of the SQLite database at which multiple time series have been collected. Each time series may be for a different variable (e.g., temperature, pH, dissolved oxygen, specific conductance, etc.). The ProcessingLevel may vary from series to series. For the resourcemetadata.xml document, I suggest encoding all time series specific metadata for a time series within its "timeSeriesResult" element. If two time series in a SQLite file share the same site, variable, method, or processing level, that information will get repeated in the resourcemetadata.xml file. In other words, each time series will have its own "timeSeriesResult" element that is a complete description of the site, variable, method, units, processinglevel, etc. for that time series.

> If there are multiple sites in the SQLite db, then I assume multiple 'coverage' elements (core metadata) need to be created. Currently we allow only maximum of 2 coverage elements (one of type 'period' and the other one can be either 'point' or 'box').

Let's do one coverage element.  If there is a single site in the SQLite file, you can assume that the coverage is a point with the same coordinates as the site.  If there are multiple sites in the SQLite database, you should calculate the max and min latitude and longitude of the site coordinates in the SQLite file and do a box coverage that uses these min and max coordinates. Given this, I think it is necessary to add the latitude and longitude coordinates of the site to the description of the site within the "timeSeriesResult" element. We did not have these there before because we were assuming that there was only one site/series and so the site coordinates were covered by the "coverage" element.

**Comment by pkdash** [comment]
@horsburgh Another question related to 'keywords'. We generate keywords metadata elements from the Variables table. If there are more than one variable, do we need to track keywords by variable? If we don't track keywords by variable, then we won't be able to write the edited keywords back to the Variable table.

**Comment by horsburgh** [comment]
@pkdash - Extracting the variable names from the ODM2 database as keywords for the resource is something we should do as a convenience upon uploading an ODM2 time series database to HydroShare.  But, I wouldn't go the other direction.  A user could add keywords to the resource that are not variables (e.g., "Utah", "Little Bear River", etc.).  So, I wouldn't try to put keywords back into the database.  I realize that if they edit the variable names in the database using the metadata editing capabilities this will not update the keywords for the resource.  I think this is fine - the user will have to fix that if they want to.

**Comment by pkdash** [comment]
@horsburgh Need to know what editing (which CRUD operations) operations are allowed for each of the following timeseries specific metadata elements. Also need to know which table(s) in SQLite file needs to be updated as part of editing each of these elements.

Site
Variable
Method
Processing_Level
Timeseries_Result

**Comment by horsburgh** [comment]
@pkdash - Here's the tables that will be touched in the ODM2 database when editing:

**Site:**
- Sites
- SamplingFeatures

**Variable:**
- Variables

**Method:**
- Methods

**ProcessingLevel:**
- ProcessingLevels

**TimeSeriesResult:**
- Results
- Units
- TimeSeriesResults

**NOTE:** For all of the fields in these tables that are CVs (e.g., SamplingFeatureTypeCV, VariableTypeCV, VariableNameCV, etc.) users should be picking terms from a drop down that is provided by querying the corresponding CV table in the ODM2 schema. If the term they want to use isn't in the list, we should allow them to add their own terms.

**Comment by pkdash** [comment]
@horsburgh I have implemented initial code to extract metadata from SQLite file with one ore more timeseries. I used the 3 test SQLite files you provided to test my metadata extraction code. The xml for the extended metadata for timeseries is also generated as per the sample you have provided above.  I still have to work on editing of extended metadata. At this point if you would like I can deploy this work for you to test metadata extraction and xml generation. However,  you won't be able to test metadata editing.

**Comment by horsburgh** [comment]
@pkdash - I can take a look if you want me to.

**Comment by pkdash** [comment]
@horsburgh How should we be displaying the resource specific metadata? Should it be by each timeseries?

**Comment by horsburgh** [comment]
@pkdash - yes.  Right now we've got it laid out on the "Resource Specific" tab for a single time series.  We just need the ability to flip through all of the time series.  The metadata display for each can be the same, we just need some way of selecting which one to look at.  You could list them one after another and just scroll the whole thing, but that would get really long (especially if there was a large number of time series).  Another option would be a drop down where you could select a time series whose metadata you want to display.  A third option would be to display all of the time series as a collapsed list in the "Resource Specific" tab and then have each one as a link that would expand a panel containing the metadata for that time series.

**Comment by pkdash** [comment]
@horsburgh For each time series I only keep track of the 'ResultUUID' to identify a specific timeseries. I am not sure if the user would like to select a timeseries by this UUID to see the corresponding metadata. I will do some basic layout for displaying/editing of metadata. Then we should ask @mauriel133 to work on the desired layout for displaying/editing timeseries metadata.

**Comment by horsburgh** [comment]
@pkdash - Yes, the ResultUUID is going to uniquely identify each one and should be used as the key.  But, one could create a label for each one that is a concatenation of a few of the metadata elements that should serve to let the user differentiate between them in a list (say in a table or in a drop down list).

**Comment by pkdash** [comment]
@horsburgh I have deployed my current work at riverdev.hydroshare.org. I think the best way to test if the metadata extraction for multiseries SQLite file upload works is to see the resourcemetadata.xml file. You can also see all the resource specific metadata  on resource landing page both in view and edit mode. But the elements are not yet well organized on the landing page.

**Comment by pkdash** [comment]
> NOTE: For all of the fields in these tables that are CVs (e.g., SamplingFeatureTypeCV, VariableTypeCV, VariableNameCV, etc.) users should be picking terms from a drop down that is provided by querying the corresponding CV table in the ODM2 schema. **If the term they want to use isn't in the list, we should allow them to add their own terms**.

If we allow the user to add their own terms, are those terms need to written to the appropriate CV table in the SQLite file?

**Comment by horsburgh** [comment]
@pkdash - technically, yes, we should do that.  SQLite doesn't have to enforce referential integrity of tables in the database, but the most complete and correct option would be to add it to the CV table and then add it to the table where it is used.  The two required fields in the CV tables are "term" and "name".  The "term" is a URI friendly version of the term using Camel Casing, and the name is the term as you would expect to see it in a sentence.   See examples for all vocabularies at http://vocabulary.odm2.org.

**Comment by pkdash** [comment]
> Yes, the ResultUUID is going to uniquely identify each one and should be used as the key. But, one could create a label for each one that is a concatenation of a few of the metadata elements that should serve to let the user differentiate between them in a list (say in a table or in a drop down list).

@horsburgh  -  What metadata elements should I use for creating a label for each timeseries?

**Comment by pkdash** [comment]
@hyi As part of the functionality in this issue, the uploaded SQLite file needs to be updated when the user updates the timeseries specific metadata. I assume this would require copying the SQLite from irods over to Django to update this file. Then delete the same file from irods and add the updated file as new file to the resource. There may be some performance issue with this strategy. If I have to go this route, then I would probably not update the SQLite file every time the user updates metadata. Rather indicate to the user that the SQLite file needs to be updated and provide a button on the UI to do so. 

It would be ideal if I don't have to copy the file over to the Django in order to write to the file. Is that possible?

**Comment by hyi** [comment]
@pkdash If I understand this correctly, I don't think copying SQLite file to Django is needed in order to update SQLite file. You can just call a function in irods storage class to update file directly if you already have updated file locally ready to iput to iRODS backend storage. However, if you need to retrieve the original file in order to update it, you will have to retrieve it first. All these read (if needed) from and write to iRODS storage will be done via icommands which will leverage parallel transfer, so the performance will not be too bad. However, for big data, the performance impact might be an issue. Alternatively, iRODS NFS can be leveraged to locally mount iRODS collections when it is available, but the performance impact also needs to be evaluated. In short, if you have updated file ready locally, you don't have to retrieve the file first, you can just iput the updated file to iRODS directly.

**Comment by pkdash** [comment]
@hyi In order to update the file I have to first retrieve it from iRODS. Should I be then looking at the ```django_irods``` module for api to retrieve file from IRODS and putting the file back into IRODS?

**Comment by hyi** [comment]
@pkdash You can use this function https://github.com/hydroshare/django_irods/blob/b8a4b6ae5fec9355bc16867c01bf3c941c3e7712/storage.py#L42 to retrieve file, and this function https://github.com/hydroshare/django_irods/blob/b8a4b6ae5fec9355bc16867c01bf3c941c3e7712/storage.py#L121 to save file.

**Comment by pkdash** [comment]
@hyi Got it. Thanks.

**Comment by horsburgh** [comment]
@pkdash how about something like this for starters:

SamplingFeatureCode:SamplingFeatureName, VariableCode:VariableName, UnitsName, ProcessingLevelCode, MethodName

Yes, it will be very long in some cases. So, I would fix the width of the drop down and make it so the user can over over the elements of the list and have a tool-tip text that pops up with the whole string.  

In most interfaces where we select individual time series, we have multiple drop downs so we don't have to cram all of this into one (e.g., one for Site, one for Variable, etc.).  But, I'm not sure that's needed in this case.

**Comment by pkdash** [comment]
@horsburgh I did implement labeling each time series with a set of metadata (not with what you have suggested now) yesterday. I will later change it the format you have suggested. The current status of work you can test at riverdev.hydroshare.org.

**Comment by pkdash** [comment]
@hyi I noticed some performance issue when trying to update the SQLite file every time a metadata element gets updated even with using the djang-irods api for retrieving the file from irods and saving it back to irods. I think I should go for bulk update of the SQLite file which can be activated by the user (a button on the UI to update the SQLite file) or at the time of bag download. Your thoughts on this approach.

**Comment by hyi** [comment]
@pkdash Yes, definitely some performance impact especially for large files, and on-demand file update is the way to go to make sure file is only updated when needed. You can use similar approach as on-demand bag downloading/updating to update the SQLite file when that content file is downloaded or when the bag is downloaded. When metadata is changed, bag_modified iRODS AVU for the resource gets set anyway, so you can just add code to update the SQLite file when bag or content file is downloaded rather than every time when metadata is changed.

**Comment by horsburgh** [comment]
@pkdash - I just had a look on riverdev.hydroshare.org.  Here's some things that I think need to be modified:

* [ ] Modify the contents of the drop down box with the format suggested above.  Let's not do multiple drop down boxes.
* [ ] Modify the label that says "Select a time series to see corresponding metadata:" to extend all the way across the tab and then move the drop down box under that label and left justify within the tab (instead of having it off the right).
* [ ] Since you are viewing metadata for one time series at at time, change the labels to singular (e.g., change "Sites" to "Site" and "Variables" to "Variable", etc.)
* [ ] Right now if I select a new time series from the drop down it looks like it is reloading the entire page.  It would be nice if it updated with an Ajax call so you don't leave where you are at on the page, but rather the "Resource Specific" tab just updates without reloading the page.
* [ ] Theres an issue with the resourcemetadata.xml file.  Check the example above.  Right now you are closing the <rdf:Description> element under the <hsterms:timeSeriesResult> element but then adding the Site, Variable, Method and ProcessingLevel.  All of those elements should be within the <rdf:Description> element for time series result.

So, instead of this (see the offending line just below my comment):

```xml
   <hsterms:timeSeriesResult>
      <rdf:Description>
        <hsterms:timeSeriesResultUUID>51e31687-1ebc-11e6-aa6c-f45c8999816f</hsterms:timeSeriesResultUUID>
        <hsterms:units>
          <rdf:Description>
            <hsterms:UnitsType>Temperature</hsterms:UnitsType>
            <hsterms:UnitsName>degree celsius</hsterms:UnitsName>
            <hsterms:UnitsAbbreviation>degC</hsterms:UnitsAbbreviation>
          </rdf:Description>
        </hsterms:units>
        <hsterms:Status>Unknown</hsterms:Status>
        <hsterms:SampleMedium>Surface Water</hsterms:SampleMedium>
        <hsterms:ValueCount>1441</hsterms:ValueCount>
        <hsterms:AggregationStatistic>Average</hsterms:AggregationStatistic>
      <!-- The following line should not be here. Close the rdf:Description after processingLevel -->
      </rdf:Description>
      <hsterms:site>
        <rdf:Description>
          <hsterms:SiteCode>USU-LBR-SFUpper</hsterms:SiteCode>
          <hsterms:SiteName>South Fork Little Bear River above Davenport Creek near Avon, Utah</hsterms:SiteName>
          <hsterms:Elevation_m>1573</hsterms:Elevation_m>
          <hsterms:ElevationDatum>NGVD29</hsterms:ElevationDatum>
          <hsterms:SiteType>Stream</hsterms:SiteType>
        </rdf:Description>
      </hsterms:site>
      <hsterms:variable>
        <rdf:Description>
          <hsterms:VariableCode>USU36</hsterms:VariableCode>
          <hsterms:VariableName>Temperature</hsterms:VariableName>
          <hsterms:VariableType>Water Quality</hsterms:VariableType>
          <hsterms:NoDataValue>-9999</hsterms:NoDataValue>
          <hsterms:Speciation>Not Applicable</hsterms:Speciation>
        </rdf:Description>
      </hsterms:variable>
      <hsterms:method>
        <rdf:Description>
          <hsterms:MethodCode>28</hsterms:MethodCode>
          <hsterms:MethodName>Quality Control Level 1 Data Series created from raw QC Level 0 data using ODM Tools.</hsterms:MethodName>
          <hsterms:MethodType>Instrument deployment</hsterms:MethodType>
          <hsterms:MethodDescription>Quality Control Level 1 Data Series created from raw QC Level 0 data using ODM Tools.</hsterms:MethodDescription>
        </rdf:Description>
      </hsterms:method>
      <hsterms:processingLevel>
        <rdf:Description>
          <hsterms:ProcessingLevelCode>1</hsterms:ProcessingLevelCode>
          <hsterms:Definition>Quality controlled data</hsterms:Definition>
          <hsterms:Explanation>Quality controlled data that have passed quality assurance procedures such as routine estimation of timing and sensor calibration or visual inspection and removal of obvious errors. An example is USGS published streamflow records following parsing through USGS quality control procedures.</hsterms:Explanation>
        </rdf:Description>
      </hsterms:processingLevel>
   </hsterms:timeSeriesResult>
```
Do this instead:

```xml
    <hsterms:timeSeriesResult>
      <rdf:Description>
        <hsterms:timeSeriesResultUUID>51e31687-1ebc-11e6-aa6c-f45c8999816f</hsterms:timeSeriesResultUUID>
        <hsterms:units>
          <rdf:Description>
            <hsterms:UnitsType>Temperature</hsterms:UnitsType>
            <hsterms:UnitsName>degree celsius</hsterms:UnitsName>
            <hsterms:UnitsAbbreviation>degC</hsterms:UnitsAbbreviation>
          </rdf:Description>
        </hsterms:units>
        <hsterms:Status>Unknown</hsterms:Status>
        <hsterms:SampleMedium>Surface Water</hsterms:SampleMedium>
        <hsterms:ValueCount>1441</hsterms:ValueCount>
        <hsterms:AggregationStatistic>Average</hsterms:AggregationStatistic>
        <hsterms:site>
          <rdf:Description>
            <hsterms:SiteCode>USU-LBR-SFUpper</hsterms:SiteCode>
            <hsterms:SiteName>South Fork Little Bear River above Davenport Creek near Avon, Utah</hsterms:SiteName>
            <hsterms:Elevation_m>1573</hsterms:Elevation_m>
            <hsterms:ElevationDatum>NGVD29</hsterms:ElevationDatum>
            <hsterms:SiteType>Stream</hsterms:SiteType>
          </rdf:Description>
        </hsterms:site>
        <hsterms:variable>
          <rdf:Description>
            <hsterms:VariableCode>USU36</hsterms:VariableCode>
            <hsterms:VariableName>Temperature</hsterms:VariableName>
            <hsterms:VariableType>Water Quality</hsterms:VariableType>
            <hsterms:NoDataValue>-9999</hsterms:NoDataValue>
            <hsterms:Speciation>Not Applicable</hsterms:Speciation>
          </rdf:Description>
        </hsterms:variable>
        <hsterms:method>
          <rdf:Description>
            <hsterms:MethodCode>28</hsterms:MethodCode>
            <hsterms:MethodName>Quality Control Level 1 Data Series created from raw QC Level 0 data using ODM Tools.</hsterms:MethodName>
            <hsterms:MethodType>Instrument deployment</hsterms:MethodType>
            <hsterms:MethodDescription>Quality Control Level 1 Data Series created from raw QC Level 0 data using ODM Tools.</hsterms:MethodDescription>
          </rdf:Description>
        </hsterms:method>
        <hsterms:processingLevel>
          <rdf:Description>
            <hsterms:ProcessingLevelCode>1</hsterms:ProcessingLevelCode>
            <hsterms:Definition>Quality controlled data</hsterms:Definition>
            <hsterms:Explanation>Quality controlled data that have passed quality assurance procedures such as routine estimation of timing and sensor calibration or visual inspection and removal of obvious errors. An example is USGS published streamflow records following parsing through USGS quality control procedures.</hsterms:Explanation>
          </rdf:Description>
        </hsterms:processingLevel>
      </rdf:Description>
    </hsterms:timeSeriesResult>
```

Otherwise, the metadata extraction worked OK for my examples, and pretty much everything else looked OK.  I can test more if you have specific questions.

**Comment by pkdash** [comment]
@horsburgh I will fix the problem with xml generation. I was aware of all the UI problems you have listed. I just implement the minimum UI functionality so that I can test the backend-code. I will work with @mauriel133 to finalize the UI issues.

**Comment by pkdash** [comment]
@horsburgh 

>  Modify the contents of the drop down box with the format suggested above. Let's not do multiple drop down boxes.

Not sure about 'not doing multiple drop down boxes'.

**Comment by horsburgh** [comment]
@pkdash - just go with this in one drop down box:

SamplingFeatureCode:SamplingFeatureName, VariableCode:VariableName, UnitsName, ProcessingLevelCode, MethodName

Multiple drop down boxes (e.g., one for site and one for variable, etc.) would complicate things.

**Comment by pkdash** [comment]
@horsburgh Got it.

**Comment by pkdash** [comment]
@horsburgh In order to provide dropdowns for CV related fields when editing metadata elements, I am assuming only values for the 'Term' and 'Name' fields of the CV table would be sufficient. The dropdowns will be listing the values for the 'Term' field.

**Comment by horsburgh** [comment]
If you look at them the values in the "Term" field are URI friendly camel cased terms.  So, they can be the keys for the drop down items, but you want to display for users the "Name".  Also, the primary key/foreign key relationships in the ODM2 database are on the "Name" field in the CV table.  I can tell you all about why that is if you want to know.

**Comment by pkdash** [comment]
@horsburgh Do I have to worry about PK/FK as it relates to these CV tables and metadata editing?

**Comment by horsburgh** [comment]
As long as a term is already in the SQLite database (e.g., its already in the CV table), it should show up in the dropdown list.  If they choose from the list, no problem.  If they want to use a term that is not in the list (i.e., not already in the database), it would be technically correct to add the term to the corresponding CV table in the database first and then use it in the related table.  I believe that SQLite does not enforce referential integrity by default, so you could get away with not doing this, but it would be better to just take care of it.

**Comment by pkdash** [comment]
I should be able to maintain the referential integrity in case of new terms are added by the user.

**Comment by pkdash** [comment]
@horsburgh I have now deployed the current work for this issue at riverdev.hydroshare.org. 

The new work includes:

- Metadata editing with dropdowns listing data for the corresponding CV tables. At this point the feature to add new terms has not been implemented. 
- A specific timeseries is identified with the suggested metadata from that series (with tooltip for the full text).
- The bug in xml generation has been fixed
- Updated metadata for the 'variable' element can be written to the SQLite file by clicking the Update SQLite file button (this button needs some formatting as it relates to positioning on the page). I still need to apply the same logic of updating the SQLite file for other elements.

**Comment by pkdash** [comment]
@horsburgh For the user to add a new term what data needs to be entered by the user? term and name?

**Comment by horsburgh** [comment]
@pkdash - yes, term and name are required.  You could write a little function to construct the term from the name so they only have to enter the name.  The function would remove spaces between words, lower case the first word, and upper case the first letter of any subsequent words.  See the examples at http://vocabulary.odm2.org.

**Comment by pkdash** [comment]
@horsburgh Sounds good.

**Comment by pkdash** [comment]
@horsburgh Here is an issue related to deleting/adding SQLite file to a resource.  When the user deletes the SQLite file we don't delete the extracted metadata (that has been the case since the phase-1 of the timeseries resource type implementation). When the user adds a SQLite file to an existing resource, we provide the option (check box) for extracting metadata from the uploaded file. If the user selects to extract metadata then all is good. However, if the user selects not to extract metadata then the following is an issue:

We will not be able to write metadata changes to the new SQLite file that the user added after deleting the original SQLite file as the series ids stored in Django database can be completely different from that in the currently held SQLite file.

**Comment by pkdash** [comment]
@horsburgh Currently we store the uploaded SQLite file even if it fails ODM2 schema  validation. Not sure how the metadata editing need to work when the resource contains an invalid SQLite file.

**Comment by dtarb** [comment]
I suggest we should not store a file known to not be valid.  With other resource types we reject the files if they are not compliant with the resource type requirements.  (Although I do recognize that the requirements are less stringent with other resource types).  That said, it may not be possible to ensure that the file is always right and when metadata editing encounters a problem it should gracefully indicate that there is a problem with the file and that the metadata can not be edited, with a message to the user that they may need to download and fix, or replace the file.

**Comment by horsburgh** [comment]
@pkdash - Answers to your questions:

1.  _What to do about extracting metadata from a new uploaded file_:  Perhaps we just need to couple metadata extraction tighter than we did before.  Given that we have now added the capability to have multiple time series in a time series resource, and users could delete a SQLite file containing only a single time series but then upload a SQLite file containing multiple time series (and many other potentially weird scenarios), it just doesn't make sense to let them decouple the HydroShare metadata from the contents of the SQLite file.  I suggest we just remove the current option to extract metadata when uploading a new file, make it mandatory, and use the current warning to let the users know that they are uploading a new file and so any metadata in the new file will overwrite their existing metadata.  They can always edit it after the fact.

2. _What to do about storing files that fail ODM2 schema validation_:  I suggest we follow Dave's advise here and fail with an error that says something like, "Your uploaded file is not in the correct format or does not contain the necessary elements to define a time series resource.  You can either modify and correct the file and upload it again, or you can consider using a Generic Resource instead." (or something like that).  If you do not allow them to upload an invalid file, the metadata editing issue goes away.

**Comment by pkdash** [comment]
@horsburgh Another question. If the user creates a timeseries resource with no SQLite file uploaded what should we doing with metadata editing? Should we be allowing adding/updating metadata to the resource when there is no SQLite file?

**Comment by pkdash** [comment]
@horsburgh I assume we delete metadata if the SQLite file is deleted.

**Comment by pkdash** [comment]
@horsburgh As part validation of the uploaded SQLite is it necessary to check that there is data in all of the CV lookup tables that are being used (dropdown list) for metadata editing?

**Comment by horsburgh** [comment]
@pkdash - I think it is unnecessary to delete the metadata if the SQLite file is deleted.  We already have functionality for hiding resources without content files (e.g., removing their public status if they were public).  And, the current plan is to re-extract/update metadata upon uploading a new file.  So, I would just leave the metadata as is until they upload a new file.

For CV validation - it's obviously going to be hard for them to edit metadata if they have nothing to choose from in their drop down lists because the CV tables in their database are empty (which should really be an invalid state for an ODM2 database even if SQLite allows it).  We've got options:

1.  Do validation upon upload, and if their CV lookup tables are empty reject the database as invalid
2.  Upon upload, automatically update their CV tables to contain all of the ODM2 CV terms
3.  Upload whatever database they give us and add a button in the resource specific metadata editing that enables them to update their database with the ODM2 CV terms. 

There is a Python script for loading the CV terms to a blank database, but it currently doesn't have functionality for checking to see if terms exist in the database already.  See: https://github.com/ODM2/ODM2/blob/master/src/load_cvs/cvload.py

**Comment by pkdash** [comment]
@horsburgh Will keep the metadata upon SQLite file deletion. As it relates to missing CV lookup tables, I prefer option#1 at least initially. May be later I assume we have to do option#2 when we allow uploading CV file as timeseries.

**Comment by pkdash** [comment]
@horsburgh As part of the SQLite file validation I am checking that the following CV tables exist and there is at least one record in each of these CV tables:

CV_VariableType
CV_VariableName
CV_Speciation
CV_SiteType
CV_ElevationDatum
CV_MethodType
CV_UnitsType
CV_Status
CV_Medium
CV_AggregationStatistic

**Comment by horsburgh** [comment]
@pkdash - this seems like a reasonable plan.

**Comment by hyi** [comment]
@pkdash Can this issue be closed now?

**Comment by pkdash** [comment]
This has been implemented. This functionality is now available on www. So closing.
