### ISSUE TITLE
Profile and Home Page follow up issues

### ISSUE THREAD

**Issue by Maurier** [hydroshare/hydroshare#1237]
I will be addressing some problems that were discovered while going through the Pre-Deploy Checklist: https://docs.google.com/document/d/1iHySO-5Kpfp1sBgixWj-Hv0yFy95WUVPvsmg2JmURaU/edit#

- [x] when resetting the password I was taken to the old profile edit page (not sure if this is intended). The password field here requires at least 6 characters, but this constraint didn't exist during account creation process. (related: https://github.com/hydroshare/hydroshare/issues/1835)
- [x] When filling out metadata in order to make the resource public, "Sufficient to make public" message appears when all other required metadata, except content files, have been filled out. The buttons to change sharing status are also enabled, but they fail because of the content files constraint and an error message is shown: "Resource does not have required content files to be public".
- [x] When resetting password from profile edit page, the 6 character constraint seen is not existent.
- [x] Apps link does not open in new tab.
- [ ] Link triggers Gmail (in my case) in the same tab. This should be changed to open in a new tab.
- [ ] Report a bug link opens in same tab.
- [ ] Site Map page needs to be restyled.

**Comment by pkdash** [comment]
@mauriel133 Is this issue still relevant?

**Comment by mauriel133** [comment]
Yes, these are minor issues discovered while doing pre-deploy checks. I will address them once other high priority features are implemented.
