### ISSUE TITLE
Resource landing page UI

### ISSUE THREAD

**Issue by mauriel133** [hydroshare/hydroshare#124]
I will be changing the style/layout of the resource details page and some other general UI changes.
- [x] Move abstract to the top.
- [x] Restyle "Content" field.
- [x] Create Keywords container and remove the old field from the table.
- [x] Reposition citation
- [x] Reposition Rights and URL
- [x] Organize the rest of the fields into the following tabs: Contact, Coverage, Related Resources, Resource Specific, System Metadata
- [x] Reposition footer to always float at the bottom of the screen or the page.
- [x] Remove title bar and add a title at the beginning of every page instead.

**Comment by dtarb** [comment]
@horsburgh can you please check these in the 1.4 release candidate when it is deployed, then close if satisified.
