### ISSUE TITLE
White space at bottom of page

### ISSUE THREAD

**Issue by mauriel133** [hydroshare/hydroshare#1240]
There is a white space at the bottom of the page caused by legacy code. (See: https://github.com/hydroshare/hydroshare/blob/develop/ga_resources/templates/includes/ga_editable_form.html)

See spacing between "FOLLOW" and the icons.

How it should look like:
![capture](https://cloud.githubusercontent.com/assets/2448568/15756792/058c5674-28c0-11e6-96a8-0d146954506b.PNG)

How it looks:
![capture](https://cloud.githubusercontent.com/assets/2448568/15756896/7de6c410-28c0-11e6-9bd4-7d4cd41391c5.PNG)

**Comment by mauriel133** [comment]
@mjstealey, I'm not sure how to fix this issue since the legacy code template doesn't seem to render in our beta deployment, but it renders on my local instance after signing in (causing the extra space seen above).

**Comment by hyi** [comment]
Verified it is fixed on www.hydroshare.org. Closing.
