### ISSUE TITLE
Group and user permission on a resource overlapping

### ISSUE THREAD

**Issue by mauriel133** [hydroshare/hydroshare#1241]
Under "Manage Access" window, if I grant some access to a group, the permission level is also listed for each member of the group. This overlaps with the user's current permission level on the resource and causes errors when trying to change it.

![capture](https://cloud.githubusercontent.com/assets/2448568/15759596/8e8a4484-28cc-11e6-84bb-c0534e6cd8df.PNG)

**Comment by mauriel133** [comment]
@pkdash, the objects 'view_users' and 'edit_users' should only return entries for which the access has been granted specifically to the user, and not through being members of a group.

https://github.com/hydroshare/hydroshare/blob/develop/theme/templates/resource-landing-page/modals.html#L945

**Comment by pkdash** [comment]
@mauriel133 Will work on this first then.

**Comment by pkdash** [comment]
@mauriel133 Question. So how are we going to show that a user has access to a resource through group membership?

**Comment by mauriel133** [comment]
For that case we show the group entry only. We don't need to show that a specific member has access to the resource specifically through this interface.

**Comment by pkdash** [comment]
@mauriel133 I have fixed this now in branch '1241-user-access-only'. Can you pull this and test it from the UI?

**Comment by pkdash** [comment]
@mauriel133 See if you can close this issue?
