### ISSUE TITLE
Allow Group 'active' status to be set

### ISSUE THREAD

**Issue by pkdash** [hydroshare/hydroshare#1242]
This involves quite a bit of backend coding including unit tests.

**Comment by pkdash** [comment]
@Horsburgh, @mjstealey and @mauriel133 Want to make sure we want this feature to be added as a hotfix for release 1.7.

**Comment by pkdash** [comment]
@mauriel133 I assume the 'active' status be set from the group update interface.

**Comment by horsburgh** [comment]
@pkdash - this functionality is important.  It could probably wait for the next release, which should be next week right?

**Comment by mauriel133** [comment]
I think this should be added as soon as possible. Deactivating or removing a group will be necessary if a user creates a group by mistake and wants to get rid of it.

**Comment by pkdash** [comment]
@mauriel133 But my question (see above) is the 'active' status be set using the group update interface?

**Comment by mauriel133** [comment]
Either that or a link in the same page to deactivate the group, similar to how we deactivate profiles in the Profile page. I like the idea of an input field for it in the edit form.

**Comment by hyi** [comment]
@pkdash Is this issue already fixed? Can you check and see if it can be closed?

**Comment by pkdash** [comment]
This issue has been addressed. Closing.
