### ISSUE TITLE
Groups: Make it Easier to Share Resources with a Group

### ISSUE THREAD

**Issue by horsburgh** [hydroshare/hydroshare#1244]
According to @ChristinaB - 

> I created a new resource, but it took too long to figure out how to share the resource with the group. Either I need a spend time asking someone how to do it, or it's not obvious, but working with the impatient busy user timeframe of 30-60 sec, I suggest it needs to be more obvious. I think the Collaborate page could use a 'Share my Resources' button that takes me back to the start of the workflow. This may be redundent, since I could use the dashboard, but if you keep the lock as the workflow to sharing, you may need a more obvious pathway via the Collaborate page.

**Comment by mauriel133** [comment]
A toggle to share resources with a group or a user was added to the Manage Access window. 

![image](https://cloud.githubusercontent.com/assets/2448568/17445026/2c5c0ee4-5b00-11e6-9db7-4b655de0aa21.png)

**Comment by dtarb** [comment]
Good.  Closing.
