### ISSUE TITLE
Resource Landing Page: Consider Changing "Manage Access" Icon

### ISSUE THREAD

**Issue by horsburgh** [hydroshare/hydroshare#1245]
Submitted by @ChristinaB:

> I created a new resource, but it took too long to figure out how to share the resource with the group. Either I need a spend time asking someone how to do it, or it's not obvious, but working with the impatient busy user timeframe of 30-60 sec, I suggest it needs to be more obvious. I think the Collaborate page could use a 'Share my Resources' button that takes me back to the start of the workflow. This may be redundent, since I could use the dashboard, but if you keep the lock as the workflow to sharing, you may need a more obvious pathway via the Collaborate page.

> **Eventually I searched through each of the icons from my resource page and found the lock**, which led to the Groups radio button. ***I think the lock for user access control is not as intuitive***. I expected to share with the group with the arrow escaping the box icon (which is publish HydroShare, but is typically used to share). I suggest this be reconsidered.

**Comment by pkdash** [comment]
@horsburgh Can this be closed?

**Comment by horsburgh** [comment]
The icon has been changed, and we are no longer using a radio button on the manage access modal window, but rather using a toggle between users and groups that is more obvious.  I'm going to close this one as I think it's consistent to manage all access to resource through this one interface. We may eventually want to enable managing access to multiple resources at once, but that is a separate issue (and I think may have already been added to the issue tracker. Closing.
