### ISSUE TITLE
Query Model Program with the linked Model Instance

### ISSUE THREAD

**Issue by mohamedmorsy** [hydroshare/hydroshare#1249]
Now for each Model Instance resource type it could be linked to a Model Program resource type that is used to execute this instance by using the metadata "Executedby" from the Model Instance resource side. It would be great if a method could be implemented in the Discover page to display all the Model Instance resources that are linked to a certain Model Program resource. This would be good if a user is interested in seeing all the model instances for his/her favorite model.

**Comment by Castronova** [comment]
No longer relevant
