### ISSUE TITLE
Improve Access Control Messages

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#1250]
In the manage access panel change the text to:

Use this window to share your resource with specific HydroShare users. You can give other users the ability to view or edit this resource. You can also add additional owners who will have full permissions.

Owners can perform all operations on a resource and set whether a resource is Public, Discoverable, or Private and Shareable.  Resources that are Public have all their content visible to all users.  Resources that are Discoverable have only their metadata public.  Resources that are private are only accessible to specific users or groups that they have been shared with.

Editors can edit resource metadata and add and delete resource content files.  If the resource is Shareable editors can use manage access to extend editing or viewing access to other users.  

Viewers can view resource metadata and download resource content files.  If the resource is Shareable viewers can use manage access to extend viewing access to other users.

---

This is intended to help address the misunderstanding about resource deletion that led to issue #1212.  @christinab please comment on or edit this wording if you think it needs additional clarification for users.

**Comment by hyi** [comment]
@dtarb Can you verify and close the issue if it works now?

**Comment by dtarb** [comment]
Super!.  Closing.
