### ISSUE TITLE
Discovery Page - adjustments needed for search bar and mobile view

### ISSUE THREAD

**Issue by ChristinaB** [hydroshare/hydroshare#1253]
Hi Muriel - great work! One issue is that for about a month I thought that the discovery page only consisted of the left column filters.  In that view, the search bar is at the bottom and needs to be moved to the top.  It wasn't until I talked to David that he explained its a screen width issue.  Maybe put a message at the top of the screen informing the user with something like 'You are viewing the mobile page. For the full website click here' or some other kind of information that asks the user to widen the screen, or only shows the mobile view on mobile phones. In mobile view, be sure the search bar appears at the top.  
Thanks so much!
Christina

**Comment by mauriel133** [comment]
@ChristinaB, I made some layout changes that have now been deployed to www. Could you verify if this issue is fixed now?

**Comment by ChristinaB** [comment]
This seems great now. It has to be cell phone narrow to lose the right side results now, great!
Thanks Mauriel. 
C
