### ISSUE TITLE
Hide "Extended Metadata" tab in view mode if there is no extended metadata

### ISSUE THREAD

**Issue by zhiyuli** [hydroshare/hydroshare#1254]
This issue was mentioned in #647:
"dtarb commented 14 days ago
If there is no extended metadata the extended metadata tab should not be displayed when not in edit mode."

**Comment by hyi** [comment]
@zhiyuli Can this issue be closed? Please close it if the fix has already been merged and works.

**Comment by zhiyuli** [comment]
already merged and tested on www
