### ISSUE TITLE
Raster resource validation error when uploading zip file on dev

### ISSUE THREAD

**Issue by hyi** [hydroshare/hydroshare#1257]
This is a regression error due to the latest merge of raster issues branch. When uploading a zip file to create a raster resource type, it raises file validation error: ```Raster validation error. The uploaded files should contain only one .vrt file and .tif files referenced by the .vrt file.```. This can be reproduced on dev as well as in my local dev env after I merge my irods user zone branch with latest develop. Before merging, everything works, so this looks like a regression error introduced by the latest raster issues branch. Assigning to @gantian127 to look into it.

**Comment by gantian127** [comment]
@hyi I deployed raster-issue branch on playground yesterday and it worked to create the VRT raster resource. The link here is the VRT raster resource created yesterday for testing on playground.hydroshare.org. 
http://playground.hydroshare.org/resource/01b51b81d9ce4a3bb323beff12c978b1

But this morning the playground won't allow the creation of VRT raster resource. Is it possible that the backend settings for iRODS causes this issue? I will also look into this error. Thanks

**Comment by hyi** [comment]
@gantian127 Hmmm, it does not look like an iRODS backend issue since the file validation error is raised in pre-create-resource action before the resource is created, i.e., before the resource even gets to irods backend yet. Can you reproduce this in your local dev env? The error seems to come from this code block https://github.com/hydroshare/hydroshare/blob/develop/hs_geo_raster_resource/receivers.py#L118..L121. Let me know if you can reproduce it in your local dev env or not.

**Comment by gantian127** [comment]
@hyi Thanks for the info. I will test on the local dev and try to find out the bug.
