### ISSUE TITLE
Relabel non-API views

### ISSUE THREAD

**Issue by ironfroggy** [hydroshare/hydroshare#126]

**Comment by selimnairb** [comment]
@ironfroggy Is this issue still valid?  If so could you please provide a description of what is needed?  Thanks.

**Comment by selimnairb** [comment]
@ironfroggy Has this been completed?

**Comment by ironfroggy** [comment]
No. I'd like to get to it once post-migration pull requests are done.

**Comment by aphelionz** [comment]
@ironfroggy @selimnairb @dtarb Checking on this one...

**Comment by pkdash** [comment]
@aphelionz The person who created this issue (ironfroggy) is no more working in this project.  I don't know what this issue is about. May be we close it.

**Comment by dtarb** [comment]
I am going to close this with a mention for @alexlemann. If you know what Calvin was referring to and think this is still needed, please create a new issue that we understand.

**Comment by alexlemann** [comment]
I checked-in with Calvin / @ironfroggy  about this, but have not heard back yet. I'll let you know if I get a response.

In general though, there could be some cleanup of files (views.py vs. api.py) and urls that mix API functions with user/frontend views. Likely not high priority.
