### ISSUE TITLE
User group functionality phase-2

### ISSUE THREAD

**Issue by pkdash** [hydroshare/hydroshare#1260]
**Phase-2 should include the following features as it relates to groups:**
- [ ] Start a discussion
- [ ] Delete a discussion
- [ ] Comment on a recent activity or discussion.
- [ ] Get recent activity list (additional items): comments, discussion posts, user joined the group.
- [ ] Dynamic/on demand loading in Find Groups and Recent Activity.
- [ ] Ability for members outside of a group to share resources with it.
- [ ] Add labeling/favorite functionality to resource listing of Group page.

**Comment by Castronova** [comment]
No longer relevant.
