### ISSUE TITLE
View attribute table fails to load in HydroShare GIS App

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#1261]
I tried to view attribute table in the following Geographic Raster resource https://www.hydroshare.org/resource/93f49ab913fd4c639c98ab4a070d20e0/ using the GIS app and get a perpetual Loading spinning wheel.

**Comment by shawncrawley** [comment]
@dtarb This issue should be fixed.

**Comment by dtarb** [comment]
Tested.  OK.
