### ISSUE TITLE
CUAHSI Time series viewer app cannot open HIS referenced time series resource type

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#1262]
The CUAHSI Time series viewer app is on apps.hydroshare.org.  www.hydroshare.org has a HIS referenced time series resource type.  How do I open a specific HIS referenced time series resource with the apps viewer.  There is no Open with ... option for this.

**Comment by alvacouch** [comment]
AFAIK, this is because the REST API for referenced time series does not yet exist, as discussed on the call last Monday.

**Comment by zhiyuli** [comment]
tested on www
