### ISSUE TITLE
Collection resource coverage

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#1263]
When resources with coverage metadata (either spatial or temporal) are added to a collection the collection spatial or temporal coverage metadata should be extended (or initially written if empty) to the superset of the coverage of the resources being added with the coverage already there.

**Comment by alvacouch** [comment]
I presume that the coverage will remain a box?

**Comment by horsburgh** [comment]
Yes - I think coverage should be a box for collections unless the collection contains a single resource (say a time series) with a single point coverage.  Not sure why one would create a collection with a single time series in it though.

**Comment by dtarb** [comment]
Just thinking outside the box a bit, a collection of resources all at the same point in space, i.e. time series of different variables could have a point for coverage.  Similarly not all resources have spatial coverage (e.g. generic files or documents) so where they are in a collection, perhaps only one resource in the collection has spatial coverage, and perhaps it is a point.  So there do seem to be cases where a collection could have point coverage or no spatial coverage at all.

**Comment by zhiyuli** [comment]
A collection updates its coverage metadata only when new resources get added into (or existing contained res get removed from) this collection. To avoid breaking access control rules, if a contained res changes its coverage or gets removed from hs system, the collection WILL NOT re-calculate its coverage. That means in some cases the coverage of the collection may not accurately reflect the overall coverage of all current contained resources. 
@dtarb @horsburgh @danames @pkdash Are you OK with this?

**Comment by alvacouch** [comment]
@zhiyuli @pkdash This is a misconception. Access control was not intended to prevent such updating. Since the coverage box for a collection is a computed quantity that is a deterministic function of its content, if the content changes, the box should change. This is not the same thing as adding a file or a resource to a collection. These are things that users do. 

The only reason that I would not do this would be performance, not access control.  It could potentially take a while to compute the box coverage.

**Comment by alvacouch** [comment]
@zhiyuli @pkdash In general, we have provided for this with a very flexible model of access control. My library defines what a user should be able to do. Meanwhile, all users actually have complete access to the iRODS repository and the data models. It is our software that mediates. Thus, there is nothing preventing auto-magical update of computed resource metadata based upon peripheral changes, e.g., posting new data or changing metadata in a sub-object or reference. This doesn't need user permission. For example, consider the case of referenced time series; the time extent should be able to change without a user requesting that change.

**Comment by zhiyuli** [comment]
@alvacouch I got your point. Your access control code will not block any "auto-magical update". 

I was thinking the user who can change a contained res may not have any permission over the collection. In addition, when any change happens to a res, the bag should log which user did the last change. In this case, "auto-magical update" will bring trouble determining the "last change user".

**Comment by pkdash** [comment]
As @zhiyuli mentioned that's the issue with auto update the ' last change user'.

**Comment by alvacouch** [comment]
@zhiyuli @pkdash This is a matter of carefully defining semantics. The "last change user" is the user who made the last change to this particular collection resource, i.e., adding or removing an element. It is not the user who made a change to an element of a collection. That is at a different level of the system and is recorded there, in the other resource. And it is definitely not a user whose actions kicked off a re-harvest of external metadata.

**Comment by horsburgh** [comment]
The use case we are talking about requires that a user has created a collection resource that contains resources that they do not have sole control over. Given this - they have to know that this situation is a possibility.

I would be OK with not automatically updating the coverage element for the collection resource if a resource in the collection is removed or modified (i.e., changes that the owner of the collection resource may not have control over).  But, I think you might want to consider adding a button in the space for editing the coverage for the collection that enables the collection owner to update the coverage based on whatever resources are left in the collection.  

Trying to do too much stuff automatically adds complexity.  Perhaps we should place the burden on the user to maintain his/her collection metadata.

**Comment by alvacouch** [comment]
@horsburgh But I can guarantee that for referenced time series, users are going to want periodic updates of the time coverage.

**Comment by zhiyuli** [comment]
@horsburgh @alvacouch I will add a "update coverage button" on collection landing page allowing collection owners/editors to manually re-calculate coverage.

**Comment by horsburgh** [comment]
@alvacouch - I think you are right about people potentially wanting automatic updates of the time coverage for referenced time series resources.  I don't think we ever really settled on which actions constitute an update of the resource/metadata versus which ones could be done by the system but not necessarily be reflected in the update dates in the metadata.

Let's say we created reference time series resources for everything published via a WaterOneFlow web service in the Water Data Center.  Would we really dynamically update the temporal coverage for all of these referenced time series in HydroShare (or even just for the ones to which data are being added)?

**Comment by alvacouch** [comment]
@horsburgh @zhiyuli @pkdash @dtarb At the Water Data Center we update the time coverages weekly.

**Comment by zhiyuli** [comment]
tested on www
