### ISSUE TITLE
Referenced time series HTML header not synchronized with resource title

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#1265]
The following screen shot for a HIS referenced time series resource shows that the HTML header is out of sync with the Resource title.

![untitled](https://cloud.githubusercontent.com/assets/3456833/15995152/3b269b4e-30d3-11e6-9020-765cd97010c1.png)

This is the same as #995 that was fixed and closed for other resource types.

**Comment by pkdash** [comment]
@dtarb and @zhiyuli This resource was created prior to the fix for issue #995 which did not include a custom migration to update title of the existing resources.

**Comment by dtarb** [comment]
OK.  I guess we can ignore it then or @zhiyuli can recreate the resource or edit the title to see if it fixes it.  @zhiyuli once you have done this, feel free to close the issue.

**Comment by zhiyuli** [comment]
a new refts res is created here: https://www.hydroshare.org/resource/7be4a9c2f43b407f85aaf1154612d6a3/
the HTML header shows up correctly
closing
