### ISSUE TITLE
Show local times

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#1271]
A user has indicated that times presented in UTC are difficult to interpret.  Figure out a way to show local times, where times are presented in HydroShare.  

Defining what "local" time is, for the internet may be a challenge.  If possible could we have local time keyed to the time zone associated with the location of their IP address.  Perhaps the time zone should be displayed in parentheses after where time is indicated for clarity on this). 

(This is not very high priority).

**Comment by martinseul** [comment]
closing refers to https://github.com/hydroshare/hydroshare/issues/2369
