### ISSUE TITLE
Delete User functionality - cascade across all databases

### ISSUE THREAD

**Issue by mjstealey** [hydroshare/hydroshare#1274]
Need to implement a cascading delete user function so that accounts that have not been activated within 24 hours can be properly released by the system.
- Prevents account limbo - user creates an account, doesn't use emailed link in time, cannot create a new account using the same username/email.
- Prevents orphaned accounts - user creates an account and never uses it
- Needs to remove any information propagated by a created user call throughout the system

Django tracks 3 user account statuses
- Active
- Staff status
- Superuser status

If an user is not flagged as "Active" after 24 hours, the account should be deleted so that the username and/or email could be reused to generate a future account.

![screen shot 2016-06-15 at 3 54 10 pm](https://cloud.githubusercontent.com/assets/5332509/16095219/b295e226-3311-11e6-811f-514e63189fde.png)

![screen shot 2016-06-15 at 3 54 24 pm](https://cloud.githubusercontent.com/assets/5332509/16095225/b8c23276-3311-11e6-9871-3007b820cabf.png)

**Comment by pkdash** [comment]
@mjstealey @alvacouch Since the ```User``` object is used in hs_access always as a ForeignKey, I assume deleting a user will do the cascade delete automatically. However, at this point we lack a unit test in hs_access to prove this.

**Comment by alvacouch** [comment]
It is only safe to delete a user who is not mentioned in resource metadata. I suggest that we modify `BaseResource` so that deleting a user who appears in resource metadata is impossible. It is an easy fix and affects nothing except the new code for user cleanup. .

**Comment by hyi** [comment]
@mjstealey @alvacouch Can this issue be closed?

**Comment by mjstealey** [comment]
Functions as expected for tests run
