### ISSUE TITLE
Save button on user profile page not working

### ISSUE THREAD

**Issue by goodalljl** [hydroshare/hydroshare#1275]
Using Fire Fox, I edited my user profile to try and add my organization, but when I hit save changes, nothing happens. When I exit out of this page, my organization is still blank.

**Comment by mauriel133** [comment]
Thanks for reporting this. I'll have a look and have it fixed asap.

**Comment by jbradberry** [comment]
I just figured out what's going on with this.  Firefox is autofilling the first password field, hidden under "Change password", but not the second password field, so it's failing validation.  These fields do have `autocomplete="off"` set, but it seems FF is not respecting it.

**Comment by hyi** [comment]
@goodalljl Looks like this issue has been fixed. Can you verify and close this issue if it works?

**Comment by goodalljl** [comment]
It now works for me. Thanks for fixing this! Closing ...
