### ISSUE TITLE
REST API needs to support iRODS federation zone for resource creation and adding files to resources

### ISSUE THREAD

**Issue by hyi** [hydroshare/hydroshare#1276]
Creating this issue as @pkdash suggested during his code review for iRODS federation work. This is the second phase functionality after the iRODS federation work is deployed. REST API needs to add support for resource creation and adding files to existing resources from a federated zone by exposing functionalities to REST API end points. @alvacouch I am assigning it initially to you, but feel free to reassign as appropriate.

**Comment by pkdash** [comment]
@alvacouch I can work on this issue. Let me know.

**Comment by pkdash** [comment]
@hyi Not sure how I can write unit tests for updated REST endpoints that involve federated iRODS zone.

**Comment by hyi** [comment]
@pkdash I suggest to just mock it in the similar way as you mock other irods-related operations for REST API endpoint tests. I will add tests for irods-related operations including irods federations as part of issue https://github.com/hydroshare/hydroshare/issues/1292.

**Comment by pkdash** [comment]
@hyi Another question. How can I test it manually (not unit test)? I have to have an IRODS account right.

**Comment by cuahsimarko** [comment]
@hyi can you close this if Federation indeed now supports this?

**Comment by hyi** [comment]
@cuahsimarko I don't think we have exposed this functionality in REST API yet. We don't seem to have users request this in REST API, so it is most likely a low priority item.

**Comment by hyi** [comment]
This issue does not apply any more due to our recent change that removed functionality to create resources in user zone.
