### ISSUE TITLE
Broken links for the group members

### ISSUE THREAD

**Issue by mohamedmorsy** [hydroshare/hydroshare#1277]
If I would like to know some information about a specific member of a group by clicking on the member name, nothing happen except for the group owner. You can reproduce this issue through the "HydroShare Developers" group.

![image](https://cloud.githubusercontent.com/assets/5543781/16122914/0b6571b4-33b7-11e6-9437-4151678ce561.png)

**Comment by mauriel133** [comment]
Fix has been applied to www

**Comment by mjstealey** [comment]
Implemented
