### ISSUE TITLE
Date formats are inconsistent in period coverage resources

### ISSUE THREAD

**Issue by xuezhaokun** [hydroshare/hydroshare#1279]
When I work on filtering period coverages, I noticed that we have inconsistent date formats for "start" and "end" property in period coverage resources. Some of them are stored as "01/31/2008", some are stored as "1979-01-01 06:00:00", some are stored as "2015-05-24T13:00:00Z", and some are stored as "1985-10-01".  This inconsistency is really inconvenient for parsing date strings into date objects. Can anyone fix this issue and add a validator for this JSON field?

**Comment by hyi** [comment]
@pkdash Assigning this to you for initial investigation.

**Comment by pkdash** [comment]
@xuezhaokun Can you test on beta if this issue got resolved?

**Comment by xuezhaokun** [comment]
@pkdash I checked couple period coverage resources. It looks good now.
