### ISSUE TITLE
Remove TastyPie

### ISSUE THREAD

**Issue by ironfroggy** [hydroshare/hydroshare#128]
- [ ] Remove references from pg.hs_init_db.sql (is there a way to generate a new version of this?)
- [ ] Remove unused imports
- [ ] Remove/empty all api modules
- [ ] Remove requirements and remove from any images
- [ ] Remove settings
- [ ] Remove tastypie-swagger
- [ ] Remove from hs_bagit
- [ ] Remove API tests

Open questions:
- [ ] What is hs_core/hydroshare/resource.py lines 56-57 referencing?

**Comment by ironfroggy** [comment]
@mjstealey can you give some direction on my first bulletpoint here: removing tastypie from pg.hs_init_db.sql? Do you have a way to regenerate that file when the schema changes?

**Comment by hyi** [comment]
I believe this has been resolved. @ironfroggy can you close this issue if it is resolved, or comment otherwise? Added Release 1.6 milestone to keep track of it.
