### ISSUE TITLE
ubuntu VirtualBox VM should have flake8 installed in host OS for convenience

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#1289]
@mjstealey I am currently manually installing flake8 at the top level of the Ubuntu vm so that syntax checking doesn't require actually running the HydroShare container. This saves time.

**Comment by hyi** [comment]
@mjstealey Can this issue be closed?

**Comment by mjstealey** [comment]
completed and posted at distribution.hydroshare.org
