### ISSUE TITLE
DataONE Tier 1 (Read-Only) Compatible API

### ISSUE THREAD

**Issue by ironfroggy** [hydroshare/hydroshare#129]

**Comment by rayi113** [comment]
See: https://docs.google.com/document/d/1WL4s1EL1Yg0omuHgO6pb4haKetVyszpWZ2HzLV7d-0s/edit

**Comment by hyi** [comment]
@rayi113 @horsburgh @dtarb What is the current plan for this issue?

**Comment by dtarb** [comment]
I am reassigning to @horsburgh for him to regroup on this issue.

**Comment by horsburgh** [comment]
@dtarb - I'm happy to revisit this over the next several months.  Three questions:

1. Are we for sure going to do this?  
2. Are we going to do this ourselves? We had talked about partnering with someone else to get this functionality, but I don't think that relationship took off.
3. Assuming the answer to 2 is yes, which developer(s) can I work with to do the implementation?

I think this would be a good thing to put some effort into for a number of reasons, but it will be highly dependent upon our existing API.

**Comment by rayi113** [comment]
@horsburgh @dtarb I ran this past the DFC folks and they are open to meeting about it.  DFC has a DataOne member node as an update of my Feb 2015 comment in this thread above.

**Comment by dtarb** [comment]
@horsburgh can you please reassess where we stand on this issue and identify the best approach to getting DataOne member node functionality in the simplest way.  I do not mind whether we do it in partnership with DFC or independently.  This is still an important project goal.  We need to identify if there are API elements missing.  The API and RDM was designed with this in mind, so I am hoping that this can be achieved quite simply but simple things always seem to blossom in complexity, so if we start getting bogged in complexity we may need to triage this.

**Comment by horsburgh** [comment]
@dtarb - after listening to the discussion on the call yesterday, it didn't sound like there is an immediate/readily available pathway for HydroShare to get DataONE compatibility through DFC.  I think it could be feasible in the relatively near future though.  

Given this, I think the best route for us to go is to first investigate the existing DataONE Generic Member Node implementation.  It is Python/Django based, open source, and, according to their documentation, it can be pointed at any data that is available via a URL (which means that we might not even have to move or replicate any HydroShare Resources).

See: https://www.dataone.org/software-tools/generic-member-node
More details: http://www.pythonhosted.org/dataone.generic_member_node/

If their Generic Member Node isn't going to meet our needs, I think we should continue down the path to partnership with someone that already has a Member Node.

**Comment by aphelionz** [comment]
@dtarb @horsburgh Let me know where we are on this one, thanks!

**Comment by horsburgh** [comment]
No progress on this one.
