### ISSUE TITLE
Add unit tests for iRODS federation zone work detailed at issue [#1120]

### ISSUE THREAD

**Issue by hyi** [hydroshare/hydroshare#1292]
Add unit tests for iRODS federation zone work detailed at issue https://github.com/hydroshare/hydroshare/issues/1120

**Comment by pkdash** [comment]
@hyi Can you assign a priority to this issue?

**Comment by hyi** [comment]
@pkdash I give this issue a medium priority, but as soon as @mjstealey gets dockerized irods containers into our development environment, I plan to start to work on this.

**Comment by hyi** [comment]
Merged, closing.
