### ISSUE TITLE
update variable definitions for federated iRODS environments

### ISSUE THREAD

**Issue by mjstealey** [hydroshare/hydroshare#1299]
The variable definitions for the two federated iRODS instances should be better disambiguated.
- iRODS for site based resources (generally wwwHydroProxy settings)
- iRODS for users and user held resources (generally hsuserproxy settings)

**Comment by pkdash** [comment]
@mjstealey Is this still an issue? If so, assign a priority level.

**Comment by mjstealey** [comment]
@pkdash Yep, this is still a thing. Will be completing this at the same time as the Docker iRODS work for the CI environment. No milestone, it just is when it is.

**Comment by mjstealey** [comment]
With the docker level iRODS option made available to the user the variables can stay as is.
