### ISSUE TITLE
After adding a resource to My Resources, I can't remove it

### ISSUE THREAD

**Issue by horsburgh** [hydroshare/hydroshare#1300]
I click on the button to add a resource that I have discovered to "My Resources". After doing this, I visit the landing page for that resource and click the button to remove it from My Resources.  The button changes color, but the resource is still in the list of My Resources when I go back to that page.

**Comment by mauriel133** [comment]
@horsburgh, I tried to replicate this issue with no success. Could you link me the resource with this problem?

**Comment by horsburgh** [comment]
It's this one:

https://www.hydroshare.org/resource/da7973a47a0849798be5ae5a1110c1c0/

It's the first one in the list when you go the search page.  It's a bit weird because it still shows up in my list of resources, but the button to add it to my resources is green and when I hover over it, it says "Add to My Resources".  If I click the button, it turns red, but the tool-tip text still says "Add to my Resources".

**Comment by mauriel133** [comment]
@pkdash, it seems that the context variable 'cm.is_mine' in genericresource.html is not being populated. Could you look into this?

I'm working on this branch: https://github.com/hydroshare/hydroshare/tree/1300-add-to-my-resources-button

**Comment by pkdash** [comment]
@mauriel133 What value you see for 'cm.is_mine'?

**Comment by mauriel133** [comment]
When I try to output the value it's just empty.

**Comment by pkdash** [comment]
I think it probably never worked before. I have to add a new context variable 'resource_is_mine'. So where you are currently using 'cm.is_mine' you have to replace it with 'resource_is_mine'. Let me know when I can pull your branch to make the change.

**Comment by mauriel133** [comment]
I updated the branch with the new context variable name. It is being used here: https://github.com/hydroshare/hydroshare/blob/1300-add-to-my-resources-button/theme/templates/resource-landing-page/top-right-buttons.html#L9

**Comment by mauriel133** [comment]
@horsburgh, the fix for this issue has been deployed to www. Could you verify and close?

**Comment by horsburgh** [comment]
Appears to be fixed on www.hydroshare.org. Closing.
