### ISSUE TITLE
Discover Page - Discoverable filter

### ISSUE THREAD

**Issue by mauriel133** [hydroshare/hydroshare#1307]
Under Filter By Availability, it seems that the item 'Public' works as a superset of the item 'Discoverable'. For example, if I check 'Discoverable' all public resources in the search still show up together with the discoverable ones.

 I think this should be changed to filter only their corresponding sharing status, either 'Public' or 'Discoverable', but not both when 'Public' is checked.

**Comment by xuezhaokun** [comment]
@mauriel133 I agree. It is a reasonable change. As previous discussion with Alva, probably we will remove this filtering option or we can do the change as you suggested. I will take a look at this problem.

**Comment by mjstealey** [comment]
merged and deployed to www
