### ISSUE TITLE
API Create resource doesn't set dublin core metadata

### ISSUE THREAD

**Issue by Castronova** [hydroshare/hydroshare#1309]
In `hs_core/views/resource_api.pi` (line 210), the create_resource function parses a `dublin_metadata` dictionary, but these values don't seem to be saved correctly in `hs_core/hydroshare/resource.py` (line 496)

Test by using the following dictionary for `dublin_metadata`:

```
{"Source": {"derived_data": "some value here"}}
```

**Comment by hyi** [comment]
@Castronova I believe this functionality has been added to REST API by @pkdash recently. Can you test and close this issue if it works now?

**Comment by pkdash** [comment]
@Castronova Test and see if this can be closed.

**Comment by pkdash** [comment]
@Castronova I am closing this.
