### ISSUE TITLE
REST API for creating a resouce needs capability to pass all valid metadata appropriate for a specific resource type

### ISSUE THREAD

**Issue by pkdash** [hydroshare/hydroshare#1313]
Currently a resource can be created using the REST API that allows only passing data for the following three metadata terms:

Title
Abstract
Keywords

This endpoint needs to be changed so that data for all valid metadata terms including the resource specific metadata terms can be passed when calling this endpoint.

Related issue: #1309

**Comment by hyi** [comment]
@pkdash Can this issue be closed now?

**Comment by pkdash** [comment]
Closing as this functionality has been implemented.
