### ISSUE TITLE
Improve the EPA WATERS Services HydroShare App

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#1315]
This comment relates to the EPA WATERS Services app available on https://apps.hydroshare.org/apps/watershed-delin/
- Is there a way to have the Welcome box that opens at the start and provides instructions moveable to position elsewhere on the screen and refer to while following the instructions.
- In step 4 in the instructions please remove the word "permanent".  The resource in HydroShare are not all permanent (majority are not).
- The More Info button links to https://github.com/danames/tethys_watershed_delin.  I prefer not to link to a personal github repository, and in any event this does not clearly provide more info.
- Since the results created are geographic features, it seems it would be best to load them into HydroShare as geographic feature resources, rather than generic resources in KML.  
- The HydroShare GIS app is unable to open the resources loaded by this service, but they are "geographic".
- Spatial coverage in HydroShare should be set for the resources created by this service.
- Some points one clicks at do not work.  I clicked on a random point and was taken to the following that appears to be an NHDPlus stream 
  ![untitled](https://cloud.githubusercontent.com/assets/3456833/16562979/d2775a98-41bc-11e6-8102-2cd8eb9ee332.png)

However delineate watershed results in the following error
![untitled](https://cloud.githubusercontent.com/assets/3456833/16563002/f8a3adb6-41bc-11e6-9c1f-96251a99f2b0.png)
- Basemap tiling and zooming sometimes does not work resulting in a fuzzy picture.
  ![untitled](https://cloud.githubusercontent.com/assets/3456833/16563325/967b6712-41be-11e6-9dbf-9e7d05981309.png)

@danames please take the lead in assigning your team members to address these, as this functionality involves coordination among the apps and functionality your group has developed.

**Comment by aphelionz** [comment]
This issue was moved to CUAHSI-APPS/tethys_watershed_delin#2
