### ISSUE TITLE
Geographic feature create failing on www for single point shapefile

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#1317]
When I try create a geographic feature resource using the attached shapefile on www it fails.  This is reproducible on beta where debug is on and generates the error below.  Since this is a point file with a single point this suggests the error may be due to the north latitude being equal to the south latitude (not strictly greater than).  The system should be tolerant of such instances.

[LoganOutlet.zip](https://github.com/hydroshare/hydroshare/files/350490/LoganOutlet.zip) 

ValidationError at /hsapi/_internal/create-resource/do/

[u'Value for North latitude must be greater than that of South latitude.']

Request Method: 	POST
Request URL: 	http://beta.hydroshare.org/hsapi/_internal/create-resource/do/
Django Version: 	1.8.12
Exception Type: 	ValidationError
Exception Value: 	

[u'Value for North latitude must be greater than that of South latitude.']

Exception Location: 	/home/docker/hydroshare/hs_core/models.py in _validate_coverage_type_value_attributes, line 982
Python Executable: 	/usr/local/bin/python2
Python Version: 	2.7.11
Python Path: 	

['/home/docker/hydroshare',
 '/usr/local/bin',
 '/usr/src/src/python-irodsclient',
 '/home/docker/hydroshare',
 '/usr/local/lib/python27.zip',
 '/usr/local/lib/python2.7',
 '/usr/local/lib/python2.7/plat-linux2',
 '/usr/local/lib/python2.7/lib-tk',
 '/usr/local/lib/python2.7/lib-old',
 '/usr/local/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/site-packages',
 '/home/docker/hydroshare']

Server time: 	Wed, 6 Jul 2016 17:27:29 +0000

**Comment by pkdash** [comment]
@dtarb The following line of code causing the above error:

```if value_dict['northlimit'] <= value_dict['southlimit']:
       raise ValidationError("Value for North latitude must be greater than that of South latitude.")```

If we need to allow northlimit to be same as southlimit, then I need to change it to be like this:

```if value_dict['northlimit'] < value_dict['southlimit']:
       raise ValidationError("Value for North latitude must be greater or equal to that of South latitude.")```

The same kind of changes also need to be done for the eastlimit and westlimit.

**Comment by zhiyuli** [comment]
@pkdash @dtarb 
Current Feature res type does not take this "single point" case into account. It creates "box coverage" metadata for any shapefiles regardless of its geometry type or feature count. In this particular "single point" case, it should create a "point coverage" instead.

But I think changing the "<= " to "<" still makes sense. If we have a shapefile contains only two points (or one single line), and these two points (or this single line) locate at the same longitude line or latitude line, the bonding box is actually a line (east=west or north=south)

**Comment by dtarb** [comment]
Thanks.  I agree it makes sense to use <= in both N-S and E-W tests.  Unless it will cause problems elsewhere, I am OK for the coverage to always be box (a point is a box with equal N, S and E,W bounds), however if setting this as point when both are equal is easy we should do so.

**Comment by hyi** [comment]
@pkdash Can this issue be closed now?

**Comment by dtarb** [comment]
Tested on www.  Closing.
