### ISSUE TITLE
files/ APi for resource data access

### ISSUE THREAD

**Issue by ironfroggy** [hydroshare/hydroshare#132]
GET or PUT individual files, ranges of files, or append to a file

**Comment by hyi** [comment]
@pkdash Do you think this capability is already available in REST API? If so, please close this issue. I am assigning it to @jbradberry for now if it is still an issue.

**Comment by pkdash** [comment]
@hyi Currently GET/POST/DELETE are supported for resource file. PUT yet to be implemented.

**Comment by aphelionz** [comment]
@pkdash Are we still implementing PUT

**Comment by pkdash** [comment]
@aphelionz I would think we need to implement PUT. @alvacouch your thoughts?

**Comment by aphelionz** [comment]
This is a legacy requirement and has been superceded by new functionality. Create new issues if they arise.
