### ISSUE TITLE
script res type landing page error when linked with a webapp

### ISSUE THREAD

**Issue by zhiyuli** [hydroshare/hydroshare#1320]
This issue is reported by Matthew Bayles (a BYU developer who is working on CUAHSI apps).

The script res type works fine by itself. After linking a webapp with script res type, that script res landing page shows an error.

![image](https://cloud.githubusercontent.com/assets/10070599/16635091/f90c402e-438d-11e6-9023-35ec4ed74f8b.png)

**Comment by hyi** [comment]
@zhiyuli Can this issue be closed?

**Comment by zhiyuli** [comment]
tested on www
