### ISSUE TITLE
Remove iRODS user information from public view

### ISSUE THREAD

**Issue by mjstealey** [hydroshare/hydroshare#1322]
The iRODS user information should only be visible to the user and not to the public.
Presently iRODS user state, including username, is visible to all once they are logged in...

Example: logged in as **mjstealey** I can see my own information which is acceptable.

![screen shot 2016-07-07 at 9 46 40 am](https://cloud.githubusercontent.com/assets/5332509/16655313/b917a7e8-4427-11e6-90c1-f5de0dbd5a6a.png)

However, I can also see **Drew's** information... not so acceptable.

![screen shot 2016-07-07 at 9 50 44 am](https://cloud.githubusercontent.com/assets/5332509/16655455/6788ed5a-4428-11e6-92ab-e4200d9e1d9b.png)

This information should only appear to the individual user, not all logged in users.

Assigning @mauriel133 to this, though @hyi may be required for consult due to the iRODS nature of the issue.

**Comment by hyi** [comment]
@mjstealey Fixed this issue together with the issue #1339 in the PR #1341. After they are merged, you can test to make sure both issues will be resolved by that PR.

**Comment by mjstealey** [comment]
verified on beta
