### ISSUE TITLE
delete multiple resources

### ISSUE THREAD

**Issue by yanliu-chn** [hydroshare/hydroshare#1323]
Hi,

Is there a way to delete multiple resources in portal without getting into each one and confirm? I think that will be useful.

Thanks,
Yan

**Comment by horsburgh** [comment]
This is covered by Issue #771 

The plan would be to add a "Delete" button to the My Resources page that would delete any resources that are selected on the page (check boxes for those resources are checked).

**Comment by mauriel133** [comment]
This has been implemented and deployed to www.

**Comment by danames** [comment]
Done in 771
