### ISSUE TITLE
Manage access autocomplete fails for geographic Feature resources

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#1330]
This is a quirky bug.  On www I have created a geographic Feature resource.  I want to add access for another user and click the manage access button.  However when I try enter a name, it does not autocomplete, and as a result I am not able to add access for anyone else.  The manage access works fine for other resource types I have worked with (generic and geographic raster).  To provide access to the resource that exhibits this I had to make it public, as I can not change its access.  To reproduce you will need to download the contents from https://www.hydroshare.org/resource/78f573e7ffb34e568bdf3a8702efcea4/ then create a new resource yourself to try.  This bug also occurs on beta.

**Comment by pkdash** [comment]
@dtarb The problematic resource you have provided seems to be of type geographic feature.

**Comment by zhiyuli** [comment]
@dtarb hmmm...it is weird...the auto-complete works in EDIT mode, not VIEW mode for Feature res.

**Comment by dtarb** [comment]
Pabitra, thanks for noticing the typo in the title and Drew thanks for fixing.

**Comment by hyi** [comment]
@dtarb Can you verify and close if it works now?

**Comment by dtarb** [comment]
Tested on www.  Closing.
