### ISSUE TITLE
Better enforcement of the file download cap of 1 GB

### ISSUE THREAD

**Issue by mjstealey** [hydroshare/hydroshare#1336]
@hyi, @pkdash - Presently the code still appears to attempt to download any sized file (singleton or bag) even when exceeding our 1 GB cap.

The browser hangs on what should be a quick and simple call to determine the size of the requested file and rapidly display the message:
**File larger than 1GB cannot be downloaded directly via HTTP.**
**Please download the large file via iRODS clients.**

Testing this on dev yields a many minute wait period before the message is displayed... 
I suspect that the file is actually being transferred until the 1 GB limit is hit and then displays the message. Need to look deeper into what is going on in the container's temp space to verify this.

**Comment by pkdash** [comment]
@mjstealey It seems from the code that the file size is retrieved first and only if the size is within the limit we get file from irods ('iget'), otherwise display the message. I think the delay may be happening if the bag has been modified and we need to re-create the bag before we can determine the size.

**Comment by mjstealey** [comment]
@pkdash - This does appear to be the case. Tested using: https://dev.hydroshare.org/resource/126bb28f05224636a8bc8b3d1bdad6b5/

This singleton file does generate the appropriate tool tip message:
<img width="1326" alt="screen shot 2016-07-15 at 3 54 41 pm" src="https://cloud.githubusercontent.com/assets/5332509/16886857/9d804dfe-4aa4-11e6-8a48-551606db09eb.png">

On the first click of the bag download for this resource it does simply hang for a number of minutes, generating the bag for the first time, before generating the output message.

On subsequent clicks of the bag download the message does appear immediately.

We may want to look at changing the download icon for resource files larger than 1 GB to an iRODS symbol of some kind. The tool tip can be easy to miss if you're just clicking and not hovering over the download icon for a sufficient period of time.

**Comment by hyi** [comment]
@mjstealey @pkdash Yes, that is exactly what happened. We did not have download size check before, and I added this check and tooltip notification in a haste as part of irods federation work. I agree with @mjstealey this notification interface can definitely be improved. Perhaps @mauriel133 can work on this to make this notification more user-friendly as part of UIUX improvement.
