### ISSUE TITLE
Broken links in "Support" tabs 

### ISSUE THREAD

**Issue by jsadler2** [hydroshare/hydroshare#134]
The "sign in" links in the 'Support' tabs are broken

**Comment by mauriel133** [comment]
Referenced this issue by mistake, corrected it on the correct issue [#124].

**Comment by dtarb** [comment]
@jsadler2 can you please check if these links are still broken when the 1.4 release candidate is deployed.  If fixed, close the issue.  If not work with @mauriel133 to resolve or push to 1.5 deploy so as not to hold up 1.4

**Comment by rayi113** [comment]
Should be fixed now - see http://dev.hydroshare.org/help/
