### ISSUE TITLE
Reply not working

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#1342]
I just tried to reply to a comment on the following resource https://www.hydroshare.org/resource/93f49ab913fd4c639c98ab4a070d20e0/.  Clicking on reply below the comment does nothing, so I had to respond with a new comment.

**Comment by hyi** [comment]
The underlying cause for this issue is the same as https://github.com/hydroshare/hydroshare/issues/1137 - primary key conflict which happens intermittently from time to time as detailed in that issue. So I am closing this one but copy the description for this issue there instead.
