### ISSUE TITLE
Implement create_bag_by_irods() function as a celery task

### ISSUE THREAD

**Issue by hyi** [hydroshare/hydroshare#1343]
For large files including files greater than 1GB limit, create_bag_by_irods() needs to happen regardless of file size to get bag file up to date when downloading or replicating resource bag to iRODS user zone on-demand. Downloading via https has a size limit of 1GB, but create_bag_by_irods() needs to happen to get bag file updated even for files bigger than 1GB so that users can download from iRODS clients.  This function may take a long time to run for large files so it should not block the web thread, and should be implemented as a celery task so that it can be executed asynchronously without blocking the main web thread.

**Comment by pkdash** [comment]
@hyi Can this be closed?

**Comment by hyi** [comment]
implemented and merged, and can be tested on dev, closing.
