### ISSUE TITLE
1.7.3 Beta: popup window does not show up when deleting a mandatory file from Feature Res

### ISSUE THREAD

**Issue by zhiyuli** [hydroshare/hydroshare#1344]
bug found on 1.7.3 Beta: 
popup window does not show up when deleting a mandatory file from Feature Res

**Comment by mjstealey** [comment]
@zhiyuli - can you verify this on beta

**Comment by zhiyuli** [comment]
it works on beta. thanks

**Comment by hyi** [comment]
@zhiyuli Can this issue be closed? If so, please close it.

**Comment by zhiyuli** [comment]
tested on www
