### ISSUE TITLE
Failed to delete the resource content files for NetCDF resource

### ISSUE THREAD

**Issue by gantian127** [hydroshare/hydroshare#1346]
The netcdf header information file is created with a temporary file name, which is not expected. Moreover, when user deletes one of the resource content files, the system will show the following error. 
This bug also exists on www site.

![image](https://cloud.githubusercontent.com/assets/5016511/16971303/d71617c2-4ddf-11e6-939e-f872393f46d7.png)

![image](https://cloud.githubusercontent.com/assets/5016511/16971305/dc833a96-4ddf-11e6-92ac-488fcd03ed6f.png)

**Comment by hyi** [comment]
@gantian127 get_resource_file_name() is in resource.py, not in utils.py, so it looks like this issue can be fixed if you call get_resource_file_name() from resource.py module, not utils.get_resource_file_name().

**Comment by gantian127** [comment]
@hyi Thanks for letting me know. I will change the code to see if this will fix the issue.
