### ISSUE TITLE
Author Name Hyperlinked to HydroShare Account of Resource Creator

### ISSUE THREAD

**Issue by AmberSJones** [hydroshare/hydroshare#1349]
I have created a resource and re-assigned to a different author who is not a HydroShare user. However, that author's name is hyperlinked to my HydroShare account. The hyperlink on the author's name should be removed.
![image](https://cloud.githubusercontent.com/assets/5023186/17024888/c6fdce9c-4f16-11e6-8467-385ee3fb382d.png)

**Comment by horsburgh** [comment]
To be clear - "Elizabeth Ogata", the author's name, is linked to the profile page for the "iUTAH Data Manager" HydroShare user. "Elizableth Ogata" is not a HydroShare user.

@AmberSJones - I'm assuming that when you originally created this resource, you did it under the "iUTAH Data Manager's" account and that you then removed "iUTAH Data Manager" as the author and then added "Elizabeth Ogata" and "Michelle Baker" - neither of which is a HydroShare user.  Is this correct?

**Comment by AmberSJones** [comment]
Yes, @horsburgh is correct. Thanks for clarifying.

**Comment by horsburgh** [comment]
@AmberSJones - @mauriel133 and I discussed this, and here's our approach for a fix. We had made a decision earlier that we would not allow people to modify the URL of the HydroShare user's profile. So, the immediate fix for you is to add a new author that has the name you want (HydroShare user or not) and then delete the iUTAH Data Manager user as an author.  Don't try to modify the iUTAH Data Manger author by changing its name or editing it.

Now, there is still an issue that we will solve by modifying the edit button on an Author that is a HydroShare user. First, we will allow people to add HydroShare users as authors, which will take a snapshot of the information in their profile and paste it into the Author metadata. The edit button will not allow them to edit the author metadata for an existing HydroShare user, but it will allow them to click a button to update the author metadata to the most recent information in the user's profile.  So, the workflow is edit your profile, then update your author information.

**Comment by AmberSJones** [comment]
@horsburgh This sounds good, and we will work to modify the author info on the datasets that we have added. I'll leave the issue open until you address the question of not allowing the edit button to change the author metadata for an existing HydroShare user- unless you have that documented elsewhere.

**Comment by dtarb** [comment]
No change to system needed.  This is a user education issue.  Need to think about messaging.
