### ISSUE TITLE
Inviting to group is either slow or broken on www

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#1351]
I am trying to invite participants to a group on www.  I click send invitation.  Nothing happens.  I click close. The box goes away.  I click invite people again, the box comes back.  If I wait about 20 min (two phone calls) and click invite again, it indicates it was sent.  But we really need to speed this up.

**Comment by hyi** [comment]
@pkdash I am assigning this to you for initial investigation.

**Comment by dtarb** [comment]
Closing this as with current deploy does not seem to be a problem.  Presuming that infrastructure upgrades resolved.
