### ISSUE TITLE
Revise help pages to be consistent with existing functionality

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#136]

**Comment by mjstealey** [comment]
Duplicate of #134 
Fix has been merged into develop branch #135

**Comment by dtarb** [comment]
Even on dev help pages are significantly out of sync with functionality.  For example mentions of groups and my-resources pages.  @rayi113 we need to identify a person to help with this.  Pushing back to milestone 1.5 to not hold up 1.4 deploy.

**Comment by rayi113** [comment]
Updated support page when this pull request goes live on dev: https://github.com/hydroshare/hydroshare/commit/94c27cb1af4fbd80dc8630802d18d9b4537d1d68

**Comment by rayi113** [comment]
Should be fixed now - see http://dev.hydroshare.org/help/

**Comment by dtarb** [comment]
I reviewed the help pages.  They are good to go but will need continued updating as new features get added, like explaining how to use the new resource types.
