### ISSUE TITLE
Suggestions for web app resource type

### ISSUE THREAD

**Issue by gantian127** [hydroshare/hydroshare#1365]
These suggestions are based on the use cases of the OPeNDAP web app resource 
http://www.hydroshare.org/resource/32902798f88040edb4d15f975852afdb

- [ ] Enable the App URL to include the NetCDF file name

- [ ] Enable the web app to show up only when the resource is public or private

- [ ] Change the "App URL" as "App URL Pattern" and change the link as text string, because it is not a real URL link.

**Comment by zhiyuli** [comment]
@gantian127 An  implementation has been deployed on riverdev.hydroshare.org. Please check it out to see if it fits your basic requirements. 
Notes:
1) the new term added for url pattern is ${HS_NETCDF_FILE_NAME}, which represents the full name of the .nc file
2) all webapp resources support any sharing status (Published, Public, Discoverable and Private) by default. user could change it in edit mode

**Comment by gantian127** [comment]
@zhiyuli I just tested the functions. They work as expected. Thanks a lot for your work.

**Comment by dtarb** [comment]
@zhiyuli I think that the functionality needed is a bit different from standard sharing status.  What is needed is for the open with app to only open when the resource is public even if the resource has been shared privately.  The reason for this is that the netCDF functionality only works for public resources.  This is a special case of other instances where there may be functionality only associated with resources that are public, such as OGC web services, or WaterML web services or any web services that do not support access control easily.

**Comment by gantian127** [comment]
@dtarb I think what Drew has implemented allows the situation that when the netCDF resource is shared as "public" and also shared privately with other users, the web app will show up in the resource landing page for that resource.  Here is an example.
https://riverdev.hydroshare.org/resource/50fa9c5b3b5b4263bf4f1752a8b6723c/

The four options listed (Discoverable, Public, Private and Published) is based on the sharing status of the resource. The "Private" means that the resource can only be accessed by assigned users. 
![image](https://cloud.githubusercontent.com/assets/5016511/17268049/e826c3ca-55d9-11e6-898c-9773a5ce76a7.png)

**Comment by dtarb** [comment]
Thanks.  I tested on riverdev and the functionality is correct.  Good work.
