### ISSUE TITLE
Raster zipped VRT upload issue

### ISSUE THREAD

**Issue by shawncrawley** [hydroshare/hydroshare#1367]
When attempting to create a Raster resource from a zipped folder containing a VRT files and its associated TIFs, I kept getting the following error: 

'The .tif files provided are inconsistent (e.g. missing or extra) with the references in the .vrt file.' 

I checked my VRT file and it seemed that everything was fine, although I noted that each SourceFilename had a filename path relative to the current directory (i.e. './filename'). To fix the problem, I deleted the './' in front of each SourceFilename in  the VRT, and re-attempted to create the resource. This time it worked. 

It seems to me that the raster_file_validation function in receivers.py should be modified to overlook the './' since that is how the VRT was automatically generated through gdalbuildvrt. 

Here is the line that triggered the error:
https://github.com/hydroshare/hydroshare/blob/master/hs_geo_raster_resource/receivers.py#L88

Here is the line that would need to be modified:
https://github.com/hydroshare/hydroshare/blob/master/hs_geo_raster_resource/receivers.py#L86

I wouldn't mind making the change, however since you, @gantian127, are already the primary developer of the Raster resource, would this be a fix that you could slip in to other work you are already doing?

**Comment by gantian127** [comment]
@shawncrawley Thanks a lot for reporting the bug. I will fix it.

**Comment by gantian127** [comment]
@shawncrawley Would you please test the fix on playground.hydroshare.org. If you find any problem, please let me know. Otherwise, I will make a pull request. Thank you.

**Comment by shawncrawley** [comment]
@gantian127 It appears to be fixed. Good work.
