### ISSUE TITLE
Question: What becomes of the Users API?

### ISSUE THREAD

**Issue by ironfroggy** [hydroshare/hydroshare#137]
We discussed the problematic Resources API and the non-TastyPie Internal API, but there is also a Users API (the url mappings are below for reference) which handles several things separate entirely from anything under the umbrella of DataOne compliance, so I'm wondering what to do with it. I don't know if this is used, functional, correct, or some combination of the three. The plan was to remove TastyPie, but that might not happen if we have other APIs we need to keep where DataOne compliance isn't an issue. There is no sense in replacing APIs that aren't problems in their current forms, after all.

Please advice. Dave, I'm assigning this question to you expecting you either know the answer or know best who to pass it along to. I hope that's fine procedure.

```
    url(r'^resource/owner/(?P<pk>[A-z0-9]+)/$', views.users_api.SetResourceOwner.as_view()),
    url(r'^resource/accessRules/(?P<pk>[A-z0-9]+)/$', views.users_api.SetAccessRules.as_view()),
    url(r'^accounts/$', views.users_api.CreateOrListAccounts.as_view()),
    url(r'^accounts/(?P<pk>[A-z0-9]+)/$', views.users_api.UpdateAccountOrUserInfo.as_view()),
    url(r'^groups/$', views.users_api.CreateOrListGroups.as_view()),
    url(r'^groups/(?P<pk>[A-z0-9]+)/$', views.users_api.ListGroupMembers.as_view()),
    url(r'^groups/(?P<g>[A-z0-9]+)/owner/(?P<u>[A-z0-9]+)/$', views.users_api.SetOrDeleteGroupOwner.as_view()),
    url(r'^resources/$', views.users_api.GetResourceList.as_view()),

**Comment by dtarb** [comment]
Perfectly fine to assign to me.  Lets also have @horsburgh and @selimnairb involved in the discussion.  We definitely need a user API.  I am not aware of anything that actually uses the user API yet so given the changes to underlying user profile it is likely not working.  There may be one or more unit tests for this API that were written sometime April-June 2014.  @rayi113 may be able to troll through old pivotal tracker records to identify who did these and may be familiar with them.  At this stage I suggest some looking back at what was there, but if it looks like getting bogged down it may be more efficient to start fresh than build on the old stuff.

**Comment by selimnairb** [comment]
Unless we have immediate use cases for these API calls, I suggest we remove them for now, leaving them unimplemented.

**Comment by ironfroggy** [comment]
Resolution: Remove.
