### ISSUE TITLE
bugs in multiple checkbox of SWAT res type

### ISSUE THREAD

**Issue by zhiyuli** [hydroshare/hydroshare#1371]
@mohamedmorsy @jsadler2 
We first found this bug in WebApp res type. Initially some code of the multiple checkbox implementation was copied from the SWAT res type, so we suspect SWAT is having the same bug, and looks like it does.

The bug is: 1) user first checks a model objective and clicks "Save", 
2) then un-checks all options and clicks "Save", 
3) then checks some options and clicks "Save", an error will occur "Error! Metadata failed to update".

The reason is the "update" function in models.py removes the metadata obj if no option is checked: https://github.com/hydroshare/hydroshare/blob/develop/hs_swat_modelinstance/models.py#L86.
When user tries to check some options again, the "Save" button calls "update" the function, but at this time nothing can be updated as the metadata obj is gone already.

In webapp res type we just removed the corresponding lines 85, 86 in your swat code, and looks like it does not break anything in webapp res app so far.

**Comment by hyi** [comment]
@jsadler2 Assigning to you initially, feel free to reassign as needed.

**Comment by jsadler2** [comment]
@zhiyuli thanks for pointing this out. lines 85-86 delete the object if there is nothing in the object. This way, if the user unselects all of the boxes, an empty the metadata term won't appear in the "Resource Specific" page and in the metadata xml document. But that doesn't seem to be happening with the webapp resource type so I will check it out with SWAT.

**Comment by mohamedmorsy** [comment]
@zhiyuli this should be solved now on beta.hydroshare.org.
