### ISSUE TITLE
Certain download buttons lack action/info when either filesize or resource size > 1GB

### ISSUE THREAD

**Issue by shawncrawley** [hydroshare/hydroshare#1376]
I happened upon the bug(s) regarding attempting to download resource bag files and/or individual resource files. There are two resources that will help me illustrate the bug(s). Here is the first:

https://www.hydroshare.org/resource/126bb28f05224636a8bc8b3d1bdad6b5/

This resource is storing one file of 1.6GB.  If I click the "Download All Contents as Zipped BagIt Archive" a page immediately loads with the message: 'File larger than 1GB cannot be downloaded directly via HTTP.Please download the large file via iRODS clients.' This is great; no problem here. However, if I try to click the download button next to the the individual file, then nothing very indicative happens for a while... By that I mean that 1) the informative page mentioned before never comes up, and 2) the browser does show a loading icon in place of the hydroshare icon in the tab, yet that is hardly noticeable. It just seemed like nothing was happening. No message, no alerts, no popups. It made me just want to click the button again... and again, just to make sure. That is a problem.

The same problem mentioned above can also be seen with the following resource, however I'm going to highlight the other problem with it as well:

https://www.hydroshare.org/resource/31f35199a2e548e29786182fbb3e2941/

I would expect, since the cummulative size of this resource is well over 1GB, that when clicking the "Download All Contents as Zipped BagIt Archive" button, I would get the same page immediately loading to inform me that the BagIt archive is over 1GB. However, that never happens. I did get a loading bar in the browser tab, but it remained for a long time until finally a page came up informing me of a '504 Gateway Time-out'. That is a problem. Another odd thing is that even if trying to simply download the 243.8 KB sized file, it takes a very long time (minutes). Luckily, I did not get the 504 error, but still.

I have no idea who to assign to this, so I'll leave that up to someone else.

**Comment by hyi** [comment]
@shawncrawley Thanks for reporting this. I am assigning it to myself and will take a look at this issue.

**Comment by hyi** [comment]
@dtarb @mjstealey @rayi113 I have added a popup "Download Alert" message box being displayed when the user clicks on Download button trying to download a file larger than 1GB as shown below:

![download_warning](https://cloud.githubusercontent.com/assets/476302/17481811/e2afa34c-5d4c-11e6-9bff-05be804e808b.png)
Let me know if you want to modify the alert message to make it more informational for users so that I can incorporate changes before getting the fix into our code develop branch.

**Comment by mjstealey** [comment]
> Let me know if you want to modify the alert message to make it more informational

@hyi - I think once we have proper pages.hydroshare.org documentation for exactly how to use iRODS clients we'll be able to update the text you have with links to the how-to information. Otherwise I think it looks fine.

For how-to's:
- How to create an iRODS user account from your profile page
- How to use Cyberduck to connect to your iRODS user account

**Comment by rayi113** [comment]
For the "How to use Cyberduck to connect to your (HydroShare) iRODS user account"  how-to, there's a start here: https://pages.hydroshare.org/accessing-hydroshare-irods-from-a-windows-pc-or-mac/

**Comment by hyi** [comment]
@mjstealey @rayi113 @dtarb Have added the how-to link for Cyberduck and icommands link, so the popup notification looks like the following now:
![download_alert](https://cloud.githubusercontent.com/assets/476302/17602272/ecb2c9fc-5fd9-11e6-956a-889044347319.png)
After we have the how-to link for how to create iRODS user account in user space, I will add that link then. Let me know if there are any further suggestions. Will create a PR soon to address this issue as well as other large file download issues.

**Comment by hyi** [comment]
@shawncrawley The fix to this issue has been deployed to www. Could you test it out and see whether this issue has been fixed? If so, please close this issue, and if not, please add details on the issues and I will look into them further.

**Comment by shawncrawley** [comment]
It looks good to me. Great work.
