### ISSUE TITLE
[1.7.4 beta] newly created webapp crashes in edit mode

### ISSUE THREAD

**Issue by zhiyuli** [hydroshare/hydroshare#1379]
A newly created webapp on beta crashes when switching to edit mode.
This issue does not affect existing webapps
The same issue is NOT observed on riversdev.hydroshare.org which is supposed to run the same code of webapp.
 
![image](https://cloud.githubusercontent.com/assets/10070599/17493051/e04aadda-5d6b-11e6-9a69-670e176eb0ef.png)

**Comment by zhiyuli** [comment]
@pkdash 
I used debugger to step through the code and I found a weird thing (at least weird to me) that causes this issue:
Say a webapp is just created, by switching to Edit mode:
This line returns a **None** to variable supported_res_types_obj :
https://github.com/hydroshare/hydroshare/blob/develop/hs_tools_resource/page_processors.py#L70
**supported_res_types_obj** = content_model.metadata.supported_res_types.first()

The next line passes in "instance=None" with other parameters.
https://github.com/hydroshare/hydroshare/blob/develop/hs_tools_resource/page_processors.py#L71
supported_res_types_form = SupportedResTypesForm(**instance=supported_res_types_obj**,
                                                         res_short_id=content_model.short_id,
                                                         element_id=supported_res_types_obj.id
                                                         if supported_res_types_obj else None)

But inside the __init__ function of class SupportedResTypesForm, self.instance is not None
https://github.com/hydroshare/hydroshare/blob/develop/hs_tools_resource/forms.py#L133
if self.instance:
   supported_res_types = self.instance.supported_res_types.all()
So the above if statement is True and then it runs its inner code.
at this time visiting self.instance.supported_res_types.all() causes an exception.

**Comment by zhiyuli** [comment]
@pkdash A "try....except....." statement was wrapped outside the above "if statement" before, but we removed it in the code review phase. 

I just tried adding the "try...except " statement back and that could "fix" this issue.

**Comment by pkdash** [comment]
@zhiyuli  If an instance of a model is passed then self.instance is set to that model object. Otherwise, the ModelForm initialization creates a new model of that model and assigns to self.instance. That's why self.instance is never None.

**Comment by zhiyuli** [comment]
tested on www
