### ISSUE TITLE
Failed to upload a file to user irods space using CyberDuck

### ISSUE THREAD

**Issue by zhiyuli** [hydroshare/hydroshare#1397]
Got an error in CyberDuck when trying to upload a file to my irods user space.

![image](https://cloud.githubusercontent.com/assets/10070599/17677316/824bf7e6-62ef-11e6-9423-fc294e30ff08.png)

**Comment by rayi113** [comment]
Have you used Cyberduck successfully in the past, or is this error first time you tried to use it?

**Comment by zhiyuli** [comment]
@rayi113 
Just now when I opened the cyberduck a pop-up showed up saying "a newer version is available". So I updated my cyberduck and then found uploading does not work (downloading still works).

I vaguely remember I could download and upload before.

**Comment by rayi113** [comment]
Default resource might be misnamed - see here: https://github.com/irods/irods/issues/2553  Did you try using this for your CyberDuck profile: https://www.hydroshare.org/resource/87f5341f93b944a7bb6e21c0745cb167/

**Comment by zhiyuli** [comment]
@rayi113 I will redo the configuration following this instructions: https://pages.hydroshare.org/accessing-hydroshare-irods-from-a-windows-pc-or-mac/

will keep you updated on this. thanks

**Comment by zhiyuli** [comment]
@rayi113 OK, it is working now. I thought I was using an old profile file that has some deprecated settings. 
I am going to close this issue. Thanks.
