### ISSUE TITLE
Put bag replication to iRODS user zone to async task framework

### ISSUE THREAD

**Issue by hyi** [hydroshare/hydroshare#1404]
This is a follow-up issue to issue #1343 and will be tackled after the PR #1392 is deployed which makes`create_bags_by_irods` a celery task that can be executed asynchronously with bag download view function calling this celery task to run it asynchronously.

**Comment by pkdash** [comment]
@hyi Can this be closed now?

**Comment by hyi** [comment]
Just a note here for bookkeeping purposes. For gigabyte large files whose bag need to be recreated, it does take a long time for the bag to be regenerated when users try to replicate the bag to their user zone space, as observed by @mjstealey when he tried to resolve a bag download issue for this resource https://www.hydroshare.org/resource/ff2e648104254ee4bcf8db925170ea91/ which is about 3GB in size. Users have to replicate resource bag to their user zone in order to download it using iRODS client, and if the bag needs to be recreated, it takes a long time when replicating due to the bag creation time which is still a synchronous call. It'd be better to inform users in the similar way as big file async download, so this issue still needs to be worked on and I will put it on my to-do list and work on it when I have time.

**Comment by Castronova** [comment]
@hyi Have the recent async changes addressed this?

**Comment by hyi** [comment]
@Castronova Not yet, but this is the next item on my to-do list to implement in the async framework.

**Comment by hyi** [comment]
Deployed. Closing.
