### ISSUE TITLE
isCopiedFrom missing in terms list

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#1407]
The term hsterms:isCopiedFrom is missing in https://www.hydroshare.org/terms/ but is used in metadata of at least one model program resource.  I thought all hsterms were supposed to be defined on this page (or am I missing something).  This came up when reviewing paper by @mohamedmorsy that uses this term.

**Comment by horsburgh** [comment]
@dtarb - If it's being used, it just needs to be added to the namespace document along with a definition. 

@pkdash - is this something you can quickly add?

**Comment by pkdash** [comment]
@mohamedmorsy Can you implement this minor fix?

**Comment by mohamedmorsy** [comment]
@pkdash will do

**Comment by mohamedmorsy** [comment]
This issue has been resolved. @dtarb could you please close this issue?

**Comment by dtarb** [comment]
Thanks
