### ISSUE TITLE
Async downloading impacts on RefTimeSeries

### ISSUE THREAD

**Issue by zhiyuli** [hydroshare/hydroshare#1408]
@hyi  I just talked to @pkdash  about the changes needed for REST client to fit async downloading . And I  just realized the RefTimeSeries code on hydroshare side needs to change as well. This is because RefTS is using a different way to download its bag. When a RefTS res is created, an "empty" bag is created on irods with only metadata (xml) in it (like collection). When a user clicks the "download button", the backend does the following things:
1) download the "empty bag" to django site using django_irods.download()
2) download latest WaterML file (contains time series data) from referenced url
3) put this waterml file into the bag
4) return this filled-in bag to frontend.

Since the django_irods.download() is already changed to run as a async task, the above step (1) needs to change as django_irods.download() will return a task id instead of the bag file stream. This is doable. But in the case of RefTS, all the bags are "empty bags". Using async in step (1) wont get much performance improvement but will add more complexity.  

I am thinking is it possible to retain the traditional sync call as an option in django_irods.download().
We could add a new parameter to django_irods.download(): useAsync=True. Its default value is True that means it uses async call by default. But if we pass in useAsync=False, the django_irods.download() can perform traditional sync call just as before.

If this change can be done to django_irods.download(), I just need to add that new parameter "useAsync=False" in step (1) and it will continue using sync call to get the "empty bag".

**Comment by pkdash** [comment]
@zhiyuli I think this needs to be done in a higher priority.

**Comment by zhiyuli** [comment]
@pkdash I already checked with @hyi , she will add the sync call back to django_irods.download() as an option ASAP.

**Comment by hyi** [comment]
@zhiyuli @pkdash Will work on this tomorrow morning.

**Comment by hyi** [comment]
@zhiyuli Could you verify this on beta and close the issue if things are working as expected now?

**Comment by zhiyuli** [comment]
tested on beta. closed
