### ISSUE TITLE
Group resources landing page message says no resources shared when a resource has been shared.

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#1409]
I shared a resource with a group.  It shows up on the group resources list.  But the page still indicates no resources shared with the group.

![untitled](https://cloud.githubusercontent.com/assets/3456833/17944509/4793eac2-69fd-11e6-9bc8-7ccfe6a331fe.png)

**Comment by pkdash** [comment]
@dtarb Check if this can be closed.

**Comment by dtarb** [comment]
Appears to be fixed.
