### ISSUE TITLE
Got the "Invalid publisher name" error when Publishing a Collection

### ISSUE THREAD

**Issue by zhiyuli** [hydroshare/hydroshare#1410]
A reminder: the "Publish" feature on Collection res needs more debugging and testing.

**Comment by zhiyuli** [comment]
@pkdash 
I would like to check with you about the design before fixing this bug. Is the following statement correct? 

Under NO circumstances may users add/edit/remove this "Publisher" metadata directly. 
HS system creates this metadata automatically when a res gets published. The value of publisher "name" is always 'Consortium of Universities for the Advancement of Hydrologic Science, Inc. (CUAHSI)',  and value of "url" is always 'https://www.cuahsi.org'

**Comment by horsburgh** [comment]
@zhiyuli - I would say that your statement is true as long as HydroShare and CUAHSI are the publisher (which is the only option right now). In the event that HydroShare partners with another publisher, there might be another option, but the user should not be editing the "Publisher" element - it should get set automatically.

**Comment by pkdash** [comment]
@zhiyuli Currently if the resource to be published  has content files then CUAHSI can only be the publisher. If a resource to be published has no content files, it is possible to programmatically set  anyone else as the publisher for that resource. That's the current logic of the ```create``` function of the Publisher element.

**Comment by pkdash** [comment]
@zhiyuli Is this still an issue? Otherwise, close it.
