### ISSUE TITLE
Bag checksum compliance issues

### ISSUE THREAD

**Issue by hyi** [hydroshare/hydroshare#1418]
@horsburgh noticed the following two bag checksum compliance issues when validating new implementation of time series:
1. checksum algorithm used should match what is in the file name
2. The order in each line of the checksum files should be reversed to comply with bagit specification in the format of "CHECKSUM FILENAME"

Will modify the iRODS bagit rule to resolve the two compliance issues above. Also need to set bag_modified AVU metadata to true so that all bags will be regenerated when being downloaded.

**Comment by horsburgh** [comment]
@hyi - one other thing that I noticed was that there is a string "SHA2:" prepended onto each of the checksum values in the file. Is that part of the checksum? Can you check the text of the BagIt spec to see if this is allowed?  

https://tools.ietf.org/html/draft-kunze-bagit-05#section-2.1 

There's some technical language in there that I wasn't completely sure about("CHECKSUM is a hex-encoded checksum..."). See section 2.1.3.

**Comment by hyi** [comment]
@horsburgh Good point. The checksum string including "SHA2:" is created from the iRODS microservice directly. I will have to dig into the microservice source code to verify this. Will confirm tomorrow.

**Comment by hyi** [comment]
@horsburgh I have scanned through relevant iRODS code for checksum generation and found the checksum string we currently get is base64 encoded sha256 checksum prefixed with "SHA2:" I have emailed iRODS folks with some questions regarding this, and will modify the rule accordingly after I receive response from them. In the meantime, I want to run by you whether we need to change the file names to be ```manifest-sha256.txt``` rather than ```manifest-sha2.txt``` just to be a bit more specific on the hash algorithm we use for creating checksum since sha256 is just one algorithm in sha2 family.

**Comment by horsburgh** [comment]
@hyi - yes, let's be specific. If it's "sha256" then lets call it "manifest-sha256.txt".

**Comment by hyi** [comment]
@horsburgh I have not received response from iRODS folks, but I have dig into their code and understand how checksum is computed by the microservice. After hex-encoded checksum is computed, the iRODS microservice explicitly base64-encode the checksum, then prepend the "sha2:" prefix to it. I can easily remove "sha2:" prefix, but to recover the original hex-encoded checksum, base64-decoding has to be run followed by hexdump, which can be done outside iRODS using command line utilities, but needs some work if we want to do it directly in iRODS, I think, either by modifying their existing microservice, writing a new microservice, or writing a new script to do decoding and hexdump to be invoked from the iRODS rule with the script residing on iRODS server side. Doing latter will involve coordination with iRODS folks and some effort and time on my side to get it to work eventually. Before we go along that route, I want to confirm with you whether base64-encoded checksum is acceptable by bagit specification. I did find something here: http://www.digitalpreservation.gov/documents/bagitspec.pdf, which toward the end of the page on section A6 mentions ```Fixed checksum encoding reference to base64 rather than hex.``` So there might be a possibility that bagit spec allows to base64 encode checksum. Perhaps we can name the manifest file to "manifest-sha256-base64.txt" to indicate that? Please advise.

**Comment by hyi** [comment]
@horsburgh Could you test this on beta.hydroshare.org to verify the bag compliance issue has been resolved? Let me know if you observe any further issues. If everything looks good now, you can close this issue. Thanks.

**Comment by hyi** [comment]
@horsburgh Just a clarification note, we are going back to MD5 hash algorithm now which is hex checksum without base64 encoding. We just need to explicitly set hash algorithm to MD5 in iRODS client and server since the default hash algorithm is SHA256 in iRODS which is base64 encoded which does not comply with bagit spec.

**Comment by horsburgh** [comment]
@hyi - I downloaded a resource and checked the manifest files. Things look like they are in the right order. I calculated a couple of MD5 checksums for a couple of the files locally and they match what is in the manifest file.  So, this looks good to me.

**Comment by hyi** [comment]
@horsburgh Thanks for the thorough testing. I am closing this issue then.
