### ISSUE TITLE
Spanish accents not supported

### ISSUE THREAD

**Issue by felherc** [hydroshare/hydroshare#1424]
I created a HydroShare account and my last name has a Spanish accent: Hernández. I would get an error every time I wanted to see a resource I had created. I removed the accented character on my account name and now I can access resources I create after that, but I still cannot access those created before the change. These special characters should be supported throughout the entire system.

**Comment by dtarb** [comment]
@mauriel133 are you able to address this?

**Comment by mauriel133** [comment]
Yes, I'll look into it.

**Comment by mauriel133** [comment]
@pkdash, I'm assigning this to you as we discussed for investigation.

**Comment by pkdash** [comment]
@dtarb It seems this issue has been resolved based on my testing. Let me know if I can close it.
