### ISSUE TITLE
Modflow Model Instance Phase 2

### ISSUE THREAD

**Issue by jsadler2** [hydroshare/hydroshare#1428]
Phase 2 for implementing the Modflow Model Instance resource type. 

The main enhancement for this phase is the automatic completion of some metadata fields based on uploaded file content. Other enhancements may include reorganizing metadata layout in edit view.

**Comment by pkdash** [comment]
@jsadler2 Can you put a priority label for this issue (available options: High, Medium and Low)?

**Comment by pkdash** [comment]
@jsadler2 Is this going to be part of release 1.10.0?

**Comment by jsadler2** [comment]
@pkdash we are first focusing on #1815 so I think we should plan on this going out on the next release.
