### ISSUE TITLE
Unit tests fails occassionally

### ISSUE THREAD

**Issue by pkdash** [hydroshare/hydroshare#1433]
This unit test `test_refts_creation_via_rest_api()` seems to fail occasionally due the code that trying to access an external website.

**Comment by zhiyuli** [comment]
@pkdash  you have snapshot or log on those failing test cases? thanks

**Comment by zhiyuli** [comment]
@pkdash 
I think I am seeing it right now. it happened on my PR for collection
![image](https://cloud.githubusercontent.com/assets/10070599/18317792/641bdf62-74dc-11e6-8c0c-25d247b9b2f3.png)

Error Message

500 != 200
-------------------- >> begin captured logging << --------------------
requests.packages.urllib3.connectionpool: INFO: Starting new HTTP connection (1): data.iutahepscor.org
requests.packages.urllib3.connectionpool: DEBUG: "GET /LoganRiverWOF/REST/waterml_1_1.svc/datavalues?location=iutah:LR_WaterLab_AA&variable=iutah:WaterTemp_EXO&startDate=2014-12-02T19:45:00Z&endDate=2014-12-05T19:45:00Z HTTP/1.1" 500 1047
--------------------- >> end captured logging << ---------------------
Stacktrace

  File "/usr/local/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/hydroshare/hs_core/tests/api/rest/test_create_resource.py", line 347, in test_refts_creation_via_rest_api
    self.assertEqual(response.status_code, status.HTTP_200_OK)
  File "/usr/local/lib/python2.7/unittest/case.py", line 513, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/local/lib/python2.7/unittest/case.py", line 506, in _baseAssertEqual
    raise self.failureException(msg)
'500 != 200\n-------------------- >> begin captured logging << --------------------\nrequests.packages.urllib3.connectionpool: INFO: Starting new HTTP connection (1): data.iutahepscor.org\nrequests.packages.urllib3.connectionpool: DEBUG: "GET /LoganRiverWOF/REST/waterml_1_1.svc/datavalues?location=iutah:LR_WaterLab_AA&variable=iutah:WaterTemp_EXO&startDate=2014-12-02T19:45:00Z&endDate=2014-12-05T19:45:00Z HTTP/1.1" 500 1047\n--------------------- >> end captured logging << ---------------------'

**Comment by pkdash** [comment]
@zhiyuli I am not sure how you would mock the call the that URL. We may already have code that do mocking in other unit tests.

**Comment by zhiyuli** [comment]
@pkdash 
I skipped this test case in that PR for collection as this failing test is not related to collection and I dont want to hold that PR.

The url in that failing test only returns a wml file. If we could host that wml file locally and make up a local url for it, that would fix it I believe. Any idea how we can make up a local url for a local wml file?

**Comment by pkdash** [comment]
@zhiyuli Then just store that wml file somewhere under the tests directory and use it directly without the need for http call to retrieve that file.

**Comment by zhiyuli** [comment]
@pkdash 
I can save that wml file locally but we have to give it a url. The purpose of this test case is to test creation of a  RefTS res through rest api, which is expecting for a url as a required input parameter.

I am trying to save the wml as a static file and use "/static/file.xml" as the url.

**Comment by pkdash** [comment]
@zhiyuli I assume this line is causing the problem: ```response = requests.get(ref_url)```

Instead of using the ```requests``` try using the ```self.client.get(ref_url)``` that's (self.client)  what has been used everywhere else in rest testing code for http request.

**Comment by zhiyuli** [comment]
@pkdash 
you mean keep using the external url and changing requests.get(ref_url) to self.client.get(ref_url)?
I am assuming the error was caused by the instability of that external url

**Comment by pkdash** [comment]
@zhiyuli Now I realize that won't work. I think we have to mock the call to ref_url. See the testing code in hs_restclient for some idea how to mock a function/service call.

**Comment by zhiyuli** [comment]
@pkdash 
I am thinking instead of mocking up external url access in rest api test cases, the RefTS code itself should provide a "test mode".  Some thing like if user passes in a parameter "test_mode: True", the refts will use a locally pre-stored wml sample file directly, instead of querying external url to download wml on the fly. 

Then we could simply add "test_mode: True" to that failing test, which should be able to fix it.
What do you think?

**Comment by cuahsimarko** [comment]
Unit tests don't fail regularly
