### ISSUE TITLE
Error with the "Extended Metadata" tab for SWAT Model Instance resource type

### ISSUE THREAD

**Issue by mohamedmorsy** [hydroshare/hydroshare#1440]
For the SWAT Model Instance resource edit mode view, The "Resource Specific" tab includes the ability to added extended metadata entry which should be included under the separate tab "Extended Metadata".

![image](https://cloud.githubusercontent.com/assets/5543781/18329184/42591e5a-7520-11e6-8574-a5c3c50e0b23.png)

The "Extended Metadata" tab content is exactly the same as "Resource Specific" tab content

![image](https://cloud.githubusercontent.com/assets/5543781/18329194/49307f70-7520-11e6-827d-bde8ffe7298a.png)

**Comment by mjstealey** [comment]
merged
