### ISSUE TITLE
MODFLOW Model Instance does not have an icon 

### ISSUE THREAD

**Issue by mohamedmorsy** [hydroshare/hydroshare#1447]
@mauriel133 could you please create an icon for the MODFLOW Model Instance resource type?

![image](https://cloud.githubusercontent.com/assets/5543781/18449636/e3b9a090-78fd-11e6-988b-203f5504e0fa.png)

**Comment by horsburgh** [comment]
@mohamedmorsy - any quick thoughts on what that icon should look like to get @mauriel133 started?

**Comment by mohamedmorsy** [comment]
@horsburgh @mauriel133 SWAT model instance resource icon was inherited from the generic model instance icon by changing the icon color and adding a tag for SWAT. We can do the same for the MODFLOW model instance resource by using the same icon for the generic model instance but with different color and adding a tag "MODFLOW".............

**Comment by mauriel133** [comment]
Will do.
