### ISSUE TITLE
add a "resource list text file" to collection res

### ISSUE THREAD

**Issue by zhiyuli** [hydroshare/hydroshare#1451]
Paste here "Collections summary" from @dtarb as a reminder.
Strikethrough indicates features have been implemented.
This issue will be focusing on the "resource list text file" section in bold.

"
Jeff, Christina, Drew, Jimmy,

Reflecting a bit on the discussion about collections, it seems like we have come full circle on collections and I worry that we have wasted time.  But hopefully we have got to a better solution, and I appreciate all your patience on this. Following the call, discussion continued with Pabitra and here is where I think the discussion should have ended.  If you can live with this, I’d like this to be a decision.

Collection resource type
1.       Need additional functionality to do a full download that is limited to resources a user has access to view (view includes public).  The current specification says that this should be in a single Bagit Bag, but Pabitra suggests it need not be formally built into a bag and can just be a zip file with bagit folders for each contained member resource.

~~2.  Automatically add hasPart reference whenever a resource is added to a collection, and automatically delete this hasPart reference whenever a resource is removed from a collection~~

~~3.  Adding or removing a resource from a collection has no impact on the on disk metadata of the member resource.~~

~~4.  Independent deletion of a member resource does not automatically propagate to the collection.  Instead when the collection is viewed that resource appears in the deleted contents list which a user with edit permissions can clear.~~

~~5.       Need to add functionality to implement logic rules for collection #2 that limits resources that can be added to a collection to those with shareable flag set to true. [This was not discussed today and remains the same as decided in the document earlier]~~

Resources that are a member of a collection
~~1.  Need to modify the landing page to show collections that the resource is a member of.  This could be under the Related Resources tab, or a separate “Connections” tab that may be usable for additional future functionality too (such as listing resources that have cited this resource if/when we implement citation functionality).  The landing page will draw this information from the Django database, so we do not implement the isPartOf relationship.~~

Resource List Text File [This modifies/simplifies my earlier suggestions related to this file]
~~1.       Develop the capability to generate on the fly a resource list CSV text file that lists Title, Owners, Type, URL of the member resources similar to the collection contents displayed on the collection contents part of the collection resource landing page.  Provide a button “Download list” that allows users to download this file.  Deleted resources are part of this text file.  The on the fly generation ensures that this list is in sync with any title or owner changes to member resources.~~

Bagit considerations
**1.  Change the button “Download Collection Bag” to “Download Collection List Bag” that provides in Bagit format the resource list text file and other metadata files that are normally part of the bag.  This always generated on the fly (as it is a small text file so bagging should not be onerous) to maintain synchronicity with any member resource title or owner changes.**
2.  Implement a “Download Accessible Resources” button next to this that on the fly generates and provides download of the zip file in item #1 of collection resource type above.  This to include the resource list text file, but following suggestions by Pabitra, not to be in formal Bagit format.

Note that implementation of the resource list text file could be deferred if choosing to stage this implementation.

I hope we are close.

Dave
"

**Comment by zhiyuli** [comment]
@dtarb 
An implementation of the "resource list txt file" has been deployed on riverdev.

![image](https://cloud.githubusercontent.com/assets/10070599/18678936/e2fcaf26-7f1a-11e6-8685-f4f2ed275e44.png)

The csv gets generated and saved into bag as a resource file on the fly when user clicks the download btn. Its contents reflects the latest info of contained resources.

**Comment by dtarb** [comment]
Nice work.  From experimenting with this in riverdev I have the following suggestions:

1. In the downloaded CSV I think ID is redundant since the ID is part of the URL.  So I suggest to not include the ID column.
2. It is a bit odd to include deleted resources in the list downloaded but I respect retaining this until the owner clears this.  If the ID column is deleted the URL column would need to retain the ID, rather than indicate Resource Deleted.  Resource Deleted should still be indicated in the Sharing Status column.
3. When a user with edit permissions clicks on "View deleted contents" the box that opens should display the button "Clear and Update Bag" without requiring them to go into edit mode.
4. When there are multiple owners I suggest separating them with comma's and having the entire list of owners in quotes, rather than the & sign.  In other words change David Tarboton&Dave Tarboton tp "David Tarboton, Dave Tarboton"

**Comment by zhiyuli** [comment]
@dtarb 
I am thinking the 'ID' column has some value in at least one use case: user writes a script to parse that csv in collection bag and then uses hs_restclient to retrieve data for each contained res. 
Since some hs_restclient functions need "res_id" as a input parameter, user can get the value of res_id from the "ID" column more easily than extracting it from the "URL" column.

**Comment by dtarb** [comment]
It is just a suggestion.  You are free to ignore it.

**Comment by zhiyuli** [comment]
@dtarb 
OK,
(1) and (2) are ignored with explanations provided above.
(3) and (4) are implemented and being pushed to riverdev

**Comment by pkdash** [comment]
@dtarb See if this should be closed.

**Comment by dtarb** [comment]
I tested this and downloaded a resource with multiple owners.  I found that there are three quotes around the owner list.  This seems too many.  One would be enough.

![capture](https://cloud.githubusercontent.com/assets/3456833/19323487/69023792-907a-11e6-8191-8764031171e1.JPG)
