### ISSUE TITLE
Make URLs in Resource abstract clickable

### ISSUE THREAD

**Issue by hyi** [hydroshare/hydroshare#1453]
This is at the request of @rayi113 so users can put URLs in the abstract of a hydroshare resource and click to go to an external page such as a THREDDS server page.

**Comment by horsburgh** [comment]
Is there a Django plugin of some sort that supports Markdown formatting.  Something like this box I'm typing in right now for instance?

**Comment by mjstealey** [comment]
merged and implemented on www manually

**Comment by hyi** [comment]
@horsburgh There are markdown editors built for Django such as this one: https://github.com/adi-/django-markdownx It will take time to get it in and investigate to make it work with our Django environment seamlessly, though.

**Comment by horsburgh** [comment]
@hyi - OK. This issue is closed, but I think there is another open issue about text formatting in the Abstract element, so it should get addressed there.
