### ISSUE TITLE
Help page navigation 

### ISSUE THREAD

**Issue by ChristinaB** [hydroshare/hydroshare#1456]
The Help navigation needs to be updated so that the nested organization expands as needed. In it's current state, the list of pages extends down the page into oblivion.  The update should be consistent with other navigation look and feel on Hydroshare if possible.  Thanks!!
See main page - https://pages.hydroshare.org/

**Comment by dtarb** [comment]
Can you produce a mock up of what you think the help page should look like.  I am not sure there is consensus on whether this is about providing information to users on how to use hydroshare, or getting users to help us.  I think the former should be the first (rapid) implementation, and the latter could come after a bit more deliberation.
