### ISSUE TITLE
Help page interaction

### ISSUE THREAD

**Issue by ChristinaB** [hydroshare/hydroshare#1457]
The welcome page for Help needs to be updated.  CUAHSI has agreed to help us develop content that they will help manage to extend the user information collection that may help guide software design and priorities.  This is a link to an extended survey taken by the CUAHSI users committee. 
Survey link: https://goo.gl/forms/YXsDscvcfJybuwJ82
The idea is to take one or two questions from this survey and put them on the front page. 
A question like: Which Hydroshare functionality is most helpful for your research??
![image](https://cloud.githubusercontent.com/assets/4108369/18714644/4846082c-7fcb-11e6-8b15-8b5c8d1d6ff4.png)

**Comment by ChristinaB** [comment]
We can also then collect emails for listserv communications.

**Comment by ChristinaB** [comment]
The need/request is to build in the functionality to collect data from the Help welcome page. This will be updated and designed in collaboration with CUAHSI staff and Users Committee to collect more frequent information and engagement with a broader group of users.

**Comment by ChristinaB** [comment]
I don't know if the listserv request needs to be a different issue. My understanding is that we don't want to use a third party mail server to spam users, but manage it internally. This may warrant further discussion.

**Comment by dtarb** [comment]
This issue does not have enough specificity and touches too many subjects to be actionable.

**Comment by ChristinaB** [comment]
My current suggestion is to use this example (http://help.osf.io/)  that does not require any user interaction. Most help pages that I researched (and Jeff suggested) are populated by user interactions with customer service departments that grow as users have issues and questions.  

The OSF Framework is the closest Help resource to the help we can currently provide, so I suggest using infographics that provide a front page matrix for users to navigate to Help topics. 

If we go this route we can postpone this issue until we are ready to integrate user questions to a centralized support system.
