### ISSUE TITLE
Error loading netCDF resource

### ISSUE THREAD

**Issue by BrianOBlanton** [hydroshare/hydroshare#1458]
Hello Hydroshare,  I'm trying to add a new netCDF resource that happens to have variable attributes with long (100+) characters.  This appears to throw this error: 

Validation Error: value too long for type character varying(100)

Is it possible to have this dimension extended?  

Cheers,
Brian

**Comment by gantian127** [comment]
@BrianOBlanton I will fix it and let you know when it is finished. Thanks for reporting the bug.

**Comment by gantian127** [comment]
@BrianOBlanton would you please test on https://testservices.hydroshare.org/ to create a new NetCDF resource? The bug fix extended the maximum character length to 1000.  If the new extension can't satisfy the requirement of your netCDF file, please kindly let me know. Thanks.

**Comment by dtarb** [comment]
@gantian127 @pkdash is it possible to have a variable type that does not have a bound for quantities like this.  Every time a number is picked, someone always finds a need for it to be bigger.

**Comment by pkdash** [comment]
@dtarb It is possible, but not sure of database performance if we make all database string type fields set to unlimited length.

**Comment by pkdash** [comment]
@gantian127 I assume this has been implemented. If so close this issue.
