### ISSUE TITLE
How can I delete a group

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#1462]
I created a group today while demonstrating HydroShare to a potential user.  I said I would delete to clean up when we are done.  But there is no delete button.

**Comment by mauriel133** [comment]
If I remember correctly I asked for this feature while developing the group's front end functionality, but it wasn't ready yet. We implemented a way to deactivate the group in the meantime which hides it for everyone else but the owner. I think this should be implemented.

@pkdash might know more.

**Comment by pkdash** [comment]
Last time when we discussed deleting groups I think we didn't want to delete groups due to provenance issues. @alvacouch may remember.

**Comment by dtarb** [comment]
I think that @alvacouch preferred not to delete groups as that would lose provenance.  I think that we should retain the "inactive" functionality, but label it "delete" and when a group is deleted hide it from all interfaces except the owners my groups page after they click a button show deleted.  An owner once they have opened "show deleted" should be able to "restore" the group (activate functionality).

**Comment by dtarb** [comment]
Tested.  Closing
