### ISSUE TITLE
HydroShare GIS not finding rasters

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#1463]
I tried a demo today that has worked before.  I created a raster resource, and attempted to open with HydroShare GIS.  I get the error "the resource was not found on hydroshare"

**Comment by shawncrawley** [comment]
The issue has been fixed. The hs_restclient was pointing at beta.hydroshare.org since I had done some testing against that server, but has now been switched to point back at www.

**Comment by danames** [comment]
Shawn/Dave, I think it's time to implement a formal release policy for apps
on apps.hydroshare.org so that we can avoid these kinds of issues in the
future. We'll work on a strategy here and share with the team on Wednesday.
- Dan

**Comment by dtarb** [comment]
OK. Closing.
