### ISSUE TITLE
>1GB Resource Creation from iRODS Fails

### ISSUE THREAD

**Issue by rayi113** [hydroshare/hydroshare#1467]
When one uploads a >1GB file into users.hydroshare.org and attempts to create a HydroShare resource from said file, it fails with the message "Error.  Sorry, an error occured."  Small files work though.

**Comment by hyi** [comment]
@rayi113 This has been fixed and the fix has been manually applied on www. It appears to work as expected on www based on my testing. Can you test to see if it works now, and if it works, close this issue?

**Comment by rayi113** [comment]
@hyi @mjstealey Yes, works now on www.  Thanks very much!
