### ISSUE TITLE
Allow using existing units for TimeSeries Result element editing

### ISSUE THREAD

**Issue by pkdash** [hydroshare/hydroshare#1472]
This would apply only incase of CSV upload. Once the user enters data for "Units type", "Units name" and "Units abbreviation" for a given TimeSeries Result element, the system needs to allow the user to copy this data when entering data for another TimeSeries Result element.

**Comment by Castronova** [comment]
@horsburgh close or act if needed.

**Comment by horsburgh** [comment]
I'm going to say this is pretty low priority right now and can be closed. It's a convenience functionality and shouldn't affect existing functionality if we don't  get it.
