### ISSUE TITLE
Provide help text for time series metadata element form fields.

### ISSUE THREAD

**Issue by pkdash** [hydroshare/hydroshare#1473]

**Comment by horsburgh** [comment]
@pkdash - this is important. I'm assuming we can do this after you do the initial deployment?

**Comment by pkdash** [comment]
@horsburgh If you give me the help text for each of the metadata element form fields, I will try to do it on Monday.

**Comment by horsburgh** [comment]
@pkdash - as part of the time series documentation, I wrote definitions of each of the metadata elements for the time series resource that could be used as hover/help text on the edit page for time series. See the Google Doc at: 

https://docs.google.com/document/d/1Cte984eak5-jvksHgI8R6TKYCSgzN9S1u3AvpFvIxLg/edit

See the section titled: What do all of the resource specific metadata elements for Time Series mean? Some of the text may be a little long, but let me know if what I wrote would be sufficient for what you need on this issue.

**Comment by pkdash** [comment]
@horsburgh I will try to implement this soon.

**Comment by pkdash** [comment]
@horsburgh This has been implemented now. You should be able to test it tomorrow on dev.hydroshare.org.

**Comment by mjstealey** [comment]
presumed to be done
