### ISSUE TITLE
Error associated with resource files

### ISSUE THREAD

**Issue by AmberSJones** [hydroshare/hydroshare#1476]
I have a resource for which I cannot open some of its files. I get a screen saying that an error has occurred. I tried to remove the files to re-upload them, and I get them same error when I try to remove the files.

**Comment by dtarb** [comment]
How long are the file names?  This may be the same as #1474.

**Comment by AmberSJones** [comment]
They are long, so it is likely the same issue. Feel free to mark as duplicate- I don't have the permissions.

**Comment by pkdash** [comment]
@hyi Has this been addressed already?

**Comment by hyi** [comment]
@pkdash Yes, it has been merged to develop. I will ask @dtarb to test after it is pre-deployed to beta.

**Comment by dtarb** [comment]
Done
