### ISSUE TITLE
inconsistency between resourcemap.xml and actual access URLs

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#1483]
@pkdash @hyi 
I'm working with a dev instance in SSL mode and have discovered an anomaly. When HydroShare puts a URL into a resourcemap, it always uses the non-SSL TCP port for it. However, when running in SSL, it isn't available at that port. The hs_restclient knows this and ignores that URL and constructs its own. 

URLs that aren't actually pointing to the resource are of limited usefulness. We need to construct URLs that we're actually using!

**Comment by Castronova** [comment]
@alvacouch please close or act if needed.

**Comment by alvacouch** [comment]
This is a deep issue that remains to be addressed.  As commented in later issues, the generation of URLs remains inconsistent between production and beta deployments, and is inconsistently implemented.

**Comment by eclark-cuahsi** [comment]
@alvacouch should we address this issue as a bug or is it an enhancement?

**Comment by dtarb** [comment]
Scott indicated that URLs in resource map are being used successfully, so suggests closing.
