### ISSUE TITLE
small bugs in REST URL definitions

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#1484]
There are several small but annoying bugs in the definitions of REST endpoints. 
1. The  regular expression pattern [A-z0-9]+ for a GUID is incorrect. This matches the characters [ \  ]  ^  _  ` which are between Z and a and cannot be part of a GUID. The correct pattern is [A-Za-z0-9]+. 
2. in _internal/group_membership, (hs_core/urls.py), the pattern (?P<token>[-\w]+) matches more or less anything! Be more specific about what a token should contain. Likewise for (?P<uidb36>[-\w]+), which should be (?P<uidb36>[A-Za-z0-9]+) as explained above. I suspect that these are broken even now.
3. The current REST file access patterns do not support folders. To do this, the pathname must be a trailing pattern allowing /'s, e.g., [A-Za-z0-9_-. /]+ (to allow '_', '-', '.',  spaces in filenames). We should be very careful to be consistent about what we allow, both here in the URL and in the implementation. The current filename patterns do not allow special characters in file names. The current file pattern is [^/]+ which means anything except /. This is definitely not what we want.

**Comment by alvacouch** [comment]
@hyi @pkdash I am starting to document the things I have found as issues.

**Comment by alvacouch** [comment]
@hyi @pkdash In fact, the URLs can be made even more restrictive. If we adopt: 
`resource/(P<pk>[0-9a-f-]+)/ `instead of `resource/(P<pk>[A-z0-9]+)/` this will match every current resource, because all of the uuids have only hex digits 0-9, a-f, and -. 

A basic question, though: to what extent should we accept and filter later. Putting in a non-matching UUID to a more restrictive pattern will result in a URL 'NOTFOUND' error (as opposed to a **resource** NOTFOUND error). If we want a more descriptive error we would have to employ a less strict pattern. 

The argument for stricter patterns is that they pose less of a security risk.

**Comment by pkdash** [comment]
@alvacouch Since no one is likely to manually type the resource ID, I don't expect the URL NOTFOUND to occur often. Better to use stricter pattern.

**Comment by alvacouch** [comment]
@pkdash @hyi 
These are mostly addressed by #1496 fix REST API. 
I changed the main patterns to [0-9a-z-]+ because this is what the uuid package is generating. 
This is a string consisting of choices of 0-9, a-z, and '-', with at least one character. 

I did not fix the private strings  or the filename strings yet. All in good time. 

@hyi to fix the filename patterns I need to know what your iRODS module is going to accept as a valid pathname in a folder situation. I presume something like [a-zA-Z0-9,./-]+which translates that a path is a combination of a-z, A-Z, 0-9, "," (used in RCS), "." (for extensions), "/" (for subdirectories), '_' and '-' (to replace spaces). **It is exceedingly important that we do not allow /../ in the path.** That would allow people to CD out of their resources and affect others. Question is, do we allow .'s in folder names or otherwise? Do we allow leading '.'s? This is an invisible file in Linux. 

So, if we don't allow leading dots, one pattern is: 
`([a-zA-Z0-9@,:_][a-zA-Z0-9@,.:_+-]*/)*[a-zA-Z0-9@,:_][a-zA-Z0-9@,.:_+-]*+`
which says that a filename has the following attributes: 
- Each element of the path doesn't start with '.' or '-' but can contain a-z, A-Z, 0-9, '@', ',', '.', ':', '_', '+', and '-'
- Elements are separated with '/'. 
- There is at least one element. 
- That element contains at least one character.  

This rules out filenames that are antisocial in Linux because they make the command-line interface unusable, including ' ', $, {, }, [, ], (, ), <, >, *, ^, %, #, !,  \, |, ?, ', and ".  These all mean something on the command line. As well, it eliminates +name and -name because these are command line options in many commands! Anyone who manages to name a file one of these will have problems. For example, on the command line 
`this (is) [a] {stupid} filename`
must be written as 
`this\ \(is\)\ \[a\] \{stupid\}\ filename`
(!)
In addition, 
- filenames starting with . are invisible
- the Linux command line treats ' ' as a parameter separator. 
- filenames starting with - look like command options(!)
So these are disallowed as well. It can take serious work to input a filename starting with '-' as a filename, and the workaround is command-specific. This is a total pain. 

So, the above is the least restrictive pattern that doesn't make life difficult for people in Linux when unpacking files. 

To make things friendly in Windows, we would have to disallow : in filenames as well. But windows doesn't treat -name as a command line option. 

Your thoughts? In other words, how much of this should we protect users from, and how much of it should we allow them to do and make data users' lives potentially miserable?

@dtarb Perhaps you should weigh in on this as well.

**Comment by alvacouch** [comment]
@hyi @pkdash @dtarb 
Perhaps a deeper question is at which level we should make the check: application or URL pattern. The above pattern will reject all references to malformed filenames as "not found". You might want to tell the user that they are malformed, instead. 

The absolute minimum pattern on the filename should prevent security problems. If someone is trying to hack us, they should get a "not found". This concerns preventing the sequence '/../' from being processed. 

A pattern that prevents '/../' (and invisible files), but doesn't prevent anything else, is 
`([^./][^/]*/)*[^./][^/]*`
which says that each path component 
* must start with something other than / or .
* can contain anything but /
* contains at least one character (that is not / or .) 

and that there is at least one path component and path components are separated by /s.

If we use this, then the application should reject the other options in the above and inform the user that the filename contains illegal characters. This is perhaps a better error message than "not found" in this case. 

This is the bare minimum that will keep crackers from breaking into our system and wreaking havoc. Not allowing files a regular user can't see is just good UI design, but that also prevents crackers from inserting files that users cannot see, e.g., bootlegged software.

**Comment by alvacouch** [comment]
@Horsburgh Is there any reason that a user should be able to create a resource file whose name begins with '.'? This is a hidden file in Linux. I want to prevent these, but am checking with you as to whether you can foresee any situation in which we'd want to create such files..... Thanks!

**Comment by alvacouch** [comment]
@dtarb @hyi @pkdash This may be low priority of itself, but because it is a prerequisite for a high priority task (folders in REST), I must treat it as such.

**Comment by alvacouch** [comment]
@pkdash @hyi @dtarb @horsburgh 
For now, unless anyone has any objections, I am going to replace the filename pattern in urls.py and resourcefile_urls.py with `([^./][^/]*/)*[^./][^/]*` and run with that one. This prevents security problems but places the weight of enforcing filenames with the application. The current pattern [^/]+ doesn't allow folder actions, and the alternative .+ (accept anything) is a security hole.

**Comment by horsburgh** [comment]
@alvacouch - I cannot think of an instance where the user would want to create a resource file that begins with a '.' - I think it's OK to prevent this.

**Comment by pkdash** [comment]
@alvacouch Is this mean we also need to put similar filename restriction for file upload and file rename?

**Comment by dtarb** [comment]
I have several folders on my computer with files named .Rdata and .Rhistory in them where R keeps its workspace and history information.  These are "hidden" files but one could conceive of a desire to want to zip up the folder with these files in them and share in HydroShare, and one could conceive of that zip file being unzipped in HydroShare.  Then what happens?  For what it is worth, Drop box handles these files perfectly cleanly, but some other synchronization I have tried (not sure whether it was Box or OneDrive or Goodsync) croaked on it.  I do not want to complicate matters and am OK with not allowing files beginning with "."  Just mentioning that it may be possible.

**Comment by alvacouch** [comment]
@pkdash Yes, we need symmetry between upload and download. Branch #1515 contains new file paths and they are working. 

Note, also, that **we also need an API change for file upload.** We currently have no way to specify the path for a file during upload, and we assume that the path is the original name of the file as documented in the POST, at top level. The obvious thing is to utilize the same pattern if it exists in the URL, and otherwise pull the filename from the POST as before. Unambiguous and easy enough to do.

**Comment by alvacouch** [comment]
@dtarb I can make the restriction without blocking .Rhistory by utilizing a NULL URL rule, i.e., a URL that **always** sends a "not found" error. If that is needed, I can do it. But it's a bit ugly. 

A URL pattern has to be something that matches. In this case we want to reject anything with a specific pattern in it. So we have to match that and then reject it.  

Pattern is `^resource/(?<pk>[a-zA-Z0-9-]+)(.*/\.\./.*)$`.In other words 
`resource/{something-without-slashes}{something containing /../}{anything}/$`

**Comment by dtarb** [comment]
@alvacouch while I mentioned .R* files I do not want this to hang us up.  We have to be practical and I can live without them.  It was just an answer to the question about files that begin with .  However there is another vector for files to get into the system and that is in a zip file that is unzipped.  So it is not only downloads and uploads that have to be checked.  If a file with a disallowed file is in a zip file that is unzipped, how to handle this?

**Comment by hyi** [comment]
@alvacouch The resource file url is formed corresponding to our resource bag file hierarchical organization in the format of ```<res_id>/data/contents/<file_name>```, ```<res_id>/data/contents/<file_relative_path>/<file_name>```, ```<res_id>/data/resourcemap.xml```, etc. The view function first split the path to find the ```<res_id>``` then check whether this resource guid exists in our system or not, and if it exists, whether the requesting user has authorization to access this resource, and if all check passes, it will pass the file name with path to iRODS to retrieve the file. I agree it is important we should not allow ```..``` in the path. You rule for restricting file names looks good to me except that I am not sure about spaces in file names. Currently, we allow file names to contain spaces and they are stored in iRODS with the same file names that contain spaces. I am not sure whether we should replace spaces in file name with "_" or "-" and thinking we should preserve the original file names and allow spaces in file names. Other than that, your proposal looks good to me.

**Comment by pkdash** [comment]
@alvacouch I think this issues has been addressed. See if it needs to be closed.

**Comment by alvacouch** [comment]
All has been addressed. Closing now.
