### ISSUE TITLE
Conforming to REST best practices in REST API

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#1488]
@dtarb @hyi @pkdash @horsburgh 

See Google Drive: `hydroshare/SystemDesign/REST API/REST API gap analysis` for a spreadsheet of suggested REST endpoints for HydroShare functions. Most of these are unimplemented and I advocate changing the endpoints accordingly. 

The endpoints should have a consistent structure, of the form:
- `/object/{id}/{function}/`  for all operations concerning specific objects. 
- `/object/{function}/` or just `/object/` for all operations concerning a subset of objects of that type. 

Thus we have the strong patterns: 
- `/user/{id}/` for operations on users 
- `/group/{id}/` for operations on groups 
- `/resource/{id}/` for operations on resources. 

The endpoints `/{object}/` without an ID concern operations on a subset of such objects. What is done is determined by the REST operation: 
- POST -- create an object. Mostly, we use this convention already. 
- GET -- list all objects according to various criteria (in parameters). We currently have separate list endpoints, which are not needed.  
- PUT -- update all objects according to various criteria (in parameters). We have none of these yet. These are REST batch operations. E.g., batch publish. 
- DELETE -- batch delete a subset of objects. Might not be needed.  

It is rather important that the parameters be the same for each of these "search" and "batch" functions, for a specific object type. No reason not to be systematic. 

Object hierarchies follow the same patterns. E.g.
- `/resource/{id}/note`references a subset of annotations, while 
- `/resource/{id}/note/{nd}` references a specific note. 

This is echoed throughout the URL scheme. 

Fortunately, very few of the non-conforming endpoints are actually implemented and in use. 

_**Thus, a path forward is to instantiate and test new endpoints for the same functions, leaving the old endpoints in place but deprecating them. Revise the documentation to refer to the new endpoints.**_ 

Thus, documentation will guide new users toward the new endpoints. For a while, we'll have both normal and legacy endpoints in the system, but the end result will be an REST endpoint system that makes much more sense than before, and is easier to remember.

**Comment by alvacouch** [comment]
Note that there are two hidden issues in this table

1. The rest of the information needed for the calls are in parameters and files. I didn't list these. My next proposal will make these consistent as well. One thing at a time.  
2. The ground truth for each call leads to possible inconsistencies if there are other bugs. For example, note that the ground truth for discovery is Django, while the ground truth for resource download is -- of course -- iRODS. So, if these get out of sync, there will be discovered items that don't turn out to be what was expected. Long term, the hope is that we will construct a way of enforcing iRODS ground truths, via an rdflib parser that instantiates Django to match a resource xml document.

**Comment by alvacouch** [comment]
@dtarb @horsburgh @pkdash 
There are several considerations that come from DataOne. For the most part, DataOne is completely compliant with the above setup. The main deviation is what they name their endpoints. 
See https://releases.dataone.org/online/api-documentation-v1.2.0/apis/REST_overview.html , 
which defines the following endpoints for a DataOne member node: 

* /object: The set of objects available for retrieval from the node.
* /meta: Metadata about objects available for retrieval from the node.
* /formats: Object formats registered on the node.
* /log: Log records held on the node.
* /reserve: Identifiers that have been reserved for future use.
* /accounts: Principal and ownership related functionality.
* /sessions: Authenticated session management functions.
* /node: Service and status information for all nodes on the system.
* /monitor: Node health monitoring
* /replicate: Member node to member node replication functionality

These -- for the most part -- follow the GET/PUT/POST/DELETE pattern discussed above, in the sense that the URIs are of the form /object/{id}/... and the meanings of GET/PUT/POST/DELETE are the same. 

There is one huge difference, however: DataOne defines the specific format of resourcemetadata.xml, sciencemetadata.xml, and resourcemap.xml, including how to fetch them, and otherwise considers the data package indivisible and -- with some subtle exceptions -- immutable. In this pursuit, resourcemap.xml is the root of the metadata, not resourcemetadata.xml. 

**The DataOne API doesn't satisfy our purposes.** There is no support for modifying or otherwise managing resource content. It is also a moving target: as revisions are made to the DataOne core infrastructure. Therefore, it is dangerous (and somewhat pointless) for us to adopt the DataOne API for apps. We can instead "support" it in some meaningful way. I would go as far as suggesting that it be in a different namespace, e.g., /dataone rather than /hsapi, so there is no possibility of name collision. While the code for /object (dataOne) and /resource (HydroShare) is going to look very similar, it is dangerous to think of them as coupled. It would be better to create two APIs.

**Comment by horsburgh** [comment]
@alvacouch - thanks for looking a this. The point of looking at the DataONE API is not for us to adopt it for all of our purposes, but rather for us to set it up so that HydroShare can become a DataONE Member Node. This gives us increased and broader impact for published resources in HydroShare. In our initial conversations with DataONE, we have been looking at HydroShare being a "read only" Member Node and that we would only expose formally published resources to DataONE, so the immutability issues go away (at least for an initial implementation).

DataONE actually supports multiple metadata formats, so I'm not sure what you mean by they "define the specific format of" resourcemetadata.xml. In the context of HydroShare/DataONE, our resourcemetadata.xml IS the science metadata for DataONE.  Also - I'm not sure what you mean by the resource map being the root of the metadata.

I don't think we should use their API to replace our API, nor do I think we should adopt their API for Apps - rather, we just need to make sure that we have the capabilities to satisfy the requirements of their API so we can become a Member Node (and this may require some mapping from their API to ours).  They have a generic member node implementation for Python that may give us most everything we need without us having to do much development - and yes, it would have its own API.

**Comment by alvacouch** [comment]
@hyi @pkdash Why do we have two endpoints: 

* /resource/{id}/files/x
* /resource/{id}/data/x 

that should do the same thing and don't? The first one seems contorted. The second one seems to do exactly what I want.....

**Comment by alvacouch** [comment]
@horsburgh 
In the detailed documentation I read, the pattern of access is to grab the resourcemap first, then to use that to discover the science and system metadata. The formats of these three files are discussed in great detail. So are the SOLR bindings they use to search them. 

The question is whether becoming a read-only member node should influence our API for apps -- or not. 

Currently, there is a lot of crosstalk; several of the endpoints for a member node are echoed in our API. However, our endpoints are already not compliant; the semantics defined for our versions of the endpoints differ from DataONE requirements in our documents -- perhaps because the definition drifted after the name of the endpoint was decided. E.g., in DataOne, the /meta tag does not just load science metadata; it can load any of the metadata files. 

I think it is going to take an outrageous amount of time to reconcile our endpoints with DataOne. I would prefer not to try, but would rather write a custom set of endpoints just for DataOne. Thus, if the data is compliant, the endpoints will work. Since we seem to have full data compliance, this is not going to be difficult. 

What I don't want to do at this point is to fall down the rathole of trying to make the existing endpoints DataOne compliant. I can't serve two masters. The endpoint designs have different purposes.

**Comment by hyi** [comment]
@alvacouch Just took a look at the two endpoints you mentioned above. It appears ```/resource/{id}/files/x``` is a REST API endpoint which has been used to download files in Hydroshare, while the other endpoint  ```/resource/{id}/data/x``` was added by @pkdash to make sure the urls encoded in the resourcemap.txt in our bags can resolve to direct file download and it is not used by REST API at all. I speculate the REST API document have the ```/resource/{id}/files/x``` endpoint specified for file downloading while the other ```/resource/{id}/data/x``` is just a simple url mapping to our download view function which does not go through Django REST framework at all, and thus may not be a "legitimate" REST endpoint. @pkdash Any additional thoughts?

**Comment by alvacouch** [comment]
Currently, the following inconsistencies remain in the REST interface: 
1. The current embedded resource map URLs only work for non-authenticated, public access. They are not https, so they cannot refer to authenticated access. 
2. Thus, the python REST client ignores these URLs, because it does authenticated access, and builds its own URLs accordingly. 
3. To fix this, we have to make https the default for development. Otherwise, the URLs will not resolve.

**Comment by alvacouch** [comment]
@pkdash @hyi Admittedly, there is no `PUSH`, `DELETE`, or `PUT` for `/resource/{id}/data/x` but I do not otherwise see why I could not resolve the links in `resourcemap.xml `to `/resource/{id}/files/x` rather than `/resource/{id}/data/x`. Why not?

**Comment by alvacouch** [comment]
FYI: some additional comments on differences between DataOne and HydroShare APIs: 

| HydroShare API | DataOne API |
| ------------------|----------------|
| Private, authenticated read/write           | Public read plus authenticated write                                |
| Ability to change parts of objects          | atomic write only, whole object or whole metadata unit |
| Metadata included in published object | Metadata can be separate from published object            |
| Emphasis upon composite types           | Emphasis upon single file types only                                |

**Comment by hyi** [comment]
@alvacouch @pkdash @mjstealey I thought http would automatically resolve to https when SSL is enabled, so having http as the protocol for URLs could work in both local development and production. @mjstealey can you clarify?

**Comment by alvacouch** [comment]
@hyo @pkdash Or, a better question: if the resource is not public, what should the links `resource/{id}/data/x `do? I would think that this is the crucial difference. `resource/{id}/files/x` is supposed to refer to a managed object, while `resource/{id}/data/x `refers to a public object. So, it would seem that the main difference is that `resource/{id}/data/x `would return `NotFound` (and not `PermissionDenied`) for a private object.

**Comment by pkdash** [comment]
@alvacouch Both ```resource/{id}/files/x``` and ```resource/{id}/data/x``` have the same authorization checks.

**Comment by cuahsimarko** [comment]
This ticket is too big to implement across the legacy codebase at this point and should be moved to a google design / developer standards document.

**Comment by dtarb** [comment]
I think this can be closed.  @sblack-usu is now product owner for API and the REST API has advanced considerably since this discussion.  I'll leave it to you Scott to do the honors of closing after noting anything actionable in the discussion.

**Comment by sblack-usu** [comment]
The endpoints described were implemented quite awhile ago.
