### ISSUE TITLE
Improve the relations tab content entry and display

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#1494]
Add source and Add relation buttons on the Related Resources tab should allow user the option to pick a HydroShare resource or enter the information for an external resource (similar to the way the add author button gives users an option).

When information from an external resource is entered there needs to be more structure, such as Title, URL, Owner.

The listing of relationships should be more informative.  Extending what @horsburgh suggested in #1444 
"isDerivedFrom" --> "This resource was derived from the following sources:"
"isPartOf" --> "This resources is part of the following resources:"
"isHostedBy" --> "This resource is hosted by the following system or organization:"
"isCopiedFrom" --> "This resource was copied from the following resource or source:"
"isExecutedBy" --> "This resource can be executed by the following resources:"
"isDataFor" --> "This resource is the data for the following publication:"

These headings should be followed by a formatted readable list of Title, URL (that is clickable) and owner.  

These were unfinished items from #1444 that I am closing.

**Comment by horsburgh** [comment]
The drop down list in the "Add Relation" dialog has been modified to use the more descriptive labels of the relationship types. 

![image](https://user-images.githubusercontent.com/3485902/55981582-453acb00-5c54-11e9-94a3-c04291586b96.png)

They have also been modified for display on the landing page:

![image](https://user-images.githubusercontent.com/3485902/55981652-6f8c8880-5c54-11e9-86b5-cfb484566294.png)

Note that "Derived from" is not a descriptive label and will be fixed as part of a more comprehensive modification to relations as part of #3261. I'm going to close this issue as it is mostly live on www and instead address with the remaining issues related to relations in #3261.
