### ISSUE TITLE
Add federated Docker instances of iRODS hydroshareZone and hydroshareuserZone

### ISSUE THREAD

**Issue by mjstealey** [hydroshare/hydroshare#1501]
Generate two new Docker containers each running iRODS v.4.1.8 and federate them.
- [x] add `irods` directory to repo
- [x] **use-local-irods.sh** script to create federated local hydroshareZone and hydroshareuserZone
- [x] **use-local-irods.env** file to define iRODS variables
- [x] helper scripts to be defined for updating **local_settings.py**, etc.

**Comment by mjstealey** [comment]
@hyi - I'd be curious to have you deploy this locally to see if you get the same results. All appears to stand up as expected, but there is an iRODS error related to the paramiko section when creating the federated user account. I've added a note about this in the README.md file that accompanies the work. Hopefully we can debug this next week.

Reference [1501-docker-irods](https://github.com/hydroshare/hydroshare/tree/1501-docker-irods/irods)

**Comment by hyi** [comment]
@mjstealey Thanks. Will do next week. I suspect the paramiko ssh execution for creating irods user account may be related to the iRODS service account authentication via remote ssh session. In the worst case, we may just create an iRODS rodsadmin user which has been iinit'ed to be associated with the linux user used to do ssh. I have a feeling that should work. We can debug and try it out next week hopefully.

**Comment by mjstealey** [comment]
@hyi - issues resolved. Came down to "1247" vs 1247 for an iRODS port declaration and the proper resolution of the resource definition in the users zone. I had a malformed resc_net and resc_def_path pair.

```
$ docker exec -u irods users.local.org iadmin lr hydroshareLocalResc
resc_id: 10009
resc_name: hydroshareLocalResc
zone_name: hydroshareuserZone
resc_type_name: unixfilesystem
resc_net: users.local.org
resc_def_path: /var/lib/irods/iRODS/Vault
free_space:
free_space_ts Never
resc_info:
r_comment:
resc_status:
create_ts 2016-10-22.20:05:22
modify_ts 2016-10-22.20:24:29
resc_children:
resc_context:
resc_parent:
resc_objcount: 1
```

PR coming shortly

**Comment by mjstealey** [comment]
completed and merged
