### ISSUE TITLE
Folder appearance of file types

### ISSUE THREAD

**Issue by ChristinaB** [hydroshare/hydroshare#1503]
@mauriel133 @horsburgh (I don't think I have permissions to assign issues, so I am just mentioning you)
I suggest making a list of file types and adding, for example, an orange color that resembles the icon for Jupyter notebook, similar to the green X for Excel. 

![image](https://cloud.githubusercontent.com/assets/4108369/19526166/685720e2-95d8-11e6-8fcb-e53ae4d25a24.png)

IN this example,
https://playground.hydroshare.org/resource/0e49df4b97f94247a8d52bac4adeb14a/
we have textfiles, Jupyter Notebook and a Excel doc.  If the File Type work continues  #(  @dtarb @pkdash ), this should obviously be consistent.

Nice work!

**Comment by mjstealey** [comment]
> I don't think I have permissions to assign issues

@ChristinaB - You should have a pending invite to the extension developers group which would give you permission to assign people.

![screen shot 2016-10-19 at 11 51 06 am](https://cloud.githubusercontent.com/assets/5332509/19526438/752630be-95f2-11e6-81e9-d37de76cbf7c.png)

**Comment by ChristinaB** [comment]
Hi @mauriel133 
If this is done I can close the issue.  Thanks for all your work.
Christina

**Comment by mauriel133** [comment]
@ChristinaB,  we currently have a simple list associating file types and file icons. I can add more items. Could you tell me the file type you want associated with this new file icon? For example, for the green Excel icon we use "xls", "xlt", "xml", and "csv".

**Comment by mauriel133** [comment]
@ChristinaB, could you provide more details as to what needs to be done for this issue?

**Comment by ChristinaB** [comment]
For example, https://www.hydroshare.org/resource/a5b52c0e1493401a815f4e77b09d352b/
has .p and .ipynb files, so let's add a Jupyter icon or  python icon to a limited list of extensions.

**Comment by aphelionz** [comment]
@ChristinaB @Maurier We may be able to close this after 1.14 goes out

**Comment by horsburgh** [comment]
@Maurier - did this one get resolved? If so, let's close it.

**Comment by Maurier** [comment]
This was implemented a while back. Closing.
