### ISSUE TITLE
Order recent activity in groups from last to first

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#1505]
Recent activity in groups right now starts from resources that are quite old, but scrolling down you can see recent resources added.  I think that the latest should be listed first to see recent stuff.

**Comment by Lizabrazil** [comment]
@cuahsimarko will this impact the CZO work? I'm not sure if you caught this when coding for community. The recent activity lists is not in order of date.

**Comment by cuahsimarko** [comment]
That may share a backend and UI component with all Resources views. This is on my radar.

**Comment by Lizabrazil** [comment]
good good

**Comment by cuahsimarko** [comment]
![image](https://user-images.githubusercontent.com/45397838/56303404-d5bc5400-6109-11e9-84a2-c28d2e98feb8.png)

**Comment by cuahsimarko** [comment]
![image](https://user-images.githubusercontent.com/45397838/56749750-530e4700-6750-11e9-9004-dbe54361250d.png)
