### ISSUE TITLE
My Resources Page:  Anchor Default Filter Menu

### ISSUE THREAD

**Issue by horsburgh** [hydroshare/hydroshare#151]
On the "My Resources page", the default filter menu (e.g., Owned by me, Editable by me, Viewable by me) pops up above the table of resources when the browser window gets narrow.  I think we need to anchor it to the left of the table because the area to the top of the table will eventually be used by additional filtering options.

![myresources](https://cloud.githubusercontent.com/assets/3485902/6191037/b0da610c-b363-11e4-8df7-17376882a8dd.png)

**Comment by mauriel133** [comment]
Wouldn't this make the table too small on mobile devices?

**Comment by dtarb** [comment]
@mauriel133 see also discussion with @ironfroggy on #455 and #376 about using check boxes rather than links.

**Comment by horsburgh** [comment]
@mauriel133 - Yes, anchoring the menu to the left might cause issues for mobile devices with narrow screens.  But, moving the menu to the top of the table when the window gets narrow results in a bunch of blank space above the table.  Can the styling be dependent on whether the client is mobile device or not?  If so, we need to figure out what it should look like for mobile browsers.

**Comment by ironfroggy** [comment]
I will revisit my earlier mockups of the in-progress changes to this page and address responsiveness (the ability for the design to respond to different screen sizes)

**Comment by mauriel133** [comment]
Is this still an issue after the revamp of My Resources page?

**Comment by dtarb** [comment]
I am OK with this, but will leave for @horsburgh to close if it meets his pleasure.  The filters do still flip to the top on small windows and Mobile devices.

**Comment by horsburgh** [comment]
This is functional, but still not my favorite.  Even at the resolution of half of my Macbook Pro retina display (e.g., browser window taking up half of the screen) it puts them at the top. I understand why you would put them at the top for a mobile browser, but I'm not sure why I would ever want them to flip to the top in a modern desktop browser.  

@mauriel133 - if you have any thoughts about this, let me know.  Otherwise, just close it and move on.  There are bigger fish to fry!

**Comment by horsburgh** [comment]
Didn't get any more feedback on this, so I am closing.
