### ISSUE TITLE
Updates to REST interface

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#1515]
This is a catchall issue that documents several needs in REST other than folders (issues #1484 and #1495).
These include: 
1. Completing the REST API according to the API documentation. 
2. Modifying interfaces (in code and documentation) to capitalize upon REST best practices and Django capabilities. 
3. Adding new functionality as documented in recent conversations.

**Comment by alvacouch** [comment]
A brief list of REST deficiencies to be fixed first: 
1. Expose access control fully via REST. 
2. Expose groups and group actions fully.
3. Expose folder actions when iRODS folder API is present.  
3. Eliminate file URLs in resourcemap.xml containing the /data/ prefix; replace with /files/ prefix that does the same thing. Eliminate references to all URLS in resourcemap_urls.py and delete file. This is a data migration that requires rewriting all resourcemap.xml files in a globally consistent format. 
4. Complete REST editing functions for resources, where there are now gaps. Establish a new pattern for editing resources, that is simpler and not dependent upon proxy class structure. 
6. Expose selected facets of resource map and resource metadata as JSON rather than XML/RDF for ease of use in apps. Accordingly, make these functions Django model-based rather than XML-based. Switch the ground truth to Django rather than RDF for these. It's just plain easier. 
6. Expose system metadata correctly as XML. Current function doesn't work.

**Comment by dtarb** [comment]
@alvacouch I am worried that number 4 above is a data model change that may have further implications and would like @horsburgh to comment on whether it is needed and consistent with the data model.

**Comment by horsburgh** [comment]
@dtarb and @alvacouch - there are some considerations with number 4. Technically, as long as the URLs in the resource map resolve to the actual files, we should be OK. But there may be some confusion about why the URL path has "/files/" in it when the actual physical structure of the resource has "/data/" in it. Not sure why this change is needed?

Also, related to 6 - I think this is probably OK and OK for the functions to get their information from the Django models. But, the ground truth should always be the resource files on disk, which the Django models should always reflect with fidelity.

**Comment by pkdash** [comment]
@alvacouch Not sure if item#6 covers resource metadata update. If not then that needs to be of higher priority than the REST end points for group actions.

**Comment by alvacouch** [comment]
Addressed via REST API changes.
