### ISSUE TITLE
Resource landing page UI - suggestions

### ISSUE THREAD

**Issue by mauriel133** [hydroshare/hydroshare#152]
I will be addressing recent suggestions made by Dave and Jeff on the modifications I've made to the resource landing page. This changes are running in the sandbox at http://sandbox.hydroshare.org/

Dave's:
* [x] {This will be done via the download button}It should be possible to download the file itself by clicking on it, in addition to download all 
* [x] The Sharing information seems to belong near the Rights information.  I suggest bringing the statement about Sharing to after rights, before Keywords.  I think that sharing information from System Metadata and sharing status can be combined.  Sharing Status: Public seems the same as This resource can be viewed and downloaded by anyone.  I suggest that they be combined to something like:
Sharing Status: Public (This resource can be viewed and downloaded by anyone)
* [x] I think that the blocks for creators and contributors take up too much space.  Could we have one line for each person, e.g.
Jeff Horsburgh, Utah State University, 8200 Old Main Hill, Logan UT 84322-8200, Phone: 435 797-2946, Web: http://jeffh.usu.edu
* [x] There is not much information in the temporal tab.  Could this be combined with other date information on System Metadata to have one place that has all date information together
* [x] For my taste the line spacing in the abstract could be a bit smaller.
* [x] The share and delete icons top right should not be visible when I am not logged in with credentials to use these
* [x] The URL in the Citation should be a hyperlink
* [x] Citation should read "How to cite"

Jeff's:
* [x]  Let's keep the headings consistent.  Add an "Abstract" heading that is the same style as  as "Keywords" and "Content".  
* [x]  Change "Citation" to "How to Cite" as dave suggests and make it a heading that is consistent with "Abstract", "Keywords", "Content", etc.
* [X] Move the "Sharing" heading up and consolidate with the rights information as Dave suggests.  Make the rights information the same font size as the rest of the content.
* [x]  When I make the page narrow in my browser, the "System Metadata" tab wraps to the next line.  I think you should set is so the tabs never wrap.
* [x]  {Taken care of in another issue}I get an error when I click the delete file button.  I wanted to delete the existing file and upload the same file, but with a different file name, but I wasn't able to do it because the delete button is broken. Eventually, we may want to consider a "Rename File" option, but not for this round.
* [x]  The Share, Edit, and Delete icons for the resource (at the top of the page) and the download and delete icons (on the file) are too small.  They need to be larger and/or somehow more pronounced so they are easier to find.  Dave suggested having the file download when you click on it, but I prefer the download button so that you know for sure what is going to happen when you click on it.
* [x] Hide tabs if they are empty
* [x] Add Creative Common badges to 'Rights'
* [x] Restyle 'Manage Access' panel
* [x] Check if authors/contributors are HydroShare users and display as link
* [x] Authors and contributors should be links to user's HydroShare profile when applicable.

**Comment by dtarb** [comment]
I have reviewed these changes in sandbox.hydroshare.org and am happy to approve the layout.  @horsburgh can close when he approves.  However see #209.

**Comment by dtarb** [comment]
@horsburgh is this ready to close
