### ISSUE TITLE
Failed to show the detailed error info when an invalid resource file is uploaded

### ISSUE THREAD

**Issue by gantian127** [hydroshare/hydroshare#1521]
When I upload an invalid raster file to an empty raster resource, the system doesn't show the corresponding detailed error information on the resource landing page. 

**On the www site it will show error like:**
![image](https://cloud.githubusercontent.com/assets/5016511/19985335/ce6ab956-a1d7-11e6-8025-0a5ced389eed.png)

**On the beta site, the error detail info is not shown:**
![image](https://cloud.githubusercontent.com/assets/5016511/19985348/e4f8684e-a1d7-11e6-9036-c4c46a32636a.png)

**Comment by hyi** [comment]
@gantian127 @mauriel133 I am working on this issue now. @mauriel133 Will let you know if I need help on the frontend to address this issue.

**Comment by gantian127** [comment]
@hyi Thank you for working on this issue.

**Comment by hyi** [comment]
I am closing this issue since @gantian127 has tested on beta and validated it is working on beta.
