### ISSUE TITLE
Collections csv lists, should these exist?

### ISSUE THREAD

**Issue by mjstealey** [hydroshare/hydroshare#1523]
@zhiyuli - Question regarding collections. We're hitting an error with usage reporting regarding a missing file from collections, but we're unsure if this file should actually exist or not.

Filename: **collection_list_9700b80f5cfa42d4a52c9aaab81a4e11.csv**

Error:
```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/hydroshare/hs_tracking/management/commands/stats.py", line 218, in handle
    self.resources_details()
  File "/hydroshare/hs_tracking/management/commands/stats.py", line 144, in resources_details
    for f in r.files.all()]
  File "/usr/local/lib/python2.7/site-packages/django/db/models/fields/files.py", line 76, in _get_size
    return self.storage.size(self.name)
  File "/hydroshare/django_irods/storage.py", line 256, in size
    stdout = self.session.run("ils", None, "-l", name)[0].split()
  File "/hydroshare/django_irods/icommands.py", line 180, in run
    raise SessionException(proc.returncode, stdout, stderr)
django_irods.icommands.SessionException: (SessionException(...), 'Error processing IRODS request: 4. stderr follows:\n\nERROR: lsUtil: srcPath /hydrotestZone/home/alphaHydroProxy/9700b80f5cfa42d4a52c9aaab81a4e11/data/contents/collection_list_9700b80f5cfa42d4a52c9aaab81a4e11.csv does not exist or user lacks access permission\n')
```

Files as stored by iRODS:
```
$ ils -rL /hydrotestZone/home/alphaHydroProxy/9700b80f5cfa42d4a52c9aaab81a4e11/
/hydrotestZone/home/alphaHydroProxy/9700b80f5cfa42d4a52c9aaab81a4e11:
  C- /hydrotestZone/home/alphaHydroProxy/9700b80f5cfa42d4a52c9aaab81a4e11/data
/hydrotestZone/home/alphaHydroProxy/9700b80f5cfa42d4a52c9aaab81a4e11/data:
  alphaHydroPr      0 hydrotestResc         4856 2016-11-04.10:59 & resourcemap.xml
        generic    /projects/hydroshare/vaults/devProxy/home/alphaHydroProxy/9700b80f5cfa42d4a52c9aaab81a4e11/data/resourcemap.xml
  alphaHydroPr      0 hydrotestResc         2945 2016-11-04.10:59 & resourcemetadata.xml
        generic    /projects/hydroshare/vaults/devProxy/home/alphaHydroProxy/9700b80f5cfa42d4a52c9aaab81a4e11/data/resourcemetadata.xml
  C- /hydrotestZone/home/alphaHydroProxy/9700b80f5cfa42d4a52c9aaab81a4e11/data/contents
/hydrotestZone/home/alphaHydroProxy/9700b80f5cfa42d4a52c9aaab81a4e11/data/contents:
```

**Comment by zhiyuli** [comment]
@mjstealey @hyi 
I need some help debugging this error. I could duplicate the error on dev.hydroshare.org. But I could not duplicate it on my local vm.

The csv file should exist on irods. It is a resource file created dynamically (remove any existing and then create a new one) every time when the collection bag gets downloaded. The error seems to suggest a discrepancy between django db and irods. The Django db has a record of this resource file tied to this collection res, but no physical file exists on irods. 

The discrepancy may happen at two places:
1) remove existing csv file
https://github.com/hydroshare/hydroshare/blob/develop/hs_collection_resource/utils.py#L63

2)  add new csv file 
https://github.com/hydroshare/hydroshare/blob/develop/hs_collection_resource/utils.py#L110

Both the two operations were implemented in one function and wrapped by one try..except statement. So if any of them raises an exception, the log should have a record: "Failed to update_collection_list_csv in {RES_ID}. Error: ERROR_MESSAGE"
https://github.com/hydroshare/hydroshare/blob/develop/hs_collection_resource/utils.py#L113

Can you see it in the log?
Thanks

**Comment by hyi** [comment]
@zhiyuli The erroneous resource as shown in the log @mjstealey copied above is https://beta.hydroshare.org/resource/9700b80f5cfa42d4a52c9aaab81a4e11/ which is exactly the collection resource Christina reported the issue with, which I have checked the log and seen the error message indicating failure to update the collection csv file. You can see details in that email thread. That is exactly the issue which caused this issue.

**Comment by zhiyuli** [comment]
@hyi  @mjstealey 
Currently I have no clue what has happend to this collection......
Could you please go to the django shell of www and dev to check what res files are recorded in db tied to collection 9700b80f5cfa42d4a52c9aaab81a4e11? thanks

**Comment by hyi** [comment]
@zhiyuli The res file tied to this collection resource shown in django DB is: 9700b80f5cfa42d4a52c9aaab81a4e11/data/contents/collection_list_9700b80f5cfa42d4a52c9aaab81a4e11.csv. So the csv file is recorded in django DB, but missing on iRODS backend?

**Comment by zhiyuli** [comment]
@hyi @mjstealey @Christina 
I created a new collection on beta that holds exact the same 2 resources as collection 9700b80f5cfa42d4a52c9aaab81a4e11 does. I could download its bag, and the bag contains csv without any issue.

I am would suggest Christina to make me a owner of this broken collection for research and create a new collection for use.

**Comment by zhiyuli** [comment]
@hyi 
thanks for checking the backend. Yes, I think that the case. Django has a record of a res file but it is not on irods....

**Comment by pkdash** [comment]
@zhiyuli What's the status of this issue?

**Comment by ChristinaB** [comment]
Is this related to the resource integrity issue that @alvacouch is working on??  If so, we could close this.
