### ISSUE TITLE
Buttons do not activate

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#1526]
If I open a generic resource with multiple files, switch to edit mode and click on a file such that it is selected (highlighted with light orange box) the buttons (download, delete, rename etc) above the file box do not activate.  They appear to only activate when I right click on the file.  It seems the buttons should be active whenever a file is selected.

**Comment by mauriel133** [comment]
@dtarb, I'm trying to replicate this problem. Could you tell me which browser and OS you are using?

**Comment by mauriel133** [comment]
I have found the error and will have a fix soon.

**Comment by dtarb** [comment]
Windows 10.  Firefox (49.0.2 up to date).

**Comment by dtarb** [comment]
Verified on beta.
