### ISSUE TITLE
New HydroShare account request with pre-existing user name needs more descriptive error message

### ISSUE THREAD

**Issue by rayi113** [hydroshare/hydroshare#153]
When going to main HydroShare landing page to sign-up for new account, if details are entered such that new user requests a user name that is already taken, the error message is simply: Account cannot be created.  

This error message should be more descriptive additionally stating that the user name is already taken.

**Comment by hyi** [comment]
Fix pushed to github and a pull request has been created to have it merged into release-candidate-1.4.0 branch.

**Comment by hyi** [comment]
It is working and ready for testing on alpha.

**Comment by hyi** [comment]
The fix to this issue is already included in release 1.4, and ready for testing on beta.

**Comment by dtarb** [comment]
Tested in alpha.
