### ISSUE TITLE
Failed Signup yields wireframe page without styling

### ISSUE THREAD

**Issue by mjstealey** [hydroshare/hydroshare#1530]
An issue for this may already exist, but could not find it on a cursory search.

If a field is missing or is not entered correctly when the Sign Up button is pressed for a new user account and validation fails, a wireframe page is returned without any of the proper site theming.

![screen shot 2016-11-07 at 11 28 22 am](https://cloud.githubusercontent.com/assets/5332509/20065843/9b652182-a4dd-11e6-8b14-fd863f94c8bc.png)

**Comment by pkdash** [comment]
@mjstealey I believe this has been fixed.

**Comment by mjstealey** [comment]
resolved
