### ISSUE TITLE
Help: Phase 1 Simple Styling Modifications

### ISSUE THREAD

**Issue by horsburgh** [hydroshare/hydroshare#1534]
@dtarb and @ChristinaB - @mauriel133 and I just met and came up with the following set of things for getting started on the HydroShare help pages. I want to do this in more bite sized chunks, so I've called this issue "Help: Phase 1". Please comment in this issue if you have feedback.

* [x] 1. Modify starting page for help to have help group icons/images (i.e.g, topics) - style these like the "How it works" section on the main HydroShare page.
* [x] 2. Modify styling of page to be as consistent with www as possible - modify header and footer to be consistent
* [x] 3. Fix styling and text padding issues on each individual help content page
* [x] 4. Modify left hand navigation to get rid of navigation column, but focus instead on the icon groups (i.e., topics)
* [x] 5. Add a subsidiary page for each help icon group that lists individual help topics/links to pages
* [ ] 6.  Add user stories as either a separate icon group and/or potentially featured articles on the main help page
* [ ] 7. Add images to existing help articles
* [x] 8. Figure out how the search works and make sure it it useful

**Comment by horsburgh** [comment]
@mauriel133 and @ChristinaB - Here's a first cut at the help categories/group icons for the opening page of the help pages with a mapping of the existing content to where I think it should go under each major topic. Numbered items would be the main categories/group icons on the first page.

1. Introduction to HydroShare
  * Introduction to HydroShare
2. HydroShare Resource Types
  * Resource Types
    * Generic
    * Collection
    * Time Series
    * Geographic Raster
    * Multidimensional (NetCDF)
    * Model Program
    * Model instance
    * SWAT model
    * Modflow model
    * Web App
3. Creating and Managing Resources
  * Creating Resources
  * Creating Resource Versions
  * View, Download, Edit, or Delete a Resource
  * Accessing HydroShare iRODS from a Windows PC or Mac
  * Uploading Large Files into HydroShare
4. Sharing and Privacy
  * Sharing and Publishing Resources
  * Managing Access
5. Discovering Resources
  * Discover
6. Participation and Collaboration
  * Participation and Collaboration
    * Find Groups
    * My Groups
    * Group Landing Page
    * Group Membership
    * Setting Group Visibility
  * Comment on and Rate Resources
7. Apps
8. Modeling
  * Applying Models
  * Run a Model Using a Python  Notebook Server
9. About HydroShare
  * About HydroShare
  * Tutorial Webinars and Publications

I think our initial focus for Phase 1 should be on users of the web user interface. For Phase 2, other categories that we need to add eventually include (but in a new issue):

1. Information for HydroShare App Developers
2. HydroShare REST API Documentation
2. HydroShare user stories or Blog posts (e.g., here's how to use HydroShare to do such and such).

**Comment by ChristinaB** [comment]
I think this list is spot on!
@mauriel133 
Is it useful for me and @jphuong  to update this moqup with @horsburgh  outline?  and @dtarb edits?
https://app.moqups.com/jphuong/hPfKvNNcT6/view/page/a2dcc2955

I would update it to be very similar to the https://www.hydroshare.org/  landing page, but with 9 infographics that link to content.   If the landing page and help landing page have a similar style, should I make a new issue to update the landing page to remove the 'What you can do with HydroShare' list and laptop image?

**Comment by ChristinaB** [comment]
Heads up @Lizabrazil 
Here is some information you should be aware of for helping with help.  
We can discuss this tomorrow in the phone call.  

Hi @mauriel133 
Let us know your timeline on Help page work (or if folders are still in your radar). 
Christina

**Comment by ChristinaB** [comment]
@horsburgh  - I think the first list you have is sufficiently clear, my only concern is with the question about what to do with the navigation. If you click into the subject icon, the user next see the list of topics within that heading. They can navigate out/back using a top navigation.   This means there will be no left navigation. Correct?

**Comment by horsburgh** [comment]
@ChristinaB - Correct.

**Comment by ChristinaB** [comment]
@Lizabrazil and I talked about the help content. She is reviewing to see if there are any gaps.  I clarified that we are going to use the existing material and put it into the format described in the list above.  What is the timeline for the update? Should I plan on being the one to port the content to new pages? Or can we link the new landing to existing pages? THanks @mauriel133 !!!

**Comment by horsburgh** [comment]
@ChristinaB - @mauriel133 's work should mostly just be styling. It shouldn't affect content.  The pages are already in the system and shouldn't have to be moved - unless you want to reorganize and change the number of pages or what is on each one. The same pages that are there now will be there when @mauriel133 is done.

**Comment by danames** [comment]
These help pages are looking really good. Styling is fairly clean. Info is easy to find. It's sort of weird that the question you click on doesn't match the title of the help page it goes to, but I can get used to that.

**Comment by ChristinaB** [comment]
1.  Nice work!! Thanks @horsburgh and @mauriel133 !
2. The search box at the top has a drop down box with options Pages, Blog Posts, and Everything.  I think 'everything' can stay, but I think the users will be confused what 'pages' refers to, and we don't have 'blogposts'.    I think this requires a bigger conversation with @alvacouch about what is searchable from the help pages (resources?), but suggest only keeping items in the dropdown list that are currently functional, for now.
3. The dynamic adjustments on the text are great, but I wonder if we can still do a tad bit more optimization with the wide screen. For example, when the screen is wide enough for a 3x3 matrix, the 1-2 line title and the 2-3 line description are misaligned.    This is not an issue for a narrow screen and 2x4 +1 matrix, for example.   The 1X9 mobile view is best, because the title and the description don't have any horizontal comparative views.   My guess is that this could be solved by forcing the shorter titles to always have the same white space as is taken up by the longer titles?  
4.  I don't think we should include the question version of the page, for example, on https://park.hydroshare.org/creating-and-managing-resources/ 
This is not consistent with the layout in https://park.hydroshare.org/hydroshare-resource-types/   
and it is too repetitive in a confusing way. (Is this different info, or the same info?)
I think it is sufficient to click on the hyperlinked navigation, and have the content populate below.

**Comment by horsburgh** [comment]
@ChristinaB - some responses below:

**Related to 2**: I would be OK with just getting rid of the drop down box next to the search. I don't think we need @alvacouch 's help here. The search box is only related to the help system and will only return results within the content from the help pages. It is not designed to return resources or any content other than what is in the help pages.

**Related to 3**:  I'm not seeing the misalignment of the text in the 3X3 configuration (in Chrome on a Mac). Unless you are referring to the text wrapping, and I think that's a very minor issue that doesn't bother me at all. I probably wouldn't waste cycles on this. 

**Related to 4**: If you don't like the question version of the page, then we need something else to fill that page. That is the landing page for one of the 9 topics, and we need a landing page for each topic. I don't feel like they have to be consistent because they are describing fundamentally different things, but if you want to suggest some alternative content, we can implement. Also - the navigation links only show up at the top of the page if you have a very narrow screen. Otherwise they show up on the left. So, we can't just expand content below the navigation items.

**Related to 5**: The navigation is just pointers to pages. It isn't content, and the content is not embedded in the navigation.  The concept is - you have 9 main help topics represented as tiles on the first page. Each topic must have a landing page with text - this is the target page when you click on one of the 9 tiles. We can change the text to whatever you want, but each of the 9 tiles needs a target page. Then, under each of the 9 landing pages, you can have subsidiary pages with more detailed content. I added the questions as an alternative way to get to the subsidiary pages, but you are welcome to suggest an alternative.

**Comment by horsburgh** [comment]
I'm going to go ahead and close this one. It's implemented on beta.hydroshare.org. The two items that are not checked in the original post are content related. If we end up having a separate help section for user stories/blog posting, we should implement them as a separate issue.
