### ISSUE TITLE
What does the "map results" radio button do?

### ISSUE THREAD

**Issue by danames** [hydroshare/hydroshare#1544]
The discover page on BETA has two radio buttons "all results" and "map results".  I clicked "map results" and didn't get any change. What is the purpose of this button? Do we need it? Is it in the right place? 

Perhaps when you click the "map results" radio button it should also switch to the map discover tab?  or should this radio button only be available on the map tab?

**Comment by xuezhaokun** [comment]
I removed this ambiguous function for AGU. I think this issue can be closed for now.
