### ISSUE TITLE
Need to hardwire beta.hydroshare.org to appsdev.hydroshare.org and vice versa

### ISSUE THREAD

**Issue by danames** [hydroshare/hydroshare#1545]
Resources in beta.hydroshare.org should launch apps in appsdev.hydroshare.org

Apps in appsdev.hydroshare.org should use resources in beta.hydroshare.org

**Comment by aphelionz** [comment]
@danames Closing this as we no longer rely on tethys for the app landing page. If need be we can create separate resources that then open up the proper app server
