### ISSUE TITLE
Multiple resource file endpoints should be consolidated

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#1548]
There are currently three distinct undeprecated REST ways to access a resource file individually: 

1. /resource/{resource-id}/files/{filename}
2. /resource/{resource-id}/data/{filename} 
3. /resource/{resource-id}/data/contents/{filename} 

We need to standardize on one of these. Further, the first one is the documented solution, while the second one is now used in each individual resourcemap.xml and -- to my knowledge -- is the only one that actually works with federated resources. 

Thus, we need to:

1. Make one file access function used everywhere. Theoretically, this is solution (2) above, mapped to solution (1) REST endpoint. 
2. Migrate the individual resourcemap.xml files to contain that form of URL. 

The latter is a data migration.

**Comment by hyi** [comment]
@alvacouch REST API URL for accessing files, /resource/{resource-id}/files/{filename}, does not resolve from a browser, but No. 2 and No. 3 in your list resolve to file download directly from a browser, which were added to meet the requirement that URIs in resourcemap.xml must be resolvable. I may misunderstand what it meant in No. 2 "Migrate the individual resourcemap.xml files to contain that form of URL," but want to point this out just in case.

**Comment by alvacouch** [comment]
I plan to make the first one resolvable in a browser, and then replace the other with it, because the /files/ URL is the one that is specified in the REST API requirements.

**Comment by cuahsimarko** [comment]
This ticket should be moved to a developer standards doc and then 1-2 specific endpoints me earmarked for fixing and opened as GH Issues,.

**Comment by Castronova** [comment]
@sblack-usu can you please close this or act on it if needed?

**Comment by sblack-usu** [comment]
`/resource/{resource-id}/data/{filename}` and `/resource/{resource-id}/data/contents/{filename}` today, are the same thing and really is `/resource/{resource-id}/{filename}` where `/data/contents/` is included in filename.  We need to include `data/contents` in the path to access files such as `data/resourcemetadata.xml`

#3928 enables api download with authentication for for the resourcemap urls, which follow the path above.  

Leaving `/resource/{resource-id}/files/{filename}` for compatibility.
