### ISSUE TITLE
Add explanation to Help page landing page

### ISSUE THREAD

**Issue by Lizabrazil** [hydroshare/hydroshare#1561]
"When you use HydroShare in new ways, Help HydroShare." If you want to link to a Christina's page, you need an explanation of why you are directing users there. Is it because Christina is the point of contact for help questions? If so, say that before redirecting. 
![help page](https://cloud.githubusercontent.com/assets/13852599/20191244/add04460-a752-11e6-9a6f-900c435ee187.JPG)

**Comment by ChristinaB** [comment]
Hi Liza - this page is getting totally revamped ASAP by @mauriel133 based on something like this moqup This is the link that can be edited. https://app.moqups.com/jphuong/hPfKvNNcT6/edit/page/a35efcbed
I'll ping you on Jeff's list that will be used to update this in a different issue. 
Christina

**Comment by Lizabrazil** [comment]
Hi Christina,

It says I am not authorized to edit this project and therefore also not able to view it.
