### ISSUE TITLE
Jupyter notebook quality check

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#1567]
The public jupyterhub deployment Jupyterhub-NCSA on hydroroger needs testing that each script from the 5 given runs beginning to end automatically without problem.  See also https://github.com/hydroshare/hydroshare-jupyterhub/issues/4.

**Comment by gantian127** [comment]
@Castronova would you please test this and close this issue if it works? Thanks

**Comment by Castronova** [comment]
@gantian127 I am still working on bug fixes.

**Comment by pkdash** [comment]
@Castronova Should this be closed?

**Comment by dtarb** [comment]
@Castronova I pushed this to 1.11.  Can you please affirm when you have done this check, then close.

**Comment by aphelionz** [comment]
@Castronova Can you move this to the jupyterhub repo or close?
