### ISSUE TITLE
Square up group icon layout on Collaborate page

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#1568]
Make groups icon layout equal height/width.

**Comment by pkdash** [comment]
@mauriel133 Hope this is an easy fix.

**Comment by mauriel133** [comment]
@dtarb, @pkdash  Could you elaborate on this one?

**Comment by dtarb** [comment]
This had to do with the group layout looking irregular.  It is working nicely now on www, so was evidently fixed at some point and I will close.
