### ISSUE TITLE
Question: Is serialize_science_metadata_xml() used or needed?

### ISSUE THREAD

**Issue by ironfroggy** [hydroshare/hydroshare#157]
It is defined in `hs_core/hydroshare/utils.py` and was written in October of 2014, but is only used in a single test case which does not actually assert *any* conditions. This function uses the User API that is being removed, but only in a minor way. I've disabled those bits for the time being with comments to fix when the User API is replaced.

However, if this isn't used, I'd like to know the status. Assigning the question to @pkdash who wrote it.

**Comment by pkdash** [comment]
It is no more needed.
