### ISSUE TITLE
Reference time series rework

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#1570]
Based on discussions with @danames reference time series are being reworked to have a json file hold the reference information, to accommodate better integration with logically typed file resources.  I'm putting this on the 1.9.0 milestone.

**Comment by danames** [comment]
Example json file. Actual file extension will be different. Maybe .json.refts
[timeseriesLayerResource.json.txt](https://github.com/hydroshare/hydroshare/files/585090/timeseriesLayerResource.json.txt)

**Comment by dtarb** [comment]
Closing this issue as it has been superceded by #1571 that has more detail.
