### ISSUE TITLE
Add reference time series logical file type to composite resource

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#1571]
Here are the requirements for this file type as discussed with @alvacouch and @dtarb and Matthew on 3/31/2017:

1. This file type will contain only one json file
2. This json file needs to be validated (initially will do some minimum validation)
3. No metadata editing is allowed except the editing file level key/value metadata
4. The content of the json needs to be displayed as part of the file type metadata
5. The content of the file needs to be be stored in Django db for metadata query and discovery purposes
6. We still need to decide/specify what needs to be written to resource metadata xml file for this file type

**Comment by danames** [comment]
This should be easy since referenced time series is now represented by a simple JSON file. An example such file is attached here. Note that the actual resource will have extension is yet to be determined. We may want to use ".json.refts" to help apps understand it.

[timeseriesLayerResource.json.txt](https://github.com/hydroshare/hydroshare/files/585088/timeseriesLayerResource.json.txt)

**Comment by pkdash** [comment]
@dtarb , @danames and @alvacouch I have noted the requirements (see above) for implementing this file type based on the discussion we had today. If I have missed any requirements please add/modify the note I have above.

**Comment by dtarb** [comment]
Answers to questions, as I recall them from the phone call are:
1. Yes one json file
2. Yes validate that the json file has needed elements
3. No metadata editing except for file level keywords.  The json file is not edited as it reflects the contents of the reference resource that cannot be changed.  Keywords from the json file are copied into the Django file level keywords on initial load, but a HydroShare user is able to change them, resulting in changes in the Django db and XML metadata, but not json file.
4. Yes, display json file
5.  Yes store contents in Django db.
6.  We did not answer this question.  Can we use a format similar to stored time series.

**Comment by horsburgh** [comment]
According to @alvacouch - the JSON file specification for referenced time series is in flux. So, that needs to be finalized.

**Comment by aphelionz** [comment]
Need to test after HIS work is done

**Comment by danames** [comment]
More specifically, once the Resource Creator app is finished and posted to Apps, then we can test this by finding resources in data.cuahsi.org and then turning them into referenced time series JSON files in a composite resource.

**Comment by dtarb** [comment]
Tested today and found the following small shortcomings.

- When a .json.refts file is set to refts type and the resource title has not yet been entered, it needs to take the value from the title entry in the refts file.
- Editing refts file type title should change the title entry in the refts file (or provide the option for this, similar to sync operations in netcdf and sqlite time series)

Also are there API functions to
- load a file into a composite resource
- set the file to Reference Timeseries file type

If (once) these are done, I think this issue should be closed and work on apps that access this resource type managed in separate issues.

**Comment by dtarb** [comment]
Tested and working on release candidate 1.13.
