### ISSUE TITLE
Add time series logical file type to composite resource

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#1573]
Do for time series files what has been done for raster files - see #1477

TODO:
- [x] SQLite file to be set as time series file type
- [x] File level metadata view
- [x] File level metadata edit
- [x] File level metadata changes to write back to SQLite file
- [x] XML metadata to include file level metadata
- [x] Unit tests related to file type based on SQLite file 
- [x] CSV file to be set as time series file type
- [x] Unit tests related to file type based on CSV file

**Comment by pkdash** [comment]
@dtarb I don't think we can implement time series file type for release 1.9.0. Among all file types, this one is going to be most challenging.

**Comment by pkdash** [comment]
@dtarb and @horsburgh Here is how I am implementing writing metadata changes to SQLite file:
- Metadata changes at the file level can be written to SQLite file. Though the user is allowed to edit keywords at the file level, keyword changes are not written to the SQLite file. Let me know if we should not allow user to edit keywords at the file level.
- Metadata changes at the resource level (including creators and contributors) are not written to the SQLite file.

**Comment by dtarb** [comment]
I am happy to defer to @horsburgh.  On the keyword question my suggestion would be to be consistent with how this functionality works for the time series resource type.  If keywords editable there are not written to the SQLite file then don't write them for file type either.

**Comment by pkdash** [comment]
We don't write keyword changes to SQLite file for time series resource type.

**Comment by dtarb** [comment]
OK.  Then do the same for the time series file type.

**Comment by aphelionz** [comment]
@pkdash @dtarb Can this be closed?

**Comment by dtarb** [comment]
Yes closing.  If there are any limitations or issues found new issues can be created.
