### ISSUE TITLE
Using delayed commitment semantics to improve performance. 

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#1575]
@pkdash @dtarb There is a conflict in the REST API between "instant gratification" and performance, in the sense that every small edit of resource metadata triggers a **resource commitment**, in the sense that the resource metadata files need to be rebuilt. This wastes a lot of time and really should be done asynchronously. This means that if the intent is to edit a lot of metadata, **each individual edit triggers a separate commitment**. _This is exceedingly wasteful of computing resources._ 

There are two ways to deal with this: 

1. **Commitment absorption**: put the commitments to do into a queue, and reduce the number of commits by making the later commits delete the earlier ones in the queue. 
2. **Delayed commit**: make a new command that does the commit. 

I suggest that (2) is much easier to understand that (1):

| Commitment absorption | Delayed commit  |
|-----|-----|
| It is unclear when commit will happen | Commit is the result of an explicit command |
| Absorption logic is complex | Explicit commit logic is simple | 
| There are multiple commits for a stream of changes | There is exactly one commit for a stream of changes |
| REST best practice | Violates statelessness of REST in a minor way |

How delayed commit works: 
1. When you make an edit to metadata, e.g., a single field, **it is changed in Django but not in the resource files.** 
2. When you're done making changes, you issue a REST request of the form 
```/resource/{id}/commit```
**This updates all files.** 
3. In the meantime, between edits and commit, **anyone who requests the resource gets the old version.**  This includes requests during the commit. 

This has rather profound implications for the way the REST API Is written, though: 

1. The ground truth for reads must be the files. 
2. The truth for writes must be the Django database. 
3. Commits move truth from the Django database to the files.

**Comment by dtarb** [comment]
What are the UI implications of delayed commit.  There is a save button for editing each field.  I'd prefer for a user not to have to do any extra commit button pushes on the interface, but am OK aggregating all edits to one save button.  As long as this is clear and simple for a user I am OK with delayed commit.

**Comment by alvacouch** [comment]
@dtarb This is not a UI issue because when the user presses "save", that is the same thing as a commit.  The number of commits that can be generated by the UI is thus bandwidth limited by the speed of the UI, i.e., about 1 per minute. This is acceptable. 

In the REST interface, however, it is possible to generate requests far faster than the UI, which leads to the commit storm I am trying to avoid. **It is possible to generate hundreds of request per minute.**

**Comment by alvacouch** [comment]
Understanding queue contraction: 

* suppose we make a flurry of 100 requests **for the same resource** and commit them all. The celery queue then contains 
`{c1}, c2, c3, c4, c5, .... c100`
where celery is processing c1. This takes a long time, in which c2, ..., c100 were queued. 
* The queue system realizes that c2, ... c99 are redundant and cancels them. Thus, the queue now contains 
`{c1}, c100 `
where c1 is being processed now. 
* Thus, when c1 finishes, c100 starts, and **there are two commits rather than 100.** 

Thus the queue system always maintains a maximum of one **unstarted commit per resource,** and a large flurry of commit requestss will always lead to executing exactly two commits.

**Comment by alvacouch** [comment]
The one downside of delayed commit is that two apps both making changes to the same resource can mistakenly partially commit each other. This will lead to two commits, where the first commit picks up changes from both apps, while the last one picks up changes from both apps. Thus, the first commit is a partial change, and it is possible -- though unlikely -- that someone will fetch the resource in this "semantically inconsistent" state.

**Comment by dtarb** [comment]
OK.  I am fine with this then.  Thanks for the clarifications.

**Comment by alvacouch** [comment]
Queue contraction is much harder to accomplish than delayed commit. I will thus start with delayed commit.

**Comment by pkdash** [comment]
@alvacouch I assume the 'delayed commit' refers to regeneration of the metadata xml file and commits to Django database are immediate. If this assumption of mine is correct then I am not sure the need for the celery queue. Currently we regenerate the metadata xml file every time we make metadata change commit to the database. Since we also set the resource AVU to 'modified' at the same time, we can use the AVU to trigger regeneration of the metadata xml file at the time of bag download or at the time of xml file download.

**Comment by alvacouch** [comment]
@pkdash I am concerned that the complete generation of resourcemetadata.xml is too expensive to repeat 1000 times in a minute. What I meant by delayed commit was to write resourcemetadata.xml only upon a /commit operation. This reduces the number of commits to one for a large flurry of requests.

**Comment by alvacouch** [comment]
To put this more bluntly, when we enable piecemeal editing of resource metadata, 

1. We'll be the first group to do that. 
2. We need to be careful that the piecemeal edits don't overwhelm the system. 

There is also a similar issue for harvesting file metadata for uploaded files. It would be better not to regenerate resourcemetadata.xml every time we upload a file, but rather, to store the harvested data in Django and commit once.

**Comment by alvacouch** [comment]
@pkdash There is also a major issue as to what happens when we ask for a specific file from a resource, e.g., resourcemetadata.xml or resourcemap.xml. In principle, these would be regenerated when the bag is created, but the request isn't for a bag. What happens then? Is there a way we could force an update before fetching the affected file?

**Comment by hyi** [comment]
@alvacouch You can call ```resource_modified()``` which will update both resourcemap.xml and resourcemetadata.xml files.

**Comment by pkdash** [comment]
@alvacouch Whenever there is a request to download the bag or one of the metadata xml files, we will check the AVU status of the resource and if it says 'modified' then we need to call the ```resource_modified()``` which should regenerate the metadata xmls files. So instead of calling ```resource_modified()``` on every file upload or metadata edit, we should be calling the ```set_dirty_bag_flag()``` to set the AVU.

**Comment by hyi** [comment]
@alvacouch @pkdash Just want to clarify, ```resource_modified()``` is called whenever a metadata element is modified currently as well as set bag dirty flag. This bag dirty flag is only checked to determine whether the bag zip file needs to be regenerated or not upon downloading a bag on demand. ```resource_modified()``` does regenerated resourcemetadata.xml file and resourcemap.xml file to keep them up to date which is pretty fast. This makes sure resourcemetadata.xml and resourcemap.xml is always in sync with Django database with only zipped bag being generated on demand upon bag downloading. It is probably better to move this resourcemetadata.xml and resourcemap.xml file creation/update to when bag is being downloaded on demand as well, but so far we have not had this need yet, and if there is a need from REST API, we can certainly modify the current code base to do so.

**Comment by pkdash** [comment]
@alvacouch and @hyi Even if we have not seen problems with regenerating the metadata xml files every time metadata is updated, it would be better to regenerate only at the time of bag or xml file download.

**Comment by hyi** [comment]
@alvacouch @pkdash We could do that, but we have to make sure REST API functions for retrieving resourcemap.xml and resourcemetadata.xml need to checked the bag dirty flag and create or update them if the bag is dirty. Also, django would be the single point of truth for resource metadata and resource maps meaning we cannot restore django database from bags until we bring resourcemap.xml and resourcemetadata.xml all in sync with Django database.

**Comment by alvacouch** [comment]
I am closing this because it seems to have been addressed in interveining PRs.
