### ISSUE TITLE
WebApp missing supported resource types

### ISSUE THREAD

**Issue by Castronova** [hydroshare/hydroshare#1583]
The MODFLOW model instance is not listed as resource type that can be selected on the WebAPP edit page.  To replicate this issue, create a new web app resource, navigate to the edit page, and view the supported resource types list.  The ModflowModelInstance is not listed as an option.

![image](https://cloud.githubusercontent.com/assets/4822372/20223589/577b0454-a808-11e6-9da2-fc44566ea2a3.png)

**Comment by zhiyuli** [comment]
merged and tested
