### ISSUE TITLE
Update Dockerfile - 1.9.0

### ISSUE THREAD

**Issue by mjstealey** [hydroshare/hydroshare#1588]
@mjstealey Here are my notes for getting this to work on the docker image:

pip install selenium
curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash -
sudo apt-get install -y nodejs
sudo npm install -g phantomjs-prebuilt

I'm also running into issues with the live_server_url. I'm not sure yet if this is a configuration or docker issue.

**Comment by dtarb** [comment]
Seems not essential for AGU.  Move to 1.10.0

**Comment by mjstealey** [comment]
revised as #1725
