### ISSUE TITLE
Update Django REST Framework to 3.5.3

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#1589]
There are bugs in the REST framework version we are using that were addressed in 3.5.0. The current revision is 3.5.3. We should upgrade to that version and then remove the workarounds that we needed to deal with the bugs. These bugs concerned file upload and put limits on file upload capabilities.

**Comment by mjstealey** [comment]
> The current revision is 3.5.3. We should upgrade to that version

In progress over at [hs_docker_base](https://github.com/hydroshare/hs_docker_base/blob/develop/Dockerfile#L80)

**Comment by dtarb** [comment]
Pushing to Future issues.  @alvacouch or @aphelionz to determine a specific future milestone to target

**Comment by cuahsimarko** [comment]
@phuongdm please close or comment

**Comment by phuongdm** [comment]
Closed becasue at least I saw 3.5.4 was used
