### ISSUE TITLE
REST API for piecemeal resource metadata editing

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#1599]
@pkdash @horsburgh @dtarb
This issue is the overarching one that issue #1575 was intended to solve. We need a way to modify metadata one element at a time in the REST API. This -- in turn -- requires thinking about the considerations in #1575. 

At present, there are two needs: 

* **immediately, support editing of Dublin core metadata** (straightforward). 
* later, support editing of metadata for other resource types (requires complex validation). 

The first of these can be solved by creating a REST generic model-based API for BaseResource, independent of resource type. This API is for the most part provided by Django except for foreign key and many-to-many relationships, that must be custom coded. This can be implemented via REST PATCH (partial update) functionality. 

The second of these is more challenging, because each extended metadata element applies to only a few types and not every type. One must disallow writes to metadata elements that do not concern the resource's base type. This set of requirements is not even represented canonically anywhere; it is hard-coded into the validator code.  

Finally, it would be ideal to be able to ingest a whole resourcemetadata.xml file and populate the Django object. This is challenging for reasons documented in issue #1598 and not part of this issue.

**Comment by pkdash** [comment]
@alvacouch Once I see your approach (some code) how you planning to implement update of Dublin core metadata elements for BaseResource (via REST call), I may be able see a way to apply the same approach to any resource type and any instance of AbstractMetdataElement.

**Comment by horsburgh** [comment]
@alvacouch and @pkdash - I asked @fryarludwig if he could get me a list of metadata elements that he is trying to update through the API for our iUTAH datasets.  It turns out that once the resources have been created, the only one he really needs to update periodically through the API is the Temporal Coverage element (because we are periodically adding new data and the temporal coverage changes).

But, he is also trying to update the following through the API after the resource has been created because he was unable to figure out how to specify them when creating the resources (he's automatically creating the resources using code:

SpatialCoverage
ExtendedMetadata (key/value pairs)
Contributor(s)
Credits (the funding agency info)

@pkdash - is he just missing where he can specify these on resource creation?

**Comment by pkdash** [comment]
@horsburgh Except the extended metadata (key/value) all other metadata (which user supposed to create)can created using the hs_restclient. Though we have recently modified the resource create REST endpoint to allow key/value metadata, the hs_restclient has not been updated.  Here is an example how to create metadata elements at the time of resource creation:


```>>> from hs_restclient import HydroShare, HydroShareAuthBasic```
```>>> auth = HydroShareAuthBasic(username='myusername', password='mypassword')```
```>>> hs = HydroShare(auth=auth)```
```>>> abstract = 'My abstract'```
```>>> title = 'My resource'```
```>>> keywords = ('my keyword 1', 'my keyword 2')```
```>>> rtype = 'GenericResource'```
```>>> fpath = '/path/to/a/file'```
```>>> metadata = '[{"coverage":{"type":"period", "value":{"start":"01/01/2000", "end":"12/12/2010"}}}, {"creator":{"name":"John Smith"}}, {"creator":{"name":"Lisa Miller"}}]'```
```>>> resource_id = hs.createResource(rtype, title, resource_file=fpath, keywords=keywords, abstract=abstract, metadata=metadata)```

**Comment by fryarludwig** [comment]
@pkdash After adding "metadata" to the "createResource" function in hs_restClient, I was able to use your example to reliably add metadata for spatial, temporal, agency, and creator (I haven't tried contributors yet). Is this same format required for PUT requests to the scimeta endpoint?

**Comment by pkdash** [comment]
@fryarludwig The scimeta PUT endpoint does not take json data. It needs the xml file that you have been trying. When we have REST endpoint for adding/updating individual metadata elements, we should be able to pass json data similar to how we are using the ```metadata``` parameter in create resource.

**Comment by alvacouch** [comment]
@fryarludwig @pkdash @horsburgh 
OK, I understand what the issues are. We'll give priority as specified above. I propose that we implement a new endpoint resource/{resource_id}/scimeta/elements for whom:
* PUT will do partial updates of metadata. 
* GET will read all editable metadata (currently limited to the Dublin Core)
This pattern can be applied to other piecemeal edits and will retain the current GET/PUT for whole files to the endpoint resource/{resource_id}/scimeta

**Comment by pkdash** [comment]
@alvacouch I believe this has been addressed. Should you close it then?

**Comment by aphelionz** [comment]
@pkdash @alvacouch I now doubly believe this can be closed given the work in #1871

**Comment by Castronova** [comment]
Resolved.
