### ISSUE TITLE
Wrong file gets downloaded if the resource has multiple files with the same name

### ISSUE THREAD

**Issue by pkdash** [hydroshare/hydroshare#1602]
If I have 2 files with the name 'test.txt' - one within a folder and the other one not in any folder then if I try to download the file that's not inside the folder, it downloads the file that's inside the folder.

**Comment by hyi** [comment]
@pkdash Can you check what the download urls are for each file with the same name?

**Comment by pkdash** [comment]
Both files show the same url for download:
"/django_irods/download/30a20765b66f4bfeb05106322eeaca71/data/contents/test-demo/test.txt"

**Comment by hyi** [comment]
The PR that fixed this issue has been merged for 1.8 deploy and has been verified by @pkdash. So I am closing this issue now.
