### ISSUE TITLE
Model Input term does not add in Modflow Model Instance

### ISSUE THREAD

**Issue by jsadler2** [hydroshare/hydroshare#1606]
When a user completes and clicks save in the dialogue box for adding a Model Input term for a MODFLOW Model Instance, the term is not added to the DB.
![image](https://cloud.githubusercontent.com/assets/6943441/20406395/2c838794-acdb-11e6-9715-c3759d6690a1.png)

**Comment by jsadler2** [comment]
@pkdash since you helped us implement this, do you have any idea why this isn't working any more? We're pretty sure we haven't changed anything related to this in our code. Any advice?

**Comment by jsadler2** [comment]
@pkdash the action attribute in the form tag for this element is showing as blank: 
`"<form action="" method="POST" enctype="multipart/form-data">"`
Also, it doesn't have a form id. So we think it's something in Crispy Forms. We tried to set the action attribute manually but were unsuccessful.

**Comment by pkdash** [comment]
@jsadler2 Would you check the form action attribute as soon as the page reloads. My guess is some javascript might be resetting the action attribute when some other metadata elements get updated. If that's not the case we may be able to debug the output html for this modal form in the page_preproccessors.py.

**Comment by pkdash** [comment]
@jsadler2 or @mohamedmorsy Can you test to see if this has been fixed and close it?

**Comment by mohamedmorsy** [comment]
@pkdash this works now as expected. @pkdash Thanks!
