### ISSUE TITLE
Modifications to Resource Publication Workflow

### ISSUE THREAD

**Issue by horsburgh** [hydroshare/hydroshare#1608]
Based on recent issues we've been having with users not understanding the semantics of sharing versus publishing, @dtarb and I discussed some potential changes to the resource publication workflow. The following reflect those thoughts:

1. There is an immediate need to modify the messaging of resource publication. An additional dialog box needs to be instituted when the user clicks the "Publish" button with text something like the following:

> **Are you sure you want to formally publish this resource**? You will **NOT** be able to edit your resource or its metadata if you proceed. This is a permanent step and should only be done when you are finished modifying your resource and you are ready to formally publish it. 
> 
> If you want to make your resource public or share with specific HydroShare users without formally publishing it, click "**Cancel**" and use the manage access panel or toggle your resource to be public instead."

Once this additional dialog is implemented, there may be a need for the following in the longer term:

2. Implement notifications to send email notifications to Authors and contributors when a resource they have authored or contributed to is published.
3. Implement a period between when a user requests to publish a resource and when it is actually made immutable (perhaps one week).
3. Develop messaging that states something like - "You just requested that we publish your resource. HydroShare will now request a permanent DOI for your resource. You have one week to verify that your files and metadata are correct and that all authors and contributors are in agreement. After this period, your resource will be permanently published and you will no longer be able to modify it."

**Comment by hyi** [comment]
@horsburgh @dtarb We do have the following text in the popup dialog when users hit the publish button: 
```
Upon submitting the resource for publication it will be permanently published and assigned a digital object identifier (DOI). This is final and changes can only be made on a new version (copy) of the resource.

Please confirm that you accept the HydroShare Publication Agreement shown below.
```
where ```final``` is bold to stand out. Even though the message is already pretty clear and the user has to take an extra step to check the publication agreement acceptance checkbox before having publish button enabled, the fact that the user still makes the mistake to hit publish button unintentionally makes me think the user probably did not take the time to read the text or in a hurry to try things out. I guess having another popup message box wouldn't hurt and would help to force the user to read it, but if the user does not read the texts, another popup message box probably wouldn't help a lot either. Just a thought.

**Comment by horsburgh** [comment]
@hyi - I don't disagree at all. But the fact that this has happened now twice in the same week (that we know of) leads me to believe that something else needs to be done. Yes - I think that if either of these users had read the message carefully they might not have made the mistake, but I think there's also some misunderstanding among new users about what "publish" means - this is my attempt to try and clarify it for them. I suspect there will be those that ignore any and all warnings we give them.

**Comment by pkdash** [comment]
@horsburgh Would an approval process be better? Where the user makes a request to publish at that  point the resource gets locked from editing. Then when a user with admin account approves this  request then only a DOI is issued. Obviously this involves much more work then displaying the new message.

**Comment by horsburgh** [comment]
@pkdash - it would be awesome to set up some kind of peer review process for publishing datasets. @dtarb and I discussed this and it seems a bit unsustainable at the moment as an admin would have to look at every publication request and make judgements about them. There's three issues with that:

1. An admin wouldn't have known that these two users were not actually ready to publish. They would only have been able to assess whether the metadata were complete or not.
2. The overall process would be a lot of work for the small number of people we have now.
3. It may be a deterrent for users because they can get a DOI from systems like Figshare without any sort of review.

**Comment by dtarb** [comment]
I think the steps @horsburgh recorded from our conversations are spot on.  Number 1 does need to be implemented with high priority because despite us having the word final in bold, users are not noticing or understanding it.  One of the users thought that the wording "changes can only be made on a new version" that followed final, did allow for changes.  The subtleties of versions are unclear to users and we have to recognize this.

We can not sustain an approval process, but I think a week waiting period where parties involved have a chance to correct errors or stop the process before the DOI gets registered at crossref provides another safety net.

I would also like the following policy to be stated on our help pages.  

> If a user makes a mistake publishing a resource HydroShare admin (contact support@hydroshare.org) can delete the resource and work with CrossRef to disassociate the DOI link.  The user is then themselves responsible for copying or again uploading the files and creating a new resource and publishing it when they are ready.

**Comment by horsburgh** [comment]
@dtarb - I added a modified version of your text to the help page that describes formal resource publication.

**Comment by hyi** [comment]
@dtarb @horsburgh I can modify the messaging on the pre-publish dialog as stated by @horsburgh as follows:
```
    Are you sure you want to formally publish this resource? You will NOT be able to edit your resource or its metadata if you proceed. This is a permanent step and should only be done when you are finished modifying your resource and you are ready to formally publish it.

    If you want to make your resource public or share with specific HydroShare users without formally publishing it, click "Cancel" and use the manage access panel or toggle your resource to be public instead.
```
for AGU release. The rest of potential publication workflow improvement can be deferred later. Let me know if you want to make any further modifications to the messaging above slated for the AGU release.

**Comment by horsburgh** [comment]
@hyi - I think the language of the message is good. Don't forget the bolded words!

Agreed that the rest of the modifications can wait until after AGU.

**Comment by hyi** [comment]
@horsburgh Here is the new/updated popup dialog after the user hits the publish icon:
![res_pub](https://cloud.githubusercontent.com/assets/476302/20682128/b107833e-b574-11e6-8c98-3e6767714ee1.png)
Does this look good to you? Any further modifications needed?

**Comment by horsburgh** [comment]
@hyi - sorry if I was unclear.  I think we should keep the existing form as it was. Then, when the user clicks the "Publish" button, a second warning dialog opens up with the new message.  

The issue was that the user did not read the existing form, so adding more text to that form is not going to help the problem.  This second dialog is basically an "Are you sure you are sure" type of confirmation that the user has to click through.  Is this possible?

**Comment by hyi** [comment]
@horsburgh OK. Got it. Will implement this accordingly then as an "Are you sure you are sure" type of confirmation to add in another layer of protection for users to bail out if needed.

**Comment by hyi** [comment]
@horsburgh @dtarb I have made corresponding changes to add another layer of "Are you sure you are sure" type of confirmation for resource publication and deployed it to riverdev.hydroshare.org for you to take a look. If you think it looks good, I will create a PR and merge it. Let me know.

**Comment by horsburgh** [comment]
@hyi - the new, second pop up in the publish workflow looks good to me. I didn't actually click the "publish" button on the second pop-up, but the wording looks good.

**Comment by dtarb** [comment]
I tested the flow on riverdev and am happy for you to create a PR and merge.

**Comment by hyi** [comment]
@dtarb What is deployed on riverdev was already merged today - that PR with resource versioning wording changes also included the "are you sure" dialog addition in publication workflow.

**Comment by dtarb** [comment]
Thanks.  Sorry, I am slow in keeping up with all of these.

**Comment by horsburgh** [comment]
The initial "Are you sure you are sure" dialog has been implemented on beta.hydroshare.org for the AGU release. I'm moving the remaining parts of this to #1649 so this one can be closed.
