### ISSUE TITLE
Update the App Resource Type to include Registering an App to a specific file extension

### ISSUE THREAD

**Issue by danames** [hydroshare/hydroshare#1610]
Presently a user can register an App in HydroShare - using HydroShare itself as the App catalog. The current mode allows a user to associate an app with one or more resource types. See below:
![image](https://cloud.githubusercontent.com/assets/3472628/20421371/a8a5e368-ad20-11e6-8099-4f91b4ce9a82.png)

Now we need to add additional functionality to allow an app builder to register to one or more resource types AND/OR to one or more file types. By file type, we specifically will focus on file extensions. The app developer would get a text box where they can add a list of comma separated file extensions. This does not need to be fancy because it is really only used by programmers who are registering a new app. 

This list of file extensions associated with apps then gets searched when a user right clicks a file. Then a list of all apps that have registered that file extension appear in the Open With file right click menu.

This will give us quick and easy file based app opening and will make our composite resources much more interesting. This is related to #1609

**Comment by dtarb** [comment]
This needs to (also) apply to opening a supported "file type" in a resource that holds typed files (like composite resource).  A supported type may be multiple files grouped together (such as shapefile and vrt geographic raster) so keying off extension alone may not be sufficient.  Also, extensions are not 100% unique and reliable.

**Comment by pkdash** [comment]
I don't know what benefit we would get by registering a web app with file extension for files in resources that are not of composite resource type. I suggest we allow web apps to be associated only with non-composite resource types (which we have already implemented) and file types (need to implement) that live within composite resource. Once a web app is registered  with a specific file type, user should get the Open With option from any files within that file type.

**Comment by dtarb** [comment]
I think @danames wants to allow Open With based on mime types for which we do not code file types in composite resources.  E.g. a pdf or jpg in a generic resource.  I am happy to support this use, but do want to ensure that we have the functionality for supported file types within composite resources too which is more than specifically focusing on file extensions that Dan writes about in introducing the issue.

**Comment by dtarb** [comment]
Noting the need for open with to act on formally typed files in composite resources as well as files matched by extension, the Web App Resource type needs additional entries to have a user select not only resource type, but also file type (from the list of file types implemented) and extensions.  File types should be a list of check boxes similar to resource type.  Extensions can be a CSV separated list of file extensions. 

Also app launching patterns will need to be specified for when an app is launched from a typed file or a generic file with an extension.  These will need to pass identifying information for the app to have the specific file that it was opened from and API functionality will need to be extended (perhaps implying a separate API issue to address this) for accessing specific files within a resource given the information passed.  This design needs to accommodate that typed files within composite resources may be best identified by their logical file id, and that there may be many typed files within a composite resource so an app should not have to retrieve metadata for the whole resource and sift through it to find information on the file it was opened from.

**Comment by dtarb** [comment]
Closing.  Open with functionality has deployed.
