### ISSUE TITLE
Development support for data migrations needs serious help

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#1613]
At present, it is not possible to see printing to stdout during migrations or testing on the docker host. This is necessary to debug migrations and tests.

**Comment by alvacouch** [comment]
In the case of testing, I have determined that `nosetests` is running the `Capture `plugin that doesn't print `stdout` unless there is an error. The` nosetests `option `--nocapture` turns this off and exposes printouts. I don't know what to change to make this happen, though.

**Comment by pkdash** [comment]
@alvacouch In seetings.py you can try adding this line:

```NOSE_ARGS = ['--nocapture']```

**Comment by alvacouch** [comment]
On the issue of writing data migrations, I had severe problems with the suggestion that I use the production database. This worked, but broke everything else: 

1. I couldn't print during a migration. 
2. I couldn't attach to the hydroshare docker instance. Attempts to attach simply hung. Therefore: 
3. I couldn't store output in a file I could read, or a log I could read. 

So, I could test the migration on the production file, but in all other ways, I was blind. All I knew was when it crashed. Then it provided a traceback.

**Comment by mjstealey** [comment]
> see printing to stdout during migrations

@alvacouch - you could pipe the [migration output](https://github.com/hydroshare/hydroshare/blob/develop/hsctl#L232-L240) of the hsctl script to a file locally.

Adding `> migrate` or `>> migrate` to the 3 lines shown below should make finding the migration output easier.

```bash
migrate_hs() {
    echo "MIGRATE:"
    echo "  - docker exec -u hydro-service hydroshare python manage.py migrate sites"
    docker exec -u hydro-service hydroshare python manage.py migrate sites > migrate.log
    echo "  - docker exec -u hydro-service hydroshare python manage.py migrate --fake-initial"
    docker exec -u hydro-service hydroshare python manage.py migrate --fake-initial >> migrate.log
    echo "  - docker exec -u hydro-service hydroshare python manage.py fix_permissions"
    docker exec -u hydro-service hydroshare python manage.py fix_permissions >> migrate.log
}
```

**Comment by alvacouch** [comment]
@pkdash The NOSE_ARGS option worked for nose. Thanks. Will try the other option later.

**Comment by alvacouch** [comment]
@mjstealey your fix doesn't work. The printing is somehow being stopped before that point. The input doesn't contain the printing, so that redirecting it doesn't do anything.

**Comment by mjstealey** [comment]
> fix doesn't work. The printing is somehow being stopped before that point

@alvacouch - running with develop branch on production db I get the following output. If there were to be an error it would have printed out here, but the migration was clean.

```
$ cat migrate.log
Operations to perform:
  Apply all migrations: sites
Running migrations:
  No migrations to apply.
Operations to perform:
  Synchronize unmigrated apps: inplaceeditform, accounts, rest_framework, grappelli_safe, corsheaders, boot, jquery_ui, haystack, crispy_forms, postgres, hs_metrics, staticfiles, filebrowser_safe, sitemaps, gis, hs_sitemap, mobile, autocomplete_light, debug_toolbar, widget_tweaks, irods_browser_app, django_nose, heartbeat
  Apply all migrations: redirects, theme, ga_resources, galleries, hs_geo_raster_resource, hs_geographic_feature_resource, conf, ga_ows, hs_labels, forms, generic, hs_model_program, sites, blog, contenttypes, hs_tools_resource, hs_access_control, hs_app_netCDF, hs_app_timeseries, hs_modelinstance, core, ref_ts, django_comments, sessions, hs_swat_modelinstance, auth, hs_script_resource, django_docker_processes, pages, hs_collection_resource, oauth2_provider, hs_modflow_modelinstance, hs_tracking, admin, hs_core, django_irods
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
  Installing custom SQL...
Running migrations:
  Rendering model states... DONE
  Applying hs_tools_resource.0009_auto_20160929_1543... OK
  Applying hs_tracking.0004_auto_20161010_1402... OK
```

I can look at your branch and see what I get locally.

There may be one more thing to modify on your side, and that is the UID/GID settings.
By default, these are set to the hydro user UID=1000, GID=1000 that it is on the hydrodev VM.
These are set in [hydroshare-config.yaml](https://github.com/hydroshare/hydroshare/blob/develop/config/hydroshare-config.yaml#L6-L7)

If you're not using the hydrodev VM you'll want to update these to the UID/GID of the user running the hsctl script.

**Comment by alvacouch** [comment]
@mjstealey My hydro user and group in my own dev environment are 1000,1000 like yours. 

But I've been using a dev environment built according to your instructions rather than the VM environment, and my dev environment is also seriously screwed up in some way. I now cannot attach to any container regardless of whether I am running the default or production database. This might be related to the printing problems. 

Meanwhile, if you want to watch the migration run, there are multiple print statements that can be uncommented in the script hs_access_control/migrations/0015*.py

I think the real issue in all of these printing problems is a conflict between guest os and host os in some way. 

I am building in a dev VM now to end-run around these issues and finish this PR.

**Comment by alvacouch** [comment]
@hy1 @mjstealey Currently, the dev environment is sufficient, but it will not be sufficient when we go to local iRODS for everything.
