### ISSUE TITLE
No content files are displayed (getting spinning wheels forever) for some resources on www

### ISSUE THREAD

**Issue by hyi** [hydroshare/hydroshare#1624]
One example of such resources is https://www.hydroshare.org/resource/89e4e1e18f3746fc936d7185baf6f76e/ I see a spinning wheels forever without displaying content files for the resource, however, the same resource displays as expected on beta https://beta.hydroshare.org/resource/89e4e1e18f3746fc936d7185baf6f76e/. Not sure why it works on beta but not on www.

**Comment by horsburgh** [comment]
@hyi - I just clicked on both of these links and they both worked for me.

**Comment by hyi** [comment]
@horsburgh Just tried on my home computer, and yes, both links works as expected. Not sure what is going on with my computer at work, I even tried both firefox and chrome browsers and got the same spinning wheel without content files on both browsers, perhaps some kind of caching issues. Whew...I am glad to close this issue now.
