### ISSUE TITLE
USGS and AHPS Gaugeviewer: Confusing forecast location and Gateway message errors - but it did create a new resource

### ISSUE THREAD

**Issue by ChristinaB** [hydroshare/hydroshare#1627]
@danames -  please also include Jim. Is he on Github?

To build a demo for AGU, we need a few polished workflows.  
Here was my test.   
![image](https://cloud.githubusercontent.com/assets/4108369/20574626/49aa8938-b16a-11e6-841c-620e397286e7.png)

First issue is that I'm not sure why the forecast is in the middle.  

I love that the New resource content is autofilled!!!   And it did work, but gave me this error message.  
![image](https://cloud.githubusercontent.com/assets/4108369/20574569/f4aa9680-b169-11e6-9f29-bae271c05d84.png)

Although this did show up in my resources. 
https://www.hydroshare.org/resource/7ff9740ac2ef4145a5fa32f0707f0819/

**Comment by ChristinaB** [comment]
Hi @danames  and @dtarb  -  this is another issue that needs to be assigned and addressed before AGU. 
Thanks!

**Comment by aphelionz** [comment]
This issue was moved to CUAHSI-APPS/gaugeview#1
