### ISSUE TITLE
Owner shares of resources should not override user shares of same privilege

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#1631]
@dtarb There has been a general discussion between myself and @pkdash about whether sharing requests that do not result in a change of permission should be accepted or raise an exception. At present: 

1. Owner shares that set the same privilege as before are accepted and change the grantor of privilege to the owner, even though there is no change in actual privilege. Thus, "owner shares are idempotent".  
2. Non-owner shares of the existing privilege are rejected and the first grantor is preserved. Thus, "non-owner shares are not idempotent". 

It is somewhat desirable -- from a social standpoint -- to preserve the first grantor as a matter of record and disallow actions that change that grantor for no good reason. At this point, with the *_undo_* routines removed in PR #1576,  the grantor field is purely informational, but it seems rather rude to overwrite it simply because "owners should be able to do anything". 

However, changing this has some small chance of breaking the UI, and there is no time before AGU to check that non-idempotence of owner actions doesn't break the UI. Thus this change is deferred until after AGU.

**Comment by dtarb** [comment]
I could go either way on this one and am happy to leave it to after AGU

**Comment by alvacouch** [comment]
Addressed in PR #1710
