### ISSUE TITLE
add autopep8 to dev environment

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#1634]
Would be nice to have autopep8 installed in dev environment. It works and makes code pass flake8.

**Comment by cuahsimarko** [comment]
@alvacouch please close this issue if the current setup meets your expectations for this issue 
![image](https://user-images.githubusercontent.com/45397838/56231192-dabace00-604b-11e9-9f1a-aaa38f6f4513.png)

**Comment by alvacouch** [comment]
This is not the same thing, but it suffices and I have found no one else who likes autopep8. Closing.
