### ISSUE TITLE
JupyterHub-NCSA app broken

### ISSUE THREAD

**Issue by Lizabrazil** [hydroshare/hydroshare#1636]
When i open the JupyterHub-NCSA app i get this server error. My server is working successfully for other apps...
This app should be put on dev before AGU.
![app broken](https://cloud.githubusercontent.com/assets/13852599/20720519/6ddefab0-b62d-11e6-83c4-2e9cf10db6cf.JPG)

**Comment by dtarb** [comment]
@Castronova please assess what is going on and report if it is feasible to fix the problem by AGU.

**Comment by Castronova** [comment]
I believe this problem is a result of `killing` running containers when updating the jupyterhub server.  Removing the `jupyterhub.sqlite` file may fix this problem.
