### ISSUE TITLE
Worldwater app directs to a website...not an app

### ISSUE THREAD

**Issue by Lizabrazil** [hydroshare/hydroshare#1638]
This resource: brazil, l. (2016). Onion Terrain Analysis Start, HydroShare, http://www.hydroshare.org/resource/c19c2b0f57de443e999824c4d95456e1
has open with the worldwater app as an option. When I click to open worldwater app, i get redirected to this website: http://worldwater.byu.edu/app/index.php/yellowstone/home
This should either be redirected to app within that website or it should be put on dev before AGU.

**Comment by dtarb** [comment]
This particular open with app instance was removed a while back.  The general open with problem remains as a separate issue.

**Comment by aphelionz** [comment]
@dtarb @Lizabrazil Likewise this issue - closing in light of the new apps page. However, feedback is welcome!
