### ISSUE TITLE
USGS and AHPS Gaugeviewer WML broken

### ISSUE THREAD

**Issue by Lizabrazil** [hydroshare/hydroshare#1641]
Following the instructions, I cannot successfully view data for gauge of interest. I zoom in as much as possible and click on a gauge and nothing happens. This app should be moved to dev before AGU. 
![gaugeviewer broken](https://cloud.githubusercontent.com/assets/13852599/20726821/1f339976-b645-11e6-8898-42a1fb3e1711.JPG)

**Comment by Lizabrazil** [comment]
Dan or Drew is looking into a pop up that explains that the app only works with a certain browser.

**Comment by aphelionz** [comment]
This issue was moved to CUAHSI-APPS/gaugeview#2
