### ISSUE TITLE
Disable publication for web apps

### ISSUE THREAD

**Issue by danames** [hydroshare/hydroshare#1648]
Given that web apps are likely to be malleable with changing URL's and functions and capabilities and other meta data, I suggest that we disable "publication" of web app resources. i.e. there should be no "publish" button and no DOI issued.

**Comment by hyi** [comment]
@danames Can you test this on beta and close this issue if it works?

**Comment by hyi** [comment]
@danames Can you test this on www and close this issue if it works now?

**Comment by danames** [comment]
Verified fixed on www...
