### ISSUE TITLE
Versioning inconsistencies

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#1652]
If I create a new version of a HydroShare resource the old version is removed from the My Resources page and editing/deleting no longer permitted.  If I then go to the new version which I can edit and delete the reference back to the old resource  I am allowed to do this.  If I then delete the new version the old version is left in an inconsistent state.  It is still there (I can find it if I know the GUID) but it does not appear on My Resources Page and can not be edited or deleted.

**Comment by pkdash** [comment]
@hyi Not sure if this still is an issue.

**Comment by hyi** [comment]
@dtarb @horsburgh To fix this issue, I will remove the edit and delete icons from isVersionOf relations as shown below:
![relation](https://cloud.githubusercontent.com/assets/476302/22512660/c5852250-e867-11e6-8040-4bd254e34b86.png)
so that isVersionOf can only be created by the system, but not editable by owners. Let me know if you think otherwise.

**Comment by dtarb** [comment]
I think this is OK.    I  think there is a need to take a look at relationship creation workflows and patterns holistically for versioning and copying and see if they all make sense.  @horsburgh is this something you would have time to do in the near (perhaps not immediate) future.

**Comment by horsburgh** [comment]
@hyi and @dtarb - I think this change is OK. Would this preclude us from adding a "isVersionOf" relationship to something outside of HydroShare - e.g., in the case that someone creates a resource in HydroShare that is a new version of something that lives elsewhere on the web?

**Comment by hyi** [comment]
@horsburgh Yes, "isVersionOf" option is not present in Add Relation dialog which has been done from the beginning when versioning was implemented. The proposed fix to this issue will not allow users to edit or remove isVersionOf relation value. I believe the current versioning implementation precludes users from adding "isVersionOf" relationship manually, so users will not be able to create a resource in HS that is a new version of something outside of HydroShare. Do we need to support it? Can we use other relations to support this use case?

**Comment by horsburgh** [comment]
@hyi - I think the changes you have proposed are fine. The implication is just that we are consciously giving up the ability for HydroShare to express that specific versioning relationship to something outside of the system. I think this is OK for simplicity sake.

**Comment by hyi** [comment]
@horsburgh OK. Agreed.

**Comment by hyi** [comment]
@dtarb I have tested this on beta and the issue appears to be resolved based on my testing. It'd be great if you can test it on beta also and close this issue if it works on beta or you can wait until after the 1.9.5 deploy so you can test on www, whichever works better for you.

**Comment by dtarb** [comment]
Tested on Beta.  OK.
