### ISSUE TITLE
Improvements to iRODS federation code

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#1657]
@hyi @rayi113 @mjstealey @pkdash @dtarb 
The iRODS federation code as written has several problems: 

1. The **federation logic is embedded into the application,** rather than into the storage object where it belongs. 
2. This means that in the normal Jenkins framework, there is **application code that can never be tested** because testing the federation requires a custom testing rig. 
3. In turn, **every manipulation of a file object requires dealing with federation.** 
4. Thus, there are two storage objects that deal with files, where only one can be instantiated at a time. 
5. These objects do not share the ground truth as to where the federation lives. 

Ideal federation code should be **transparent**, in the sense that the application (HydroShare) should not have to know whether it's federating or not. This is not difficult, but it is a radical departure from the federation code as written now. 

The proposed improvement is based upon these observations: 
1. It is easy to determine from the iRODS path alone whether an object is federated or not. 
2. It follows that `IrodsStorage` can take such a path and determine whether it is federated. 
3. Thus, `IrodsStorage` can handle all the federation logic by switching on the path that it is given; there do not need to be two variants `IrodsStorage()` and `IrodsStorage("federated")` that -- in turn -- require their own FileFields. 
4. Thus, the application need only manage the federated paths, and does not need to choose between storage models. 
5. This management can be eased by subclassing the `FileField` object to understand federation paths. 

Steps in accomplishing this: 
1. Encode all federation logic into `IrodsStorage`
    a. Define a configuration variable `LOCAL_IRODS_PREFIX` that determines whether a path is local. 
    b. If the path passed to `IrodsStorage` is local, then this prefix will match. 
    c. Else it is considered to be federated. 
2. Build a new field type `IrodsField` that subclasses `FileField`. See code [here](https://github.com/django/django/blob/stable/1.8.x/django/db/models/fields/files.py#L229)
    a. Look up the federation prefix of the resource from the Resource object that contains the `ResourceFile` that contains the `IrodsField`. 
    b. Call `IrodsStorage` in `IrodsField` with this federation prefix instead of the default `MEDIA_ROOT`. 
    c. Arrange to utilize this federation prefix in all code that uses the `IrodsField` contents. The cleanest way is to arrange for the prefix to be automatically prepended to the path! 
3. Perform a straightforward data migration to migrate data from the existing two `FileField`s to the one `IrodsField`. 
4. Refactor code for one `IrodsField` rather than two `FileField`s, by removing federation logic from the application. 
5. Remove the two `FileField`s from the model. 

Notes and caveats: 
1. This requires that the testing and validation for `IrodsStorage` needs to be separate from that of HydroShare and implemented in `django_irods` rather than in Jenkins tests.  Thus, `django_irods` must remain a separate repository. 
2. In turn, the Jenkins tests will not test federation at all. 

After this refactoring, 
1. There is no federation code at all in the application; all is in `IrodsStorage`. 
2. One can establish a separate testing regimen for `IrodsStorage` that doesn't run inside Jenkins and requires separate testing logic. 
3. Full code coverage testing of the affected application code is now possible in Jenkins. 
4. Further uses of files other than resources can transparently invoke federation.

**Comment by alvacouch** [comment]
@mjstealey Here are some notes on how this fits into what we have for federation so far. 

The simplest configuration for this scheme is to define -- in django_irods configuration -- a set of irods path prefixes that always correspond to local resources. This is the switch that turns on federation for the others. This can be read by the HydroShare application so that it agrees on these prefixes. 

The django_irods application is quite free to do federation any way it wishes. This proposal is -- to some extent -- **independent of federation structure**. More importantly, **one can make changes in structure without touching the HydroShare app.** This is what is really important. 

This does not alleviate the need -- as outlined in #1639 -- to establish hard boundaries in django_irods between "that which is required in order to make FileField work" and "that which is requires as utility functions in the HydroShare code". These are quite independent. The reason, as stated there, is to make the code more robust against changes in _Django_, e.g., the pending upgrade to 1.9 and (**gasp**) the impending discontinuity when and if Django 2.0 is released. 

This does make it possible and practical to store other kinds of objects in federated spaces. E.g., other things than resources.

**Comment by hyi** [comment]
Adding my notes here just for bookkeeping purposes:

1. The first simple improvement is to move a few lines where I used direct session run method to IrodsStorage in folder-related code and remove that getfile() method which is never used in our codebase. There might be a few minor simplifications in other places as well. But overall, these are some simple improvements for better encapsulation which can be done very quickly.

2. Currently there is a routine to detect whether files come from a federated zone or not dynamically after users select a file from an iRODS zone using irods browser, then after the resource is created, a property resource_federation_path is set on the resource object indicating where the resource is stored. This is all dynamic and determined at run time, so I am not sure how you can define a configuration variable LOCAL_IRODS_PREFIX to determine whether a path is local. In addition, purely determining whether a path is local is not sufficient, you will have to specify which zone the path comes from.

3. I did try subclassing FileField a bit when I initially implement federation, but I did not get it to work within reasonable complexity, so I gave up and implemented the way it is now. The other FileField object is for accommodating cases when adding a file from local disk to a federated zone, either in resource creation phase when adding files both from local disk and a federated zone, or in adding file to existing resource phase.

**Comment by alvacouch** [comment]
Reposting from email: 
As should be obvious, I cannot do that until your current PR is merged.

The key here is to 

a. tune django_irods to do what we want, and only then 
b. mess with FileField to understand the extra semantics. 

The absolutely crucial step is to get django_irods to be aware enough of federation – by whatever means – that it can decide which methods it needs for each kind of path. This is a function of your federation architecture. 

The rest is a straightforward Django hack.

I’ll need your help for the first part, because that is determined almost entirely by your federation architecture, but the second part I can handle easily. 

... or someone can explain the federation architecture to me and I can propose a solution.

**Comment by alvacouch** [comment]
Here -- for example -- is a simple hack that might work. 
1. Define only the local zone in django_irods configuration. 
2. Store the zone of files in the resource object. 
3. Subclass FileField to read the zone from the resource and then construct an appropriate path relative to that zone.

**Comment by hyi** [comment]
As you can see from django_irods code, the only difference between local zone and a federated zone is the session object which is used to do irods file operations. So I think it is simpler to provide a set session object method in django_irods storage, then the rest of methods have no need to change, which is what is currently implemented.

**Comment by alvacouch** [comment]
@hyi Another simple change is to keep two session objects open....! @mjstealey Are there any problems with that?

**Comment by hyi** [comment]
@alvacouch @mjstealey In my experiments, there can only be one active session object which iRODS uses to do the work. Otherwise, iRODS does not know which one to use, just like when using icommands, you will have to set up irods_environment.json file for one active session.

**Comment by hyi** [comment]
@alvacouch I really think the current way in django_irods to allow users to set an active session at run time works well, it worked well for our HydroShare RADII demo where we have to switch to a few different sessions at run time. It has been working well and simple in my opinion.

**Comment by alvacouch** [comment]
@hyi The actual strategy has to be based upon how we want IrodsStorage objects to be used in the code base. This includes potential service of parallel queries.  The assumption that all requests for a thing are going to hit a storage object in the appropriate state may not be well-founded. It is only true now because there is one storage object per kind of FileField. This is something to watch out for. In other words, I have to do a bit of research before accepting that strategy.

**Comment by alvacouch** [comment]
Note that my intent is not to take ownership of this code or to limit its function. My intent is to create a very open playground where federation strategies can be tried out, and where that experimentation is pretty much independent of the HydroShare code base.

**Comment by hyi** [comment]
@alvacouch Sounds good. Would be interested in knowing a better strategy when you come up with one.

**Comment by alvacouch** [comment]
Working with @mjstealey to understand the assumptions in the current federation scheme.

**Comment by alvacouch** [comment]
To me it seems that giving HydroShare a little information about each federated zone -- including its zone name and a bit of information about it's set up (the root resource directory) -- allows HydroShare to do pretty much anything with that zone. So there may not be inherent architectural limits on this. The really simple approach would be to create an IrodsZone object and register each zone in HydroShare, and then refer to that for each resource. 

This may not even be needed --- though -- if that information is functionally determined by other things we already know, e.g., an object's federation path. 

Then an object IrodsField based upon FileField could do more or less all of the heavy lifting, including computing the federation path, generating the iRODS url, etc.... things that are currently determined as needed.

**Comment by alvacouch** [comment]
A really simple way to deal with needing multiple sessions is by what's called "lazy binding" in which the django_irods application keeps a dictionary of active session objects, filed by capability. When a specific function is needed, the session is opened for that function. This session is left open until the end of life of the IrodsStorage() instance, because there is a possibility that the requests will be repeated. The lifetime of this object is almost always short, and the possibility that more than one session object will be needed is small, but this strategy prevents session state botches and makes use of the IrodsStorage() object pretty much general and unlimited in the code. When IrodsStorage() is destroyed, the sessions are closed. 

The reason for going to this trouble is that it would make use of the IrodsStorage object **context-independent**, in the sense that it could be used more or less anywhere in the code -- including during complex file migrations from one zone to another (!) -- with no ill effects.

**Comment by hyi** [comment]
@alvacouch I believe the lazy binding of active session object to IrodsStorage object is exactly what is currently implemented. Note that the plain password is part of the session setting, so we don't really want to keep sessions in database. After session is set, a temporary irods environment file and irodsA file for password is created under a unique directory and used for all subsequent irods operations. We don't always pass in session variables since if we know the session name, we can just set the name, then IrodsStorage() object knows where to find the temporary irods environment files and do operations using those settings, so all we need to do for subsequent operations when switching sessions is to provide the session name. This is what is exactly what is currently implemented.

**Comment by alvacouch** [comment]
@hyi @pkdash @dtarb 
In working on the folder code, I have evolved a very simple strategy for solving this problem: **make the model `ResourceFile` definitive for operations on files.** This involves moving all functions on files there, including moving, renaming, etc.  Then the application can simply call those functions. 

Specifically, 
1. **Encapsulate the filesystem operations inside the `ResourceFile` entity** and don’t let them leak out into the application. 
2. **Make the model fields and states of `ResourceFile` private** and opaque to the application. 
3. In the application, **call functions in `ResourceFile` to implement all file operations.**

In particular, I do not have to fix django_irods, as much as I would like to :) The real problem is to get the states of a file under control and managed in one place. Then we can modify federation strategy by modifying the ResourceFile object, and the application doesn't need to know about what we're doing at all.

**Comment by pkdash** [comment]
@alvacouch Encapsulating all file/folder operations within ResourceFile class sounds great.

**Comment by alvacouch** [comment]
2pkdash @hyi See branch # 1657 for a beginning. This is the crucial logic required to modify the `ResourceFile` for a modification of iRODS. The crucial method is `ResourceFile.set_storage_path`. This takes an iRODS path and sets up the `ResourceFile` so that it points to that path, regardless of allowed variations in the structure of that path. The result is a ResourceFile that is in one of two states: federated according to federation logic, or unfederated according to the original logic. The FileFields are modified to hold the actual position of the resource and local path variables are unnecessary. 

This does not implement the local caching of federated resources that has been mentioned, but that is a straightforward extension. .

**Comment by cbcunc** [comment]
Adding self as participant.

**Comment by alvacouch** [comment]
Addressed by migrating file operations to CompositeResource.
