### ISSUE TITLE
getResourceFromHydroShare "Not a zip file" 

### ISSUE THREAD

**Issue by leonard-psu** [hydroshare/hydroshare#1658]
I've been modifying the RHESSys workflow notebook to access resources from HydroShare.
I created two generic resources for the tutorial and published them. 

When I trying accessing the resource as follows:
content = hs.getResourceFromHydroShare('3328a6b2215e429a95ffb64e579f9d80')

I get a "not a zip file" error message. However, if I try to load the zip file using a "web app" i.e. document viewer, then I try again, the getResourceFromHydroShare function works.

**Comment by pkdash** [comment]
Is ```getResourceFromHydroShare()``` a custom function that you have written?

**Comment by leonard-psu** [comment]
No, 
using hs_utils inside jupyter notebook.

# import required libaries for geoprocessing
import os
import hs_utils
%matplotlib inline

# establish a secure connection to HydroShare
hs = hs_utils.hydroshare()
content = hs.getResourceFromHydroShare('2bca3052389d4b509a82444031af7f4d')

**Comment by mjstealey** [comment]
> using hs_utils inside jupyter notebook

@Castronova might have a better idea with regards to Jupyter notebook interaction...

**Comment by Castronova** [comment]
I'm working on this issue, but I haven't been able to reproduce it yet.

https://github.com/hydroshare/hydroshare-jupyterhub/issues/18

**Comment by pkdash** [comment]
@Castronova Are you using the latest version of hs_restclient?
