### ISSUE TITLE
make Web App res public without associating it with any Supported Res Type

### ISSUE THREAD

**Issue by zhiyuli** [hydroshare/hydroshare#1659]
In current implementation of Web App Res Type, the Supported Res Type metadata is a required field to make webapp public. That means user had to associate this webapp with at least one data res type before making it public. This is why we are having this issue "National water model data explorer. Should not open from resources." listed in #1650.

**Comment by zhiyuli** [comment]
this issue has been fixed. but it introduced a new issue see #1690

**Comment by pkdash** [comment]
@zhiyuli Can you test and close this issue?

**Comment by zhiyuli** [comment]
tested on www
