### ISSUE TITLE
Access control panel is not shown on the resource landing page

### ISSUE THREAD

**Issue by gantian127** [hydroshare/hydroshare#1660]
This error happens in the following situation: 
Suppose User 1 creates a resource and a group. User 1 shares this resource to User 2 with "edit" or "view" access right. User 1 adds User 2 as the group member.  After User 1 edits the group as "inactive", User 2 logs in the system and clicks on the resource that is shared from User 1, the resource landing page can't show the access control panel button. 

**resource landing page when the group is active:**

![image](https://cloud.githubusercontent.com/assets/5016511/20805383/a625d06a-b7b3-11e6-9b1d-02d605c8fd88.png)

**resource landing page when the group is inactive:**

![image](https://cloud.githubusercontent.com/assets/5016511/20805456/eed154ec-b7b3-11e6-8025-525a5643aba5.png)

**Comment by pkdash** [comment]
@alvacouch When debugging this issue, I found that ```r.raccess.view_users``` does not include User2. So it seems to me it is a bug in access control and not in the view function or at the UI level.

**Comment by pkdash** [comment]
@gantian127 Can you test this on beta to see if got fixed and then close it?
