### ISSUE TITLE
Add optional author identifiers

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#1666]
Resource authors/contributors may have additional identifiers associated with them that improve their identifiability.  These include ORCID, ResearcherID, Google Scholar ID, Research Gate ID etc.  Functionality needs to be added to HydroShare to support these and support data citation where identification using these is encouraged (see e.g. http://www.copdess.org/copdess-suggested-author-instructions-and-best-practices-for-journals/)

The following is needed
- [x] Add to user profiles optional fields for "Identifier Name" and "Identifier Link" that may hold content such as ("ORCID", "http://orcid.org/0000-0002-1998-3479"), ("ResearcherID","http://www.researcherid.com/rid/G-8972-2011").  A user may have 0 to many of these.  Display these as links on the user's profile page.
- [x] Add to author/contributor entries in resources the ability to automatically include these fields when loading content from a HydroShare user, and to add these fields manually when adding an author or contributor who is not a HydroShare user. 

This functionality is outlined in the science metadata design, but I do not think implemented anywhere yet https://docs.google.com/document/d/10xO-aIyaHC8y2baBupJukPhTjg-PJcrCmgT3gJ1qZ_s/edit

**Comment by pkdash** [comment]
@mauriel133 I am assigning this to you for the front-end changes needed for this issue. I can do the back-end changes.

**Comment by Maurier** [comment]
We are going to start with a small curated list and add an option to add Others. 

> ORCID, ResearchGate, Google Scholar, ResearchedID

**Comment by pkdash** [comment]
@dtarb and @horsburgh I assume these additional identifiers need to be written to the xml metadata file.

**Comment by horsburgh** [comment]
I was only intending for them to be part of the user's profile in HydroShare. So, if someone went to my profile page they would see the links i have created to my other profiles and could click on them. 

I don't think we should make them part of the metadata that gets added to resources a user creates.

**Comment by pkdash** [comment]
@horsburgh The example science metadata xml document for HydroShare that you once provided to me includes these external identifiers.

**Comment by horsburgh** [comment]
@pkdash - thanks for being thorough. @dtarb - you posted this issue, which I think is adding new functionality that we have discussed in the past. You indicated above that you want people to be able to add these optional author identifiers to the metadata of a resource when they create authors and contributors on resources. This means that they would become part of a resource's metadata (they would actually get written to the resource's resourcemetadata.xml file). I told @pkdash (2 comments above) that they should only be part of a user's profile and not get copied to a new resource from the profile. @pkdash needs feedback so he can move forward on this.

I guess my latest thinking (obviously a little different than in the past) is that when creating authors and contributors for a resource we should copy enough information from their profile to identify and contact them (essentially what we have now), but not necessarily copy all of these links to other profiles into the metadata for a resource. Something similar to what a journal does. When a viewer of the resource wants to get more information about an Author or Contributor, they would click on the links that we provide to the HydroShare profile page for the Author/Contributor. These optional, external profile links would appear on a user's HydroShare profile page.

My justification is that we have no control over the links to these external systems or the content that is there. Our resources are archival - and, where possible, I think we should think carefully about copying content into them that may be ephemeral. This is less of an issue I think on a user's profile page.

**Comment by dtarb** [comment]
I think that this identifier metadata should be copied into creator and contributor records that are part of resources.  ResearcherID and ORCID are not ephemeral.  They uniquely identify a specific researcher and are well established in the research citation world.  Journals often ask for them when publishing a paper.  The uniqueness they provide is not guaranteed by name and email (which is ephemeral).  I am not certain how stable ResearchGate and Google Scholar are, and I do not actually know what a Google Scholar ID is or how to find mine.  If there is concern over this, I would not object to scaling back and only doing ResearcherID and ORCID.

Another rationale for having the unique creator/contributor identifiers as part of the resourcemetadata.xml is that resource bags may persist outside HydroShare (e.g. if we do DataOne), and having identifiers not have to refer back to HydroShare makes them better.

**Comment by horsburgh** [comment]
@pkdash - looks like we are adding these to the resource metadata. This won't change the resource landing page display at all. This will only change what is included in the resourcemetadata.xml file.

**Comment by pkdash** [comment]
@horsburgh Only if we decide not show the identifiers for creators and contributors on the landing page. But I imagine we also at some point want the user to be able to add identifiers as part of creating creator/contributor on the resource landing page. If we do that then we probably have to list the identifiers there.

**Comment by horsburgh** [comment]
I don't think we should do profile editing type things on the resource landing page. I think creation or editing of linked profiles should only be done via the user's profile page.

**Comment by dtarb** [comment]
Correct, you do not edit a users profile from a resource landing page.  But you do edit author or contributor metadata.  That metadata may have been copied from the profile page.  If there is a place for these identifiers in the resource data model as part of author or contributor metadata, then we will need to have a place on the resource landing page to edit and add this when we are adding author or contributor that may not be a HydroShare user.  The behavior is the same as for other author or contributor metadata, such as organization.  It is copied at the time the resource is written, then only changed manually after that, no matter what a user does on their profile, e.g. change organization.

**Comment by dtarb** [comment]
Perhaps the distinction is that profile information is not linked, it is copied into the resource data entries.

**Comment by horsburgh** [comment]
@dtarb - this is why I was suggesting to NOT add the optional identifiers to the metadata and ONLY make that information part of the profile in HydroShare. Now, we have to add complexity to the user interface by providing all of this new editing functionality on the resource landing page.

But - OK - have at it @pkdash. @dtarb is right - if we are going to allow the inclusion of this information as part of the resource's metadata then it needs to be editable. But, I think we should NOT have a 2-way linkage between the user's profile and the metadata editing on the resource landing page. In other words, when a user is added as an author/creator to a resource, their information gets automatically pulled from their profile (or typed in where the author/creator is not a HydroShare user). But, when a user adds an external identifier or modifies some other piece of their information on the resource landing page, that that change would NOT get copied back into their profile.

If they want to edit their profile, they should go edit their profile.

**Comment by pkdash** [comment]
There has never been any linkage between hydroshare user object and creator/contributor and I am not proposing for creating any such linkage. The only thing that we do with user object as it relates creator/contributor is that we sometime create creator/contributor objects by copying data from the user object. The 2nd part of this github issue has the requirement that the user should be able to add/edit identifies for creators/contributors. Creators/contributors are currently editable only on the resource landing page.

**Comment by horsburgh** [comment]
Sounds good. Thanks @pkdash

**Comment by dtarb** [comment]
@horsburgh and @Maurier while you are looking at this issue please also look at #1787 and #1774 that are related.

**Comment by dtarb** [comment]
@Maurier @pkdash @horsburgh Based on being told that this was implemented in beta.hydroshare.org, my testing revealed the following problem

I tried
 
![image](https://user-images.githubusercontent.com/3456833/37163564-5df09316-22b5-11e8-8673-e8df6966043f.png)

I got the message 
![image](https://user-images.githubusercontent.com/3456833/37163583-67240cce-22b5-11e8-856f-fcd1ddaca3c2.png)
 
I tried
 
![image](https://user-images.githubusercontent.com/3456833/37163592-6cf2f1a6-22b5-11e8-8d91-93a4c522653f.png)

I got the message
![image](https://user-images.githubusercontent.com/3456833/37163604-72cedf04-22b5-11e8-8308-cad41b50c7b1.png)
 
I tried with https
 
![image](https://user-images.githubusercontent.com/3456833/37163621-7ad05976-22b5-11e8-8493-029031f6019a.png)

I got
![image](https://user-images.githubusercontent.com/3456833/37163638-821f1ef6-22b5-11e8-9a91-f77906786eb0.png)

Going around in circles

**Comment by pkdash** [comment]
@dtarb I this can be closed.
