### ISSUE TITLE
Upload into folder places file at the top level

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#1671]
In the resource landing page folder implementation, the UI enables a user to create a folder then open the folder and drag and drop files into the folder.  The appearance is that the file should go into the open folder.  However the file actually gets saved at the top level (contents).  It can then be moved into the folder, but it seems misleading to place files dragged into a folder at the top level.

**Comment by alvacouch** [comment]
This is not the whole problem. The other problem is that the current move software loses track of the actual file location in Django. This is because the folder into which it is being moved is not tracked.

**Comment by alvacouch** [comment]
@mauriel133 In PR #1672, the add_file* routines now include an optional argument file_folder that can be utilized to force an upload to a subfolder, but I don't know where to change the UI to make this possible in the UI.

**Comment by mauriel133** [comment]
@alvacouch, I can work on adding the rest. Is this argument implemented in the develop branch?

**Comment by mauriel133** [comment]
This has been implemented and deployed to www.
