### ISSUE TITLE
refine webapp resource metadata logic

### ISSUE THREAD

**Issue by zhiyuli** [hydroshare/hydroshare#1673]
Had a conversation with @pkdash about webapp resource metadata logic. This is a memo of the discussion and the new logic will be implemented after AGU.
"The way it should be implemented is that setting an empty string should fail the update action. Instead the user should be provided an option to delete an existing element the way we do with creators/contributors. I assume the base_url element has only one attribute (value). If there is no data for the value attribute then what's the use of the element?"

**Comment by dtarb** [comment]
@zhiyuli Is this still outstanding.  I see a merged PR so if this is already done, please close.  If not, please note what additional work is needed.

**Comment by aphelionz** [comment]
@zhiyuli @dtarb Please let me know the status of this

**Comment by zhiyuli** [comment]
closed
