### ISSUE TITLE
Better formatting of invalid CAPTCHA message 

### ISSUE THREAD

**Issue by pkdash** [hydroshare/hydroshare#1675]
![image](https://cloud.githubusercontent.com/assets/2523434/20896044/36fc4952-bad9-11e6-8a58-eedb9401f2f4.png)

Instead of the above message, it should show:

![image](https://cloud.githubusercontent.com/assets/2523434/20896772/7f4765b8-badc-11e6-899e-b0de55210c83.png)

**Comment by dtarb** [comment]
Good.
