### ISSUE TITLE
failed to create resource when the title includes non-English character

### ISSUE THREAD

**Issue by gantian127** [hydroshare/hydroshare#1691]
On resource creation page, if the title includes non-English character, the following error is shown:
![image](https://cloud.githubusercontent.com/assets/5016511/20948118/9a69d7d8-bbcf-11e6-93f1-b793af276f32.png)

**Comment by pkdash** [comment]
@gantian127 This has been fixed and can be tested on dev. Please close this issue if you find it resolved.

**Comment by mjstealey** [comment]
presumed to be done
