### ISSUE TITLE
Final Checklist for AGU Release

### ISSUE THREAD

**Issue by gantian127** [hydroshare/hydroshare#1698]
Please _**check the item**_ and _**close the issue**_ after testing the function on Beta site. https://beta.hydroshare.org/  
This final check need to be finished **before Thur** (Dec 8, 2016)
If the item assigned is not implemented for AGU release, please make a note beside the item.

**Christina** @ChristinaB
- [ ] #1561 
- [ ] #1560 
- [ ] #1554  
- [ ] #1457 
- [ ] #1456 

**Dan** @danames 
- [x] #1648
- [x] #1637 

**David** @dtarb 
- [x] #1616 
- [x] #1522 
- [x] #1464 

**Drew** @zhiyuli 
- [x] #1659 
- [ ] #1523 This broken res should be deleted by admin or owner on www (and beta): https://beta.hydroshare.org/resource/9700b80f5cfa42d4a52c9aaab81a4e11/
and
https://www.hydroshare.org/resource/9700b80f5cfa42d4a52c9aaab81a4e11/

**Jeff** @horsburgh 
- [ ] #484 
- [x] #1608 
- [x] #1534 
- [ ] #1411 

**Mauriel** @mauriel133 
- [ ] #1061
- [ ] #1530 

**Pabitra** @pkdash 
- [x] #1682 
- [ ] #1146 (not resolved)
- [x] #1147 
- [x] #1685 
- [x] #1675
- [x] #1425 

**Tian** 
- [x] #1660 

**Tony** @Castronova 
- [ ] #1531 

**Zhaokun** @xuezhaokun 
- [x] #1544
- [x] #1517 
- [ ] #1479 I think we have fixed almost all the awkward behaviors in the merged PR. We do not have a good solution for the slowness issue so far.

**Comment by dtarb** [comment]
With AGU behind us, closing this
