### ISSUE TITLE
More appropriate icon for manage access

### ISSUE THREAD

**Issue by jsadler2** [hydroshare/hydroshare#1699]
I think it be helpful from a UI perspective to have a more relevant icon for "sharing the resource"
![image](https://cloud.githubusercontent.com/assets/6943441/21019946/6fa50a8c-bd40-11e6-8c8a-a253b3d35725.png)

**Comment by jsadler2** [comment]
I have done the modification and this is what it looks like:
![image](https://cloud.githubusercontent.com/assets/6943441/21020066/e4ad7990-bd40-11e6-89ac-c422420e36b7.png)
@dtarb @mauriel133 what do you think? Should I make a PR?

**Comment by danames** [comment]
Much better icon. Good work, Jeff.

**Comment by dtarb** [comment]
I am OK with both the old and the new one.  If folks want to change I have no objection.

**Comment by mauriel133** [comment]
I like this icon as well.

**Comment by pkdash** [comment]
@jsadler2 Are you planning to implement this change?

**Comment by jsadler2** [comment]
This has been pulled into develop
