### ISSUE TITLE
iRODS basics

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#17]
Establish and document the procedures for HydroShare to use iRODS for resource storage.  This comprises
1.  Setting up a HydroShare iRODS server (operating system selection and software stack setup script)
2.  Setting up a HydroShare iRODS datagrid zone (iCAT server)
3.  Documenting procedure for HydroShare iRODS server to join HydroShare iRODS datagrid zone.
4.  Documenting procedure for configuring HydroShare Django instance to use HydroShare iRODS grid as a network file system.
Note that at this stage we are not using Federation, but do contemplate multiple servers participating in the same datagrid zone served by an iCAT server.

**Comment by rayi113** [comment]
- [x] Setting up a HydroShare iRODS server (operating system selection and software stack setup script)
- [x] Setting up a HydroShare iRODS datagrid zone (iCAT server)
- [ ] Documenting procedure for HydroShare iRODS server to join HydroShare iRODS datagrid zone.
- [ ] Documenting procedure for configuring HydroShare Django instance to use HydroShare iRODS grid as a network file system.

**Comment by aphelionz** [comment]
@dtarb @mjstealey @rayi113 

Do we want to close this and / or make tickets for the remaining items?

- Documenting procedure for HydroShare iRODS server to join HydroShare iRODS datagrid zone.
- Documenting procedure for configuring HydroShare Django instance to use HydroShare iRODS grid as a network file system.

**Comment by rayi113** [comment]
I suggest closing this and creating tickets for the remaining items to be completed after #1566 @hyi implementation of file quota.

**Comment by dtarb** [comment]
OK Closing.
