### ISSUE TITLE
Unable to add existing user to author list 

### ISSUE THREAD

**Issue by leonard-psu** [hydroshare/hydroshare#1705]
I'm trying to add authors to a new generic resource. When I search for "Larry Band" his name appears, but is greyed out. I cannot "Save Changes". If I change from "Existing HydroShare User" to "Other", and type Band's details, then I can save changes.

**Comment by dtarb** [comment]
@hyi @pkdash @mohamedmorsy can you please investigate this as a possible hotfix item.  Adding authors is the sort of thing that AGU demos will likely want to show.

**Comment by pkdash** [comment]
@dtarb I have found the bug and will be creating PR as a hot fix soon.

**Comment by dtarb** [comment]
@pkdash Much appreciated!

**Comment by hyi** [comment]
@leonard-psu or @dtarb Can you verify the fix and close the issue if it works now?

**Comment by dtarb** [comment]
Verified.
