### ISSUE TITLE
Uploaded executable files should be scanned for viruses.

### ISSUE THREAD

**Issue by aphelionz** [hydroshare/hydroshare#1709]
Since registration on hydroshare is free and since anybody can create a resource / upload a file, we can't assume every file uploaded is safe. Certain files uploaded to Hydroshare pose the risk of being maliciously infected with malware/spyware/viruses/etc, posing a risk to users who try to download and run certain resources. We should investigate options for virus scanning software for 64 bit linux and implement one to run against uploaded executable files.

**Comment by sblack-usu** [comment]
This is a "nice to have" but has not been communicated as a priority and we are unlikely to get to it with our current backlog.
