### ISSUE TITLE
Science Metadata XML Document Missing Dublin Core Type Element

### ISSUE THREAD

**Issue by horsburgh** [hydroshare/hydroshare#171]
I created two resources on dev.hydroshare.org.

Time Series Resource: http://dev.hydroshare.org/resource/f5e4c6083e8d4e91be216295f7b6282e/
Generic Resource:  http://dev.hydroshare.org/resource/26973647d27d46b58be3dcd1d889f6bb/

When I download either one, the Dublin Core Type element is missing from the science metadata document.  It should be something like:

Time Series Resource:  <dc:type rdf:resource="http://hydroshare.org/terms/timeSeriesResource"/>
Generic Resource:  <dc:type rdf:resource="http://hydroshare.org/terms/genericResource"/>

NOTE:  we need URI friendly labels for each HydroShare resource type that are part of our controlled vocabulary of HydroShare resource types.  For example:

Time Series Resource:  http://hydroshare.org/terms/timeSeriesResource
Generic Resource: http://hydroshare.org/terms/genericResource
Raster Resource:  http://hydroshare.org/terms/rasterResource

**Comment by dtarb** [comment]
@pkdash will you be able to address this for 1.4 or should we put off to 1.5.  @horsburgh please help Pabitra with specific format of type element if he needs.

**Comment by pkdash** [comment]
@horsburgh and @dtarb We don't have these 'type' specific URI endpoints implemented yet. Not sure what would be the content of each of these endpoints. I suggest we implement this in 1.5.

**Comment by pkdash** [comment]
@horsburgh Is this resource 'type' URI should point to a web page for each specific resource type?

**Comment by ironfroggy** [comment]
Does this refer to the XML generated by `serialize_science_metadata_xml()`? If so, that is being removed in my API purge branch, based on confirmation that it was not in use. Perhaps while this was true, it was not the complete story and it *should* be used and I need to update my purge to keep it?

**Comment by ironfroggy** [comment]
Reference to its removal in my pull request:

https://github.com/hydroshare/hydroshare/pull/252/files#diff-739dd5e04e836fb8447f3556c16a7075L131

**Comment by hyi** [comment]
@pkdash correct me if I am wrong, but I am pretty sure serialize_science_metadata_xml() is not used and replaced by new method written by Pabitra, and it is safe to remove it.

**Comment by pkdash** [comment]
@hyi and @ironfroggy The 'serialize_science_metadata_xml()' method is no more used. It is safe to purge it.

**Comment by horsburgh** [comment]
This comes down to whether and how we are going to have any controlled vocabularies.  My original suggestion that we have terms expressed as URIs assumed that we would formally define terms that we are using in controlled vocabularies and that they would be defined somewhere in the HydroShare domain (see my example above) and that they would have formal URIs.  

But, if we are not going to do this, we could just use a list of terms that we agree upon and encode them within a "Type" element rather than referencing them as a URI. 

@dtarb - Do you want to make HydroShare resource types a formal vocabulary, or do you want us to just come up with a list of terms for the resource types that get consistently used within the "Type" element?

**Comment by dtarb** [comment]
@horsburgh which option do you think is best for a user?  I do not want to create formal vocabularies just for the sake of creating them, but if they are something that is best for a user then we should do it.  Can we list the advantages and disadvantages of each approach from the perspective of a user and use these to decide?

**Comment by horsburgh** [comment]
From a user perspective, I think what is needed is a list of terms to choose from. These would be static terms with no links to definitions when displayed in selection dialogs or menus throughout the site, We need to agree on the list of terms and use it consistently (e.g., everywhere we use the resource type terms, they need to be the same - drop down lists, encoded in science metadata, URL query strings, etc.). 

What exactly do we mean when we say "Time series resource" or "Raster resource".  We need to have some documentation somewhere on the website that tells users what these are.

**Comment by pkdash** [comment]
I have done some work to have a web page for each resource type to describe the resource type. For example, I have the "type-timeseriesresource.html" to describe the 'Time series resource". For now I have taken some content out of the time series content model specification document to show in this web page. The url for this web page is  /timseriesresource. This will be the url pattern for other resource types. For other implemented resource types I have created the resource type template pages. Each resource type developer just need to put content in that page.

**Comment by dtarb** [comment]
I think this is a good solution.

**Comment by pkdash** [comment]
@horsburgh and @dtarb This issue is currently part of the release 1.5. If we just want a valid url for the 'type' element I can get it done today however, except for 'TimeSeriesResource' for all other resource types it will point to a page that just shows resource type name. I am not sure if other resource type developers will have time to put resource type content to these pages for release 1.5.

**Comment by dtarb** [comment]
It is fine to create placeholder pages for the other resource types.  Please as you do it, include at least a sentence saying what the resource type is (i.e. more than just a name) and then create an issue assigned to the resource champion for the other resources to fill out the content (that is for a deploy later than 1.5)

**Comment by horsburgh** [comment]
Another option would be to have separate URIs that all resolve to the same page.  For example, see:

http://purl.org/dc/terms/abstract and http://purl.org/dc/terms/contributor

Both of these take you to:

http://dublincore.org/documents/2012/06/14/dcmi-terms/?v=terms

So, we could maintain one page that has all of our terms and definitions on it.

**Comment by hyi** [comment]
I like this option to have separate URIs all resolve to the same page that has all of our terms and definitions. Specific resource type URI can then directly jump to the relevant resource type description and terms by query string in the request.

**Comment by horsburgh** [comment]
If this core metadata element is left out of resources that are created for NFIE, and if the NFIE release is going to be www.hydroshare.org, when will this element get added to all resources for which it will be missing?  The HydroShare resource type seems like something that is fundamental.

**Comment by pkdash** [comment]
@horsburgh and @dtarb - The last commit that I have made will create the core metadata term 'type' when a new resource gets created. The science metadata document will now contain this term with a resolvable url and the namespace 'hsterms' will also have a resolvable url. However, any existing resource will still not have the 'type' metadata element. Not sure what we can do about that. 

I have added a new web page "hs_core/templates/pages/metadata_terms.html" as a placeholder for term definitions. I have put some content in that web page related to Time Series Resource Type. I think once this fix is merged to the develop branch, each resource type developer needs to update this web page for which we can create separate github issues.

If this implementation looks OK to you I can create a PR for it soon.

**Comment by horsburgh** [comment]
@pkdash - didn't we have this metadata element already?  It has always been one of the required Dublin Core elements.

**Comment by pkdash** [comment]
@horsburgh  - I know it is a required element but I think I didn't create as part of the resource creation as there was no resolvable url endpoint for this element until now. That's the reason this element has been missing in the xml document which is this issue you created a while ago.

**Comment by pkdash** [comment]
Here is the template (as displayed in browser) that is used as a resolvable url for hsterms and metadata type element:

![image](https://cloud.githubusercontent.com/assets/2523434/9044798/3de33d86-39dc-11e5-9d93-ec4a96f8fe03.png)

**Comment by pkdash** [comment]
@gantian127 - Please pull this branch and update hs_core/templates/pages/metadata_terms.html file to describe netcdf resource type and resource type specific metadata terms.

**Comment by pkdash** [comment]
@zhiyuli - Please pull this branch (171-metadata-xml-document-missing-type-element) and update hs_core/templates/pages/metadata_terms.html file to describe Reference Time Series resource type, Tools resource type and corresponding resource type specific metadata terms.

**Comment by pkdash** [comment]
@Castronova - Please pull this branch (171-metadata-xml-document-missing-type-element) and update hs_core/templates/pages/metadata_terms.html file to describe Model Program Resource type and corresponding resource type specific metadata terms.

**Comment by pkdash** [comment]
@mohamedmorsy Please pull this branch (171-metadata-xml-document-missing-type-element) and update hs_core/templates/pages/metadata_terms.html file to describe Model Instance Resource Type. and SWAT Model Instance Resource Type and corresponding resource type specific metadata terms.

**Comment by hyi** [comment]
set it to ready for testing as things are working as expected on dev based on my testing.

**Comment by horsburgh** [comment]
@pkdash - assuming this is working correctly, I can do a couple of tests and close.  But, what did we decide to do about resources in HydroShare created before this fix was in place and that do not have the required "Type" element?

**Comment by pkdash** [comment]
@horsburgh Since we will be recreating resources as part of the base concrete class migration, the 'type' element would be automatically added at the time of resource creation.

**Comment by pkdash** [comment]
@horsburgh and @dtarb Tomorrow during the dry run of the bag ingestion as part of resource migration we will know if the metadata element 'type' gets created in Django database as well as written to the xml file. If it does then this issue can be closed.

**Comment by dtarb** [comment]
Have you identified some resources being migrated where it is that you can use to check.

**Comment by hyi** [comment]
@dtarb Based on my check, the type element is included, at least present from the resourcemetadata.xml file, but @pkdash can double check to make sure, and we can do the extra check during migration dry-run.

**Comment by dtarb** [comment]
@hyi we need to check whether an old resource that currently does not have this metadata element gets it during the migration process.

**Comment by pkdash** [comment]
@horsburgh and @dtarb I checked on riverdev where Michael has done a dry run of bag ingestion as part of the data migration, and I can see the 'type' metadata element in metadata xml document for resources that were created before we fixed this issue. This issue now can be closed.

**Comment by dtarb** [comment]
@pkdash @selimnairb I checked the migration of 50fa9c5b3b5b4263bf4f1752a8b6723c by looking at its contents in both www.hydroshare.org and riverdev.hydroshare.org.  While there is now a type element I note the following problems.

1.  The type element is given as "NetcdfResource".  This is not the right name and not defined at https://www.hydroshare.org/terms/.  There is a document/issue that defines these elements.  I can not find it right now.  Going by memory I think it is supposed to be "Multidimensional".

2.  In the resource on riverdev HydroShare Admin is listed as owner and first author.  This is not right.

3.  The description element that holds the abstract is not present in the XML file for the migrated resource.

4.  The relation element that gives what this resource cites is not present in the XML file for the migrated resource.

**Comment by selimnairb** [comment]
@dtarb See my comments for each item.

1. In the resourcemap.xml from www.hydroshare.org:

    <dcterms:type>NetcdfResource</dcterms:type>

The displayed resource type on both www. and riverdev. is: Multidimensional (NetCDF)

2. The owner of the original resource on www. is:

    <dc:creator>
      <rdf:Description>
        <hsterms:name>Tseganeh Z. Gichamo</hsterms:name>
        <hsterms:creatorOrder>1</hsterms:creatorOrder>
        <hsterms:organization>Utah state university</hsterms:organization>
        <hsterms:address>Logan, UT 84322</hsterms:address>
      </rdf:Description>
    </dc:creator>

This creator has no HyroShare user associated with it.  Because some user is required to be the creator when the resource is created, in this case, the migration code uses the admin user.  We will have to manually change ownership for such resources on a case-by-case basis.

3. & 4 You are correct, the abstract and relation are missing from the serialization of the migrated resource.  Also, the original creator is not showing up.  @hyi Can you update your migration script to force all bag files to be recreated after migration?  This should force a flush of all metadata elements from the Django database into the appropriate RDF+XML serialization.

**Comment by hyi** [comment]
@selimnairb I think rather than doing post-processing to recreate bags in migration script, it is better to call utils.resource_modified() function at the end of your serialization function write_metadata_to_resource() to recreate bags and set bag_modified irods AVU accordingly as is currently done in hydroshare code base whenever metadata elements or resource files are changed. This will make sure the bag recreation is taken care of when this metadata serialization function is used for bag ingestion REST API in the future. You may not be able to directly call utils.resource_modified() function since that function update date metadata element to current date which you don't want for bag ingestion, but can be easily adapted to be leveraged by your bag ingestion needs. We can discuss further in today's dev call if needed or we can chat via hipchat.

**Comment by selimnairb** [comment]
@hyi I have just experimented with calling hs_core.hydroshare.hs_bagit.create_bag_files() after the resource metadata is created.  This seems to solve the problems of missing metadata.  Is this sufficient, or do we also call code to update the iRODS AVU?  (I'd rather not call resource_modified() as I don't want the modification date to change)

**Comment by hyi** [comment]
@selimnairb I believe this is sufficient since hs_bagit.create_bag(resource), called by create_resource() which is called by your bag ingestion serialization function, sets irods AVU to mark resource dirty initially when resource is initially created. Yes, I think it is sufficient.

**Comment by pkdash** [comment]
@dtarb and @horsburgh The resource class name is being used for the 'type' element. I think we need to use the resource 'verbose_name' instead which is also used in resource listing page. @selimnairb This change needs to be done before we do the final bag ingestion/resource migration.

**Comment by selimnairb** [comment]
@hyi I believe this is sufficient as well because the bag I get back after calling create_bag_files() has the metadata that was missing when this function was not called after resource ingest.  See #657.

**Comment by selimnairb** [comment]
@pkdash Will this change how the resource type is represented in resourcemap.xml, or just resourcemetdata.xml?

**Comment by pkdash** [comment]
@selimnairb It will only change the resourcemetadata.xml. The resourcemap.xml will still have the resource class name for the type. I am not sure if that would be a problem as the type element will have different values between these two documents.

**Comment by selimnairb** [comment]
@pkdash.  No this will not be a problem.  Currently I do not validate the type between the resource map and resource metadata.  I use the type in the resource map to determine the resource type; this happens before the resource metadata is even looked at.  This should have no affect on the ingest code.

**Comment by pkdash** [comment]
@selimnairb I was thinking if @horsburgh or @dtarb would have any issues with the 'type' element having different values between the 2 documents.

**Comment by horsburgh** [comment]
The difference between the two encodings for the Resource Type element we were discussing on the call would be as follows:

Option1: <dcterms:type>TimeSeriesResource</dcterms:type>
Option2: <dcterms:type rdf:resource="http://www.hydroshare.org/terms/TimeSeriesResource"/>

Using Option 2 would require that we add a section to the page at https://www.hydroshare.org/terms/ that specifically defines each of the resource type terms (i.e., "TimeSeriesResource").  Right now, we have sections on that page for each of them, but the resource type terms are not specifically listed and defined.  And, we would need to ensure that the URI encoding of the terms actually resolves to this page.

Obviously, the URI friendly versions of these terms (either option above) is probably not what we want to display on any views.  If we want the longer, more human readable terms with spaces, etc. along with the URI encoding we could add the following:

<rdf:Description rdf:about="http://www.hydroshare.org/terms/TimeSeriesResource">
    <rdfs1:label>Time Series Resource</rdfs1:label>
    <rdfs1:isDefinedBy>http://www.hydroshare.org/terms</rdfs1:isDefinedBy>
</rdf:Description>

**Comment by pkdash** [comment]
@horsburgh I would prefer option2 as this would not affect our current migration work since the only change we have to make later is the metadata terms html page is to define the resource type terms.

**Comment by horsburgh** [comment]
@pkdash - would you also add the additional RDF code that encodes the label for the term (the second bit of code in my post)?

**Comment by pkdash** [comment]
@horsburgh I will include the 2nd bit of rdf. But I am not sure if it would be a nested element of the type element.

**Comment by dtarb** [comment]
Getting back to @selimnairb 's point 2 above it is not right to say the "owner" is and then show an xml snippet that gives the "creator".  Owner and creator are not the same.  Owner is the HydroShare user that has access control rights over the resource in HydroShare.  Creator is Dublin Core metadata for the person responsible for the intellectual content - the author in more common terminology.  These are not the same.  In the case of this resource on www the HydroShare owners are Tian Gan and David Tarboton.  If these ownership rights are to be transferred manually we need to enumerate what is involved to be able to scope this problem.  Alternatively a second script that uses the API to set permissions may be more automatible and less error prone.

**Comment by horsburgh** [comment]
@pkdash - it doesn't have to be nested with the type element.  Below is an example of how this would look in a Resource Map document. Unfortunately GitHub doesn't allow embedding of XML files.
```xml
<?xml version="1.0" encoding="UTF-8"?>
<rdf:RDF
   xmlns:citoterms="http://purl.org/spar/cito/"
   xmlns:dc="http://purl.org/dc/elements/1.1/"
   xmlns:dcterms="http://purl.org/dc/terms/"
   xmlns:foaf="http://xmlns.com/foaf/0.1/"
   xmlns:ore="http://www.openarchives.org/ore/terms/"
   xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
   xmlns:rdfs1="http://www.w3.org/2001/01/rdf-schema#"
>
  <rdf:Description rdf:about="http://www.hydroshare.org/resource/1a25b11fa1354773b6edb9495e754f4e/data/contents/ODM2.sqlite">
    <dc:format>application/sqlite</dc:format>
    <ore:isAggregatedBy>http://www.hydroshare.org/resource/1a25b11fa1354773b6edb9495e754f4e/data/resourcemap.xml#aggregation</ore:isAggregatedBy>
  </rdf:Description>
  <rdf:Description rdf:about="http://www.openarchives.org/ore/terms/Aggregation">
    <rdfs1:label>Aggregation</rdfs1:label>
    <rdfs1:isDefinedBy>http://www.openarchives.org/ore/terms/</rdfs1:isDefinedBy>
  </rdf:Description>
  <rdf:Description rdf:about="http://foresite-toolkit.googlecode.com/#pythonAgent">
    <foaf:mbox>foresite@googlegroups.com</foaf:mbox>
    <foaf:name>Foresite Toolkit (Python)</foaf:name>
  </rdf:Description>
  <rdf:Description rdf:about="http://www.hydroshare.org/resource/1a25b11fa1354773b6edb9495e754f4e/data/resourcemetadata.xml">
    <ore:isAggregatedBy>http://www.hydroshare.org/resource/1a25b11fa1354773b6edb9495e754f4e/data/resourcemap.xml#aggregation</ore:isAggregatedBy>
    <dc:title>Dublin Core science metadata document describing the HydroShare resource</dc:title>
    <dc:format>application/rdf+xml</dc:format>
    <citoterms:documents>http://www.hydroshare.org/resource/1a25b11fa1354773b6edb9495e754f4e/data/resourcemap.xml#aggregation</citoterms:documents>
  </rdf:Description>
  <rdf:Description rdf:about="http://www.openarchives.org/ore/terms/ResourceMap">
    <rdfs1:label>ResourceMap</rdfs1:label>
    <rdfs1:isDefinedBy>http://www.openarchives.org/ore/terms/</rdfs1:isDefinedBy>
  </rdf:Description>
  <rdf:Description rdf:about="http://www.hydroshare.org/resource/1a25b11fa1354773b6edb9495e754f4e/data/resourcemap.xml#aggregation">
    <dcterms:type rdf:resource="http://www.hydroshare.org/terms/TimeSeriesResource"/>
    <ore:aggregates rdf:resource="http://www.hydroshare.org/resource/1a25b11fa1354773b6edb9495e754f4e/data/resourcemetadata.xml"/>
    <citoterms:isDocumentedBy>http://www.hydroshare.org/resource/1a25b11fa1354773b6edb9495e754f4e/data/resourcemetadata.xml</citoterms:isDocumentedBy>
    <dc:title>Water Temperature in the Little Bear River at Mendon Road near Mendon, UT</dc:title>
    <ore:aggregates rdf:resource="http://www.hydroshare.org/resource/1a25b11fa1354773b6edb9495e754f4e/data/contents/ODM2.sqlite"/>
    <ore:isDescribedBy>http://www.hydroshare.org/resource/1a25b11fa1354773b6edb9495e754f4e/data/resourcemap.xml</ore:isDescribedBy>
    <rdf:type rdf:resource="http://www.openarchives.org/ore/terms/Aggregation"/>
  </rdf:Description>
  <rdf:Description rdf:about="http://www.hydroshare.org/resource/1a25b11fa1354773b6edb9495e754f4e/data/resourcemap.xml">
    <dc:format>application/rdf+xml</dc:format>
    <dcterms:modified>2015-06-06T04:25:06Z</dcterms:modified>
    <dc:identifier>1a25b11fa1354773b6edb9495e754f4e</dc:identifier>
    <dc:creator rdf:resource="http://foresite-toolkit.googlecode.com/#pythonAgent"/>
    <ore:describes rdf:resource="http://www.hydroshare.org/resource/1a25b11fa1354773b6edb9495e754f4e/data/resourcemap.xml#aggregation"/>
    <dcterms:created>2015-06-06T04:25:06Z</dcterms:created>
    <rdf:type rdf:resource="http://www.openarchives.org/ore/terms/ResourceMap"/>
  </rdf:Description>
  <rdf:Description rdf:about="http://www.hydroshare.org/terms/TimeSeriesResource">
    <rdfs1:label>Time Series Resource</rdfs1:label>
    <rdfs1:isDefinedBy>http://www.hydroshare.org/terms</rdfs1:isDefinedBy>
  </rdf:Description>
</rdf:RDF>
```

**Comment by pkdash** [comment]
@horsburgh Then I assume the changes are only for the resourcemap document and not science metadata document.

**Comment by dtarb** [comment]
I think that the label used for a resource type should be consistent between resourcemap and resourcemetadata document.

**Comment by horsburgh** [comment]
@pkdash - can we make the same changes in both documents?

**Comment by pkdash** [comment]
@horsburgh will make same changes to both documents. Once the bags are ingested, we will run a script to regenerate the xml documents to get these document in the new format.

**Comment by selimnairb** [comment]
@horsburgh @pkdash This is fine with me.  When we do this, we will need to also add an internal API call to map the pretty name (e.g. Time Series Resource) to the internal model class name (e.g. TimeSeriesResource).  This way code such as the bag ingest code can easily determine the class to load for deserialization without jumping through a lot of hoops.

**Comment by pkdash** [comment]
@horsburgh Please test this at www and close this issue if found to be resolved.

**Comment by horsburgh** [comment]
@pkdash - I just had a look at this one.  It appears that on www.hydroshare.org, the "type" element has been added to my existing public resource. I also created a new resource and made sure that it showed up for a newly created resource.  I had just a couple of observations:

* In my existing public resource, there was some extra indentation for the type element.  This was not an issue in my newly created resource. I submitted the XML to the W3C RDF validator and this did not affect the parsing (of at least that tool).

![screenshot](https://cloud.githubusercontent.com/assets/3485902/10825730/f501aeb0-7e2b-11e5-9316-079147d6d662.png)

* In the resource map document we use `<dcterms:type>` whereas in the science metadata we use `<dc:type>`. I don't think this matters too much because the "type" term actually exists in both namespaces and as far as I can tell is the same.

If neither of these are significant, I think this can be closed.

**Comment by pkdash** [comment]
@horsburgh When I tried to look at the resourcemap document for the same resource, I am not seeing the extra indenting problem:

![respourcemap](https://cloud.githubusercontent.com/assets/2523434/10834677/f22a2a48-7e60-11e5-91aa-a8d9138587f9.png)

**Comment by horsburgh** [comment]
@pkdash - I think the web browser uses a style sheet to render the XML, and so the extra spacing doesn't show up.  My screen shot is from a text editor.  Like I said, I don't think it really matters because it seems to be being interpreted just fine.  I'm going to close this one.
