### ISSUE TITLE
Various problems in access control

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#1710]
This is a container for several deficiencies in access control discovered during the AGU release: 
1. antibugging routines are called too frequently. #1643 
2. get_resources_with_explicit_access does not list access via groups. 
3. Base existing privilege on individual or group privilege, but not upon combined privilege #1622

**Comment by alvacouch** [comment]
@pkdash How should we resolve the issue about access granted through groups not showing up in `get_resources_with_explicit_access()`.

I suggest that I create a new method `get_resources_with_explicit_group_access()`
that satisfies the requirements, and then factor that into the UI. 

That is how @mauriel133 usually thinks about this in coding the UI. Keep group privilege and user privilege separate. 

Other possibilities?

**Comment by pkdash** [comment]
@alvacouch Can we create a function similar to this? https://github.com/hydroshare/hydroshare/blob/develop/hs_access_control/models.py#L2365

**Comment by alvacouch** [comment]
@pkdash Yes, but I dislike that function's calling style.... quite confusing to me.... should use accumulated Q expressions....

**Comment by alvacouch** [comment]
@pkdash See PR #1717 for a new version of get_resources_with_effective_access that handles 'via_group' and 'via_user' parameters. See the discussion there of how `via_group` and `via_user` interact. In particular, **when both are enabled, lower privilege number (higher privilege) in one 'masks' the existence of the other.**

**Comment by alvacouch** [comment]
Issue addressed in PR#1717
