### ISSUE TITLE
Pass http/https status from nginx to django

### ISSUE THREAD

**Issue by zhiyuli** [hydroshare/hydroshare#1711]
Currently nginx takes care of ssl/https encryption/decryption, but django is ignorant of this and assumes all requests are over http. In some cases where django dynamically generates a url for redirecting, it must know the http/https status of the original request made against nginx in order to assemble a correct url.

A sign of this issue is the presence of a "301 redirect" when logging in apps server through hydroshare oauth. Nignx redirects a request against a http url (generated by django oauth) to its corresponding https url.
![image](https://cloud.githubusercontent.com/assets/10070599/21118363/d158b070-c07a-11e6-924e-bec5fd9d83d6.png)

**Comment by pkdash** [comment]
@zhiyuli Is this still need to be resolved?

**Comment by martinseul** [comment]
Close: stale @alvacouch please re-open if its still an issue
