### ISSUE TITLE
Fail to share resource

### ISSUE THREAD

**Issue by Maurier** [hydroshare/hydroshare#1712]
I'm encountering an error at https://beta.hydroshare.org and at my local instance when trying to share a resource. I get the following error:

![image](https://cloud.githubusercontent.com/assets/2448568/21119004/b547745e-c07d-11e6-839e-03ebd7aa02c0.png)

Edit: also happens at https://www.hydroshare.org

**Comment by mauriel133** [comment]
@pkdash, could you check if you are also getting this error?

**Comment by pkdash** [comment]
@mauriel133 I am aware of this error. If you try to add any other user who is not a super user you should not see this error. It's   a bug in access control.

**Comment by cuahsimarko** [comment]
This is only for superusers
