### ISSUE TITLE
weird username displayed on apps-tethys home page

### ISSUE THREAD

**Issue by zhiyuli** [hydroshare/hydroshare#1715]
A reminder to this issue brought up by Lorne Leonard during AGU
![image](https://cloud.githubusercontent.com/assets/10070599/21122353/ce9572f6-c08e-11e6-8910-de8cb0c72b40.png)

**Comment by pkdash** [comment]
@zhiyuli Wondering if this has been fixed.

**Comment by mjstealey** [comment]
> Wondering if this has been fixed

@pkdash - That is an artifact of using oauth as a sign in mechanism along side of standard sign in on Apps.
This would be the case for any site using both standard account creation along side of oauth from site XXX without some other kind of explicit user mapping. 

In short, user **drew** is a different user than **drew6252fee7c0934e4c** from Apps point of view.

i.e.
- Sign in with USERNAME/PASSWORD points to account: USERNAME
- Sign in with USERNAME@Facebook/Token points to account USERNAME#FacebookToken
- Sign in with USERNAME@Twitter/Token points to account USERNAME#TwitterToken

You'll get 3 different accounts as there is no default way to match these to each other out of the box. Every oauth service chooses what information to send back to the client, so there isn't any magical match to USERNAME <--> USERNAME#OauthToken unless you explicitly code it. To my knowledge we have not done this.

**Comment by zhiyuli** [comment]
fixed a while ago
