### ISSUE TITLE
NWM App Fixes

### ISSUE THREAD

**Issue by danames** [hydroshare/hydroshare#1716]
Suggestions from @dtarb 

- [ ] In Forecast viewer filter the blue line streams to show only those with forecasts.  It is possible to click on a canal and get an error.
- [ ] Make  the default date the day before so that the issue of forecast not ready is handled.
- [ ] Use space better in Forecast viewer.  When I view on a portrait oriented screen I get a map in about the top 1/5 of the screen and 80% white.

**Comment by danames** [comment]
I'm assigning to @zhiyuli to help keep track of it. Though probably Christian can make these updates.

**Comment by ChristinaB** [comment]
[NWMForecastViewerDemo_CB.docx](https://github.com/hydroshare/hydroshare/files/1075526/NWMForecastViewerDemo_CB.docx)

Hi @danames and @zhiyuli 
As you finalize the NWM App updates for the Summer Institute, I wanted to direct your attention to the latest printable demo for the App (attached).  We will also want to review the Help page for the App at https://pages.hydroshare.org/apps/nwm-forecast-viewer/
The plan is to add a link to the demo on the Help page. You could also include a link from the App information page.  

Once this demo is updated to match the current changes, the plan is to upload it to a HydroShare resource and get a public file URL that can be used for the linking, unless you have another suggestion.

**Comment by ChristinaB** [comment]
HI @zhiyuli  -- let's see if your latest updates fix this issue, and then we can close it, or break into smaller issues and then we can continue the updating from there.

**Comment by aphelionz** [comment]
This issue was moved to CUAHSI-APPS/nwm-forecast-viewer#25
