### ISSUE TITLE
Jenkins reports flake8 errors, but error report is blank

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#1718]
@mjstealey  Lately, I have received (real) flake8 errors in Jenkins but the actual error report is blank and reports no errors found!

**Comment by mjstealey** [comment]
@alvacouch - would you have a link to a build on Jenkins where you've observed this?

Often times you have to look at the file named: pylint.out using the "view" option.
Random example
- 1 flake8 error: http://ci.hydroshare.org:8080/job/github-commit-builder-hydroshare/1455/
- pylint.out: http://ci.hydroshare.org:8080/job/github-commit-builder-hydroshare/1455/artifact/pylint.out/*view*/

**Comment by alvacouch** [comment]
Discussed offline. The flake8 reports are filed under another name.
