### ISSUE TITLE
Remove dockerworker container and associated code

### ISSUE THREAD

**Issue by mjstealey** [hydroshare/hydroshare#1725]
On next update of hs_docker_base:1.10.0 the dockerworker container no longer runs successfully due to AMQP and Celery errors. Since this container is not used, it is going to be removed instead of debugged.
- As a side effect we should also be able to remove the code for [django_docker_processes](https://github.com/hydroshare/django_docker_processes/tree/53c7d181aac16200b663d78be80ccf0c7177fcc1)

**Comment by aphelionz** [comment]
Dooooo it

**Comment by mjstealey** [comment]
merged in #1729
