### ISSUE TITLE
Simplify relationships and their entry

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#1726]
In resource landing pages right now we have separate buttons AddSource and AddRelation.  The AddSource button creates a relationship Derived from.  The Add relation includes a number of other possible relationships, including Copied from.  I suggest the the following
1. Consolidated editing of relationships into one button AddRelation
2. Remove copied from as an option and retain only derived from.  The rationale is that there is no guarantee that after a resource is copied it is not changed (in fact it likely will be or else there would be no reason to copy) and derived from better records this.
3. Add capability to browse a resource picker in setting up relationships rather than having to type/cut paste in a URL.

**Comment by horsburgh** [comment]
@dtarb - I don't necessarily have a problem with this, but it does conflate two Dublin Core metadata elements.  Dublin Core has both:

Source: http://dublincore.org/documents/dcmi-terms/#terms-source
Relation: http://dublincore.org/documents/dcmi-terms/#terms-relation

Best I can tell, the "isDerivedFrom" relationship should go with the Source term and any other relationship types should go with the Relation term. This is why we originally designed the interface this way, but I agree that it seems kind of arbitrary. If we collapse all relationships on the "Relation" element, that is probably sufficient for our needs but may cause minor issues down the road if there are other systems looking inside HydroShare's metadata to find "isDerivedFrom" type metadata in a "Source" element that doesn't exist. It's a provenance issue, but may not be significant enough to not do what you suggest.

**Comment by dtarb** [comment]
Discussed with @horsburgh. Decided to keep source and relation separate as they are separate DC terms.  @horsburgh to define improvements to clarify this for users and facilitate easier entry.

**Comment by dtarb** [comment]
@horsburgh while the broader clean up can be deferred, we do need immediate specific guidance to @hyi as to the type of relationship to be written when a resource is copied, #1029.  Source may be good, but if we recognize a use case may be to copy start data then do processing that adds quite a lot, the term source may not persist throughout the use case.  Please bear this in mind as you think this through.
