### ISSUE TITLE
Time Series Resource:  incorrect element labels in resourcemetadata.xml

### ISSUE THREAD

**Issue by horsburgh** [hydroshare/hydroshare#173]
Testing on dev.hydroshare.org.  See resource: http://dev.hydroshare.org/resource/f5e4c6083e8d4e91be216295f7b6282e/

There are a couple of issues in the resourcemetadata.xml created for a time series resource:

1.  The "UnitsAbbreviation" element is incorrectly encoded as UnitsType.  The content of the element is correct, it is just the name of the element that is incorrect.
2.  The "AggregationStatistics" element should singular - AggregationStatistic

**Comment by dtarb** [comment]
@pkdash is this ready for 1.5.0 release.  If it would be a distraction from your current work please indicate whether (a) time series can be included as is without this fix in 1.5 or (b) whether we should withhold time series from 1.5 until this is fixes.  Change the milestone based on your choice.

**Comment by pkdash** [comment]
@dtarb and @horsburgh I missed it as it was not in the 1.5 release check list. It is a small fix and I think I should fix it today so that time series resource can be included in release 1.5.

**Comment by horsburgh** [comment]
I would hate to put it off if it is something small.  Thanks Pabitra.

**Comment by pkdash** [comment]
@horsburgh I have now fixed this. I think you should be able to test it on dev.hydroshare.org sometime tomorrow after tonight's build. Then you can close this if see it being fixed.
