### ISSUE TITLE
my-resources - follow up concerning UI qunit tests

### ISSUE THREAD

**Issue by mjstealey** [hydroshare/hydroshare#1733]
Addition of qunit test renders my-resources page not usable in UI... 

When the [following code](https://github.com/hydroshare/hydroshare/blob/develop/hs_core/templates/pages/my-resources.html#L546-L550) is left uncommented, the user can no longer see their resources in the my-resources page:

```python
        // TODO: fix the following references
{#        $(document).ready(function () {#}
{#            start_resource_table();#}
{#            $.fn.dataTable.ext.search.push(hs_resource_table_custom_search);#}
{#        });#}
```

**Comment by pkdash** [comment]
@mjstealey and @alexlemann What's the status on this issue?

**Comment by dtarb** [comment]
Closing as my resources appears to be working @mjstealey or @alexlemann re-open if still an issue.
