### ISSUE TITLE
Tests fail due to hard-coding of 2016 date

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#1741]
The test: hs_core.tests.api.native.test_get_citation fails due to a hard-coded 2016 date. 2016 != 2017. Similar issues with other tests in hs_core.tests.api.native.

**Comment by alvacouch** [comment]
I have more or less fixed this in my current PR.

**Comment by pkdash** [comment]
@mohamedmorsy or @jsadler2 Can one of you fix this issue? I think the tests that are failing are originally written by you.

**Comment by mohamedmorsy** [comment]
@pkdash @alvacouch said that he has fixed this in his PR. @pkdash do you still want us to work on that?

**Comment by pkdash** [comment]
@alvacouch Have you already fixed this issue? I don't see a PR for this yet.

**Comment by pkdash** [comment]
@mohamedmorsy No need for you to work on this.

**Comment by alvacouch** [comment]
PR forthcoming.

**Comment by alvacouch** [comment]
PR submitted, approved, and merged.
