### ISSUE TITLE
Keyword editing removes existing keywords

### ISSUE THREAD

**Issue by AmberSJones** [hydroshare/hydroshare#1743]
I am editing a resource to add keywords. I get an error that "Metadata failed to update". Then, some of the keywords that had previously been there are removed. The resource previously had 18 keywords. After attempting to add a keyword, it is reduced to 10 keywords. Is there a limit on the number of keywords allowed? 

![image](https://cloud.githubusercontent.com/assets/5023186/21611270/53950d12-d189-11e6-9d2c-96d503bc91ea.png)
![image](https://cloud.githubusercontent.com/assets/5023186/21611281/629adb5c-d189-11e6-9b58-610685638375.png)

**Comment by pkdash** [comment]
@AmberSJones There is no limits to the number of keywords. It seems the update failed due to duplicate keywords (Oxygen). The update code needs to be changed so that some of the original keywords are not lost in the event of a update failure.

**Comment by AmberSJones** [comment]
Great, thanks for investigating and addressing @pkdash

**Comment by pkdash** [comment]
@AmberSJones I am working now to fix this issue. I am not able to reproduce this error. I see in the screenshot there are duplicate keywords. However, I am not able to enter duplicate keywords.

**Comment by AmberSJones** [comment]
These resources were originally generated via the API by @fryarludwig, so it is likely that the API permits duplicate keywords.

@fryarludwig, can you address our utility to prevent duplicate keywords?

**Comment by pkdash** [comment]
At the database level there is constraint not to allow duplicate keywords. I am not sure how this could happen.

**Comment by fryarludwig** [comment]
The utility actually performs checks to ensure that only unique keywords are added. Is it possible that two keywords may have hidden characters that make them appear to be duplicated, while showing as unique? Simple keyword duplication checking is already handled on my end, but I'd be happy to investigate more if you would like.

**Comment by pkdash** [comment]
@AmberSJones can you test to see if this issue got resolved and then close it?

**Comment by AmberSJones** [comment]
We determined that the duplicate keywords were a result of attempting to load terms that contained commas, which were then parsed as separate keywords. @fryarludwig changed our script so that we don't try to pass any commas. 

However, I just tried to manually edit the keywords on a resource and ran into a few issues. When I tried to add any keywords, I got an error that Metadata failed to update although the keywords are added to the resource. Furthermore, it permitted the addition of duplicate keywords (precipitation, temperature). The duplicate keywords were only added when the casing was different.

![image](https://cloud.githubusercontent.com/assets/5023186/22033490/ed544ce8-dca5-11e6-8c55-491f03fcbe0f.png)

![image](https://cloud.githubusercontent.com/assets/5023186/22033477/de32c9ce-dca5-11e6-8e74-5f1b3b2fac22.png)

**Comment by pkdash** [comment]
@horsburgh and @dtarb Currently the keywords are case sensitive when checking for duplicates. Should we ignore case when checking for duplicate keywords?

**Comment by dtarb** [comment]
Yes I would ignore case when checking for duplicate keywords.

**Comment by horsburgh** [comment]
I agree. Ignore casing.

**Comment by pkdash** [comment]
@AmberSJones @dtarb I have done some work to fix many of the issues related to keywords editing. Now it should not be possible add duplicate keywords. It should be possible to delete all keywords. 

This work has been deployed at testservies.hydroshare.org for testing. Let me know if it meets the requirements.

**Comment by dtarb** [comment]
I tested this on testservices.hydroshare.org.  I generally like this but think that a message is needed if a keyword is not added.  For example I added a keyword dem.  Then I tried to add Dem.  It was not added (correct behavior), but rather than just nothing happening, there should be a message "Duplicate.  Keyword not added."

We might consider other helpful messages too.  If a resource is public and I delete the last keyword it switches to private.  I think a message. "Resource set to private as keywords were deleted.  Add keywords and set to public again if you want this resource to be public."

If you prefer not to extend the work associated with this issue to include messaging, I am fine deferring it.  Please then write these as separate issues before this one is closed.

**Comment by pkdash** [comment]
@dtarb I have made some changes based on your comments above. The new interface looks like this:

![image](https://cloud.githubusercontent.com/assets/2523434/22179721/63827d2e-e019-11e6-856a-0782df2a4ec0.png)

The first message is displayed always. The 2nd message related to duplicate keywords will be displayed only when the user tries to add a duplicate keyword. That message will disappear next time the user adds new keyword. If this does not meet the requirements, I will create new issues for these to be addressed in another PR.

**Comment by dtarb** [comment]
This is good.

**Comment by pkdash** [comment]
@AmberSJones Can you test this and see if you can close this issue?

**Comment by AmberSJones** [comment]
Thanks for the reminder. I tested at testservices.hydroshare.org and had no issues. The error messages were helpful. I'll close it.
