### ISSUE TITLE
Default behavior of files when duplicates are uploaded. 

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#1744]
@pkdash @hyi @dtarb 
Django -- by default -- ensures that each uploaded file has a unique filename. This is getting in the way of revising the filesystem. The worst behavior is that Django is preventing me from reusing a file name that I have already uploaded and then deleted. I can't figure out where it gets that information from. 

I cannot currently envision any use for this in our system, and propose that we make a minor change so that **uploading the same file twice is always a replace operation.** This is a trivial change to django_irods. 

Do you concur?

**Comment by dtarb** [comment]
By same file, do you mean the exact same file, or any file with the same name.

I am happy to be practical and concur but do have a preference, but not an insistence, for common protections.  We have some protections in the folder front end already that warn/prevent a user from renames/moves or unzipping operations that clobber an existing file.  I would prefer the following common protections that operating systems (e.g. Windows) give me.
- on the UI if a user does something that overwrites/replaces an existing file they get a warning to replace or cancel.
- in the API do not overwrite an existing file unless the user gives a "force" parameter.

**Comment by alvacouch** [comment]
@dtarb I mean the exact same file, in the sense that the filename and folder are precisely the same. Two files with the same name in different folders are different files.

**Comment by hyi** [comment]
@alvacouch @dtarb We had a similar discussion related to overwriting the file with the same name when doing unzipping. Initially I implemented what @alvacouch proposed here, i.e., replace the file with the same file name when unzipping, then we decided this is not a desired behavior and we should not replace without user's consent, but instead should present users with a warning such as the following:
```
iRODS error results in unzip being cancelled. This may be due to protection from overwriting existing files. Unzip in a different location (e.g., folder) or move or rename the file being overwritten. iRODS error follows: ...
```
So @alvacouch a similar behavior will most likely be needed here for file uploading as well for consistency.

**Comment by alvacouch** [comment]
@dtarb Currently, django_irods.storage does something silly, in the sense that it automagically enforces a new filename unpredictably if one uploads two files with the same name. I don't think we ever want that. 

However, the behaviors you specify would not be part of django_irods. These are part of the API and UI. 

My solution would turn off the annoying behaviors of django_irods and then replace them with API and UI code. Django_irods is not designed to provide this functionality, but it can be annoying in providing functionality we really don't want, e.g., when it mangles names of uploaded files for its own reasons. This mangling is what I want to turn off.

**Comment by pkdash** [comment]
@alvacouch 

> The worst behavior is that Django is preventing me from reusing a file name that I have already uploaded and then deleted.

The above behavior seems strange to me.

**Comment by alvacouch** [comment]
@pkdash I have a test that reproduces that behavior. Further, that behavior is documented as correct. There must be some cache of filenames that have been used that is being used to detect conflicts.

**Comment by alvacouch** [comment]
@pkdash @hyi @dtarb I have successfully turned off this behavior with a short function in django_irods.

**Comment by hyi** [comment]
@alvacouch Could you paste a django documentation link here that documents that behavior as expected?

**Comment by alvacouch** [comment]
@pkdash It might be that using ResourceFile.delete (instead of iRODS delete) would fix the above behavior. I will see what that does. Currently, we are mixing native iRODS commands with FileField commands. This could be leading to the confusion I am seeing. 

Further, with corrections to the way FileFields are constructed, I now have cascade delete, in the sense that deleting a ResourceFile deletes the files contained in its FileFields.

**Comment by pkdash** [comment]
@alvacouch With this behavior being turned off what happens when same file is uploaded twice?

**Comment by alvacouch** [comment]
@pkdash It will happily overwrite it unless we modify istorage to prevent that, which is -- again -- a trivial mod.

**Comment by pkdash** [comment]
@alvacouch 

> I now have cascade delete, in the sense that deleting a ResourceFile deletes the files contained in its FileFields

Is one ResouceFile object has more than one FileField?

**Comment by alvacouch** [comment]
@hyi see https://docs.djangoproject.com/en/1.10/howto/custom-file-storage/#django.core.files.storage.get_available_name

The functionality is in get_available_name, which is method of the IrodsStorage class. The default is to deal with duplicates by adding a 7-character hash code to the file name before the extension. This is working exactly the way it should, but not a way that we would want!

**Comment by alvacouch** [comment]
@pkdash Currently one ResourceFile has two FileField objects, one for unfederated storage and one for federated storage. Only one is used at a time.

**Comment by pkdash** [comment]
@alvacouch That means deleting a ResourceFile object always deletes only one physical file - right?

**Comment by alvacouch** [comment]
@pkdash Yes. Deleting one ResourceFile always deletes one physical file. 

In essence, we are in a situation of "plenty" in the sense that everything ResourceFiles should be doing is being done. This -- unfortunately -- has a few side effects. For example, now the ResourceFiles have full pathnames in the FileField, so that determining uniqueness is easy and handled at the istorage level. Previously we had relative pathnames, which istorage couldn't make much sense of and thus could not check for uniqueness. E.g., when you say a filename is just `foo.txt`, rather than `{resource_id}/data/contents/foo.txt`, then the istorage module can't make any sense of that path.

**Comment by pkdash** [comment]
@alvacouch Sounds good.

**Comment by alvacouch** [comment]
@pkdash this is what I was talking about when I looked at your code for collections. Fortunately, I have written some things that help, including `get_resource_path(resource, file, folder)` that always returns a fully qualified pathname that istorage can grok....

**Comment by alvacouch** [comment]
@hyi @pkdash @dtarb Thinking about @dtarb's requirements carefully, I think the proper thing to do is to always disallow naïve replacement of files with duplicate names, raising an exception in IrodsStorage whenever a user tries to do that. The user can then execute an API call to delete the pre-existing files and all will work; this is essentially the "force" option that @dtarb wants. This has the added advantage that the logic is simple and calling pre_delete and post_delete signals is straightforward....

I'm looking for the minimal mod of IrodsStorage that accomplishes this behavior.....

**Comment by hyi** [comment]
@alvacouch Thanks for the link. Now I understand where those random 7 character alphanumeric string comes from for a duplicate file name. I'd be interested in knowing how you turned off this Django default behavior by writing a function in django_irods, perhaps when you open a PR for code review.

**Comment by hyi** [comment]
@alvacouch Agreed that we should always disallow naive replacement of files with duplicate names with an iRODS exception raised, which is what we have decided and what has been done for unzipping. The only thing needed in irodsStorage to allow this is to remove the ```-f``` parameter in ```_save()``` method. Then iRODS will raise an exception when trying to overwrite an existing file, and user interface can respond accordingly then.

**Comment by alvacouch** [comment]
@hyi might be better to raise an exception in the get_acceptable_name routine, whose purpose is to disallow duplicate file names.... this seems to be how Django wants to handle it..... this is called before by save before _save.

**Comment by alvacouch** [comment]
@hyi: (I rewrote IrodsStorage.get_acceptable_name already to turn off the renaming.)

**Comment by hyi** [comment]
@alvacouch Got it. This makes sense to me and agreed it is better to disallow duplicate names even before it hits iRODS command.

**Comment by alvacouch** [comment]
The feature has been merged and tested.
