### ISSUE TITLE
Help Page Update -- Resource Types: Geographic Feature

### ISSUE THREAD

**Issue by ChristinaB** [hydroshare/hydroshare#1753]
This is currently one sentence.  Let's expand it. 
[Here is a link to the Google Doc](https://docs.google.com/document/d/1NSEhfWKOEr9EEXUyA6OQtJUrwUi6Pl72l0wWFXKIPvg/edit)

**Comment by horsburgh** [comment]
@ChristinaB - The BYU guys developed the geographic feature resource type. Perhaps they should take care of the help for this one.
