### ISSUE TITLE
Discovery improvements

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#1755]
@xuezhaokun @dtarb @martinseul @danames I conferred with Rick Hooper on how to best improve discovery. He made the following tangible observations. 

1. The practice of clicking on a point to list overlapping regions is confusing to the naïve user. 
2. Ordering by number of instances doesn't support use cases in which one is looking for a name in alphabetical order. 
3. Geographical classification of coverages into "global", "continental", "national", "provincial" categories would be useful. 

Rick suggests the following enhancements: 
1. Eliminate clicking on a point to show overlapping regions. Do not show any regions by default. Do not show region markers, either. These are confusing. 
    a. Show point coverages on the map. 
    b. Show coverages that overlap with the view region in the window below.  
    c. Allow highlighting one of them by clicking in the listing box. This should zoom to the region in 
       question. 
3. Organize the listing (on both listing and map pages) into regions via the following rubrics: 
    a. A **global region** involves _two or more continents_. 
    b. A **continental region** involves _two or more countries_. 
    c. A **national region** involves only one country. 
    d. Implement finer subdivisions (state, province, etc) when plausible. 
4. In effect, this defines a "region facet" with values "global", "continental", "national", and "provincial". 
5. Allow facets to be sorted alphabetically rather than just by number of resources. 
    a. Sort peoples' names by _last name_, not first name. 

This is made somewhat difficult by the fact that some of these facets are not defined in metadata, but must be inferred from imperfect and incomplete information, including the fact that real coverages are polygons but our metadata only records bounding boxes. 

For example, it is going to be very easy for a national-scale coverage to be mistaken for continental scale, simply because it overlaps marginally with other countries because countries aren't square. Likewise, it is difficult for us -- without additional metadata -- to conclude that US coverages don't include Canada or Mexico, because of the limits of what we are recording.  Thus, a rather imperfect heuristic is probably needed.

**Comment by dtarb** [comment]
@alvacouch I am all for Discovery improvements.  I recognize that this is a tough problem.  When you review our previous issue on this #1361 you see that comments were all over the map (pun intended).  I worry that the approach of taking input from all is inefficient and generates inconsistent suggestions with the coder getting jerked around a lot.  I think we need someone (or a small group) to carefully think through the discovery goals and options, perhaps reviewing other sites and then propose a holistic design.  I'd prefer an approach different from the way we bounced around previously.  So, saying this about process, I am going to hold back on comments on the specifics.  I have some comments on specifics in #1361 that I think still have merit, but have not been tried and whenever I think about specifics find myself circling back to them.

**Comment by alvacouch** [comment]
@dtarb One of the main challenges of these specific suggestions is that several of the suggestions Rick made are not "practical", in the sense that they are not supported by the underlying data model. There are two main themes: 
1. We have insufficient metadata to reliably sort creators by last name(!)
2. We have  insufficient metadata to reliably categorize coverage resources by geographic region name (global, continental, national, and provincial).

I am going to comment on each of these in detail and in separate issues. Meanwhile, @dtarb, could you briefly enumerate the suggestions that you wish us to consider again from #1361?

**Comment by alvacouch** [comment]
@dtarb I think Rick has the proper approach for sorting this out: 
1. Concentrate on "use cases" and "enabling common workflows". 
2. Evaluate each approach as to how well it matches the user's needs.

**Comment by dtarb** [comment]
Here are my suggestions related to the map in response to @alvacouch request.  Some come from #1361, but many are new in reaction to the problems mentioned above. 

1. The map should essentially function as another filter facet with the only difference between the  list tab and the map tab being the map at the top.  The resources listed below the map and displayed on the map when you are in map tab should respond to facet selections, temporal coverage selections and keyword searches just as they do in the list tab.  
1. The display domain and map search box domain should be decoupled. 
1. The display domain should zoom when a user clicks the + or -, or uses a shift drag, or turns on drag zoom mode.
1. The display should zoom when a user enters a search location and clicks Go as it currently does.
1. There should be a zoom back button that zooms back to previous display and zoom full button that zooms to the area covering the full extent of the boxes of the resources that satisfy the other active search facets.
1. The display domain should pan when a user drags the mouse in default mode.
1. A search rectangle should be activated when a user selects a search tool and then drags to set a rectangle, or when a user clicks a button "Filter by display", in which case it is set to just slightly less than the display so it can be seen.
1. A search rectangle should be deactivated when a user clicks "Clear map search" button
1. When a search rectangle is active only resources that overlap or are contained within the search rectangle should be shown on the map.
1. The search rectangle should be shown as a dashed rectangle.
1. Switching back to the list tab deactivates the search rectangle.
1. The resource list below the map should be a long list just as in the list tab.  I do not think it needs a separate scroll bar.
1. The display should show points for point resources that fall within the domain and satisfy the other active search facets (red dots).
1. The display should show points for box centers of resources that have box centers within the domain and satisfy the other active search facets
1. Where there are too many points to show close together a Cluster with the number of points (adding box centers and points) should be shown. 
1. Clicking on a cluster triggers a zoom in to a box defined by the centers of all the points that define the cluster.  Where all points are at exactly the same location the zoom in should be just far enough to exclude all other points that would be on the display from the display and the points that define the cluster should be exploded using a star so each is clickable.
1. Clicking on a point or box center shows the title as a link to the resource landing page and if it is a box, shows the box on the display.  (Display size is not adjusted but there should be an option to zoom display to show resource extent).
1. Boxes should not by default be shown.  
1. Boxes should only be shown for resources selected.
1. Resources may be selected by clicking on their center (which brings up the box and title label pop up) or by clicking on them in the list below (this is how boxes can be shown for resources whose center are not in the display but whose extent matches the selection (and satisfies other selection facets)
1. Multiple resources may be selected at once (showing multiple boxes on the display)
1. Selected resources may be clicked again to toggle selection off, and there should be a "Clear selections" button to clear all selected resources and the display of all boxes.

I probably have left things out, but also worry this is too much explicit detail.  While these are my suggestions, I do want to be receptive to other solutions.  I also want to be sensitive to the challenge of implementation and efficient and open to you advancing a solution that while different, works.

**Comment by Castronova** [comment]
@cuahsimarko Is this still relevant given the recent changes to discovery?

**Comment by cuahsimarko** [comment]
@dtarb I think sufficient time has passed and with the most recent changes to Discover a clean process for Maps enhancements might be appropriate. Thoughts?

**Comment by dtarb** [comment]
@cuahsimarko @Castronova I do not think we are done with the mapping part of Discover, but do not have the capacity to address more right now.  I am going to create a new label "Discover map" and use this for all issues that give ideas on this so that when we do have capacity to address it, they can be referred to in a fresh approach.  I'll also leave the label "design phase needed" as these are in this category too.

**Comment by cuahsimarko** [comment]
@dtarb I have a label, geo and maps that has been used to identify those areas across all the GH Issues... can we reuse that?

**Comment by martinseul** [comment]
@dtarb @cuahsimarko I also don't think we're done with the mapping part of discover and using the new label for Discover map will work to separate out discover map issues the "geo and maps" has non discover issues as well

**Comment by cuahsimarko** [comment]
@dtarb @martinseul I just looked again and it appears as though all the Issues labeled `geo and maps` have been closed, except for one. I'm more inclined to remove that label and go with the new Discover map label. The Discover label should also apply.

**Comment by cuahsimarko** [comment]
@dtarb @martinseul @Castronova I don't think we are done with the Mapping part of Discover. It would be nice to capture Discover map enhancements in a new workflow, with design discussion and collaboration, similar to how the Citations work was outlined. Early involvement of the person, who will implement the work is also a good idea. The conversation should start with requirements, use cases and functionality.

**Comment by cuahsimarko** [comment]
@dtarb I had created the `geo and maps` label to capture all relevant topics. Adding a `Discover` label complements that label, in this case. I had spent a lot of time finding all `geo and maps` Issues and labeling them. Would you be ok with applying the 'Discover" label to this Issue and deleting the new `Discover map` label? The final state would show the Discover label and geo and maps to identify this work.

**Comment by dtarb** [comment]
I suggest lets not machinate too much over which labels are right.  The "design phase needed" keeps this in a group to consider holistically when we design new functionality.  The "Discover map" says it has ideas for the map part of discover.  Discover is OK because it also refers to discover.  As @martinseul there are a lot of non discover issues related to geospatial information where geo and maps is used.  You are welcome to add that here if you think it helps, but I think it is not really needed.

**Comment by cuahsimarko** [comment]
I think we should have some conventions, though. I like having geo and maps, as I had intended to include Discover Maps but also more than just Discover Maps. I'm ok with creating the third "Discover Maps" label.

**Comment by eclark-cuahsi** [comment]
Closing per backlog review discussion on 6/9/22. discovery work is happening has part of the CZ Net work. this can be revisited if needed.
