### ISSUE TITLE
Add setting to require agreement to license before manual downloading.

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#1756]
Following discussion with @darctur and at his request, lets add capability to have a pop up that opens when a user tries to download from a resource that requires them to click that they have read and agree to the rights statement.  This should be optional.  A resource editor should be able to set “Require agreement to rights statement before downloading” on a resource landing page.  I suggest this be below the license statement in editing mode as below.

![image](https://cloud.githubusercontent.com/assets/3456833/21991516/2bd26a9e-dbd0-11e6-9593-871ddb5d0d38.png)

When this setting is checked any manual download of the resource or file in the resource should pop open a window that says:
> This resource is shared according to the license: 
> \<insert license statement> 
> \<insert license URL> 
> To download you must agree to the terms of this license. 

Then provide an "Agree" and "Cancel" button and trigger the download only when agree is clicked.

This should only be for manual downloads as required clicks are troublesome for automated downloads.

**Comment by horsburgh** [comment]
+1 for this. We also need this capability to support the iUTAH project. We already have the language of our access/use agreement. We just need a place to put it and a way to require people to agree to it before they access iUTAH datasets.

**Comment by pkdash** [comment]
@dtarb I have made only the owner of the resource to set the optional license agreement requirement for file download. I am wondering which user should be prompted to agree to this agreement before file download. I am assuming resource owners should not be asked to agree to the resource license. What about users who have edit access? Should they be prompted to agree to the license?

**Comment by dtarb** [comment]
Please ask @horsburgh while I am away.  I think all users including the owner should be prompted so that the owner can check that the behavior is what they want.

**Comment by pkdash** [comment]
@horsburgh Can you comment on my question above as it relates to which user should prompted to agree to license agreement for downloading files/bag?

**Comment by horsburgh** [comment]
@pkdash - I agree with @dtarb that all users should see it. The only way an owner will know that it is functioning correctly is to see it. And, that will likely make implementation easier.

**Comment by pkdash** [comment]
@horsburgh Sounds good. That's how I have already implemented.

**Comment by pkdash** [comment]
@dtarb and @horsburgh I have implemented this feature and have deployed on riverdev for testing.

**Comment by horsburgh** [comment]
@pkdash - I just tested on riverdev. I think this is mostly working, but there are some formatting issues on the form that pops up. When I used a custom Rights statement, here's what I get:

![image](https://user-images.githubusercontent.com/3485902/27500079-07103486-5824-11e7-9d80-f8dcf0ee54c5.png)

I entered the text "Please give me credit when you use my data." into the "Statement" text box on the edit page for the resource.

There is an extra word "License" in the text that is not in the text I entered, and there is an extra period at the end of the first statement. Also, I think you should add a blank line between the first statement (my text or the text of the creative commons license) and the second statement (the text that starts "In downloading...).

The extra word "License" shows up where the custom license statement is displayed on the landing page as well:

![image](https://user-images.githubusercontent.com/3485902/27500262-f7a655f6-5824-11e7-8cdb-e72fdff91125.png)

Also, when a longer, more complicated text string with some carriage returns and minimal formatting are entered into the text box, all formatting is lost when displayed on the landing page:

![image](https://user-images.githubusercontent.com/3485902/27500480-e0dff5ce-5825-11e7-8f9d-ea45285ac8bb.png)

Realizing this, my immediate solution would be to shorten our license statement and point to an online document with the longer text and formatting via the URL attribute, but it seems like we should at least be able to honor carriage returns in the text the user enters.  When I go back into edit mode after saving, the text is displayed with the carriage returns.

I was working on this resource, which is public:

https://riverdev.hydroshare.org/resource/050fe4b2fea64e90b3cb37289b3bc4e8/

**Comment by pkdash** [comment]
@horsburgh I will look into the above issues. Thanks for testing.

**Comment by pkdash** [comment]
@horsburgh I have tried to address the issues you described above. The updated code has been deployed on riverdev.hydroshare.org

**Comment by horsburgh** [comment]
@pkdash - these issues appear to be fixed. One last thing that I think would help - right now the custom license text shows up in a scrollable text box. This is fine that it is scrolling, but there is no indication that the box is scrollable.  

![image](https://user-images.githubusercontent.com/3485902/27622818-b0deecc6-5b96-11e7-95be-93c5866cd61e.png)

Can you put a border around the text box to indicate that the user needs to scroll to see the full contents? This is both on the main landing page and on the agreement window that pops up when the user tries to download.

Otherwise, +1 from me.

**Comment by pkdash** [comment]
@horsburgh It seems like a browser issue. Firefox and Edge show the vertical scrollbar:

![image](https://user-images.githubusercontent.com/2523434/27651731-8a17f62c-5bf6-11e7-9326-4b14ed6741e5.png)

**Comment by horsburgh** [comment]
@pkdash - I tested in both Chrome and Firefox on my Mac and the result is the same. I can scroll the whole page and even hover over the text - the scroll bar doesn't pop up or become visible until I both hover over the text AND start scrolling. Since there are no boundaries around the text, I may never know that it is constrained to a set area, I might never hover over the text, and I might not know that I can scroll to read more.

**Comment by pkdash** [comment]
@horsburgh Not sure why I don't see the same behavior when I use FireFox and Chrome.

**Comment by dtarb** [comment]
I tested this today and found that while there is a check box 
![image](https://user-images.githubusercontent.com/3456833/30003582-015e9488-907d-11e7-99f6-d1a725ff43d3.png)

on resource landing pages, checking it does not stick.  The page appears to refresh and then the check mark goes away.  @pkdash can you please assess what is going on and advise if this is something you, @Maurier or @aphelionz are best to address.  

I am setting this as high priority because this is deployed functionality visible to users on www that is not working.  (while it was still a feature request under development priority would have been lower)

**Comment by pkdash** [comment]
@dtarb I will look into it today and may have to do a hotfix.

**Comment by pkdash** [comment]
@dtarb A hotfix PR has been created. Waiting for code review and approval.

**Comment by aphelionz** [comment]
@pkdash @dtarb Can this be closed?

**Comment by pkdash** [comment]
@aphelionz This should be closed. @dtarb can confirm.

**Comment by dtarb** [comment]
Yes this is working.
