### ISSUE TITLE
Help Page Update- Collection Resource Type

### ISSUE THREAD

**Issue by Lizabrazil** [hydroshare/hydroshare#1758]
Expand on Collection Resource Type. Explain the steps involved of creating a collection of resources and the details involved with DOIs. Does each resource need a DOI before the collection of the resources obtains a DOI?
https://pages.hydroshare.org/hydroshare-resource-types/collection/

**Comment by Castronova** [comment]
@jtpollak @AmberSJones Are there any plan to address this in HydroShare documentation?

**Comment by ClaraCogswell** [comment]
This is resolved.
