### ISSUE TITLE
connecting to iRODS during data migrations

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#1761]
@mjstealey @hyi @rayi113 (cc: @dtarb) As I am now writing several data migrations to generally "harden" the code, it would be extremely useful to be able to contact iRODS during a data migration. 

* At present, I am writing a data migration from "old" to "new" file handling. **Calling IrodsStorage.exists() would be particularly handy** as a sanity check that I did things correctly. I am translating from a highly polymorphic set of possible file name inputs to a relatively monomorphic representation. So it would be very handy to be able to stop the migration if a file doesn't exist where I think it should. That has to be my error.  

* In the immediate future, I'll need to move some metadata around for files. It would be particularly handy to be able to **mine the metadata directly from the files during a data migration.** This would -- in turn -- fix any data mining that was done earlier and was incomplete. 

Could you please work out the details of how I would bring up IrodsStorage during a data migration?

**Comment by hyi** [comment]
@alvacouch If I understand your comment correctly, I think this can be done easily and has already been done as shown here in a custom raster data migration: https://github.com/hydroshare/hydroshare/blob/develop/hs_geo_raster_resource/migrations/custom_migration_for_tif_to_vrt_20160223.py

**Comment by hyi** [comment]
@alvacouch I assume this is not an issue for you any more. If so, you can close this issue.

**Comment by alvacouch** [comment]
iRODS is working during migrations now.
