### ISSUE TITLE
move file metadata to ResourceFile object

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#1762]
@pkdash @dtarb @martinseul @hyi @aphelionz 

In analyzing the quality of the code, I found significant duplication of file handling. As well, the main problems mentioned in issue #1644 concern handling of file metadata. There is a relatively straightforward solution to these problems that we now have within our grasp. 

In a nutshell, I propose that we **move file metadata to an attribute of the `ResourceFile` object rather than the resource "metadata" object.** 

This has become possible and within our reach lately due to the work of several people: 

* @pkdash has an approach to separating file metadata from resource metadata for the composite resource. 

* @alvacouch is writing data migrations and can handle the ensuing migration from resource metadata to file metadata. 

* @aphelionz is revising the UI and REST API and could incorporate changes into those during the revision. 

This proposal is -- in essence -- an adaptation of the Composite resource work to solve a code duplication and application logic problem in general.

 In reviewing the `CompositeResource` design, I disagree with one detail, which is where the logical files are handled. Currently, `LogicalFiles` contain `ResourceFiles`. This leads to an unnecessary branch complexity that can be avoided. I think the following scheme makes much more sense:  
* The concept of a `ResourceFile` is that of a logical file.
* Only a `ResourceFile` can contain metadata. 
* `ResourceFile`s contain one or more `PhysicalFile`s. There is also a reasonable interpretation of containing zero `PhysicalFile`s and one or more URIs for linked data.  
* `PhysicalFile`s do not contain metadata. They just document where a file is on disk. 
* Currently invisible `PhysicalFile`s (e.g., *.shx in the Geographic Feature Resource) can be made visible via  a data migration. 

I believe that this reorganization would have a profound effect on our agile ability to create and manipulate resource types. All we'd have to do in order to create a new resource type would be to specify the types of files that should be contained in it. The code for manipulating those files would already be written. 

The proposal is as follows: 
1. Create a layer called `PhysicalFile` under `ResourceFile`. Migrate all physical file information there. 
2. Create a type hierarchy for file data, starting with `AbstractFileMetaData` (that contains data for all possible file types) and subclasses `NetCDFFileMetaData`, `RasterFileMetaData`, etc.
3. Move handling of file metadata to these classes.
4. Move `pre_add_file` and `post_add_file` to apply to this metadata. 
5. Arrange cascade delete for file metadata, in the sense that deletion of a file deletes its metadata. 
6. Migrate existing file metadata to these classes.  

I am confident that I can accomplish steps 1 and 6, which is most of the heavy lifting. The rest is moving code around.

 The impact of this will be rather profound: 
* The REST API can deal with the `FileMetaData` objects, which are simpler objects than resource metadata objects. 
* There will be a single point of truth for handling each kind of file. Extra requirements (e.g., naming conventions) can be layered on top of this. 
* It will be straightforward to rewrite the serializers for the resource types to look up file metadata from the `FileMetaData` objects. These serializers need a review anyway. This will profoundly simplify them and allow code reuse when two resource types contain the same kinds of files.

**Comment by hyi** [comment]
@alvacouch Your proposal looks good to me. My only potential concern is that there might be migration issues as a result of making the proposed changes. If Django can handle migrations automatically without issues, I am all for it.

**Comment by pkdash** [comment]
@alvacouch Are you proposing that we implement metadata in all resource types how it is done in the new composite resource?

Why we need to create ```PhysicalFile``` which is currently same as the ```ResourceFile```?  What you proposing the new '''ResourceFile``` to be that is the ```LogicalFile``` in composite resource type. May be I am missing something.

**Comment by alvacouch** [comment]
@pkdash Yes, I want the metadata for files to be in its own object, just like for CompositeResource. I think it will save us a lot of trouble in the future. 

PhysicalFile is not the same as ResourceFile. ResourceFile is a container for possibly multiple files with overlapping metadata. PhysicalFile is one of those files. 

It is agreed that there is still resource metadata. For example, parameters of model instances. The ideal, however, is that this metadata utilizes key/value pairs, so that the main polymorphism concerns the kinds of files.

**Comment by alvacouch** [comment]
@hyi I plan to write manual data migrations to accomplish this. These are relatively straightforward, as I am just copying a set of model fields from one place to another. 

@pkdash It would actually help to leave the NetCDF metadata as explicit, because that makes it easier to copy than coding it into key/value pairs.

**Comment by alvacouch** [comment]
(The current data migrations I am writing are much more complex than these. If I can successfully complete the current migrations, the next set will be much easier to craft.)

**Comment by hyi** [comment]
@alvacouch For manual migration you are going to write, you would have to retrieve those metadata elements from the old resource metadata model and create them in the new ResourceFile model, right? Since in the new ResourceFile model, the old resource metadata elements would not exist, your manual migration would include two stages, the first would be the manual migration that would run in the old system to retrieve those metadata elements from the old resource metadata model and output them in some format for subsequent ingest into the new ResourceFile model, and the second would run in the new system to ingest output from the first stage into the new ResourceFile model. This was the manual migration we did when we migrated resources over from the old abstract resource model to the new proxy resource model, and would be better to avoid if at all possible. You may have different manual migration strategy in mind, but want to bring this up for discussion beforehand just in case. Of course, if Django can handle model and data migration automatically, it would be ideal.

**Comment by martinseul** [comment]
@alvacouch is this still relevant or has been resolved?

**Comment by alvacouch** [comment]
This issue was resolved via implementation of CompositeResource.
