### ISSUE TITLE
django model constraints inadequate

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#1765]
The current crisis is a symptom of a larger problem. **It should not be possible to enter nonsensical metadata into Django.** Addressing this is a matter of 
1. Adding reasonable constraints to the metadata models so that this is not possible. 
2. Where necessary, slightly redesigning the models so that constraints are easier to define.

**Comment by alvacouch** [comment]
The crisis in PR #1766 should be a learning experience. The search interface was overly presumpive that a `Creator`'s name would never be None. Since the database allowed it to be None (presumably, because a `Creator` can be an organization, which is another field in the `Creator`/`Party` model, **making the name None was a legitimate use.**

**Comment by alvacouch** [comment]
@cuahsimarko This issue is latent and several things have been done to address parts of this. This is related to the structure imposed by proxy classes, and the composite resource model will make it possible to fix this.

**Comment by cuahsimarko** [comment]
https://github.com/hydroshare/hydroshare/issues/1645

**Comment by cuahsimarko** [comment]
https://docs.google.com/document/d/1aYvFgOymrWJKv3cv8kkwXtOspdaGKSR40UgCdY4QNWU/edit?usp=sharing

**Comment by martinseul** [comment]
@alvacouch is this still relevant or has been resolved?

**Comment by alvacouch** [comment]
This issue has largely been resolved by the implementation of CompositeResource.
