### ISSUE TITLE
Browse button appearance truncated

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#1770]
In the Firefox browser on a Windows 10 PC the button to Browse to add a file to a resource is truncated at the bottom

![image](https://cloud.githubusercontent.com/assets/3456833/22176803/38d38522-dfcf-11e6-9a06-3df3eedb81d7.png)

**Comment by pkdash** [comment]
@dtarb This seems to have been fixed. You can test it at dev.hydroshare.org

**Comment by dtarb** [comment]
Verified on dev.
