### ISSUE TITLE
Discovery -- insufficient metadata to categorize spatial coverages by geographic region name

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#1775]
In #1755, one of the possible improvements for discovery is to treat geographic region name as a facet. This is problematic, because our current geographic coverages are rectangular, and there is no precise algorithm for determining what region name to map to each rectangle. 

For example, a coverage for Italy overlaps surrounding countries, and there is no way to know whether there is actually data for the other overlapping countries or not. In fact, in some cases, there is not; the rectangle is a bounding box but the data is for Italy only. We have no way of discovering whether this is true or not. 

Thus, anything we might do to categorize by geographic region is going to be imprecise, in the sense that we can know when a country is covered **but not when data for a country is all that is present.** The same comment applies to continents and provinces (a.k.a. states). 

@danames Do you have suggestions on how to infer the placename(s) for a geographic coverage?

**Comment by Castronova** [comment]
Stale.
