### ISSUE TITLE
"Visualize" button on resource landing page

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#1776]
@horsburgh @dtarb @danames Discussions last Wed demonstrated a need for a "Visualize" button on each resource landing page that easily gives access to the appropriate visualization app. This can point to an app or internally, but bypasses the app registry and is only sensitive to resource type. Thus, a user does not have to learn about the app registry in order to visualize something. 

This -- in turn -- means that we will designate one app for each type of resource as the first point of contact.

**Comment by dtarb** [comment]
See #1161, #1609, and #1610 that also relate to how apps are launched.  I think we need a holistic design for this.

**Comment by dtarb** [comment]
Closing.  This need is served by enhanced Open With functionality that has deployed.
