### ISSUE TITLE
Composite resource cannot cut and paste files (and thus cannot move files in folders to higher level)

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#1777]
In a composite resource, even for files that are generic the cut and paste functionality is not enabled.  This means that if a file is put in a folder, there is no way it can be moved back out to a higher level.

**Comment by pkdash** [comment]
@dtarb This should have been fixed and you can test on dev.

**Comment by dtarb** [comment]
Tested on dev
