### ISSUE TITLE
Help page update- Add examples to google docs notes for additional resources

### ISSUE THREAD

**Issue by Lizabrazil** [hydroshare/hydroshare#1784]
Dave, when you get a chance please add links to resource examples for the following resource types: 
SWAT  Model Instance
MODFLOW Model Instance
Web App
Script
Collection
https://docs.google.com/document/d/14rPVmHvrRXeT5YVthK_ffoFUZ5zGxsP492k7h5AlZL8/edit

**Comment by dtarb** [comment]
I added SWAT Model Instance.  https://www.hydroshare.org/resource/1f5dfda783574c45b36b8a884e07c6e0/.  @vmmerwade please confirm that this is a good one to use.

MODFLOW.  @goodalljl please provide a good MODFLOW example for the help page examples.

Web App. https://www.hydroshare.org/resource/9674a0af9f30410e9e02397c91284f54/.

**Comment by dtarb** [comment]
Script https://www.hydroshare.org/resource/6b642d6ede9f4b289ae1adb4be48a022/

**Comment by mohamedmorsy** [comment]
@dtarb @goodalljl Here is a complete example for MODFLOW model instance resource type.

https://www.hydroshare.org/resource/e7b29a3767654250bed7cd46c52e95d9/

**Comment by dtarb** [comment]
Complete set of examples is

- Raster Example: https://www.hydroshare.org/resource/b7822782896143ca8712395f6814c44b/  
- Second Raster Example: https://www.hydroshare.org/resource/877bf9ed9e66468cadddb229838a9ced/ 
- Multidimensional example https://www.hydroshare.org/resource/50fa9c5b3b5b4263bf4f1752a8b6723c/ 
- Time series example https://www.hydroshare.org/resource/1a25b11fa1354773b6edb9495e754f4e/ 
- Model instance example https://www.hydroshare.org/resource/12d195906f2c41918cb24e11a5c3ab60/ 
- Model program example https://www.hydroshare.org/resource/2cddae40e9594c21b947fdbbe4225439/ 
- SWAT  Model Instance https://www.hydroshare.org/resource/1f5dfda783574c45b36b8a884e07c6e0/ (See  also the paper that this refers to in related references)
- MODFLOW Model Instance: https://www.hydroshare.org/resource/e7b29a3767654250bed7cd46c52e95d9/
- Web App.  https://www.hydroshare.org/resource/9674a0af9f30410e9e02397c91284f54/ 
- Script https://www.hydroshare.org/resource/6b642d6ede9f4b289ae1adb4be48a022/ 
- Collection https://www.hydroshare.org/resource/2adee16a5b0d4df0b5e687046be8515e/ 
- Geographic Feature example: https://www.hydroshare.org/resource/93f49ab913fd4c639c98ab4a070d20e0/ 
- Composite Resource: https://www.hydroshare.org/resource/d7b7f9d5c7e0411683b76ef45c6bf0d8  

JAWRA paper on resource data model that should also be mentioned in the help as a place where you can learn more: Horsburgh, J. S., M. M. Morsy, A. M. Castronova, J. L. Goodall, T. Gan, H. Yi, M. J. Stealey and D. G. Tarboton, (2016), "HydroShare: Sharing Diverse Environmental Data Types and Models as Social Objects with Application to the Hydrology Domain," JAWRA Journal of the American Water Resources Association, 52(4): 873-889, http://dx.doi.org/10.1111/1752-1688.12363.

@Lizabrazil @ChristinaB passing this issue back to you.  You can close when you have this information captured for the help pages.

**Comment by Lizabrazil** [comment]
Great, thanks Dave. All examples are now included in their individual resource pages. I do not see a page for composite yet, but i am assume someone is working on it.
Christina, I'm not sure where to put this...can you add it in where it fits:
JAWRA paper on resource data model that should also be mentioned in the help as a place where you can learn more: Horsburgh, J. S., M. M. Morsy, A. M. Castronova, J. L. Goodall, T. Gan, H. Yi, M. J. Stealey and D. G. Tarboton, (2016), "HydroShare: Sharing Diverse Environmental Data Types and Models as Social Objects with Application to the Hydrology Domain," JAWRA Journal of the American Water Resources Association, 52(4): 873-889, http://dx.doi.org/10.1111/1752-1688.12363.

**Comment by dtarb** [comment]
@Lizabrazil the composite resource is the last bullet point two comments up.

**Comment by dtarb** [comment]
@gantian127 could you please write a composite resource description page.  It should go in https://docs.google.com/document/d/1K2QNfTYRQV7LBKtfh_XFLBpPS5z-gvBxxN2evgCy9wY/edit.  You can look at other resources documents in the same folder for examples on the content.  Please alert @ChristinaB  when you are done.

**Comment by gantian127** [comment]
@dtarb @ChristinaB Yes, I will write a document for composite resource type. Thanks!

**Comment by dtarb** [comment]
@ChristinaB @Lizabrazil the composite resource help file in Google Docs is done.  Thanks @gantian127
