### ISSUE TITLE
Strip pickle out from celery setting to avoid potential security issues

### ISSUE THREAD

**Issue by hyi** [hydroshare/hydroshare#1799]

**Comment by hyi** [comment]
@mjstealey @alexlemann @aphelionz @dtarb I have verified simply stripping out pickle serializer from celery will prevent celery tasks from working. After some investigation, I found out before celery version 4.0, the default celery task serializer is pickle, but since version 4.0, the default celery task serailzer becomes JSON. Since we are using celery version 3.1.23, the current celery version makes us dependent upon pickle for object seriallizer. I think the best route for us is to update to celery version 4.0, then we can strip out pickle without issues. Let me know what you think.

**Comment by alexlemann** [comment]
@hyi do you have any sense of why removing the pickle serializer breaks things? Do you think that simply upgrading Celery will fix that? If not you might be left trying to debug that lingering problem in a less familiar environment.

It sounds like 4.x is the way of the future and makes sense to get there sooner rather than later in order to keep upgrades less bumpy later on. That said, moving to 4.x may be complicated. Are there any other packages that rely on it?

**Comment by hyi** [comment]
@alexlemann See this http://docs.celeryproject.org/en/latest/faq.html specially on the section "Is Celery dependent on pickle" in which is says the default serialization support used to be pickle, but since 4.0 the default is now JSON. Also see this http://docs.celeryproject.org/en/latest/userguide/security.html#security-serializers. When I remove "pickle" from CELERY_ACCEPT_CONTENT setting, celery task never gets executed although there is no error being reported. When I add "pickle" back in, celery task immediately working after restarting everything. I believe default serializer used by celery version 3.1.23 is pickle based on information presented in the celery doc/links above. I did not further investigate what is needed to use a serializer other than the default pickle in version 3.1.23 since I thought if we go with version 4.0, we will not run into this issue any more, so it seems to me the effort is not worthwhile to investigate further to use a different serializer than the default pickle if we will go with the version upgrade route. @mjstealey also mentioned he already has a prior work that version-upgraded hydroshare base image including upgrading celery to 4.0, so I think this security issue will resolve itself if we upgrade celery version. Let me know if you have other thoughts.

**Comment by hyi** [comment]
@alexlemann I think you are right, upgrading to 4.0 may involve a lot of work with our current code base since I see a lot of celery deprecation warning such as ```celery.task.sets and TaskSet is deprecated and scheduled for removal in version 4.0. Please use "group" instead (see the Canvas section in the userguide)```. I have also tried to update celery in my container to version 4.0.2, but ran into a lot of import errors for celery due to those deprecations. Agreed fixing this issue by upgrading to version 4.0 does not look like an easy path to us. I really does not want to spend too much time on this, any reference or idea you can share with me to strip out pickle from our current code base without celery version upgrading?

**Comment by hyi** [comment]
@alexlemann I managed to get it to work without using pickle object serialization on the current celery version 3.1.23. I have to add two additional settings to inform celery to use JSON as serialization format rather than the default pickle. This makes object not serializable, so I have to change create_bag_by_irods() task signature a bit without passing object to the task. Everything seems to work as expected now with pickle being stripped out. Will deploy it to a VM for @mjstealey and @pkdash to test and code review.

**Comment by alexlemann** [comment]
@hyi  Apologies to not getting to your Q's sooner, but it sounds like it worked out well. This will also be an important step towards 4.x .

**Comment by hyi** [comment]
@alexlemann Agreed, this is one item to be resolved in celery 4.x since we cannot depend on pickle serialization format in 4.x. Thanks for your comment on 4.x upgrade route which prompted me to dig deeper into this issue.

**Comment by hyi** [comment]
Tested on beta and it works as expected. Closing.
