### ISSUE TITLE
Get file type metadata - POST error

### ISSUE THREAD

**Issue by mauriel133** [hydroshare/hydroshare#1804]
I'm getting a POST error whenever I click on a file item in the resource landing page.

![image](https://cloud.githubusercontent.com/assets/2448568/22441290/02c04886-e6f4-11e6-8eef-2f5d40fe719c.png)

I think this has to do with the function function **showFileTypeMetadata** declared inside hs_file_browser.js

**Comment by pkdash** [comment]
@mauriel133 I will fix it.

**Comment by pkdash** [comment]
@mauriel133 Can you test this on dev and then close the issue if it got resolved?

**Comment by mjstealey** [comment]
presumed to be done
