### ISSUE TITLE
Review XSS

### ISSUE THREAD

**Issue by alexlemann** [hydroshare/hydroshare#1805]

**Comment by aphelionz** [comment]
@alexlemann Are you comfortable closing this in light of the work I've done in https://github.com/hydroshare/hydroshare/pull/1819

**Comment by alexlemann** [comment]
@aphelionz In order to close this, input validation and output checking needs to be improved. Check out the call notes for specifics.

**Comment by dtarb** [comment]
@alexlemann @aphelionz can this be closed or is more needed.

**Comment by alexlemann** [comment]
@aphelionz with #2052 merged can this issue be closed?
