### ISSUE TITLE
Review CORS + CSP

### ISSUE THREAD

**Issue by alexlemann** [hydroshare/hydroshare#1806]
django-cors-headers settings
nginx config

**Comment by alexlemann** [comment]
Check ordering of middlewares in settings (see: django-cors-headers docs)

**Comment by aphelionz** [comment]
@alexlemann Are you comfortable closing this in light of the work I've done in https://github.com/hydroshare/hydroshare/pull/1819

**Comment by alexlemann** [comment]
Sounds okay to merge your CSP ( #1819 ) + CORS works. I added comments to your PR and updated this ticket's title to include CSP.

**Comment by alexlemann** [comment]
Oops... And given my previous comment, I'm comfortable closing this once the PR is merged.

**Comment by dtarb** [comment]
@alexlemann @aphelionz can this be closed, or is more needed.

**Comment by dtarb** [comment]
Alva reported entire nginx has been updated since this, so closing.
