### ISSUE TITLE
Model Program - 'Data Files' front end does not update with new version

### ISSUE THREAD

**Issue by jsadler2** [hydroshare/hydroshare#1815]
When a new version of a Model Program resource is created, the file names that have been assigned to the "Computational Engine", "Software", "Documentation," and "Release Notes," metadata terms are not reflected on the front end in edit mode when a new version is created.

![image 2](https://cloud.githubusercontent.com/assets/6943441/22517480/3bbae752-e877-11e6-8b18-1e9832d92cca.png)
![image](https://cloud.githubusercontent.com/assets/6943441/22517490/3f6c07a0-e877-11e6-9440-bfc691074937.png)

**Comment by pkdash** [comment]
@jsadler2 Where did you do this test?

**Comment by jsadler2** [comment]
@pkdash this test was done on www

**Comment by pkdash** [comment]
@jsadler2 If it was on www, then my recent huge code cleanup did not introduce this bug.

**Comment by jsadler2** [comment]
@pkdash right. it has to do with making a new version of the _resource_ not the new, cleaned up version of the _code_

**Comment by pkdash** [comment]
@jsadler2 What's the status on this issue?

**Comment by jsadler2** [comment]
@pkdash still working on it

**Comment by jsadler2** [comment]
Resolved and pulled into code base. Closing
