### ISSUE TITLE
Upgrade HydroShare to use iRODS version 4.2

### ISSUE THREAD

**Issue by rayi113** [hydroshare/hydroshare#1818]
Upgrade HydroShare to use iRODS version 4.2

**Comment by mjstealey** [comment]
Branch [1818-irods-4.2.0](https://github.com/hydroshare/hydroshare/tree/1818-irods-4.2.0) created as starting point for this work.

- MUST run using `irods/use-local-irods.sh` script in order to enable locally federated iRODS v.4.2.0 Docker containers.
- Example using the hydrodev VM

    ```
    $ cd /home/hydro/hydroshare/
    $ git checkout 1818-irods-4.2.0
    $ cd irods/
    $ ./use-local-irods.sh
    $ cd ../
    $ ./hsctl rebuild --db
    ```

**Comment by rayi113** [comment]
Closing this since we'll revisit upgrading HydroShare 4.2.x and not 4.2 at this time due to #2140.
