### ISSUE TITLE
Failed to create a ref_ts res on www

### ISSUE THREAD

**Issue by zhiyuli** [hydroshare/hydroshare#1822]
We just noticed this error on www.
![image](https://cloud.githubusercontent.com/assets/10070599/22569447/ce9a1952-e954-11e6-92fe-a47f23afa22c.png)

**Comment by zhiyuli** [comment]
@pkdash  @hyi 

I could reproduce the error locally. Looks like something changed in hs_core broke it??? You know any recent changes may contribute to this?

Traceback (most recent call last):
  File "/hydroshare/ref_ts/views.py", line 199, in create_ref_time_series
    metadata=metadata)
  File "/hydroshare/hs_core/hydroshare/resource.py", line 426, in create_resource
    hs_bagit.create_bag(resource, fed_zone_home_path=fed_zone_home_path)
  File "/hydroshare/hs_core/hydroshare/hs_bagit.py", line 242, in create_bag
    istorage = create_bag_files(resource, fed_zone_home_path)
  File "/hydroshare/hs_core/hydroshare/hs_bagit.py", line 97, in create_bag_files
    out.write(resource.get_metadata_xml())
  File "/hydroshare/hs_core/models.py", line 1511, in get_metadata_xml
    return self.metadata.get_xml(**pretty_print=pretty_print**)
TypeError: get_xml() got an unexpected keyword argument 'pretty_print'

**Comment by zhiyuli** [comment]
@hyi @pkdash 
OK...I compared the get_xml() in Ref_TS code with other res_types' code, Ref_TS had a missing parameter "pretty_print=True" in get_xml(). I added it and seems it fixed this error. 
Looks like that parameter had been missing in Ref_TS for a while until some recent changes finally exposed this issue.

**Comment by pkdash** [comment]
@zhiyuli Should this be closed?

**Comment by zhiyuli** [comment]
fixed on www
