### ISSUE TITLE
Notifying users of future service outages and changes

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#1831]
There needs to be some mechanism -- on the initial HydroShare page -- that notifies users of future events like downtime and releases.  The way this is typically done is as follows: 
1. In an admin interface, someone like Michael writes a message with a start and end date, specifying the outage or change to be made. Most systems allow one to also specify a "posting date" so that one can write notifications that appear in the future. This particular design is based upon the notification system in ExpressionEngine, upon which www.cuahsi.org is based. It is typical. 
3. Then we write code that shows those notifications on the start page, for which the posting date >= today and the end date <= today. 
4. When the end date is passed, the notification automatically disappears but is kept in a history. Thus, users can view past notifications on a history page, as desired. .

**Comment by aphelionz** [comment]
We have an MOTD now. Closing this.
