### ISSUE TITLE
App testing: emerging process to communicate with developers, CUAHSI, and users on Help

### ISSUE THREAD

**Issue by ChristinaB** [hydroshare/hydroshare#1841]
What we do now needs guidance from HydroShare leadership communicating with developers on expectations. 
1. Developer posts App (some of these are live on main HS website, some are beta)
2.  Developer works with UW and CUAHSI in Google doc to draft help page for expert users which gets posted as a Help page.
3.  Ad-hoc testing with inner circle of App supporters occurs based on .... random set of ill formed processes. [THIS IS WHERE WE NEED TO IMPROVE]
4.  Printable demo is developed with step by step instructions. This is needed for an introduction to any new user, at AGU and other events.  This process has proven exhausting because it highlights the bugs and limitations of the App.  [THIS IS SOMETHING WE NEED DEVELOPERS TO DO, not Help page editors].
5.   Test for App Bugs with SWOT analysis.  This is limited to the use case in the printable demo.
6.  Define if the bug is a code issue or explanation/education issue.  [COMMUNICATION AND ITERATION BETWEEN TESTERS AND DEVELOPERS NEEDED HERE]  Decide next steps: Schedule a retest with SWOT analysis, remove from App page, recommend for use in CUAHSI events, Design Chaperone tips
If used in CUAHSI events - needs a printed demo handout, training with CUAHSI staff by developer.
If recommended removed from App page - discuss in developer meeting
7. Testing with larger audience (10-30+ students) with Google form data collection. This is a minimum one hour commitment per App per tester.

Off line ongoing testing option of note:
Add pop-up with short question: How did you like [This App] ???  1-5 stars answer. (see webex example). 
Send to CUAHSI for user (10+ users?) testing

**Comment by dtarb** [comment]
Addressed in #1843
