### ISSUE TITLE
Enable unlimited, bidirectional file transfer for apps

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#1842]
Edit: Expanding this issue to cover all potential methods for file transfer. 

The basic problem is that native REST -- no matter how much we might tune it -- is going to be limited in terms of file size to transfer. The real limit is the REST timeout, which defines -- in turn -- how big the file can be, regardless of platform.  Thus, to really solve this problem, some kind of out of band transfer -- not involving REST -- is needed. 

We need a mechanism that can transfer literally any size of file. At the same time, we are limited by the following design issues: 
1. Any mechanism has to be asynchronous. We can't afford to wait for the transfer to finish. We need to be able to check on progress. 
2. We made the decision that file metadata would be harvested at arrival time. Thus
3. Django has to be able to figure out that an uploaded file has arrived, in order to harvest metadata. 
4. The app server should not have persistent access to the iRODS repository on the core server. This would potentially violate resource privacy. 

That being said, there are several solutions that have this property, including iRODS icommands, secure FTP (SFTP), torrents, etc. In this thread, we were mainly discussing how to utilize iRODS as this out of band mechanism. There are other solutions, but all have the same basic form: 

1. The app makes a REST request of the Django server to either

    a. get upload credentials or 
    b. give the Django server access to a directory on the app server. 

2. The transfer proceeds asynchronously, either by 

   a. The app starts a transfer using upload credentials that allow transfer of a single file or 
   b. Django starts a transfer using credentials on the app server.

3. Progress is monitored in the two cases by 

   a. Direct monitoring of the transfer by the app. 
   b. REST requests to Django to request progress. 

The question in this thread is which of these to implement. We are presently considering two possible solutions: iRODS and SFTP. 
1. iRODS documentation doesn't make it immediately clear that one will be able to authorize an app in a limited enough fashion to protect other resources from changes during an upload, and protect other resources from access during a download. The other solution -- Django federating with the app -- is documented to work. 
2. SFTP/SCP has the drawback that the resource has to be read from and uploaded to a holding area and then transferred to iRODS. If that SCP is initiated by the app, then there is a question of how to keep apps from interfering in doing uploads. If the SCP is initiated by Django there is no such concern. 
 
--------

Original description: Apps need the high-speed data transfer capabilities from iRODS to send and receive large files to and from HydroShare. This requires the "UDP blast" technology of iRODS, which runs at roughly 10X the speed of REST, and requires no middle servers between source and sink even in federated mode. However, it runs on a completely different port than REST and there are security concerns with opening up the federated iRODS servers fully to the app server. There is a straightforward way to securely accomplish this but it takes some careful planning. Details are filled in below. 

---

@pkdash @zhiyuli @mjstealey @hyi @dtarb The full plan for UDP Blast implementation is as follows. 

* The Apps server will have an iRODS instance that is **not federated** with HydroShare. Federation is for permanent storage management; we want to act on files and not permanently store them. 

* The REST interface will be used to tell HydroShare to "push" and "pull" files from the Apps server. These work a lot like "push" and "pull" in GitHub. **This involves icommands for which only HydroShare has credentials.**
 
  * Using REST, **the app informs HydroShare of the app credentials necessary for HydroShare to send or receive a file.** As mentioned on the call, these can be temporary credentials with a lifetime of one request, or can be longer term credentials at need. 

  * Then **HydroShare has all of the credentials required** and initiates the transfer as a "push" (HydroShare to app) or "pull" (app to HydroShare) request in iRODS itself. 

  * The app can check up on the status of a transfer using REST requests.

* Thus the app communicates only with HydroShare via REST, and then HydroShare initiates an under-the-table PUSH or PULL between iRODS servers, and then manages that. 

The whole process will require the following REST commands to Django. Django will then "manage" the appropriate icommands to make the transfers happen. Note that these icommands will not actually involve the Django server as a middleman. Note also that the typical app programmer will never call these directly, but will use the python HydroShare client to invoke them.  
* `/hsapi/irods/pull/{resource_id}/{file_path}`
   * Initiate a pull from HydroShare or a federated server to the app server via iRODS direct connectivity.
   * File path is optional.  
   * _**NOT NECESSARY DUE TO DESIGN DETAILS** The parameters include the app server iRODS credentials._
   * _The parameters include the HydroShare user credentials of the requesting user._  
   * HydroShare checks access privileges and, if appropriate, 
   * The iRODS request is started and proceeds asynchronously. HydroShare tracks its progress. 
   * This request is actually initiated between the data source and sink, and does not involve Django at all.
   * Return is a "request id" that identifies the request. 
* `/hsapi/irods/push/{resource_id}/{file_path}`
   * Initiate a push from the app server to the HydroShare server or a federated server.
   * File path is optional.  
   * _**NOT NECESSARY DUE TO DESIGN DETAILS** Again, the parameters include the app server iRODS credentials._ 
   * _The HydroShare requesting user credentials need to be part of the parameters._ 
   * The iRODS request is started and proceeds asynchronously.
   * This request is actually initiated between the data source and sink, and does not involve Django at all.
   * Return is a "request id" that identifies the request. 
* `/hsapi/irods/check/{request_id}` 
    * Reports on the status of a request and whether it is completed. 
* `/hsapi/irods/cancel/{request_id}`
    * Cancels a request. 

Note that the REST command `pull` actually does a `put` in the other direction, while `push` does a `get` in the opposite direction.

Note the following very important features of this solution: 
* The App server never has credentials over the HydroShare iRODS store. 
* Thus, anyone can create an app server that works this way, without special privileges or credentials. 
* HydroShare receives the App server iRODS credentials and has the HydroShare iRODS credentials.
* Only with all of these credentials can the transfer be accomplished, so it must be initiated and managed on the HydroShare side. 
* These PUSH and PULL requests are very much like "PUSH" and "PULL" in GitHub. 
 
Thus **more or less anyone can safely write code anywhere that utilizes this mechanism.** No special privilege on the app server is necessary. 

**One should never store HydroShare iRODS credentials on the app server.** This is a security hole beyond imagination, and not sustainable in any case. We need people to be able to build app servers at will. 

**All of this can be accomplished in the context of hs_restclient, as the control interface for an app consists entirely of REST requests.**

---

NOTE: thread edited by @mjstealey

---

Other design considerations gleaned from discussion below: 
1. This requires the app server to be federated with the HydroShare iRODS zone with one way privilege;  read/write  from HydroShare -> apps; no privilege from apps -> HydroShare.
2. Thus, this requires an iRODS instance to run on the app server. 
3. After this change, the HydroShare proxy user gets read/write on apps, so the scheme works. 
4. Files are only copied from the HydroShare iRODS servers to the app iRODS zone. We also need to arrange for access to the copied file by apps on the app server, either via copying to the local filesystem, or FUSE.
5. UDP blast technology is not practical on noisy networks and should not be enabled (via icommands -Q option) unless necessary and tuned. 
6. PUSH to HydroShare from apps should be done similarly to copying files from a user zone; the file should be pushed to the final location and then indexed.

**Comment by pkdash** [comment]
@alvacouch Is this going to be only one way file transfer - from Hydroshare to user Irods server? The other way transfer would be great if we can do using hs_restclient.

**Comment by mjstealey** [comment]
> Is this going to be only one way file transfer

I would think yes, as there is no guarantee the user will want to generate a new resource from the manipulated output of their work. One-way high speed transfer to get the files onto the apps server.

> The other way transfer would be great if we can do using hs_restclient

Once the resource files are over at apps being consumed, manipulated, etc., wouldn't the existing mechanisms stay in place for generating a new resource, or appending to an existing resource from them as there is now?

**Comment by pkdash** [comment]
@mjstealey 

> Once the resource files are over at apps being consumed, manipulated, etc., wouldn't the existing mechanisms stay in place for generating a new resource, or appending to an existing resource from them as there is now?

You mean the transfer over http? That would stay. But we again have the same problem. What if the user generates a big file (>1 GB)?

**Comment by zhiyuli** [comment]
Will this make the route of data transfer even longer?  hydroshare irods --> apps irods --> apps server

**Comment by pkdash** [comment]
The path may be long but it will behave like a super highway.

**Comment by mjstealey** [comment]
> But we again have the same problem. What if the user generates a big file (>1 GB)?

Could be treated in the same manner as large resources in the hydroshareuserZone, assuming the apps generated output gets registered into iRODS on the apps side.

Then on a "save to HydroShare" call the apps iRODS server could give the hydroshare iRODS server temporary credentials to iget the data from it. This would an analogous converse to the iput it had done to push data over there in the first place, which may be what you were asking in the first place...

**Comment by zhiyuli** [comment]
after hydroshare irods server pushes a res to apps irods sever, how can apps access the res data? should apps use some credentials to access apps irods sever? Does access control at this point? How to prevent userA's app from accessing a res previously downloaded to apps irods server by userB's app?

**Comment by mjstealey** [comment]
@zhiyuli - I would think about this in a different way. 

Think of the apps server as being in control of the apps irods server, and work out the access control issues more generically. Whatever mechanism you use to prevent apps developers from doing malicious things to other peoples apps or data on local disk can be abstracted to iRODS calls or rules in some form or another. 

Define how you'd want things to work as if they were just written to local disk first, then we subset them into iRODS based actions.

If however you don't have a way of preventing apps developers from interfering with other apps developers data, then that is the first issue that needs to be resolved.

**Comment by pkdash** [comment]
@mjstealey 

> Then on a "save to HydroShare" call the apps iRODS server could give the hydroshare iRODS server temporary credentials to iget the data from it. This would an analogous converse to the iput it had done to push data over there in the first place, which may be what you were asking in the first place...

That's what we need. The GeoTrust project team has a need to push very big files to Hydroshare.

**Comment by zhiyuli** [comment]
@mjstealey 
Good points regarding the permission issues. 

I agree that once res data has been delivered to apps server, it becomes apps/Tethys's responsibility to prevent any illegal access to locally stored res data. 

This new architecture/changes we are working on should keep hydroshare access control integrity at every step before data is delivered to apps server. I am visioning the new changes could be transparent to apps, or say apps should keep using hs_restclient as usual without major changes.

**Comment by alvacouch** [comment]
@mjstealey @zhiyuli @pkdash The proposal will allow two way transfer but enabling correct access control without federating the apps server (which I really don't want to be necessary) requires a careful dance of protections. Under no circumstances should the apps server (or any apps server) be responsible for access control. That is a big mistake. Will post details now.

**Comment by alvacouch** [comment]
@pkdash @zhiyuli @mjstealey @hyi @dtarb The full plan for UDP Blast implementation is as follows. 

* The Apps server will have an iRODs instance that is **not federated** with HydroShare. Federation is for permanent storage management; we want to act on files and not permanently store them. 

* The REST interface will be used to tell HydroShare to "push" and "pull" files from the Apps server. **This involves icommands for which only HydroShare has credentials.**
 
  * Using REST, **the app informs HydroShare of the app credentials necessary for HydroShare to send or receive a file.** As mentioned on the call, these can be temporary credentials with a lifetime of one request, or can be longer term credentials at need. 

  * Then **HydroShare has all of the credentials required** and initiates the transfer as a "push" (HydroShare to app) or "pull" (app to HydroShare) request in iRODs itself. 

  * The app can check up on the status of a transfer using REST requests.

* Thus the app communicates only with HydroShare via REST, and then HydroShare initiates an under-the-table PUSH or PULL between iRODS servers, and then manages that. 

The whole process will require the following REST commands to Django. Django will then "manage" the appropriate icommands to make the transfers happen. Note that these icommands will not actually involve the Django server as a middleman. Note also that the typical app programmer will never call these directly, but will use the python HydroShare client to invoke them.  
* /hsapi/irods/pull/{resource_id}/{file_path}
   * Initiate a pull from HydroShare or a federated server to the app server via iRODS direct connectivity. 
   * The parameters include the app server iRODS credentials. 
   * HydroShare checks access privileges and, if appropriate, 
   * The iRODs request is started and proceeds asynchronously.
   * This request is actually initiated between the data source and sink, and does not involve Django at all.
   * Return is a "request id" that identifies the request. 
* /hsapi/irods/push/{resource_id}/{file_path}
   * Initiate a push from the app server to the HydroShare server or a federated server. 
   * Again, the parameters include the app server iRODS credentials. 
   * The iRODS request is started and proceeds asynchronously
* /hsapi/irods/check/{request_id} 
    * Reports on the status of a request and whether it is completed. 
* /hsapi/irods/cancel/{request_id}
    * Cancels a request. 

Note the following very important features of this solution: 
* The App server never has credentials over the HydroShare store. 
* Thus, anyone can create an app server that works this way, without special privileges or credentials. 
* HydroShare receives the App server iRODS credentials and has the HydroShare iRODS credentials.
* Only with all of these credentials can the transfer be accomplished, so it must be initiated and managed on the HydroShare side. 
* These PUSH and PULL requests are very much like "PUSH" and "PULL" in GitHub. 
 
* Thus **more or less anyone can safely write code anywhere that utilizes this mechanism.** No special privilege on the app server is necessary.

**Comment by hyi** [comment]
@alvacouch @mjstealey @rayi113 @zhiyuli @dtarb @pkdash I agree this proposal sounds promising, but there are concerns/issues we need to resolve before we even consider to go this route. Initial set of concerns/issues/comments are listed below:

- All REST irods file transfer requests only accomplish transferring files from hydroshare federated zone controlled by hydroshare irods server to an apps irods account irods storage space controlled by apps irods server. As a result, after making these REST calls, files only reside in an irods zone storage space, not on Django server or Apps server. For apps server to retrieve the files to apps server for preprocessing or put the files to geoserver on apps server, apps server has to use icommands to retrieve the files from apps irods server. For the other way around, i.e., for django server to use files retrieved from apps irods server storage, it is even more problematic. Our current way for apps to create a resource using files from apps server or add files to an existing resource, the files need to be on django server or in a user's scratch space in hydroshare user zone if the user has created an irods account in user zone, so we need to determine where to put files transferred from apps server to HydroShare iRODS server. In any case, there is an extra hop required to retrieve files from irods server to django server or apps server if our REST only transfer files between two iRODS servers. In fact, I believe direct iRODS server to iRODS server file transfer is only supported if these two iRODS servers are federated or they are in the same zone, so a middleman (e.g., Django server with icommands installed) has to be involved for an extra hop. So I don't see much performance gain using this proposed approach as opposed to using icommands on apps server to retrieve files from hydroshare irods zone directly to apps server. The only potential issue I can see with using icommands on apps server directly without involving a separate irods server is potential security concerns. But I think these security concerns can be worked around with careful design.

- The proposed REST functions need to have user included in the request since REST is stateless and user info is needed for access control purpose.

- Specific to iRODS UDP blash, the following comments are brought up by @rayi113: ```it’s been my experience that iRODS UDP blast requires some manual tuning to get better performance out of it vs. just native iput/iget, plus taking into consideration that without specifying –N for normal tcp-based transfers iput/iget defaults to 32 threads, but can go up to 64.  In other words, it may be better to deterministically rely on tcp-based iput/iget with a higher –N argument than go to UDP with “untuned” environment variables.```. Reference from iRODS documentation: ```The -Q option specifies the use of the RBUDP transfer mechanism which uses the UDP protocol for data transfer. The UDP protocol is very efficient if the network is very robust with few packet losses. Two environment variables - rbudpSendRate and rbudpPackSize are used to tune the RBUDP data transfer. rbudpSendRate is used to throttle the send rate in kbits/sec. The default rbudpSendRate is 600,000. rbudpPackSize is used to set the packet size. The default rbudpPackSize is 8192.```

**Comment by alvacouch** [comment]
@hyi @mjstealey It is true that iput and iget issued from HydroShare put the resource file in the local iRODS zone, but the apps server has the flexibility to decide how that file is accessed. One can access it via local icommands that has no access to HydroShare zones, or one could expose the iRODS zone as a filesystem mount on the app server. The latter would be transparent to apps; it would not require a copy but it would be a bit slower to access in the app. I recommend this option. 

All things considered, the transfer rate of iRODS blast is much faster than the REST transfer rate, and the file size is unlimited rather than limited by REST. These two factors outweigh the slightly slower speed of file access (which is really a proxied access). 

One reason that iRODS blast requires performance tuning is that many firewall administrators consider its bandwidth use to be antisocial and block such transfers. It might be necessary to tune down its bandwidth use to be "sociable" and avoid firewall blocks. 

Still, even if it only runs at 5x the speed of REST, the fact that it can transfer files of arbitrary size makes it better than REST overall for large file movement.

**Comment by alvacouch** [comment]
@hyi  @mjstealey @rayi113 If the apps server contains credentials to the HydroShare zone, there is no measure or workaround that can make the solution secure. An app developer has control of the app server. Even the capability of issuing icommands from the apps server to the HydroShare iRODS server is a very bad idea.

**Comment by hyi** [comment]
@alvacouch @mjstealey @rayi113 Agreed having apps server to have credentials to HydroShare zone is a security issue and bad idea, but I believe @mjstealey has already set up a read-only iRODS account to hydroshare zone for apps server so that read-only iRODS separate account can be used to retrieve large files directly from hydroshare zone subject to access control by REST. This approach is only a viable option if apps server is a trusted party with careful security enforcement, otherwise, read-only iRODS account can still be used to bypass access control and retrieve resources that are not granted access. This will have performance benefit for large files since only one parallel transfer is needed to retrieve file directly but are not as secure as the proposed approach by @alvacouch.

**Comment by hyi** [comment]
@alvacouch @mjstealey @rayi113 As for UDP blast, we are not currently using it for iget/iput although we can add the ```-Q``` option to use UDP transfer. I'd recommend to keep using the current default irods tcp-based parallel transfer without customized performance parameter tuning unless we ran into parallel transfer performance issues.

**Comment by alvacouch** [comment]
#hyi @mjstealey @rayi113 I've read over the docs again and here are my conclusions: 

1. We do have to federate the apps server with the HydroShare zone. 
2. We do not have to allow any access from the app server to the HydroShare zone. The federation can be one-way, from HydroShare to apps, and not the other way. 
3. We can do everything via federated access from HydroShare to the app server. 

This is the only way we can assure security in a situation in which we have no control over a server.

**Comment by alvacouch** [comment]
@hyi @rayi113 @mjstealey The problem with the existing iRODS zone is that it completely bypasses access control. I have told Drew to keep using it but to watch for something better. If we keep providing that functionality, we will not be able to have untrusted app developers.

**Comment by alvacouch** [comment]
@hyi @rayi113 @mjstealey It is perfectly fine to develop this mechanism without UDP and then enable UDP at need. The Restart option alone justifies using iRODS transfer rather than REST transfer. 

To listen to users, there's a need.

**Comment by hyi** [comment]
@alvacouch I agree with your conclusions - federation is required to enable parallel file transfers between irods servers in different zones. One way transfer from hydroshare to apps would simplify things a lot, but apps would not be able to post resources larger than 1GB back to hydroshare via REST, which may be a good thing for performance and policy consistencies.

**Comment by pkdash** [comment]
> One way transfer from hydroshare to apps would simplify things a lot, but apps would not be able to post resources larger than 1GB back to hydroshare via REST, which may be a good thing for performance and policy consistencies.

So are we going to support both pull and push or not?

**Comment by alvacouch** [comment]
@pkdash Yes, we can support both push and pull by creating an iRODS federation connection with apps that is read/write on the apps side but has no privilege on the HydroShare side. This is different from a publication federation.

**Comment by hyi** [comment]
@alvacouch @pkdash There is more to it for a push from apps to hydroshare. Specifically, where to put files initially for resource creation or add files to existing resources if we bypass django? It can be put into the user's irods account in hydroshare user zone, but that depends on users already having an irods account in user zone, plus some other bits and pieces that need to be worked out.

**Comment by alvacouch** [comment]
@hyi @pkdash The problem of where to put pushes is solvable. Long term, we are going to need a holding area larger than /tmp and a systematic approach to temporary files. This is true whether or not the files are pushed or uploaded. Remember that in the proposed solution, HydroShare has complete control of where files are put and the app gets no say at all.

**Comment by hyi** [comment]
@alvacouch Agreed it is solvable, but we should leverage existing implementation as much as possible rather than adding new implementations. Currently, the resource can only be created from files uploaded to django server or from files in irods user zone from user's irods scratch space assuming the HydroShare user has already created a corresponding irods user in user zone. If we add another temporary common space, we'll have to add that into HydroShare codebase to support the third option for resource creation or adding files to existing resources. It is definitely doable, but it'd be the best to leverage existing implementations if possible.

**Comment by pkdash** [comment]
@alvacouch @hyi Is it not possible to push the file to Hydroshare zone first and then link it to  ResourceFile object?

**Comment by hyi** [comment]
@pkdash @alvacouch That is what is currently done for files coming from user zone. I think it can be done in the similar way also for files coming directly from a federated zone in apps irods server, but some bells and whistles need to be added into resource creation and add files to resources functions to make sure the path all set up correctly. I agree this is more direct and avoid an extra hop, so should probably what we should go for if we decide to go with this.

**Comment by alvacouch** [comment]
@hyi @pkdash Pushing to the HydroShare zone first -- just like for user-zone files -- is fine.

**Comment by alvacouch** [comment]
@hyi @pkdash  It strikes me that we could prove this concept on the current App server, by giving the core HydroShare zone the permission to write or read anything in the app server zone, in the context of the existing federation.  We could keep the app server's read-only access but not use it for this experiment. 
@mjstealey Could we make this change and try this out at the icommands level?

**Comment by alvacouch** [comment]
@mjstealey @hyi @pkdash @rayi113 One technical question: if we want to copy something from a federated zone to the app zone, do we need specific privilege for the federated zone or is the privilege of the hydroproxy user on the main zone sufficient? The latter would seem to be sufficient by the definition of federation but I cannot be sure.

**Comment by mjstealey** [comment]
> HydroShare zone the permission to write or read anything in the app server zone, in the context of the existing federation

There is no federation, there is no app server zone.
There is not an iRODS server installed on the apps server, only iCommands as far as I know
@zhiyuli may be able to better explain what's installed over there.

**Comment by alvacouch** [comment]
@mjstealey Are the app server icommands now enabled based upon a different user login than hydroproxy, with read-only access credentials?

**Comment by hyi** [comment]
@alvacouch Yes, if we want to copy something from a federated zone to the "hypothetical" app zone, we can set up permission to have hydroshare zone proxy user to "own" anything in the app server zone. As @mjstealey mentioned, nothing exists on apps server yet, so everything is hypothetical at this point.

**Comment by alvacouch** [comment]
@mjstealey What kinds of changes would have to be made on the app server to enable such a federation? How difficult would it be to maintain? How does it scale? These are the real questions that we need answered before we proceed with this proposal. CC: @rayi113 @hyi @pkdash

**Comment by zhiyuli** [comment]
apps.hydroshare.org server has NO irods server, irods zone or icommands installed currently. all apps are using hydroshare rest api (hs_restclient).

appsdev.hydroshare.org server (dockerized tethys) has icommands installed, and there is a script that compares performance of rest api and icommands for testing purpose. It downloads some resources via rest api first, and then downloads them again by calling iget (talking to hydrotest41Zone at hydrotest41.renci.org using hsproxy account).  No app is using icommands yet.

**Comment by mjstealey** [comment]
> What kinds of changes would have to be made on the app server to enable such a federation? How difficult would it be to maintain? How does it scale?

1. Install an iRODS iCAT server on apps (actually could be anywhere so long as its vault is reachable by apps).

2. Federate with hydroshareZone giving the wwwHydroProxy user full access in the new zone. There will be no access provided to any users from the appsZone in the hydroshareZone, so kind of a one-way street for push/pull from the hydroshareZone side exclusively.

3. Maintenance / scale come down to how much content we wish the appsZone to hold onto. I'd think we'd have some kind of cache and purge policy in that if a resource weren't interacted with over some time period it gets removed from the appsZone.

Would need to investigate credential / token passing from appZone to hydroshareZone to enable resource creation from new content generated on the apps side if the user wishes to push their work back to HydroShare.

**Comment by alvacouch** [comment]
> Would need to investigate credential / token passing from appZone to hydroshareZone to enable resource creation from new content generated on the apps side if the user wishes to push their work back to HydroShare.

@mjstealey If we give apps the ability to write into the federated app zone, and HydroShare proxy inherits access from federation, is this necessary?

**Comment by alvacouch** [comment]
Based upon the current discussion, it seems that there are two needs for the app iRODS zone: 
1. some form of cache that stores copies of resources/files copied from HydroShare to iRODS. 
2. some workspace that would be available to apps for the purpose of preparing an upload to HydroShare. 
(1) would be managed by HydroShare, while (2) would be managed by apps.

**Comment by mjstealey** [comment]
> If we give apps the ability to write into the federated app zone, and HydroShare proxy inherits access from federation, is this necessary? Can't we just pull the file in from HydroShare based upon federation credentials?

I should clarify my thought a bit on this as it is tangential and pertained to a demo using a variant of HydroShare federated with an iRODS server within RADII for running models.

The workflow incorporated the desire to write model output data back to the hydroshareuserZone, and not the hydroshareZone. This was done to allow the user the opportunity to review the data in their personal iRODS store without explicitly having to make a new resource out of it. If they then chose to make a resource from it, they could; if not, they purge the output.

Our apps ecosystem can in some ways be seen as a parallel to this. There may be times the user wants to manipulate a resource, but save the output someplace other than a HydroShare resource. In this case some kind of credential / token would be needed by the HydroShare application to transfer the data back to the appropriate iRODS user space.

Too many birds, not enough stones...

**Comment by alvacouch** [comment]
@mjstealey So, to translate this to use cases, tickets might be necessary for transfers to the iRODS user zone on the HydroShare servers?

**Comment by alvacouch** [comment]
@rayi113 @hyi @mjstealey @dtarb 

I realize that there's a simpler approach for download. One can issue an access token via rest and then the app can use the token to transfer a file. This does not require federation. 

This doesn't work as well for upload, though, because of the nature of upload. There is no straightforward way to learn in Django when the upload has been completed, because the upload is being managed by an icommand on the app server. We need to know this in order to properly harvest metadata.

**Comment by mjstealey** [comment]
> This doesn't work as well for upload, though, because of the nature of upload. There is no straightforward way to learn in Django when the upload has been completed, because the upload is being managed by an icommand on the app server. We need to know this in order to properly harvest metadata.

Can there not be some form of signal passing wrapping the process that corresponds to the state of the transaction? Assuming we want file I/O to be asynchronous to begin with due to not knowing the state of the network or size of the file ahead of time.

**Comment by alvacouch** [comment]
@mjstealey Not practical. That is in the state of the app. We would have to enforce that at the app level. 

We could write an iRODS rule that calls Django and tells it that the file has arrived and to index the file. But I don't know what the failure modes are and whether it is possible to write a rule that cleans up after a failure of transmission?

**Comment by alvacouch** [comment]
@mjstealey 
(The filesystem is already littered with the results of software failures. Attempting to clean this up.)

**Comment by mjstealey** [comment]
> Attempting to clean this up

👍

**Comment by hyi** [comment]
@alvacouch If we can really get around security issue with a token issued from HydroShare REST for apps download, I believe we should be able to use the same token for apps upload. In terms of notification of upload transfer status or transfer failure from apps to HydroShare, since apps issue icommands for file upload to HydroShare, apps know whether icommands succeed or raise exceptions and can act accordingly. In the case of success, apps can issue create_resource() call with file path being just uploaded (I think hydroshare user zone can be used for this, we don't even have to require each apps user has an account on hydroshare user zone, we can create an apps temp iRODS user account on hydroshare user zone just for this use case). In the case of failure/irods exception, apps can act accordingly including proper clean up. @mjstealey @rayi113 @dtarb

**Comment by pkdash** [comment]
I agree with @alvacouch that we should avoid cluttering our Hydroshare zone. It would be great we can use a scratch area in Hydroshare user zone for intermediate file upload. Then Django will be responsible for moving that uploaded file to Hydroshare zone - I assume this part of the workflow has already been implemented.

**Comment by hyi** [comment]
@pkdash That is in line with my thinking, i.e., create an irods user account, say, apps_user, in hydroshare user zone as the scratch space for this, and yes, the functionality has already been implementation in resource creation and adding files to existing resources if we use the scratch space in hydroshare user zone to hold files coming from apps to be uploaded into hydroshare zone. As long as the security can be addressed using REST and perhaps iRODS ticket, I believe this is the simplest and fastest approach without requiring installation of an iRODS server for apps.

**Comment by pkdash** [comment]
@hyi 

> I believe this is the simplest and fastest approach without requiring installation of an iRODS server for apps

Apps still need iRODS server for file download - right?

**Comment by hyi** [comment]
@pkdash No, apps only needs icommands installed with no need for iRODS server as long as the credentials are addressed with token/tickets as @alvacouch mentioned above, which is the only thing I am not sure whether it can be done easily and securely.

**Comment by alvacouch** [comment]
@hyi @pkdash @mjstealey @rayi113 

The token approach would have to be combined with an iRODS rule to notify Django to harvest metadata. The harvesting routine is already written. 

@rayi113 Is this the way tokens work? Are we thinking correctly about them?

**Comment by alvacouch** [comment]
@horsburgh @pkdash @hyi @rayi113 @dtarb 

I changed the issue title and expanded this issue so that the preface describes the design limits in any "unlimited", "asynchronous" file transfer. 

The reason I am going to such trouble is to truly make transfer **"unlimited",** which is something I don't know how to do with REST.  No matter what, REST is limited by the timeout one sets. I don't know how to achieve the "unlimited" part with anything simpler, and still maintain the security and privacy of data that we promised to keep private and secure.  

Using @alexlemann 's nginx solution, we can make REST able to handle larger files, but there will still be a practical limit. The solutions considered herein don't have a practical limit.  

The preface to the issue now lays out the problem independent of the solution we choose.

**Comment by alvacouch** [comment]
The SCP solution that I indicated during the call is as follows: 

1. Some entity (either the app or the core HydroShare server) reserves a directory and issues a credential that allows read/write access to that directory. This can be a password or a public/private key pair.  
2. A REST request to HydroShare from the app serves as a credential exchange. Any credentials that HydroShare needs are part of the request. Any credentials that the app server needs are part of the response. 
3. With the appropriate credentials in hand, the request is started asynchronously. 

This differs from the iRODS solution in several important ways. 

1. No iRODS server needs to run on the app server. The app server just needs ssh installed. 
2. There need to be directories for each app somewhere, either on the core HydroShare server 
or on the app, to avoid conflict when uploading and downloading files simultaneously with different apps. 

We need to decide who initiates the transfer. It is inherently easier if HydroShare writes and reads to a reserved directory on the app. It is somewhat more difficult for HydroShare to manage multiple apps writing into the same directory on the core HydroShare server.

**Comment by pkdash** [comment]
@alvacouch In the long run the file processing that we are doing (e.g. metadata extraction) on the Django server probably needs to happen somewhere else. Otherwise large file processing can also cause problem with the web server.

**Comment by alvacouch** [comment]
@pkdash Agreed. But the problem now is that we can't even upload "reasonable" files. "Unreasonable" files are reserved for future work:)

**Comment by pkdash** [comment]
@alvacouch As soon as you enable large file transfer, the file processing problem is more likely to happen. I know we don't have to worry about that now.

**Comment by hyi** [comment]
@alvacouch The SCP solution you described above don't offer the parallel transfer capability iRODS offers, and it'd involve irods fuse or NFS mount to mount iRODS collections to local directory, then scp the large files without parallel transfer from hydroshare to apps or vice versa, which would be slow for large files. Hence I think installing icommands on apps purely for transferring files between hydroshare iRODS and apps is better for performance. For security, we can even create a apps_temp irods account on hydroshare user zone, and apps can send REST request for the resource data it needs, then hydroshare push the resource data to apps_temp irods storage on hydroshare user zone, then notify apps to retrieve resource data from apps_temp user zone to apps server using icommands. It works the other way around as well. So the main idea is to use apps_temp irods on hydroshare user zone as the intermediate liaison to bypass the security concerns. I think this approach is probably the simplest and easiest one that meets our needs. Looping in @mjstealey @rayi113 @dtarb to keep them informed.

**Comment by pkdash** [comment]
@hyi Would this strategy work for any apps not hosted on our apps server?

**Comment by hyi** [comment]
@pkdash I think so, as long as the apps server know the temp_apps iRODS account credentials and have icommands installed, it should work. @alvacouch @mjstealey @rayi113 @dtarb

**Comment by pkdash** [comment]
@hyi We should start prototyping this soon. What others think?

**Comment by hyi** [comment]
@alvacouch @zhiyuli @pkdash I assigned you all as well as myself for this PR so that we may work together soon to address this issue. I think my proposed solution above is the easiest approach we can implement within the next 2 or 3 months to meet our needs. It will involve work on iRODS, HydroShare, REST API, and apps.

**Comment by pkdash** [comment]
@hyi I am OK with prototyping your proposed solution. Would you start working on the internal api for this then?

**Comment by hyi** [comment]
@pkdash Yes, that is what I planned. You and/or @alvacouch can work on REST API and REST client parts.

**Comment by pkdash** [comment]
I can work on REST API on this.

**Comment by dtarb** [comment]
@alvacouch indicated in our prioritization worksheet that transparent file access was higher priority than this.  I would like a bit more information from @alvacouch on the preferred sequencing before we jump in on this.

**Comment by eclark-cuahsi** [comment]
Closing per backlog review discussion on 6/9/22. Large file upload should address this in a different way. This issue can be reopened if needed.
