### ISSUE TITLE
Release management and quality control for apps

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#1843]
@ChristinaB This issue is a placeholder for my action item from today's call, which is to depict my proposed app release management strategy here for everyone's perusal. It will largely be the proposal I made on Monday in the PI call, with some background. I am not committed to this in any way, but I am committed to the **principles upon which it is based.** Any solution that obeys these principles will be great.

**Comment by alvacouch** [comment]
@ChristinaB @dtarb  First, any management strategy for apps should seek to **maximize signal to noise for users**. CUAHSI -- as an organization -- serves its members by providing content that they need without noise that they don't need. This should be the same for apps. Thus, we should manage apps in a way that
* avoids duplication of functions. 
* clearly labels each app as to its potential quality. 
* assures that clicking upon the app will accomplish what is claimed. 

A side issue is that any release mechanism needs to avoid "app spam", which consists of apps that have some ulterior motive other than aiding the user, e.g., promoting something. We haven't seen this so far, but we probably will eventually. 

There are well established best practices for rating software as to its quality and usability. These include: ratings of: 
* **Alpha release**: has been only vetted by a small group of non-users, typically developers. 
* **Beta release**: has been tested and approved by a pilot group of target users. 
* **Full release**: suitable for all users. 

The concrete definitions of these categories differs from project to project. 

On the Monday call, I proposed the following definitions for these ratings: 
* **Alpha release** There is a documented use case that works. 
* **Beta release** There is evidence -- as determined by the management team -- that the entirety of intended use cases actually work, including documentation of how to accomplish each use case. 
* **Full release** There is evidence -- such as user feedback -- that the use cases are valid and actually work for the community. 

Note that the first two are decisions of a core evaluation team and the last is a community decision. 

In our case there are probably more release categories: 
* **Core**: The app is considered sufficiently important that it is managed by the HydroShare team. 
* **Stable**: There is some assurance and confidence that the app will never be removed. 
* **Recommended** The app is recommended for visualizing and viewing specific resource types. 

Obviously, alpha < beta < full < core < stable < recommended and it is typical for apps to release new features via the same mechanism. It will often be true that the same app has full and beta releases. Eventually, the beta becomes a full release.  

So far, the categories have been only defined in vague terms. Now we need to concentrate on exactly what these categories might mean, in terms of objectively quantifiable metrics. These metrics must be defined in terms of what is reasonable for us to sustain. The next post will clarify that to the extent possible.

**Comment by alvacouch** [comment]
@ChristinaB @dtarb In the previous post, I described what is in essence an ideal strategy. No ideal strategy survives. Any strategy we sustain has to be based upon **human** motivation, and not just software quality. Thus our vetting process for apps has to be **humanly** sustainable. 

Thus, we must design our vetting process so that the human tasks are in some sense self-justifying, and so that the human participants are sufficiently rewarded by participating that they continue participating. Also, the method has to account for the basic fact that the humans available to us are typically not expert programmers, though they may be expert *users*. 

First, let's divide the vetting process into two phases. In the first phase, an app works its way up from alpha to beta to full and -- in that motion -- we use human volunteers outside CUAHSI staff. But once an app becomes "core", the decisions become the purview of CUAHSI, so we won't consider those steps here. 

So, let's think about things that humans who are not expert programmers but are somewhat expert users could test as quality factors about an app. 

Alpha status
--------------
* App is public (open source) on GitHub and accepting issues. 
* App conforms to and advertises one of the acceptable open source licenses. 
* App GitHub site has an acceptable and understandable description of the App's function in the README
* At least one use case is documented. We need to determine acceptable forms of documentation. In this case, "documenting a use case" means that the user is led -- step by step -- to a specific goal, ideally with screenshots. 
* The use case is verified to work. 

Beta status
--------------
All of the conditions of Alpha, plus: 
* All of the functions of the app are documented via use cases. 
* The use cases actually work. 
* There is user documentation -- in some form -- on each control and feature. Acceptable documentation includes pop-up help in the app itself (which may be beyond many app contributors), as well as written documentation. 

We need standards for where documentation should be stored. In GitHub wiki? Somewhere else? 

Full release status
---------------------
All of the conditions of beta, plus: 
* There is evidence of community use according to usage metrics. 
* GitHub issues indicate no serious defects. 

This is just one way we could vet the apps. Vetting of statuses above "full release" is much more technical. But I think this might suffice for promotion from alpha to beta to full.

**Comment by dtarb** [comment]
See #1161.  I suggest the following:

I suggest HydroShare support apps at the various release levels as follows
Recommended.  These appear on the open with button for an associated resource or file type. 
Full release.  These appear on the launch page from apps.hydroshare.org and in apps tab within resource landing pages.

Beta release.  These appear on the launch page from apps.hydroshare.org and in apps tab within resource landing pages.  They should have the word "beta" in their name.

The approval of an app for the three levels above to be by development team, PI and CUAHSI education and outreach support staff after vetting that it meets the requirements outlined above.  I do not think we need to at this stage try to be too prescriptive of exactly what the vetting should involve.  I think it will be apparent to the people doing it whether the app works for general use cases and whether the documentation is sufficient.  The practical metric is thus that the app gets approved if CUAHSI support staff and use it and demo it smoothly.

An app in any other state is treated as alpha by HydroShare.  The creation of an app instance that points to the app and the sharing of that app instance results in its icon it being placed on the web apps tab for a resource.  Users can open these apps by clicking within the web apps tab.  Users can also open alpha apps from the app instance resource.

Users may "activate" apps that are not recommended yet.  Such apps would appear on the open with button for that user as outlined in #1161.

**Comment by ChristinaB** [comment]
@aphelionz 
Hi Mark, the original list of things that UW -BYU are doing to test Apps is a simple list at the top of closed App testing: emerging process to communicate with developers, CUAHSI, and users on Help #1841[https://github.com/hydroshare/hydroshare/issues/1841]
You can see the rest of the conversation above, with a lot of good ideas and strategy.  We, however, are running around in circles with the simple fact that developers need communication in advance that they are expected to write a help page and develop a Printable Demo.  We have been using the Printable Demo as the first simplest use case for testing the App. 

My question for App developers is-
1. How many use cases should be tested to ensure that this App will work for the target audience?  If more than one, then the developer needs to clearly define the uses and audience in the Help page, and the use case examples in multiple printable demos (e.g. Data Rods Explorer has three printable demos @jphuong has developed). 

My question for CUAHSI quality controllers is:
2.   How many human reviewers are required to properly vet an App (and corresponding Help pages and Printable Demos)??  Currently we are gearing up for 4-5 Beta testers and a Google Form. In the future we were hoping for 10-20 volunteer students.  The result of the testing should be an assessment that could be included in a publication on the App written by the App developer.    This outcome may be an incentive to get developers focused on drafting documentations (with UW- CUAHSI editorial support). 

Thanks for talking today!  #developer outreach  #target audience
Christina

**Comment by Lizabrazil** [comment]
I think all of this is captured here: https://docs.google.com/document/d/1qECBlW3TJAm6AEYmThoe0Q8-LDwkXfPiWTLSc901qeE/edit?usp=sharing so i am closing
