### ISSUE TITLE
Raster coverage information not correctly harvested.

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#1844]
For the resource Bear Creek Spatial Reference https://www.hydroshare.org/resource/0601fbe2002b46df8c49c4840fe2294b/ the spatial reference information is incorrectly harvested from the tif file and the result is that coverage information places this in the ocean.

**Comment by dtarb** [comment]
@hyi @zhiyuli I have looked into this problem with @pkdash and in offline testing find the problem occurs in https://github.com/hydroshare/hydroshare/blob/develop/hs_file_types/raster_meta_extract.py in the code in lines 165 to 200

Do any of you know the reason for the logic at lines 178 to 187?

For the raster file in the resource linked above that causes this error, line 165 gets the projection of the file correctly.  Then line 183 constructs ogc_wkt and the resulting string has the correct projection parameters but name "Unknown".  The transform at line 200 then generates an incorrect result.

If I comment out line 183 which results in ogc_wkt not being defined line 184 generates an exception and the exception code at line 187 is executed.  When this is done the transform at line 200 generates the right result.

My question is: Why are we not always getting the original_cs spatial reference from the projection of the input raster dataset as at line 187 rather than parsing through wkt as at lines 183 and 184.

An option for fixing this would be to switch line 187 with lines 183 and 184, which gives priority to line 187 instead of lines 183 and 184.  But I do not know the history of this code, and there are no comments to indicate the basis for this, so before switching I wanted to see if any of you knew what the logic here was.

**Comment by hyi** [comment]
@dtarb I don't know anything about the history of this code, but your suggestion to switch line 187 with lines 183-184 makes sense to me. It seems to me it makes more sense to try to ImportFromWkt of the original projection first to see if a spatial reference can be successfully set, if not, then try to call line 183-184 for another try. Just my two cents, @zhiyuli may know more about this and @gantian127 should be able to explain why she did it the way it is.

**Comment by zhiyuli** [comment]
@dtarb @hyi @pkdash 
from my understanding, the project string extracted on line 165 may be in different formats (esri style, ogc style or other 3rd party styles..) depending on the specific software/tools used to produce this raster file. So to make things easy, Tian uses line 183 to convert this original project string into OGC style projection string before proceeding coordinate system transformation. The error we saw occurred in the conversion of projection string. The possible causes are:
1) the raster itself has a wrong/uncommon/non-standard projection string
2) the function/lib Tian uses for projection string conversion does not recognize this projection string (need a newer version or alternative???)

@shawncrawley (I know you are travelling and may not respond to this quickly).  I remember you had similar "non-standard projection string" issues in GIS app,  any thought/input would be appreciated.

**Comment by dtarb** [comment]
Thanks @zhiyuli.  I've worked on this with @pkdash and we have it figured out.  There will be a PR on this soon.

**Comment by pkdash** [comment]
@dtarb I think you can close this now.
