### ISSUE TITLE
Raster Resource displays incorrectly in HydroShare GIS

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#1845]
The resource https://www.hydroshare.org/resource/0601fbe2002b46df8c49c4840fe2294b/ displays tiled in HydroShare GIS and bound values are not set for symbology editing.

![image](https://cloud.githubusercontent.com/assets/3456833/22758111/7f4b0e1e-ee0a-11e6-8dea-dc68f1356eb5.png)

![image](https://cloud.githubusercontent.com/assets/3456833/22758101/71c1a672-ee0a-11e6-8b41-f458558dae45.png)

**Comment by zhiyuli** [comment]
@dtarb 
Most time this kind of "tiled" issue was due to missing or incorrect Min/Max values.
Geoserver could not use global Min/Max values to render the whole raster, instead it renders each tile separately based on its local Min/Max values.

**Comment by zhiyuli** [comment]
@dtarb 
There is no resource-specific metadata stored in xml file. GIS app parses this xml file to know Min/Max values

![image](https://cloud.githubusercontent.com/assets/10070599/22759962/ac2d4562-ee11-11e6-9be1-d54cbf147b51.png)

**Comment by dtarb** [comment]
Interesting.  That information is in the resource landing page.  So the bug is to fix the resource metadata file.
![image](https://cloud.githubusercontent.com/assets/3456833/22764665/42da1cee-ee29-11e6-8811-c2895a5fbf88.png)

**Comment by dtarb** [comment]
@pkdash @hyi do either of you know why this metadata is missing in the resource metadata xml file.  It used to be there.

**Comment by pkdash** [comment]
@dtarb I will look into it and fix it.

**Comment by dtarb** [comment]
Tested and verified fixed on www for new resources created.  Old resources still may have a problem.  Leaving for users to fix if they encounter, so closing.
