### ISSUE TITLE
Enable automatic group joining

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#1846]
@Lizabrazil asked that for workshops students should be able to join a public group without having to be approved by an owner.  To support this lets add a setting in group details that an owner can set "Automatically approve membership requests" that if checked will result in anyone who requests membership automatically being added.

@alvacouch to the extent that this involves access control can you please work on this.

@mauriel133 to the extent that this involves UI can you please help.

**Comment by alvacouch** [comment]
@dtarb @mauriel133 @Lizabrazil There is no dependence upon whether the group is viewable/public. 

I envision a flag that bypasses the approval process and pre-approves members, something like `approve`.  I would rather not couple this to access privileges -- e.g. public -- because it really has nothing to do with that.  There is a use case for pre-approval of membership in a private group, e.g., for anonymous participation.  

Thus the approve flag would act on the create_group_membership_request to grant that request immediately. 

All we would have to do in the UI is to give the group owner the right to set approve=True or False.

**Comment by pkdash** [comment]
@dtarb Do we need to send email notification to group owners on this auto approval of group membership?

**Comment by pkdash** [comment]
@alvacouch I assume if the group owner has set the flag for the group for auto approval to True, then we directly call the ```share_group_with_user()``` and no need to create membership request object. Who would be the share grantor in this case?

**Comment by alvacouch** [comment]
@pkdash Well, share_group_with_user remains unconditional. I could accomplish this more easily by simply trying to make a request for group membership and having it succeed immediately. This would require no changes anywhere. Thus, we call the same function from the UI and it knows what to do. I think this is easier.

**Comment by pkdash** [comment]
@alvacouch That too works. But still who is the grantor for this membership? Can we just pick any one owner of the group? In this case also we don't want to send emails to group owners for approval. So the view function needs some change. I can work on this and may be able to get this into release 1.9.5.

**Comment by pkdash** [comment]
I have mostly implemented this feature now. Will be creating a PR tomorrow.

**Comment by dtarb** [comment]
Answering @pkdash question quite far up this chain, I think that when someone joins a group where approve is automatic, that it would be good to send the owner an email that says "X joined your HydroShare group Y".  However this is not a critical issue if it will require much additional work.

**Comment by alvacouch** [comment]
@pkdash @dtarb Well, the actual choice of approving owner isn't all that important, as any owner can override any other owner's approvals. I would suggest an arbitrary but consistent choice, e.g., "first owner" as defined in the query order for retrieving owners.

**Comment by alvacouch** [comment]
@pkdash Edited previous answer to show actual code to derive "first" owner.

**Comment by pkdash** [comment]
@alvacouch Will make the above change. Is first owner is useful anywhere else? If its then I will make that as a property

**Comment by dtarb** [comment]
I do not see a need/use for first owner to be a property to use anywhere else.  Much of our design is premised on all owners are equal.

**Comment by pkdash** [comment]
@dtarb and @ChristinaB This work has been deployed on testservices.hydroshare.org for testing. The create/update Group dialog box now has a checkbox (Auto approve membership). If this checkbox is checked, then any Hydroshare user can join the group without the need for the group owner approval.  All group owners will be notified via email indicating who is the user joined a specific group.

**Comment by dtarb** [comment]
+1  I tested and like the functionality.  I'll leave open so @ChristinaB can provide feedback if she wants to, but @pkdash feel free to submit the PR and get it merged once code review is done, and close this when you do this.

**Comment by Lizabrazil** [comment]
Hi,
What is the status on this? I am preparing my activity instructions this week and need to have a final answer on if this will be implemented and how by this week. 

Thanks,
Liza

**Comment by pkdash** [comment]
This has been implemented and will be available in the next release. You can test the functionality at dev.hydroshare.org

**Comment by pkdash** [comment]
This feature has been added. Closing.
