### ISSUE TITLE
App-HydroShare I/O consistency and best practices

### ISSUE THREAD

**Issue by ChristinaB** [hydroshare/hydroshare#1848]
The great thing about Apps is that they interact with HS data, it is currently a bit confusing because they all interact with HydroShare in different ways.  Some are initiated with data from My Resources (e.g. NWM Forecast Viewer button 'Add Watershed') and saved back to HydroShare (e.g. USGS/AHP does this perfectly!).   HydroGIS has a form that uploads data in a form within the App. But, for example, in NWM Forecast viewer, when a user clicks 'Add Watershed', and they want to add a public resource, the user has to leave the App, Discover the resource, add the resource to My Resources, and then come back to the App to interact with it.  Is there a standard prescription for coding and a user navigating this piece of the App-HydroShare database interaction?    At the end of an App user session, there is also a lot of variability on saving work done in an App back to HydroShare.    Rather than focus on one App, I suggest deciding on a App-HydroShare interaction best practice, and then update all the Apps to perform in a consistent way.

**Comment by alvacouch** [comment]
@ChristinaB @aphelionz It seems that we don't have the current machinery for a clear best practice. Yet. The reason that things are confusing is that there isn't a seamless way to bounce back and forth between HydroShare and apps, so I am dubious to recommend that we do that. Solving this problem is going to take a lot of thought. As well, I see no particular reason that an app should not input a resource. In fact, we are thinking that eventually, we would want to empower that. We are a long way from being able to do that.

**Comment by alexlemann** [comment]
Would it make sense to classify what we have now in terms of interactions in a matrix, @ChristinaB to determine if we see some commonalities that could be refined into best practices now that we have a few apps to consider? Getting input from the app developers would be useful as well. Obviously the best practices may change, but this would be a way to codify the emergent practices into recommendations.

These commonalities would not necessarily need to be distilled into a single level of access. For example, using payment APIs (stripe, paypal, etc.) it is common to allow at least three modes of access that I can think of off the top of my head ( 1) interact through a javascript/ajax form injected onto the seller's site but largely not customizable, 2) be redirect from the seller's site to perform the payment on paypal.com and be bounced back to the seller's site at the end of the transaction 3) use the paypal service seamlessly on the seller's site with their own custom payment experience but having the paypal API called behind the scenes completely without the buyer's knowledge). In payment land, each of these types of interactions is separated out as best practices and documentation provided for implementers on the seller side.

And lastly, it would be great if these were consolidated into a message on apps.hydroshare.com and on the resource page that is focused towards end users. EG. App1 can read resources from HS, do work and write new resources, so it's a Read/Write app that has a RW icon. App2 can read data resources run a model with parameters you input on the app with the data but doesn't have the automatic writing back of the resource (yet, they're hoping to implement that next year), so it has a RO icon.

**Comment by alvacouch** [comment]
See related issue #1842 for the reason that some of the things we are doing now are a security nightmare and not best practices. The current way we are doing reads and writes in apps is badly broken. Large files are being transferred via apps that have read access to all of HydroShare, thus bypassing privacy and access control. 

I have proposed a fix. This will become a best practice if implemented, and I cannot recommend the majority of current code as representing best practices other than existing code that uses only hs_restclient.

**Comment by aphelionz** [comment]
@ChristinaB @alvacouch Has this work been discussed enough and encapsulated in other issues? If so, can we close this?

**Comment by cuahsimarko** [comment]
@ChristinaB Can we consider moving this to a design process (e-mails, meetings, google docs, and other tools)?

**Comment by dtarb** [comment]
Stale.
