### ISSUE TITLE
bagit restructuring

### ISSUE THREAD

**Issue by mjstealey** [hydroshare/hydroshare#185]
Checklist (partial)
- [ ] implement flat file storage hierarchy (local)
- [ ] implement flat file storage hierarchy (iRODS)
- [ ] on demand zipping (local)
- [ ] on demand zipping (iRODS)

Restructure the bagit workflow such that all files do not need to be moved from iRODS each time an modification to the resource is made.

**Comment by rayi113** [comment]
iRODS team identified bug in zip support within iRODS.  Entered here on GitHub/iRODS: https://github.com/irods/irods/issues/2613

**Comment by dtarb** [comment]
Not fully resolved for 1.5.1 release.  Still needs metadata updating separate from bag zipping and bag zipping only on demand to improve performance of metadata editing.  Labeled for possible hotfix.

**Comment by hyi** [comment]
@dtarb This follow-up issue has been raised in  #446 and being worked on. Once a proper deployment with sufficient resource for testing large file metadata update specifically for NFIE use cases is complete, we'll open it up for team testing. Once vetted, it will be good to make a hotfix for NFIE.
