### ISSUE TITLE
Some tests are not run by run-tests-jenkins on Jenkins server

### ISSUE THREAD

**Issue by hyi** [hydroshare/hydroshare#1850]
I discovered this issue while working on https://github.com/hydroshare/hydroshare/issues/1838 to delete dangling resources in iRODS in unit tests. I found the test ```hs_core.tests.api.native.test_create_new_version_resource``` tests actually failed after @pkdash's changes to raster resource type as part of file type work, however the test failure was not caught by Jenkins since it gave green check for tests in that file type work PR. When chatting with @mjstealey, we found this test indeed is not included in Jenkin test report here: http://ci.hydroshare.org:8080/job/nightly-build-test/lastCompletedBuild/testReport/. We cannot figure out why some tests are not run by Jenkins as part of coverage test run. @pkdash Can you take a look first to see if you can figure out? If not, we may need to ask @aphelionz or @alexlemann for ideas.

**Comment by pkdash** [comment]
@hyi Should I delete this issue as I created a duplicate issue #1865 ?

**Comment by hyi** [comment]
Closing this as it has been addressed as part of issue #1865
