### ISSUE TITLE
Mezzanine admin interface unable to list pages

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#1856]
The Mezzanine admin interface is not able to list pages on current beta release candidate.  This is presumably due to dependency on geoanalytics code that was removed in the code cleanup.

On beta if you click on pages in the admin interface you get 
![image](https://cloud.githubusercontent.com/assets/3456833/22854082/f096218e-f022-11e6-904e-f11e75147cec.png)

The probematic page appears to be the one named "Alex Lemann" illustrated below.
![image](https://cloud.githubusercontent.com/assets/3456833/22854086/17c84408-f023-11e6-8b5c-e39b63a0128c.png)

One way to resolve this may be just to delete these pages on www prior to the upgrade to current beta release, but I'd like to understand and think through the ramifications of this more fully.  It is unclear how such a resource/page was created in the first place.

**Comment by mjstealey** [comment]
@dtarb - Once the "Alex Lemann" resource was removed, the "Pages" view from the admin panel will now resolve correctly on https://beta.hydroshare.org

**Comment by pkdash** [comment]
@mjstealey I am assuming that resource was related to ga_resource.

**Comment by dtarb** [comment]
Fixed by deleting culprit resources
