### ISSUE TITLE
Register Permissions with the admin site

### ISSUE THREAD

**Issue by mjstealey** [hydroshare/hydroshare#1864]
@all - Thoughts on making the Permissions editable from the admin panel?

Add following to` admin.py`
```python
from django.contrib.auth.models import Permission
admin.site.register(Permission)
```

We have left overs from prior apps lurking in our database. We could expose and control these via the admin panel if that is thought to be a good way to handle this.

For example: **ga_ows** and **ga_resources** permissions remain
<img width="882" alt="screen shot 2017-02-14 at 11 01 13 am" src="https://cloud.githubusercontent.com/assets/5332509/22936999/35611b78-f2a5-11e6-9fdc-d8c9f43da47f.png">

Could be exposed and deleted from admin panel:
![screen shot 2017-02-14 at 11 10 37 am](https://cloud.githubusercontent.com/assets/5332509/22937318/3e0f3416-f2a6-11e6-89f1-94cc50f22833.png)

Downside being ease of removal of needed permissions if not careful.

**Comment by pkdash** [comment]
@mjstealey This editing of permission needs to be done one time right?

**Comment by mjstealey** [comment]
> This editing of permission needs to be done one time right?

@pkdash - In a perfect world, yes.
Should also take into consideration other leftovers like django_docker_processes:
```
 public | django_docker_processes_containeroverrides                      | table | postgres
 public | django_docker_processes_dockerenvvar                            | table | postgres
 public | django_docker_processes_dockerlink                              | table | postgres
 public | django_docker_processes_dockerport                              | table | postgres
 public | django_docker_processes_dockerprocess                           | table | postgres
 public | django_docker_processes_dockerprofile                           | table | postgres
 public | django_docker_processes_dockervolume                            | table | postgres
 public | django_docker_processes_overrideenvvar                          | table | postgres
 public | django_docker_processes_overridelink                            | table | postgres
 public | django_docker_processes_overrideport                            | table | postgres
 public | django_docker_processes_overridevolume                          | table | postgres
```

Like everything else in the admin panel, things can go awry if buttons get pushed too hastily.

**Comment by pkdash** [comment]
@mjstealey I mean once you delete the ga related permissions using the Admin panel we can unregister Permission so that no one has access to it in the admin panel.

**Comment by mjstealey** [comment]
> I mean once you delete the ga related permissions using the Admin panel we can unregister Permission so that no one has access to it in the admin panel

@pkdash - Correct. Could simply comment it out. Or check it into the codebase already commented out, and then uncomment it when needed.

**Comment by pkdash** [comment]
@mjstealey I think it should be possible to control whether the Permission menu appears or not from a parameter settings in settings.py

**Comment by mjstealey** [comment]
> I think it should be possible to control whether the Permission menu appears or not from a parameter settings in settings.py

@pkdash - using beta as a test, have removed any permissions and/or database entries for ga_ows, ga_resources and django_docker_processes. The 2 lines of code were added manually, updates made, and then removed again. If no issues are discovered with beta, the same method can be used for production when the time comes and doesn't involve persisting any code.

**Comment by pkdash** [comment]
@mjstealey Sounds good.

**Comment by mjstealey** [comment]
deployed to production, manually updated, and removed.
