### ISSUE TITLE
Add Message Of The Day MOTD

### ISSUE THREAD

**Issue by rayi113** [hydroshare/hydroshare#1866]
Per @dtarb , @mauriel133 @mjstealey Need a notice on the HydroShare home page (probably a green banner notice in a style similar to what you get when you create a resource) that says (for example):
Planned HydroShare Maintenance.  HydroShare will be offline Friday February 17 from 8 am to 11 am Eastern US Standard time for system wide storage maintenance at the RENCI data center.  We apologize for any inconvenience.

**Comment by mauriel133** [comment]
@pkdash , @hyi could one of you take care of this one? I'll be traveling until Thursday and I'm unavailable in the meantime.

**Comment by pkdash** [comment]
@rayi113 I am not sure about the requirements here. Is this going to be displayed automatically based on some conditions? Or we just have a place holder for the notification in the template that we enable and disable manually as we need?

**Comment by pkdash** [comment]
@mjstealey We can use the text of the ```content``` field of the Home page (which the Admin can edit in the admin interface) to dynamically display as the notification message on the home page.

**Comment by mjstealey** [comment]
> We can use the text of the content field of the Home page (which the Admin can edit in the admin interface) to dynamically display as the notification message on the home page.

@pkdash - The "Home" page in the admin panel is overridden by our present setup and is a placeholder. None of the content there will display to the site.
The only editable fields I've found are from the Theme settings for the information found at the footer regarding contact information, release status, etc.

Please do try this on dev if you think it can be done from the admin panel b/c I don't see how it would be accomplished that way.

**Comment by pkdash** [comment]
@mjstealey I have tested it and it works.

**Comment by hyi** [comment]
@mjstealey @pkdash I have tried to edit content for home page from admin but it did not work for me. However, @mjstealey you may directly edit theme/templates/pages/homepage.html on www to insert the site maintenance message when needed.

**Comment by rayi113** [comment]
@pkdash - Place holder for the notification in the template that we enable and disable manually as we need.

**Comment by pkdash** [comment]
Only editing in admin is not sufficient. The template needs to have code to display it.

**Comment by mjstealey** [comment]
> Only editing in admin is not sufficient. The template needs to have code to display it.

@pkdash - Please implement for demo during today's call

**Comment by hyi** [comment]
@pkdash That makes sense, i.e., display content edited from admin in template page. Either doing that or directly editing homepage.html would work.

**Comment by rayi113** [comment]
@pkdash @hyi what about editing theme/templates/pages/homepage.html  to put a motd under the text superimposed on the 3 rotating images on the landing page.  Would be very visible and easy to turn on and off.

**Comment by rayi113** [comment]
Or is that what @hyi proposed just prior to this comment?

**Comment by hyi** [comment]
@rayi113 That is pretty much what I suggested since I took a look at homepage.html and it appears it is easy just to append a MOTD message there. But @pkdash may investigate to show content field that can be edited from admin panel in homepage.html, which is better in the sense that @mjstealey can just edit the content field without directly appending the message into homepage.html as needed.

**Comment by rayi113** [comment]
@hyi Okay, thanks, sounds good.

**Comment by mjstealey** [comment]
Proposed MOTD on https://beta.hydroshare.org/

![screen shot 2017-02-15 at 11 32 50 am](https://cloud.githubusercontent.com/assets/5332509/22984199/9a3502bc-f372-11e6-9ddb-e61f9215893d.png)

**Comment by pkdash** [comment]
@mjstealey I assume you tested turning this message off.

**Comment by rayi113** [comment]
@mjstealey Can this also display when a user is logged in since that status is cached for returning existing users?  I.e. There is the potential for a loggged-in HydroShare user to miss this message.

**Comment by pkdash** [comment]
@rayi113 Should be possible.

**Comment by mjstealey** [comment]
Message has been applied to https://www.hydroshare.org

**Comment by pkdash** [comment]
We can also add the feature where one can specify start date/time and end date/time during which the maintenance message should be displayed. Not sure how that would work with various time zones though.

**Comment by mjstealey** [comment]
Implemented on production as disposable code
