### ISSUE TITLE
MOTD - message of the day

### ISSUE THREAD

**Issue by mjstealey** [hydroshare/hydroshare#1876]
The MOTD should have the following characteristics.
1. Be a user closable sub-window that appears within the main page of the HydroShare site
2. Message content settable from the admin panel with
    - Message content
    - Enable / Disable "switch"
    - Date range to be displayed

Existing implementation is insufficient as it involves writing directly to the `homepage.html` file to enable/disable showing the message on the main page

**Comment by pkdash** [comment]
@mjstealey 

> Existing implementation is insufficient as it involves writing directly to the homepage.html file to enable/disable showing the message on the main page

Does this mean we don't want the message to be part of the homepage.html?

**Comment by mjstealey** [comment]
> Does this mean we don't want the message to be part of the homepage.html?

@pkdash - No, it means that whatever code winds up in `homepage.html` should enable/disable the message based on a value set by the user in the admin panel.

Current implementation requires commenting out the code in `homepage.html` to disable the display.

**Comment by pkdash** [comment]
@mjstealey 

> Current implementation requires commenting out the code in homepage.html to disable the display.

There is no need to comment out the template code. If you edit the Home page content to contain only the following text, it should not display that message.

Planned HydroShare Maintenance.

**Comment by mjstealey** [comment]
So our maintenance message can say anything other than **Planned HydroShare Maintenance.**
This seems kind of arbitrary.

A more formalized implementation would be preferred, will use the hack until that time.
As an aside the code for this was manually pasted onto www and is not in the repo.

**Comment by pkdash** [comment]
Initially I was trying to see if there is any text in that field then display it otherwise not. However, the content field does not allow it to be blank. That is the reason I had to use the above logic given the time I had yesterday to make it work.  

We can easily add a new model Boolean field to the HomePage model and use that to turn on/off the message. That would obviously require migration file to be generated. This needs to be done in a formal PR.

**Comment by pkdash** [comment]
@mjstealey I can also try having start date/time and end date/time settings during which the message will be displayed. I am not sure what that would to different time zone though.

**Comment by mjstealey** [comment]
@hyi, @pkdash - Maintenance is only one aspect of MOTD, but it's use cases go beyond that.
1. Maintenance: Hard to pin down an exact time, so leaving it on until it's manually switched off via some boolean is valid
2. Special Events:
   a. By the day: Conference, workshop, other event taking place at a daily granularity
   b. By the hour: Webinar, lecture, other event taking place at an hourly granularity
3. Advertisement: Highlighting a special event, software release, publication, or other entity for a known duration of time. i.e. New Web App available to do XYZ

May also be useful to define the background color to the message as red may not always be the best choice.
- Maintenance = Red
- Special Event or Advertisement = Green

**Comment by pkdash** [comment]
@mjstealey Do we then use a Boolean field to turn on/off message? The green/red message can be done with an addition Boolean attribute 'Maintenance' .

**Comment by mauriel133** [comment]
@pkdash, let me know if/when you need my help on the front end of this.

**Comment by pkdash** [comment]
@mauriel133 Thanks. At this point I am not sure about the requirements of this feature. There has been some talk about a full blown messaging system. That's why I stopped working on this PR.

**Comment by pkdash** [comment]
@mjstealey Should you be closing this issue?

**Comment by pkdash** [comment]
@mjstealey Can we close this?

**Comment by pkdash** [comment]
@mjstealey I think this can be closed.

**Comment by mjstealey** [comment]
closing
