### ISSUE TITLE
Release 1.9.5: Coverage map is blank on resources

### ISSUE THREAD

**Issue by horsburgh** [hydroshare/hydroshare#1879]
In the newest release on WWW, the coverage map has been pulled out of the coverage metadata tab, but it's blank on the page. Tested just now on www in Chrome on my Mac.

![image](https://cloud.githubusercontent.com/assets/3485902/23079242/4c8e4a9e-f509-11e6-9616-1a2c69971ea6.png)

**Comment by pkdash** [comment]
@horsburgh Seems to be working on other browsers (FireFox and MS Edge).

**Comment by mauriel133** [comment]
I was unable to reproduce this error. @pkdash, could you test on a Mac computer and report the error back to me?

**Comment by mjstealey** [comment]
Mac, Chrome, Little Bear resource:

![screen shot 2017-02-17 at 7 11 28 pm](https://cloud.githubusercontent.com/assets/5332509/23087786/07dbaa90-f545-11e6-8863-3dcff6ac5747.png)

@horsburgh - stale browser cache maybe?

**Comment by horsburgh** [comment]
Well... It's working now. I didn't specifically clear my cache, but let's chalk it up to that. Crisis averted!
