### ISSUE TITLE
Reference Time Series: Error on Create Resource

### ISSUE THREAD

**Issue by horsburgh** [hydroshare/hydroshare#188]
I tried to create a referenced time series on dev.hydroshare.org.  I used the following URL:

http://data.iutahepscor.org/RedButteCreekWOF/REST/waterml_1_1.svc/datavalues?location=iutah:RB_ARBR_C&variable=iutah:AirTemp_Avg/methodCode=1/sourceCode=1/qualityControlLevelCode=0&startDate=&endDate=

I clicked the button to validate the REST URL and preview and it retrieves the data and creates a plot.  But, when I click the "Create Resource" button, it throws an error.

**Comment by dtarb** [comment]
I have been able to create reference time series, but the URL above does not work for me.  @horsburgh are sure the above URL is correct.  Closing this issue for 1.4.0 release but refts will need ongoing improvement.
