### ISSUE TITLE
Slack Channel to expand Developer, User, and Education Outreach

### ISSUE THREAD

**Issue by ChristinaB** [hydroshare/hydroshare#1885]
@aphelionz 
I love the idea of a Slack Channel =    hydroshare.slack.com  

Are you thinking one thread? Or multiple?
The current groups I propose we start with are:
Developers (managed by you)
Education (managed by Liza)
Users (managed by Jon Pollack - I am on the CUAHSI user's committee so I would propose we take some conversations there, but it depends on the committee, and if we decide to expand to a larger user group beyond the 6-10 person committee) 

@jphuong and I and other UW folks would be able to support on technical issues and questions as needed, but it is probably best to have CUAHSI officially manage the channel. 

Groups found under the Collaborate Dashboard may or may not already have their own channel, if so, is there a way to integrate?

We are redesigning the front page footer and could send people to these channels as an alternative to emails, if they wanted to search by forum. 

We can talk later about integration with HydroShare, but not too much later...  when we get news of the next round of funding we can bring @horsburgh back into the conversation.   Currently, we can email people from the profile user page, but there is not easy communication pathway within HydroShare at the moment.  This will be needed in the social focus of the next stage. My view is if we can use Slack and **not** reinvent the wheel, it would be great.  

Let's start using it stand alone and see how far we get and if it helps with communication beyond the HydroShare inner circle.   

C

**Comment by ChristinaB** [comment]
On the backend, we should continue using Trello for collaborative task management and Github for issue management with developers.

**Comment by aphelionz** [comment]
@ChristinaB I created a slack channel https://hydroshare.slack.com, and I also registered the #hydroshare channel on freenode.irc.net so Non-Slack developer types can chat with me.

Any member of the hydroshare channel can invite people, so have at it!

**Comment by horsburgh** [comment]
@ChristinaB - my developer group uses Slack daily for our messaging within our group. It works great for that.  And, I can recommend it to the HydroShare developers group.

But, I'm not sure I would recommend it for user support (at least for the user facing side). My main concern is that it's one more thing that users have to figure out - "what is this Slack thing?...I just want to report a bug..." But, maybe it could work, and there's even a customer service app for slack: https://get.slaask.com/ (disclaimer - just googled this 5 seconds ago)

But, there's also a number of articles like this out there: https://www.gosquared.com/blog/customer-service-doesnt-belong-in-slack

Whatever we choose to do, it needs to be deliberate and it needs to work for our users. HydroShare Groups integration with Slack might also be cool.

**Comment by ChristinaB** [comment]
For context: Here is a Footer design Google Doc [https://docs.google.com/document/d/1dkoZh6GgkeftP1gaNxbJA7g1PQBoDTXOustVKvYH6Tg/edit?usp=sharing]  where need to keep talking about Customer Service aspects of outreach and user interaction because we need to make sure we have the backend processes to support the 'Contact' links on the footer.    

I don't think  hydroshare.slack.com was proposed directly for CUAHSI-user HydroShare customer service, but as a forum type environment for groups of developers, educators, researchers, etc.   We will talk about it in the Wednesday E&O meeting and take feedback on it from developers in that follow up meeting as well.

**Comment by ChristinaB** [comment]
I think if we want to go down the road of having users report a bug, we would do better to add on a LiveChat and keep that funded.  We sure aren't there, quite  yet...

**Comment by aphelionz** [comment]
@ChristinaB Ok to close this now that we've got a handful of poeple on the channel? We can discuss tomorrow.
