### ISSUE TITLE
Coverage issue after updating to the new interface

### ISSUE THREAD

**Issue by mohamedmorsy** [hydroshare/hydroshare#1889]
I have a paper I am working on that includes a screenshot of the coverage landing page in the edit mode. I used the old interface for the figure when I submitted it. Now during reviewing the paper, I decided to update the figure with the new interface. I found the following for [this resource type](https://www.hydroshare.org/resource/12d195906f2c41918cb24e11a5c3ab60/): 

In the old figure, the start and end dates were 2012-06-01 and 2013-06-01 respectively. (see below)

![image](https://cloud.githubusercontent.com/assets/5543781/23176965/335a683c-f833-11e6-9b9a-85ea08896275.png)

After deploying the new coverage interface and on the same resource landing page, I can see that these dates were changed to 04/31/2012 and 04/31/2013 keeping in consideration that the last time I modified this resource was on Dec. 4, 2015. (see below)

![image](https://cloud.githubusercontent.com/assets/5543781/23176994/444cd60c-f833-11e6-9ecd-4aecaeb3f734.png)

Also when I go to the edit mode landing page I get different dates (see below)

![image](https://cloud.githubusercontent.com/assets/5543781/23177006/4df62dca-f833-11e6-865d-991a546b0c95.png)

**Comment by mjstealey** [comment]
@mohamedmorsy - Neither set of dates looks to match up with the files themselves... Is that expected?

From "RBw simulation.rpt"
```
 ****************
  Analysis Options
  ****************
  Flow Units ............... CMS
  Process Models:
    Rainfall/Runoff ........ YES
    Snowmelt ............... NO
    Groundwater ............ NO
    Flow Routing ........... YES
    Ponding Allowed ........ NO
    Water Quality .......... NO
  Infiltration Method ...... CURVE_NUMBER
  Flow Routing Method ...... DYNWAVE
  Starting Date ............ FEB-04-2013 00:00:00
  Ending Date .............. FEB-06-2013 00:00:00
  Antecedent Dry Days ...... 0.0
  Report Time Step ......... 00:15:00
  Wet Time Step ............ 00:01:00
  Dry Time Step ............ 00:01:00
  Routing Time Step ........ 30.00 sec
```

From "RBw simulation.inp"
```
[OPTIONS]
FLOW_UNITS           CMS
INFILTRATION         CURVE_NUMBER
FLOW_ROUTING         DYNWAVE
START_DATE           02/04/2013
START_TIME           00:00:00
REPORT_START_DATE    02/04/2013
REPORT_START_TIME    00:00:00
END_DATE             02/06/2013
END_TIME             00:00:00
SWEEP_START          01/01
SWEEP_END            12/31
DRY_DAYS             0
REPORT_STEP          00:15:00
WET_STEP             00:01:00
DRY_STEP             00:01:00
ROUTING_STEP         0:00:30 
ALLOW_PONDING        NO
INERTIAL_DAMPING     PARTIAL
VARIABLE_STEP        0.75
LENGTHENING_STEP     0
MIN_SURFAREA         0
NORMAL_FLOW_LIMITED  BOTH
SKIP_STEADY_STATE    NO
FORCE_MAIN_EQUATION  H-W
LINK_OFFSETS         DEPTH
MIN_SLOPE            0
```

**Comment by mohamedmorsy** [comment]
@mjstealey Yes, there are several simulations based on the storm event you can choose from included in the inp file. Based on the chosen storm event these dates changed, but still these files cover the start and end date I mentioned. The one you mentioned is for storm event started on FEB-04-2013 and ended on FEB-06-2013. Also here, we do not do automatic extraction for the dates.

**Comment by mauriel133** [comment]
I think this has to do with the front end sending the dates in a different format string that the back end expects. Right now we display the dates using "mm/dd/yyyy" and send it like so. I like that as display date because it is widely common. I will try to find a way to keep displaying it like that, but send a string formatted as "yyyy/mm/dd" in the submission.

**Comment by mjstealey** [comment]
> Also here, we do not do automatic extraction for the dates

Ah, that is the key to the issue here then. So it's not an auto-extraction error, but rather your manually entered data was somehow changed without you doing it.

The most recent edit made to the resource was done by the HydroShare Admin account. This implies there was some type of migration done to this resource to migrate versions/formats and that may have reordered something improperly.

**Comment by mauriel133** [comment]
There was an error in the front end causing wrong values for the dates. I just pushed a PR with the fix: https://github.com/hydroshare/hydroshare/pull/1890

**Comment by aphelionz** [comment]
I think we can close this now

**Comment by mauriel133** [comment]
This fix has been deployed to www.

**Comment by pkdash** [comment]
@mohamedmorsy Can you close this?
