### ISSUE TITLE
DataOne reference resource

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#1892]
@dtarb @horsburgh @martinseul At the CUAHSI management review I had a great idea. We can't afford to store everything people want to publish but we have --  by far -- the easiest editing for metadata and we store everything in DataOne compliant form, suitable for publication on any DataOne node. We should be able to reference and index a DataOne bag. Then it won't matter where it is stored. Thus, people can use HydroShare to create bags and publish them in their own University libraries. This is totally free to both us and them; paid for by overhead...! If we make this seamless by use of a DataOne client, we'll have a simple and free publication option for many academics that is blessed by their own institutions!

**Comment by cuahsimarko** [comment]
Per conversation with Alva not needed
