### ISSUE TITLE
Conflicting migrations detected - Tests will not run in this state

### ISSUE THREAD

**Issue by mjstealey** [hydroshare/hydroshare#1899]
@alvacouch, @pkdash, @hyi - Looks like we managed to put conflicting migrations into the develop branch.

Have not checked migrations since the 1.9.5 release. Generally the `makemigrations` call is not part of our scripts and is only done at release time. The `--merge` flag as suggested below has not been part of our process at all to this point.

Reference: 
```
CommandError: Conflicting migrations detected (0019_manual_populate_provenance, 0017_groupaccess_auto_approve in hs_access_control).
To fix them run 'python manage.py makemigrations --merge'
```

**Comment by hyi** [comment]
@alvacouch @pkdash @mjstealey It appears to me that this may be caused by two PRs that both involve migrations, and after one was merged, the other one rebased with develop, but did not run ```makemigrations --merge``` hence causes this conflicting migrations. @pkdash can you make a PR to fix this migration issue?

**Comment by alvacouch** [comment]
I am somewhat confused because I cannot reproduce the error on develop. 
When I try to makemigrations --merge,  it reports there is nothing to merge. 
Will check dependencies instead.

**Comment by mjstealey** [comment]
merged and tests are running again
