### ISSUE TITLE
Tool for Defining Spatial Coverage

### ISSUE THREAD

**Issue by Castronova** [hydroshare/hydroshare#190]
Rather than manually filling out bounding box fields, provide a few functions to automate this process.

1. A map where the user can draw a bounding box, or select a point of interest
2. The ability to search for locations would enable users to select a city nearby their site
3. The ability to load a shape file or csv file and parse the spatial coverage
4. An interactive map that enables users to select HUCs as the coverage

**Comment by horsburgh** [comment]
@mauriel133 - I think we should start with number 1 in @Castronova 's list above.  I would base it on a Google Map.  Given other priorities for Release 1.6.0, I'm not sure this one should be included.  And, I'm not sure we should do all 4 of Tony's suggestions (at least not yet).

**Comment by mauriel133** [comment]
Alright, I think Google Map is the right approach too.

**Comment by Castronova** [comment]
@horsburgh I agree, functions 2-4 are more of a wish list.

**Comment by selimnairb** [comment]
[WGS84 bounds](http://spatialreference.org/ref/epsg/wgs-84/)

**Comment by gantian127** [comment]
@Castronova would you please close this issue if you think it is fixed? Thanks
