### ISSUE TITLE
Onclick Refactor

### ISSUE THREAD

**Issue by aphelionz** [hydroshare/hydroshare#1900]
Mauriel and I will be spliiting this up. The goal here is to replace code like this:

`<a href="#" onclick="inlineFunctionCall('arg1', 'arg2')">click here</a>`

with: 

```
<a href="#" id="newButtonID">click here</a>
<script>
  $('#newButtonID").on('click', function() {
    inlineFunctionCall('arg1', 'arg2');
  });
</script>
```

Function calls with arguments can be handled via `data-*` attributes:

```
<a href="#" data-whatever="blah" id="newButtonID">click here</a>
<script>
  $('#newButtonID").on('click', function() {
   var arg1 = $(this).data('whatever');
    inlineFunctionCall(arg1);
  });
</script>
```

- [x] ./hs_modflow_modelinstance/forms.py
- [x] ./hs_app_netCDF/forms.py
- [x] ./hs_app_netCDF/page_processors.py
- [x] ./hydroshare/static/mezzanine/tinymce/plugins/example/dialog.html
- [x] ./hs_collection_resource/templates/pages/collectionresource.html
- [x] ./hs_geo_raster_resource/forms.py
- [x] ./hs_file_types/models/generic.py
- [x] ./hs_file_types/models/base.py
- [x] ./hs_file_types/models/raster.py
- [x] ./ref_ts/templates/pages/create-ref-time-series.html
- [x] ./theme/templates/accounts/profile.html
- [x] ./theme/templates/base.html
- [x] ./theme/templates/pages/group.html
- [x] ./theme/templates/resource-landing-page/citation.html
- [x] ./theme/templates/resource-landing-page/abstract.html
- [x] ./theme/templates/resource-landing-page/coverage.html
- [x] ./theme/templates/resource-landing-page/modals.html
- [x] ./theme/templates/resource-landing-page/title-section.html
- [x] ./hs_app_timeseries/forms.py
- [x] ./hs_core/templates/503.html
- [x] ./hs_core/templates/404.html
- [x] ./hs_core/templates/search/search.html
- [x] ./hs_core/templates/500.html
- [x] ./hs_core/templates/pages/genericresource.html
- [x] ./hs_core/templates/400.html
- [x] ./hs_core/forms.py

**Update** Mauriel is nearly done with the inline JS refactor. Work for Mark remaining:

- [ ] removing crsf_token in base.html
- [ ] data: urls

**Comment by mauriel133** [comment]
All items have been checked. We will open new tickets for future issues.
