### ISSUE TITLE
Add Profile requirements to HydroShare new user steps

### ISSUE THREAD

**Issue by ChristinaB** [hydroshare/hydroshare#1915]
Currently, new HydroShare users are only required to put their first and last name.   This leads to what I call the 'Empty Profile Problem' which makes social functions or use tracking severely limiting (see use tracking reporting by @Castronova ).  

The Education & Outreach group has come to a consensus that adding the requirement to fill 'Institution' and 'Title' adds sufficient benefits without significantly slowing down the workshop and introduction process for new users.  

Thanks!!

**Comment by ChristinaB** [comment]
We also need to think about using controlled lists for the Title and Institution so it is more easy for Kibana and @Castronova  to do useful work with the Profile info. 

Would also be nice to have an option where someone signing up at an event, or by referral , could volunteer the information, so that @Castronova can track where the users came from.

Thanks!
C

**Comment by pkdash** [comment]
@aphelionz Should @mauriel133 work on this?

**Comment by ChristinaB** [comment]
Hi All, 
What is the timeline to update this feature?  Thanks!
Christina

**Comment by ChristinaB** [comment]
Thanks Mauriel!!  Let me know if/when you want help with testing.
C

**Comment by mauriel133** [comment]
@ChristinaB, do you have curated lists for Title and Organization or are these going to be self updating (by providing the option to input new values and adding to the list)?

**Comment by mauriel133** [comment]
The tracking for organization had already been implemented here:
https://github.com/hydroshare/hydroshare/pull/1303/commits/10738fa5c5a8fbeca2ed5d8c9325bd12f90d8f45

@jbradberry, it looks like this work didn't make it into development. Is it in some other branch?

**Comment by jbradberry** [comment]
@mauriel133 According to https://github.com/hydroshare/hydroshare/pull/1303#issuecomment-270412686 , this work was copied elsewhere and merged.  However, I haven't been on this project for months now, so I have no first-hand knowledge that this is the case.

**Comment by mauriel133** [comment]
@pkdash, it looks like this work (https://github.com/hydroshare/hydroshare/pull/1303) didn't make it into the development branch. Who would be a good candidate to bring these back end changes into our current development branch?

**Comment by pkdash** [comment]
@mauriel133 I guess @aphelionz or @hyi can help on this. Is this functionality needed for release 1.10? The RC for release 1.10 supposed to come out on Wednesday.

**Comment by mauriel133** [comment]
@pkdash,

Yes, this is needed for release 1.10. The work that was done in that PR implements the Organization field as a self-updating autocomplete list. It also implement other important constraints on tracked fields.

**Comment by ChristinaB** [comment]
Thanks for your work on this @Maurier !!

**Comment by ChristinaB** [comment]
I tested this on beta and it is not implemented.  Any chance we can sneak it in 1.10?

**Comment by dtarb** [comment]
see prt #1303

**Comment by aphelionz** [comment]
@rayi113 @ChristinaB @dtarb 

Do we want highest level of education as a required field here or will we nag them about it with the notification... or will we do nothing? let me know.

**Comment by rayi113** [comment]
Required would be great as this information is used for reporting purposes, however if we do require this we may additionally need an option like "Prefer not to disclose" in addition to how these options are usually stated.  Defer to @dtarb  for ultimate decision on this.

**Comment by horsburgh** [comment]
@aphelionz - can you check in with @Maurier ? He can work on the front end changes needed for adding education level to the profile, but he wanted to know who could help him out with the back end stuff.

**Comment by aphelionz** [comment]
@horsburgh @Maurier 

I was able to cherry pick the commit you mentioned to get the organizations field. I'm planning on doing the rest, is that ok?

**Comment by horsburgh** [comment]
Fine with me. @Maurier ?

**Comment by Maurier** [comment]
Yes, sounds good.

**Comment by horsburgh** [comment]
Removing @Maurier from this one since it looks like @aphelionz is taking care of it.

**Comment by aphelionz** [comment]
I believe this ticket has been satisfied. Please re-open or make a new ticket if that is not the case

cc @horsburgh @ChristinaB
