### ISSUE TITLE
Disable Right-Click Download Option HydroShare Resource files > 1GB

### ISSUE THREAD

**Issue by rayi113** [hydroshare/hydroshare#1917]
A HydroShare user should not be offered the option to right-click "Download" a HydroShare resource file > 1GB via http, or the selecting that option for a file > 1GB via http should immediately resolve to a message pointing to the [Help ](https://pages.hydroshare.org/creating-and-managing-resources/uploading-large-files-into-hydroshare/) page on how alternately to do this.

Currently, right-clicking "Download" on a HydroShare resource file > 1GB says "Waiting for www.hydroshare.org..." but then disappears without successful action or status.

**Comment by aphelionz** [comment]
Proposal. Make this display a message that says "your download will be emailed to you when its ready."

Then send an email with a link to the user that requested it

**Comment by mauriel133** [comment]
The original suggestion was implemented here: https://github.com/hydroshare/hydroshare/pull/1925 and it has been merged to www. Please verify.

@aphelionz, I think your idea is good. We need input from @dtarb and @horsburgh to see if we can push it forward and assign it a priority.

**Comment by rayi113** [comment]
When testing on 1.9.6, I'm not see the #1925 behavior; this is what results for this resource: https://www.hydroshare.org/resource/23b0fbef0a1b4c4c8f128ef5ddeb7287/ 

![hs_error](https://cloud.githubusercontent.com/assets/2846017/24216193/b9a5bba4-0f11-11e7-84f7-365e032afecf.png)

**Comment by mauriel133** [comment]
@rayi113, I can't replicate this issue. Could you double check by clearing the cache?

![image](https://cloud.githubusercontent.com/assets/2448568/24216921/9da82756-0f03-11e7-9487-77da708412cb.png)

**Comment by hyi** [comment]
@rayi113 I also did a quick test on this resource, and the download is disabled from the right click popup menu, so I am not able to download this file. I used Chrome browser. Not sure how you get that "Failed-forbidden' to happen.

**Comment by rayi113** [comment]
Yes, this is a browser cache issue, it now works successfully on both Chrome and Firefox.  Thanks very much.  Closing issue.
