### ISSUE TITLE
iRODS federation for expanded storage 

### ISSUE THREAD

**Issue by hyi** [hydroshare/hydroshare#1918]
Make sure the capability for institutions to add their own storage capacity and to federate with HydroShare using iRODS works as designed. Document this functionality so that third party institutions can easily follow along to add their own storage capacity as part of HydroShare resource storage.

**Comment by hyi** [comment]
@dtarb @alvacouch @rayi113 @mjstealey I have tested with NFIE zone on www as a test case for third party external federated zone since NFIE zone is federated with www. Everything works as expected by design. I will do the same test after release 1.10 is deployed just to make sure external federation still works as expected with our new file system implementation code base. Another related to-do item is to add help page for this third-party expanded storage functionality. @alvacouch I think you are the best person to draft the help page for this given your CUAHSI role and your understanding to the codebase. You can refer to descriptions in our paper if needed since the codebase behaves exactly as we described in the paper, and works as expected based on my testing so far. Let me know what you think.

**Comment by hyi** [comment]
@dtarb @alvacouch @rayi113 @mjstealey I believe this works as expected. See my comments above for details. I am closing this issue, but feel free to reopen it if you find any issues related to this.

**Comment by dtarb** [comment]
Thanks.  Can you point me to the document that describes "this functionality so that third party institutions can easily follow along to add their own storage capacity as part of HydroShare resource storage." as indicated in the issue description.
