### ISSUE TITLE
Bug in the temporal coverage metadata

### ISSUE THREAD

**Issue by mohamedmorsy** [hydroshare/hydroshare#192]
During testing the model instance resource parsed metadata which is included in the downloaded parcel (resourcemetadata.xml), I found that the temporal coverage metadata gives the wrong dates which are constant for any created resource even if this resource is generic resource or model instance resource. The value of the temporal coverage is <rdf:value>start=2015-01-01T00:00:00+00:00; end=2015-01-01T00:00:00+00:00; scheme=W3C-DTF</rdf:value> if the input dates in year 2015 while it is <rdf:value>start=2014-01-01T00:00:00+00:00; end=2015-01-01T00:00:00+00:00; scheme=W3C-DTF</rdf:value> if the input dates in years 2014 and 2015 while it appears correct on the website. I tested that on my local machine and also on the dev.hydroshare.org website. Here are two screen shots for more illustration:

![image](https://cloud.githubusercontent.com/assets/5543781/6473414/3c99db84-c1c7-11e4-91b9-71f5b27da063.png)

![image](https://cloud.githubusercontent.com/assets/5543781/6473423/4cd87dc0-c1c7-11e4-9129-8a85fa859712.png)

**Comment by pkdash** [comment]
Here how it looks after the fix:
![image](https://cloud.githubusercontent.com/assets/2523434/9016237/9890011c-378c-11e5-88b2-b7e65b53f606.png)

![image](https://cloud.githubusercontent.com/assets/2523434/9016239/a5c8e6aa-378c-11e5-9480-cb2441ab8e98.png)

**Comment by mohamedmorsy** [comment]
Pabitra @pkdash  fixed this issue. Now, the temporal coverage metadata element works as expected on dev.hydroshare.org.
