### ISSUE TITLE
Metadata Editing for NetCDF Resource Type

### ISSUE THREAD

**Issue by gantian127** [hydroshare/hydroshare#1924]
This function will write the resource science metadata stored in Django to the netCDF file in the NetCDF resource.

**Comment by dtarb** [comment]
@gantian127 please tell @Lizabrazil what has changed on the UI for this issue.  She needs to change help documentation and screen shots to reflect changes in functionality.  Help documentation is prepared in google docs in https://drive.google.com/drive/u/1/folders/0B8FGrdqHDtsDLTdjTWswdmZvWW8.  @Lizabrazil can point you to specific documents that need updating.  I did not see a document for multidimensional in resource types, but there is a document for composite.  There is a help page for multidimensional, that can serve as a starting point https://pages.hydroshare.org/hydroshare-resource-types/multidimensional-netcdf/, but this is very short.

**Comment by gantian127** [comment]
@dtarb @Lizabrazil I will prepare the screen shots and the documentation. It will be great if I could be pointed to the specific documents for updating. Thanks.

**Comment by Lizabrazil** [comment]
Hi Tian, I'm not sure there is much on the help page for Multidimensional yet. Here is the link i know of: https://pages.hydroshare.org/hydroshare-resource-types/multidimensional-netcdf/

**Comment by gantian127** [comment]
@dtarb @Lizabrazil I created a new help document for Multidimensional (NetCDF) resource. It can be accessed from HydroShare google drive folder: SystemDesign -> User Experience -> HELP content development -> Resource Types.  The section of " Update Metadata in the NetCDF File " in the document can be used as the content for 1.10 release documentation. If I need to provide other information, please let me know. Thanks,
@ChristinaB would you please assign a proof reader of this new help document and update the help page content for the Multidimensional (NetCDF) resource ? Thanks

**Comment by dtarb** [comment]
OK
