### ISSUE TITLE
Composite resource problems RC 1.9.6

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#1928]
In testing for RC 1.9.6 I found the following problems (to fix before deploy) and quirks (not essential to address before deploy).

Problems

 - [x] Dragging a file into a folder results in an error
 - [x] If I have a zip file containing a tif file and attempt to set geo raster file type, I get the error below.  The tif file is OK as verified by setting the raster file after unzipping. [3/18/17 edit.  This is OK as an as yet unsupported use case.  This works if the zip file has a vrt file, but should also be made to work if it only has a tif file as a future enhancement.  @gantian127 please note as additional feature to implement.]

Quirks
 - [x] Unzip is only enabled upon right click
 - [x] Setting of a file type should create the file type in the current folder, not root level folder as it does now

The resource that illustrates these errors is https://beta.hydroshare.org/resource/074b845a667049719f96f34b660be906/

Error from dragging a file already in a resource into a folder
![image](https://cloud.githubusercontent.com/assets/3456833/23823758/74aed588-0626-11e7-9e40-461f6f71d4e7.png)

Error from setting geo raster on zip file containing tif file even when tif file is correct.
![image](https://cloud.githubusercontent.com/assets/3456833/23824032/6b59986e-062c-11e7-82ab-27d0dac59e61.png)

Unzip enabling illustration
![image](https://cloud.githubusercontent.com/assets/3456833/23823963/101d7322-062b-11e7-805c-b56495c50466.png)

**Comment by pkdash** [comment]
@dtarb 

>  Dragging a file into a folder results in an error

This problem is not specific to composite resource. It will happen with any resource type where such action is enabled. This is a bug with the recent work on REST API.

@aphelionz Would you look into it? The error comes as attribute error for accessing ```request.data``` ( https://github.com/hydroshare/hydroshare/blob/develop/hs_core/views/resource_folder_hierarchy.py#L363). There may be other places where ```request.data``` may have used to handle both rest call and UI call.

**Comment by pkdash** [comment]
@dtarb 

>  If I have a zip file containing a tif file and attempt to set geo raster file type, I get the error below. The tif file is OK as verified by setting the raster file after unzipping

It seems the validation of the vrt file is failing. @gantian127 can you comment on this? (https://github.com/hydroshare/hydroshare/blob/develop/hs_file_types/models/raster.py#L411)

**Comment by pkdash** [comment]
@dtarb 

> Quirks
 Unzip is only enabled upon right click
 Setting of a file type should create the file type in the current folder, not root level folder as it does now

Both these will be fixed as part of the NetCDF PR.

**Comment by mjstealey** [comment]
@aphelionz, @pkdash - Has this been verified on www?

**Comment by pkdash** [comment]
@mjstealey The following seems to work on www:

- Unzip is enabled upon selection of zip file
- Dragging a file into a folder works without the above error

Setting a file type creates a new folder in the current folder on beta but not on www. I am not sure why I am seeing this difference.

**Comment by pkdash** [comment]
@mjstealey Ignore my comment related to file type setting and new folder creation. It works on www.

**Comment by pkdash** [comment]
@dtarb Can you test and close this issue?

**Comment by dtarb** [comment]
The last check box at the top is still not done.  Setting of a file type should create the file type in the current folder, not root level folder as it does now on www.

**Comment by dtarb** [comment]
Done.  Close if tests out on next candidate release.

**Comment by dtarb** [comment]
OK
