### ISSUE TITLE
Change semantics of replicate to iRODS to copy

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#1929]
Please change Replicate to Copy at locations indicated below.

![image](https://cloud.githubusercontent.com/assets/3456833/23824222/9627623a-062f-11e7-8044-c13128b9c525.png)

**Comment by pkdash** [comment]
@mauriel133 Can make this small fix?

**Comment by mauriel133** [comment]
Yes, I'll make this change.

**Comment by mauriel133** [comment]
Should the change also be made to this message?

> File larger than 1GB cannot be downloaded directly via HTTP. Please create an iRODS account in your iRODS user zone from your profile page if you have not done so already, and **replicate** the resource...

**Comment by dtarb** [comment]
OK
