### ISSUE TITLE
Error in Creating Referenced Time Series

### ISSUE THREAD

**Issue by jirikadlec2** [hydroshare/hydroshare#193]
The following REST URL's cause an error:
http://hydrodata.info/chmi-h/cuahsi_1_1.asmx/GetValues?location=CHMI-H:89&variable=CHMI-H:PRUTOK&startDate=2015-01-01&endDate=2015-03-01&authToken=

http://hydrodata.info/chmi-h/cuahsi_1_1.asmx/GetValuesObject?location=CHMI-H:89&variable=CHMI-H:PRUTOK&startDate=2015-01-01&endDate=2015-03-01&authToken=

**Comment by horsburgh** [comment]
I suspect this may be the same as #188

**Comment by dtarb** [comment]
I was able to create a reference time series resource.
