### ISSUE TITLE
iRODS connectivity enhancements

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#1930]
I suggest the following 

- [ ] Enable copying of individual files from a resource to an iRODS server (not only the entire bag as is the case now)
 - [ ] Enable copying to any iRODS server (not only the users.hydroshare.org iRODS server as is the case now).  We can load files from any iRODS server, so should be able to put files there too.
 - [ ] Enable storing of multiple iRODS server connection credentials in a users profile so that a user that for example uses iPlant/Cyverse can more easily connect.  This is a precursor to holding credentials for any 3rd party storage system that HydroShare can interoperate with.

**Comment by cbcunc** [comment]
Adding self as participant.

**Comment by dtarb** [comment]
@martinseul I'd like @hyi, @wclenhardt and @cbcunc to work out an overall iRODS plan.  A decision needs to be made as to whether we deprecate the  hydroshareuserZone at data.hydroshare.org or sustain and fill out its capability.  I think that once large file uploads are possible from systems like Box, Google Drive etc, that it could be deprecated.  I think there is still merit in having capability to load files from other iRODS servers, such as Cyverse where the data explorer is at iRODS iplant zone on data.iplantcollaborative.org.  If I ever need to load large files into HydroShare, this is what I use to avoid having to deal with CyberDuck.  Having the ability to put entire resources and single files in Cyverse would be good.  I'm happy to participate in discussion on working out what is reasonable and sustainable, but not ready to close this till we have had discussion and have a deliberate plan.

**Comment by hyi** [comment]
@dtarb @martinseul @wclenhardt @cbcunc I agree if we have large file upload working to meet our requirement, we can deprecate iRODS HydroShare user zone and keep the iRODS browser functionality that allow users to browser files from another iRODS server such as Cyverse.

**Comment by dtarb** [comment]
@hyi part of this issue was the suggestion to download single files or the resource bag as a whole to another iRODS instance, such as Cyverse.  If this was possible, then we have all the functionality wanted with Cyverse and the enhancements in this issue would be met.  Is this possible.  What would it take?

**Comment by hyi** [comment]
@dtarb What we will need to get single files or resource bag copied to another iRODS instance such as Cyverse is the iRODS credential and Cyverse iRODS info such as iRODS host, port, zone name, similarly to what we have for logging into iRODS. So we will need to have a iRODS login first before copying files or resource bag to another iRODS instance.

**Comment by dtarb** [comment]
@hyi yes.  Just as we can log in to iRODS to get files, I would imagine a similar approach to login to iRODS to put files.
