### ISSUE TITLE
"Reifying" matters of opinion in RDF

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#1931]
I am concerned that we are being a bit sloppy in how we code things in RDF (in resourcemetadata.xml). The specific instance is when a user overrides metadata that was in fact derived from the physical resource file. In this case, the user is saying that the file isn't definitive. This is a claim, and not a fact, because it differs from the content of the file. 

In RDF, **reification** is the process of qualifying a statement with its source. Whereas an unqualified statement would read like _"the value of Y is Z"_, a reified statement reads like _"the person or organization X claims that the value of Y is Z"_. 

See the [excellent explanation of reification](https://library.oreilly.com/book/9780596002633/practical-rdf/53.xhtml?ref=toc#pracrdf-CHP-4-SECT-3.1) in the Shelley Powers book "Practical RDF". 

This comes into play directly in the above scenario. A user is claiming that something asserted in a source file isn't completely accurate. Thus, there are two sources: the metadata in the source file, and the claimed metadata from the user. Reification clears up the source. 

It looks a little weird in RDF to claim something different from what is present in the source file without reifying the claim. 

Reification becomes very important when inferring something via crowdsourcing. If something gets a lot of +1s, this is equivalent to the reified statement _"The HydroShare user community believes this resource is useful"_, and not simply _"This resource is useful."_

**Comment by martinseul** [comment]
@sblack-usu Is this still relevant given your work on DSAW? If not, please close.

**Comment by sblack-usu** [comment]
I haven't considered "Reifying" opinions in RDF, it is not part of the DSAW work.  The link in the description is broken.

**Comment by eclark-cuahsi** [comment]
Closing per backlog review meeting on 6/9/22. Reopen if needed.
