### ISSUE TITLE
Resource Landing Page: Need to Display full Citation

### ISSUE THREAD

**Issue by horsburgh** [hydroshare/hydroshare#1941]
In the most recent versions, the citation has been reduced to a single line that does not wrap and part of the citation is not shown. The citation box should display the full citation, including the HydroShare URL and/or the DOI URL if the resource is published. The copy functionality is nice and should remain.

![image](https://cloud.githubusercontent.com/assets/3485902/24013946/afcc33d8-0a48-11e7-8626-dce112a25c9e.png)

**Comment by dtarb** [comment]
OK
