### ISSUE TITLE
Time Series Phase 2

### ISSUE THREAD

**Issue by horsburgh** [hydroshare/hydroshare#1942]
The following web user interface changes and API support are needed to make Time Series Phase 2 complete. I'm collecting some thoughts in this issue so I can close the other time series issue (#559). These may eventually get split out into multiple issues for work:

**Phase 2 API Support**
- [x] 1. Ensure capability to upload and download time series resource files through API (I believe that this is done already, but just want to make sure it works correctly.  
- [ ] 2. Ensure capability to set and get time series metadata through API.

**Phase 2 Additional tools that would be useful for Time Series resources:**
- [ ] 1. Add capability to create a resource from advanced CSV/YODA file/Excel Template upload.
- [ ] 2.  Develop Visualization tool(s) for time series - need to follow up with Dan about what is now available via the CUAHSI Apps.
- [ ] 3.  Develop tools for exporting to other formats (e.g., CSV, WaterML 1.1, 2.0). Likely add this to the Resource Specific Metadata tab where each individual time series is listed and allow them to export each time series as a CSV file with full metadata header (at least).

**Longer Term**
- [ ] 4. Develop tools for establishing a CUAHSI HIS compatible web service endpoint to serve time series resource content (using WaterML flavors)

More edits to this issue to come.

**Comment by Castronova** [comment]
@horsburgh is this still relevant? If not, please close.

**Comment by horsburgh** [comment]
Closing this issue as old and stale. 

* Capability to get/edit time series metadata through the API has been implemented.
* I suggest that we address capability to create a time series aggregation from an advanced/template upload be future functionality that not be tied to prior time series work. Here I'm thinking about CSV on the Web as an enabler https://www.w3.org/TR/tabular-data-primer/
* I think we should leave time series visualization and export to alternative formats to apps.
* Development of tools for establishing a CUAHSI HIS compatible web service endpoint has been worked on by others and doesn't need to stand in the way of closing this issue.
