### ISSUE TITLE
resource metadata xml file bug for netCDF resource and file type

### ISSUE THREAD

**Issue by gantian127** [hydroshare/hydroshare#1943]
When there is no original spatial reference metadata, the xml file still shows the term "projection_name=". This is not working as expected.

![image](https://cloud.githubusercontent.com/assets/5016511/24019723/d0d527e0-0a5e-11e7-818c-f7062b0dc528.png)

**Comment by pkdash** [comment]
@gantian127 Can test to see if this has been fixed and close this issue?

**Comment by gantian127** [comment]
@pkdash I tested it on Beta and it works. Thanks for fixing the bug!
