### ISSUE TITLE
file type metadata extended key/value pair metadata creation bug

### ISSUE THREAD

**Issue by gantian127** [hydroshare/hydroshare#1944]
When a key/value pair metadata of the file type metadata is created, the system shows error about "key already exists"which should not show up.

**Comment by pkdash** [comment]
@gantian127 Can you test on beta if this got fixed?

**Comment by gantian127** [comment]
@pkdash I just tested and it works as expected now. Thanks.

**Comment by pkdash** [comment]
This seems to have been fixed. Closing.
