### ISSUE TITLE
Resource type specific upload file validation

### ISSUE THREAD

**Issue by pkdash** [hydroshare/hydroshare#195]
When creating a resource only file the file types supported by that resource type should be allowed to be uploaded. The number of files (possibilities are: zero, one and multiple) that can be uploaded for a resource type also needs to be applied at the time of creating a resource. When adding a file to an existing resource, file type as well as the number of files allowed for that resource type need to be enforced.

**Comment by dtarb** [comment]
Deployed and working in 1.4.0
