### ISSUE TITLE
More issues with composite resources in 1.9.6 beta

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#1953]
I created a composite resource.  I added some zip files to it and unzipped them.  One of the folders contained a tif file.  I set Georaster file type.  I then imported a netCDF file and set NetCDF file type.  This resource inherited a title and abstract (that I had not yet set) from the NetCDF file.  I then set a keyword.  This should be everything that I need to make the resource public.  However I have the following problems with this resource
- [ ] It can not be made public
- [ ] The File Metadata for Multidimensional files does not display
- [x] The right click menu item "Set NetCDF File Type" should be generic "Set multidimensional data file type". [This is cosmetic]
- [x] I would also prefer the menu item "Set Geo Raster File Type" to be "Set Geographic Raster File Type." [Also cosmetic]

The resource where this occurs is https://beta.hydroshare.org/resource/b893874081244403bab1626860e0f0f3/.  This is shared with developer group, but not public because it cannot be made public (first problem above).

**Comment by dtarb** [comment]
I looked into this some more.  The test file I am using is in this zip file
[SWE_time.zip](https://github.com/hydroshare/hydroshare/files/852697/SWE_time.zip).  Note that for the tests below I load directly the nc file out of this zip file.

- On www I know this file has worked before.  When I attempt to create a multidimensional resource with this file I get.  "Error - Sorry an error occurred"
- On beta when I try create a multidimensional resource, a resource is created but spatial metadata is not properly harvested so as a result the resource is missing spatial coverage metadata (which is why it is not able to make it public).  This is odd because local projection extent data is harvested.
- On beta when I try create a netCDF file type within a composite resource I am unable to see file type metadata so do not know if it has been harvested.  Other metadata (Title and abstract) is harvested, but not keywords.  The message I get indicates that keywords are required to make it discoverable or public, but even adding keywords does not allow it to be made public (though the message goes away after a refresh).

My hunch is that an error is occurring in the code involving projection of local to WGS84 metadata and that is triggering the errors in all cases.  This is functionality that was worked on for geographic rasters, and either the same fixes are needed here, or the fixes there somehow are interfering here.

Also assigning to @gantian127 and @hyi as I know you have worked on these parts of the code in the past.

**Comment by pkdash** [comment]
@dtarb 

> On www I know this file has worked before. When I attempt to create a multidimensional resource with this file I get. "Error - Sorry an error occurred"

It seems www is giving that error today if one tries to create any resource type with or without files.

**Comment by pkdash** [comment]
@dtarb I did some debugging using the SWE_time.nc. It is not creating the Spatial coverage metadata element as there is no box information in the extracted metadata. Without the spatial coverage the file type metadata display fails. I have to work with @gantian127 to sort this out as I don't why the extracted metadata does not contain box information.

**Comment by pkdash** [comment]
@dtarb On www I tried to create a NetCDF resource using the SWE_time.nc file. I see the same issue - no coverage data and thus resource can't be made public.

**Comment by dtarb** [comment]
@pkdash yes I see the same on www.  So the problem is on www too.  But look at https://www.hydroshare.org/resource/392fc3a92ea54ad69f67728d13c9d919/.  This is the same netCDF file in a resource created earlier that has a bounding box and is public.  I believe that the March 1, 2017 date on this may be misleading, but cannot be sure.  I believe that this resource has existed for several months, but that this date was due to "migration" with an update.  @mjstealey could confirm the date of last deploy.  The error may have been introduced with an earlier deploy and not been caught.

**Comment by dtarb** [comment]
Note also that in the resource https://www.hydroshare.org/resource/392fc3a92ea54ad69f67728d13c9d919/ the only Author is Gichamo.  I believe that loading from the file superceded the owner.  Now however the author that comes from the file appears to be added.  I prefer to retain the previous behavior unless we deliberately decide on a change.

**Comment by dtarb** [comment]
In testing this I found that when setting multidimensional type, keywords in a netCDF file are not harvested.  They should be harvested and added to the keywords of the resource level metadata.

**Comment by dtarb** [comment]
Other issues have been resolved in my testing, so once this merges, it can be closed.

**Comment by dtarb** [comment]
Keyword issue in separate issue #1976 .  Other items done, so closing.
