### ISSUE TITLE
Resource access control - undo probably not working 

### ISSUE THREAD

**Issue by pkdash** [hydroshare/hydroshare#1955]
The following observation was made during pre-deployment testing for 1.9.6:

User A (resource owner) granted view permission to user B and edit permission to user C. Then C granted edit permission to B. Now when C tries to change permission for B back to view, system does not allow that and says 'Non-owners can't decrease privilege of others'. If C tries to delete existing edit permission (click on X) of B, system says 'You don't have permission to remove this sharing setting'. I was expecting it to go back to original view permission granted by user A.

**Comment by alvacouch** [comment]
@pkdash Undo is a different function than unshare. Undo is invariant of user privilege. One can invoke it even if one loses the privilege first.

**Comment by pkdash** [comment]
@alvacouch Is that means **unshare** should call **undo** internally from the UI perspective?

**Comment by alvacouch** [comment]
@pkdash There is actually no reasonable way to do that. 

* undo_share reinstates the previous privilege you might not have granted. E.g., if you gave CHANGE, and someone else gave VIEW, undoing restores VIEW.

* unshare permanently unshares, in the sense that it does not reinstate any previous privilege granted by another. In the same situation, unshare would remove all privilege including VIEW. 

So, one has to call undo_share separately if that is what one wants to do. 
Or, one can write a function undo_or_unshare to do that.

**Comment by alvacouch** [comment]
@ pkdash The problem with combining the functions concerns only owners. 

* Non-owners cannot unshare. 
* Owners can unshare, which means removing all privilege. 
* Non-owners can undo. 

So, my simple question is: should an owner be able to undo? 
* If so, undo and unshare are different UI buttons. 
* If not, undo and unshare can be the same UI button.

**Comment by pkdash** [comment]
@alvacouch Would it work then if we use the same button (x) but do different actions depending upon if the user is owner (remove all privileges) or non-owner (undo)?

**Comment by alvacouch** [comment]
@pkdash It will work but that is exceptionally poor UI design.  An owner should still have the option of a simple undo. It really needs two buttons that appear when `can_unshare_*` and `can_undo_share_*` are true.

**Comment by alvacouch** [comment]
@pkdash If you must use one button, I recommend a button that makes "undo" the priority operation, so that:

* if `undo_share_*` is true, then it is labelled `undo share` and undoes the share when pressed (without necessarily wholly unsharing the resource if privileges were assigned by others). 
* else if `unshare_*` is true (only for owners), then it is labelled `unshare` and unshares the resource when pressed. 

Thus, an owner who assigned a new privilege can unshare by pressing the button at most twice. 

IMHO this is a decent UI design.

**Comment by alvacouch** [comment]
(remember that undo is limited to a single action, and that further undos are prohibited after the first one by the backend, even though the information is there.)

**Comment by pkdash** [comment]
@mauriel133 Can you work on the above UI changes (as suggested by Alva) in access control panel? Any backend changes you need, I can do.

**Comment by mauriel133** [comment]
Yes, I'll work oj it.

**Comment by alvacouch** [comment]
@mauriel133 @pkdash The functions `UserAccess.can_unshare_*_with_*` and `UserAccess.can_undo_share_*_with_*` tell whether a user can unshare and/or undo. 

So, to emulate the behavior above, you would write
```
if user.uaccess.can_undo_share_resource_with_user(resource, u2): 
    user.uaccess.undo_share_resource_with_user(resource, u2) 
elif user.uaccess.can_unshare_resource_with_user(resource,u2): 
    user.uaccess.unshare_resource_with_user(resource, u2) 
```

This undoes a share if possible, and otherwise unshares it if possible.

**Comment by dtarb** [comment]
@pkdash please tell @Lizabrazil what has changed on the UI for this issue.  She needs to change help documentation and screen shots to reflect changes in functionality.  I cannot actually see any front end changes, but perhaps they are subtle, which is why we need your help to point out what is different.

**Comment by dtarb** [comment]
OK
