### ISSUE TITLE
data/contents subpath does not belong in /hsapi/resource/{pk}/functions paths

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#1956]
@pkdash @dtarb 
Currently, the API functions that support the REST endpoints in `/hsapi/resource/{pk}/functions` take a full path like in iRODS. Since the application is not allowed to modify files in any subpath except `{pk}/data/contents`, `data/contents` should not be required to be part of that pathname. This means -- in turn -- that we need to transition apps using this code in the hs_restclient to the modified, shorter pathnames. Affected functions are `zip` and `unzip`.

**Comment by alvacouch** [comment]
This is also an integrity exposure, as the routines do not check currently whether the path is allowed or not. I have changed this in my debugging mode code, but in production, invalid requests are simply acted upon, writing files to forbidden areas in the resource.

**Comment by pkdash** [comment]
@alvacouch ```zip``` and ```unzip``` are not yet implemented in hs_restclient. So no existing apps using hs_resclient need any change.

**Comment by alvacouch** [comment]
@pkdash It's a little weirder than that. The REST endpoints add data/contents to the path; the API functions don't. I will modify this if it is safe.

**Comment by pkdash** [comment]
@alvacouch Are you referring to Hydroshare internal API functions (view functions)? Any changes to those likely to break Hydroshare UI.

**Comment by dtarb** [comment]
@sblack-usu Is this still relevant given your work on hsapi.

**Comment by martinseul** [comment]
stale, closing
