### ISSUE TITLE
Making release documentation accurate at release time

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#1967]
@dtarb @martinseul @rphtufts 

@Lizabrazil is taking the initiative to ensure that user documentation stays in sync with our releases.  She needs to be able to run, try out, and document the function of the release (including making screenshots) starting a couple of weeks **before** we might want to actually release it. 

Our current release schedule has been much more rushed than this. The way things are being done now, there is no way that Liza can complete the documentation by the time the release is up and running. 

This came up because we're planning a change in the discovery interface in the next release (PR forthcoming) and Liza would like the chance to document this before it becomes part of the main website. In this release there will be an extra tab and an extra facet ("Variable") that are rather important to our users. The documentation should adequately explain them when they appear, and not two weeks later!

I'm not sure how we should handle this. We could, perhaps: 
1. Relax the release schedule and give some time for documentation to catch up. 
2. Provide a "beta release" preview before incorporation with the full release, that people can try out before the main release. We would have to be predictable about this and that release would have to appear at the same URI all the time. 
3. This would mean -- in turn -- that there'd be another branch "beta" in GitHub that contains the beta release, and that we would merge develop into beta and then beta into master. 

Your thoughts?

**Comment by alvacouch** [comment]
@mjstealey Your thoughts on the above?

**Comment by pkdash** [comment]
@mjstealey I assume item#2 and#3  above mostly what you currently do. Right?

**Comment by dtarb** [comment]
I like the idea of a beta release that is held longer for testing and documentation, and being predictable about it.

**Comment by pkdash** [comment]
@dtarb @mjstealey and @alvacouch 

I think the following git branching model should work better for us:

![image](https://cloud.githubusercontent.com/assets/2523434/24421276/e6a3517a-13b2-11e7-9b71-4a7ec5d91b84.png)

**Comment by dtarb** [comment]
This seems good to me.  @aphelionz ?

**Comment by pkdash** [comment]
The above git branching model is explained here: http://nvie.com/posts/a-successful-git-branching-model/
I suggest hotfixes be merged only by one designated person (currently that's @mjstealey ).

**Comment by cuahsimarko** [comment]
@dtarb @Lizabrazil @engineSound can we close this GitHub Issue, since there is https://docs.google.com/document/d/1ABdDZCg6nRpV7BbYMA11QsOWczGF7tZ1zd31e0VmQ0k/edit ?
