### ISSUE TITLE
fix the bugs for add_files_to_resource() and delete_file()

### ISSUE THREAD

**Issue by gantian127** [hydroshare/hydroshare#197]
fix the bugs for the two functions in hs_core/__init__.py. 
This is related to making the signals of pre_delete_file_from_resource and pre_add_files_to_resource to work as expected.
When sending the pre_delete_file_from_resource or pre_add_files_to_resource signals, the "sender" parameter value is not the resource class and just empty string, which will make receiver functions not to work as expected.
In the add_files_to_resrouce() function the pre_add_files_to_resource should be put before the for loop for adding the files.

**Comment by selimnairb** [comment]
@gantian127 Could you briefly describe these bugs?  This will help when the eventual pull request is evaluated.  Thanks.

**Comment by dtarb** [comment]
Working in 1.4.0
