### ISSUE TITLE
Add About to Header and Footer

### ISSUE THREAD

**Issue by ChristinaB** [hydroshare/hydroshare#1973]
- [x] Add Link to About on the left after HELP, move HydroShare logo home page further right. 
  - @ChristinaB - can you clarify this a bit (there is no on the left after help?)
- [x] Architecture
- [x] Metrics - link to Kibana website 
- [x] Publications - add years tabs
- [x] Team - add years tabs
- [x] Governance
- [ ] Funding with @dtarb 
- [x] Update links  in footer
- [x] Update design in footer with @aphelionz

**Comment by ChristinaB** [comment]
Governance Notes
[Link to ongoing Discussion ](https://docs.google.com/document/d/1g1Z9jO-Q0HHg43MbngyN3N7m0nK9CC9HXW0EvpRqgQg/edit#)  

Web page draft for Governance developed in Google Docs
 [Link to Draft Governance webpage](https://docs.google.com/document/d/17MAIpCNzojmoPCSD8lLYyVcSZ0g9G_iKZkTCi65PqyI/edit)

**Comment by ChristinaB** [comment]
@mjstealey - this will be ready for you to add to the header once we get the checkboxes added.

**Comment by ChristinaB** [comment]
@aphelionz   -  jon pollack said he was on Github, but I'm not sure that he is added to this group. Is that something you can do?

This issue is for organizing the About pages needed, checking them off as they are ready, and then @mjstealey can do his magic on the header.   Do we need a different issue to work on adding tabs to years?  @mjstealey  Is this something that can be done in Mezzanine?    Here is an example webpage that would make updating publications and team relatively simple moving forward.  [See this link to an example of tabs by year-yes, we should be jealous on the sponsor funding, but the point is can we do this for Team and Publications?)](https://cos.io/about/our-sponsors/)

**Comment by ChristinaB** [comment]
@mjstealey  - I just wanted to re-ping you on this question of using tabs on the About pages.  My understanding is that we could make a new page for each year (for team and publication) and reorganize the dashboard to look like tabs.  If you have a better recommendation, please let me know.

**Comment by mjstealey** [comment]
@ChristinaB - Adding questions here as well as inline with the original post.

What is the exact wording for the left hand nav bar:
Key: REQUESTED (CURRENT) 
- About (About HydroShare) **?**
  - Architecture (Architecture)
  - Metrics (Usage Metrics) **?**
  - Publications (Publications)
  - Team (Team)
  - Governance (Policies) **?**


![screen shot 2017-04-19 at 11 55 48 am](https://cloud.githubusercontent.com/assets/5332509/25189473/42d4f566-24f7-11e7-870c-967a69c7213b.png)

**Comment by ChristinaB** [comment]
@mjstealey 
I updated Usage Metrics to Metrics.
Governance is a new page, I have posted what I have ready now.  The new structure on Pages (pending further suggestions, but currently live) is:
![image](https://cloud.githubusercontent.com/assets/4108369/25190526/4f9e1e1e-24e1-11e7-8ef5-057a47a4c6df.png)

**Comment by ChristinaB** [comment]
Footer links have been moved to Pages for Statement of Privacy and Terms of Use.  
SiteMap does not seem to be something we really need to include (at this time, in the current crazy long list format).

**Comment by horsburgh** [comment]
Seems like the sitemap was there for search engine optimization purposes?

**Comment by ChristinaB** [comment]
@aphelionz and @mjstealey  - is the site map generating automatically from iRODS ? This link should stay were it is.  Statement of Privacy and Terms now live officially on Pages.    

Is this a good time to change the name from Pages to Help?

**Comment by ChristinaB** [comment]
I fixed up Publications and added an ALL page per @rayi113. 
I added a Funding page but need more info from  @dtarb and others to finalize. Are we listing all projects that have contributed to HydroShare development? I think yes.

**Comment by mjstealey** [comment]
@ChristinaB - The sitemap should actually be updated. Currently the sitemap link on pages goes to the sitemap of HydroShare. The sitemap on HydroShare is a custom implementation that was put in place by a prior Caktus developer (Calvin).

Ideally we break the sitemap link between pages and www and allow them to both have their own sitemap for web crawlers to find.

Added #2018 to reference the Terms of Use and Statement of Privacy issue.

And yes, will look at changing the name from pages.hydroshare.org to help.hydroshare.org in the near term.

**Comment by ChristinaB** [comment]
I updated Team pages to be consistent with the fake tabs like Publication.  2017 needs a review, I'm not sure that the entire list is active. We can add new 2.0 people when funding is in place. 

I need clarification on 2014  -- 1) do we want to include the following? if so, I need the first name and affiliation.

J. Coposky,
 K. Gustafson, 
S. Jackson,
 H. Johnson, 
Y. Kim, 
T. Whitenack, 
I. Zaslavsky,
 L Zhao, 
N. Martin,
 S. Duncan, 
L. Christopherson,

**Comment by ChristinaB** [comment]
@mjstealey 
I think everything is ready to go on the Header and Footer updates.  
This is the Footer update text and layout (maintain original color scheme)  that @aphelionz put together.  
![image](https://cloud.githubusercontent.com/assets/4108369/25201288/0819c87a-2506-11e7-999d-570cd6ce6b88.png)

Contact Us Here (hyperlink) should go to support@hydroshare.org

In future work, we will work with @Lizabrazil on how to support and where to post  team@hydroshare.org, def@hydroshare.org,announce@hydroshare.org etc

**Comment by dtarb** [comment]
@rayi113 is there a separate issue to fix pages 
![image](https://user-images.githubusercontent.com/3456833/27408420-bbd3d904-5699-11e7-890e-3bf553e63b44.png)

**Comment by mjstealey** [comment]
@dtarb - Yep #2093
