### ISSUE TITLE
Make composite resource the default resource type

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#1977]
Lets make composite resource the default resource type, instead of generic, when content is being added to HydroShare.  This is part of the process of encouraging use of composite resource types more.

**Comment by horsburgh** [comment]
Do we have composite resource nailed?  If we are going to make this change, it better be ready for prime time.

**Comment by mauriel133** [comment]
@dtarb, @pkdash 

Could you confirm if the Composite Resource type is ready to be used as default?

**Comment by dtarb** [comment]
Confirmed.

**Comment by mauriel133** [comment]
Included as part of Create Resource page revamp (https://github.com/hydroshare/hydroshare/pull/1957)

**Comment by dtarb** [comment]
Implemented
