### ISSUE TITLE
On multidimensional resources message displaces location of Public/Discoverable/Private buttons

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#1978]
Public/Discoverable/Private buttons should appear below, not next to a message in sharing status.
![image](https://cloud.githubusercontent.com/assets/3456833/24518201/6051c86c-153e-11e7-8639-2d9e4ea1c6de.png)

**Comment by pkdash** [comment]
@mauriel133 Can you fix this?

**Comment by hyi** [comment]
@dtarb @gantian127 I think this message can be removed now that we do real-time on-demand update for OpeNDAP service rather than depending on a cron job that does update every 2 minutes. The real-time update is pretty quick, so I don't think this message is needed any more.

**Comment by mauriel133** [comment]
@dtarb, let me know how to proceed given @hyi's observation above.

**Comment by dtarb** [comment]
If there is no hesitation when a user clicks Public, then it is OK to remove the message.  If there is hesitation due to the on demand updating that is more than 2 seconds, then I think we need the message.  Please test with some biggish files and decide.

**Comment by hyi** [comment]
@dtarb @mauriel133 @gantian127 Let's then keep the message for now as a precaution.
