### ISSUE TITLE
Allow existing coverage metadata to be deleted

### ISSUE THREAD

**Issue by gantian127** [hydroshare/hydroshare#199]
This function is used for deleting old coverage metadata info when user replaces the old resource file with a new resource file for an existing resource. Currently, the coverage metadata can't be deleted and can only be updated if the resource has the coverage metadata information.

**Comment by dtarb** [comment]
For resource types that have a single file that contains coverage and resource type specific metadata information, when that file is deleted a subset of metadata should be retained and a subset reset to default values.  When a new file is read the type specific metadata should be populated from the new file.

@gantian127, @hyi, and @pkdash please develop lists of the metadata for netcdf and raster resources and categorize these into those that need to be refreshed when a file is changed, versus retained.  Pabitra please guide the underlying data structure for managing this.

**Comment by mjstealey** [comment]
Related to #176

**Comment by hyi** [comment]
As Dave suggested, I am putting a list of metadata sub-elements for raster resource type here for bookkeeping:
When the raster file is deleted, the following happens:
1. Spatial Coverage is reset to default values (units and projection are reset to "Unnamed" with other limit values are set to 0.
2. CellInformation is reset to default values (either 0 or "Unnamed")
3. All band information from the deleted file is deleted. The default band count is reset to 1 with default BandInformation set to "Unnamed" or empty.
4. Other metadata manually entered by users such as Title, Abstract, creators, etc., are untouched by deletion of the file.

While the raster file is added, the following happens:
1. Spatial Coverage is extracted from the file and added into core metadata.
2. CellInformation is extracted from the file and added into extended metadata.
3. Band count is extracted from the file, and the corresponding number of bands are added into extended metadata with default values such as "Unnamed" or empty.
4 Other metadata are untouched.

**Comment by hyi** [comment]
@pkdash Is this something that needs to be addressed at your hs_core level since coverage core metadata is managed at the hs_core level? If this is true, can you reassign this issue to yourself to address it? You may discuss this with Tian to see what is the exact issue. For raster resource type, I think updating/resetting coverage to default values will suffice when replacing an old file with a new file.

**Comment by pkdash** [comment]
Currently once a coverage metadata element is created it can't be deleted. I can change that.

**Comment by dtarb** [comment]
@pkdash will it be possible to do this for 1.4.  Then @hyi can coordinate the raster resource type changes with what you do

**Comment by pkdash** [comment]
@dtarb, @hyi and @gantian127 It seems there is a way to delete coverage metadata elements. In fact, I have done that in my branch '5-time-series-resource-phase-1'. The following line of code will delete all coverage elements of a resource:

resource.metadata.coverages.all().delete()

**Comment by hyi** [comment]
@pkdash Can you point where in your time series branch you deleted coverage metadata? Currently, Coverage class remove() method raises validation error indicating coverage cannot be deleted. I am trying to replace my current logic to reset coverage to default values with deleting coverage element, and try to find out whether I need to modify anything in the hs_core Coverage class implementation to allow me to do so.

**Comment by hyi** [comment]
@pkdash Please disregard my earlier comment. I realized I can simply delete the object by using delete() and have tried that and everything works for me at my local branch, so this issue has been resolved.

**Comment by hyi** [comment]
Fix pushed to github and a pull request has been created to merge it into release-candidate-1.4.0.

**Comment by hyi** [comment]
Tested it on alpha and it is working now for raster resource type. Adding ready for testing label. @gantian127 You can take a look at raster resource type code on release 1.4.0 branch to see how coverage metadata is deleted when a file is deleted.

**Comment by gantian127** [comment]
I just test that on local dev for netCDFand it works now. Thanks for the work.

**Comment by dtarb** [comment]
Tested by deleting a file from a raster resource and adding another one and the metadata is reset properly
