### ISSUE TITLE
We need to understand how RDF is created from Django

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#1991]
@dtarb @pkdash @martinseul @horsburgh The discussion of referenced time series (issue #1571) yesterday exposed a rather important issue going forward. Of the team, only @horsburgh knows how RDF is generated from Django.  It would help greatly if the other parties involved (including myself, @pkdash, and @martinseul) know more about the algorithm for going from Django metadata to RDF. 

@horsburgh: Could you give us some lessons?  Or, more presently, could you explain the rules by which you're creating the RDF for composite referenced time series from the Django you have?

**Comment by horsburgh** [comment]
@alvacouch - I worked with @pkdash on the implementation. As we have worked on different resource types, I have given him examples of how to encode various metadata items in the resourcemetadata.xml file. First we worked out how to do the standard Dublin Core elements and then we worked out how to do resource specific stuff, etc. The examples are validated using an RDF/XML validator to make sure they are syntactically correct and then Pabitra has done all of the coding and implementation for actually creating the XML file.  So - @pkdash is the resident expert on how the XML file gets generated.

The composite resource work is new.  And I'm still working with Pabitra to make sure metadata elements get written to the resourcemetadata.xml document for each file.  For the composite, referenced time series file type, I will take the final version of the JSON file, convert the necessary elements to an RDF/XML representation and embed it in the resourcemetadata.xml document so Pabitra knows what it should look like. Then, Pabitra will implement that.  But we still need to look at this in the context of what Pabitra has already done for the NetCDF file type and make sure we are being as consistent as possible across file types and also making sure that we don't do something dumb that precludes adding metadata from other files of other types.

**Comment by pkdash** [comment]
@alvacouch 

Refer to following link to see how the RDF/XML gets generated for core metadata:
https://github.com/hydroshare/hydroshare/blob/develop/hs_core/models.py#L2852

Refer to the following link to see an example of how resource specific (e.g., time series)  RDF/XM gets generated:
https://github.com/hydroshare/hydroshare/blob/develop/hs_app_timeseries/models.py#L792

**Comment by aphelionz** [comment]
@horsburgh @pkdash @alvacouch I'd like to close this but I'd like to make sure the knowledge ends up being disseminated to the team. We can either move it to the wiki or send it out via an email. What do you think?

**Comment by pkdash** [comment]
@aphelionz I am OK with closing this.
