### ISSUE TITLE
ResourceFile API doesn't create files properly for CompositeResource

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#1999]
@dtarb @hyi 

@pkdash reports that files aren't copied properly for composite resource. Bag file is not generated correctly. 

Further, quick examination of the current version of `copy_resource_files_and_AVUs` in `hs_core/hydroshare/utils.py` shows some redundancy in file copying.

**Comment by alvacouch** [comment]
See branch 1999-ResourceFile-API-fix for initial comments. The copy routine definitely needs help. Will get to this asap. I have guests now.

**Comment by alvacouch** [comment]
Further investigation shows that AVUs are being set on the wrong element during the copy.  This is true for all copies.

**Comment by alvacouch** [comment]
@pkdash @hyi @dtarb @martinseul PR #2000 merged. This should be fixed. This does **not** fix the problems with the REST API reported separately. They're on www, this was on develop.

**Comment by pkdash** [comment]
@alvacouch I did test this on beta and it seems to have fixed this issue. You can close this issue.
