### ISSUE TITLE
Capability to create resource via REST API from content specified by http URL

### ISSUE THREAD

**Issue by selimnairb** [hydroshare/hydroshare#20]
Allow for the creation of a new resource using the REST API where the resource file content is not uploaded as part of the POST request, but instead the POST contains an http URL from which the resource content should be downloaded.

**Comment by dtarb** [comment]
@alvacouch please figure out what to do with this.

**Comment by aphelionz** [comment]
@dtarb @alvacouch Where are we at on this one?

**Comment by dtarb** [comment]
Closing as I do not think we have a current use case demanding this.
