### ISSUE TITLE
Remove name, Email and website from 'New Comment' section when user is signed in

### ISSUE THREAD

**Issue by mauriel133** [hydroshare/hydroshare#200]
Name, Email and website input fields should not appear on the comment section when the user has already signed in. This information is already given in the user profile.

**Comment by hyi** [comment]
This new comment section comes directly from Mezzanine code. This issue is part of issues detailed in #186 which I am currently working on to address as the first phase of implementation for issue #186. @mauriel133 Let me know if you have other ideas in mind for addressing this issue.

**Comment by horsburgh** [comment]
This was at the end of a longer list of things that Mauriel was working on. He was done with everything else in that list, so we moved this one to a new issue. It overlaps with #186. So, I'm closing this one.
