### ISSUE TITLE
New REST API /scimeta/elements/ does not change resourcemetadata.xml

### ISSUE THREAD

**Issue by yirugi** [hydroshare/hydroshare#2001]
Hi,

I have found that the new REST API, /scimeta/elements/, does not change resourcemetadata.xml file.
For example, after I change 'description' field using the API, I downloaded the xml file, but the 'abstract' field is the same.

**Comment by pkdash** [comment]
@yirugi This is a bug. Seems like a simple fix. @mjstealey I plan to make this as a hot fix on master if that's OK with you.

**Comment by pkdash** [comment]
@yirugi Can you try REST endpoint call to see if this bug got fixed? Thanks.

**Comment by yirugi** [comment]
@pkdash I just confirmed that the REST API, /scimeta/elements/, correctly change the resourcemeta.xml as well. Thanks!! I'll close this issue.

**Comment by pkdash** [comment]
@yirugi Thanks for your help on testing. Glad to know it got resolved.
