### ISSUE TITLE
Resource file download failure

### ISSUE THREAD

**Issue by yirugi** [hydroshare/hydroshare#2002]
Right after a new resource creation, if I try to download resource bag file using REST API, I got this error message:
{"bag_status": "Not ready", "task_id": "78c45101-290b-4f16-a09e-e8f63aa473a4"}

I guess that it needs time to prepare the bag file; however, sometimes, I get this error message even when I try to download old resources. 
It happens not frequently, so I couldn't reproduce the problem, but I wonder if this is normal.

**Comment by mjstealey** [comment]
@yirugi - Bagging is an on-demand procedure that doesn't occur until a user requests it.
The life cycle of a zipped bag file is as follows.
1. New resource created - Zipped bag file does not exist until user requests a bag download
2. Bag download requested (1st time) - Starts an async process to generate the bag - in the UI the user is shown a message that the bag is being created, and it's downloaded once this process completes. I'm unsure how this is relayed to the REST user.
3. Zipped bag file (2nd - Nth downloads) - Remains in place as long as no changes have been made to the underlying resource and is immediately available for download via UI or REST
4. User updates resource - Bag file is marked as "dirty", but not regenerated until the next download is requested (See step 2.)

**Comment by yirugi** [comment]
@mjstealey Thank you for the explanation. This helps a lot in understanding the bagging system.
So, there is no way to know when the bag is ready using RESt API unless we try multiple times?

**Comment by mjstealey** [comment]
> So, there is no way to know when the bag is ready using RESt API unless we try multiple times?

@hyi, @alvacouch - Could you help clarify @yirugi's question w.r.t. REST?

**Comment by hyi** [comment]
@yirugi @mjstealey @pkdash The similar check for whether bag is ready is put to REST API side as well by @pkdash as documented below in REST API docs:
```
Note that when the BagIt archive is not ready for download (this archive zip file needs to be recreated) the client by default will wait until the BagIt archive is recreated. This may take a while. If you want to get the BagIt archive only if it is ready for download:

>>> from hs_restclient import HydroShare
>>> hs = HydroShare()
>>>try:
>>>     hs.getResource('e62a438bec384087b6c00ddcd1b6475a', destination='/tmp', wait_for_bag_creation=False)
>>>except HydroShareBagNotReadyException as e:
>>>     print('BagIt file is being generated and not ready for download at this time.')
```
So it looks like your code that calls REST API can set wait_for_bag_creation to True if you want to wait until bag is created for you. @pkdash Feel free to chime in with more info as needed.

**Comment by pkdash** [comment]
```wait_for_bag_creation ``` is set to True by default.

**Comment by pkdash** [comment]
@yirugi 

> Right after a new resource creation, if I try to download resource bag file using REST API, I got this error message:
{"bag_status": "Not ready", "task_id": "78c45101-290b-4f16-a09e-e8f63aa473a4"}

From the above it seems you are calling the REST endpoint directly and are not using the hs_restclient. That is the expected behavior when using the REST endpoint directly. 

There is a spate REST endpoint that you can call passing the task_id to get the status of the bag creation.

**Comment by yirugi** [comment]
@pkdash yes, we calls the REST API directly, instead of using hs_client.
Can you let me know the REST API for checking status of the bag creation?

**Comment by pkdash** [comment]
@yirugi The url pattern for the endpoint to check task status:

```www.hydroshare.org/hsapi/taskstatus/task id goes here/```

The response from the above call will return a json object with key 'status'. If 'status' has a value then it means the bag is ready.

**Comment by yirugi** [comment]
@pkdash Thank you so much!! I'll close this issue.
