### ISSUE TITLE
Update nwmZone and nfiehydroZone to iRODS 4.2.1

### ISSUE THREAD

**Issue by rayi113** [hydroshare/hydroshare#2006]
Update nwmZone and nfiehydroZone to iRODS 4.2.0 when updating other production HydroShare iRODS servers to 4.2.0.

**Comment by rayi113** [comment]
nfiehydroZone iCat upgraded to 4.2 on 04/19/17.  Federation between hydroshareZone and nfiehydroZone verified.

**Comment by rayi113** [comment]
Updated this activity to upgrading to HydroShare 4.2.1 and not leaving at 4.2 due to #2140.

**Comment by aphelionz** [comment]
@rayi113 Where are we at with this?

**Comment by dtarb** [comment]
Closing as I think we are past this.  There is other work that  @rayi113 and @cbcunc have underway to update iRODS.  If this needs to remain open one of you can reopen.
