### ISSUE TITLE
Extra Metadata tab page is NOT working on current Dev branch

### ISSUE THREAD

**Issue by zhiyuli** [hydroshare/hydroshare#2007]
Looks like Extra Metadata tab page is not working on current Dev branch. I was able to add a new extra metadata, but I was not able to save it. 
It is working fine on current WWW though... Any recent changes may be related to this?

**Comment by mauriel133** [comment]
@zhiyuli, I was unable to reproduce this error. Are you using the most recent version of the develop branch?

**Comment by zhiyuli** [comment]
@mauriel133 
Thanks! It is working now....I am using latest dev. I thought the issue I saw just now was probably caused by some old javascripts cached in browser.  I am closing this issue....
