### ISSUE TITLE
On edit access list, the auto-complete text should be "[Name] - [Email]"

### ISSUE THREAD

**Issue by mauriel133** [hydroshare/hydroshare#201]
Right now it lists only the Email, but since some emails are abbreviations of the name, sometimes is not very clear.

**Comment by dtarb** [comment]
Are you going to be able to fix this for 1.4 release.  Looking at what is in 1.4 rc0 the functionality is awkward.   I suggest the following
- user real names and emails for display.  Never display a username
- dont collapse manage access on update so a user can see what is going on
- use a different approach for removing access.  The having to select all and update is confusing
- make it clear that the button "update access list" is a button.  I first thought it was a text box and clicked it hoping to enter text and was surprised when the display got reset back.

Also see earlier comments at https://github.com/hydroshare/hydroshare2/issues/59

If properly fixing this pushes it back to release 1.5, that is OK.  @horsburgh thoughts?

**Comment by horsburgh** [comment]
I would rather just fix the whole thing once with the new styling we discussed for the whole "manage access" panel.  I suspect that will push it to 1.5.

**Comment by dtarb** [comment]
I think that the same text should be used in the listing of users as in the add user element.  This should include organization.  The basis for this is that the same disambiguation may need to be applied when seeing a name on a list as when picking from an auto-complete element.  See below.
![untitled](https://cloud.githubusercontent.com/assets/3456833/7550463/023ac474-f621-11e4-8d2d-ee46ffddc7c9.png)

**Comment by mauriel133** [comment]
I can't access any of the resources on sandbox right now. I get an error screen. Is somebody else experiencing the same problem?

**Comment by horsburgh** [comment]
Same for me. It may have broken while I was trying to create a referenced time series resource earlier.

**Comment by mjstealey** [comment]
@mauriel133, @horsburgh - access to resources should be good again. The error that I saw was a reference to being unable to retrieve files size from iRODS. Not sure why the connection to iRODS was failing as the server is running as expected and was available using the sandbox credentials via command line. I restarted the hydroshare instance on sandbox and all appears to be working as expected again.

**Comment by mauriel133** [comment]
Thanks for taking care of that, Michael.

Maurier Ramírez
Cel: 407 520 4585






On Sat, May 9, 2015 at 5:00 PM, Michael J. Stealey <notifications@github.com

**Comment by dtarb** [comment]
@mauriel133 as deployed on dev.hydroshare.org right now Organization does not appear in the manage access section as suggested above.

**Comment by mauriel133** [comment]
Yes, this is still on my todo list. Will get it done as soon as I can.

**Comment by mauriel133** [comment]
I need help identifying where in the code this list is populated. Perhaps @pkdash or @mjstealey can help me.

**Comment by mauriel133** [comment]
This issue has been taken care of by the new access control interface being developed [#447] and can be closed.

**Comment by horsburgh** [comment]
Based on @mauriel133 's comment about this being addressed by the new access control panel, I'm going to close this issue.  We can revisit if needed after the new access control panel is implemented.
