### ISSUE TITLE
Make selenium tests work in Firefox

### ISSUE THREAD

**Issue by alexlemann** [hydroshare/hydroshare#2013]

**Comment by alexlemann** [comment]
This was blocked by https://github.com/mozilla/geckodriver/issues/659 . It looks like a new version of geckodriver (0.16) was released. I will install that locally and adjust tests as needed so that this can get closed out.

**Comment by alexlemann** [comment]
The new geckodriver works great. There are some issues with the drag and drop test in FF that need to be resolved for this. This shouldn't block 1.10 and it relates to documentation in #2039 so I'm pushing out to 1.11.

**Comment by dtarb** [comment]
Closing this as it appears to be superceded by work of @ndebuhr and @cuahsimarko .  Feel free to reopen if still needed.
