### ISSUE TITLE
Discovery filter by  Resource Type breakpoint display

### ISSUE THREAD

**Issue by alexlemann** [hydroshare/hydroshare#2016]
Notice the + sign to expand the Resource Type filter.

![discovery-resourcetype-breakpoint](https://cloud.githubusercontent.com/assets/46069/25193629/bf276db6-2505-11e7-8cde-c2dcf6616171.png)

**Comment by alvacouch** [comment]
@aphelionz Not sure this is still an issue.

**Comment by Lizabrazil** [comment]
I am closing this because it is not necessary to fix at this point we will reassess the filter panels during Discover Redesign
