### ISSUE TITLE
Relocate text for - Terms of Use - Statement of Privacy - to pages site

### ISSUE THREAD

**Issue by mjstealey** [hydroshare/hydroshare#2018]
Extract text from hydroshare site and relocate to pages site.
- [Terms of Use](https://www.hydroshare.org/terms-of-use/)
- [Statement of Privacy](https://www.hydroshare.org/privacy/)

Update links for each within the code to point to the new location.

**Comment by mjstealey** [comment]
@ChristinaB - Have updated the links on HydroShare and pages to reference your new Terms of Service and Statement of Privacy docs.

Feel free to close once verified

**Comment by ChristinaB** [comment]
Extracted  text from hydroshare site and relocated to pages site for:
Terms of Use
Statement of Privacy
