### ISSUE TITLE
Catalog CSDMS Models in Hydroshare

### ISSUE THREAD

**Issue by edwmorgan** [hydroshare/hydroshare#2019]
- [ ] Wrote [script](https://github.com/uva-hydroinformatics-lab/CSDMS-to-Hydroshare) to pull metadata from CSDMS models and populate Hydroshare Model Programs through the REST API

- [ ] Uploaded any resource files/documentation for each model (manually)

- [ ] Listed correct authors for each resource, also through a script

**Comment by Castronova** [comment]
@goodalljl Is this still relevant? If not please close.

**Comment by Castronova** [comment]
Closing, no longer relevant as per @goodalljl .
