### ISSUE TITLE
signals are not consistently raised in file/folder operations

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#2020]
1. pre-delete and post-delete signals are not consistently raised in the several routines that can delete a file or folder from iRODS in `hs_core/views/utils.py`. Different sets are called via the REST API and the UI. 
2. It is not consistently checked whether a folder can be deleted before deleting it.

**Comment by dtarb** [comment]
@alvacouch is this still an issue.

**Comment by alvacouch** [comment]
There have been many changes since this was pointed out. Largely this disappears with the implementation of asynchronous tasks.
