### ISSUE TITLE
Track app status

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#2023]
It appears bad when apps supported as part of the system do not work, or even open.  Two recent examples are the opendap app that acts on multidimensional resources/files, and Jupyterhub.   I suggest:
1. An "app heartbeat" function that periodically (e.g. daily) automatically attempts to open each app to verify that it is still up and if not reports this to administrators.  
2. Use tracking functionality to monitor and report which apps are up and down and for how long.
3. Setting the permissions for all approved app instances to have an appropriate system administrator an owner, so that when an approved app is offline the permissions can be set to private to limit attempts to use that result in an error, and that if warranted, a message of the day message posted.
4. An alternative to message of the day, is an "offline" setting in the app instance that rather than attempting to open an app presents an "offline" message.

**Comment by alexlemann** [comment]
Would an external service eg http://pingdom.com suffice here? What monitoring service is being used for HS proper?

**Comment by mjstealey** [comment]
@alexlemann - HydroShare is using [django-heartbeat](https://pypi.python.org/pypi/django-heartbeat)

We have a Jenkins monitoring job that runs at a 5 minute interval to check the status. On failure it attempts a restart HydroShare and emails a subset of the HydroShare team regarding status.

**Comment by dtarb** [comment]
@Castronova giving this to you.  I'd like this to be part of CUAHSI system tracking functionality.  If too much to do for 1.11, you could put later.

**Comment by cuahsimarko** [comment]
Could something like Datadog, New Relic or other DevOps tool serve for both internal engineering and also provide a lighter public portal?

**Comment by dtarb** [comment]
@Castronova Can we close this.  It is not repository role to track apps.

**Comment by martinseul** [comment]
closing this, it is stale we can reopen if needed
