### ISSUE TITLE
File URLs incorrect in REST API after ResourceFile fix. 

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#2025]
The URLs returned for file listing in the REST API are incorrect because they depend upon an old version of ResourceFile.url.  

@mistealey @dtarb @pkdash  I am going to try to make this repair before 1.10.0.

**Comment by alvacouch** [comment]
@pkdash @hyi @dtarb @mseul @aphelionz 
Moving the discussion to this issue for archival purposes. 

Everyone, I'm trying to squash a serious bug in the REST API before 1.10.0. Part of it was caused by the ResourceFile revision. Another part was exposed (but already not working properly). 

The two bugs so far are: 
1. The URL in the response to `resource/{pk}/list` is incorrect due to ResourceFile changes.
2. The mapper for that URL to iRODS is incorrect as well: doesn't handle federation. 

The issues so far include that: 
1. we need to decide the final format of the file URLs in `resource/{pk}/list`. 
2. we need to ensure that the mapper works properly for these URLs. 

The constraints of the problem are that
1. The pattern `resource/{pk}/data/contents/{folder}/{file}` needs to be preserved for DataOne reasons. 
2. The pattern `resource/{pk}/data/{something}.xml` needs to be preserved for DataOne conformance reasons. 
3. These paths are embedded into `resource/{pk}/data/resourcemap.xml` already. **Changing them requires a data migration.**

These patterns are read-only. By contrast, `resource/{pk}/files/{path}` is **read-write** and only available when access is granted. 

Long-term issues include that: 
1. These paths are currently transduced directly into iRODS paths via the mapper. 
2. AFAIK There is **no evidence of access control** on this transduction. 

This is a difficult situation with 1.10.0 coming so fast. 

Decisions so far: 
1. Conform to `resourcemap.xml` conventions in the return value for `resource/{pk}/files`
2. Rewrite the transducer to work properly for both federated and unfederated paths.
3. Defer and consider what to do about the fact that it is rather easy to bypass access control and get to any resource file (read-only) through this mechanism. **Apps are now using this mechanism, and anything we do to address this will break them.**

I am stuck here. This is not an ideal solution because of the lack of access control, but slapping access control onto these at this late date **will break apps.**  Meanwhile, there is a need for consistency in what we're providing to apps. Since they get urls of this form in `resourcemap.xml`, it is only fitting that we conform to these URLs in the "rest" of the REST API (pun intended).

**Comment by hyi** [comment]
@alvacouch Access control is indeed enforced in django irods download view function, so you cannot download any file if you don't have at least view permission. You will get a page that indicates ```You do not have permission to download this resource!```

**Comment by hyi** [comment]
@alvacouch I think federated resource file download urls have the same pattern as unfederated counterparts since internally in the download view function, we check whether the resource is federated or not based on resource id and then serve files accordingly. Did you test and see it does not work? I am pretty sure it used to work.

**Comment by pkdash** [comment]
@hyi You are right on the access control as it relates to file download.

@alvacouch 

> AFAIK There is no evidence of access control on this transduction

Are you referring to the mapper view function? The mapper view function currently checks for access.

**Comment by alvacouch** [comment]
@hyi Ok I will check out django_irods for the protections. I didn't know to look there. Thanks! 

The current code uses unfederated logic to invoke the mapping. E.g., `IrodsStorage().url(stuff)` rather than `IrodsStorage("federated").url(stuff)`. Is this appropriate?

**Comment by hyi** [comment]
@alvacouch The current code logic you indicated will work in production environment where IrodsStorage() and IrodsStorage("federated") actually refers to the same irods storage session object, however, it will not work in local development environment where federation is not set up or not set up correctly. Since we allow the same code base to work in both non-federated environment and federated environment, the parameter "federated" is needed to make sure it works in environments where federation is not set up correctly. This was especially true when I initially developed federation related code when no federation test environment is set up so I was using production wwwHydroProxy to test in my local development environment while trying not to mess up with our production environment. That said, the current code base and federation-related settings in local_settings.py can definitely be much simplified in we ensure only federation environment, for example, using irods federated local containers. Hope this makes sense.

**Comment by pkdash** [comment]
I think the following change in the mapper function should work (capture resource from call to the authorize function)

```istorage = resource.get_irods_storage()```

**Comment by alvacouch** [comment]
@hyi @pkdash There is one inconsistency that I do not understand how to resolve. 

The way to build a URL for a file should be: 
```
reverse('get_resource_file',
             kwargs={ 'shortkey': self.resource.short_id,
                             'path': self.short_path } )
```
This puts in a trailing slash, because the pattern in resourcemap_urls.py is: 
```
    url(r'^resource/(?P<shortkey>[A-z0-9]+)/data/contents/(.*)/$', views.file_download_url_mapper,
        name='get_resource_file'),
```
If I use `reverse`, tests not expecting that trailing slash fail. 

Which should I return? Trailing slash or no trailing slash?

**Comment by hyi** [comment]
@alvacouch Since the url mapping defines the url with a trailing slash, I think it should return the url with trailing slash, otherwise, it will not work. Trailing slash makes a big difference, without it, the view function will not be mapped to according to the url RE mapping.

**Comment by pkdash** [comment]
All our url patterns have a trailing slash. So I guess we have to fix the failing tests.

**Comment by alvacouch** [comment]
My guess is that the former file lister -- which wasn't done to best practices -- didn't put in the slash. 
Will fix tests.

**Comment by pkdash** [comment]
@alvacouch hs_restclient uses trailing slash everywhere except for specific resource file retrieval. Does that mean we have to fix rest client after your changes?

**Comment by alvacouch** [comment]
@pkdash I will avoid changing `hs_restclient` by accepting trailing / as well as no trailing /.

**Comment by pkdash** [comment]
@alvacouch You mean no changes to hs_restclient.

**Comment by dtarb** [comment]
@alvacouch is this still an issue.

**Comment by alvacouch** [comment]
Substantive changes to the REST API obsolete this issue.
