### ISSUE TITLE
Bulk metadata update for Time Series Resource

### ISSUE THREAD

**Issue by pkdash** [hydroshare/hydroshare#2028]
The ```TimeSeriesMetaData``` class needs to extend the base class ```update()``` to support resource specific metadata update. This ```update()```  function is used by REST api.

**Comment by dtarb** [comment]
@pkdash is this still an issue given composite resource work.

**Comment by horsburgh** [comment]
This issue is old, and I don't know whether it is still relevant. I'm going to close it as stale.
