### ISSUE TITLE
Got error when removing multiple folders from Composite resource

### ISSUE THREAD

**Issue by zhiyuli** [hydroshare/hydroshare#2029]
I have a composite res that has multiple folders, and each folder contains multiple files (nc files). When I selected multiple folders and tried to remove them, a error message showed up. After refreshing the page, I found the folders I selected actually got removed. Looks like this is a 'fake' error message, or it is suggesting some other issues? 
https://www.hydroshare.org/resource/271d64a09da9460c919603b7bd5e9b29/ 

![image](https://cloud.githubusercontent.com/assets/10070599/25294428/688a55ca-269c-11e7-9859-7daf0b7d643b.png)

**Comment by zhiyuli** [comment]
OK, I found I could not download its bag any longer. I clicked "please click here" but nothing got downloaded...

https://www.hydroshare.org/resource/271d64a09da9460c919603b7bd5e9b29/

**Comment by pkdash** [comment]
I was able to download the file.

**Comment by zhiyuli** [comment]
@pkdash 
I can download it now as well...

**Comment by dtarb** [comment]
@zhiyuli please check if this is still an issue on beta, and if not, close

**Comment by zhiyuli** [comment]
@dtarb 
The folders and files seemed to get remove successfully. But I still saw a error message, and its contents are different from last time.
![image](https://cloud.githubusercontent.com/assets/10070599/25633204/967bfd22-2f33-11e7-940a-1c53415eed3b.png)

Folder Deletion Failed
DoesNotExist at /hsapi/_internal/data-store-delete-folder/ GenericFileMetaData matching query does not exist. Request Method: POST Request URL: https://beta.hydroshare.org/hsapi/_internal/data-store-delete-folder/ Django Version: 1.8.14 Python Executable: /usr/local/bin/python2 Python Version: 2.7.11 Python Path: ['/hydroshare', '/usr/local/bin', '/src/python-irodsclient', '/hydroshare', '/usr/local/lib/python27.zip', '/usr/local/lib/python2.7', '/usr/local/lib/python2.7/plat-linux2', '/usr/local/lib/python2.7/lib-tk', '/usr/local/lib/python2.7/lib-old', '/usr/local/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/site-packages', '/hydroshare'] Server time: Tue, 2 May 2017 18:32:49 +0000 Installed Applications: (u'mezzanine.boot', u'test_without_migrations', u'autocomplete_light', u'django.contrib.auth', u'oauth2_provider', u'corsheaders', u'django.contrib.contenttypes', u'django.contrib.redirects', u'django.contrib.sessions', u'django.contrib.sites', u'django.contrib.sitemaps', u'django.contrib.gis', u'django.contrib.postgres', u'inplaceeditform', u'django_nose', u'django_irods', u'theme', u'theme.blog_mods', u'heartbeat', u'mezzanine.conf', u'mezzanine.core', u'mezzanine.generic', u'mezzanine.blog', u'mezzanine.forms', u'mezzanine.pages', u'mezzanine.galleries', u'crispy_forms', u'mezzanine.accounts', u'mezzanine.mobile', u'haystack', u'jquery_ui', u'rest_framework', u'robots', u'hs_core', u'hs_access_control', u'hs_labels', u'hs_metrics', u'irods_browser_app', u'hs_geo_raster_resource', u'ref_ts', u'hs_app_timeseries', u'widget_tweaks', u'hs_app_netCDF', u'hs_model_program', u'hs_modelinstance', u'hs_tools_resource', u'hs_swat_modelinstance', u'hs_geographic_feature_resource', u'hs_script_resource', u'hs_sitemap', u'hs_collection_resource', u'hs_modflow_modelinstance', u'hs_tracking', u'hs_file_types', u'hs_composite_resource', u'security', u'debug_toolbar', u'filebrowser_safe', u'grappelli_safe', u'django.contrib.admin', u'django.contrib.staticfiles', u'django_comments') Installed Middleware: (u'django.contrib.sessions.middleware.SessionMiddleware', u'django.middleware.locale.LocaleMiddleware', u'django.contrib.auth.middleware.AuthenticationMiddleware', u'corsheaders.middleware.CorsMiddleware', u'django.middleware.common.CommonMiddleware', u'django.middleware.csrf.CsrfViewMiddleware', u'django.contrib.messages.middleware.MessageMiddleware', u'mezzanine.core.request.CurrentRequestMiddleware', u'mezzanine.core.middleware.RedirectFallbackMiddleware', u'mezzanine.core.middleware.TemplateForDeviceMiddleware', u'mezzanine.core.middleware.TemplateForHostMiddleware', u'mezzanine.core.middleware.AdminLoginInterfaceSelectorMiddleware', u'mezzanine.core.middleware.SitePermissionMiddleware', u'mezzanine.pages.middleware.PageMiddleware', u'hs_core.robots.RobotFilter', u'hs_tracking.middleware.Tracking', u'debug_toolbar.middleware.DebugToolbarMiddleware') Traceback: File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response 132. response = wrapped_callback(request, *callback_args, **callback_kwargs) File "/hydroshare/hs_core/views/resource_folder_hierarchy.py" in data_store_remove_folder 378. remove_folder(user, res_id, folder_path) File "/hydroshare/hs_core/views/utils.py" in remove_folder 712. remove_irods_folder_in_django(resource, istorage, coll_path, user) File "/hydroshare/hs_core/views/utils.py" in remove_irods_folder_in_django 583. post_delete_file_from_resource.send(sender=resource.__class__, resource=resource) File "/usr/local/lib/python2.7/site-packages/django/dispatch/dispatcher.py" in send 189. response = receiver(signal=self, sender=sender, **named) File "/hydroshare/hs_composite_resource/receivers.py" in post_delete_file_from_resource_handler 46. update_resource_coverage_element(resource) File "/hydroshare/hs_file_types/utils.py" in update_resource_coverage_element 10. if lf.metadata.spatial_coverage is not None] File "/usr/local/lib/python2.7/site-packages/django/db/models/fields/related.py" in __get__ 614. rel_obj = qs.get() File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py" in get 334. self.model._meta.object_name Exception Type: DoesNotExist at /hsapi/_internal/data-store-delete-folder/ Exception Value: GenericFileMetaData matching query does not exist. Request information: GET: No GET data POST: res_id = u'271d64a09da9460c919603b7bd5e9b29' folder_path = u'data/contents/forcing_short_range' FILES: No FILES data COOKIES: csrftoken = 'fsHi33VkYZ3oG5EbYGt2u1m07ANAcGVh' sessionid = 'mlsqknh91qkdzy7el8cszilllr0ixsmi' _ga = 'GA1.2.355875342.1493069068' _gat = '1' _gid = 'GA1.2.997379029.1493749941' META: HTTP_REFERER = 'https://beta.hydroshare.org/resource/271d64a09da9460c919603b7bd5e9b29/' SERVER_SOFTWARE = 'gunicorn/19.6.0' SCRIPT_NAME = u'' HTTP_X_CSRFTOKEN = 'fsHi33VkYZ3oG5EbYGt2u1m07ANAcGVh' REQUEST_METHOD = 'POST' PATH_INFO = u'/hsapi/_internal/data-store-delete-folder/' HTTP_ORIGIN = 'https://beta.hydroshare.org' SERVER_PROTOCOL = 'HTTP/1.0' QUERY_STRING = '' HTTP_X_REAL_IP = '128.187.112.19' CONTENT_LENGTH = '89' HTTP_USER_AGENT = 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.81 Safari/537.36' HTTP_CONNECTION = 'close' HTTP_COOKIE = 'sessionid=mlsqknh91qkdzy7el8cszilllr0ixsmi; _gat=1; csrftoken=fsHi33VkYZ3oG5EbYGt2u1m07ANAcGVh; _ga=GA1.2.355875342.1493069068; _gid=GA1.2.997379029.1493749941' SERVER_NAME = 'beta.hydroshare.org' REMOTE_ADDR = '' wsgi.url_scheme = 'https' SERVER_PORT = '443' HTTP_X_REQUESTED_WITH = 'XMLHttpRequest' HTTP_X_FORWARDED_PROTO = 'https' wsgi.input = HTTP_HOST = 'beta.hydroshare.org' wsgi.multithread = False HTTP_ACCEPT = '*/*' wsgi.version = RAW_URI = '/hsapi/_internal/data-store-delete-folder/' wsgi.run_once = False wsgi.errors = wsgi.multiprocess = True HTTP_ACCEPT_LANGUAGE = 'en-US,en;q=0.8' gunicorn.socket = CONTENT_TYPE = 'application/x-www-form-urlencoded; charset=UTF-8' HTTP_X_FORWARDED_FOR = '128.187.112.19' wsgi.file_wrapper = '' CSRF_COOKIE = u'fsHi33VkYZ3oG5EbYGt2u1m07ANAcGVh' HTTP_ACCEPT_ENCODING = 'gzip, deflate, br' Settings: Using settings module hydroshare.settings TESTING = False SECURE_REDIRECT_EXEMPT = [] MONTH_DAY_FORMAT = 'F j' INPLACE_SAVE_URL = u'/hsapi/save_inline/' DEV_SERVER = False IRODS_PORT = '1247' IRODS_ROOT = '/tmp' CSRF_COOKIE_SECURE = False CELERY_DEFAULT_QUEUE = 'default' LANGUAGE_CODE = u'en' ROOT_URLCONF = u'hydroshare.urls' MANAGERS = BROKER_URL = 'amqp://guest:guest@172.17.0.178:5672//' SOLR_HOST = '172.17.0.176' HS_USER_ZONE_PROXY_USER_DELETE_USER_CMD = '/home/betaLinuxProxy/delete_user.sh' SILENCED_SYSTEM_CHECKS = [] DEFAULT_CHARSET = 'utf-8' CELERY_DEFAULT_EXCHANGE_TYPE = 'topic' SESSION_SERIALIZER = 'django.contrib.sessions.serializers.JSONSerializer' IRODS_BAGIT_POSTFIX = 'zip' COMMENTS_USE_RATINGS = True USE_THOUSAND_SEPARATOR = False ALLOWED_HOSTS = '*' TEMP_FILE_DIR = u'/hs_tmp' HYRAX_SCRIPT_RUN_COMMAND = '' RABBITMQ_PORT = '5672' USE_CROSSREF_TEST = True EMAIL_SUBJECT_PREFIX = '[Django] ' IPYTHON_SETTINGS = [] REDIS_PORT = 6379 SECURE_HSTS_SECONDS = 31536000 CELERY_RESULT_SERIALIZER = 'json' RABBITMQ_HOST = '172.17.0.178' SESSION_CACHE_ALIAS = 'default' DOCKER_URL = 'unix://docker.sock/' RESOURCE_LOCK_TIMEOUT_SECONDS = 300 SESSION_COOKIE_NAME = 'sessionid' PACKAGE_NAME_GRAPPELLI = u'grappelli_safe' TIME_INPUT_FORMATS = IRODS_ZONE = 'hydrotestZone' DATABASES = {'default': {'ENGINE': 'django.contrib.gis.db.backends.postgis', 'AUTOCOMMIT': True, 'ATOMIC_REQUESTS': False, 'NAME': 'postgres', 'CONN_MAX_AGE': 0, 'TIME_ZONE': 'UTC', 'PORT': 5432, 'HOST': '172.17.0.175', 'USER': 'postgres', 'TEST': {'COLLATION': None, 'CHARSET': None, 'NAME': None, 'MIRROR': None}, 'PASSWORD': u'********************', 'OPTIONS': {}}} EMAIL_SSL_KEYFILE = u'********************' TEMPLATE_DEBUG = False FILE_UPLOAD_DIRECTORY_PERMISSIONS = None PREPEND_WWW = False FILE_UPLOAD_PERMISSIONS = 420 POSTGIS_DB = 'postgres' FILE_UPLOAD_HANDLERS = TEMPLATE_CONTEXT_PROCESSORS = DEFAULT_CONTENT_TYPE = 'text/html' IRODS_CWD = '/hydrotestZone/home/betaDataProxy' TEST_WITHOUT_MIGRATIONS_COMMAND = u'django_nose.management.commands.test.Command' CARTO_HOME = '/hs_tmp/node_modules/carto' TEST_RUNNER = u'hs_core.tests.runner.CustomTestSuiteRunner' DEFAULT_EXCHANGE = APPEND_SLASH = True FIRST_DAY_OF_WEEK = 0 DATABASE_ROUTERS = [] DEFAULT_TABLESPACE = '' POSTGIS_PASSWORD = u'********************' RATINGS_ACCOUNT_REQUIRED = True CACHES = {'default': {'BACKEND': 'django.core.cache.backends.locmem.LocMemCache'}} CELERY_DEFAULT_ROUTING_KEY = u'********************' SERVER_EMAIL = 'root@localhost' SESSION_COOKIE_PATH = '/' USE_X_FORWARDED_HOST = False HS_BAGIT_README_FILE_WITH_PATH = 'docs/bagit/readme.txt' POSTGIS_PORT = 5432 SECURE_CONTENT_TYPE_NOSNIFF = True MIDDLEWARE_CLASSES = USE_I18N = False THOUSAND_SEPARATOR = ',' IRODS_AUTH = 'fa9ohzeecheethooChie3baecoo4aeph' REST_FRAMEWORK = {u'DEFAULT_PAGINATION_CLASS': u'rest_framework.pagination.PageNumberPagination', u'PAGE_SIZE_QUERY_PARAM': u'PAGE_SIZE', u'EXCEPTION_HANDLER': u'rest_framework.views.exception_handler', u'PAGE_SIZE': 100, u'DEFAULT_AUTHENTICATION_CLASSES': (u'rest_framework.authentication.BasicAuthentication', u'rest_framework.authentication.SessionAuthentication', u'oauth2_provider.ext.rest_framework.OAuth2Authentication')} LANGUAGE_COOKIE_NAME = 'django_language' FILE_UPLOAD_TEMP_DIR = u'/hs_tmp' HS_IRODS_LOCAL_ZONE_DEF_RES = 'betaLocalResc' LOGGING_CONFIG = 'logging.config.dictConfig' HS_LOCAL_PROXY_USER_IN_FED_ZONE = 'betaUserProxy' ADMINS = TEMPLATE_LOADERS = TRACKING_PROFILE_FIELDS = [u'title', u'user_type', u'subject_areas', u'public', u'state', u'country'] WSGI_APPLICATION = None SETTINGS_MODULE = 'hydroshare.settings' REDIS_CONNECTION = Redis>> X_FRAME_OPTIONS = u'deny' CSRF_COOKIE_NAME = 'csrftoken' HAYSTACK_CONNECTIONS = {u'default': {u'ENGINE': u'haystack.backends.solr_backend.SolrEngine', u'URL': u'http://172.17.0.176:8983/solr'}} CELERY_DEFAULT_EXCHANGE = 'tasks' OAUTH2_PROVIDER = {u'ACCESS_TOKEN_EXPIRE_SECONDS': u'********************'} FORCE_SCRIPT_NAME = None IRODS_DEFAULT_RESOURCE = 'betaReplResc' EMAIL_TIMEOUT = None SECURE_SSL_HOST = None SIGNING_BACKEND = 'django.core.signing.TimestampSigner' SESSION_COOKIE_SECURE = False HS_WWW_IRODS_ZONE = 'hydrotestZone' IRODS_GLOBAL_SESSION = True USE_SOUTH = False PROJECT_DIRNAME = 'hydroshare' REDIS_HOST = '172.17.0.177' SECURE_BROWSER_XSS_FILTER = False CSRF_COOKIE_DOMAIN = None FILE_CHARSET = 'utf-8' DEBUG = True COMMENTS_APP = u'mezzanine.generic' LANGUAGE_COOKIE_DOMAIN = None DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage' INSTALLED_APPS = HYRAX_SSH_HOST = '' HS_WWW_IRODS_PROXY_USER = 'betaDataProxy' USE_L10N = False YEAR_MONTH_FORMAT = 'F Y' STATIC_ROOT = u'/hydroshare/hydroshare/static' SECURE_HSTS_INCLUDE_SUBDOMAINS = False STATICFILES_DIRS = CSP_DICT = {u'script-src': [u'self', u'*.google.com', u'*.googleapis.com', u'*.rawgit.com', u'*.cloudflare.com', u'*.datatables.net ', u'*.github.io', u"'sha256-knR/FBinurfPQntk2aEOJBVdKTB+jAzLBk5er9r0rEI='", u"'sha256-s9/ymLoZ5XUQCLrYU4LA0197Ys8F+MChBBmMgWyBUm4='", u"'sha256-r8WSQMRpNued376HSguoGRJRnDD1TXEdhbfJ9agQytA='", u"'sha256-EeeHsgrKQ0j+QXY9+NqkhS9pB8fZ4iPEiytjK3sVD/k='", u"'sha256-JB94IjPO9ws/1kVTgg5lq3sUp/3Yt/1gm4wx82JRCVE='", u"'sha256-5ps1OUcNv+F/rpDQlMFLOuF67quHYXVbFf9yOJNjqaw='", u"'sha256-ptl8NJjRX6En62nAGX95mPmBq5Zq1p7JIsTIzhM+s3Q='", u"'sha256-ukGEpm76ZWGDlDStysCDbVRJgILWSgR1XiInXHpnqeo='", u"'sha256-1pdWRQ5pLai42G3EWfkHyJXR4TFGVlzxJHpNF89iLTQ='", u"'sha256-C8FeZKK7Sju/xx6ArM4j9W2/TcxCpb2IPSHJeqVK3hg='", u"'sha256-/dNLhMcPPsv9gDusbsJ+xgTBKgl67iqN75nRsJwY1y8='", u"'sha256-Fj+sWytTahUAg3Na/4zjY6QnSNhwgFsnz4JxbA2vzcw='", u"'sha256-JCBsts/37Jx84rU5noLWawBDCAgz9kEjdmJQN3jBY8k='", u"'sha256-04T2hHmvLBivvYNrvZCsJi3URODWHuMDbrtYi3CIfB4='", u"'sha256-DC3munJ0pghuoA4hX8dh32935FOMe4Ek0lEToguPh04='", u"'sha256-NDFP8wAl44R2n9vT1corxoEbvzy3cusyeGupfuQ1U0c='", u"'sha256-PA1G79Xx6LLYGxSPHSieelZ8bBLAWIMgD/XXawZp7qU='", u"'sha256-mCQxt+MP+ovw3u4TQgt01msH6eqt4mSVB0Qu2YWWMTg='", u"'sha256-JvKBe3eX3y4VMRRoZ6gtD3NERM2ie6izqcfCYApav2Y='", u"'sha256-TxuSliz/loxO7gZryrQvb0iCfYpUhvSaFj/6Td2gWFQ='", u"'sha256-45pN/AJ0kQzJz9vwICzvV3MnuOG8gtGxggQwABWnymA='", u"'sha256-obaP6XgYiPObVeZTvXdVlgt809T2Dm6PIk16JE30820='", u"'sha256-X48Mhnt413YPDQKQ1WJRKySArZrDCn1RHfPwUz3f1n8='", u"'sha256-4xP5qvZtoBaEfC9gZ43CQp8bEku+/CZOsq9FaRvF7OU='", u"'sha256-mZcvwmv6hKtoYTrQMxgb/EQ337dAnjIahuJ3pleT24M='", u"'sha256-DkOZu61D7CazmSXGaEnSn2z9djJ8MykUT8DxDGQdjbs='", u"'sha256-DkOZu61D7CazmSXGaEnSn2z9djJ8MykUT8DxDGQdjbs='", u"'sha256-rkLuhOrYkT+nja4WGqG4TPLui5JaWiPDYJJ8UCuslJw='", u"'sha256-LvGubOm7HawnJzw+vOyACi6DYfal1wKpJYCE7KN/XDI='", u"'sha256-5tQ8oYGMvQerAFL7X6FcoOun/fzsYLKwBeMevN0pth8='", u"'sha256-wwXL5J3dFy1OlT0B3+GEak+gfFt97tLZtgA03Ww5uKU='", u"'sha256-jZ0Oc9ZvtRDz3fu+52erC3krRmxFNM123/clxHqXT6I='", u"'sha256-5SxuHuYxmlu7rNBznCkw0RTE+ONtAqVChmyV8gMsnyM='", u"'sha256-fH3rM69L3MlQuLHwmENXZ9SSP9u+7mECRGOpE5pY/Hw='", u"'sha256-7Xlpbhi2uHJajOb377ImeVoPP2wXatX9zj+Yr/DS0qA='", u"'sha256-4rt4xlh501T8mF5LZkGs/NIyq3fs7igdd8csZexAN8I='", u"'sha256-daEdpEyAJIa8b2VkCqSKcw8PaExcB6Qro80XNes/sHA='", u"'sha256-j91bFxk70pyBgSjXdJizPOSoYZaC0Zt+fq9U4OF/npQ='", u"'sha256-ZWirjyeue1OSyGpYxoRjbS2NRwKf/b/XZiYaHuUV6Wc='", u"'sha256-rQJ6epAwyFQxC0sb4uq4sgIKJLr2jP19K4M0Bork7kM='", u"'sha256-hH6THo5mChVoQ5wrDhew4wuTZxOayUnEJC3U1SK80VQ='", u"'sha256-fUjKhLcjxDsHY0YkuZGJ9RcBu+3nIlSqpSUI9biHAJw='", u"'sha256-7ydyyMhpPIo0fTHZtxmllQ+MJpMVM299EkUKAf0K1hs='"], u'style-src': [u'self', u'unsafe-inline', u'*.googleapis.com', u'*.bootstrapcdn.com', u'*.datatables.net', u'*.cloudflare.com ', u'*.github.io'], u'default-src': [u'none'], u'frame-src': [u'self', u'*.hydroshare.org'], u'img-src': [u'self', u'data:', u'*.datatables.net', u'*.googleapis.com', u'*.gstatic.com', u'*.google.com'], u'connect-src': [u'self', u'*.github.com'], u'font-src': [u'self', u'*.gstatic.com', u'*.bootstrapcdn.com']} CROSSREF_LOGIN_PWD = '' HS_USER_IRODS_ZONE = 'hydroshareuserdevZone' PASSWORD_RESET_TIMEOUT_DAYS = u'********************' LANGUAGE_COOKIE_AGE = None IPYTHON_BASE = '/hydroshare/static/media/ipython-notebook' DEBUG_PROPAGATE_EXCEPTIONS = False INTERNAL_IPS = u'127.0.0.1' APPS_TO_NOT_RUN = HYDROSHARE_SHARED_TEMP = '/shared_tmp' PERMISSIONS_DB = Redis>> LOGIN_URL = '/accounts/login/' SESSION_EXPIRE_AT_BROWSER_CLOSE = True IRODS_HOST = 'hydrotest.renci.org' CROSSREF_LOGIN_ID = '' WMS_CACHE_DB = Redis>> TIME_FORMAT = 'P' REMOTE_USE_IRODS = True SITE_TITLE = 'HydroShare' POSTGIS_HOST = '172.17.0.175' AUTH_USER_MODEL = 'auth.User' DATE_INPUT_FORMATS = AUTHENTICATION_BACKENDS = u'mezzanine.core.auth_backends.MezzanineBackend' EMAIL_HOST_PASSWORD = u'********************' DEBUG_TOOLBAR_PATCH_SETTINGS = False PACKAGE_NAME_FILEBROWSER = u'filebrowser_safe' AUTH_PROFILE_MODULE = u'theme.UserProfile' SESSION_FILE_PATH = None CACHE_MIDDLEWARE_ALIAS = 'default' DEFAULT_SUPPORT_EMAIL = 'support@hydroshare.org' SESSION_SAVE_EVERY_REQUEST = False STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage' NUMBER_GROUPING = 0 SESSION_ENGINE = 'django.contrib.sessions.backends.db' HS_USER_ZONE_HOST = 'usersdev.hydroshare.org' CSRF_FAILURE_VIEW = 'django.views.csrf.csrf_failure' CSRF_COOKIE_PATH = '/' USE_MODELTRANSLATION = False GRAPPELLI_INSTALLED = True CELERY_TASK_SERIALIZER = 'json' TRACKING_USER_FIELDS = [u'username', u'email', u'first_name', u'last_name'] PROJECT_ROOT = '/hydroshare/hydroshare' DECIMAL_SEPARATOR = '.' CACHE_MIDDLEWARE_KEY_PREFIX = u'********************' ROBOTS_SITEMAP_URLS = [u'http://localhost:8000/sitemap/'] LOCALE_PATHS = TRACKING_SESSION_TIMEOUT = 900 TEMPLATE_STRING_IF_INVALID = '' MESSAGE_STORAGE = u'django.contrib.messages.storage.cookie.CookieStorage' LOGOUT_URL = '/accounts/logout/' EMAIL_USE_TLS = True LOGIN_REDIRECT_URL = '/accounts/profile/' FIXTURE_DIRS = EMAIL_HOST = 'mail.hydroshare.org' DATE_FORMAT = 'N j, Y' IRODS_USERNAME = 'betaDataProxy' OPTIONAL_APPS = MEDIA_ROOT = u'/hydroshare/hydroshare/static/media' LANGUAGE_COOKIE_PATH = '/' DEFAULT_EXCEPTION_REPORTER_FILTER = 'django.views.debug.SafeExceptionReporterFilter' CELERY_ROUTES = 'hs_core.router.HSTaskRouter' FORMAT_MODULE_PATH = None DEFAULT_FROM_EMAIL = 'support@hydroshare.org' HS_WWW_IRODS_PROXY_USER_PWD = 'fa9ohzeecheethooChie3baecoo4aeph' IRODS_BAGIT_PATH = 'bags' HYRAX_SSH_PROXY_USER_PWD = '' MEDIA_URL = u'/static/media/' DATETIME_FORMAT = 'N j, Y, P' TEMPLATE_DIRS = u'/hydroshare/hydroshare/templates' USE_SECURITY = False CELERY_ACCEPT_CONTENT = ['json'] IRODS_ICOMMANDS_PATH = '/usr/bin' SITE_ID = 1 DISALLOWED_USER_AGENTS = ALLOWED_INCLUDE_ROOTS = DOCKER_API_VERSION = u'********************' LANGUAGES_BIDI = LOGGING = {u'loggers': {u'': {u'handlers': [u'hydrosharelog'], u'propagate': False, u'level': u'DEBUG'}, u'django.db.backends': {u'handlers': [u'syslog'], u'propagate': False, u'level': u'WARNING'}, u'django': {u'handlers': [u'syslog', u'djangolog'], u'propagate': True, u'level': u'DEBUG'}}, u'version': 1, u'formatters': {u'simple': {u'datefmt': u'%d/%b/%Y %H:%M:%S', u'format': u'[%(asctime)s] %(levelname)s %(message)s'}, u'verbose': {u'datefmt': u'%d/%b/%Y %H:%M:%S', u'format': u'[%(asctime)s] %(levelname)s [%(name)s:%(lineno)s] %(message)s'}}, u'disable_existing_loggers': False, u'handlers': {u'djangolog': {u'backupCount': 10, u'level': u'DEBUG', u'filename': u'/hydroshare/log/django.log', u'formatter': u'verbose', u'class': u'logging.handlers.RotatingFileHandler', u'maxBytes': 15728640}, u'syslog': {u'backupCount': 10, u'level': u'WARNING', u'filename': u'/hydroshare/log/system.log', u'formatter': u'simple', u'class': u'logging.handlers.RotatingFileHandler', u'maxBytes': 15728640}, u'hydrosharelog': {u'backupCount': 10, u'level': u'DEBUG', u'filename': u'/hydroshare/log/hydroshare.log', u'formatter': u'verbose', u'class': u'logging.handlers.RotatingFileHandler', u'maxBytes': 15728640}}} HS_WWW_IRODS_HOST = 'hydrotest.renci.org' SHORT_DATE_FORMAT = 'm/d/Y' SECRET_KEY = u'********************' TEMPLATES = [] SECURE_PROXY_SSL_HEADER = HS_USER_ZONE_PROXY_USER = 'betaLinuxProxy' SOLR_PORT = u'8983' HS_USER_ZONE_PRODUCTION_PATH = '/hydroshareuserZone/home/localHydroProxy' STATICFILES_FINDERS = IGNORABLE_404_URLS = SECURE_SSL_REDIRECT = False HYRAX_SSH_PROXY_USER = '' CORS_ORIGIN_ALLOW_ALL = True FILE_UPLOAD_MAX_MEMORY_SIZE = 0 HS_USER_ZONE_PROXY_USER_CREATE_USER_CMD = '/home/betaLinuxProxy/create_user.sh' EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend' POSTGIS_USER = 'postgres' POSTGIS_VERSION = EMAIL_USE_SSL = False CRISPY_TEMPLATE_PACK = u'bootstrap' CELERY_QUEUES = -> task.default> MIGRATION_MODULES = {} SESSION_COOKIE_AGE = 1209600 IPYTHON_HOST = '127.0.0.1' NEVERCACHE_KEY = u'********************' USE_ETAGS = False SESSION_COOKIE_DOMAIN = None LANGUAGES = (u'en', u'English') HAYSTACK_SIGNAL_PROCESSOR = u'hs_core.hydro_realtime_signal_processor.HydroRealtimeSignalProcessor' DEFAULT_INDEX_TABLESPACE = '' CSRF_COOKIE_AGE = 31449600 STATIC_URL = u'/static/' USE_IRODS = True IRODS_HOME_COLLECTION = '/hydrotestZone/home/betaDataProxy' EMAIL_PORT = '587' USE_TZ = True SHORT_DATETIME_FORMAT = 'm/d/Y P' COMMENTS_ACCOUNT_REQUIRED = True TEST_NON_SERIALIZED_APPS = [] PASSWORD_HASHERS = u'********************' SESSION_COOKIE_HTTPONLY = True ABSOLUTE_URL_OVERRIDES = {} ADAPTOR_INPLACEEDIT_EDIT = u'hs_core.models.HSAdaptorEditInline' RUN_HYRAX_UPDATE = False HS_USER_ZONE_PROXY_USER_PWD = 'quiiCoh4oogia4patu7eezee9EoMaeke' IRODS_BAGIT_RULE = 'hydroshare/irods/ruleGenerateBagIt_HS.r' CACHE_MIDDLEWARE_SECONDS = 600 EMAIL_SSL_CERTFILE = None DEBUG_TOOLBAR_CONFIG = {u'INTERCEPT_REDIRECTS': False} CSRF_COOKIE_HTTPONLY = False DATETIME_INPUT_FORMATS = TIME_ZONE = 'Etc/UTC' OAUTH2_PROVIDER_APPLICATION_MODEL = u'oauth2_provider.Application' EMAIL_HOST_USER = 'hydroshare@hydroshare.org' You're seeing this error because you have DEBUG = True in your Django settings file. Change that to False, and Django will display a standard page generated by the handler for this status code.

**Comment by pkdash** [comment]
@zhiyuli Can you give me the steps how to reproduce this error?

**Comment by zhiyuli** [comment]
@pkdash 
1) create a composite res with this zip file
https://www.hydroshare.org/django_irods/download/271d64a09da9460c919603b7bd5e9b29/data/contents/nwm.20170419.zip

2) unzip this zip file in edit mode

3) select all or some folders and try removing them

**Comment by pkdash** [comment]
@mauriel133 I think this line here causing this issue:
https://github.com/hydroshare/hydroshare/blob/release-candidate-1.10.0/theme/static/js/hs_file_browser.js#L1124

The JS code trying delete multiple folders at the same time. Is there a way delete folder one after another meaning wait for the response for the first delete then make another call for the next folder in line?

**Comment by pkdash** [comment]
@mauriel133 Never mind. Ignore my comment above related to JS code.

**Comment by pkdash** [comment]
This issue seems to be as a result of race condition when multiple folders are deleted asynchronously from JavaScript. At this point the fix for this issue is not to allow multiple folder deletion from the UI.

**Comment by dtarb** [comment]
@zhiyuli please check if this is fixed in beta deployed 5/8/17.  The "solution" that was implemented is to disallow multiple folder deletions.

**Comment by pkdash** [comment]
@zhiyuli Can you check on beta if this issue has been resolved?

**Comment by pkdash** [comment]
@zhiyuli Can you check on beta if this issue has been resolved? Let me know if you want me check and close.

**Comment by aphelionz** [comment]
@pkdash @zhiyuli Can this be closed?

**Comment by pkdash** [comment]
@aphelionz It should be closed. @zhiyuli Can test and close.

**Comment by aphelionz** [comment]
@zhiyuli Please do so!

**Comment by zhiyuli** [comment]
closed
