### ISSUE TITLE
REST API doesn't respond to URLs that REST calls generate!

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#2030]
@dtarb @pkdash @hyi @danames
**It's time to fix a long-standing problem.** The crux of the problem is that URLs in the responses to `/resource/{pk}/files/` don't actually work when we try to access them. The reason for this is that the listed URLs don't end with trailing slashes, and the REST API as written requires these slashes. The `hs_restclient` fudges things by adding trailing slashes where required. 

I tried -- and failed -- to address this before 1.10.0 by adding a trailing '/' to the responses. This was impractical in the time we have. See discussion in PR #2026. At the same time, there is some thought that we should actually respond to the URLs we're generating, _without_ the '/'s.  

This is practical with just a _little_ more time. 

After 1.10.0, I plan to try to get this to work, with more time to deal with the aftermath before the next release. 

Scope of the problem includes URLs embedded in all REST responses, as well as URLs embedded into `resourcemap.xml`.

**Comment by alvacouch** [comment]
@hyi @pkdash @dtarb After a little thought, I think the way to fix this is to make the REST API respond to **both** trailing slashes and no trailing slashes. That way, the existing URLs embedded in the files and responses will work. This is possible, and just a little tricky: 

* The pattern `^resource/(?P<shortkey>[A-z0-9]+)/data/contents/(?P<path>.+)/?$` matches both trailing slash and no trailing slash. This binds `shortkey` and the file `path`. 
* The pattern `^resource/(?P<shortkey>[A-z0-9]+)/data/(?P<meta>[^/]+)/?$` matches `resource/{shortkey}/data/resourcemetadata.xml` and `resource/{shortkey}/data/resourcemap.xml/` but not `resource/{shortkey}/data/contents/{path}`
* The processing has to be adapted to those matches. 

The trick here -- if you can call it that -- is to ensure that the metadata pattern doesn't match the same things as the file path, so there's no confusion. There is none, because `data/resourcemap.xml` doesn't contain any more slashes than the first, while `data/contents/foo.txt` does.

**Comment by hyi** [comment]
@alvacouch @pkdash @dtarb I think it is a good idea to make REST API respond to both trailing slashes and no trailing slashes. However, rather than changing url map pattern, can we add the trailing slash if it does not exist in REST API view function acting as a top-level wrapper to ensure it can handle the case with no trailing slash?

**Comment by alvacouch** [comment]
@hyi I don't understand the distinction. The best way to map a pattern is to have a regexp that matches. I've given you the regexps. Leaving a regexp unanchored (no $) can lead to conflicts.

**Comment by hyi** [comment]
@alvacouch I know addition of ```?``` at the end of the regex allows the trailing slash optional, but I am not sure whether the trailing slash will be included in the <path> variable in the view function, and thought perhaps some extra check is needed in the view function to determine whether <path> variable contains the trailing slash or not. However, that is a simple test, I am just not sure at this point without debugging. If the new regex pattern works without extra check, I am all for the new regex pattern to make the trailing slash optional. If not, I thought both view function and rest API needs to be the check, so thought it'd be better to make the trailing slashes explicit in regex in this case.

**Comment by alvacouch** [comment]
@hyi The REST API for HydroShare is determined by resourcemap_urls.py, but that remaps to an iRODS URL that **requires the slash**. So far, I have been able to make it optional via (?<path>.*)/?$ which says there can be a / after the stuff bound to path, but then before calling the mapper I have to put it back in or the mapped iRODs path breaks! Since making it optional in the HydroShare REST URLs addresses the problem, this is sufficient. PR forthcoming.

**Comment by dtarb** [comment]
@sblack-usu is this still an issue?

**Comment by sblack-usu** [comment]
I don't know of any work done to resolve this issue and it appears to persist.

**Comment by eclark-cuahsi** [comment]
adding @sblack-usu as well as this issue pertains to HS Core Services. @sblack-usu and @alvacouch is this an issue that should be addressed as a bug and pursued at this time?

**Comment by dtarb** [comment]
After conferring with Alva and Scott, sense was that it is fixed and working.
