### ISSUE TITLE
Log app launches

### ISSUE THREAD

**Issue by Castronova** [hydroshare/hydroshare#2042]
Include logging for app launches so that we can report on their usage in the Kibana metrics.

**Comment by dtarb** [comment]
See also #2023.  I think it is more important to know when apps are working and not, than how much they are used.

**Comment by aphelionz** [comment]
@Castronova Can this be closed?

**Comment by aphelionz** [comment]
@Castronova Closing this as we now have derivative work based on it. Reopen if you need to.
