### ISSUE TITLE
REST endpoint for listing resources should not include obsoleted resources

### ISSUE THREAD

**Issue by pkdash** [hydroshare/hydroshare#2045]
Older resource versions should not be returned by REST API. It seems code change needs to be made in the internal API. No change is needed in rest endpoint.

**Comment by dtarb** [comment]
Is this related to #1988.

**Comment by horsburgh** [comment]
@pkdash - just to clarify - I should be able to request to download an old version of a resource via the API, but any listing/discovery API methods would only list the most recent version right?

**Comment by hyi** [comment]
@pkdash Which resource list are you talking about here? The obsoleted resources did get filtered out from get_my_resources_list() as shown here: https://github.com/hydroshare/hydroshare/blob/develop/hs_core/views/utils.py#L369-L370

Is there another resource listing function REST API is using?

**Comment by pkdash** [comment]
@hyi The REST endpoint uses this internal api: https://github.com/hydroshare/hydroshare/blob/develop/hs_core/hydroshare/users.py#L246

**Comment by hyi** [comment]
@pkdash OK. I will fix this internal api to exclude obsoleted resources.

**Comment by hyi** [comment]
@aphelionz This has been merged into develop, but has not been verified. @pkdash Can you verify and close this issue if it is indeed fixed?

**Comment by pkdash** [comment]
@hyi it seems to work on beta (release 1.11). So closing.
