### ISSUE TITLE
Create Resource Page - Resource Type dropdown indicator

### ISSUE THREAD

**Issue by mauriel133** [hydroshare/hydroshare#2048]
From Liza

> Hi,
Tony cued me in on working in beta to update the documentation by next week. I noticed something right off the bat that I’m wondering about- when I click create resource, the default resource type is Composite and the button doesn’t look like a drop down. I’m nervous that new users will automatically choose composite without knowing there are other options.
Thought?

I will be adding a dropdown indicator to this button.

**Comment by dtarb** [comment]
See also #74 comments at the end.

**Comment by dtarb** [comment]
tested on beta
