### ISSUE TITLE
Multidimensional file in composite resource results in blank screen for landing page

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#2060]
I added a multidimensional (netCDF) file to a composite resource.  I then set multidimensional data file type.

I received the following blank screen
![image](https://cloud.githubusercontent.com/assets/3456833/25556255/9d8f01c4-2cb6-11e7-843e-859c90518d27.png)

I was able to refresh and see the resource landing page.

**Comment by pkdash** [comment]
@dtarb I am trying to reproduce this issue. I created a new empty composite resource and then added a netcdf file. Then set the file type. I did not see this issue happening. I also tried to add a netcdf file to an old composite resource and set file type. There also I did not see this issue.

**Comment by dtarb** [comment]
I am not able to reproduce either now, so perhaps we should close this and keep an eye out for it again.
