### ISSUE TITLE
Create resource messages repetative regarding irods

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#2061]
![image](https://cloud.githubusercontent.com/assets/3456833/25556182/90635cf8-2cb5-11e7-9208-105c926b5ace.png)

I suggest changing the wording above to:
Files uploaded directly from a browser are limited to 1 GB per file.

Use iRODS to add files larger than 1 GB.  Any iRODS server may be used.  If you do not have an account on an iRODS server you can create a HydroShare iRODS account from your [User Profile Page](https://beta.hydroshare.org/user/#/). 

See [Creating and Managing Resources](https://pages.hydroshare.org/creating-and-managing-resources/) for more information on working with iRODS directly.

**Comment by aphelionz** [comment]
@Maurier Can this be closed if the PR is merged?

**Comment by Maurier** [comment]
This work has been merged, so we can close this.

**Comment by aphelionz** [comment]
@Maurier thank you
