### ISSUE TITLE
A composite resource can get into a state where a netcdf file is not recognized for setting as multidimensional file type

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#2062]
Testing on beta.hydroshare.org candidate release I did the following:
Created a composite resource and added two files (geographic raster and netcdf).  I then used Set Geographic raster on the geographic raster file.  I then deleted the folder holding the raster file type.
The result is a resource with a single netcdf file but it is in a state where "set multidimensional data file type" that should be enabled for netcdf files is not enabled.

Also the resource has a message "You must add content files to your resource before it can be published, public or discoverable", but there is a content file.  The resource is https://beta.hydroshare.org/resource/def9d27b0c6d464eb22a617235410b2c/

**Comment by pkdash** [comment]
> The result is a resource with a single netcdf file but it is in a state where "set multidimensional data file type" that should be enabled for netcdf files is not enabled.

Looking at the release candidate code, it seem this bug got introduced as part of the RespourceFile api work. I think I know how to fix it and will be creating a hotfix PR.

**Comment by dtarb** [comment]
Tested on beta
