### ISSUE TITLE
multidimensional file metadata Spatial reference string does not wrap and is not displayed properly

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#2063]
![image](https://cloud.githubusercontent.com/assets/3456833/25556554/c54e6c4a-2cbb-11e7-8420-c78da187f5af.png)

**Comment by mauriel133** [comment]
@dtarb, could you provide a link to this resource?

**Comment by dtarb** [comment]
https://beta.hydroshare.org/resource/4e26d640a1224559b802fa62dc6b3e42/.  Look at file metadata in non edit mode.

**Comment by pkdash** [comment]
@mauriel133 This html code is generated in python  here: https://github.com/hydroshare/hydroshare/blob/release-candidate-1.10.0/hs_app_netCDF/models.py#L170

**Comment by dtarb** [comment]
tested on beta
