### ISSUE TITLE
Adding composite resource file metadata key value gives error

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#2064]
I created a composite resource.  I added a file and set it to geographic raster type.  I added a Key/Value extended metadata element.  The message: "Error! Update failed.  Key already exists" is displayed.  This was for a new Key that did not exist before, and the Key/Value appears to be added, so it is just the message that is spurious.

**Comment by pkdash** [comment]
I have seen this before. However, I have not been able track this bug as it is not easily reproducible. I think @gantian127 has created this issue originally. Will try again to see if I can fix it.

**Comment by dtarb** [comment]
Verified working on beta as deployed now.
