### ISSUE TITLE
Sync up pages.hydroshare.org footer with www.hydroshare.org footer

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#2065]
The footer of pages.hydroshare.org footer needs to show the correct version and information consistent with www.hydroshare.org 

![image](https://cloud.githubusercontent.com/assets/3456833/25556759/f01e6250-2cbf-11e7-80e4-382bcbb1e050.png)

**Comment by mjstealey** [comment]
@mauriel133 - This seems to be coming from a theme template rather than parameters of a mezzanine page named "home". If you could update this to be 1.10.0 and I'll denote what file this was for future reference.

**Comment by dtarb** [comment]
This is correct as currently deployed.  Closing, while noting that I am uncertain whether this is a manual or automated syncing configuration, and if manual a separate issue to ensure automated syncing may be required.
