### ISSUE TITLE
Beta 1.10: Format of Temporal Coverage Messed Up

### ISSUE THREAD

**Issue by horsburgh** [hydroshare/hydroshare#2066]
Testing time series resource on beta.hydroshare.org - the format of the temporal coverage is messed up.  It should be:

mm/dd/yyyy hh:mm:ss

Instead - this is what is currently shown:

![image](https://cloud.githubusercontent.com/assets/3485902/25557154/e912544a-2cc8-11e7-8d86-eee397511a57.png)

**Comment by dtarb** [comment]
@horsburgh to test and close if OK

**Comment by horsburgh** [comment]
This seems to be fixed on beta.hydroshare.org. Closing.
