### ISSUE TITLE
Beta 1.10: Edit and Delete Icons for Extended Metadata Elements Inconsistent

### ISSUE THREAD

**Issue by horsburgh** [hydroshare/hydroshare#2067]
Testing on beta.hydroshare.org - the icons for editing and deleting an extended metadata element look like this:

![image](https://cloud.githubusercontent.com/assets/3485902/25557218/84befca8-2cca-11e7-91d8-319dd06a8bad.png)

The icons for the same function elsewhere on the page look like this:

![image](https://cloud.githubusercontent.com/assets/3485902/25557223/91198b08-2cca-11e7-9927-6c7ae5215d91.png)

I suspect these just need to be updated.

**Comment by dtarb** [comment]
@horsburgh to test and close if OK

**Comment by horsburgh** [comment]
Looks good on beta. Closing.
