### ISSUE TITLE
Beta 1.10: Editing Site Elevation Throws Error if Decimal

### ISSUE THREAD

**Issue by horsburgh** [hydroshare/hydroshare#2068]
When I try to set the site elevation to a number that is not an integer, I get this error:

![image](https://cloud.githubusercontent.com/assets/3485902/25557246/1374bc26-2ccb-11e7-86f2-c36bd5fea764.png)

I suspect this one has been around for a while and probably doesn't need to be fixed before releasing 1.10, but the Elevation of a site in meters should be a decimal number and not limited to an integer.

**Comment by pkdash** [comment]
At the database level the 'elevation_m' field has been defined as an integer. Will fix it in release 1.11.

**Comment by horsburgh** [comment]
@pkdash - do you mean in the ODM2 SQLite database or the Django database?  I just checked the script that creates the SQLite database and the data type of that field should accept floating point numbers.  Just wondering if this is something I need to fix or if its just a HydroShare implementation thing.

**Comment by pkdash** [comment]
@horsburgh I need to fix this field in Django database.

**Comment by pkdash** [comment]
@horsburgh Can you test and close this?

**Comment by horsburgh** [comment]
This is still not working on www.hydroshare.org. Should I be testing somewhere else?

**Comment by pkdash** [comment]
@horsburgh This should be fixed in next release (1.11) which can be tested now on beta.hydroshare.org

**Comment by horsburgh** [comment]
Appears to work correctly now on www.hydroshare.org. Closing.
