### ISSUE TITLE
Beta 1.10: Open With Button Spacing is Off

### ISSUE THREAD

**Issue by horsburgh** [hydroshare/hydroshare#2069]
Testing on beta.hydroshare.org - Chrome on my Mac. The spacing on the "Open With" button is off. This is what it looks like on Beta:

![image](https://cloud.githubusercontent.com/assets/3485902/25557349/cf6adb8a-2ccc-11e7-9339-33325372bd8f.png)

This is what it looks like on www:

![image](https://cloud.githubusercontent.com/assets/3485902/25557351/d979e97c-2ccc-11e7-924c-46834d67dede.png)

**Comment by dtarb** [comment]
tested on beta
