### ISSUE TITLE
Beta 1:10: Text overflow on user name in Manage Access panel

### ISSUE THREAD

**Issue by horsburgh** [hydroshare/hydroshare#2070]
Testing on beta.hydroshare.org in Chrome on my Mac. I select a user to share with and if the user has a long name, the text overflows the text box:

![image](https://cloud.githubusercontent.com/assets/3485902/25557566/70395f74-2cd1-11e7-8dee-10924f551fb5.png)

I suspect this one has been around for a while.

**Comment by dtarb** [comment]
Tested on beta
