### ISSUE TITLE
Resource creation page: move the multidimensional resource type icon to the geospatial data type list

### ISSUE THREAD

**Issue by gantian127** [hydroshare/hydroshare#2086]
@mauriel133 Would you please move the multidimensional resource type icon after the geo graphic raster resource type ? Thanks for your help.

![image](https://cloud.githubusercontent.com/assets/5016511/25642776/24a38a28-2f59-11e7-9eb9-1d921948c1c4.png)

**Comment by mauriel133** [comment]
Here is what I propose for the order of these items:

![image](https://cloud.githubusercontent.com/assets/2448568/25670504/22096b3e-2fea-11e7-926b-157a44812111.png)

**Comment by mohamedmorsy** [comment]
@mauriel133 I like this. In my opinion, even to include "Resources" for all of the titles or remove it. Just to be consistent.
