### ISSUE TITLE
Add ABOUT to top of pages.hydroshare.org

### ISSUE THREAD

**Issue by mjstealey** [hydroshare/hydroshare#2093]
@mauriel133 - Need to add a link for **ABOUT** at the top of the pages.hydroshare.org site.

Link to associate with **ABOUT**: https://pages.hydroshare.org/about-hydroshare/

Ordering would be:
<img width="779" alt="screen shot 2017-05-03 at 3 55 36 pm" src="https://cloud.githubusercontent.com/assets/5332509/25678795/ff8b05f2-3018-11e7-9a72-9803b090c15c.png">

@ChristinaB can confirm this for placement

**Comment by ChristinaB** [comment]
This looks great.  Thank you!

**Comment by dtarb** [comment]
Implemented on beta

**Comment by mjstealey** [comment]
@dtarb - This issue is for implementation on the pages.hydroshare.org site and must be done from the [https://github.com/hydroshare/hs_pages](hs_pages) repository.

Assigned to @Maurier

**Comment by dtarb** [comment]
This has been deployed.
