### ISSUE TITLE
debugging really complex user interfaces

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#2095]
@dtarb@hyi @pkdash @martinseul @mauriel133
We now have a problem that has been with us for awhile but has lately been expressed in a rather obvious fashion. **Our user interface is really complex.** Thus, **it is really difficult to find defects.** 

I suggest a rather aggressive approach to finding defects in the user interface, which is to be able to "watch for integrity violations" after each operation. This is an "antibugging" approach in which we embed the following calls into the code for the UI after every change in a resource: 

```
if (resource.watch)
    resource.check_integrity(stop_on_error=True) 
```
`check_integrity` will be based upon my current routines for debugging synchronization between iRODS and Django, but will include more comprehensive checks, including metadata integrity (to be developed for 1.11). 

So, to find the bugs that are causing problems for Christina, she can turn on `watch` and then proceed normally, and every operation she does will be checked for whether it results in an error. The good thing about this is that the system will stop when it encounters the _first_ error, in a state where _we have some chance of figuring out exactly what went wrong._

**Comment by dtarb** [comment]
I am OK with this.  How are you proposing that Christina (or any user for that matter) turn on `watch`.  Will this be in their profile.

**Comment by pkdash** [comment]
We may also need to think about keeping provenance  records in DB of at least the critical resource operations (resource create, delete, file add , file delete etc). These resource activities then can be viewed by authorized resource users. I guess we may not have time to do this before the end of this project.

**Comment by alvacouch** [comment]
@dtarb It's per resource, not per user, on the resource landing page. It's just like public or discoverable. 

It is impractical to make it per-user, because many operations on resources don't know who the user is at the time they're performed. 

We could arrange a default for newly created resources on the user profile page. That would be for later. 

For now, we could ask that the people doing the Summer Institute work always turn this on.

**Comment by dtarb** [comment]
OK.  This should probably be enabled on the resource editing page (or landing page in edit mode) as in view mode no changes are made (but a bag can be built by a download request).

I am a bit unclear on how you are planning for this to affect the user experience.  If an integrity check finds a problem, what will the user see.  If the message is something like "Action stopped due to failing resource integrity check", what is a user supposed to do.  Perhaps just report it.  Could the report be sent automatically.  Should the check always be on, because if actions are causing resource integrity problems perhaps we always want the rest of the action stopped.  But if we are concerned that the integrity checker may be fragile and not good for general use, then a watch button seems OK.

**Comment by alvacouch** [comment]
@dtarb The watcher is **expensive**. It takes a **long time** to do the integrity checks. Thus using it will slow down the user's experience, **and** flag errors as they occur. Thus it is not something for general use, but rather, something that people designing a procedure for general use can use to ensure that nothing will go wrong with the procedure.

**Comment by ChristinaB** [comment]
I know a lot of people like Drag and Drop and do all their operations that way.  When I started noticing inconsistency I quickly changed to only using the upload 'here' link.  This is very small below the window and obviously not the main way the interface is designed for users to upload files.    Can we replace the spinning wheel with messages that prevent the users from trying things the system isn't ready for?    Is this issue being addressed by https://github.com/hydroshare/hydroshare/issues/2056 ?  

Or should we continue discussing how to make the interface less complex??   

I agree with @alvacouch that we should not do anything that makes anything slower.  I actually suggest removing any user functionality that is slowing down the browser.   We don't have a user experience data collection system, but I can anecdotally say that users would rather have things happen fast, than have more functions that are rarely used.

**Comment by alvacouch** [comment]
@ChristinaB #2056 does not address the problem of speed.

**Comment by alvacouch** [comment]
Substantive changes in file upload and the UI obsoleted the need for this change.
