### ISSUE TITLE
Unable to edit spatial coverage for geographic raster file type in composite resource

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#2096]
I added a geographic raster that does not have spatial reference information.  I set it as a geographic raster file type.  I receive the warning that spatial coverage metadata is required before making public (good).  I enter edit mode and go to edit spatial coverage.  There are two problems
- [x] There is no save button to click after entering data values (I am using firefox)
- [x] 6 latitude and longitude fields are shown (below).  If a box is selected only the fields labeled North, East, South, West, should be shown.  If a point is selected, only fields Longitude and Latitude should be shown.

![image](https://cloud.githubusercontent.com/assets/3456833/25711598/942a4a86-30ac-11e7-836c-9e72e31dd1c2.png)

**Comment by pkdash** [comment]
@dtarb Do we want this as a hotfix for 1.10.0 or fix it in 1.11?

**Comment by pkdash** [comment]
@dtarb I have fixed this as a hotfix to 1.10. Next time when beta site gets updated, you can test this issue.

**Comment by dtarb** [comment]
Tested on beta and closed
