### ISSUE TITLE
Combine metadata_dirty flag and bag_modified flag into one bag_modified flag

### ISSUE THREAD

**Issue by hyi** [hydroshare/hydroshare#2097]
Having two flags metadata_dirty and bag_modified is confusing and can be simplified into one bag_modified flag. Have discussed this with @pkdash and @alvacouch and we all agreed one flag is better and clearer. I will work on this slated for release 1.11.

**Comment by alvacouch** [comment]
@hyi Might be better to call it `resource_modified` or simply `modified` because it's going to be used both to update the resource files and the bag.

**Comment by hyi** [comment]
@alvacouch Agreed it is probably more accurate to simply call it ```modified``` or ```resource_modified```. On the other hand, since this flag is only checked when the zipped bag is downloaded and the resource is part of the bag, it probably makes sense also to call this flag ```bag_modified``` as whenever a resource is modified regardless whether the modification is metadata or files, the resource bag is modified.

**Comment by pkdash** [comment]
@hyi and @alvacouch Here is my probably stupid question. Why are we keeping this flag (bag_modified) as an AVU in iRODS and not as resource flag (```BaseResource.modified```) in Django?

**Comment by hyi** [comment]
@pkdash @alvacouch I think keeping a flag as a resource flag in Django would serve the same purpose as keeping this flag as a AVU in iRODS. I guess the benefit of keeping it as an AVU flag in iRODS is that it can be easily accessed from iRODS without involving Django migrations if there is an issue with a specific resource during bag creation, and after we fixed the issue, we can simple set this AVU to true for the bag to be regenerated. So from management point of view, it is easier, and also keeping the bag specific metadata close to data where it resides sounds like a better approach. Looping in @mjstealey as well since he may have some perspective regarding this from system devOps point of view.

**Comment by pkdash** [comment]
@hyi What we currently do with the bag_modified AVU I guess it is possible to do the same thing if this flag lived in Django through the management command. But if we have to keep the other flag Is_Public as AVU then we might as well keep the bag_modified as AVU.  I am trying to see if we keep these flags only in Django then we can avoid sync issues between Django and iRODS.

**Comment by hyi** [comment]
@pkdash The other flag is_Public has to stay as AVU since it is used by my script that expose public netcdf resources to hyrax server for THREDDS service. That script runs on a different VM with no access to Django, so is_public flag has to stay as AVU in iRODS. I think we can keep what we have now and there is a possibility bag_modified may need to be accessed out of Django for devOps and/or other potential tasks.

**Comment by pkdash** [comment]
@hyi I assume the 'is_public' AVU is only for exposing the NetCDF resource to hyrax server and it has nothing to do with HydroShare. In that case, can we set this AVU flag using script/management command using a scheduled job?

**Comment by hyi** [comment]
@pkdash This is_public AVU has to be set instantly whenever a netCDF resource is made public or private or discoverable, so the THREDDS service will be exposed on netCDF resource landing page or not depending on its sharing status. So scheduled job won't work.

**Comment by pkdash** [comment]
@hyi I see the function ```run_script_to_update_hyrax_input_files(shortkey))```  where we run the ssh_command passing the resource id. Can't we pass an additional flag ```is_public`` to the ssh command?

**Comment by hyi** [comment]
@pkdash Yes, that can be done, but the script is also scheduled as a cron job to run nightly to initialize the mapped symlinked directory for hyrax server and to clean up mapped public netCDF resources from iRODS fuse mount or NFS mount (pending to work) which will need to loop through all resources and check isPublic AVU flag for clean up. The function ```run_script_to_update_hyrax_input_files(shortkey))``` is for instant update when a user changes sharing status of a public netCDF resource, which is only one case to run the script to update status.

**Comment by pkdash** [comment]
@hyi How does the scrip that runs nightly know which ones are netcdf resources? I may have been asking stupid questions.

**Comment by hyi** [comment]
@pkdash There is resourceType AVU as well that informs what resource type a resource is.

**Comment by pkdash** [comment]
@hyi Got it. Thanks.

**Comment by alvacouch** [comment]
@hyi @pkdash Alas, both flags are necessary. I read the code in the process of troubleshooting the bag download problem. 

1. `metadata_dirty` generates `resourcemetadata.xml` before it is downloaded, **without generating a bag**
2. `bag_modified` generates a bag for bag download; bag generation also checks `metadata_dirty` to figure out whether to generate `resourcemetadata.xml` before generating the bag. 

So, if we combine these, we'll generate a bag every time someone makes a `scimeta` call, which can be potentially quite wasteful.... especially since apps make the `scimeta` call to figure out if they want a bag or not, and don't always download the bag....

I agree that these don't have to be iRODS flags. The reason they are -- as I recall -- was that we were thinking of building the bag generation script into iRODS itself. That -- alas -- proved quite challenging. The reason for that is that more or less all the daa we need for that operation is in Django. 

However, if they're not iRODS flags, we'll need a management command to set them in Django, like the commands I've written before, because setting them to false is part of the server build script.

**Comment by hyi** [comment]
@alvacouch @pkdash I believe we only need one flag if we want to achieve the same functionality we have currently. Yes, ```metadata_dirty``` generates ```resourcemetadata.xml``` as well as ```resourcemap.xml``` since ```created_bag_files()``` create both files currently. I believe ```bag_modified``` flag behavior can be modified to accommodate ```medata_dirty``` flag behavior. Specifically, when the new single ```bag_modified``` flag is ```true```, ```create_bag_files()``` is called to recreate ```resourcemetadata.xml``` in the same way as what happens when the current ```metadata_dirty``` flag is true. In other words, whenever ```bag_modified``` is set to true, it implies ```metadata_dirty```, and while it is set to false, it implies metadata is not dirty which we just need to guarantee in this case, a zipped bag already exists which allows direct bag download. I believe this can be done, but let me know if you can think of other cases where one flag is not sufficient. Note with one flag implementation, the current bag_modified behavior will be modified to make sure bag_modified flag accommodates metadata_dirty flag.

**Comment by pkdash** [comment]
@hyi I think @alvacouch is right. I now remember the same reason for which I added the ```metadata_dirty``` flag. If we only use one flag ```bag_modified``` we have to regenerate the xml files each time the user asks for one of the xml files when the ```bag_modified``` is True. We can't set this flag to False after generating the xml files since the same flag is used for recreating the bag. If we set to False after regenerating the xml files then the user may end up not getting an updated bag when the user asks for the bag.

**Comment by hyi** [comment]
@pkdash I may not capture your use case fully, but I think if we modify ```bag_modified``` flag behavior to be set to true whenever there is metadata change or file change, then when bag is downloaded, the bag will be regenerated since this flag is true. In short, whenever there is a change that affect the bag, this single flag is set to true. This single flag is only set to false when there is no metadata changes after the bag is regenerated upon being downloaded. I think this should address your use case, right? I am looping in @alvacouch as well since I am still convinced the single flag will address this use case you indicated.

**Comment by pkdash** [comment]
@hyi 

> This single flag is only set to false when there is no metadata changes after the bag is regenerated upon being downloaded. 

This works as long as we don't mind generating xml files **more than once** even though there is no metadata changes after the first time generation.

**Comment by hyi** [comment]
@pkdash I don't understand why xml files would be generated **more than once** even though there is no metadata changes after the first time generation. If there is no metadata changes, this single flag will be set to false, hence xml file can be directly retrieved without being regenerated. XML file is only regenerated when the flag is set to true, in which case, xml files along with the whole bag will be regenerated. So the more I think about it, the more I am convinced that single flag will suffice as long as we augment what we have now to make this single flag do what we want. @alvacouch

**Comment by alvacouch** [comment]
@hyi @pkdash  The problem arises when one discovers data via REST.. In that case it is a common pattern  to fetch `reaourcemetadata.xml to see all metadata rather than downloading the whole  bag. if one does this, then the bag will be generated before we know the app really wants it.

**Comment by hyi** [comment]
@alvacouch That is a valid use case. However, can we augment REST get file end point to check this single flag ```bag_modified``` if ```resourcemetadata.xml``` or ```resourcemap``` is requested, and if the flag is true, then call create_bag_files() to regenerate the files before sending the file to the client? In this special case, we do not set the flag to ```false``` since we have not created the bag files and zipped bag yet. Now I understand @pkdash 's point that the files may be created multiple times if we keep the single flag. Since I assume this use case does not happen often, and create_bag_files() execution is very fast since both resourcemetadata.xml and resourcemap.xml are small, the benefit of simplicity for using single flag may outweigh this potentially wasted recreation of resourcemetadata and resourcemap files. What do you think? If you think we should keep the way it is now, I am fine with it also, then will close this PR.

**Comment by hyi** [comment]
@alvacouch @pkdash Given discussion above, I decide to keep the two flags we have now and close this issue.
