### ISSUE TITLE
Completing implementation of logical files

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#2099]
@pkdash @dtarb @hyi 
In PR #2084 there was some discussion of the fact that the logical files implementation (for `CompositeResource`) is incomplete. 
There are two main issues: 
1. deleting the last physical file associated with a logical file with `delete_logical_file=False` can leave a logical file around forever. This is a memory leak. 
2. at present, we can "ingest" most any set of files from disk to Django, simply by using `add_file_to_resource` on existing files in iRODs. However, it is unclear how this would handle logical files in `CompositeResource`. If this could be clarified, we could re-ingest any new files from disk into any resource, simply by calling `add_file_to_resource` on each one in turn.  This also affects `zip` and `unzip` functions, which utilize this technique already. Long term, in HS2.0, we could use this to ingest whole DropBox directories into resources. (This is different from ingesting existing metadata. Ingesting file hierarchies is much easier.)

**Comment by pkdash** [comment]
> deleting the last physical file associated with a logical file with delete_logical_file=False can leave a logical file around forever. This is a memory leak.

This can happen only in the case **misuse** of the ```delete_resource_file()```.  This parameter  ```delete_logical_file``` is intended to be set to ```False``` **only** by the ```logical_delete()``` function of The LogicalFile object. 

The current implementation does not wait for the last file to be deleted to delete the associated logical file.  Rather the logical file (including file level metadata) and all its physical files will be deleted on the delete of the first physical file that is part of a logical file.

Not sure how there would be memory leak if for some reason a logical file is not get deleted.

It is easy to add the extra logic to delete logical file when the last physical file gets deleted if needed.

**Comment by pkdash** [comment]
> at present, we can "ingest" most any set of files from disk to Django, simply by using add_file_to_resource on existing files in iRODs. However, it is unclear how this would handle logical files in CompositeResource. If this could be clarified, we could re-ingest any new files from disk into any resource, simply by calling add_file_to_resource on each one in turn. This also affects zip and unzip functions, which utilize this technique already. Long term, in HS2.0, we could use this to ingest whole DropBox directories into resources. (This is different from ingesting existing metadata. Ingesting file hierarchies is much easier.)

The zip/unzip functionality as far as I know is limited to Generic resource. We can't just add a file from iRODS to any resource type. It will break the integrity of that resource. Besides Generic and composite resource types all other resource types do validate files (and possibly reject files if validation fails) and do extract metadata.

In the case of Composite resource if we need to add a file from iRODS, we need to send a post file add signal. Composite resource makes the added file part of a new Generic Logical file by listening to post file add signal.

**Comment by alvacouch** [comment]
@pkdash How do you plan to handle shapefiles (with multiple files and one logical file) in `CompositeResource`? Do you plan to require registering them at the same time? What conventions do you plan on enforcing?

**Comment by dtarb** [comment]
Based on discussion with @pkdash a few days ago here is my understanding of what is, and what I think should be done.

Files with the following extensions can comprise a shape file 
".shp", ".shx", ".dbf", ".prj", ".sbx", ".sbn", ".cpg", ".xml", ".fbn", ".fbx", ".ain", ".aih", ".atx", ".ixs", ".mxs".

These are grouped into
Required
".shp", ".shx", ".dbf"
Acted on
".prj", ".xml"
Just saved (non required/non acted on)
".sbx", ".sbn", ".cpg", ".fbn", ".fbx", ".ain", ".aih", ".atx", ".ixs", ".mxs".

1. Files are loaded and stored in the resource as untyped (generic).
2. A file with one of the extensions above may be identified and used to "Set Geographic Feature File Type"
3. All files with the same root name and one of the extensions above are identified, looking only in the folder of the file selected.
4. Validation check to make sure that the 3 required files are present.
5. Metadata is harvested from the 3 required files, and .prj and .xml if present.  This also serves as a validation check.  If harvesting metadata results in an error it indicates possible corruption or incorrect format of one of the files and the type conversion process should be aborted, resource contents left unchanged, and user sent an error message.
6. All files identified moved into a folder with the root name and become registered as the logical file type at the same time.
7. Once the logical file type with files in a folder are set up deleting any file in the folder deletes the entire file type instance.
8. Files may not be added to the registered file type.

I think that the above is close to what @pkdash has already implemented, but he can correct what is not right.  (.xml harvesting may not be implemented, but should be similar to geographic feature resource type)

Future enhancements that could be considered include
1. An ability to add or remove non required non acted on files after the file type instance has been established. (change to 7 above)
2. An ability to add or remove acted on file types (.prj, .xml) triggering a re-harvesting of metadata
3. An ability to unregister the file type to revert the contents of the file type folder back to being individual generic files.

**Comment by dtarb** [comment]
@alvacouch with all the work on composite resources, I think this issue is now moot.  Please close it if you agree, and/or post another issue with any remaining points to address.

**Comment by martinseul** [comment]
@alvacouch I'm closing this as the migration to composite resources has completed, please reopen if you disagree.
