### ISSUE TITLE
Suggestion: Put docs/ in an online readable format

### ISSUE THREAD

**Issue by ironfroggy** [hydroshare/hydroshare#21]
When potential contributors are looking at at the repository on Github, the docs/ folder is very opaque. They can't see anything without checking out the repo first or grabbing specific files in flat formats. This is why most development documentation for a project is usually in a format like Markdown where they'd be able to read through documentation right on the repo to know if it is something they'd like to get into further.

Would you consider moving some of that documentation out of the PDF and Word docs?

**Comment by hyi** [comment]
@dtarb I am assigning this to you for re-delegating the task.

**Comment by dtarb** [comment]
Closing this.  It is stale.  Alfresco is deprecated.  Active design docs are in Google.  Github wiki documents the development process and pages.hydroshare.org holds user oriented help documentation.
