### ISSUE TITLE
Add file coordinate system coverage to resource specific metadata

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#210]
We have decided for uniformity to have the generic resource spatial coverage element always use WGS 84 geographic coordinates.  This simplifies mapping of multiple resources.  However the resource file may have data in a projected coordinate system.  Conversion from the coordinate system of the file to WGS 84 is done when a file is loaded.  However there is a need to also expose the coverage metadata the way it is stored in the files projected coordinate system.  This should be added to the resource specific metadata.  This applies immediately to raster resources, but likely applies to other resource types too (geographic feature, multidimensional space time).

**Comment by hyi** [comment]
This has been addressed for raster resource type. Added fix pushed to github label for tracking purpose.

**Comment by hyi** [comment]
Tested it on alpha and it is working now. Adding ready for testing label. Original coverage info cannot be edited for release 1.4. Will tackle coverage metadata editing in release 1.5.

**Comment by dtarb** [comment]
This has been working in demos on beta.hydroshare.org.  Closing.
