### ISSUE TITLE
Avoid embedding configuration into ResourceFile paths

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#2104]
@dtarb @hyi @pkdash 
Currently, there are three kinds of resources: 
1. local: stored in some local disk and accessed via relative paths. 
3. federated: stored in a remote iRODs server
3. **user**: stored in an iRODS user account on the RENCI iRODS user server. This is done to avoid unnecessary copying between the user server and the "local" iRODS server.
The problem is that in case (3), **the path to user resources changes with configuration** and **that path is hard-coded into the `ResourceFile`s** as the path used during deployment. 

Thus, **the user paths break during testing,** and this was recently addressed by creating a command in PR #2040. This just isn't good enough. Since the path prefix is a configuration parameter, it should not be hard-coded into the file names. 

There was extensive discussion in PR #2040 about how to fix this, and the conclusion is that we should subclass `FileField` to handle the extra logic. Currently we have two `FileField`s in a `ResourceFile`: one for federated and user files, and another for local files. The reason for this split is that the raw `FileField` doesn't know how to handle several different kinds of storage objects, including federated and unfederated sessions. By subclassing, we can reduce the number of required `FileField`s to one while embodying three kinds of files as documented above, with no embedding of configuration into file paths.

**Comment by hyi** [comment]
@alvacouch Sounds good. I am looking forward to seeing your PR for subclassing ```FileField``` to handle both federated zone and main hydroshare zone. The only thing I like to point out is that we could actually use the same main hydroshare zone iRODS settings to create the same istorage object to be used for federated zone storage as well if all our development and deployment environments all have federated zone set up correctly. The reason to create a separate istorage object for federated resource file is for not breaking development/deploy environment when federated zone is not set up.

**Comment by pkdash** [comment]
@alvacouch I have not yet fully digested all these combinations of configurations and how the files at different locations are accessed and manipulated. Any attempt to further simplify file handling code is great.

**Comment by dtarb** [comment]
@hyi @alvacouch is this still an issue.  I think we no longer have federated and user resources.

**Comment by hyi** [comment]
@dtarb @alvacouch I believe this issue still applies even though we no longer have federated and user resources. The reason is that I kept the federation storage and file field code intact for potentially handling future federation use cases although there is no longer federation path present among all HydroShare resources in the database. Not sure it is worth the effort at this point to tackle this enhancement issue, though, given that we don't have a federation use case at this point.

**Comment by cbcunc** [comment]
Adding self as participant.

**Comment by cbcunc** [comment]
Closed per @alvacouch
