### ISSUE TITLE
Drastic differences between file/folder assumptions in iRODs (REST) code and in JavaScript code

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#2105]
@pkdash @hyi @dtarb I am looking for possible causes of file corruption as addressed in PR #2090 .

The code [here](https://github.com/hydroshare/hydroshare/blob/develop/hs_core/views/utils.py#L778) doesn't match the comment: 
```    
    # if we are moving to a directory, put the filename into the request.
    if src_file_dir != tgt_file_dir and tgt_file_name != src_file_name:
        tgt_full_path = os.path.join(tgt_full_path, src_file_name)
```
There is no way it could match the comment, because 

1. The target need not exist (and is created automatically if not), so 
2. There is no way to check whether it is a directory (because it might not exist). 

The way it is written, 
1. The only way you can change a file name if is it is in the same directory as before. 
2. If you move a file to a new directory, it assumes that the whole `tgt_full_path` is that directory even if the intent is to change the file name at the same time. 

It strikes me that naïve use of this routine could have very unexpected results. This might be at the root of @ChristinaB's problems as routed out by @Castronova . E.g., if one calls
```
move_or_rename_file_or_folder(user, resource_id, 'data/contents/foo/cat.txt', 'data/contents/bar/dog.txt')
```
then the result will be `data/contents/bar/dog.txt/cat.txt`. `dog.txt` is interpreted as a directory (whether it is or not).

**Comment by alvacouch** [comment]
@pkdash @hyi @mauriel133 @dtarb
So, I am now looking at how this is called. It is a very complex path. 

* `hs_core/views/utils.py:move_or_rename_file_or_folder`
* is called by `hs_core/views/resource_folder_hierarchy.py`
* which is exposed in `hs_core/urls.py` as `move-or-rename-file-or-folder` public and private REST calls
* the private one of which is referenced in `static/js/hs_file_browser.js` 

Here's where life gets interesting. In `hs_file_browser.js` [here](https://github.com/hydroshare/hydroshare/blob/develop/theme/static/js/hs_file_browser.js#L1080): 
```
        if (folderName && folderName.lastIndexOf(".") == -1) {  // Makes sure the destination is a folder
            targetPath = targetPath + "/" + folderName
        }
```
**which assumes that folder names cannot contain `.`**.  _This is the first time I have encountered that limit anywhere in the code._

My conclusion is that a number of rash assumptions are being made. 
1. In the drag-and-drop interface, there is a rather limiting assumption about folders. 
2. In the REST (internal) API, move-or-rename-file-or-folder assumes that only one of two conditions are met: either:  
    a. A file is being moved to a different name in the same folder or 
   b. The destination file is a folder. 

So far, this sort of works but the point is that the drag and drop interface and the iRODS interface that it calls have fairly different ideas about what constitutes a folder!

**Comment by alvacouch** [comment]
To fix this, we need to do three distinct things: 

1. Decide what a legal folder looks like for both REST and js. 
2. Refactor REST to be absolutely clear about the intent of each REST call. 
3. Update js and REST for shared conventions. 
4. Add REST -- as needed -- to clarify js code. 

The second one is rather easy to address. The current REST call `move-or-rename-file-or-folder` is a conflation of two use cases: 

a. Rename file (in same folder)
b. Move (file or folder) to folder. 

I suggest, therefore, that we refactor the REST API to provide (at least): 

a. `rename-file-or-folder` and
b. `move-to-folder` (where the thing moved can be a file or folder) 
that do not conflate these issues. These will be more difficult to misuse and will allow use cases other than the original `move-or-rename`. 

Optionally, we could also provide a REST endpoint for:
 
c. 'replace-file` (which would solve **other** problems) 

(3-4) seem to be much more difficult to address.

**Comment by alvacouch** [comment]
More specific recommendations: 

1. Modify `hs_core/views/resource_folder_hierarchy.py`: `data_store_structure` so that it 
    a. Doesn't return data for anything not in Django. 
    b. Logs errors for files missing from Django or iRODs

2. In `theme/static/js/hs_file_browser.js`, disambiguate calls to `move_or_rename_file_or_folder` so that work to qualify names is done server-side rather than client-side. Use `move_to_folder` and `rename_file_or_folder` as mentioned above. 

The offending line of code **isn't even necessary** if the REST API is structured better.

**Comment by alvacouch** [comment]
This doesn't solve every behavioral problem I have seen. I still don't know how '/'s get left out of paths.

**Comment by hyi** [comment]
@alvacouch I am trying to recollect my memory, and I believe the code here https://github.com/hydroshare/hydroshare/blob/develop/hs_core/views/utils.py#L778 tries to make sure the ```tgt_full_path``` contains path/file_name so that the path can be created automatically if it does not exist in here: https://github.com/hydroshare/django_irods/blob/master/storage.py#L162. The comment can be made better, but the point is that if ```tgt_file_name``` is not included in the taget_full_path, then we assume it is a file-move-to-a-directory operation, so we attend the ```src_file_name``` to tgt_full_path. Does it make sense to you? I have yet to read the full thread for this issue, but want to point this out in case it helps.
