### ISSUE TITLE
Geo Feature Resource creation issues

### ISSUE THREAD

**Issue by pkdash** [hydroshare/hydroshare#2106]
When creating this resource on beta, if I select one file for upload and then click the Create Resource button, I see a spinning cursor that goes on for ever. I think it would be better to show a message if the use has selected one ore more files but has missed to select one of the 3 required files.

**Comment by pkdash** [comment]
@mauriel133 See this can be addressed as a hotfix the current release candidate.

**Comment by Maurier** [comment]
@pkdash, it is not clear from the UI which ones are the required files. I think this specification should appear as a hint below the file browser. Also, the solution you propose is very specific for this resource type. Should we implement business logic for handling required files before a resource can be created?

**Comment by pkdash** [comment]
@Maurier I think this problem of spinning wheel we experienced in many different scenarios. @hyi recently noticed the same issue when testing quota. I think she tried to fix that in the PR (https://github.com/hydroshare/hydroshare/pull/2184) that she currently has for quota feature.

**Comment by aphelionz** [comment]
@pkdash @Maurier We may be able to close this after 1.14 goes out

**Comment by horsburgh** [comment]
@pkdash and @Maurier - is this still an issue? If not close it. If it is, I'm not sure we want to spend time on it now that geographic feature content can be added to composite resources and we should soon discourage the creation of geographic feature resources.

**Comment by Maurier** [comment]
This issue was fixed with the implementation of filer requirements in the Create Resource page. Closing.
