### ISSUE TITLE
File icon needed for .shp file

### ISSUE THREAD

**Issue by pkdash** [hydroshare/hydroshare#2107]

**Comment by Maurier** [comment]
Let me know if this would work as the icon for .shp files:
![image](https://user-images.githubusercontent.com/2448568/28037300-1da8b4f0-6578-11e7-8200-a4bb271ff62b.png)
![image](https://user-images.githubusercontent.com/2448568/28037313-265da2b8-6578-11e7-88dc-cf1bbc1784e3.png)

**Comment by horsburgh** [comment]
Seems reasonable to me.
