### ISSUE TITLE
Spatial coverage in composite resource problems

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#2110]
- [x] If I load two files into a composite resource, then set the spatial coverage for each of them as a point, at the resource level I get a box (which is correct), but I am unable to edit the Place/Area Name

![image](https://cloud.githubusercontent.com/assets/3456833/25850685/76be3a52-3480-11e7-87cf-80d0540d437a.png)

- [x] If I add a geographic raster that does not have spatial coverage then go to edit coverage the interface only allows me to select Box (which is correct behavior) but there is no visual indication on Point as to why I cannot select it.
![image](https://cloud.githubusercontent.com/assets/3456833/25851135/ca3f97ce-3481-11e7-82e2-59fd35ef8160.png)

- [x] At the resource level when editing a composite resource it shows Point and Box for Spatial Coverage.  Since a user cannot switch between these, this should not be shown.
![image](https://cloud.githubusercontent.com/assets/3456833/25850941/821a2d92-3481-11e7-9993-5ca0cae0d268.png)

**Comment by aphelionz** [comment]
@dtarb @pkdash Can we close this?

**Comment by pkdash** [comment]
@aphelionz I think this issue has been resolved. @dtarb can test and close.

**Comment by aphelionz** [comment]
@dtarb  Please do!

**Comment by dtarb** [comment]
Tested - closing
