### ISSUE TITLE
Show where (which zone) a resource is stored on resource landing page

### ISSUE THREAD

**Issue by hyi** [hydroshare/hydroshare#2115]

**Comment by dtarb** [comment]
This needs a complete description of what is proposed.  I actually would like to see a design document that works this out before we go to code.  This is related to federated iRODS stores and a user's quota on each.  Firstly here are some considerations.

1. Information on the iRODS store a resource is held in is only relevant to owners, so should only be shown on the landing page if you are an owner.
2. Each user has a set quota on each iRODS store federated with HydroShare.  This is by default 20 GB on the HydroShare store and 0 GB on any other federated store.  I have suggested elsewhere that a quota resource be used by the administrators of federated zones to specify the quota for users on the iRODS store they administer.  Users can increase their quota by requesting and motivating it form the respective iRODS store administrator.
3.  A resource can have multiple owners.
4.  A resource has one owner who is a "quota holder" for the resource.
5.  When any owner is looking at the landing page for a resource they should be able to see who the quota holder for the resource is.
6.  When any owner is looking at the landing page for a resource they should be able to see the name of the iRODS store that the resource is held in.
7.  When any owner is looking at the landing page for a resource they should have a button "Move to different iRODS store" that is enabled when the quota holder has quota on a different federated iRODS store. If they click on this button they should then be able to select the destination iRODS store to move the resource to.  This action should be rejected if the quota holder does not have sufficient quota on the destination iRODS store to hold the resource.
8.  Any owner should be able to change the quota holder to any other owner.  This action should be rejected if the new quota holder does not have sufficient quota on the iRODS store where the resource is stored.
9.  Note that these rules allows owners complete control over moving resources around subject to quota limitations.  Owners can perform actions that consume the quota of other owners.  This is consistent with the principle that Owners trust each other.  We do not attempt to manage the social interactions or set rules between Owners.  Owners need to work together.  If you do not trust someone, do not make them an owner of your resource.

There may be additional rules that are needed and some of these may be repetitive of requirements expressed elsewhere.  I encourage discussion and development of a design document that fleshes these out before implementation.  It would be good to have @alvacouch and @rayi113 comment.

**Comment by hyi** [comment]
@dtarb Here are my comments/answers to each of your bullets:
1. Can implement this in this PR.
2. This is complicated and its implementation depends on existence of external federated zones and quota management for external federated zones. Given that the first complete quota implementation is not even in yet, I don't think we are ready to implement this yet. It can be implemented at the second pass after we have an external federated zone and our current quota management implementation from admin or implementation of a quota management resource for external quota management as you suggested are in place first. I don't think we have time to do anything about this for HydroShare 1.0 since we only have 3 weeks left for HydroShare 1.0.
3. already implemented.
4. already implemented.
5. already implemented.
6. Related to No. 1 and can be implemented in this PR.
7. Related to No. 2 and should be implemented together with No. 2 as the second pass with detailed explained on No. 2 above.
8. This is already implemented, however, the check is not done to make sure the owner to be changed to quota holder has enough quota before being made a new quota holder for the resource. I'll create an issue to have this check added for release 1.11.
9. already implemented.
@dtarb do you want me to implement No. 1 and No. 6 in this PR to have it merged for release 1.11 or 1.12 given that No. 2 and No. 7 cannot be implemented as explained above? I am fine to retract this PR if you think we should not put it in until we are ready to implement more complete solution such as including implementation for No. 2 and No. 7, although I personally think it has merit even though we cannot implement No. 2 and No. 7 yet. Looping in @alvacouch @rayi113 @mjstealey for their reference and comments as well.

**Comment by dtarb** [comment]
Without an ability to move a resource from one zone to another (No. 7), I do not think we should show a user anything about the zone a resource is in.  Furthermore, until we have this ability I think we should put all resources in the data zone.  I think that the complications of having multiple zones are just getting us into trouble without the ability to do anything about it and move resources around.  So, until this can be done properly, I think this should be deferred.

**Comment by hyi** [comment]
@dtarb Having federated multiple zones is essential for extended and distributed storage and quota management. We are patching things up and making the system to work better as we work through the issues, but we are heading in the right direction to leverage iRODS federation for distributed data and storage management. After giving this a bit of more thought, I think I can add partial solution for No. 2 and No. 7 based on what we have currently implemented. Specifically, I can add move option for users to move the resource between HydroShare data zone and HydroShare user zone regardless of whether users have iRODS user account in the user zone or not. Then in the future when external third party federated zones come into existence in HydroShare, this move-between-zones functionality can be extended to external zones. If you think this partial solution has merits and we should pursue for HydroShare 1.0, I can make an effort to make it happen. Otherwise, I am happy to close this PR to defer this for now. Let me know.

**Comment by dtarb** [comment]
I agree that the functionality is essential.  But half the functionality is not very helpful.  I think that if you can make a plan that states what the end functionality will be for both federated zones and for the interface that allows users to work with resources in them, and the sequence of steps for implementing the plan, then I will be more comfortable moving ahead.

**Comment by hyi** [comment]
@dtarb I can write a design doc for this, but I don't think I will have time to implement this plan even for the partial solution I suggested above given the time left, my vacation schedule, and items for other projects I have to address before I leave for vacation. I will keep this PR open for a week or two just for discussion purposes based on the design doc I will write, then I'll close this PR since the actions will have to be deferred due to limited time we have left.

**Comment by Lizabrazil** [comment]
@hyi Can you comment on the status of this?

**Comment by hyi** [comment]
@Lizabrazil I think the plan for third party federated iRODS zone storage is still in the works or up in the air, looping in @dtarb and @alvacouch for comments as needed. I'll defer to @dtarb on whether we should close this issue or not.

**Comment by rayi113** [comment]
@Lizabrazil @hyi @dtarb @alvacouch The current thinking via the RENCI HydroShare roadmap work-in-progress is to no longer pursue federation via iRODS in HydroShare.  Recommend closing this issue.
