### ISSUE TITLE
UI does not communicate errors to user from REST API

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#2120]
@aphelionz @Maurier @dtarb There is a systematic problem in the file drag-and-drop interface, that errors that are sent back from the REST API are not ever shown to the user. This is problematic, because **these messages contain details on how to solve the problem.**

As well, there is a need to display messages that are informational and not errors. The most prevalent example of this is when the back-end makes a resource private as a result of deleting the last file. I would appreciate a standardized approach to this to which we could conform in the REST API.

**Comment by eclark-cuahsi** [comment]
closing per backlog review meeting on 6/9/22. can address wording in specific error messages individually.
