### ISSUE TITLE
File drag-and-drop UI back-end error checking is not comprehensive

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#2121]
The error checks in the back-end are at best spurious. We should check for the following errors system wide: 
1. target or source of operation has moved before operation commenced. This is due to a stale page. 
2. source files for operation don't exist in iRODS or in Django. 
3. operation would overwrite one or more existing files. 

I have implemented these for the `data-store-move-to-folder` endpoint in PR #2118. But they need to be implemented for all endpoints in the "data-store" category.

**Comment by alvacouch** [comment]
Addressed in #2118

**Comment by dtarb** [comment]
Alva says this is done.
