### ISSUE TITLE
Should be able to rename and/or move some kinds of files in composite resource

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#2124]
Currently no files can be renamed in the composite resource. This is very inconvenient when using the composite resource as a replacement for generic resource, and this renaming should be possible. 

Some discussion with @dtarb, @pkdash indicates that the ability to rename (as well as the way a resource would be moved between folders, e.g.) is a function of the logical file rather than the physical file. Thus, types of logical files should be tagged as to whether renaming is possible. In like manner, moving of logical files should be possible, but only if the whole logical file (consisting of perhaps multiple physical files) is moved at once. Currently one can move parts of a logical file and thus break association. 

Some preliminary comments by @dtarb and @pkdash 
1. Raster logical files consist of two files that cannot be renamed because one serves as a catalog for the other, and should be moved together. 
2. NetCDF logical files have an additional metadata attachment that should be moved with the original file if the logical file is moved.  
3. Geographic feature files have a strong naming convention that must be preserved when renaming.

**Comment by Lizabrazil** [comment]
@alvacouch @dtarb @pkdash This is now resolved from what i tested. I will close out, please reopen if there is something i didn't catch
