### ISSUE TITLE
Timeout issue for large set of file display on resource landing page

### ISSUE THREAD

**Issue by hyi** [hydroshare/hydroshare#2125]
For resources with large set of files, such as https://www.hydroshare.org/resource/8fd42ad1d86f495a914e7ce9be21bbce/ which has about 15k files all residing at the top level, the spinning wheel goes on and on until receiving a 504 (Gateway Time-out) error with no files being displayed. On the current www, there is also an request error as shown below:
```
Failed to load resource: /resource/8fd42ad1d86f495a914e7ce9be21bbce/undefined/ the server responded with a status of 404 (NOT FOUND)
```
However, we don't see the error above on beta, so assume the error has been fixed along the way for release 1.10. However, we need to think through how to handle file display for a resource with such large set of files. Assigning this to @alvacouch and @Maurier for initial ideas for now.

**Comment by dtarb** [comment]
This has sat a while.  There are other file system issues, e.g. #2266 .  @hyi if this is still a problem can you post a specific problem issue (with example - example resource above is no longer there).  Otherwise, closing this.
