### ISSUE TITLE
No resource file gets uploaded when creating a Composite Res through hs_restclient 1.2.8

### ISSUE THREAD

**Issue by zhiyuli** [hydroshare/hydroshare#2137]
The following code works fine for "GenericResource". 
For "CompositeResource", it was able to create a resource with correct title, keywords and abstract, but no resource file got uploaded.

hs.createResource("CompositeResource",
                             "myres",
                              resource_file=zip_file_full_path,
                              keywords=['kw1', 'kw2'],
                              abstract='my abstract')

environment:
hs_restclient 1.2.8  + current www-hydroshare.

**Comment by zhiyuli** [comment]
OK. I see a workaround: First I created an empty CompositeResource by not passing parameter 'resource_file' to hs.createResource(), then called hs.addResourceFile(resource_id, file_path) to append a new resource file to this composite resource.

**Comment by aphelionz** [comment]
@zhiyuli If this is still an issue, can you move it to the hs_restclient repo?

**Comment by zhiyuli** [comment]
Old issue already fixed.
