### ISSUE TITLE
Account sign-up not visible under iOS

### ISSUE THREAD

**Issue by selimnairb** [hydroshare/hydroshare#214]
Under iOS the [home page](http://dev.hydroshare.org/) for un-authenticated users does not display the user sign-up form.  This occurs under both Safari and Chrome on an iPhone and iPad (both running iOS 8.2).

**Comment by mjstealey** [comment]
@selimnairb - Is this only for dev? or for all hydroshare instances (alpha, beta, etc.)?

**Comment by horsburgh** [comment]
This is also an issue when normal desktop browser windows are made narrow. At a certain point the user sign up form just disappears.

I may be unpopular for suggesting this again, but could we move the user sign up to a separate page?

**Comment by dtarb** [comment]
This is part of overall UI appearance that @mauriel133 will work on with @horsburgh

**Comment by dtarb** [comment]
@horsburgh or @selimnairb can one of you Mac users test whether this is still a problem on www.hydroshare.org and if not, close this issue.

**Comment by horsburgh** [comment]
I just tested on my iPhone and in my browser, and the sign in form now remains visible.
