### ISSUE TITLE
HydroShare 1.10 Release Regroup Plan

### ISSUE THREAD

**Issue by rayi113** [hydroshare/hydroshare#2140]
### Next Steps

 * Build HydroShare with iRODS 4.1.8 on Beta to determine if 1.10 stalled release best-estimate cause of being related to iRODS ibun problem goes away
	 * Partition Beta to use iRODS replication servers, but with different accounts so as not to perturb the production www environment in place

### Proceed Depending on Outcome

Outcome 1
* Beta with iRODS 4.1.8 works and ibun-related problem goes away
	* Then use this configuration as the basis for the HydroShare 1.10 release
	* Package up the prior HydroShare stalled 1.10 release with iRODS 4.2 configuration and submit to iRODS team as bug

Outcome 2
* Beta with iRODS 4.1.8 does not work
	* Look for deviations between configuraitons on Beta with iRODS 4.1.8 and www.hydroshare.org with iRODS 4.1.8 and isolate where bug is (i.e. not necessarily iRODS bug at that point)
	* If configuration issue, then fix and retry on on Beta with iRODS 4.1.8 again to verify

### After HydroShare Release 1.10 Deployed
* Reevaluate migration to iRODS 4.2 on Beta for a later HydroShare 1.x release

**Comment by rayi113** [comment]
iRODS 4.2 ibun does have a reproducible bug as just logged here: https://github.com/irods/irods/issues/3571

Thus HydroShare team should not pursue iRODS 4.2 until above iRODS bug is fixed.

**Comment by alvacouch** [comment]
Many thanks for getting to the bottom of this!

**Comment by rayi113** [comment]
Thanks to @phuongdm for isolating iRODS ibun on HydroShare side and making it concicely repeatable for the iRODS team, @xu-hao for making it concicely repeatable on the iRODS side, and @jasoncoposky for fixing it and making a test for it as part of iRODS CI.
