### ISSUE TITLE
Allow unzipping of compressed file formats other than zip

### ISSUE THREAD

**Issue by pkdash** [hydroshare/hydroshare#2143]
In particular the unzip api should support unzipping of gzip.

**Comment by lichray** [comment]
libarchive, or just bsdtar.

**Comment by Castronova** [comment]
@hyi Have you made any progress on this? If not, do you have any plans to work on it?

**Comment by hyi** [comment]
@Castronova No, I have not done anything on this. With the current implementation, unzipping depends on iRODS ibun operation which only supports tar, gzip, bzip2, and zip data types. I'd suggest to close this issue for now unless we have specific use case that requires support of other compressed file formats.
