### ISSUE TITLE
Loading bug with HydroShare GIS

### ISSUE THREAD

**Issue by ChristinaB** [hydroshare/hydroshare#2144]
Please review these printable demos.  If you have files from Demo4 already open in the App, and then try to load the project in Demo 3, the App gets stuck loading forever.  

[HSGISDemo4_CB.docx](https://github.com/hydroshare/hydroshare/files/1042637/HSGISDemo4_CB.docx)
[HSGISDemo3_vCB.docx](https://github.com/hydroshare/hydroshare/files/1042636/HSGISDemo3_vCB.docx)

![image](https://cloud.githubusercontent.com/assets/4108369/26649232/18055ec4-45fa-11e7-9522-b936e3ace2c7.png)

**Comment by aphelionz** [comment]
This issue was moved to CUAHSI-APPS/tethysapp-hydroshare_gis#14
