### ISSUE TITLE
Enable use of irsync for Jypyter notebooks manipulations of genericResource, compositeResource

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#2146]
@dtarb @danames @martinseul  I was talking with @Castronova about what we could do to make Jupyter notebook interactivity better. So far he is using icommands to move things back and forth to user space, and then copying them from userSpace to HydroShare using the web front end. 

I got to thinking that we could enable something much more direct. The tool `irsync` synchronizes a local directory with iRODS. This is basically `rsync` over iRODS. This could be used to re-synchronize specific kinds of resources with their images in HydroShare, in both directions. 

Accomplishing this would require: 

1. Implement the ticketing solution proposed elsewhere for direct iRODS access. This would allow one to use Django REST to obtain a ticket for a specific iRODS operation. (This ticket will allow modification via either icommands or iRODS REST).  
2. Issue a ticket for the change (upward or downward) to the requesting user (e.g., via hs_restclient). Better: create a new library hs_irodsclient to encapsulate this. 
3. Make the change using the ticket. 
4. Invoke another REST call to "re-ingest" the changed files into the resource. 

Notes: 
1. This works because we usually ingest files after upload. 
2. Thus, our code for ingestion will work on files that are in place. 
3. It's fairly easy to scan for changes an re-ingest anything that's changed. 

However: 
1. It only works for unconstrained filesystems including Composite and Generic
2. It won't work well for types that constrain the file hierarchy because I can't request a ticket that is specific enough.  (We could make it possible by constraining these types more, though)

(A dumb approach to making this work for everything: Suppose we want to use this for all types. Then we could standardize the file names for the various kinds of resources, and not let them be set by the user. Then I could request tickets (in Django) that are specific enough to allow these to be irsync'd as well) 

The point of this is that this is a much easier paradigm by which apps could do things with resources than the traditional approach. Django requests and issues tickets for read and/or write; icommands and/or IRODS REST makes these things happen.

This would ideally require development of a (rather trivial ) hs_irodsclient application to supplement hs_restclient.

**Comment by alvacouch** [comment]
Everyone: note that the code to handle write has already been written; it is in essence the file integrity checker that I wrote to detect differences between iRODS and Django, along with a "repair" option to be written that ingests an arbitrary directory of files as a generic resource :)

**Comment by aphelionz** [comment]
@alvacouch @Castronova Should we move this issue to the jupyterhub repo issues?

**Comment by martinseul** [comment]
@Castronova is this still relevant or can it be closed?

**Comment by Castronova** [comment]
Closing because there has been no action and no planned action on this.
