### ISSUE TITLE
/user throws an error

### ISSUE THREAD

**Issue by alexlemann** [hydroshare/hydroshare#2164]
Loading /user on beta and prod throws an error. It shows up as a ``MultiValueDictKeyError`` on my develop branch.

Can anyone else confirm this?

**Comment by hyi** [comment]
@alexlemann I can confirm this. I believe it has always been like this from the beginning of HydroShare, /user does not work, but /user/2, for example, works, and shows the profile page of that user. Agreed this error should be fixed, but in the meantime I am wondering what /user page should show.

**Comment by alexlemann** [comment]
I think a 404 would be fine. It would at least be a reasonable start.

**Comment by martinseul** [comment]
Close: Stale
