### ISSUE TITLE
Add selenium tests for user registration

### ISSUE THREAD

**Issue by alexlemann** [hydroshare/hydroshare#2165]
* Create new user
* Check email link to complete registration process
* Basic profile functionality
  * Edit profile fields
  * Upload a CV
  * HTML tags escaped in name field (fixed XSS issue #1805)

**Comment by alexlemann** [comment]
@dtarb Any additional items to add to the tests above?

It appears that first name and last name are not required fields to register. Is this intended?

There are no restrictions (length, type of characters) on passwords that I see immediately. I'm assuming that this is not intended and will create a bug for this unless I hear otherwise.

**Comment by dtarb** [comment]
Firs tname and last name should be required fields to register.  For passwords, I think we should follow industry best practices, without being to onerous.  I hear conflicting information.  Some sites advocate pass phrases like "thecrazyfoxjumpedintothelake", while others require special characters and limit length.  What do you recommend?

**Comment by alexlemann** [comment]
Django 1.9 introduced a new password validation system that would be great to include. This is the current best practices. It appears to be backported via this project:
https://github.com/orcasgit/django-password-validation

**Comment by alexlemann** [comment]
Other items of note:
1) There are two styles of error messages for registration for errors. This is inconsistent and the UI is confusing as a user.
    * One is a javascript popup from presumably JS validation of the fields
    * The other is when the POST is incorrect and Django returns errors.
2) There can be three types of alerts active at one time on the home page: MOTD, You have successfully registered, and you need to fill in your organization.
    * These are styled differently, can overlap, and be confusing
    * It would be less error-prone to have one type of alert system (use the built in django messages framework). Then the styling can support stacking multiple messages cleanly.
3) Why not make the organization a required field to create an account now? It's not a lot more work for a user since it's not a controlled vocab and when it's not set the UX bounces the user all around to fill it in.
4) Can we quit using username and standardize on email? I thought that there was some movement in this direction.

The commit here should fix most of the issues in the description except it does not do file uploads. I can add that next and then submit a PR.

**Comment by hydrocheck** [comment]
See github.com/CUAHSI/QA-AutomationEngine.  Most of this is handled - others not handled due to limitations on test environments (e.g. captcha on user creation and smtp config).
