### ISSUE TITLE
SWATshare model update - pending Error 'Downloading and Extracting the resource failed'

### ISSUE THREAD

**Issue by ChristinaB** [hydroshare/hydroshare#2167]
[SWATDemo1_3pg_v2.docx](https://github.com/hydroshare/hydroshare/files/1075619/SWATDemo1_3pg_v2.docx)

@yirugi @vmmerwade 

I started in to try to update the latest printable demo above, and ran into this error when trying to open c65bce3e4459476f9950c6510728695e/ 

I got this error:
 
![image](https://user-images.githubusercontent.com/4108369/27149750-7add54e8-50f9-11e7-896e-33fef2ee44c2.png)

**Comment by ChristinaB** [comment]
To do to update App:

- [ ] Fix bug

- [ ] Update Printable demo  - 
[SWATDemo1_3pg_v2.docx](https://github.com/hydroshare/hydroshare/files/1075637/SWATDemo1_3pg_v2.docx)

- [ ] Update Modeling Help pages at https://pages.hydroshare.org/modeling/swatshare/   here is a[ link to the Google doc that needs to be updated](https://drive.google.com/open?id=1AT2I20UQMW0IPXL6DwcsQKX5Xef3FOHm-Oh0T5TaxlE) (then we will load it online)

- [ ] Add Help pages to Apps ??  https://pages.hydroshare.org/apps

**Comment by yirugi** [comment]
Hi Christina, we were aware of the error. We fixed the problem, and now, we are testing it on our dev site.

**Comment by yirugi** [comment]
We have fixed the bug.

**Comment by aphelionz** [comment]
@ChristinaB @yirugi Can somebody confirm and close this issue please?

**Comment by yirugi** [comment]
@aphelionz 
We have fixed the bug. I'm closing this.

**Comment by aphelionz** [comment]
@yirugi Thank you!
