### ISSUE TITLE
HydroShare banner covers resource title

### ISSUE THREAD

**Issue by zhiyuli** [hydroshare/hydroshare#2170]
I am not sure this is a issue of my browser or not... the "HydroShare" banner is too big and covers res title on my end
![image](https://user-images.githubusercontent.com/10070599/27295918-ed70e70a-54db-11e7-8302-420e4a903dd6.png)

**Comment by mjstealey** [comment]
Should be resolved now.

**Comment by zhiyuli** [comment]
@mjstealey  Thanks!
Tested on www.
![image](https://user-images.githubusercontent.com/10070599/27296281-71e4681c-54dd-11e7-8451-79d687b2a83c.png)

Closing...
