### ISSUE TITLE
Resource list needs metadata attribute null checks

### ISSUE THREAD

**Issue by aphelionz** [hydroshare/hydroshare#2171]
Ok, so this is likely what’s happening here:

1.	Admin users can “see” resources that other users can’t – likely resources that are invalid or incomplete
2.	One of such resources is missing required metadata somehow, in this case, the title.
3.	The code can’t catch that and errors out when trying to access that attriute without doing a null check first.

**Comment by alvacouch** [comment]
One can't normally create a resource without a title. This represents -- therefore -- some kind of crash while creating a resource.

**Comment by alvacouch** [comment]
It's quite likely that the way this happened is that someone was trying to create a resource with a file upload, and the file upload failed (probably due to file size). That's something we need to fix.

**Comment by Castronova** [comment]
@alvacouch Can you please review this and close/comment as necessary?

**Comment by martinseul** [comment]
closing this, @alvacouch please feel  reopen if you think it's necessary.
