### ISSUE TITLE
Quota holder functionality has blocked the capability to change the owner of a resource

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#2175]
Prior to deployment 1.10 the owner of a resource could be changed by adding a new user as the owner, then deleting the old owner.  However at 1.10 this is disabled as it appears not possible to change the quota holder.  This is a regression in functionality.

**Comment by hyi** [comment]
@dtarb Could you please provide a bit more specifics on this issue? The only extra constraints I put on changing owners related to quota holder is that the quota holder owners cannot be removed. If an owner is the quota holder, the quota holder has to be changed to another owner before this quota holder owner can be removed. I think that is reasonable assumption we should keep. Is there any other constraint you see that I am not aware of?

**Comment by dtarb** [comment]
I was having trouble changing the quota holder.  Now I have found how to do it.  Sorry.
