### ISSUE TITLE
File upload and delete work differently in REST API and UI

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#2177]
@dtarb @pkdash @hyi The functions for file upload send different signals depending upon whether one is using the REST API or UI. The procedures should be the same. Notably, an important post-upload signal is skipped when using the REST API, which causes default logical files to fail to be created for composite resources.

**Comment by pkdash** [comment]
@alvacouch 

>  Notably, an important post-upload signal is skipped when using the REST API, which causes default logical files to fail to be created for composite resources


Which specific REST endpoint is missing the post file upload signal? Both resource create and file add rest endpoints seem to have this signal.

**Comment by Castronova** [comment]
@alvacouch Is this still an issue? Please comment or close.

**Comment by alvacouch** [comment]
I am unaware of any fix of this problem. I have reviewed the REST API and its relationship with the UI in the more recent past, but this needs to be checked upon again.

**Comment by dtarb** [comment]
@sblack-usu can you please look at this and comment or close if not needed or addressed.

**Comment by eclark-cuahsi** [comment]
adding @sblack-usu as this pertains to HS Core Services. Please review and comment or close if not needed or addressed.

**Comment by sblack-usu** [comment]
Both the UI and API endpoints use [resource_file_add_process](https://github.com/hydroshare/hydroshare/blob/develop/hs_core/hydroshare/utils.py#L891) which includes the noted post-process signal with a file add.  For file delete, both the UI and API endpoints use [delete_resource_file](https://github.com/hydroshare/hydroshare/blob/develop/hs_core/hydroshare/resource.py#L858) which includes the post-process signal as well.
