### ISSUE TITLE
Case insensitive and partial word search function needed for all searches

### ISSUE THREAD

**Issue by ChristinaB** [hydroshare/hydroshare#2180]
Case insensitive search example:  I want to find Jeff's HydroShare postcard.  I got to DIscover, input 'postcard'.  Jeff has used the keyword 'Postcard' in caps, and Discover does not retrieve the resource. 

Partial work search example:  David is looking for his UCGIS2017 keyworded demo tutorial, and inputs 'UGGIS' into Discover, no resources are discovered.  

Thanks!

**Comment by aphelionz** [comment]
@ChristinaB Just pushed this to a PR. In an hour or so you should be able to test it on playground.

i was able to tackled case insensitivity in the UI and REST API, however partial search is elusive...

**Comment by aphelionz** [comment]
@ChristinaB  Actually! I fixed that too. It's up on playground. Have a look.

**Comment by ChristinaB** [comment]
It works! My little test is to search for 'postcard' and find @horsburgh 'Postcard' key work with 'Postcard' in the title.   This only works from My Resources because it was private.  

Are there more tests that need to be done?  Other examples?

Glitch - I started trying to do this in Discover, I had forgotten that  it was private and I didn't realized the search in My Resources and Discover worked differently.  I originally thought your caps fix wasn't working.  @Castronova is making a new issue for this.

**Comment by ChristinaB** [comment]
It looks like this is working from my short test.  I'll let you close, merge, and check the box on https://github.com/hydroshare/hydroshare/issues/2166
