### ISSUE TITLE
Update Quota message text to be more understandable

### ISSUE THREAD

**Issue by mjstealey** [hydroshare/hydroshare#2196]
Update the text that will appear in the quota message emails.
@dtarb, @horsburgh, @alvacouch, @rayi113 for content

1. Warning content prepend:

```
Your quota for HydroShare resources is {allocated}{unit} in {zone} zone. You currently have 
resources that consume {used}{unit}, {percent}% of your quota. Once your quota reaches 100% you 
will no longer be able to create new resources in HydroShare. 
```

2.  Grace period content prepend

```
You have exceeded your HydroShare quota. Your quota for HydroShare resources is {allocated}{unit}
in {zone} zone. You currently have resources that consume {used}{unit}, {percent}% of your quota. 
You have a grace period until {cut_off_date} to reduce your use to below your quota, or to acquire 
additional quota, after which you will no longer be able to create new resources in HydroShare. 
```

3. Enforce content prepend

```
Your action was refused because you have exceeded your quota. Your quota for HydroShare 
resources is {allocated}{unit} in {zone} zone. You currently have resources that consume {used}
{unit}, {percent}% of your quota. 
```

4. Content

```
To request additional quota, please contact support@hydroshare.org. We will try to accommodate 
reasonable requests for additional quota. If you have a large quota request you may need to 
contribute toward the costs of providing the additional space you need. See 
https://pages.hydroshare.org/about-hydroshare/policies/quota/ for more information about the 
quota policy.
```

![screen shot 2017-06-28 at 3 05 09 pm](https://user-images.githubusercontent.com/5332509/27655443-68172418-5c13-11e7-921f-e96bfb6cd96f.png)

**TODO** attach copies of actual emails to this issue

**Comment by hyi** [comment]
@horsburgh @dtarb @mjstealey @rayi113 @alvacouch If you think we should change the name for the default zone from ```hydroshare_internal``` to just ```hydroshare``` or ```hydroshare storage``` or anything else you can suggest, I can make the change quickly this week for release 1.11 before I take the next two weeks off assuming we want to slate quota implementation for release 1.11.

**Comment by hyi** [comment]
@horsburgh I checked the send email code, and do see "html" is added as a content type as ```msg.attach_alternative(render("html"), "text/html")```. And I checked the signup activation email which does show the verification URL link as html clickable link. So I think what we saw during the demo was an artifact of directing email content to a file which does not support html. If the email goes to an email provider server, it should show "text/html" as the content type. This will not prevent the email from going to the spam folder, but would make it a bit user-friendly so less likely to be deleted and treated by users as spam.

**Comment by dtarb** [comment]
Please refer to #1566 where I drafted text for the messages previously.  It adds information on how users can request additional quota that the above messages do not.  The exact wording is not too critical as it looks like there is a control page to control it.  Quotas and quota policy need to be a CUAHSI issue as we move forward into the operational phase so @martinseul and @Castronova need to review.  It also needs to be part of an overall welcoming and friendly messaging that @ChristinaB could help with.  While quotas are needed, we do not want them to be a barrier.  We want to accommodate all reasonable requests.  The purpose of the messages is really to get big users into a discussion with us about their use and needs and how they should be best accommodated.  Big users are our important customers, and may end up having to contribute to HydroShare by paying for additional storage by some mechanism.

I am not quite sure I understand the question related to name.  Where does the name get shown to the user?  Something like "HydroShare store" seems better than HydroShare internal.  It would be better to configure this in a way that we can tweak it if we want to without too much trouble.

**Comment by hyi** [comment]
@dtarb I did create the default quota messages according to your draft #1566, and these messages can indeed by customized/modified from Django admin panel. ```hydroshare_internal``` is the default zone name I made up that refers to both hydroshare data zone and hydroshare user zone. I can easily change the default zone name to something like "HydroShare store" if that is the name we decide to use. I just need a decision on what name to use for the default zone name that refers to hydroshare data and user zones.

**Comment by horsburgh** [comment]
@dtarb and @hyi - I think I may have sparked some of this with my questions on the HydroShare call. My point about the name of the iRODS zone in this messaging is that 99% of HydroShare users do not know what a HydroShare iRODS zone is. Nor do they want/need to know - especially since there is really only one zone right now, right?  My suggestion was simply:

> Your quota for HydroShare resources is {allocated}{unit}.

Unless, and until we have multiple zones implemented, I suggest just leaving off the iRODS zone information.

**Comment by hyi** [comment]
@horsburgh @dtarb Agreed. This can be accomplished easily by removing ```in {zone} zone``` from all quota messages from admin panel, and can be added back in as needed when we have multiple zones and after we keep users better informed with zone concept. I have tested it out and it works, although I did find an oversight which has been created by a newly created PR https://github.com/hydroshare/hydroshare/pull/2228 @mjstealey

**Comment by ChristinaB** [comment]
The current message reads:

HydroShare resources will be 20 GB, and only resources that you are the "quota owner" for will be tallied against your quota. More details are forthcoming.

This could be improved by giving the user a bit more context and making it present tense, with an action item. 

"Development update: HydroShare resources are 20 GB, but only resources that you are the "quota owner" for are  tallied against your quota. Contact support@hydroshare.org to learn more."

Alternatively, you could send them to a quota Help page rather than collect emails, and on the quota help page you can ask them to email if the quota is going to impact their current usage.

**Comment by dtarb** [comment]
I am supportive of improving the messaging, but I do not think that the statement "HydroShare resources are 20 GB" that @ChristinaB suggests above is accurate or meaningful.  We are talking here about the quota that a user gets not resources.  

Can we clarify what we are trying to achieve here. Do we want to alert users that a quota system is coming and that if they are over we want them to contact us.  Perhaps we should identify users where quota is going to be an issue and approach them.  I suggest that until we have a plan fully worked out that we not give any message at all.   If users contact support@hydroshare.org do we have a message for them.  

See #1566 where we discussed what the messages should be.

The 20 GB that we state on the policy page https://pages.hydroshare.org/about-hydroshare/policies/quota/ is an arbitrary estimate that I made to start with but we need to be soft, at least initially on users who are over this, or at lease we need to identify who they are and what use patterns are.

**Comment by ChristinaB** [comment]
What about something shorter and more direct.  

Development Update: User storage is 20 GB.  Visit [Quota Policy](https://pages.hydroshare.org/about-hydroshare/policies/quota/) to learn more.

Copied on #1566   When I logged on this morning I saw the quota message and it didn't read quite right, this is the only Issue I knew of for bringing it up.

**Comment by dtarb** [comment]
Closing
