### ISSUE TITLE
NWM Viewer - Missing help for subsetting

### ISSUE THREAD

**Issue by Castronova** [hydroshare/hydroshare#2201]
The help dialog that appears when the app is first opened does not mention anything about the new subsetting functionality.  This may lead to confusion since the first thing the user see's are the `add watershed` and `subset watershed` buttons. 

![image](https://user-images.githubusercontent.com/4822372/27705405-bd1a8f36-5cdb-11e7-8afe-48e8fcd9ff21.png)

![image](https://user-images.githubusercontent.com/4822372/27705410-c12a0bb0-5cdb-11e7-9a93-7b094148b7dc.png)

**Comment by zhiyuli** [comment]
fixed on apps server
![image](https://user-images.githubusercontent.com/10070599/28381658-e31939b0-6c78-11e7-8ead-4c26dd8efcb4.png)

**Comment by aphelionz** [comment]
This issue was moved to CUAHSI-APPS/nwm-forecast-viewer#24
