### ISSUE TITLE
NWM Viewer - Missing help button

### ISSUE THREAD

**Issue by Castronova** [hydroshare/hydroshare#2202]
When the app is initially launched a help dialog is shown.  Once this is closed, there is no way to open it again.  Consider adding a button to the top of the page (`Help`) that can be used to reopen this dialog.

**Comment by zhiyuli** [comment]
Fixed on apps server.
![image](https://user-images.githubusercontent.com/10070599/28381624-c4afa8e2-6c78-11e7-8ddf-d67c5b985fa5.png)

**Comment by aphelionz** [comment]
This issue was moved to CUAHSI-APPS/nwm-forecast-viewer#23
