### ISSUE TITLE
NWM Viewer - Toolbar button positions change when screen is maximized

### ISSUE THREAD

**Issue by Castronova** [hydroshare/hydroshare#2203]
When I maximize the my web browser, the `api` and `exit` buttons are positioned over the map instead of their original position above the map.

![image](https://user-images.githubusercontent.com/4822372/27705711-c111f196-5cdc-11e7-8612-9a6eb6bc98f5.png)

![image](https://user-images.githubusercontent.com/4822372/27705718-c7226b6a-5cdc-11e7-9cc7-3abf812eeeab.png)

**Comment by zhiyuli** [comment]
This is strange.  I can duplicate this issue on apps server, but it works find on appsdev and my local vm.
All of them have the same version of code.
![image](https://user-images.githubusercontent.com/10070599/28387862-f4b9dea8-6c8d-11e7-904f-8eaaa230fdff.png)

**Comment by zhiyuli** [comment]
![image](https://user-images.githubusercontent.com/10070599/28387978-5979ba02-6c8e-11e7-9bcf-f6be1fec16ca.png)

**Comment by zhiyuli** [comment]
This should be fixed on both apps and appsdev now.

**Comment by aphelionz** [comment]
This issue was moved to CUAHSI-APPS/nwm-forecast-viewer#22
