### ISSUE TITLE
NWM Viewer - Subset Watershed button activated when no watershed has been loaded

### ISSUE THREAD

**Issue by Castronova** [hydroshare/hydroshare#2204]
After launching the app, I can click the `Subset Watershed` button even though no watershed has been specified.  This gives an error: 

![image](https://user-images.githubusercontent.com/4822372/27705856-521e4662-5cdd-11e7-809e-f8f1409825b3.png)

Instead, this button should not be activated until the first step has been completed, `Add Watershed`

**Comment by zhiyuli** [comment]
fixed on apps server

**Comment by aphelionz** [comment]
This issue was moved to CUAHSI-APPS/nwm-forecast-viewer#21
