### ISSUE TITLE
NWM Viewer - Begin time should be constrained

### ISSUE THREAD

**Issue by Castronova** [hydroshare/hydroshare#2205]
I am able to select a `Beginning Date` earlier then the available NWM data.  The input date should be constrained to the available data, otherwise users will be confused about why data from last year can't be accessed.

![image](https://user-images.githubusercontent.com/4822372/27705983-d05acdca-5cdd-11e7-8354-479beb89bb5f.png)

**Comment by zhiyuli** [comment]
Fixed on apps server.
We only keep NWM data for 30 days (swap out old data each day), so the date range for which data is available for view or download is dynamic:
1) Begin date is constrained on app UI
2) List current date range on Help page
![image](https://user-images.githubusercontent.com/10070599/28387783-9eb2dcd0-6c8d-11e7-882e-e2c9960b790f.png)

**Comment by aphelionz** [comment]
This issue was moved to CUAHSI-APPS/nwm-forecast-viewer#20
