### ISSUE TITLE
NWM Viewer - Form titles revision

### ISSUE THREAD

**Issue by Castronova** [hydroshare/hydroshare#2206]
The form titles all begin with **Enter**, however many of the controls are select boxes.  I suggest changing them to the following:

Enter Configuration -> Model Configuration
Enter Geometry -> Geometry
Enter Variable -> Variable
Enter COMID -> NHD COMID
Enter Beginning Date -> Begin Date
Enter Initialization Time (UTC) -> Initialization Time (UTC)

![image](https://user-images.githubusercontent.com/4822372/27706104-40b79a1c-5cde-11e7-95ce-6c4949cdff38.png)

**Comment by zhiyuli** [comment]
Fixed on apps server

**Comment by aphelionz** [comment]
This issue was moved to CUAHSI-APPS/nwm-forecast-viewer#19
