### ISSUE TITLE
NWM Viewer - Documentation for Configuration

### ISSUE THREAD

**Issue by Castronova** [hydroshare/hydroshare#2207]
The configuration, geometry, and variable fields should have documentation that the user can read.  For example, explaining the difference between short, medium, long, and assimilated configurations.  This could take the form of a simple `help` button that opens a modal window.
Help Pages have this documentation already- add help button with link to direct users to Help Page.
Liza will add the documentation to the Help Page.

**Comment by Lizabrazil** [comment]
http://water.noaa.gov/about/nwm

**Comment by zhiyuli** [comment]
A link to NWM introduction is added to Help page
![image](https://user-images.githubusercontent.com/10070599/28381551-864d5400-6c78-11e7-89a9-d631d36dfb21.png)

**Comment by aphelionz** [comment]
This issue was moved to CUAHSI-APPS/nwm-forecast-viewer#18
