### ISSUE TITLE
NWM Viewer - Improve Workflow

### ISSUE THREAD

**Issue by Castronova** [hydroshare/hydroshare#2208]
The layout of the controls on the page needs to reflect the intended user workflow.  The additions of the `Add Watershed` and `Subset Watershed` functionality is a bit confusing because it is largely independent from the other search/visualization functionality.   This may be improved by adding a radio button select "search be comid" or "search by area" which controls the search options below.  Moreover, the `subset watershed` button should probably be at the bottom of the page.

**Comment by zhiyuli** [comment]
fixed on apps server

**Comment by aphelionz** [comment]
This issue was moved to CUAHSI-APPS/nwm-forecast-viewer#17
