### ISSUE TITLE
NWM Viewer - Zooms to Kansas Randomly

### ISSUE THREAD

**Issue by Castronova** [hydroshare/hydroshare#2209]
When an invalid COMID is entered, the app zooms into some location in Kansas.  This is very strange and doesn't make much sense.  I would expect the map to not change and see an error message along the lines of "Could not find an NHD reach that matches to provided COMID"

**Comment by zhiyuli** [comment]
We refactored workflow of this app. This issue should be gone on apps server.

**Comment by aphelionz** [comment]
This issue was moved to CUAHSI-APPS/nwm-forecast-viewer#16
