### ISSUE TITLE
Uploading a file into a resource is not working - files disappear

### ISSUE THREAD

**Issue by scleveland** [hydroshare/hydroshare#2216]
I have attempted to upload a file into a resource (.csv file) it shows the file uploading and progress but when the upload is complete the file does not show up in the directory.  Uploading another file results in the same result.  Thus no files appear in the resource - downloading the bagit has no data other than the metadata.

**Comment by horsburgh** [comment]
@scleveland - I just tried this and everything looked OK for me. Can you provide a little more information? 

* Are you in edit mode on an existing resource or creating a new resource from the create resource page? 
* Do you have any spaces, special characters, or periods in your file name?  
* Are you uploading to the main content folder of the resource or have you created a folder within the resource into which you are trying to upload files? 

Let us know and we can try and get you sorted.

**Comment by scleveland** [comment]
@horsburgh  - I'm in edit mode. No space or special character.  Just uploading to the main folder (no even sure how to create another folder in there).  Here is a link to a screen video capture of me trying to upload into my "test" resource using the select file dialog and also doing a drag.  As you will note the system indicates the file uploaded, it refreshes and then there is nothing in there. Perhaps it is a permissions issue?
[https://drive.google.com/open?id=0B6TVbd5hgJKxZVNBa192OFkzMTA](https://drive.google.com/open?id=0B6TVbd5hgJKxZVNBa192OFkzMTA)

**Comment by scleveland** [comment]
Ok - so if I scroll down below the yellow info box below the upload area I get a quick 1 or 2 second view of an error before the page refreshes (I would recommend putting the error message not that far below the upload area and also keeping it visible until the user closes it).  The error is - 

File Upload Failed
validation_error: Uploaded file is not a valid timeseries csv file. There needs to be at least 2 columns of data.(Uploaded file was not added to the resource).

However the file has multiple columns and some of it is old voeis timeseries data so it should be valid?  This is a timeseries resource specifically.

**Comment by scleveland** [comment]
So creating a new timeseries resource with the file returns a more meaningful error message:

Validation Error: Uploaded file is not a valid timeseries csv file. Data for the first column must be a date value.(Uploaded file was not added to the resource)

This message displays at the top of the new resource and remains until I close it.  Moving the datetime column to be the first allows my file to upload on newly created resource and editing resource.  

So the true issue here is the error message for uploading into an existing resource displays in a manner that a user may not observe it and makes the system appears not to give any feedback - also the Error message being given back from the edit screen is not as useful as the error given when uploading at create.

**Comment by horsburgh** [comment]
@scleveland - thanks a lot for sticking with it and for reporting your continued experiences. It helps a lot to know that you were uploading to a time series resource, and yes, HydroShare is looking for a particular format for the CSV file. 

We can work on the messaging - both where the errors show up, and potentially some information indicating what the CSV should look like for upload to a Time Series resource.

**Comment by aphelionz** [comment]
@horsburgh Assigning this to you. Can you please close this issue and / or make a new issue to improve the messaging?
