### ISSUE TITLE
Resourcemap.xml not correct in alpha release candidate 1.4.0 rc0

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#222]
resourcemap.xml returned with a resource needs updating.  It still refers to resourcemetadata.json in places and has several url's that do not work embedded in it.  For example  http://hydroshare.org/resources/1.4.0 - Logan DEM/resourcemetadata.json and /tmp/hydroshare/6e3ffe34505e4510990e48c25ce0609b/2015.03.13.19.34.08/contents/logan.tif

**Comment by pkdash** [comment]
This bug has been there since release 1.0. Do we have to fix this for 1.4.0 release? I can take a look at it.

**Comment by dtarb** [comment]
This could wait for 1.5.

**Comment by horsburgh** [comment]
I think this is essentially the same as #169.

**Comment by dtarb** [comment]
This also relates to #258

**Comment by pkdash** [comment]
The fix to resoursemap.xml generation that we did as part of issue #169 in release 1.4 generates the document correctly for any resource created after we applied this fix. The older resources will still have the wrong resourcemap.xml document until the bag is regenerated.

**Comment by dtarb** [comment]
I think that it is best to resolve this after @mjstealey completes bagit restructuring #185. At that point since the folders will be a bit different all resources will need to get moved from the old structure to the new structure.  That seems like a good time to regenerate these metadata documents in a consistent way.

**Comment by horsburgh** [comment]
Resource Map documents currently created on beta.hydroshare.org and playground.hydroshare.org are incorrect.  They were actually more correct before.  Not sure what happened.  Here's what's not right:

1.  Within the description of the aggregation, there should be an ore:aggregates triple for every single content file in the resource, including the resource metadata file.  Right now there is one for the resource metadata file and then a general pointer to the "contents" folder.  The contents folder should not show up as the aggregated object - each file in the contents folder all the way down any sort of heirarchy should be included.
2.  Every file within the aggregation (every file listed in the description of the aggregation with an ore:aggregates triple) must have an rdf:description element. Right now there's one for the resource metadata file, and there's one for the content folder (which there shouldn't be), but there isn't one for any of the content files.

I think this needs to be fixed for the NFIE release.

**Comment by horsburgh** [comment]
By the way - what does the "invalid" label mean?

**Comment by pkdash** [comment]
Here the log shows that I added the 'invalid' label. I have no idea now why I would have done that. I too not sure what the 'invalid' label means. I am removing this label.

**Comment by hyi** [comment]
@horsburgh @pkdash I checked the resourcemap.xml on www and it appears to me the two bullets which @horsburgh indicated above were not correct have been fixed. Could you confirm and see whether this issue is indeed fixed?

**Comment by pkdash** [comment]
@hyi - I think I have fixed it. @horsburgh can check and close this issue.

**Comment by horsburgh** [comment]
This looks good for the most recent resources on www.hydroshare.org, so I'm assuming it's been fixed for a while. Closing.
