### ISSUE TITLE
Data Rods Explorer App: Data retrieval is incurring errors from NASA web-services

### ISSUE THREAD

**Issue by ChristinaB** [hydroshare/hydroshare#2222]
Data retrieval is incurring errors from NASA web-services for the PlotOneVariable and CompareTwoVariables demos, though the YearOnYear plotting demo seems to work fine. These are new developments and have not been updated onto the report yet.

 [Link to the pdf file download to test the broken](https://www.hydroshare.org/django_irods/download/3b65a4ae9d404bbe9b5f232fb0b73d9b/data/contents/DRE_Demo_VisualizeNasa_Jun2017.pdf)

[Link to HydroShare Demo: Visualize NASA data](https://www.hydroshare.org/resource/3b65a4ae9d404bbe9b5f232fb0b73d9b/)

**Comment by ChristinaB** [comment]
Here is the latest version on the State of the App so that it can be updated as the App is updated:
[DRE_assessment_report_jp.docx](https://github.com/hydroshare/hydroshare/files/1142995/DRE_assessment_report_jp.docx)

**Comment by ChristinaB** [comment]
@dtarb  -- if you want to add details about the NASA changes and necessary App changes, here may be be a good place to have that conversation with @aphelionz who can track the App policy white paper and CUAHSI Board suggestions (forthcoming).

**Comment by aphelionz** [comment]
This issue was moved to CUAHSI-APPS/datarodsexplorer#1
