### ISSUE TITLE
Broken resource - exploded when a new file with existing name was added

### ISSUE THREAD

**Issue by ChristinaB** [hydroshare/hydroshare#2224]
Thanks @alvacouch 
I have a new broken resource that had all the files deletes from it when I tried to upload a new version of a file, but a file with the same name already existed.   https://www.hydroshare.org/resource/7a77f525667b42f69cdc3f8db18e1280/
The data has disappeared and even in edit mode, there is no way to attempt to add in new files except to drag and drop.  

I tried to recreate this issue with a new composite resource, and the system worked as expected by giving an error, but no other files were deleted/removed.  

1.  Create new composite resource - add multiple files with similar version names
![image](https://user-images.githubusercontent.com/4108369/28132722-7eaa9874-66f2-11e7-8706-525244469d24.png)

2. Edit Resource and Add a file with the same name (by accident!).  File Upload Failed Error Received.
![image](https://user-images.githubusercontent.com/4108369/28132777-af290ae4-66f2-11e7-8996-d31da88ff69f.png)

What is the difference between this resource that is now broken https://www.hydroshare.org/resource/7a77f525667b42f69cdc3f8db18e1280/
and this resource https://www.hydroshare.org/resource/9c564489f08b48efa1851d796d426b6f/ that gives an error but does not delete the rest of the files?

**Comment by dtarb** [comment]
I am closing this issue.  The Sauk Suiattle Watershed Observatory resource https://www.hydroshare.org/resource/7a77f525667b42f69cdc3f8db18e1280/ was one of the ones intensively tested in resolving file system problems with the current deploy and I believe that issues related to it are fixed.  @ChristinaB if you encounter any further problems with this resource (or other new resources) please create a new issue that documents them.
