### ISSUE TITLE
Profile photo adding not working

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#223]
When I tried to add my photo to my profile it came in huge.  I clicked update, and it was not accepted due to the organization entry not being filled in.  After filling in organization the photo could be added, but is still too big.  This is part of the whole profile clean up needed related to #68

**Comment by horsburgh** [comment]
Part of user profile page redesign by @mauriel133.

**Comment by horsburgh** [comment]
I believe that this is working now on www.hydroshare.org, but replacing the profile picture is not.  I'll close this one and add a new issue.
