### ISSUE TITLE
Suggested Improvements for EPA Waters App

### ISSUE THREAD

**Issue by ChristinaB** [hydroshare/hydroshare#2234]
•	Weaknesses of the App
The location search can return feature names that do not match the search term. This may be confusing to the user as it seemingly selects a different location.
There are navigation problems associated with the different views on the app interface. There is only one vertical scroll bar for the whole interface, but it mainly controls the map. This may hide functions and features on the left-side navigation menu; it seems to have separate scroll controls without a scroll bar. Moreover, when the left-side navigation menu is collapsed, the map view enlarges, but this may hide the map zoom and information buttons (top left and bottom right of the map view).
In some instances, the “delineate downstream watershed” function has encountered errors. The Error message received reads: “Flowline comid 10373572 at measure 100 not found in NHDPlus stream network.” The cause of this error has not be understood. 
•	Opportunities for the App
During the testing phases, no notable additional opportunities were mentioned. The use-case seems to finish without the need for additional help.
•	Potential pitfalls from the demo or external factors
The map is interactive. This information was not given to the user, so accidental clicks can change the selected Feature name.

Find out more about the strengths and testing done to date in this State of the App (SOTA) report:
[EPAwaters_April2017assessment_SOTAreport.docx](https://github.com/hydroshare/hydroshare/files/1160031/EPAwaters_April2017assessment_SOTAreport.docx)
also organized in the HydroShare Google Drive in the [State of the App Reports](https://drive.google.com/drive/u/0/folders/0B8FGrdqHDtsDQlVpZ1pqRF9lUW8) folder

Any updates should also be applied to this HydroShare Help page: [EPA Waters App](https://pages.hydroshare.org/apps/epa-waters-services/)

**Comment by aphelionz** [comment]
This issue was moved to CUAHSI-APPS/tethys_watershed_delin#1
