### ISSUE TITLE
Have "Create your iRODS user account" on main profile page

### ISSUE THREAD

**Issue by jsadler2** [hydroshare/hydroshare#2235]
I found it unclear that I needed to "edit" my profile to create my iRODS user account. In my opinion, it would be better to have it in the "view" mode of the profile page (indicated below)
![image](https://user-images.githubusercontent.com/6943441/28385527-67fdbb8e-6c96-11e7-8986-a6bcd5bc6aec.png)

**Comment by hyi** [comment]
@jsadler2 Since any action is done in edit mode, to be consistent, I'd argue that creating an irods account should be done in edit mode. I do agree users need to be better informed of this, though. I'd propose to add something along the line of ```Go to edit mode to create an associated iRODS account in HydroShare user zone``` after ```You have not created an associated ...``` in view mode. What do you think?

**Comment by jsadler2** [comment]
@hyi I think that would work, though technically they are creating an iRODS user account not editing their profile which may be confusing.

**Comment by hyi** [comment]
@jsadler2 I guess it depends on how you view the relationship between an associated iRODS user account and user profile. I can see argument for both ways. I am bringing in @horsburgh @dtarb @mjstealey and @rayi113 for their input as well. The implementation is easy, but we have to get a team consensus on what makes the best sense from users perspective.

**Comment by horsburgh** [comment]
I don't have a strong feeling either way. But, if it isn't clear that the user needs to edit their profile to add the iRODS account then at least the messaging needs to change to make sure they know what to do.

**Comment by aphelionz** [comment]
I'm with @jsadler2 on this one.

I think we should be migrating most of these interactions out to the profile view page. Having to click edit is slightly annoying in general. It's not the worst thing in the world, but for example I like being able to switch a resource between Public/Discoverable/Private without having to click edit.

**Comment by Castronova** [comment]
stale, closing
