### ISSUE TITLE
Give HydroShare iRODS Host and User Zone in iRODS sign-in dialogue box

### ISSUE THREAD

**Issue by jsadler2** [hydroshare/hydroshare#2236]
I'm thinking it would be good to give users the HydroShare iRODS Host and User Zone in the iRODS sign-in dialogue box so it's clearer how to access that and what to put into those fields. 
So maybe instead of this:
![image](https://user-images.githubusercontent.com/6943441/28387689-135c8f3a-6c9e-11e7-953c-2830208e0f06.png)
This (except the examples will be on the same line (not sure how to do that)):
![image](https://user-images.githubusercontent.com/6943441/28387994-2fbfc2fe-6c9f-11e7-8098-398fa3a81fd6.png)

**Comment by jsadler2** [comment]
@hyi here is another iRODS usability improvement that I thought would be good.

**Comment by hyi** [comment]
@jsadler2 I think this is a good idea. I am thinking to put these user zone host and zone name as the default values for the fields, e.g., ```e.g., hydroshareuserZone``` to replace ```Zone``` in the input box rather than putting it as part of the label. This can be easily done, but I'll wait a bit for others to chime in before working on this.

**Comment by horsburgh** [comment]
More informative = better. I think its useful.

**Comment by aphelionz** [comment]
Yeah, I vote +1 on just assigning the default `value` of the field to `users.hydroshare.org`.

**Comment by hyi** [comment]
This has been implemented. See screen capture below. Closing.
![iRODS_login](https://user-images.githubusercontent.com/476302/78388071-60fa5800-75ae-11ea-806c-d382273bc6ee.JPG)
