### ISSUE TITLE
Add file to raster resource should be disabled when file already there

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#224]
In alpha 1.0.0 rc0 it is possible to add a file to a raster resource.  This results in two files in a raster resource which is inconsistent with the data model.

**Comment by pkdash** [comment]
This bug seems to be a result of conflicts resolution of template file (conflicts due to me and Mauriel working on the same html page). I saw this bug in my working branch (timeseries) when I pulled the latest develop branch on last Friday. I have now fixed that in my working branch. @hyi if you want I can make a hotfix once we have a alpha release branch.

**Comment by hyi** [comment]
@pkdash It'd be great if you can make a hotfix. I fixed this a while ago in my local branch in genericresource.html, which must have been lost due to merging conflict. If you already have a fix, it'd be great to make a hotfix. I am assigning this to you then, Pabitra.

**Comment by hyi** [comment]
@pkdash Do you already have hotfix available locally to be pushed? If yes, could you push it in? If not, I can make a fix specific to raster resource type.

**Comment by pkdash** [comment]
@hyi I don't have hotfix that can be pushed. I fixed this bug in my timeseries branch which we can't push to the alpha. We have to make a separate hotfix for this.

**Comment by hyi** [comment]
@pkdash OK. I will add my old fix in then as part of my pending current pull request pertaining specifically to raster resource type for release 1.4 then.

**Comment by hyi** [comment]
Fix pushed to github and a pull request has been created to merge it into release-candidate-1.4.0.

**Comment by hyi** [comment]
Tested it on alpha and it is working now. Adding ready for testing label.

**Comment by dtarb** [comment]
Tested by adding a file to a raster resource.  The add button is not present when there is a file in the resource so the issue is fixed.
