### ISSUE TITLE
Unable to make a resource public in 1.11 deploy

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#2241]
I just created this resource https://www.hydroshare.org/resource/6cb2da4dffa248c09bc4d7d883fdf4a1/.  I added abstract and keyword and received the message that it could be made public, but when I click on the public button nothing happens.  I am not doing anything that I have not done before, so have to assume this is to do with the 1.11 deploy.

**Comment by horsburgh** [comment]
For what it's worth - I just created a new composite resource and tried to make it public. I got the same result as @dtarb - I can click the button, but nothing happens.

**Comment by aphelionz** [comment]
@dtarb @horsburgh Lucky for you guys my wife and kids are at my mother in law's tonight! I'll take a look ASAP. Any ideas @pkdash or @alvacouch ?

**Comment by aphelionz** [comment]
@dtarb @horsburgh PR created, should fix the issue.

**Comment by dtarb** [comment]
Thanks for the quick work fixing this.
