### ISSUE TITLE
Add page to help on how to create and account

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#2245]
I suggest that a page be added below https://pages.hydroshare.org/introduction-to-hydroshare/ that explains
- How to create a HydroShare account
- Explains that a validation email will be sent requiring email verification
- Indicates profile information required (and a bit about why)
- Explains iRODS accounts

It seems we may have had content like this before, but I cannot find it in the current help system.  @rayi113 if you know where older content was please dig it out.

**Comment by aphelionz** [comment]
Has everything except for iRODS account, @Lizabrazil will lead that effort.

**Comment by dtarb** [comment]
Closing as I think current account creation documentation is sufficient.  @Lizabrazil feel free to reopen, or open a new issue if there are further documentation needs to plan.
