### ISSUE TITLE
Resource-specific metadata is missing from resourcemetadata.xml file

### ISSUE THREAD

**Issue by zhiyuli** [hydroshare/hydroshare#2246]
I just find Resource-specific metadata is missing from 'resourcemetadata.xml' file of some NetCDF resources and  Geo-Feature resources I created recently. 
This is causing a issue when retrieving resource metadata via REST API (hs_restclient) in our apps.

It seems old resources are fine. I am not sure this issue affects other resource types or not.

**Comment by hyi** [comment]
@zhiyuli I am closing this issue but use #2248 to keep track of this issue instead.
