### ISSUE TITLE
Metadata strings updated through hs_restclient are parsed incorrectly

### ISSUE THREAD

**Issue by fryarludwig** [hydroshare/hydroshare#2247]
When using the hs_restclient to update metadata for Generic and Composite resources (I haven't tested other types), string values are updated as a unicode string inside an array (e.g. [u'some_string'] ). 

Here's an example code snippet:
`
put_data = {"title": "New Title", "description": "New Description"}
client.updateScienceMetadata('f44c00556cd847b98dd47f3a6279014d', put_data)
`

Two resources that show this issue:
![image](https://user-images.githubusercontent.com/8953221/28534607-84703f50-705e-11e7-9e73-5edd5058368f.png)
![image](https://user-images.githubusercontent.com/8953221/28534643-984a8530-705e-11e7-84d7-df0ba05379f5.png)

**Comment by horsburgh** [comment]
@aphelionz - do you have any ideas on this? Is this something that we are doing incorrectly on our end?

**Comment by aphelionz** [comment]
I believe the hs_restclient is transliterating the string "New Title" to the python unicode, and then back to a normal string again, which would be represented as "[u'New Title']," which is then passed to the REST api. I'll take a look.

**Comment by horsburgh** [comment]
@aphelionz - any additional feedback on this issue? @fryarludwig is working on a tool to move data from a CUAHSI HydroServer into HydroShare, and we've got nearly the whole thing working - except updating individual metadata elements through the API. This seems like a pretty big issue with metadata updating in the API?

**Comment by aphelionz** [comment]
@horsburgh I will prioritize this next!
