### ISSUE TITLE
resource specific metadata is missing from resourcemetadata.xml

### ISSUE THREAD

**Issue by hyi** [hydroshare/hydroshare#2248]
Reported from @zhiyuli: I just find Resource-specific metadata is missing from 'resourcemetadata.xml' file of some NetCDF resources and Geo-Feature resources I created recently.
This is causing a issue when retrieving resource metadata via REST API (hs_restclient) in our apps.
It seems old resources are fine. I am not sure this issue affects other resource types or not.

**Comment by zhiyuli** [comment]
Tested on www. Thanks @hyi @pkdash @aphelionz @mjstealey 

I believe there are some resources owned by other users also got affected by this issue, so those bags are 'corrupted'. Need a plan to fix them.

**Comment by hyi** [comment]
@zhiyuli Affected resources can be fixed by manually setting metadata_dirty AVU to true so that metadata can be regenerated next time when the bag is downloaded. If needed, this metadata_dirty flag can be set to true manually for all resources to cover this. I believe Michael may have a script handy just to do this, so if it is not urgent, let's wait for Michael to come back and run his script to set this AVU to true for all resources; otherwise, if it is urgent, I can try to take care of this as well, which I prefer not to spend time on unless it is urgent since there is always a risk to touch things on production, especially for people like me who only does things on production occasionally when needed.

**Comment by pkdash** [comment]
@hyi It will be good to create a management command to set this flag for  all resources or specified resources. Let me know if I should write code for this.

**Comment by hyi** [comment]
@pkdash I thought about it too, but still need to run the command on production. May need @mjstealey 
s weigh in on this, but it won't hurt to write such a management command in case it is needed in the future. If you have time for this, feel free to write it.

**Comment by hyi** [comment]
There is already a management command set_bag_dirty.py that can accomplish this, so closing this.
