### ISSUE TITLE
Raster resource metadata editing and defaults

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#225]
Following are suggestions for better managing raster resource metadata
Within Spatial Coverage 
- Place/Area Name should be editable
- Coordinate System/Geographic Projection should be WGS 84 
- Box or Point Longitude and Latitudes should be WGS84 coordinates computed from bounding box and projection in the file if possible.  Should be editable.  This is to accommodate cases where this information is incomplete or incorrect in the file.
- Should be possible to have it as a point in case the raster is so small that it makes sense to regard as a point on the earth.

Extended metadata should include
- File coordinate system and projection.  
- Bounding box information from file (untransformed)
These should in not be editable if they are read from the file.  If they are missing in the file they should be defaulted to "unknown" and should be user editable.

**Comment by hyi** [comment]
Fix has been deployed to dev.renci.org and everything works as expected according to my testing. Setting it to ready for testing. Note that bounding box info is not disabled for editing even when they are extracted from the uploaded file, which has merits in my opinion, to provide the flexibility for users to update bounding box info when needed and write back to geotiff file as needed. The part of writing back to geotiff file is not implemented for Phase I now, but can be done for Phase II.

**Comment by dtarb** [comment]
@gantian127 can you please test this in Dev then if you are happy note this here.

**Comment by dtarb** [comment]
Tian indicated in email that this was working, and it seems to be working based on my testing, so closing.
