### ISSUE TITLE
Extend Hyrax OPeNDAP server/app to provide access to multidimensional file types in public composite resources

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#2250]
The Hydrax OPeNDAP server/app provides OPeNDAP access to public netcdf files that are part of the multidimensional resource type.  This should also be extended to netcdf files that are part or composite resources typed as multidimensional (and fit within size constraints).  This may require file level app launching functionality per #1609.

**Comment by hyi** [comment]
@dtarb @aphelionz @alvacouch I have updated my server-side script that copies public netCDF resources or composite resources with netCDF file type on demand and only refresh data on subsequent requests as needed by comparing the last modified time stamps. I have tested various scenarios and all work as expected, so @cbcunc and I have deployed this update to hyrax production server and @cbcunc has done a basic subsetting test for a big netCDF resource and it works well. @dtarb You can do some testing when you have a chance and let me know if you find any issues with hyrax OPeNDAP service. The backend server script and script trigger code in HydroShare have all been updated to support composite resource type with netCDF file type as well. The only issue remaining for this is to add Open With OPeNDAP service to composite resource type with netCDF file type, and can be addressed when Open With revamp work with ongoing design is done by @danames and @zhiyuli

**Comment by dtarb** [comment]
Based on discussion with @hyi code for this has been merged to develop.  I have verified that nightly script updates netCDF files.  This can be closed once immediate copy of netCDF files in composite resource made public is verified in deployment.  This cannot be tested in a candidate release due to nature of Hyrax server iRODS interactions.

**Comment by aphelionz** [comment]
@hyi @dtarb Can this be closed?

**Comment by dtarb** [comment]
Because this is app based it is not testable on beta.  Wait for www deploy to close.  I can create a composite resource on beta, but OpenDap app assumes www and does not find resource.

**Comment by dtarb** [comment]
Has been done for a while.
