### ISSUE TITLE
Inconsistencies in Multidimensional resource type metadata reading

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#2251]
If I follow the sequence
1. Create New
2. Set resource type as multidimensional
3. Identify a netcdf file that has CF conventions title element (I am testing using the file from https://www.hydroshare.org/django_irods/download/bb9e1cc9e8b0487b99576938029fccb0/data/contents/Data%20Files/SWE_time.nc)
4. Click create resource 
I get a resource that is missing the html title field.
![image](https://user-images.githubusercontent.com/3456833/28566051-40e0d974-70eb-11e7-8567-f708b9c88d82.png)
It also only has the author from the file.

If however I first create an empty multidimensional resource by following the sequence
1. Create New
2. Set resource type as multidimensional
3. Click create resource without adding a file
4. Then on the landing page of the resource created I switch to edit mode and add the file I get a resource with html header element set (good) but the user has been retained as an author (inconsistent with behavior above) and the warning "netcdf file out of sync with resource metadata changes", (but I did not make any resource metadata changes).  Presumably this warning is due to the user having been added as an author but that is not in the netCDF file.  
![image](https://user-images.githubusercontent.com/3456833/28566534-ab1b5b10-70ec-11e7-9497-9cc1429b6a6f.png)

I think that the behavior should be
1. html element populated in creation method 1 above
2. User not added as an author in creation method 2 above (i.e. the creator_name element from the file overwrites and does not add to the list of authors).  This behavior is different from when a netcdf file is added as a multidimensional type to a composite resource, because in that case appending authors makes sense as a composite resource may have multiple logical files, but a multidimensional resource only has one logical file.

**Comment by Castronova** [comment]
Closing. No longer relevant due to re-design into composite resource type.
