### ISSUE TITLE
Improve file download interface

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#2255]
Following is a comment from Rick Hooper on downloading files from HydroShare

http://www.hydroshare.org/resource/bb9e1cc9e8b0487b99576938029fccb0/#comment-108

I tried to double click on a resource to download and get the spinning ball (which did not clear). I found out that i had to right click to download. I should have been presented with an error or a suggestion to right click rather than double click

**Comment by aphelionz** [comment]
There are two issues here:

1. Double clicking on a resource file causes the CPU to max out (I reproduced this on Windows as well as Rick's OSX)
2. It's unclear that single clicking selects the file and right clicking opens the custom contextual menu. 

Maybe we just make double click download the file? That would solve both.

**Comment by horsburgh** [comment]
I like the suggestion for double click to download. 

@Maurier - what do you think?

**Comment by Maurier** [comment]
Double click is usually assigned to trigger primary actions on items in the UI. It is intuitive to open a file (or download in our case) using double click, so I agree it would be a good addition to the file browser interface. 

With this same reasoning, I'd like to point out that for folders double clicking should open said folder rather than download its content.

**Comment by horsburgh** [comment]
Yes - agreed on double clicking folders should open the folder (not download).

**Comment by dtarb** [comment]
@Maurier @horsburgh what is the status of this issue.  I see that there was a PR merged.  The spinning wheel does not seem to occur any more, and double click opens a folder, but double click on a file does not download it (as was part of the discussion above)

**Comment by horsburgh** [comment]
@Maurier - can you have a look at this one and make sure the double click to download is implemented?

**Comment by Maurier** [comment]
> double click on a file does not download it (as was part of the discussion above)
I have tested this in all modern browsers except Safari in IOS. It works as expected on my end. @dtarb, are you still experiencing this issue?

**Comment by horsburgh** [comment]
Just to verify, I tested this on www in the latest version of Safari 11.0 on my Mac. It works as expected - double clicking on a file downloads it. However, there is a slight delay on the download before it happens (in Safari and Chrome) that made me wonder if it was working correctly. If you wait just a second, the download happens.

**Comment by danames** [comment]
In most operating systems, double clicking a file opens the file in an associated application. Does it make sense to have a double click download instead of open? Is there a clever interface design that could allow both?

**Comment by dtarb** [comment]
I have found that double click on files in composite resources does not download a file (even for a very small .txt file).  I found that double click on files in generic and multidimensional resource types downloads all the file occurrences I clicked on (small and large).

**Comment by horsburgh** [comment]
@dtarb - I am going to close this issue. I believe that it is working correctly on www, and for the composite resource case it is working in @pkdash 's most recent deployments on park.
