### ISSUE TITLE
App tracking logs shouldn't contain spaces

### ISSUE THREAD

**Issue by Castronova** [hydroshare/hydroshare#2267]
The activity logs for app launches sometimes contain spaces in the kvp strings.  This causes errors when parsing an results in incomplete/incorrect metadata in Kibana.  For example, `HydroShare` should be `HydroShare GIS`:

![image](https://user-images.githubusercontent.com/4822372/29085945-e39c1b84-7c3e-11e7-8e31-999508dd10d4.png)

2017-08-04 07:13:46.565625+00:00 user_id=536 session_id=290175 action=app_launch name=JupyterHub NCSA user_email_domain=edu resourcetype=CompositeResource resourceid=0a5ce7ffa1da4be0863de9b95df683dc user_type= user_ip=205.175.118.79 husername=jphuong

This makes other things break too:

```
user_type |   | user_ip=205.175.118.79
```

To fix this, replace all spaces with a different *unique* separator.

Moreover, blank values should NOT be allowed in the logs.  Instead use a value of 'Unspecified'

**Comment by dtarb** [comment]
@Castronova is this still an issue.  Please close if resolved.
