### ISSUE TITLE
HydroShare GIS tiling is not loading

### ISSUE THREAD

**Issue by ChristinaB** [hydroshare/hydroshare#2270]
Here is my view of a watershed from a Chrome Browser. HELP!
![image](https://user-images.githubusercontent.com/4108369/29287954-deb96d5e-80eb-11e7-94e6-df1dc615dd33.png)

**Comment by danames** [comment]
Unfortunately, @shawncrawley isn't working on the project but he's probably the one who can figure this out. I've asked him to look into it and give us some suggestions on where to start.

**Comment by aphelionz** [comment]
This issue was moved to CUAHSI-APPS/tethysapp-hydroshare_gis#13
