### ISSUE TITLE
HydroShareGIS is not updating changes to attributes

### ISSUE THREAD

**Issue by ChristinaB** [hydroshare/hydroshare#2271]
These points are set to green.  They are not mapping green.   Here is also another view of the tiling problem (and frustrating message given this does not look successful)

![image](https://user-images.githubusercontent.com/4108369/29288042-2af79b14-80ec-11e7-9229-4ee5c300e61c.png)

**Comment by ChristinaB** [comment]
![image](https://user-images.githubusercontent.com/4108369/29288089-5f2f0340-80ec-11e7-9420-117c42d29141.png)

Steps:  Click on Hamburger, Modify symbology, select new color, Apply.  

You can try it using 'Open With' HydroShareGIS App at https://www.hydroshare.org/resource/70b977e22af544f8a7e5a803935c329c/

**Comment by danames** [comment]
We were hoping that refreshing the Geoserver on a regular basis would take care of this tiling issue. I'll invite Shawn to look at it again and tell us what he learns.

**Comment by aphelionz** [comment]
This issue was moved to CUAHSI-APPS/tethysapp-hydroshare_gis#18
