### ISSUE TITLE
HydroShareGIS App - needs polgyon transparent option

### ISSUE THREAD

**Issue by ChristinaB** [hydroshare/hydroshare#2272]
![image](https://user-images.githubusercontent.com/4108369/29288168-a5cbd0b2-80ec-11e7-9b4c-818a78ef435c.png)

Having limited colors is fine, but 'no fill' is needed to use for watershed boundaries when one would like to see the map in the watershed while viewing the boundary.

![image](https://user-images.githubusercontent.com/4108369/29288273-ff381f3e-80ec-11e7-90e6-cff350f8fc17.png)

**Comment by danames** [comment]
Did you try setting the interior to no fill? That's the "checkerboard" color patch.

**Comment by aphelionz** [comment]
This issue was moved to CUAHSI-APPS/tethysapp-hydroshare_gis#17
