### ISSUE TITLE
Non-human DOI vetting

### ISSUE THREAD

**Issue by Castronova** [hydroshare/hydroshare#2274]
Issue #2229 discusses the need for human interaction during the formal publication process to weed out resources that should not be issued DOI's.  We need to also improve/implement non-human validation approaches to help deter the publishing of "test" resources.  Below are a few ideas (as well as our current methods) that @Lizabrazil  and myself came up with:

[x] Multiple dialogs to let the user know that this action is permanent.
[x] Send an email to @Lizabrazil to check the resource before a DOI is issued.
[ ] Validation of resource content, e.g. title or keywords contain "test", resource does not contain content.
[ ] 24 or 48 hour holding period before a DOI is issued
[ ] holding queue that allows a group of developers to review outstanding DOI requests and either issue or deny requests.  This might be an extension of #2229 that allows multiple people to "accept" doi requests so that we don't have a single point of failure.

**Comment by hyi** [comment]
Agreed non-human validation would be ideal, but with only simple validation like making sure title or keywords not containing "test" is not sufficient to prevent wrongly publishing a resource, for example, this resource https://www.hydroshare.org/resource/b01ff941e62f4d3f8814affcbc3bbc14/ which was just wrongly published does not contain "test" in title or keywords or abstract. We already enforce that resource with no content cannot be made public and hence cannot be published. To make validation work well, I think some machine learning or NLP approaches have to be incorporated to catch signs that the resource may be wrongly published, and I am not sure whether we would want to go with that route. With human-in-the-loop validation, it can be implemented without involving too much effort, but we need to determine a workflow that works best, and make it a sustainable action to justify the effort.

**Comment by aphelionz** [comment]
We could theoretically use Human-in-the-Loop validation to train an ML system, but that seems like overkill. Maybe not though, based on @Lizabrazil's concerns about keeping up with demand as we scale up...

**Comment by rayi113** [comment]
@hyi @aphelionz I like the idea of potentially using machine learning in issuing DOIs with or without a human-in-the-loop in my capacity to think about HydroShare 2.0 resource citation.  Even if we keep humans-in-the-loop for issuing DOIs for the forseeable future, it seems prudent to address an ML approach now for scalability and assesing the performance of an ML approach in tandem with the human approach.

**Comment by hyi** [comment]
@rayi113 incorporating machine learning in HydroShare is intriguing and sounds to me like a good idea in HydroShare 2.0 to pursue. I like @aphelionz 's idea of using Human-in-the-Loop validation to train ML system to make ML work better over time as well.

**Comment by pkdash** [comment]
For human in the loop this Django module may be useful to control publishing resources: https://github.com/javrasya/django-river

**Comment by dtarb** [comment]
I worry that researching machine learning to get this automated is beyond scope.  See # 2229 for my outline of Human in the loop approach.  The computer science folks can write a proposal to get funds to do this.

**Comment by dtarb** [comment]
Closing as CUAHSI made a policy decision to go with a manual review process.  See #2298
