### ISSUE TITLE
Group membership request email message: more information needed

### ISSUE THREAD

**Issue by ChristinaB** [hydroshare/hydroshare#2275]
When a user requests membership to a group, the current message only includes the first name., e.g.

Dear Christina
User Heidi has requested to join your HydroShare group (Landlab).
Click here to find information about the requesting user.
Click on the link below to accept this request.
https://www.hydroshare.org/hsapi/_internal/group_membership/4on-4438f415960b31cd6a31/77/493/?next=/
The HydroShare Team

Now that we are enforcing more information to be added, please include this in the email so the Group owner knows this is a legitimate request by adding
Last Name
Institution
Position

For example, 

Dear Christina
Heidi Cunnick, Lehigh University Graduate Student, has requested to join your HydroShare group (Landlab).

**Comment by horsburgh** [comment]
@Lizabrazil - please work with @hyi to get the wording of this email changed. You may need to consult with @ChristinaB. Please suggest new text, and @hyi can implement.

**Comment by cuahsimarko** [comment]
@Lizabrazil can you confirm the wording in the e-mail as described or offer any changes?

**Comment by Lizabrazil** [comment]
@cuahsimarko Christina's wording works. I'd just add for the signature"
"Thanks, 
The CUAHSI-HydroShare Team"

**Comment by cuahsimarko** [comment]
@mraocuahsi you need to modify both the group_membership.txt file and group_membership.html I just tested and it works.
![image](https://user-images.githubusercontent.com/45397838/56749478-cbc0d380-674f-11e9-8d3a-838932f5fcd7.png)

**Comment by cuahsimarko** [comment]
When you are testing, ensure the Profile of the user you "requested to join" from has the appropriate information, otherwise null/empty string will appear as "no change" in the "e-mail/console"

**Comment by cuahsimarko** [comment]
![image](https://user-images.githubusercontent.com/45397838/56749870-8f41a780-6750-11e9-95a5-6672063cf68a.png)

**Comment by dtarb** [comment]
Refer to https://github.com/hydroshare/hydroshare/issues/3806#issuecomment-782191510 where the email text needed is given.  Implement this at #3806 as one issue.

**Comment by devincowan** [comment]
@Castronova here are the items that will be added to the email:
- Last name
- Organization
- Country
- State
- Email
- Title (if available)
