### ISSUE TITLE
Allow commenters to delete their own comments

### ISSUE THREAD

**Issue by hyi** [hydroshare/hydroshare#228]
A user who makes a comment can delete or edit it later. No one else can edit a comment, except system administrator who can delete an inappropriate comment.
This is the outstanding issue from the issue #186 to be slated for release 1.5.

**Comment by dtarb** [comment]
@hyi what is the status of this issue.  It should be either in 1.5.1 or 1.6.

**Comment by hyi** [comment]
Put it on Release 1.7 for now. Will change it to 1.6 if I can get it done in time.

**Comment by hyi** [comment]
This issue is the same as the newly created issue [#1213], so I am closing this one and use the other one [#1213] to keep track of this issue.
