### ISSUE TITLE
Resource list endpoint returns resources that do not meet the coverage query parameters

### ISSUE THREAD

**Issue by pkdash** [hydroshare/hydroshare#2280]
It seems when a box type coverage is passed to this endpoint the list of resources returned includes some resources that do not have any coverage data. These resource should not be part of the returned resource list.

![image](https://user-images.githubusercontent.com/2523434/163592175-6fcf8b6b-23ee-486c-9e3f-89a962189024.png)

**Comment by dtarb** [comment]
@pkdash please confirm if an issue, and if so document, otherwise close

**Comment by eclark-cuahsi** [comment]
@sblack-usu and @pkdash  to review. thanks!

**Comment by sblack-usu** [comment]
Relevant code https://github.com/hydroshare/hydroshare/blob/develop/hs_core/hydroshare/users.py#L360-L391
