### ISSUE TITLE
Gracefully handle attempts to delete published resources

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#2288]
If I go to the my resources page I can select (place a check next to) a published resource and click delete (the trash can).  I then get prompted to confirm.  If I click confirm I get an indefinite spinning wheel.  This is because the system correctly does not delete a published resource.  However the interface should not hang with the spinning wheel.  Instead I suggest a message when the delete button (trash can) is clicked that says "One or more of the resources you have selected is published.  A published resource may not be deleted."

**Comment by Maurier** [comment]
@dtarb, I need delete permissions on a published resource to test this. Could you give me access in one of our sandboxes? Perhaps beta.hydroshare.org

**Comment by Maurier** [comment]
@dtarb, I found an error and deployed a fix to https://playground.hydroshare.org/my-resources/

Please test and confirm if it worked.

**Comment by dtarb** [comment]
It works properly for me on Playground.

**Comment by dtarb** [comment]
Tested on release candidate 1.13.
