### ISSUE TITLE
NWM Viewer app:  implement "lateset" parameter to retrieve most recent data without specifying a date

### ISSUE THREAD

**Issue by zhiyuli** [hydroshare/hydroshare#2289]
Tim Whiteaker: "I just tried your subsetting service for the first time right now.  What do you think about allowing "latest" as the value for the startDate parameter, so that I can get the latest forecast. This would be helpful because, although you give me the date of the latest forecast, I do not know the hour (e.g., 06, 12, 18) of the latest forecast that you have."

**Comment by zhiyuli** [comment]
Implemented and deployed on at appsdev.
Also a new endpoint (nwm-forecasts/latest-data-info) is implemented to info user what most recent data are available for subsetting:
{  
   'short_range.forcing':{  
      'date':'20170925',
      'time':'16'
   },
   'analysis_assim.forcing':{  
      'date':'20170925',
      'time':'17'
   },
   'analysis_assim.land':{  
      'date':'20170925',
      'time':'17'
   },
   'analysis_assim.terrain_rt':{  
      'date':'20170925',
      'time':'17'
   },
   'medium_range.land':{  
      'date':'20170925',
      'time':'06'
   },
   'checked_at_utc':'20170925-18:42:33',
   'long_range.land.mem1':{  
      'date':'20170925',
      'time':'00'
   },
   'analysis_assim.channel_rt':{  
      'date':'20170925',
      'time':'17'
   },
   'short_range.reservoir':{  
      'date':'20170925',
      'time':'16'
   },
   'short_range.terrain_rt':{  
      'date':'20170925',
      'time':'16'
   },
   'medium_range.forcing':{  
      'date':'20170925',
      'time':'12'
   },
   'long_range.land.mem3':{  
      'date':'20170925',
      'time':'06'
   },
   'medium_range.terrain_rt':{  
      'date':'20170925',
      'time':'06'
   },
   'medium_range.channel_rt':{  
      'date':'20170925',
      'time':'06'
   },
   'long_range.reservoir.mem4':{  
      'date':'20170925',
      'time':'06'
   },
   'long_range.reservoir.mem1':{  
      'date':'20170925',
      'time':'00'
   },
   'long_range.reservoir.mem3':{  
      'date':'20170925',
      'time':'06'
   },
   'long_range.reservoir.mem2':{  
      'date':'20170925',
      'time':'06'
   },
   'long_range.channel_rt.mem4':{  
      'date':'20170925',
      'time':'06'
   },
   'long_range.land.mem2':{  
      'date':'20170925',
      'time':'06'
   },
   'analysis_assim.reservoir':{  
      'date':'20170925',
      'time':'17'
   },
   'long_range.channel_rt.mem1':{  
      'date':'20170925',
      'time':'00'
   },
   'long_range.channel_rt.mem3':{  
      'date':'20170925',
      'time':'06'
   },
   'long_range.channel_rt.mem2':{  
      'date':'20170925',
      'time':'06'
   },
   'long_range.land.mem4':{  
      'date':'20170925',
      'time':'06'
   },
   'medium_range.reservoir':{  
      'date':'20170925',
      'time':'06'
   },
   'short_range.channel_rt':{  
      'date':'20170925',
      'time':'16'
   },
   'short_range.land':{  
      'date':'20170925',
      'time':'16'
   }
}

**Comment by aphelionz** [comment]
This issue was moved to CUAHSI-APPS/nwm-forecast-viewer#13
