### ISSUE TITLE
[DOI Registration] Disable formal publication using the API

### ISSUE THREAD

**Issue by aphelionz** [hydroshare/hydroshare#2292]
Simply remove the functionality from the API as well as the hs_restclient.

**Comment by aphelionz** [comment]
@pkdash I just audited the code and it looks like publishing is not available via the REST API. Can you confirm? I just need a second set of eyes on this. 

There is an `_internal` endpoint that doesn't have an `@api_view` decorator here:  https://github.com/hydroshare/hydroshare/blob/develop/hs_core/views/__init__.py#L679 and I don't see anything else calling that.

The publishing code is very specific so I don't think you can hack it using the flags endpoint or anything like that.

**Comment by pkdash** [comment]
@aphelionz Yeah, I too don't see any rest endpoint for publishing.

**Comment by aphelionz** [comment]
Cool, waiting on @castronova as the third set of eyes to confirm and then will close

**Comment by martinseul** [comment]
@sblack-usu can you please close this or act on it if needed?
