### ISSUE TITLE
[DOI Registration] Pending Queue

### ISSUE THREAD

**Issue by aphelionz** [hydroshare/hydroshare#2293]
- [x] Place resources submitted for publication in a publication pending queue
- [x] Alert reviewers that there are resources pending publication.
- [x] Implement a simple system for reviewers to either approve a resource for publication (click a button) or disallow it (reverting resource to original state) and transmit explanatory message (I suggest email) to the resource owners.
- [x] Add a step to alert users that their resource has been added to the publication queue and that they will be notified once their resource has been approved for publication. This alert should be a message within HydroShare. It should probably also indicate that they can click a button on the resource landing page to remove their pending publication request until the resource has been approved by the reviewer (see #2295). Notification of approval or rejection should be via email once the reviewer accepts or rejects the resource for publication.

**Comment by horsburgh** [comment]
Add a step to alert users that their resource has been added to the publication queue and that they will be notified once their resource has been approved for publication. This alert should be a message within HydroShare. It should probably also indicate that they can click a button on the resource landing page to remove their pending publication request until the resource has been approved by the reviewer (see #2295). Notification of approval or rejection should be via email once the reviewer accepts or rejects the resource for publication.

**Comment by aphelionz** [comment]
Thanks @jsadler2. When we get to this we can discuss if we want to break this into separate tickets or not.

**Comment by hyi** [comment]
@aphelionz I think this issue, although on stage 2, is ready to be worked on. In terms of division of labor between you and me on this issue, I am thinking I can work on all the checkboxes outlined above, and you can work on setting up the process for assigning reviewers and having this list of reviewers for DOI approval available in Django so that the approval page with all pending publications in the queue can be set up to be only accessible by the authorized reviewers. @dtarb suggested to have the list of authorized reviewers in a csv file in a resource so that resource owners can add or remove reviewers as needed, and HydroShare app can access this resource file to retrieve the list of authorized reviewers. This is one way to approach this. The other way I can think of is to use admin console. Feel free to come up with other methods as needed. Does this sound like a good way to divide labor on this issue between us?

**Comment by aphelionz** [comment]
@hyi I need a bit more information - who is allowed to access the admin panel currently? is it only the "admin" user or are there other "staff members" in Django, as they're called?

**Comment by aphelionz** [comment]
Right, but I'm asking - do such users already exist or would we be creating a new security ring for this process?

**Comment by hyi** [comment]
@aphelionz Such users don't already exist and yes, we would be creating a new security ring for this process if this would be the approach we would be going with. Could you spearhead this to come up with a better approach we should go with?

**Comment by mjstealey** [comment]
@aphelionz 

On www:
- admin is the only "**official**" administrative user created for purposes of administering the site.
- Other users have "**administrative accounts**" that grant them the same level of access as the admin role
  - This extends to PIs and lead developers generally (would need to scan the users to verify exactly who this applies to)
- To my knowledge there are no hybrid accounts that have partial admin panel access as would be seen on pages/help.
  - Custom groups can be defined and then attributed to specific users to extend any granularity of permission you want them to have

On pages/help:
- admin is the only "**official**" administrative user created for purposes of administering the site.
- Other users exist with limited "**editor**" permissions to be able to create/update/delete content from the admin panel.
  - The admin panel display limits scope to only show what the user has permissions for

**Comment by aphelionz** [comment]
@mjstealey .@hyi Copy that, and thanks. I see nothing MAJORLY wrong with creation a small group of users and using the built-in permission system to restrict access to just the moderation queue. The code required would be minimal or nil.

**Comment by horsburgh** [comment]
@hyi and @aphelionz - I know @dtarb suggested maintaining the list of resource reviewers in a CSV file inside a HydroShare resource. The discussion you have had above where you are proposing to instead define these people using the Admin functionality in Django (not as admins but as a new kind of user with reviewer/publisher rights) seems to me like the right way to go.  I'm kind of going from the gut here, but doing this via a resource seems like it would require custom programming to read that resource to check permissions, etc. and it is effectively adding another type of access control to our system. I don't think we want/need to build something new for this. Plusd

All that said - I think @dtarb suggested doing it as a resource so the list of reviewers/publishers could be easily maintained. So - as long as doing this via the Admin panel in Django remains pretty easy (multiple people can easily manage the list in a timely way), I'm all for it.

**Comment by hyi** [comment]
@horsburgh @aphelionz @mjstealey @cbcunc I played a bit with Django admin on beta, created a resource publication approval board group, and added myself with staff status into the group, and played a bit on assigning limited permissions to this group. It seems to me the default Mezzanine admin functionality does not have the granularity we desire for managing resource publication approvals. For example, I believe @dtarb wants that the designated users can add or remove users to the resource publication approval group without admin privilege. However,  if the admin gave "add and change user" permissions to this group of designated users, these users would be able to add users, and even delete existing users. It is possible I did not find the right way to do this in the default admin panel, so it'd be great if others could chime in and see if the default Mezzanine admin panel would allow us to control the permission as we desire, e.g., only allow a staff member who can login to admin panel and add or remove an existing user to or from that specific resource publication approval group without admin power beyond that.

**Comment by dtarb** [comment]
One other thing to consider is whether we want to build additional dependency on Mezzanine admin features.  Some on the team are pushing for removing Mezzanine, and while that may be a major rethink, not building dependency where it can be avoided may be wise.

**Comment by hyi** [comment]
@dtarb Mezzanine admin is built on top of Django admin with some enhancement, mainly on menus, orderings, etc. See http://mezzanine.jupo.org/docs/admin-customization.html for details. I don't think we will be using specific Mezzanine customized features, but rather only use the standard Django admin features with built-in permissions.

**Comment by horsburgh** [comment]
@dtarb - agreed. I was under the impression that this was a Django functionality and it looks like @hyi confirms that we wouldn't need to use Mezzanine.

**Comment by dtarb** [comment]
OK.  I was just keying of the writing that named "Mezzanine admin" not Django admin.  I am happy for you to all do what is simplest.  I offered the CSV in a resource solution because I thought it would be simple and not require any additional interface elements.

**Comment by aphelionz** [comment]
@dtarb Makes total sense. As it stands we can do this using core Django admin features and core Django groups, which is great. I can personally live with needing to loop an admin user in to add/remove somebody from the publication approval group, as it won't be happening very frequently.

🥇 **HOWEVER** 🥇 

If we need to, each `ModelAdmin` instance has some functions you can override to only give users access to certain subsets of the data. A generic example that filters the list of users to only members within some `Organization` looks like:

```
def get_queryset(self, request):
        if not request.user.is_superuser:
            organization_user = OrganizationUser.objects.filter(user=request.user)
            organizations = Organization.objects.filter(organization_users=organization_user)
            users = User.objects.filter(organizations_organization__in=organizations)
            return Button.objects.filter(user__in=chain(users, [request.user]))

        return Button.objects.all()
```

That's almost certainly way beyond the pale for this task, just something we can consider for future reference.

**Comment by hyi** [comment]
@aphelionz @dtarb @horsburgh I agree with @aphelionz that since adding or removing users to or from the resource publication approval group should be infrequent, it sounds reasonable for system admin to manage this. If we can live with this, the code just need to only allow this resource publication approval group members to access the resource publication pending queue, which is easiest without requiring any coding.

**Comment by aphelionz** [comment]
@dtarb @Lizabrazil 

I need text for two emails:

1. one to be sent to the user to let them know that their resource publication status has changed, which will contain the reason for the change (positive or negative)
2. The other to be sent once a day to the publication review group to let them know that # number of resources need their review.

**Comment by dtarb** [comment]
1. See my answer to #2295.  I believe that answers 1.
2. "There are \<insert number> resources awaiting review and pending publication in HydroShare.  Please go to http://\<give url> to approve or reject them."

**Comment by cuahsimarko** [comment]
This has been indexed alongside over 20 related GH Issues, and relevant information extracted into a growing design document, and reorganized beneath major topics. Areas for meeting/presentation/async viewing by stakeholders, meetings and discussion/action items are also designated. This is WIP.
