### ISSUE TITLE
[DOI Registration] Metadata Updates

### ISSUE THREAD

**Issue by aphelionz** [hydroshare/hydroshare#2294]
Change messaging in help pages and on any other websites to be consistent with this approach. The messaging should be clear that this is a value added service provided by CUAHSI to ensure that published resources are of a minimum level of completeness to facilitate discovery. Messaging should also include the criteria used for review (see list below).

**Comment by horsburgh** [comment]
This is assigned to @Maurier, but I think this is an issue for Liza/CUAHSI. I'm going to reassign.

**Comment by cuahsimarko** [comment]
This has been indexed alongside related GH Issues, and relevant information extracted into a growing design document, and reorganized beneath major topics. Areas for meeting/presentation/async viewing by stakeholders, meetings and discussion/action items are also designated.
