### ISSUE TITLE
[DOI Registration] Design Training Module

### ISSUE THREAD

**Issue by aphelionz** [hydroshare/hydroshare#2297]
Develop an online training module that provides guidance for users on preparation of resources for publication and the DOI publication process

**Comment by dtarb** [comment]
I am unassigning myself and @ChristinaB as I need to delegate activities like this and Christina may not have time (but she is welcome to take it back if she wants).  I am assigning @Lizabrazil as I think this fits in CUAHSI's user support work.  I am happy to review design drafts, but will not be able to develop the initial design.

**Comment by Lizabrazil** [comment]
We have several help articles and a pdf guide to data publishers now, closing

**Comment by Lizabrazil** [comment]
Appropriate documentation will be developed when DOI work is completed.

**Comment by ChristinaB** [comment]
@Lizabrazil  can you give links to the help articles and pdf guide? I will share it with Waterhackweek participants as part of motivational prompts to get project work finalized. Thanks!
