### ISSUE TITLE
Fail to create resource when file names include unicode characters

### ISSUE THREAD

**Issue by hyi** [hydroshare/hydroshare#2299]
This issue came from iUTAH data measuring oxygen levels. For some reason, file names include some unicode characters even if they cannot be distinguished from normal characters. Used their test data to reproduce the issue.

**Comment by horsburgh** [comment]
@hyi - yes, this came up with an iUTAH resource that had a file containing a strange unicode character. We explained to the user that he probably shouldn't have unicode characters in the filename and so renaming the file was a short term fix for this one case. But, I'm not sure we can count on this never happening again with other users.

**Comment by hyi** [comment]
@horsburgh @Maurier @aphelionz I tried to verify this fix on dev.hydroshare.org and found even though the unicode issues have been resolved on Django side, it still exists on iRODS side although it works just fine with iRODS docker container which I was using in my local development environment when testing the fix. After some further investigation, I found iRODS can indeed handle file names with unicode, and the issue should be caused by the django_irods submodule we use to interface with iRODS from HydroShare. I will have to work on this further to get it fully resolved.

**Comment by hyi** [comment]
@horsburgh @Maurier @dtarb I believe you all have the test files that include unicode character in file names. Can you test it out on dev.hydroshare.org to see if this unicode in file name issue gets resolved? I created a PR for django_irods submodule here: https://github.com/hydroshare/django_irods/pull/31 and already manually applied that fix on dev.hydroshare.org. Before applying the fix, it gave me the unicode encoding error, but after the fix, everything works. I tested various file-related workflow including creating a resource, deleting file from resource, adding file into resource, deleting the whole resource, and everything works. It'd be good to get your confirmation to make sure it does work on dev, then that PR can be merged and this issue can be closed. looping in @aphelionz as well since I asked him to code review that PR.

**Comment by horsburgh** [comment]
@hyi - should I be able to log in at dev.hydroshare.org to test this? I can't.

**Comment by dtarb** [comment]
@horsburgh you may have to create an account.  I think that every time dev stands up it is clean, as opposed to other testing platforms that may be stood up with live data.

**Comment by hyi** [comment]
@horsburgh Right, dev is different from other VMs, it does not have database pre-populated. So you'll have to sign up to create a new account, then login, and go from there to test it out.

**Comment by horsburgh** [comment]
@hyi - I just created an account on dev.hydroshare.org to try this. First, the resource creation page was not the most recent interface. "Composite" was not the default resource type and the drag and drop interface was not present. I clicked the button to add files to the resource through the file browser. I selected the set of files that created this error in the past and then clicked the button to create the resource. I get a Unicode error:

![image](https://user-images.githubusercontent.com/3485902/30489268-0aed9a64-99f4-11e7-840e-8426126515a0.png)

**Comment by hyi** [comment]
@horsburgh Weird, I took a look at dev and made sure the new code is there. Then I restarted the server and ran collectstatic. I have no idea why it is old interface for create resource page on dev, but I tested it again with two test files and they all work without unicode issues. Can you give it a quick try and see if it makes any difference? If you still run into this unicode issue, can you attach the test file here or send me the test file so that I can give it a try to see if I can reproduce it? The test files I used were from Maurier which I have been using to test and make the fix, and those test files seem to work without issues on dev for me now.

**Comment by hyi** [comment]
@horsburgh I just tried on beta and this issue appears to be fixed on beta as well. Can you give it a try on beta first to see if it works for you without unicode issues on beta?

**Comment by horsburgh** [comment]
@hyi - no joy. On beta.hydroshare.org I get the issue as originally submitted - I drop the files in the upload area and when I click "Create Resource," the files change so they have a red outline and when I hover over them I get a big red pop up with a bunch of code in it. There are 13 total files, but I think only one of them has the unicode issue. I'll try to figure out which one it is and link it to this post.

**Comment by horsburgh** [comment]
@hyi - The file I just posted is the culprit. Interestingly, GitHub handled it no problem. If you do not get the issue with the file I uploaded let me know and I will send it to using another mechanism. I have no idea if GitHub modified the file in any way.

**Comment by hyi** [comment]
@horsburgh I looked at beta and found my new code is not there. I think for some reason, the unicode were probably stripped out at some point for the test files I have been using to test this issue. Let me dig out Maurier's original email and save attachement again to try it out and see if I can reproduce this issue. Will keep you posted.  
Oh, I just saw your latest post. I actually tried the file you posted there, but could not reproduce the problem. Can you just email me this problematic file? That would save me from digging out the old email to find the attached files. Thanks.

**Comment by hyi** [comment]
@horsburgh I believe I finally got to the bottom of this issue. I have created PRs and once approved it can be merged and made into the next release 1.13. The code has been deployed on park.hydroshare.org for you to test. I have used the file you sent me which still fails on beta, but succeeds on park with the whole workflow including resource creation, deletion, adding and deleting files. Please test it out on park and let me know if you still run into issues with this. Thanks.

**Comment by horsburgh** [comment]
@hyi - getting closer. I was able to successfully create and edit a resource using the offending testing files on park.hydroshare.org. Unfortunately, when I tried to download the zipped bag I get the same unicode error. Downloading individual files worked correctly.

**Comment by hyi** [comment]
@horsburgh Thanks for testing bag download which I had not tested, but I just tested that on beta, and it worked for me. I made that resource public for you to take a look here: https://park.hydroshare.org/resource/b9789fc0561b4c809e62c86ff193da3e/ 
Can you make the resource you tested with bag download issue public or share it with me so that I can use that resource to reproduce the issue, then further debug and make any further fix as needed?

**Comment by horsburgh** [comment]
Here it is: https://park.hydroshare.org/resource/11edad2f4680485e9917f09c4f5323c7/
It should be public.

**Comment by hyi** [comment]
@horsburgh Just made a further fix. The bag download for your resource above now works. Also updated my PR with this further fix, looping in @aphelionz to keep him informed while doing code review for this issue. Can you test again on park and confirm this indeed fix the bag download issue?

**Comment by horsburgh** [comment]
@hyi - I just tested this again on park. It worked all the way through the bag download. +1 from me.

**Comment by hyi** [comment]
@horsburgh I have checked on beta release candidate for 1.13 and everything works as expected. Just to make sure, can you do a quick check as well on beta and close this issue if everything works as expected now?

**Comment by horsburgh** [comment]
Tested and everything works as expected on beta. Closing.
