### ISSUE TITLE
Checkbox for agreement to file download not working 

### ISSUE THREAD

**Issue by pkdash** [hydroshare/hydroshare#2302]
It seems a regression issue. Needs to be a hotfix for master.

**Comment by dtarb** [comment]
Verified fixed on www.

**Comment by dtarb** [comment]
This is not working on RC 1.13

**Comment by pkdash** [comment]
@dtarb This was a hotfix on master and seems didn't make into develop. @phuongdm or @aphelionz can one of you fix it?
