### ISSUE TITLE
Prevent editing of file level metadata for reference timeseries file type

### ISSUE THREAD

**Issue by pkdash** [hydroshare/hydroshare#2304]
This includes title, keywords and temporal coverage.

**Comment by dtarb** [comment]
Content should only be non editable if it is part of the refts file.  Did we settle on what mandatory entries were?  Are title and keywords among them.  If title and keywords are not required parts of the file, then they could and should still be editable.

**Comment by pkdash** [comment]
@dtarb 
The last example of json file that I got from @danames had only 'sampleMedium' as optional, which means everything else is required. Also in the same example he had 'sampleMedium' set to 'unknown'. So I did not make it optional. However, you wanted 'title', 'keywords' and 'abstract to be optional. So in the current implementation only those 3 are optional.

So you want these 3 elements (title, keywords and abstract) to be editable? Also I assume we are still not going to update the json file.

**Comment by dtarb** [comment]
I certainly do not want to redesign what is settled, so I think you should go with what @danames and @martinseul had as required.  What I was trying to get clear is implementation of the principle that content that comes from the JSON file should not be editable, whereas content that is not in the JSON file should be user editable, so users can add it.

With this:
- If an item is required and the file does not have it, then the file gets rejected and not converted to refts type.
- If an item is required and the file has it then it is loaded from the file and not editable in Django.
- If an item is optional and present in the file, then it is loaded from the file and not editable in Django.
- If an item is optional and not present in the file then it is editable in Django so users can add it.  The file is not updated so the only record of the value is in Django and the resourcemetadata.xml file generated from Django.

**Comment by pkdash** [comment]
I will be then making further changes to implement these new set of requirements. Hope to get it done by next week.

**Comment by dtarb** [comment]
Sorry that my pointing out of small shortcomings in #1571 has ballooned into new requirements.

**Comment by dtarb** [comment]
Tested and OK on beta release candidate.
