### ISSUE TITLE
Find and edit HTML links in help.hydroshare.org that still point to pages to point to help

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#2306]
There are links in help.hydroshare.org that point to the deprecated pages.hydroshare.org.  

Specifically many links in https://help.hydroshare.org/modeling/ and https://help.hydroshare.org/modeling/jupyter-python-notebook/

The issue #2277 is updating links in www.hydroshare.org, but these links in help.hydroshare.org will require manual editing (I do not know of an automated way to fix these).

**Comment by Lizabrazil** [comment]
@dtarb When i go to hydroshare.org and click on HELP it navigates to pages.hydroshare.org 
I do not see the help.hydroshare.org implemented anywhere on the site. I cleared my cache.

**Comment by Lizabrazil** [comment]
@mjstealey I think this is something only you have the admin to fix..?

**Comment by dtarb** [comment]
@Lizabrazil help.hydroshare.org will be implemented soon once #2277 and associated pull request #2278 get deployed.  Then help will be the operational help site.  The editing issue here is to get help.hydroshare.org ready for this by getting all its internal links correct.

**Comment by rayi113** [comment]
Occurances of https://pages.hydroshare.org/* have been manually changed to https://help.hydroshare.org/* on https://help.hydroshare.org/ (refresh browser page prior to testing this).

**Comment by dtarb** [comment]
Searching in help.hydroshare.org does not find any remaining issues of pages.hydroshare so closing.
