### ISSUE TITLE
NWM Viewer: handle polygon with holes

### ISSUE THREAD

**Issue by zhiyuli** [hydroshare/hydroshare#2307]
Current subsetting api has some troubles in handling polygon with holes.

polygon file from Tim Whiteaker
![image](https://user-images.githubusercontent.com/10070599/30126387-0c7798c8-92f9-11e7-9dfa-2e727cc273c2.png)

**Comment by zhiyuli** [comment]
It turns out to be a 'invalid' geometry issue. The original polygon (shapefile) is a self-intersection polygon which is not supported well in GeoJSON format. After fixing the intersected portion, subsetting API started working again.
![image](https://user-images.githubusercontent.com/10070599/30136845-fbb8d504-931d-11e7-8a22-7d3bd59602eb.png)

![image](https://user-images.githubusercontent.com/10070599/30136858-045c9826-931e-11e7-8f12-ce2e77113566.png)

**Comment by aphelionz** [comment]
Wow, good catch!

**Comment by aphelionz** [comment]
@zhiyuli Can this be closed?

**Comment by zhiyuli** [comment]
closed
