### ISSUE TITLE
NWM Explorer app failed to download files

### ISSUE THREAD

**Issue by zhiyuli** [hydroshare/hydroshare#2312]
Tim from UT Austin reported NWM Explorer app on appsdev server failed to download some NWM files.
A initial investigation indicates some exceptions occur when extracting file metadata/attribute from Linux file system.
A quick dirty remedy has been applied that skips file metadata extraction and display once any exception occurs, which should be able to let users download the files they want for now. 
![image](https://user-images.githubusercontent.com/10070599/30395949-2b0fb266-9885-11e7-80f1-7ac7c45f8c91.png)

![image](https://user-images.githubusercontent.com/10070599/30395940-22841768-9885-11e7-8af7-41e2ab1c2180.png)

**Comment by aphelionz** [comment]
This issue was moved to CUAHSI-APPS/tethysapp-nwm_data_explorer#1
