### ISSUE TITLE
Private sharing link

### ISSUE THREAD

**Issue by lichray** [hydroshare/hydroshare#2313]
Intro
=====

Feature request.  This feature presents in Figshare.  A resource owner can request generating a link to allow any user who obtained the link to have read access to the private resource.  The concept also present in many collaboration products as well, such as Google Docs, HackMD, etc.

Details
======
Figshare also support disable the link, and if the resource owner request generating such a link again, he/she will get a new link.  Some existing products will give you the same link again, but it seems that disable a already generated link is a common demand.  Producing a different link may worth considering though.

**Comment by phuongdm** [comment]
Figshare should have link's life time. In most of file sharing sites, links will be dead after one month.

**Comment by lichray** [comment]
In Figshare the link is dead after user "Yes, disable" the generated link.  I don't think it automatically expires.  Do you think expiring is necessary?  I feel expiring makes more sense for sites purely made for sharing rather than for long term storage.

**Comment by phuongdm** [comment]
In file sharing sites, premium users (of course paid money users) can keep their links alive forever (but have to keep paying :)) . With Figshare, we should give this ability for our "valued member". Who is "valued member":
+ who is usually login, upload resource, use HS app...
+ has some publications
+ we think they are "valued member" 
...
with others who login once or twice times per year, and did nothing... We are sorry, your link has only 1 week/month/year before expired.

**Comment by lichray** [comment]
However, as long as a user filled in the necessary information he/she can make the resource public, and that will be permanent... Being said that this level of details doesn't affect myself; but the private sharing link itself is necessary for us to simplify collaboration.

**Comment by aphelionz** [comment]
Discussed at 9/18 dev meeting - @alvacouch will investigate

**Comment by dtarb** [comment]
[PrivateLinkSharingThread.pdf](https://github.com/hydroshare/hydroshare/files/5706904/PrivateLinkSharingThread.pdf)

@pkdash Can you take a look at this during down times in modeling work.

**Comment by dtarb** [comment]
Add a button "Generate private link" (in edit mode) that then shows the link.  Adjacent to the displayed link have button "Disable link" to turn it off.

**Comment by dtarb** [comment]
Refer to discussion notes https://docs.google.com/document/d/1ReqmZ66MZnWwAaqRLIGWWP46b7x_tTpHo6vYbKWBDEE/edit

**Comment by dtarb** [comment]
@martinseul Refer to discussion notes https://docs.google.com/document/d/1ReqmZ66MZnWwAaqRLIGWWP46b7x_tTpHo6vYbKWBDEE/edit

**Comment by devincowan** [comment]
@ClaraCogswell this Private Link Sharing feature will be included in our next release of HS. We need to update the documentation to include this info. This is Pabitra's implementation but I've done some testing around it so I'm familiar and would be happy to show you so that you can document? Thanks!

**Comment by ClaraCogswell** [comment]
What is the final decision on how quickly the link will expire? I need to know for documentation purposes. Once it is rolled out I can add screen shots of the button placement to the documentation

**Comment by ClaraCogswell** [comment]
The page is updated and ready to be deployed, I can either deploy it now or deploy it on Tuesday morning with the release, is there a preference?
