### ISSUE TITLE
Decomission old help page

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#2317]
The page https://www.hydroshare.org/help/ is still active in HydroShare.  Prioir to establishment of help.hydroshare.org this was the help and was maintained by @rayi113 .  I think the following needs to happen.

- [x] Documentation team @Lizabrazil to review https://www.hydroshare.org/help/ and make sure any content of value from there is included in current help pages. Check the box here when done.
- [x] The code behind https://www.hydroshare.org/help/ and page in Mezzanine to be removed.  It would be best if @rayi113 and @cbcunc could facilitate this.

**Comment by cbcunc** [comment]
Merged in #2468.
