### ISSUE TITLE
NWM viewer app: merge all days into a single file for subsetted analysis_assim

### ISSUE THREAD

**Issue by zhiyuli** [hydroshare/hydroshare#2319]
Feature request from Tim (UT Austin):
 
The subsetting service currently creates one merged analysis_assim file per day.  Instead, can you merge all days into a single file?

**Comment by zhiyuli** [comment]
deployed at appsdev.
Help page will be updated to reflect this changes shortly.

**Comment by aphelionz** [comment]
This issue was moved to CUAHSI-APPS/nwm-forecast-viewer#11
