### ISSUE TITLE
GIS app: Forgetting Projections?

### ISSUE THREAD

**Issue by crae2244** [hydroshare/hydroshare#2320]
I have uploaded a shapefile to Hydroshare. When I select "view With" -> "GIS App", the layer loads but in Africa, not in Missouri where it should. Below is the link to the resource. 
https://www.hydroshare.org/resource/87507f766e634c9199b1f9275c14e9ad/

**Comment by aphelionz** [comment]
This issue was moved to CUAHSI-APPS/tethysapp-hydroshare_gis#12
