### ISSUE TITLE
Unable to create/update "Funding Agencies" resource metadata via the API

### ISSUE THREAD

**Issue by fryarludwig** [hydroshare/hydroshare#2321]
I'm using the hs_restclient to create resources and update their metadata. The resource's title and abstract can be set and updated without issue. When setting/updating funding agencies, HydroShare responds in one of two ways: If the JSON for the funding agencies portion is syntactically correct, the request succeeds but the funding agencies are not updated. If the JSON for the funding agencies is incorrect, the request fails. Below is an example JSON payload that succeeds but does not update the funding agencies metadata:

`{'funding_agencies': [{'award_number': '1208732', 'agency_name': 'National Science Foundation', 'agency_url': 'http://www.nsf.gov', 'award_title': 'iUTAH-innovative Urban Transitions and Aridregion Hydro-sustainability'}], 'description': 'This dataset contains raw data for all of the variables measured for the iUTAH GAMUT Network River Heights Bridge Storm Drain (LR_RH_SD). Each file contains a calendar year of data. The file for the current year is updated on a daily basis. The data values were collected by a variety of sensors at 15 minute intervals. The file header contains detailed metadata for site and the variable and method of each column.', 'coverage': [{'type': 'period', 'value': {'start': u'', 'end': u''}}], 'title': 'iUTAH GAMUT Network Raw Data at River Heights Bridge Storm Drain (LR_RH_SD)'}`

**Comment by darksinge** [comment]
I know this was asked a while ago, but I came across the same problem. 

The `funding_agencies` keyword shows up in `hs_restclient` library's documentation, which is where I think the confusion comes from. It turns out `funding_agencies` is the wrong keyword. The correct one to use is apparently `fundingagency`, and is a dict containing the data for a single funding agency.

This code snippet worked for me, which successfully created a resource and added a funding agency.

```python
metadata = [{'fundingagency': {
        'agency_name': resource.funding_agency,
        'award_title': resource.award_title,
        'award_number': resource.award_number,
        'agency_url': resource.agency_url
    }
}]

self.client.createResource(resource_type='CompositeResource',
                                         title=resource.title,
                                         abstract=resource.abstract,
                                         metadata=json.dumps(metadata, encoding='ascii'))
```

I figured this out by looking at the [unit tests for creating a resource (line 167)](https://github.com/hydroshare/hydroshare/blob/develop/hs_core/tests/api/rest/test_create_resource.py).

**Comment by cuahsimarko** [comment]
@zhiyuli given your familiarity from working with REST client lately, can you provide and useful details if this is a REST API repo issue or hydroshare/hydroshare issue or any other helpful info?

**Comment by Castronova** [comment]
@sblack-usu Is this still relevant given the recent work you're doing on the API? Please comment and close.

**Comment by sblack-usu** [comment]
You can't add funding agencies at resource creation, but you can add them after by hitting the `​/hsapi​/resource​/{id}​/scimeta​/elements​/` endpoint.  The equivalent call on hs_restclient would be `updateScienceMetadata()`.  And yes, the hs_rdf work allows you to update funding agencies in an object oriented manner.  We're aiming for the first hs_rdf release to happen this month.
