### ISSUE TITLE
Private shared resource prompting for login doesn't land on that resource after logging in

### ISSUE THREAD

**Issue by rayi113** [hydroshare/hydroshare#2323]
In the current version of HydroShare, when a private link is shared e.g. https://www.hydroshare.org/resource/8b0f1122242b41a4a1762be4dfb59b14/ ,  and a user with valid access to that resource is not logged in, once the user logs in HydroShare only lands them on the HydroShare overall landing page, and not on the landing page for that specific resource.  This is inconsistent with best practice that when an unauthenticated resource link is shared routinely with another user e.g. in email, upon authenticating it would land the user directly on that resource.  The current approach may inefficiently cause the user after authenticating either to search through their resources for that particular shared resource, or again click the shared link after authenticating.

![hd_private_resource](https://user-images.githubusercontent.com/2846017/30600311-1bc39500-9d2d-11e7-8f23-4999ad73679c.png)

**Comment by Lizabrazil** [comment]
This is being fixed by https://github.com/hydroshare/hydroshare/issues/2556
