### ISSUE TITLE
HydroShare GIS does not accommodate Web Mercator Projection

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#2326]
This is reproducible with data in the test resource https://www.hydroshare.org/resource/148de6e6b8354318be24f68c128f3c7c/

The file SMFlowlineGeo.zip in NAD 1983 coordinates displays correctly in HydroShare GIS

The file SMFlowlineWebM.zip that is the same data in Web Mercator coordinates causes an error in HydroShare GIS.

**Comment by dtarb** [comment]
For easier testing the resource https://www.hydroshare.org/resource/142ff904212144c2842abba738de8d14/ holds the SMFlowline shapefile with Web Mercator projection from the zipfile in the resource above.

**Comment by aphelionz** [comment]
This issue was moved to CUAHSI-APPS/tethysapp-hydroshare_gis#11
