### ISSUE TITLE
NWM Viewer: add a new endpoint to return spatial query results

### ISSUE THREAD

**Issue by zhiyuli** [hydroshare/hydroshare#2327]
add a new endpoint /nwm-forecasts/spatial_query/ to return a list of stream/reservoir comids or grid cell ids that intersect with a given polygon geometry.

User can use this results to inspect if the right features are included before performing real subsetting job and estimate how much time it will take.

**Comment by zhiyuli** [comment]
deployed at appsdev
new endpoint implemented as "nwm-forecasts/spatial-query"

**Comment by dtarb** [comment]
We need discussion about apps that have an API vs general system API functionality.  What is the best design.

**Comment by dtarb** [comment]
After discussion agreed that apps are totally free to have an API.

**Comment by aphelionz** [comment]
This issue was moved to CUAHSI-APPS/nwm-forecast-viewer#10
