### ISSUE TITLE
Add map based spatial coverage editing for composite resources

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#2330]
For a generic resource it is possible to edit spatial coverage metadata by interacting with the coverage map.

Similar functionality is needed for the coverage metadata of a file in a composite resource.  At present text based coverage information can be added, but there is no map to edit.

**Comment by aphelionz** [comment]
@Maurier @dtarb Pull request was merged. Can this be closed?

**Comment by dtarb** [comment]
Unless I am missing something this is not working on beta.hydroshare.org.  I do not see a Google Map for editing coverage metadata for the file type spatial coverage of a composite resource.

**Comment by Maurier** [comment]
@dtarb this is accessible by clicking on the widget on the input.

![image](https://user-images.githubusercontent.com/2448568/33520484-e94d699e-d778-11e7-91f8-d30479857df9.png)

**Comment by dtarb** [comment]
I did not find that at all intuitive.  It is different from other editing patterns we have, such as for generic where the map is always there.  I did not realize there was anything under those buttons.   It is also confusing if I already have a coverage set and go to edit it, it does not show me the box or point already set.  So there is no real adjusting of an existing coverage, just starting new.  Also I do not like the map window that pops up.  It is small compared to my screen.  I cannot enlarge it (except for full screen).  I cannot move it around.  It just seems limiting.

However, given the late hour, I do not think this should be a show stopper for AGU.  You and @horsburgh can discuss whether to leave this open, or close this and tackle a more natural way to edit these coverages as part of the composite resource interface overhaul that is brewing.  See @horsburgh comments in #2366 for where he also had trouble with this.

**Comment by Maurier** [comment]
@dtarb, I agree with your suggestion above. However, when this was first requested it was described as it is implemented now.

See https://github.com/hydroshare/hydroshare/issues/1966

**Comment by aphelionz** [comment]
@Maurier and @dtarb I suggest closing this and creating a new enhancement ticket with the feedback

**Comment by horsburgh** [comment]
Modifying the coverage for a composite resource has changed completely. I'm closing this issue as it is based on the prior implementation.
