### ISSUE TITLE
Metadata extraction slow for MODFLOW MI

### ISSUE THREAD

**Issue by jsadler2** [hydroshare/hydroshare#2332]
When either a '*.dis' file or a '*.nam' file is uploaded to a MODFLOW Model Instance, these files are read and metadata is extracted from them. This process takes quite a long time (maybe 30 seconds). It would be nice to have it done quicker, if possible.

**Comment by jsadler2** [comment]
@edwmorgan I think a good thing to do initially would be to benchmark the process to see how long it takes with 
1. neither the '*.dis' or the '*.nam' file
2. just the '*.dis' file
3. just the '*nam' file
4. both of them

**Comment by edwmorgan** [comment]
Upload times for Issue #2332
1. no files: 4.45s
2. example.dis ONLY: 11.61s
3. example.nam ONLY: 16.64s
4. both files: 21.23s

**Comment by goodalljl** [comment]
@jsadler2 @edwmorgan Checking on this issue to see about progress.

**Comment by goodalljl** [comment]
@jsadler2 checking again on status for this issue. Any updates?

**Comment by jsadler2** [comment]
@goodalljl, we haven't looked at this lately. It's been put on my backburner.

**Comment by goodalljl** [comment]
Ok, moving to the backburner for now.

**Comment by dtarb** [comment]
Stale.  Being deprecated.
