### ISSUE TITLE
Account confirmation message should indicate email address

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#2333]
When a user creates an account there is the message
![image](https://user-images.githubusercontent.com/3456833/31077596-4f3771ae-a73c-11e7-9cea-10e20e73e0a6.png)

I suggest this message be changed to 

> A verification email has been sent to [insert email address] with a link that must be clicked prior to your account being activated. If you do not receive this email please check that you entered your address correctly, or your spam folder as sometimes the email gets flagged as spam. If you entered an incorrect email address, please request an account again.

The rationale for this is to help show users the email address they entered in case there was an error (typo) and they wonder why the did not get the email.

**Comment by dtarb** [comment]
Sorry, but I am re-opening this.  The message on www at present does not insert the email address. 
![image](https://user-images.githubusercontent.com/3456833/33181747-9db895f4-d02e-11e7-9e46-ac301365241f.png)

**Comment by hyi** [comment]
@dtarb @aphelionz I verified the fix is in develop and has not made its way to master branch yet, so it is not fixed on www, but it will be included in the next release when everything in develop branch is deployed.

**Comment by dtarb** [comment]
OK.  I guess that even though merged on Oct 16, it did not make it into our Oct 16 deploy or our Nov 13 deploy.  We can hope it makes it into the next one.

**Comment by aphelionz** [comment]
@dtarb This will be in 1.14

**Comment by dtarb** [comment]
Verified on 1.14 beta.
