### ISSUE TITLE
Web App Resource Updates Needed including new Resource Specific Metadata

### ISSUE THREAD

**Issue by danames** [hydroshare/hydroshare#2336]
On the Resource Specific tab, include:

[Check box] Show this app on my Open With button:
(this will only make the app appear for resources you own. To have it appear on all public resources, contact CUAHSI.) - This appears for users - not just developer of this app. 

* Testing Protocol URL: (should be a link to a page that gives repeatable steps to fully test the app)
* Help Page URL: (should be a link to a page that gives full help documentation)
* Source Code Page URL: (preferably a GitHub or Bitbucket page)
* Issues Page URL: (preferably a GitHub or Bitbucket page)
* Mailing list sign up URL: (if this is filled in then the user will be notified that they can sign up for a mailing list at the specified link). 
* Roadmap (Text box) - should include information about why the app was developed, what’s the development status, future development plans, links to github issues, etc. - How we hope things will progress, etc.
* Option to show or not show the icon on a landing page with the "open app" button.

Owner of the app needs to know who’s been using it… 

Need to shift the organization of the resource page for web apps. 

Need to show the icon more prominently on the actual app landing page - not just on the open with page.

Need to add title to the list of codes for a launching pattern

**Comment by dtarb** [comment]
See also #1610 and #1609.  These indicate how web app resource type needs to hold information to support the resource types, file types, and file extensions it can be launched from (3 separate modes).

See also #1161 where there are also ideas about the Open With functionality.

**Comment by Castronova** [comment]
**Testing Protocol URL** may not fit every type of app, e.g. JupyterHub is too complicated to have a single testing procedure.  It should be sufficient to require unit tests that provide an X% coverage of the app's source.

**Comment by ChristinaB** [comment]
[app white paper.docx](https://github.com/hydroshare/hydroshare/files/1356763/app.white.paper.docx)

**Comment by ChristinaB** [comment]
Unit test would work for some Apps. A simple demo or workflow would work for others.  Just running a test Notebook may also be useful, these get dated quickly (but that's not the App, just the notebook).

**Comment by aphelionz** [comment]
@dtarb @danames This will be on park momentarily. Please see Pull request #2322 for instructions on how to test.

**Comment by dtarb** [comment]
See my comment on [#2301](https://github.com/hydroshare/hydroshare/issues/2301#issuecomment-341554842)
