### ISSUE TITLE
Change OpenDAP link to hydroshare directory off Hyrax root

### ISSUE THREAD

**Issue by cbcunc** [hydroshare/hydroshare#2340]
- [ ] Copy all the copies of HS NetCDF resources in /var/opt/hyrax/inedcdf_public_hydroshare to a new subdirectory /var/opt/hyrax/inetcdf_public_resource/hydroshare.
- [ ] Change tgt_path Hong's /var/log/bes/scripts/expose_pub_netcdf_res.py script on hyrax.hydroshare.org to point to the that hydroshare catalog subdirectory
- [ ] In hs_app_netCDF, change page_processors.py to generate links to `/opendap/hydroshare/` instead of just `/opendap/`. This is so that Hydroshare NetCDF datasets in Hyrax can be in a hydroshare directly off the Hyrax catalog root, rather than in the root itself. This is so that the hydoshare datasets do not obscure the nwm directory on the catalog root. This would result in a visit to http://hyrax.hydroshare.org/opendap/ showing two top leverl directories, hydroshare and nwm. Merge into RC1.14 and deploy as hotfix to www.hydroshare.org.
- [ ] Delete all the copies of HS NetCDF resources in the tope level only /var/opt/hyrax/inedcdf_public_hydroshare. Do nor remove the copies in /var/opt/hyrax/inedcdf_public_hydroshare/hydroshare.
- [x] Create a repo in the hydroshare organization for the hyrax.hydroshare.org scripts and configuration data.

**Comment by cbcunc** [comment]
@hyi @gantian127 @aphelionz ^^^ and ref http://hyrax.hydroshare.org/opendap/ and http://hyrax.hydroshare.org/opendap/nwm/

**Comment by hyi** [comment]
@cbcunc Nice and thorough summary of bullet points on the steps. Just want to point out that for the last bullet point, I have already created a repo in the hydroshare organization just for this purpose here: https://github.com/hydroshare/hs_netcdf_to_hyrax, so I have checked off that bullet point.

**Comment by cbcunc** [comment]
Decommissioning Hyrax.
