### ISSUE TITLE
Team page on About needs regular updating

### ISSUE THREAD

**Issue by ChristinaB** [hydroshare/hydroshare#2345]
This is out of date and needs team input.   @Lizabrazil  - let's make a 2018 page and put the data we have, and let people review.  Do you want to do this in the Google Doc Help folders?  Or here? Or a new Zen desk webpage? 

I would like to remove the outdated team meeting data.  
and add the following suggested text :

HydroShare code and development are managed on Github (https://github.com/hydroshare) with 30 HydroShare related repositories (as of April, 2017) coordinated by NSF Principal Investigators, grant funded researchers and developers, and professionals at the Consortium of Universities for the Advancement of Hydrologic Science, Inc. (CUASHI) and Renaissance Computing Institute (RENCI).     Users are encouraged to communicate with the developer and user communities using the Slack platform.   You can request an invitation to HydroShare.slack.com or contact Mark Henderson at mhenderson@cuahsi.org.

**Comment by ChristinaB** [comment]
We also need to update the Sponsors page.  I made a shorter list at the end of David's guidance document.  https://docs.google.com/document/d/13iI1R7MT7VYCqjhpXzUhwczxnFApuN_RlHe4USvvsJE/edit#

**Comment by Lizabrazil** [comment]
Let’s keep using the google docs help folders until further notice. Thanks, Christina.

**Comment by dtarb** [comment]
The process for updating is in place.
