### ISSUE TITLE
BUG: URLs in Abstract not working correctly

### ISSUE THREAD

**Issue by horsburgh** [hydroshare/hydroshare#2356]
I just noticed that in this resource:

https://www.hydroshare.org/resource/be41963c348d401f94252fd25af00b45/

The HTML code of the URL that I have in my Abstract is now showing instead of just the text of the link. This is a bug.

I confirmed this by doing the following:

1. Create a new resource.
2. Add some text and a URL to the abstract and then exit edit mode. The URL displays correctly.
3. Go back into edit mode and add additional text to the abstract - then exit edit mode. The HTML of the link shows instead of just the URL.
4. Go back into edit mode and add additional text to the abstract - then exit edit mode. It appears that each time I exit edit mode it is embedding the HTML code of the link, so now the HTML code is showing twice.

Here is a test resource demonstrating the problem, which I can share if needed with whoever:

https://www.hydroshare.org/resource/76534919021c424ab361309a23e80120/

**Comment by dtarb** [comment]
@horsburgh we think this should be a quick fix that @Maurier can do.

**Comment by Maurier** [comment]
Fix contained in this PR: #2362 

The resources affected will need to be manually fixed by editing their abstracts once the PR is merged.
