### ISSUE TITLE
Another Broken Resource

### ISSUE THREAD

**Issue by horsburgh** [hydroshare/hydroshare#2365]
I have another resource that I am unable to download any of the data from. I have been working on this over the past several days with my MS student who is still trying to finalize his resource for publication in HydroShare. I believe what happened to this resource (not completely sure) is that Bryce accidentally drug a folder containing a whole bunch of files (yep, the same files that broke it last time) onto the resource. He meant to add a zip file. 

He managed to get the folder with the many files removed from the resource and was able to upload the files that he wanted. They show up in the file content view, but I cannot download any of the files and I cannot download the bag. I suspect there is again an inconsistency between what is actually stored in iRODS and what is listed in Django.

@alvacouch - can you work your "fixit" magical scripts on this resource?  We really need it to work very soon because Bryce is in the process of finalizing the proofs of the paper that will cite this resource and we need the resource to be published as as soon as we can. We also need to keep the identifier because we have used it in the reference list of the paper.

https://www.hydroshare.org/resource/a3a9ba772aac4cba9533b35bb6b5fe42/

**Comment by hyi** [comment]
@horsburgh @alvacouch Just done a quick check of this resource. The bag actually exists for this resource, however, the following error resulted when downloading this resource triggered by hs_tracking code which tracks all download sessions and tries to loop through all files of this resource to aggregate the file size: ```Error processing IRODS request: 4. stderr follows:\n\nERROR: lsUtil: srcPath /.../a3a9ba772aac4cba9533b35bb6b5fe42/data/contents/Finalized_EEMs/BSA1506102006.csv does not exist or user lacks access permission``` due to out of sync ResourceFile fields in Django database and the files in iRODS. As you can see, that csv file (even the Finalized_EEMs directory) does not exist in this resource. Hopefully, Alva's script can fix the ResourceFile fields in Django database for this resource.

**Comment by alvacouch** [comment]
@horsburgh @phuongdm Phuong has another script check_irods_files that should clear this up. @phuongdm could you see what the script says.

**Comment by horsburgh** [comment]
@phuongdm - if you could look at this as soon as you can it would be great. We've spent quite a lot of time on this resource and we are just waiting on getting the downloads working again so we can publish the resource. We've already created the citation to the resource in the proof of the paper that we need to send back to the editors as soon as possible. Thanks!

**Comment by phuongdm** [comment]
1. "check_irods_files a3a9ba772aac4cba9533b35bb6b5fe42" showed a lot of error
...
check_irods_files: django file a3a9ba772aac4cba9533b35bb6b5fe42/data/contents/Finalized_EEMs/GSA1605151200.eps does not exist in iRODS
check_irods_files: django file a3a9ba772aac4cba9533b35bb6b5fe42/data/contents/Finalized_EEMs/GSA1605150606.csv does not exist in iRODS
check_irods_files: django file a3a9ba772aac4cba9533b35bb6b5fe42/data/contents/Finalized_EEMs/HAG1607131022.csv does not exist in iRODS
check_irods_files: django file a3a9ba772aac4cba9533b35bb6b5fe42/data/contents/Finalized_EEMs/GSA1605251227.csv does not exist in iRODS
check_irods_files: django file a3a9ba772aac4cba9533b35bb6b5fe42/data/contents/Finalized_EEMs/GSA1605251227.eps does not exist in iRODS
check_irods_files: django file a3a9ba772aac4cba9533b35bb6b5fe42/data/contents/Finalized_EEMs/GSA1605191800.csv does not exist in iRODS
check_irods_files: django file a3a9ba772aac4cba9533b35bb6b5fe42/data/contents/Finalized_EEMs/GSA1605191800.eps does not exist in iRODS
check_irods_files: django file a3a9ba772aac4cba9533b35bb6b5fe42/data/contents/Finalized_EEMs/HAG1607131022.eps does not exist in iRODS
check_irods_files: django file a3a9ba772aac4cba9533b35bb6b5fe42/data/contents/Finalized_EEMs/GSA1605192045.eps does not exist in iRODS
check_irods_files: django file a3a9ba772aac4cba9533b35bb6b5fe42/data/contents/Finalized_EEMs/HAG1608241103.csv does not exist in iRODS
check_irods_files: django file a3a9ba772aac4cba9533b35bb6b5fe42/data/contents/Finalized_EEMs/HAG1608241103.eps does not exist in iRODS
check_irods_files: django file a3a9ba772aac4cba9533b35bb6b5fe42/data/contents/Finalized_EEMs/GSA1605192045.csv does not exist in iRODS
check_irods_files: affected resource a3a9ba772aac4cba9533b35bb6b5fe42 type is CompositeResource, title is 'Grab Sample Data for Dissolved Organic Matter Study in the Northwest Field Canal in Logan, UT'

2. "ingest_irods_files a3a9ba772aac4cba9533b35bb6b5fe42" did not fix

3. "check_irods_files --clean_django a3a9ba772aac4cba9533b35bb6b5fe42" seems work
...
check_irods_files: django file a3a9ba772aac4cba9533b35bb6b5fe42/data/contents/Finalized_EEMs/BSA1506102130.csv does not exist in iRODS (DELETED FROM DJANGO)
check_irods_files: django file a3a9ba772aac4cba9533b35bb6b5fe42/data/contents/Finalized_EEMs/BSA1506102130.eps does not exist in iRODS (DELETED FROM DJANGO)
check_irods_files: django file a3a9ba772aac4cba9533b35bb6b5fe42/data/contents/Finalized_EEMs/BSA1506102015.csv does not exist in iRODS (DELETED FROM DJANGO)
check_irods_files: django file a3a9ba772aac4cba9533b35bb6b5fe42/data/contents/Finalized_EEMs/BSA1507050748.csv does not exist in iRODS (DELETED FROM DJANGO)
check_irods_files: django file a3a9ba772aac4cba9533b35bb6b5fe42/data/contents/Finalized_EEMs/BSA1507050745.csv does not exist in iRODS (DELETED FROM DJANGO)
check_irods_files: django file a3a9ba772aac4cba9533b35bb6b5fe42/data/contents/Finalized_EEMs/BSA1507050745.eps does not exist in iRODS (DELETED FROM DJANGO)
check_irods_files: django file a3a9ba772aac4cba9533b35bb6b5fe42/data/contents/Finalized_EEMs/BSA1506102200.csv does not exist in iRODS (DELETED FROM DJANGO)
check_irods_files: django file a3a9ba772aac4cba9533b35bb6b5fe42/data/contents/Finalized_EEMs/BSA1506102200.eps does not exist in iRODS (DELETED FROM DJANGO)
check_irods_files: django file a3a9ba772aac4cba9533b35bb6b5fe42/data/contents/Finalized_EEMs/BSA1507050748.eps does not exist in iRODS (DELETED FROM DJANGO)
check_irods_files: django file a3a9ba772aac4cba9533b35bb6b5fe42/data/contents/Finalized_EEMs/BSA1506102345.eps does not exist in iRODS (DELETED FROM DJANGO)
check_irods_files: django file a3a9ba772aac4cba9533b35bb6b5fe42/data/contents/Finalized_EEMs/BSA1507081130.csv does not exist in iRODS (DELETED FROM DJANGO)
check_irods_files: django file a3a9ba772aac4cba9533b35bb6b5fe42/data/contents/Finalized_EEMs/BSA1507081130.eps does not exist in iRODS (DELETED FROM DJANGO)
check_irods_files: django file a3a9ba772aac4cba9533b35bb6b5fe42/data/contents/Finalized_EEMs/BSA1506102345.csv does not exist in iRODS (DELETED FROM DJANGO)
...

**Comment by phuongdm** [comment]
@alvacouch , @horsburgh 

the third step is running, I will update the status after finished

**Comment by phuongdm** [comment]
Done,

@horsburgh could you please check it again?

**Comment by horsburgh** [comment]
@phuongdm - thanks a lot for getting to this! I can now download individual files and the zipped bag. I've got a couple of people looking through the contents, but it looks good to me so I'm going to close this issue.
