### ISSUE TITLE
Need to be able to edit spatial and temporal coverage for composite resources

### ISSUE THREAD

**Issue by horsburgh** [hydroshare/hydroshare#2366]
Since composite is the default resource type, I need to be able to create my own spatial and temporal coverage information. Right now, the coverage can only be set if there is a logical file in the composite resource that has coverage information. Then, the coverage for the resource as a whole inherits the coverage of it's member logical files as a superset of those. The user can't actually edit the coverage information for the composite resource as a whole. The interface for editing it is actually disabled - which is frustrating and confusing for users. 

In contrast - I can use the Google map interface and/or text boxes to edit the coverage information for a generic resource.

I have multiple composite resources now that do not contain any logical files. I created them as composite resources because that is the recommended default resource type.  These resources will not ever contain any logical files that have coverage information associated with them. However, these resources do have a spatial and temporal coverage, which I would like to indicate in the metadata for the resource by using the coverage editing tools in the same way I could with a generic resource.  I suggest the following:

* [ ] Re-enable the editing of resource level spatial and temporal coverage for the composite resource. This functionality would work exactly the way it does for the generic resource. Any coverage information set for the resource as a whole is stored in the metadata as the coverage for the resource (and not necessarily the coverage for the individual files).
* [ ] Add a button that the user can click to set the resource-level coverage based on the coverage information from its content logical files.
* [ ] Maintain the ability to set the coverage for individual files within a resource. Coverage information for individual files would be stored at the file level within the resource's metadata.

This better enables both resource level and file-level coverage information. As a consequence, it may result in the resource-level coverage not being the same as the superset of the coverage information from the logical files contained in the resource.

**Comment by horsburgh** [comment]
FYI - the reason I am adding the "High Priority" label is that to meet a publication deadline I am likely going to be forced to publish my three composite resources without coverage information because I actually cannot set a spatial or temporal coverage for those resources given the functionality that is there now - even though I would like to have coverage information and it is a basic metadata element.

**Comment by horsburgh** [comment]
Update - trying this again, I was able to add coverage information to a file within a composite resource that is not a "logical file", but I had to try multiple times before I stopped getting errors and it actually saved. The file-level coverage metadata editing seems buggy.

**Comment by horsburgh** [comment]
I'm moving this back to medium priority because I was able to create coverage information on a file in a composite resource that is not a "logical file". The process is still a bit buggy, but those bugs can be addressed as part of the changes laid out in the original post above.

**Comment by aphelionz** [comment]
@horsburgh nice labels :D

**Comment by horsburgh** [comment]
Ha ha - there are so many to choose from!

**Comment by pkdash** [comment]
@Maurier I have already implemented this as part of my current on going work on phase-2 of composite resource.

**Comment by horsburgh** [comment]
I'm closing this because it is superseded by Phase 2 composite work. See issue #2577
