### ISSUE TITLE
Need file validation for pre_add_files_to_resource signal function

### ISSUE THREAD

**Issue by gantian127** [hydroshare/hydroshare#237]
This is needed for netCDF resource. When a new file is added for the netCDF resource, the netcdf_pre_add_files_to_resource receiver function is running. So there is a need to check if the netCDF file stores valid netCDF data (This is for the condition that when a file is in "XXX.nc" format but is not real netCDF data set).

**Comment by gantian127** [comment]
This issue has been solved and merged back to the develop branch

**Comment by dtarb** [comment]
@gantian127 based on your comment above I am closing.  Reopen if you think this still needs work.
