### ISSUE TITLE
Composite Resource: Enhancements to Time Series File Type

### ISSUE THREAD

**Issue by horsburgh** [hydroshare/hydroshare#2373]
I've done some initial testing on the first implementation of the time series file type in the Composite resource. After discussion with @pkdash - it's largely ready to go, but still has a few remaining issues. The plan is to do a major pull request (which has already been issued) and then make the relatively minor changes described in this issue after that has been done.  The following enhancements/fixes are needed:

- [X] Remove buttons for setting file types that are currently in the file browser toolbar.

![image](https://user-images.githubusercontent.com/3485902/32156112-fe57a328-bd00-11e7-8d06-212922b1ead6.png)

- [ ] Stay in edit mode after right clicking on a file to set file type. Right now the interface reloads the page and removes you from edit mode.

- [ ] Move the "Extended Metadata" section in the File Metadata tab to appear below the time series metadata elements (not before the Abstract where it is now).

- [ ] In the time series metadata - ProcessingLevelCode is a text code and not an Integer. It is currently being validated to require a whole number, but it can be any string. 

- [ ] After typing in all of the time series metadata, I get the green message saying I can make the resource public. I then click the button to update the SQLite file, which seems to work, but when I scroll back to the top of the page, the yellow message stating that I need to add the time series metadata is still being displayed. If I click on the "View Resource" button to exit edit mode, the message goes away. This message persists too long and should be removed as soon as the metadata are complete.

- [X] There is weird text wrapping going on in the display of the file-level metadata. See the word "datalogger" in the image below. It should wrap the whole word and not just part of it.

![image](https://user-images.githubusercontent.com/3485902/32156285-08f0962c-bd02-11e7-9925-7e7b545efea3.png)

- [ ] The message in the dialog box that pops up when you are doing the conversion of a file to the time series type could be a little more informative so users know what HydroShare is up to. When converting a CSV file, it could say something like "Converting your CSV file to a Time Series File type. Please wait for the process to complete." When converting from a SQLite file, it should say something like "Converting your SQLite file to a Time Series File type and extracting metadata. Please wait for the process to complete."

**Comment by pkdash** [comment]
@horsburgh

>  After typing in all of the time series metadata, I get the green message saying I can make the resource public. I then click the button to update the SQLite file, which seems to work, but when I scroll back to the top of the page, the yellow message stating that I need to add the time series metadata is still being displayed. If I click on the "View Resource" button to exit edit mode, the message goes away. This message persists too long and should be removed as soon as the metadata are complete.

The above issue I think has been resolved. You can test on riverdev.

**Comment by danames** [comment]
I still think it is a terrible design decision to require the user to
manually "set" the resource type in composite files. Put another way, is
there ever a case when a user would drop the parts of a shapefile in a
composite resource and NOT want HydroShare to know that it's a geographic
feature set?

**Comment by horsburgh** [comment]
Copied @danames comment above into #2374 to make it a separate issue.

**Comment by pkdash** [comment]
@horsburgh Should this be closed?

**Comment by horsburgh** [comment]
This is old and no longer relevant with phase 2 of composite resource implemented and the reorganization of the resource landing page that will go out soon. Closing as no longer relevant.
