### ISSUE TITLE
TauDEM example notebook not working due to ImportError

### ISSUE THREAD

**Issue by itaher1995** [hydroshare/hydroshare#2375]
To create the problem attempt to import all the required libraries. The following import error appears when you attempt to import all required libaries:

"ImportError: libicui18n.so.56: cannot open shared object file: No such file or directory"

Appears to occur when taudem attempts to import gdal from osgeo.

**Comment by aphelionz** [comment]
@itaher1995 This is great that you're capturing this feedback. However, these should probably go into this repository instead:  https://github.com/hydroshare/hydroshare-jupyterhub. I will comment on the rest of these tickets as well. Sorry for the bother.

Please close and move to https://github.com/hydroshare/hydroshare-jupyterhub
