### ISSUE TITLE
Opening Jupyter Notebook Hub from Hydroshare App Page develops an invalid Resource Id

### ISSUE THREAD

**Issue by itaher1995** [hydroshare/hydroshare#2376]
To create problem, open Jupyter Notebook from the Apps page on https://www.hydroshare.org. Then go through the steps until you're asked to set the resource_id to a variable, resid. It will set what seems to be a cached, but invalid resource id. This is shown when we attempt to get resources from hydroshare using this invalid resource id in which jupyter notebook prints out an Exception where it states: "hs_restclient.HydroShareNotFound: Resource '985b566102d54a599e6a5a34c142427c' was not found."

**Comment by aphelionz** [comment]
@itaher1995 Please close and move to https://github.com/hydroshare/hydroshare-jupyterhub
