### ISSUE TITLE
Importing matplotlib and matplotlib.pyplot is redundant (landslide_driver)

### ISSUE THREAD

**Issue by itaher1995** [hydroshare/hydroshare#2378]
when importing matplotlib and matplotlib.pyplot a whole slew of warnings occurs. If don't import matplotlib these errors disappear. HOWEVER, after making a change in this import one needs to change the following:

`core_nodes
mpl.rcParams['xtick.labelsize'] = 15
mpl.rcParams['ytick.labelsize'] = 15
mpl.rcParams['lines.linewidth'] = 1
mpl.rcParams['axes.labelsize'] = 18
mpl.rcParams['legend.fontsize'] = 15`

to

`core_nodes
plt.rcParams['xtick.labelsize'] = 15
plt.rcParams['ytick.labelsize'] = 15
plt.rcParams['lines.linewidth'] = 1
plt.rcParams['axes.labelsize'] = 18
plt.rcParams['legend.fontsize'] = 15`

**Comment by aphelionz** [comment]
@itaher1995 Please close and move to https://github.com/hydroshare/hydroshare-jupyterhub
