### ISSUE TITLE
AttributeError: 'LandslideProbability' object has no attribute 'landslide_factor_of_safety_histogram' (landslide_driver)

### ISSUE THREAD

**Issue by itaher1995** [hydroshare/hydroshare#2379]
`core_nodes = LS_prob.grid.core_nodes`

`LS_prob.landslide__factor_of_safety_histogram[core_nodes[10]]`

results in the following error

> AttributeError: 'LandslideProbability' object has no attribute 'landslide_factor_of_safety_histogram'

**Comment by aphelionz** [comment]
@itaher1995 Please close and move to https://github.com/hydroshare/hydroshare-jupyterhub
