### ISSUE TITLE
MatplotlibDeprecationWarning: The 'hold' keyword argument is deprecated since 2.0.   mplDeprecation) (landslide_driver)

### ISSUE THREAD

**Issue by itaher1995** [hydroshare/hydroshare#2380]
Create Depracation Warning:

`plt.figure('Elevations from the DEM [m]')`
`watershed_line = grid.at_node['Thunder_Creek_watershed'] < 0.0`
`overlay_watershed = np.ma.array(grid.at_node['Thunder_Creek_watershed'],`
                               ` mask=watershed_line)`
`imshow_node_grid(grid, 'topographic__elevation', cmap='terrain',`
                 `grid_units=('coordinates', 'coordinates'),`
                 `shrink=0.75, var_name='Elevation', var_units='m')`
`elev = grid.node_vector_to_raster(z)`
`cs = pylab.contour(elev, extent=[0,42500, 0,32500], hold='on', colors='black')`
`manual_locals = [(11000,11000), (14000,30000), (20000,8000), (36000,3000)]`
`pylab.clabel(cs, inline=True, fmt='%1i', fontsize=10, manual=manual_locals)`
`imshow_node_grid(grid, overlay_watershed, color_for_closed='None',`
                ` allow_colorbar=False, cmap='spring')`

Output is fine; however, the following Depracation Warning occurs:

> /opt/conda/envs/python2/lib/python2.7/site-packages/matplotlib/pyplot.py:2774: MatplotlibDeprecationWarning: The 'hold' keyword argument is deprecated since 2.0.
  mplDeprecation)

**Comment by aphelionz** [comment]
@itaher1995 Please close and move to https://github.com/hydroshare/hydroshare-jupyterhub
