### ISSUE TITLE
imshow_node_grid gets a field error for 'landslide__mean_factor_of_safety' (landslide driver)

### ISSUE THREAD

**Issue by itaher1995** [hydroshare/hydroshare#2381]
Create error by running the following:

`imshow_node_grid(grid, 'landslide__mean_factor_of_safety', cmap='OrRd_r',`

                `grid_units=('coordinates', 'coordinates'), vmax=5.,`

                 `shrink=0.75, var_name='Factor of Safety',`

                 `var_units='no units')`

This will return the following error:

> FieldError: landslide__mean_factor_of_safety

Which basically means that landslide__mean_factor_of_safety is not a valid field for this method. I tried getting rid of the extra underscore and that did not help either.

**Comment by aphelionz** [comment]
@itaher1995 Please close and move to https://github.com/hydroshare/hydroshare-jupyterhub
