### ISSUE TITLE
AttributeError: 'LandslideProbability' object has no attribute 'landslide__factor_of_safety_histogram'

### ISSUE THREAD

**Issue by itaher1995** [hydroshare/hydroshare#2382]
Running the following code:
`example_FS_dist = LS_prob.landslide__factor_of_safety_histogram[`
   ` core_nodes[46]]`

Returns the following error:

> AttributeError: 'LandslideProbability' object has no attribute 'landslide__factor_of_safety_histogram'

**Comment by aphelionz** [comment]
@itaher1995 Please close and move to https://github.com/hydroshare/hydroshare-jupyterhub
