### ISSUE TITLE
(grid, z) = read_esri_ascii(hs.content['thun_elevation.txt'], name='topographic__elevation') creates an array that can't be analyzed

### ISSUE THREAD

**Issue by itaher1995** [hydroshare/hydroshare#2383]
When running the following piece of code:

`(grid, z) = read_esri_ascii(hs.content['thun_elevation.txt'],`
                          `name='topographic__elevation')`

It seems as though two variables are returned, one of which is a grid. Upon inspection, it seems that the grid is of type array, but we can't do any sort of iteration or slicing on grid. 

The following pieces of code:

`grid[0]`

`for n in grid:`

`    print n`

`list(grid)[0]`

`np.array(grid)[0]`

All result in the following error:

`/opt/conda/envs/python2/lib/python2.7/site-packages/landlab/field/grouped.pyc in __getitem__(self, group)`
 
`   864             return self._groups[group]`

`    865         except KeyError:`

`--> 866             raise GroupError(group)`

`<type 'str'>: (<type 'exceptions.TypeError'>, TypeError('__str__ returned non-string (type int)',))`

Upon inspection of this error it appears that the object from which the grid is derived may have a function __str__(), that does not return a string.

**Comment by aphelionz** [comment]
@itaher1995 Please close and move to https://github.com/hydroshare/hydroshare-jupyterhub
