### ISSUE TITLE
Open with button should not appear for resources where a user can not access the files

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#2385]
If a resource is discoverable and a user does not have permissions on the resource then they can not see the content files.  However they still see the Open With button.  This should be removed from the landing page in this discoverable mode, because Open With requires an app to be able to access the files.

**Comment by zhiyuli** [comment]
@dtarb @danames 
Current WebApp Res Type allows WebApp res Owners and Editors to select "Supported Resource Sharing Status". So a WebApp only shows up in the OpenWith list of a Data Resource whose Sharing Status value is one of WebApp's "Supported Resource Sharing Status".

By default the GIS WebApp supports all Sharing Status( Private, Discoverable, Public and Published). I just removed "Discoverable" and this is a "quick fix" for the error Rick saw. 

But this also prevents GIS app from showing up on a Discoverable Resource's landing page when a user who has access to resource files is viewing it, like Owner or Editor.

**Comment by danames** [comment]
The purpose of letting the app developer indicate what sharing status to
support for files he opens is that there may be a case or two where someone
builds an app that works on all resources - including discovery only
resources, i.e. an app that works on the metadata, not the file itself. So
this is a matter for the app developer to ensure that they check the
correct box in their app resource page.

**Comment by dtarb** [comment]
@danames agreed.  But we need to have the ability to have open with not appear where a resource is discoverable and the app would attempt to access a file if the user does not have access to the files, but for the button to appear in the case that a user has had the resource shared with them, or is the owner.  This is currently not the case.  At present the app developer does not have a combination of boxes to check that can make this work.

**Comment by zhiyuli** [comment]
@dtarb @danames 

I am exploring a solution on my local VM. It added a new Metadata term "Required Permission" to WebApp Res Type, which offers 3 options as shown below. The default value is "Read Resource Metadata and Files". WebApp owner/editor can change this value on demand. 

This new metadata term can support the following use case in conjunction with existing "Supported Resource Sharing Status" metadata.

GIS app supports all Res Sharing Status but requires User to have at least "Read Resource and Metadata Files" permission over a target resource. So GIS app will not show on the landing page of a Discoverable resource unless current user has Own/Edit/View permission. 

![image](https://user-images.githubusercontent.com/10070599/32580733-e9f7c462-c4a3-11e7-8253-2415142496cc.png)

**Comment by Castronova** [comment]
@zhiyuli Has this issue been resolved?

**Comment by dtarb** [comment]
Tested 12/23/21 and found that open with does not appear for me on a discoverable resource so changes above appear to have resolved.
