### ISSUE TITLE
Reference Time Series link on Help Pages broken

### ISSUE THREAD

**Issue by rayi113** [hydroshare/hydroshare#2386]
On this help page: https://help.hydroshare.org/hydroshare-resource-types/time-series/  where it says:

This page describes the Time Series resource. To learn more about HIS Referenced Time Series, click here (https://help.hydroshare.org/hydroshare-resource-types/his-referenced-time-series/).

The https://help.hydroshare.org/hydroshare-resource-types/his-referenced-time-series/  link is broken and returns witha 404 Page not found error.  Not sure where the real page is that it should point to.

**Comment by Lizabrazil** [comment]
The page has been removed. I have a local copy of the page in case HIS referenced time series return as an option.
