### ISSUE TITLE
Discover Page - Resource labels do not dissapear when the resource is removed from view.

### ISSUE THREAD

**Issue by ndebuhr** [hydroshare/hydroshare#2387]
Resource labels do not disappear when the resource is removed from view.
[171025_WDC1129_test-env.txt](https://github.com/hydroshare/hydroshare/files/1437899/171025_WDC1129_test-env.txt)

[X1-video-log.zip](https://github.com/hydroshare/hydroshare/files/1437909/X1-video-log.zip)

**Comment by hydrocheck** [comment]
Issue resolved as a part of the Discover redesign
