### ISSUE TITLE
Discover Page - Unfriendly Error Message When 0 Results

### ISSUE THREAD

**Issue by ndebuhr** [hydroshare/hydroshare#2388]
The error raised when there are no results is not especially user friendly
[171025_WDC1129_test-env.txt](https://github.com/hydroshare/hydroshare/files/1437917/171025_WDC1129_test-env.txt)
[X2-video-log.zip](https://github.com/hydroshare/hydroshare/files/1437920/X2-video-log.zip)

**Comment by hydrocheck** [comment]
Issue resolved as a part of the Discover redesign
