### ISSUE TITLE
Discover Page - Box Coverage Center Icon Label Multiple Instances

### ISSUE THREAD

**Issue by ndebuhr** [hydroshare/hydroshare#2389]
Clicking on a box coverage center icon brings up a label instance, regardless if one already exists.  This could seemingly cause some confusion if the user clicks an icon multiple times (it then looks like the close button doesn't do anything).
[171025_WDC1129_test-env.txt](https://github.com/hydroshare/hydroshare/files/1437934/171025_WDC1129_test-env.txt)
[X4-video-log.zip](https://github.com/hydroshare/hydroshare/files/1437936/X4-video-log.zip)

**Comment by hydrocheck** [comment]
Issue resolved as a part of the Discover redesign
