### ISSUE TITLE
Discover Page - Selection Appearance During Zoom Changes

### ISSUE THREAD

**Issue by ndebuhr** [hydroshare/hydroshare#2390]
Zooming in or out on the map removes the selection fill for a box.  Is this desired behavior?  It seems as though a selection should persist through zoom in and out.
[171025_WDC1129_test-env.txt](https://github.com/hydroshare/hydroshare/files/1437955/171025_WDC1129_test-env.txt)
[X5-video-log.zip](https://github.com/hydroshare/hydroshare/files/1437956/X5-video-log.zip)

**Comment by hydrocheck** [comment]
Issue resolved as a part of the Discover redesign
