### ISSUE TITLE
Discover Page - Legend Items

### ISSUE THREAD

**Issue by ndebuhr** [hydroshare/hydroshare#2391]
Should the Point Coverage Locations icon only be on the "Site" tab legend?  It does not appear on the "Area" tab map, but is in the "Area" tab legend.  The same is true for the Box Coverage Centers icon - these icons are only on the "Area" tab map, but appear on the legend for the "Site" tab.
[171025_WDC1129_test-env.txt](https://github.com/hydroshare/hydroshare/files/1437964/171025_WDC1129_test-env.txt)
[X6-video-log.zip](https://github.com/hydroshare/hydroshare/files/1437966/X6-video-log.zip)

**Comment by hydrocheck** [comment]
Issue resolved as a part of the Discover redesign
