### ISSUE TITLE
Discover Page - Map Location Search Error

### ISSUE THREAD

**Issue by ndebuhr** [hydroshare/hydroshare#2392]
The error raised for an empty search (the map search) is not especially user friendly.  Geocode "invalid request".  Should this even raise an error at all?
[171025_WDC1129_test-env.txt](https://github.com/hydroshare/hydroshare/files/1437976/171025_WDC1129_test-env.txt)
[X7-video-log.zip](https://github.com/hydroshare/hydroshare/files/1437977/X7-video-log.zip)

**Comment by hydrocheck** [comment]
Issue resolved as a part of the Discover redesign
