### ISSUE TITLE
Snotel HydroServer not validating

### ISSUE THREAD

**Issue by jsadler2** [hydroshare/hydroshare#240]
The SNOTEL URL does not validate even though it should...

http://worldwater.byu.edu/interactive/snotel/services/index.php/cuahsi_1_1.asmx/GetValuesObject?location=SNOTEL:823&variable=SNOTEL:WTEQ&startDate=2014-10-01&endDate=2015-03-17

**Comment by dtarb** [comment]
I tried and it did not work.  What am I doing wrong
![capture](https://cloud.githubusercontent.com/assets/3456833/6720642/1f693462-cd9b-11e4-833f-6e185ec16c51.PNG)

**Comment by valentinedwv** [comment]
URL ideally should be: http://worldwater.byu.edu/interactive/snotel/services/index.php/cuahsi_1_1.asmx
or
http://worldwater.byu.edu/interactive/snotel/services/index.php/cuahsi_1_1.asmx?wsdl

it's the PHP clone. 

WaterMLNamespace missing: 
<?xml version="1.0" encoding="utf-8" ?><timeSeriesResponse xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

needs at least a targetNamespace="http://www.cuahsi.org/waterML/1.1/" 

also datetime is funky... no time.

<value censorCode="nc" dateTime="2014-10-01" timeOffset="-7" dateTimeUTC="2014-10-01" methodCode="1" sourceCode="1" qualityControlLevelCode="1">0</value>

**Comment by jsadler2** [comment]
David, try the same URL with the REST option. It should work that way

**Comment by jirikadlec2** [comment]
I've just tried it on sandbox.hydroshare.org.
When I choose the REST option and enter the url: http://worldwater.byu.edu/interactive/snotel/services/index.php/cuahsi_1_1.asmx/GetValuesObject?location=SNOTEL:823&variable=SNOTEL:WTEQ&startDate=2014-10-01&endDate=2015-03-19

I get the preview graph, but then when I click "Create Resource" there is an error:
![image](https://cloud.githubusercontent.com/assets/4144642/6723122/c6f5aa96-cda8-11e4-9cba-f80f44f63106.png)

**Comment by jirikadlec2** [comment]
Creation of the SNOTEL resource works on: http://dev.hydroshare.org using the REST URL. I successfully created one resource for the Cascade Mountain SNOTEL site:
http://dev.hydroshare.org/resource/7fc68cfc085c4063b2ad0be5fb30c9be/

**Comment by dtarb** [comment]
I tested on alpha.hydroshare.org and got a bit further, but still not working fully
![capture](https://cloud.githubusercontent.com/assets/3456833/6733246/50734994-ce27-11e4-8d7a-b7de9d6b8005.PNG)

**Comment by jirikadlec2** [comment]
This was a bug in the SOAP web service on worldwater.byu.edu. The service didn't return any data when the startDate or endDate was empty. Now I fixed it, and if startDate and endDate are blank, the service returns all available data values. Successfully tested on dev.hydroshare.org with url: http://worldwater.byu.edu/interactive/snotel/services/index.php/cuahsi_1_1.asmx?WSDL

**Comment by dtarb** [comment]
The site where we are testing the release candidate is alpha.hydroshare.org.  Can you please test it there.

**Comment by jsadler2** [comment]
I just pushed a little fix on our end as well. I think it should work now.

**Comment by dtarb** [comment]
Works - closing
