### ISSUE TITLE
Resource Landing Page: Performance Enhancements Needed

### ISSUE THREAD

**Issue by horsburgh** [hydroshare/hydroshare#2405]
Right now the landing page for a resource is starting to take a long time to load. I think it's time to take a look and see if we can optimize this a bit. It's getting painful to switch back and forth between resource landing pages and the My Resources page because both of those pages are taking a long time to load. I'm assinging this to @Maurier to look at the front end first, but he may identify areas where he needs help with back end stuff.

**Comment by Maurier** [comment]
Most of the time is allocated waiting for a response:
![image](https://user-images.githubusercontent.com/2448568/32749082-6ad64f2e-c87b-11e7-8155-9cfe9e6fbc23.png)
For this page we need to look at which information is being passed to the view to find where we can improve it.


Loading the publication agreement also takes some time: 
![image](https://user-images.githubusercontent.com/2448568/32749064-5a4345cc-c87b-11e7-98f4-7f46b0bb3fbc.png)
This agreement is being loaded even when not needed. We need to wrap it in a conditional which will render it only when the resource owner is viewing it.

**Comment by pkdash** [comment]
@horsburgh and @Maurier 
Currently we hitting the database 2 times for each resource - once to to get the keywords and the other one to get creators. That means if the user has 50 resources, we are querying the database 100 times. The keywords and the creator name seem to be used in resource filtering shown below.

![image](https://user-images.githubusercontent.com/2523434/53580591-f6c0e980-3b49-11e9-98fc-eaae1a753517.png)

I can probably get everything else that we display on resource landing page for all the resources by querying the database only once except the creators and keywords as those are part of the metadata. I am not sure how frequently users use this filtering feature. If we can live without this filter, it is most likely we can substantially improve page load time for my resources page.

**Comment by cuahsimarko** [comment]
Related or duplicated
https://github.com/hydroshare/hydroshare/issues/2368

**Comment by pkdash** [comment]
@horsburgh I think this issue can be closed.

**Comment by horsburgh** [comment]
I'm going to close this for now. The recent performance enhancements have made significant improvements here.
