### ISSUE TITLE
missing unique constraint statement in WebApp (hs_tools_resource) models.py 

### ISSUE THREAD

**Issue by zhiyuli** [hydroshare/hydroshare#2408]
We found the following required unique constraint statement is missing from some resource-level metadata classes in WebApp (hs_tools_resource) models.py, like class SupportedResTypes and SupportedSharingStatus

class Meta:     
        unique_together = ("content_type", "object_id")

An investigation on the impact on existing WebApp resources and corresponding remedy are needed.

@hyi @pkdash @aphelionz  @cbcunc @mjstealey 
Any comment would be appreciated

**Comment by aphelionz** [comment]
@pkdash Looking for your input here

**Comment by pkdash** [comment]
@zhiyuli I don't expect it to cause any issues with the existing web apps. There will be issues only in the event of if we had for example 2 or more instances of SupportedResTypes attached to any given web app. I don't think that's the case. If you want to make sure this is not the case, you can in the django db shell, loop through each of the web apps and get a count on those specific metadata elements. It should give you count as 1. This needs to be checked against the copy of the production database.

**Comment by zhiyuli** [comment]
@pkdash 
Thanks for the comments. I wrote a script to check that and @aphelionz will be running it against a copy of real www data. 

I also did some testings locally. In some cases, the UI may create more than one metadata element objects.  One case I saw: I create a empty WebApp res, Switch to Edit mode, Fill some resource-level metadata, Click Save. This is the first time this element being created so the UI calls "add-metadata" api. Once the element is created successfully, the UI should change form's url to "update-metadata" api. But it failed to change url for some reason. I continues making more changes and click Save again, a second element got created.

Let see what result the script will give us. If none WebApp res has duplicated metadata term objects, we can simply add that constraint statement to models.py and migrate it.

**Comment by zhiyuli** [comment]
@aphelionz @pkdash @hyi @cbcunc 

I copied the email thread here:

"
The result is more favorable than I expected. 
No WebApp resource has duplicated metadata element objects. 
14 res have 0 SupportedResTypes metadata element object
2 res have 0 SupportedSharingStatus metadata element object
which means those webapp resources have never been edited after their creations. Maybe they were created just for testing purpose.

So I think we can safely add that unique constraint statement in models.py and migrate it.
We can try the migration on your local copy data and see if it works.

What do you think?
"

**Comment by aphelionz** [comment]
@zhiyuli @dtarb We can close this after 1.14 goes out

**Comment by aphelionz** [comment]
@zhiyuli This can be closed now @dtarb

**Comment by dtarb** [comment]
I do not know what the symptom of this was or how to test for it, so someone else should verify/close.

**Comment by aphelionz** [comment]
@zhiyuli Please verify and close when you get a chance
