### ISSUE TITLE
[NWM] Forecast starts an hour after initialized in Short Range Configuration

### ISSUE THREAD

**Issue by itaher1995** [hydroshare/hydroshare#2409]
If the initialization time for the Short Range Configuration is 00:00 UTC time, then the NWM Forecast Viewer will begin at 01:00. 

![image](https://user-images.githubusercontent.com/22031618/32625414-2451115c-c55a-11e7-88f3-cf674b45195e.png)

This is an example of the configuration being set to short range and the  initialization time being set to 00:00.

**Comment by zhiyuli** [comment]
@itaher1995 
This is expected.  Short range start producing forecast 1 hour after model init time.
0-hour lag for analysis assim
3-hour lag for medium range 
6-hour lag for long range

**Comment by Castronova** [comment]
@zhiyuli is this documented anywhere on the app?  We need to make sure that users understand this.

**Comment by zhiyuli** [comment]
This is confused as NWM has "Model Initialization Time“ as well as ”Valid Analysis Time“. The former is explained on NOAA page, while the latter exists nowhere but inside NetCDF files.
We tried to explain this on app help page:
![image](https://user-images.githubusercontent.com/10070599/33740070-956fda4a-db5c-11e7-8380-08a9a03f0756.png)

**Comment by aphelionz** [comment]
This issue was moved to CUAHSI-APPS/nwm-forecast-viewer#9
