### ISSUE TITLE
[NWM] Unclear units for time lag

### ISSUE THREAD

**Issue by itaher1995** [hydroshare/hydroshare#2410]
![image](https://user-images.githubusercontent.com/22031618/32627130-756765aa-c55f-11e7-90d4-5d2ab7c329f9.png)

What is the unit z? Hours? Should use a more universal unit.

**Comment by zhiyuli** [comment]
Looks like we should change it to upper-case "Z"

https://en.wikipedia.org/wiki/ISO_8601#UTC
"If the time is in UTC, add a Z directly after the time without a space. Z is the zone designator for the zero UTC offset"

**Comment by Castronova** [comment]
@zhiyuli It would also be helpful to provide an info dialog button for Time Lag that describes the purpose and units (i.e. hours) of this attribute.

**Comment by aphelionz** [comment]
This issue was moved to CUAHSI-APPS/nwm-forecast-viewer#8
