### ISSUE TITLE
[NWM] Members in Long Range Configuration are unclear.

### ISSUE THREAD

**Issue by itaher1995** [hydroshare/hydroshare#2412]
![image](https://user-images.githubusercontent.com/22031618/32627467-840a9810-c560-11e7-9d12-4dcb99f9d8f0.png)

What are the members in this chart?

**Comment by zhiyuli** [comment]
@Castronova @itaher1995 
An updated legend.
![image](https://user-images.githubusercontent.com/10070599/33047147-8648ccdc-ce11-11e7-8da7-bc37bc3942f3.png)

**Comment by Castronova** [comment]
@zhiyuli are these defined anywhere on the page, e.g. what does "member 1 of cycle no 1" mean?

**Comment by aphelionz** [comment]
This issue was moved to CUAHSI-APPS/nwm-forecast-viewer#6
