### ISSUE TITLE
[NWM] When you pick the begin date to be the current date, it should state that the chart is projected values

### ISSUE THREAD

**Issue by itaher1995** [hydroshare/hydroshare#2413]
![image](https://user-images.githubusercontent.com/22031618/32627601-fc71b9e6-c560-11e7-9999-1cc0730dadb2.png)

These are technically projections right? The chart should state that?

**Comment by zhiyuli** [comment]
All data in NWM outputs are kind of "predicted data" no matter a past or present date user has chose. 
We added more help info to the app. Also we add a NOAA link that briefly introduces NWM's background.

**Comment by aphelionz** [comment]
This issue was moved to CUAHSI-APPS/nwm-forecast-viewer#5
