### ISSUE TITLE
[NWM] Snow-Cover Forecast Chart Units

### ISSUE THREAD

**Issue by itaher1995** [hydroshare/hydroshare#2417]
The units for the snow-cover variable is fraction. Fraction is an ambiguous term and we do not know what the numerator or denominator are for this variable.

![image](https://user-images.githubusercontent.com/22031618/32670502-f5d1a342-c611-11e7-96dc-689b04c9fba9.png)

**Comment by Castronova** [comment]
duplicate of https://github.com/hydroshare/hydroshare/issues/2419
