### ISSUE TITLE
[NWM] For geometry "land" changing variable causes map reload 

### ISSUE THREAD

**Issue by itaher1995** [hydroshare/hydroshare#2418]
If I am looking at a certain grid cell and change the variable and click view forecast, the website refreshes and although it returns data about the forecast, in certain instances, it refreshes the map to be the default view (the United States.)

**Comment by Castronova** [comment]
@itaher1995 can you provide an example so we can reproduce this?

**Comment by itaher1995** [comment]
I can't seem to recreate the problem. I'll go ahead and close this!
