### ISSUE TITLE
[NWM] For Geometry "Land" Variable "Soil Saturation" has ambigious units "Fraction"

### ISSUE THREAD

**Issue by itaher1995** [hydroshare/hydroshare#2419]
The soil saturation's units for the forecast chart are in the units fraction. This is ambiguous as we do not know what the numerator and denominator are.

**Comment by Castronova** [comment]
@zhiyuli can we have a more descriptive unit label?

**Comment by aphelionz** [comment]
This issue was moved to CUAHSI-APPS/nwm-forecast-viewer#4
