### ISSUE TITLE
[NWM] Medium Range Configuration, the variable "Soil Moisture" should have units in its chart but does not.

### ISSUE THREAD

**Issue by itaher1995** [hydroshare/hydroshare#2420]
There are no units for soil moisture. Although it is obvious that the higher the value the more moist the soil is, I think it's good practice to have units for soil moisture. 

![image](https://user-images.githubusercontent.com/22031618/32673196-2df7bd9c-c61c-11e7-9d43-f4d1485d98cd.png)

**Comment by Castronova** [comment]
All plots should have units.

**Comment by aphelionz** [comment]
This issue was moved to CUAHSI-APPS/nwm-forecast-viewer#3
