### ISSUE TITLE
Discover page: currently no support for phrase matching in text box

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#2426]
The discover page currently doesn't interpret quoted phrases like "water quality" properly. It uses the default Haystack processing, which interprets sequences of words as requirements connected by "AND". To use this, we have to change the default parser to pick up these phrases, and process them as search terms differently than the default. 

To do this, we can use the Haystack query syntax `text__exact=phrase`, which matches the whole phrase anywhere it lives in the resource. Note that this overrides such things as word stemming, so it really is only an exact match. 

See [the description of exact matching in Haystack](http://django-haystack.readthedocs.io/en/v2.4.1/inputtypes.html#exact) for details on this.

**Comment by alvacouch** [comment]
This was originally implemented by passing all requests from this line directly to SOLR, but got unimplemented as a result of a request that we match prefixes of keywords as well as full keywords. That is definitely not SOLR syntax. In 20/20 hindsight, this was probably a poor decision. We might want to re-institute SOLR syntax at the expense of eliminating implicit substring matching. This would give us "search phrase" capability at no cost.

An additional fact: there was previously a privacy problem with implementing SOLR syntax because resources marked 'private' from 'public' were staying in the index. **This has been fixed.**  There are currently no privacy concerns with opening up full SOLR query syntax to users.

**Comment by alvacouch** [comment]
@mseul @dtarb @aphelionz @Lizabrazil I think it is time to re-enable full SOLR syntax on the search box. 

* There will be a special syntax for prefix matching. 
* Other powerful queries will become possible. 

This will mean writing a simplified and more approachable guide to that syntax but will give us what we want. @Lizabrazil and I will prepare a simplified guide to syntax for your perusal. This is a very simple change of the software, but documenting it in a usable fashion is crucial. Sending people to an impenetrable SOLR manual was not a good idea.

**Comment by alvacouch** [comment]
@mseul @dterb @aphelionz @Lizabrazil An even better idea. If we simply use one of the "haystack query parsers", we get the function we need without any bother at all. The advantage of these is that they're both simple and portable. See 

* https://github.com/mattdeboard/rawqs-sq/blob/master/queryparser.py
* https://github.com/Aplopio/haystack-queryparser

I am partial to the last, which enables "search phrase" and field:value and field:"search phrase" matching that integrates nicely with current code.

**Comment by dtarb** [comment]
@alvacouch I am totally fine to leave these choices up to you based on your knowledge of the options in this area.

**Comment by alvacouch** [comment]
Addressed by PR #2578

**Comment by cuahsimarko** [comment]
close me?

**Comment by Lizabrazil** [comment]
@cuahsimarko  yes, will close now
