### ISSUE TITLE
Discover page: anomaly in map view listings

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#2427]
It was generally agreed long ago that the map listing should include all resources currently viewable on the map, up to a reasonable limit of -- e.g. -- 200 matches.  Lines of that listing should be highlighted when the user selects things on the map. 

I remember this being implemented but somehow it got removed and/or forgotten, and the current listing only shows the selected resources on the map. Further, only one resource is shown at a time.

**Comment by engineSound** [comment]
I like the map feature and recognize its potential  to provide users a good experience. I found it is challenging to use. Selecting an area  is barely possible. We need to sort out how to correctly use Google map and it's APIs before addressing map issues.

**Comment by engineSound** [comment]
Reason to change to unassigned: Discovery page is on re-design 2019.

**Comment by martinseul** [comment]
Addressed with redesign 1.38
