### ISSUE TITLE
Discover page: coverage type facet

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#2428]
Instead of having two map views, the idea of instituting a **coverage type facet** seems a better approach. This would allow one to select "`Site`" or "`Area`" coverages (or both) to show on the map. Thus, we would only need one map for both use cases. 

Some composite resources would match both.

**Comment by alvacouch** [comment]
Addressed by #2578

**Comment by cuahsimarko** [comment]
close me?

**Comment by martinseul** [comment]
closing does does not apply anymore
