### ISSUE TITLE
JupyterHub Server Down

### ISSUE THREAD

**Issue by ChristinaB** [hydroshare/hydroshare#2433]
@swuiuc 
This is the error of the day:  
![image](https://user-images.githubusercontent.com/4108369/32792409-263e1322-c918-11e7-9fa8-3eef2eab7f8d.png)

Thanks for looking into why the server is not working.

**Comment by ChristinaB** [comment]
The above error was produced with https://jupyter.cuahsi.org/user/christinabandaragoda/tree?
and https://jupyter.cuahsi.org/

Per Dandong's email below, his restart seems to have fixed the problem.  
 
From what I see here, everything works perfectly fine. No infrastructure or service failure. I also checked the live log of the JupyterHub service and find no error in it. All signs indicating that it is working smoothly and normally.

Meanwhile, I do have problem jumping to Jupyter from Hydroshare. So I tried to restart the server and the JupyterHub service. Now JupyterHub is still working fine, but at the very beginning I see it has difficult starting containers, due to some errors talking with Hydroshare.

However, after waiting for a few minutes, I suddenly can log in to Jupyter from Hydroshare. 

As a result, although I don’y know why and how, I seem to have fixed the problem by restarting and waiting...

**Comment by ChristinaB** [comment]
@horsburgh   Are you launching notebooks from HydroShare at the BigCZ meeting today and tomorrow? I know that Jezra was planning to do so.   It should be fine now.

**Comment by horsburgh** [comment]
@ChristinaB - we are doing a bunch of demos via Jupyter notebooks in our workshop. The BiG CZ Team stood up our own Jupyter server for this.

**Comment by ChristinaB** [comment]
@horsburgh   Please be sure to do a few tests before you go live.  I think everything is running fine now, but you should be sure for the resources you plan to use.
