### ISSUE TITLE
 "add to my resource" button shows confusing messages

### ISSUE THREAD

**Issue by zhiyuli** [hydroshare/hydroshare#2436]
The grey and yellow messages of "add to my resource" are confusing...

![image](https://user-images.githubusercontent.com/10070599/32846544-cb265288-c9e4-11e7-8a68-0297aeda0308.png)

**Comment by Maurier** [comment]
This is a bug I can fix.

**Comment by aphelionz** [comment]
@Maurier @zhiyuli We can close this after 1.14 goes out

**Comment by Maurier** [comment]
Texted fix deployed to www and confirmed working.
