### ISSUE TITLE
[Hydroshare GIS] Possible resolution error with app

### ISSUE THREAD

**Issue by itaher1995** [hydroshare/hydroshare#2440]
![pagegoesoffscreen in chrome](https://user-images.githubusercontent.com/22031618/32922126-ad2fee04-cafe-11e7-9bcd-357f91c18400.PNG)

As you can see in this image, the toggle button goes off on multiple web browsers (chrome and edge). It could be a resolution error on my computer. If it is this, then there should be an instruction to show the optimal resolution.

**Comment by Castronova** [comment]
@itaher1995 can you provide a bit more explanation for this?

**Comment by itaher1995** [comment]
@Castronova Basically when you look at the app in browser the toggle button (those three lines in the top right corner) don't really show up so at first glance you cant really see them.

**Comment by aphelionz** [comment]
This issue was moved to CUAHSI-APPS/tethysapp-hydroshare_gis#10
