### ISSUE TITLE
[Hydroshare GIS] In Chrome, feedback button blocks checkboxes of layers

### ISSUE THREAD

**Issue by itaher1995** [hydroshare/hydroshare#2441]
![layersblocked](https://user-images.githubusercontent.com/22031618/32922252-56a3f566-caff-11e7-8c74-03f48c132e4c.PNG)

In chrome the layers' checkboxes are blocked, by the feedback button, I can't find a way to undo this. This is not the case in edge.

![layersnotblocked](https://user-images.githubusercontent.com/22031618/32922394-047d2b58-cb00-11e7-9e4e-401ce1a61cba.PNG)

**Comment by aphelionz** [comment]
This issue was moved to CUAHSI-APPS/tethysapp-hydroshare_gis#9
