### ISSUE TITLE
[Hydroshare GIS] Different outputs for shapefiles in different Browsers

### ISSUE THREAD

**Issue by itaher1995** [hydroshare/hydroshare#2442]
It seems that the issues with Chrome persist.

When uploading the TauDEM files to Hydroshare GIS, the output layers are different between two web browsers, enough that when looking at a subset of layers, the chrome output it essentially a black blob and in edge it is actually in a readable format. 

![edgeoutput](https://user-images.githubusercontent.com/22031618/32925579-9837c690-cb10-11e7-9933-6a17e65d08dc.PNG)

This is a subset of the layers in Microsoft Edge

![chrome output](https://user-images.githubusercontent.com/22031618/32925591-a28ee902-cb10-11e7-902e-13d4e76d3d88.PNG)

This is the same subset of layers in Chrome.

**Comment by aphelionz** [comment]
This issue was moved to CUAHSI-APPS/tethysapp-hydroshare_gis#8
