### ISSUE TITLE
[Hydroshare GIS] You can add files that are not tif or shp files that don't do anything on the map

### ISSUE THREAD

**Issue by itaher1995** [hydroshare/hydroshare#2443]
I can add .ipynb, .pdf files and so forth that do not change anything on the map into the layers. Although it does not do anything to map, there should be a way not to add those files. It makes no sense to have them in the layers list.

There should be a way that resources with no files that can be loaded onto Hydroshare GIS won't be displayed.

**Comment by Castronova** [comment]
To add to this:

1. The "Add Resource" button should only search GIS capable resource.  This would drastically speed up the query
2. You can also add non-gis files using the "Add Local" button.  This file browser should filter to only show GIS capable files as well.

**Comment by aphelionz** [comment]
This issue was moved to CUAHSI-APPS/tethysapp-hydroshare_gis#20
