### ISSUE TITLE
[Hydroshare GIS] When you click apply in the modify symbology window, the window does not go away

### ISSUE THREAD

**Issue by itaher1995** [hydroshare/hydroshare#2446]
![modifysymbology](https://user-images.githubusercontent.com/22031618/32925913-6fdae2c0-cb12-11e7-93fe-2ee97d3c7a14.PNG)

Generally when someone clicks apply, they expect the window to go away so they can see the changes. I have to click close to see my changes.

**Comment by aphelionz** [comment]
This issue was moved to CUAHSI-APPS/tethysapp-hydroshare_gis#5
