### ISSUE TITLE
[Discover Page]When I attempt to put in a date range the website refreshes

### ISSUE THREAD

**Issue by itaher1995** [hydroshare/hydroshare#2448]
Let's say I wanted to look up all resources from 10-10-2017 to 11-01-2017.

If I go to put in 10-10-2017, the website will refresh and give me all the values from 10-10-2017 till present. Only after that can I put in 11-01-2017.

This causes the user to have to wait for a refresh and generally when you put in a date range, it will allow you to put in the date range and then it will return results.

**Comment by hydrocheck** [comment]
Issue resolved as a part of the Discover redesign
