### ISSUE TITLE
[Discover Page] Filter by Owner does not work

### ISSUE THREAD

**Issue by itaher1995** [hydroshare/hydroshare#2449]
If I try to filter by owner, it will not do the filter accordingly.

For example, I tried to filter by owner in which David Tartoban was the owner, and when I did so, most of the choices that were available, Mr.Tartoban was not an explicit owner (if you click on the resource, it shows the owners.)

![image](https://user-images.githubusercontent.com/22031618/32926311-9c027636-cb14-11e7-8b03-3f61f84c96d5.png)

**Comment by alvacouch** [comment]
Addressed by #2578
