### ISSUE TITLE
Fix RefTS workflow

### ISSUE THREAD

**Issue by jsadler2** [hydroshare/hydroshare#245]
* Problem: The current workflow is flawed. The user can create a RefTS resource without the reference metadata terms but does not have the option of adding that metadata in the resource landing page. The only place to add the reference metadata (e.g. URL) is in the RefTS creation page.

* Solution: the user is still sent to the same custom RefTS creation page but the resource is not created until the reference metadata is input and validated.

**Comment by dtarb** [comment]
Tested by verifying that metadata can be edited after the resource is created.
