### ISSUE TITLE
[Discover Page] Some of the filters don't make sense

### ISSUE THREAD

**Issue by itaher1995** [hydroshare/hydroshare#2450]
![image](https://user-images.githubusercontent.com/22031618/32926493-80c9b018-cb15-11e7-9ecf-42713d0e6f60.png)
I am not exactly sure about what goes into each category. If we are looking at all papers that use this filter, than degree Celsius should have WAY more resources no? Also shouldn't the four instances of degree Celsius be the same instance in the filter?

![image](https://user-images.githubusercontent.com/22031618/32926540-cddac838-cb15-11e7-9ac4-a4efabee2326.png)

Also same with filter by variable, what allows for the classification of a resource into a certain variable. And what are the variables p05, p10, etc.

**Comment by Castronova** [comment]
@itaher1995 these are units and variables that are defined by resources.  I'm tagging this as an enhancement.

**Comment by itaher1995** [comment]
Ok this makes a bit more sense. However I still believe there is no need for three degree Celsius

**Comment by hydrocheck** [comment]
Issue resolved as a part of the Discover redesign
