### ISSUE TITLE
[Discover Page] When you use the map option and the top search option, it returns to the list setting AND also does not update the map 

### ISSUE THREAD

**Issue by itaher1995** [hydroshare/hydroshare#2454]
When you use the top search it returns back to the list setting and also does not update the map setting's resources listed.

![image](https://user-images.githubusercontent.com/22031618/32927204-4f170422-cb19-11e7-9e43-ecc5d0744f86.png)

The highlighted resource has no reference to a Christina in it.

**Comment by engineSound** [comment]
See issue related [2427](
https://github.com/hydroshare/hydroshare/issues/2427)

**Comment by engineSound** [comment]
Reason to change to "unassigned": discovery re-design is on the roadmap this year.

**Comment by hydrocheck** [comment]
Issue resolved as a part of the Discover redesign
