### ISSUE TITLE
Drag and drop of folders into resource contents does not use folder heirarchy and can create a corrupt resource. 

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#2456]
An example broken resource was created as follows:

1. Create a composite resource but do not add files
2. Switch to edit mode
3. Drag and drop a folder onto the content space. The folder I dragged had two files with the same name (but different content) in separate folders within the folder that I dragged onto the resource.

There is an error message at step 3 indicating a duplicate file name, and the content display then shows no files.  But bag download returns a bag with one of the files. The resource is thus corrupt in that there is an inconsistency between the files on disk and display.

This problem seems to be related to the flattening of folder structure when files are uploaded, because if a folder without duplicated names in separate folders is drag and dropped, the result is the files loaded into the folder where they were dropped, without retaining any folder heirarchy.

With a generic resource flattening of folder structure behavior is similar, but the resulting resource content display does show the file that was uploaded.

The broken resource is at https://www.hydroshare.org/resource/c2c0070eaaca4d1eacf8d99c7c9e1d94/.

**Comment by pkdash** [comment]
@dtarb I am working on this and should be creating a hotfix PR tonight.

**Comment by dtarb** [comment]
Verified fixed on beta.  A broken resource no longer results, but folder drag and drops still flatten the folders.  That will be a new issue.

**Comment by dtarb** [comment]
Re-opening.  This issue has re-appeared/regressed.  On www I can currently create corrupt resources (that have contents in the download bag but display no files) by following the sequence outlined above.  This was verified fixed on beta 16 days ago, so the recent work related to deployment seems to have lost this fix.  A new resource with this problem is https://www.hydroshare.org/resource/238c4452a7bf44e9b6de024277b48d21/

**Comment by ChristinaB** [comment]
I may have encountered this issue today.  
The resource was working fine. Then I made a folder, dragged files into from within the resource, and now it appears to be broken. I get errors downloading it and getting it to the JH server using getResourceFromHydroShare()      
https://www.hydroshare.org/resource/abe2fd1e3fc74e889b78c2701872bd58/

I made a copy to see if that would help. It didn't.  Here's the copy.
https://www.hydroshare.org/resource/31bd8cc9eb1e4f14b1e760c08f596920/

Here is the error:
![image](https://user-images.githubusercontent.com/4108369/35359001-6e4f79da-010d-11e8-879b-918a1f050ff3.png)

**Comment by ChristinaB** [comment]
@alvacouch Did I break https://www.hydroshare.org/resource/abe2fd1e3fc74e889b78c2701872bd58/
https://www.hydroshare.org/resource/31bd8cc9eb1e4f14b1e760c08f596920/
or are they just too big?  I am not clear on how to resolve the issue given this error message.

**Comment by ChristinaB** [comment]
I resolved my problems with the resource by deleting the folder I had created, and then making a new copy of the resource.  Without the folder and with a new copy, things are working as expected.  @alvacouch I would like to delete the dysfunctional resource but will wait until I hear from you whether you want to use it for further investigations.  Thanks! 

Here is the original resource where I made a folder, drag and dropped a file in the resource into the folder, and then had errors.  
https://www.hydroshare.org/resource/abe2fd1e3fc74e889b78c2701872bd58/

This is a copy of the resource, I deleted the folder after making a copy and was able to use it without problems. 
https://www.hydroshare.org/resource/31bd8cc9eb1e4f14b1e760c08f596920/

This is another copy of the resource, I deleted the folder first, and then made this copy, it appears to work. 
https://www.hydroshare.org/resource/2b69ca6ca3b54cdda0eea0892456d37e/

**Comment by aphelionz** [comment]
@pkdash Can you please add a 1,2,3 point estimate label to these tickets?

**Comment by horsburgh** [comment]
@pkdash - I'm removing @Maurier from this issue since you had worked on a fix for it already that didn't seem to take. I'm going to have him work on other stuff.

**Comment by pkdash** [comment]
@horsburgh, @aphelionz Though it seems to be an issue on www, I could not reproduce it on park. I am assuming the phase-2 work on composite resource has fixed it.

**Comment by dtarb** [comment]
Done with 1.16
