### ISSUE TITLE
Discovery search operators

### ISSUE THREAD

**Issue by Castronova** [hydroshare/hydroshare#2459]
The search box currently interprets " " as an AND query.  For instance `water hydrology` becomes `water AND hydrology`.  

In addition, both `+` and `AND` should be interpreted the same way.  For instance `water + hydrology` should be interpreted as `water AND hydrology`, however it's currently interpreted as `water AND + AND hydrology`.

**Comment by alvacouch** [comment]
Did not implement + because it is a very non-standard syntax for AND. Did implement -x as a shorthand for NOT x. Addressed by #2578

**Comment by cuahsimarko** [comment]
close me?

**Comment by hydrocheck** [comment]
Issue resolved as a part of the Discover redesign
