### ISSUE TITLE
Discovery match word stems

### ISSUE THREAD

**Issue by Castronova** [hydroshare/hydroshare#2466]
Partial word searches currently do not work, but should.  For example, `derive` should match `derived`.

**Comment by alvacouch** [comment]
@Castronova This is an artifact of stemming. The stem of derived is deriv The stem of derive is derive. These don't match.

**Comment by aphelionz** [comment]
@Castronova I thought we tested this and it worked?

**Comment by alvacouch** [comment]
@Castronova The stemmer is too aggressive. I need to modify the SOLR configuration. It varies by word.

**Comment by Castronova** [comment]
@aphelionz My mistake, it looks like it is working.
