### ISSUE TITLE
Discovery: resources whose title starts with ' ' appear first in title order. 

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#2470]
Now that sorting works, it is clear that there are some problems with the data. Particularly, author names and titles that start with space are not cleaned and appear before those that don't start with space.

**Comment by alvacouch** [comment]
Note: we can clean up the titles in SOLR ingestion and not have to clean up the real ones.

**Comment by dtarb** [comment]
I am puzzled by the lead in "now that sorting works".  Sorting was disabled on the last deploy.  It has also appeared odd to me that the numbers at the beginning of titles seem to come first before letters.

**Comment by alvacouch** [comment]
@dtarb Now sorting works in PR #2473
