### ISSUE TITLE
Horizontal Scroll bars at bottom of My Resources and Discover pages not necessary  (for wide screens).

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#2474]
This is the bottom of MyResources (Firefox on Windows 10).  
![image](https://user-images.githubusercontent.com/3456833/33141825-9d32e0b6-cf71-11e7-991c-1d547c10018d.png)

Discover page has a similar scroll bar.   

This is a 1920 x 1200 display with browser set to full window so there is plenty of white space on either side for the scroll bar not to be necessary.

**Comment by horsburgh** [comment]
@Maurier - can this issue be closed?

**Comment by dtarb** [comment]
Validated problem now resolved on www.
