### ISSUE TITLE
HydroShare GIS fails for some shapefiles

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#2475]
I received the error below for the shapefile in https://www.hydroshare.org/resource/23b8c221ebea4b93a90e22031735c530/.  This appears to be a "proper" shapefile produces by ArcGIS as a subset from NHDPlus.  The projection is a standard Geographic coordinates GCS_North_American_1983. 

![image](https://user-images.githubusercontent.com/3456833/33142502-0767a636-cf74-11e7-821f-dd36c4e2a277.png)

**Comment by aphelionz** [comment]
This issue was moved to CUAHSI-APPS/tethysapp-hydroshare_gis#3
