### ISSUE TITLE
Raster symbology for HydroShare GIS does not work

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#2476]
To reproduce this, 

1. While logged into HydroShare, go to https://www.hydroshare.org/resource/b7822782896143ca8712395f6814c44b/ (a public and published raster) [Resource specific metadata appears correct with minimum and maximum values filled in]
2. Open With HydroShare GIS.  You see a display with black around the edges (where there is no data) and white in the middle.
3. Click to Modify Symbology.  Try adjust raster color values (e.g. see below)
4. Click apply and close (The display is not updated)

The fix should address
- [ ] When color scheme is changed the display should update
- [ ] When data is loaded where Min and Max values are known, the range should be set to that so that a reasonable initial view is presented (not the black edge with no data and white edge where there is data)
- [ ] There should be a way to see a "legend" of the color symbology without expanding Modify Symbology.

![image](https://user-images.githubusercontent.com/3456833/33143241-8a462882-cf76-11e7-8924-4f9a0fbfa548.png)

**Comment by aphelionz** [comment]
This issue was moved to CUAHSI-APPS/tethysapp-hydroshare_gis#2
