### ISSUE TITLE
A visual separator needed for multiple relations on landing page

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#2480]
If a resource has multiple relations, the landing page (in view mode) blends them together.  Some sort of separator (perhaps similar to the line in edit mode) is needed.

A resource that illustrates this is https://www.hydroshare.org/resource/4104f344a1cc4a639a63164d0bf237c9/

![image](https://user-images.githubusercontent.com/3456833/33232017-4e8ead6c-d1bc-11e7-8c7c-79a9656f50a3.png)

**Comment by aphelionz** [comment]
@dtarb @Maurier  This can be closed after 1.14 goes out

**Comment by dtarb** [comment]
Verified on candidate release beta.hydroshare.org and closing.  @aphelionz I feel it is OK to close issues that have been verified on a candidate release.

**Comment by aphelionz** [comment]
@dtarb copy that
