### ISSUE TITLE
Discovery: jquery select "change" does not work properly on MS Edge

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#2481]
When running HydroShare on the new Microsoft Edge browser, select "change" events are not processed properly. This is used in the new "sort order" select fields. These events are processed early, as if they were "click" events. 

**This is likely a jquery version issue.** Our version of jquery is very much out of date. 

The offending lines are here: 
https://github.com/hydroshare/hydroshare/blob/develop/theme/static/js/discover.js#L965

**Comment by hydrocheck** [comment]
Issue resolved as a part of the Discover redesign
