### ISSUE TITLE
NWM Viewer - Fails to get long range data

### ISSUE THREAD

**Issue by Castronova** [hydroshare/hydroshare#2484]
![image](https://user-images.githubusercontent.com/4822372/33340824-216ac64a-d44b-11e7-87c0-767a50a73cd0.png)

1. select a river
2. choose long range forcase
3. often get the error above

**Comment by zhiyuli** [comment]
This only happens on some random stream reaches. Need more investigation on this after AGU

**Comment by aphelionz** [comment]
This issue was moved to CUAHSI-APPS/nwm-forecast-viewer#1
