### ISSUE TITLE
[AGU Beta] -- public resource landing page failed to open without signing in

### ISSUE THREAD

**Issue by zhiyuli** [hydroshare/hydroshare#2493]
Reported by @jsadler2 
Public resource landing page failed to load if user is not signed in.
This is probably related to the new code added by me...
![image](https://user-images.githubusercontent.com/10070599/33439943-f55c6772-d5ab-11e7-9afe-cb6d3c7180cd.png)

**Comment by aphelionz** [comment]
@zhiyuli This is true right?

**Comment by zhiyuli** [comment]
tested on www. closing
