### ISSUE TITLE
Augmenting help pages

### ISSUE THREAD

**Issue by rphooper** [hydroshare/hydroshare#2494]
I suggest adding a section to the current help page on resources to provide guidance on how resource types are intended to be used. Currently, the page simply defines each resource type.

This could be as simple as adding a few sentences at the end of the current page such as

> Users are encouraged to use resource types that reflect the underlying data structure rather than creating a generic resource. Hydroshare supports automatic metadata creation for resources such as shape files and netcdf files and various apps permit users to preview the resource prior to downloading for declared resource types. These apps cannot access generic resources. If users create a generic resource, it is considered best practice to include a readme.txt file that describes the content of each file contained in the generic resource.

> If a user wishes to combine multiple files, potentially of different resource types, we encourage users to use a Composite Resource type rather than a Generic Resource.

**Comment by cuahsimarko** [comment]
@Lizabrazil can you update docs or close if irrelevant or done?

**Comment by Lizabrazil** [comment]
@cuahsimarko can close
