### ISSUE TITLE
[GIS App] Symbology not working in Firefox

### ISSUE THREAD

**Issue by zhiyuli** [hydroshare/hydroshare#2496]
Reported by @Lizabrazil and @dtarb 
https://www.hydroshare.org/resource/b7822782896143ca8712395f6814c44b/

Symbology works in Chrome but not in Firefox
![image](https://user-images.githubusercontent.com/10070599/33492204-9a5dab32-d679-11e7-96b2-500dfc5b2356.png)
![image](https://user-images.githubusercontent.com/10070599/33492228-a7cbfab2-d679-11e7-9b65-4546d8379233.png)

**Comment by aphelionz** [comment]
This issue was moved to CUAHSI-APPS/tethysapp-hydroshare_gis#1
