### ISSUE TITLE
Beta missing profile link on menu bar

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#2503]
On current release candidate I see 
![image](https://user-images.githubusercontent.com/3456833/33519462-4e538cf2-d764-11e7-9c43-05394d5ce525.png)

but on www I see 
![image](https://user-images.githubusercontent.com/3456833/33519466-5c3e10a8-d764-11e7-8990-04f1a49d6b5e.png)

As a result I am unable to get to profile functions

**Comment by Maurier** [comment]
I've seen this error before. This is specific to the deployment. The profile information points to an image that is not stored in the deployed databse. In www this will not happen since the database actually contains the image.
