### ISSUE TITLE
Update sqlite file fails for time series file type-HOTFIX

### ISSUE THREAD

**Issue by pkdash** [hydroshare/hydroshare#2504]
When time series file type is created from a csv file the Update sqlite file option should not appear until all required file level metadata have been entered.

![image](https://user-images.githubusercontent.com/2523434/33522253-271e6826-d7b6-11e7-9e70-aaa33380db56.png)

**Comment by aphelionz** [comment]
@pkdash Can this be closed?

**Comment by pkdash** [comment]
@aphelionz On www this issue still exists. I am not sure if we should resolve it as a HOTFIX. When is the next release? I would prefer to make this fix part of the next release. I can also do a HOTFIX if that is needed.

**Comment by aphelionz** [comment]
@pkdash Next release will be mid to late January. I'm OK with waiting. Thank you

**Comment by pkdash** [comment]
This seems to have been fixed. Closing.
