### ISSUE TITLE
check_irods_files should know how to ingest irods files

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#2510]
The management command `check_irods_files` only knows how to delete unreferenced files, and not how to put them in Django as in `ingest_irods_files`. Thus ingestion is a two-step process: one has to run `check_irods_files` and then `ingest_irods_files`. This should be a one-step process.

**Comment by aphelionz** [comment]
@alvacouch does it do this now?

**Comment by martinseul** [comment]
@alvacouch is this still an issue or can it be closed.

**Comment by alvacouch** [comment]
There remains an ongoing issue, but this is not the center of it. Closing because other issues cover the problems.
