### ISSUE TITLE
Failed to Add an existing HydroShare user as Resource Author

### ISSUE THREAD

**Issue by zhiyuli** [hydroshare/hydroshare#2518]
This is NOT a serious bug. No Alarm

I am creating WebApp Resources for Tethys Apps.
I could not add this existing hydroshare user as a resource author. Nothing happened after clicking the "Save" button. No error message displayed.

So far this glitch only happens to this user. I have added other existing hydroshare users as resource author successfully. I ended up with adding this Author as a non-hydroshare user.

![image](https://user-images.githubusercontent.com/10070599/33724161-e000552a-db2b-11e7-9b25-09c1e5cc779a.png)

**Comment by dtarb** [comment]
If this is only an issue for this user, explore whether this has a possible cause of special characters in the name.

**Comment by martinseul** [comment]
closing, retested an works fine now
