### ISSUE TITLE
Enabling use of GABBs MultiSpec online tool for HydroShare resources

### ISSUE THREAD

**Issue by hyi** [hydroshare/hydroshare#2520]
Goal: allow HydroShare users to launch GABBs tool directly from resource landing page.
Tasks involved:
- [x] Federate GABBs tool iRODS server and HydroShare iRODS data server so that HydroShare iRODs proxy user can push HydroShare resources to designated HydroShare collection in GABBs iRODS zone for GABBs tool to consume on demand, i.e., when a HydroShare user opens GABBs tool via Open With button in HydroShare.
- [x] Create a Web App resource for GABBs tool launch. https://www.hydroshare.org/resource/8e4efd86e06d4bdabd9a56753a6a1a57/
- [x] Write a view function in HydroShare to push HydroShare resource files to the designated collection in GABBs iRODS zone and redirect to GABBs tool launch url with needed request parameters. 
- [x] Modify the GABBs tool launch web app resource home page url so that it can be mapped to the custom view function I will write as detailed in the task above.
- [x] Test integration and adjust/modify as needed. This will also involve user authentication via OAuth setup configuration.

**Comment by hyi** [comment]
@zhiyuli This GABBs tool web app is different from other web apps in that it needs some extra work in HydroShare to push resource files before launching to a tool url. I plan to map the web app home page url to a view function in HydroShare to handle this extra work before redirecting to the tool launch url from inside the view function. I believe it will work with the current web app implementation, but have not got a chance to test it yet. Let me know if think this would not work with the current web app framework.

**Comment by dtarb** [comment]
@hyi is this complete.  Can it be closed
