### ISSUE TITLE
Can't update user profile

### ISSUE THREAD

**Issue by darksinge** [hydroshare/hydroshare#2521]
When I try updating the organization field on my profile and click save, I get an error that says "Sorry, an error occurred". 

When I go to the `/profile` route and open the developer console in chrome, I see some scripts are not being loaded and an error:

```
www.hydroshare.org/:32 GET https://www.hydroshare.org/static/css/jquery.tagsinput-revisited.min.css net::ERR_ABORTED
www.hydroshare.org/:62 GET https://www.hydroshare.org/static/js/jquery.tagsinput-revisited.min.js net::ERR_ABORTED
www.hydroshare.org/:62 GET https://www.hydroshare.org/static/js/jquery.tagsinput-revisited.min.js 404 (Not Found)
profile.js:320 Uncaught TypeError: $(...).tagsInput is not a function
    at HTMLDocument.<anonymous> (profile.js:320)
    at l (jquery-1.8.3.min.js:2)
    at Object.fireWith [as resolveWith] (jquery-1.8.3.min.js:2)
    at Function.ready (jquery-1.8.3.min.js:2)
    at HTMLDocument.A (jquery-1.8.3.min.js:2)
```

Apparently the organization field on the user update form should be populating a list of organization names to select from, but it's not.

**Comment by aphelionz** [comment]
Thanks @darksinge. I'll be looking to get this out this weekend.

**Comment by aphelionz** [comment]
This is confirmed fixed on https://park.hydroshare.org/

Hotfix will be deployed to www.hydroshare.org this evening.

**Comment by aphelionz** [comment]
Verified fixed on WWW
