### ISSUE TITLE
Home URL overwritten by RefTS code

### ISSUE THREAD

**Issue by jsadler2** [hydroshare/hydroshare#253]
The GUID that was stomped overtop of the URL value for “home” was  1173171ea834460d8bc5f57ded5aea50.
Home’s URL should always be “/“, and it is being written over somehow when the ref_ts resource is being created.
This is the same GUID as found in the SNOTELBevansCabin resource

**Comment by dtarb** [comment]
Tested after creating a new refts resource and the site remains up.
