### ISSUE TITLE
REST API Resource Creation Question

### ISSUE THREAD

**Issue by rajadain** [hydroshare/hydroshare#2530]
Hello,

I'm trying to implement project export functionality from [Model My Watershed](https://github.com/WikiWatershed/model-my-watershed) into HydroShare, and plan to use the REST API to create and modify resources. As part of this exercise I read the documentation both in [Swagger](https://www.hydroshare.org/hsapi/#!/hsapi/resource_create) and the [source](https://github.com/hydroshare/hydroshare/blob/97e3b7ea1193bc5ffcaea2469e16e8f55d9bdf23/hs_core/views/resource_rest_api.py#L316), which lead me to believe that the only required parameter for creating a resource is `resource_type`, all else being optional. However, when I try to POST to the `/resource/` endpoint with that, I get the following message:

```http
> http --print HhBb https://dev.hydroshare.org/hsapi/resource/ Authorization:"Bearer $MMW_HYDROSHARE_ACCESS_TOKEN" resource_type=GenericResource

POST /hsapi/resource/ HTTP/1.1
Accept: application/json, */*
Accept-Encoding: gzip, deflate
Authorization: Bearer $MMW_HYDROSHARE_ACCESS_TOKEN
Connection: keep-alive
Content-Length: 36
Content-Type: application/json
Host: dev.hydroshare.org
User-Agent: HTTPie/0.9.9

{
    "resource_type": "GenericResource"
}

HTTP/1.1 400 BAD REQUEST
Allow: GET, POST, HEAD, OPTIONS
Connection: keep-alive
Content-Language: en
Content-Type: application/json
Date: Mon, 18 Dec 2017 19:22:34 GMT
Server: nginx/1.11.10
Transfer-Encoding: chunked
Vary: Accept, Accept-Language, Cookie

{
    "resource": "Resource creation failed. 'NoneType' object is not iterable"
}
```

I believe this error is coming from [this line](https://github.com/hydroshare/hydroshare/blob/97e3b7ea1193bc5ffcaea2469e16e8f55d9bdf23/hs_core/views/resource_rest_api.py#L487), although I am unsure what is causing it. I tried adding `title` and `subject` to the request, but the endpoint continued to return the same message.

I was also unable to find an example payload for this endpoint to copy from. I would appreciate any guidance to amend this request.

**Comment by aphelionz** [comment]
Hi @rajadain Can you please try the same on beta.hydroshare.org? We discussed this this morning and dev.hydroshare.org is out of date currently.

**Comment by rajadain** [comment]
Trying it now.

**Comment by rajadain** [comment]
Yes I get the same result:

```http
> http --print HhBb https://beta.hydroshare.org/hsapi/resource/ Authorization:"Bearer $MMW_HYDROSHARE_ACCESS_TOKEN" resource_type=GenericResource

POST /hsapi/resource/ HTTP/1.1
Accept: application/json, */*
Accept-Encoding: gzip, deflate
Authorization: Bearer $MMW_HYDROSHARE_ACCESS_TOKEN
Connection: keep-alive
Content-Length: 36
Content-Type: application/json
Host: beta.hydroshare.org
User-Agent: HTTPie/0.9.9

{
    "resource_type": "GenericResource"
}

HTTP/1.1 400 BAD REQUEST
Allow: GET, POST, HEAD, OPTIONS
Connection: keep-alive
Content-Language: en
Content-Type: application/json
Date: Mon, 18 Dec 2017 19:46:55 GMT
Server: nginx/1.11.13
Transfer-Encoding: chunked
Vary: Accept, Accept-Language, Cookie

{
    "resource": "Resource creation failed. 'NoneType' object is not iterable"
}
```

Do `beta` and `www` share the same backend? Or does it simply have a recent copy of `www`? `dev` seemed to be a different environment, which made it a good candidate for connecting to the staging site and experimenting in a sandbox.

**Comment by aphelionz** [comment]
@rajadain Ok, this is a bug then. beta and www are clones of each other and are generally in sync as far as versioning, etc

**Comment by rajadain** [comment]
If I create a test resource in `beta` will it also show up in `www`?

**Comment by aphelionz** [comment]
Negative

**Comment by dtarb** [comment]
@pkdash or @Castronova may be able to provide guidance here.  I know that the Jupyter App platform is able to successfully create resources in HydroShare using the API.  I am not sure how that is different from from what is being tried here.

**Comment by rajadain** [comment]
I'll try using the hs_restclient library which may work better.

**Comment by Castronova** [comment]
@rajadain Here is some code that should help you get started:

```
from hs_restclient import HydroShare, HydroShareAuthBasic
auth = HydroShareAuthBasic(username='myusername', password='mypassword')
hs = HydroShare(auth=auth)

hs.createResource("genericresource", 
                  "my title", 
                  resource_file="my file",
                  abstract="my abstract", 
                  keywords=["keyword 1", "keyword 2"])

```

**Comment by rajadain** [comment]
Thank you, the above is working for me.

@aphelionz, this is no longer blocking my work, so maybe doesn't need the `High Priority` tag anymore. Perhaps this is more a documentation issue at this point.

Thank you all for your support.

**Comment by aphelionz** [comment]
Thank you @rajadain

**Comment by martinseul** [comment]
closed, implemented or stale
