### ISSUE TITLE
skip first gratuitous SOLR rebuild in hsctl

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#2531]
The first SOLR build in hsctl always fails because the schema has not been loaded at that time. One must both copy the schema and restart SOLR.

**Comment by cuahsimarko** [comment]
@phuongdm I believe this is no longer an issue, can you close it or add updated information here?

**Comment by alvacouch** [comment]
@phuongdm @cuahsimarko This is fixed.
