### ISSUE TITLE
Extend systems operations monitoring to all operational components

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#2534]
Currently www.hydroshare.org is monitored by http://ci.hydroshare.org which, when a problem is detected sends an alert email to a list of developers (from hydroshare@hydroshare.org) and attempts an automated restart.  This functionality needs to be extended to all operational components of HydroShare including hyrax.hydroshare.org, apps.hydroshare.org, jupyter.cuahsi.org.  The list of people who receive alerts also needs to be managed. I'll create a separate issue for this.

**Comment by dtarb** [comment]
Also looping in @danames because some Apps generate messages such as.  We need to know who gets these messages and is responsible for acting on them.
 
![image](https://user-images.githubusercontent.com/3456833/34258147-ecbed536-e619-11e7-80c7-6f70a75054c1.png)

**Comment by cbcunc** [comment]
Tracking here: https://docs.google.com/spreadsheets/d/1U52G1P32F3BU9EvozZu96IUCgzmeY_eUej4-IgooR0c/edit#gid=0

**Comment by cuahsimarko** [comment]
Can we move this issue to each respective repo, such as https://github.com/hydroshare/hydroshare-jupyterhub/issues

**Comment by cbcunc** [comment]
Monitors currently in place for www (nginx1), data, users, apps, thredds, hyrax, beta (nginx1-beta). Need monitors for help and jupyter. Need to fix and re-enable beta monitor to use nginx1-beta.

**Comment by martinseul** [comment]
@cbcunc can we close this as we have nagios in place?

**Comment by cbcunc** [comment]
Now handled by Nagios.
