### ISSUE TITLE
Establish (or clarify) email list for systems operations alerts

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#2535]
I suggest establishing an email address such as admins@hydroshare.org for people who get systems operations email alerts from the operations monitoring system.  This is so that we can clarify and manage who is responsible for acting on these. See #2534

**Comment by cbcunc** [comment]
This was already accomplished via the hsmonitor@lists.renci.org email list, used by some monitor jobs. However, I just added an email forward through the Namecheap VM Cpanel for monitor@hydroshare.org forwarding to hsmonitor@lists.renci.org for cosmetic purposes.

**Comment by cbcunc** [comment]
Please note that different operational monitors have different sets of people receiving those monitors. For example, apps.hydroshare.org has @hyi and @zhiyuli on the notification list. So are core group of people are notified by monitor@hydroshare.org for every operational monitor, while other people receiving the notifications will still need to be maintained in the Jenkins configuration for each monitor job requiring additional people receiving notifications.

**Comment by cbcunc** [comment]
An additional email forward was just added for admins@hydroshare.org to forward to hsmonitor@lists.renci.org. It didn't seem practical to maintain another list (e.g. Hydroshare-Admins@lists.renci.org) with the same members, so using the existing list seems like the best approach.

**Comment by cbcunc** [comment]
Note also that an email forward to a Mailman list must be included in List Admin -> Privacy Options -> Recipient Filters -> Acceptable Aliases in order to avoid moderation and ensure timely delivery. monitor@hydroshare.org and admins@hydroshare.org have been added to the acceptable aliases.
