### ISSUE TITLE
Permissions for Creating Folders?

### ISSUE THREAD

**Issue by rajadain** [hydroshare/hydroshare#2537]
Hello,

I'm working on HydroShare export functionality for Model My Watershed. I am now able to successfully create resources and add files to them (for example: [66ce7b01a1e7490383e37a407979631c](https://beta.hydroshare.org/resource/66ce7b01a1e7490383e37a407979631c/)). So far I am using `hs_restclient`'s `createResource` and `addResourceFile` methods, which work very well. However, if I try to create a folder with `createResourceFolder`, I get a HydroShareNotAuthorized exception:

```
HydroShareNotAuthorized at /export/hydroshare/
Not authorized to perform PUT on https://beta.hydroshare.org/hsapi/resource/3c741c66702649f689aedcd580e23f9b/folders/area-of-interest.
```

I am able to create folders using the HydroShare UI, so it seems I just don't have the permission in the REST API, which seems odd.

Here's what my code looks like (messy, early draft):

```python
resource = hs.createResource(
    'CompositeResource',
    params.get('title', project.name),
    abstract=params.get('abstract', ''),
    keywords=('mmw', 'model-my-watershed')
)

aoi_folder = 'area-of-interest'
hs.createResourceFolder(resource, pathname=aoi_folder)

# AoI GeoJSON
aoi_geojson = GEOSGeometry(project.area_of_interest).geojson
aoi_file = StringIO.StringIO()
aoi_file.write(aoi_geojson)
hs.addResourceFile(resource, aoi_file,
                   '{}/{}'.format(aoi_folder, 'shape.geojson'))

# AoI Shapefile
aoi_json = json.loads(aoi_geojson)
crs = {'no_defs': True, 'proj': 'longlat',
       'ellps': 'WGS84', 'datum': 'WGS84'}
schema = {'geometry': aoi_json['type'], 'properties': {}}
with fiona.open('/tmp/{}.shp'.format(resource), 'w',
                driver='ESRI Shapefile',
                crs=crs, schema=schema) as shapefile:
    shapefile.write({'geometry': aoi_json, 'properties': {}})

for ext in SHAPEFILE_EXTENSIONS:
    with open('/tmp/{}.{}'.format(resource, ext)) as shapefile:
        hs.addResourceFile(resource, shapefile,
                           '{}/shape.{}'.format(aoi_folder, ext))
```

**Comment by aphelionz** [comment]
Hi @rajadain thanks for reporting this. I should be able to get to this later this week.

**Comment by aphelionz** [comment]
@rajadain Just checked into this and it seems to be a missing property on the CompositeResource model. I just opened up https://github.com/hydroshare/hydroshare/pull/2560

**Comment by rajadain** [comment]
Please let me know when this has been deployed to beta, so we can use it.

**Comment by aphelionz** [comment]
We will be looking at deploying this by the end of the month, but beta should be deployed this week for testing. I will re-open this ticket now.
