### ISSUE TITLE
What characters should we allow in file names?

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#2538]
I am able to create a resource that has the following file names

![image](https://user-images.githubusercontent.com/3456833/34322702-0139c9c0-e7ec-11e7-9fcc-e27ff8dd84ac.png)

If I download a bag and attempt to unzip in windows, I get an error message about TextFile:1.txt. I have the option to skip the error message and then I get 
![image](https://user-images.githubusercontent.com/3456833/34322705-11b769ec-e7ec-11e7-9c4b-1685ac8e8c68.png)

Notice that the : has been replaced with a _ and the \ in the name has resulted in a folder.  This folder construction occurred during the zipping process on the server as the folder is already there in the zip file downloaded.

The manifest file is as follows 
![image](https://user-images.githubusercontent.com/3456833/34322706-289b16d6-e7ec-11e7-8eb5-53b4f58cc3fc.png)

Thus it is inconsistent with the files one receives in the bag, making this a bug.

The resourcemap.xml file also does not have the “TextFil” folder in it that appears in the bag.

There are likely other weird things that can happen due to unusual characters in file names.  I suggest this be resolved by only allowing an official portable filename character set in our file names.  Wikipedia https://en.wikipedia.org/wiki/Filename led me to the following http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_276.  This gives the portable character set as 
A B C D E F G H I J K L M N O P Q R S T U V W X Y Z
a b c d e f g h i j k l m n o p q r s t u v w x y z
0 1 2 3 4 5 6 7 8 9 . _ -

I suggest that when a user attempts to load a file with a character not in this set that the action be blocked and an error message be generated. If the action can be gracefully continued by replacing the offending character with “_” then we should consider doing so, though it is possible for there to be cascading errors, such as name clashes resulting from the new name.  

I would like @alvacouch  and some of our iRODS experts @rayi113 @hyi @cbcunc to weigh in.  Perhaps the portable character set I identified is not the best, or there are other possible solutions.  

The resource where I created this example is
https://www.hydroshare.org/resource/a746c0a1a4d042a6ae9b5416e93aeccf/

**Comment by cbcunc** [comment]
I experience problems with blanks and parenthesis in file names for purposes of harvesting files for publication on Thredds.

**Comment by cbcunc** [comment]
I recently encountered a resource (https://www.hydroshare.org/resource/699227b982f5498281709e3d23a8cfce/), since corrected, with these two sibling folder names in contents

Content Analysis
Content_Analysis

So replacing the space in the first folder would result in a name collision with the second folder and fail. In the THREDDS harvester, I changed it to replace the space with dunder for a stopgap measure. I think this is pointed to needing to reject non-compliant file names rather than trying to fix them as I originally advocated.

**Comment by dtarb** [comment]
Design phase is assigned to @alvacouch.  Until there is an actionable recommendation, keep this on hold.

**Comment by dtarb** [comment]
See https://docs.google.com/document/d/1G7KHstXs6AqCHWHayhLI0A0SCU8QURkAwRnVZwmWvk4/edit#heading=h.sram8htt4ndg

**Comment by eclark-cuahsi** [comment]
Related to #2789 and #3024

Discussed that this is a complex issue that would need to be carefully worked out.

**Comment by dtarb** [comment]
@pkdash is working on this issue.  I've written a help file that I suggest be added to "Uploading and Publishing Data and Models" in our help pages.  The draft text is at https://docs.google.com/document/d/1ugaSzz0rWMxNkt-SlfLnfxso65D0cJwDF5A_mOs223Y/edit.  @horsburgh @ClaraCogswell 

I believe that this help file captures the decisions made in our recent discussions surrounding this and the implementation Pabitra is working on.

I suggest the following wording for the Resource landing page warning to display when a resource has non-preferred characters.
_The following files/folders contain non-preferred characters in their name.  This may result in problems and you are encouraged to change the name to follow the HydroShare preferred character set \<link to help file\>_
