### ISSUE TITLE
A corrupt multidimensional file type can result when netcdf file is loaded from iRODS

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#2539]
I created a new composite resource using a netcdf file from my desktop then set multidimensional file type and it worked fine.

I then created a new composite resource using the same netcdf file, but this time from iRODS and I get the following error 
![image](https://user-images.githubusercontent.com/3456833/34330730-3122f02a-e8dd-11e7-9e5e-9936e0462c22.png) 
when I click on the file metadata tab.

The good resource is https://www.hydroshare.org/resource/804f18eb031743f4826de2b5ee8dc0b9/
The problem resource is https://www.hydroshare.org/resource/1fe5622b13624cdfb9429b21241b200e/

**Comment by hyi** [comment]
@dtarb Both resources you linked above don't exist any more. Could you please check whether this issue still persists or not?

**Comment by dtarb** [comment]
I tested and confirmed that this is fixed.
