### ISSUE TITLE
Unable to Add Box Coverage to Resource

### ISSUE THREAD

**Issue by rajadain** [hydroshare/hydroshare#2543]
Hello,

I have two questions about adding coverages to resources in HydroShare. My code in MMW looks like this (irrelevant details elided):

```python
...

resource = hs.createResource(
    'CompositeResource',
    title,
    abstract=params.get('abstract', ''),
    keywords=('mmw', 'model-my-watershed') + keywords
)

...

aoi_bbox = aoi.envelope
[westlimit, southlimit] = aoi_bbox[0][0]
[eastlimit, northlimit] = aoi_bbox[0][2]
metadata = {
    'title': title,
    'coverages': [
        {
            'type': 'box',
            'value': {
                'northlimit': northlimit,
                'eastlimit': eastlimit,
                'southlimit': southlimit,
                'westlimit': westlimit,
                'projection': 'WGS 84 EPSG:4326',
                'units': 'Decimal degrees',
            }
        }
    ]
}
hs.updateScienceMetadata(resource, metadata=metadata)
```

1. While trying to add a coverage to a CompositeResource, I get this error:

       {
          "resource": "Resource metadata update failed: <class 'django.core.exceptions.ValidationError'>, Coverage metadata can't be updated for CompositeResource resource"
       }

    Is this by design? Is there a way to add coverage information during `hs.createResource` rather than using `hs.updateScienceMetadata`?

2. If I switch to using a `GenericResource` above, I get this error (had to monkey patch `hs_restclient` to show the original error which it was omitting):

        File "/usr/local/lib/python2.7/dist-packages/hs_restclient/__init__.py", line 460, in updateScienceMetadata
          raise HydroShareHTTPException((url, 'PUT', r.status_code, metadata, r.content))
        HydroShareHTTPException: Received status 400 Bad Request when accessing https://beta.hydroshare.org/hsapi/resource/c84b1b5c654d4685a692f0a6b73631eb/scimeta/elements/ with method PUT and params {u'coverages': [{u'type': u'box', u'value': {u'northlimit': 40.0310812816138, u'projection': u'WGS 84 EPSG:4326', u'units': u'Decimal degrees', u'southlimit': 39.876054698521, u'eastlimit': -75.159759422944, u'westlimit': -75.2585830259156}}], u'title': u'rajadain Local Philadelphia HUC12'}. Text: {"resource":"Resource metadata update failed: <class 'django.core.exceptions.ValidationError'>, Coverage type data is missing"}

    It indicates that `Coverage type data is missing`, even though `coverages: [{type: 'box', ...]` is specified. What is really curious is that if I PUT the same request via `curl` it works correctly and I get a successful response:

        $ curl --request PUT \
            --url https://beta.hydroshare.org/hsapi/resource/c84b1b5c654d4685a692f0a6b73631eb/scimeta/elements/ \
            --header 'authorization: Bearer XXXXXXXXXXXXXX' \
            --header 'content-type: application/json' \
            --data '{
            "coverages": [
              {
                "type": "box",
                "value": {
                  "eastlimit": -75.159759422944,
                  "northlimit": 40.0310812816138,
                  "projection": "WGS 84 EPSG:4326",
                  "southlimit": 39.876054698521,
                  "units": "Decimal degrees",
                  "westlimit": -75.2585830259156
                }
              }
            ],
            "title": "rajadain Local Philadelphia HUC12"
          }'

        {"title":"rajadain Local Philadelphia HUC12","creators":[{"name":"Model My Watershed","description":"/user/2123/","organization":null,"email":"systems+mmw@azavea.com","address":null,"phone":null,"homepage":null,"order":1}],"contributors":[],"coverages":[{"type":"box","value":{"northlimit":40.0310812816138,"projection":"WGS 84 EPSG:4326","units":"Decimal degrees","southlimit":39.876054698521,"eastlimit":-75.159759422944,"westlimit":-75.2585830259156}}],"dates":[{"type":"created","start_date":"2018-01-05T19:17:07.000125Z","end_date":null},{"type":"modified","start_date":"2018-01-05T19:37:01.133624Z","end_date":null}],"description":"Test Abstract","formats":[{"value":"text/csv"},{"value":"application/geojson"},{"value":"application/cpg"},{"value":"application/dbf"},{"value":"application/prj"},{"value":"application/x-qgis"}],"funding_agencies":[],"identifiers":[{"name":"hydroShareIdentifier","url":"http://www.hydroshare.org/resource/eaa37c8d9ea34fab96d591e9f1833ad1"}],"language":"eng","rights":"This resource is shared under the Creative Commons Attribution CC BY. http://creativecommons.org/licenses/by/4.0/","type":"http://www.hydroshare.org/terms/GenericResource","publisher":null,"sources":[],"subjects":[{"value":"mmw"},{"value":"model-my-watershed"},{"value":"tr55"}],"relations":[]}

    So is this a problem in `hs_restclient` or am I doing something wrong?

**Comment by cbcunc** [comment]
Adding myself to the comments in order to get more notifications.

**Comment by pkdash** [comment]
> While trying to add a coverage to a CompositeResource, I get this error:
{
   "resource": "Resource metadata update failed: <class 'django.core.exceptions.ValidationError'>, Coverage metadata can't be updated for CompositeResource resource"
}

This is by design for now. Composite resource coverage is a superset of all the coverages of all the file types. Resource level coverage is auto updated when the file type coverage changes. However, after  phase-2 of composite resource implementation, it should be possible to edit resource level coverage.

**Comment by rajadain** [comment]
> Resource level coverage is auto updated when the file type coverage changes.

Ah thanks for clarifying. How is the file type coverage set? I'm uploading a set of shapefiles in my resources (named `area-of-interest.shp` and `.dbf`, `.prj`, `.shx`, etc) but that shape isn't picked up. Do they have to be named something, or in a folder, for it to work?

On that note, I should also mention that we have been unable to create folders because of #2537.

**Comment by rajadain** [comment]
@pkdash the only examples of CompositeResource I can find with box coverages are these:

* [test harvey netcdf file](https://www.hydroshare.org/resource/75d17f265dba4c8396725cf98f652302/)
* [Testing NetCDF file type](https://www.hydroshare.org/resource/895425a231584353bb678fc7f2243092/)

Is there support of (and an example for) a CompositeResource that picks up the box coverage from a shapefile or geojson?

**Comment by pkdash** [comment]
@rajadain There is no REST endpoint for setting coverage for file types. However, for all file types excluding Generic file type, the coverage for a file type is automatically set when the file type is created. Here is an example of using hs_restclient to set/create a NetCDF file type:

```
>>> from hs_restclient import HydroShare, HydroShareAuthBasic
>>> auth = HydroShareAuthBasic(username='myusername', password='mypassword')
>>> hs = HydroShare(auth=auth)
>>> options = {
                 "file_path": "file.nc",
                 "hs_file_type": "NetCDF"
                          }
>>> result = hs.resource('ID OF RESOURCE GOES HERE').functions.set_file_type(options)

```
For creating a GeoFeature file type using a shp file set the file_path to path of the shp file and hs_file_type to 'GeoFeature'

Note: The file specified for file_path must exist for the specified resource.

**Comment by rajadain** [comment]
Perfect, thank you! We are now able to export the geographic features from Model My Watershed to HydroShare:

![screen shot 2018-01-16 at 3 59 06 pm](https://user-images.githubusercontent.com/1430060/35012036-4d63fbde-fad6-11e7-878b-32a7385e810f.png)

![screen shot 2018-01-16 at 3 59 03 pm](https://user-images.githubusercontent.com/1430060/35012038-4faf6bbc-fad6-11e7-8fba-1c46cb8ce0b9.png)

Since my query has been resolved, I am now closing this issue.
