### ISSUE TITLE
Swagger - get scimeta returns no content

### ISSUE THREAD

**Issue by Castronova** [hydroshare/hydroshare#2544]
Running the `GET /hsapi/resource/{id}/scimeta/` returns ` "error": "no response from server"`.

When I call this command using the `hs_restclient` I get the science metadata back:

```
>>> hs.getScienceMetadata('520f59bd5e72435b83390a571bb972b0')
{'title': 'testing', 'creators': [{'name': 'Anthony Castronova', 'description': '/user/11/', 'organization': 'CUAHSI', 'email': 'castronova.anthony@gmail.com', 'address': None, 'phone': '3399334127', 'homepage': None, 'order': 1}], 'contributors': [], 'coverages': [], 'dates': [{'type': 'created', 'start_date': '2018-01-05T20:12:53.234724Z', 'end_date': None}, {'type': 'modified', 'start_date': '2018-01-05T20:20:04.853416Z', 'end_date': None}], 'description': 'here is an abstract', 'formats': [{'value': 'application/zip'}, {'value': 'text/plain'}], 'funding_agencies': [], 'identifiers': [{'name': 'hydroShareIdentifier', 'url': 'http://www.hydroshare.org/resource/520f59bd5e72435b83390a571bb972b0'}], 'language': 'eng', 'rights': 'This resource is shared under the Creative Commons Attribution CC BY. http://creativecommons.org/licenses/by/4.0/', 'type': 'http://www.hydroshare.org/terms/GenericResource', 'publisher': None, 'sources': [], 'subjects': [{'value': 'test'}, {'value': 'resource'}, {'value': 'template'}, {'value': 'resource1'}], 'relations': []}
```

**Comment by Castronova** [comment]
adding `elements` to the end of the query string seems to work.  

```
GET /hsapi/resource/{id}/scimeta/elements
```

**Comment by pkdash** [comment]
@aphelionz and @Castronova 

The ```GET /hsapi/resource/{id}/scimeta/``` is an endpoint for downloading the resource science metadata xml file. I am guessing swagger interface is not capable of handling a file download. 

The use of ```hs.getScienceMetadata('520f59bd5e72435b83390a571bb972b0')``` is same as using the following:
```GET /hsapi/resource/520f59bd5e72435b83390a571bb972b0/scimeta/elements```

**Comment by aphelionz** [comment]
@pkdash and @Castronova As it stands right now, on the branch, swagger works and calling the endpoint directly via the browser downloads the XML File successfully. All I need to do is fix the tests.
