### ISSUE TITLE
"My resource" page doesn't list all resources owned by user

### ISSUE THREAD

**Issue by gantian127** [hydroshare/hydroshare#2546]
I own several public resources (author is not the owner) which can be find through the "Discovery" page. But it is not listed in "My resource" page. Can someone check what causes this? Thanks

**public resources owned by user which is listed in "Discover" page**
![image](https://user-images.githubusercontent.com/5016511/34642575-566eb2a2-f2d2-11e7-8bb4-779143e1bf5b.png)

**all netCDF resources listed in "My resource" page (missing the public resources shown above)**
![image](https://user-images.githubusercontent.com/5016511/34642548-cddda8da-f2d1-11e7-99c5-de11d2282134.png)

**Comment by dtarb** [comment]
@gantian127 please discuss with me if still an issue, otherwise close
