### ISSUE TITLE
NetCDF file type in composite resource failed to extract file type metadata

### ISSUE THREAD

**Issue by gantian127** [hydroshare/hydroshare#2547]
The netCDF resource can extract the time coverage metadata successfully from the example file. 
https://www.hydroshare.org/resource/c1f2679252c54d92bf54fc71eb1e03f4/

But when the composite resource converts the same file as netCDF file type, it will show error info and at the same time showing a message that the file type metadata has been extracted. (There is no file type metadata shown in the landing page)

![image](https://user-images.githubusercontent.com/5016511/34642714-00cdeec8-f2d5-11e7-93d1-7769e872db78.png)

![image](https://user-images.githubusercontent.com/5016511/34642717-129dda96-f2d5-11e7-9313-e63da7b63bb9.png)

**Comment by pkdash** [comment]
@gantian127 I will fix it soon.

**Comment by gantian127** [comment]
@pkdash thanks for looking into this issue.

**Comment by pkdash** [comment]
@gantian127 Can you check if this is still an issue?

**Comment by pkdash** [comment]
@gantian127 Thanks for checking. Can you then close this?
