### ISSUE TITLE
NetCDF file type metadata has wrong spatial reference and spatial coverage forms

### ISSUE THREAD

**Issue by gantian127** [hydroshare/hydroshare#2548]
The NetCDF file type in composite resource doesn't show the same metadata forms as that of NetCDF resource type (for spatial reference and spatial coverage metadata).

This makes the private composite resource unable to become a public resource when user needs to manually enter the required metadata. This issue can be tested with the NetCDF file in resource https://www.hydroshare.org/resource/25d864632a764ac3bb43fc35df7ff265/

The spatial coverage form should not include "longitude" and "latitude" fields. The spatial reference form should include "north extent", 'east extent', 'south extent', 'west extent' fields. 
But after the user edits the metadata and clicks "update netCDF file" button, the two forms will show correctly. 
![image](https://user-images.githubusercontent.com/5016511/34682491-444e53d0-f45c-11e7-8f3d-201f867561e4.png)

![image](https://user-images.githubusercontent.com/5016511/34682434-2c121f22-f45c-11e7-99fb-9e00580ff461.png)

**Comment by martinseul** [comment]
@sblack-usu @pkdash is this still relevant or can be closed?

**Comment by sblack-usu** [comment]
It can be closed.  The other extent fields are displayed and the longitude/latitude are no longer displayed in netcdf aggregations.
