### ISSUE TITLE
Not correct GUID...old URL method

### ISSUE THREAD

**Issue by jsadler2** [hydroshare/hydroshare#255]

**Comment by dtarb** [comment]
@jsadler2 Is this fixed.  Does 1.4.0 need to wait for this.  I am not sure what this refers to.

**Comment by jsadler2** [comment]
As far as I am aware, this is fixed. @mjstealey, do you know if this is still a problem?

**Comment by dtarb** [comment]
The title is not sufficiently descriptive for me to know what the problem was in the first place, so I am unable to test this.  @danames can you please test this (with @jsadler2 if necessary) and close if it meets your satisfaction.
