### ISSUE TITLE
Redirect To Resource After Login

### ISSUE THREAD

**Issue by rajadain** [hydroshare/hydroshare#2556]
Currently, if while not logged in, I attempt to access My Resources, I'm taken to a login page, after which I'm taken to the My Resources page:

![2018-01-10 13 48 17](https://user-images.githubusercontent.com/1430060/34789700-43628ccc-f60d-11e7-9332-d565fc2d8e0a.gif)

However, if while not logged in, I attempt to access a specific resource, I'm taken to a login page, and then to the home page, instead of back to that resource:

![2018-01-10 13 49 50](https://user-images.githubusercontent.com/1430060/34789718-572a8a2a-f60d-11e7-8166-dd0a1c7b5e05.gif)

Users should be taken to the resource they were originally trying to access after logging in.

**Comment by rayi113** [comment]
Adding that this appears to be related to GitHub issue #2323

**Comment by rajadain** [comment]
Ah I think it's the same exact same issue. I tried to search for "redirect" in existing open ones but didn't find that one.

**Comment by cuahsimarko** [comment]
Related to https://github.com/hydroshare/hydroshare/issues/2829 ?

**Comment by cuahsimarko** [comment]
https://github.com/hydroshare/hydroshare/issues/2557

**Comment by Lizabrazil** [comment]
@cuahsimarko this is pretty high priority and I do not think it needs much design. Let me know if you have questions.

**Comment by Lizabrazil** [comment]
#2323 I am closing this related issue

**Comment by pkdash** [comment]
@rajadain This issue can be closed.

**Comment by rajadain** [comment]
Has this been addressed in a PR or commit?

**Comment by cuahsimarko** [comment]
I don't know the exact commit, but I have observed for a while now, that when I attempt to access a protected resource, I'm prompted to login then redirected to the requested resource... which is my understanding of what's being requested in this GH Issues 2556

**Comment by rajadain** [comment]
+1 tested on beta.hydroshare.org, it is now working as desired. Thanks!
