### ISSUE TITLE
Redirect After Signing Up

### ISSUE THREAD

**Issue by rajadain** [hydroshare/hydroshare#2557]
We use an OAuth flow to have users authorize Model My Watershed to post to their account. This works pretty well when they already have an account:

![2018-01-10 14 33 54](https://user-images.githubusercontent.com/1430060/34791870-47c6bfb6-f614-11e7-9267-d9aa383a9905.gif)

However, if they try to sign up with a new HydroShare account, the workflow is quite broken:

![2018-01-10 14 36 07](https://user-images.githubusercontent.com/1430060/34791949-80798744-f614-11e7-803a-f1b415cec11b.gif)

After signing up they are taken to the home page and can't do anything. This can be significantly improved if when signing up the previous URL is preserved in the `/next=` query parameter, so that after signing up the user can be brought back to the login page, after which they'll be taken to the OAuth page.

Similar to #2556

**Comment by cuahsimarko** [comment]
@Lizabrazil will the new dashboard capture the login redirect? If so, I believe you can close this GH Issue. Otherwise, it should be coordinated with @engineSound how to redirect users to their original request OR the new dashboard, based on the page referrer.

**Comment by cuahsimarko** [comment]
https://github.com/hydroshare/hydroshare/issues/2829
https://github.com/hydroshare/hydroshare/issues/2556

**Comment by engineSound** [comment]
@cuahsimarko These issues are outside of the dashboard scope.

**Comment by Lizabrazil** [comment]
yeah not sure that this will be fixed as it is a separate application that is using oauth to sign in a hydroshare user and then needs to be redirected to the resource that the application is exporting.

**Comment by rajadain** [comment]
Just to clarify, Model My Watershed (the third party application in the screenshots above) opens an iframe to HydroShare for the login part, so the interface you see in the modal is entirely HydroShare.

**Comment by Lizabrazil** [comment]
Ah, so once the modal opens it should already know to redirect to the resource which you exported from Model My Watershed. The issue has to do with account creation requiring a user to verify their account via email before having access to their account. Create account->verify via email->access HydroShare account

Unfortunately, we do not have plans to bypass the email verification requirement for accessing an account. @dtarb @martinseul was an alternative ever discussed? I could see how this could negatively impact experiences with apps that have a HS connection. I'm not sure of the security issues.

**Comment by dtarb** [comment]
I would like to retain the email verification step as part of HydroShare account creation, but if there is a way to retain this and have the process work, we should try to do it.

What I think is being asked is that when a user is redirected to sign in it retains a next page parameter.  This is done on our pages such as collaborate when not signed in https://www.hydroshare.org/accounts/login/?next=/collaborate/.  I think@rajadain is asking for this to also be done for the page used in the model my watershed workflow.

If it is possible to do this, we should do this, but do not know the details of what would be involved.

@rajadain if you can provide any specific guidance, this may be something that @hyi can work on.

**Comment by dtarb** [comment]
@rajadain we have discussed this in our team and @hyi will have some availability following April 29 to look into this issue and make small changes that may be needed.  However I do not think it is clear yet exactly what the workflow should be where account creation and email verification is involved.  It would be helpful if you could provide suggestions or specific guidance.  Would an acceptable solution be that MMW users need to create and link a HydroShare account first before attempting to export a resource.  This would be a solution on the MMW side, not HydroShare side.

**Comment by horsburgh** [comment]
@dtarb - this is what we did with the Monitor My Watershed data sharing portal. Users register their HydroShare account with the portal and then they can copy data to HydroShare.

**Comment by rajadain** [comment]
When we start the OAuth dance with HydroShare, the first URL we try to hit is `https://beta.hydroshare.org/o/authorize/?redirect_uri=http://localhost:8000/user/hydroshare/authorize&response_type=code&client_id=model-my-watershed`, which, if the user is not logged in to HydroShare, redirects to `https://beta.hydroshare.org/accounts/login/?next=/o/authorize/%3Fredirect_uri%3Dhttp%253A%252F%252Flocalhost%253A8000%252Fuser%252Fhydroshare%252Fauthorize%26response_type%3Dcode%26client_id%3Dmodel-my-watershed`. Because of the `?next=` parameter, once the user does log in, they are redirected back to the original URL and the authorization continues.

At first, I had thought it was a simple matter of adding the `?next=` handler to the sign-up process, but thanks to the explanations above I see that signing up does not log one in automatically: they have to click a verification link in their email for that.

UX-wise, I don't really think there is a good way around this that also keeps the email verification intact. I suppose we could add messaging on the MMW side letting people know that they should have already signed up for HydroShare, but I doubt it would be very helpful.

@aufdenkampe Do you have any recommendations? Or a sense of how often people without HydroShare accounts encounter this from MMW? If it is a small enough number then perhaps we can leave this as is?

**Comment by hyi** [comment]
@rajadain Agreed that UX-wise, there is not a good way around this that also keeps the email verification intact. Adding messaging/advertising on the MMW side sounds acceptable to me letting people know that they should have already signed up for HydroShare before accessing MMW resources in HydroShare. I will not do any work in HydroShare on this unless MMW team come up with specific recommendations for changes in HydroShare to support the OAuth workflow in MMW. Looping in @dtarb @martinseul @rayi113

**Comment by cuahsimarko** [comment]
@Lizabrazil let's refine this

**Comment by dtarb** [comment]
@cuahsimarko what does "refine this" mean in the context of this issue?

**Comment by martinseul** [comment]
Close, take no further action at this time
