### ISSUE TITLE
P2 Composite Res: Change text references from "logical files" to "Aggregations"

### ISSUE THREAD

**Issue by horsburgh** [hydroshare/hydroshare#2564]
Phase 2 of composite resource implementation involves a terminology change. Any text references in the user interface to "Logical Files" needs to be changed to "Aggregations" for consistency
* Change the File Metadata tab to "Aggregation Metadata"
* Change the right click action labels to "Set as Geographic Raster Aggregation", "Set as Multidimensional Aggregation", "Set as Geographic Feature Aggregation", "Set as Reference Timeseries Aggregation", "Set as Timeseries Aggregation"

**Comment by aphelionz** [comment]
@pkdash Can you please add a 1,2,3 point estimate label to these tickets?

**Comment by horsburgh** [comment]
Not sure this needs to be rated. It's effectively done in the latest implementation of composite resource.

**Comment by horsburgh** [comment]
@pkdash - given the semantic changes I asked for today in #2762 I'm going to close this issue as it really no longer applies.
