### ISSUE TITLE
P2 Composite Res: Write Aggregation metadata and OAI-ORE resource map to the Aggregation's folder

### ISSUE THREAD

**Issue by horsburgh** [hydroshare/hydroshare#2565]
Implement writing of the Aggregation's metadata and OAI-ORE resource map .xml files to the folder that contains the Aggregation.  
* Resource-level metadata files include resourcemetadata.xml and resourcemap.xml. These files are written to the resource's "/data" folder. This is current functionality and will not change.
* Aggregation-level metadata files include <Aggregation>_meta.xml and <Aggregation>_resmap.xml. These files will be written to the same folder that contains the Aggregation's files. 

NOTE: See the issue on Aggregation naming to ensure that the Aggregation-level metadata files are named correctly.

* Include the metadata document as an aggregated file within the Aggregation's OAI-ORE resource map document
* The Aggregation-level metadata document should be constructed in the same way the resource level metadata document is constructed, but contains only Aggregation-level metadata
* The Aggregation-level metadata document should contain the Aggregation type, language, and Rights (inherited from the resource) because Aggregations can be downloaded separate from the whole resource
* The Aggregation-level metadata document should initially contain any Aggregation level metadata automatically extracted from the Aggregation's content files upon creation of the Aggregation (e.g., Coverage, Abstract, Title, Keywords, etc.)
* Modify the Resource-level OAI-ORE resource map document so that it doesn't list the individual files of a referenced Aggregation, but rather that it "aggregates" each separate sub-Aggregation within the resource by referencing only the Aggregation
* Ensure that the Aggregation-level OAI-ORE resource map document includes all of the Aggregation's content files + the Aggregation-level metadata document as Aggregated files
* Ensure that the Aggregation type is included
* The Aggregation-level OAI-ORE resource map document should be constructed in the same way that the resource-level OAI-ORE resource map document is constructed

This implementation should ensure that metadata and resource map file names and URL paths contained inside the files remain in sync with the file/folder hierarchy of the resource when it is changed. The file/folder names of the resource take precedence, so an implementation approach may be to set a "dirty" flag whenever any file/folder names are changed, so that these files are re-generated when needed.

Bagit Packaging
* Implementation of Bagit packaging will not change
* Need to verify that all Aggregation-level resource map and metadata documents are included in the Bagit bag and the Bagit Manifest tag file.

Key-value extended metadata for Aggregations 
* Key-value metadata pairs that describe an Aggregation should be written to the Aggregation-level metadata document instead of the Resource-level metadata document.
* Implementation of the encoding is the same as before, just the location has changed for which metadata document it gets written to.

Business rules for propagating metadata from an Aggregation to the resource level
* Treat these essentially as they were being treated in the phase 1 implementation
  * Title and Abstract are propagated if they are blank at the resource level
  * Keywords get appended to those at the resource level
  * Spatial and temporal coverage are propagated if they are blank at the resource level as a superset of the Aggregation's spatial and temporal coverage

**Comment by aphelionz** [comment]
@pkdash Can you please add a 1,2,3 point estimate label to these tickets?

**Comment by horsburgh** [comment]
I think this is already implemented in the work @pkdash has already done.

**Comment by dtarb** [comment]
1.16 deploy
