### ISSUE TITLE
P2 Composite Res: Enable upload of physical files that do not participate in an Aggregation

### ISSUE THREAD

**Issue by horsburgh** [hydroshare/hydroshare#2566]
Enable upload of physical files that do not participate in an Aggregation - Remove implementation that every file is a "logical file".

**Comment by aphelionz** [comment]
@pkdash Can you please add a 1,2,3 point estimate label to these tickets?

**Comment by horsburgh** [comment]
This is already done in the phase 2 composite resource implementation.

**Comment by dtarb** [comment]
1.16 deploy
