### ISSUE TITLE
P2 Composite Res: Implement UI functions for Aggregation files and folders

### ISSUE THREAD

**Issue by horsburgh** [hydroshare/hydroshare#2567]
Implement user interface functionality to have actions on folders:
* [x] Right click on a folder that is not already an Aggregation to convert contents to an Aggregation
* [x] Click on a folder that is an Aggregation to view or edit content in the "Aggregation Metadata" tab 

NOTE: For a first implementation, we can repurpose the "File Metadata" tab as the "Aggregation Metadata" tab. But, see the issue about redesigning the metadata view for an Aggregation to get away from a separate tab far down on the page.

* [x] Download the Aggregation as a zip file including the Aggregation's metadata file and OAI-ORE resource map document
* [x] Download a folder and its contents as a zip file - general purpose zip and download function for any folder within any resource.
* [x] Delete the Aggregation - removes folder, files, OAI-ORE resource map document, Aggregation-level metadata document, and any references to the Aggregation at the resource level
* [x] Remove Aggregation - deletes the Aggregation association, Aggregation-level metadata document, and OAI-ORE resource map document, but leaves the physical files and folder where they are
* [x] Rename the Aggregation - This should be the same as current folder or file rename functionality
* [x] Open with - presents options for launching the Aggregation to a list of Apps

**Comment by aphelionz** [comment]
@sblack-usu Can you please add a 1,2,3 point estimate label to these tickets?

**Comment by horsburgh** [comment]
I believe that the only thing that is not done here is the right click "Open with" functionality.

**Comment by aphelionz** [comment]
Sounds like it could be a decent amount of effort, no?

**Comment by sblack-usu** [comment]
@aphelionz I'm not ignoring your point estimate label, just waiting for the discussion on Monday to learn more about what each label means.

Downloading Aggregations is ready for review.
We get a freebie for aggregations in folders.  There is work necessary for single file aggregations.
https://github.com/hydroshare/hydroshare/pull/2754/files
https://github.com/hydroshare/django_irods/pull/39/files

Note that these are building off of functionality that haven't been merged into development/master yet, so the PR is against the branch I branched off of.

**Comment by Lizabrazil** [comment]
I noticed the Set Time Series option is "Timeseries" but we call it Time Series everywhere else on the site. Also, I may be out of the loop on this but I see a "Reference Timeseries" option...I thought that was deprecated..? 
I put this on the other ticket by accident.

**Comment by dtarb** [comment]
@Lizabrazil I am happy for us to standardize on two word "time series" usage for consistency.   Where they are inconsistently used, please point out and we can fix (though English usage is not consistent).  Reference time series as a resource type is deprecated, but as a content type within a composite resource, through the .refts.json file that is output from a CUAHSI app (data.cuahsi.org or data series viewer) they are still being used (and enhanced/developed more).
