### ISSUE TITLE
P2 Composite Res: Implement Aggregation Naming Rules

### ISSUE THREAD

**Issue by horsburgh** [hydroshare/hydroshare#2568]
An Aggregation within a composite resource will be named by its relative filename for single file Aggregations and by its relative folder path for multi-file Aggregations. Names will be relative to the "/data/content/" folder in the HydroShare resource. This ensures uniqueness of the Aggregation name, even where there are files or folders at different parts of a resource's folder hierarchy that may have the same name.

File and folder names should follow a portable file name character set (see https://github.com/hydroshare/hydroshare/issues/2538). This only includes alphanumeric and ". _ -" characters. Notably it does not include "/" and "\\" that are common file system folder separators. Also it does not include "+".  

The file names used for the Aggregation-level metadata file and Aggregation-level OAI-ORE resource map file will be:
\<Aggregation>_meta.xml
\<Aggregation>_resmap.xml  
Where \<Aggregation> is the base file or folder name for the Aggregation. See the following examples:

#### Single file Aggregation example:
* File location: /data/content/userfolder1/userfolder2/textfile.txt
* Aggregation name:  userfolder1/userfolder2/textfile.txt
* Name and path of Aggregation Metadata file:  /data/content/userfolder1/userfolder2/textfile.txt_meta.xml 
* Name and path of Aggregation OAI-ORE resource map file:  /data/content/userfolder1/userfolder2/textfile.txt_resmap.xml
NOTE: The Aggregation metadata file and the Aggregation OAI-ORE resource map file would be written to the same folder as the content file. The extension of the content file (.txt) is included in the naming of the Aggregation metadata file and the Aggregation OAI-ORE resource map file so that content files that differ only in extension could, if needed, be separate Aggregations with their own metadata files.

#### Multiple file aggregation example:
* Location of folder containing the Aggregation: /data/content/userfolder1/aggregationfolder
* Aggregation name: userfolder1/aggregationfolder
* Name and path of the Aggregation Metadata file: /data/content/userfolder1/aggregationfolder/aggregationfolder_meta.xml
* Name and path of Aggregation OAI-ORE resource map file:
/data/content/userfolder1/aggregationfolder/aggregationfolder_resmap.xml
NOTE: The Aggregation metadata file and the Aggregation OAI-ORE resource map file would be written inside the folder containing the Aggregation's content files and would be named using the name of the folder.

NOTE: The name for the Aggregation's folder (which becomes the aggregation name) should be obtained from (in the following order of preference): (1) The name of the zip file or the name of the folder if the Aggregation was created from a zip file or a folder, (2) the name of the primary file of the Aggregation without the file extension (i.e., the name of the “.shp”, “.nc”, “.vrt”, etc. file) if the Aggregation was created by clicking on an individual file. The folder containing the Aggregation will be created at the same location in the resource’s folder hierarchy as where that the original file(s) from which the Aggregation was created were located.

#### Aggregation Name Changing
Changing the name of the file for single file Aggregations or the name of the folder for multi-file Aggregations changes the name of the Aggregation. These file/folder name changes must be written to:
* <GUID>/manifest-md5.txt
* <GUID>/data/resourcemap.xml
* <GUID>/data/\<Path to Aggregation>/\<Aggregation>_resmap.xml
* <GUID>/data/\<Path to Aggregation>/\<Aggregation>_meta.xml
* Any Django representations of the above

**Comment by horsburgh** [comment]
Only that it is what you will see in the file browser interface. The aggregation name for an individual file is the name of the file, and for an aggregation contained within a folder, it is the name of the folder. The name is important, though, for referencing the aggregation through the REST API.

**Comment by pkdash** [comment]
@horsburgh Multiple file aggregation question:

Are we allowing to have these 2 aggregation names in a specific composite resource instance?

folder_1
folder_1/folder_2

If we do then I guess we are creating nested aggregation.

**Comment by horsburgh** [comment]
@pkdash - I'm looking through the Composite Resources Design Discussion document. In our latest iteration, we do have a rule that says that Aggregations may be nested as long as the Aggregation type permits it. However, I don't see any text stating which Aggregation types permit nesting and which ones don't. I do see text that specifically states the "File Set" Aggregation does not allow nesting.

@dtarb - were there specific Aggregation types that you think should allow nesting? It's funny that our text only specifically states that "File Set" doesn't allow nesting, but in my opinion that's the only one out of the list of Aggregation types we want to support where I think we might want to allow nesting. Maybe I neglected to update the text (see item g under list item 21 at the top of page 10 in the document). Easiest for @pkdash would be if we did not allow nesting, but I can see the use case for it under a "File Set".

**Comment by pkdash** [comment]
@horsburgh and @dtarb I guess only for "File Set" which is a new aggregation type we may consider nesting. The nesting implementation complexity will depend on the business rules of File Set aggregation type.

In my current phase-2 implementation I am not allowing any nested aggregation. If nested aggregation is needed we should implement in the next phase of composite resource including File Set.

**Comment by horsburgh** [comment]
@pkdash - I had a moment of clarity last night and remembered that we discussed eventually having model instance resources as a special class of composite resource that may have nesting of other content types.

But, since that's a future goal, I think your suggestion for Phase 1 to not include nesting and then look at nesting for a next phase seems reasonable to me.

Are you suggesting that "file set" would be included in Phase 1 (without nesting) or that "file set" would be entirely Phase 2?

**Comment by pkdash** [comment]
@horsburgh Since "File Set" is going to be a new aggregation type, I suggest we implement it in the next phase so that I can finish my current work so soon as I can. That way Mauriel can start working on the needed UI changes for aggregation as soon as my current work gets merged. While Mauriel is working on UI changes I can add the File Set aggregation.

**Comment by horsburgh** [comment]
@pkdash - sounds good to me.

**Comment by dtarb** [comment]
Sounds good to me too.  File set is a new aggregation type, and will be the first that admits nesting.  But it is better to get this functionality out in small increments, so I am happy for it to be part of a later phase.

**Comment by aphelionz** [comment]
@pkdash Can you please add a 1,2,3 point estimate label to these tickets?

**Comment by horsburgh** [comment]
@pkdash can verify, but I believe the aggregation naming rules have been implemented.

**Comment by dtarb** [comment]
1.16 deploy
