### ISSUE TITLE
P2 Composite Res: New layout for Aggregation-level metadata on composite resource landing page

### ISSUE THREAD

**Issue by horsburgh** [hydroshare/hydroshare#2569]
The current "file metadata" tab on the composite resource landing page is located too far down the page, requires confusing selection of a file, then scrolling down to see the metadata for that file. In this issue we will design a new layout for Aggregation-level metadata on the composite resource landing page 
* Move closer to the Aggregation and access via right click on the Aggregation in the file browser
* May be a modal view
* Must also enable editing of Aggregation-level metadata when in Edit view for the resource
* Remove existing "File Metadata" tab lower down on the page

**Comment by Maurier** [comment]
Implemented as part of resource landing page reorganization: https://github.com/hydroshare/hydroshare/issues/2810

**Comment by horsburgh** [comment]
This is done and deployed to www as part of 1.19 release. Closing.
