### ISSUE TITLE
P2 Composite Res: Add new functionality for creating Aggregations

### ISSUE THREAD

**Issue by horsburgh** [hydroshare/hydroshare#2570]
Add new functionality for creating Aggregations within a composite resource. These did not exist in the Phase 1 implementation:
* Unzip a file and automatically detect Aggregations
* Extract multiple Aggregations from a single zipped file - e.g., multiple shapefiles in one zip file

**Comment by pkdash** [comment]
@horsburgh Trying to understand the requirements of this feature. I assume the user is going to ask the system to unzip the file (using the unzip menu option) after uploading the zip file.

**Comment by horsburgh** [comment]
Yes - It would essentially be treating an unzip operation in the same way as we would treat the multi-file upload operation.

**Comment by pkdash** [comment]
It seems then this functionality is available on www. There is a minor issue though. For some reason it creates a nested folder. Should be a minor fix.

**Comment by cuahsimarko** [comment]
@horsburgh is this obsoleted by the current roadmap? 
![image](https://user-images.githubusercontent.com/45397838/55359375-b681bd80-549f-11e9-9d9b-0dd09d013802.png)

**Comment by dtarb** [comment]
Testing this I find the following works as desired
- Multiple shapefiles can be added and they are properly auto-aggregated
- Zip files are not unzipped when they are loaded 
- When a zip file that holds one shapefile is unzipped, one aggregation is created
- When a zip file that holds two shapefiles is unzipped, two aggregations are created.  

In the case of two shapefiles, the aggregations are created in a folder named the same as the original zip file.  @pkdash commented that this would be a minor fix.  It may be debatable whether this is a problem or the desired/intended functionality.  

I will close this and leave @horsburgh to comment on this or reopen if he wants folders treated differently.
