### ISSUE TITLE
P2 Composite Res: Add Aggregation type terms to HSTerms vocabulary namespace

### ISSUE THREAD

**Issue by horsburgh** [hydroshare/hydroshare#2572]
Add terms describing Aggregation types to HSTerms vocabulary namespace. Also, should ensure that the HSTerms is an importable namespace of terms if it isn't already.

For example, see: http://dublincore.org/2012/06/14/dcterms

**Comment by horsburgh** [comment]
@pkdash - I've attached the text for the aggregation types to this comment.

[Composite_Resource_Terms.txt](https://github.com/hydroshare/hydroshare/files/1803998/Composite_Resource_Terms.txt)

**Comment by sblack-usu** [comment]
made the requested changes and submitted the PR

**Comment by aphelionz** [comment]
@pkdash Can you please add a 1,2,3 point estimate label to these tickets?

**Comment by horsburgh** [comment]
@sblack-usu can verify, but I think this one has been implemented.

**Comment by sblack-usu** [comment]
@horsburgh This is currently deplyed to beta and slated for the 1.15.1 RC.  You can verify here.  https://beta.hydroshare.org/terms/#singleFileAggregation

**Comment by aphelionz** [comment]
Cool, thanks!

**Comment by aphelionz** [comment]
Closing as 1.15.1 has been deployed. @horsburgh please confirm
