### ISSUE TITLE
P2 Composite Res: Modify /hsapi/_internal/data-store-structure to include Aggregations

### ISSUE THREAD

**Issue by horsburgh** [hydroshare/hydroshare#2574]
Modify the existing /hsapi/_internal/data-store-structure API function to include Aggregations. Need to include the full folder/file listing, but also include Aggregations and their type so that folders that are aggregations can be displayed as such with an appropriate icon in the file browser interface on the resource landing page.

**Comment by aphelionz** [comment]
@pkdash Can you please add a 1,2,3 point estimate label to these tickets?

**Comment by horsburgh** [comment]
I believe this is complete - or at least the work to make the file browser correctly display files, folders, and aggregations is complete in the phase 2 composite work.

**Comment by aphelionz** [comment]
Perhaps we should close these subtickets as they are added to the larger body of work. what do you think?

**Comment by dtarb** [comment]
Deployed 1.16
