### ISSUE TITLE
P2 Composite Res: Implement NEW REST Endpoints for Aggregations

### ISSUE THREAD

**Issue by horsburgh** [hydroshare/hydroshare#2575]
Implement new REST API endpoints to support creation, editing, deletion, and retrieval of Aggregations within a Composite resource.;
* Change the name of the existing endpoint resource_functions_set_file_type_create to resource_functions_set_aggregation_type_create
* Implement getAggregationList
* Implement getAggregationFileList
* Implement getAggregation

NOTE: It is assumed that other, existing API endpoints can be used to enable all file CRUD operations for Aggregations, but may need to verify or revisit this.

Details of the REST endpoints listed above are are in the composite resource design discussion Google Doc: https://docs.google.com/document/d/1Hb18tUZyG7PHSwrclRHOmcYcEJvD0i9dQSmNdVckBUc/edit?ts=5a591278 

In general, the REST API needs to be extended, adjusted or clarified so that there are functions to:
* Return the folder hierarchy in a resource
* Return a list of the files in a folder if the path to the folder is input
* Return all the files in a folder (retaining any folder hierarchy within the folder) as a zip file
* Create an Aggregation (of a designated type) from files in a resource
* Create an Aggregation by inputting the Folder path holding Aggregation files
* Create an Aggregation by inputting the path to zip file holding Aggregation files
* Remove an Aggregation by inputting the folder path to the Aggregation folder or the file path to the Aggregation file
* Download an Aggregation (the content files and metadata files) as a zip file

**Comment by pkdash** [comment]
@dtarb Let me know if you want Scott to work on this.

**Comment by dtarb** [comment]
@sblack-usu is product owner for the API, so yes I would like him to work on this, or at least coordinate with you as to who is in the best position to do this.

**Comment by dtarb** [comment]
see https://github.com/hydroshare/hydroshare/issues/2563#issuecomment-455803939

**Comment by martinseul** [comment]
@sblack-usu and @horsburgh review and act as needed
