### ISSUE TITLE
P2 Composite Res: Right click "open with" functionality for Aggregations

### ISSUE THREAD

**Issue by horsburgh** [hydroshare/hydroshare#2576]
Add functionality for right click "Open-With" to construct a URL to launch an Aggregation to an external web App.
* Present as a right click option on the file for single file Aggregations and on the folder for multi-file Aggregations
* Limit to list appropriate Apps in the "Open-with" list
* URL that is constructed should contain the following:
  * Resource Identifier (GUID)
  * Aggregation type in a URL-friendly encoding
  * Aggregation name

NOTE: See the issue on naming Aggregations. The Aggregation name will be the relative filename for a single-file Aggregation and the relative folder path for multi-file Aggregations.

**Comment by horsburgh** [comment]
@dtarb - given our recent conversation, would you say that this functionality is complete on www? I know that some of our apps are not currently keyed to open content types, but if I read your comments via email correctly, this functionality is complete? Can I close this?

**Comment by dtarb** [comment]
It was - but some errors crept in that @sblack-usu knows about and needs to fix.  Scott, you can choose whether to use this issue as the one for fixing the problems related to open with URL construction, or close this one and create a separate issue that describes the problem precisely.

**Comment by dtarb** [comment]
This is now implemented.  Closing.
