### ISSUE TITLE
Raster resource without projection metadata can be made public?

### ISSUE THREAD

**Issue by zhiyuli** [hydroshare/hydroshare#2579]
We noticed some public raster resources have no projection metadata, which made visualization in GIS app impossible. What is our policy/rule on making a raster resource public?

https://www.hydroshare.org/resource/1028f383d0d6426d86a3118a221f8fac/

https://www.hydroshare.org/resource/b91f3d1221ac4b20838e687b22e8470a/

**Comment by Castronova** [comment]
@zhiyuli what is the status of this? Please close or comment.

**Comment by dtarb** [comment]
Close as no raster resources any more
