### ISSUE TITLE
Migrate/regenerate resource metadata documents

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#258]
resourcemap.xml and resourcemetadata.xml for old resources need to be regenerated to make consistent with the updated way we are representing content in these.

**Comment by dtarb** [comment]
@pkdash can you please take a look at this.  It seems to me that we need two utility functions
1.  To generate resourcemetadata.xml from the contents in Django model
2.  To read resourcemetadata.xml and load the contents in to Django model
These will depend on resource type.  They will be used to maintain consistency between the Django model content and files in iRODS.

**Comment by pkdash** [comment]
Suggest we move this to release 1.6

**Comment by dtarb** [comment]
Closed since this referred to resources on beta that need to be hand migrated
