### ISSUE TITLE
Remove hs_metrics app

### ISSUE THREAD

**Issue by hyi** [hydroshare/hydroshare#2580]
@aphelionz I am assigning this issue to you just to evaluate whether it is appropriate to remove hs_metrics app from HydroShare repo. I believe it is not used and can be removed, but leave it up to you whether you think it should be removed or not.

**Comment by Castronova** [comment]
`hs_metrics` is being used to record HydroShare actions. These "actions" are used to generate usage reports via Jenkins and ELK-stack.
