### ISSUE TITLE
Empty resource created when nearing the threshold of 1GB

### ISSUE THREAD

**Issue by Lizabrazil** [hydroshare/hydroshare#2583]
User tried creating a resource with .9GB of data. The resource said it was created successfully but was actually empty with no content. The HS resource is still private so I will not share here. Mark has the resource.

**Comment by engineSound** [comment]
@aphelionz By looking at the phenomena, I would send it to back end for a quick check. It is functional defect.

**Comment by aphelionz** [comment]
Looks like I've been removed from the Hydroshare developers group and cannot un-assign myself from issues. Could somebody please remove me as assignee on all of these? https://github.com/hydroshare/hydroshare/issues/assigned/aphelionz

**Comment by cuahsimarko** [comment]
See screenshots on related issue for closue reasons https://github.com/hydroshare/hydroshare/issues/2584#issuecomment-549977591

Fixed.
