### ISSUE TITLE
Resource creation page continuously loads when nearing the 1 GB threshold

### ISSUE THREAD

**Issue by Lizabrazil** [hydroshare/hydroshare#2584]
Related to #2583 . The User also noted that during his first attempt to create a resource with .9GB of data, the resource creation page continuously loaded and never gave any feedback to why it was not creating properly or within a reasonable time. We need to add some feedback that informs the user after a certain amount of time goes by.

**Comment by cuahsimarko** [comment]
Consistently able to create 975MB files (nearing 1GB) via hs_restclient: 
![image](https://user-images.githubusercontent.com/45397838/68237138-95082780-ffd4-11e9-908a-456396ad7828.png)

**Comment by cuahsimarko** [comment]
Successful upload of 1.02 GB (on macOS filesystem), recognized as 975MB in HydroShare and received helpful status, percentage display the whole time 
![image](https://user-images.githubusercontent.com/45397838/68238487-4c05a280-ffd7-11e9-8496-58d0a64abb00.png)

**Comment by cuahsimarko** [comment]
![image](https://user-images.githubusercontent.com/45397838/68238531-5f187280-ffd7-11e9-8ead-7e6b8354e6e2.png)
