### ISSUE TITLE
IRODS PW Change 

### ISSUE THREAD

**Issue by Lizabrazil** [hydroshare/hydroshare#2585]
1.	Provide a “Change iRODS password” button on user profile page which only shows up when a user has logged into HydroShare and has an iRODS account created. Clicking this button would allow users to enter a new password to change to without requiring entering the old password. 
2.	Provide a “Reset iRODS password” button on user profile page which only shows up when a user has logged into HydroShare and has an iRODS account created. Clicking this button would allow the user’s password to be reset with the temporary password displayed to the user so that the user can change it later by logging into a linux shell and use ipasswd icommand.

No. 1 would be easiest on the user with the simplest workflow. As long as we don’t think it would pose any further security risk, we could go with it.  No. 2 pretty much does what Tony proposed below with a little bit of more automation. We could email the temporary password to the user or just display to the user in a popup box. 

Yes, if we want to make it more automated, please create an issue and assign it to me.

**Comment by devincowan** [comment]
I'm adding steps that one can take using [moduser](https://docs.irods.org/master/icommands/administrator/#moduser) to update passwords to our Confluence docs for now...
