### ISSUE TITLE
Establish URL mapping so that links in metadata documents work

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#259]
The metadata documents contain a lot of links of the form
http://<hydroshare url>/resource/<GUID>/data/resourcemap.xml
http://<hydroshare url>/resource/<GUID>/data/resourcemetadata.xml
These give a 404 error.  I think they should be made to work.

**Comment by pkdash** [comment]
This depends on the implementation of #185

**Comment by pkdash** [comment]
@dtarb Please check if this has been resolved and if so close this issue.

**Comment by dtarb** [comment]
The URL's I checked resolved.
