### ISSUE TITLE
GRoups invitation to email link expires too quickly

### ISSUE THREAD

**Issue by Lizabrazil** [hydroshare/hydroshare#2590]
The email notification that is sent when someone invites you to a group has a link that expires less than 24 hours. It should be valid longer.  (Not sure who to assign)

**Comment by sblack-usu** [comment]
I dug around to figure out where to extend the expiration window and found the settings in hydroshare/settings.py with the settings key of PASSWORD_RESET_TIMEOUT_DAYS.

It's currently set to 1 day, however if we update this value it will also update the window for all other email links using django's user authentication system (password resets, user creation, etc).  I doubt this is a concern, but I thought I'd point it in case there is concern.
