### ISSUE TITLE
Add quota usage and filter on My Resources Page

### ISSUE THREAD

**Issue by hyi** [hydroshare/hydroshare#2591]
@Maurier @horsburgh On the coordination call today, it was decided it'd be the best for @Maurier to work on integrating quota usage and filter on My Resources page after my PR https://github.com/hydroshare/hydroshare/pull/2525 will be merged this week for the next release. The quota information can be easily retrieved from the back end and I will provide any support needed on the back end for the front end work. The requirement related to this from Quota Rollout Plan document is copied below for your reference when implementing this:

-  Display dynamic size calculated from iRODS microservice on the user’s “My Resources” page. The size will be updated automatically in Django database when the user's quota is changed. 
-  There may be value in including resource size as one of the columns. I also suggest changing the Filter on the left to include "Hold Quota" so a user can isolate and list just the resources that are counting against their quota.

**Comment by cuahsimarko** [comment]
I see a quota usage when I log in. Does that cover this ticket, can it be closed?

**Comment by ClaraCogswell** [comment]
closing, addressed
