### ISSUE TITLE
Add Explore page

### ISSUE THREAD

**Issue by aramatev** [hydroshare/hydroshare#2592]
@dtarb @horsburgh @martinseul @aphelionz @aramatev 
The project is to create a "you might also like..." page for HydroShare. This page uses machine learning to infer resources (and other users and groups) that are likely of interest to each user, based upon usage patterns that HydroShare records. 

This is an MS project at Tufts University in partial fulfillment of the Master of Science in Computer Science. 

This issue serves to notify everyone that this project is ongoing.

**Comment by aphelionz** [comment]
Hi @aramatev can you elaborate? :)

**Comment by aramatev** [comment]
Hello, just joining the project. I have lots of python code reading to do. 
Waiting for @alvacouch, he'll elaborate don't worry. thanks!

**Comment by aphelionz** [comment]
Welcome!

**Comment by alvacouch** [comment]
@martinseul @Castronova To what extent are you using the data from the user activity logs? If I add recorded events, will that foul up your use tracking?

**Comment by Castronova** [comment]
It shouldn’t mess anything up since we’re only custom logs for the metrics.

Tony


On January 25, 2018 at 4:54:49 PM, Alva Couch (notifications@github.com)
wrote:

@martinseul <https://github.com/martinseul> @Castronova
<https://github.com/castronova> To what extent are you using the data from
the user activity logs? If I add recorded events, will that foul up your
use tracking?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/hydroshare/hydroshare/issues/2592#issuecomment-360613279>,
or mute the thread

**Comment by alvacouch** [comment]
@Castronova @martinseul 
Are you retrieving any usage data from 
`hydroshare.org/tracking/*` as implemented in `hydroshare/hs_tracking`?
Currently, `history` times out (probably due to response length) and `profiles` forces a login and doesn't respond.

**Comment by alvacouch** [comment]
@horsburgh @dtarb @martinseul I just changed this issue name to "Explore" and am creating a prototype "explore" tab. This would seem to overlap with Jeff's social discovery line item. The concept of the "explore" tab is that it shows you things that might interest you based upon your usage patterns. 

This is fundamentally a different activity than discovery. In discovery, you show the system what you want. In Explore, the system shows you things you might be interested in based upon your prior activities. 

For now, the "explore" tab will recommend resources based upon users' usage patterns. However, it has much more potential, including highlighting new holdings, showing top-rated or recently updated holdings, etc. So, @horsburgh should think about panes other than "recommendations" that might go into this page.

**Comment by dtarb** [comment]
Where do you envisage this new page/tab going in the overall website page set.  The current page map design is at https://docs.google.com/drawings/d/1WBGON5o7zDxSWaNytCMkIV1ewfSCQ0ccqXIz0w3ZOs0/edit.  If you are considering revisions, some discussion (and perhaps mocking up) of the big picture may be good, so we know what the purpose and goal is before too much coding.

**Comment by horsburgh** [comment]
I think this could potentially be two separate pages, but I think we should consider consolidating them in the main navigation of the site. For example, we use one "Explore" link at the top of the page that perhaps has a fly down menu that enables a user to select:
* Search for Resources - What we have now
* Explore Resources - New functionality Alva is proposing
* And perhaps even "Explore Users" - Browse and search users

**Comment by horsburgh** [comment]
Also - I had originally envisioned that suggestions of content a user might want to look at would happen on a user's "Dashboard" page that would have other social functionality like showing a feed of recent activity, etc. We haven't designed this page, and it isn't in our overall webpage set that @dtarb provided the link to, but it is in our early mockups and designs. Explore could be done via a separate page as @alvacouch suggests, but we could also decide that we want to do it via a Dashboard page. It's worth a discussion.

**Comment by cuahsimarko** [comment]
Does Recommendations work handle this? Also note RENCI and CUAHSI work on clustering and "proximity search" did not yield very usable results, due to low quantity of data.

**Comment by martinseul** [comment]
Close, part of recommendations
