### ISSUE TITLE
Data Rods Explorer - Sort out Login interactions with HydroShare

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#2593]
If I go to www.hydroshare.org and click on Apps (without logging in), I can open Data Rods Explorer.
I then do the following
- put a dot on the map
- click plot one variable
- click plot
I get the plot of the variable of interest (if I do not click anything else this was hourly precipitation)
- There is a button Upload to HydroShare
- I click on it and select ASCII
- I enter a title and click upload

I get an error "You must be logged into the app through HydroShare to access this feature"

There was nothing in the interface that indicated I had to log into HydroShare.  I was able to launch the app from HydroShare without logging in.

I then go back to HydroShare and sign in.  I repeat the process.  I still get the same error.

I then go to https://apps.hydroshare.org/apps/.  This is the Tethys Portal.  This logs me into HydroShare using Oauth, I presume.

I can now open Data Rods Explorer and have it "Upload to HydroShare".

There needs to be a smoother way for logging in to this App using HydroShare.

It can get even worse.

I completely close my browser.  Then I reopen it and do the following
- Click on Apps and go to Data Rods Explorer
- Create a plot (same sequence as above).
- Save to HydroShare.  This time it works.  
If however I click on the link to view it, it says I need to be logged in to see it.

Tethys, hosting the app appears to have remembered (perhaps through a cookie/token) my login credentials.  But HydroShare does not.  A similar problem occurs if I log in to HydroShare as a different user to the one I last used the app from.  

This could be resolved if the App gave an indication of who it was logged in as, and provided log in and log out capability.

**Comment by dtarb** [comment]
3rd party App.  @martinseul  is CUAHSI maintaining this.

**Comment by danames** [comment]
I believe this can be closed. The newly updated Data Rods Explorer linked here https://www.hydroshare.org/apps/ doesn't exhibit any of these issues... I'm closing this issue but if someone can duplicate any of these errors feel free to re-open. I can duplicate it.
