### ISSUE TITLE
Update Apps Help for consistency with approved apps on apps library page

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#2602]
The Apps library page holds 6 approved apps (at present) https://www.hydroshare.org/apps/
The Apps help page provides help for 8 apps (at present) https://help.hydroshare.org/apps/

Apps with help that are not approved include
- CUAHSI time series viewer
- CyberGIS TauDEM App
- EPA Waters Services App
- National Water Model Data Explorer App
- USGS AHPS Gageviewer App

Apps approved but where there is not help 
- OPeNDAP
- SWATShare (There is a help page in Modeling)
- JupyterHub (there is a Jupyter Python Notebook help page in modeling)

@Lizabrazil can you please address this with the help of others in the Education and Outreach team.

I suggest it is OK to have Apps documented in https://help.hydroshare.org/apps/ that are not on the Apps Library page, but then the help documentation should (near the top) explain how to open these apps (from the App Resource instance page).

I do not think it is OK to have approved apps that do not have help on  https://help.hydroshare.org/apps/.  Thus please move SWATShare and JupyterHub pages to the Apps section of help.  Please work with @gantian127 to get content for the OpenDap app help.

**Comment by Lizabrazil** [comment]
@dtarb documentation for approved apps are now on pages.hydroshare.org  OpenDAP SwAtshare, jup hub

**Comment by martinseul** [comment]
@ClaraCogswell could you please check if this is still an issue or can be closed

**Comment by ClaraCogswell** [comment]
This can be closed. Some of the apps listen in the original post are no longer on https://www.hydroshare.org/apps/ but all apps on that page have help documentation.
