### ISSUE TITLE
Add File Metadata

### ISSUE THREAD

**Issue by Castronova** [hydroshare/hydroshare#2604]
Add the ability to set file-level kv metadata using the API.  This is currently possible through the HS interface, but not accessible using the API.  The syntax might look something like this:

```
hs.resource('RESID').file('FILE NAME').custom({'test':'value'})
```

![image](https://user-images.githubusercontent.com/4822372/35923405-27e633d0-0bee-11e8-89db-1bcab47c158f.png)

This is related to issue #2545

**Comment by pkdash** [comment]
`'FILE NAME' -> 'AGGREGATION NAME'`

Metadata lives in aggregation/file type object and not in a specific resource file.

**Comment by aphelionz** [comment]
@pkdash thanks - is this exposed via REST, or only in an internal endpoint?

**Comment by aphelionz** [comment]
@Castronova @pkdash 

Here are the functions that I believe we need to map to REST API endpoints in order to get the fill filesystem metadata functionality available. Looking through the code now

![image](https://user-images.githubusercontent.com/106148/35930474-00491a60-0c00-11e8-99ca-95060d4a64f6.png)

**Comment by pkdash** [comment]
@aphelionz At this time there are no REST endpoints for file type/aggregation metadata update. I think we need a single REST endpoint for updating metadata similar to the one we have for resource. We should probably have a separate endpoint for key/value (custom) metadata update for file type. Once I  finish the major pieces of phase-2 of composite resource, you can easily add the endpoint for key/value custom metadata update.  The file type specific metadata update needs quite a bit of backend code before we can add the endpoint for that.

**Comment by aphelionz** [comment]
@pkdash Thanks. Do you have an ETA for when you expect the phase 2 composite resource updates? We have a conflicting deadline for a bulk import of resources into hydroshare and we were hoping to add the REST endpoints this week.

**Comment by pkdash** [comment]
@aphelionz I am hoping to get my part of the phase-2 by the end of this month. Then Mauriel can start on UI changes for phase-2. Also my initial work on phase-2 won't include any backend code to support bulk update of file type/aggregation metadata.  I am not sure I understand bulk import of resources and its dependency on REST endpoints.

**Comment by aphelionz** [comment]
@pkdash We are using the hs_restclient to essentially loop through an excel spreadsheet and pull scores of files from iRODS to create scores ofresources inside HydroShare. For this we need API endpoints as well as hs_restclient implementations...

What are the risks of going ahead and creating the file metadata endpoints before composite phase 2 completion?

**Comment by pkdash** [comment]
@aphelionz I don't see any changes to the models that represent file type (aggregation) and file type metadata between phase-1 and 2, there is probably not much risk in creating endpoints based on phase-1 (current) implementation. However, the url patterns for these endpoints need to change for phase-2. There is going to be some custom migration between phase-1 and phase-2 for generating file type metadata xml file and resource map file for existing phase-1 composite resources as these files are new and part of the file type in phase-2.

**Comment by cuahsimarko** [comment]
@zhiyuli Is this still an issue? Can you close it or add any insights you have from working on CZO?

**Comment by Castronova** [comment]
@sblack-usu will this be possible with the planned changes to the API?

**Comment by sblack-usu** [comment]
This already exists and should have been closed earlier.  From hs_restclient readthedocs.
```
>>> hs.resource('ID OF RESOURCE GOES HERE').files.metadata(pathname).content
```
```
>>> params = {}
>>> params['keywords'] = ["keyword1","keyword2"]
>>> params['spatial_coverage'] = {
        "units":"Decimal degrees",
        "east":-90.0465,
        "north":48.6791,
        "name":"12232",
        "projection":"WGS 84 EPSG:4326"
    }
>>> params['temporal_coverage'] = {"start":"2018-02-23","end":"2018-02-29"}
>>> params['extra_metadata'] = {"extended1":"one"}
>>> params['title'] = "New Metadata Title"
>>> hs.resource('ID OF RESOURCE GOES HERE').files.metadata(pathname, params)
```

The hs_rdf work will also allow you to read/update the aggregation metadata in an object oriented manner.
