### ISSUE TITLE
Change from address on outgoing quota warning email to an appropriate CUAHSI email

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#2606]
The email message sent when a user is over quota is:

![image](https://user-images.githubusercontent.com/3456833/35946170-02425ed8-0c20-11e8-9782-bf3c5ef55c4f.png)

- The salutation should use the users real first and last name "Dear David Tarboton", not dtarb.
- The from address should be a CUAHSI email address that is monitored, so that if someone replies, or there is a bounce, someone gets it and can act on it.
- The address to request additional quota should likely be the same
- The help information should link to help.hydroshare.org

Similar changes need to also be made to the quota warning email.

**Comment by hyi** [comment]
@dtarb  I took a look at the code and found the FROM address the code uses for sending quota warning email is ```settings.DEFAULT_FROM_EMAIL``` which is set as CUAHSI email address on www, so you should see FROM address set correctly in the over-quota email you received. I did find those over-quota warning email in my junk email folder as those emails are sent to support@hydroshare.org as well and verified the from address does come from CUAHSI email address, and the address to request additional quota is not the same but also an email address from CUAHSI. The address to request additional quota and the help info link are all part of the quota message that can be customized from admin panel, and I saw they all point to the right CUAHSI email address and help link. So I think the only thing I need to address in the code is the No. 1 item to make the salutation use the real user name. That can be done quickly and make into 1.16 release.

**Comment by dtarb** [comment]
Yes - the action needed still here is the salutation.
