### ISSUE TITLE
Use Kleene star convention in discovery parser

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#2610]
@Castronova @Lizabrazil @dtarb 
The current discovery parser does not implement any concept of "starts with". There is a well-accepted syntax for this that maps well into SOLR. The syntax `Cou*` means "a word starting with `Cou`". In computing, this is known as the **Kleene star convention**, and it is used ubiquitously in such places as the Linux shell and other command-line tools. 

Note that this syntax is incompatible with the quote syntax for exact phrases, so that `"Cou*"` matches a literal "Cou*". It is only operative in single-term match mode, outside of quotes. This is a SOLR limitation.

**Comment by martinseul** [comment]
@alvacouch review and act as needed

**Comment by cuahsimarko** [comment]
Covered by partial string matches GH Issue at https://github.com/hydroshare/hydroshare/issues/3937
