### ISSUE TITLE
[1.15 HOTFIX] new user identifiers break SOLR harvesting

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#2612]
In a routine validation of 1.15RC I discovered that SOLR harvesting is crashing because of the new user identifiers! 
```
django.db.utils.ProgrammingError: column hs_core_creator.identifiers does not exist
```

**Comment by aphelionz** [comment]
aha! Good catch. @alvacouch will you make the fix?

**Comment by alvacouch** [comment]
I'm on it. Need to do a rebuild and migration and validate.

**Comment by alvacouch** [comment]
(I was actually tracking down a busted harvesting validator; I had changed SOLR field names and not updated it. This is a maintenance command.)

**Comment by alvacouch** [comment]
```
CommandError: Conflicting migrations detected (0009_userprofile_identifiers, 0011_auto_20180211_0105 in theme).
```

**Comment by aphelionz** [comment]
@alvacouch This was merged.
