### ISSUE TITLE
[1.15 HOTFIX] User identifier data is not getting copied over to the first creator of the resource

### ISSUE THREAD

**Issue by pkdash** [hydroshare/hydroshare#2614]

**Comment by aphelionz** [comment]
@pkdash FYI we will be pushing RC1 to beta around 3:30pm EST today

**Comment by pkdash** [comment]
@aphelionz I will be creating the hotfix PR tonight. Could not create the PR before due to the migration files issue that Alva resolved later.

**Comment by pkdash** [comment]
@aphelionz This PR is going to be one liner change. Let me know if you want to make that change. I can give you the change pointers.

**Comment by aphelionz** [comment]
Sure go ahead. I will do it (more or less) now.

**Comment by pkdash** [comment]
@aphelionz 

After this line: https://github.com/hydroshare/hydroshare/blob/1.15-RC1/hs_core/hydroshare/utils.py#L862

add this one line:
`` party_data['identifiers'] = user_profile.identifiers``

**Comment by pkdash** [comment]
This has been fixed. Closing..
