### ISSUE TITLE
Author and Owner links on resource landing page

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#2615]
If the Author of a resource is an Organization, even if the homepage field has been filled in, a hyperlink is not set in the landing page.  

Also Owner Hyperlinks are not working, at least for this web app resource instance.
![image](https://user-images.githubusercontent.com/3456833/36151045-01f8b456-1083-11e8-8230-81c0f3bed1ca.png)

https://www.hydroshare.org/resource/88f69c2de0414d5dbeb9538eca0b7527/

**Comment by Maurier** [comment]
Additionally, a link needs to be shown for the Organization entry in the Authors table.

**Comment by dtarb** [comment]
Tested
