### ISSUE TITLE
Captcha does not work on beta RC 1.15

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#2627]
On Chrome
![image](https://user-images.githubusercontent.com/3456833/36235599-e746ca76-11ae-11e8-8801-9367dba9c323.png)

On Firefox
![image](https://user-images.githubusercontent.com/3456833/36235621-020f63e0-11af-11e8-8e79-6d31c7dbdb95.png)

**Comment by aphelionz** [comment]
Fixed on beta. We will add an additional step to the deployment checklist to cover this.
