### ISSUE TITLE
Updating Profile page with no Author Identifiers fails on beta RC 1.15

### ISSUE THREAD

**Issue by Maurier** [hydroshare/hydroshare#2629]
![image](https://user-images.githubusercontent.com/2448568/36272272-45f0d4ce-123e-11e8-97f5-31f445d9f0d4.png)

No error shown in console

**Comment by pkdash** [comment]
@Maurier I will try to fix this.

**Comment by Maurier** [comment]
Sounds good. Thanks!

**Comment by pkdash** [comment]
@Maurier It will be a one liner change in the backend. Would you like to fix it?

**Comment by Maurier** [comment]
Sure. Let me know what to do.

**Comment by pkdash** [comment]
@Maurier 
Change this line: https://github.com/hydroshare/hydroshare/blob/1.15-RC1/theme/views.py#L222
to:
`identifiers = post_data_dict.get('identifiers', {})`

**Comment by Maurier** [comment]
That worked.

However, here is another issue that I experienced. This happens when I try to create a resource after I've added identifiers to my Profile.

![image](https://user-images.githubusercontent.com/2448568/36274848-4d8491be-1246-11e8-9ace-dc301523bfdb.png)

**Comment by pkdash** [comment]
@Maurier For some reason I am not bale to create any resource on beta.

**Comment by Maurier** [comment]
@pkdash I am experiencing the same. I can no longer create resources on beta, but this only started happening once I added an identifier to my Profile.

**Comment by pkdash** [comment]
@Maurier I guess we didn't do much testing of identifiers before merging. Anyway, are you able to create a resource as user with no identifiers?

**Comment by Maurier** [comment]
@pkdash, well this wasn't happening locally until our work got merged with everything else. I did test for this use case, as I was also programming logic for the resource landing page regarding identifiers. 

I am able to create resources locally when the Profile contains no identifiers.

**Comment by pkdash** [comment]
@Maurier So locally are you seeing problem in creating resource if the creator has identifiers?

**Comment by Maurier** [comment]
Correct. I see the error below. 
![image](https://user-images.githubusercontent.com/2448568/36274848-4d8491be-1246-11e8-9ace-dc301523bfdb.png)

**Comment by pkdash** [comment]
@Maurier I think I know what's wrong. Give me a second.

**Comment by pkdash** [comment]
@Maurier I guess I introduced this bug when I did the hotfix for the resource creator identifiers. This need bit of debugging. Hope to fix it soon.

**Comment by pkdash** [comment]
@Maurier It seem we can't have identifier name that consists of words (e.g., Google Scholar). This error comes from generating the metadata xml file. If you replace your  profile identifier 'Google Scholar' with another one I think you should be able to create resource.  I am not sure how we should be validating the name part of the identifier. For now in the drop down menu we can change the option from Google Scholar' to 'GoogleScholar'. But if the user selects the option 'other' and then enters a name that has multiple words then the same error will happen. In that case I need to validate the name in the backend to make sure it is a single word.

**Comment by Maurier** [comment]
I propose another approach:

We could encode the spaces as HTML entities (&nbsp;) and save it as such. This way I can parse the identifier name as markup language and display it accordingly using the DJango built in pipe "safe".

I tested this locally and it works fine, it would just look a little weird in the metadata xml file.

**Comment by Maurier** [comment]
Additionally and to make a more elegant solution, we could agree on a way to encode the spaces and write our own custom filter to send the data to the view.

https://stackoverflow.com/questions/21483003/replacing-a-character-in-django-template

**Comment by pkdash** [comment]
@Maurier I don't think we can have the identifier name in the xml file in that format even though xml generation is not be any more a problem. I have to double check if I am doing the encoding of the 'identifier' element in the xml file correctly or not. This is the first time we are writing identifier data to the xml file. Would you be able create a resource with the creator with one identifier (ORCID) and generate a bag file and email me that bag file?

**Comment by Maurier** [comment]
I emailed you the bag file requested now. 

My point is, however, that if there is any encoding we can agree on to encode the spaces in the xml file, it can be accommodated in the front end.

**Comment by pkdash** [comment]
The encoding of the identifier element in the xml file is not correct. I have to fix that. Then we won't have this error.

**Comment by pkdash** [comment]
@Maurier This has been fixed in PR #2634
