### ISSUE TITLE
Update resource file metadata REST API endpoints to use aggregation name instead of file_id

### ISSUE THREAD

**Issue by aphelionz** [hydroshare/hydroshare#2635]
Based on this comment from @pkdash https://github.com/hydroshare/hydroshare/pull/2633#pullrequestreview-97364497

**Comment by aphelionz** [comment]
@pkdash @sblack-usu revisiting this. will this be necessary for composite phase 2 rollout?

**Comment by cuahsimarko** [comment]
@sblack-usu does this belong in another GH Repo?

**Comment by sblack-usu** [comment]
This was fixed in #3089
