### ISSUE TITLE
Author identifier - provide user control to indicate what should go into resource metadata

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#2636]
Issues #2629 and #2630 have addressed the need to have author identifiers associated with users in HydroShare.  The author identifiers listed include ORCID, ResearchID, Google Scholar Profile and ResearchGate Profile.  It seems to me that there are two separate needs (use cases) for these identifiers
1. To include in creator or contributor metadata in Resource metadata to disambiguate authors
2. To provide links in a user profile page into other systems where there is more information about the user.

It seems to me that these different use cases require different sets of identifiers.  For example, on my profile page I would like to be able to create links to
- ORCID
- ResearcherID
- LinkedIn (Note this is not on our current list)
- Google Scholar

However when I create a resource I do not think it meaningful to have as part of the resource metadata my Google Scholar and LinkedIn references.  I would also (personally) only like to put ORCID as it is more "open" than ResearcherID, so I want to support its use.  I think these choices may be different for other users.

Right now, all the identifiers I add to my profile would be included in resource metadata for resources where I am made a creator or contributor.

I therefore suggest we add a check box labeled "Include in resource metadata when adding me as a creator/contributor to a resource" next to each identifier on the profile landing page, that a user can use to control what gets into resource metadata about them.  With this the profile page can have many identifiers and external profile links, but the resource metadata only has publication type identifiers required and appropriate for resource creator/contributor identification.  This is a bit similar to a journal publisher asking for my ORCID when I submit a paper (but not my LinkedIn or Google Scholar).

If we take this approach, I would be comfortable expanding the current list of identifiers we support to also include
- LinkedIn
- Mendeley
- Scopus
- Facebook
- Figshare
- Twitter
- Github
- Youtube

Note that to some degree HydroShare already endorses some of these by including links to the CUAHSI pages for these in the HydroShare footer.

I am assigning this to @horsburgh to review this concept, and refine/accept, and then when ready, assign to @Maurier for implementation.

**Comment by horsburgh** [comment]
@dtarb - this seems reasonable. I suggest we finish the current work with the first 4 and release it and then add this functionality after that.

@Maurier - I'm assigning this to you. I am assuming that there will be back-end things that you will need help with?

**Comment by Maurier** [comment]
@horsburgh, yes. This will need some minor additions in the back end.

**Comment by dtarb** [comment]
Closing.  I no longer see merit in devoting resources to this.
