### ISSUE TITLE
Limit file size of images stored in our site

### ISSUE THREAD

**Issue by Maurier** [hydroshare/hydroshare#2637]
The images we allow to be uploaded in order to use as Group and Profile pictures need to be compressed to a reasonable size. At this point accessing the Collaborate page can take a while because of the time it takes to render the images. 

This is quite serious when the page is loaded for the first time in the device, but it also hinders user experience even after the images have been cached, since they are so large it still takes quite a long time to render them properly on the page.

An example of current image sizes in the Collaborate page:
![image](https://user-images.githubusercontent.com/2448568/36434603-a487a56c-161c-11e8-8a4b-efd1358c6769.png)

I propose we resize the images before they can be uploaded.

**Comment by dtarb** [comment]
Limit size for web app icons too while doing this.

**Comment by engineSound** [comment]
@Maurier @dtarb @sblack-usu @cuahsimarko I totally agreed front end should catch it. The backend should also have a double check. With the javascript source code in the browser and a user can alter it easily, it can go straight to the backend.

**Comment by sblack-usu** [comment]
While I do agree we should put limits on image size upload, they are not the major cause of the collaborate page loading slowly.  It takes nearly 6 seconds before the page actually starts to request images, with about 5 seconds for the hydroshare server to serve an initial response.  The largest image size you listed is 5.5 MB, which is not outrageous and the page displays while the images are being served.

**Comment by engineSound** [comment]
@sblack-usu Thanks for the update. I just loaded up the collaborate page. It is outrageously slow. It is a very simple page.  Even with images, it should not be take 5 seconds.

**Comment by devincowan** [comment]
I will add a filesize limit for the images. However I am inclined to agree with @sblack-usu. This[ performance profile](https://share.firefox.dev/383AVRS) for revisit load of https://www.hydroshare.org/groups shows some of the delays he mentioned
