### ISSUE TITLE
Edit to text on My Resources

### ISSUE THREAD

**Issue by jtpollak** [hydroshare/hydroshare#2638]
Text at the bottom of the My Resources page should be updated to "Search for Public Resources not owned by you." w/ a link to Discover. 

![image](https://user-images.githubusercontent.com/3604316/36443165-ff367ff0-1645-11e8-8e24-c7e559bc781f.png)

**Comment by horsburgh** [comment]
I suggest the following text:

"Search for public resources not owned by you on the Discover page."

The word "Discover" should be a link to the HydroShare discover page.
