### ISSUE TITLE
Create helper function to encapsulate FileMetaData updates

### ISSUE THREAD

**Issue by aphelionz** [hydroshare/hydroshare#2639]
from https://github.com/hydroshare/hydroshare/pull/2633#pullrequestreview-98061913

@pkdash wrote:
I think instead of having all these code logic here if we can make that as part of a function of the FileMetaData class similar to Resource MetaData class then later each File type metadata class can override the logic to meet it's own metadata editing requirements. Here is the reference to the use of a similar function in the case of updating resource level metadata in an endpoint:

https://github.com/hydroshare/hydroshare/blob/develop/hs_core/views/resource_metadata_rest_api.py#L196

**Comment by Castronova** [comment]
Stale, closing. This will also be deprecated with the `hsrdf` library
