### ISSUE TITLE
Duplicate migrations created for Model Program

### ISSUE THREAD

**Issue by Castronova** [hydroshare/hydroshare#264]
This seems like something that shouldn’t get generated each time a migrations call is made…. perhaps a better way to define it so that it doesn’t keep piling on a new migration file could be found.

```
operations = [
    migrations.AlterField(
        model_name='mpmetadata',
        name='date_released',
        field=models.DateTimeField(default=datetime.datetime(2015, 3, 12, 18, 31, 27, 686328), help_text=b'The date of the software release (m/d/Y H:M)', null=True, verbose_name=b'Release Date', blank=True),
        preserve_default=True,
    ),
```

Currently a new migrations file gets generated each time the instance is brought up and makemigrations is run since datetime will always be marching forward.

I can infinitely apply the "$ python manage.py makemigrations && python manage.py migrate" call and always get new migrations content for that field.

**Comment by dtarb** [comment]
@Castronova can you discuss this with @mjstealey .  I do not understand why we need code that embeds specific dates you have above.  It seems like there needs to be a simpler way to do it.  These issues are not cropping up for other resource types.  A model program is just another kind of file.  What am I missing.

**Comment by hyi** [comment]
@Castronova Is this still an issue or it has already been resolved?

**Comment by Castronova** [comment]
This has been resolved.
