### ISSUE TITLE
Suggested Edits to Footer

### ISSUE THREAD

**Issue by jtpollak** [hydroshare/hydroshare#2644]
Under Contact Us, change current text to "[Email Support](mailto:help@cuahsi.org)" and add another line with "Visit [cuahsi.org](http://www.cuahsi.org)"

All GitHub links (and other external links) should probably open in a new window...they currently do not. 

![image](https://user-images.githubusercontent.com/3604316/36688489-a0412644-1afa-11e8-884f-95cda4a8210a.png)

**Comment by aphelionz** [comment]
@jtpollak Luckily this is all inside the content management system and doesn't require a code change. As such, this has been updated on https://beta.hydroshare.org. If it looks good let me know and I'll make the edits on production as well.

**Comment by jtpollak** [comment]
Looks good! thanks @aphelionz

**Comment by aphelionz** [comment]
@jtpollak Updates have been made to production. Verify and close, please
