### ISSUE TITLE
Change the from email in outgoing emails

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#2645]
The current from email in outgoing emails, hydroshare@cuahsi.org, should be changed to an email address that someone reads and can respond to.  It used to be support@hydroshare.org, that was acted on by us in the developer team.  Currently no one appears to receive emails sent to hydroshare@cuahsi.org (I sent a test email on 2/5/18 and received no reply).

The from address should be an email address that is received by someone, as if anything goes wrong with a hydroshare generated email, receipt of a bounce can alert us of a problem.  Also if a user replies, and gets no answer that is poor public relations.

**Comment by dtarb** [comment]
@martinseul has this been addressed.  Test emails I sent on 2/5/18 and 4/3/18 received no response.

**Comment by dtarb** [comment]
Suggest solution 1 above.

**Comment by aphelionz** [comment]
hydroshare@cuahsi.org should forward to

* help@cuahsi.org
* Chris Calloway
* Ray I.
* Dave T
* Me

cc @phuongdm

**Comment by aphelionz** [comment]
This has been set up internally at CUAHSI. Closing.
