### ISSUE TITLE
OpenWith redirect hangs for a long time

### ISSUE THREAD

**Issue by Castronova** [hydroshare/hydroshare#2646]
When I go to jupyter.cuahsi.org the JH site appears in several seconds.  However when I launch JH from the HS OpenWith button it takes 15-20 seconds.  It appears to hang on the following url, which leads me to believe that it has something to do with tracking the applaunch. 

https://www.hydroshare.org/tracking/applaunch/?url=https%3A//jupyter.cuahsi.org%3A8080/jupyter%3Fhusername%3DTonyCastronova%26resourcetype%3DCompositeResource%26resourceid%3Dab5876a4522a415ba242b0ebabc3b11c;name=JupyterHub

**Comment by dtarb** [comment]
I am going to close this.  This was written May 2018.  I have done many JupyterHub opens between then and now, and others have too, with limited complaints and no specific further complaints about hanging.
