### ISSUE TITLE
Fix Selenium tasks

### ISSUE THREAD

**Issue by sblack-usu** [hydroshare/hydroshare#2652]
Selenium Tests currently aren't running.  Track progress to work on getting the selenium tests running again.

**Comment by aphelionz** [comment]
Moving this to high priority as we now have PRs dependent on this...

**Comment by aphelionz** [comment]
@sblack-usu Remind me which selenium tasks you were trying to run locally?

**Comment by sblack-usu** [comment]
theme/tests/multiplatform.test_register_account

**Comment by sblack-usu** [comment]
I support migrating the existing tests over to https://github.com/CUAHSI/QA-AutomationEngine and removing selenium tests from the hydroshare repository.

**Comment by aphelionz** [comment]
Changing this to an enhancement since the task is now "migrate existing tasks to selenium grid"
