### ISSUE TITLE
Fix link in Create Resource Message on resource create page

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#2653]
The message link on the resource landing page is dead, https://www.hydroshare.org/hsapi/_internal/create-resource/.  

![image](https://user-images.githubusercontent.com/3456833/36816255-85c03552-1c9a-11e8-87c2-d6a4c6b94f2b.png)

 It should go to <s>https://help.hydroshare.org/creating-and-managing-resources/formally-publishing-data/ </s> https://help.hydroshare.org/creating-and-managing-resources/

Reported by Rick Hooper, transmitted by @Lizabrazil

**Comment by sblack-usu** [comment]
verified on beta

**Comment by dtarb** [comment]
Verified.
