### ISSUE TITLE
Create Geographic raster messages need improvement

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#2657]
On the Create Resource page for a geographic raster add the message below immediately below the box where files are added.  

> Geographic rasters are stored in GDAL Virtual Dataset (VRT) format.  Add either a single file in GeoTIFF format, or zip file containing all the files of a GDAL Virtual Dataset.  See Geographic Raster Resource Type Documentation [https://help.hydroshare.org/hydroshare-resource-types/geographic-raster/].

![image](https://user-images.githubusercontent.com/3456833/36928313-18fa58d6-1e42-11e8-8dea-322d070454f8.png)

**Comment by Castronova** [comment]
No longer relevant since the migration to composite resource.
