### ISSUE TITLE
Clarify invalid geographic raster error message

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#2658]
Replace the message given when a file loaded does not validate as a geographic raster with the following 

>Validation Error: Unable to add file to resource. See Geographic Raster Resource Type Documentation [https://help.hydroshare.org/hydroshare-resource-types/geographic-raster/] for the requirements for files that can be added.

![image](https://user-images.githubusercontent.com/3456833/36928377-a186a254-1e42-11e8-9e20-e6b13c3f4b92.png)

This should be changed for both the create resource page and adding files to an empty resource.

**Comment by Castronova** [comment]
resolved
