### ISSUE TITLE
Do not refresh page when an error occurs adding a file to a geographic raster.

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#2659]
If a user attempts to add an incorrect file to a geographic raster, the file upload validation error is displayed, but immediately the browser attempts to refresh and the resend clears the error so a user has a hard time seeing the error.

![image](https://user-images.githubusercontent.com/3456833/36928494-8b0280f6-1e43-11e8-98e8-a106cdde090f.png)

**Comment by Castronova** [comment]
resolved. If the raster cannot be processed, an aggregation is not set.
