### ISSUE TITLE
Recommend Jupyter Notebook as an alternative to Cyberduck for large files

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#2662]
I found that it is possible to retrieve large files from iRODS into our JupyterHub instance (that has iCommands installed) and then download them from JupyterHub.  This was faster than CyberDuck for me and avoids having to use an old version of CyberDuck.  It also avoids having to install any 3rd party software - just use 3rd Party Software that HydroShare is already using (i.e. JupyterHub).  I suggest developing a clean JupyterHub notebook that provides guidance to users on doing this and revising our instructions in help to describe this.

See https://docs.google.com/document/d/1XCYVzaOFI2P9innJ2KITfQiw3MIj4CmDLFjjCYB3xRI/edit# for some additional details.

**Comment by ChristinaB** [comment]
@rayi113   I am trying to download this public resource: 
https://www.hydroshare.org/resource/ec518c49772b420b97047f7482ae92aa/

The first step of Dave's suggested work around is to Copy Resource Bag to iRODS User Zone
![image](https://user-images.githubusercontent.com/4108369/39202816-f114257e-47a7-11e8-897e-719de04eb441.png)

@Lizabrazil   You will note that this error also provides a link to the User, but the Downloading instructions at this link are not actually useful - they focus on Uploading only.  I did ask @alvacouch for a short State of the System description of what HydroShare can and can't do, so a user can make their own decision on how to manage their large files.  

@rayi113  -  in the short term, I would love help just actually getting the data from this 3GB file. I'm guessing the error is related to me not making the original upload, but the owner did share all permissions with me, to try to avoid this issue.  Any help would be appreciated.

**Comment by rayi113** [comment]
@ChristinaB I put a manually created zip file of the resource here in iRODS hydroshareuserZone: /hydroshareuserZone/home/public/ec518c49772b420b97047f7482ae92aa.zip

**Comment by cuahsimarko** [comment]
@dtarb Is this Issue more appropriate for the JupyterHub repo? If so can it be moved to there?

**Comment by dtarb** [comment]
I am OK with moving, but his is really an issue of documentation and I am not sure moving this will alter what needs to be done, or whether we decide not to do anything.

There is no enhancement or code change in what I am suggesting, just a JupyterNotebook that helps users work with iRODS from JupyterHub.  I think that this stalled out because @Castronova was in the past not supportive of this approach because he does not want to have JupyterHub get cluttered with a lot of large files when users do not clean up after themselves. However I feel that the CyberDuck alternative is overly difficult.  I would like for @Castronova and @Lizabrazil to discuss the options for large file loading and agree what advice to give to users and then do it.  If @rayi113 needs to help with documentation, he can help, but we first need to decide on a direction. 

The issue is
1.   It is presently not possible to load a file larger than 1 GB into HydroShare directly.  This will be addressed in the future, but that may be a while.     
2. Thus presently to load a file larger than 1 GB it has to be loaded into iRODS and then moved to HydroShare.
3. CyberDuck is a 3rd party iRODS client and the current help page explains its use.  However this is not very user friendly and the latest version of CyberDuck does not work with HydroShare iRODS.  This "may" be a limitation of the current iRODS version, but this is unclear.  So CyberDuck is doubly difficult, because if a user upgrades to the latest CyberDuck, which they are prompted to, they are unable to load files to HydroShare.
4. JupyterHub is able to receive large file uploads.
5. CUAHSI JupyterHub has iRODS icommands installed so it is possible to use these to load large files into iRODS and then into HydroShare.  A JupyterNotebook could be written to do all this, and that was what I suggested.  No changes to present code are needed.
6. @Castronova was in the past not supportive of this approach because he does not want to have JupyterHub get cluttered with a lot of large files when users do not clean up after themselves. 

There is a separate problem with the resource that @ChristinaB mentioned.  I believe the zip file in it is corrupt.  I am able to download the zip file but then 7zip complains extracting it.  Creating the bag to download the zip file or copy the bag to iRODS fails for me, possibly due to #2724 that seems to be awaiting the iRODS upgrade, and the issues are cascading.

**Comment by cuahsimarko** [comment]
I hope to maintain documentation, project, design and non-coding task tracking out of GitHub hydroshare/hydroshare code repository Issues. Similarly, REST API Client and JupyterHub tasks should be reflected in those respective repositories in GitHub Issues or Wiki or google docs.

**Comment by Lizabrazil** [comment]
@dtarb May be a good time to start adding to my "to-do list" https://docs.google.com/spreadsheets/d/18zHXyJdKZTw_lerKMzj2XVI6mXcqlC-sivRl5ztScRA/edit?usp=sharing

**Comment by dtarb** [comment]
@Lizabrazil I have added to your to do list.  @cuahsimarko what do we want to do about addressing the problem with the corrupt resource that @ChristinaB mentioned.

**Comment by cuahsimarko** [comment]
@dtarb @ChristinaB Ok my understanding of the situation, is we've moved the tracking of the documentation task out of GH Issues and there is still a corruption issue. Please confirm, @ChristinaB 
![image](https://user-images.githubusercontent.com/45397838/55839741-f6c3ea00-5af6-11e9-917a-392bc84503f0.png)

**Comment by Castronova** [comment]
I will create a jupyter notebook that demonstrates the HS <-> iRods interaction.
