### ISSUE TITLE
Update footer of help.cuahsi.org to have correct contact us information

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#2665]
The footer of http://help.cuahsi.org uses support@hydroshare.org as the contact us address.  This should be updated to help@cuahsi.org

**Comment by aphelionz** [comment]
Updated. @dtarb please confirm and close.

**Comment by dtarb** [comment]
The NSF award numbers listed in the footer of https://www.hydroshare.org/ and https://help.hydroshare.org/ are different.  I suggest they be the same.  I suggest use the list from www.

**Comment by aphelionz** [comment]
@dtarb fixed

**Comment by dtarb** [comment]
Not sure how much you want to sweat the details and be picky.  The substance is now the same, so I will close, but look at:  One is (c) 2016, the other (c) 2018.  I am not sure which is correct (not being a lawyer) - I've heard opinions about the first date being better to assert being first, but then there may also be a need to update.  Also  the fonts are different so the wrapping is different.
![image](https://user-images.githubusercontent.com/3456833/40682327-ae26c214-6348-11e8-8513-23995fcb2eb5.png)
