### ISSUE TITLE
Add "Cancel" button to "Create Resource Page

### ISSUE THREAD

**Issue by rphooper** [hydroshare/hydroshare#2668]
Currently there is no way (except to use browser navigation) to bail out of creating a resource. Add a "Cancel" button on the bottom left, opposite of "Create Resource" to allow user to back out of creating a resource and return to My Resources page.

**Comment by cuahsimarko** [comment]
Implemented 
![image](https://user-images.githubusercontent.com/45397838/56230449-413eec80-604a-11e9-9e2b-694a93980fbe.png)
