### ISSUE TITLE
New Landing Page

### ISSUE THREAD

**Issue by rphooper** [hydroshare/hydroshare#2669]
The current landing page is
![image](https://user-images.githubusercontent.com/6717493/37043922-0215d9ec-2130-11e8-93d8-de1676ef0fdf.png)

Keep carousel as it is (for now). 
Change "How it works" to "What it does" and have the following sections

1. Publish Data and Models
    * Easily publish shape files, netCDF files and more
   * Automatic population of metadata
   * Preserve metadata and provenance
   * Publish models, R, Python, or Matlab scripts and model instances
1. Get a DOI
   * Hydroshare can provide a DOI to reference your data
1. Share your data and models
   * Control access to files--share with as many or as few people as your like
   * Create research groups
   * Comment on files
1. Teach with Hydroshare
   * Organize data and models for assignments
   *  Create class groups

**Comment by rphooper** [comment]
@Lizabrazil and @ChristinaB can you review this suggestion?

**Comment by dtarb** [comment]
It would be good to have broader discussion of this as the landing page is high profile.  I am mentioning the User interface team, who are listed in [HydroShare Planning](https://docs.google.com/spreadsheets/d/1-RV8KjTsImUAYwytTxGef5J1EszCDpx-ZlZ02KThn3U/edit#gid=1307420991) who are @aphelionz @horsburgh @Maurier @martinseul @yanliu-chn for their input too.

**Comment by horsburgh** [comment]
@rphooper - there is already a section on the landing page "What you can do with HydroShare". We could swap the order of those and refocus the "What you can do with HydroShare" on the points you list.

We could also have a really simple focus when the page first loads and then add more detail about the features of the system as you scroll down. I could mock something up if you are interested.

**Comment by horsburgh** [comment]
Looking at this issue closer, we should  be referring to this as "HydroShare's home page" - not a landing page.

**Comment by rphooper** [comment]
@horsburgh Good point. I didn't scroll down far enough to see it. I don't think the current "how is works" is effective or helpful, so I would eliminate it to try to get the entire home page to fit without having to scroll. The carousel is some eye candy, but mostly empty calories, IMHO. 

The bigger issue is that all these decisions are subjective. I think the home page is off putting for new users. Who decides whether to act on that opinion?

**Comment by cuahsimarko** [comment]
@Lizabrazil @engineSound is this deprecated by new landing page work?

**Comment by Lizabrazil** [comment]
@cuahsimarko no, we still need to fix the homepage to better educate the user before they create an account.

**Comment by engineSound** [comment]
@cuahsimarko There is some work to do. @Lizabrazil has more details coming up, I think.

**Comment by Castronova** [comment]
Closing because this is no longer relevant.
