### ISSUE TITLE
Error adding Reference TS with Czech Characters

### ISSUE THREAD

**Issue by jirikadlec2** [hydroshare/hydroshare#267]
I tried to add the reference time series of snow depth at "Labská Bouda" site. I used the REST service option with the following REST URL: http://hydrodata.info/chmi-d/cuahsi_1_1.asmx/GetValuesObject?location=CHMI-D:1&variable=CHMI-D:SNIH&startDate=2014-11-01&endDate=2015-03-27&authToken=

The preview is shown correctly, but when I try to save the resource, I get an error: 'ascii' codec can't encode character u'\xe1' in position 644: ordinal not in range(128). Please see the attached error message.
![image](https://cloud.githubusercontent.com/assets/4144642/6872483/25d662cc-d46f-11e4-9e43-630bc284f6e3.png)

**Comment by dtarb** [comment]
@danames can you please test this on dev and if it is working close the issue.

**Comment by danames** [comment]
Is there a reason dev.hydroshare.org isn't sending confirmation emails for
new accounts? I'm not able to get in with my old account so I tried
creating a new one, but no confirmation email...

**Comment by dtarb** [comment]
@mjstealey please comment on the confirmation email.  There have been changes related to the "secrets" getting secured.  Also Michael will shortly (possibly in process already) be updating dev with code improvements from Calvin that better secure the email handling so some things will be changing there anyway.

**Comment by danames** [comment]
Just verified this is fixed in dev.hydroshare.org.
