### ISSUE TITLE
Long response times while using the REST API.

### ISSUE THREAD

**Issue by darksinge** [hydroshare/hydroshare#2670]
I experienced long response times (> 1-2 minutes) from the HydroShare server around 9:00 AM. Response times of that length are problematic! However, it sped up as the day progressed.

I'm concerned if this is an ongoing problem or (hopefully) just an isolated event, but I understand HydroShare went through some updates yesterday (3/5/18). I'm a couple months into working on a project that consumes the REST API and this is the first time I've had this problem. Has anyone else experienced this problem?

**Comment by horsburgh** [comment]
Ha ha - and unfortunately I discovered this behavior this morning as I was doing a demo on a teleconference!! I asked @darksinge to post this issue as it seems things have sped up now, but we were definitely experiencing issues this morning.
