### ISSUE TITLE
Add RENCI NWM capture to HydroShare Hyrax

### ISSUE THREAD

**Issue by rayi113** [hydroshare/hydroshare#2674]
Please add the following as an enhancement to  http://hyrax.hydroshare.org/opendap/nwm/  

/projects/water/nwm/data

/projects/water/matthew 

Thanks.

**Comment by aphelionz** [comment]
@rayi113 @cbcunc what is the status of this?

**Comment by cbcunc** [comment]
Exists on Thredds and decommissioning Hyrax.
