### ISSUE TITLE
Add Thumbnail View to Resource Landing Page

### ISSUE THREAD

**Issue by danames** [hydroshare/hydroshare#2678]
We have significant wasted white space on the top right of our landing page where the user would want to see a thumbnail of the resource. See proposed image. I believe we already have the concept of a thumbnail in our resource bag, but we need 1) API access to read/write the thumbnail; and 2) Draw the thumbnail (if it exists) in the indicated space. 

![screen shot 2018-03-13 at 3 51 45 pm](https://user-images.githubusercontent.com/3472628/37371878-8832afb8-26d6-11e8-92ee-3d9bfc950283.png)

**Comment by ClaraCogswell** [comment]
closing: stale, cosmetic, unlikely to allocate resources to this
