### ISSUE TITLE
Initial Setup of Automated UI Testing

### ISSUE THREAD

**Issue by valentinedwv** [hydroshare/hydroshare#268]
Choose UI test framework to so some automated UI testing of the interface.

Choices:
- https://saucelabs.com/
- python robotframework web driver http://robotframework.org/

Use in Jenkins

**Comment by valentinedwv** [comment]
add id to web page elements for testing
especially buttons.

**Comment by selimnairb** [comment]
@dtarb Assigning to you as we need to re-delegate this task.  This may be something @mauriel133 can work on as he is writing the client code.

**Comment by alexlemann** [comment]
Example available in the [UI testing branch](https://github.com/hydroshare/hydroshare/tree/268_ui_testing). 

@mjstealey Here are my notes for getting this to work on the docker image:
* pip install selenium
* curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash -
* sudo apt-get install -y nodejs
* sudo npm install -g phantomjs-prebuilt

I'm also running into issues with the ``live_server_url``. I'm not sure yet if this is a configuration or docker issue.

**Comment by alexlemann** [comment]
Initial set up completed with merge of PR #1614
