### ISSUE TITLE
Selection of map coverage boxes do not work

### ISSUE THREAD

**Issue by Lizabrazil** [hydroshare/hydroshare#2682]
related to #2649 i guess. See that when you select a box within a very large box that expands to most of the world you cannot narrow down results. 
![image](https://user-images.githubusercontent.com/13852599/37480414-93cff83c-2855-11e8-908e-a858d0d0ba63.png)
![image](https://user-images.githubusercontent.com/13852599/37480420-993b4c9a-2855-11e8-943e-6a788748317a.png)

**Comment by aphelionz** [comment]
@alvacouch can you have @xuezhaokun submit a fix for tix?

**Comment by engineSound** [comment]
This seems to be related to map API.

**Comment by engineSound** [comment]
@alvacouch Following up with @aphelionz recommendation plus my previous look into the issue, can @xuezhaokun take a look into this issue?

**Comment by hydrocheck** [comment]
Issue resolved as a part of the Discover redesign
