### ISSUE TITLE
Adding JSON-LD to hydroshare home page and resource detail pages

### ISSUE THREAD

**Issue by aphelionz** [hydroshare/hydroshare#2685]
- [x] Hydroshare Home Page
- [x] Resource Detail Pages

**Comment by horsburgh** [comment]
@aphelionz - can you provide any details about what this is? I'm curious. JSON-LD for what?

**Comment by aphelionz** [comment]
@horsburgh This is for enhanced discoverability by google and other search engines. The end user will not notice any difference at all. See the docs here: https://developers.google.com/search/docs/guides/intro-structured-data

**Comment by horsburgh** [comment]
Cool. Thanks. JSON-LD is something that I've read some about in relation to earlier work related to the resource data model and I was just curious what we were using it for in this context. Thanks for the link.

**Comment by aphelionz** [comment]
If you're curious and can get to it before I need to switch branches in my dev environment, you can view source at https://dev-hs-2.cuahsi.org to see it in action on line 178

**Comment by sblack-usu** [comment]
Is there a PR for this?  I'd like to take a look at the diff to see how we're using JSON-LD

**Comment by aphelionz** [comment]
Closing as 1.15.1 has been deployed. Confirmed.
