### ISSUE TITLE
Hotfix for quota and google recaptcha

### ISSUE THREAD

**Issue by hyi** [hydroshare/hydroshare#2696]
- [x] Also send quota warning email to administrator
- [x] Make administrator email link clickable with subject automatically populated.
- [x] Passing google recaptcha site key from server to template client without manual filling in.

**Comment by AaronV77** [comment]
Any plan on when you will release the 1.14.2 version of HydroShare? The 1.14.1 version has the broken reCaptcha and makes it not useable.

**Comment by aphelionz** [comment]
Closing as 1.15.1 has been deployed. @hyi please confirm
