### ISSUE TITLE
Improved verification e-mail security

### ISSUE THREAD

**Issue by ironfroggy** [hydroshare/hydroshare#27]

**Comment by dtarb** [comment]
It is still possible to have multiple accounts with the same name.  Full details of the desired email rules are in docs/DesignDocs/UserNameEmailRules.md on branch 72-sign-in-and-sign-out that should be merged in due course.  

This is part of the process to migrate design documents from Alfresco to github on an as needed basis.

**Comment by dtarb** [comment]
While we now check for duplicate usernames, it is still possible to create a new account with an email address the same as an existing account.  Thus this is a bug that we should sort out for release 1.6.

**Comment by dtarb** [comment]
A quirk just discovered related to this (#512) is that if a user has another account with the same email address (which should not be permitted) they are unable to edit their profile.

**Comment by aphelionz** [comment]
@hyi @dtarb @mjstealey Where are we at on this one?

**Comment by hyi** [comment]
@aphelionz I don't think we have made any progress on this one, but @dtarb or @mjstealey may know more on this.

**Comment by dtarb** [comment]
I think this is resolved.  The system does not let one create an account with the same email as an existing account.
