### ISSUE TITLE
Update Development Environment Instructions to use Docker

### ISSUE THREAD

**Issue by sblack-usu** [hydroshare/hydroshare#2701]
The Virtualbox environment used previously by the development team is slow to work with and most (all?) developers are no longer using it.  Support for Docker has grown and is much easier to work with than in the past.  Developers are able to work with docker natively on Windows, Mac and Linux.

Update the documentation to show how to setup a hydroshare development environment using docker.

**Comment by cuahsimarko** [comment]
Slacked with Scott. Closing due to https://cuahsi.atlassian.net/wiki/x/A4BS
