### ISSUE TITLE
Create "child" resource from Collections Resource

### ISSUE THREAD

**Issue by jsadler2** [hydroshare/hydroshare#2706]
It would be convenient to be able to **create** a new resource from a collections resource landing page. Currently users can only add existing resources to a collection.

**Comment by jsadler2** [comment]
The system should populate the `isPartOf` metadata relation in the "child" resource with the collections resource from whose landing page the "child" resource was created. This saves the steps of 

1. creating a new "child" resource from the normal, separate, page 
2. going back into the collections resource and finding and adding the "child" resource.

**Comment by ClaraCogswell** [comment]
Closing, stale
