### ISSUE TITLE
Having the option to push/pull collection metadata to "child" resources

### ISSUE THREAD

**Issue by jsadler2** [hydroshare/hydroshare#2707]
It would be convenient to "push" or "pull" metadata in a collections resource to it's "child" resources.

**Comment by jsadler2** [comment]
PUSH - For example, say that you've added several resources to a collection and you have added several keywords to the collections resource. Instead of editing each "child" resource individually to add the keywords, it would be convenient if you could just click "Push metadata to resources" which maybe opens a dialog where you can choose which elements ("keywords" in this case) and which resources to push to. Then the keywords in collections resource are copied to the selected "child" resources.

**Comment by jsadler2** [comment]
PULL (the inverse of PUSH) - For example, say you've added several resources to a collection and you have added different sets of keywords the various "child" resources. If you wanted the keywords of the collection resource to be the combined set of keywords from the "child" resources you should be able to click something like "Pull metadata from 'child' resources" which maybe opens a dialog where you can choose which elements ("keywords" in this case) and which resources to pull from. Then the keywords in collections resource are copied from the selected "child" resources.

**Comment by ClaraCogswell** [comment]
Closing, stale
