### ISSUE TITLE
Add ability to change rights / license type through API

### ISSUE THREAD

**Issue by darksinge** [hydroshare/hydroshare#2710]
Currently, the API can only update the rights/license statement, but not the URL.

Features built into data.wikiwatershed.org (formerly data.envirodiy.org) allow users to share their data with hydroshare.org, which in turn creates a Composite Resource. Users of data.wikiwatershed.org agree the data they create will be shared using the *Creative Commons Attribution Share Alike License* (CC-By-SA). However, when data.wikiwatershed.org consumes hydroshare's API to create a resource, the license type is defaulted to *Create Commons Attribution* (CC-BY). 

It is a small technicality, but we need resources created using data.wikiwatershed.org to use the same license our user's agreed to on our website. There is no way to update this for our users.
@horsburgh

**Comment by sblack-usu** [comment]
#4390 enables the API to modify the rights url.
