### ISSUE TITLE
Connections with the Pangeo project

### ISSUE THREAD

**Issue by jhamman** [hydroshare/hydroshare#2714]
*This issue is meant to provide a broader context to a few follow-on issues.*

@dtarb and I have had a few conversations following EGU and would like to explore where the Hydroshare and Pangeo projects might overlap and where we might be able to find some opportunities to collaborate. We mostly focused on the Jupyter workflow in Hydroshare (launch, run, save). Here are a few topics that may be of interest. 

- **JupyterHub**: Deploying and managing community Jupyter environments on HPC and cloud resources
  - Tools for deploying JupyterHub instances on cloud resources, see https://github.com/pangeo-data/helm-chart for more information on this effort
  - Methods for deploying JupyterHub on JetStream and HPC resources like NCAR's Cheyenne
  - User workspace customization: best practices for providing users with flexibility in user workspaces, e.g. https://github.com/pangeo-data/pangeo/issues/67 
- **BinderHub**: Tech for managing the deployment of specific jupyter resources (notebooks/environments)
  - This is getting at the deployment of notebooks from hydroshare. Specifically, binder may offer the extended ability (relative to the current workflow in hydroshare) to 1) automatically load notebooks, and 2) specification of user environments. 
  - The conversation starting [here](https://github.com/pangeo-data/pangeo/issues/16#issuecomment-348341366) may be of most interest 
- **Notebook publishing**: It should be easier to publish jupyter notebooks. Currently, the hydroshare approach is functional but not optimal since it requires a fair bit of boilerplate within the notebook. I've suggested to @dtarb that hydroshare engage with the jupyter team to scope the development of a jupyter native feature to this end. In my mind, saving/publishing to github/anaconda/hydroshare/etc should be quite doable.

For those unfamiliar with Pangeo:
- Pangeo is a community effort for big data geoscience: https://pangeo-data.github.io/
- We have a github page where we communicate: https://github.com/pangeo-data/pangeo/issues
- We have a beta-level JupyterHub running on Google Cloud Platform: http://pangeo.pydata.org
  - There are some special things about this jhub, particularly that it uses Kubernetes and dask to enable scalability both in terms of the number of users but also the size of the computational pool.

 
cc @Castronova @dtarb @rabernat

**Comment by Castronova** [comment]
Thanks for starting this dialog @jhamman! This is my first time seeing BinderHub but at first glance, it looks like it would be a great addition to our current implementation.  Also, we’ve been thinking quite a bit about ways to customize individual user spaces as well as how we can streamline the overall notebook workflow.  I’m happy to share my thoughts with you and I’d love to hear what you think, in addition, this might help us identify collaboration opportunities.

Tony

**Comment by horsburgh** [comment]
@Castronova - I saw a presentation at EGU from a guy that was using Binder with R and GitHub to create interactive Jupyter environments. I was going to pass the info about Binder along, but sounds like the cat is out of the bag. It looks really cool!

**Comment by jhamman** [comment]
@Castronova - a few thoughts after letting this sit for a while:

- My understanding is that binder is most easily configured to run in conjunction with notebooks and environment files stored in a git repository of some kind. It may be possible to have binder point to resources in the storage layer you have in hydroshare but this would likely require building a custom interface of some sort. Perhaps a longer-arc idea would be to use git to manage the versioning of resources in hydroshare...
- I want to push you to consider the concept of environment specifications to manage notebook dependencies. As you probably know, they really help with the problems of reproducibility and portability. When a notebook is launched from hydroshare, it should also have the functionality to automatically start in a custom environment. Does this make sense?
- Publishing notebooks from binder/jupyterhub is something that is on our radar. Do you have development time/resources slated to work on this? This may be the right place to begin a collaboration between our projects.

**Comment by aphelionz** [comment]
@horsburgh @Castronova @dtarb what is the status of this?

**Comment by dtarb** [comment]
This is still an ongoing discussion.

**Comment by dtarb** [comment]
This is inactive.  Closing.
