### ISSUE TITLE
Refts simplify creation

### ISSUE THREAD

**Issue by jsadler2** [hydroshare/hydroshare#272]
No more "search buttons"
No more "rest/soap dropdown"

**Comment by dtarb** [comment]
@danames can you please test this in HydroShare 1.5 release candidate on alpha.hydroshare.org, and if agreed close.

**Comment by danames** [comment]
alpha.hydroshare.org won't load this morning.

**Comment by mjstealey** [comment]
Deferred to later release cycle

**Comment by zhiyuli** [comment]
closed. tested on 1.5.3 release candidate
