### ISSUE TITLE
Read hydroshare-yaml into settings.py

### ISSUE THREAD

**Issue by aphelionz** [hydroshare/hydroshare#2721]
We currently have a complex system of configuration management that involves the parsing of a yaml file, the generation of another, and then ingestion into two (2) different python settings files. This leads to duplicate keys, as well as mismanagement.

In the long run, I think we want to shoot for @cbcunc 's proposal of encrypted config files (hopefully ONE encrypted config file) checked into source. My proposal for a quick fix is to write some code inside settings.py that parses the YAML. and creates settings.py keys to at least solve the duplicate problem.

Open to suggestions.

**Comment by phuongdm** [comment]
That's very wonderful if we can do that. So, there is only hydroshare-config.yaml needs to be changed in every deployment. 

Can we split YAML file into several sections like:

`
\#\#\# start - system config \#\#\#
HS_DATABASE: pg.deploy.sql
\#\#\# end - system config \#\#\#
 
\#\#\# start - local_settings.py config \#\#\#
HS_WWW_IRODS_ZONE: 'hydroshareZone' 
\#\#\# end - local_settings.py config \#\#\#

\#\#\# start - settings.py config \#\#\#
SOLR_PORT: '8983'
\#\#\# end - settings.py config \#\#\#

`

**Comment by phuongdm** [comment]
Have no time to think about this :( Please move it to the next sprint. Thanks!

**Comment by aphelionz** [comment]
@phuongdm I will take this

**Comment by aphelionz** [comment]
Please see PR #2869 

I have added these in local_settings.EXTERNAL_CONFIG
