### ISSUE TITLE
Enable streaming download in REST API

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#2725]
@dtarb @martinseul @aphelionz 
The current REST API does not support streaming download and it had to be disabled in the newest PR #2718 for streaming download. To see how it should work, see 
[this stackoverflow post](https://stackoverflow.com/questions/16694907/how-to-download-large-file-in-python-with-requests-py). This seems to be a relatively straightforward fix to hs_restclient.

**Comment by alvacouch** [comment]
@dtarb @martinseul @aphelionz @Castronova 
Note that the dynamics of this solution are currently entirely handled within NGINX. The browser/client sets an HTTP header that indicates that streaming is desirable. When it sees that header, NGINX then provides streaming. Otherwise it doesn't provide streaming. Thus, in principle, the current REST client should work fine with the new solution, because if the client doesn't set the streaming header, then NGINX will respond normally. 

Thus, from this evidence, I think I can safely enable REST streaming on the server side without breaking hs_restclient in its current form.  We should test this, though!

**Comment by aphelionz** [comment]
@Alva, I have assigned this a 2 for medium effort - correct me if I'm wrong

**Comment by dtarb** [comment]
Large file download in 1.16 addresses or works around this.
