### ISSUE TITLE
Time Series Resource: ProcessingLevelCode should be a string and not an integer

### ISSUE THREAD

**Issue by horsburgh** [hydroshare/hydroshare#2727]
In testing with an ODM2 SQLite database from a user, we discovered that HydroShare's time series functionality is interpreting the ProcessingLevelCode field in the ODM2 database as an Integer when it should be interpreting it as a string. Need to modify the validation code to accept strings.

**Comment by pkdash** [comment]
@horsburgh I think this can be closed.

**Comment by horsburgh** [comment]
Just tested and verified on production. This has been fixed.
