### ISSUE TITLE
New Resource Creation: Tell user that "composite" is the preferred type

### ISSUE THREAD

**Issue by danames** [hydroshare/hydroshare#2728]
When a new user creates a new resource, the first thing they see is a dropdown to pick the resource type. I'm uploading a PowerPoint. There is no type "PowerPoint". How am I supposed to know that "Composite" is the right answer to this dropdown? I suggest we either 

1) Rename "Composite" in that dropdown to "File(s)" so that it is clear this is just a catch all for files. 

OR

2) Add some explanatory text: "Composite really means any file you have that you want to store in HydroShare and by the way, if it is a certain type that we know about we will add metadata, but don't worry because composite can hold anything. So just go ahead and choose Composite if you don't know any better. And by the way, even though we are engineers, this use of the term composite has nothing to do with concrete."

I think option 1 would be better.

**Comment by danames** [comment]
And by the way, why can't I add labels to my issues???

**Comment by horsburgh** [comment]
Once we’ve thoroughly tested the new composite resource functionality and it’s released, I suggest that we remove most of the resource types from the list. We shouldn’t call new resources “composite resources” but we still need to differentiate that resource type from the modeling resource types that will remain.

**Comment by hyi** [comment]
@horsburgh Another consideration is to make sure web app tool resource supports file aggregation type for launching apps before we can remove other resource types and use composite resource type as a replacement.

**Comment by horsburgh** [comment]
Also - @danames I just discovered/remembered that if you click on the pull down and hover over each of the resource types, there is pop-up text describing each resource type.

**Comment by aphelionz** [comment]
I believe this is addressed in this PR: mark deprecated resource types and block their creation throu… #2894

**Comment by Lizabrazil** [comment]
Closing this, as terms will change with the migration
