### ISSUE TITLE
New Resource Creation: Can't set spatial or temporal coverage information for PPT/composite

### ISSUE THREAD

**Issue by danames** [hydroshare/hydroshare#2730]
I just uploaded my PPT as a "composite" resource and went into edit mode and am unable to change the spatial or temporal coverage information. Perhaps this is by design to not allow this for PPTs? Suggest the following:

1) Remove display of spatial and temporal coverage for non spatial data types

OR 

2) Allow the user to edit these fields (i.e. my PPT may be related to a case study in a certain location, so it would be good to be able to change the spatial coverage. Likewise, it was presented on a certain date so let me set the temporal coverage.)

I suggest the latter option.

**Comment by horsburgh** [comment]
@danames - this will be addressed by enabling editing of the coverage in phase 2 of composite resource functionality. I believe @pkdash already has this fixed and just deployed it for testing on Park.

**Comment by dtarb** [comment]
This will be addressed in composite resource PR that is under review.  You will be able to edit resource level coverage information as well as set coverage information for files #2577.  Closing this as an issue.  Reopen if needed.
