### ISSUE TITLE
New Resource Creation: What do the asterisks mean on spatial and temporal coverage params?

### ISSUE THREAD

**Issue by danames** [hydroshare/hydroshare#2731]
Generally when you put an asterisk on an item in a form or a page or a book or document, it indicates that somewhere else in the page - usually near the bottom - there is another asterisk with an explanation of what the asterisk means. However hear on the "edit resource" page we see asterisks by the spatial and temporal coverage parameters but no explanation of these asterisks anywhere else on the page. Suggest the following:

1) Remove the asterisks from these parameters

OR 

2) Add some text nearby that explains what the asterisks mean. Perhaps it means, "You cannot edit these fields." See Issue #2730 

I suggest the first option.

**Comment by horsburgh** [comment]
Asterisks on fields on web forms typically mean that a field is required and must be filled in.

**Comment by danames** [comment]
Exactly, yet in this case the asterisk is only on the fields that can't be edited. So... something needs to be modified I guess. Maybe the asterisks mean "Hong is working on this as part of phase 2 of the composite resource deployment, please be patient and come back in the future and edit these fields."

**Comment by horsburgh** [comment]
Ha ha - you can try this out on park.hydroshare.org right now if you want. It's fixed. I tested it this morning.  Now you can either set the coverage yourself by entering values, clicking on the map, or by clicking a button to set the coverage from the extent of the data in the resource.

**Comment by danames** [comment]
OK I tested this on Park and was able to edit the spatial and temporal coverage. However, I still think that the asterisks need to be removed because a) they aren't described anywhere and b) these aren't required fields.

**Comment by horsburgh** [comment]
@danames - I'm giving this one to @Maurier.

Mauriel - let's just remove the asterisks next to the spatial and temporal coverage. They are not required, so the asterisks should not be there.

**Comment by Maurier** [comment]
@danames These changes, as discussed here, have been implemented and deployed to www. Closing...
