### ISSUE TITLE
Make subject keywords hyperlinks to direct discovery search based on that term

### ISSUE THREAD

**Issue by danames** [hydroshare/hydroshare#2732]
When viewing a resource, it would be expected and useful behavior to be able to click on a Subject term/keyword and automatically load a search results page for resources that have that term. My use case is: I just created my AWRA GIS and Water Resources 2018 PPT resource. We are asking all of the attendees from the conference to do the same. We are asking them to tag their resources with AWRA2018. When looking at one resource with this tab, my natural inclination is to click the "AWRA2018" keyword and have the system show me all other resources that use this same tag.

Here is my resource: https://www.hydroshare.org/resource/f9f530c514624a118fbd94624be02c61/

When clicking the AWRA2018 keyword, here is the search page that should load: https://www.hydroshare.org/search/?q=awra2018&NElat=&NElng=&SWlat=&SWlng=&start_date=&end_date=&sort_order=title&sort_direction=

**Comment by engineSound** [comment]
Fix has been in production. PR #2850
