### ISSUE TITLE
deletion race condition corrupts Django

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#2734]
@dtarb @martinseul @aphelionz @phuongdm 
It has recently come to my attention that HydroShare is having severe problems with deleting resources. When a resource is deleted and the browser is reloaded before confirmation, the irods component of the resource gets deleted, while the Django component -- that takes much longer to complete -- is not deleted. 

Thus the resource "remains" but doesn't really exist, sort of a hydroshare version of a "zombie" -- looks like it's alive but is really dead. Attempts to view the resource show no files, but attempts to download the resource bag crash. 

There are two parallel fixes required to deal with this: 

1.   Improve the speed of deletion of the Django object. The deletion code is really inefficient and can be sped up by an order of magnitude -- at least. 
2.  Background the django deletion. While the iRODS deletion of the whole resource is virtually instant, the django deletion takes longer. But once the irods files are gone, the Django deletion should not be interrupted.

**Comment by cuahsimarko** [comment]
@engineSound This seems pretty straightforward. I'll try to reproduce.

**Comment by martinseul** [comment]
@Alva this is part of async framework, closing this please reopen if needed
