### ISSUE TITLE
P2 Composite Res: Enable Discovery by Content Type rather than Resource Type

### ISSUE THREAD

**Issue by horsburgh** [hydroshare/hydroshare#2738]
With the development of Phase 2 of the composite resource functionality, we are essentially collapsing several resource types into one (the new composite resource). We have been enabling discovery by resource type before, but this won't work to help users discover a composite resource that contains content of a particular type. So, we need discovery to catalog information about the types of content (aggregations) contained within resources so when people search by content type they should discover resources containing that content type. Discovery should be based on content type, rather than resource type.

Cataloging of content types should be automatic - e.g., a user who creates a resource should not have to tag it with content-type keywords or otherwise. They have gone through the trouble of creating the content, HydroShare should be able to detect content types within resources.

@alvacouch - I'm assigning this one to you, but after review, others may need to help.

**Comment by danames** [comment]
+1

**Comment by alvacouch** [comment]
Merged into Composite Resource phase 2.

**Comment by horsburgh** [comment]
This has been deployed to www. There is now a "Filter by content type" facet on the left hand side of the discover page. It does seem to work with both content type and resource type. Closing.
