### ISSUE TITLE
CUAHSI Branding Updates

### ISSUE THREAD

**Issue by aphelionz** [hydroshare/hydroshare#2745]
Creating a retroactive ticket to encapuslate the work done in this PR: https://github.com/hydroshare/hydroshare/pull/2683

**Comment by Lizabrazil** [comment]
@dtarb Jon Pollak and I made some improvements to strengthen the CUAHSI brand on the HydroShare homepage. If you see anything wrong with the homepage then let us know. These changes included things like, adding our logo, linking back to the CUAHSI site, etc.

**Comment by dtarb** [comment]
I am only seeing small subtle changes in the footer, which I am OK with, but it seems like the link back to CUAHSI that is in the operational site footer is not in the playground footer.  I am OK if that is what you want.

**Comment by dtarb** [comment]
Done in 1.15.5
