### ISSUE TITLE
HydroShare GIS Add Local File not working for Shapefiles

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#2746]
I created a HydroShare GIS Map Project saved in https://www.hydroshare.org/resource/c5ea17e850c64b34a93fb778e03a0222/
 I loaded a shapefile using the Add Local File Button.  I selected all parts of the shapefile to add.
The current layers list then showed each file individually and did not recognize this as a single shapefile entity to display.
I then tried loading the parts of the shapefile as a zip file, but the zip file was not opened and displayed on the map.  It appears in the Current Layers as a zipfile.

**Comment by aphelionz** [comment]
This issue was moved to CUAHSI-APPS/tethysapp-hydroshare_gis#24
