### ISSUE TITLE
Quota message incorrect 

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#2747]
Following is the over quota message that I get when I push to go over quota (as a test).
Note that the contact email address should be help@cuahsi.org.  The help page mentioned should be https://help.hydroshare.org/about-hydroshare/policies/quota/ and should be a link.  There should be space between numbers and units.  This message appears when I log in, so the words "Your action to add content ..." do not make sense.  Please refer to earlier guidance on these messages to get these right.
![image](https://user-images.githubusercontent.com/3456833/39946155-51051e7c-552a-11e8-9ca3-2232d1a8469f.png)

Note that I also did not get this message in email (yet).  I understood that over quota email messages were supposed to be sent.

**Comment by aphelionz** [comment]
@hyi Can you look into the nightly quota emails on prod?

**Comment by hyi** [comment]
@aphelionz The quota email content is retrieved from quota field setup from admin panel, so I think if you go to admin and edit the quota content, the email should reflect the updated quota content.

**Comment by dtarb** [comment]
Closing.  I think we are OK for now
