### ISSUE TITLE
Quota use does not reflect all resources - suspected omission of files in iRODS user zone from total.

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#2748]
I noticed that my demo account (David Tarboton, but user name demo) was reporting only a small percentage of the 20 GB quota used, yet it contained a resource with an 8 GB file.

I made a copy of this resource, increasing usage to more than 16 GB, and this still did not reflect in my quota total.  The suspected reason is that these resources were created copying files from iRODS.

I then created a resource and added a file from disk, so it should be in the iRODS hydroshare zone.  I then added big files to this resource and made copies.  The total storage use reported when I log in now reports a total close to only the new big resources I created, and not the prior existing big resources.

**Comment by phuongdm** [comment]
@hyi ,
I've checked AVU value of demo-usage:
- 47521599850 on hydroshareZone
- 19637089211 on hydroshareuserZone
they seem OK in iRODS, could you check these value on Django?

**Comment by hyi** [comment]
@phuongdm used quota value for demo is 44.2579387221GB. I checked the code, and update_quota_usage does get called when a file is added from iRODS, so I am not sure what caused the out-of-sync issue between quota usage in Django and in iRODS. In any case, when a add file operation happens, the updated quota usage from iRODS will get populated into Django. @dtarb Can you create a new resource with files using this demo account and see if quota is up to date with iRODS after doing so?

**Comment by dtarb** [comment]
I deleted the 3 big resources.  I then created a new resource to which I added a file.  The quota message now says 
![image](https://user-images.githubusercontent.com/3456833/40022560-9b5e9a22-5785-11e8-8f51-7a7e7cdb357e.png) which is incorrect because I have this resource https://www.hydroshare.org/resource/d0e6d4c7f7ef4d9d9486be87fc425314/ with an 8 GB file in it.

**Comment by phuongdm** [comment]
@hyi,

it seems that, your quota function does not count user usage on hydroshareuserZone

@dtarb ,

I've check your resource: https://www.hydroshare.org/resource/d0e6d4c7f7ef4d9d9486be87fc425314/ its exactly size is 19636679744 (around 18.2 GB).

**Comment by hyi** [comment]
@dtarb @phuongdm I can reproduce this issue and indeed files added from user zone somehow are not counted toward the quota. Not sure what could have caused it and whether it has anything to do with zero down deployment process that was used for the last release deployment. I am sure it worked before and somehow it does not work in the new deployment. Will investigate and see what has caused this regression.

**Comment by hyi** [comment]
@dtarb @phuongdm @aphelionz I have found what have caused this issue and will make a hotfix today.

**Comment by hyi** [comment]
@dtarb Beta has been updated to include the hotfix I made, and I have just checked on beta and verified now files added from the user zone is counted toward the user's quota now. If you have time, it'd be great if you can verify on beta as well to make sure it indeed works now. Make sure you use hydroshareuserdevZone and usersdev.hydroshare.org to test things out since that is the user zone hooked up on beta.
