### ISSUE TITLE
Add progress indicator when creating a new resource with large files

### ISSUE THREAD

**Issue by Lizabrazil** [hydroshare/hydroshare#2751]
.98GB takes 5-10 minutes to upload. We need to provide feedback to the user that it is going to take this long due to the size. Most users assume it wont work after several minutes and give up. @mark

**Comment by dtarb** [comment]
I am changing this to Add progress indicator when creating a new resource with large files.  I do not think we can improve easily on upload times.

For what it is worth uploading a 0.43 GB file to Google takes 5 min, so we are not too bad.   Google indicates progress as follows

![image](https://user-images.githubusercontent.com/3456833/40615009-436eb23a-6242-11e8-9233-860c6a7a4e84.png)

In HydroShare if a new resource is created there is no indicator of progress uploading files, but if files are added to an existing resource HydroShare gives the following progress indicator
![image](https://user-images.githubusercontent.com/3456833/40615174-e76bb43c-6242-11e8-96b3-7af5380cb451.png)

**Comment by cuahsimarko** [comment]
Let's consider having progress indicators for uploads.

**Comment by dtarb** [comment]
We do have progress indicators for file uploads
![image](https://user-images.githubusercontent.com/3456833/56870785-f4f09680-69d1-11e9-8c7e-37e832c94513.png)

With #3242 the create page will be bypassed and all files will need to be uploaded via the interface that has this progress bar.  

I think this can be closed.

**Comment by Lizabrazil** [comment]
@dtarb There are no progress indicators on the Create Resource page which was what this issue was originally for but since we are taking away that page then we do not need to worry about this.
