### ISSUE TITLE
Create SciDAS evaluation version for HydroShare

### ISSUE THREAD

**Issue by clarisca** [hydroshare/hydroshare#2753]
Create RENCI-hosted deployment of SciDAS for evaluation by the HydroShare team.

**Comment by clarisca** [comment]
@Castronova @dtarb : 
We are deploying a SciDAS evaluation version for HydroShare. 
I am thinking in using the Workshop that you all held in May with ~40 students as a use case for this environment. 

Therefore, it would be helpful to know what kind of resources were needed and how much. Do you have this information?

**Comment by aphelionz** [comment]
@dtarb @Castronova what is the status of this?

**Comment by Castronova** [comment]
I need to follow up on this.

**Comment by dtarb** [comment]
It would be good to get an update sometime from @clarisca on the status of SciDAS work.

**Comment by dtarb** [comment]
Stale - closing.
