### ISSUE TITLE
Add are you sure check when deleting extended metadata

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#2756]
The delete extended metadata button for a resource should have a "Confirm to Delete Key/Value Metadata" prompt before deleting, consistent with deleting other metadata.

This was discovered while testing #2733 where I found that when deleting Key/Value Metadata associated with a file type, there is a check, but when deleting Key/Value metadata at the resource level there is no check.
![image](https://user-images.githubusercontent.com/3456833/40377416-1e579eb4-5dae-11e8-838a-642362a32fd5.png)

![image](https://user-images.githubusercontent.com/3456833/40377560-6a84f426-5dae-11e8-9070-381a53257be5.png)

**Comment by aphelionz** [comment]
@pkdash @Maurier Can you give me a quick briefing on where all this code lives? I'm looking through and there's a lot of dynamic JS, a lot of HTML being rendered in the JS, and a lot of disparate functionality in different files. I'm happy to fix it but I think it would go a lot faster if I had some quick guidance.

**Comment by engineSound** [comment]
The deletion action was done in a javascript via ajax which is clear and good. I have looked at the confirmation dialog code for file metadata deletion. The html code was generated in a python file which was challenging to tear apart for reuse.

**Comment by engineSound** [comment]
I am on my way to fix this. Another thought came up to @dtarb

@dtarb While maintaining consistency is great. I would like to know if this behavior is intended for the purpose of fast deletion. Is there a specification or style guide. If there is none, we need to have one so that we know what is expected behavior and what isn't.

**Comment by dtarb** [comment]
I am not aware of a style guide for this.  There is a balance to strike in avoiding a one click deletion that can result from an errant click in the wrong place, versus having to have the user respond "confirm" too many times.  I think there would be value in you reviewing all the places in HydroShare where we have confirms for deletes, and where we do not and then deciding in an objective way.  Perhaps we need a principle that nothing should be deleted irreversibly by a single click, and use that to guide us.

In writing this issue I was pointing out that for exactly the same thing "deleting extended metadata" we were requiring a confirm in one place and not the other.  For consistency both should be handled the same, and I think both should require a confirm.  If you want to broaden the question to other things, that is more work.

**Comment by engineSound** [comment]
@dtarb Got it. Thanks.

**Comment by martinseul** [comment]
close - fixed as part of  https://github.com/hydroshare/hydroshare/pull/3369
