### ISSUE TITLE
Quota does not count a resource that is copied.

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#2759]
I have a quota use reported of 18 GB.  Included in this is a 15 GB resource https://www.hydroshare.org/resource/50b977461a1c4d4392bc07b2c8e9cc4e/.  I made a copy of this resource (https://www.hydroshare.org/resource/0860e585772542e3929de88e0af35aa6/) and waited a day to give the quota system time to add things up, but my quota use is still reported as 18 GB.

**Comment by phuongdm** [comment]
@dtarb 

I've did some tests and my quota usage was increased. @hyi also said she did test before and it worked. Could you please test again? 

Thanks

**Comment by dtarb** [comment]
See #2970.  I created a resource by moving a file from iRODS.  It does not appear to count against my quota.

**Comment by hyi** [comment]
@dtarb If you move a file from iRODS, your quota will not change since your old file in your user space also counts toward your quota. You should see your quota increases if you choose copy option (rather than move option).

**Comment by hyi** [comment]
@dtarb I believe this issue can be closed as well especially given that we removed the option of copy or move as a result of removing the functionality to create a resource in user zone.

**Comment by dtarb** [comment]
Correct
