### ISSUE TITLE
API Subject Keyword search doesn't work

### ISSUE THREAD

**Issue by danames** [hydroshare/hydroshare#2760]
We can't seem to get the API to work to discover via keyword as per the documentation in ReadTheDocs http://hs-restclient.readthedocs.io/en/latest/

Here's the example provided in the documentation that doesn't seem to work:

`>>> from hs_restclient import HydroShare, HydroShareAuthBasic
>>> auth = HydroShareAuthBasic(username='myusername', password='mypassword')
>>> hs = HydroShare(auth=auth)
>>> result = hs.resources(subject="comma,separated,list,of,subjects")`

**Comment by cuahsimarko** [comment]
@danames An example of using subject keyword from an API client working today is:

https://www.hydroshare.org/discoverapi/?filter={%22subject%22:[%22mmw%22]}

Happy to do a walkthrough, otherwise may be self-evident. Note the outer parts of the response, which contain items like "rescount", the number of results. If the API clients are unable to consume such RESTful resources, let me know and we can discuss another solution.

**Comment by danames** [comment]
Thanks @cuahsimarko. Just verified your URL requests with some other keywords and works for public/discoverable resources as expected.

**Comment by danames** [comment]
Also for completeness, I tested this subject search with the hs_restclient and am able to return resources by subject keyword successfully for both private and discoverable resources:

from hs_restclient import HydroShare, HydroShareAuthBasic
auth = HydroShareAuthBasic(username='myname', password='mypassword')
hs = HydroShare(auth=auth)
result = hs.resources(subject="keywords,separated,by,commas")
for resource in result:
     print(resource)

**Comment by danames** [comment]
Closing this issue as keyword/subject search via API and hs_restclient appears to work fine now.

**Comment by danames** [comment]
Note from @alvacouch  that this method doesn't take advantage of SOLR.

**Comment by cuahsimarko** [comment]
@danames hs_restclient does not take advantage of SOLR? The API I've provided uses the same SOLR fields that prod Discover uses.

**Comment by sblack-usu** [comment]
hsapi has it's own implementation of search that queries the db directly.  I believe that was done to allow users to search their private resources as well.
