### ISSUE TITLE
P2 Composite Resource: Improve Semantics for Usability

### ISSUE THREAD

**Issue by horsburgh** [hydroshare/hydroshare#2762]
@sblack-usu and @pkdash - I assigned you both to this, but I suspect either one of you could do these changes. This is all in response to discussion and feedback received on the HydroShare call this week for completion as part of the 1.16 release.

We have received feedback from members of the team that the semantics of some of the user interface related to Phase 2 composite resource functionality needs to be simplified to improve usability. the following need to be done for the 1.16 Release:

On the right click context menu in the file browser:

* [x] Change "Set Generic Aggregation" to "Add metadata to file" with tool tip text "Add metadata to an individual file"
* [x] Change "Set Geographic Raster Aggregation" to "Convert to Geographic Raster" with tool tip text "Convert GeoTiff files to a geographic raster dataset to which you can add metadata."
* [x] Change "Set Multidimensional Aggregation" to "Convert to Multidimensional" with tool tip text "Convert NetCDF files to a multidimensional dataset to which you can add metadata."
* [x] Change "Set Geographic Feature Aggregation" to "Convert to Geographic Feature" with tool tip text "Convert a shapefile to a geographic feature dataset to which you can add metadata."
* [x] Change "Set Reference Timeseries Aggregation" to "Convert to Referenced Time Series" with tool tip "Convert to a referenced time series dataset with metadata."
* [x] Change "Set Timeseries Aggregation" to "Convert to Time Series" with tool tip text "Convert to a time series dataset to which you can add metadata."
* [x] Change "Remove Aggregation" to "Remove content type" with tool tip text "Remove the content type association and delete content-level metadata."

NOTE: When we add the file set aggregation functionality, the right click text for that should be "Add metadata to folder"
NOTE: Per Dan's comment - the user should rarely have to do this right click function. Rather the software should recognize "known file groups" and automatically treat them as such. This functionality has already been added by the auto-aggregation work to the Phase 2 composite implementation.

Also on the right click context menu, add the following 

In the hover text when you hover over a typed aggregation:
* [x] Change the hover text for each of the different content types to the following:
    * Single File Content: A single file with file specific metadata
    * Geographic Feature Content: The multiple files that are part of a geographic shapefile
    * Geographic Raster Content: A geographic grid represented by a virtual raster tile (.vrt) file and one or more geotiff (.tif) files
    * Multidimensional Content: A multidimensional dataset represented by a NetCDF file (.nc) and text file giving its NetCDF header content
    * Referenced Time Series Content: A reference to one or more time series served from HydroServers outside of HydroShare in WaterML format
    * Time Series Content: One or more time series held in an ODM2 format SQLite file and optional source comma separated (.csv) files

NOTE: When we add the file set aggregation functionality, the hover text should be "File Set Content: A folder containing multiple files and/or folders with specific metadata"

On the resource edit page for the Coverage element:
* [x] Add a text label under the main "Coverage" header that states the following: "Fill in the spatial and/or temporal coverage that bound the entirety of the data inside your resource. This will display on the map at right. If your resource is public, this will display on the Discover map for others to find. You can set the spatial and temporal coverage manually by filling in the inputs below or you can add content files to your resource that have spatial coverage information (e.g., geographic feature, geographic raster, multidimensional, etc.) and then click the button to set the coverage from the content files. 

On the "Aggregation Metadata" tab:
* [x] Change the name of the tab from "Aggregation Metadata" to "Content Metadata"
* [x] Change the text of the message that pops up from "Select an aggregation to see aggregation type metadata." to "Select content in the file browser to see metadata specific to that content. Metadata will only display here when the the content is selected above. Content specific metadata does not display on the Discover page."

**Comment by pkdash** [comment]
@horsburgh and @sblack-usu I will implement thes changes.

**Comment by pkdash** [comment]
@horsburgh Question related to tooltip for typed aggregation

> Single File Content: A single file with file specific metadata

Is the tooltip text in the above example be 'A single file with file specific metadata' or 'Single File Content: A single file with file specific metadata'?

**Comment by pkdash** [comment]
@horsburgh and @dtarb I plan to finish implementing these changes and deploy to park tonight. I assume this deployment has all the functionalities needed for composite resource for release 1.16.

**Comment by dtarb** [comment]
Thanks.  That would be great.

**Comment by sblack-usu** [comment]
I'm getting close to submitting a review for open with for aggregations.  I've got the functionality for opening apps per aggregation finished, just working on extending it to include file extensions and then writing tests.  After that, I think everything will be ready with composite resource for 1.16.

**Comment by horsburgh** [comment]
@pkdash - in answer to your question about the tool tip text - It should be the full text of what is in quotes:

Single File Content: A single file with file specific metadata

**Comment by pkdash** [comment]
@horsburgh Good. That's how I have implemented.

**Comment by rphooper** [comment]
@horsburgh Why use the term "Geographic Raster", "Multidimensional", or "Geographic Feature" rather than simply stating "GeoTIFF file", "NetCDF file" or "ESRI Shape File" directly rather than adding these as a tool tip. Is there any advantage of adding another layer of terminology? Any comments from @Lizabrazil or @dtarb ?

**Comment by horsburgh** [comment]
It's a good question. There is always the concept of a "type" of thing (e.g., a Geographic Raster) and a "format" for that thing (e.g., GeoTIFF file). But, I'm not really sure that distinction does much for a user because we have settled on a single format for each type. If we never intend for there to be anything but a 1:1 relationship between a type and format, then the importance of the "type" terms is somewhat diminished. However, there may be some people who do not know what a GeoTIFF file is.

These terms were essentially adopted from the original resource types.

**Comment by rphooper** [comment]
I understand the reasoning, but, if it is a 1:1 relationship, then I think the terminology overcomplicates an already complicated terminology.

A user who is going to publish a geographic raster must know what a GeoTIFF file is. A person searching for data may not know what a GeoTIFF file is, but _that_ is the concept to be explained in the tool tip. Maybe just inverting the text solves both problems. Lead from the file type and use the generic “type” of thing in the tool tip. Does that work?

**Comment by dtarb** [comment]
@rphooper I like the way @horsburgh has phrased the semantics.  Check out park.hydroshare.org to see this live and see if it perhaps works better for you.

Philosophically I think it is better to use plain language rather than jargon.  That is why I have been pushing for terms like "geographic raster" rather than "GeoTiff".  Also technically we are storing our rasters in the GDAL Virtual (.vrt) format.  "GDAL Virtual (.vrt)" is a "Long name" among many formats listed at http://www.gdal.org/formats_list.html.  GDAL is the authority when it comes to raster formats.  We chose this particular GDAL format so that large rasters can be made up of multiple GeoTIFF files, rather than just one.  When a single GeoTIFF file is converted to Geographic Raster format, the .vrt file is generated.  Multiple GeoTIFF files, with already existing associated .vrt file may also be added.

**Comment by sblack-usu** [comment]
@horsburgh - I'm testing beta right now and it looks like the coverage text label doesn't match this ticket.  [git blame](https://github.com/hydroshare/hydroshare/blame/develop/theme/templates/resource-landing-page/coverage.html#L134) shows the current message to be tied to this ticket... was the message decided to be different outside of this ticket?  
>On the resource edit page for the Coverage element:

>  Add a text label under the main "Coverage" header that states the following: "Fill in the spatial and/or temporal coverage that bound the entirety of the data inside your resource. This will display on the map at right. If your resource is public, this will display on the Discover map for others to find. You can set the spatial and temporal coverage manually by filling in the inputs below or you can add content files to your resource that have spatial coverage information (e.g., geographic feature, geographic raster, multidimensional, etc.) and then click the button to set the coverage from the content files.

**Comment by dtarb** [comment]
I think it is safe to assume that the current text was decided outside.  @horsburgh @pkdash and I did have a fair bit of email about this at that time.  In any event, reviewing the text on beta and the text above, I think the text on beta is better, so prefer not to change from what is there now.

**Comment by dtarb** [comment]
Done in 1.16
