### ISSUE TITLE
Resource Landing Page: Modify Related Resources

### ISSUE THREAD

**Issue by horsburgh** [hydroshare/hydroshare#2763]
Given feedback from users, some changes are needed on the Related Resources section of the resource landing page. Per issue #2810 the "Related Resources" tab will be removed and replaced with a "References" section on the page. 

The following additional changes are needed:

On the Edit page:
* [x] Under "Sources", add the following text label: 

>If the data in your resource was derived from another source or dataset, you can cite or acknowledge those references here. Click on "Add Source" and then add a full text citation to the original content, a web link, or text describing the source of the data.

* [x] Under "Relations", add the following text label: 

>If this resource is related to other documents, datasets, websites, etc., you can record those relationships here as references. For example, if this resource is cited by a paper you published, select a relationship type of "Data for" and then provide a full text citation for the paper that used the data, including the paper's DOI encoded as an HTTP URL if available. This records that this resource is the data for the paper that cited it. If you enter a URL as part of the citation, it will be converted to an active link.

On the "Add Relation" pop-up/modal form:
* [x] Change the text label "Relation type*" to "Type of relationship*"
* [x] Change the text label "Related to*" to "Full text citation, URL link for, or description of the related resource*"

On the display of the information in the new "References" section on the resource landing page:
* [x] Modify how the relationship type is displayed. The semantic terms like "isDataFor" are great for encoding in the XML metadata, but for display on the page, we need more intelligible terms. I suggest the following:
    * For "HostedBy" display the text "The content of this resource is hosted by:"
    * For "CopiedFrom" display the text "The content of this resource was copied from:"
    * For "PartOf" display the text "The content of this resource is part of:"
    * For "ExecutedBy" display the text "The content of this resource can be executed by:"
    * For "CreatedBy" display the text "The content of this resource was created by:"
    * For "DataFor" display the text "The content of this resource serves as the data for:"
    * For "Cites" display the text "This resource cites:"
    * For "DescribedBy" display the text "This resource is described by:"
    * For "IsReferencedBy" display the text "This resource is referenced by:"

@Lizabrazil - tagging you here because you described the confusion for users. These changes are meant to address the issues you described.

**Comment by Maurier** [comment]
These items have been implemented as part of the new resource landing page.

**Comment by horsburgh** [comment]
Implemented on www with 1.19 release. Here's an example. I like the new semantics:

![image](https://user-images.githubusercontent.com/3485902/53191206-75f17300-35c8-11e9-82d6-ea49cb40b015.png)

Spacing could probably be improved a little.

**Comment by Lizabrazil** [comment]
@horsburgh I like the new semantics and agree about the spacing but I don't think it fully solves the problem. When a user is in edit mode and they are selecting from the dropdown Types of relationships, they only see the short text options and do not know which to select. They can guess and then check but i think it might help to include some of this text during the selection. This is something we want to make really easy, so we can get those associated publications. 
![image](https://user-images.githubusercontent.com/13852599/53245390-91698600-367b-11e9-84fc-f496afa9e686.png)

**Comment by horsburgh** [comment]
@Maurier - Can we change the text in the "Type of relationship" dropdown to match the text that is displayed on the page? Also, while you are at it, can you fix the spacing? The display of multiple items puts them too close together. See my example above.

**Comment by Maurier** [comment]
@horsburgh - Sure thing!

**Comment by Maurier** [comment]
Change of text:
![image](https://user-images.githubusercontent.com/2448568/53257230-e068e880-3686-11e9-9e11-ee6513d77855.png)

@horsburgh Let me know if this works

Spacing:
![image](https://user-images.githubusercontent.com/2448568/53257288-fc6c8a00-3686-11e9-856b-eb243e8f7a07.png)

**Comment by horsburgh** [comment]
Yes. That looks good. @Lizabrazil - I'm assuming that this will meet our needs. All of what the user now sees should be human readable.

**Comment by Lizabrazil** [comment]
Thanks @Maurier @horsburgh  let's close this out and maybe continue discussion on what else we can do to make it explicitly clear which one should be used for associated journal publications. Maybe we just have a separate field for Cite the associated Journal Publication: _______
