### ISSUE TITLE
Can't update keywords/subjects through rest API

### ISSUE THREAD

**Issue by darksinge** [hydroshare/hydroshare#2773]
I'm trying to find a way to update resource keywords through the rest API. [This comment on another issue](https://github.com/hydroshare/hydroshare/issues/1599#issuecomment-262588374) made me think it's possible, but nothing I've tried has worked. 

This code snippet shows a bit of what I've tried:

```python
def updateKeywords(self, id, keywords):  # type: (str, [str]) -> object
    url = "{url_base}/resource/{id}/scimeta/elements/".format(url_base=self.url_base, id=id)

    r = self.request('PUT', url, json={'subjects': keywords})

    # Also tried: 
    # r = self.request('PUT', url, json={'keywords': keywords})
    # r = self.request('PUT', url, json={'subjects': [{"value": "keyword 1"}, {"value": "keyword 2"}]})

    if r.status_code != 202:
        raise HydroShareHTTPException((url, 'PUT', r.status_code, keywords))
    return r.json()
```
All three attempts to update the keywords (in the code snippet above) return a 202 response, but the keywords/subjects remain unchanged on the resource.

Can someone provide an example that works?

**Comment by sblack-usu** [comment]
@darksinge, sorry this took me a while to get to, I was taking some time off and recently got back in the office.

Using swagger (https://www.hydroshare.org/hsapi/), I was able to update keywords successfully,  Here is the generated curl statement.
```
curl -X PUT "https://www.hydroshare.org/hsapi/resource/82f7acf72b8e461886d37b637cbd4766/scimeta/elements/" -H "accept: application/json" -H "Content-Type: application/json" -H "X-CSRFToken: x2ODHmdqtm3GtgJnaTlngtOaRKfe0hmu" -d "{ \"subjects\": [{\"value\": \"key 1\"}, {\"value\": \"key 2\"}]}"
```

Looks like one of your attempts looks about right.
```
# r = self.request('PUT', url, json={'subjects': [{"value": "keyword 1"}, {"value": "keyword 2"}]})
```

You say you got a 202 response, could you share the response body? it should show the updated metadata.

**Comment by darksinge** [comment]
I tested this again today and was able to update the keywords. It turned out to be an issue using a request method from the `hs_restclient` library in an extension I've been working on. Thanks, and sorry for the trouble!
