### ISSUE TITLE
development testing broken due to federation-mode-testing code

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#2774]
@hyi @dtarb @martinseul @aphelionz 
The code: 

```
class TestUserZoneIRODSFederation(TestCaseCommonUtilities, TransactionTestCase):
    #....
    def setUp(self):
        super(TestUserZoneIRODSFederation, self).setUp()
        super(TestUserZoneIRODSFederation, self).assert_federated_irods_available()

```
crashes on my local dev environment, because `assert_federated_irods_available` only works for instances at RENCI. This also fails on `cuahsi-dev-1` and `cuahsi-dev-2`. These test cases should be skipped unless running on a RENCI host. 

`assert_federated_irods_available` is

```
    def assert_federated_irods_available(self):
        """assert federated iRODS is available before proceeding with federation-related tests."""
        self.assertTrue(settings.REMOTE_USE_IRODS and
                        settings.HS_USER_ZONE_HOST == 'users.local.org' and
                        settings.IRODS_HOST == 'data.local.org',
                        "irods docker containers are not set up properly for federation testing")
        self.irods_fed_storage = IrodsStorage('federated')
        self.irods_storage = IrodsStorage()
```
This can never succeed on a host using iRODS servers with different names and -- since it is invoked in setup and teardown -- registers as a testing error rather than a skip. 

These tests should be **skipped**.

**Comment by phuongdm** [comment]
@alvacouch 

iRODS servers for cuahsi-dev-1 and cuahsi-dev-2 is cuahsi-irods-1 and cuahsi-irods-2 and both were configured correctly, cuahsi-dev-2 is Federated of cuahsi-irods-1, not sure why your code got failed on these server?

**Comment by hyi** [comment]
@alvacouch @phuongdm The reason ```assert_federated_irods_available``` was written that way was that we expected that all iRODS federation-specific tests would only run using the two iRODS docker containers that were federated. This was how the iRODS tests have been run in sandbox triggered by Jenkins for all our PRs and commits. The main consideration for this is based on the assumption that we don't really use real iRODS servers for testing purposes but rather only use iRODS docker containers for easy cleanup without potentially polluting real iRODS servers.

**Comment by cuahsimarko** [comment]
@phuongdm Please comment or close, if you will...

**Comment by phuongdm** [comment]
Yes, it's wrong configuration problem, fixed
