### ISSUE TITLE
Replacing Celery Tasks with Jenkins + Django Management Scripts

### ISSUE THREAD

**Issue by aphelionz** [hydroshare/hydroshare#2776]
Celery is esoteric, opaque, and does not properly report errors in a the meaningful way that Jenkins does. There is also no UI available like Jenkins' that I am aware of.

I propose we replace the following tasks with a suite of Jenkins wrappers that simply call the appropriate management commands.

**./hs_core/tasks.py**
- [x] nightly_zips_cleanup
- [x] sync_email_subscriptions
- [x] manage_task_nightly

Note: removed all marked as `@shared_task`: `add_zip_file_contents_to_resource`, `delete_zip`, `create_temp_zip`, `update_quota_usage_task`

Skip **./hs_publication/tasks.py**, **./django_irods/tasks.py** for now.

**Comment by dtarb** [comment]
This sounds reasonable, but it would be good for @hyi to weigh in as I think she likely wrote many of the celery tasks.  The ones that run on a regular schedule (e.g. nightly) I see no problem with.  Some of these, however, may run on demand (e.g. create_bag_by_irods) and when this is being done a user is usually waiting for the bag to be downloaded.  Would doing this by Jenkins be just as effective?

**Comment by hyi** [comment]
@aphelionz As @dtarb mentioned above, on-demand celery tasks cannot be moved to jenkins. There are two on-demand celery tasks currently in use, one is on-demand bag creation for downloading, the other is update_quota_usage_task. These two celery tasks have to stay. The other nightly run tasks could be moved to Jenkins. The only potential downside I can see is that this would create the dependency on Jenkins server jobs, and it seems sometimes Jerkins jobs got queued up badly and did not run until much later than scheduled, so not sure whether Jenkins server would be overloaded with running all those testing as well as running production level tasks.

**Comment by cuahsimarko** [comment]
I would like to invest more into celery over time and revisit any former shortcomings. Celery should be used for tasks and other async operations until we are on Python 3.7.1 with asyncio, which is probably still a little in flux. 2019/2020 hopefully will be more mature and at that point team can evaluate if staying with Celery or moving to asyncio or using both is desirable.

**Comment by cuahsimarko** [comment]
I was on another team that used Jenkins exclusively for async python calls and I'm aware of all the potential issues. Celery is the way to go.
