### ISSUE TITLE
Eliminate case sensitivity of email addresses and usernames

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#2781]
If a user entered their email as e.g. DTAR@usu.edu but attempts to log in as dtar@usu.edu, login (and other email related functionality, such as changing a password) fails.  Eliminate case sensitivity in email addresses and user names.  However passwords should remain case sensitive.

**Comment by dtarb** [comment]
There is at least one case where case insensitivity will result in username clashes, namely Mladams1 vs mladams1.  We will need to disambiguate these.  Perhaps there are sufficiently few that we can handle on a case by case basis.  In this particular case they are the same person and one could likely be deleted.

**Comment by sblack-usu** [comment]
Code to find clashes in usernames and emails:
```
for u1 in User.objects.all():
  for u2 in User.objects.all():
    if u1 != (u2):
      if u1.email.lower() == u2.email.lower():
        print(u1.email + " " + u2.email)
      if u1.username.lower() == u2.username.lower():
        print(u1.username + " " + u2.username)
```
Results:
```
jeffrey.sadler2@gmail.com jeffrey.sadler2@gmail.com
jeffrey.sadler2@gmail.com jeffrey.sadler2@gmail.com
ns1@rcs.urz.tu-dresden.de ns1@rcs.urz.tu-dresden.de
ns1@rcs.urz.tu-dresden.de ns1@rcs.urz.tu-dresden.de
jeffrey.sadler2@gmail.com jeffrey.sadler2@gmail.com
jeffrey.sadler2@gmail.com jeffrey.sadler2@gmail.com
jeffrey.sadler2@gmail.com jeffrey.sadler2@gmail.com
jeffrey.sadler2@gmail.com jeffrey.sadler2@gmail.com
Jsun@streammethods.com jsun@streammethods.com
jsun@streammethods.com Jsun@streammethods.com
Dahal.prasanna@gmail.com dahal.prasanna@gmail.com
TonyTest tonytest
tonytest TonyTest
Bardia7 bardia7
muyang Muyang
Januka januka
januka Januka
bardia7 Bardia7
patrick PATRICK
patrick Patrick
erikab ErikaB
wrights1997@outlook.com Wrights1997@outlook.com
b6018310 B6018310
dahal.prasanna@gmail.com Dahal.prasanna@gmail.com
B6018310 b6018310
Muyang muyang
mladams1 Mladams1
Andrew andrew
Wrights1997@outlook.com wrights1997@outlook.com
andrew Andrew
PATRICK patrick
PATRICK Patrick
ErikaB erikab
treyton.m2@gmail.com Treyton.M2@gmail.com
Treyton.M2@gmail.com treyton.m2@gmail.com
Mladams1 mladams1
graciela Graciela
Plgreen plgreen
Graciela graciela
plgreen Plgreen
NehrkeSM@cdmsmith.com nehrkesm@cdmsmith.com
NehrkeSM@cdmsmith.com NehrkeSm@cdmsmith.com
nehrkesm@cdmsmith.com NehrkeSM@cdmsmith.com
nehrkesm@cdmsmith.com NehrkeSm@cdmsmith.com
Patrick patrick
Patrick PATRICK
NehrkeSm@cdmsmith.com NehrkeSM@cdmsmith.com
NehrkeSm@cdmsmith.com nehrkesm@cdmsmith.com
```

**Comment by sblack-usu** [comment]
Just so everyone is aware, the part of the email address before @ is by specification, case sensitive.  BUT, most email providers make the whole email case insensitive.  Along the same lines, popular sites that use email for usernames, ignore cases as well.  So, we're going ahead with ignoring case sensitivity in emails.

**Comment by sblack-usu** [comment]
We can roll this out in two deployments,  The first deployment will stop conflicting users from being created.  The first deployment will also use both the old and new backends, allowing existing conflicting users to still login as well as allowing users to login without case sensitivity.

The second deployment would remove the old backend (and remove an exception catch in the new backend).

Between deployments, we will clean up conflicting users.

**Comment by sblack-usu** [comment]
We have to remove the old authentication system in another deploy.

**Comment by sblack-usu** [comment]
I ran the check again and no clashes were found.

**Comment by sblack-usu** [comment]
I have been made aware that problems can occur with User Quota if a username is changed.  However, since the one user's username we updated did not have any resources, it will not cause problems.
