### ISSUE TITLE
Fix institution selection during account sign up

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#2784]
I just went through the process of creating an account in HydroShare.  I had the following experience.

I typed my institution as Utah, then in the drop down picked "Utah State University"  It did not stick, instead it showed me a red "Utah".  I then typed a few more letters "st" and tried again.  This time it showed me "Utah St".  At this point I just moved on and created the account.
![image](https://user-images.githubusercontent.com/3456833/41611851-5f5d23c8-73ae-11e8-8d26-c42b036caa08.png)

When I verified the email and got directed to the profile page I got the following that shows 3 institutions
![image](https://user-images.githubusercontent.com/3456833/41612019-dd7b2c96-73ae-11e8-9753-f373fd2cfe16.png)

We need to simplify this process of a user entering their institution or picking from a list to match.

**Comment by aphelionz** [comment]
Likely related to autocomplete. Will investigate

**Comment by aphelionz** [comment]
Part of this investigation should be an inspection of the organization metadata to look for susupicious dupilcates, i.e. USU <---> Utah State University

**Comment by sblack-usu** [comment]
You can turn off autocomplete for an input with  ```autocomplete="off"```

**Comment by cuahsimarko** [comment]
@dtarb are these related https://github.com/hydroshare/hydroshare/issues/2968

**Comment by dtarb** [comment]
Closing.  I am not able to reproduce at present and this may have been resolved by cleanups done on the institution list @sblack-usu worked on a while back.
