### ISSUE TITLE
"Create Resource" multi-click creates multiple resources

### ISSUE THREAD

**Issue by ndebuhr** [hydroshare/hydroshare#2785]
On the resource creation page, multiple clicks of the create resource button generates resource duplicates - for example double clicking button creates two resources.
[Testing Environment](https://github.com/hydroshare/hydroshare/files/2116987/180619_001_test-env.txt)
[Video](https://drive.google.com/file/d/12DofKW7pKy9OFv486SteES_3Ke0T3oUe/view?usp=sharing)

**Comment by engineSound** [comment]
Reproduced. The button can be clicked as many times as possible as the mouse is capable.

Two options: 1. disable the button once detect the first click. We may do this in other places as well like create New resource. 2. just use the first click to trigger backend call, ignoring the rest. 

Currently estimate it as small effort.

**Comment by aphelionz** [comment]
I vote option 1, thanks @engineSound

**Comment by engineSound** [comment]
I vote option 1 as well.

**Comment by engineSound** [comment]
Bootstrap has button.js that allows us to set loading state and disable the button at the same time. I have made some code in and the result was what I expected. I need to look into how to reset it when creating a resource fails, catching the edge cases.

**Comment by engineSound** [comment]
@Maurier 
I think this issue was fixed in the resource landing page redesign. I can prepare to close it when it is in production.

**Comment by Maurier** [comment]
@engineSound Correct.

**Comment by engineSound** [comment]
@Maurier Thanks. I will add this item to the back-tracking list.

**Comment by engineSound** [comment]
Verified on beta. Need to close this out after 1.19 is out.

**Comment by engineSound** [comment]
Verified in 1.19.
