### ISSUE TITLE
Resource page Author content is notably less responsive than the rest of the page

### ISSUE THREAD

**Issue by ndebuhr** [hydroshare/hydroshare#2786]
Authors is a noticeable step down in responsiveness for small width windows/screens
[Test Environment](https://github.com/hydroshare/hydroshare/files/2117004/180619_002_test-env.txt)
[Video](https://drive.google.com/file/d/1NqnfTkwIfrkoPgTSy8okbvZm_HDu9RX_/view?usp=sharing)

**Comment by cuahsimarko** [comment]
@engineSound please retest and close if no longer an issue

**Comment by engineSound** [comment]
In the current resource landing page, his issue is not applicable (N/A).
