### ISSUE TITLE
The character set for renaming a resource file is restrictive

### ISSUE THREAD

**Issue by ndebuhr** [hydroshare/hydroshare#2787]
Restrictive character set for file renaming within resource.  Error message is overwhelming.  File uploads do not impose the same filename restrictions - "über.txt" is fine for uploading, but not renaming.

[Test Environment](https://github.com/hydroshare/hydroshare/files/2117010/180619_003_test-env.txt)
[Video](https://drive.google.com/file/d/1G83TE1x4HvCvU5VHuQLk_zYwnOyMQ2YK/view?usp=sharing)

**Comment by dtarb** [comment]
See #2538 where I suggested limiting allowed characters in file names to be from a portable character set.

**Comment by martinseul** [comment]
closing fixed
