### ISSUE TITLE
Resource files with non-English characters cannot be downloaded or viewed

### ISSUE THREAD

**Issue by ndebuhr** [hydroshare/hydroshare#2788]
Files with non-English characters cannot be downloaded or viewed through the file URL.

[Test Environment](https://github.com/hydroshare/hydroshare/files/2117039/180619_004_test-env.txt)
[Video](https://drive.google.com/file/d/1i-ne95tke4kincaypmMPeMaxBrGQVbaX/view?usp=sharing)

**Comment by dtarb** [comment]
See #2538 where I suggested limiting allowed characters in file names to be from a portable character set.

**Comment by pkdash** [comment]
@alvacouch I am not able reproduce this issue locally. I created a file with filename containing non-english character. If I use that file on prod/beta I can see the issue. However, the same file I can download locally. One thing to note that locally I am not running nginx. I have not yet been able to run nginx locally. Do you think nginx may be causing this file download issue?

**Comment by martinseul** [comment]
in 1.48
