### ISSUE TITLE
No message to user when resource folder creation fails due to duplicate name

### ISSUE THREAD

**Issue by ndebuhr** [hydroshare/hydroshare#2790]
When creating a folder, no message is displayed to the user if the folder name already exists in the resource.  The user experience suggests the action was successful when in fact it did nothing.

[Test Environment](https://github.com/hydroshare/hydroshare/files/2117057/180619_006_test-env.txt)
[Video](https://drive.google.com/file/d/1WmWfyfJDYPUybnpPDDZGG7Yxp4iBo_nu/view?usp=sharing)

**Comment by engineSound** [comment]
@Maurier @pkdash While UI can make duplicate name check to alert user and prevent it from flowing into backend. But I do think this should be caught by the backend and error message should also be provided by backend. 

I am aware there is a balance to which place to seek an optimum solution. I appreciate if @pkdash can take a look and give some input.

**Comment by pkdash** [comment]
@engineSound I agree that the backend should check for duplicate folder. As currently implemented iRODS throws a SessionException if it finds duplicate folder and we then report that as 'INTERNAL SERVER ERROR. I think we need to check for duplicate folder name first (in the backend) then run the iRODS command to create the folder.

**Comment by engineSound** [comment]
@pkdash Do you want to put the issue in your bucket or you want reassign to some other backend colleagues?

**Comment by engineSound** [comment]
@cuahsimarko @mraocuahsi

**Comment by pkdash** [comment]
@engineSound I will to fix it this weekend. If I don't get time for it then someone else can work on it.

**Comment by pkdash** [comment]
@ndebuhr This issue can be closed.

**Comment by cuahsimarko** [comment]
@martinseul I think this can be closed

**Comment by martinseul** [comment]
close, fixed
