### ISSUE TITLE
Issues when a folder and a file have the same name within a resource

### ISSUE THREAD

**Issue by ndebuhr** [hydroshare/hydroshare#2791]
The error handling is not friendly when the user creates a folder with the same name as a file.

[Test Environment](https://github.com/hydroshare/hydroshare/files/2117059/180619_007_test-env.txt)
[Video](https://drive.google.com/file/d/13JLPVZkKp05bzkVbN6snu6_moNhgJiCG/view?usp=sharing)

**Comment by engineSound** [comment]
This is was fixed in the latest resource landing page.
![image](https://user-images.githubusercontent.com/35352595/56997629-6e28ee80-6b76-11e9-9844-18b7d4d78ccd.png)
