### ISSUE TITLE
Geo raster validation error message is missing spaces

### ISSUE THREAD

**Issue by ndebuhr** [hydroshare/hydroshare#2792]
Trying to use an improperly formatted file as a geographic raster results in a multi-sentence error message that is missing spaces.  "Geo raster file type file validation failed.File is not a zip file"

[Test Environment](https://github.com/hydroshare/hydroshare/files/2117068/180619_008_test-env.txt)
[Video](https://drive.google.com/file/d/1ouEm_XL7vJLzz2OUMPlO4YO06xH3867j/view?usp=sharing)

**Comment by engineSound** [comment]
###  Closing justification: 

> GUI design has changed in this regard. The pop up menu item no longer exists.
