### ISSUE TITLE
Composite Resource: Enable Adding and Managing Referenced File Content via the REST API

### ISSUE THREAD

**Issue by horsburgh** [hydroshare/hydroshare#2797]
Modify the REST API to handle adding referenced file content to a resource and managing it once it is there. 

* [x] Enable creation of a reference file (.url file) at any level in the resource's folder hierarchy. This should probably be done by accepting a URL as an input parameter, after which the API creates the .url file.
* [x] Enable deletion of a referenced file (should already exist since references will be stored in physical .url files that can be deleted using existing functions).
* [x] Enable listing of referenced files with the resource file list (should already work once .url files are implemented). .url files are physical files in the resource and will be listed by existing functionality.
* [x] Enable download of resource containing reference files (should already work since references will be encoded as .url files that can be downloaded as part of the resource)
* [x] Copy of resource containing referenced content (should exist already)
* [x] Version a resource containing referenced content (should exist already)

This list may not be inclusive of what will be required. Many of these should just work once the user interface functions for adding references to files as .url files in a resource are complete, but we need to verify that we can perform the adding, deleting, moving, etc. of referenced files via the API in the same way we can via the user interface.

**Comment by dtarb** [comment]
Is the ability to accept a URL as an input parameter in the API, really necessary.  Could this not be handled by the python client or client program just writing a .url file and uploading it.

**Comment by horsburgh** [comment]
We already have the capability to upload a file through the API. So, if someone wants to add a .url file to a resource, they can do it now.

For creating new referenced content through the API, we definitely want to have the URL as in input parameter. We have no guarantees that everyone interacting with the API will be doing so through the Python client, and I'm pretty convinced that nobody is gong to create .url files on their own. The API should accept the URL as an input parameter and create the .url file on the HydroShare side.

**Comment by sblack-usu** [comment]
Most of the acceptance criteria came free from url files just being like other files.  The extent of the work is just exposing @hyi work through hsapi and updating hs_restclient to use those methods creation and update.

**Comment by dtarb** [comment]
Deployed with 1.16.1 and tested from PASDA Scraper.  Thanks team.
