### ISSUE TITLE
Discover page info modal does not close when clicking outside the modal

### ISSUE THREAD

**Issue by ndebuhr** [hydroshare/hydroshare#2803]
The modal does not close when clicking in another part of the page.  There is also no "X" in the corner of the modal and it is regularly clipped (at least stylistically) by the top menu and general browser window.  Clicking the "i" button again does close the modal, but that could perhaps be unintuitive to some users who are used to the "clickout" or "x" closure approaches previously described.

[Video](https://drive.google.com/file/d/1jC4PwX15Icka_-b5HWdKQEVGJNP2VtQJ/view?usp=sharing)
[Test Environment](https://github.com/hydroshare/hydroshare/files/2146073/180628_001_test-env.txt)

**Comment by hydrocheck** [comment]
Issue resolved as a part of the Discover redesign
