### ISSUE TITLE
Redirect to HTTPS results in an empty subfolder in URL

### ISSUE THREAD

**Issue by ndebuhr** [hydroshare/hydroshare#2804]
When redirecting to HTTPS, an empty subfolder is added to the URL.  While this does not cause any obvious, immediate issues, it seems risky to leave odd url behavior like this.  While the video shows the homepage case, the same behavior arises for other pages (e.g. http://beta.hydroshare.org/search/ redirect to https://beta.hydroshare.org//search/).  The behavior is only seen in beta (as detailed in video) - no analogous behavior in production.

[Video](https://drive.google.com/file/d/1RrhWXvPxtd7-8bOYDYWg4JTeK9_-SXj3/view?usp=sharing)
[Test Environment](https://github.com/hydroshare/hydroshare/files/2146085/180628_002_test-env.txt)

**Comment by dtarb** [comment]
2 years later is no longer an issue.  Appears to have been fixed somewhere along the way.  Closing.
