### ISSUE TITLE
Long file names cause issues in list view of resource files

### ISSUE THREAD

**Issue by ndebuhr** [hydroshare/hydroshare#2805]
When long files are uploaded to a resource and then viewed in list mode, the table styling breaks down.  It seems like a "..." should bring the resource name down to a reasonable size.  Instead, the row cells become misformatted, having some content line break and shift horizontally.  The attached video should assist in understanding the problem, and you can skip to the end if you already have files to use in reproducing the bug.

[Video](https://drive.google.com/file/d/15D13tUb_oZ9qB71HRSWd79PkZ9lQ5Zvf/view?usp=sharing)
[Test Environment](https://github.com/hydroshare/hydroshare/files/2146092/180628_003_test-env.txt)

**Comment by mraocuahsi** [comment]
Not able to reproduce the error 

![Screenshot from 2019-05-06 13-22-21](https://user-images.githubusercontent.com/49655428/57243715-c5124600-7004-11e9-821f-e0c5a3c77ee4.png)

**Comment by Castronova** [comment]
This has been resolved.
