### ISSUE TITLE
Problems with label validation and presentation

### ISSUE THREAD

**Issue by ndebuhr** [hydroshare/hydroshare#2806]
- Long project tags which have no spaces or hyphens create nonideal formatting in sidebar
- Single space possible as label (this breaks styling on filter sidebar)
- Label processing eats all "<" and ">" symbols (related to next item).  Labels with these characters cannot be deleted by the user.
- HTML and JavaScript injection is possible for labels.  
- It is possible to create duplicate labels (e.g. two labels with exact same name "1").  This is the only bullet not detailed in the attached video, but hopefully is rather intuitive.

On a personal note, if someone could please clear my undeletable labels from the beta backend (those with "<" or ">" characters in them), that would be appreciated. 

[Video](https://drive.google.com/file/d/14XvkPdDbWpclye_UF3sCviCOZhzMEQGj/view?usp=sharing)
[Test Environment](https://github.com/hydroshare/hydroshare/files/2146098/180628_CUAHSI-QA_test-env.txt)

**Comment by cuahsimarko** [comment]
Interaction with beta moved to https://github.com/hydroshare/hydroshare/issues/3336

**Comment by engineSound** [comment]
Apparently this didn't pass the negative testing cases. In the report, it contains multiple issues all of which are related to the labeling. To address issue, it's better to start from functional requirement. What we support and what we don't support. For the cases we don't support, we should not allow them to add the label, for example the "<" tag.

**Comment by engineSound** [comment]
During testing, I found a long tag name that is constituted with multiple words is presented well. Freedom to let user enter HTML formatted texts got gobbled.

#### Actions to take:

- HTML injection should not be allowed
- Tag name should have a length limit 
- A tip showing the chopped off tag name is needed when presenting a long single word tag like ABCDEFGHIJKLMNOP
- A tag with only space(s) should not be allowed

**Comment by eclark-cuahsi** [comment]
@Castronova I believe this falls under Pages and General HS Components. Please review and relabel if needed.

**Comment by sblack-usu** [comment]
Some constraints are made to prevent html injection.  #3684

**Comment by martinseul** [comment]
@ndebuhr could you please retest this? Scott mentioned that the injection issue is fixed and assess if this is still a bug?

**Comment by devincowan** [comment]
My simple injection attempts were prevented:
![image](https://user-images.githubusercontent.com/17934193/157067414-e267e974-5558-400b-ac2a-4232cea819ed.png)
However LONG labels still create formatting issues and whitespace gives an error that doesn't make sense.
I will fix those...
