### ISSUE TITLE
Discover page should list author where author is an organization.

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#2809]
None appears for some resources below,
![image](https://user-images.githubusercontent.com/3456833/42118905-308c0578-7bc4-11e8-9794-94f331d4cfe1.png)

But the author is an organization
![image](https://user-images.githubusercontent.com/3456833/42118959-89c9550a-7bc4-11e8-8681-6af4d896d584.png)

**Comment by aphelionz** [comment]
Likewise resourcemetadata.xml

**Comment by horsburgh** [comment]
I checked some of our iUTAH resources today and the organization is listed as a creator in the resourcemetadata.xml.

Here's an example:

https://www.hydroshare.org/resource/9dea1ecec7ca4c33a4bdbe2b06391dd5/

**Comment by dtarb** [comment]
Has been fixed for a while now.
