### ISSUE TITLE
If user presses Enter, refts creation form can be submitted prematurly

### ISSUE THREAD

**Issue by jsadler2** [hydroshare/hydroshare#281]

**Comment by dtarb** [comment]
@danames Can you please test this and if it is working close.

**Comment by dtarb** [comment]
@danames can you please test this in HydroShare 1.5 release candidate on alpha.hydroshare.org, and if agreed close.

**Comment by mjstealey** [comment]
Deferred to later release cycle

**Comment by zhiyuli** [comment]
tested on alpha (1.5.3). closed
