### ISSUE TITLE
Resource Landing Page: Add Readme Functionality

### ISSUE THREAD

**Issue by horsburgh** [hydroshare/hydroshare#2812]
On the resource landing page, add the ability to automatically render a readme file directly on the page. If a user has uploaded a readme.txt file or a readme.md file, it should automatically be displayed in the readme area on the page. If no readme.txt or readme.md file exists, the readme viewer should not appear on the page. Only readme files in the root content directory will be supported.

The readme content area should be styled/treated the same as the file content area. It should have a minimum and maximum vertical height on the page, but should be draggable to make it larger and scrollable if the content doesn't fit within the maximum height.

If a readme.txt or readme.md file are present in the resource (even if it is only discoverable), the readme file should get rendered on the page.

If both a readme.txt and a readme.md file are uploaded to a resource, the default display will be readme.md.

Need to add the following text to the "Uploading" information box that shows up below the Content area in Edit Mode:  

>"If you upload a readme.txt or readme.md file at the root level in your resource, it will be rendered automatically on the page. Markdown formatting is allowed in readme.md. Learn more about Markdown."  

The text "Learn more about Markdown" should link to the following page: 

https://guides.github.com/features/mastering-markdown/#syntax

See the mockup of the page for what it should look like and the location on the page:

https://app.moqups.com/jeff.horsburgh@usu.edu/UNcFub9Dcj/view

**Comment by horsburgh** [comment]
This functionality will come with the resource landing page reorganization, so I added it to the 1.19 milestone.

**Comment by engineSound** [comment]
@horsburgh We should prepare to close this issue by the time 1.19 is released, or should we close it now? @Maurier is the actual owner of the task. I removed @engineSound and added @Maurier to the assignee to reflect the ownership.

**Comment by Maurier** [comment]
I think we should close it once the reorganization PR gets merged.

**Comment by horsburgh** [comment]
Agreed with @Maurier.

**Comment by horsburgh** [comment]
Live and functional on www. Closing this one, but see #3176, which is a new issue about rendering readme.txt.
