### ISSUE TITLE
User accounts becoming disassociated with their HydroShare account

### ISSUE THREAD

**Issue by aphelionz** [hydroshare/hydroshare#2816]
Recently there have been two incidents that involved a user trying to create an iRODS account and receiving an error that they cannot - investigation revealed that accounts already existed.

**Comment by hyi** [comment]
The fix to this issue has been deployed a couple of releases back. I am closing this issue for now. If this problem crops up again in the future, we can reopen this issue, but I believe it has been fixed, so closing.
