### ISSUE TITLE
Discover page "Sort By" and "Sort Direction" both clear filters

### ISSUE THREAD

**Issue by ndebuhr** [hydroshare/hydroshare#2817]
Using the "Sort By" and "Sort Direction" clears filters, but only in the backend/results and not in the frontend - the frontend still suggests these filters are place while the results count suggests different.

[180709-test-files-001v.zip](https://github.com/hydroshare/hydroshare/files/2177824/180709-test-files-001v.zip)

**Comment by hydrocheck** [comment]
Issue resolved as a part of the Discover redesign
