### ISSUE TITLE
Quick filter selections create discontinuity in Discover page

### ISSUE THREAD

**Issue by ndebuhr** [hydroshare/hydroshare#2818]
In multiple trials of testing, it was relatively easy to create discontinuity between the filters selected and the actual results displayed by clicking the filters with substantial feed.  I'm not sure how the system is supposed to process new filter selections while the last filter selections are still being processed.  In any case, the filters should be consistent with the results, and consistent filters should product the same number of results across multiple trials.  Neither of these are currently true in beta.  Perhaps we disable controls while a filter is processing and being applied?

[180709-test-files-002v.zip](https://github.com/hydroshare/hydroshare/files/2177827/180709-test-files-002v.zip)

**Comment by hydrocheck** [comment]
Issue resolved as a part of the Discover redesign
