### ISSUE TITLE
Discover page filters are not url parameters

### ISSUE THREAD

**Issue by ndebuhr** [hydroshare/hydroshare#2819]
Discover page filters are not setup as url parameters.  Using url parameters is more of the industry standard (precedent example https://scholar.google.com searching).  The main downsides:
1) A user cannot bookmark/favorite a search that they regularly perform.  Rather, they must manually configure the same filters/setup on Discover any time
2) Since resources open in the same tab, a user cannot then use the "back" browser button to go back to their old query.  Rather, it takes them to a blank category.  So if you click the wrong resource, or want to look at more resources in the result set, it can be a pain to bring back your old search.

[180709-test-files-003v.zip](https://github.com/hydroshare/hydroshare/files/2177830/180709-test-files-003v.zip)

**Comment by cuahsimarko** [comment]
My understanding of this request is that #2 is resolved, part of #1 is handled by the functionality, for example, https://www.hydroshare.org/search/?q=jupyter and allowing URL sharing of searches with specific facets checked is desired. This ticket 2819 can be deprecated by the more recent thread at: https://github.com/hydroshare/hydroshare/issues/4057

**Comment by martinseul** [comment]
superseded by #4057 closing
