### ISSUE TITLE
Timeout in refts creation

### ISSUE THREAD

**Issue by jsadler2** [hydroshare/hydroshare#282]
When trying to add time series with a large amount of data (for example http://data.iutahepscor.org/RedButteCreekWOF/REST/waterml_1_1.svc/datavalues?location=iutah:RB_ARBR_AA&variable=iutah:WaterTemp_EXO/methodCode=56/sourceCode=1/qualityControlLevelCode=0&startDate=&endDate= ) the website times out

**Comment by jsadler2** [comment]
The original problem has been solved. There is a new problem now, [issue #282](https://github.com/hydroshare/hydroshare/issues/282)

**Comment by dtarb** [comment]
@danames can you please test this in HydroShare 1.5 release candidate on alpha.hydroshare.org, and if agreed close.

**Comment by danames** [comment]
Looking forward to alpha.hydroshare.org coming back online so we can test
these things...

**Comment by mjstealey** [comment]
Deferred to later release cycle

**Comment by zhiyuli** [comment]
time out error is gone but got new a new error (alpha, 1.5.3), will look into this shortly
![image](https://cloud.githubusercontent.com/assets/10070599/9634962/357721e4-5151-11e5-874e-c8a92ba44a73.png)

**Comment by hyi** [comment]
@zhiyuli Is this still an issue or can be closed?

**Comment by zhiyuli** [comment]
tested on www. res created at  https://www.hydroshare.org/resource/3f81c2b3b7844532b6b2d6e9901c5214/
P.S. This is relatively a big time series data (17mb wml) .
closing
