### ISSUE TITLE
Inconsistent capitalization approach for group page tabs

### ISSUE THREAD

**Issue by ndebuhr** [hydroshare/hydroshare#2822]
Tabs are currently "OVERVIEW", "Resources", and "MEMBERS".  Can we instead do "OVERVIEW", "RESOURCES", and "MEMBERS"?  Or otherwise "Overview", "Resources", and "Members".  Elsewhere in the system, all caps seems to be reserved just for the top main menu.  As such, it seems like the "Overview",.. approach would be ideal.

[180709-test-files-006v.zip](https://github.com/hydroshare/hydroshare/files/2177836/180709-test-files-006v.zip)

**Comment by Lizabrazil** [comment]
approved

**Comment by cuahsimarko** [comment]
@Lizabrazil you can approve in the parent Pull Request after reviewing all the bugs - https://github.com/hydroshare/hydroshare/pull/3325
