### ISSUE TITLE
No resolution validation for profile image

### ISSUE THREAD

**Issue by ndebuhr** [hydroshare/hydroshare#2823]
Normally, I've noticed that application systems require that profile images be under a certain resolution.  HydroShare appears to accept any resolution (tested with >8k by >8k).  Further, looking at the source, the huge file is actually saved and used "as is", with no downscaling.  This could seemingly cause performance problems later which would be hard to identify.  

[180709-test-files-007v.zip](https://github.com/hydroshare/hydroshare/files/2177842/180709-test-files-007v.zip)

**Comment by aphelionz** [comment]
See Also #2637

**Comment by engineSound** [comment]
Thanks for the video!
We need to specify image size limitation upfront when a new profile image is uploaded.

**Comment by aphelionz** [comment]
Also groups images. Really any images updated that are not resource files. see also #2637

**Comment by engineSound** [comment]
There are two parts of the work:
* Check size
* Give error message

Future enhancement: drag and drop image

**Comment by engineSound** [comment]
<img width="316" alt="image" src="https://user-images.githubusercontent.com/35352595/52753171-a8491200-2fc3-11e9-8857-028f7cefb1b1.png">

## After checking size, it would be like this.
## The maximum allowed is `64 KB`.

**Comment by horsburgh** [comment]
We wouldn't really expect users to create an image that is <= 64 KB in size would we?

**Comment by engineSound** [comment]
@horsburgh What would be the right size limit? I am ready to make changes.

**Comment by horsburgh** [comment]
I'm just thinking about the perspective of the user. I'm a user. I have a photo I want to use for my profile. I try to upload it. I get an error saying it has to be less than 64 KB. I don't know how to shrink it. End result = no profile photo for most users.

Most sites I've used allow me to upload a photo, then they ask for me to crop that photo to a preset extent/aspect ratio and save the portion of the photo I want to use. I'm assuming that they compress the photo after I have done this to make the file smaller. Seems like a reasonable maximum file size might be something more like 2 MB.

If we don't want to make this complicated, that's OK. I just think there won't be that many users that are going to go through the work to come up with a 64 KB file.

**Comment by engineSound** [comment]
@horsburgh I got you. Thanks for bringing the good user experience up. This was something in my head as well. I felt this feature should be worth a separate GitHub issue.

**Comment by engineSound** [comment]
Fix has been in production. PR #3150
