### ISSUE TITLE
No file selection filters for profile image

### ISSUE THREAD

**Issue by ndebuhr** [hydroshare/hydroshare#2824]
The file selection dialog accepts "all files" when uploading a profile image.  Additionally, the user is not provided with feedback until they click "Save".  Restricted file upload type might be helpful.  There are lots of different image types the user could possibly upload.  Do we support all of them?  Should the user "guess and check" to see which ones are valid for HydroShare profile?

[180709-test-files-008v.zip](https://github.com/hydroshare/hydroshare/files/2177843/180709-test-files-008v.zip)

**Comment by eclark-cuahsi** [comment]
@Castronova I believe this falls under the Pages and General HS Components category. Please feel free to relabel if incorrect.

**Comment by dtarb** [comment]
Related to #4363
