### ISSUE TITLE
Resource upload progress shows a much too large number for total upload size

### ISSUE THREAD

**Issue by ndebuhr** [hydroshare/hydroshare#2825]
The total upload size and the sum total of all files uploaded are off by about an order of magnitude.  This is by going to the resource page, clicking edit, then uploading using the "click here to select them" file manager dialog approach.  

[180709-test-files-009v.zip](https://github.com/hydroshare/hydroshare/files/2177844/180709-test-files-009v.zip)

**Comment by engineSound** [comment]
Reproduced. Need to look into the javascript code where byte is converted to MB.

**Comment by engineSound** [comment]
In beta.hydroshare.org and www.hyrdoshare.org, it can no longer be reproducible. So closing. Welcome reopen if this reproducible again.
