### ISSUE TITLE
DataError page for 80+ character group names

### ISSUE THREAD

**Issue by ndebuhr** [hydroshare/hydroshare#2826]
Seemingly we need to provide some feedback to the user, constrain the field length, auto-shorten the name, etc. (something more friendly)

[180709-test-files-010v.zip](https://github.com/hydroshare/hydroshare/files/2177845/180709-test-files-010v.zip)

**Comment by Lizabrazil** [comment]
Still get the error.

**Comment by Lizabrazil** [comment]
![image](https://user-images.githubusercontent.com/13852599/56321930-bb986b00-6135-11e9-97df-a0cd44a93393.png)

**Comment by cuahsimarko** [comment]
approved
