### ISSUE TITLE
Visibility of logout notification is window-size dependent

### ISSUE THREAD

**Issue by ndebuhr** [hydroshare/hydroshare#2828]
On some browser widths, the message is hidden when the use logs out

[180709-test-files-012v.zip](https://github.com/hydroshare/hydroshare/files/2177855/180709-test-files-012v.zip)

**Comment by engineSound** [comment]
Thanks for the video! It saves tons of time.  I appreciate it.

The logged out message got hidden at a certain size. It is annoying to users. Certainly we should fix this. The Sign In button is compensating for the missing logout issue. So users still know they have logged out.

**Comment by engineSound** [comment]
Verified working on main stream browsers.
