### ISSUE TITLE
When rating resource and not logged in, system doesn't redirect after login

### ISSUE THREAD

**Issue by ndebuhr** [hydroshare/hydroshare#2829]
If a user wanted to rate a resource (for example), they would click the link to login.  It seems like after the login, the system should redirect back to where the user wanted to make a login-dependent action.

[180709-test-files-013v.zip](https://github.com/hydroshare/hydroshare/files/2177859/180709-test-files-013v.zip)

**Comment by aphelionz** [comment]
See also #2556 and #2557 and #1099

**Comment by engineSound** [comment]
@aphelionz Mark, the three issues you listed are related to a general scheme how hydroshare implement "come back with the flow". It is also the same as the "add author rolling back to top of the page" [issue](https://github.com/hydroshare/hydroshare/issues/2729). We should fix all of them in one batch of work. It significantly affects user experience.

**Comment by aphelionz** [comment]
@engineSound agree

**Comment by engineSound** [comment]
At the bottom of a resource landing page, when you add a comment without login, you will be directed to a login page. After login, you are back to the page.

However when you click on the adjacent link "You need to be logged in to comment", it went to login dialog, then to hydroshare homepage. 

A quick code look up manifests issue at this line:

https://github.com/hydroshare/hydroshare/blob/b4a80b41def7aafa8198e5bbc6f2475898d26d66/theme/templates/generic/includes/rating.html#L47

**Comment by cuahsimarko** [comment]
Related to https://github.com/hydroshare/hydroshare/issues/2556 ?

**Comment by ndebuhr** [comment]
There has been some progress on this, but behavior varies.   For example, posting a comment redirects to resource after commenting, but rating a resource redirects to https://beta.hydroshare.org/home/.  Keeping open.
