### ISSUE TITLE
Front page slider section text overflow on some devices

### ISSUE THREAD

**Issue by ndebuhr** [hydroshare/hydroshare#2830]
On some mobile devices, the text on the front page of the site overflows the section and is cutoff.  

[180709-test-files-014v.zip](https://github.com/hydroshare/hydroshare/files/2177863/180709-test-files-014v.zip)

**Comment by engineSound** [comment]
I reviewed the video from Neal. Thanks for the effort.
On my iPhone 7 plus which doesn't have the issue. Is this something to do with simulator? As a restraint to us is that we don't have all the physical devices.

It could be small effort, but challenging to validate changes on all the physical devices. 

I tend to treat it as low priority. Mark what do you think?

**Comment by aphelionz** [comment]
@engineSound - what about with responsive mode in Chrome Dev tools? You have variable width there and can try different configurations

**Comment by cuahsimarko** [comment]
No mobile phone support officially that will be a larger design effort in the code
