### ISSUE TITLE
Support for groups of groups

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#2831]
There has been much discussion of support for "groups containing groups". There are several possible interpretations. This is a placeholder issue to contain discussion as it develops.

**Comment by cuahsimarko** [comment]
Feature is live as of 1.21

**Comment by dtarb** [comment]
Is this really live.  I would be interested in seeing a demo.  I do not think this is live.

**Comment by cuahsimarko** [comment]
The support for group of groups is merged. This is a backend ticket. The UI functionality is separate. Interaction with group of groups is heavily documented as a part of the work reflected in this ticket.

**Comment by cuahsimarko** [comment]
Documentation is at hs_access_control/management/commands/README.md I think it wasn't presented as the only interest in this for now seems to be coming from communities and the consumers of this backend for now are me, Drew, Martin...

**Comment by cuahsimarko** [comment]
I think of GitHub as a code-level/repo level context. The "Product" level themed discussion/tracking should happen in Jira/Trello/google docs, design docs, and other systems. This scoping is part of managing roles/responsibilities, reducing cognitive load and having a smoother, more manageable flow across the lifecycle from bug report/feature request, design discussion, implementation detail, architecture, actual implementation... etc... verification on product side.. .full circle Key Performance Indicators... (did the engineering implementation solve the business problem)...
