### ISSUE TITLE
Apps link hardwired

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#2834]
Testing 1.16 release candidate on https://dev-hs-6.cuahsi.org/ I noticed that on the top menu APPS links to www.hydroshare.org/apps.  It should be a relative link to the page on whatever machine it is running, in this case https://dev-hs-6.cuahsi.org/apps.

![image](https://user-images.githubusercontent.com/3456833/42723992-25ea1c7c-8727-11e8-8169-1a281312982a.png)

**Comment by hyi** [comment]
@dtarb @aphelionz I believe this resulted from using www database for deployment on a development machine since the url is in the database. It can be easily changed from admin panel to whatever url proper.

**Comment by dtarb** [comment]
OK.  I can see that it is questionable whether it is worth changing the database, so I'll close this.  If @aphelionz thinks anything needs to be done, feel free to reopen.  I got to looking at this because I was checking the branding on dev-hs-6 and when looking at apps did not see the new branding then realized I had been taken to www.  But I was able to change the url to dev-hs-6 in my browser to examine.
