### ISSUE TITLE
Resource content not displaying correctly in 1.16 candidate release

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#2835]
I have the following resource on www https://www.hydroshare.org/resource/d0e6d4c7f7ef4d9d9486be87fc425314/ 
![image](https://user-images.githubusercontent.com/3456833/42724382-5c151a66-872e-11e8-815f-4ec3d9a07fda.png)

On dev-hs-6 this does not show file contents https://dev-hs-6.cuahsi.org/resource/d0e6d4c7f7ef4d9d9486be87fc425314/
![image](https://user-images.githubusercontent.com/3456833/42724388-8548144c-872e-11e8-8e94-bc6c34e5e179.png)

and debug results in an iRODS processing error 
![image](https://user-images.githubusercontent.com/3456833/42724400-bb650c9c-872e-11e8-9a85-b79a364e5fec.png)

Suspicion is that this is due to inconsistency in the moving of files from www to dev-hs-6 for testing.

The same problem occurs for https://dev-hs-6.cuahsi.org/resource/0860e585772542e3929de88e0af35aa6/ and https://dev-hs-6.cuahsi.org/resource/50b977461a1c4d4392bc07b2c8e9cc4e/

**Comment by aphelionz** [comment]
@sblack-usu @dtarb Can you review on the latest 1.16 deployment on dev-hs-6 and report back or close the ticket?

**Comment by sblack-usu** [comment]
I'm still running the repair_resource command on dev-hs-6.  I'll comment again here when it's finished.

**Comment by dtarb** [comment]
Appears fixed on www and the problem resource no longer exists
