### ISSUE TITLE
Composite resource not properly migrated to CR 1.16

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#2836]
I looked at the following resource.  
https://dev-hs-6.cuahsi.org/resource/ba59b91b681141259bc621493960b6d9/
This includes a geographic feature and a bunch of single files.  The single files are each represented as single file aggregations.  They should have been represented just as files.  This suggests that the migration script to change the www representation of generic logical files to plain files has not been run on dev-hs-6.

If I download the bag for this resource I do not get the aggregation metadata files for the geographic feature aggregation within this resource.  This suggests that the setting to reset bags has not been done for dev-hs-6.

I tried to make a copy of this resource to see if aggregation metadata files would be correctly created for a copy that presumably did not already have a bag.  

- Immediately after the copy action the resource contents display properly (albeit showing each file as a single file aggregation).   
- Download content as a zipped bag results in a bag zipfile being downloaded.  However after this action the resource contents does not display any files
![image](https://user-images.githubusercontent.com/3456833/42724639-39833f1e-8733-11e8-8f4b-f71ceaa1cef4.png)
- The bag zipfile appears to be correct with *meta.xml and *resmap.xml files present for each aggregation (spot checking contents I did not see anything wrong with these).
- Debug reports inconsistencies between iRODS and Django - likely same cause as #2833. 
- There appears to be "remembering" of bag creation/downloading that results in odd behavior.  I added 'debug' at the end of the resource URL to check the point above.  Then I clicked "back" in the browser and was again prompted to save or open the bag zipfile I had already downloaded.

**Comment by alvacouch** [comment]
Note that `fix_irods_file_paths` must be run **before** migrating the composite resources; otherwise migrations will not be done on user resources.

**Comment by dtarb** [comment]
remove_auto_generated_generic_metadata command developed to be run at deploy to resolve this.
