### ISSUE TITLE
Cancel button during resource creation is missing for certain resource types

### ISSUE THREAD

**Issue by ndebuhr** [hydroshare/hydroshare#2837]
Using the "Collection" or "Web App" resource creation results in the "Cancel" button no longer being available to the user.  This is in contrast to the other resource types where this button is available.  Please note that this was tested on a local development build, using the develop branch, so this may not be reproducible on beta or other deployed systems.

[test-files.zip](https://github.com/hydroshare/hydroshare/files/2195318/test-files.zip)

**Comment by engineSound** [comment]
I watched how it was reproduced in the attachment.

**Comment by dtarb** [comment]
Defer and close this issue as the general plan is to avoid an intermediate page during resource creation and after clicking create be straight in a landing page in edit mode to fill in content.  This was suggested by Olin.

**Comment by engineSound** [comment]
Go straight to edit mode is the right approach.
