### ISSUE TITLE
Inconsistent user interface labeling for "Subject Keywords"

### ISSUE THREAD

**Issue by ndebuhr** [hydroshare/hydroshare#2838]
On the resource landing page, the label for "Subject Keywords" is "Subject" on the resource landing page in "view mode".  When entering the edit mode, the same title becomes "Subject Keywords".  "Subject Keywords" should seemingly be the case for both situations.

Please note that this was tested on a local development build, using the develop branch, so this may not be reproducible on beta or other deployed systems.

[test-files.zip](https://github.com/hydroshare/hydroshare/files/2195324/test-files.zip)

**Comment by dtarb** [comment]
Fixed in 1.16 CR.
