### ISSUE TITLE
Adding Utilities at hydroshare-jupyterhub

### ISSUE THREAD

**Issue by ChristinaB** [hydroshare/hydroshare#2844]
@dtarb @Castronova 
We have a request from an organization (CSDMS  https://github.com/csdms) and a toolkit publication (Observatory https://github.com/Freshwater-Initiative/Observatory done in part with HydroShare funding from 2016) to add Utilities.   

From notes in a 4/18/2017 Team meeting (currently page 20) I asked for Team Input on "Is it a HydroShare responsibility or the CUAHSI JupyterHub server?  How do we build utilities?"

Proposal Option 1: Develop a document to describe CUAHSI suggested steps/standards, test with OGH (independently developed tools that uses HydroShare REST client)
Proposal Option 2: Muddle through just making it work for examples above and develop a document describing the process for future utilities

Notes and thoughts on the utility adding process- 
- Should  be general purpose utility:  USU student WhamDam was a bit too niche
- If it works in many applications, not just HydroShare

### Possible steps to Contribute to hydroshare-jupyterhub/Utilities (TBD)

1.  Release code on Github repo, link with TravisCI for conda and pip installation. This can be tested in HS notebooks. 
2.  Present tools to HydroShare Team
3.  Publish code in Journal of Open Source Software (JOSS; get DOI for  Github repo)
4.  Publish tutorial/sample data on HydroShare
5.  Publish peer reviewed journal for community users
6.  Pull request to hydroshare-jupyter when code is finalized
7.  Published examples supported by HS will always work, version testing
If dev continues, users can do a pip install to those evolving repos

Is this too much work for the utility developer? 

- [ ] yes

- [ ] no

### Library options currently for using tools in a Notebook:

- Install  each instance in your user space from Conda or pip install (e.g. my niche library that I’m testing)
- Import generic libraries from hydroshare-jupyterhub docker image (e.g. pandas, json, numpy)
- Import hydroshare team dev libraries from hydroshare-jupyterhub/Utilities (e.g hydroshare, Taudem and other general purpose Hydro tools).

**Comment by amabdallah** [comment]
It would be best if HydroShare can work as a source to https://mybinder.org/ to turn the notebooks live

**Comment by aphelionz** [comment]
@ChristinaB @amabdallah Should this be moved to https://github.com/hydroshare/hydroshare-jupyterhub?

**Comment by amabdallah** [comment]
I talked with @dtarb and @Castronova about it and yes it would be pretty cool to make a public composite resource in HydroShare to work with Binder. It should not be a hug amount of work. Binder deploys the content of a public GitHub repo which may include Jupyter Notebooks and makes them live and interactive. 
I tried to use a public composite resource (which has the same GitHub repo files) with Binder but it returned an error. 

Maybe my issue though is different than what @ChristinaB is asking for

**Comment by cuahsimarko** [comment]
@ChristinaB @dtarb can we consider moving this work tracking item to a different system, other than the hydroshare/hydroshare source code repo Issues?

**Comment by dtarb** [comment]
This should be part of  https://github.com/hydroshare/hydroshare-jupyterhub development.  I suggest @Castronova record the key points here in a jupyterhub issue then close this.

**Comment by cuahsimarko** [comment]
https://github.com/hydroshare/hydroshare-jupyterhub/issues/153
