### ISSUE TITLE
Consider making public group pages open without logging in

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#2854]
Right now in HydroShare, accessing a group page, such as https://www.hydroshare.org/group/2, requires logging in and thus requires a HydroShare account.  

I think there should be an option for a group owner to enable group information from a public group to be accessed without logging in.  The access model for group landing pages should be made the same as the access model for resource landing pages. 

There are use cases where we may want to have a group be publicly accessible without logging in.  One use case is including HydroShare Developers as an author in a publication.  For example AGU provides for teams to be authors for AGU abstracts: 'A research team may be referenced during the submission process in the “Title of Team” field, in lieu of adding the names of individual team members.' https://fallmeeting.agu.org/2018/abstract-submissions/author-policy/.  A HydroShare group page could be used to define a team.  But if a group URL is given e.g. https://www.hydroshare.org/group/2, it redirects to the login page for users not logged in.

As this relates to policy for accessing information about groups (i.e. the list of their members) I am labeling this as 'needs discussion' prior to be considered for coding.

**Comment by cuahsimarko** [comment]
Invite non HS member to group https://github.com/hydroshare/hydroshare/issues/1243

**Comment by Castronova** [comment]
resolved
