### ISSUE TITLE
Multiword subject is returned in single word subject search

### ISSUE THREAD

**Issue by ndebuhr** [hydroshare/hydroshare#2855]
Note - this was tested with 2732 feature branch, although the details below are not necessarily related to 2732 branch development work.
1)
Click a subject/keyword within a resource (to run a search for discoverable resources with a matching subject/keywork).  If a resource has a two word subject, and the first word matches the search, it will be included in the results.  For example, "ice melt" subject matches a "ice" subject search.  Should subject/keywords be limited to no spaces?  The url query parameters suggest "subject_exact" in these searches, which doesn't seem to be the case.  
2)
In the side panel for the Discover interface, if a subject/keyword matches the first word of a multi-word subject/keyword, then the results count will be distorted.  For example, a resource with subject "two" and a different resource with subject "two test" will both be counted for "two test" in the sidebar.  "two" by itself will not show up as a subject in the sidebar, despite being a valid subject 9in one of the resources.

We have plenty of multi-word subjects in the production system, so the bugs above do impact users.

[subject-keyword-search-abnormalities.zip](https://github.com/hydroshare/hydroshare/files/2239156/subject-keyword-search-abnormalities.zip)

**Comment by engineSound** [comment]
@ndebuhr Can you reproduce this problem on hyrdoshare.org? This helps us to identify if this is a regression.

**Comment by engineSound** [comment]
@ndebuhr I was able to reproduce the behavior on hydroshare.org. It isn't a regression.

**Comment by cuahsimarko** [comment]
Involves compound word searching, partial matches in keywords, multiword keywords and also the keyword click behavior on RLP to generate a subject search in Discover
