### ISSUE TITLE
Metadata files for the aggregations, the path to the aggregation contains duplicate folder/path info. 

### ISSUE THREAD

**Issue by pkdash** [hydroshare/hydroshare#2856]
Example:
http://park.hydroshare.org/aa4765dc90194a7e9b44adecd5d47eb1/data/contents/aa4765dc90194a7e9b44adecd5d47eb1/data/contents/Multidimensional_Aggregation/Multidimensional_Aggregation_resmap.xml#aggregation

**Comment by dtarb** [comment]
@pkdash is this still an issue.

**Comment by pkdash** [comment]
This has been resolved. Closing.
