### ISSUE TITLE
Non-Composite Resource Type Deprecation Strategy

### ISSUE THREAD

**Issue by aphelionz** [hydroshare/hydroshare#2858]
Now that composite resource is to be launched as the primary resource type, we should deprecate all other resource types.

In general:

- [ ] Remove Items from dropdown on the "create resource" page
- [ ] E-mail users to let them know of our plans
- [ ] Migration path for converting existing 
- [ ] Figure out how modeling resources
- [ ] Figure out iconography / tagging for resource types

**Comment by aphelionz** [comment]
TODO: Break this into smaller tickets

**Comment by aphelionz** [comment]
@jsadler2 Great. Please link to the sub-tickets from the description of this one. Feel free to edit my description.

**Comment by jsadler2** [comment]
The subticket for the model resource types is https://github.com/hydroshare/hydroshare/issues/2959.

**Comment by cuahsimarko** [comment]
@dtarb Is this covered by other GitHub Issues?

**Comment by dtarb** [comment]
Yes.  Closing
