### ISSUE TITLE
Support Bulk File Uploads

### ISSUE THREAD

**Issue by rajadain** [hydroshare/hydroshare#2859]
Currently, only one file at a time can be added to a HydroShare resource using the `POST hsapi/resource/{id}/file_list/` endpoint, or using the `hs_restclient.addResourceFile`. When export large projects to HydroShare, which can sometimes have dozens or scores of files, adding them one by one takes a long time.

It would be more efficient if the HydroShare API supported bulk uploads which could take a large payload of all the files and save it at once.

**Comment by horsburgh** [comment]
Could this be done by transferring a single zipped file and then unzipping on the HydroShare side when thats done?

**Comment by rajadain** [comment]
If unzipping on the HydroShare side is supported, then yes I think we can do that. How will existing files be handled? Can they be overwritten upon unzipping?

**Comment by rayi113** [comment]
If helpful, there is a builtin iRODS command called "ibun" that can zip and unzip collections of files directly in iRODS.

**Comment by horsburgh** [comment]
@rajadain - good question about the existing files. @aphelionz, @sblack-usu, and @pkdash - I'm assuming that one can upload a zip file through the API and then unzip that file using an API command?  Can you answer the question from @rajadain about what happens if you were to unzip a file in a directory where files of the same name already exist?

**Comment by sblack-usu** [comment]
```
/hsapi/resource/{id}/functions/unzip/{pathname}/
```
or with the client
```
options = {
                 "zip_with_rel_path": "new_folder.zip",
                 "remove_original_zip": True
                          }
hs.resource(resource_id).functions.unzip(options)
```
Overwriting files when unzipping is currently not supported.  Release 1.16 introduces functionality to unzip to a folder, this prevents overwriting files on unzip.

**Comment by rajadain** [comment]
Is there support for bulk delete, where a number of files to be deleted can be specified at once?

Can the files be moved to the root directory of the resource after unzipping them in a folder?

**Comment by sblack-usu** [comment]
Unfortunately we currently do not support a bulk delete through the API.  That is probably something we should support.  I will look into the possibility of supporting this in a future release.  

You can move files after unzipping them, however you'll currently have to do it one at a time.  I can look into supporting some bulk options for this (and other commands).

The move command can be found on readthedocs.  http://hs-restclient.readthedocs.io/en/latest/  Just search for "To move or rename a resource file:"

Or through the REST API:
```
{url_base}/resource/{pid}/functions/move-or-rename/
```

**Comment by sblack-usu** [comment]
The functionality required is met with zip overwrite #2860
