### ISSUE TITLE
Support Overwriting Files

### ISSUE THREAD

**Issue by rajadain** [hydroshare/hydroshare#2860]
Currently, if a file already exists in HydroShare, one must first `DELETE /hsapi/resource/{id}/files/{pathname}/` then `POST /hsapi/resource/{id}/files/{pathname}/`. This doubles the number of API calls, and time taken, for updating all files in a project when the project updates. `POST`ing a file that already exists results in an error.

It would be great if one could pass a flag explicitly asking to overwrite. This would not change existing behavior, simply add the option to overwrite for those who want it, and would halve the number of API calls required to do it.

**Comment by sblack-usu** [comment]
@rajadain - We talked about supporting a bulk upload by uploading a zip and unzipping it with an overwrite after the upload.  I'm looking at implementing the changes to overwrite files on unzip and there are some curve balls introduced by irods and some of our special datasets in HydroShare that complicate overwriting with nested folders.  As long as the zipped files you're sending are flat (do not contain folders), we can support this fairly easily.  I do intend to support overwrite with folders too, it's just going to take a little longer to work out the implementation.

Are the zip files you want to send over flat?

**Comment by rajadain** [comment]
Hi @sblack-usu, here's what an export would look like:

![image](https://user-images.githubusercontent.com/1430060/43966360-aea2e5da-9c8f-11e8-8ed1-7fc56ab56cc7.png)

As you can see, the only folder is for the area-of-interest shapefile, and all the other files are flat in the root space. The way WikiWatershed works is that you cannot change the shape of a project once it is created, so we will not be re-exporting that shapefile on subsequent updates, so that folder can be ignored for this use case.

**Comment by sblack-usu** [comment]
@rajadain - zip overwrite has been deployed to beta.  readthedocs will be updated shortly after the www deploy to document the feature.  You can turn on overwrite by passing {"overwrite": True} to the options.  Let me know if you have questions.  It'd be great if you could test this out soon as we're scheduled to release to www Nov 6th.

**Comment by sblack-usu** [comment]
It should also be noted that we treat aggregations (I think we're calling them file sets now) as a single object.  The "area of interests" folder in your screenshot is an Geographic Raster Aggregation.  So if there is a clash in the unzip, the whole aggregation will be deleted instead of just the file(s) that clash.  So if you wanted to update the area of interest, you'll have to include all the files in that folder.

**Comment by rajadain** [comment]
Hi @sblack-usu, thanks for letting me know. Unfortunately I'm currently at a conference and the earliest I can test this is Monday Nov 5. I'll post here if I run into any problems.

**Comment by rajadain** [comment]
Hi @sblack-usu, I am running into a strange behavior. My code is here: https://github.com/WikiWatershed/model-my-watershed/pull/3032.

If I create a new project with zip file, it works correctly. This is an example of the zip file I generate, and it unzips correctly on the HydroShare end: [8315abfe863043e690a5ebc9c65f574d.zip](https://github.com/hydroshare/hydroshare/files/2605594/8315abfe863043e690a5ebc9c65f574d.zip)

However, when I export to the same project again, now with only a subset of files, like this: 
[8315abfe863043e690a5ebc9c65f574d (1).zip](https://github.com/hydroshare/hydroshare/files/2605604/8315abfe863043e690a5ebc9c65f574d.1.zip) (which includes only one file: `mmw_project_snapshot.json`), the previously existing file is deleted, but the new one isn't saved, so effectively this file stops existing.

Here's a project where I'm seeing this behavior: https://beta.hydroshare.org/resource/8315abfe863043e690a5ebc9c65f574d/

Please let me know if I'm doing something wrong, or if this needs to be addressed on your end.

**Comment by sblack-usu** [comment]
Thanks @rajadain.  I was able to reproduce your issue.  I'm debugging it locally to figure out what is going on.  I'll let you know shortly.

**Comment by sblack-usu** [comment]
@rajadain - sorry about this bug, I found out what was going on.  It was introduced at the end of the review process by adding some logic that wasn't completely thought out and caused this issue.  I've submitted a branch with the fix and deployed it to dev-hs-1.  You can see an example resource using your test case here https://dev-hs-1.cuahsi.org/resource/9bca85088bd24b8cac040011ce5fff31/.  You can also develop against dev-hs-1 for now.  I should be able to get it deployed to beta tomorrow after the 1.17 release, so you shouldn't have to wait much longer.

**Comment by rajadain** [comment]
Thanks @sblack-usu! So I should not have to change any code on my end?

**Comment by sblack-usu** [comment]
no, this was a bug on my end.

**Comment by sblack-usu** [comment]
@rajadain - could you test this out against beta today.  I deployed the bug fix.

**Comment by rajadain** [comment]
It looks good on initial review by me. A colleague will review my PR and confirm. Thanks!

**Comment by sblack-usu** [comment]
good to hear

**Comment by rajadain** [comment]
Tested on Beta, seems to be working great! Thanks so much!

**Comment by sblack-usu** [comment]
@rajadain - this has been deployed to production.
