### ISSUE TITLE
Add "Is Referenced By" to "Relations" drop down on resource edit page

### ISSUE THREAD

**Issue by aphelionz** [hydroshare/hydroshare#2861]

**Comment by horsburgh** [comment]
Also see #2763 which provides some better semantics for how the relations terms should be displayed on the page once a relationship is created. I modified that issue to include this new term.

**Comment by horsburgh** [comment]
And - just a minor semantic wiggle - we have the term "Cites". Do we want this term to be "IsCitedBy" instead of "IsReferencedBy?"

**Comment by horsburgh** [comment]
Sure - it can. I just thought since we already had "Cites" as a term, it made more sense to have the converse "IsCitedBy" as a new term rather than introducing something that might be a little semantically different. I'm not sure it really matters. "IsReferencedBy" could be considered a little broader in that a "reference" may or may not be a formal citation.

**Comment by aphelionz** [comment]
IsReferencedBy is pure dublin core, if we care. Happy to make it say whatever

**Comment by horsburgh** [comment]
@aphelionz - yep, Dublin Core in its dcterms namespace has both "References" and "IsReferencedBy". The other terms we are using came from a cito namespace and add the ability to have relation types that are maybe a bit more expressive. I would be fine with "IsReferencedBy" - let's just make sure it gets associated with the right namespace when it gets written to the metadata.

**Comment by rayi113** [comment]
So superset is:  
 * References  
 * IsReferencedBy  
 * Cites  
 * IsCitedBy

**Comment by zhiyuli** [comment]
@horsburgh I was referred by @martinseul to this ticket and then realized this might have been superseded by the new changes you proposed a couple of weeks ago on Wed call. Can we close this ticket? Thanks

**Comment by horsburgh** [comment]
@zhiyuli - yes, see the discussion in #3261. There's a link to a Google doc there where I lay out the changes that will need to be made to related resources, including addition of new relationship type terms. There are Dublin Core relationship types for "references" and "isReferencedBy" that can be used to create more generic pointers from and to external references. Also, they are Dublin Core and so more consistent with our overall metadata model. I think we can close this ticket, knowing that the terms will be reconciled with work on #3261.
