### ISSUE TITLE
Create HydroShare Profile Badge for AGU Fellows

### ISSUE THREAD

**Issue by rayi113** [hydroshare/hydroshare#2868]
Driven by Dave Tarboton's recent honor of being selected as an AGU Fellow https://eos.org/agu-news/2018-class-of-agu-fellows-announced, consider creation of a badge to be rendered in the HydroShare profile page for AGU fellows that have HydroShare accounts.

**Comment by aphelionz** [comment]
@dtarb appreciates this greatly and also has indicated that this will not be necessary
