### ISSUE TITLE
My Resources page should probably have pagination like Discover page

### ISSUE THREAD

**Issue by ndebuhr** [hydroshare/hydroshare#2870]
All resources are displayed without pagination on My Resources.  For some of our power users with 200+ resources, this is a lot of content to load and makes the page huge.  In my own testing, it seems like loading all this content upfront and displaying in one long list has a considerable impact on page loadtime/performance.

[Video and Other Bug Report Files](https://github.com/hydroshare/hydroshare/files/2288927/001.zip)

**Comment by aphelionz** [comment]
@dtarb hates pagination and wants "show all"
