### ISSUE TITLE
No user message during processing for resource creation/deletion

### ISSUE THREAD

**Issue by ndebuhr** [hydroshare/hydroshare#2871]
If the user is creating a large resource or deleting many/large resources, then the processing time is substantial.  There is no notification to the user that this processing is underway, except for a small cursor change.  It seems like having no notification to the user risks users becoming confused, navigating away from the page, or pressing the create/delete button again.

[Video and Other Bug Report Files](https://github.com/hydroshare/hydroshare/files/2288934/002.zip)

**Comment by Castronova** [comment]
Pressing the `delete` button multiple times because nothing seems to be happening might be the root cause of users accidentally deleting data that they didn't have selected.

**Comment by dtarb** [comment]
I am certainly supportive of this.  It would be helpful to start/outline a design specification for the team to contribute, in whatever format you prefer (e.g. Google Doc or file in github).

**Comment by aphelionz** [comment]
Luckily, I've already started work to this effect - we just need to finish it:

https://github.com/hydroshare/hydroshare/search?q=universalmessage&unscoped_q=universalmessage

**Comment by cuahsimarko** [comment]
@dtarb @ndebuhr @engineSound @sblack-usu @Lizabrazil @alvacouch @martinseul @pkdash @Maurier @maryal01 

This is a good token GitHub Issue that I'd like to call attention to. Lots going on here in terms of Engineering but also our Processes.

I think we should split this ticket up.

1. Disable buttons like the delete button while in progress
2. Investigate possible efficiency gains during delete to make it faster (I see options in the API for delete one and delete many, haven't dug any deeper yet but will be a good exercise)
3. Maintain consistency by strategy, yet to be determined, if user does something like navigating away (potentially async background action that is not interrupted when back button pressed)
4. A much larger, frontend component story to develop a notifications system in the UI that would be used initially here and then elsewhere. My vision is perhaps different than what Henderson suggested with universalmessage in September 2018

These are the types of detail I like to see in JIRA, as the format and quantity (450+) of items in GitHub Issues has really become impractical. There are story, design elements, screenshot and generally the types of activities that GitHub doesn't support well.

**Comment by cuahsimarko** [comment]
Second phase https://github.com/hydroshare/hydroshare/issues/3346
