### ISSUE TITLE
No phone number validation on profile page

### ISSUE THREAD

**Issue by ndebuhr** [hydroshare/hydroshare#2872]
There seems to be no limits/validation for phone numbers on the profile page.  It seems like allowing the users to use characters like Ü could cause problems downstream in the system.  Additionally, analysis/parsing of user data might be messy when the phone number could take virtually any form.

[Video and Other Bug Report Files](https://github.com/hydroshare/hydroshare/files/2288939/003.zip)

**Comment by aphelionz** [comment]
TODO: Add Django field validators for telephone numbers
