### ISSUE TITLE
Profile editing interface has display issues on mobile

### ISSUE THREAD

**Issue by ndebuhr** [hydroshare/hydroshare#2874]
Navigating the profile edit interface on mobile results in display abnormalities, overlapping interface elements, and elements falling off the screen.  On the home page, we advertise "Available on all your devices", so it seems like users should be able to use mobile devices to edit their profile.

[Video and Other Bug Report Files](https://github.com/hydroshare/hydroshare/files/2288941/005.zip)

**Comment by cuahsimarko** [comment]
No mobile phone support officially that will be a larger design effort in the code
