### ISSUE TITLE
File Download tweaks

### ISSUE THREAD

**Issue by sblack-usu** [hydroshare/hydroshare#2880]
Found the following issues while looking at the current composite resource deployment.

- [x] Download message displays bag when downloading a zip.
- [x] Add ability download single file aggregations as single file or zipped with metadata
- [x] Update Content Metadata permissions to not require login for public resources

**Comment by sblack-usu** [comment]
Updating download message to ```Please wait for the download to be prepared```

**Comment by sblack-usu** [comment]
@aphelionz - could I get a sanity check?  I'm looking at hs_file_types/views.py and writing the fix to get_metadata so metadata displays on public resources without the user logged in.  Then it occurred to me, all the methods in this file are using the login_required decorator.  This seemed correct at first glance, but that means anyone who is logged in can call any of these methods on any resource... That's a bit of a security flaw if I'm reading this right.  We should be checking the user for permissions on the resource like we're doing for the main resource page.

**Comment by aphelionz** [comment]
@sblack-usu Correct, we should be using the `authorize` helper function
