### ISSUE TITLE
Audit Trail & Private Only Feature Requests

### ISSUE THREAD

**Issue by ChristinaB** [hydroshare/hydroshare#2881]
For Ray and Christina to work out for RAPID project

**Comment by ChristinaB** [comment]
@rayi113  Thanks for talking and I'll see you here next week.

**Comment by ChristinaB** [comment]
Let me know about the common share badge implementation.

**Comment by aphelionz** [comment]
@ChristinaB Are there any details you can share in the ticket so we can contextualize & prioritize?

**Comment by dtarb** [comment]
Not having heard anything about what is needed I am closing.  Please reopen a new issue with greater specificity if needed.
