### ISSUE TITLE
Abstract Message Error is not helpful

### ISSUE THREAD

**Issue by Lizabrazil** [hydroshare/hydroshare#2883]
User tried filling out the abstract and the following message popped up. If there is a character limit then the error message should say that. 
![image](https://user-images.githubusercontent.com/13852599/44725245-dcc32300-aaa2-11e8-8feb-14860a94206d.png)

**Comment by dtarb** [comment]
If it is a length issue the message should indicate what the length limit is and how many characters were used.  Also add after Abstract "(max 3000 char)".

**Comment by engineSound** [comment]
![image](https://user-images.githubusercontent.com/35352595/47183040-05260b80-d2f5-11e8-991f-168ad04aec74.png)

Verified in 1.16 beta.
