### ISSUE TITLE
Message Block in Resource Landing Page

### ISSUE THREAD

**Issue by jsadler2** [hydroshare/hydroshare#289]

**Comment by pkdash** [comment]
@jsadler2 I think we can use django messaging framework (https://docs.djangoproject.com/en/1.8/ref/contrib/messages/) to display messages and our base.html already includes code to display messages from this framework.

**Comment by horsburgh** [comment]
@jsadler2 - is this still an issue or can it be closed?

**Comment by pkdash** [comment]
@jsadler2 Please close this issue.
