### ISSUE TITLE
Update how to cite field for permanently published resources to drop dx

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#2892]
The DOI system now does not need the dx in URL's anymore.  We should update the "how to cite" field in landing pages to use the new preferred format:
https://doi.org/10.4211/hs.877bf9ed9e66468cadddb229838a9ced. 
![image](https://user-images.githubusercontent.com/3456833/45187958-c8dc9700-b1ef-11e8-8fbf-e188ee0c3459.png)

**Comment by dtarb** [comment]
The following resource published yesterday still has dx in it.  https://www.hydroshare.org/resource/caa886183ec94d50a25ea868367c1ee7/

**Comment by horsburgh** [comment]
See #2689, which was closed for some reason, but never resolved. There was a pull request that got merged. We do generate the DOIs on our side.

The current preferred DOI resolver is https://doi.org

**Comment by sblack-usu** [comment]
Looks like new resources do not have the dx subdomain, so we will only need to do the migration.

https://github.com/hydroshare/hydroshare/blob/develop/hs_core/hydroshare/resource.py#L912
