### ISSUE TITLE
Files are repeated in contents listing in just deployed 1.15

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#2897]
In 1.15 just deployed files are repeated in the content area
![image](https://user-images.githubusercontent.com/3456833/45324783-65fb4080-b50c-11e8-97ad-2fe46a07aa29.png).

Appears only a display issue.  Bag still has one copy of each file.

**Comment by aphelionz** [comment]
Rolled back to 1.15.4 while we investigate

Not happening on beta, oddly enough

**Comment by aphelionz** [comment]
Cloising as we found the source of the problem and the hotfix was merged
