### ISSUE TITLE
Verification Resend is not Functional

### ISSUE THREAD

**Issue by ironfroggy** [hydroshare/hydroshare#29]
http://beta.hydroshare.org/hsapi/_internal/resend_verification_email/

**Comment by hyi** [comment]
Fix pushed to github and a pull request has been created to merge into release-candidate-1.4.0 branch.

**Comment by hyi** [comment]
It is working and ready for testing on alpha.hydroshare.org now.

**Comment by dtarb** [comment]
Tested by creating an account and verifying that the resend email works.
