### ISSUE TITLE
Modify Delete File Message

### ISSUE THREAD

**Issue by horsburgh** [hydroshare/hydroshare#290]
When I delete a file from a resource, I get a message telling me to save the file if I want to keep a copy.  This text should probably be changed to "Consider saving a copy of the file before you delete it if it is important to you."

This would make it more clear that a user should make a copy of the file before deleting.

**Comment by dtarb** [comment]
@horsburgh please check this on alpha.hydroshare.org and close if the message is to your satisfaction

**Comment by horsburgh** [comment]
Looks good to me.
