### ISSUE TITLE
Ownership changes do not propagate to Owner displayed for a resource

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#291]
If I change the owner of a resource this does not propagate to the owner(s) displayed for a resource.  For example for the following resource I created it as user David (UNC) Tarboton, then added David Tarboton and Ray Idaszak as owners and removed David (UNC) Tarboton.  Owner is still listed as "David (UNC) Tarboton" in the resources landing and listing pages.
![untitled](https://cloud.githubusercontent.com/assets/3456833/7064506/2ac02a9e-de7d-11e4-847e-00139f04a9bb.png)

This manifests on both the resource landing page illustrated above and the resource listing page where Owner listed is the user who created the resource, even after it is changed.  Though the filter "Owned by me" on the resource listing page does appear to recognize ownership changes.

**Comment by dtarb** [comment]
@ironfroggy this is an example of a ticket about ownership

**Comment by hyi** [comment]
I have addressed this issue in my access control branch, which is actually a resource landing page display issue, i.e., it only displayed the first owner, not all owners. I have fixed landing page template to display all owners in my access control feature branch, which can be viewed on playground now.

**Comment by hyi** [comment]
Fix pushed to github and a pull request has been created to have it merge into develop and built on dev for testing.

**Comment by hyi** [comment]
Tested on dev.hydroshare.org and things work as expected. I created three test users: testuser1, testuser2, and testuser3, and assigned the ownership of a resource I created to testuser1, read-write permission to testuser2, and read-only permission to testuser3, and logged in as each test user and performed operations as specified by the access control they were assigned as expected. Set it to ready for testing for the team to test.

**Comment by mjstealey** [comment]
@hyi - The resource you've been denoting is private and cannot be seen unless logged in as one of the test users with rights on the resource or as admin...

May want to perform tests on resources that can be observed by others without having to log in as a specific user or as admin.

**Comment by hyi** [comment]
@mjstealey Good idea. I have made the resource public: http://dev.hydroshare.org/resource/8728319dfb5f45bfa1f0113651d5f453/
However, you will have to log in as each individual test user to test the permissions they are assigned for this resource. Let me know if you need to know these testusers' passwords to look into them, but I thought you may want to test in your own way.

**Comment by dtarb** [comment]
Tested.  Working correctly on Alpha.  Presentation of manage access still needs to be improved but is addressed in other issues.
