### ISSUE TITLE
Image formats handling for icon url (web app resources)

### ISSUE THREAD

**Issue by ndebuhr** [hydroshare/hydroshare#2910]
The "feature suggstion" part of this:
It seems like .ico "Icon file" should be accepted by the Icon URL input for Web App resources.  SVG files seem like they should be possible as well.  Further, both of these file types correctly render a preview when the user inputs the url.  We should probably not show the preview if we are not accepting the file?  This could make the user think the file format restrictions are arbitrary (maybe to some extent they are).  

The "bug" part of this:
For these ico and svg files, the right error message is not always displayed.  For "https://duckduckgo.com/favicon.ico" I get a "Error! Metadata failed to update." as opposed to the expected "Error! Failed to update metadata element 'toolicon'. Supported icon image types are png, gif and jpeg."  So if the user tried https://duckduckgo.com/favicon.ico they would have no insight into the issue or how to successfully implement the icon.

[002.zip](https://github.com/hydroshare/hydroshare/files/2421102/002.zip)

**Comment by Castronova** [comment]
related to #2895

**Comment by eclark-cuahsi** [comment]
@horsburgh I believe this falls under the Resource Model Category; adding this label but please feel free to reassign if there is a better fit.
