### ISSUE TITLE
Icon URL can be animated gif for Web App resources

### ISSUE THREAD

**Issue by ndebuhr** [hydroshare/hydroshare#2911]
This seems like an exceptionally odd case, but I suppose worth mentioning.  Animated GIFs are accepted as valid icon files for Web App resources.  I imagine that's probably not by design.

[001.zip](https://github.com/hydroshare/hydroshare/files/2421117/001.zip)

**Comment by aphelionz** [comment]
I think for now we're just going to limit the size and not worry too much about this - this could be fun for people.
