### ISSUE TITLE
Phone number visible by non-logged-in users

### ISSUE THREAD

**Issue by ndebuhr** [hydroshare/hydroshare#2914]
https://beta.hydroshare.org/user/11/

Do we want phone numbers exposed like this?  We have a "(Log in to send email)" blocker for email, but the phone number is visible in plain text without logging on?

[005.zip](https://github.com/hydroshare/hydroshare/files/2421233/005.zip)

**Comment by dtarb** [comment]
I do not object to phone number being exposed.  A user does not have to submit a phone number to get an account, while they do have to submit an email address.  We should (and perhaps do) have a message indicating that content added to the profile is public information and not to provide it if you do not want it to be public.  I'd be happy for this content handling to be reviewed and to consider enhancements to improve this, but I do not think this is a security issue, and only marginally is this a bug.

**Comment by cuahsimarko** [comment]
Consider closing this

**Comment by Castronova** [comment]
Closing. Profile information is public by default.
