### ISSUE TITLE
Use Firstname Lastname, Organization (username) as display names for managing access

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#292]
In the access management interface use the users real name followed by email in parentheses to identify users.  See illustration 
![untitled](https://cloud.githubusercontent.com/assets/3456833/7064989/4e865030-de81-11e4-8b8e-3afa519b6634.png)

**Comment by ironfroggy** [comment]
This makes all users email addresses public. I think you should strongly reconsider this. Most users will (rightly so) consider this an egregious privacy violation.

**Comment by horsburgh** [comment]
This will get addressed with the redesign of the sharing interface.  But, we should make sure we address any privacy concerns before we implement something.

**Comment by dtarb** [comment]
Is there an alternative that better respects privacy.  @alvacouch what do you think?  I thought quite hard about this while writing the document about usernames and emails that is at https://github.com/hydroshare/hydroshare/blob/master/docs/DesignDocs/UserNameEmailRules.md.  We need a way for someone wanting to share a resource with someone to be able to identify and find them.  In the document I stated that emails in HydroShare are not private, because I think it is impossible to guarantee their non disclosure in a system of this nature where they can be part of metadata records for resources that may be public.  However we do try make it hard for spammers.  In the document I suggested a messaging system rather than emails for directly contacting other users, but given the non uniqueness of names, the arbitrariness of usernames, I think that seeing an email address is necessary to make sure a resource is being shared with the right person.

**Comment by dtarb** [comment]
Lets use Firstname Lastname, organization (username) as the identifier string in all places on this interface consistently and not display emails.

Other recommendations
- Avoid the multi-select.
- List with check boxes for the permissions being given (owner, change, view)
- Have a definitive remove icon for removing users
@ironfroggy  will post a mockup

**Comment by dtarb** [comment]
See #201.  @mauriel133 this relates to the branch you are working on

**Comment by dtarb** [comment]
This is implemented in 1.6.0 and 1.6.1 deploys.
