### ISSUE TITLE
Resource Landing Page: File Browser List View Formatting off for Long File Names

### ISSUE THREAD

**Issue by horsburgh** [hydroshare/hydroshare#2924]
When viewing the list of files in a resource in list view, the contents of the list are muddled when there are files with long names. The columns of information (file type, size, etc) get misaligned. An example is below. It is worse when the browser window is narrow, but doesn't entirely go away when the browser window is made wide.

![image](https://user-images.githubusercontent.com/3485902/46386131-e4b34b80-c67c-11e8-8990-eabfa19eb4ff.png)

@Maurier - I know you've already got a lot of stuff going with the resource landing page. Is this something that can be fixed with your ongoing work?

**Comment by Maurier** [comment]
I rather fix this apart from my current work because we are trying to keep the PR size small. I will push a fix for this soon.

**Comment by horsburgh** [comment]
Sounds good. I'm all for keeping pull requests smaller.

**Comment by horsburgh** [comment]
This is sorted on www as part of the 1.19 release. Closing
