### ISSUE TITLE
DOI should not be shown for a resource not published.

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#2939]
I noticed in testing a beta.hydroshare.org that at the top of a resource landing page a DOI is given for a resource that is not published.  E.g. 
![image](https://user-images.githubusercontent.com/3456833/47052550-18ef3780-d166-11e8-95bc-80d0bcc926cf.png)
This is incorrect because the DOI has not been issued and does not resolve at doi.org

I suggest that this DOI row on the resource landing page only be shown if the resource is published.

The cite link next to the DOI is tagged to go down to the citation part of the resource landing page.  But goes too far down.  It should go to above "How to Cite" not below it as it currently does.

I think the word "cite" is unclear and would be better stated "How to Cite" or "Cite this resource" as @Maurier suggested in code review.  There is plenty of space.

This was implemented in #2918 in response to #2917

**Comment by engineSound** [comment]
Dave, thanks for paying attention to the change. Displaying an DOI even a resource is not published is intentional. We tested DOI on several users and they all liked it of seeing DOI is given even the resource isn't published. Also two commercial repositories figshare and mendeley go with the same design.

To address the concern,  add "inactive" when the resource isn't published.

**Comment by horsburgh** [comment]
Like Dave, I'm fine with the DOI getting promoted to the header of the page, but it should not be displayed without messaging alerting the user that it is not active until the resource is published (and the message should disappear when the resource is published). 

I just looked at a "private" resource in Figshare, and here is how they display the DOI for something that is not published (thy really only have two states for datasets - private and public/published):

![image](https://user-images.githubusercontent.com/3485902/47108029-07f70280-d208-11e8-8735-5f92a5cad2bd.png)

Also - in the private view of their equivalent of the resource landing page available to the creator of the dataset in Figshare (I select their "Preview Item" option), the DOI is not listed in their preview that I could see.

**Comment by engineSound** [comment]
The fix includes:
1. Added "A" in the statement on file uploader page: **A** DOI is reserved... (per @danames comment)
2. DOI displays only when published.
3. changed cite to "How to Cite"
4. erratic cite display.

**Comment by engineSound** [comment]
PR #2944

**Comment by dtarb** [comment]
@engineSound thanks for fixing these on beta.  I just checked and the "How to Cite" link still goes to below the How to cite header, not above it as it should.  (I am using firefox if that matters)

**Comment by engineSound** [comment]
I looked at this before and figured the reason might come from the fixed hydroshare header. It requires a special manipulation to shift downward the page. I don't have a solution yet.

**Comment by dtarb** [comment]
Ok.  Closing this as it is essentially done and created #2945 to address the tag overshoot issue.
