### ISSUE TITLE
RefTS updating the files

### ISSUE THREAD

**Issue by jsadler2** [hydroshare/hydroshare#294]
When the resource landing page is loaded HydroShare should access the reference url to get the latest data

**Comment by dtarb** [comment]
Be careful about this.  If the web service is not responding you may build in a vulnerability.  Avoid anything that would prevent landing page opening.  Consider options that either use a static visualization or a visualization that does not block and perhaps gradually fills in.

**Comment by dtarb** [comment]
@jsadler2 what are your plans for resolving this?

**Comment by zhiyuli** [comment]
this issue does not exist any longer. current refts only retrieves latest data upon user request.
closing
