### ISSUE TITLE
Placement of Cite link in DOI line on landing page is erratic

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#2940]
In testing beta.hydroshare.org I saw the following

Case 1.  Cite quite close to DOI https://beta.hydroshare.org/resource/7b2c6e5e63f34d348bde5fa8be51a85a/
![image](https://user-images.githubusercontent.com/3456833/47052957-0ece3880-d168-11e8-936d-24728c381ee9.png)

Case 2.  Cite way to the right https://beta.hydroshare.org/resource/e76494ebad394bdfb06343f54682978c/
![image](https://user-images.githubusercontent.com/3456833/47052973-2b6a7080-d168-11e8-90e5-f4a0a2004f12.png)

This appears to be related to the length of the line listing authors.  I think the cite link (which per #2939) should be clarified to "How to cite" should be immediately to the right of the DOI as for case 1.

**Comment by engineSound** [comment]
A fix is altogether with #2939.

**Comment by engineSound** [comment]
PR #2944

**Comment by dtarb** [comment]
This is fixed in beta.  Thanks.

**Comment by engineSound** [comment]
Thank you!
