### ISSUE TITLE
Improve geographic feature error message

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#2946]
Change the error given when a user tries to add incomplete content to a geographic feature (shapefile) from
![image](https://user-images.githubusercontent.com/3456833/47246506-69130780-d3bb-11e8-9c60-eb98f4d17429.png)

to "Failed to set the selected aggregation type:
Shapefile component file at location: <folder> are incomplete or incorrect.  The .shp, .shx, and .dbf shapefile component files are required.  Other shapefile component files (.cpg, .prj, .sbn, .sbx, .xml, .fbn, .fbx, .ain, .aih, .atx, .ixs, .mxs) should also be added where available."

**Comment by engineSound** [comment]
@dtarb Can you provide the steps to reproduce as well as incomplete content and shapefile. This will help me verify the error message I am about to change is the right one.

**Comment by engineSound** [comment]
I have a PR #3113 for the issue. I need to validate it before merge into develop.

**Comment by dtarb** [comment]
If you attempt to load the files from this
[CubOutletMissingFiles.zip](https://github.com/hydroshare/hydroshare/files/2818985/CubOutletMissingFiles.zip) you should get the error when you right click and convert to geographic feature.

If you try load these files, a geographic feature aggregation should automatically be created
[CubOutletOK.zip](https://github.com/hydroshare/hydroshare/files/2818991/CubOutletOK.zip)

**Comment by engineSound** [comment]
@dtarb Thanks. I will try it out.

**Comment by engineSound** [comment]
@dtarb I reproduced it. 

Below is the result with the correct message you provided.

![image](https://user-images.githubusercontent.com/35352595/52153508-52ca4800-2648-11e9-9265-a0cb943043b2.png)

**Comment by dtarb** [comment]
Thanks.  I worry reading this now that it is still not nicely worded.  The intent is to convey that there was some sort of problem with a component file, but we do not exactly know what.  Either one of the required files is missing, or one of the files has incorrect content.  The phrase "file at location:" awkward.  

So I would like to offer the following as a suggestion:
"Failed to set the selected aggregation type
There was a problem parsing the component files associated with (\<put location and filename here\>) as a geographic shapefile.  This may be because a component file is corrupt or missing.  The .shp, .shx, and .dbf shapefile component files are required. Other shapefile component files (.cpg, .prj, .sbn, .sbx, .xml, .fbn, .fbx, .ain, .aih, .atx, .ixs, .mxs) should also be added where available."

While really long, I think that length is better in this case because if a user is faced with this error, versus a shorter error, they may read it carefully and solve the problem themselves rather than tell us the system does not work.  I would appreciate it if @horsburgh and @Lizabrazil could vet this wording before finalizing it.

**Comment by horsburgh** [comment]
I like the new wording @dtarb suggests for this.

**Comment by engineSound** [comment]
@dtarb sure. The new is clearer and more helpful to user.
