### ISSUE TITLE
[1.16 deployment] Resource level temporal coverage display in edit mode is not correct

### ISSUE THREAD

**Issue by pkdash** [hydroshare/hydroshare#2948]
For composite resource the display of resource level coverage is correct in view mode. But when displayed in edit mode, it is not correct - shows always the current date.  Most likely a bug in JavaScript code.
![image](https://user-images.githubusercontent.com/2523434/47273596-03fb1580-d565-11e8-905c-422239b6844f.png)

**Comment by dtarb** [comment]
Closing.  Duplicate of #2949
