### ISSUE TITLE
User can change privacy status not in edit mode

### ISSUE THREAD

**Issue by Lizabrazil** [hydroshare/hydroshare#2956]
User can go out of edit mode and still edit the resource to make private, public, disc, shareable, publish. This seems unintuitive as it is an edit to the resource yet not in edit mode.

**Comment by horsburgh** [comment]
This will be handled by the updates to the resource landing page. All access control options have been moved to the “manage access” dialog. Those options won’t appear on the page anymore in either view or edit mode. They will be on the form that pops up when you click the “manage access” button.

**Comment by Lizabrazil** [comment]
Jeff, wonderful. Thank you.

**Comment by Lizabrazil** [comment]
Oops, I guess this needs to stay open until the issue is resolved.

**Comment by dtarb** [comment]
Closing as will be addressed with resource landing page.  Strictly changing access rules is not editing.  Trying to avoid too many open issues.
