### ISSUE TITLE
Create Resource page - Change text indicating file size limit

### ISSUE THREAD

**Issue by danames** [hydroshare/hydroshare#296]
The create resource page says there is s 10GB limit to file uploads. This is apparently a falsehood. Change this text to 1GB (or other tested value?)

**Comment by dtarb** [comment]
Bagit restructuring #185 is supposed to fix the problems currently experienced with small file sizes.  Lets evaluate the real limits after this is done.

**Comment by dtarb** [comment]
Bagit restructuring as stood up capability to work with large files.
