### ISSUE TITLE
Enable large file download via API

### ISSUE THREAD

**Issue by sblack-usu** [hydroshare/hydroshare#2960]

**Comment by hyi** [comment]
@sblack-usu While working on API for this issue, you can incorporate the following two code changes in the core code which is related to large file download as well:

- Add one line ```--worker-class gevent \``` after this line https://github.com/hydroshare/hydroshare/blob/develop/gunicorn_start#L31

- Remove these lines: https://github.com/hydroshare/hydroshare/blob/develop/django_irods/views.py#L385-L395 and the conditional check for size here: https://github.com/hydroshare/hydroshare/blob/develop/django_irods/views.py#L373

**Comment by sblack-usu** [comment]
@hyi will take care of the gevent with referenced content.  No changes are needed to enable large file download via api
