### ISSUE TITLE
Download failures

### ISSUE THREAD

**Issue by brubash** [hydroshare/hydroshare#2962]
Large downloads fail apparently due to timeouts at Hydroshare. Restart at an offset with e.g. wget don't work: the restart starts over at file offset zero. Usually the timeout is at about 120 megabytes, but at times when speeds are robust from my ISP I have been able to surpass 200 megabytes.

**Comment by aphelionz** [comment]
@alvacouch or @phuongdm can you take a look at this?

**Comment by phuongdm** [comment]
@brubash 

could you please give me the resource link?

**Comment by brubash** [comment]
Do you mean an example of a download that failed? Here's one:
https://www.hydroshare.org/resource/5c7ea11d0ba744ea872e9027920ce662.zip

**Comment by phuongdm** [comment]
@brubash 

I've tried several times and all of them are successfully downloaded. It took me some minutes (less than 3) to download this file (556 MB).

Could you please try again in other network?

**Comment by Castronova** [comment]
@brubash How did you get this url?

The correct url appears to be:
https://www.hydroshare.org/django_irods/download/bags/5c7ea11d0ba744ea872e9027920ce662.zip

**Comment by phuongdm** [comment]
@brubash 

Oh, I'm sorry, I went to resource page then click to the "Download All Content as Zipped BagIt Archive" button.

Thanks @Castronova

**Comment by brubash** [comment]
I can't "try in other network." That would be a ferry ride and 1/2 hour drive away.

"Download All Content as Zipped BagIt Archive" worked today, however. I'm satisfied.
