### ISSUE TITLE
Creating user account organization difficulties

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#2968]
In signing up for a new account I entered USU (typing somewhat fast).  USU was not presented as an option so I moved on to fill in the password field.
![image](https://user-images.githubusercontent.com/3456833/47748892-777de080-dc51-11e8-968e-38337b1cb036.png)

USU then appeared in red in the organization field
![image](https://user-images.githubusercontent.com/3456833/47748945-9a0ff980-dc51-11e8-89d7-28a24e616094.png)

I created the account.  Then when I clicked on the link in the verification email it took me to my profile with multiple organization entries as below.
![image](https://user-images.githubusercontent.com/3456833/47749020-c88dd480-dc51-11e8-8bda-d5d68cc3ea81.png)

**Comment by cuahsimarko** [comment]
@dtarb are these related? https://github.com/hydroshare/hydroshare/issues/2784

**Comment by dtarb** [comment]
This and #2784 are essentially the same.  I am going to close both.  I am not able to reproduce at present and this may have been resolved by cleanups done on the institution list @sblack-usu worked on a while back.
