### ISSUE TITLE
Email Host Password Exposed

### ISSUE THREAD

**Issue by ironfroggy** [hydroshare/hydroshare#297]
https://github.com/hydroshare/hydroshare/blob/master/hydroshare/local_settings.py#L128

**Comment by mjstealey** [comment]
resolved once release-candidate branch is merged with develop

**Comment by ironfroggy** [comment]
Are you also changing the passwords and keys in that file everywhere? They'll still be in the repository history here.

**Comment by mjstealey** [comment]
Yes, changes will be made to all previously exposed data.

**Comment by mjstealey** [comment]
Working with Will Beeler for an alternative to hostgator which is being migrated away from. Until then password to be changed for all environments making use of the smtp server

**Comment by mjstealey** [comment]
Updated all public facing servers to use new configuration.
No longer use hostgator.
