### ISSUE TITLE
Raster resource created from iRODS is incomplete and does not count against quota

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#2970]
I created the resource https://www.hydroshare.org/resource/e4dba5ce4a974718907ff1506f7ef423/, by moving the file from iRODS.  

This does not count against my quota. 

A folder containing the .vrt file was created, but it is not symbolized like an aggregation.

**Comment by hyi** [comment]
@dtarb Incomplete aggregation sounds to me like an issue with either the tif file you are using or the aggregation code. For quota, want to point out that if you picked move option, your quota will not change since the old file in your user zone also counts toward your quota.

**Comment by phuongdm** [comment]
@hyi 

the problem is when a user uploads his files to home directory, in iRODS layer his usage will be updated but there is no change in HS layer

**Comment by hyi** [comment]
@phuongdm This is true - there is no notification built in yet to pick up quota changes from iRODS to HS Django if a user adds files using iRODS client to their user zone space. However, When a resource were created or any other actions that would trigger quota change, the quota values on iRODS AVU would be read by HS Django server to update the quota in HS. Let me know if you notice any problems with quota update except for this single notification issue from iRODS to HS Django which we already know about.

**Comment by dtarb** [comment]
I did some additional testing on this issue.  

Resources created from iRODS do not add to quota.  This occurs for both resources created from an internal irods instance (users.hydroshare.org) and external irods (data.iplantcollaborative.org).  Examples are
- https://www.hydroshare.org/resource/87e14b25627d49cf90a0bb16c0d77077/ this is 2 GB created from data.iplantcollaborative.org.
- https://www.hydroshare.org/resource/e4dba5ce4a974718907ff1506f7ef423/ this is 2GB created from users.hydroshare.org irods
- My quota consumption is reported as 0.0006 GB, so neither of these resources is counted.

@phuongdm and @hyi please look into the above and recommend how to resolve.

Aggregations (I only tested raster aggregations) automatically created from internal iRODS (users.hydroshare.org) are not created properly.
- https://www.hydroshare.org/resource/8760fb04c78548f9be58684741ddcc36/ was created using iRODS copy from users.hydroshare.org.  I selected the single file logan.tif.  HydroShare produced the folder logan, and the .vrt virtual file, but does not display the folder created using the raster aggregation icon.
- https://www.hydroshare.org/resource/1bf16cd6afa845da913d8c50a0c2fbe8/.  This was created loading logan.tif from a local PC and works properly, demonstrating that the problem is not the .tif file
- https://www.hydroshare.org/resource/8867e6fc6c5946579c072d558d56645d/.  This was created copying the single logan.tif file from external irods data.iplantcollaborative.org.  The resource is correct, indicating that the aggregation creation problem seems limited to files originating from a HydroShare irods.

@pkdash @sblack-usu @hyi please look into the above aggregation creation and recommend how to resolve.

**Comment by phuongdm** [comment]
@dtarb 

I and @hyi had a dicussion yesterday. Hong will develop a new REST API for this case then I could call the API from micro-services to notify to HS about files updated outside Django. That will solve this issue.

**Comment by hyi** [comment]
@dtarb I created this issue https://github.com/hydroshare/hydroshare/issues/2977 trying to close the loop on quota update,. As part of that work, @phuongdm and I will test this special case detailed in this issue to make sure quota update is working.

**Comment by hyi** [comment]
@dtarb I believe this has been working from a while back after Phuong updated his quota microservices to call a HydroShare REST API to update quota usage to handle this case where files are added into iRODS directly without going through HydroShare. I think this issue can be closed.

**Comment by dtarb** [comment]
Closing - taking @hyi word for it.
