### ISSUE TITLE
Confusing asterisk next to Temporal Start Date and End Date

### ISSUE THREAD

**Issue by Lizabrazil** [hydroshare/hydroshare#2972]
The asterisk next to the Start and End Date fields seem to indicate they are required fields, although they are not required. Users have assumed those are the only required fields.

**Comment by Lizabrazil** [comment]
![image](https://user-images.githubusercontent.com/13852599/47855545-46212400-ddbb-11e8-9022-6fe2e00aca61.png)

**Comment by cuahsimarko** [comment]
@mraocuahsi You can get clarification from Liza what page this is on and if it's intended to be "required" or not, meaning you can leave the asterisk or take it away. Backend changes may be required. We can chat after we ask Liza the intent here.

**Comment by cuahsimarko** [comment]
Note resource landing page doesn't have asterisks so wondering if this is still a thing
![image](https://user-images.githubusercontent.com/45397838/56307547-110f5080-6113-11e9-8c56-6db8abc80f85.png)

**Comment by Lizabrazil** [comment]
looks fixed!
