### ISSUE TITLE
Users are confused that they have to go into edit mode while viewing resources from their My Resources

### ISSUE THREAD

**Issue by Lizabrazil** [hydroshare/hydroshare#2973]
Users assumed that resources that they owned or had editing rights to (that they navigated to from My Resources) would open up in edit mode and would have an option to preview not in edit mode.

**Comment by horsburgh** [comment]
This is opposite of most web sites I have visited. Once content is created, when I access it, I get it in view mode. If I want to edit it, I choose to do so by clicking a button or link to enter an edit mode. Seems like this is a pretty well accepted pattern on the web.

The only one I can think of that is different is Figshare (I'm sure there are others out there). I think figshare opens items in edit mode until you choose to publish them - and then you can no longer edit them. So, they have a "preview" mode to show you what it will look like when it is published. Nobody can view a figshare dataset except the creator until it is published, so opening in edit mode is more reasonable. Given that HydroShare has more public view modes than figshare, and the fact that once something is shared or made public, other people can see it (even if they don't have edit rights), defaulting to view mode seems like the right thing to do.

**Comment by cuahsimarko** [comment]
I find this disorienting too and would prefer clicking on a resource goes into edit mode

**Comment by horsburgh** [comment]
So, if I click on a resource that I have edit access to it automatically goes into edit mode (even if I don't want to edit it), but if I click on a resource that I don't have edit access to I get totally different behavior? 

Editing is a deliberate action. I think we should keep it so.

**Comment by cuahsimarko** [comment]
@Lizabrazil did I misunderstand the user's intent in opening this ticket? My opinion counts for less, as I'm not a hydrologist

**Comment by horsburgh** [comment]
@cuahsimarko - certainly you don't have to be a hydrologist to have an opinion here. It's a pattern for how the site works. Your opinion is just as valid as mine.

**Comment by cuahsimarko** [comment]
@horsburgh I'm thinking more of an in-place edit, live edit mode.

**Comment by horsburgh** [comment]
@cuahsimarko - yeah, in place edit could provide some nice improvements although would probably be a pretty big change because we have two separate views now (view and edit). 

My concern is just making sure edits are deliberate - and, as a user, my immediate goal in accessing a resource is not always to edit it.

**Comment by Lizabrazil** [comment]
i take this back! I more recently learned about best practices with editing in context and yes I agree it should be a deliberate user action. I
