### ISSUE TITLE
create REST API endpoint for iRODS to notify HS quota update

### ISSUE THREAD

**Issue by hyi** [hydroshare/hydroshare#2977]
When files are added to iRODS user zone using an iRODS client, although iRODS has updated quota usage for the user, HydroShare does not know it. This REST API endpoint would allow iRODS microservice to call it  so that quotas in HydroShare can be updated accordingly for this special case.

**Comment by sblack-usu** [comment]
https://github.com/hydroshare/hydroshare/pull/3003

**Comment by phuongdm** [comment]
@dtarb, @sblack-usu and @hyi 

I've just tested new quota msi on beta. It works as expected: 
- Create a new resource with iRODS files (select Copy)
- Create a new resource with iRODS files (select Move)
- Use iCommand to upload/remove file on HS Federated User Zone

Note: when create a new resource, user's usage will be increased at least 5755 bytes for resourcemap.xml (3825 bytes) and resourcemetadata.xml (1930 bytes) even the resource has no file

Please let me know if any problem.

**Comment by hyi** [comment]
@phuongdm That is great to hear. You will have to update your iRODS rule to call the new quota usage update REST API to capture the third scenario in your list above, right? If that is the case, after the normal deploy of 1.18, we then need to create an iRODS service account in newly deployed HydroShare production instance, and update local_settings.py with corresponding iRODS service account username as well as your iRODS rule in order for the new iRODS quota update to work, right?

**Comment by phuongdm** [comment]
@hyi yes

**Comment by sblack-usu** [comment]
@phuongdm - could you add this to the deployment notes?

**Comment by dtarb** [comment]
Thanks.  It is perfectly fine to count resource*.xml files in the quota.

**Comment by phuongdm** [comment]
@dtarb , @hyi , @sblack-usu 

This issuse has been closed, however I did not install new quota msi into Production's iRODS User Zone server yet. Will do when upgrading it to 4.2.4. So, user usage counting still not correct in some cases

**Comment by sblack-usu** [comment]
sorry, that was me.  I must've closed it on accident while I was going through the issues in the Milestone.
