### ISSUE TITLE
HydroShare reports error unzipping a bag file it created

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#2978]
I created a resource, then downloaded the bag zip file, then uploaded the bag zip file into a new hydroshare resource.  When I attempt to unzip the bag zip file I get the following error.
![image](https://user-images.githubusercontent.com/3456833/47875456-382fcb00-dddc-11e8-83e1-08911e5cba57.png)

Note that the contents of the folder created by the unzip appear to be complete, so perhaps the error is a false alarm.

**Comment by sblack-usu** [comment]
I see the problem, but I already fixed this with some refactoring I did for overwrite... so this'll be fixed with 1.16.1

**Comment by sblack-usu** [comment]
@dtarb - try this out and beta and if you're satisifed, please close the ticket.

**Comment by dtarb** [comment]
Verified fixed on beta.

**Comment by sblack-usu** [comment]
good find.  This is a bug with the rename code.  if a file is sitting next to a folder that starts with the same name as the folder and you rename the folder, it'll try to move a bad path constructed by a naive regex that builds the destination. 

This code exits the loop and throws the error when the bad path is encountered, so there is the possibility of the rename not being reflected in django for every file, depending on the order it walks through the files

**Comment by sblack-usu** [comment]
Offending code for reference when this bug is worked on.

https://github.com/hydroshare/hydroshare/blob/develop/hs_core/views/utils.py#L756
