### ISSUE TITLE
Consider changing the term "Private" to "Limited" in the terminology surrounding access control

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#2986]
This is to open discussion on a terminology change that I think may improve the understanding of access control in HydroShare.  I suggest changing the label "Private" to "Limited" when referring to a resource access permissions status.  The reason for this is that private has a non open connotation and a resource shared with other people and other groups of people is no longer really private.  I do not suggest any change in implemented functionality, just the labeling and terminology.  I recognize that the term "private" is pervasive throughout HydroShare, so this is quite a consequential change, which is why, at this point this is just and idea I am floating for discussion.

I have written a draft update to the "Sharing and Privacy" help page that is in the following Google Document and substantiates this suggestion.
https://docs.google.com/document/d/1VjsNxXfs1OBXI0v4oAswYSZYmWhNv6sgY-yGbVDv3lU/edit#

In addition to changing the terminology, this documentation draft update attempts to clarify the workings of HydroShare a bit better and resolve some other points where there has sometimes been confusion.

I wrote this into a Google Doc, because I think a Google Doc is a better place to collaboratively edit than in a github issue.  If you have ideas or comments on this suggestion, feel free to edit the Google doc directly or write a comment here as you like.

**Comment by horsburgh** [comment]
I'm not sure this terminology change really helps. I think the concept of something that is shared privately (e.g., keep this between you and me) is pretty well established. In that respect, changing the word from "Private" to "Limited" doesn't really change anything but the word. What does matter are the words describing what "Private" or "Limited" mean with regard to functionality in the system.

**Comment by dtarb** [comment]
@horsburgh, please take a look at the writing in the current help pages about private, and then what I have drafted in the Google doc above.  I was helping with some writing explaining our terms to users and found that using the term "limited" seemed to make it easier to explain the functionality than using the term "private".  But if you can edit the writing to be clear and still use the term "private", then I am OK with that.  It just seemed to me that semantically saying that access was limited to specific users, or a group of users was clearer and easier to explain.

**Comment by dtarb** [comment]
Closing this - decided not to pursue this discussion further
