### ISSUE TITLE
Resource unsharing duplicate functionality

### ISSUE THREAD

**Issue by ndebuhr** [hydroshare/hydroshare#2987]
When sharing a resource, one can "undo" the share or "remove" the share.  These seem to serve the exact same purpose of unsharing a resource.  Is there any utility in having both?  The "X" icon for remove is intuitive, but the undo icon is unintuitive and doesn't have a tooltip.  A new use could think this is redo, undo, retry, etc..

[001.zip](https://github.com/hydroshare/hydroshare/files/2546898/001.zip)

**Comment by dtarb** [comment]
The X Icon removes that user from the resource being shared with them.  The Undo button reverses the last action for that person.  Behavior is thus not exactly the same.  There are however inconsistencies in the Manage Access interface.  Sometimes the drop down does not show all permission levels, and sometimes the undo button goes away.

**Comment by engineSound** [comment]
@Lizabrazil It is helpful for the UX team to review the usability issues as a whole.

**Comment by cuahsimarko** [comment]
@engineSound @Lizabrazil Looks like this is indeed separate functionality. If you agree, please close.

**Comment by cuahsimarko** [comment]
Maybe update support docs as well.
