### ISSUE TITLE
Old resource types can still be created through the REST API

### ISSUE THREAD

**Issue by kjlippold** [hydroshare/hydroshare#2991]
It's still possible to create old resource types like Generic and TimeSeries through the REST API.  This Python code will generate a Timeseries resource (not Timeseries content type).

```
import requests
from requests_toolbelt import MultipartEncoder


auth = requests.auth.HTTPBasicAuth(user, pass)

rest_url = "https://www.hydroshare.org/hsapi/resource/"

params = MultipartEncoder({
    "resource_type": "TimeSeriesResource",
    "title": "Total Bed Load Transport Rate at Big Wood River near Ketchum"
})

headers = {
    "content-type": params.content_type
}

response = requests.post(rest_url, data=params, headers=headers, auth=auth)

print response
print response.content
```

**Comment by dtarb** [comment]
This is important once we have migrated content to composite resources.  However there are Jupyter notebooks that may use this that need to be changed before this is done.

**Comment by cuahsimarko** [comment]
@sblack-usu does this belong in https://github.com/hydroshare/hs_restclient

**Comment by sblack-usu** [comment]
No, this belongs here.  We're still discussing when to turn off the ability to create other resource types via the api.

**Comment by Castronova** [comment]
@sblack-usu has this functionality been "turned off"?

**Comment by sblack-usu** [comment]
Sort of.  If you attempt to create a deprecated resource type, it will create a Composite.  The justification for this is is that the resource types have been migrated to aggregations and you can get the same functionality from the type as an aggregation within a composite resource.
