### ISSUE TITLE
HydroShare reference timeseries validation requires method link url

### ISSUE THREAD

**Issue by kjlippold** [hydroshare/hydroshare#2992]
HydroShare is expecting the method link parameter in the refts json file to always contain a valid url. Sometimes this parameter is unknown, but the file should still be treated as valid, so HydroShare should also accept either an empty string, or some predefined string like "Unknown" for the method link.

**Comment by pkdash** [comment]
@dtarb Let me know if you want me to work on this issue.

**Comment by dtarb** [comment]
Yes, please work on it.  @martinseul @horsburgh please comment on whether the "design is settled".  Is the solution @kjlippold offers above what we want to implement.  The ultimate goal is to have HydroShare be able to take in reference time series files from HydroClient, but format and requirements have to be agreed/reconciled.

**Comment by horsburgh** [comment]
MethodLink is an optional field in terms of the ODM1/ODM2 information models. I suspect that most data coming from the HydroClient will not have a value for MethodLink. A NULL value for this field should be acceptable. A value of "Unknown" is not a valid URL, so I would lean toward this field either containing a valid URL or NULL.

**Comment by danames** [comment]
OK so we discussed this on the call today. The plan is that @pkdash will modify the json file validation to allow any of the following three options: null, "unknown", valid URL. The word unknown can appear with any capitalization. This doesn't change anything in the data display, the full JSON file will still be displayed in the resource metadata.

**Comment by pkdash** [comment]
@danames Will have a PR ready soon.

**Comment by pkdash** [comment]
@kjlippold, @danames & @dtarb I have made the change for the new validation of the json file. You can test this new validation at testservices.hydroshare.org. A PR (https://github.com/hydroshare/hydroshare/pull/3036) has been created.

**Comment by pkdash** [comment]
@danames and @horsburgh Do we need to allow also empty string?

**Comment by sblack-usu** [comment]
@pkdash @horsburgh - A validation on valueCount broke the reftimeseries file I often use in testing.  My file has a valueCount of -1, which is no longer considered valid with the changes here.  This is more of a public service announcement than a request.  I know reftimeseries is still pretty fluid, but I wanted to bring this to your attention in case you hadn't considered it could break some existing reftimeseries.

https://github.com/hydroshare/hydroshare/blame/develop/hs_file_types/models/reftimeseries.py#L1035

**Comment by horsburgh** [comment]
@sblack-usu - is there an instance where a value count of -1 for a referenced time series is valid?

**Comment by sblack-usu** [comment]
no idea.  I'm not familiar with the specs for reftimeseries.

**Comment by kjlippold** [comment]
The schema at https://drive.google.com/drive/u/0/folders/0B8eTpsoVua0KWEp0eTBoSzlUbjg?ths=true <https://drive.google.com/drive/u/0/folders/0B8eTpsoVua0KWEp0eTBoSzlUbjg?ths=true> says the value count can be either an integer or null. I don’t think that would make negative values invalid, but I’d recommend using null if the value count is unknown, and a positive integer for anything else. I can update the schema to not allow negative integers.

WaterML has a value count field, but it’s often blank, so the resource creator app gets the value count from the length of the list of values in the time series. Because of that, the resource creator shouldn’t ever be able to create a referenced time series with a negative value count. Since the value count isn’t a WaterOneFlow parameter, having a negative value count shouldn’t break any other apps that use them, but the value wouldn’t really mean anything to a user.

- Ken Lippold

**Comment by pkdash** [comment]
As implemented now a json file with ValueCount of null or non-negative value is a valid json file.

**Comment by pkdash** [comment]
@kjlippold Can you test this issue on www and if has been resolved then close this issue?

**Comment by kjlippold** [comment]
Alright, I've tested it on www.hydroshare.org and method link will now be valid with either a url or null value as defined in the schema found here: 
https://drive.google.com/drive/u/0/folders/0B8eTpsoVua0KWEp0eTBoSzlUbjg
