### ISSUE TITLE
repair_resource doesn't repair composite resources 

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#2997]
Repair of resources doesn't yet work properly for composite resources and cannot currently be safely used.

**Comment by martinseul** [comment]
@alvacouch review and act as needed

**Comment by alvacouch** [comment]
Remains an issue. There is currently no comprehensive "repair" for composite resources that get out of sync with their IRODS files.

**Comment by devincowan** [comment]
Perhaps resolved by https://github.com/hydroshare/hydroshare/pull/5412
