### ISSUE TITLE
Develop metadata editing for generic resource.   

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#3]
Metadata editing on generic resource landing page with science metadata consistent with spec.

The resource landing page should appear after a resource is created.  This functionality to serve as a template that can be encapsulated in the pages for specific resource types which will have additional metadata elements added.

**Comment by rayi113** [comment]
HydroShare Generic Resource Issues in GitHub: #3, #57, #75

**Comment by dtarb** [comment]
Implemented and tested at Alpha v1.3
