### ISSUE TITLE
ReCaptcha Must be Verified by Server

### ISSUE THREAD

**Issue by ironfroggy** [hydroshare/hydroshare#300]
Right now, the ReCaptcha implementation is ineffective at deterring automated signups. The server never verifies the racaptcha result, it is only handled within the browser. This is not secure because you do not have control within the browser, and any automation attack would not be likely be done via a browser anyway, but making a registration request to the appropriate URL directly.

**Comment by horsburgh** [comment]
I think the ReCaptcha should go away entirely.

**Comment by dtarb** [comment]
@ironfroggy please recommend what needs to be done to resolve this.

**Comment by ironfroggy** [comment]
I'd like to fix this as soon as I can push filtering through. What is needed is for the backend, after submitting the reCAPTCHA and the form, to validate that the user did, indeed, pass the reCAPTCHA. There is a Python library from the reCAPTCHA project that can do that. reCAPTCHA sends challenge/response fields back to your server and you pass these along to reCAPTCHA to confirm they match. Unfortunately, their library isn't well documented, but here's a StackOverflow post that outlines the relatively simple usage:

http://stackoverflow.com/questions/1440239/how-to-use-python-plugin-recaptcha-client-for-validation

**Comment by hyi** [comment]
@ironfroggy Based on your comment above that you'd like to fix this as soon as you could push filtering through, I am wondering whether you still plan to do so perhaps after you finish base resource refactoring. @dtarb asks me to look through issues related to account creation and try to resolve them, so I want to get your take on this issue, specifically, whether you want to work on it or I can work on it while consulting you on issues I run into since I never had experience on this.

**Comment by dtarb** [comment]
Can you please check with @horsburgh on this issue.  I think he has some specific ideas.  I have divided up the issues into categories and delegated managing issues to a category manager.  See https://github.com/hydroshare/hydroshare/wiki/Team-and-Managers-for-Issues.  You @hyi  are the manager for issues labeled clean up.  @horsburgh is the manager for issues labeled Appearance as this one is, as @mauriel133 is doing a lot of the UI front end.  So before jumping in and working on it, at least coordinate with @horsburgh . 

Also, I've asked to have a coordination call between @robline and @horsburgh .  This has not been scheduled yet.  With Oauth drawing to a close, I am hoping that @robline can help with some of these user profile issues (and creating an account creates a user profile).  @ironfroggy has his hands full with the refactoring at the moment.

So, while I certainly do not want to slow things down and dissuade you from fixing this.  Just let @horsburgh know and see what he says.

**Comment by hyi** [comment]
@horsburgh as decided in Monday's planning meeting, I was going through issues on account creation and UI appearance listed in https://docs.google.com/spreadsheets/d/1MGz60mQDowAiqRUYvABf84JzJBhYPX9Iz_ggrVj3Rms/edit#gid=0 and see whether there are any issues I can work on that have not been assigned to anyone. In addition to one issue [#223] that has already been assigned to me which I will look into, a few other profile-related bug issues, namely, [#180], [#300], [#44], and [#27], have not been assigned to anyone as well as five enhancement issues related to profiles (as noted in the release planning document). I guess enhancement issues can wait after bugs are fixed. It'd be good if you can assign to @mauriel133 any unassigned issues @mauriel133 can take care of. @dtarb @horsburgh @robline I don't plan (and certainly will not jump in) to work on any unassigned issues unless there is an agreement to assign the issues to me. I think it'd be great if @robline can help out with some of these user profile issues. Just assign issues to me as you see fit if you want me to work on any of these issues.

**Comment by ironfroggy** [comment]
@hyi yes i still think this should be addressed, but there have also been other changes to the sign up page since then. you should re-verify the problem still exists.

**Comment by horsburgh** [comment]
@hyi - have you looked at this issue enough to be able to verify that the problem still exists (and if so, fix it)?  

Earlier, I had some thoughts about how we could potentially change the sign-up/log-in process (in particular I'm not really fond of the re-captcha). I was going to assign this to @mauriel133 to work on, but there are so many other things to work on right now that I think we should just verify that the sign-up/log-in process we have now works correctly and move on to other things. I think it's good enough.

**Comment by hyi** [comment]
@horsburgh Just looked into this issue and believe this problem does not exist any more. Specifically, the captcha is verified on the server as shown in verify_captcha() view function here: https://github.com/hydroshare/hydroshare/blob/develop/hs_core/views/__init__.py#L345, so it appears to me captcha is verified both on client and server side. @ironfroggy could you confirm and close this issue if you agree it does not exist any more?

**Comment by dtarb** [comment]
@ironfroggy this has sat for a while.  Others think this is done, but could you please verify and if there is a security issue clarify what still needs to be done.

**Comment by ironfroggy** [comment]
Has been done and merged
