### ISSUE TITLE
Invalid username/email error message improvement

### ISSUE THREAD

**Issue by Lizabrazil** [hydroshare/hydroshare#3001]
For a user that tries to create an account for a second time mistakenly, the error message just says "invalid', it would be more helpful it said "username or email already exists"

![image](https://user-images.githubusercontent.com/13852599/48288909-b5da8300-e43b-11e8-8427-5bf7f561e4ec.png)

**Comment by dtarb** [comment]
@Lizabrazil That message is correct.  The user is submitting an invalid username and password in an attempt to log in.  There is a link lower down to reset the password.

If you attempt to create an account with an existing username you get the message below.
![image](https://user-images.githubusercontent.com/3456833/48289449-c6373180-e42c-11e8-87fb-53e734824b83.png)

If you attempt to create an account with an existing email address you get
![image](https://user-images.githubusercontent.com/3456833/48289521-0bf3fa00-e42d-11e8-9d7b-f158ecb2e803.png)

I would be supportive of changing the above white messages to red, so they are less likely to be missed.  I would also be supportive of changing the wording if you provide explicit improved wording and @engineSound is able to do this change.

**Comment by Lizabrazil** [comment]
Yep, thanks Dave. I realized this. I do think consistent error message with red banner and red text is the way to go. The text is fine.

**Comment by engineSound** [comment]
The error message should be delivered from backend. The front end should not remember the number of login attempts.

**Comment by engineSound** [comment]
I reproduced the issue. The error message for re-sign-up with the same email is correct. The font color should be red. I will move ahead to fix the frontend styling issue.

**Comment by engineSound** [comment]
I am wondering why we allow an error message to be closed. An error message should stay on the page until a further form submission.

![2019-01-11_16-55-29](https://user-images.githubusercontent.com/35352595/51061605-d224a880-15c1-11e9-9a9d-7712a95a8ed8.png)

**Comment by engineSound** [comment]
I thought it would be just a line code change.  After digging into the code, I found more than what I originally thought. The message box we are
referring to is a generic message box that has been used as a vehicle to deliver messages without
differentiating an error or information. For example, it is used to deliver a message like  "Successfully logged in - Your quota for
HydroShare resources is 20.0GB in hydroshare zone. You currently have resources that consume 0.0GB,
0.0% of your quota. Once your quota reaches 100% you will no longer be able to create new resources
in HydroShare."

I am ok to continue to look for solutions but think it is better to allocate effort to fix other high priority issues.

**Comment by engineSound** [comment]
@Maurier do you have anything to add to the conversation? 
@Lizabrazil @dtarb S

**Comment by martinseul** [comment]
@Lizabrazil  can you please weigh in if this needs to be fixed or put into the 'do not fix bucket'

**Comment by cuahsimarko** [comment]
@martinseul my understanding of the 'do not fix' bucket is the Delete button

**Comment by Lizabrazil** [comment]
@cuahsimarko I think you can close this if it is a large effort. Ultimately, we need a design pattern library where we can be consistent across the entire website, for instance when it comes to feedback messages.

**Comment by cuahsimarko** [comment]
Larger issue here: https://github.com/hydroshare/hydroshare/issues/976
