### ISSUE TITLE
Deploy iRODS replica on AWS S3

### ISSUE THREAD

**Issue by rayi113** [hydroshare/hydroshare#3008]
Deploy iRODS disaster recovery solution on AWS.  @cbcunc has created an AWS instance with iRODS installed for this purpose in the HydroShare AWS account at RENCI and will work with @phuongdm to deploy.  Here is the plan:

 - [ ] Make a backup copy of the hydroshareZone iCAT
 - [ ] Schedule 1 hour of HydroShare downtime
 - [ ] Create an iRODS UFS (unix filesystem, i.e. not S3) resource server on AWS called hydroAWSResc
 - [ ] Add hydroAWSResc as a child of hydroshareReplResc in  hydroshareZone 
 - [ ] Trigger an iRODS rebalance operation of hydroshareReplResc that will ensure that hydroshareReplResc has two replicas: one under mdcRRResource and one under the hydroAWSResc
- [ ] Verify the hydroAWSResc resource is operational and stable as the new HydroShare disastery recovery solution 
 - [ ] Conclude downtime
 - [ ] Make a backup copy of the hydroshareZone iCAT
 - [ ] Find and unregister all data-at-rest on mdcRRResource from the hydroshareZone iCAT
 - [ ] Schedule 1 hour of HydroShare downtime
 - [ ] Set the iRODS status of mdcRRResource and its two leaf nodes to down
 - [ ] Permanently remove the mdcRRResource resource from hydroshareZone
 - [ ] Test and verify that powering down the Dell 730xd boxes does not bring the HydroShare website down
 - [ ] Conclude downtime

Two separate downtimes are scheduled to make sure the AWS solution is working satisfactorily and contains a full valid replication of hydroshareZone before taking the former mdcRRResource replication server offline.

**Comment by cbcunc** [comment]
In process of revising this to reflect plan previously sent to Mark, @phuongdm, @dtarb, @martinseul, and @rayi113 on 7/25/18 as well as additional details supplied by the iRODS team concerning itrimming the existing replicas at https://docs.irods.org/4.2.4/system_overview/tips_and_tricks/#decommissioning-a-storage-resource.
