### ISSUE TITLE
Registration does not verify email address

### ISSUE THREAD

**Issue by ironfroggy** [hydroshare/hydroshare#301]
It allows me to register with an email address that is not valid and which could never receive the verification email.

**Comment by dtarb** [comment]
Thanks for pointing this and #300 out.  Can we have a concerted push/sprint to fix these.  Problems with our sign ups and sign ins have gone on too long and are frankly embarrassing.  @ironfroggy I hate to be reassigning priorities all the time but can you please make it a high priority to sort this out.

**Comment by dtarb** [comment]
I think this issue is fixed.  @ironfroggy can you please check it and if you agree close this. I am not sure exactly what you did to register with an invalid email.

**Comment by ironfroggy** [comment]
Fixed by previous changes to registration form
