### ISSUE TITLE
Invite people modal uses odd button styling

### ISSUE THREAD

**Issue by ndebuhr** [hydroshare/hydroshare#3014]
Fixes #3014

**Comment by ndebuhr** [comment]
[181120_181120_test-env.txt](https://github.com/hydroshare/hydroshare/files/2598571/181120_181120_test-env.txt)

**Comment by cuahsimarko** [comment]
If you have questions about layout, you can ask @Lizabrazil , though Neal's suggestion seems good.

**Comment by mraocuahsi** [comment]
![Screenshot from 2019-04-19 09-20-57](https://user-images.githubusercontent.com/49655428/56426629-f827ac00-6286-11e9-935c-28f9ec2b96b8.png)
In Chrome it is looking fine. 
@ndebuhr @cuahsimarko

**Comment by mraocuahsi** [comment]
Chrome and Firefox screenshots . 
@ndebuhr @cuahsimarko 
![Chrome](https://user-images.githubusercontent.com/49655428/56427404-bba97f80-6289-11e9-92ca-35e9b4aed7d2.png)
![Firefox](https://user-images.githubusercontent.com/49655428/56427405-bc421600-6289-11e9-82c6-4627f962d6ed.png)
