### ISSUE TITLE
Moderately long group names without spaces causes display problems

### ISSUE THREAD

**Issue by ndebuhr** [hydroshare/hydroshare#3015]
Moderately long group names without spaces causes display problems

[003.zip](https://github.com/hydroshare/hydroshare/files/2598536/003.zip)

**Comment by ndebuhr** [comment]
[181120_181120_test-env.txt](https://github.com/hydroshare/hydroshare/files/2598573/181120_181120_test-env.txt)

**Comment by Lizabrazil** [comment]
not completed yet

**Comment by Lizabrazil** [comment]
![image](https://user-images.githubusercontent.com/13852599/56321475-bedf2700-6134-11e9-80a9-4267c74ab5e3.png)

**Comment by cuahsimarko** [comment]
@mraocuahsi can you have another look?

**Comment by cuahsimarko** [comment]
@Lizabrazil Ok I think it was just a git issue. It hopefully just won't be an issue in the future 
![image](https://user-images.githubusercontent.com/45397838/56369701-da474200-61c7-11e9-9b97-2e3e238967d2.png)

approved
