### ISSUE TITLE
Checkboxes are not vertically centered on discover page

### ISSUE THREAD

**Issue by ndebuhr** [hydroshare/hydroshare#3019]
The checkboxes are not vertically centered on the discover page filter options - the result is a messy appearance.

[007.zip](https://github.com/hydroshare/hydroshare/files/2598548/007.zip)

**Comment by ndebuhr** [comment]
[181120_181120_test-env.txt](https://github.com/hydroshare/hydroshare/files/2598578/181120_181120_test-env.txt)

**Comment by Maurier** [comment]
This appears to be fixed in Chrome and Firefox. Could someone confirm if this still happens in Safari?
![image](https://user-images.githubusercontent.com/2448568/52015542-730ad300-249f-11e9-9ed9-2e512dbf4b4c.png)

**Comment by hydrocheck** [comment]
Issue resolved as a part of the Discover redesign
