### ISSUE TITLE
The recenter button blocks other UI elements in the "Coverage" part of the resource detail page.

### ISSUE THREAD

**Issue by ndebuhr** [hydroshare/hydroshare#3020]
The recenter button blocks other UI elements in the "Coverage" part of the resource detail page.  For example https://beta.hydroshare.org/resource/55c30255450e4f19825e9a5eee0e89ab/

[008.zip](https://github.com/hydroshare/hydroshare/files/2598549/008.zip)

**Comment by ndebuhr** [comment]
[181120_181120_test-env.txt](https://github.com/hydroshare/hydroshare/files/2598580/181120_181120_test-env.txt)

**Comment by Maurier** [comment]
This was fixed as part of #3064. I'd like to add that Google Maps API can potentially introduce breaking changes like this one again in the future. A possible fix would be to choose a version, keep an eye on their releases, and upgrade as necessary (they do stop serving old versions).

> Specify a version by number only if you regularly test and update your application. This is because numbered versions are eventually deleted as new versions are created every quarter.

from: https://developers.google.com/maps/documentation/javascript/versions
