### ISSUE TITLE
Required label for comment text field is not styled well

### ISSUE THREAD

**Issue by ndebuhr** [hydroshare/hydroshare#3021]
There is a "required" text label below the comment text field.  There is only one field - is it really necessary to note this is required?  Comment text intuitively seems necessary to post a comment - especially with the lack of any other fields.  If we do keep the required note, it should probably be handled in a more conventional way (e.g. with the *, or perhaps could be validated after user submission/editing).

[009.zip](https://github.com/hydroshare/hydroshare/files/2598551/009.zip)

**Comment by ndebuhr** [comment]
[181120_181120_test-env.txt](https://github.com/hydroshare/hydroshare/files/2598582/181120_181120_test-env.txt)

**Comment by Maurier** [comment]
This was fixed as part of #3064

**Comment by cuahsimarko** [comment]
![image](https://user-images.githubusercontent.com/45397838/56602956-a3f53280-65cc-11e9-9162-b0f6722634ed.png)
