### ISSUE TITLE
"hidden" buttons on resource landing page are "pressed" by web spiders

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#3022]
@martinseul @sblack-usu 

In release 1.17, it was discovered that buttons that are hidden by javascript code are actually being pressed by web spiders in an attempt to discover content. This leads to disturbing errors in the log files, including permission denied for deleting resources! Fortunately, the backend traps and denies these actions, but having them present in the HTML at all is poor UI design for a public-facing landing page. 

The solution is to cause these buttons to disappear at the template level -- using template conditionals -- rather than at the javascript/html level, so that they cannot be "pressed" by spiders.

**Comment by Maurier** [comment]
@sblack-usu, @alvacouch  Thanks for bringing this to my attention. I'll include this in my work for the page redesign this week. I will be pinging you later for more details.

**Comment by Maurier** [comment]
This was fixed as part of #3064

**Comment by Maurier** [comment]
@alvacouch, could you confirm this fix and close if it looks right?
