### ISSUE TITLE
iRODs - Add File to Resource Fails

### ISSUE THREAD

**Issue by Castronova** [hydroshare/hydroshare#3030]
When creating a new resource I'm able to add files from my iRODs userspace. However when adding files from iRODs to an existing resource, I get the following error:

![image](https://user-images.githubusercontent.com/4822372/49162789-a7281300-f2f9-11e8-8cf9-346e81cde370.png)

**Comment by hyi** [comment]
@Castronova @dtarb The fix to this issue has been merged into develop and @sblack-usu is in the process to update beta for further testing. I did manually update beta to verify this fix, but it'd be nice if you can verify also on beta since you have a test resource handy to test.

**Comment by sblack-usu** [comment]
Beta deploy is finished.

**Comment by hyi** [comment]
@Castronova @dtarb The fix has been deployed to www as part of 1.18 release. I have just tested it out on www and it works now. Please test it out as well on www and close this issue if it works for you as well.

**Comment by dtarb** [comment]
Closing as partly fixed on www - but see #3069
