### ISSUE TITLE
Information button on Discover page - styling issues

### ISSUE THREAD

**Issue by ndebuhr** [hydroshare/hydroshare#3046]
This "i" button on the discover page is pressed up against the search window (no padding for a cleaner interface) and also opens to a modal which overlaps with the top menu.  Depending on the device/view, some of the modal text may not be visible.

This seems like a top candidate for some UI work.

[001.zip](https://github.com/hydroshare/hydroshare/files/2683196/001.zip)

**Comment by dtarb** [comment]
This appears to now be fixed, so closing 
![image](https://user-images.githubusercontent.com/3456833/55236346-4e0fb380-51f5-11e9-9537-feb584ea64b6.png)
