### ISSUE TITLE
Content metadata display issues on resource detail page

### ISSUE THREAD

**Issue by ndebuhr** [hydroshare/hydroshare#3048]
When content doesn't have associated content metadata, then the same message shows up as if no content was selected.  Namely, "Select content in the file browser to see metadata specific to that content. Metadata will only display here when the the content is selected above. Content specific metadata does not display on the Discover page."  A message like "The selected content does not have content metadata" would seemingly be much better from a UX perspective and would minimize user confusion.

[003.zip](https://github.com/hydroshare/hydroshare/files/2683198/003.zip)

**Comment by martinseul** [comment]
Fixed. Closing issue
