### ISSUE TITLE
Content metadata can be slow to load

### ISSUE THREAD

**Issue by ndebuhr** [hydroshare/hydroshare#3049]
Content metadata can be slow to load.  It looks like there is no cache/preloading - the content metadata query only runs when the user clicks on the content.  If an asyncronous approach (implemented upon initial page load) was used, it could seemingly improve UX.  It is likely that users clicking through files could miss content metadata, simply because they are clicking through the files and it is taking too long to load.  At the least, it would be nice to replace the "no metadata" message with a blank screen during load (so the user is presented with no message, instead of the wrong message).  I'm not sure if internet speed is a substantial factor here, but note the 90 Mpbs download in the test-env file.  If it is a substantial factor (seems unlikely, but I don't know), then the delay times could be exacerbated for lower speed user environments.

[004.zip](https://github.com/hydroshare/hydroshare/files/2683200/004.zip)

**Comment by martinseul** [comment]
@ndebuhr. This seems to be fixed or NA as the implementation has changed. Closing, please reopen if still needed
