### ISSUE TITLE
Poor error handling for empty file

### ISSUE THREAD

**Issue by ndebuhr** [hydroshare/hydroshare#3051]
If the user uploads an empty .bmp, a non-descript error comes up - "Error!".  Further, the error message is duplicated for each of the files uploaded, even if only one of the files fails to upload, and the others are fine.  So if a user uploads 300 files, and only one of them has an poorly-handled error (in this case, the empty bmp), then the user will be presented with 300 instances of "Error!"

[006.zip](https://github.com/hydroshare/hydroshare/files/2683203/006.zip)

**Comment by martinseul** [comment]
@ndebuhr. This seems to be fixed or NA as the implementation has changed. Closing, please reopen if still needed
