### ISSUE TITLE
No timezone specification in user interfaces

### ISSUE THREAD

**Issue by ndebuhr** [hydroshare/hydroshare#3052]
Resources are created, organized, and listed, based on UTC.  For example, Discover page table, My Resources table, and resource detail pages.  However, there's no obvious spot in any of the interfaces where this is noted to the user.  

[007.zip](https://github.com/hydroshare/hydroshare/files/2683204/007.zip)

**Comment by ClaraCogswell** [comment]
Close: duplicate
