### ISSUE TITLE
Long subject keyword causes silent fail

### ISSUE THREAD

**Issue by ndebuhr** [hydroshare/hydroshare#3053]
After about 100 characters, subject keywords fail to add on the resource detail page.  An visible error or some kind of user feedback would be ideal here.  Please see the video.

[008.zip](https://github.com/hydroshare/hydroshare/files/2683205/008.zip)

**Comment by mraocuahsi** [comment]
Duplicated by :

https://github.com/hydroshare/hydroshare/issues/3053

**Comment by mraocuahsi** [comment]
Duplicate : 

#3224

**Comment by cuahsimarko** [comment]
I am still able to reproduce this long keyword silent failure. Also, there is a styling issue: 
![image](https://user-images.githubusercontent.com/45397838/59707256-42b69d80-91d0-11e9-8825-aaaaab2197b8.png)

**Comment by cuahsimarko** [comment]
Just need to update the template formatting in the error message. Otherwise, now the error is caught

![image](https://user-images.githubusercontent.com/45397838/63282325-956a0f80-c27c-11e9-8ffe-c55af10c1e20.png)
