### ISSUE TITLE
Capitalization inconsistency across resource tables

### ISSUE THREAD

**Issue by ndebuhr** [hydroshare/hydroshare#3054]
In the My Resources table, there is a "Last modified" column.  This should be changed to "Last Modified" to match the style of all other columns on both the My Resources and Discover tables.

[009.zip](https://github.com/hydroshare/hydroshare/files/2683206/009.zip)

**Comment by cuahsimarko** [comment]
@mraocuahsi you can link this to the work you did _if it fixes it_. Add it to the GitHub Description with Fixes ....

https://github.com/hydroshare/hydroshare/pull/3325

![image](https://user-images.githubusercontent.com/45397838/56307044-fdafb580-6111-11e9-9451-b7f0f5aac6e5.png)

**Comment by Lizabrazil** [comment]
approved 
![image](https://user-images.githubusercontent.com/13852599/56322107-2f3a7800-6136-11e9-8b03-e5d846fd44a5.png)
