### ISSUE TITLE
Deleting irods user generates cryptic error

### ISSUE THREAD

**Issue by ndebuhr** [hydroshare/hydroshare#3055]
When deleting an irods user, the interface shows a cryptic error (but the operation is successful).  Please see video.

[010.zip](https://github.com/hydroshare/hydroshare/files/2683207/010.zip)

**Comment by hyi** [comment]
@ndebuhr I believe I have fixed this issue not long ago. Could you check again when you have a chance to verify this problem is indeed fixed?
