### ISSUE TITLE
Add backend library for user dashboard

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#3059]
@horsburgh @dtarb @martinseul @Maurier 
To enable the new "dashboard" functionality, we need a set of back-end routines that

* report the last changes and modifications to a user's followed resources. 
* report access to user's published resources. 
* report which recently added resources might be of interest to the user. 

These backend functions should return a list of resource id's and/or details.  This is the first step in building a UI for this data in hydroshare

**Comment by alvacouch** [comment]
Details of issue: #2592 gives a framework for these commands that is implemented in branch 2592-recommendations-2. This branch needs to be modified to be more friendly in order to build UIs. The principal routines from 2592-recommendations-2 are found in the file [features.py](https://github.com/hydroshare/hydroshare/blob/2592-recommendations-2/hs_core/hydroshare/features.py) 

A UI for this is found in [hs_explore](https://github.com/hydroshare/hydroshare/tree/2592-recommendations-2/hs_explore) 

The main code for generating recommendations is in [recommend.py](https://github.com/hydroshare/hydroshare/blob/2592-recommendations-2/hs_explore/management/commands/recommend.py)

The tasks involved in this include: 

1. Generate a new branch 3059-dashboard-support that starts from 2592-recommendations-2. 
2. Merge in changes from develop and rebase. 
3. Generate more friendly routines for the user dashboard based upon functions in [features.py](https://github.com/hydroshare/hydroshare/blob/2592-recommendations-2/hs_core/hydroshare/features.py) . 
3. Write tests for these routines using the nosetest framework. Place these tests into [hs_core/tests/api/native](https://github.com/hydroshare/hydroshare/tree/2592-recommendations-2/hs_core/tests/api/native)
4. Write user documentation for using these commands in a dashboard. You can do this in the inline comments that are allowed for every routine. 

Please see @xuezhaokun for details on how this works.

**Comment by martinseul** [comment]
completed, Closing
