### ISSUE TITLE
Eliminate lost file botches in uploading and deleting large numbers of files. 

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#3061]
@mseul @Lizabrazil @cuahsimarko @dtarb @engineSound 
There are several ways in which a long-running Django request can be interrupted. These include pressing the "back" button and Django timeouts. At present, file ingestion and deletion is subject to these interruptions, leading to file integrity failures in which Django and iRODS disagree on the presence of files. This is most likely with an upload request that uploads large numbers of small files, or a deletion request for a large number of files. 

Symptoms are different for the two kinds of interruptions:

1. File upload interruptions leads to files that are present in iRODS but not in Django. This is because sending them to iRODS is nearly instant but ingesting them into Django can take considerable time. 

2. File deletion interruptions lead to files that are present in Django but not in iRODS. This is likewise because iRODS deletion is nearly instant but deleting files from Django can take considerable time. 

This is unrelated to uploading and downloading of "large files". This instead affects requests that act on large numbers of (typically small) files. 

The user symptoms of this are that files (or even whole resources) that are deleted are still present in Django after they disappear from iRODS, while files that are uploaded disappear from the UI but are invisibly still present in iRODS. The user perceives an upload botch as a failed upload, but the upload consumes quota. The user perceives the deletion of a resource as unsuccessful, but the resource doesn't contain any data. 

The proposed solution for this is to make uploads and deletions of large numbers of files uninterruptible, by backgrounding the process of ingesting the files. This means -- to the user -- that the resource is unavailable while an upload is in process. 

At present, the only way to deal with such integrity problems is via the management commands `check_resource` and `repair_resource`. These commands indicate when there are problems and try to repair them. However, it would be considerably better if these problems could not occur.

**Comment by alvacouch** [comment]
In some cases the symptoms of this are serious enough to completely break the UI for the resource.

**Comment by dtarb** [comment]
@alvacouch thanks for sorting this out.  I was a bit unclear what the meaning of "the resource is unavailable while an upload is in progress" is, or how it would manifest.  What if a user (even separate user) hits the resource landing page during this operation (from a separate browser tab or window or computer).  What happens.  What about if the landing page is already open, while actions are happening from another browser.

**Comment by alvacouch** [comment]
@cuahsimarko See https://docs.google.com/document/d/1KvtdBfZcQ6kaftnupali-5_Osi7NtA3DyVtxK6pxB0s/edit?usp=sharing for detailed notes on where problems occur in the code.

**Comment by alvacouch** [comment]
@dtarb @Lizabrazil It will look like the resource is still uploading files, which it actually is. The spinner will continue. However, the user can do other things while this is happening, including working with other resources. If you browse back to the resource while it is -- e.g. -- still uploading 1000 files, the spinner will return to tell you that an operation is still in progress. This spinner will also appear during other time consuming operations, including, e.g., unzip zipfile into resource. It will persist as long as the operation is running, and will disappear when the operation completes. Since these operations can take considerably longer than a Django request -- which is the root of all evil -- the spinner will persist through multiple user commands until the operation is done. During this time, the file interface will remain unavailable, but the user can do other things.

**Comment by cuahsimarko** [comment]
I'm removing myself for now as we were unable to reproduce and there are still some unknowns as to root cause.

**Comment by martinseul** [comment]
@alvacouch tagging you as it part of large file handling and async

**Comment by alvacouch** [comment]
Addressed via asynchronous operations.
