### ISSUE TITLE
Honest problem messaging

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#3067]
There was a crash and reboot of HydroShare today - unplanned.  I happened to try access a resource at the time and noticed first

Bad Gateway 502 Nginx error, then when it was rebooting, the message below
"We'll be back soon! "  We're performing some maintenance.  I feel that we should not say we are performing maintenance when we are not.  We should be honest that there is a problem.  I suggest changing the page to

"Sorry, there is an unexpected problem with HydroShare.  The systems operation team has been notified and will address the problem as soon as possible.  Sorry for the inconvenience.  Contact help@cuahsi.org if you need further information."
The HydroShare team.

It would be better if this page could show for both Nginx and other system problems.

The performing maintenance message is OK when we are actually performing and upgrade.  However, I suggest changing the wording to
"HydroShare is offline for maintenance or upgrading.  The maintenance is scheduled to be complete by \<date and time>.  Sorry for the inconvenience.  Contact help@cuahsi.org if you need further information.
The HydroShare team

![image](https://user-images.githubusercontent.com/3456833/50248540-9880c900-0398-11e9-9928-4dd665cd7cd1.png)

**Comment by dtarb** [comment]
Can we please implement this honest messaging.  @martinseul

**Comment by zhiyuli** [comment]
I am still getting a nginx 502 bad gateway error.

**Comment by dtarb** [comment]
@martinseul given the down time today, I would like to make another plug for doing this.  Is this easy to do.  Could @hyi do this?

**Comment by ClaraCogswell** [comment]
Did this get done? @martinseul It seems like it has been done

**Comment by martinseul** [comment]
I don't think so, @devincowan would you please take a looks should be straight forward
