### ISSUE TITLE
Error raised when uploading a bad tif file for raster resource type

### ISSUE THREAD

**Issue by hyi** [hydroshare/hydroshare#307]
This issue results from raster resource type testing by Tian who found error being raised when uploading a bad tif file for raster resource type. Have added validation to address this issue. Will create a pull request shortly to have my fix merged into develop.

**Comment by dtarb** [comment]
@gantian127 please test on alpha.hydroshare.org and close if fixed

**Comment by gantian127** [comment]
It works without showing error info page. The system recognizes the bad tif file as an incomplete tif file and populate the metadata with "NA" value.
