### ISSUE TITLE
Migrate Model Instance resource type

### ISSUE THREAD

**Issue by jsadler2** [hydroshare/hydroshare#3070]
Migrate `Model Instance` resource type. 

Subticket of #2959

**Comment by jsadler2** [comment]
branch for this issue: https://github.com/uva-hydroinformatics/hydroshare/tree/3070-migrate-model-instance

**Comment by pkdash** [comment]
The management command for migrating model instance resources has been deployed as part of release 1.53. However, the migration command has not be executed on production. This issue will be closed once we run the management command to migrate model instance resources on prod.

**Comment by pkdash** [comment]
This migration has been done on prod - so closing.
