### ISSUE TITLE
Migrate Model Program resource type

### ISSUE THREAD

**Issue by jsadler2** [hydroshare/hydroshare#3071]
Migrate `Model Program` resource type to a file type of composite resource.
Subticket of #2959

**Comment by cuahsimarko** [comment]
duplicates https://github.com/hydroshare/hydroshare/issues/3070

**Comment by dtarb** [comment]
Model program and model instance are different.

**Comment by pkdash** [comment]
The management command for migrating model program resources has been deployed as part of release 1.53. However, the migration command has not be executed on production. This issue will be closed once we run the management command to migrate model program resources on prod.

**Comment by pkdash** [comment]
This migration has been done on prod. So closing.
