### ISSUE TITLE
Spam resources in Hydroshare - production and beta

### ISSUE THREAD

**Issue by ndebuhr** [hydroshare/hydroshare#3078]
Consider removal of the following.  Beta and prod separated into different csv files
[spam-in-prod-and-beta.zip](https://github.com/hydroshare/hydroshare/files/2730166/spam-in-prod-and-beta.zip)

**Comment by ndebuhr** [comment]
A few more:
https://www.hydroshare.org/resource/fba6ea82e89648be9211e07d86a33cc4/
https://beta.hydroshare.org/resource/47eb669191214722a878a4f16fb88b11/
https://beta.hydroshare.org/resource/def0ed878c844affa2fbb4899d7dbd2e/

**Comment by danames** [comment]
Someone needs to remove these asap. More importantly, how can we avoid getting these types of resources in the future? Maybe it's impossible. The creators of these resources would have to have manually created their accounts and these resources, right? There's no way for them to automate creating spam resources?

**Comment by hyi** [comment]
@danames Account creation involves manual step - the account creation has to sign up and then click on a link with random token string to confirm and activate the account. However, after the spammers had created accounts, they could be used to create spam resources programmatically using REST API.

**Comment by Lizabrazil** [comment]
all listed here are removed.
