### ISSUE TITLE
Editing name in profile throws in an incorrect message

### ISSUE THREAD

**Issue by Lizabrazil** [hydroshare/hydroshare#3079]
I tried to edit my name in my profile to have uppercases and it said "email already in use" and didn't work.

![image](https://user-images.githubusercontent.com/13852599/50779119-86929780-126d-11e9-923c-a3bd159fe3c5.png)

**Comment by Lizabrazil** [comment]
it worked on the second try... but i still see this as an issue if it can be replicated.

**Comment by cuahsimarko** [comment]
Unable to reproduce
