### ISSUE TITLE
Social icons in footer - hard coded http should probably be avoided

### ISSUE THREAD

**Issue by ndebuhr** [hydroshare/hydroshare#3086]
In the hydroshare footer, the footer links are mixed http/https.  Https for all would seemingly be best practice.

![bildschirmfoto vom 2019-01-13 22-49-50](https://user-images.githubusercontent.com/14877920/51091103-1fea0e00-1786-11e9-9873-be4920985298.png)

**Comment by engineSound** [comment]
Verified these three links are still using http. These links should not be in source code. They should be in an external resource file. 
  http://github.com/hydroshare
  http://twitter.com/cuahsi
  http://github.com/hydroshare

**Comment by engineSound** [comment]
https://github.com/hydroshare/hydroshare/blob/5e2d1227813060435f79ee8fbf69f26bf235c49b/pg.development.sql#L13676

We are writing HTML into database. @hyi  @cuahsimarko  Any reason to do this?

**Comment by hyi** [comment]
@engineSound I don't think there is any particular reason that warranted us to do this. The reason it made into db was that these page contents were added directly from Mezzanine-based admin control panel, and Mezzanine added these page contents into db to persist page contents. These page contents can be modified directly by any admins from the admin control panel.

**Comment by engineSound** [comment]
@hyi Thank you! 

Where do we access the Mezzaine-based admin control panel?

**Comment by hyi** [comment]
@engineSound Go to ```/admin``` URL which needs admin credential to login. You can check with others at CUAHSI for admin credential if you want to take a look.

**Comment by engineSound** [comment]
@hyi Got it. Transfer this issue to @Lizabrazil  who has control over admin on the production. I don't have it the authority. I assign @hyi  and myself as reviewers.

After @Lizabrazil made the change on admin panel, we need to notify @sblack-usu who has been working on production upgrade.

**Comment by Lizabrazil** [comment]
Not following what exact action is required of me. Is this mezzanine of help pages? 
The pages.hydroshare.org admin page (help mezzanine) is not loading for me..

**Comment by engineSound** [comment]
@Lizabrazil I will work with you together to fix this issue.

**Comment by Lizabrazil** [comment]
looks fixed
