### ISSUE TITLE
HTML element unique ids for selenium automation testing

### ISSUE THREAD

**Issue by engineSound** [hydroshare/hydroshare#3096]
Selenium automation testing uses id to target a specific element and emulate user action.  When the  element doesn't have an id, automation scripts need trace to a parent that has a id. Then the script start from the parent, hardcode levels to reach down to the child element to emulate user action. It is not flexible to respond to future changes. 

This GitHub issue would like to involve automation testing engineer and design and development engineer into discussion of this issue that is not quite visible to developers, but yet affecting automation testing.

**Comment by sblack-usu** [comment]
I see I've been summoned to this ticket, however I'm not quite following what the need is here.  Could you expound a bit?

**Comment by engineSound** [comment]
In resource landing page code review, I noticed id(s) attribute of some HTML elements are not defined. The id is used in selenium automation to query the element and simulate user interaction. @ndebuhr 

It was suggested to add id(s) at the time automation needs it.

**Comment by engineSound** [comment]
Closing to discuss offline in future.
