### ISSUE TITLE
requirements.txt isn't used

### ISSUE THREAD

**Issue by ironfroggy** [hydroshare/hydroshare#31]
The requirements.txt file lists dependencies, but the Dockerfile only installs a few specific Python packages, instead. Does requirements.txt need to be added to the Dockerfile? It is the standard way to define Python dependencies for a project and a convention that will help any prospective or new developers find their way around the infrastructure.

**Comment by hyi** [comment]
Just want to add a note that requirements.txt file is used in hs_docker_base sub-directory when most (if not all) required packages are installed into hs_base container for use by hydroshare. There is no requirements.txt being used in the hydroshare root directory, though.

**Comment by ironfroggy** [comment]
In the interests of continuing the discussing in a single location, here was Michael's follow up:

As Hong mentioned, make reference to the requirements.txt and Dockerfile found in hydroshare/hs_docker_base

In general the Dockerfile defines install components at the OS level (for example apt-get or yum) and requirements.txt defines the Python packages installed using pip.
You will however notice a mix of apt-get and pip install in the Dockerfile that defines hs_docker_base, and I'm unsure if that was intentional or not for dependencies and such.

The Dockerfile in the main hydroshare directory builds off of the hs_docker_base image that was already built using the definitions in the hs_docker_base directory.
The pip install statements could very likely be migrated to the requirements.txt file that resides within hs_docker_base, and probably exist where they currently do because they were easier to add on there as the project evolved. By this I mean it's much quicker to build in packages at the outer layer rather than recompile the whole base image again.

**Comment by ironfroggy** [comment]
I did not notice the other Dockerfile in hs_docker_base, I was only looking at the root Dockerfile and that requirements.txt and wondering why they weren't connected. I was however not basing this only on the contents of the files, but on the haystack package I added to requirements.txt not being installed when I rebuilt my containers, until I added them to that root Dockerfile.

Can you explain why that may have been?

Can you also explain the benefit of not simply installing all dependencies in each container, so that nothing can become amiss or out of sync? What does the root Dockerfile container run that it does not need the python packages?

**Comment by mjstealey** [comment]
Resolved via discussion by email of usage
