### ISSUE TITLE
"Create Resource" button should be more prominant than "Log in to iRODS button" 

### ISSUE THREAD

**Issue by danames** [hydroshare/hydroshare#3107]
When creating a new resource on the old landing page (and the new one as far as I can tell), we are presented with "Login to iRODS" more prominently than "Create Resource". This should be changed. It is confusing to newbies. Also the button "login to iRODS" - even if made less prominant- is still quite ambiguous. Why would I do that? What is iRODS? why am I being told to do this? It is not clear at all that this is a method related to uploading large files and that there is a whole process that has to be gone through. 
![image](https://user-images.githubusercontent.com/3472628/52006383-38963b80-2489-11e9-89bf-a7ed23562a51.png)

**Comment by danames** [comment]
Addendum- there is text "To load files from an iRODS server including your iRODS user HydroShare server:" but this is still very non-obvious what this means. The button should be removed completely and replaced with an in-line hyptertext link. I envision text at the very bottom of the page that says something like, "Users with access to an iRODS data server may want to connect there HydroShare and iRODS accounts to facilitate data transfer between iRODS and HydroShare. Click here to connect your iRODS server." "Click here" would be the hypertext link to the login.

**Comment by Maurier** [comment]
I want to note that this issue could be fixed as well by #3095

**Comment by cuahsimarko** [comment]
> I want to note that this issue could be fixed as well by #3095

I believe 3095 was obsoleted

**Comment by cuahsimarko** [comment]
As a quick fix, I'd like to propose swapping locations of the log into iRODS and Cancel/Create Resource buttons. I've also noted this in the past and glad someone else feels the same way.

**Comment by dtarb** [comment]
This can be closed because Create page will go away with #3242
