### ISSUE TITLE
Move logs in hydroshare container

### ISSUE THREAD

**Issue by cuahsimarko** [hydroshare/hydroshare#3117]
The drive mapping for hydroshare container tries to store logs on the host machine. Refactor logging to store to local container in non-mapped path.

**Comment by cuahsimarko** [comment]
@sblack-usu @hyi @phuongdm can we discuss implications here? The initial conversation was Scott and I and we thought this would be nice to remove the requirement from the developer setup to create the logs directory. Also, I get annoyed that when I search source code in hydroshare while I'm coding, I get hits from the logs directory.

**Comment by sblack-usu** [comment]
I think it's a no brainer, leave the ability configure a different location but default to inside the container when there is no config... 

Come to think of it, production doesn't even sync the log directory with the host machine so you have to go inside the container to look at the logs anyways.  I don't think it's expecting much if we ask developers to either set a path for logs or look inside the container.

**Comment by sblack-usu** [comment]
oh, didn't see @hyi comment until now.

**Comment by cuahsimarko** [comment]
If we leave the default the way it is, then the app will crash when you don't create a logs directory. Docker Windows may have issues/extra steps required for developers due to filesystem sharing if the app tries to create logs. That's why "mkdir logs" is part of the developer setup -- manual creation. App crash if you don't.

**Comment by cuahsimarko** [comment]
I'll do whatever Hong and Scott decide as long as you both agree.

**Comment by hyi** [comment]
@sblack-usu I have always looked at the logs on the host in both local development environment and production environment, and have never actually gone into the docker container to look at the logs. I think it is easier to look at the logs from host without the need to go inside the container. We did run into some permission issues with logs occasionally, i.e., log files on the host somehow got owned by root so hydro-service account did not have permission to write to them, hence bringing containers down. If pre-creating a logs directory were the only drawback with the way it works currently, we could create a logs directory as part of our code base and put a readme file to it if github does not allow to commit an empty directory.

**Comment by cuahsimarko** [comment]
@hyi This keeps finding a way to come up and bite me. It complicates deployments and developer setup. Are you willing to type docker logs hydroshare anytime you need to view the logs or do we need to keep this in so you can view logs in the container as well as your host os (VirtualBox)?

**Comment by hyi** [comment]
@cuahsimarko I don't understand the issue here. I can look at logs inside docker container or on the host, and I always look at logs on the host since it is easier. What is the exact issue that keeps coming up to bit you?

**Comment by cuahsimarko** [comment]
Ok, we will not implement this change, so you can continue to do so.
