### ISSUE TITLE
New owner requires refresh before it shows up on landing page

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#3120]
If manage access is used to add a new owner to a resource, then the manage access panel is closed, the new owner does not show up on the landing page until the landing page is refreshed.  Consider having close manage access trigger a page refresh so that actions in manage access are shown to have taken effect.

**Comment by engineSound** [comment]
* I am able to reproduce this on www. It isn't a regression. @dtarb Are you aiming to get this fixed for 1.19?

* @horsburgh There are two scopes of refresh. One is only refreshing the fields on the resource landing page that are affected by the sharing panel. The second is the entire resource landing page. I think we should the first one. Using ajax call to update just portion of the page. I checked the hsapi, I did spot an REST API to do that. @Maurier can shed light on this.

**Comment by Maurier** [comment]
I agree with @engineSound in that we should update the items via an ajax call rather than refreshing the page. We already have a response set up for this action, it would be a matter of adding this data and use it to update the UI.

**Comment by dtarb** [comment]
I agree that this is not a regression.  It does not have to be fixed for 1.19.  I am happy for the solution to be whatever is best.  "consider trigger page refresh" was one suggestion, but if there is a better way to do it, I am happy for you to do that.

**Comment by pkdash** [comment]
We should aim for zero page reload once the user is in resource edit mode. There are still couple of use cases where the page elements don't get updated until a manual page reload is done. @Maurier I can help on backend code changes to avoid any need for page reload.

**Comment by cuahsimarko** [comment]
@engineSound is this deprecated by new Landing page?

**Comment by engineSound** [comment]
@cuahsimarko It is the current behavior of the new landing page.

**Comment by cuahsimarko** [comment]
@dtarb I'm unable to reproduce this problem. When I add an owner, I'm required to update the Quota holder, then remove myself as owner, at which time I get a warning dialog. Upon accepting consequences of removing myself as owner (assigning the new owner), it takes me to the My Resources View and the resource no longer appears in that view.

**Comment by dtarb** [comment]
@cuahsimarko I do not think your attempt followed what I did.  I did not describe doing anything about quota holder.  Closing based on no reading the issue properly does not seem warranted.  This may not be a high priority issue, but please look at it to get an understanding of what it actually is.

**Comment by Lizabrazil** [comment]
[changed owner is not reflected on page.zip](https://github.com/hydroshare/hydroshare/files/3149338/changed.owner.is.not.reflected.on.page.zip)

**Comment by Maurier** [comment]
The way this was addressed in https://github.com/hydroshare/hydroshare/pull/3390, in my opinion, is inefficient. Pressing the button to dismiss the window now refreshes the page. This unnecessarily introduces yet another page reload, which we are trying to get rid of.

This could have been implemented better by updating the UI in the AJAX response that was already set up.
