### ISSUE TITLE
Groups menu hidden when resizing window

### ISSUE THREAD

**Issue by Castronova** [hydroshare/hydroshare#3126]
When the window is resized, the "Find Groups" and "My Groups" menu items become obstructed.

![image](https://user-images.githubusercontent.com/4822372/52372677-c2647c80-2a26-11e9-996a-510b2dc51836.png)

![image](https://user-images.githubusercontent.com/4822372/52372687-cb554e00-2a26-11e9-81c4-2cccb8fb68d6.png)

**Comment by cuahsimarko** [comment]
@mraocuahsi when you are ready, can you start researching this to see level-of-effort?

**Comment by Lizabrazil** [comment]
Approved
