### ISSUE TITLE
Put copy resource bag to iRODS button with other buttons

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#3136]
In the revised landing page I think the copy resource bag to iRODS button should be moved up to with the other buttons.

![image](https://user-images.githubusercontent.com/3456833/52528119-e3310a00-2c92-11e9-80ed-77cdac6a94a5.png)

**Comment by Lizabrazil** [comment]
Agree. Consolidate all actions on data in content panel.

**Comment by Maurier** [comment]
@dtarb, @Lizabrazil - I'm looking for ideas on which icon to use. Let me know if something from here works: https://fontawesome.com/v4.7.0/icons/

I could also create a custom icon if you have a suggestion.

**Comment by Lizabrazil** [comment]
The only thing I can think of is a file icon. @dtarb Do you not like Hamburger menus? I feel bad that I now suggested moving all tools to the tool bar because i think it's getting crowded and because of that tools are feeling hidden. Maybe there is a better solution to make these tools more visible? @engineSound Any ideas here?

**Comment by Maurier** [comment]
I gave this one a try:
![image](https://user-images.githubusercontent.com/2448568/53268745-27b1a200-36a4-11e9-8753-8d755a109612.png)

**Comment by engineSound** [comment]
@Lizabrazil I vote for hamburger menu. It first makes the layout clean, so people feel the space to breathe. Second, hamburger menu is already a familiar symbol of entry to options. 

As to confusing icons, a good practice to convey clear message is to use a button built by  icon + text. See example below. Text assists human to interpret the icon. When we combine this practice with the hamburger menu,  it is not crowded at the main page and icons are clear to understand.
 
![image](https://user-images.githubusercontent.com/35352595/53269124-0e195600-36b6-11e9-833d-df0a98bda3e5.png)

**Comment by dtarb** [comment]
I suggest an iRODS icon, similar to 
![image](https://user-images.githubusercontent.com/3456833/53294764-3e422100-37aa-11e9-9df4-f2691fba56b4.png) from irods.org

I prefer to avoid a hamburger menu right now.  With a button it is one click.  With a hamburger it is two clicks and you have to go there to learn what each can do.  One click button you can hover over and learn.  Only when you really can not fit all the buttons you need should you revert to hamburgers.  

In view there are only 6 buttons so adding one more is not too much.  In edit mode the buttons are starting to get a bit cluttered, but I still think not too many and the benefit of fewer clicks has me in favor of keeping the interface as it is, at least until it has had a fair shake.  We deployed less than a week ago.  Lets give folks a chance to like it.

**Comment by horsburgh** [comment]
I would also prefer to not hide buttons behind multiple clicks if we don't have to.

**Comment by martinseul** [comment]
Discussed this with the team and consensus is for now to move button into the row with other icons, we can use the icon Dave suggested

**Comment by Maurier** [comment]
In order for the icon to look consistent with the rest of the icons I had to also import it as a font so that it keeps the same styling as the other ones. I created font files that we can maintain with our own custom icons. It works similar to icon packages we are using like Bootstrap's glyphicons and FontAwesome.

I also added documentation on how to add new icons: https://github.com/hydroshare/hydroshare/pull/3213

![image](https://user-images.githubusercontent.com/2448568/53749696-2bdc7d00-3e65-11e9-968c-c453dad0d2ff.png)

**Comment by dtarb** [comment]
I like it.  Thanks.

**Comment by Lizabrazil** [comment]
@dtarb @Maurier  I think this came up on the Monday call but i cannot exactly remember. I see the copy icon (the two squares one
![image](https://user-images.githubusercontent.com/13852599/53842486-9f69b180-3f6d-11e9-984d-b3d0051d5959.png)
) on beta. Is the IRODs icon making it into 1.20? I will wait to update the documentation until the irods icon goes out so I don't do it twice.

**Comment by Maurier** [comment]
@Lizabrazil The code that adds the icon is pending code review. @sblack-usu might now if we can include it in 1.20.

**Comment by Lizabrazil** [comment]
@Maurier thanks!

**Comment by Maurier** [comment]
@dtarb This has been implemented and deployed to www. Closing...
