### ISSUE TITLE
Attempt to remove self as owner instead switches quota holder to self

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#3138]
The following sequence results in incorrect behavior 
- User A creates a resource
- User A uses manage access to set user B as an additional owner of the resource
- User A changes the quota holder of the resource to user B.

All the above works correctly
- Now user A attempts to remove themselves as owner.  On www this results in a warning that this is irreversible, and if the user indicates to remove they end up being removed as an owner
- On release candidate 1.19 beta if user A attempts to remove themselves as an owner, they are not removed as an owner.  Instead they become the quota holder.

This is related to #2127 but describes a specific problem introduces with version 1.19 beta that did not exist at the time #2127 was written.

**Comment by Maurier** [comment]
@dtarb This has been fixed and deployed to www. Closing...
