### ISSUE TITLE
Resource specific metadata getting cutoff

### ISSUE THREAD

**Issue by Maurier** [hydroshare/hydroshare#3141]
It seems resource specific metadata is not getting displayed properly (getting cutoff on the left side) in both view and edit modes for resource types like Time Series, Multidimensional, Geographic Feature, Geographic Raster. Here is an example of the problem:

![image](https://user-images.githubusercontent.com/2523434/52569425-2bf5d980-2ddf-11e9-8bfa-089e7ada014e.png)

_Originally posted by @pkdash in https://github.com/hydroshare/hydroshare/issues/3102#issuecomment-462347432_

**Comment by Maurier** [comment]
@pkdash, do we have a way of creating resource of these types in local development, or maybe a database I can test with?

**Comment by cuahsimarko** [comment]
I wonder if Neal D. has this in his scripts.

On Feb 11, 2019, at 10:17 AM, Maurier Ramirez <notifications@github.com<mailto:notifications@github.com>> wrote:


@pkdash<https://github.com/pkdash>, do we have a way of creating resource of these types in local development, or maybe a database I can test with?

**Comment by cuahsimarko** [comment]
Whoops, didn't mean to reply all, was just mentioning for Mauriel.

On Feb 11, 2019, at 10:18 AM, cuahsimarko <notifications@github.com<mailto:notifications@github.com>> wrote:

I wonder if Neal D. has this in his scripts.

On Feb 11, 2019, at 10:17 AM, Maurier Ramirez <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com>> wrote:


@pkdash<https://github.com/pkdash>, do we have a way of creating resource of these types in local development, or maybe a database I can test with?

**Comment by pkdash** [comment]
@Maurier 

> do we have a way of creating resource of these types in local development, or maybe a database I can test with?

Yes, You can edit the create-resource.html file to insert an li element like this: https://github.com/hydroshare/hydroshare/blob/develop/hs_core/templates/pages/create-resource.html#L81 for a specific resource type.

**Comment by dtarb** [comment]
Tested on beta.
