### ISSUE TITLE
Resource creation REST API changes needed

### ISSUE THREAD

**Issue by pkdash** [hydroshare/hydroshare#3146]
It seems it is still possible to create a resource of any deprecated resource types (Geo Raster, Geo Feature, Multidimensional, Time Series) using the REST API. Before we start migrating these existing resources to composite resource type, I think necessary change needs to be made to REST API to prevent creation of resource of any of these deprecated resource types.

**Comment by Castronova** [comment]
This has been resolved

**Comment by dtarb** [comment]
Close - refer to #2991
