### ISSUE TITLE
Many storage related operations bad

### ISSUE THREAD

**Issue by cuahsimarko** [hydroshare/hydroshare#3149]
File create, read, delete operations in HydroShare are poor. Most evident in bulk operations, but sometimes be noticeable even in single transactions. Most apparent in:

1) Lengthy 3-5 hour unit testing
2) Painful bulk CZO operations (400 resources with varying complexity and additional sub-resources) ... Local CRUD operations are slower than downloading all of the resources from the remote site over my phone.
3) Bulk delete operations (see various related iRODS tickets)
4) Potentially related (is it a postgres, Django storage class or iRODS issue?) when a user has 400 resources, page load takes 20-30 seconds.

**Comment by cuahsimarko** [comment]
@dtarb I suspect this is a root cause for lots of pain points and poor user experience across the entire platform. I haven't had time to run a profiler on it yet, but given recent conversations, maybe I can give it a day to see if I can gather any more differential/diagnostic information.

**Comment by dtarb** [comment]
I agree that finding the root cause of poor system behavior is vitally important.  Any information you can gather via profiling would be great.

**Comment by hyi** [comment]
@cuahsimarko Want to point out that bulk storage-related operations in iRODS itself is fast. I believe what needs to be improved is the Django and iRODS synchronization for bulk operations especially for time consuming operations for large files in a web environment.

**Comment by cuahsimarko** [comment]
@hyi Thank you that is great information. Can you help me identify which specific tests those are?

**Comment by hyi** [comment]
@cuahsimarko I don't think we have tests that test Django and iRODS synchronization or performance-related tests.

**Comment by cuahsimarko** [comment]
Duplicate issue / history: https://github.com/hydroshare/hydroshare/issues/2368

**Comment by cuahsimarko** [comment]
400 resources is an edge case. Unpinning, though the extent and depth of the issue warrant high priority Label,.

**Comment by cuahsimarko** [comment]
Some of the performance issues with resource-based listings have been addressed. In favor of more specific work tickets, this Issue is being closed.
