### ISSUE TITLE
Creating a new resource - feels like an error when it's not...

### ISSUE THREAD

**Issue by danames** [hydroshare/hydroshare#315]
1) Create a new resource (I tried both referenced time series and geotiff)
2) You are greeted with RED BOLD messages that give the sense that you have done something wrong on in some way failed badly. The messages say, "Data for the following required elements are missing..." 

It would be better to greet the user with a nice green "Congratulations! Your resource has been created. Next steps: Add the abstract and the keywords."

**Comment by horsburgh** [comment]
I like this suggestion.  And, it could also solve issue #316 if the message directed them to the Edit button. User's only really need to be directed to the edit button once.

**Comment by dtarb** [comment]
@horsburgh please coordinate with @mauriel133 to work this into interface improvements

**Comment by mauriel133** [comment]
Sounds good, I'll have this implemented today.

**Comment by mauriel133** [comment]
![screenshot - 05092015 - 03 01 00 pm](https://cloud.githubusercontent.com/assets/2448568/7551600/52d0b354-f65c-11e4-8f48-3fb7e4f30610.png)

Would this work?

**Comment by horsburgh** [comment]
Yes - this is better.  My only question is whether you want to add the "Edit this resource" button or just direct them to click on the existing edit resource button (the pencil icon). One of the original comments from @danames was that it is isn't readily apparent right away that you need to use the pencil button to go into edit mode.

**Comment by mauriel133** [comment]
![neweditmessage](https://cloud.githubusercontent.com/assets/2448568/7551674/1fba0ce6-f660-11e4-9211-238b363bb366.png) 
How about this?

**Comment by horsburgh** [comment]
I like it.

**Comment by dtarb** [comment]
I like it too.  Is there a way to indicate that those metadata elements are required to make the resource public.  There are other metadata elements that can be added in editing. Perhaps something like
Congratulations! Now that your resource has been created click on the edit button below to add additional metadata.
The following metadata are still required before you can make the resource public
* Abstract
* Keywords

If you can figure out a way for the list that shows to dynamically show what is still required based on the resource data model for that resource type, then it would be slick.  Also, a different message may be needed when a user comes back to a resource they can edit.  The Congratulations is then not necessary and the message might be.

Click on the edit button below to add additional metadata.  The following metadata is still required before this resource can be made public ...

**Comment by mauriel133** [comment]
That is much better. I'll try to implement it. @pkdash, is there a way to know when a resource has just been created once in the resource landing page?

**Comment by pkdash** [comment]
@mauriel133 I am not sure I understand your question. As per @dtarb suggestion to show dynamically what required metadata elements are still missing data, I think that's is already in place. Any time a resource page is refreshed, it should always show if there are still required metadata elements missing data.

**Comment by danames** [comment]
I also like it. Much better. Thanks. - Dan

**Comment by horsburgh** [comment]
The question that @mauriel133 asked was related to the message that is displayed when a resource is first created.  Now it says something like "Congratulations, you successfully created your resource..." and then it highlights missing metadata elements. That's fine for the first time you see that message, but for any subsequent times the user accesses the resource it shouldn't use the same message.  So, the question is - is there a way to determine whether it is the first time you are accessing the landing page after the resource creation?

**Comment by pkdash** [comment]
Currently there is nothing in place to make that distinction. But with little bit of code I think we can know if the resource is being displayed for the first time or not.I can help @mauriel133 on that.

**Comment by dtarb** [comment]
Testing on dev at present the message is inconsistent across resource types.  For a generic resource the message says "Congratulations! Now ...".  For other resource types the message says "Now that ..."

The following functionality is desired
* same messaging for all resources.
* when a resource is first created the first line should read "Congratulations.  Now that your resource has been created the following metadata are still required ..."
* when a resource is viewed by a user with edit permissions and metadata is insufficient for making public the message should be "The following metadata are still required ..."

**Comment by dtarb** [comment]
Implemented in 1.5.1
