### ISSUE TITLE
Error message when an owner reduces access privilege

### ISSUE THREAD

**Issue by engineSound** [hydroshare/hydroshare#3153]
#2127 

It would be nice to have a paragraph explaining why a user get the error message. It is at your discretion.

**Comment by Lizabrazil** [comment]
@engineSound there is documentation on the help pages on which files are required for adding a shapefile. Do you mean/think we need documentation for the actual error message too?

**Comment by Lizabrazil** [comment]
@engineSound I'm not sure what we need documentation on here, should we close this?
