### ISSUE TITLE
Web app tab missing in new 1.19 resource landing page

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#3155]
On www for each resource there is a web app tab in the tabs area below the content area that lists all web apps available to the user that are set to be able to open the resource type.

With the removal of these tabs in the 1.19 resource landing page revamp this content is no longer available on a resource landing page

@horsburgh is this by design

Originally this web app tab, designed by @danames was intended for users to discover in an unobtrusive way what web apps were available (i.e. for which hydroshare "web app connector" resources had been created by other users) that could act on that resource.  A user who wanted to use that web app could then open the "web app connector" (hydroshare resource that connects to the external app), add the web app connector to their open with list and then open the resource from the resource open with button to launch the 3rd party web app that opens their hydroshare resource.  We appear to have cut off this pathway for users to work with contributed web apps.

**Comment by horsburgh** [comment]
@dtarb - the tabs are obviously gone. That was by design, so the tab is not missing.  "Open With" now has to happen with a right click at the content level because resources can now contain multiple content types. Before, "Open With" happened at the resource level, which no longer makes sense.

I've asked multiple times whether the right click and "Open with" capabilities are working correctly with content types in Phase 2 of composite resource and now with the new resource landing page. I've been told yes, but I've never seen this demonstrated.

@pkdash, @Maurier, and @sblack-usu - can you let us know how this is now supposed to happen? I just created a new resource on beta (because I can't remember the URL for the new beta) and added a geographic shapefile. When I right click on the aggregation, there is an "Open", which opens the folder and shows me the file. There is no option to "Open with", which I would expect there to be. Shouldn't I be able to open that aggregation in the HydroShare GIS?

@dtarb - in terms of discovering web apps in an unobtrusive way, shouldn't that be done on the "Apps" page? We likely need to revisit this web app connector stuff because I don't think all of these connections have been made.

**Comment by dtarb** [comment]
@horsburgh the functionality that is going away is the ability to discover a web app (connector) that has been set to be applicable for a resource type and was in the web apps tab.  As long as we are deliberate and aware of this, I am OK with this.

beta.hydroshare.org has been redirected to the current deploy so no need to remember the new URL.

As an example of file level open with on www go to a composite resource that has a .ipynb file in it (an example I have is https://www.hydroshare.org/resource/c17a0da1bd1f4489b4e72e0eaf2ae475/).  At the bottom in the web apps tab you will see Jupyter Notebook Viewer.  This is the web apps tab discovery that is going away.  You can then click on it to get to the web app connector resource page and click on the grid top right to add web app to open with list. 
![image](https://user-images.githubusercontent.com/3456833/52902940-0e58b380-31d5-11e9-9bca-c6628b1a811a.png)
Then go back to the resource with the jupyter notebook and (perhaps after refreshing) right click on a .ipynb and you should be able to open with the jupyter notebook viewer.  

Without the web app tab to discover the Jupyter Notebook viewer you need to use Discover, or have it explicitly shared with you (so you see it on your My Resources page having checked shared with me) or be told about it.  A limitation of the web apps page is that it is only CUAHSI approved apps and we do want to encourage users to develop and share apps.

Note that in writing the above it occurred to me to start calling web app resources, web app connectors, to distinguish them from web apps that are the tools outside HydroShare.

If you look at the Jupyter Notebook Viewer web app connector resource I created 
https://www.hydroshare.org/resource/366cecf46086483b8a5003abe8376b73/
you can see how it is set up for files with a specific extension. The same can be done for aggregations

The HydroShare GIS  web app connector is https://beta.hydroshare.org/resource/9674a0af9f30410e9e02397c91284f54/ (on beta).  If you go to this you will see that it supports a list of resource types including Composite resource.  If you click to edit this (you should be able to do this because edit permissions have been given to the HydroShare developer group) you will see that no aggregation types have been checked as supported, and the App-Launching Aggregation Level URL pattern has not been filled in.  This is why this App does not appear on the right click for an aggregation.

If you make a copy of this web app connector (or look at the copy I made https://beta.hydroshare.org/resource/90b9528f910e48489c91343127077707/) I have set Geographic Raster and Geographic Feature Content as supported aggregation types.  I have also set an App-launching aggregation level URL pattern.  I used the same launching pattern as for a resource.

I then found a resource I owned that has a geographic feature content aggregation in it.
At the resource level I can see Open with HydroShare GIS, but not HydroShare GIS DGT Copy
At the aggregation level I can not see any open with right click options.

I then set Add WebApp to Open With in my copy of HydroShare GIS web app connector (the one where I had changed the properties)

Back in my resource (after refreshing) I now have Open With HydroShare GIS DGT Copy at the resource level and at the aggregation level when I right click on the Aggregation.  If I use the Aggregation level right click open with HydroShare GIS does open.  Note that I was careful to test using a resource that existed on www (even though I was testing from beta) because HydroShare GIS is hard wired to retrieve resources from www.  If you try with a resource you just created in beta you get a resource not found error.

The procedure above could have been done on www because no new open with functionality has been added to beta.

This is how I understand the new (a few releases back) open with at the aggregation and file levels to work.  @horsburgh does this substitute for a demo?

What still needs to be done
1. Apps developers in general and HydroShare GIS developers in particular need to take advantage of functionality for retrieving and opening just aggregations or files, rather than whole resources.  The REST API patterns for launching apps from an app connector described at https://www.hydroshare.org/terms/#AppURLPattern have been designed with the intention to have the generality to pass individual file or aggregation paths to an app.  The Jupyter Notebook Viewer is a 3rd party app that I was able to set up to access HydroShare notebooks.

2. Once web apps have been developed to take advantage of this, the web app connectors (hydroshare resources) need to have connection metadata filled in consistent with the web app calling structures.

What we have lost (with resource landing page redesign).
Users can no longer go to the Apps tab on a resource landing page to discover apps that may be applicable to their resources.  They therefore need to discover apps some other way.  CUAHSI approved apps are discoverable and launchable from https://www.hydroshare.org/apps/.  Web apps that have web app connectors as HydroShare resources and are public (or discoverable) are discoverable on the HydroShare Discover page.  If a web app connector has been directly shared with a user (via manage access, but in not public), a user needs to find it on their resources page among resources shared with me, or be directly told about it.  Once users know about the web app and the web app connector resource, the need to go to the web app connector resource page and set the web app to open with if they want to use the app, or open the web app directly from the web app connector page if it is set up to do this.   We need to document this as the procedure for discovering and using web apps that are not CUAHSI approved.

**Comment by horsburgh** [comment]
@dtarb - this seems really complicated. If you had to write all of that text to explain it to me, how will users ever get it?

We want to encourage people to develop Apps. We as the HydroShare team have developed a set of Apps. We may need a process for registering 3rd party apps and associating them with content types, but can't we make the association between content types and CUAHSI/HydroShare Team approved apps automatic so all users can just use our approved apps without making any associations? Maybe I'm not fully understanding the process.

Why would we not want all users to be able to automatically open known content types with our own approved Apps? 

We've discussed an Apps registry before. Maybe that's were all of this stuff should be done since we have removed the tab from the resource landing page and it isn't really appropriate to do it at the resource level anyway.

**Comment by dtarb** [comment]
@horsburgh if you can figure this out - you can then start on quantum mechanics, and then explain it to me.

Joking aside, I get your point, but some of the above is probably my poor writing, or to quote Pascal "I would have written a shorter letter, but I did not have the time"

I think the process is actually fairly simple and it was trying to conflate multiple things that led to the poor writing.  First is the point that the web apps tab has gone away.  This simply amounted to a list of web apps that could act on a resource.  If we chose it could be replaced by a list of "Web apps available to work with this resource" that could be listed near the bottom of a resource landing page.

Second was addressing your question that you had not seen demonstrated the open with capabilities working correctly and I set out to show this.  I did this by setting up a web app connector that launches for a .ipynb file a 3rd party (from Jupyter) notebook viewer.  This proves that we can encourage anyone to develop apps and that our system allows them to be registered. The process for registration involves creating a web app connector (web app resource type) and then sharing it with users, just as you would share any resource.  The web app connector has check boxes to set which resource and aggregation types it applies to, and what file extensions to match.  It also allows flexibility in the calling strings so as to not limit web app developers.  

I also explained how the HydroShare GIS web app connector could be copied and used to open geospatial content type aggregations.  I used a copy because I did not want to mess with what was not mine and what was not coordinated with the actual app.

We do want users to be able to automatically open known content types with our own approved apps, and they can.  This is already in place.  Nothing I wrote or explained is counter to this.  But the HydroShare GIS app is right now programmed to open resources.  Before it can be used to open aggregations, its programming needs to be changed to use the API that accesses aggregations individually, rather than resources as a whole.  That is work for the HydroShare GIS developers to do.  In general any web app developer can choose whether the app should work on a whole resource, or on an aggregation or on a file.  

The HydroShare resource database filtered by "web app" resource type, is effectively our app registry.  There is also an admin page where a CUAHSI admin can approve any web app by checking a box, and once this is done, that web app appears on the apps tab.  All the business about finding web app connectors and enabling them for your open with button only applies to non CUAHSI approved apps, that we should encouraging users to develop and use, but on a buyer beware basis until they get recognized as being of broad value and get documentation that meets the CUAHSI approval needs.  Dan wrote a document that described the tiers involved here quite nicely.

**Comment by cuahsimarko** [comment]
Correct Web Apps are in Open With...
<img width="219" alt="image" src="https://user-images.githubusercontent.com/45397838/56442079-57a0ae80-62bd-11e9-9b07-c1a853b9f2da.png">
