### ISSUE TITLE
Edit mode for geographic feature does not recognize point coverage in composite resource

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#3158]
If I create a geographic feature in a composite resource that is a point (e.g. from 
[CubOutlet.zip](https://github.com/hydroshare/hydroshare/files/2872977/CubOutlet.zip)) this is recognized as a point in the resource level coverage and content metadata in view mode
![image](https://user-images.githubusercontent.com/3456833/52913488-0011a280-327c-11e9-86de-f55fb1a7949a.png)
but in edit mode spatial coverage is indicated to be box and required fields are empty and not able to be edited.  What should be shown is the filled in point required fields (and still not editable)
![image](https://user-images.githubusercontent.com/3456833/52913538-4b2bb580-327c-11e9-988c-dc2185a618a0.png)

**Comment by pkdash** [comment]
@dtarb I think this can be closed.
