### ISSUE TITLE
After creating new resource it is not clear how to edit the abstract

### ISSUE THREAD

**Issue by danames** [hydroshare/hydroshare#316]
1) Create a new resource (I just did a geotiff). 
2) You are instructed that the abstract is missing.
3) There is no additional information on how you should go about adding an abstract.
4) You are stuck.

(then you discover the edit pencil button but only because you saw it in a demo.)

There should be some more obvious way to edit the abstract. At a minimum, add a line under "Last updated:" that says, "Abstract:  None added. Click here to add one."

Ditto with keywords. There should be a line under abstract that says, "Keywords: None added. Click here to add some."

**Comment by dtarb** [comment]
Thank you @mauriel133 for implementing the messages on the interface that resolve this.
