### ISSUE TITLE
Enable ToolMetaData in mezzanine

### ISSUE THREAD

**Issue by sblack-usu** [hydroshare/hydroshare#3163]
This was disabled during the django 1.11 upgrade.  It is something useful enough to enable again.

Change this line from unregister to register
https://github.com/hydroshare/hydroshare/blob/develop/hs_tools_resource/admin.py#L67

Go to the mezzanine admin page and confirm ToolMetaData shows up.  It may or may not throw errors with registering.  There were similar issues with SiteConfiguration and Home that has since been worked out and I'll bet that ToolMetaData will work now because of those changes

**Comment by cuahsimarko** [comment]
Looks like this went out in 1.21
