### ISSUE TITLE
Local iRODS installation fails without local_settings.py

### ISSUE THREAD

**Issue by kjlippold** [hydroshare/hydroshare#3169]
I tried setting up local iRODS in a VM using the most recent .ova file, and I got an error because it relies on local_settings.py. I ran the command ./use-local-irods --persist, and got the following errors:

<img width="1081" alt="screen shot 2019-02-20 at 9 53 08 am" src="https://user-images.githubusercontent.com/27028728/53110036-65bd9300-34f7-11e9-87ba-ac2002748c08.png">

I was able to get around this by duplicating local_settings.cutover as local_settings.py, but from what I can see, the documentation at https://github.com/hydroshare/hydroshare/tree/develop/irods doesn't explain this.

The documentation should either be updated, or the use-local-irods script should be changed to use the new settings files.

**Comment by cuahsimarko** [comment]
If you can add a line to the README:

Generate a local_settings.py file by copying hydroshare/local_settings.template to hydroshare/local_settings.py

that's helpful, otherwise, I can open a separate PR to do so.

**Comment by cuahsimarko** [comment]
@phuongdm are we ready to move these into settings.py or would that be to big a change for hsctl to handle?
