### ISSUE TITLE
Go to metadata edit mode. How to get out of it?

### ISSUE THREAD

**Issue by danames** [hydroshare/hydroshare#317]
1) On a resource landing page, hit the pencil "edit" button.
2) View the metadata editor page.
3) Try to go back to the landing page.
4) Get stuck.

There should be a button on the metadata landing page that says, "Return to Resource View" or something like this. The only way I could get out was to click the main Resources button and then go to the resource again.

**Comment by dtarb** [comment]
Thanks to @mauriel133 there is now a button top right "View Resource" that resolves this.
