### ISSUE TITLE
Store Resource size in the Database

### ISSUE THREAD

**Issue by sblack-usu** [hydroshare/hydroshare#3171]
Currently, we're looking up the size of all files in a resource and adding it together to calculate the storage size of the resource every time a resource landing page loads.  The time to calculate slows considerably as the number of files increases.

Setup a size field on the resource with hooks to update the value on creation and file upload.

https://github.com/hydroshare/hydroshare/blob/develop/hs_core/models.py#L3342

**Comment by cuahsimarko** [comment]
Will there be a separate issue ticket for the My Resources page or can they be tied together / resolved with a common fix?

**Comment by sblack-usu** [comment]
This is separate work and a fix has been identified.  the My Resources page will likely need a different fix.  There is no size lookup on the my resources page.
