### ISSUE TITLE
Support update of Funding_Agencies, Relations and Extended Metadata via REST API

### ISSUE THREAD

**Issue by zhiyuli** [hydroshare/hydroshare#3180]
REST API (including hs_restclient) currently doesnt support update of Funding Agencies, Relations or Extended Metadata terms.

A broader issue: is it possible to implement REST APIs in a more generic way to handle a group of metadata terms with similar formats and syntax?

**Comment by zhiyuli** [comment]
Only "sources" got updated in the following code snippet

metadata_dict = {'funding_agencies': [{'agency_name': "NSF",
                                    'award_title': "Cyber Infrastructure",
                                    'award_number': "NSF-101-20-6789",
                                    'agency_url': "https://www.nsf.gov",
                                    },
                                    {'agency_name': "NSF2",
                                    'award_title': "Cyber Infrastructure2",
                                    'award_number': "NSF-123",
                                    'agency_url': "https://www.google.com",
                                    },
                                   ],
               "relations": [
               {
                   "type": "isCopiedFrom",
                   "value": "https://www.hydroshare.org/resource/asd/"
               },
               {
                   "type": "isExecutedBy",
                   "value": "https://www.hydroshare.org/resource/asdasd/"
               },
                     ],
              "sources": [
                   {
                       "derived_from": "Source 3"
                   },
                   {
                       "derived_from": "Source 2"
                   },
               ],
}

res = hs.updateScienceMetadata(hs_id, metadata=metadata_dict)

**Comment by martinseul** [comment]
@dtarb is this something @sblack-usu could look into, it is functionality we need to update the CZO metadata and if possible we can fix it and role out with 1.21

**Comment by dtarb** [comment]
Yes.
