### ISSUE TITLE
Hide items in Comments section

### ISSUE THREAD

**Issue by Maurier** [hydroshare/hydroshare#3183]
In the latest version of the develop branch I'm seeing some items that were previously hidden in the Comments section. This was probably caused by changes we've made recently in auto generating some template element Ids.

![image](https://user-images.githubusercontent.com/2448568/53251641-59ae0e80-367a-11e9-879b-bed302a63184.png)

**Comment by cuahsimarko** [comment]
So is that a "security" feature to try to capture robot behavior (hidden field that only a script would see)?

**Comment by Maurier** [comment]
Indeed. It looks like it's handled by Mezzanine.

**Comment by cuahsimarko** [comment]
Can we just get rid of Mezzanine? (I would normally discuss this in Slack but I've been dialing down my Slack usage lately, and I've already spammed a bunch of people with e-mails today, so just going to ask the question here)

**Comment by Maurier** [comment]
Bringing in others as they might know more than me about how we use Mezzanine. @pkdash, @hyi, @sblack-usu

**Comment by dtarb** [comment]
This was fixed in 1.20.1 so I am closing.  The reduction in the use of Mezzanine needs to be (and is) an ongoing architectural discussion.
