### ISSUE TITLE
Getting rid of page refresh when updating Resource Landing page items

### ISSUE THREAD

**Issue by Maurier** [hydroshare/hydroshare#3186]
In this issue we will document our plan to get rid of page refreshes when updating Resource Landing page items. As of now, we have done so by using ajax calls, but this is a bit repetitive to extend.

We can also discuss the possibility of turning this form into a single page application with well known tools like Redux (https://redux.js.org/).

**Comment by Maurier** [comment]
@cuahsimarko, any general ideas on how to proceed on this? I think this page form will be a great candidate to turn it into a SPA.

**Comment by Maurier** [comment]
We will move this conversation to Slack and post our decisions back in this issue after.
![image](https://user-images.githubusercontent.com/2448568/53259819-52dcc700-368d-11e9-97c3-58cbd967b97d.png)

**Comment by cuahsimarko** [comment]
I would like to look into Vue.js together with you, @Maurier let's talk soon

**Comment by engineSound** [comment]
@Maurier The direction you set is bright and promising. I am in. Thanks.

**Comment by cuahsimarko** [comment]
https://github.com/hydroshare/hydroshare/issues/3120

**Comment by Maurier** [comment]
The plan to turn the Resource Landing page into a single page application (no unnecessary page refreshes) is to instantiate each component of the page as a Vue instance.  While doing so, any server side responses will be changed to handle AJAX requests and return appropriate json data. 

We will list the components below so we can keep track of the work and overall progress. 

- [x] Keywords (Completed)
- [ ] Resource Title (In progress @cuahsimarko)
- [ ] Manage Access window (In progress - @Maurier )

**Comment by martinseul** [comment]
Stale and in large part completed, closing
