### ISSUE TITLE
Email addresses should not be scrapable

### ISSUE THREAD

**Issue by danames** [hydroshare/hydroshare#319]
1) Do not log in
2) View a resource
3) Click the creators name
4) Hover over the creator's name and you can scrape their email address.

Easy/quick fix: Only show the "Email: Send email to Dan" link for users that are logged in. For visitors who are not logged in show: "Email: (log in to send email)"

**Comment by horsburgh** [comment]
This is done on dev.hydroshare.org. Closing.
