### ISSUE TITLE
Reimplement non-transitioned work

### ISSUE THREAD

**Issue by cuahsimarko** [hydroshare/hydroshare#3194]
Assess priority of and capture any relevant knowledge from this stale PR https://github.com/hydroshare/hydroshare/pull/2976 , while revisiting the enduser needs and getting visibility to the changes across Organizations. Finally, get implemented.

**Comment by dtarb** [comment]
See also https://docs.google.com/document/d/1TEWjijx-ZR6NR_Zy-1GIOjy9ZqGkFb64cE_2d-OevFY/edit# and #2298 where DOI functionality was worked out in quite a bit of detail.

**Comment by martinseul** [comment]
@cuahsimarko closing this one here, we can readdress tis as part of the DOI work with a more actionable ticket.

**Comment by cuahsimarko** [comment]
@martinseul yes, I have it linked in my index of old documentation for the project that I'm collecting.
