### ISSUE TITLE
Delete unused profile static media files

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#3196]
If a user adds their CV to their profile, it is saved as a static media file, e.g. https://www.hydroshare.org/static/media/profile/tarboton_short_resume.pdf.  If the user clicks the button to delete their CV the View CV link is removed but the file remains and the link to the CV still works.  A user complained about this.  

The behavior for profile pictures is similar.

We should
1. Delete the media file when the CV delete button is clicked (and confirmed).
2. Delete old user profile picture file when it is deleted or replaced
3. Implement a periodic garbage collection script to remove unused media files on the alternate worker
4. Fix CV updating functionality.  At present the buttons below to update a profile do not work as intended in edit mode.  View CV actually attempts to browse a file.  The circle arrows are non intuitive, but function to browse a file.  If a file is selected it is not shown.
![image](https://user-images.githubusercontent.com/3456833/53376801-d7914480-391c-11e9-91ad-59257cdb9a92.png)

**Comment by Castronova** [comment]
Closing, this appears to be resolved.

**Comment by martinseul** [comment]
still an issue

**Comment by martinseul** [comment]
Closing, fixed with Release 1.45; PR https://github.com/hydroshare/hydroshare/pull/4254
