### ISSUE TITLE
Adding elasticsearch to docker setup

### ISSUE THREAD

**Issue by ironfroggy** [hydroshare/hydroshare#32]
There will need to be a new Docker container defined to install, run, and manage an ElasticSearch instance to perform content indexing and search queries.

**Comment by mjstealey** [comment]
I'd think the stock dockerfile/elasticsearch image should suffice... no?
https://registry.hub.docker.com/u/dockerfile/elasticsearch/

Would need to add something like this to the fig.yml file after the rabbitmq declaration.

elasticsearch:
  image: dockerfile/elasticsearch
  ports:
    - "9200:9200"
    - "9300:9300"
