### ISSUE TITLE
resource updated time is updated on view and download

### ISSUE THREAD

**Issue by sblack-usu** [hydroshare/hydroshare#3206]
With the resource landing page redesign, a view and download count was introduced to the Resource model.  These counts are updated each time the resource page is loaded or the resource is downloaded, which triggers a save that hooks into mezzanine's TimeStamp model which automatically updates the updated time.  
https://github.com/hydroshare/hydroshare/blob/develop/hs_core/models.py#L1672

Proposed changes:
Instead of using mezzanine's updated field, we should add our own and only update it in the resource_modified method here. https://github.com/hydroshare/hydroshare/blob/develop/hs_core/hydroshare/utils.py#L455

This will fix the bug we're currently experiencing and avoid accidentally creating this bug again.

**Comment by sblack-usu** [comment]
@pkdash @hyi - Please review and let me know if you agree with the proposed changes or have any other ideas.  We noticed after 1.19.1 was released that the last updated time always reflects the current time that you're viewing.  We initially thought it was due the resource size change, but after further investigation, I've found the view_count and download_count on the resource model to be the real culprits.

**Comment by pkdash** [comment]
@sblack-usu Since we store the resource update as part of the metadata, we can use that in resource landing page. 

https://github.com/hydroshare/hydroshare/blob/develop/hs_core/hydroshare/utils.py#L469
https://github.com/hydroshare/hydroshare/blob/develop/hs_core/models.py#L646

**Comment by pkdash** [comment]
Mezzanine is a big headache for HydroShare. Hope one day we can get rid of it.

**Comment by sblack-usu** [comment]
Thanks @pkdash.  I think we should be able to use that date easily.  And it will restore the actual "last updated" time... which is a pretty big win.

**Comment by hyi** [comment]
@sblack-usu @pkdash Agreed - it should be pretty easy just to use modified date type in resource metadata for display on resource landing page to address this issue.

**Comment by sblack-usu** [comment]
released in 1.20
