### ISSUE TITLE
Mistaken name of a Readme.txt to Readme.md gives an error page

### ISSUE THREAD

**Issue by gopalam** [hydroshare/hydroshare#3208]
I was looking to render text via readme.txt. When my file did not render after a few refresh attempts, I did not think through and renamed the file as .md file (which it was not a markdown format file), and uploaded to the resource landing page.
The mistake took down my resource landing page for this particular dataset. My apologies for the mistake. Could my archive be revived?

**Comment by dtarb** [comment]
Please give the identifier of the problem resource or your name so we can find it and take a look.  You should be able to see the resource listed on My Resources and right click copy link location in the title to get the resource landing page URL without opening the landing page.

If you have the data and have not made any references to this specific resource it may be easiest to create a new resource with the same data and delete this resource (also from the My Resources page).

**Comment by horsburgh** [comment]
Also - it might be useful to have a look at the readme file you renamed. If it's small enough, I think you can just upload it in this issue. Markdown files are just text files with a .md extension. They may contain markdown formatting, but ultimately, it's just text. So, it would be useful to see if we can duplicate your error with your file so we can track down what caused this.

**Comment by gopalam** [comment]
Hi David
Thank you for this information. Here is the link to the resource identifier.
https://www.hydroshare.org/resource/252c0c060afd4d4798e78cb805e81887/
While the resource and metadata are small enough to recreate, we  linked it to a  proposal and report that we submitted right before this error occurred. So, it would be good if I can retain the identifier so that the access is not an issue for review.  As a last resort, I will delete the resource and create a new one.

Thank you very much for your help.I really appreciate the work you have out to create Hydroshare. This is, bar none, the best data repository for our work.

Gopal
On 2/28/2019 11:26 PM, David Tarboton wrote:
Caution - External Email
________________________________

Please give the identifier of the problem resource or your name so we can find it and take a look. You should be able to see the resource listed on My Resources and right click copy link location in the title to get the resource landing page URL without opening the landing page.

If you have the data and have not made any references to this specific resource it may be easiest to create a new resource with the same data and delete this resource (also from the My Resources page).

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_hydroshare_hydroshare_issues_3208-23issuecomment-2D468538078&d=DwMFaQ&c=c6MrceVCY5m5A_KAUkrdoA&r=BOxETivY186L3R4xZ4LRGtxqlYsLGlGsM3FSw65iZtk&m=b_pVWgDFFg5l7eDhvQl-QAFJrXJqU5uvoP1lhniD7cc&s=g6i7x7kJbwT2pDb4FewLgmV3xjsCoCKu3l4yvrMDEi0&e=>, or mute the thread<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AIY5YlOnBwIDXMRgHA35fTH-2D4eQNi3Adks5vSKwBgaJpZM4bYHeX&d=DwMFaQ&c=c6MrceVCY5m5A_KAUkrdoA&r=BOxETivY186L3R4xZ4LRGtxqlYsLGlGsM3FSw65iZtk&m=b_pVWgDFFg5l7eDhvQl-QAFJrXJqU5uvoP1lhniD7cc&s=jp9mBpiccJddKdHYGw5nMIBomdQxMJJynlcB_FZq-EY&e=>.


--
Water Systems Analysis Group
Earth Systems Research Center
University of New Hampshire
603-862-2460

**Comment by gopalam** [comment]
Hi Jeff.
Thank you for your efforts to fix this issue. I have attached the readme.md file with this email. I initially uploaded this text as a readme.txt file, but it failed to render .  I then mistakenly left the file in, and uploaded the same file as a renamed readme.md.  That was when the resource landing page showed the error.  The link to the resource landing page is here.
https://www.hydroshare.org/resource/252c0c060afd4d4798e78cb805e81887/
The text is a basic description of sites, and some variable names in our files.  I am still trying to learn your system, and the ODM metadata format . I am yet to convert my csv formatted files to Sqlite file, so I figured incorporating some basic meta data this way would be helpful.

Thank you once again. I have followed your research and publications over the years, and I really appreciate the work you are doing.

Gopal

On 3/1/2019 12:11 AM, Jeff Horsburgh wrote:
Caution - External Email
________________________________

Also - it might be useful to have a look at the readme file you renamed. If it's small enough, I think you can just upload it in this issue. Markdown files are just text files with a .md extension. They may contain markdown formatting, but ultimately, it's just text. So, it would be useful to see if we can duplicate your error with your file so we can track down what caused this.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_hydroshare_hydroshare_issues_3208-23issuecomment-2D468544946&d=DwMFaQ&c=c6MrceVCY5m5A_KAUkrdoA&r=BOxETivY186L3R4xZ4LRGtxqlYsLGlGsM3FSw65iZtk&m=0MXZMv2qSRCRks0I_AU-hF7GihB53ZIfq4U0JE7JAVU&s=plZgGwnl-UFlWyoMRcQ0FlwnnBIH_ESpyygLu01CdF8&e=>, or mute the thread<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AIY5YqQEH2MeqZeoSFWmb-5FIbXtwgr8imks5vSLaVgaJpZM4bYHeX&d=DwMFaQ&c=c6MrceVCY5m5A_KAUkrdoA&r=BOxETivY186L3R4xZ4LRGtxqlYsLGlGsM3FSw65iZtk&m=0MXZMv2qSRCRks0I_AU-hF7GihB53ZIfq4U0JE7JAVU&s=q98Gho2okqGSAGcRh_8VSMeXz8wgW1gFmr_uKwmpxmM&e=>.


--
Water Systems Analysis Group
Earth Systems Research Center
University of New Hampshire
603-862-2460

METADATA DOCUMENT
Water Quality at Mill Pond Reservoir on Oyster River , Durham, NH
Developed by: Gopal Mulukutla, with input from Wil Wollheim and Eliza Balch, University of New Hampshire
Contact information: gopal.mulukutla@unh.edu
Table1 – Describes the monitoring locations on the Oyster River.  Station names referred here are used in aggregated level 1 files archived on Hydroshare.

Station Name, Station
Description, Lat, Long, Total Area
km2, Comment
HAM, Hamel Brook, 43.118508, -70.921881, 1.8, Major Inflow to Reservoir
CLGB, College Brook at Mill Plaza, 43.131306, -70.924639, 2.3, Major Inflow to Reservoir
ORR, Oyster River at OR Road, 43.126653, -70.927921, 44.9, River Inflow to Reservoir
OMPD, Oyster River at Mill Pond, 43.130880, -70.918497, 50.6, Outflow from Reservoir


Table 2:  Sensors deployed at each site.
Description including name of equipment: , Measurement, Location
SUNA (Submersible Ultraviolet Nitrate Analyzer), Nitrate , ORR HAM OMPD
Realtech GL2000 Series Sensor, Nitrate, ORR
YSI EXO2, fDOM*, turbidity*, pH*, conductivity, dissolved oxygen*, OMPD
Onset Inc. Hobo water level and conductivity logger, Stage height, water temperature and specific conductivity., ORR CLGB HAM 
Meter Environment, CTD-10 , conductivity, water depth and temperature sensors, OMPD CLGB
*data for these variables not compiled in the datasets provided here.


      Table3: Time frame of deployment of sensors for each site.
Station Name, Station
Description, Sensors Deployed, Time Frame of Study, Time Frame of Nitrate Sensor Deployment
HAM, Hamel Brook, Stage height, conductivity, temperature, and nitrate, 2018-05-01 to 2018-11-19, 2018-08-20 to 2018-10-12
CLGB, College Brook at Mill Plaza, Stage height, conductivity, temperature, 2018-05-30 to 2018-12-14, N/A
ORR, Oyster River at OR Road, Stage height, conductivity, temperature, 2018-05-30 to 2018-12-15, 2018-08-14 to 2018-12-11
OMPD, Oyster River at Mill Pond, Stage height conductivity nitrate , 2018-05-01 to 2018-12-20, 2018-05-01 to 2018-12-20

Table 4:  Summary of variable names in headers, and their description
Variable Name, Description
STAGE.M.HOBO, Stage height in meters
TEMP.C.HOBO, Temperature in degrees Celsius from continuous sensor
SPCOND.uScm.HOBO, Specific Conductance in µS/cm from continuous sensor
NO3.MGL, Sensor based NO3-N milligram per liter
Cl.MGL.GRAB, Chloride milligram per liter
NO3.MGL.GRAB, Grab sample based NO3-N milligram per liter
SO4.MGL.GRAB, Grab sample based SO4 milligram per liter
NA.MGL.GRAB, Grab sample based Sodium milligram per liter
K.MGL.GRAB, Grab sample based Potassium in milligram per liter
MG.MGL.GRAB, Grab sample based  Magnesium in milligram per liter
CA.MGL.GRAB, Grab sample based  Calcium in milligram per liter
TEMP.C.HANDHELD, Temperature in degrees Celsius from handheld sensor
SPCOND.uScm.HANDHELD, Specific Conductance in µS/cm from handheld probe
DO.PERCENT.HANDHELD, Dissolved Oxygen Percent Saturation from handheld probe
DO.MGL.HANDHELD, Dissolved Oxygen concentration in milligram per liter 
STAGE.CM.VISUAL, Stage height in cm from visual in-ground stream gage
NO3_MGL_REALTECH , Sensor based NO3-N milligram per liter from Realtech sensor
NO3_FLAG_REALTECH, Bad data flag for sensor based NO3-N milligram per liter from Realtech sensor
NO3_MGL_MOVAVG_REALTECH , Sensor based NO3-N milligram per liter processed data by removing noise
NO3_MGL_SUNA, Sensor based NO3-N milligram per liter from SUNA sensor

**Comment by horsburgh** [comment]
I suspect there may be something else going on here. I copied the text in your comment above into a file called readme.md and uploaded it to a new resource on production HydroShare and the beta system. Both systems rendered the text of the readme file on the page. I also tried readme.txt on both systems, and that extension worked as well. I also tried renaming the files from .txt to .md after uploading and didn't get errors. We may have to dig deeper.

**Comment by gopalam** [comment]
Thank you for following up on this. I am pretty sure that the resource landing page started showing an error as soon as I uploaded the readme.md file and refreshed. Perhaps there is something else that occurred at the same time. I will go ahead and re-create my archive. If it helps, I will leave the current, non-functional one,  as is for now.
I appreciate your help.
Gopal
On 3/1/2019 10:38 AM, Jeff Horsburgh wrote:
Caution - External Email
________________________________

I suspect there may be something else going on here. I copied the text in your comment above into a file called readme.md and uploaded it to a new resource on production HydroShare and the beta system. Both systems rendered the text of the readme file on the page. I also tried readme.txt on both systems, and that extension worked as well. I also tried renaming the files from .txt to .md after uploading and didn't get errors. We may have to dig deeper.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_hydroshare_hydroshare_issues_3208-23issuecomment-2D468706510&d=DwMFaQ&c=c6MrceVCY5m5A_KAUkrdoA&r=BOxETivY186L3R4xZ4LRGtxqlYsLGlGsM3FSw65iZtk&m=okF3o6xns97lA1nj8s6N8wM4aAGjYmoh0aclJBCX2J4&s=z5aUmiNVSooDOcGn1Z-2G2NTWU2T7u0kbRvIjhzByKs&e=>, or mute the thread<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AIY5Ym58zsjiVwxypKqqBSh2VuYnLY8sks5vSUl8gaJpZM4bYHeX&d=DwMFaQ&c=c6MrceVCY5m5A_KAUkrdoA&r=BOxETivY186L3R4xZ4LRGtxqlYsLGlGsM3FSw65iZtk&m=okF3o6xns97lA1nj8s6N8wM4aAGjYmoh0aclJBCX2J4&s=6UjgtYsCVTAr16xmElUNllhjf74HTNalTUaQcotfRUk&e=>.


--
Water Systems Analysis Group
Earth Systems Research Center
University of New Hampshire
603-862-2460

**Comment by sblack-usu** [comment]
@gopalam It looks like you deleted the resource, could you confirm?  I have some time to look into this issue and will try to recreate if you've already deleted the resource.

**Comment by Castronova** [comment]
Closing, cannot replicate and original resource does not exist for testing. @gopalam please re-open if you're still encountering this issue.
