### ISSUE TITLE
Change name of "Multidimensional Space and Time Data Resource"

### ISSUE THREAD

**Issue by danames** [hydroshare/hydroshare#321]
Can we change this to something simple like "Multidimensional NetCDF"?

Can we put the file type in parentheses in the "Select a resource type" drop down box: 

"Geographic Raster (GeoTiff)"

Can we remove the word "Resource" from our resource names?

**Comment by dtarb** [comment]
For consistency how about
"Multidimensional (NetCDF)"
"Geographic Raster (GeoTiff)"

**Comment by danames** [comment]
Yes. It's brief and informative. I like these two names.

**Comment by gantian127** [comment]
The geographic raster may support other raster file formats in the future, so not so sure if we need to include the file format info in the resource type name. Besides, in the initial plan, HydroShare will provide webpages to introduce each of the resource type and it may include the detailed info for supported file formats and the resource creation page also shows the supported file format extension info.

One suggestion for the two resource type names:
"Geographic Raster": data as 2D grid data (sometimes data may include time dimension)
"Multidimensional Geospatial Data": data as 3D or higher dimension feature or grid data (sometimes data may be 2D data)

**Comment by dtarb** [comment]
Tested in alpha

**Comment by dtarb** [comment]
This issue was fixed in our 1.5 beta deployment but appears to have been lost in the current deployment on dev.

**Comment by dtarb** [comment]
@mjstealey please re-merge Tian's code that set these names.

**Comment by mjstealey** [comment]
This is likely due to a branch being merged that had made it's own changes to the create-resource file, but had not rebased against the updated information as added by Tian.

Will do this as a new branch, and not re-open a previously closed branch as that might add it's own inaccuracies to what is already there.

**Comment by dtarb** [comment]
Tested.  Now correct on dev.
