### ISSUE TITLE
Large files are rejected, but resource creation process continues without warning

### ISSUE THREAD

**Issue by hydrocheck** [hydroshare/hydroshare#3215]
If you upload a large file (e.g. 2GB), then click Create Resource, it appears as though everything is working fine.  However, the file is not in the resulting resource contents.  there is a red glow around the file, but better warning of the 1GB limit would be ideal here. 

[002.zip](https://github.com/hydroshare/hydroshare/files/2929474/002.zip)

**Comment by Maurier** [comment]
The file will also show a more descriptive error message when hovered over. 
![image](https://user-images.githubusercontent.com/2448568/54325370-6bbf0500-45c7-11e9-9f25-ceb7b1822144.png)

However, this entire page will be obsolete and removed with changes to the resource creation process in https://github.com/hydroshare/hydroshare/issues/3242 in the near future. For this reason we probably won't be making improvements to this part of the UI.

**Comment by ndebuhr** [comment]
This has since been resolved
