### ISSUE TITLE
The navigation that usually stays at the top of the screen (for quick use) works differently in IE11

### ISSUE THREAD

**Issue by hydrocheck** [hydroshare/hydroshare#3221]
The navigation does not move with the page (stay fixed on the screen), as is usually expected with the other browsers.  This is on the resource page.

[008.zip](https://github.com/hydroshare/hydroshare/files/2929485/008.zip)

**Comment by Maurier** [comment]
This has been fixed and can be tested at https://beta.hydroshare.org
