### ISSUE TITLE
The "No Extended Metadata" message does not display on IE11

### ISSUE THREAD

**Issue by hydrocheck** [hydroshare/hydroshare#3222]
Compare Chrome to IE11 images.  The "No Extended Metadata message should presumably be displayed - it is not for IE11.  Rather, just the table header is there.

[009.zip](https://github.com/hydroshare/hydroshare/files/2929488/009.zip)

**Comment by Maurier** [comment]
This has been fixed and can be tested at https://beta.hydroshare.org
