### ISSUE TITLE
No handling of long keywords in resource pages

### ISSUE THREAD

**Issue by hydrocheck** [hydroshare/hydroshare#3224]
A "..." or other truncation would generally be expected for long keywords in the resource pages.  However, there is no handling like this, and the keyword instead messes up the interface.

[011.zip](https://github.com/hydroshare/hydroshare/files/2929495/011.zip)

**Comment by cuahsimarko** [comment]
@mraocuahsi Let's fix this in Groups and then consider other areas it needs to be applied, because code is just repeated across a few other places.

**Comment by mraocuahsi** [comment]
Not able to reproduce the error in production server
![Screenshot from 2019-05-06 13-22-21](https://user-images.githubusercontent.com/49655428/57242707-3b617900-7002-11e9-9893-dafc125bd986.png)

**Comment by mraocuahsi** [comment]
Duplicated : #3053 3053
