### ISSUE TITLE
Searching users to add as contributors does not work in IE11

### ISSUE THREAD

**Issue by hydrocheck** [hydroshare/hydroshare#3226]
If you create a Web App resource, then try to add contributors, you'll find that the user search feature doesn't work like other browsers.  Namely, the search doesn't work at all.

[013.zip](https://github.com/hydroshare/hydroshare/files/2929499/013.zip)

**Comment by Maurier** [comment]
This bug was reintroduced recently, but caused by another issue: 
![image](https://user-images.githubusercontent.com/2448568/57311608-2e4b9500-70a9-11e9-9517-dfbf9113834b.png)

I will be addressing these.

**Comment by Maurier** [comment]
This has been fixed and can be tested at https://beta.hydroshare.org
