### ISSUE TITLE
Support any tiff file and gracefully handle missing geotiff data

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#324]
If a tiff file without geotiff tags is loaded the latitude and longitude are filled with the number of rows and columns.  They should rather be filled with NA and eventually allow user editing to fill them in.

**Comment by hyi** [comment]
Fix pushed to my feature branch with a pull request created.

**Comment by hyi** [comment]
Tested on dev and everything works as expected now. Set ready for testing label to be tested on dev.

**Comment by dtarb** [comment]
Incorrect and invalid north latitude and east longitude were still filled in on my test.  These should be NA.
![untitled](https://cloud.githubusercontent.com/assets/3456833/7550277/782b301e-f618-11e4-88bf-52b8c78f02ef.png)

**Comment by dtarb** [comment]
Also the labeling of resource specific coordinates is incorrect.  The terms latitude and longitude should not be used to refer to projected quantities.  See the following suggested edits.  
![untitled](https://cloud.githubusercontent.com/assets/3456833/7551900/556adca2-f657-11e4-8a6f-ed1b392ee083.png)

**Comment by dtarb** [comment]
See following Alfresco document for details on editable fields for raster resource https://my.alfresco.com/share/s/DeXkAhEgS8GjrgTWOSpp0w

**Comment by dtarb** [comment]
The problem of Spatial Reference Holding Spurious information when it is missing still persists.
![untitled](https://cloud.githubusercontent.com/assets/3456833/8026163/89fc11be-0d29-11e5-84ec-feedb03100d5.png)

**Comment by hyi** [comment]
Tested on dev and it appears this issue is fixed, so set it as ready for testing.

**Comment by dtarb** [comment]
I tested this and it does not seem quite right.  When I loaded the Honduras tif file (which you can see at https://www.hydroshare.org/resource/c81142cbe23548718657c34099c3b254/) the coverage metadata tab is missing and under resource specific the cell sizes are 0.  In the current implementation on www the coverage element is there but with NA, and the cell sizes are 1.  This seems preferable to me.

**Comment by hyi** [comment]
@dtarb: @gantian127 indicated she had discussed this with you, and you kind of agreed what is currently on dev now sounds acceptable and right. I also agree what is on dev now seems to look reasonable with coverage tab missing when coverage info does not exist, and user always can edit the metadata and add coverage info as needed. @gantian127 will work on any further issues related to this if any. So I am assigning this issue to @gantian127 although this issue might be ready to close.

**Comment by hyi** [comment]
@dtarb @gantian127 Can this issue be closed?
