### ISSUE TITLE
Toggle public button without refresh

### ISSUE THREAD

**Issue by sblack-usu** [hydroshare/hydroshare#3243]
Currently a new resource cannot be made public unless it has a title, keywords, abstract and file(s).  I determined that if you add a file after adding the others, the public button does not enable without a refresh.  However, if you modify keywords it will enable the public button without a refresh.

Update the file add process to enable the public button on upload if appropriate.  For guidance, look at how keywords is already doing it.  Check to ensure Title and abstract have the same functionality, and update them if necessary.

**Comment by Lizabrazil** [comment]
@Maurier This came up for pushing to 1.22, what is the status on it? thanks

**Comment by Maurier** [comment]
@Lizabrazil. The code is ready for a final review: https://github.com/hydroshare/hydroshare/pull/3246. Hopefully @sblack-usu can take a look sometime this week.

**Comment by Lizabrazil** [comment]
Great, I will tag with 1.22

**Comment by Maurier** [comment]
These changes have been made and deployed to www.hydroshare.org
