### ISSUE TITLE
Update modified date on discover

### ISSUE THREAD

**Issue by sblack-usu** [hydroshare/hydroshare#3245]
The list of resources on the discover page shows the wrong updated time.  We should be using the the res_modified_date saved in metadata, not the mezzanine updated field.

**Comment by sblack-usu** [comment]
@alvacouch - I assigned you because you have the most familiarity with with solr.  If you don't have time to make the change, please leave some guidance on how to make the change.

**Comment by alvacouch** [comment]
This is systemic as there are several displays thst use the last updated time. same issue with current code for communities, dashboard.

**Comment by sblack-usu** [comment]
we've already update resource landing page and my-resources.  Communities and Dashboard haven't been finished yet, but should use modified date as well.
