### ISSUE TITLE
Some improvements needed to references

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#3261]
This follows on from #2763 which was closed.

@horsburgh and @Lizabrazil  please take a look at this.  I think @Maurier can fix the presentation aspects of this, but the review of how metadata is handled needs design level input.

I think there is ambiguity between "Sources" and "Related resources".  In particular "Derived from" which is the only option under "Sources" is explained as "data in your resource was derived from another source or dataset" and seems to mean almost the same as "The content of this resource was copied from" which is associated with copy.  Further, if I make a copy of a resource using the HydroShare copy button the "Derived from" field is filled out.

Looking into this further leads to identification of a number of additional problems and  I think there is a need for a review of our handling of the relationships aspects of metadata.

I think that "Sources" and "Related Resources" should be consolidated into a single list just named "Related Resources".  I suggest related resources, not References as "Relation" is the word used in Dublin Core.  http://www.dublincore.org/specifications/dublin-core/dcmi-terms/#terms-relation

Following are some problems I identified (but there are probably others).
-	The terms hsterms:isDataFor, hsterms:cites, hsterms:isExecutedBy, hsterms:isCreatedBy, hsterms:isDescribedBy, hsterms:isDerivedFrom are missing definitions in https://www.hydroshare.org/terms/
-	Some of the above could probably be covered by standard Dublin core terms.  E.g cites could use Dublin Core "References" "A related resource that is referenced, cited, or otherwise pointed to by the described resource." http://www.dublincore.org/specifications/dublin-core/dcmi-terms/#terms-references
-	In our metadata we have source as a separate entry from relationships.  I think it may be better to have source as a type of relationship.  This appears to be how it is done at http://www.dublincore.org/specifications/dublin-core/dcmi-terms/#terms-source.  This would mean replacing the following in our metadata 

```
<dc:source>
      <rdf:Description>
        <hsterms:isDerivedFrom rdf:resource="http://www.hydroshare.org/resource/c6af6c104bed4f16a60a272dd5115be3"/>
      </rdf:Description>
</dc:source>
```
by
```
<dc:relation>
      <rdf:Description>
        <dcterms:source rdf:resource="http://www.hydroshare.org/resource/c6af6c104bed4f16a60a272dd5115be3"/>
      </rdf:Description>
</dc:relation>
```
Inconsistent formatting in edit mode
![image](https://user-images.githubusercontent.com/3456833/54882411-5e9fe280-4e1f-11e9-99a3-a6d4fa8fc4a1.png)
This resolves if there is more content
![image](https://user-images.githubusercontent.com/3456833/54882430-94dd6200-4e1f-11e9-9691-3d936c6836ee.png)

Our business logic does not admit creating an "isCopiedFrom" relationship and an "isHostedBy" relationship.  Does the isHostedBy relationship still make sense now that we have reference links in the content of the resource.

![image](https://user-images.githubusercontent.com/3456833/54882445-bcccc580-4e1f-11e9-9623-af515e8aa611.png)
The relationship created when a resource is copied using the HydroShare copy button should be the full citation, not just the URL
![image](https://user-images.githubusercontent.com/3456833/54882471-e1c13880-4e1f-11e9-8bc8-a41c16cbe72c.png)
The relationship created when a new version is created using the HydroShare new version button, should have more descriptive text and should be the full citation (as from how to cite), not just the URL
![image](https://user-images.githubusercontent.com/3456833/54882479-12a16d80-4e20-11e9-83a0-24dea073e189.png)

The rdfs1 schema we refer to in our metadata is no longer findable http://www.w3.org/2001/01/rdf-schema#

**Comment by horsburgh** [comment]
# In process ignore for now

Collecting some notes for this issue, but will likely split this out into multiple issues for implementation:

"Source" and "Relation" are two separate Dublin Core metadata elements. Thus, we implemented them that way in our metadata. I think we should keep this, but Dave points out a simplification that may help with semantics. Here's the definitions from Dublin Core:

DC "Relation": A related resource.
DC "Source": A related resource from which the described resource is derived.

So, "Source" is a "Relation" and could be expressed as such. If we make the change suggested by @dtarb, it simplifies the metadata and puts the "Source" element inside of the "Relation" element. That's fine, but does affect the RDF triples:

Current:
![image](https://user-images.githubusercontent.com/3485902/55021005-a2c8e980-4fbd-11e9-9c34-6008cecc4494.png)

Proposed:
![image](https://user-images.githubusercontent.com/3485902/55020933-7f9e3a00-4fbd-11e9-9325-d09ad1a2c617.png)

I don't think this change is a problem except that a reader would actually have to look up the "Source" term at Dublin Core to determine that "Source" actually means "derived from."

I suggest we adopt the change in metadata suggested by @dtarb as follows:

```
<dc:relation>
      <rdf:Description>
        <dcterms:source rdf:resource="http://www.hydroshare.org/resource/c6af6c104bed4f16a60a272dd5115be3"/>
      </rdf:Description>
</dc:relation>
```

**NOTE: This will affect every HydroShare resource that has a "Source" element.**

http://www.w3.org/2001/01/rdf-schema# should be corrected to http://www.w3.org/2000/01/rdf-schema#
Note sure what happened here or why this URL is incorrect.

**Comment by horsburgh** [comment]
Proposed approach for handling cleanup of all related resource issues is in the following Google doc for discussion: 

https://docs.google.com/document/d/1BssYnm6Taw3GVW8Qv8ldLO-H3VZqo16Kejypkrmd6KA/edit

I'm going to close the related issues and point them here because this is a comprehensive coverage of those other issues.

**Comment by dtarb** [comment]
#1494 (that was closed) offered the suggestion for an interface option to select or "pick" a HydroShare resource when adding a relationship (similar to the way add author gives an option to pick from existing users).  This is thus a picker or helper interface over and above the entry of content into a text box and clarification of terminology that is being addressed here.  I wanted to draw attention to this here, so it did not get lost in the closing of #1494.  If a resource is picked, a full citation to the resource should be inserted into related resource field.

**Comment by horsburgh** [comment]
@Maurier, @sblack-usu, and @pkdash - I think the work on this issue can proceed. We've had some feedback from @alvacouch on the Google Doc (linked in the post above), but I think it doesn't change the plan. 

@Maurier - I'm hoping you can do the front end changes that need to be made.

@sblack-usu and @pkdash - do you guys want to talk and decide who is best to do the back end parts of this? These changes touch several pieces of functionality in HydroShare, including the Resource Landing Page, the resourcemetadata.xml encoding, copying resources, versioning resources, collections, and the HydroShare terms page.

@hyi - I'm also tagging you here because this touches versioning and copying which I think you worked on.

We should probably have one coordinator for the overall package to make sure everything gets done. I'll be happy to help with testing, etc.  Let me know if you think we need to break the Google Doc up into multiple issues for tracking or whether you want to work from the Google Doc.

**Comment by Maurier** [comment]
@horsburgh, understood. We'll coordinate to have it ready for the upcoming release. 

@sblack-usu, @pkdash Let me know which one of you would like to implement this backend functionality.

**Comment by sblack-usu** [comment]
I'd like to tackle this with @Maurier.  It'll give me some time to better understand how we generate our metadata and help me with bag ingestion.

**Comment by hyi** [comment]
@horsburgh Yes, I worked on versioning and copying. The code that need to be changed related to this issue are isolated to these few lines of code: https://github.com/hydroshare/hydroshare/blob/develop/hs_core/hydroshare/resource.py#L659-L661
for resource copying and https://github.com/hydroshare/hydroshare/blob/develop/hs_core/hydroshare/resource.py#L698-L705 for resource versioning. Looping in @sblack-usu for his reference when he tackles the backend.

**Comment by pkdash** [comment]
Let me know if you need me on this.

**Comment by dtarb** [comment]
@horsburgh we are looking at this as part of issue review.  Please review and act as needed.

**Comment by dtarb** [comment]
There is a question in the Google Doc mentioned above as to whether the relationship dcterms:IsPartOf should be saved in resourcemetadata.xml.  I suggest it should as this is part of the general trend towards all metadata being file based.  But @horsburgh suggested to check with @sblack-usu.  Thinking about this though does raise a policy question we need to consider.  At present user A can permanently publish a resource R.  User B who has no permissions from user A can add R to a collection.  This would trigger a change in the metadata on R, but A has no permissions to change anything on R.  There is also a bit of a spam consideration.  If I add your resource to my dubious collection, you end up with a resource that says it is part of my dubious collection.  Should this be allowed.  It is so far and there have not been complaints or abuse we know of.

**Comment by pkdash** [comment]
@dtarb and @horsburgh I did test this issue on production and it seems to be working -so closing it for now. Feel free to re-open if you see something is not working.
