### ISSUE TITLE
Non-utf8 characters cause issues in resource READMEs

### ISSUE THREAD

**Issue by hydrocheck** [hydroshare/hydroshare#3262]
Intense error comes up if non-utf8 characters are used in a resource readme.

[001.zip](https://github.com/hydroshare/hydroshare/files/3000651/001.zip)

**Comment by dtarb** [comment]
I think this one is high priority.  I do not recall who implemented README rendering functionality so am tagging @Maurier @sblack-usu @hyi @pkdash @cuahsimarko.  I suggest that the behavior whenever a problem readme file is encountered (e.g. unable to parse the text or markdown) should be a message "Unable to parse and format readme" in the place where it would have been displayed followed by a display of the text from the file as converted to whatever text encoding we are using.  Hopefully that would let a user see the problem.  

While it would be nice to be as comprehensive as github in parsing markdown as discussed in #3227, that may be too hard and I am in favor of a simple solution that while perhaps not completely general at least provides a user with some feedback and ability to construct their markdown in a way that HydroShare can parse.

**Comment by Maurier** [comment]
Could I have the file that was used to test this?

**Comment by hydrocheck** [comment]
@Maurier Sorry meant to attach that.
[readme.zip](https://github.com/hydroshare/hydroshare/files/3000984/readme.zip)

**Comment by Maurier** [comment]
@pkdash, I found that decoding as "unicode_escape" instead of "utf-8" can handle these characters, but I would like to hear your opinion on how we encode and decode these files.  Let me know if it's ok to make the switch.

**Comment by pkdash** [comment]
@Maurier We are not encoding the contents of the readme file. I guess we need to check the file content encoding first before decoding to utf-8. I will try to fix it soon.

**Comment by cuahsimarko** [comment]
UTF-8 primer https://pythonhosted.org/kitchen/unicode-frustrations.html

**Comment by pkdash** [comment]
Should this be closed?

**Comment by sblack-usu** [comment]
Was released in 1.22
