### ISSUE TITLE
When adding an author website, the protocol is required but that's not made clear

### ISSUE THREAD

**Issue by hydrocheck** [hydroshare/hydroshare#3263]
When adding an author website, it will reject domains without the protocol.  For example www.example.com.  I'm not aware of a way to have a website run on something besides http/https, so the protocol seems unnecessary.  Additionally, the error message is not very helpful - just mentions the url is invalid.

[003.zip](https://github.com/hydroshare/hydroshare/files/3000653/003.zip)

**Comment by ClaraCogswell** [comment]
Closing: implemented
