### ISSUE TITLE
Capitalization issue - "Programming language" in the resource landing page Resource Specific metadata

### ISSUE THREAD

**Issue by hydrocheck** [hydroshare/hydroshare#3267]
All the other fields with multiple words have all words capitalized

[008.zip](https://github.com/hydroshare/hydroshare/files/3000660/008.zip)

**Comment by cuahsimarko** [comment]
@ndebuhr Let's consider consolidating some of these, when it's such a tiny change.

**Comment by cuahsimarko** [comment]
![image](https://user-images.githubusercontent.com/45397838/56605216-99896780-65d1-11e9-86b4-3de71521e496.png)
