### ISSUE TITLE
Without resource logos, the Discover table can look messy

### ISSUE THREAD

**Issue by hydrocheck** [hydroshare/hydroshare#3268]
Some of the resources don't have resource type logos, which makes the table look somewhat messy.

[009.zip](https://github.com/hydroshare/hydroshare/files/3000661/009.zip)

**Comment by Maurier** [comment]
I believe this a duplicate of https://github.com/hydroshare/hydroshare/issues/3259

**Comment by pkdash** [comment]
PR #3260  should also fix this issue.

**Comment by dtarb** [comment]
Fixed on 1.21 RC
