### ISSUE TITLE
When the "About" tab is clicked, the "Help" tab is styled as active

### ISSUE THREAD

**Issue by hydrocheck** [hydroshare/hydroshare#3270]
When the "About" tab is clicked, the "Help" tab is styled as active

[011.zip](https://github.com/hydroshare/hydroshare/files/3000663/011.zip)

**Comment by dtarb** [comment]
If we act on #3242 suggestions to remove About, this will be moot.

**Comment by engineSound** [comment]
@martinseul  The "Help" and "About" menu items are separated from the rest. The rest are built from mazzanine. So the behavior is different. With the new static link fix from @sblack-usu, where the mazzanine gear is disengaged, the behavior should be gone.

**Comment by hydrocheck** [comment]
Verified on beta.  Closing as resolved.
