### ISSUE TITLE
User is logged out upon password change

### ISSUE THREAD

**Issue by hydrocheck** [hydroshare/hydroshare#3272]
Other websites tend to keep the user logged in after they change their password.  Is there a reason we are logging users out after a password change?

[013.zip](https://github.com/hydroshare/hydroshare/files/3000665/013.zip)

**Comment by cuahsimarko** [comment]
@ndebuhr many sites I use log me out or ask me to if I recall. Can someone else confirm?

**Comment by ClaraCogswell** [comment]
Closing: this is typical behavior, low impact
