### ISSUE TITLE
The "user type" on the hydroshare profile page is incorrectly formatted

### ISSUE THREAD

**Issue by hydrocheck** [hydroshare/hydroshare#3273]
When using "Other" for User Type on the profile page, the field is styled with blank space before the input field.

[014.zip](https://github.com/hydroshare/hydroshare/files/3000666/014.zip)

**Comment by Maurier** [comment]
The idea with the indent was to make it look as a child input of the one above. But I think it doesn't really accomplish that, so I agree this would look better if we remove the blank space.

I'll wait to hear from @Lizabrazil or @dtarb on this.

**Comment by dtarb** [comment]
I really do not mind on this one.  This has been there for so long.  I think there are many more important things to worry about than changing this, but then also many more important things to worry about than debating not changing this.  I would be inclined to fix higher priority things first like #3262, #3242, #3263, #3261

**Comment by Lizabrazil** [comment]
Not a show stopper, when you get a chance it should be fixed to remove the blank space.

**Comment by hydrocheck** [comment]
Verified on beta.  Closing as resolved.
