### ISSUE TITLE
Search by title fails

### ISSUE THREAD

**Issue by martinseul** [hydroshare/hydroshare#3292]
For the CZO we have Titles that are automatically created as a concatenation of several attributes and look like this 
BCCZO - Well Water Levels - (GGU_GW_1,2,6_Pducer_Tran) - Gordon Gulch: Upper (2011-2017) 
![1]
if i search for this in discover I get this error:
Field delimiter 'Gulch' is not recognized. Field delimiters include title, contributor, subject, etc. Please try again.

![Capture](https://user-images.githubusercontent.com/5427742/55502106-cfae7980-5619-11e9-9b8a-3151b1b8f03a.JPG)

looks like the colon creates a problem

**Comment by horsburgh** [comment]
I'm sure @alvacouch can elaborate here, but this is related to the fact that HydroShare enables search terms to be entered that search specific metadata "Fields" for specific terms where the field and terms are separated by colons. For example the following search string looks for all resources with an author of "Horsburgh" and a subject keyword of "Temperature":

author:Horsburgh subject:Temperature

So, if you include colons in resource titles and search using a big long string that has colons in it, it will cause problems.

**Comment by alvacouch** [comment]
I will ignore bad search terms and treat them as plaintext. This is easy. Other changes are much harder.

**Comment by horsburgh** [comment]
@alvacouch - that seems like a reasonable approach. For what it's worth - I really like the ability to do the search using the *{field}:{value}* syntax and so would be sad to see it go.

**Comment by alvacouch** [comment]
Fixed in pr #3309 .

**Comment by cuahsimarko** [comment]
@alvacouch hi we are discussing this right now just marking

**Comment by alvacouch** [comment]
I remain convinced that I should put keywords in ALL CAPS, e.g., TITLE: AUTHOR: CONTRIBUTOR: .... 
in order to avoid collision. Other than this, PR #3309 addresses this issue.

**Comment by cuahsimarko** [comment]
@martinseul I successfully searched for "BCCZO - Well Water Levels - (GGU_GW_1,2,6_Pducer_Tran) - Gordon Gulch: Upper (2011-2017)" as the custom behavior with colons is no longer a part of Discover.
