### ISSUE TITLE
Inconsistency between isDerivedFrom and isCopiedFrom metadata usage and term definitions and help documentation

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#3296]
The term hsterms:isCopiedFrom is described in our term definitions (https://www.hydroshare.org/terms/) and help as: "Name or URL of the source from which a resource is copied.".  However when I use the copy button to make a copy of a resource, a relationship is established using hsterms:isDerivedFrom.

I suggest that, as part of addressing broader improvements to references #3261 that hsterms:isCopiedFrom be removed and in metadata the dcterms:source relationship be used.

To address the fact that dcterms:source definition "A related resource from which the described resource is derived" is not immediately accessible and requires looking up, I suggest on the UI using relationship type:
"The content of this resource is derived from" 
with longer help pages description
"The content of this resource is derived from: If your HydroShare resource was derived from another HydroShare resource or of content that is hosted or exists somewhere else, you can use this relationship type to refer to the location from which the content in your HydroShare resource was derived.  This relationship includes content copied in whole or in part, or used as input to the resource.  When a resource is created by copying another HydroShare resource, this relationship is automatically added."

**Comment by horsburgh** [comment]
This will be resolved as part of #3261, so I'm going to close this one.
