### ISSUE TITLE
Prefetch metadata for resource listing

### ISSUE THREAD

**Issue by pkdash** [hydroshare/hydroshare#3297]
Should be able to prefetch metadata for resource listing - my resources and profile page which should improve page loading time

**Comment by cuahsimarko** [comment]
@pkdash I came across something yesterday on memcached pages using the @vary_on_cookie and @cache_page decorators. Do you think this may be useful here?

**Comment by pkdash** [comment]
@cuahsimarko I am aware of the decorator '@cache_page' and it can help in page loading time in certain scenarios. However, it also can give an impression of a bug when the user doesn't see a resource in the resource list which he/she just created due to page caching. The new resource won't appear unit the cache expires.

**Comment by pkdash** [comment]
This has been deployed on www. Closing.
