### ISSUE TITLE
Box needed around text elements that are large to know where they end

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#33]
This is based on testing of alpha.hydroshare.org version 1.2.1.  The abstract for a resource can be quite long and on a resource landing page it is unclear where it ends and other resource metadata starts.  A box to separate text elements that can be large, such as is illustrated below would be good.
![p1](https://cloud.githubusercontent.com/assets/3456833/5604014/f8936d0a-935f-11e4-9f29-4e2a943a06d7.JPG)

**Comment by horsburgh** [comment]
My preference would be to have space be the delimiter rather than having lots of boxes or lines. But, agreed that things run together a bit right now.

**Comment by horsburgh** [comment]
This is addressed by the new edits that Mauriel is making to the Resource landing page.  The new layout will make things more clear.  The layout has changed significantly enough that I am going to close this issue.
