### ISSUE TITLE
For reference time series there are two download all buttons (that display different sizes)

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#330]
![capture](https://cloud.githubusercontent.com/assets/3456833/7288607/4ea5b234-e932-11e4-9e4b-a92affd08606.PNG)

**Comment by dtarb** [comment]
@jsadler2 is this still a problem?

**Comment by zhiyuli** [comment]
![image](https://cloud.githubusercontent.com/assets/10070599/9635189/6c0432f0-5152-11e5-8d54-d2bf1189a5c6.png)

no seeing this on alpha 1.5.3. closed
