### ISSUE TITLE
3 Listing Pages dont behave the same over Organization as First Author

### ISSUE THREAD

**Issue by cuahsimarko** [hydroshare/hydroshare#3316]
I just created a res on QAT with account czo_boulder/123. It has only one Author which is an Organization. 
http://qat.hydroshare.org:8000/resource/9cdc19783a574c289e87a4f416ef3785/
I shared this resource with CZO Boulder Group with View Permission.

Its Resource Landing Page shows Author correctly.
![image](https://user-images.githubusercontent.com/10070599/55963290-c469d800-5c2f-11e9-97b8-df9b4dc0e19d.png)

This resource shows up in 3 listings:
Listing 1: My Resource Listing shows Organisation as First Author, which is correct I think
![image](https://user-images.githubusercontent.com/10070599/55963332-db102f00-5c2f-11e9-93fe-8638b4c35471.png)

Listing 2: CZO Boulder's Group Resource Listing --- First Author is empty
![image](https://user-images.githubusercontent.com/10070599/55963363-e82d1e00-5c2f-11e9-94bb-0bbf4b8d88e7.png)
Listing 3: CZO Community Resource Listing -- First Author is empty
![image](https://user-images.githubusercontent.com/10070599/55963388-f7ac6700-5c2f-11e9-8777-2dbf947749d9.png)

**Comment by cuahsimarko** [comment]
"This is a systemic error. On ALL hydroshare resource listing pages, organization is not counted as author.
On ALL resource landing pages, an organization counts as an author.
This is very difficult to fix."

**Comment by Maurier** [comment]
@cuahsimarko I think this can be fixed in the frontend. We added a django filter to retrieve this field correctly. I believe we just forgot to extend it to the other pages where this is rendered.

You can use it like this:
`{{ res|resource_first_author }}`

**Comment by cuahsimarko** [comment]
@Maurier Thank you I will implement this

**Comment by cuahsimarko** [comment]
@Maurier ah I see what you're saying. The underlying query in question doesn't have that data that you're suggesting, it's deeper in the data. Alva, Drew and I are working in that deeper layer.

**Comment by cuahsimarko** [comment]
My current understanding is that this is a data issue and the fix is incumbent upon data managers. @zhiyuli if you agree can you please close this issue?
