### ISSUE TITLE
URL of RDF namespace in resourcemetadata.xml incorrect

### ISSUE THREAD

**Issue by horsburgh** [hydroshare/hydroshare#3319]
@dtarb noticed this as he was testing things related to relationship types for HydroShare resources. New resources that I am creating have the following in the XML namespace declarations at the top of their resourcemetadata.xml file:

http://www.w3.org/2001/01/rdf-schema#

This URL does not resolve. I believe the link should be:

http://www.w3.org/2000/01/rdf-schema#

Note sure what happened here or why this URL is incorrect.

I'm making this a separate issue because it needs to get fixed and it isn't related to the relationship type work and I don't want it to get lost.

**Comment by pkdash** [comment]
@horsburgh I assume we need to make this correction in code. If we make this change then we need to regenerate the bag before it gets downloaded for any existing resource.

**Comment by Castronova** [comment]
Resolved.
