### ISSUE TITLE
Res landing page crashed with UnicodeEncodeError after being made Public

### ISSUE THREAD

**Issue by zhiyuli** [hydroshare/hydroshare#3324]
We have a CZO resource created via hs_restclient. Everything seemed to be fine in Private mode. But once make it Public, the landing page crashed with a UnicodeEncodeError message.
As far as I can tell this resource has a special character í in Author names. But strange thing is I was able to copy this special char into other resources' authors, abstracts, keywords and made them public with no issue... 

http://qat.hydroshare.org:8000/resource/aaaa58457dd04597b8e29495bce55f9e/
![image](https://user-images.githubusercontent.com/10070599/56165200-9964e880-5f8f-11e9-9958-46ae1fe40148.png)

![image](https://user-images.githubusercontent.com/10070599/56165239-ac77b880-5f8f-11e9-9572-00804eb37d5b.png)

**Comment by sblack-usu** [comment]
This is the same issue, but in a different area than #3294 (user's name causes a failure in resource creation)

**Comment by sblack-usu** [comment]
Looks like it's happening here.  https://github.com/hydroshare/hydroshare/blob/develop/hs_core/search_indexes.py#L43

We should be careful to make sure we can still search by the user's name with that character.
