### ISSUE TITLE
Reference to tastypie still exists

### ISSUE THREAD

**Issue by pkdash** [hydroshare/hydroshare#333]
```hs_core/hydroshare/users.py``` still has reference to tastypie

**Comment by ironfroggy** [comment]
You'll need to be more specific. I have a fresh checkout of develop and all references in that module have been removed. Perhaps you're looking at master, where the purge branch has not been merged yet?

**Comment by pkdash** [comment]
I am referring to line#282 to 286 in ```hs_core/hydroshare/users.py```.  I am assuming those are tastypie related.

**Comment by ironfroggy** [comment]
The function in question doesn't seemed to be invoked from anywhere. Do you know if it will need to be used or if it can be removed?

**Comment by hyi** [comment]
Not sure whether this refers to the function get_user_info(user) which imports UserResource from hs_core.api, which does not exist in the code base. This get_user_info() is not used in the code base (only used by test script). @pkdash @selimnairb @ironfroggy Can this get_user_info() be removed safely or it is used implicitly somehow by REST API?

**Comment by pkdash** [comment]
@hyi Using PyCharm I found that function get_user_info() (defined in hs_core.hydroshare.users.py) is used only in unit tests. The unit tests where it is being used are marked to be skipped from unit test run. It should be safe to remove this function.

**Comment by hyi** [comment]
@pkdash That is what I found using PyCharm as well. I think if we remove this function, we should remove the corresponding unit test as well. Could you take care of removing this as well as the corresponding test as part of clean-up in conjunction with bringing in coverage test to our development and deployment workflow? Thanks!

**Comment by hyi** [comment]
The pull request was merged into develop and tested on dev; nothing is broken due to this removal, so closing.
