### ISSUE TITLE
Error! Metadata update failed - why does this happen?

### ISSUE THREAD

**Issue by solomonvimal** [hydroshare/hydroshare#334]
![abstract edit - error](https://cloud.githubusercontent.com/assets/2102394/7352681/9dd6d818-ecdb-11e4-9b9f-a0085fa19601.jpg)

**Comment by dtarb** [comment]
This is also I believe related to bagit restructuring #185

**Comment by dtarb** [comment]
Labeled for possible hotfix.  Functionality is improved with bagit restructuring, but editing of metadata on large resources still results in the error message being displayed even though the editing completes satisfactorily.

**Comment by hyi** [comment]
linking it to issue #446 currently being addressed.
