### ISSUE TITLE
Prevent Orphaned Metadata and File Objects at aborted res creation

### ISSUE THREAD

**Issue by cuahsimarko** [hydroshare/hydroshare#3346]
Navigating away from Resource page during creation should not result in orphaned metadata or file objects.

Currently, if you create a resource that's large or with many files and navigate away or clsoe the browser it results in unwanted artifacts.

- learn how to find the orphaned metadata in database
- learn how to find the iRODS objects
- prevent the behavior

------

If the user is creating a large resource or deleting many/large resources, then the processing time is substantial.  There is no notification to the user that this processing is underway, except for a small cursor change.  It seems like having no notification to the user risks users becoming confused, navigating away from the page, or pressing the create/delete button again.

[Video and Other Bug Report Files](https://github.com/hydroshare/hydroshare/files/2288934/002.zip)

**Comment by cuahsimarko** [comment]
Locking the UI work already done https://github.com/hydroshare/hydroshare/issues/2871

**Comment by dtarb** [comment]
@cuahsimarko given async work that may have addressed this, is there still a reproducible error that occurs.  If so, please document the error, if not, please close.

**Comment by cuahsimarko** [comment]
Between async work completed and a related ticket (https://github.com/hydroshare/hydroshare/issues/3549), this should be closed.
