### ISSUE TITLE
OS error - this screen appeared after a 300 mb zip file was uploaded (create resource)

### ISSUE THREAD

**Issue by solomonvimal** [hydroshare/hydroshare#335]
![upload error 300mb file oserror at hsapi_internalcreate-resourcedo](https://cloud.githubusercontent.com/assets/2102394/7352702/db18d334-ecdb-11e4-9b2b-190ddb6cc163.jpg)

**Comment by ironfroggy** [comment]
If you click the link there "Switch to copy-and-paste view" and copy and paste the information it gives you into this ticket, that would be very helpful.

**Comment by solomonvimal** [comment]
Though this error appears, the file seems to have been uploaded.
The contents of copy-and-paste view are pasted below: 

Environment:


Request Method: POST
Request URL: http://beta.hydroshare.org/hsapi/_internal/create-resource/do/

Django Version: 1.7.1
Python Version: 2.7.6
Installed Applications:
(u'mezzanine.boot',
 u'django.contrib.auth',
 u'django.contrib.contenttypes',
 u'django.contrib.redirects',
 u'django.contrib.sessions',
 u'django.contrib.sites',
 u'django.contrib.sitemaps',
 u'django.contrib.gis',
 u'inplaceeditform',
 u'django_nose',
 u'django_irods',
 u'theme',
 u'theme.blog_mods',
 u'mezzanine.conf',
 u'mezzanine.core',
 u'mezzanine.generic',
 u'mezzanine.blog',
 u'mezzanine.forms',
 u'mezzanine.pages',
 u'mezzanine.galleries',
 u'crispy_forms',
 u'mezzanine.accounts',
 u'mezzanine.mobile',
 u'autocomplete_light',
 u'jquery_ui',
 u'tastypie',
 u'ga_ows',
 u'ga_resources',
 u'dublincore',
 u'hs_core',
 u'hs_metrics',
 u'hs_geo_raster_resource',
 u'djcelery',
 u'ref_ts',
 u'widget_tweaks',
 u'debug_toolbar',
 u'django_extensions',
 u'filebrowser_safe',
 u'grappelli_safe',
 u'django.contrib.admin',
 u'django.contrib.staticfiles',
 u'django.contrib.comments')
Installed Middleware:
(u'django.contrib.sessions.middleware.SessionMiddleware',
 u'django.middleware.locale.LocaleMiddleware',
 u'django.contrib.auth.middleware.AuthenticationMiddleware',
 u'django.middleware.common.CommonMiddleware',
 u'django.middleware.csrf.CsrfViewMiddleware',
 u'django.contrib.messages.middleware.MessageMiddleware',
 u'mezzanine.core.request.CurrentRequestMiddleware',
 u'mezzanine.core.middleware.RedirectFallbackMiddleware',
 u'mezzanine.core.middleware.TemplateForDeviceMiddleware',
 u'mezzanine.core.middleware.TemplateForHostMiddleware',
 u'mezzanine.core.middleware.AdminLoginInterfaceSelectorMiddleware',
 u'mezzanine.core.middleware.SitePermissionMiddleware',
 u'mezzanine.pages.middleware.PageMiddleware',
 u'ga_resources.middleware.PagePermissionsViewableMiddleware',
 u'debug_toolbar.middleware.DebugToolbarMiddleware')


Traceback:
File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py" in get_response
  111.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py" in _wrapped_view
  22.                 return view_func(request, *args, **kwargs)
File "/home/docker/hydroshare/hs_core/views/__init__.py" in create_resource_new_workflow
  717.             content=res_title
File "/home/docker/hydroshare/hs_core/hydroshare/resource.py" in create_resource
  516.     hs_bagit.create_bag(resource)
File "/home/docker/hydroshare/hs_core/hydroshare/hs_bagit.py" in create_bag
  142.         'slug': resource.slug
File "/usr/local/lib/python2.7/dist-packages/bagit.py" in make_bag
  90.     old_dir = os.path.abspath(os.path.curdir)
File "/usr/lib/python2.7/posixpath.py" in abspath
  371.             cwd = os.getcwd()

Exception Type: OSError at /hsapi/_internal/create-resource/do/
Exception Value: [Errno 2] No such file or directory

**Comment by twhiteaker** [comment]
I just experienced this error for a 224 MB netCDF file upon creating a resource (beta.hydroshare, Firefox, Windows 7).  Here's my version of the traceback in case that helps.

Environment:


Request Method: POST
Request URL: http://beta.hydroshare.org/hsapi/_internal/create-resource/do/

Django Version: 1.7.1
Python Version: 2.7.6
Installed Applications:
(u'mezzanine.boot',
 u'django.contrib.auth',
 u'django.contrib.contenttypes',
 u'django.contrib.redirects',
 u'django.contrib.sessions',
 u'django.contrib.sites',
 u'django.contrib.sitemaps',
 u'django.contrib.gis',
 u'inplaceeditform',
 u'django_nose',
 u'django_irods',
 u'theme',
 u'theme.blog_mods',
 u'mezzanine.conf',
 u'mezzanine.core',
 u'mezzanine.generic',
 u'mezzanine.blog',
 u'mezzanine.forms',
 u'mezzanine.pages',
 u'mezzanine.galleries',
 u'crispy_forms',
 u'mezzanine.accounts',
 u'mezzanine.mobile',
 u'autocomplete_light',
 u'jquery_ui',
 u'tastypie',
 u'ga_ows',
 u'ga_resources',
 u'dublincore',
 u'hs_core',
 u'hs_metrics',
 u'hs_geo_raster_resource',
 u'djcelery',
 u'ref_ts',
 u'widget_tweaks',
 u'debug_toolbar',
 u'django_extensions',
 u'filebrowser_safe',
 u'grappelli_safe',
 u'django.contrib.admin',
 u'django.contrib.staticfiles',
 u'django.contrib.comments')
Installed Middleware:
(u'django.contrib.sessions.middleware.SessionMiddleware',
 u'django.middleware.locale.LocaleMiddleware',
 u'django.contrib.auth.middleware.AuthenticationMiddleware',
 u'django.middleware.common.CommonMiddleware',
 u'django.middleware.csrf.CsrfViewMiddleware',
 u'django.contrib.messages.middleware.MessageMiddleware',
 u'mezzanine.core.request.CurrentRequestMiddleware',
 u'mezzanine.core.middleware.RedirectFallbackMiddleware',
 u'mezzanine.core.middleware.TemplateForDeviceMiddleware',
 u'mezzanine.core.middleware.TemplateForHostMiddleware',
 u'mezzanine.core.middleware.AdminLoginInterfaceSelectorMiddleware',
 u'mezzanine.core.middleware.SitePermissionMiddleware',
 u'mezzanine.pages.middleware.PageMiddleware',
 u'ga_resources.middleware.PagePermissionsViewableMiddleware',
 u'debug_toolbar.middleware.DebugToolbarMiddleware')


Traceback:
File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py" in get_response
  111.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py" in _wrapped_view
  22.                 return view_func(request, *args, **kwargs)
File "/home/docker/hydroshare/hs_core/views/__init__.py" in create_resource_new_workflow
  717.             content=res_title
File "/home/docker/hydroshare/hs_core/hydroshare/resource.py" in create_resource
  516.     hs_bagit.create_bag(resource)
File "/home/docker/hydroshare/hs_core/hydroshare/hs_bagit.py" in create_bag
  142.         'slug': resource.slug
File "/usr/local/lib/python2.7/dist-packages/bagit.py" in make_bag
  90.     old_dir = os.path.abspath(os.path.curdir)
File "/usr/lib/python2.7/posixpath.py" in abspath
  371.             cwd = os.getcwd()

Exception Type: OSError at /hsapi/_internal/create-resource/do/
Exception Value: [Errno 2] No such file or directory

**Comment by dtarb** [comment]
I think that this is related to bagit restructuring and should be resolved once #185 is resolved.

**Comment by dtarb** [comment]
Appears to have been fixed with bagit restructuring.  Have successfully loaded files upward in size of 1 GB.
