### ISSUE TITLE
"Show All" button is off to the side and somewhat unintuitively labeled

### ISSUE THREAD

**Issue by hydrocheck** [hydroshare/hydroshare#3353]
To my knowledge, a "Reset Filters" label would be much more direct and intuitive for users.  Additionally, the button is not styled similarly to the filters below it, so it doesn't comfortably feel like it belongs with the filters.  Can we style this more closely to the filters below it?  For example, same width and have one "outline box" that groups together all the filters and the reset button?

[002.zip](https://github.com/hydroshare/hydroshare/files/3123961/002.zip)

**Comment by Lizabrazil** [comment]
closing this as it will be removed with first iteration clean up of discover
