### ISSUE TITLE
For group searches with no results, no message is displayed.

### ISSUE THREAD

**Issue by hydrocheck** [hydroshare/hydroshare#3362]
If the user searches for a group, but there are no results, they will not see a message displaying that information.  For consistency with other parts of the application, and to avoid any user confusion, a message should probably be added.

[011.zip](https://github.com/hydroshare/hydroshare/files/3123977/011.zip)

**Comment by Lizabrazil** [comment]
We couldn't find anything for "user input" 

Try entering a name, location, or different words. 

Facebook example: 
![image](https://user-images.githubusercontent.com/13852599/57311048-e7fe3200-70b8-11e9-9043-f05f0afffee9.png)

**Comment by hydrocheck** [comment]
Verified on beta.  Closing as resolved.
