### ISSUE TITLE
Display of multiple orgs on the profile page is unfriendly

### ISSUE THREAD

**Issue by hydrocheck** [hydroshare/hydroshare#3364]
The use of a semicolon delimited list for multiple organizations on the profile page is not very clean, user-friendly, or attractive.  The profile edit page looks nice in the display of multiple organizations - maybe a similar approach can be taken for the profile view.

[013.zip](https://github.com/hydroshare/hydroshare/files/3123981/013.zip)

**Comment by devincowan** [comment]
I gave this a go using the [tagsinput](https://github.com/xoxco/jQuery-Tags-Input) as hydrocheck suggested
![image](https://user-images.githubusercontent.com/17934193/202540867-336876a4-14b7-4ddd-bd9e-a03d9167982b.png)
My feeling is that it looks too much like these organizations are an input field (as seen in View mode).
So I'm going with a delimiter similar to what we have for our authors:
![image](https://user-images.githubusercontent.com/17934193/202541360-ebf43304-58b8-42de-9c3f-f87d440adcb1.png)
