### ISSUE TITLE
Inconsistent approach for help/supporting documentation opening strategy

### ISSUE THREAD

**Issue by hydrocheck** [hydroshare/hydroshare#3378]
Examples in same tab:
1. In the new home page, links in "Getting Started"
2. License reference links on resource pages

Examples in new tab:
1. BagIt "Learn More" button on resource pages
2. Discover page help documentation

[002.zip](https://github.com/hydroshare/hydroshare/files/3147544/002.zip)

**Comment by engineSound** [comment]
@Lizabrazil

**Comment by Castronova** [comment]
Discussion between @dtarb @Castronova @martinseul @eclark-cuahsi 

Any link that takes you out of www.hydroshare.org should open in a new tab.

**Comment by ClaraCogswell** [comment]
What is the status of implementing this in  the help pages? Currently most of the links redirect the current page, which is difficult if you still need to reference the page. 
Example: https://help.hydroshare.org/introduction-to-hydroshare/getting-started/upload-data-and-models-and-share-with-others/
But in a learning environment I agree opening in a new tab is better.

**Comment by dtarb** [comment]
@ClaraCogswell this is something you can do in Mezzanine.  You just need to use the target=top or target=new html in the link.  You can probably find an example that does open a new page to see exactly the syntax.
