### ISSUE TITLE
Implement iRODS file browser for ingestion of files from iRODS into HydroShare 

### ISSUE THREAD

**Issue by hyi** [hydroshare/hydroshare#338]
To support NFIE use case in particular, an iRODS file browser needs to be implemented to allow browsing and selecting files in another iRODS zone to create resources in HydroShare, which is needed for NFIE demo in CUAHSI Hydroinformatics conference this July.

**Comment by rayi113** [comment]
Per @dtarb , a NFIE summer camp starts June 1 that precedes the CUAHSI Hydroinformatics conference in July, so June is when it needs to be ready.

**Comment by dtarb** [comment]
I am unable to successfully log in to iRODS from playground.hydroshare.org as currently deployed.  In the following sign in I tried both 1247 and 8080 in the 3rd box.  The credentials I am using do work going in to iDROP  http://hydrotest.renci.org:8080/idrop-web2/.

![untitled](https://cloud.githubusercontent.com/assets/3456833/7671347/f7766106-fc88-11e4-875c-f95467d81a50.png)

Ultimately we need to get to where a user does not need to enter anything other than the username and password (and preferably not even that once hydroshare and iRODS accounts are aligned).  At a minimum if other stuff is going to be needed then the page should give guidance as to what they are.

**Comment by hyi** [comment]
Port 1247 should be used to connect to hydrotest.renci.org host. I will need to see a demo in order to figure out what is going on. If we want to allow users to browse into any iRODS host and zone (not necessarily the same host and zone used by HydroShare) to add files to create HydroShare resource, I am afraid we will have to ask users to enter host, zone, and port, although I can leave default values as placeholder texts in these input fields so users don't have to enter them if they want to use default values.

**Comment by dtarb** [comment]
I got it to work.  I was using incorrect credentials.  Sorry about that mistake.  It would be good to default the port number iRODS server and zone to something valid so that a user does not have to "know" and retype these every time.  If we want to have users change these we could remember the iRODS port, host and zone as properties of a user so that they always get back the last one they used as their default. Also since we now have upload from iRODS, we may want export to iRODS for the file or the whole bag as functions to round out the capability, e.g. if someone wants to work completely in iRODS and HydroShare without retrieving anything to the desktop.

**Comment by mjstealey** [comment]
If by defaulting information you mean populated but still changeable then I agree.
The provided fields allow you to connect to any arbitrary iRODS server that you know the credentials for, not just your own credentials on the particular iRODS deployment that HydroShare is connected to.

As an example, a user can use the iRODS file browser to reach into the iRODS server on iPlant, on beta, on dev, on any iRODS install that they happen to know credentials for and bring files in as a new resource to the HydroShare they are working from.

So, pre-populating the credentials with the "local" iRODS instance is fine so long as these are changeable by the user to reach into other installations if they so choose.

**Comment by dtarb** [comment]
I also found the following cool thing.  I was able to import a file from iPlant discovery environment, using the server and zone I looked up here https://pods.iplantcollaborative.org/wiki/display/DS/Using+iCommands#UsingiCommands-InitiatingtheiRODSconnectionandconfiguringthesettings%28One-timeonly%29.

**Comment by dtarb** [comment]
Yes I do mean changeable.

**Comment by hyi** [comment]
Functionality implemented and deployed on dev. Closing.
