### ISSUE TITLE
Without user logged in, the hydroshare page url should not redirect

### ISSUE THREAD

**Issue by engineSound** [hydroshare/hydroshare#3392]
In the latest dashboard implementation, when you type www.hydroshare.org, the browser is redirected to www.hydroshare.org/landingPage. @Lizabrazil said this is a negative experience. This can be changed without ambiguity. This issue can be fixed.

There is another one related to this that appears to be complex and requires extra effort. 

> When a user logs on to hydroshare with the dashboard feature, hydroshare redirects from www.hydroshare.org to www.hydroshare.org/home, the user's home as designed. In this scenario, hydroshare can not redirect to another url. A pointer can not point to north and south at the same time. The hydroshare icon at the top left has been pointing to url www.hydroshare.org. In order to avoid it routes back to www.hydroshare.org/home.  I have to assign a new URL www.hydroshare.org/landingPage so that the icon consistently loads up the original hydroshare home page.

**Comment by Lizabrazil** [comment]
I do not think the second problem with the icon url should be a show stopper for going into this release, mostly bc it does not impact the UX. Also, we can fix this at a later point without any impact to the user.

**Comment by Lizabrazil** [comment]
The first problem you describe needs to be fixed which you are already on top of

**Comment by cuahsimarko** [comment]
Unable to reproduce. When I navigate to www.hydroshare.org it does not append /landingpage was likely fixed and forgot to close issue

![image](https://user-images.githubusercontent.com/45397838/59706016-8fe54000-91cd-11e9-90f4-aea0f6a9dbdb.png)
