### ISSUE TITLE
Help Menu Nav and Hydroshare Main Nav Divergent

### ISSUE THREAD

**Issue by cuahsimarko** [hydroshare/hydroshare#3396]
Navs don't match

MAIN
![image](https://user-images.githubusercontent.com/45397838/57631178-fd69d500-756c-11e9-85f0-c9480bc82f57.png)

HELP
![image](https://user-images.githubusercontent.com/45397838/57631196-05c21000-756d-11e9-8bc1-42e7de9cfeed.png)

**Comment by Maurier** [comment]
The latest changes to the Help pages are not live yet, but they have been deployed for testing at https://pages.hydroshare.org/

Once the release is ready, these changes will be deployed to production.

**Comment by cbcunc** [comment]
What do you mean by "Main." hydroshare.org and help.hydroshare.org both match. Neither have the home or create links. Only the development server, pages.hydroshare.org, has the home land create links at present.

**Comment by cuahsimarko** [comment]
The navigation bars for help.hydroshare.org and hydroshare.org now match
