### ISSUE TITLE
Resizing in Chrome Hides Welcome Text

### ISSUE THREAD

**Issue by cuahsimarko** [hydroshare/hydroshare#3397]
go to hydroshare.org (dev) resize to approximately 1/3 or 1/4 screen:

<img width="889" alt="image" src="https://user-images.githubusercontent.com/45397838/57634084-9bac6980-7572-11e9-9461-b77e0dfb1611.png">

**Comment by dtarb** [comment]
I have experienced this problem in Firefox too on beta.hydroshare.org.  I think this should be fixed before 1.23 goes out as it is a regression.

**Comment by engineSound** [comment]
@dtarb We added two new navi-menu entries 1. home 2. create
When windows downsizes, the navibar pushes down but the body doesn't react to the change. Thus  the welcome content is gobbled.

**Comment by engineSound** [comment]
@dtarb I am working on a solution.

**Comment by engineSound** [comment]
The solution is here
https://stackoverflow.com/questions/18192082/bootstrap-3-navbar-collapse

**Comment by engineSound** [comment]
Testing solution today. If everything looks good, PR is expected later today.

**Comment by engineSound** [comment]
Fixed. PR #3403

**Comment by cuahsimarko** [comment]
This was fixed at some point
![image](https://user-images.githubusercontent.com/45397838/68156939-b1e02480-ff1a-11e9-844c-fcd9e7ceda1b.png)
