### ISSUE TITLE
Profile picture and sign out missing on 1.23 beta

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#3400]
![image](https://user-images.githubusercontent.com/3456833/57794211-6170d280-7700-11e9-8ca6-dff4e7251272.png)

**Comment by sblack-usu** [comment]
@phuongdm - I think this is probably just the deployment changes with media.  I thought these were reversed, could you check to make sure?

**Comment by phuongdm** [comment]
@sblack-usu 

Just checked on the console log:

https://new-hs-ci.hydroshare.org/view/02%20-%20Deployment/job/Beta%20deployment/job/beta-deploy-by-branch/67/console

![image](https://user-images.githubusercontent.com/24579275/57795299-9cc8cc80-7713-11e9-8451-058c41f114bc.png)

**Comment by sblack-usu** [comment]
This was a deployment problem due to a previous attempt to change the way we deploy static media files.  It has been worked out on beta, and I'm adding notes to the release checklist for 1.23 to make sure the static media files deploy correctly on the production deploy.
