### ISSUE TITLE
For model instance resource landing pages, display issues arise with model name dropdown

### ISSUE THREAD

**Issue by hydrocheck** [hydroshare/hydroshare#3408]
Issue arises on Firefox

[000.zip](https://github.com/hydroshare/hydroshare/files/3193443/000.zip)

**Comment by mahesh437** [comment]
raising in all browsers. It's due to the bootstrap used for this dropdown.

**Comment by dtarb** [comment]
Given that model instance resource type will be deprecated in favor of model instance in composite resource, lets close.
