### ISSUE TITLE
Time Series: Implement Metadate Edits in Underlying SQLite Database

### ISSUE THREAD

**Issue by horsburgh** [hydroshare/hydroshare#341]
Eventually we need to reflect any changes to the metadata made in the HydroShare metadata editing form into the underlying SQLite database for the time series.

**Comment by ironfroggy** [comment]
What SQLite database does this refer to?

**Comment by horsburgh** [comment]
The time series data are stored in a SQLite file that is the content of the resource.  Pabitra has programmed automated metadata extraction from an uploaded time series SQLite file, but then you can edit the metadata in HydroShare.  I don't think we have added code to reflect metadata changes made in the HydroShare web user interface back into the SQLite file.  

The time series resource uses ODM2 as a data model for storing the time series data in a SQLite file and ODM2 contains all of the metadata HydroShare needs to define a time series resource.

**Comment by pkdash** [comment]
@horsburgh I think this can be closed.

**Comment by horsburgh** [comment]
Deployed on www. Closing.
