### ISSUE TITLE
Restore display of basic resource information when attempting to access a private resource when not logged in

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#3429]
If when not logged in someone attempts to access a resource that is not public a "landing" page with resource title and owner should be shown, similar to the below (which is for logged in but without access)

![image](https://user-images.githubusercontent.com/3456833/59154078-80c0fe00-8a27-11e9-8594-1124ebba6e5c.png)

This used to be the case.  However present behavior has changed to instead redirect to the login page.  This appears to be a regression unintentionally introduced.

**Comment by eclark-cuahsi** [comment]
@Castronova I believe this falls under the Pages and General HS Components Category

**Comment by devincowan** [comment]
discussed today: The title on this issue is a bit misleading now. 

- We will continue to redirect non-logged-in users to the login page.
- Will restore redirect after login, back to the resource landing page
- Users who are logged in but don't have access to a private resource will be able to see the owner and title info
- Published resources will be publicly available

**Comment by dtarb** [comment]
@devincowan @martinseul There has been work to redirect users attempting to access private resources to login, under the assumption that when logged in they may have access to the resource.  I do not think we should do this as the assumption that the logged in user will have access is not always the case.  I think that instead we should change the messaging on the page display for private users

Cases
1. Private resource landing page accessed from anonymous (not logged in user).  Message at the top: This is a link to a private HydroShare resource.  To access it you need a HydroShare account and permission from its owner.  Log in (link to https://www.hydroshare.org/accounts/login/) or create account (link to https://www.hydroshare.org/sign-up/).
- Title
- Owner
- Any versioning links
 
![image](https://user-images.githubusercontent.com/3456833/157665824-f8a32738-37e6-4a8f-b2d9-49d9d1160d24.png)

This changes current behavior that automatically redirects a user to the login page.  I now feel we should avoid this redirection as a user may not know why suddenly they are being asked to log in when they received and clicked on a link purported to be a hydroshare resource.

2. Private resource landing page accessed from logged in user who does not have access
Leave page as it is  Example.
 
![image](https://user-images.githubusercontent.com/3456833/157665858-dab78f89-fcdd-44e6-a073-a9b1b93e12cf.png)

Behavior does not change if the owners of any of the resources involved are inactive, except, referring to #3077 for wording in the owner field indicating that the resource does not have an active owner.

Refer also to #4357.

**Comment by devincowan** [comment]
@dtarb this issue came up during private link sharing demo on today's HS call
Still in process, will be included in 1.55

**Comment by dtarb** [comment]
@devincowan thanks.  I recalled having discussed it and thought it may be in this release, but then did not see it and worried it have been in a previous release and regressed.  Good to know we are still on track.
