### ISSUE TITLE
Update hs_docker_base to release 1.9.10

### ISSUE THREAD

**Issue by cbcunc** [hydroshare/hydroshare#3436]
See hydroshare/hs_docker_base#30

**Comment by cbcunc** [comment]
Need to update mjstealey/irods-provider-postgres to 4.2.6 (for local development).

**Comment by dtarb** [comment]
@cbcunc is this still a concern.   If so, please prioritize at a developer call.  If not, please close.

**Comment by cbcunc** [comment]
Current release is 1.13.
