### ISSUE TITLE
HydroShare Certificates

### ISSUE THREAD

**Issue by mjstealey** [hydroshare/hydroshare#344]
get certificates for hydroshare.org and subdomains

**Comment by mjstealey** [comment]
Conversation thus far

Request:
```
From: Averill, Casey Martin 
Sent: Wednesday, April 29, 2015 11:37 AM
To: ITS Software
Subject: Certificate Request - hydroshare.org
 
I have attached a CSR for:
 
CN=hydroshare.org
SAN=hydroshare.org
SAN=www.hydroshare.org
```
Response:
```
From: ITS Software 
Sent: Wednesday, April 29, 2015 2:34 PM
To: Averill, Casey Martin
Subject: RE: Certificate Request - hydroshare.org
 
Casey,
 
The Organization Registrant for this domain is Utah State. Before I can create a certificate it needs to change to The University of North Carolina at Chapel Hill. Also the “tech email” is listed as dtarb@usu.edu, that should be changed to hostmaster@unc.edu.
 
http://whois.domaintools.com/hydroshare.org
```
Follow on:
```
I don’t have a work-around, so the only 2 options you have identified are correct:
 
1)      Have USU issue the cert, not UNC, or
2)      Transfer hydroshare.org to UNC so UNC can issue the cert
 
This is Dave’s call.  If he goes with option 1, you may need to provide instructions about how one goes about obtaining these certificates since he’s still travelling on the road for another ~week.
```
Additional information:

 - Universities don’t generally act as certificate authorities, except for in rare cases.  If USU has a partnership with a particular CA to provide low-cost certs, by all means go through the local IT department to purchase one.  Otherwise, you’ll have to get it from a trusted commercial authority like DigiCert.  Commercial authorities will verify the identity of the requesting institution via a series of e-mails and phone calls.  Commercial certs range in price from ~$100 per year for single-name certificates up to ~$1000 per year for wildcard certificates.

**Comment by ironfroggy** [comment]
StartSSL also offers certificates for free, verified through domain e-mail without human intervention. LetsEncrypt, the EFF/Mozilla initiative to make certificates easier to obtain, should also be launching soon. Both may be alternatives to the university red tape.

**Comment by dtarb** [comment]
Bought a wildcard certificate from GoDaddy for *.hydroshare.org.  Casey Averill reports he has installed and validated on load balancer.  Details of certificate are with @mjstealey @rayi113 and @dtarb.

**Comment by ironfroggy** [comment]
Are there follow up tickets for:

- Webserver configuration changes required?
- Hydroshare project/application changes required?

**Comment by mjstealey** [comment]
> Are there follow up tickets for:
> 
> Webserver configuration changes required?
> Hydroshare project/application changes required?

Not yet - will be soon though
