### ISSUE TITLE
Apps menu on help.hydroshare.org

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#3440]
The apps menu item on help.hydroshare.org links to https://apps.hydroshare.org/apps.  It should link to http://www.hydroshare.org/apps.  This is a regression that I noticed today. @cbcunc

**Comment by cbcunc** [comment]
Fixed.

**Comment by cbcunc** [comment]
Fixed on help.

**Comment by dtarb** [comment]
Thanks.  It looks right now.

**Comment by dtarb** [comment]
Re-opening.  This has happened again.  What can we do to prevent this happening?

**Comment by cbcunc** [comment]
Fixed in hydroshare/hs_pages#27
