### ISSUE TITLE
Modal dialog closes when dragging and releasing mouse button outside dialog

### ISSUE THREAD

**Issue by Maurier** [hydroshare/hydroshare#3449]
This is a bug inherited from the current version of bootstrap we use: https://github.com/twbs/bootstrap/issues/13816

When selecting text and the mouse drags outside of the dialog, the drag release will dismiss the dialog.

Possible solutions and workarounds:
- Disable modal dismiss when clicking on modal backdrop entirely. 
- Update bootstrap to a newer version.
- Figure out a way to intercept the event and stop propagation.

**Comment by horsburgh** [comment]
Just for background, I discovered this while testing the fix that @Maurier did for Author name entry. The modal form for Author name entry has several metadata elements and it kept disappearing on me as I was trying to edit those elements. I think this will be disturbing for some users who will not know why the modal window keeps disappearing. Luckily, when you click the button to open the modal window again, the information that has already been entered is still there.

**Comment by cuahsimarko** [comment]
This is a problem in the Profile page, too for the iRODS setup

**Comment by devincowan** [comment]
@horsburgh @Maurier seems like this has been resolved:

https://user-images.githubusercontent.com/17934193/155557132-69fbd3f1-85b4-4a7a-a5c8-a080e25d5244.mov
