### ISSUE TITLE
Date Range Error Message

### ISSUE THREAD

**Issue by cuahsimarko** [hydroshare/hydroshare#3451]
There is a bug with Start Date, when creating a new resource. To reproduce:

- Create new resource
- Fill out a Start Date a few days in the past
- Save

![image](https://user-images.githubusercontent.com/45397838/59931826-d62be080-9413-11e9-8667-e6e4ab453725.png)

**Comment by dtarb** [comment]
The problem is really that you need to specify both a start and end date and the end date needs to be not before the start date.  This bug is that if end date is blank (not filled in) a more descriptive error message needs to be written (e.g.  "Missing end date").  The same occurs if a user only enters an end date, in which case the message should be "Missing start date".

**Comment by cuahsimarko** [comment]
Various ways of handling this might be:

a) Start Date is entered, today's date automatically populates the End Date; user should know they can change that to an earlier date but this signifies a date is necessary (auto behavior may not be expected)
b) End Date is entered and Start Date of oldest resource automatically populates Start Date (probably bad idea)
c) End Date is entered and current date is entered automatically in Start Date (questionable)
d) Start Date or End Date Entered and a message is displayed inline, beneath the date fields informing the user with the message [phrasing goes here] that the other date needs to be provided; prevent submission until compliant

**Comment by cuahsimarko** [comment]
@dtarb ^^^

**Comment by dtarb** [comment]
I am not sure what ^^^ means.  I think that automatically filling in the dates is a bad idea.  This is consistent with comments following (a), (b) and (c) above.  Dates need to be deliberately chosen and consistent (start <= end).  Thus my recommendation is just to clarify the messaging to do this.

**Comment by cuahsimarko** [comment]
@dtarb I forgot to @mention your name and was unsure if editing my comment and adding the @mention would generate the necessary email notification, so I made an additional comment with a shorthand for "scroll up". Next time, I can be more formal and delete the old message, copy-paste into a net new comment, with the appropriate @mention. Noted, that's the direction I was leaning towards, providing the error message about the missing corresponding date, not allowing the user to Save until the error condition is cleared.

**Comment by cuahsimarko** [comment]
More specifically, I was thinking italicized text in red, beneath the date inputs with the message "Both a Start Date and End Date are required if providing temporal information"

**Comment by cuahsimarko** [comment]
Clearing both dates or entering both dates causes the error message to go away and the Save button to be enabled.

**Comment by dtarb** [comment]
@cuahsimarko no worries.  Yes - text below the dates would be great, and messaging more descriptive than just "failed to update" if a user does not get it right.
