### ISSUE TITLE
There are no password rules - accounts can be creates with password "a"

### ISSUE THREAD

**Issue by hydrocheck** [hydroshare/hydroshare#3460]
While I'm no security expert, minimum length and complexity seem to be a standard for account passwords.  A password of "123" or "a" should probably not be allowed.

[003.zip](https://github.com/hydroshare/hydroshare/files/3335596/003.zip)

**Comment by dtarb** [comment]
Find an out of the box component to indicate password strength.

**Comment by devincowan** [comment]
* min length: at least 8 char
* at least 1 number
* at least one caps

Also as cherry on the cake: when someone edits their profile, notify that we recommend that they update their password. 

We can't selectively recommend only to users with short passwords because we hash them...

**Comment by devincowan** [comment]
Noting that this will involve configuration in Keycloak

**Comment by devincowan** [comment]
@MSDrao worked with @sblack-usu on this and resolved
