### ISSUE TITLE
Add noindex directive to hydroshare dev servers

### ISSUE THREAD

**Issue by martinseul** [hydroshare/hydroshare#3478]
the Google data set search team  contacted us in regards to the Hydroshare representation in therr search. They noted that we should add a noindex directive to all dev servers to prevent them from being included in the indexing. We could potentially also remove the sitemap.xm from all but the prod server. Please see below:

"2. Showing results from dev servers (dev-hs-1.cuahsi.org and dev-hs-1.cuahsi.org - perhaps more). 
If those are indeed dev servers and you don't want their content to appear in search you should use a noindex directive (see more at https://support.google.com/webmasters/answer/93710?hl=en) or a robots.txt disallow (https://support.google.com/webmasters/answer/6062596?hl=en).

**Comment by martinseul** [comment]
I did try the google dataset search and when searching for Hydroshare the resources on the dev servers still appear. This did go out with 1.25. @alvacouch  is there something we need to do to enable this behaviour? Also looping @horsburgh and @sblack-usu in

**Comment by martinseul** [comment]
@hyi Hong looking at the recent work you did with schema.org would you be able to look at this issue again as it seem to still persist. When going to https://datasetsearch.research.google.com/ and entering dev-hs there are hundreds of results?

**Comment by hyi** [comment]
@martinseul I did have this in mind when implementing schema.org for HydroShare. Specifically, I checked the debug flag in HydroShare and only embed schema.org json-ld script when debug is false (i.e., only on production). However, I did not do anything about the sitemap, so those resources on our dev servers are still indexed by google through sitemap.

**Comment by martinseul** [comment]
@hyi Thanks that is helpful. I did try to open a https://dev-hs-7.cuahsi.org/sitemap.xml and https://dev-hs-3.cuahsi.org/sitemap.xml and the sitemaps are different. maybe we should disable the creation of a sitemaps for non prod systems altogether?

**Comment by hyi** [comment]
@martinseul Agreed that we should only create sitemap for production.

**Comment by horsburgh** [comment]
@hyi and @martinseul - what is the status of this issue? I did a test search on Google dataset search, and I am now finding resources from www.hydroshare.org, dev-hs-1.cuahsi.org, and nginx1.hydroshare.org.

![image](https://user-images.githubusercontent.com/3485902/79468708-80d14900-7fbc-11ea-89a0-feea0408c7d7.png)

**Comment by martinseul** [comment]
@hyi @sblack-usu @alvacouch  this is still an issue, i search for dev-hs-1 at the google dataset search and it still finds data: https://datasetsearch.research.google.com/search?query=dev-hs-1&docid=uxaB3T7rOBzkoXj6AAAAAA%3D%3D wha t can we do to prevent this?

**Comment by eclark-cuahsi** [comment]
@martinseul to review per discussion on 4/28.

**Comment by martinseul** [comment]
I doublechecked https://datasetsearch.research.google.com/ for entries referring to any dev-hs* machines that were there before and they seem to have all disappeared so I'm closing this ticket
