### ISSUE TITLE
Resource landing page slower when loading private pages 

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#3481]
Amazingly, the resource landing page loads more slowly (15s) when the resource is private than when it is public (10s). Common causes of this have been explored and ruled out. Forensic analysis is needed. The behavior is independent of the size of the resource.

**Comment by pkdash** [comment]
I was not able to reproduce this behavior. I got a resource page loaded in 7-8s in either public or private. Didn't notice any noticeable difference in page loading time with public vs private.

**Comment by alvacouch** [comment]
@pkdash What I am seeing is substantively different. It's a few more seconds for private resources at least on the beta machines. 

I've profiled various things already, and have ruled out template execution, template preparation. 

One clue is that the system seems to invoke SOLR indexing before rendering a page each time. It issues an `add` if the resource is public, and a `delete` if it is private. This is weird.

**Comment by alvacouch** [comment]
@sblack-usu @pkdash Crap! I see what is going on now. The new code for use tracking modifies the resource _system_ metadata independent of the science metadata. The SOLR indexer picks that up and treats it as a modification of the _science_ metadata. So it goes through the procedure it goes through for _science_ metadata.

**Comment by alvacouch** [comment]
@pkdash @sblack-usu This is not easy to fix. The appropriate fix is to put system metadata somewhere else that SOLR doesn't index. In fact, it doesn't index that data now, but it reacts to changes in that data by re-indexing everything. 

This requires moving the system metadata into another model, and migrating the data that has been collected there so far, which includes a running count of resource accesses.

**Comment by alvacouch** [comment]
@pkdash @sblack-usu Here is the offending code, in hs_core/models.py
```
    # for tracking number of times resource and its files have been downloaded
    download_count = models.PositiveIntegerField(default=0)
    # for tracking number of times resource has been viewed
    view_count = models.PositiveIntegerField(default=0)

    def update_view_count(self, request):
        self.view_count += 1
        self.save()

    def update_download_count(self):
        self.download_count += 1
        self.save()
```

**Comment by alvacouch** [comment]
@pkdash @sblack-usu Theory refuted. SOLR no longer called, 8 seconds load for public, 14 seconds load for private. Private is smaller.

**Comment by pkdash** [comment]
@alvacouch You means private resource takes longer to load?

**Comment by alvacouch** [comment]
@pkdash YES. An *empty* private resource takes longer to load than a fully populated public resource.

**Comment by sblack-usu** [comment]
Could it have something to do with whether a resource can be made public?  I can't imagine an empty field would make a 7 second difference in load time.

**Comment by alvacouch** [comment]
@sblack-usu I don't know what is going on. No current test has exposed the problem. All test results for long-running processes are negative. Back to the old drawing board.

**Comment by alvacouch** [comment]
(I even profiled the templates themselves. They are running quickly.)

**Comment by sblack-usu** [comment]
well, I just tried a private resource with the minimum needed to be made public and it still takes 15 seconds.  I'll try working through different fields to see if one of them makes the response faster.

**Comment by pkdash** [comment]
@alvacouch I am trying to reproduce this again on beta and I don't see noticeable difference. Is this happening only with a specific resource?

**Comment by sblack-usu** [comment]
@pkdash - create a new resource.

**Comment by alvacouch** [comment]
@pkdash @sblack-usu It also happens on older resources in my instance. The resources I am testing against are quite old.

**Comment by sblack-usu** [comment]
It's probably worth looking at the code that determines which web app tools can launch from a resource... It's horrendously slow.

**Comment by sblack-usu** [comment]
Yeah, I'm sure there are older resources this problem occurs with, but it's easy to reproduce the issue with a new resource.

**Comment by alvacouch** [comment]
(I am running on https://cuahsi-dev-1.hydroshare.org on the RENCI machines. I've modified a copy of develop to instrument templates. Rendering differentials are printed.)

**Comment by pkdash** [comment]
I tried with two new resources (on beta) - one public and the other private. Did not notice any difference.

**Comment by alvacouch** [comment]
What is overwhelmingly obvious to me -- from profiling all of the operations -- is that the wallclock times I am measuring for view rendering don't add up to the perceived time for rendering. Something else is going on.

**Comment by sblack-usu** [comment]
Did you pull up timings?  I just tried beta, and am seeing that a new private resource takes twice as long as a public one.

**Comment by pkdash** [comment]
This is the timing I am seeing for the public resource:
![image](https://user-images.githubusercontent.com/2523434/61246465-e7b78e00-a71c-11e9-9d26-0ea2d263ceb7.png)

This is for private:
![image](https://user-images.githubusercontent.com/2523434/61246578-277e7580-a71d-11e9-9dc5-bf8ada9f304d.png)

**Comment by alvacouch** [comment]
@sblack-usu @pkdash End of my day. I'll sleep on this and try again tomorrow.

**Comment by sblack-usu** [comment]
Could you add me as an owner of them?  I'd like to take a look.

**Comment by sblack-usu** [comment]
@pkdash - by chance are you using an admin account?  I'm noticing a significant speedup when using my admin account versus my regular account.  The same private resource that takes 15 seconds with my user takes only 3 seconds with my admin account.

I think we're getting close to figuring it out.

**Comment by pkdash** [comment]
I guess slower the network the difference is more noticeable. On my 1 gig ethernet I didn't get the difference. Tried on wireless, I got 10s for private resource and 15s for the public. Public seems to be slower.

**Comment by pkdash** [comment]
@sblack-usu I am using my admin account.

**Comment by sblack-usu** [comment]
I really doubt this has anything to do with wired vs wireless connection.

**Comment by sblack-usu** [comment]
wait... so you're getting long times with your admin account now too?

**Comment by pkdash** [comment]
Yes. I am seeing public resource slower to load than private. @alvacouch seems to see the opposite. I am getting the noticeable time difference only when using the wireless.

**Comment by sblack-usu** [comment]
that's not adding up... hmmm.

**Comment by sblack-usu** [comment]
I'm going to update something on beta real quick, so if you're still testing out timings, please do so on www.

**Comment by sblack-usu** [comment]
I'm pretty sure it's this query, still looking at it to make sure.

https://github.com/hydroshare/hydroshare/blame/develop/hs_access_control/models/user.py#L1091

**Comment by sblack-usu** [comment]
yeah, it's definitely that query.  We could speed this up a metric ton by checking the resource object instead of making a query on the db for a list of all viewable resources and then seeing if the resource is in that list.

**Comment by pkdash** [comment]
The reason I was getting more loading time with the public resource is that it had a readme file. I again tested with a new resource that has one file (not a readme file). Checked loading time making that resource public vs private. Didn't see any noticeable difference.

**Comment by pkdash** [comment]
> https://github.com/hydroshare/hydroshare/blame/develop/hs_access_control/models/user.py#L1091


Not sure how/why this query would be used for resource landing page.

**Comment by alvacouch** [comment]
@sblack-usu @pkdash Not using admin account. Connecting via CUAHSI internet: 100mb comcast for business.  

Depends upon what one does with the query. Tacking exists() onto it in the last step is much more efficient than checking for specifics. 

However, I checked the speed of that and didn't find it to be the problem.

**Comment by alvacouch** [comment]
@sblack-usu @pkdash I cleaned up that query yesterday in branch 3481-speed-up-resource-landing-page and it didn't help. See fix.

**Comment by sblack-usu** [comment]
Linked the wrong method, I meant to link the view_resources method not edit_resources, although edit_resources likely behaves similarly.  I'll do some more troubleshooting and see if I can get a functional proof this is where it's at.  

https://github.com/hydroshare/hydroshare/blame/develop/hs_access_control/models/user.py#L1019

I was led to this because my admin account loads the page more than 10 seconds faster than my regular user.  This method bypasses that view query if you're using an admin account.  https://github.com/hydroshare/hydroshare/blame/develop/hs_access_control/models/user.py#L1403

**Comment by sblack-usu** [comment]
I deployed a quick patch to https://dev-hs-1.cuahsi.org.  Here is a private resource opened with my regular user at 3.7 seconds
![image](https://user-images.githubusercontent.com/35820390/61307918-67406e00-a7ac-11e9-9cf4-65c816d4c94a.png)

And here is the same resource on beta with my regular user running at 15.4 seconds
![image](https://user-images.githubusercontent.com/35820390/61307871-5263da80-a7ac-11e9-86f5-80139bb0c52b.png)

And here is the change I made, I just updated the query to only look at the resource that's being viewed rather than all viewable resources.  There are likely other methods that could be updated through the system to get similar optimizations, but I haven't looked yet.  https://github.com/hydroshare/hydroshare/commit/362c79a9764adba474e6853f9b0819adcea0a019

**Comment by alvacouch** [comment]
@sblack-usu @pkdash 
I am not using an admin account.  I will speed this up (by inverting the query) and get back to you tomorrow. I do not consider this the root of the whole problem, though.

**Comment by alvacouch** [comment]
@sblack-usu @pkdash `UserAccess.edit_resources` has same issues.

**Comment by sblack-usu** [comment]
what do you consider the root of the problem then, @alvacouch?  And yes, I would expect edit_resources to have the same issue.

**Comment by pkdash** [comment]
@sblack-usu I think that query is the problem then. I assume you don't see any page load time difference between public vs private.

**Comment by alvacouch** [comment]
@sblack-usu @pkdash `view_resources` is called in more places than just can_change_resource, all over the page processors. If I plug your fix into all of them, it should fix things. Let me do a bit of software engineering on your fix so we aren't duplicating complex queries.

**Comment by hyi** [comment]
@alvacouch @pkdash @sblack-usu I think this ```authorize()``` function: https://github.com/hydroshare/hydroshare/blob/develop/hs_core/views/utils.py#L335 is the main base function that is called all over the place including page processor event handlers such as can_view(), can_change(), etc. Optimizing those queries being called in this authorize() function may have noticeable performance impact that would improve resource page load time.

**Comment by alvacouch** [comment]
See #3483 and please review. 

I realized that I didn't have to rewrite anything except the `x in queryset` calls. These were being interpreted slowly across the board, as `x in list(queryset)` rather than the more desirable `queryset.filter(id=x.id).exists()`. Formerly, the latter behavior was present. Now it isn't.

**Comment by alvacouch** [comment]
@sblack @pkdash Current load time is 3-4 seconds. Deployed on https://cuahsi-dev-1.hydroshare.org

**Comment by alvacouch** [comment]
@pkdash @sblack-usu One meta-comment. I have long experience with the postgres query optimizer and have learned to trust it. It is at least the equivalent of a commercial-strength query optimizer. I have no such trust in the MySQL query optimizer. So, if we were dumb enough to run Django on top of MySQL, this fix might not work.

**Comment by sblack-usu** [comment]
I don't think we'll ever move to a different database, but it's probably a good idea to note that we're relying on postgres optimizations that may not exist in other databases.  I think the docker-compose template for the postgis image seems like a good place?  Or maybe somewhere in access control.  

This is such a huge improvement, and it's pretty much site wide.

**Comment by alvacouch** [comment]
(People might forget that access control was first implemented in postgres and then ported to Django.)

**Comment by sblack-usu** [comment]
Is there a way to look at the resulting query that postgres runs just to make sure it is optimizing correctly?  The speedup certainly indicates that, but I'd feel better about it if I could see the resulting query to verify it.

**Comment by alvacouch** [comment]
@sblack-usu It's difficult. You can get to the sql for the django query. The query that is passed to postgres is raw SQL; Django does no optimization. There is a planner that one can invoke via the `EXPLAIN` SQL syntax in postgres that tells what postgres is doing. One of its first rules is that expressions like `key1=key2` go first.

**Comment by sblack-usu** [comment]
ok, I'm fine with just trusting your knowledge of postgres and the undeniable evidence of the timings.

**Comment by pkdash** [comment]
I think one get the SQL that Django sends to DB by doing:
print (queryset.query)

**Comment by alvacouch** [comment]
To my knowledge this was addressed in summer by1.24.3
