### ISSUE TITLE
Modal data persistence despite "Cancel"

### ISSUE THREAD

**Issue by hydrocheck** [hydroshare/hydroshare#3488]
Across a number of modals, user submission of "Cancel" will not clear the modal data (still populated when the modal is reopened)
1. The resource title in the resource creation modal
2. Group creation modal on the collaborate page - all the fields persist
3. Tag creation modal
4. Adding an author modal within resource page (edit mode)
5. Manage access modal within the resource page
Videos are attached for all five cases.

[000.zip](https://github.com/hydroshare/hydroshare/files/3409045/000.zip)

**Comment by cuahsimarko** [comment]
This is prevalent across all of HS

**Comment by martinseul** [comment]
Works as expected, no action needed for now.
