### ISSUE TITLE
NFIE iRODS Zone

### ISSUE THREAD

**Issue by mjstealey** [hydroshare/hydroshare#349]
Multi-(iRODS)users will be implemented directly in separate stand-alone NFIE iRODS Zone, and these resources will be accessed via a browser interface implemented as part of HydroShare NFIE Release 1.5.1
- NFIE iRODS student users who make their NFIE iRODS resources public will be accessible by HydroShare accounts, otherwise not

**Comment by dtarb** [comment]
Deployed with 1.5.1 and tested with a few files.
