### ISSUE TITLE
Import and sync ODM2 variable name vocabulary with HydroShare

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#3496]
For multiple reasons, we need access to the ODM2 variable name vocabulary inside HydroShare. For speed, this should be ingested into a Django model. Reasons include: 

1. CZO desires to use these terms in publication. 
2. Need to boost these terms during discovery.

**Comment by cuahsimarko** [comment]
Work completed in 5d9b4648e demo-frontent-community
