### ISSUE TITLE
Geographic raster resource metadata incomplete with errors

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#35]
The science metadata in resourcemetadata.xml should have coverage, band, variable and method information.  Also the identifier URL's are incorrect, missing a "/"
![p3](https://cloud.githubusercontent.com/assets/3456833/5604028/7976c412-9360-11e4-97ad-cd2b7cfc07d3.JPG)

**Comment by horsburgh** [comment]
Seems like the URLs should also have a path that indicates the type of "object" that is being referenced.  For example, resources could have "resources" in the URL, users could have "users", groups could have "groups", etc.  Mostly we need to have a little thought about URL patterns throughout the site.

**Comment by hyi** [comment]
This issue is fixed in my 82- feature branch as part of transition to the new resource creation workflow which incorporated new metadata serialization code by Pabitra.

**Comment by dtarb** [comment]
Tested.  Closing
