### ISSUE TITLE
Exclude pages from search engine indexing

### ISSUE THREAD

**Issue by cbcunc** [hydroshare/hydroshare#3505]
Exclude pages.hydroshare.org from search engine indexing.

**Comment by dtarb** [comment]
@cbcunc is this still an issue

**Comment by cbcunc** [comment]
Modified robots.txt on pages.hydroshare.org to the most restrictive possible: https://pages.hydroshare.org/robots.txt
```
User-agent: *
Disallow: /
```

**Comment by cbcunc** [comment]
Pages no longer appears in Google search: https://www.google.com/search?as_q=&as_epq=&as_oq=&as_eq=&as_nlo=&as_nhi=&lr=&cr=&as_qdr=all&as_sitesearch=pages.hydroshare.org&as_occt=any&safe=images&as_filetype=&tbs=
