### ISSUE TITLE
Open With not working working with folderless aggregations

### ISSUE THREAD

**Issue by kjlippold** [hydroshare/hydroshare#3514]
Right-clicking on an aggregation icon for the new folderless aggregations isn't pulling up apps to open them with.

New Aggregations:
<img width="807" alt="Screen Shot 2019-08-07 at 11 21 16 AM" src="https://user-images.githubusercontent.com/27028728/62643754-e8030d80-b905-11e9-9f46-9c1a468d292b.png">

Old Aggregations:
<img width="807" alt="Screen Shot 2019-08-07 at 11 23 44 AM" src="https://user-images.githubusercontent.com/27028728/62643762-eb969480-b905-11e9-89a0-b2142dca2719.png">

Open With functionality still works at the resource and file level.

**Comment by sblack-usu** [comment]
Thanks for finding this!  It should just be some updates on the frontend.  @Maurier - could you take a look?

**Comment by Maurier** [comment]
@sblack-usu - Yes, I'll have a look today.

**Comment by sblack-usu** [comment]
@kjlippold - a fix for this has been deployed to beta, mind taking a look and closing if it's resolved?

**Comment by kjlippold** [comment]
The first time I right-click on an aggregation and it loads the apps, it displays all the resource level apps like this:

<img width="829" alt="Screen Shot 2019-08-08 at 12 50 13 PM" src="https://user-images.githubusercontent.com/27028728/62729533-5e257400-b9db-11e9-985d-1dec2217e507.png">

Then when I try again it loads just the aggregation level apps correctly:

<img width="830" alt="Screen Shot 2019-08-08 at 12 50 27 PM" src="https://user-images.githubusercontent.com/27028728/62729567-6f6e8080-b9db-11e9-97b6-92297c84fad9.png">

It only seems to do this the first time after loading the page.

Nice job updating the menu to display the whole app name instead of cutting it off by the way.

**Comment by sblack-usu** [comment]
@kjlippold - that could just be your cache with old javascript files.  Try reloading the page again and see if it shows all the apps again the first time.

**Comment by kjlippold** [comment]
Alright, everything seems to be working now.
