### ISSUE TITLE
Open With button overlaps long resource titles

### ISSUE THREAD

**Issue by kjlippold** [hydroshare/hydroshare#3517]
The new open with button will overlap with some resource titles if they're too long.

<img width="1145" alt="Screen Shot 2019-08-09 at 10 31 04 AM" src="https://user-images.githubusercontent.com/27028728/62794302-fdf10980-ba90-11e9-97c1-a99260a05d53.png">

The old button would cause the title to wrap to the next line like this:

<img width="1154" alt="Screen Shot 2019-08-09 at 10 31 47 AM" src="https://user-images.githubusercontent.com/27028728/62794362-224ce600-ba91-11e9-9267-54688c3e125e.png">

**Comment by Maurier** [comment]
@sblack-usu - I pushed a fix for this to the branch containing the folderless aggregation work since we've also addressed a few other issues like this there.

**Comment by Maurier** [comment]
This has been addressed and included in the latest release. Thanks for reporting it. 

Closing
