### ISSUE TITLE
Implement Model Instance and Model Program Aggregation Types

### ISSUE THREAD

**Issue by pkdash** [hydroshare/hydroshare#3519]
The implementation of these two new aggregations types is based on the following design document:
https://docs.google.com/document/d/1DZgjLzhe40JkI9EA8OrTCDf1uFAnsSAQyqJ0rxkhBc8/edit

Jeff Sadler's presentation on these new aggregation types in HydroInformatics conference 2019:
https://docs.google.com/presentation/d/1RzrGKP4uFivE-PGzZEkzCXr0J6FzSa9e25EiCE14Pcs/edit#slide=id.p

**Comment by dtarb** [comment]
Closing.  Anything new related to model aggregations needs to be a new issue.
