### ISSUE TITLE
Large File Download messaging

### ISSUE THREAD

**Issue by sblack-usu** [hydroshare/hydroshare#3520]
Messaging on the frontend for downloading files larger than 1GB still shows up on the resource landing page.  I've identified two places in the code that it needs to be removed

 - https://github.com/hydroshare/hydroshare/blob/develop/theme/templates/resource-landing-page/modals.html#L1468
 - https://github.com/hydroshare/hydroshare/blob/develop/hs_core/templates/pages/genericresource.html#L698

**Comment by cuahsimarko** [comment]
Tested on beta
