### ISSUE TITLE
Cancel does not clear unsaved file extended metadata

### ISSUE THREAD

**Issue by hydrocheck** [hydroshare/hydroshare#3526]
When the user adds extended metadata, but then doesn't confirm the changes by pressing cancel, then the drafted metadata will still show in the boxes when the user returns to add metadata.

[002.zip](https://github.com/hydroshare/hydroshare/files/3504514/002.zip)

**Comment by hydrocheck** [comment]
Verified on beta.  Closing as resolved.

**Comment by hydrocheck** [comment]
Reopening as unresolved

**Comment by cuahsimarko** [comment]
![image](https://user-images.githubusercontent.com/45397838/106504282-b6d0b280-6494-11eb-8083-b7cdd69bbae6.png)

issue is not resolved. Also, dragging the cursor within the window causes it to close.
