### ISSUE TITLE
citation length increase

### ISSUE THREAD

**Issue by martinseul** [hydroshare/hydroshare#3529]
We received this request from Adam, @sblack-usu @alvacouch hope this should be an easy fix 

Hello – 
 
I am working on the following HydroShare entry:
Ward, A., S. Herzog, N. Schmadel, S. Wondzell (2019). Ward et al., JOURNAL TBD, 2019 - Tabular Data, HydroShare,http://www.hydroshare.org/resource/2f9643bb5d85436ba997a466ba8ed653
 
 
I am trying to cross-reference some of the underlying data from the HJ Andrews Experimental Forest catalog. As an example, the streamflow data we used to support this study are on their website, and their preferred citation is:
 
Johnson, S.; Rothacher, J. 2019. Stream discharge in gaged watersheds at the Andrews Experimental Forest, 1949 to present. Long-Term Ecological Research. Forest Science Data Bank, Corvallis, OR. [Database]. Available: http://andlter.forestry.oregonstate.edu/data/abstract.aspx?dbcode=HF004 (16 August 2019) DOI:http://dx.doi.org/10.6073/pasta/ce70a42e1f637cd430d7b0fb64faefb4.
 
However, this is too long for the current field. At present I have just trimmed this down a bit to better fit, but the length limitation seems potentially easy to allow for longer entries in this location of the database.
 
Cheers.
 
Adam
 
 
 
----------------------------------------------------------------------------
Adam S. Ward, PhD, PE
Associate Professor

**Comment by sblack-usu** [comment]
Looks like sources entries are limited to 300 characters.  It’s not much work to extend the character count but will require a migration

Relevant code:
https://github.com/hydroshare/hydroshare/blob/develop/hs_core/models.py#L1612
https://github.com/hydroshare/hydroshare/blob/develop/hs_core/forms.py#L519

**Comment by dtarb** [comment]
I would be happy if this could be addressed promptly.  I am generally in favor of using variable types that do not limit field lengths, because we have been impacted by choices of field lengths being too short a number of times before in different settings.

**Comment by martinseul** [comment]
@cuahsimarko is this still on your agenda?

**Comment by cuahsimarko** [comment]
Yes, but changes to Resource Landing Page are all undergoing scrutiny and prioritization.

**Comment by cuahsimarko** [comment]
12 of the 70 Resource Landing Page items are 'on my agenda' so I remember to discuss them with people and combine the work into sensible pull requests.

**Comment by sblack-usu** [comment]
It looks like it fell off the radar after Mark left.  This is not a big change to make, but we do need to know what the new maximum length of a source should be, if any.  I also don't know how high of a priority this is today.

**Comment by Maurier** [comment]
@sblack-usu The layout changes are implemented here: https://github.com/hydroshare/hydroshare/pull/4408
These are not breaking changes, so you can create another PR with the constraint removal.
