### ISSUE TITLE
Resources with many aggregations are slow, let's optimize

### ISSUE THREAD

**Issue by sblack-usu** [hydroshare/hydroshare#3530]
Basically anytime we lookup an aggregation within a resource we retrieve it by looping through all the aggregations in the resource and comparing the name.  This is fine when there are 1 or 2, but quickly slows down the resource landing page when a resource has several aggregations.  I'll document here the code that I've identified as places that are slowing the page down.  

### Resource
https://github.com/hydroshare/hydroshare/blob/develop/hs_composite_resource/page_processors.py#L19
https://github.com/hydroshare/hydroshare/blob/develop/hs_composite_resource/page_processors.py#L34

### File Browser
https://github.com/hydroshare/hydroshare/blob/develop/hs_core/views/resource_folder_hierarchy.py#L87
https://github.com/hydroshare/hydroshare/blob/develop/hs_core/views/resource_folder_hierarchy.py#L98

The File Browser pain points should probably be optimized within the following methods where we loop through all aggregations and files:
https://github.com/hydroshare/hydroshare/blob/develop/hs_composite_resource/models.py#L91
https://github.com/hydroshare/hydroshare/blob/develop/hs_composite_resource/models.py#L278
https://github.com/hydroshare/hydroshare/blob/develop/hs_composite_resource/models.py#L291

### Bonus Content
https://github.com/hydroshare/hydroshare/blob/develop/hs_core/models.py#L2365 (and methods below it)

I'm thinking the most straightforward fix would be to do the name matching in the db like so https://docs.djangoproject.com/en/1.11/topics/db/queries/#following-relationships-backward

**Comment by sblack-usu** [comment]
@pkdash - I think it'd be great to get you to leave some input on this.

**Comment by sblack-usu** [comment]
Looking more into how to do an aggregation lookup by name.  It's a bit more complicated than I initially thought, the aggregation name isn't a field, it's actually the primary file name.  And that primary file name is looked up dynamically each time we lookup an aggregation by name.
https://github.com/hydroshare/hydroshare/blob/develop/hs_file_types/models/base.py#L958

I think it makes sense to keep a reference to the primary file in the db for an aggregation.  I'm not sure if we can index the aggregation by resourcefile name, which is what we would need to do in order to look up an aggregation by name using an index.  More investigation is needed.

**Comment by sblack-usu** [comment]
We may also consider using `@cached_property`.  It won't be as much of a speed up as what I proposed earlier, but it is less work and considering how we currently loop over aggregations several times, we'll get similar gains after the first loop.

**Comment by pkdash** [comment]
@sblack-usu I will try to look into this tomorrow.

**Comment by pkdash** [comment]
@sblack-usu I think the following function can be optimized easily which should make the funcition https://github.com/hydroshare/hydroshare/blob/develop/hs_core/views/resource_folder_hierarchy.py#L29 more efficient - resource landing page load time improvement.

https://github.com/hydroshare/hydroshare/blob/develop/hs_composite_resource/models.py#L77

Will try to create a PR tonight.

**Comment by sblack-usu** [comment]
@pkdash - I pointed those methods out in the description.  How do you expect to optimize it easily?  I was thinking it'd be easy as well, but then I realized aggregation_name isn't a field, rather it's a property that loops over each file and determines the name from the file names.  That's why I'm thinking `@cached_property` is an easy solution... but it's not a large enough speedup because it's got to run through it one time for each call.

The only alternative I see is to add a field for the aggregation_name on the model, then make sure we update it at the correct times.  Do you have something else in mind?

**Comment by pkdash** [comment]
@sblack-usu When we are doing a lookup for an aggregation based on a folder path (get_folder_aggregation_object()), we don't need to loop over all the aggregations of the resource. Instead, I plan to do this:

This one liner for the get_folder_aggregation_object(dir_path):
   ```# query the DB for this```
```return self.filesetlogicalfile_set.filter(folder=dir_path).first()```

From the above change, this function ```can_set_folder_to_fileset()``` will benefit too.
