### ISSUE TITLE
Group invitation by person

### ISSUE THREAD

**Issue by martinseul** [hydroshare/hydroshare#3531]
Dave pointed out that if we invite user to a group it does not indicate who the person is that invites you,  Currently the user is invited by a generic message from the "Hydroshare Team"

Please see sample below:

_Dear David
You have been invited to join HydroShare user group (2019 CUAHSI Conference on Hydroinformatics ).
Click on the link below to join this group.
https://www.hydroshare.org/hsapi/_internal/group_membership/58m-f5a4b2dceda17e279885/2/1520/?next=/
The HydroShare Team_
 
To make it more personal this functionality should be changed to indicate who initiated the invite.

**Comment by cuahsimarko** [comment]
Additional suggested functionality from Dave for the invite email: When a user receives a invite the user also should be able to click a link to see the group landing page get information about the group that the invite refers to.
