### ISSUE TITLE
Improving file upload/unzipping

### ISSUE THREAD

**Issue by sblack-usu** [hydroshare/hydroshare#3533]
Unzipping or uploading numerous files with lots of processing can result in a bad database state if the thread gets interrupted.  Further, user feedback is currently minimal and should be improved.

### Requirements
- An error when processing a batch of files should not interrupt processing other files.  The error should be logged with appropriate user notification and continue to the other files.

**Comment by martinseul** [comment]
@hyi is this issue part of async and complete?

**Comment by hyi** [comment]
@martinseul Unzipping has been moved to async and deployed, so part of this issue is addressed by async, but file uploading is not part of async yet. Looping @alvacouch in since he is working on file upload and may have ideas to add async in as part of his big file upload work.

**Comment by ClaraCogswell** [comment]
@sblack-usu Is this still an issue?
