### ISSUE TITLE
Manage access not working for groups

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#3534]
I just tried to share a resource with a group.  I find that I am able to set group access but not remove or change it.

This is a regression suspected due to vue.js

![image](https://user-images.githubusercontent.com/3456833/63315526-ccfea900-c2c8-11e9-983a-a4a423038618.png)

**Comment by Maurier** [comment]
@dtarb - I am unable to reproduce this issue both locally and at https://www.hydroshare.org with one of my resources. Could you share a link to the resource you are trying this on so I can check if the problem is something specific to it?

**Comment by Maurier** [comment]
@dtarb Let me know if this is still an issue. I was not able to reproduce it on my end.

**Comment by dtarb** [comment]
Yes this is still an issue.  I just created the resource https://www.hydroshare.org/resource/d14462a14e884389b372bf5d0b0d5df4/.  Then I shared it with HydroShare Developers Group with View Access.  Initially the group did not appear in the who has access list, but a refresh of the page got it there with the exact problem above.  No remove X and unable to set Can edit.  I made you an owner.  I am using Firefox.  This is on www.hydroshare.org.

**Comment by Maurier** [comment]
I can see the issue now on this resource. I will investigate further.

**Comment by Maurier** [comment]
Found the error. This is quite an edge case. 

The issue occurs when the quota holder's Id coincides with the group's Id. In this particular case, @dtarb's user Id "2" coincides with the HydroShare Developers group Id "2" (hence why I could not reproduce it on my own). The conditional which handles the display of these controls needs to be refined a little to accommodate cases where these Ids can match.

![image](https://user-images.githubusercontent.com/2448568/66769797-3d621a80-ee73-11e9-9201-d5ad027c1a5b.png)

**Comment by dtarb** [comment]
Wow - that is subtle.

**Comment by dtarb** [comment]
@sblack-usu requested that I retest after 1.32 release.  I did.  It is still a problem.

There is a resource for which I am owner.  I shared it with HydroShare Developers as Can View.

I am still not able to remove or adjust the sharing with HydroShare Developers
![image](https://user-images.githubusercontent.com/3456833/80175060-c63fd880-85b1-11ea-8a0b-441496d494a3.png)

**Comment by sblack-usu** [comment]
I confirmed this issue still exists.  I'm leaving the changes in 1.32 as it does not introduce regressions.  We'll leave this issue open.

After looking at the code, we need to separate users from groups in the manage access interface.  It's both confusing to read and is the cause of this bug.

**Comment by devincowan** [comment]
@sblack-usu you're envisioning two separate sections within the modal, one listing groups with access and the other listing users?
