### ISSUE TITLE
Upload filename limited to 50 characters for hs_geo_raster_resource

### ISSUE THREAD

**Issue by selimnairb** [hydroshare/hydroshare#354]
Creation of new hs_geo_raster_resource resources fails when the uploaded filename is greater than 50 characters in length; this restriction is not in place for generic resources (not sure what the limit is there). We should probably allow filenames to be ~255 characters.  However:

    getconf NAME_MAX /

on a HydroShare container yields 242.  There may also be some iRods-imposed limit to consider.  Whatever the exact number, 50 is too small.

I'll assign @hyi for now, as she is the creator of this resource.

**Comment by hyi** [comment]
Increased max length for name field to 500 for both CellInformation and BandInformation metadata classes (populated automatically with the file name being uploaded) to be consistent with hs_core filename max length. Fix pushed to github and a pull request was created to be merged into release-candidate-1.5.0 branch.

**Comment by hyi** [comment]
tested on alpha.hydroshare.org and things work as expected now. Set it to ready for testing.

**Comment by selimnairb** [comment]
Tested and verified that this is now fixed.  Closing.
