### ISSUE TITLE
Inconsistency in direct title editing for CZO

### ISSUE THREAD

**Issue by hydrocheck** [hydroshare/hydroshare#3540]
Both the functionality and styling are confusing for direct title editing on CZO.  On the edit page, the title can be edited via right clicking, then typing.  The styling suggests "editable directly". The title window suggests a different story, with the generated title both functionally and stylistically uneditable.

[000.zip](https://github.com/hydroshare/hydroshare/files/3525293/000.zip)

**Comment by ndebuhr** [comment]
Moving here https://github.com/hydroshare/hydroshare/pull/3515
