### ISSUE TITLE
Inconsistent approach to field sizing for title assistant CZO

### ISSUE THREAD

**Issue by hydrocheck** [hydroshare/hydroshare#3541]
In Chrome, fields are shortened horizontally.  For example the bottom fields, which results in blank space to the right of the fields.  The year fields in that section are rather large, and close to the other fields in that row.

[001.zip](https://github.com/hydroshare/hydroshare/files/3525296/001.zip)

**Comment by ndebuhr** [comment]
Moving here https://github.com/hydroshare/hydroshare/pull/3515
