### ISSUE TITLE
Title assistant styling issues in Firefox

### ISSUE THREAD

**Issue by hydrocheck** [hydroshare/hydroshare#3542]
1. A horizontal scrollbar is visible despite being the full width of the window
2. The ">" characters on all four buttons are not centered
3. Width rows vary for the section at the bottom (the one with "Ongoing" extending beyond the others)

[002.zip](https://github.com/hydroshare/hydroshare/files/3525300/002.zip)

**Comment by ndebuhr** [comment]
Moving here https://github.com/hydroshare/hydroshare/pull/3515
