### ISSUE TITLE
multidimensional aggregations broken in 1.25 deploy

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#3544]
If I create a new resource and add a netcdf file I get the following.  The contents pane is not showing the aggregation.  However the aggregation appears to have been created. as the top of the landing page indicates multidimensional content and metadata is harvested.

![image](https://user-images.githubusercontent.com/3456833/63510791-c1fc7200-c49c-11e9-80d7-368314d8a2e5.png)

This may be related to #3543. 

This appears to be a serious regression with 1.25.

The file I used to test is in 
[SWE_time.zip](https://github.com/hydroshare/hydroshare/files/3529817/SWE_time.zip)

**Comment by pkdash** [comment]
@dtarb I was not able to reproduce this. When I created a new resource with the same nc file, I see the correct behavior.

![image](https://user-images.githubusercontent.com/2523434/63517673-68586f80-c4bd-11e9-9043-95a23887c82a.png)

**Comment by Maurier** [comment]
@pkdash @pkdash I was unable to reproduce it either.

**Comment by pkdash** [comment]
@Maurier Can this be a browser caching issue?

**Comment by Maurier** [comment]
@pkdash - Perhaps, or could be browser specific, I am not able to test on Safari right now, @dtarb if this is not a caching issue, could you check if there are any errors in the browser's console?

**Comment by pkdash** [comment]
@Maurier I tested on FireFox and Chrome. I don't think @dtarb is using Safari.

**Comment by dtarb** [comment]
Apologies - it was a caching issue.  Sorry.  It got me because I did not realize that a refresh would be needed for a new resource.  User error on my part.
