### ISSUE TITLE
Data storage as part of quota use reporting is incorrect on www.

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#3551]
For the account "demo" (name Dave Demo Tarboton) that I use for testing, the profile page reports 11 GB used.  However on "My Resources" there are just 5 resources that I own and when I look at the size of each and add them up, it is 3 GB.

On beta.hydroshare.org, the same 5 resources appear and the profile page reports 3 GB used (2.96 actually).

**Comment by phuongdm** [comment]
Fixed by resetQuota msi but actually I still don't know why it's incorrect! 

@hyi, any idea?

**Comment by hyi** [comment]
@dtarb Do you have some big files in your personal iRODS user scratch space associated with www, i.e., users.hydroshare.org host? Those big files in your personal iRODS user scratch space are counted toward your quota, and beta is using usersdev.hydroshare.org host, which are different. @phuongdm Although files in user scratch space on iRODS production server are copy-synced up to usersdev server used by beta, the user who own those sync'ed up files are the iRODS proxy user account that is used for copy-syncing up, not owned by real users, so I believe those copy-sync'ed up files are not counted toward user quota on beta, which is most likely the reason for quota discrepancy between www and beta. In any case, if @dtarb can verify how much disk space is taken in his irods user scratch space on production, that will definitely shed more light on this discrepancy/issue.

**Comment by phuongdm** [comment]
@hyi, when we copy-synced from backup storage to the beta all data was chowned to be owned by right user, so I think that's not the reason. The usage number in beta is correct because we did a fresh copy then run resetQuota after copying.

**Comment by dtarb** [comment]
This is my demo account that does not have an iRODS account as indicated by the fact that my profile does not list one.  However @phuongdm may have just done something, because the quota is now reported as being correct.
![image](https://user-images.githubusercontent.com/3456833/63611326-dc1b7a80-c598-11e9-9c9c-84b1f9f50f5c.png)

**Comment by hyi** [comment]
@dtarb looks like @phuongdm run quota reset to get quota refreshed on www, which corrected this discrepancy initially observed.

@phuongdm I don't remember specific details, but chown may not have worked correctly under some circumstances. I'll look into details when I have time and touch base with you offline on the issues I experienced on beta with my copied-over files on usersdev.

**Comment by dtarb** [comment]
@phuongdm this issue is resolved from my perspective.  If you feel it is resolved through what you did, please close it.  If there is more that needs to be done to resolve things getting out of sync and need refreshing, please do what needs to be done, either in response to this or a separate issue.
