### ISSUE TITLE
Metadata retrieval for Web App Resource type not possible through API

### ISSUE THREAD

**Issue by rfun** [hydroshare/hydroshare#3553]
Not really an issue but a feature request. 

I am trying to use a Web App Resource as a data store for a Tethys App Warehouse app. The Web App Resource fits almost perfectly for my data model as most of the fields (Icon, source url, versioning) are fields that I would otherwise have to setup using the custom metadata on a Composite Resource type. 

My concern is though when I fetch the metadata (both the core, and the sci) there is no entries for these additional fields such as Source URL, version, Icon URL, Issues URL. 

What I am looking for is, either include all of the "Resource Specific" metadata in the core, or provide a URL/Endpoint on the api for retrieval of these metadata items. Is this something that would be possible?

**Comment by martinseul** [comment]
@danames could you please take a look and assess the level of effort and priority level?

**Comment by danames** [comment]
This is actually quite a high priority. When we developed the web app resource, we created special metadata that needs to be discoverable through the API. 

It should be relatively straightforward to add this additional info to the return metadata entries. Specifically, we need the Source URL, version, Icon URL, and Issues URL.

I would estimate 16 hours total for someone to add this in and then test it. Another 16+ hours of dealing with getting a pull request through.

High priority.

**Comment by danames** [comment]
@martinseul check my notes here. I don't know who to put on this task immediately. Do you have someone there at CUAHSI who can do it?

**Comment by pkdash** [comment]
It seems there is already an endpoint that works for web app. Here is an example of the calling pattern:

https://www.hydroshare.org/hsapi/resource/ccac60d7309843658984881a5d785ef6/scimeta/elements/

The resource ID used in the above example is that of a web app.

**Comment by rfun** [comment]
That should do the trick. Thanks for the ino @pkdash

**Comment by rfun** [comment]
Sorry to revive this thread, the endpoint on the api doesn't provide the following fields: 

- Help Page URL
- Source Code URL
- Mailing List URL
- Issues URL

Here is a test resource : 

https://www.hydroshare.org/resource/9fba62f05bbb4cc8bf193f78a63f539f/

**Comment by danames** [comment]
This is critical for making the web app resource more functional via API.
**********************************************************************
Daniel P. Ames, Ph.D., P.E.
Professor, Civil & Environmental Engineering,Brigham Young University,
Provo, Utah, USA
President, International Environmental Modelling & Software Society
Editor-in-Chief, Environmental Modelling & Software
http://ceen.et.byu.edu/faculty/person/Daniel-P.-Ames
<http://ceen.et.byu.edu/content/dan-ames>
http://www.researchgate.net/profile/Daniel_Ames
http://scholar.google.com/citations?user=S0GUCeUAAAAJ

**********************************************************************

**Comment by rfun** [comment]
Any updates?

**Comment by danames** [comment]
Hi all, we're quite anxious to get this fixed. Who can is or could be working on it???

**Comment by dtarb** [comment]
@sblack-usu you are the API product owner.  Can you please investigate this and if you think it is reasonable work implementation into your work schedule.  I see @pkdash did respond with a way to do this.  This information may be available in one of the xml metadata files that can be downloaded so I am not saying that what @danames is requesting has to be done, but that we do need to holistically evaluate the need and the degree to which it can be met with existing functionality, and whether new functionality that meets the need better can be efficiently implemented.

**Comment by danames** [comment]
Exactly. We don't have to implement this exactly as requested, but it would
be great to get some discussion and holistic evaluation of the
issue. @sblack-usu please let us know if you need any more information
about this.
**********************************************************************
Daniel P. Ames, Ph.D., P.E.
Professor, Civil & Environmental Engineering,Brigham Young University,
Provo, Utah, USA
President, International Environmental Modelling & Software Society
Editor-in-Chief, Environmental Modelling & Software
http://ceen.et.byu.edu/faculty/person/Daniel-P.-Ames
<http://ceen.et.byu.edu/content/dan-ames>
http://www.researchgate.net/profile/Daniel_Ames
http://scholar.google.com/citations?user=S0GUCeUAAAAJ

**********************************************************************

**Comment by sblack-usu** [comment]
> 
> 
> Sorry to revive this thread, the endpoint on the api doesn't provide the following fields:
> 
>     * Help Page URL
> 
>     * Source Code URL
> 
>     * Mailing List URL
> 
>     * Issues URL
> 
> 
> Here is a test resource :
> 
> https://www.hydroshare.org/resource/9fba62f05bbb4cc8bf193f78a63f539f/

None of these URLs are resource specific.  We could add endpoints for this information, but I'm not convinced it's useful or necessary as this information is accessible and most likely will never change.  Could you describe the use case for these URLs?  I assume it's just for some help page, and if so I think it's reasonable to just "hardcode".

**Comment by danames** [comment]
Hey Scott the use case is that we are using the app resource to develop a
more comprehensive app catalog and need to be able to retrieve all of the
metadata for web app resources to facilitate search, display, etc. Since
this is the only additional resource type along with composite that we are
planning to have around long term, it should reasonable to provide this
data in the api for web app resources. Rohit can elaborate if further
info is needed. Thanks, Dan
**********************************************************************
Daniel P. Ames, Ph.D., P.E.
Professor, Civil & Environmental Engineering,Brigham Young University,
Provo, Utah, USA
President, International Environmental Modelling & Software Society
Editor-in-Chief, Environmental Modelling & Software
http://ceen.et.byu.edu/faculty/person/Daniel-P.-Ames
<http://ceen.et.byu.edu/content/dan-ames>
http://www.researchgate.net/profile/Daniel_Ames
http://scholar.google.com/citations?user=S0GUCeUAAAAJ

**********************************************************************

**Comment by sblack-usu** [comment]
ok, I misunderstood.  These are urls specific to web app resources, I was thinking it was for the hydroshare project.  Looking into it now.

**Comment by danames** [comment]
Thanks
**********************************************************************
Daniel P. Ames, Ph.D., P.E.
Professor, Civil & Environmental Engineering,Brigham Young University,
Provo, Utah, USA
President, International Environmental Modelling & Software Society
Editor-in-Chief, Environmental Modelling & Software
http://ceen.et.byu.edu/faculty/person/Daniel-P.-Ames
<http://ceen.et.byu.edu/content/dan-ames>
http://www.researchgate.net/profile/Daniel_Ames
http://scholar.google.com/citations?user=S0GUCeUAAAAJ

**********************************************************************

**Comment by sblack-usu** [comment]
This is still on my radar, I'm just trying to wrap up some other things.  I do think this should be added to the rest api and I'll get that change as soon as I get a chance.

**Comment by sblack-usu** [comment]
@rfun - I have a PR ready for this.  It should be ready for the next release.  I'm requesting you to review it just to make sure I've met your needs.  i'll also ask a core developer to review.

**Comment by rfun** [comment]
@sblack-usu  : Not being very familiar with HydroShare code, this seems like it should do the job. All the fields look like they are there. Thanks :)
