### ISSUE TITLE
Actions on Collection Resources are VERY slow

### ISSUE THREAD

**Issue by Castronova** [hydroshare/hydroshare#3554]
After the last release I noticed that action on Collection resource types are very slow. They are slow enough that it looks like HS is broken. This performance issue can be seen by:

1. Create a Collection resource
2. Add funding agency metadata.
3. Notice that this action takes 1-2 minutes to complete.
4. This slowdown is also experienced if you click on the pencil icon to enter edit mode.

Some actions seem to work as normal, e.g. abstract and keywords.

**Comment by cuahsimarko** [comment]
I'm just trying to follow along here. Is this partially or entirely addressed by https://github.com/hydroshare/hydroshare/pull/3547 or not?

**Comment by dtarb** [comment]
A collection is not an aggregations so I would presume that this issue is not related to #3547 that relates to aggregations.

**Comment by pkdash** [comment]
Some quick tests indicate that all the slowness is due to the generation of long list of resources (these are the resources which can be part of the collection) at the backend. Some metadata editing seems to reload the page which gives the impression that metadata editing takes forever.

**Comment by pkdash** [comment]
It seems the backend query for generating the list of resources can be substantially optimized. Should be a quick fix without any change to the current workflow.  However, the workflow probably needs to change at some point.
