### ISSUE TITLE
automatically accept owner privileges from group members

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#3555]
@dtarb @martinseul  A feature came up in my discussions of CZO capabilities that might have general utility for most users. 

Currently we make users "accept" ownership of a resource from others. Ostensibly, this is because **ownership is a responsibility.** Thus, assignment of ownership is a two-step process: request and either accept or deny. 

There is a case in which this is overly tedious, when the owner of a group wants to own all resources that relate to group work. This is particularly important when that owner is also the manager of a group of transient graduate students, e.g., as the PI of a grant. Then, the owner persists while the workers change. 

This proposal is to allow a user to set a flag in the user profile that automatically approves assignment of ownership in the following conditions: 

1. The user is the owner of a group `g`. 
2. The initiator and current owner of the resource `r` is a member of that group `g`. 
3. The user flag mentioned above is `True`. Working name is `auto_approve_owner_from_groups`

In this case, the ownership transfer would automatically be approved without queueing it in the request system. It would not be necessary to share the resource with the group first. Since multiple ownership is supported, assignment of ownership is sufficient and transfer of ownership is not required.  

This would greatly ease workflows for the CZOs, because it is their intent that site managers should own all resources for the site. This would make that a one-step process. It strikes me that most Ph.D. advisors would like the exact same feature for their research groups. 

This is really simple to implement: a day's work.

**Comment by alvacouch** [comment]
@dtarb This is curious because I specifically remember that transfer/accept was specified for ownership.

**Comment by dtarb** [comment]
We did discuss this in our early specifications, and I think it was going to be a later implementation phase.  The first implementation did not do this because we did not have messaging, and no one has complained about the current implementation that does not have transfer/accept.

**Comment by martinseul** [comment]
@dtarb @alvacouch are we OK to close this?

**Comment by dtarb** [comment]
I am happy with current functionality so am happy to close this.

**Comment by martinseul** [comment]
closing as agreed above
