### ISSUE TITLE
Identify and fix resources broken prior to hotfix 1.25.1

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#3557]
The creation of resources that no longer permitted file uploading reported in #3543 after deletion of an aggregation was fixed in hotfix 1.25.1.  However the hotfix did not correct existing problems.  There are still corrupt resources, such as https://www.hydroshare.org/resource/c71e41fe816548889ee039e870098eb4/ in HydroShare that need to be identified and fixed.

**Comment by dtarb** [comment]
Hotfix 1.25.2 was supposed to fix this issue.  However in testing this there are remnant aggregation files in the downloaded bag.  

The resource I am testing on is https://www.hydroshare.org/resource/9dd9057fd4fa4507a8f6dd355ad4eba1/.

Contents are
![image](https://user-images.githubusercontent.com/3456833/64025728-9f043a80-cafa-11e9-906f-fdca24624f8b.png)

Bag contents are
![image](https://user-images.githubusercontent.com/3456833/64025768-adeaed00-cafa-11e9-895f-1fab77ce5c12.png)

The SWE_time_* files should not be there.  They are remnants from an aggregation that was deleted.

**Comment by sblack-usu** [comment]
I think we probably just need to regenerate the bag.  I'll run a management command that will recreate the bag for those 7 resources.

**Comment by sblack-usu** [comment]
now that I'm thinking about it more, I don't think bag regeneration is enough.  I don't think hydroshare has any knowledge of those xml files now that the hanging logical files have been removed.

We could write a query that compares metadata files with what we have in the db.

**Comment by hyi** [comment]
@sblack-usu This is exactly what I am thinking of. Now that the hanging logical files have already been removed, it is not easy to find these hanging xml files any more. Writing a query that compares metadata files against aggregation data in the db sound like a way to go.

**Comment by sblack-usu** [comment]
After this command is written, I think we should consider adding checks/cleanup like this to the bag creation logic.

**Comment by sblack-usu** [comment]
I think a management command that deletes all aggregation metadata files and forces the aggregations to regenerate might be the most useful way to write this command.  Then it could be more easily added to the bag creation logic.

**Comment by hyi** [comment]
@sblack-usu Agreed that sounds like the most straightforward way to fix this issue. Just need to test on beta thoroughly to make sure aggregation metadata file and resourcemap file will be regenerated after the original ones are deleted. For example, a flag might need to be set to force regeneration of aggregation metadata and resourcemap files.

**Comment by sblack-usu** [comment]
We have a management command call `check_irods_files` that has an option `--clean_irods`.  It compares files on irods with what we have in the db.  It's out of date because it doesn't account for aggregation metadata, but we should be able to leverage it.  Maybe we run this `--clean_irods` option and then write a function to regenerate all metadata for aggregations?

**Comment by sblack-usu** [comment]
aha! we also have a management command `regenerate_xml_files_composite_resource` which just regenerates aggregation metadata files.  Running these two management command on the 7 resources will fix the problem.

**Comment by hyi** [comment]
@sblack-usu Great! Sounds like a plan to go forward with.

**Comment by sblack-usu** [comment]
alright, those commands have been written and the bags have been regenerated.  Go ahead and take a look again.  I verified the issue @dtarb outlined is fixed.
![image](https://user-images.githubusercontent.com/35820390/64037163-31640880-cb12-11e9-8180-b0c4faf532b2.png)
