### ISSUE TITLE
Title element hidden by header

### ISSUE THREAD

**Issue by Castronova** [hydroshare/hydroshare#3558]
The resource title is partially covered by the HS header when window width is between 770px and 990px. 

![image](https://user-images.githubusercontent.com/4822372/63869572-575ca200-c986-11e9-887b-501d24a19086.png)

Steps to reproduce:
1. launch google Chrome
2. open a hydroshare resource landing page
3. resize the width of the browser window

**Comment by sblack-usu** [comment]
@Castronova - Could you verify and close this issue?
