### ISSUE TITLE
Cleanup is_federated blocks

### ISSUE THREAD

**Issue by sblack-usu** [hydroshare/hydroshare#3562]
the django app in hydroshare shouldn't have if/else blocks checking federation.  This makes the code hard to maintain and is error prone.

@pkdash kindly pointed out an alternative approach here https://github.com/hydroshare/hydroshare/pull/3559/files/bc43f7e57631465dd9ff8d073152d8060f224be5#r319084487

Here is an example block that should be updated.
https://github.com/hydroshare/hydroshare/pull/3559/files/bc43f7e57631465dd9ff8d073152d8060f224be5#r319191845

**Comment by martinseul** [comment]
Hong I think to recall that you worked on a similar issue before, would you please take a look.

**Comment by hyi** [comment]
@sblack-usu I agree that the django app shouldn't have if/else blocks checking federation, but I cannot really see the relevant info in the links you gave above on an alternative approach pointed out by @pkdash and the example block that should be updated. Are the links above correct?

**Comment by sblack-usu** [comment]
@hyi, Here is a link to the comment @pkdash made, https://github.com/hydroshare/hydroshare/pull/3559/files/bc43f7e57631465dd9ff8d073152d8060f224be5#r319069643

**Comment by hyi** [comment]
@sblack-usu Got it. Thanks
