### ISSUE TITLE
Timeseries aggregation view mode issue

### ISSUE THREAD

**Issue by pkdash** [hydroshare/hydroshare#3569]
In timseries aggregation view mode, selecting a timeseries from the dropdown list doesn't show the  associated metadata.

![image](https://user-images.githubusercontent.com/2523434/64493260-fec1ba80-d24b-11e9-80d3-95374e65166d.png)

**Comment by Maurier** [comment]
This fix has been deployed to https://www.hydroshare.org. I have confirmed it's working as expected. Closing.
