### ISSUE TITLE
My Resources Filtering: Search by Filenames

### ISSUE THREAD

**Issue by ironfroggy** [hydroshare/hydroshare#357]

**Comment by dtarb** [comment]
This is not NFIE Required.  See #376 for my suggestions on required search fields.  I am open to Filename being added to the list as a "nice to have" feature.

**Comment by dtarb** [comment]
Filtering has been revamped in the My Resources page.  Assigning to @horsburgh to decide if there is still an enhancement here to consider (which should be filed as a separate issue) or whether this can just be closed.

**Comment by horsburgh** [comment]
@dtarb - I don't think this is something we should support.  The filenames are not exposed on the My Resources page. We should enable filter on the metadata items one can actually see on the page. Objections?

**Comment by dtarb** [comment]
Lets close.
