### ISSUE TITLE
Update folder listing to not choose replica

### ISSUE THREAD

**Issue by sblack-usu** [hydroshare/hydroshare#3573]
irods list command:
https://github.com/hydroshare/hydroshare/blob/develop/django_irods/storage.py#L283

choosing the replica:
https://github.com/hydroshare/hydroshare/blob/develop/django_irods/storage.py#L300

**Comment by hyi** [comment]
@sblack-usu Verified the updated code is part of 1.26 release. Can you close this issue now?
