### ISSUE TITLE
Unable to modify resource sharabile status

### ISSUE THREAD

**Issue by aaraney** [hydroshare/hydroshare#3585]
I am unable to modify the public 'sharable' status of resources I have created as non-sharable resources. Please find [this](https://hydroshare.org/resource/e7da635f4f6d404a9845fdf96b136550/) resource as an example.  Specifically, my resources do have this symbol ![non-shareable](https://hydroshare.org/static/img/non-shareable.png) rather than ![sharable](https://hydroshare.org/static/img/shareable.png) symbol. Also, I have attempted to modify resources marked as sharable to non-sharable without any success. To determine if this were a potential browser problem, I have attempted to change the resources with both Safari 12.1 and Firefox Quantum 69.0. If you can direct me to the general direction of the code where such an option could be updated, I am happy to open a pull request.

**Comment by martinseul** [comment]
Jeff, I'm trying to take a first cut at assign tickets to the proper Product owner as we discussed during the All Hands. Please review and see if it's appropriate.
