### ISSUE TITLE
bag it creation fails for resource with hidden chararacter in title

### ISSUE THREAD

**Issue by martinseul** [hydroshare/hydroshare#3586]
@Castronova discover that for this resource https://www.hydroshare.org/resource/1fedd80cd20245409a0ea02cc2a1ecf0/ downloading as a  bagit file fails . Downloading a simple zip works. I did some resource and the title does contain hidden characters:
Achieving Reproducible Computational Hydrologic Models by Integrating Scientific Cyberinfrastructures
Testing on beta by removing the characters does indeed solve the problem and the BagIt file creates correctly. 
we should consider to
1. add additional checks to sanitize the title and other textfields 
2. develop a management script to remove illegal characters

**Comment by prof-couch** [comment]
@martinseul This is in a group of related situations in which the code responds to ASCII but receives unicode. Similarly, Linux handles unicode in filenames, but our UI does not.

**Comment by martinseul** [comment]
@sblack-usu can we close this as it should have been addressed with the Python 3 upgrade
