### ISSUE TITLE
Submitting comma separated keywords will only render the first one

### ISSUE THREAD

**Issue by Maurier** [hydroshare/hydroshare#3592]
Subsequent ones only show up upon page reload. I think this was unintentionally introduced as part of the work done recently in https://github.com/hydroshare/hydroshare/pull/3515

This is specific to release 1.26 and not reproducible on www

1. 
![image](https://user-images.githubusercontent.com/2448568/65817020-b1d46280-e1bf-11e9-90e0-6fdf0de50b17.png)

2. 
![image](https://user-images.githubusercontent.com/2448568/65817022-bdc02480-e1bf-11e9-9cb5-33fec0f68a39.png)

3. (Upon reload)
![image](https://user-images.githubusercontent.com/2448568/65817027-cc0e4080-e1bf-11e9-855d-df0ade1ee784.png)

**Comment by cuahsimarko** [comment]
I just noticed this bug is present in beta and not prod

![image](https://user-images.githubusercontent.com/45397838/65890238-8ba1f480-e370-11e9-801d-7dec7b899705.png)

**Comment by Maurier** [comment]
Fix has been merged to develop
