### ISSUE TITLE
No logical files in created Composite Resources: cannot be discovered

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#3600]
@dtarb @cuahsimarko @martinseul **There are 2,083 resources in my dump -- from a couple weeks ago -- that are of type Composite Resource and contain no logical files at all.** Since the discovery interface looks to logical files to determine content type, these are indexed as generic data. 

The new composite resources of CZO data share this problem. This is a failing of the REST API but also has other potential causes.

1. inconsistency between parts of a logical file for shapefiles. 
2. manual user deletion of logical files deemed not relevant. 
3. loading parts of a composite file (e.g., a shapefile resource) via single REST actions. This is known not to create the needed logical files.

**Comment by alvacouch** [comment]
Update: I did some investigating. *All* of these resources consist of csv, txt, and zip files.

**Comment by cuahsimarko** [comment]
Very interesting.

**Comment by dtarb** [comment]
It is not a requirement for a composite resource to have a logical file.  In our resource evolution plan composite resources will just become "Resources".  Files get added to resources.  If the files are recognized as a type that can be built into an aggregation, then the auto aggregate functionality will act on them and make an aggregation that results in "logical files".  However if they are not added to an aggregation, they just sit there as generic files, or just "files".  The term logical file is a hang over from the early implementation where we did not do OAI-ORE aggregations the way we are doing now.  Also the expectation for there to be logical files may have been created from the first implementation which did make a "logical file" for each file.

Mentioning @pkdash who implemented most of this, @horsburgh who designed most of this and @sblack-usu who is working on the check resources functionality for composite resources.

**Comment by alvacouch** [comment]
The immediate problem is that -- in the way we are migrating the CZO resources -- they are not auto-aggregating. They are being migrated via the REST API and -- despite having the appropriate content for auto-aggregation -- are being classified as generic data. Thus, in the discovery interface, they are coming up as generic data, because discovery depends upon auto-aggregation.

**Comment by alvacouch** [comment]
@sblack-usu @pkdash Can someone point us to how to input resources via the REST API in such a way that uploaded files are automatically associated with logical files when appropriate?

**Comment by sblack-usu** [comment]
@alvacouch, to add a file to a resource POST to /hsapi/resource/{id}/files/.  I can work out some examples with you if you'd like.  I'm not sure what type of files these are, but if it's an aggregation that requires multiple files and you upload them one at a time, they won't be recognized as aggregations.  That's what I think is probably happening here.  If you're uploading aggregations together, then  make sure the files are valid aggregations and aren't failing due to missing certain metadata.

**Comment by sblack-usu** [comment]
@alvacouch - If aggregations aren't being recognized because they're being uploaded individually, you can also tell the aggregation code to run a specific file through the rest api.  If you give me more details about the files you're trying to aggregate, I can help out.

**Comment by alvacouch** [comment]
@dtarb @martinseul @sblack-usu  #3605 does not fully address the discovered problem (pun intended). 

I've written management commands to check the health of discovery. I am seeing a lot more discoverable resources in Django than I am seeing in discover. 

Some property of these must be making SOLR reject records. More frustrating, SOLR is not noting any rejections. Whatever it is doing, it does not view as an error. 

At the present time, **1/2 of all public or discoverable resources are disappearing from discovery.** This number comes from the correction I made in #3605, which exposes many more resources than before by making their content types nonempty.

**Comment by alvacouch** [comment]
@dtarb @martinseul @sblack-usu I have been able to restore function on my test host by indexing missing resources individually. 

* The reindex command uses `SearchIndex.update()` rather than `SearchIndex.update_object(object)` like my code. 
* **This casts suspicion that the problem is a REST request overflow error during bulk updating.** 
* What this means is that haystack is automatically creating update requests for SOLR that exceed the maximum number of characters for REST. 
* Why this does not scream error messages in SOLR, I may never know. 
* The underlying problem is that the base command `./hsctl managepy rebuild_index` is getting an amount of index data it never planned for, because our SOLR instances index a lot of fields. 
* When my code updates resource indexes individually, there is no problem. 
* This is not a runtime problem. At runtime, resources are always updated individually. I have determined that this always works. **It is a build problem.**

**Comment by alvacouch** [comment]
The problem seems to be how the user is using the system, not how data is indexed. The files don't appear in aggregations because there is no reason to. The proposed request for "search by file suffix" will discover these. 
I'll leave this open until that is implemented.

**Comment by cuahsimarko** [comment]
@martinseul or @alvacouch can you confirm the open action item here is to enable search for resources in Discover by file extension? If yes, let's deprecate this ticket https://github.com/hydroshare/hydroshare/issues/3600 and move the design conversation to https://github.com/hydroshare/hydroshare/issues/4073

**Comment by martinseul** [comment]
agreed closing here and retain in #4073
