### ISSUE TITLE
Map query for discover doesn't filter out replaced resources

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#3606]
In checking the logs for discovery, I noticed that the query for map data doesn't correctly require replaced=false, like the query for the list page.

**Comment by cuahsimarko** [comment]
Is this stale/part of old Discover?

**Comment by cuahsimarko** [comment]
@alvacouch can you add more detail and clarify if this can be covered by work on Index-related code and/or if I need to make changes to new Discover front/back/middle tiers?

**Comment by alvacouch** [comment]
This was a bug in old discover and is obsolete.
