### ISSUE TITLE
It's possible to add an author many times to a resource

### ISSUE THREAD

**Issue by hydrocheck** [hydroshare/hydroshare#3608]
Repeated additions of the same author is not prevented or warned against.

[000.zip](https://github.com/hydroshare/hydroshare/files/3692694/000.zip)

**Comment by cuahsimarko** [comment]
Will be prioritized by stakeholders/PI

**Comment by cuahsimarko** [comment]
Related
https://github.com/hydroshare/hydroshare/issues/3700
https://github.com/hydroshare/hydroshare/issues/3610

**Comment by Castronova** [comment]
![image](https://user-images.githubusercontent.com/4822372/108757740-3db6ff00-7518-11eb-84c0-3fc5dafc1537.png)

**Comment by Castronova** [comment]
After discussing this ticket during our review, we decided that focus of this ticket should be narrowed down to address only the same user id appearing multiple times. Other edge cases should not be addressed, e.g. multiple non-hs users with the same name, multiple hs user accounts with the name name, etc.

Suggested fix:
- check author and owner ids are unique
