### ISSUE TITLE
Resource type is no longer a GUI filter in the Discover page

### ISSUE THREAD

**Issue by hydrocheck** [hydroshare/hydroshare#3613]
Resource type is a filter option that must be specified via the search field.  I believe there was a filter for this before.  A high possibility this is deliberate, but reporting in case this is a regression.

[005.zip](https://github.com/hydroshare/hydroshare/files/3692701/005.zip)

**Comment by alvacouch** [comment]
It was changed to `Content type`, which better describes modern resources and allows one resource to be categorized in several ways. We should change the documentation.

**Comment by cuahsimarko** [comment]
@alvacouch @ndebuhr please close this issue if it's resolved

**Comment by martinseul** [comment]
completed
