### ISSUE TITLE
naming issues for organizations

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#3623]
The naming canonicalization still does not properly deal with the fact that owners can be organizations. Thus, these get capitalized like common names and are rendered as "last, first" rather than "first last".

**Comment by sblack-usu** [comment]
@alvacouch - could you verify and close this issue?

**Comment by alvacouch** [comment]
This has been fixed. It's in essence too good, because it also mis-classifies all users who type their names in ALL CAPS as organizations, but that is a different story.
