### ISSUE TITLE
Improve Groups page loading layout

### ISSUE THREAD

**Issue by Maurier** [hydroshare/hydroshare#3629]
The Collaborate page could be improved with CSS grid or CSS flex to fix the layout while it's loading. The errors in the layout can be seen during loading time and when images have not been cached or are too slow to render. 

The current implementation uses a script to structure the grid, but while the page is loading the layout looks off and the height of the cards is too short. Now that this functionality is included as part of CSS3 we can use that instead of a script and produce the correct layout at all times.

https://css-tricks.com/snippets/css/complete-guide-grid/

![image](https://user-images.githubusercontent.com/2448568/67298554-aadffd80-f4a8-11e9-9b08-8830f1d040eb.png)

**Comment by cuahsimarko** [comment]
Note this is now called Groups, since Groups and Communities now exist beneath Collaborate
