### ISSUE TITLE
Add word "zipped" to Download All button

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#363]
The following image shows different sizes for downloading a single file versus all files.  This is a potential source of user confusion as all  files should be bigger than just one file.  Add the word zipped to the interface to avoid potential user confusion.

![untitled](https://cloud.githubusercontent.com/assets/3456833/7550292/11c6721a-f619-11e4-8673-9609ce1a22d9.png)

**Comment by dtarb** [comment]
@mauriel133 could you please do this.  It should be relatively simple interface labeling.  See als #369

**Comment by mauriel133** [comment]
Yes, I'll have this done tomorrow.

**Comment by dtarb** [comment]
Implemented in 1.5.1
