### ISSUE TITLE
Create iRODS account in user zone is broken

### ISSUE THREAD

**Issue by hyi** [hydroshare/hydroshare#3630]
Even though a success notification message is displayed, no corresponding iRODS user is successfully created in iRODS user zone. This is a regression.

**Comment by dtarb** [comment]
Do we need an iRODS user zone.  We use this for large file upload.  Cyverse I believe gives free file storage in iRODS.  Perhaps we should partner with them and encourage our users with large file upload needs to create Cyverse accounts.  What are the tangible benefits of us maintaining our own user zone.

**Comment by hyi** [comment]
@dtarb I have fixed this issue by correcting the typo in the file path in the settings file. The benefit of having an iRODS user zone for large file upload is that this user zone is federated with data zone, so a direct copy of the large files from users scratch space can happen rather than copying large files from a different zone such as Cyverse to a temporary space in HydroShare Django server, then copy the large file over from Django server to hydroshare data zone. This extra hop will make a big difference for gigabyte large files. I am planning to improve the code logic to fix the flag in Django DB out-of-sync issue today or tomorrow to get this to work in a more robust way.

**Comment by dtarb** [comment]
OK good.

**Comment by hyi** [comment]
I am closing this since the enhancement in addition to the fix to local_settings.py has been merged into develop.

**Comment by dtarb** [comment]
@hyi can you please make checking that this works an item on the release that goes out with this.

**Comment by hyi** [comment]
@dtarb There is no code change to the fix to this issue, only a couple of typos in the backup local_settings.py for production were discovered and fixed. As a result, there was no formal release for this issue, but instead after local_settings.py typos were fixed, @sblack-usu just did a server restart on the backup worker, then switched the active worker I believe. Some further enhancement code got merged to develop today which has not been released yet mainly dealing with better error notification on user profile page if irods user account failed to create, as well as minimizing (if not removing completely) the potential for Django flag to be out of sync with iRODS user status. I was lazy to use the same issue to capture the enhancement work. Since this issue actually has already been fixed in the current release, I just closed it. If you would prefer to leave this PR open until you test it out in the next release, please feel free to reopen it.

**Comment by sblack-usu** [comment]
I verified irods user creation/deletion with the release before closing the release checklist for 1.27.2
