### ISSUE TITLE
Suspicion that discovery isn't being dynamically updated

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#3635]
@sblack-usu @dtarb @martinseul I "discovered" when re-running `solr_update` on cuahsi-dev-1 that new resources that were created during testing didn't get indexed. These were marked as "not in SOLR". Thus I suspect that dynamic updates in SOLR may be broken. It would help to run `solr_update` on beta and check whether that "discovers" unindexed resources. It should not.

**Comment by sblack-usu** [comment]
I tried running `solr_update` in beta, but am running into issues with the metadata attribute of at least some resources.  You can see an example run here https://new-hs-ci.hydroshare.org/view/02%20-%20Deployment/job/Beta%20deployment/job/beta-hsctl-command/11/console

I ran a quick test for my sanity
```
>>> res.metadata is None
True
>>> hasattr(res, 'metadata')
True
```

This makes sense, the attribute will always exist, but the returned attribute (content_object) could be set to None, which seems to be happening frequently.  Not sure why this popped up recently, no changes stand out to me and am still investigating.  Any ideas?
