### ISSUE TITLE
iRODS browser to add files into resources appears to be broken

### ISSUE THREAD

**Issue by hyi** [hydroshare/hydroshare#3638]
This is a regression issue.

**Comment by hyi** [comment]
@Maurier I identified the root of this issue - event handler callbacks in iRODS browser JavaScript code don't get triggered any more with your new GUI change on resource landing page, i.e., change irods login, logout, file-browsing buttons to corresponding ```li``` list items. For example, this click callback handler https://github.com/hydroshare/hydroshare/blob/develop/irods_browser_app/static/js/irods.js#L1 is not invoked when this btn-select-irods-file ```li``` item is clicked from the dropdown list: https://github.com/hydroshare/hydroshare/blob/develop/hs_core/templates/pages/genericresource.html#L480. I tried different things but this event callback handler has never been triggered. Really need your pointers to help connecting the click of ```li``` list items with corresponding iRODS event handlers. I think I should still be able to use click event, but not sure why click event handler is not triggered. @martinseul needs this feature to work for CZO data ingestion, so it'd be great if you could provide helpful pointers on this so I can create a PR soon to fix this regression issue. Thanks

**Comment by hyi** [comment]
@Maurier I just saw your slack response after I sent this comment. Sorry about that. Let me try it to see if it works. Will let you know. Thanks

**Comment by hyi** [comment]
@Maurier You suggestion on slack works. I'll create a PR and ask you to review it. Thanks!

**Comment by Maurier** [comment]
Good to know!

**Comment by hyi** [comment]
@martinseul @sblack-usu I have created a PR against develop to fix this issue which @Maurier has approved, which should be included in the next release. The fix to this problem only involves changes in two JavaScript files, so if you think we should get the fix in before the release, i.e., have a hotfix release for this, it can be done easily without requiring a server restart. We only need to pull the JavaScript code changes and do a collectstatic call. Let me know if you prefer a hotfix for this. If so, I'll create another PR against master branch.

**Comment by hyi** [comment]
@martinseul @sblack-usu I have just merged the PR to develop. If beta is where CZO work is being tested on, perhaps @sblack-usu can just update beta with latest develop and do a collectstatic call. Then @martinseul can test on beta to verify whether this issue has been fixed there?

**Comment by hyi** [comment]
Verified on beta. Closing for now.
