### ISSUE TITLE
In manage access panel change full permission label to owners

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#364]
Change the label below to "Owners with full permissions to do anything on this resource"
![untitled](https://cloud.githubusercontent.com/assets/3456833/7550765/a06a4af2-f62b-11e4-9dc2-765877b79241.png)

**Comment by horsburgh** [comment]
This appears to be done on dev.hydroshare.org. It will may be superseded by the new access control panel when it has been implemented.
