### ISSUE TITLE
Zipped download of single file aggregation missing aggregation xml files

### ISSUE THREAD

**Issue by pkdash** [hydroshare/hydroshare#3647]
How to reproduce this issue:
Upload a text file to a composite resource. Right click on the uploaded text file and select the option 'Add metadata'.  This should create a "Single file content type' (aggregation). Again right click on the same text file and select option 'Download zipped'. If you look inside the downloaded zip file you will not see the expected two aggregation xml files.

**Comment by pkdash** [comment]
@sblack-usu Can I assign this to you since you probably more familiar with the download code?

**Comment by sblack-usu** [comment]
Yeah, I can take a look at this.  Looks like the frontend isn't signalling the file as an aggregation when requesting the download
`https://www.hydroshare.org/django_irods/download/925946fda6da4a9486e554e27d67e765/data/contents/hsctl-sans.txt/?url_download=False&zipped=True&aggregation=False`

**Comment by eclark-cuahsi** [comment]
@sblack-usu is additional action need on this issue or has it been resolved?

**Comment by sblack-usu** [comment]
I tested this on production and "download zipped" of a single file aggregation includes the metadata XML files.  This issue got fixed somewhere along the way without this issue being closed.
