### ISSUE TITLE
Inconsistencies in join page error message

### ISSUE THREAD

**Issue by hydrocheck** [hydroshare/hydroshare#3649]
Please see the attached image.  A couple tweaks:
1) Consistently use either "user name" or "username"
2) Consistently start messages with a capital letter or not.  I.e. "Username is not valid..."

[001.zip](https://github.com/hydroshare/hydroshare/files/3802541/001.zip)

**Comment by devincowan** [comment]
![Image](https://github.com/user-attachments/assets/dfd1d71b-63df-4485-8178-3eb4cb7dc164)
resolved with Cuahsi SSO
