### ISSUE TITLE
Comment Reply Emails Unnecessary for Your Own Replies

### ISSUE THREAD

**Issue by ironfroggy** [hydroshare/hydroshare#365]
If you leave a reply to a comment, the original comment's creator gets an e-mail. If you reply to your own comment, that e-mail should be skipped.

Related: Recommend a "Backburner" label to organize tickets like this that you want to remember but should be explicitly understood as "not right now"

**Comment by pkdash** [comment]
@hyi Is this still an issue?

**Comment by hyi** [comment]
@pkdash Yes, I have not worked on this. I cleared the milestone and it is already on the backburner.

**Comment by dtarb** [comment]
Closing this issue as it is backburner and its merits could be debated.  The commentor receiving an email is not a bad thing as confirmation that their comment/reply has actually been received.
