### ISSUE TITLE
International utf-8 characters can't be used in usernames

### ISSUE THREAD

**Issue by hydrocheck** [hydroshare/hydroshare#3655]
Letters such as ü and ł can't be used in usernames.

[007.zip](https://github.com/hydroshare/hydroshare/files/3802548/007.zip)

**Comment by cuahsimarko** [comment]
![image](https://user-images.githubusercontent.com/45397838/101546377-b0332c80-3976-11eb-9680-be9dae3acd9f.png)

I am able to add umlaut u to my name in prod
