### ISSUE TITLE
Can't add file type metadata to a Jupyter Notebook file

### ISSUE THREAD

**Issue by gantian127** [hydroshare/hydroshare#3671]
I tried to add file type metadata to a Jupyter Notebook file in a composite resource. I clicked on "Add metadata" button and have the following error. Does HydroShare support to add file type metadata to a Jupyter Notebook file? Thanks!

Resource link: https://www.hydroshare.org/resource/299c7d218c4e4594bfff573139d3d9b2/
![image](https://user-images.githubusercontent.com/5016511/68516611-b91c7080-0241-11ea-8949-fb6b773331cc.png)

**Comment by dtarb** [comment]
This appears to be UX/front end related.  In testing I found
- I can right click or click on the Add metadata button on a .ipynb file (or text file and presumably other files)
- I get the message that content type creation was successful.  However the interface still shows "no metadata exists for this file".  If I click Add metadata a second time, I get the error Tian reported.
- If I reload the page with the browser I am able to see and work with the content aggregation metadata.

This may be a regression introduced with efforts to make page loading more efficient (i.e. limit reloads).  @Maurier please check on this.  If this appears to be back end, @pkdash please check.

**Comment by Maurier** [comment]
Undertood, I'll have a look.

**Comment by pkdash** [comment]
@dtarb and @Maurier It is a UI issue. For certain type of aggregation creation, the file browsing area is not getting refreshed. Once the browsing area gets refreshed I am assuming the button to add metadata will not appear or get disabled.

**Comment by pkdash** [comment]
@gantian127 Metadata can be added to any single file if it's not already part of an aggregation (except for fileset aggregation).

**Comment by Maurier** [comment]
This issue is also fixed by https://github.com/hydroshare/hydroshare/pull/3677

**Comment by Maurier** [comment]
Fix confirmed working on beta. Closing.
