### ISSUE TITLE
Groups page inconsistencies and request to join has disappeared

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#3672]
If I go to a group landing page (e.g. https://www.hydroshare.org/group/2) when not logged in I see a listing of resources shared with that group.

If I am logged in and go to a group landing page for a group that I am not a member of I see just the group description and there is a "members" tab with no content below.  If I click on the member tab, it expands to show the members, but does not show the button where I can request to join.  This is incorrect and appears to be a regression.  What should be shown is the list of public resources shared with that group and a button where you can request to join.  I think the list of members should be protected until one is admitted as a member.  Only the owners should be shown.

If I am logged in and go to a group landing page for a group that I own I see the resources tab and the members tab.  This is correct.

If I am logged in and go to a group landing page for a group that I am a member of I see the resources tab and members tab.  This is correct.

These inconsistencies appear to have been introduced with the work to "fix" group listings #3636,  #3382 and perhaps some of the CZO work.  Assigning to @martinseul and @cuahsimarko as product owner and developer respectively for Group functionality.

See https://help.hydroshare.org/participation-and-collaboration/find-groups/ as this describes how groups worked before the regressions due to recent changes.

**Comment by cuahsimarko** [comment]
This GitHub Issue is best separated into 3 actionable work items:

- Ask to join button removed as part of work at https://github.com/hydroshare/hydroshare/issues/3636
- Unauthenticated display of Groups pages is working as expected. Explanation of logged in and not logged in functionality for Groups - I believe Amber and Jon are working on this documentation. I'll follow up with @martinseul 
- Resources Tab should always display and either show available resources or an empty table and appropriate message
![image](https://user-images.githubusercontent.com/45397838/68699011-26851580-0550-11ea-9a35-e8fc0c4d1e01.png)
