### ISSUE TITLE
iframes and other injected html can be used in resource labels

### ISSUE THREAD

**Issue by hydrocheck** [hydroshare/hydroshare#3684]
For example using '<iframe src="google.com"></iframe>' as a label for resources actually renders the iframe in the user interface.

[001.zip](https://github.com/hydroshare/hydroshare/files/3867038/001.zip)

**Comment by Castronova** [comment]
Just tested this and it appears that once an iFrame is added as a label, there's no way to remove it.

**Comment by Castronova** [comment]
related to #3685  and #3683
