### ISSUE TITLE
Styling of "Send Invite" button is broken in IE11

### ISSUE THREAD

**Issue by hydrocheck** [hydroshare/hydroshare#3687]
Sending group invites with IE11, users will see broken styling for the "Send Invite" button

[004.zip](https://github.com/hydroshare/hydroshare/files/3867046/004.zip)

**Comment by Castronova** [comment]
![send-invitation-button-styling-ie11](https://user-images.githubusercontent.com/4822372/109546184-d8bf5400-7a97-11eb-9475-57909a85bb6b.png)

**Comment by Castronova** [comment]
Closing because IE11 is no longer supported.
