### ISSUE TITLE
No validation, compression, or optimization of Groups page images

### ISSUE THREAD

**Issue by hydrocheck** [hydroshare/hydroshare#3689]
Folks can upload really large images for their group images.  These are pulled from the server in their full resolution, then just cropped/scaled client-side.  This results in long load times, even now (20 sec on a gigabit connection - probably way worse on "normal" connections).  I uploaded a png to test (~3000px by ~2000px) and it took a full 10 seconds to load on the Groups page.  While this may not be a "show stopping" concern now - it could quickly become more of an issue as groups/communities grow.

[006.zip](https://github.com/hydroshare/hydroshare/files/3867052/006.zip)

**Comment by cuahsimarko** [comment]
I think this is a duplicate @ndebuhr please review related Labels and identify the duplicate and choose which one you want to keep

**Comment by hydrocheck** [comment]
Automated close - duplicate
