### ISSUE TITLE
Button for downloading a bag is ambiguously labeled

### ISSUE THREAD

**Issue by danames** [hydroshare/hydroshare#369]
The button "Download All (filesize)" is a bit uninformative and misleading. What actually happens when you click this button is you get a zip file in the BagIt format. The BagIt format is going to be new and bizarre to most users who will see this random stuff in their zip file and think, "hey what in the heck is all this stuff? And what is it doing in this zip file?"

I propose we address this problem by simply changing the text "Download All (file size)" to be, "Download All Content as Zipped BagIt Archive (file size)". Next to the Download button will be text that says, "Learn more about the BagIt Archive format used by the U. S. Library of Congress." When a user clicks that link they are taken to a nice wikipedia page about BagIt: http://en.wikipedia.org/wiki/BagIt.

**Comment by horsburgh** [comment]
Related to issue #363

**Comment by ironfroggy** [comment]
It would be a lot simpler to just add that informative link about the BagIt
format than to also add an alternative download button that requires an
alternative packing view to prepare a non-BagIt zip archive.

On Mon, May 11, 2015 at 11:53 PM, Jeff Horsburgh <notifications@github.com>
wrote:

> Related to issue #363
> <https://github.com/hydroshare/hydroshare/issues/363>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hydroshare/hydroshare/issues/369#issuecomment-101119033>
> .
>



-- 


*Calvin Spealman*Lead Front-end Developer

calvin@caktusgroup.com <calvin@caktusgroup.com>
www.caktusgroup.com

**Comment by danames** [comment]
Exactly. I think well-documented simple functionality should always trump
complex poorly-documented functionality.

**Comment by dtarb** [comment]
@mauriel133 could you please do this as part of your interface improvements.  I agree with the suggestion to use text "Download All Content as Zipped BagIt Archive (file size)" in the button and a link nearby to learn more about the Bagit archive format.

**Comment by mauriel133** [comment]
For the learn more button should I link the wikipedia entry for BagIt (http://en.wikipedia.org/wiki/BagIt) or is there a more reliable source?

**Comment by dtarb** [comment]
I considered https://confluence.ucop.edu/display/Curation/BagIt which is perhaps more authoritative, but the Wikipedia article is quite nice and comprehensive, so I lean towards it.

**Comment by mauriel133** [comment]
I've linked the wikipedia article for now.

**Comment by dtarb** [comment]
Deployed in 1.5.1
