### ISSUE TITLE
Groups description is overcropped

### ISSUE THREAD

**Issue by hydrocheck** [hydroshare/hydroshare#3693]
There is a scroll bar to view group descriptions, but the section is much smaller than it needs to be in places - resulting in a small scrollable window with a lot of whitespace underneath.

[000.zip](https://github.com/hydroshare/hydroshare/files/3884639/000.zip)

**Comment by cuahsimarko** [comment]
The title is missing from macOS chrome latest on the Groups page 
![image](https://user-images.githubusercontent.com/45397838/106624235-6d8b6c00-6543-11eb-915d-b25d4bec2bc4.png)

**Comment by Castronova** [comment]
appears to be resolved.
