### ISSUE TITLE
No pagination in community resources

### ISSUE THREAD

**Issue by hydrocheck** [hydroshare/hydroshare#3694]
All the community resources are displayed in one really long list.  There is no pagination or "infinite scroll, load more only as needed" approach.

[001.zip](https://github.com/hydroshare/hydroshare/files/3884641/001.zip)

**Comment by cuahsimarko** [comment]
@ndebuhr This is a duplicate and also doesn't provide the design information needed. Please identify the duplicate and consolidate any additional information you want into it.

**Comment by hydrocheck** [comment]
Automated close - duplicate
