### ISSUE TITLE
Filters do not work in IE11 for Communities

### ISSUE THREAD

**Issue by hydrocheck** [hydroshare/hydroshare#3695]
The Communities resources page features a "Shared by" filter.  This filter does nothing on IE11.

[002.zip](https://github.com/hydroshare/hydroshare/files/3884643/002.zip)

**Comment by cuahsimarko** [comment]
In design discussions with CZO, IE11 is not supported for the initial release. As they will be the only users of this element until another Community comes online this can remain low priority and part of the Communities generalization refactoring, where support for multiple communities is added.

**Comment by Castronova** [comment]
Closing because IE11 is no longer supported
