### ISSUE TITLE
Lots of whitespace between the "Accept" and "Reject" for managing group join requests.

### ISSUE THREAD

**Issue by hydrocheck** [hydroshare/hydroshare#3699]
There is a lot of whitespace between the "Accept" and "Reject" buttons when managing group join requests.  It feels like the Reject CSS is broken, because it's way off the right.

[006.zip](https://github.com/hydroshare/hydroshare/files/3884660/006.zip)

**Comment by cuahsimarko** [comment]
possibly related https://github.com/hydroshare/hydroshare/issues/4050
