### ISSUE TITLE
Resources in inconsistent state

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#37]
This is from testing alpha.hydroshare.org version 1.2.1

If an error occurs during resource creation the system can end up in an inconsistent state such as illustrated.  
![p4](https://cloud.githubusercontent.com/assets/3456833/5604044/26394602-9361-11e4-8411-b25b54097b88.JPG)

I am unable to delete this resource, despite being its owner.  

Also resources in this complete state do not show up in the filtering "owned by me", despite showing up in the listing of all resources with me as the owner.

**Comment by rayi113** [comment]
HydroShare Resource Creation Workflows Issues in GitHub: #37, #62, #81

**Comment by dtarb** [comment]
Presumed to be resolved by new resource creation workflow.
