### ISSUE TITLE
Globals in hydroshare/hs_core/views/__init__.py

### ISSUE THREAD

**Issue by ironfroggy** [hydroshare/hydroshare#370]
Can anyone explain, in the create_resource view, why `res_class` is a global? Or `resource`? This is making the flow and intent of resource creation very confusing and likely quite fragile. I'm filing this ticket as a recommendation to refactor this at some point (not needed for 1.5.1) and as a follow up the rest of the codebase should be reviewed for global statements, of which there should be none.

```
def create_resource(request, *args, **kwargs):
    global resource
    qrylst = request.POST
    frm = CreateResourceForm(qrylst)
    if frm.is_valid():
        global res_cls
        # Send pre_call_create_resource signal
        metadata = []
        pre_call_create_resource.send(sender=res_cls, resource=resource, metadata=metadata,
```

**Comment by hyi** [comment]
I agree we should get rid of this global res_cls variable. Once a resource object is available, res_cls can be obtained by calling "res_cls = res.__class__" as done in add_file_to_resource(). I am assigning this issue to myself as I want to remove a couple of other routines (e.g., create_resource()) that are no longer used now that we are going with the new resource creation workflow Pabitra implemented. Pabitra, if you'd like to work on this, feel free to assign it to you.

**Comment by hyi** [comment]
A pull request has been created for this a while ago. If everything runs as expected after the pull request is merged in, this issue should be closed. Added release 1.6 milestone.

**Comment by hyi** [comment]
The pull request was merged into develop and tested on dev; nothing is broken, so closing.
