### ISSUE TITLE
Clean up page processor context code for hs_core

### ISSUE THREAD

**Issue by hyi** [hydroshare/hydroshare#3704]
There are a lot of code duplication in this page processor context method: https://github.com/hydroshare/hydroshare/blob/develop/hs_core/page_processors.py#L32, which needs to be cleaned up sooner rather than later. As more context variables are being added in duplicate fashion, it'd be more work to clean up the mess. I am assigning this to myself.

**Comment by cuahsimarko** [comment]
Hong let's please discuss and also include Scott later, when the time comes as a part of cleanup work I've started.

**Comment by hyi** [comment]
@cuahsimarko Sounds good. If we remove resource landing page from being a Mezzanine page in the cleanup work you've started, this issue will be taken care of as the part of the cleanup.

**Comment by hyi** [comment]
This refactoring effort is not worthwhile due to the ongoing efforts for hsmodels based approach. Closing.
