### ISSUE TITLE
unapproved webapps shows up on the file-level right-click menu for everyone

### ISSUE THREAD

**Issue by zhiyuli** [hydroshare/hydroshare#3710]
We notice if a public webapp connector resource has indicated it supports certain file extensions, it will show up on the file-level right-click menu for everyone even it is a unapproved app.

![image](https://user-images.githubusercontent.com/10070599/70156427-88312f00-1679-11ea-98b5-fd4cf343cd39.png)

**Comment by dtarb** [comment]
@sblack-usu I think you worked on this and may be in a good position to fix.  Lets discuss to make sure we are clear on the functionality needed.

**Comment by sblack-usu** [comment]
Looking over the code, I see where this is happening and see a straightforward fix.  I'll setup PR once I get the changes in and tests updated.
