### ISSUE TITLE
where did the WebApp Tab Page go?

### ISSUE THREAD

**Issue by zhiyuli** [hydroshare/hydroshare#3711]
I remember we used to have a WebApp Tab Page somewhere on the resource landing page that showed all applicable WebApps no matter they are approved or unapproved.

**Comment by horsburgh** [comment]
The entire tabbed interface was removed a long time ago by design as part of the Resource Landing Page redesign. If we need something like this, I suggest thinking about what is needed and where it should go and then creating new designs and issues to go along with it.
