### ISSUE TITLE
Raster Aggregations in the same folder fail to aggregate

### ISSUE THREAD

**Issue by sblack-usu** [hydroshare/hydroshare#3716]
>Failed to set the selected aggregation type
>Geographic raster aggregation type validation failed. One or more additional tif files were found which are not listed in the provided logan.vrt file.

Update the raster aggregation rule associated with this message to handle aggregations in the same folder.  Check and fix other aggregations that may have similar rules.

**Comment by dtarb** [comment]
Closing as was checked in release 1.30.  Re-open in case this is appears again.
