### ISSUE TITLE
How to cite information missing on some resources

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#3717]
I noticed this doing demo's at AGU.  For most resources there is italics text below the how to cite that gives a the DOI citation format, such as 
![image](https://user-images.githubusercontent.com/3456833/70594905-17b96f00-1b9f-11ea-93b9-75b8100ee5f6.png)

However for a few resources, such as this one 
https://www.hydroshare.org/resource/49d795e48a8a42e289bc3ee7e859dd01/
the text is missing
![image](https://user-images.githubusercontent.com/3456833/70595070-88608b80-1b9f-11ea-9b61-fe1b81225821.png)

**Comment by cbcunc** [comment]
I see this:

How to Cite
Black, S. ì. (2019). CUAHSI Binder, HydroShare, http://www.hydroshare.org/resource/49d795e48a8a42e289bc3ee7e859dd01

This resource is shared under the Creative Commons Attribution CC BY.
 http://creativecommons.org/licenses/by/4.0/

**Comment by dtarb** [comment]
It is the text "When permanently published ..." that is missing.

**Comment by dtarb** [comment]
OK.  Sincere apologies.  This is a private/public issue.  The text in question shows up when a resource is made public, then disappears when it is made private.
