### ISSUE TITLE
solr_update crashes when a resource has been deleted from Django and is still in SOLR

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#3718]
If a resource has been deleted from Django and is still in SOLR, the solr_update process crashes rather than simply deleting it from SOLR.

**Comment by martinseul** [comment]
@sblack-usu @hyi @alvacouch Is this still an issue I think to remember that there was some work done looking at the deletion process?

**Comment by alvacouch** [comment]
I fixed this in a previous PR but then it popped up again and I am fixing it again in the next PR. I think it's safe to close this. I won't forget.
