### ISSUE TITLE
Google Maps displaying for development only

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#3724]
For crying in a bucket.  This is what I am getting today.
![image](https://user-images.githubusercontent.com/3456833/70869040-f7ddce80-1f43-11ea-8799-6133eb0c3af9.png)

**Comment by martinseul** [comment]
I looked into the google maps issue and there was a declined payment due to an issue with our bank that needed to be rerun and now the map is not showing the message.
![image](https://user-images.githubusercontent.com/5427742/70942704-3eebc280-201d-11ea-8ed6-5f78e25d3d32.png)

**Comment by dtarb** [comment]
Thanks
