### ISSUE TITLE
Python 3 upgrade manual beta testing

### ISSUE THREAD

**Issue by sblack-usu** [hydroshare/hydroshare#3732]
This is a checklist for a Manual pre-deploy check list used in the past.  It should help us be thorough in testing the far corners of HydroShare.  https://docs.google.com/document/d/1iHySO-5Kpfp1sBgixWj-Hv0yFy95WUVPvsmg2JmURaU

# 3 Testing Profile
- [x] 3.1 Sign Up
- [x] 3.2 Sign In
- [x] 3.3 Reset Password
- [x] 3.4 Profile Editing
- [x] corresponding iRODS user creation and deletion
# 4 Testing Homepage
- [x] 4.1 Testing links in Header Section
- [x] 4.2 Testing links in Body Section
- [x] 4.3 Testing links in Footer Section
# 5 Testing Resources
- [x] 5.1 General Functions
  - [x] 1) My resources
  - [x] 2) resource creation
  - [x] 3) resource editing
  - [x] 4) resource publication
  - [x] 5) resource versioning
  - [x] add files from iRODS to resources
# 6 Resource Copying
- [x] Resource Copying
# 7 Resource Specific Functions
- [x] 7.1 Time Series
- [x] 7.2 HIS time Series
- [x] 7.3 Geographic Raster
- [x] 7.4 Geographic Feature
- [x] 7.5 Multidimensional
- [x] 7.6 Model Program (no testing details in the above document, did basic testing @sblack-usu)
- [x] 7.7 Model Instance (no testing details in the above document, did basic testing @sblack-usu)
- [x] 7.8 SWAT Model Instance (no testing details in the above document, did basic testing @sblack-usu)
- [x] 7.9 Web App (no testing details in the above document, did basic testing @sblack-usu)
- [x]  7.10 Script (no testing details in the above document, did basic testing @sblack-usu)
- [x] 7.11 Collection (no testing details in the above document, did basic testing @sblack-usu)
- [x] 7.12 Composite (no testing details in the above document @sblack-usu)
# 8 Testing Access Control
- [x] 8.1 Sharing Status
- [x] 8.2 Manage Access
# 9 Testing Discover
- [x] 9.1 Text Search
- [x] 9.2 Map search
# 10 Testing Terms Page
- [x] it renders

**Comment by hydrocheck** [comment]
- https://github.com/hydroshare/hydroshare/issues/3735
- https://github.com/hydroshare/hydroshare/issues/3736
- https://github.com/hydroshare/hydroshare/issues/3737
- https://github.com/hydroshare/hydroshare/issues/3738
- https://github.com/hydroshare/hydroshare/issues/3739

**Comment by sblack-usu** [comment]
Made patch https://github.com/hydroshare/hydroshare/pull/3726/commits/e0c6d65c7473bcc4596722787880c6c8a3a1a6b4 to fix an issue with adding files from irods user zone to a resource.
