### ISSUE TITLE
OPeNDAP link is broken

### ISSUE THREAD

**Issue by gantian127** [hydroshare/hydroshare#3734]
The OPeNDAP function works well when user clicks on "Open with" button. But it will show error info if I right click on a netCDF file and select "OPeNDAP". 

Testing resource: https://www.hydroshare.org/resource/deb0250d446441fd886a2e288b5a8a90/
It seems the opendap link for the file is not correct when using the right click function. 

![image](https://user-images.githubusercontent.com/5016511/72114376-8e619d80-3300-11ea-8c7f-31427e7cdf02.png)
![image](https://user-images.githubusercontent.com/5016511/72114466-d4b6fc80-3300-11ea-8b51-4bfc4c8c09a8.png)

**Comment by hyi** [comment]
@gantian127 You are right that opendap link for the file is not correct when using the right click function. Specifically, this is the link being redirected when opening using the right click function: ```http://hyrax.hydroshare.org/opendap/deb0250d446441fd886a2e288b5a8a90/data/contents/ueb_swe_netcdf/ueb_swe_netcdf.nc/ueb_swe_netcdf.nc.html```. Note the last slash string in the link ```/ueb_swe_netcdf.nc.html``` which should not be there and I don't know where it comes from. Removing that from the link would make the right click link to work. @sblack-usu Any idea where that last html string comes from?

**Comment by sblack-usu** [comment]
Here is the launching string.  It looks like this web app was built before the composite resource folderless aggregation update and hadn't been updated (HS_AGG_PATH used to point to the folder for the aggregation, now points to the main file in the aggregation)
![image](https://user-images.githubusercontent.com/35820390/72167803-18554900-3389-11ea-9b6e-52716d182784.png)
I went ahead and updated the launching pattern and it is working for me.

**Comment by sblack-usu** [comment]
I'm looking to see if any other web app resources might have this same problem.

**Comment by hyi** [comment]
@sblack-usu Good catch. It works now for me.

**Comment by martinseul** [comment]
@sblack-usu @hyi thanks can we close this then?
