### ISSUE TITLE
The map tab on the Discover page never completes loading

### ISSUE THREAD

**Issue by hydrocheck** [hydroshare/hydroshare#3735]
The map and some UI elements are rendered, but the loading continues indefinitely.

[002.zip](https://github.com/hydroshare/hydroshare/files/4045858/002.zip)

**Comment by sblack-usu** [comment]
This is happening on www as well.  Confirmed with both firefox and chrome.  

From the console, could be a lead to the cause.
![image](https://user-images.githubusercontent.com/35820390/72173295-720f4080-3394-11ea-80c7-dd414222ef67.png)

Relevant code from our side:
```
    map.enableKeyDragZoom({
        key: 'shift',
        visualEnabled: true
    });
```

**Comment by sblack-usu** [comment]
@Maurier - anything thoughts here?

**Comment by Maurier** [comment]
Looks like the CDN for https://cdn.rawgit.com/googlemaps/v3-utility-library/master/keydragzoom/src/keydragzoom.js is broken. We will need to find a new CDN or host this script ourselves.

**Comment by Maurier** [comment]
Also, it looks like https://rawgit.com/ will be shut down soon, so we should probably point other dependencies we used from this CDN somewhere else. We have at least a few:
![image](https://user-images.githubusercontent.com/2448568/72178337-f5825f00-339f-11ea-9b01-b340f40ad850.png)

**Comment by Maurier** [comment]
Looks like we can use https://github.com/Concept211/Google-Maps-Markers#usage-custom to point to numbered marker images.

We can also point to the scripts at https://www.jsdelivr.com/
