### ISSUE TITLE
Anonymous users are given more access than logged-in users for Group resources

### ISSUE THREAD

**Issue by hydrocheck** [hydroshare/hydroshare#3736]
Without logging in, folks are able to see group resources like for https://beta.hydroshare.org/group/3.  Logging in, it's no longer possible to see this.  I can't envision a use case where no-login should have more rights than a logged-in users, so filing as a bug.

[003.zip](https://github.com/hydroshare/hydroshare/files/4045914/003.zip)

**Comment by cuahsimarko** [comment]
The design decision here is to have the Authenticated view match Discover and the Unauthenticated Groups View or if the Authenticated view should diverge from those two.

- Unauthenticated Discover/search allows listing Public resources currently
- The Public resource is viewable (unauthenticated) at https://beta.hydroshare.org/resource/1a25b11fa1354773b6edb9495e754f4e/
- Unauthenticated Groups View matches this behavior, by listing the Public resource and allowing the user to click/view it, without logging in
- Current Groups View (authenticated) diverges from this and requires that the user join the group, not listing the resources or providing links, even though elsewhere in the UI the user can gain access to this information/view without joining the Group

Proposal is to modify Groups to match the new, Unauthenticated view as well as the old/existing Discover permissions (can list/view Public resources without logging in) @alvacouch @martinseul @Castronova @Maurier Can you all share your opinions here?

**Comment by cuahsimarko** [comment]
@dtarb Please comment also, if you wish

**Comment by alvacouch** [comment]
@cuahsimarko I like your proposal.

**Comment by Castronova** [comment]
@cuahsimarko I agree with your proposal.

**Comment by eclark-cuahsi** [comment]
Related to #4105

**Comment by pkdash** [comment]
@dtarb I am fixing this as part my work on #4211

**Comment by dtarb** [comment]
Addressed in PR #4419

**Comment by pkdash** [comment]
This has been fixed in 1.51.1 - so closing.
