### ISSUE TITLE
The "Find Groups" menu item does not always redirect to the Find Groups page

### ISSUE THREAD

**Issue by hydrocheck** [hydroshare/hydroshare#3737]
If you are on the Find Groups page, the Find Groups link correctly redirects (to the same page you are already on).  However if you click the Find Groups menu/link on a Group page, it redirects to the collaborate page.

[004.zip](https://github.com/hydroshare/hydroshare/files/4045917/004.zip)

**Comment by pkdash** [comment]
Has been fixed as per testing on prod.
