### ISSUE TITLE
[SUPPORT] - Resource changing operations in beta not working properly

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#374]
Following from a user

I was uploading resources to Hydroserver and a couple times got this funny error. I just wanted to let you guys know that this was happening.

AttributeError at /hsapi/_internal/f7a2e8d934cf41679d7f029da0e41277/delete-resource-file/678/

'NoneType' object has no attribute 'resource_file'

Request Method: 	GET
Request URL: 	http://beta.hydroshare.org/hsapi/_internal/f7a2e8d934cf41679d7f029da0e41277/delete-resource-file/678/
Django Version: 	1.7.1
Exception Type: 	AttributeError
Exception Value: 	

'NoneType' object has no attribute 'resource_file'

Exception Location: 	/home/docker/hydroshare/hs_core/views/__init__.py in delete_file, line 251
Python Executable: 	/usr/bin/python
Python Version: 	2.7.6
Python Path: 	

['/home/docker/hydroshare',
 '/usr/local/lib/python2.7/dist-packages/netCDF4-1.1.1-py2.7-linux-x86_64.egg',
 '/usr/lib/python2.7/dist-packages',
 '/home/docker/hydroshare',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages/PILcompat',
 '/home/docker/hydroshare']

Server time: 	Thu, 14 May 2015 22:10:07 +0000

**Comment by mjstealey** [comment]
Update made to submodule django_irods that should address the observed issue.

Have tested with 383 MB file successfully as a generic resource, other resource types should also be checked.

**Comment by dtarb** [comment]
Tested and was able to add and delete a resource without this error.
