### ISSUE TITLE
Spacing around References text needs to be improved

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#3745]
![image](https://user-images.githubusercontent.com/3456833/72865413-ffa43780-3c94-11ea-8226-26229abfc9b0.png)
occurs in https://www.hydroshare.org/resource/1a116e5460e24177999c7bd6f8292421/

**Comment by horsburgh** [comment]
@Maurier - the text of the references has changed, but the spacing is still a problem:

![image](https://user-images.githubusercontent.com/3485902/80252143-ffb92800-8633-11ea-9299-baa718ac4e9d.png)

These just need some additional white space surrounding them. I'm going to change the title of this issue to reflect that it's now a spacing issue.

**Comment by devincowan** [comment]
@horsburgh perhaps this was resolved some time in the last 2 years. Does this look okay to you now? thx

https://www.hydroshare.org/resource/1a116e5460e24177999c7bd6f8292421/
![image](https://user-images.githubusercontent.com/17934193/153273545-4b458765-18d5-4746-9cfc-dda7efa28e02.png)

**Comment by pkdash** [comment]
@devincowan This was fixed as part of #3261 and deployed in the latest release 1.52. I think we can close it.
