### ISSUE TITLE
Enable large file upload

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#3748]
We need a system for large file upload parallel to the current Nginx "large file download" support. This is related also to consistency issues for large files and large number of files handling.

**Comment by Castronova** [comment]
@alvacouch is this ticket still relevant or can it be closed?

**Comment by devincowan** [comment]
I'm going to take a look and see if we can enable large file upload from a cloud bucket.
If we can, it would negate the need for issues:
* https://github.com/hydroshare/hydroshare/issues/5318
* https://github.com/hydroshare/hydroshare/issues/5329
* https://github.com/hydroshare/hydroshare/issues/5104
