### ISSUE TITLE
Folder duplicates

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#3751]
A user reported this problem.  I verified that it is real for the first of the resources indicated.  Suspicion is that this is related to Python 3 upgrade

This morning around 11 am, as ~ 15 CAS project members tried to access two hydroshare resources, the resources showed multiple copies of the same folder (see below). This issue is even worse now for the Wildfire group (16 folders named Economic Analysis and 9 folder named Fire Analysis).
Cohort 1 - Wildfire - https://www.hydroshare.org/resource/c063e0d244744d298428ea17e3a93b69/
Cohort 2 - Utah Ski Areas - https://www.hydroshare.org/resource/f528f92d8a47464d906058dd2882ba7c/

There was only 1 instance of each folder yesterday. Not sure how to resolve.

**Comment by cbcunc** [comment]
Verified that only one collection for each folder exists in iRODS:

```bash-4.2$ ils ../wwwHydroProxy/c063e0d244744d298428ea17e3a93b69/data/contents
/hydroshareZone/home/wwwHydroProxy/c063e0d244744d298428ea17e3a93b69/data/contents:
  Extended_Metadata.pdf
  Fire_PrudencioEtAl_2018.pdf
  C- /hydroshareZone/home/wwwHydroProxy/c063e0d244744d298428ea17e3a93b69/data/contents/Economic Analysis
  C- /hydroshareZone/home/wwwHydroProxy/c063e0d244744d298428ea17e3a93b69/data/contents/Fire Analysis
  C- /hydroshareZone/home/wwwHydroProxy/c063e0d244744d298428ea17e3a93b69/data/contents/Interviews
-bash-4.2$ ils ../wwwHydroProxy/f528f92d8a47464d906058dd2882ba7c/data/contents
/hydroshareZone/home/wwwHydroProxy/f528f92d8a47464d906058dd2882ba7c/data/contents:
  Instructions.docx
  C- /hydroshareZone/home/wwwHydroProxy/f528f92d8a47464d906058dd2882ba7c/data/contents/Figure3
  C- /hydroshareZone/home/wwwHydroProxy/f528f92d8a47464d906058dd2882ba7c/data/contents/Figure4
  C- /hydroshareZone/home/wwwHydroProxy/f528f92d8a47464d906058dd2882ba7c/data/contents/Figure5
  C- /hydroshareZone/home/wwwHydroProxy/f528f92d8a47464d906058dd2882ba7c/data/contents/Figure6
  C- /hydroshareZone/home/wwwHydroProxy/f528f92d8a47464d906058dd2882ba7c/data/contents/FigureS1
  C- /hydroshareZone/home/wwwHydroProxy/f528f92d8a47464d906058dd2882ba7c/data/contents/FigureS2
-bash-4.2$ ```

**Comment by hyi** [comment]
I have just fixed this issue by deleting the temporary zips folder that did not get cleaned up properly by celery tasks. I need to augment the iRODS query to be more restrictive so that it will not pick up folders in the temporary zips collection. Will create a PR today when I get it ready. I think the PR should target for a hotfix. @dtarb Can you verify when you get a chance this issue is indeed fixed for these resources?

**Comment by dtarb** [comment]
Thanks.  This appears fixed for the two resources where this was reported.  @hyi feel free to close this if you think it is settled, or leave open while the permanent fix PR is processed, as you see fit.

**Comment by cbcunc** [comment]
Just spoke with @hyi and it was triggered by creating a zip of a resource that already had a zips folder within itself and the user repeatedly creates zips of the resource. Not a use case that happens often, but one that may or not warrant a selenium test for regression purposes.

**Comment by hyi** [comment]
Code fix for this issue has been deployed, so closing this issue.
