### ISSUE TITLE
Discovery harvesting crashes if creators is None

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#3753]
if `resource.metadata` is `None` or `resource.metadata.creators` is `None` (which should not be able to happen, but does), then discovery harvesting crashes.

**Comment by cuahsimarko** [comment]
Is this a problem in hs_discover/views.py or elsewhere?

**Comment by cuahsimarko** [comment]
@alvacouch are you referring to "harvesting" in the old discover or in the Index areas of the code?

**Comment by alvacouch** [comment]
I'm referring to search_indexes.py and harvesting and this has been fixed.
