### ISSUE TITLE
NFIE Search Fields

### ISSUE THREAD

**Issue by ironfroggy** [hydroshare/hydroshare#376]
Now that my search work's first iteration has landed I want to begin expanding on it. Right now this provides full-text and resource type filtering. I need a canonical list of fields that need to be searchable from this interface for NFIE, but I can't provide that list. Please document this minimum field set here so that I can complete this followup task.

**Comment by alvacouch** [comment]
Thanks. What you have completed now does a lot for usability.

I think we need to confer amongst ourselves to answer this question.
When Dave T becomes available, will discuss with him.

Alva L. Couch, Ph.D.
Senior Architect, CUAHSI Water Data Center
http://wdc.cuahsi.org
+1 339 221 5400 x 203

**Comment by dtarb** [comment]
I am available - good timing.  @mjstealey which deployment has this work for me to see and comment on.

**Comment by dtarb** [comment]
Following is my prioritized suggestion

1. Searchable field set

  * Type (we have this)
  * Owner 
  * Author (for display we use the word Author, while in the Dublin core metadata this is Creator)
  * Contributor
  * Subject (this operates on keywords)
  * Title
  * Abstract
 

2. I would also like to see Own, Can Edit, Can View and Public as check box filters on the left as you originally proposed in your 3/11/15 email.  (In general going back through that thread would be good).  Note that there may be multiple Owners, Authors or Contributors.  Note also that filtering on owner is different from the "Resources I Own" filter on the left as it allows finding resources owned by someone else.  
![capture](https://cloud.githubusercontent.com/assets/3456833/7671108/a71bf30e-fc7b-11e4-9171-cc5e421c3b10.PNG)
Public needs to be added to the list above.

3. I would also like the ability to sort on the columns displayed.  By clicking on the column header the list displayed should be re-ordered similar to the way Windows explorer works on a PC or Finder works on a Mac in list mode. 

4. Eventually I would like column filtering as suggested in your 3/11/15 email, but that is a "nice to have" feature that should not delay deployment of the above.

1 and 2 is probably sufficient for NFIE.  3 would be nice if not too hard and 4 can be left for later.

**Comment by ironfroggy** [comment]
Dave,

Can you add the checkboxes and ordering by a column as two items to the prioritization list? If anything has to be delayed until after NFIE for time, I want to make sure the right things make it in.

**Comment by dtarb** [comment]
@ironfroggy I edited the comment above to have check boxes.  This removed the numbering, but the prioritization is top to bottom

**Comment by ironfroggy** [comment]
I have pushed Pull Request #412 To implement the search fields checked off in the list.

**Comment by ironfroggy** [comment]
I split some of the remaining issues into their own tasks.

**Comment by rayi113** [comment]
In the Chrome browser, on dev.hydroshare.org, let's say I want to do a search for all HydroShare resources with the word "test" in the title.  When I type test in the search box without quotes, it auto-identifies "Owner test user (testuser)" and "Subject test" as search parameters, however neither of these give the desired result.  

![search_test_02](https://cloud.githubusercontent.com/assets/2846017/8013441/2af65654-0b97-11e5-84fd-4c7c36966842.png)

If I type "test" in the search box with quotes, this gives the desired result.  

![search_test_03](https://cloud.githubusercontent.com/assets/2846017/8013433/2069e4bc-0b97-11e5-92a9-be13984f1c7f.png)

By comparison, typing logan in the search box without quotes gives all HydroShare resources with the word logan in the title.  In Internet Explorer the behavior is different and does not auto-identifies "Owner test user (testuser)" and "Subject test" as search parameters. 

![search_test_01](https://cloud.githubusercontent.com/assets/2846017/8013409/f833f9c4-0b96-11e5-811d-8e04b7986006.png)

Can this be made consistent, i.e. quoting vs. non-quoting search parameters across different browsers?

**Comment by ironfroggy** [comment]
@rayi113 can we open additional issues to track what you've identified? But before you do that, some quick responses:

- What is wrong with the first behavior? If the word you type matches those two items, they should be suggested. If neither are what you want, then neither need be used. They are only suggestions, after all.
- What versions of Internet Explorer does Hydroshare policy support? How many versions back do you expect to work?

**Comment by dtarb** [comment]
As policy we should support the most recent version of all major browsers (which granted is a bit of a moving target, but it is reality).  I am not sure which version @rayi113 tested with.

Testing with Firefox 38.0.5 currently the latest version I get the following somewhat counter intuitive behavior.

I type tarboton in the search box.  I get nothing found.  I type d in the search box and get an option to pick author David Tarboton which returns the 3 resources for which I am first author.  I type a in the search box and I get a list to choose from that includes author Alan Snow but not Author Tarboton, or David Tarboton.  It seems that there is no way to search only on the last name of an author, or if there is, it is not explained anywhere.

**Comment by dtarb** [comment]
Closing this issue as we are done with NFIE Release.  Remaining issues are in separate tickets: #421, Field Labels; #448 Style Fixes; #455, Own, Edit, View, Public boxes; #456, Column Sorting; #472, Filtering Refinements and #473 Browser Consistency.
