### ISSUE TITLE
Add check for LogicalFile without files

### ISSUE THREAD

**Issue by sblack-usu** [hydroshare/hydroshare#3762]
LogicalFiles without files on the system are invalid and can cause problems in a HydroShare resource.  Because the file system is our source of truth, we are safe to remove these LogicalFiles with the logical_delete method

**Comment by pkdash** [comment]
Fileset (logical file) by design can exists without any files.

**Comment by sblack-usu** [comment]
We have not seen problems caused by this since and the move towards [file-based aggregations](#4130) will  change this behavior.
