### ISSUE TITLE
Unable to load file from 3rd party iRODS

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#3776]
I tried to create a resource from my account on data.iplantcollaborative.org and after selecting the file a spinner appears for a short while and then goes away, but no file is added to the resource.

![image](https://user-images.githubusercontent.com/3456833/75612777-facc7200-5ae3-11ea-8b6c-b5f0c296ebe3.png)

**Comment by dtarb** [comment]
This bug also appears on beta attempting to load a file from users.hydroshare.org.

**Comment by hyi** [comment]
@dtarb I have verified that it works on just deployed www production server now. Can you quickly verify as well and close the issue if it works for you also?

**Comment by dtarb** [comment]
Tested on www.  Verified that file upload from iRODS works, but when I download and unzip a bag I get

![image](https://user-images.githubusercontent.com/3456833/76331099-4afdbe00-62b4-11ea-8bd7-c341628e5c70.png)

Thus https://github.com/hydroshare/hydroshare/issues/2661 is not yet fixed.  I'll close this issue but we still need to work on #2661
