### ISSUE TITLE
Cannot zip a folder containing aggregations

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#3777]
I tried to zip a folder containing aggregations and received the following message.  Is there a good reason why a folder containing aggregations can not be zipped.
![image](https://user-images.githubusercontent.com/3456833/75674269-f7e79380-5c41-11ea-8e65-ce1422497667.png)

**Comment by hyi** [comment]
@dtarb This issue is a duplicate of https://github.com/hydroshare/hydroshare/issues/2979 from which you can find explanation from @pkdash about this behavior.

**Comment by sblack-usu** [comment]
closing, duplicates #2979
