### ISSUE TITLE
Broken button for delete temporal coverage button

### ISSUE THREAD

**Issue by AmberSJones** [hydroshare/hydroshare#3781]
I am editing a resource and trying to delete the temporal coverage. The delete icon has no effect. 

![image](https://user-images.githubusercontent.com/5023186/75917304-0c30b980-5e17-11ea-8e6a-31bce5feaaab.png)

**Comment by sblack-usu** [comment]
@Maurier - could you take a look at this?  Looks like the delete ui button is broken.

**Comment by Maurier** [comment]
@sblack-usu Yeah, I'll check it out this week.

**Comment by martinseul** [comment]
@Maurier are you working on this issue?

**Comment by Maurier** [comment]
@martinseul I think this was fixed a while ago by the same fix to another issue. I can't reproduce this anymore.

**Comment by AmberSJones** [comment]
I can confirm this is now functional. I'm closing the issue.
