### ISSUE TITLE
An erroneous "x" appears when adding collaborators

### ISSUE THREAD

**Issue by hydrocheck** [hydroshare/hydroshare#3785]
Open a resource in edit mode.  Add Collaborator, and add a name.  An erroneous "x" appears outside the modal on the left part of the screen.  This appears across multiple browsers and devices.
[Screen Recording 2020-03-09 at 10.33.08 PM.zip](https://github.com/hydroshare/hydroshare/files/4309912/Screen.Recording.2020-03-09.at.10.33.08.PM.zip)

**Comment by cuahsimarko** [comment]
@ndebuhr is this resolved?
