### ISSUE TITLE
Inconsistent File Download

### ISSUE THREAD

**Issue by Castronova** [hydroshare/hydroshare#3791]
I get different files when I download the same file via (1) "Download" and (2) "Download Zipped".

1. https://www.hydroshare.org/resource/8f7c2f0341ef4180b0dbe97f59130756/
2. right click on binder/Dockerfile -> download

```
$ cat Dockerfile

FROM cuahsi/singleuser-base:centos7

USER $NB_UID
```

3. right click on binder/Dockerfile -> download zipped

```
$ cat Dockerfile

FROM cuahsi/parflow-singleuser:3cea3e4200003bbf

# Move HS resource contents into the docker container
COPY --chown=jovyan:users  data /home/jovyan

# Set the working directory
WORKDIR /home/jovyan

```

**Comment by sblack-usu** [comment]
I downloaded in both ways and got the same result
```
FROM cuahsi/parflow-singleuser:3cea3e4200003bbf


# Move HS resource contents into the docker container
COPY --chown=jovyan:users  data /home/jovyan

# Set the working directory
WORKDIR /home/jovyan
```

**Comment by Castronova** [comment]
That's strange, could this be something that my browser is caching?

**Comment by sblack-usu** [comment]
It's possible, browsers do cache links to file downloads.  When I'm testing file downloads I always disable my browser's cache.
