### ISSUE TITLE
Suggestions to improve the presentation of geographic raster resources

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#38]
From testing alpha.hydroshare.org version 1.2.1

Coverage name is unclear
Projection name is not sufficiently specific
Units should use US spelling or draw content from the file
Band and variable names should be improved per the following images

![p5](https://cloud.githubusercontent.com/assets/3456833/5604058/f988a764-9361-11e4-86b9-0bcef8bd59f1.JPG)
![p6](https://cloud.githubusercontent.com/assets/3456833/5604060/09104746-9362-11e4-94de-ef3319bb6a2d.JPG)

**Comment by horsburgh** [comment]
This could be solved with help text on metadata elements that explain what content should go in each field.  I've seen this done a number of ways: making the name of the element a link that goes to a description, hover text that expands with a description (this can get annoying), etc.

For fields that we expect to have a precise definition (e.g., Projection) - we should probably give them a list to choose from rather than expecting them to type it in right.

**Comment by gantian127** [comment]
The "projection" and "unit" information is extracted from the raster file using the GDAL functions.  I will look into the code to see how to get more projection info.

**Comment by dtarb** [comment]
Some of the needed information is in the GDAL metadata stored in GDAL tiff tags, but figuring out how to read it best may be a challenge.

In reading this in TauDEM we referred to.  This may be a place to start looking.
See http://www.awaresystems.be/imaging/tiff/tifftags/private.html.

and specifically 
http://www.awaresystems.be/imaging/tiff/tifftags/geoasciiparamstag.html
http://www.awaresystems.be/imaging/tiff/tifftags/geokeydirectorytag.html 
http://www.awaresystems.be/imaging/tiff/tifftags/gdal_metadata.html 

For the logan DEM (logan.tif) that I used in the testing the UTM zone information is the following
34737 (40 ASCII): UTM Zone 12, Northern Hemisphere|NAD83|

**Comment by hyi** [comment]
Band and variable names have been improved as suggested and the changes are in AGU branch to be merged into develop branch. Coverage name and projection are being investigated by Tian to be more clear.

**Comment by hyi** [comment]
Integrated Tian's fix to raster metadata extraction and added further fixes to other related issues and pushed changes to a new branch; created a pull request to have the new branch merged into develop. Tag it to be ready for testing.

**Comment by dtarb** [comment]
The resource landing page is now missing projection information. It is also missing Place/Area Name.

**Comment by hyi** [comment]
mark this issue as "Fix pushed to github." Now the fix has been merged into develop branch. Once it makes its way into alpha, will mark it as ready for testing.

**Comment by dtarb** [comment]
Tested on development VM.  Closing.
