### ISSUE TITLE
Upgrade to Django 1.7.8 as part of NFIE release

### ISSUE THREAD

**Issue by selimnairb** [hydroshare/hydroshare#380]
We are currently running an early version of 1.7, namely 1.7.1.  There are numerous bug fixes and security updates in 1.7.2 through 1.7.8.  Before exposing HydroShare to more users, it might be worthwhile to upgrade to the latest version of 1.7.  This assumes that we have time and that the benefits outweigh the costs.

**Comment by dtarb** [comment]
I think that you want the benefits to outweigh the costs, and I am rather leery of rolling an additional upgrade into the NFIE deploy.  We have enough on our plate already.

**Comment by ironfroggy** [comment]
It should be pointed out that if you are still running 1.7.1 that could be
the source of at least some of your migration woes. Also, upgrading minor
versions should be safe. These are well tested for backwards compatibility
and contain important security vulnerability fixes. And x.y.1 release
should be considered at least a bit risky, and getting off it should be
done if possible.

On Mon, May 18, 2015 at 5:14 PM, David Tarboton <notifications@github.com>
wrote:

> I think that you want the benefits to outweigh the costs, and I am rather
> leery of rolling an additional upgrade into the NFIE deploy. We have enough
> on our plate already.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hydroshare/hydroshare/issues/380#issuecomment-103213360>
> .
>



-- 


*Calvin Spealman*Lead Front-end Developer

calvin@caktusgroup.com <calvin@caktusgroup.com>
www.caktusgroup.com

**Comment by mjstealey** [comment]
It would be easy enough to stand up one of the VMs using Django v1.7.8 for evaluation purposes.
If all works as expected this can be integrated for the NFIE release.

There will however be some work to do prior to moving to v1.8.x due to deprecated code in our repository that will no longer be part of v1.8.x. These can be seen as warnings anytime you build the project.

**Comment by selimnairb** [comment]
@ironfroggy +1
@mjstealey +1 for holding back on 1.8 until a later date.

**Comment by mjstealey** [comment]
park.hydroshare.org has been rebuilt using Django v1.7.8
branch = develop

Output from `$ pip freeze` for reference:

```sh
Cython==0.20.1post0
Django==1.7.8
Fabric==1.8.0
Fiona==1.0.2
GDAL==1.10.1
Jinja2==2.7.1
Markdown==2.6.2
MarkupSafe==0.23
Mezzanine==3.1.10
Pillow==2.3.0
Pygments==1.6
SPARQLWrapper==1.6.4
Shapely==1.2.18
South==0.8.4
amqp==1.4.0
amqplib==1.0.2
anyjson==0.3.3
argparse==1.2.1
arrow==0.4.2
backports.ssl-match-hostname==3.4.0.2
bagit==1.3.6
beautifulsoup4==4.1.3
billiard==3.3.0.19
bleach==1.4
celery==3.1.13
certifi==0.0.8
chardet==2.0.1
colorama==0.2.5
decorator==3.4.0
django-appconf==0.6
django-autocomplete-light==2.0.9
django-celery==3.1.1
django-crispy-forms==1.4.0
django-debug-toolbar==1.2.2
django-extensions==1.5.0
django-filter==0.9.2
django-inplaceedit==1.3.0
django-jenkins==0.17.0
django-jsonfield==0.9.13
django-nose==1.3
django-picklefield==0.3.1
django-tastypie==0.12.1
django-tastypie-swagger==0.1.2
django-timedeltafield==0.7.0
django-widget-tweaks==1.3
djangorestframework==3.1.1
docker-py==1.0.0
docutils==0.11
ecdsa==0.10
filebrowser-safe==0.3.1
future==0.14.3
geojson==1.0.9
google.foresite-toolkit==1.3
grappelli-safe==0.3.13
gyp==0.1
html5lib==1.0b3
ipython==2.4.1
isodate==0.5.1
kombu==3.0.24
lxml==3.4.2
matplotlib==1.4.3
mimeparse==0.1.3
mock==1.0.1
netCDF4==1.1.1
nose==1.3.4
numexpr==2.4
numpy==1.8.2
oauthlib==0.6.0
pandas==0.15.2
paramiko==1.12.0
protobuf==2.5.0
psycopg2==2.4.5
pyasn1==0.1.7
pycrypto==2.6.1
pyparsing==2.0.1
pyproj==1.9.3
pysqlite==2.6.3
python-dateutil==2.2
python-mimeparse==0.1.4
python-safe==1.1.2
pytz==2013.9
pyzmq==14.1.1
rdflib==4.0.1
readline==6.2.4.1
redis==2.10.3
requests==2.2.1
requests-oauthlib==0.4.2
rsa==3.1.2
scipy==0.13.3
sh==1.09
simplejson==3.3.1
six==1.5.2
sqlparse==0.1.10
ssh==1.8.0
ssh-import-id==3.14
suds-jurko==0.6
tables==3.0.0
tornado==3.1.1
tzlocal==1.0
uWSGI==1.9.20
urllib3==1.5
virtualenv==1.11.4
websocket-client==0.25.0
wheel==0.24.0
wsgiref==0.1.2
```

**Comment by dtarb** [comment]
I also support 1.7.8 since it seems smooth and simple.

**Comment by mjstealey** [comment]
> I also support 1.7.8 since it seems smooth and simple.

The bulk of what is seen in the `$ pip freeze` output gets built into the hs_base image that is referenced as mjstealey/hs_base in our build script. (docker-compose.yml)

The installed Django version is one of these, so it can be distributed to the team via a rebuild and push of a new mjstealey/hs_base image. Then on the next full build cycle they would bring in the updated image on their local environment.

I'll wait for a :+1: in this issue thread before making that change.

**Comment by dtarb** [comment]
You have my :+1:

**Comment by mjstealey** [comment]
Django v1.7.8 replaces v1.7.1 and new hs_base pushed to mjstealey/hs_base on docker hub.

**Comment by dtarb** [comment]
Done
