### ISSUE TITLE
Update HydroShare Legend with content types

### ISSUE THREAD

**Issue by sblack-usu** [hydroshare/hydroshare#3807]
![image](https://user-images.githubusercontent.com/35820390/78600796-da918080-7810-11ea-8872-349f0074f61d.png)
The Legend currently looks like the above,  With the resource migration near completion, the legend is out of date and still shows deprecated resource types.  These icons are still used, but now they are aggregation types.

**Comment by sblack-usu** [comment]
Resulting legend.  I'm keeping it in hydroshare for now, we can move to the help pages if/when we find a place for it in help.
![image](https://user-images.githubusercontent.com/35820390/78839812-701a4500-79b6-11ea-9aa1-12d634e1659e.png)

**Comment by horsburgh** [comment]
@sblack-usu - I'm assuming the work on this is done? If not, do you want to have Mauriel have a look?

**Comment by sblack-usu** [comment]
This is done and part of 1.32 that goes out next week.
