### ISSUE TITLE
Nginx reverse proxies too much

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#3813]
A sanity check of Nginx indicates that it reverse proxies everything that is not static. This creates an enormous load on the Nginx server, which has to cache each request. Everything but /django_irods/download requests should be forward proxied instead.

**Comment by martinseul** [comment]
@alvacouch can this be close?

**Comment by alvacouch** [comment]
@martinseul It isn't really settled. The condition persists. I have not had the time to clean it up.

**Comment by devincowan** [comment]
closing because our cloud deployments dont use nginx
