### ISSUE TITLE
Resource download counter associated with app launching is not working correctly

### ISSUE THREAD

**Issue by horsburgh** [hydroshare/hydroshare#3827]
This issue was reported to me by a HydroShare user some time ago.

Launching content from a HydroShare resource into at least the HydroShare GIS App creates multiple counted downloads in the top metadata section on the resource landing page. Here's how I duplicated this issue:

1. Create a new resource
2. Upload an ESRI shapefile (I did not zip and upload, I uploaded files individually). The shapefile is automatically converted to a geographic feature aggregation.
3. Save the resource.
4. Click on the "Open with" button and select "HydroShare GIS"
5. The HydroShare GIS App is launched. I receive an error dialog in the HydroShare GIS App stating that an unexpected error occurred. The data were not opened.
6. I refresh the landing page for the new resource and the downloads counter has increased by 5.

I'm assuming this is related to the HydroShare GIS App requesting individual files and those being counted individually as downloads? Is that the intended functionality?

@danames - assigning to you first to see what you think about the HydroShare GIS App not opening the content and to see how you think we should be counting the downloads it is doing.

**Comment by Castronova** [comment]
Closing because the GIS app is no longer a CUAHSI verified app.
