### ISSUE TITLE
CZO title builder invasion

### ISSUE THREAD

**Issue by ChristinaB** [hydroshare/hydroshare#3829]
@cuahsimarko   
Please see: 
https://www.hydroshare.org/resource/e23ba824efcd416fa1c10177c6d930c7/
When I go to 'Edit', the title I created against my will is: 
BCCZO -- GIS / Map Data -- SCOPE Sync Testing -- Planet Earth -- (2019-Ongoing)
https://files.slack.com/files-pri/T47U9RK5Z-F012MMGPUKX/image.png
![image](https://user-images.githubusercontent.com/4108369/80500819-81a29d00-8923-11ea-8d4c-2b6bdfcc3ace.png)

**Comment by cuahsimarko** [comment]
@ChristinaB this is perhaps an artifact of the Waterhackweek Community work in progress. I will investigate. In the meantime, can you please continue this interaction via email or HydroShare Slack? You can use right click, I believe and that won't trigger the CZO Community Title Builder.

**Comment by cuahsimarko** [comment]
@ChristinaB You are a member of CZO Luquillo https://www.hydroshare.org/groups . This is a training issue with CZOs and I will follow-up with Martin. All CZO resources are accessible Publicly. Membership of CZO Groups is strictly for CZO data managers. You can simply disjoin CZO Luqillo and the behavior will cease.

**Comment by ChristinaB** [comment]
- [ ]  I am a member of a community (see below).  I also use HydroShare to archive other data resources.  However, If I use one log in to do both, I CAN NOT edit titles of any resource without the CZO titler popping up.    This issue is a usability deal breaker for any user. 

![image](https://user-images.githubusercontent.com/4108369/91084916-86d9d500-e601-11ea-872b-b782672c6eca.png)

- [ ] I don't know how to not be a member of the CZO.   I was added by Miguel Leon (I believe) as part of our RAPID work on the LCZO, because we have hurricane data for the CZO.  And hurricane archive that intersects with a CZO would have this issue. 

- [ ]  The [help page for Communities](https://help.hydroshare.org/participation-and-collaboration/) Is not clear about the current restrictions.  or title  problems.  It does not mention that is currently only one Community possible, and that no one else besides data managers should use them.

I suggest that all documentation and display of communities should be removed if your assumption is that only data managers will be able to be members.    It appears in 'Collaborate' and the help pages as if there Communities is functioning.  However, if only data managers of archives shared in communities are expected to be members, and you expect people to log in with two different emails to use Communities and other HydroShare functions separately, then the  'Communities' documentation is broken.    As is it, else who is a member of the community has their title editing broken for all other resources, this issue breaks all of HydroShare for me and is disrupting my ability to complete work and finish research.   Heading to DesignSafe in 3....2...1.....

**Comment by ChristinaB** [comment]
Once I create a new resource, I can never edit a title.  
![image](https://user-images.githubusercontent.com/4108369/91086341-aa9e1a80-e603-11ea-9daf-13f0dddbd35e.png)

**Comment by ChristinaB** [comment]
@cuahsimarko can you re-open this issue, it doesn't look like I have permissions to do that.

**Comment by horsburgh** [comment]
I agree with @ChristinaB that this needs to be revisited. A HydroShare user should be able to join a group or a community without being forced into custom functionality.
