### ISSUE TITLE
Add all required fields to the Account Creation page

### ISSUE THREAD

**Issue by Castronova** [hydroshare/hydroshare#3838]
Currently users are asked for the following fields when creating an account:

- first name
- last name
- username
- email
- organization

The following required fields are not included:
- user type
- country
- state/province

These three fields should be included in the Account Creation form.

This ticket breaks out the account creation implementation outlined in #3812

**Comment by Castronova** [comment]
@jtpollak We should also include any other fields that we plan to use for NSF reporting, e.g. Subject Areas.

**Comment by jtpollak** [comment]
@Castronova I don't think we need Subject Area - just User Type.

**Comment by sblack-usu** [comment]
@hyi - please verify this on production and close the issue.

**Comment by hyi** [comment]
Thanks for closing this issue @Castronova. @sblack-usu I did test this out and verified everything works as expected on production.
