### ISSUE TITLE
Unable to manually update spatial metadata

### ISSUE THREAD

**Issue by 12nad1** [hydroshare/hydroshare#3854]
After manually entering Longitude and Latitude box coordinates, and pressing Save Changes, the error: "Error! Metadata failed to update." appears.

**Comment by sblack-usu** [comment]
@12nad1 - sorry for the late response.  I need some more details about your issue in order to debug it.  Could you send me the resource id (or just the link to the resource landing page)?

**Comment by 12nad1** [comment]
Not sure what was going wrong when I originally posted the error, but I tried again and it seemed to work, so perhaps there is no issue, so I guess I'll close this thread. Sorry about that, and thanks.
