### ISSUE TITLE
Make Haystack return efficient JSON

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#3861]
To enable the new clientside discovery system, make the Haystack/SOLR system return specific JSON documents that the clientside library can parse and manipulate. These should contain exactly the fields that the discovery interface manipulates now, but in JSON format.

**Comment by martinseul** [comment]
@alvacouch Did you do work on this? As I understand there is no immediate  requirement for this if you did work on it do you need Dan to work on the Devops?

**Comment by cuahsimarko** [comment]
This is handled by the new endpoint created for new Discover. When Neal is closing bulk tickets for Release 1.38, this can be among those closed.

**Comment by hydrocheck** [comment]
> This is handled by the new endpoint created for new Discover. When Neal is closing bulk tickets for Release 1.38, this can be among those closed.
