### ISSUE TITLE
Corrupt resource for new DOI version title

### ISSUE THREAD

**Issue by ChristinaB** [hydroshare/hydroshare#3866]
Data in Brief journal article [Nooksack](https://www.sciencedirect.com/science/article/pii/S2352340920304728)  - this has a hydroshare URL with a missing title.   This resource updates and replaces previous version:http://www.hydroshare.org/resource/2d9787bf36d04c9383e595d179f9298b  The previous version has a DOI required by journal at submission, because no new changes resulting from the review process could be added, a new version was created. This is ‘owned’ by a government organization and the only follow up process that is known, is for someone on the HydroShare team to investigate (me). 

- [ ] title is not rendering

- [ ] DOI versioning instructions are needed for journal publication workflows. 

- [ ]  Is there a readme for users who are not in the team and how they should handle bugs ?

**Comment by sblack-usu** [comment]
It looks like this would happen anytime there is a ResourceFile in django that doesn't exist in iRODS.  I'd wager the file was deleted with a lot more files (deleting the 2016 folder), it took a long time and the request either timed out or the user gave up.  This is something that would be resolved by the async file manipulations.
I need to think about the best way to handle this while async file manipulations is being worked on.  We could handle corrupt data like this better during the generation of the landing page.  But ultimately that is just a bandaid while we wait for the fix that prevents the corruption of the resource.

**Comment by dtarb** [comment]
@sblack-usu prior to composite resources the repair resource script could fix these issues.  I know you are working on these for composite.

@ChristinaB with respect to versioning instructions and DOI's for publications see https://help.hydroshare.org/creating-and-managing-resources/connecting-your-resource-data-with-your-publication/.  I know it is awkward See #2559.  I've been discussing with @horsburgh ways to make this better.

With respect to bugs the footer of every HydroShare page has the support email and report bug links.  Now I know people often do not look at footers, so ideas to better message folks to reach out to help@cuahsi.org are welcome

**Comment by sblack-usu** [comment]
yes, I was running repair_resource on beta on the resource when you sent your message.  This resource is now fixed on beta. https://beta.hydroshare.org/resource/222e832d3df24dea9bae9bbeb6f4219d/

Unfortuantely the repair_resource script is in disrepair and the version running on production won't work.  I could expedite a review/release to fix the repair_resource script if fixing this resource quickly is necessary.  Please let me know.

**Comment by horsburgh** [comment]
I also noticed that the README.md file is not rendering on the newer version of the resource.

@ChristinaB - you list a citation in your README.md file that is going to be different than the citation on the resource landing page when that resource is published. Do you need to include the citation in the readme file given that it is prominently displayed on the landing page? Also, you list that that the resource was derived from a release of the ODM2 YODA-file repository in GitHub. Is that actually correct? Finally, I'm confused by the relationship to the resource in Zenodo you have included as a related resource. You say that the hydroshare resource serves as the data for the Zenodo resource. What is the difference between the two?

**Comment by sblack-usu** [comment]
Great observation @horsburgh.  I can now confirm that creating a new version of a resource causes the README display bug.  We have a fix for the README display that ready for the next release already, but now I know at least one condition that makes the db change to cause the README display bug.  Creating a new version of a resource sets the file_folder of root resource files to an empty string rather than None.

**Comment by martinseul** [comment]
@sblack-usu can this be closed

**Comment by sblack-usu** [comment]
There are other questions that @ChristinaB asks that have not been addressed yet.  I can answer the one about users reporting bugs, there is a link at the bottom of every page on hydroshare to report bugs.  I don't know about the DOI versioning workflows.

**Comment by martinseul** [comment]
@sblack-usu closing this, I created a separate issue for the DOI workflow question https://github.com/hydroshare/hydroshare/issues/3905
