### ISSUE TITLE
HSAPI returns non-published resource when filtering on "published"

### ISSUE THREAD

**Issue by Castronova** [hydroshare/hydroshare#3868]
I noticed when running the metrics scripts that 5 resources returned that did not have a  `published date` attribute. This should not happen since I was using the hsapi to query resources that HAVE been published. I'm wondering if something happened to these resources that would make HS think they're published when they aren't. Maybe they were accidentally published and reverted back by CUAHSI staff? @martinseul Do you have a list of all HS resources that were accidentally published?

@sblack-usu, I assigned this to you because of your in-depth knowledge of HS's REST API. Please re-assign if necessary.

To reproduce the error:

```
import pandas
import hs_restclient as hsapi
hs = hsapi.HydroShare()

resources = hs.resources(published=True)
published = list(resources)
df = pandas.DataFrame(published)

df_false = df[df.published == False]

for idx, res in df_false.iterrows():
    print(res.resource_url)
```

```
http://www.hydroshare.org/resource/885906ef97e542a8a33048ea486ddfdf/
http://www.hydroshare.org/resource/466d5b3de8a543808d96ded08d861dc5/
http://www.hydroshare.org/resource/2a6612a47f1f40098befc303a3618fe5/
http://www.hydroshare.org/resource/32faa35c14d140d3b05b43d86e8d853a/
http://www.hydroshare.org/resource/d2d2aa2b02d94f10bde859aa2584a423/
```

**Comment by sblack-usu** [comment]
This endpoint determines a resource is published if a DOI is present.  These 5 resources are showing non-null DOIs.  4 of them are empty strings and one is a pending DOI

**Comment by Castronova** [comment]
@martinseul Can you please look into the status of these 5 resources?

**Comment by sblack-usu** [comment]
I'll update the endpoint to use raccess.published instead of the doi.  Also looking at improving it's performance.

**Comment by martinseul** [comment]
I did check in our crossref portal and neither of these resources is actually published, there are no records for these potential doi's 
10.4211/hs.32faa35c14d140d3b05b43d86e8d853a
10.4211/hs.2a6612a47f1f40098befc303a3618fe5
10.4211/hs.466d5b3de8a543808d96ded08d861dc5
10.4211/hs.885906ef97e542a8a33048ea486ddfdf
10.4211/hs.d2d2aa2b02d94f10bde859aa2584a423
