### ISSUE TITLE
Redirect subdomains other than www on port 443

### ISSUE THREAD

**Issue by cbcunc** [hydroshare/hydroshare#3887]
nginx1.hydroshare.org was the original hostname for www.hydroshare.org (currently 152.54.2.89).

Currently, nginx config on www rewrites all subdomains resolving to the IP to www *for port 80*:

> server {
>     listen          80;
>     server_name     www.hydroshare.org;
>     rewrite ^/(.*)  https://www.hydroshare.org/$1 permanent;
> }

so that someone visiting **http**://nginx1.hydroshare.org will be rerouted to **https**://www.hydroshare.org.

However, if someone explicity visits www via *port 443*, then the rewrite does not occur, so that https://nginx1.hydroshare.org will be served without rewrite (as will https://152.54.2.89, which results in a security warning to the user).

We need to block access on port 443 to all but www.hydroshare.org in order to confine search results to www only. Currently nginx1 is included in third party search results. The subdomain nginx1 is still required for several non-http processes.

More that one approach exists.

1) The SEO friendly approach is to *conditionally* rewrite https in the nginx conf server block for https:

> if ($http_host != "www.hydroshare.org") {
>     rewrite ^ https://www.hydroshare.org$request_uri permanent;
> }

or

> if ($http_host != "www.hydroshare.org") {
>     rewrite ^/(.*)  https://www.hydroshare.org/$1 permanent;
> }

2) Or simply deny any explicit access to port 443 which is not for www with an additional server block:

> server {
>     listen 443 default_server;
>     server_name _;
>     deny all;
> }

Discuss.

**Comment by cbcunc** [comment]
After the weekly developers' call discussion and taking advice from https://www.nginx.com/resources/wiki/start/topics/tutorials/config_pitfalls/?highlight=rewrite#taxing-rewrites, we should do the following in both the http and https server blocks:

> if ($http_host != "www.hydroshare.org") {
>     rreturn 301 https://www.hydroshare.org$request_uri;
> }

**Comment by martinseul** [comment]
@cbcunc can we close this?

**Comment by cbcunc** [comment]
@Martin, not yet. We had to revert PR #3894. It interfered with bag download.

**Comment by cbcunc** [comment]
Fixed in #3906 and deployed in [1.35](https://github.com/hydroshare/hydroshare/releases/tag/1.35)
