### ISSUE TITLE
Prevent permanently published resource from becoming editable when new version is deleted

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#3888]
If a new version of a permanently published resource is created and then the new version deleted the original resource becomes editable though it remains permanently published.  Permanently published resources should never be editable. 

I noticed this when testing versioning functionality on https://doi.org/10.4211/hs.84c5d397abd1441a9764fdf071fbe6d2.  When I initially went to https://doi.org/10.4211/hs.84c5d397abd1441a9764fdf071fbe6d2 it was not editable as it is permanently published.  I created a new version to see how the is replaced by and is version of relations worked.  I then deleted the new version of the resource (which was not published and I had never intended to keep beyond my testing).  The old published version is now editable.  This is a bug as it provides a mechanism for users to edit permanently published resources.

**Comment by sblack-usu** [comment]
@dtarb - could you verify this in production and close the issue when you have a chance.  I verified it in beta but must have a published resource to test.

**Comment by dtarb** [comment]
@sblack-usu Only half done.  I made a new version of the resource https://doi.org/10.4211/hs.5d1356789c0c4f35addbe7dcddf12517

Then I deleted the new version.  The current version is not editable, so the problem is no longer introduced.  

However the existing resource https://www.hydroshare.org/resource/84c5d397abd1441a9764fdf071fbe6d2/ is still editable (I changed a keyword to determine this).

**Comment by hyi** [comment]
@dtarb Good point. @sblack-usu I think this remaining issue can be easily resolved by looping through all published resources and set its immutable access flag to be True if it is not True already. I think this is a one time thing and likely only this one published resource from Dave needs to be fixed, so I'll vote not to create a management command just for fixing this, but do it from Django shell. Let me know if you can take care of this. I can help out with this if needed as well.

**Comment by hyi** [comment]
@dtarb I fixed this existing published resource on production by setting its immutable access attribute to True while looking at another resource trying to figure out this issue #3899. I probably should not directly do it on production, but since it was non-disruptive, I convinced myself just to go ahead with it. I hope it was OK for this simple case, although I know this is not recommended. In any case, please test it out to verify if this existing resource is fixed.

**Comment by sblack-usu** [comment]
sorry, forgot to leave a reply.  I was going to suggest just taking care of it manually, I'm ok with your approach for something like this.

**Comment by dtarb** [comment]
@hyi thanks for fixing this.  I am OK with your approach.  It appears to be correct, so I will close.  

With respect to your "probably should not directly do it on production", I have to, and do, trust you to work in a careful, disciplined and safe way.  If a change like this in production is in your judgment the best solution, then do it.  I do not know enough to say yes or no.  Some things to bear in mind
- if you break it you fix it (and for this reason do not do at 4:55 pm on a Friday).  
- if it is possible to test it on beta first, then test it.
