### ISSUE TITLE
Extra precautions to confirm a user intends to delete a resource

### ISSUE THREAD

**Issue by sblack-usu** [hydroshare/hydroshare#3890]
The last month I've had two support issues investigating a missing resource only to discover the user had unknowingly deleted their resource.

This is up for discussion if others would like to voice opinions and what measures should be taken.  I think we should simply add a textbox that forces the user to type in DELETE before clicking the ok button when deleting a resource. This should be updated both on the resource landing page as well as the my-resources page (for bulk delete).

**Comment by horsburgh** [comment]
I know this happens - as I think it happened to one of my students. However, I'm not sure what can be done to improve the dialogs that pop up. If you click the trash can icon on the resource landing page to delete the resource, you get this:

![image](https://user-images.githubusercontent.com/3485902/84806895-a3371100-afc3-11ea-96b6-1b31c04828c6.png)

If you select the resource on the My Resources page and then click the trash can icon, you get this:

![image](https://user-images.githubusercontent.com/3485902/84806960-bf3ab280-afc3-11ea-9e64-e746c677de1a.png)

It seems like the messaging is pretty clear, so I'm not sure how people are missing this. I've used other systems that have multiple dialogs that pop up, with the second one being the "Are you sure you are sure?" dialog. I'm not sure about asking the user to type in "DELETE".

**Comment by sblack-usu** [comment]
I suggested typing DELETE or something to make sure the user reads the warning before pressing confirm.  I think it may be similar enough to deleting a file that people just click confirm without realizing they pressed the wrong button.  The 2 recent examples where a user accidentally deleted their resources were done while the users were heavily modifying their resources.  

There is precedence to forcing a user to type when permanently deleting something, Github and other services have this practice.

**Comment by horsburgh** [comment]
Looking at other options for design here, your suggestion of typing "DELETE" seems to be pretty universally recognized and would be the simplest to implement of any of the other options I saw (e.g., creating a recoverable trash folder, creating undo functionality, hiding rather than deleting content, etc.). I could get behind this.

**Comment by amabdallah** [comment]
I was about to post a new issue but luckily found this one. We live in a forgiving virtual environment where they're always ways to "recover" deleted files at least for a period of time. It's like a standard these days. So users expect this from HydroShare as well. I just deleted a resource that had a nice abstract. I wish I could recover it to copy that abstract :(

![image](https://user-images.githubusercontent.com/3268971/103491296-bb477400-4ddf-11eb-9b85-e91b03513ad2.png)

**Comment by sblack-usu** [comment]
After receiving another support issue about an accidentally deleted resource, I decided to get the ball moving on this issue again.  I've updated the Confirm button to be disabled unless a user types "DELETE" into the new textbox.  I would like help with messaging and formatting, if @horsburgh or someone else can give me some guidance on what the new confirmation box should say, I can make the changes in the HTML and we can get this completed.
<img width="594" alt="image" src="https://user-images.githubusercontent.com/35820390/128718330-dfaa0e00-3e91-4d4f-b213-942cb791244d.png">

The other suggestion of a soft delete requires more discussion.

**Comment by horsburgh** [comment]
I would like to see the following text messaging on this form:

> WARNING! DELETING A RESOURCE IS A PERMANENT ACTION!
> * This will delete the resource and all of the content files.
> * A copy of the resource will *NOT* be retained by HydroShare.
> * We highly recommend that you download the latest copy of your resource before confirming this action so that you do not lose any content you might need later.
> 
> If you are sure you want to delete your resource, type the word "DELETE" in the following text box and then click the "Delete" button below.

Move the "DELETE" text box down below the text.

**Comment by horsburgh** [comment]
@sblack-usu - don't forget that we have delete capability on the resource landing page, but also the bulk resource delete on the My Resources page. Messaging and styling should be consistent across both dialogs.

**Comment by sblack-usu** [comment]
@horsburgh - would you like the messaging to be different on the my-resources page?

**Comment by sblack-usu** [comment]
I updated the messaging for my-resources a bit.  These changes are deployed to beta, please check it out and give me any messaging/styling or functional updates.

**Comment by horsburgh** [comment]
I just checked this on beta.  I suggest the following text for the bulk delete from the My Resources Page:

> WARNING! DELETING RESOURCES IS A PERMANENT ACTION!
> * This will delete any resources you have selected and their content files.
> * HydroShare will not retain copies of your resources or content files.
> * We highly recommend that you download the latest copy of your resources before confirming this action so that you do not lose any content you might need later.
>
> If you are sure you want to delete the selected resources, type the word "DELETE" in the following text box and then click the "Delete" button below.
