### ISSUE TITLE
JSONLD has endline in fields.

### ISSUE THREAD

**Issue by valentinedwv** [hydroshare/hydroshare#3899]
https://www.hydroshare.org/resource/615d426f70cc4346875c725b4b8fdc59/

Identifier fields have a carriage return in the values. Breaks transformation from json.
 ```
           "identifier": "md5:
31954804b4fee50715c79078c4af1bbb",
            "propertyID": "MD5",
            "value": "
31954804b4fee50715c79078c4af1bbb"
```

**Comment by martinseul** [comment]
@hyi would you be able to look into this it should be a quick fix to the work you put on with schema.org?

**Comment by hyi** [comment]
@valentinedwv I have verified that this issue has been fixed. Could you please verify as well and close the issue if it is fixed?

**Comment by hyi** [comment]
@valentinedwv I am closing this issue since both @horsburgh and I have verified this issue, but feel free to reopen if otherwise.
