### ISSUE TITLE
Summa-Camels Data Resource Bugs and Coordination

### ISSUE THREAD

**Issue by ChristinaB** [hydroshare/hydroshare#3907]
![image](https://user-images.githubusercontent.com/4108369/86275137-ac111080-bb87-11ea-969d-d69b48d552b8.png)

Here is an error that is not clear for users.

**Comment by ChristinaB** [comment]
This data is needed for netcdf files before we are able to make the resource public. 
![image](https://user-images.githubusercontent.com/4108369/86275282-e1b5f980-bb87-11ea-967c-34f7c8e46ff3.png)

**Comment by sblack-usu** [comment]
We're aware of this issue when uploading many files.  The 504 is due to timing out when processing all of the files.  You can watch this issue to see updates of where we are at with handling this situation better. https://github.com/hydroshare/hydroshare/issues/3852

**Comment by ChristinaB** [comment]
https://help.hydroshare.org/hydroshare-resources/content-types/multidimensional/ 
While any NetCDF file can be used in HydroShare, we encourage use of [Climate and Forecast (CF)](http://cfconventions.org/) and [ESIP Attribute Convention for Data Discovery 1-3 (ACDD)](http://wiki.esipfed.org/index.php/Attribute_Convention_for_Data_Discovery_1-3) conventions. HydroShare matches metadata from the header file with CF and ACDD convention tags to identify and populate content level and resource level metadata (see terms). When a NetCDF file with author, keyword, spatial and temporal reference, and other matched metadata is imported to HydroShare, there is no need for the user to enter this metadata as it will be extracted automatically.

**Comment by ChristinaB** [comment]
@gantian127 is this the paper with the netcdf details? https://www.sciencedirect.com/science/article/abs/pii/S1364815219311661

**Comment by gantian127** [comment]
@ChristinaB That is not the paper for the netCDF details. Please check this one: https://doi.org/10.1016/j.envsoft.2020.104706. Thank you.

**Comment by ChristinaB** [comment]
- [ ] move over data -- https://www.hydroshare.org/resource/b4c7120f38e843c8bdfc137ea1609989/

- [ ] add netcdf detailed info - https://doi.org/10.1016/j.envsoft.2020.104706   - do we NEED a geospatial reference on every netcdf.  does this have to be used.  NOAA & NASA netcdf - do they have it? 

- [ ] talk to @Castronova  about installing hstools on Cheyenne so I can move it to https://www.hydroshare.org/resource/b4c7120f38e843c8bdfc137ea1609989/

- [ ] collaboration hygiene planning

- [ ] irods instructions from @hyi

**Comment by ChristinaB** [comment]
@gantian127 there may be an issue with requiring spatial resolution to make a resource public.  If the netcdf is only lat/long degrees, the spatial resolution may not be included.   

Also, great paper! do you have any other resources with tutorial or how to materials? I need to edit this Notebook so that the netcdf files output are in the correct format for HS resources so we can make use of  your cool features.

**Comment by ChristinaB** [comment]
@sblack-usu  @martinseul   This resource [CAMELS SUMMA Dataset - Preliminary Cheyenne Migration](https://www.hydroshare.org/resource/b4c7120f38e843c8bdfc137ea1609989/) still has a weird title editing error from the glitch related to the CZO title for resources or is it related to any resource created by CZO resource owners?

**Comment by ChristinaB** [comment]
@hyi how do I get a new irods password?  the password I expected is not working when I try to log in to irods from this CAMELS resource, and we need to upload 2G of climate data. I would prefer have the Notebooks run on Cheyenne (or any HPC) to send data directly to iRods...is this an option? Are there other existing examples?

**Comment by hyi** [comment]
@ChristinaB Here is the instruction: https://help.hydroshare.org/creating-and-managing-resources/how-can-i-reset-or-change-my-irods-password/ I can reset your iRODS password for you if you let me know your username (we can touch base offline). Yes, sending data directly to iRODS from the Notebooks running on any HPC should be an option if icommands is installed on the Notebook server. I believe @Castronova has Jupyter notebook examples to show how to do that. If not, I can send you example commands to show you how to do that.

**Comment by gantian127** [comment]
@ChristinaB A public resource requires spatial coverage (bounding box) and the spatial reference of the netCDF data. Here is an example NetCDF file that works well with HydroShare metadata functions https://www.hydroshare.org/resource/deb0250d446441fd886a2e288b5a8a90/. But there is no specific how to tutorial. 

For spatial coverage, one way to provide this information is to add global attributes in the NetCDF file by following the ACDD convention, which includes geospatial_lat_max, geospatial_lat_min, geospatial_lon_max, geospatial_lon_min. For spatial reference, it needs to define a grid mapping variable with attributes by following the CF convention (In the example NetCDF file, the grid mapping variable is "polar_stereographic"). Details for the attributes and the variable can be found from the file metadata ("NetCDF Header Information") of the example NetCDF. Thank you!

**Comment by ChristinaB** [comment]
@gantian127  this is a good almost tutorial 
for building a template https://github.com/gantian127/ueb-analysis/blob/bd716ac9062c18e07a788d7301a0ad31fd3cf64e/xmrg_to_netcdf_3.py    but I'll update it for netcdf4 and need to add the WGS for Summa or any latlong degree coordinates
@Castronova @AmberSJones what do the current instructions look like?

**Comment by eclark-cuahsi** [comment]
@sblack-usu can you please verify with @alvacouch if this is still an issue that needs to be addressed?

**Comment by sblack-usu** [comment]
The 504 timeout issue can still occur if a user uploads several files at once, especially if there is a lot of extra processing required from extracting metadata.  There are other issues discussed here that seem to be more about building the resource than the HydroShare application.

Large file upload could limit the potential for the 504 timeout, but we could also implement some lower hanging fruit to avoid this error.  
1. We can limit the number of files that can be uploaded simultaneously
2. We can suggest the user uploads a zip of the files and then unzips the file on HydroShare

**Comment by eclark-cuahsi** [comment]
@sblack-usu thanks for the quick review. Should this be classified as a bug or an enhancement?

**Comment by dtarb** [comment]
The netcdf coverage issue has been addressed (with issue # 4592 and pr #4619).  The other points in this thread are stale or difficult to act on so closing this.  If there are specific items that need attention, please open a new issue about them.
