### ISSUE TITLE
HydroShare content is low width on wide monitors, with a lot of whitespace on the sides

### ISSUE THREAD

**Issue by hydrocheck** [hydroshare/hydroshare#3916]
On a 2880x1800 display, 31% of the window is unused.  On a 4k display, a full 72% of the display is unused.
<img width="829" alt="2" src="https://user-images.githubusercontent.com/43424907/87367167-42f6a900-c548-11ea-8e14-bf51c5a2e7b9.png">

**Comment by cuahsimarko** [comment]
Submitted comments via email to Martin for Neal to confirm.

**Comment by cuahsimarko** [comment]
This is Discover on 2650 x 1140
![image](https://user-images.githubusercontent.com/45397838/105758212-ffc8ba00-5f1c-11eb-9f04-6c6705c5233a.png)

**Comment by cuahsimarko** [comment]
Appears to be same width on sides as Resource Landing Page
![image](https://user-images.githubusercontent.com/45397838/105758332-2129a600-5f1d-11eb-9481-89bceb3279e4.png)

**Comment by cuahsimarko** [comment]
@hydrocheck what do you have in mind here? Is this perhaps not an issue with Discover and could be tagged somewhere else, as it may apply across all of HydroShare and be part of another responsive design thread I am navigating with Jeff and Tony. Let me know.

**Comment by hydrocheck** [comment]
@cuahsimarko 
> Is this perhaps not an issue with Discover and could be tagged somewhere else, as it may apply across all of HydroShare and be part of another responsive design thread I am navigating with Jeff and Tony. Let me know.
Agreed.  I have nothing more in mind.

**Comment by cuahsimarko** [comment]
The requirements for mobile phones, tables, ultra-wide monitors, old square monitors should be split into use cases and manufacturers/models, and rough priority assigned to which use cases will be handled. Then a comprehensive responsive design can be applied to HydroShare, its modals and perhaps shared with the other App developers, such as JupyterHub.

**Comment by hydrocheck** [comment]
Closing with https://github.com/hydroshare/hydroshare/issues/4527
