### ISSUE TITLE
The Discover page uses inconsistent capitalization for controlled vocabulary in filters

### ISSUE THREAD

**Issue by hydrocheck** [hydroshare/hydroshare#3918]
Using title case in the pattern for everything except availability.

<img width="288" alt="7-1" src="https://user-images.githubusercontent.com/43424907/87367404-dcbe5600-c548-11ea-8c6b-388ac19c8435.png">
<img width="287" alt="7-2" src="https://user-images.githubusercontent.com/43424907/87367405-dd56ec80-c548-11ea-957b-5bcf5be6642d.png">

**Comment by cuahsimarko** [comment]
This is how items were displayed in old Discover and also how they are stored in the database, but I agree they should be Cased
