### ISSUE TITLE
Inconsistent collapse/expand icons in Discover

### ISSUE THREAD

**Issue by hydrocheck** [hydroshare/hydroshare#3919]
The legend uses a different collapse/expand icon than the filters, which creates unnecessary inconsistency and more for the users to interpret/understand.  The legend icon, and not the filter icons, appears to be the atypical/unintuitive of the two cases.
<img width="1202" alt="9" src="https://user-images.githubusercontent.com/43424907/87367543-49d1eb80-c549-11ea-9b42-a11a19539809.png">

**Comment by cuahsimarko** [comment]
This uses the legend shared around all of HydroShare, but Discover can diverge for now.
