### ISSUE TITLE
The access information is labeled "Type" in the Discover table

### ISSUE THREAD

**Issue by hydrocheck** [hydroshare/hydroshare#3920]
"Type" does not seem like an accurate table header for the access icons (availability and sharable).  A separate "Access" header column may improve understanding.
<img width="934" alt="10" src="https://user-images.githubusercontent.com/43424907/87367627-81409800-c549-11ea-870e-43f995f541ee.png">

**Comment by cuahsimarko** [comment]
Are we removing these icons/this column?

**Comment by cuahsimarko** [comment]
Remove word Type.
