### ISSUE TITLE
Inconsistent capitalization of legend categories in Discover

### ISSUE THREAD

**Issue by hydrocheck** [hydroshare/hydroshare#3926]
The legend categories are not consistently capitalized.  Consider changing "Sharing and Access" to "Sharing and access".
<img width="868" alt="17" src="https://user-images.githubusercontent.com/43424907/87368111-ba2d3c80-c54a-11ea-8ffc-b7f6178f937e.png">

**Comment by cuahsimarko** [comment]
Title case should be used for Content Types and Resource Types

**Comment by cuahsimarko** [comment]
Someone please vote with tiebreaker or @ndebuhr share your opinion

**Comment by cuahsimarko** [comment]
Going with Title Case
