### ISSUE TITLE
Casing for Legend

### ISSUE THREAD

**Issue by cuahsimarko** [hydroshare/hydroshare#3934]
Legend text should be Title Case for Not Shareable and Pending Publication
![image](https://user-images.githubusercontent.com/45397838/88333417-36b7dc00-ccfe-11ea-84fe-0529b9be0958.png)

**Comment by cuahsimarko** [comment]
Review Legend for missing icons, such as HIS-related and Scripting

**Comment by cuahsimarko** [comment]
Legend header should have FA icons for min/max and the anchor styling should be text-decorated none see new Discover for best practices

**Comment by hydrocheck** [comment]
Issue resolved as a part of the Discover redesign
