### ISSUE TITLE
Tool tip on "Manage access" doesn't indicate that one changes public/discoverable/private status there/

### ISSUE THREAD

**Issue by rphooper** [hydroshare/hydroshare#3938]
Tip indicates that this is for sharing with specific people (as icon indicates). Not clear that this is where one changes private resource to public.

**Comment by dtarb** [comment]
I suggest the Tool Tip text be changed to

> Use this button to share your resource with specific HydroShare users or set its sharing status (Public, Discoverable, Private, Shareable). You can give other users the ability to view or edit this resource. You can also add additional owners who will have full permissions.

Current tool tip text
![image](https://user-images.githubusercontent.com/3456833/89123337-c9d5dc00-d48b-11ea-9534-0b87247908d8.png)

I also suggest the blue text at the top of the Manage Access window be expanded to

> Use this window to share your resource with specific HydroShare users or set its sharing status (Public, Discoverable, Private, Shareable). You can give other users the ability to view or edit this resource. You can also add additional owners who will have full permissions. ...

Current information text at the top is
![image](https://user-images.githubusercontent.com/3456833/89123371-115c6800-d48c-11ea-8616-62bf0553a33d.png)

**Comment by cuahsimarko** [comment]
@pkdash can this be closed?

**Comment by pkdash** [comment]
@cuahsimarko This should be closed.
