### ISSUE TITLE
Maps clouded by Region rendering

### ISSUE THREAD

**Issue by cuahsimarko** [hydroshare/hydroshare#3945]
Maps could use some attention

- Maps are sluggish and become generally unusable after a few scrolls/UI actions
- Rendering of region could be re-imagined
- Integration of table resource view and google maps viewport could be improved
- maintaining code for separate resource listings in list tab vs map tap is undesirable (extra credit for reusable component for resource listings across all of HydroShare)
- Map loading experience/reactivity could be improved
- z-index and conflict between region and cluster/marker clicks leads to unusable situations

**Comment by dtarb** [comment]
I appreciate this new focus on Discover maps.  See #1361 and #1755 for prior ideas on this.  In particular in https://github.com/hydroshare/hydroshare/issues/1755#issuecomment-274372087 I generated quite a long list of suggestions for improving the map aspects of Discover that may be helpful as you re-imagine this.

**Comment by hydrocheck** [comment]
Issue resolved as a part of the Discover redesign
