### ISSUE TITLE
Clarify Shareable functionality on the interface

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#3946]
The text in the Manage Access panel below the Shareable check box should be changed to

> - Check the box to let others who have access to this resource be able to share it with others at the same permission level (Edit or View) and enable adding to Collections.
> - Uncheck the box to prevent others from sharing the resource without the owner’s permission, or from adding the resource to Collections before the resource is made Discoverable or Public.

![image](https://user-images.githubusercontent.com/3456833/89123510-2d143e00-d48d-11ea-9590-1a3619e08428.png)

**Comment by martinseul** [comment]
released in 1.36
