### ISSUE TITLE
resource.metadata.update doesn't work properly

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#3949]
Max and I tried to use this function to test "export to dataverse" functionality and found that: 
1. The documentation on how to use it is incorrect. 
2. Updates of selected fields -- notably creator -- silently fail to do anything.

**Comment by martinseul** [comment]
@alvacouch is this ticket still relevant or can it be closed?

**Comment by alvacouch** [comment]
To my knowledge this has not been addressed.

**Comment by devincowan** [comment]
When we talk about the "documentation" for this function I'm not sure if we mean anything beyond some basic docstrings?
https://github.com/hydroshare/hydroshare/blob/1.61/hs_core/models.py#L409
maybe I'm unaware of someplace else that documentation would live.

Alva mentioned that things were particularly flawed when attempting to update Creators
https://github.com/hydroshare/hydroshare/blob/1.61/hs_core/models.py#L584
I will take a look at our tests to see if we can add more coverage. If I get tests to fail, I will fix the `update()` implementation for those cases.

**Comment by devincowan** [comment]
I added some tests (https://github.com/hydroshare/hydroshare/commit/13dc58bcb39a94d93d0851f46cfd224e55c17a88) and did not find failures. Once build for those tests passes, I plan to close this issue. Perhaps problems with `resource.metadata.update()` were resolved some time since Aug 2020.
