### ISSUE TITLE
gunicorn configuration needs to be updated to support https streaming

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#3953]
@sblack-usu @martinseul @dtarb I tried to implement https streaming of SOLR results in django to avoid unneeded buffering in local memory or files, and discovered that our gunicorn configuration doesn't support that. Further, **we are incurring an unnecessary store-and-forward delay on every gunicorn transaction** due to NGINX proxy buffering, so that django streaming doesn't give any performance improvement due to the way gunicorn is set up. 

The purpose of proxy buffering is to keep django from getting held up doing tcp to slow clients and/or over slow internet connections. Instead, NGINX manages those TCP transactions. So we can't just turn this off, **we need to replace it with something.** 

Solution is to turn proxy_buffering off in NGINX, and at the same time switch gunicorn to running in multi-threaded mode to do the same thing as proxy buffering. The gunicorn "threads" interact with slow clients. This will support classical https streaming from Django itself. Right now, we only have streaming from NGINX via reverse proxy.  

Further, some of the current gunicorn configuration -- including a read timeout of 5 minutes -- is ridiculous. When a request stays open in django and wedges, gunicorn takes an incredibly long time to recover.

**Comment by alvacouch** [comment]
There are whole books on configuring this.
See [how does django streaming work?](https://andrewbrookins.com/django/how-does-djangos-streaminghttpresponse-work-exactly/) for an initial introduction to what streaming does.
See  [gunicorn concurrency](https://medium.com/building-the-system/gunicorn-3-means-of-concurrency-efbb547674b7) for the role of threads and pseudo-threads in gunicorn execution.  See particularly the entry on gevent pseudo-threads which solves our hammering problems.

**Comment by alvacouch** [comment]
The magic configuration change seems to be: 
```gunicorn --worker-class=gevent --worker-connections=1000```
which moves caching into gevent pseudo-threads at 1000 threads per worker, doing pretty much the same thing as NGINX `proxy_buffering on` for our configuration. 

What this means is that a gevent worker will work on up to 1000 slow client messages at the same time, timesharing between them, to in essence "buffer" the TCP streams.

**Comment by alvacouch** [comment]
Note also that this change works in both request and response directions and enables streaming *requests* direct to Django as well.  I doubt I can make large-file-download faster via this mechanism, but it's worth considering for large-file upload!

**Comment by sblack-usu** [comment]
Can we test this out on beta and maybe have @ndebuhr test it out with selenium?

**Comment by alvacouch** [comment]
@sblack-usu I will write up a separate PR today that makes the changes I recommend and we can mess with it on beta.

**Comment by alvacouch** [comment]
This has been addressed.
