### ISSUE TITLE
JupyterHub Featured App - OAuth State Missing from Cookies

### ISSUE THREAD

**Issue by Castronova** [hydroshare/hydroshare#3959]
Launching CUAHSI JupyterHub from the "Featured Apps" portion of the dashboard page results in the following error: 

![image](https://user-images.githubusercontent.com/4822372/90155661-93d10b80-dd59-11ea-8f5d-ddd148ac2529.png)

I believe this is because the OAuth handshake is occurring before the redirect to jupyterhub.cuahsi.org, resulting in missing browser cookies. A simple solution is to change the url for the CUAHSI JupyterHub in "featured apps" from `jupyter.cuahsi.org` to `jupyterhub.cuahsi.org`.

**Comment by martinseul** [comment]
Released with 1.36
