### ISSUE TITLE
Location data endpoint optimization

### ISSUE THREAD

**Issue by cuahsimarko** [hydroshare/hydroshare#3963]
The endpoint that returns geographic data should be investigated with performance enhancement in mind. /searchjson/ or /discoverjson/ takes over 10 seconds to serve necessary data. The initial call could be scoped to a more limited viewport/zoom level, the backend could be optimized through the Haystack/SOLR/data model layers.

**Comment by cuahsimarko** [comment]
New Discover does not use /searchjson/ or /discoverjson/ @alvacouch please advise if other systems use this or close this issue and consider removing those endpoints if appropriate.

**Comment by alvacouch** [comment]
@cuahsimarko I am not aware of anything else that uses these endpoints.
