### ISSUE TITLE
Unzip fails with Gateway timeout

### ISSUE THREAD

**Issue by Castronova** [hydroshare/hydroshare#3975]
I get an error (see below) when extracting a zip file within HydroShare. This archive can be extracted locally without any issues, but when using HydroShare's "unzip" functionality I get HTTP 504. The strange thing is that the data appears to be extracted successfully.

![image](https://user-images.githubusercontent.com/4822372/92750943-8bb6bc80-f355-11ea-957e-56bcae56a044.png)

**Comment by sblack-usu** [comment]
A 504 is a timeout.  This is because your browser doesn't receive a response before timing out due to django being busy unzipping the file.  This will be fixed with the async tasks work that is nearly complete.

**Comment by martinseul** [comment]
@hyi Is this ticket still active or should it be closed?

**Comment by hyi** [comment]
@martinseul Yes, I believe this has been fixed with the async tasks, but will leave it to @Castronova to test and close if it indeed works now.

**Comment by eclark-cuahsi** [comment]
@Castronova can you please test and confirm that this works now?

**Comment by devincowan** [comment]
@martinseul and @Castronova I tested manually and also added to [a PR for our QA suite](https://github.com/CUAHSI/QA-AutomationEngine/pull/58/) and can confirm that this works now
