### ISSUE TITLE
solr_facets management command doesn't work.

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#3976]
Due to my refactoring of discovery_form.py in which a link was forgotten, the debugging command solr_facets crashes.

**Comment by cuahsimarko** [comment]
@alvacouch new Discover does not use discovery_form.py not sure if you're using it elsewhere. Please advise or simply close this.

**Comment by alvacouch** [comment]
I will fix this in the current PR.

**Comment by devincowan** [comment]
Seems like this is stale
If I'm wrong, please re-open.
