### ISSUE TITLE
URL paths and RESTful Design Need Dev Consensus

### ISSUE THREAD

**Issue by cuahsimarko** [hydroshare/hydroshare#3988]
RESTful paths in urls.py and hydroshare/urls.py as well as implications with Mezzanine need to be discussed and a group agreement reached on approaches to configuration, such as sub paths on an endpoint. Also expectations around _hsapi and the HydroShare REST API should all be baselined and documented for all, who contribute to HydroShare core sourcecode and the REST API.

**Comment by martinseul** [comment]
@cuahsimarko  is this ticket still relevant or can it be closed?

**Comment by cuahsimarko** [comment]
This is a probem, we need to address and is only complicated by the need for API versioning, as we have old API clients and student code and other apps that rely on endpoints that will likely change as a part of HSRDF work. If anything, the scope of this ticket should be expanded. There are probably historical endpoints that need to be moved to _hsapi that are not part of HSRDF or Discover, too.

**Comment by cuahsimarko** [comment]
One of many opinions out there... https://medium.com/@petertboyer/learn-restful-api-design-ideals-c5ec915a430f

**Comment by eclark-cuahsi** [comment]
@sblack-usu is this something we should consider or should we close the issue if we're not going to pursue?

**Comment by sblack-usu** [comment]
I have figured out how to version the API and am currently working on API endpoints using hsmodels for metadata GET/PUT.  This work is being done for the Data Submission Portal but will be made available to all.  The new API version will be expanded as hsmodels gains more functionality.  I have been doing this work along with @hyi's work in #4130.  We can generate issues for work needed as this new API version is expanded.
