### ISSUE TITLE
netCDF header info text area is not shown in meta editing mode 

### ISSUE THREAD

**Issue by gantian127** [hydroshare/hydroshare#399]
This issue is found on dev site. When user clicks on the editing button, the "resource specific" tab shows the forms of the extended metadata, but the header info text area is missing. 

@mauriel133 yesterday I suggested for adding a new block section in genericresource.html to solve this problem. But if there is a better solution, please let me know. Thank you.

**Comment by mauriel133** [comment]
In view mode, I think it's better to have the header info shown as a button or a link which triggers a modal window with the text area.

Is the header info editable in edit mode?

**Comment by gantian127** [comment]
@mauriel133 The header info is not editable in editing mode. The header info is the content of the text file of the resource data files. The text file is automatically created when user uploads a ".nc" file.

The plan is to make the text area shown in the resource landing page. If there is no text file in the resource data files, a button will be shown on the resource landing page to create a new header_info.txt file. (shown as the following)
![button](https://cloud.githubusercontent.com/assets/5016511/7894510/cb148ff4-0627-11e5-9169-2bf95e408a81.png)

Currently, all the code for this function are put in the {%extended_metadata%} block. But the text area or the button is missing when it is under editing mode. Besides, there is another button for connecting to the netCDF tools page and the code is in the same block. This button is also missing when in editing mode. 

The problem for me is not where to put the text area or the button (it is fine to put them in the resource specific tab). The problem is when I put extra code not related to extended metadata in {%extended_metadata%} block, the code is not working well under editing mode.

So people may need to inherit another block from genericresource.html to put the code in rather than using the block for extended metadata. If there is a better plan to solve the problem, please let me know. Thanks.
