### ISSUE TITLE
copying a large resource breaks things

### ISSUE THREAD

**Issue by danames** [hydroshare/hydroshare#3992]
Copied a large resource >300 MB. The gateway timeout came up. Then the "My Resources" page showed an error for a couple of minutes. Then loaded OK.

**Comment by hyi** [comment]
@danames Copy resource is one of the tasks I have put into the async task framework that should make its way into beta testing and subsequent release soon (by the end of this month if things go smoothly). Once the async task framework is released, this problem should not occur any more. Let's test it out to make sure this issue is fixed by the async task work once it is deployed.

**Comment by danames** [comment]
I just tested copying an >800MB resource, https://www.hydroshare.org/resource/9572eb7fa8744807962b9268593bd4ad/. It succeeded in 2 minutes with no time out. This issue can be closed. 

Side note: it would be good if the notification that shows completed copy would provide a link "View the new resource here".

**Comment by danames** [comment]
Do I need to create a new github issue for the notification to make it more
informative and useful?
**********************************************************************
Daniel P. Ames, Ph.D., P.E.
Professor, Civil & Environmental Engineering,Brigham Young University,
Provo, Utah, USA
Past-President, International Environmental Modelling & Software Society
Editor-in-Chief, Environmental Modelling & Software
<http://ceen.et.byu.edu/content/dan-ames>
https://ceen.byu.edu/directory/dan-p-ames
http://www.researchgate.net/profile/Daniel_Ames
http://scholar.google.com/citations?user=S0GUCeUAAAAJ

**********************************************************************

**Comment by hyi** [comment]
@danames Sure, creating an issue will be good so this does not get lost. It'd be great to create a generic message that is informative for all async resource operation tasks such as file zipping/unzipping, resource copy, resource versioning, resource deletion, etc. so we don't have to customize notification message for each task individually.

**Comment by danames** [comment]
Done. Issue https://github.com/hydroshare/hydroshare/issues/4123
**********************************************************************
Daniel P. Ames, Ph.D., P.E.
Professor, Civil & Environmental Engineering,Brigham Young University,
Provo, Utah, USA
Past-President, International Environmental Modelling & Software Society
Editor-in-Chief, Environmental Modelling & Software
<http://ceen.et.byu.edu/content/dan-ames>
https://ceen.byu.edu/directory/dan-p-ames
http://www.researchgate.net/profile/Daniel_Ames
http://scholar.google.com/citations?user=S0GUCeUAAAAJ

**********************************************************************
