### ISSUE TITLE
Temporal Coverage Styling looks wrong - Discover feature parity

### ISSUE THREAD

**Issue by Castronova** [hydroshare/hydroshare#3997]
The Start and End date boxes inside the Temporal Coverage Filter don't fill the width of their parent element. This looks makes the styling look inconsistent with the rest of the page. To fix this, expand the start and end date boxes to fill the width of the Temporal Coverage Filter.

As currently implemented:
![image](https://user-images.githubusercontent.com/4822372/96141932-7f330000-0ecf-11eb-9146-e2492b19165d.png)

Recommended styling:
![image](https://user-images.githubusercontent.com/4822372/96142008-94a82a00-0ecf-11eb-9bbd-295898eb72c1.png)

**Comment by cuahsimarko** [comment]
This has a solution and has been submitted to @ndebuhr @martinseul last week for evaluation. Once a response is received, we will know if this  will be released as a part of Feature Parity + or later.

**Comment by cuahsimarko** [comment]
This is a known issue. This will be resolved and undergo extensive testing after Feature Parity+ Oct 21 release.

**Comment by hydrocheck** [comment]
Issue resolved as a part of the Discover redesign
