### ISSUE TITLE
Facets do not update after search - Discover feature parity

### ISSUE THREAD

**Issue by Castronova** [hydroshare/hydroshare#3998]
After running a search, the facets (i.e. Author, Owner, etc.) are not updated as expected. To a user this implies that these facet values can be used to further filter the search results. However, since the facets are not updated after the search takes place, they contain values that are often not present resources returned by the initial search. This results in "No resource matches". To fix this, facets should only contain values that exist in the resources returned by the search.

To reproduce:
1. search for "castronova". Notice that 45 resources are returned.
2. Notice that the first  item in the "Author Filter" (Anderson, Suzanne) appears to have 34 matches
2. Select Anderson, Suzanne
3. Notice that "No resource matches"

![image](https://user-images.githubusercontent.com/4822372/96142991-a8a05b80-0ed0-11eb-8dc9-2b27af4ea4d2.png)

![image](https://user-images.githubusercontent.com/4822372/96143017-b2c25a00-0ed0-11eb-860d-227438f242ae.png)

**Comment by cuahsimarko** [comment]
Interesting. There were conversations around Production Discover as of today and how filtering (checking a box) does not update the integer counts besides filters. It was not realized at the time that Production Discover _does_ update the integer counts, though.

Current Production Discover:
- Checkbox action (no update to filter counts beside checkboxes)
- Date filter action (no update to filter counts beside checkboxes)
- Freetext search (performs update to filter counts beside checkboxes)

New Discover
- No action updates filter counts beside checkboxes

Proposed path forward
- Design discussion around potentially removing filter "facet" checkboxes as they are legacy and there are perhaps more effective, modern UI elements to handle the uses cases more effectively
- Get concensus that integer-based checkboxes are the best solution and then implement the following: any action, whether date, checkbox, map activation or free search result in an update of checkbox integer counts

**Comment by cuahsimarko** [comment]
@Castronova Just to clarify, after further investigation the way Discover works today, is that those filter counts update only on a freetext search and such a search clears any previous selections. This is being tested now and how new Discover will function. The checkboxes are a point of contention and the team should really consider replacing them. They are a lot to maintain and make everything on the Discover page much more complicated, leading to inconsistencies.

**Comment by hydrocheck** [comment]
Issue resolved as a part of the Discover redesign
