### ISSUE TITLE
Geographic raster resource should only allow one raster file to be saved.

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#40]
Testing on alpha.hydroshare.org version 1.2.1

It is possible to add arbitrary files to a geographic raster resource.  This should not be allowed as non raster files are not part of the geographic raster data model.

**Comment by hyi** [comment]
Fixed this issue by adding the logic to remove "Add file" button if it is geographic raster resource. Fixed pushed into AGU branch. Closing this issue now for follow-up verification once it makes into alpha.

**Comment by hyi** [comment]
Reopen the issue and attach a "Ready to test" label as Dave suggested.

**Comment by dtarb** [comment]
This issue may be partly resolved, but the resource creation flow that is involved with this still has trouble.  I wanted to see what happened with respect to when it allowed files to be loaded and not loaded so I did the following:
1. Create New Resource
2. Select Type as Geographic Raster (no file selected)
3. Describe resource
4. Fill Abstract and Fill Keyword.
An internal validation error occurs.

To fix this refer to the resource creation sequence worked out at the Logan team meeting

1. User Clicks “create new” to create a new resource
2. The Select Resource page appears.  Nothing exists at this point.
3. The user selects a resource type. Nothing exists yet.
4. The user creates a title for the resource (NOTE: this should be optional and doesn’t exist yet - pre populate this field with “Untitled resource”)
5. Optionally, the user clicks choose files and selects one or more files. Nothing exists yet.
6.The user clicks the “Create Resource” button (renamed from Describe Resource).  

Note that at step 5 the identification of a file is optional.  This seems to be what is failing.  To address this issue it should be possible to select 0 or 1 file, but no more than 1.

Once the resource landing page is reached if there is 1 file it should be possible to delete it.  If there is no file there should be the possibility to add a file.  If a file is added it needs to be parsed to read metadata that is part of the file.

**Comment by hyi** [comment]
This issue as described should be fixed in my 82-raster-resource-new-workflow feature branch as part of the fix to issue [#36], which is to be merged into develop and deployed for testing soon.

**Comment by dtarb** [comment]
I just tested on dev and was able to create a raster resource containing two files by selecting both files in the initial browse.  The browse dialog initiated from create-resource when the type is a raster resource should only allow one file to be selected.

**Comment by hyi** [comment]
This issue is fixed now after adding file validation code. Fix posted in github and a pull request has been created to merge it into develop. Will add ready for testing label back once the fix is deployed to dev or alpha.

**Comment by hyi** [comment]
The only outstanding issue that should disable Add files button when there is already a file uploaded is covered in issue #224 @dtarb Could you make sure this is the case and close this issue?

**Comment by hyi** [comment]
Tested it on alpha and it is working now. Adding ready for testing label.

**Comment by dtarb** [comment]
Tested by creating raster resource.  I am able to delete a file, then browse to add a file and select more than one file and save changes and the result is a resource with two files that is not supposed to happen.  See http://alpha.hydroshare.org/resource/56b567d4cfe44174845f97dd88a137df.  This is not release blocking so I am going to relabel as 1.5

**Comment by hyi** [comment]
After reviewing the JavaScript code in genericresource.html, I am assigning this to Pabitra who added this file validation code and will be most appropriate to quickly fix it. @pkdash The bug only occurs when supposedly adding one geotiff file via Add File button from the resource landing page. Currently, the file browser triggered from Add File button allows users to select more than one geotiff files for a raster resource type, while the file browser triggered from Create resource page only allows one geotiff file to be selected.

**Comment by dtarb** [comment]
Tested on dev.
