### ISSUE TITLE
Hydroshare metadata writing back to .nc file

### ISSUE THREAD

**Issue by gantian127** [hydroshare/hydroshare#400]
Phase 2 functionality of Multidimensional netCDF resource include:
1) hydroshare metadata writing back to .nc file
2) data sub-setting
3) data inspector
4) ncdump file creation 

Other resource related functions mentioned in #8 will be implemented in the future phases.

**Comment by pkdash** [comment]
@gantian127 Should this be closed?

**Comment by pkdash** [comment]
@gantian127 If this still an issue, please assign a priority level (low, medium, high, backburner).

**Comment by gantian127** [comment]
@pkdash I think most of the items have been implemented by supporting the OPeNDAP service. The first item "hydroshare metadata writing back to .nc file" is not implemented yet.

**Comment by cuahsimarko** [comment]
@pkdash can this be closed or can you provide new info?

**Comment by pkdash** [comment]
@cuahsimarko I have no idea what still needs to be done for this issue. I would say close it unless @dtarb says otherwise.

**Comment by gantian127** [comment]
@cuahsimarko @pkdash @dtarb All the functions in this issue have been implemented. I will close the issue. Thanks.
