### ISSUE TITLE
Table sort order not respected - Discover Feature Parity

### ISSUE THREAD

**Issue by eclark-cuahsi** [hydroshare/hydroshare#4000]
Observed on dev 6 and dev 7: When the table is sorted by ascending First Author (A-Z), some of the results are returned out of order (see below).

Steps to reproduce:
1. On the resource list table, toggle First Author sort arrows so that the arrow is facing up for ascending sort (A-Z).
2. Note that midway down the page, First Author results are returned out of order.  Brigham Young University -> Stone, M.M -> Johnson, A.J. -> Aurdenkampe, A.K. -> Heldmyer, Aaron -> Thompson, Aaron -> Fellows, Aaron W. -> Abe, Camilia, etc. 

A similar issue is happening for sorting the resources by title. When the sort condition is applied, each page is sorted correctly, but the sorting does not apply across pages, so resources are not grouped alphabetically together across pages. 

Page 1...
![Dev 6 Page 1 Ascending Sort](https://user-images.githubusercontent.com/64596508/96166188-a26ba880-0eeb-11eb-9e32-133acff6af55.jpg)

Also spot checked in other places and noticed it happening randomly throughout. This is page 25. 
![Dev 6 Page 25 Ascending Sort](https://user-images.githubusercontent.com/64596508/96166275-c0d1a400-0eeb-11eb-9b70-c3b0ab1118fa.jpg)

**Comment by cuahsimarko** [comment]
Related to https://github.com/hydroshare/hydroshare/issues/3991

**Comment by cuahsimarko** [comment]
I believe the behavior is present in Production Discover

![image](https://user-images.githubusercontent.com/45397838/96170342-75ba8f80-0ef1-11eb-9d38-7b6968889060.png)

**Comment by cuahsimarko** [comment]
This is Production Hydroshare. As you can see, the index is bouncing between last name and first name. Also, new Discover has the subtle difference of finding BYU as Organization instead of providing None (to match Resource Landing page logic)

![image](https://user-images.githubusercontent.com/45397838/96170469-a1d61080-0ef1-11eb-80e5-b391a7736eb1.png)

**Comment by hydrocheck** [comment]
Issue resolved as a part of the Discover redesign
