### ISSUE TITLE
Prod Discover Title and Author Sorting

### ISSUE THREAD

**Issue by cuahsimarko** [hydroshare/hydroshare#4005]
The index sorting for Prod Discover is using order_by and the _exact field should be indexed and used and ensure that case insensitive behavior is retained during this action. Sorting now returns unexpected results when title or author are used. Currently workaround code is in place, leading to very long waits for sorting by Title and undesirable lowercase/uppercase behavior when sorting by Author.

**Comment by cuahsimarko** [comment]
@alvacouch I believe we discussed this the other day, just need these updated in the Index.

**Comment by alvacouch** [comment]
@cuahsimarko It's a little harder than that. If we want SOLR sorting by lcase, i need to make new fields author_lcase and title_lcase for you to sort by, while leaving author and title in uppercase.... is that what you want?

**Comment by cuahsimarko** [comment]
@alvacouch I should refine my Oct 19 entry:

1. Title is temporarily sorting without the Index: https://github.com/hydroshare/hydroshare/blob/088186a6fe4a24dfac05128206531ea29b6f16b3/hs_discover/views.py#L170 .... Index-related code should be updated so that patterns can be used, similar to how other fields are being sorted. I'm open to changing anything in the frontend or view.py as needed. Here is the sorting code for fields already being indexed: https://github.com/hydroshare/hydroshare/blob/088186a6fe4a24dfac05128206531ea29b6f16b3/hs_discover/views.py#L164
2. Sort by Author is using author_exact https://github.com/hydroshare/hydroshare/blob/088186a6fe4a24dfac05128206531ea29b6f16b3/hs_discover/views.py#L160 ... what needs to be done in the Index/middle-tier/frontend to make this sort case insensitive?

**Comment by alvacouch** [comment]
This has been addressed.
