### ISSUE TITLE
hsctl Sequence

### ISSUE THREAD

**Issue by cuahsimarko** [hydroshare/hydroshare#4008]
When using hsctl rebuild on dev-hs-6, I observe that it deploys, then the index populates up to around 1850 resources. This takes 10-30 minutes, then some process restarts the Docker containers, killing what was probably a reindex job. A manual reindex (./hsctl managepy solr_recover) is then required.

- Research if this behavior is unique to dev-hs-6
- Confirm that an indexing operation is indeed in process in the first 20-40 minutes, before the container restart
- Look for a race condition or missing script blocking behavior to allow the index to complete, if this is what's going on
- Remedy as necessary or at least assemble a plan and discuss the approach with Chris, Alva and Scott so everyone is in agreement

![image](https://user-images.githubusercontent.com/45397838/96501954-1c1ed180-121f-11eb-9748-87ab008f6ea0.png)
Figure 1: Screen will pause here for 20-30 minutes

![image](https://user-images.githubusercontent.com/45397838/96502061-4a9cac80-121f-11eb-89e0-8cc5a77b1703.png)
Figure 2: At around 1850 resources, this new progress will show and sequence continues, then a full reindex begins, taking 1-2 hours

**Comment by cuahsimarko** [comment]
Not urgent and should wait until after 1.38 Release and possibly even until after Async as well.

**Comment by martinseul** [comment]
closing will be addressed ongoing dev work
