### ISSUE TITLE
Embedding HydroShare in an iFrame as in HydroLearn does not work on a Chrome Browser.

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#4012]
The screen shot below is from a Page in HydroLearn, where HydroShare has been embedded in iFrames shows no content, in Chrome.  It works in Firefox.

See https://edx.hydrolearn.org/courses/course-v1:Utah_State_University+CEE6400+2019_Fall/jump_to/block-v1:Utah_State_University+CEE6400+2019_Fall+type@vertical+block@fc08f6dfe6c34b3fa1d3846f82390fb0 if you want to reproduce.

This may be to do with different Browser cookie settings, but it would be good to understand to advise users if this is the case.

![image](https://user-images.githubusercontent.com/3456833/97115884-2594b780-16bf-11eb-8a99-27420108e74e.png)

**Comment by Castronova** [comment]
Duplicate of #4043

**Comment by dtarb** [comment]
Closing as duplicate but refer to #4043
