### ISSUE TITLE
discover lists obsoleted resources

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#4015]
The new discover doesn't contain the software filters that the old discover used to hide obsoleted/versioned resources. Further, these filters were not optimal for a number of use cases. 

The proper fix is as follows: 
1. for public and published resources, show the latest public version. Other versions will be available on the resource landing page. 
2. for discoverable resources, show the latest discoverable version. Other versions will currently NOT be available on the resource landing page. This is subject to change in the future. 

This is a matter of changing the SOLR harvester to avoid acting on resources whose public status is stale.  These will simply not appear during harvesting.

**Comment by dtarb** [comment]
Small clarification on point 2 above.  At present Discoverable resources display references to older or newer versions.  E.g.
![image](https://user-images.githubusercontent.com/3456833/97373010-89afab00-187a-11eb-8a31-4c841a55d816.png)
![image](https://user-images.githubusercontent.com/3456833/97373016-8ddbc880-187a-11eb-853c-ccb2f731fb8c.png)
No change is needed with these.  The Discover page should show the latest version of the resource linked in a versioning chain that is Published or Public or Discoverable.  I think that is what is being done, but wanted to state this explicitly to be sure.

However see #4019 for a change suggested for the public page for a private resource, to not break the versioning chain.

**Comment by martinseul** [comment]
@alvacouch please review in connection wit 4019

**Comment by alvacouch** [comment]
Addressed in recent PRs.
