### ISSUE TITLE
Display versioning relationships on the public page for private resources

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#4019]
The discover page is being changed to shows the most recent published/public or discoverable resource (per #4015 ).  Versioning in HydroShare is implemented using relationships 
-	isVersionOf to indicate that a resource is a newer version of a previous resource
-	isReplacedBy to indicated that a resource has been replaced or superseded by another resource

These do not address access control.  Thus it is possible to have 
1. A published resource replaced by a resource that is still private.  In this case Discover will find the published resource.  This is the desired behavior.
2. A published resource (lets say resource A) replaced by a resource that is private (say resource B), which itself is replaced by a resource that is Discoverable/Public/Published (say resource C).  Resource C will indicate that it has resource B as a prior version. But as resource B is private, users are unable to access it, to see that it has a prior version (resource A).  

To allow users to “discover”, i.e. get back to resource A which is published, the chain from resource C to resource A needs to be open.  I thus suggest that even for private resources that versioning relationships be presented on the resource landing page.  This is a small policy change, in addition to implementation change.  It makes versioning information for private resources no longer private.

Illustration
Current page for a resource that is private where the user does not have access
![image](https://user-images.githubusercontent.com/3456833/97372780-0beb9f80-187a-11eb-9e91-6a2f0d092d53.png)

Proposed change
![image](https://user-images.githubusercontent.com/3456833/97372795-1312ad80-187a-11eb-9ffd-1c1581345315.png)

**Comment by cuahsimarko** [comment]
Related https://github.com/hydroshare/hydroshare/issues/4015 (obsoleted resources)

**Comment by martinseul** [comment]
@alvacouch please review and is this part of a current fix

**Comment by alvacouch** [comment]
Addressed via backend changes in pending PR.
