### ISSUE TITLE
Implement (or correct) logic to prevent the creation of multiple versions of a resource

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#4028]
HydroShare versioning design is based on an obsolesce chain where resource A can be superseded by version B and version B can be superseded by version C and so on.  i.e. A -> B -> C.  This is implemented using relationships "isreplacedby" and "isversionof".

However if I click repeatedly on the "Create New Version" button on A, while waiting for it to create a new version I can end up with multiple new versions
A->B->C
A->C
This is inconsistent with the design

Logic needs to be implemented to prevent clicking on the create version button repeatedly, or to prevent creation of more than one "isreplacedby" or "isversionof" relationship in a resource in cases where a user does click the button repeatedly or has multiple browser windows open acting on the resource.

**Comment by dtarb** [comment]
This problem can also lead to corrupt versioning of resources.  While testing to understand this problem I created
A https://www.hydroshare.org/resource/1a64f1c4cbcc4a2b919c943fc5ec111f/
B https://www.hydroshare.org/resource/fa2ee3738e9d407992fee78f7ab1bb3c/
C https://www.hydroshare.org/resource/b6ada7bfa435495d8dc5c30aa273d93f/
D http://www.hydroshare.org/resource/32311fe7a9284f91bd9c701acba91a89/

There are versioning relationships
C has new version D
C has old version B
B has new version C
B has old version A
A has new version B

or more succinctly
A -> B -> C -> D

But in an attempt to clean up after myself I deleted D.  Only the latest in the versioning chain can be deleted.  However the relationship on C that says it has new version D still persists and because of this C can not be edited or deleted and these resources are effectively stuck.

**Comment by dtarb** [comment]
@alvacouch see this

**Comment by alvacouch** [comment]
@sblack-usu This is not surprising. A number of integrity checks like this one are not made or repaired. My new PR #4017 works around this by checking for existence and ignoring any version that is declared and that got deleted.

**Comment by hyi** [comment]
@dtarb You can test this on beta or test on production after the next release to see if this issue is resolved.

**Comment by martinseul** [comment]
@hyi I was looking at this issue and tested on beta with this resource https://beta.hydroshare.org/resource/edbd2f01b855451d96c8e49c58101f15/ , I did notice an unexpected behaviour when clicking throught  the older versions.
What I did was create 3 new versions of the resource and when clicking through the older versions the link changed to reference a version on prod 
![image](https://user-images.githubusercontent.com/5427742/132549015-a1ed47c9-518e-4ace-979d-2915703f8abb.png)

I'll add this to your list  in the github board and we can look at it on Monday in the dev call, if you're available.

**Comment by hyi** [comment]
@martinseul The url issue is an artifact of the resource copy for testing from www to beta. Since the original resource to be versioned was copied over from production to beta, its identifier as part of metadata stored in database has production site url in it, hence the new versioned resource created on beta points to the original resource on www which was copied over from production. This url issue will not happen on production site, so it should not be an issue but only an artifact of beta testing.

**Comment by hyi** [comment]
@dtarb production is ready for you to test all resources with versioning fix now.

**Comment by dtarb** [comment]
Closing as this appears correct.  However there is a problem with dates - see #4472
