### ISSUE TITLE
Content type filtering missing options

### ISSUE THREAD

**Issue by martinseul** [hydroshare/hydroshare#4029]
when comparing the available content type filter on prod the list of available types is missing important types e.g. Shape files that were available before:

Production:
![content type filter list  new (Small)](https://user-images.githubusercontent.com/5427742/98557693-851fc500-2272-11eb-8136-5ac636bfbf2d.jpg)

previous list 
![content type filter list  old (Small)](https://user-images.githubusercontent.com/5427742/98557727-9072f080-2272-11eb-8197-1cd842b53ddf.jpg)

Need to investigate why the additinal types are not available and make additonal types available.

**Comment by cuahsimarko** [comment]
Working on my laptop, will consolidate with other fixes and deploy to dev6 later
