### ISSUE TITLE
Allow existing users to be added as creators and contributors on resource editing page

### ISSUE THREAD

**Issue by pkdash** [hydroshare/hydroshare#403]
Implement feature to search/select an existing user for adding as an author or contributor in the "Add author" and "Add contributor" modal forms.

**Comment by mauriel133** [comment]
@pkdash, what is the status of this issue and how can I use your previous work? Has it been merged to develop?

**Comment by pkdash** [comment]
@mauriel133 I think we have to start from scratch on this one. If you can start with necessary UI changes for adding existing users as creators/contributors, I can add any backend support needed.

**Comment by pkdash** [comment]
This issue is same as #1190

**Comment by mauriel133** [comment]
This has been implemented and deployed to www. Please verify and close.

**Comment by dtarb** [comment]
OK. Closing
