### ISSUE TITLE
Discover results table and facets do not resize responsively

### ISSUE THREAD

**Issue by Castronova** [hydroshare/hydroshare#4033]
Discover results table and facets do not resize responsively. Instead when the browser size decreases, the table is pushed to the bottom of the screen leaving a blank space that takes up most of the page. This table and facets should resize using responsive design similar to the "My Resources" page.

The "Discover" page elements do not resize when the page is resized: 
![image](https://user-images.githubusercontent.com/4822372/98885354-dfca4400-245f-11eb-97c4-96b60514729f.png)

The "My Resources" page elements do resize when the page is resized:

![image](https://user-images.githubusercontent.com/4822372/98885682-772f9700-2460-11eb-9a65-183e0e5f3684.png)

**Comment by cuahsimarko** [comment]
@Castronova @martinseul  I think the widened version performs no function, other than making it harder to read which integer counter goes with which checkbox and label. Motion to close this.

**Comment by Castronova** [comment]
@cuahsimarko When the browser size is decreased below the responsive "large" level, the resource table is pushed off the screen and a large blank space is displayed next to the facets. The responsive design for the discover page should remain consistent with the way we're resizing other pages on HydroShare, for example the "My Resources" page.

**Comment by cuahsimarko** [comment]
@Castronova Here is the behavior across HydroShare 
![image](https://user-images.githubusercontent.com/45397838/103579627-9b2eb800-4ea6-11eb-90ce-0e5af1cae537.png)

I don't think this adds any value and even makes the page less readable. This example only has a few fields, but there are many more in Discover, so the problem would be magnified. I am of the opinion that the version on Discover is more appropriate and that a different GH Issue should be created to rethink the responsive behavior, overall, from first principles, such as prioritizing mobile readiness, which devices and workflows we expect to be responsive and at what resolutions, and providing the tools, services and hardware to test these various display modes. Finally, a review of which sizes (widths would cause breaks and push content below other "columns").

**Comment by horsburgh** [comment]
I have to agree with @Castronova on this one. I think it's unacceptable to have totally different responsiveness behavior across the small number of pages on our site. Leaving the huge white space to the right of the discover facets just looks like a bug. Users will not know that they need to scroll to see something. It looks like the page didn't load. It's hard to make a page less readable than if the content gets moved completely out of the user's view.

We might want to consider all that @cuahsimarko suggests, but I don't think we have to do all of that to fix the one page that isn't working well now.

**Comment by cuahsimarko** [comment]
@Castronova @horsburgh I think both look out of place and suspect a third option will feel more natural and be more readable than both. The problem would be the difference between Discover and the rest of HS. I can code anything, but perhaps this warrants re-thinking. If someone wants to make a decisive move, let me know and I'll update. If we match Discover to the rest o HS, what should the date input in the Temporal Coverage Filter look like? The paging controls would likely drop out of view and move much lower on the page, when the window is small. Also, what use case is this serving? If someone has shrunk the horizontal dimensions in Discover, presumably they are looking to gain more real estate. HS consumes very little width on modern screens, so I don't see this happening often. In the case of a small window, I would think someone would rather scroll. HS does not support mobile, in my understanding, if we do, though, let's solidify the use cases across tablet, phones and manufacturers.

**Comment by horsburgh** [comment]
@cuahsimarko - I'm not sure which two options you are referring to? I suspect the reasons why the date options were not originally in the facets panel is specifically because it would cause responsiveness problems. They didn't have to go there, but they were moved there. Yes, paging controls would drop lower to stay with the list of results. 

I think it's a mistake to say that HydroShare does not support mobile. Do we really think that nobody will ever look at HydroShare on a mobile device?

I OFTEN have browser windows open on my screen at widths that cause the list of results to disappear. I am working on a 27 inch monitor. Also - when I open search on my phone or my iPad, the list of results is missing until I scroll down on the page. It isn't apparent that I need to scroll because all I see is search facets on the left with a large white space on the right side of the window. This looks like a bug and not an invitation to scroll.

It was responsive before, and now it's not. The other pages in hydroshare are responsive.

**Comment by cuahsimarko** [comment]
@horsburgh My understanding from conversations with Neal and Martin was that HydroShare does not officially support mobile. I have a refreshed perspective on the matter now.

Perhaps when resizing to the typical HS width that causes content to drop below, then paging controls could align vertically with the Temporal Coverage Filter, then the remaining filters could be displayed. Beneath that, the paging controls could be repeated and then the table of resources?

**Comment by cuahsimarko** [comment]
Using My Resources as an example of how HS resizes. Perhaps it would be a good idea to introduce alternating backgrounds (gray to white as in the resource table) to support the unusual gap between the integers and the items when on an iPad or initial breakpoint for resizing:

![image](https://user-images.githubusercontent.com/45397838/106643504-d4b31b80-6557-11eb-8a2d-79ee43f7e1be.png)

**Comment by cuahsimarko** [comment]
We could also more closely match the older behavior and put the date selectors back with the resource rows and have it just leave a gap. It would not look too awkward.

**Comment by cuahsimarko** [comment]
I have coded something for this and will be deploying for discussion. It's either all good or very close.
