### ISSUE TITLE
clean up NGINX architecture for file download

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#4037]
There are several optimizations needed before file download is reliable. These include updating the NGINX configuration so that Django requests for authorization don't overload Django, as well as updating the file download mechanism to conform to NGINX best practices. This requires modification of both the outer and inner NGINX Proxies.

**Comment by martinseul** [comment]
@alvacouch please review and close/consolidate

**Comment by alvacouch** [comment]
Completed in recent NGINX re-architecting.
