### ISSUE TITLE
URIs In Resource Map Should Resolve to Something

### ISSUE THREAD

**Issue by horsburgh** [hydroshare/hydroshare#404]
The URIs in the resource map should resolve to the individual files in the resource.  I believe that this is one of the reasons we went to the unzipped storage format in iRODS.  Right now, I believe that they result in a 404 error.

If not, rather than giving a 404 error, could they at least all resolve to the resource landing page or something like that?

**Comment by selimnairb** [comment]
@horsburgh Is this still a problem, or has it been resolved?

**Comment by hyi** [comment]
@horsburgh I believe it has been resolved, but could you check it to confirm and close if the problem is indeed resolved?

**Comment by horsburgh** [comment]
Just tested this on www.hydroshare.org and the URIs do resolve.  So, I believe that this issue has been addressed and I'm going to close.  

But, as a side note - I also tested on dev.hydroshare.org and got the same result (URIs resolve).  But I tested on beta.hydroshare.org and I'm back to having timestamps as the folder name in the zipped bag. This is a little disconcerting?

**Comment by hyi** [comment]
@horsburgh the new bagit workflow and the new url mapping to make URIs resolvable are not deployed to beta.hydroshare.org, which explains the difference you observed. beta will be decommissioned after the old resources are manually migrated to the www.hydroshare.org as I understand it.

**Comment by horsburgh** [comment]
@hyi - perfect.  I just wanted to make sure that an inconsistency hadn't crept back in.  I closed the issue since it works on www.hydroshare.org.  By the way - I'm glad this now works!
