### ISSUE TITLE
The async information panel can get stuck on initialization

### ISSUE THREAD

**Issue by hydrocheck** [hydroshare/hydroshare#4046]
After a dozen or so async resource deletes, page refreshes can cause the notifications loading icon to get stuck at initialization - without showing anything.
<img width="357" alt="stuck-notification-panel" src="https://user-images.githubusercontent.com/43424907/100402940-82232380-302b-11eb-94eb-155a8e405ff4.png">

**Comment by martinseul** [comment]
Retested and could not reliably reproduce issue, closing for now
