### ISSUE TITLE
Notifications stop refreshing status automatically, after some period of time

### ISSUE THREAD

**Issue by hydrocheck** [hydroshare/hydroshare#4048]
After a certain period of time, the "In Progress" in the notifications will no longer automatically refresh
<img width="345" alt="in-progress-no-refresh" src="https://user-images.githubusercontent.com/43424907/100402921-76cff800-302b-11eb-92a7-8c0dd5f6bad5.png">

**Comment by martinseul** [comment]
@Neal can you retest with the upcoming release it has changes to the delete process

**Comment by hydrocheck** [comment]
Closing as resolved
