### ISSUE TITLE
"X" button does not delete or hide notification cards as expected

### ISSUE THREAD

**Issue by hydrocheck** [hydroshare/hydroshare#4049]
The "X" button on the right of the notifications cards looks like it should close the notification, but it does not immediately do so - a manual page refresh is required.
<img width="361" alt="x-icon-does-not-delete" src="https://user-images.githubusercontent.com/43424907/100403130-01185c00-302c-11eb-9d7a-83970e67df7f.png">

**Comment by sblack-usu** [comment]
I have not encountered this before.  Whenever I click the "x" it closes the notification card immediately without a refresh.  Could this be browser specific?

**Comment by cuahsimarko** [comment]
The x has been closing the individual notifications for me in Chrome. However, I think the Clear button should make the modal disappear, which it does not currently.

**Comment by cuahsimarko** [comment]
@ndebuhr how did you test the x behavior?

**Comment by hydrocheck** [comment]
Behavior was not originally browser or configuration dependent.  No longer reproducible and closing as resolved.
