### ISSUE TITLE
User State wraps when user type is Other

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#4055]
On beta.hydroshare.org (which is 1.39 candidate release) if user type is set to "other" the state field in the form wraps improperly.

I believe this is a consequence of changes @hyi  did while fixing #3991 

Below is correct positioning

![image](https://user-images.githubusercontent.com/3456833/100804895-dd1d9780-33ea-11eb-83d7-3acdab110c6f.png)

However when user type is changed to "Other" the extra space results in an incorrect wrap of State Box

![image](https://user-images.githubusercontent.com/3456833/100805032-2a016e00-33eb-11eb-80af-d6022bc5fe0c.png)

**Comment by dtarb** [comment]
Sometimes improper wrapping even occurs with a normal user type
![image](https://user-images.githubusercontent.com/3456833/100806276-659d3780-33ed-11eb-8e43-728f3de6e098.png)
This is user 2000

**Comment by Castronova** [comment]
This appears to be resolved, closing.
