### ISSUE TITLE
Subject link click does not initiate search

### ISSUE THREAD

**Issue by martinseul** [hydroshare/hydroshare#4057]
In the previous discover implementation it was possible to share a search and execute a search through the query string like this: https://www.hydroshare.org/search/?q=&selected_facets=subject_exact:GIRF%20Climate . This functionality is used in the RLP in the subject field as it links to the discover page to initiate a search with this keyword. this is not working anymore. Clicking a linked keyword in the subject field does not filter the results on discover.  
We can either enable the this functionality on discover which I lean towards or remove the linkage from the subject field. @dtarb @horsburgh  what are your thought on it.

**Comment by dtarb** [comment]
I would be in favor of restoring the old functionality.  This seems to have come about by discover being handled at the front end so REST like discover calls no longer work.  This is likely to be a problem not limited to subject clicking.  I think there has been other app functionality that has used rest like discover calls that may now be a problem too.

**Comment by sblack-usu** [comment]
I believe this was intended to be a part of the new discover.  The functionality was highlighted by Mark in the code review.  https://github.com/hydroshare/hydroshare/pull/3986/files#r494583568

**Comment by horsburgh** [comment]
@martinseul - I would also vote for keeping this if we can.

**Comment by cuahsimarko** [comment]
> I would be in favor of restoring the old functionality. This seems to have come about by discover being handled at the front end so REST like discover calls no longer work. This is likely to be a problem not limited to subject clicking. I think there has been other app functionality that has used rest like discover calls that may now be a problem too.

Discover has been rewritten as a proper RESTful backend. You can now make proper RESTful calls, such as:
https://www.hydroshare.org/discoverapi/?filter={%22owner%22:[%22CZO%20Boulder%22]}

Fields author, owner, subject, contributor, type, geographic data and date can be specified. If this is of interest to any clients, please let me know. This was created for future possibilities as well as proper testing/fullstack development process and general best practices.

**Comment by cuahsimarko** [comment]
Querystring control of search parameters (for example sharing a URL in an email) is available for the freetext search, for example:

https://www.hydroshare.org/search/?q=jupyter

**Comment by cuahsimarko** [comment]
Please advise what the action items / functionality addition to New Discover is being requested.

**Comment by cuahsimarko** [comment]
This conversation probably deprecates: https://github.com/hydroshare/hydroshare/issues/2819 and 2819 should be closed and tracked by CUAHSI as a part of the 2020 Discover project.

**Comment by cuahsimarko** [comment]
The old Discover API untouched and available here: https://www.hydroshare.org/hsapi/ if/when Alva removed old code not being used by recommendations or new discover, it can be coordinated with him if you want to keep any old code around to support old ways of doing things (even if they are non-standard)....

**Comment by martinseul** [comment]
not sure how Alva's search is relevant here but as discover implements a search by query parameter can we adjust the RLP to send a querystring when clicking a subject field that the current discover can parse this would solve the problem.

**Comment by cuahsimarko** [comment]
I was referencing the APIs still available (Alva's and mine) to address: " I think there has been other app functionality that has used rest like discover calls that may now be a problem too."

**Comment by cuahsimarko** [comment]
@martinseul I see now. So do we want to initiate an exact subject search in Discover in a new tab maybe? Or perhaps pop up a modal under the cursor in RLP with a scrollable/clickable list of resources that share that keyword?

**Comment by martinseul** [comment]
@cuahsimarko the behaviour should be to initiate a subject search in discover in a new tab

**Comment by cuahsimarko** [comment]
The prior functionality was "clicking on a subject keyword on the Resource Landing Page brought the user to Discover, with the results list filtered by that exact subject". I can restore that.

**Comment by cuahsimarko** [comment]
@martinseul @hydrocheck What is the expectation here, when a person shares a URL that specifies a subject, such as `/search/?subject=boulder` but then starts taking other actions in the UI? At what point has the user decided that they are no longer concerned with just keyword boulder? Presumably, any action taken would assume there should be a filter for keyword boulder unless 1) the user removed `?subject=boulder` from the URL bar or 2) removed the checkbox for the subject "boulder" in facets. Am I understanding this correctly?
