### ISSUE TITLE
Map and list view can get out of sync

### ISSUE THREAD

**Issue by martinseul** [hydroshare/hydroshare#4058]
"Map and list views can get out of sync
1. Use checkbox filters for a search
2. Go to map view - note resources shown on the map
3. Close map view
3. Add filter checkboxes so there are no resources
4. Go back to map view - resources are shown despite none matching the current query
5. These resources can be explored, zoomed in on, and clicked to open"

**Comment by cuahsimarko** [comment]
Unable to reproduce in Chrome, Firefox. Please advise.

**Comment by martinseul** [comment]
stepped through instructions above on chrome:
![image](https://user-images.githubusercontent.com/5427742/101522040-adbfdb00-3954-11eb-884b-50b4234eb8e5.png)

**Comment by cuahsimarko** [comment]
I had to change the zoom level

**Comment by cuahsimarko** [comment]
Fixed locally will be deployed to dev6 with a larger batch of fixes
