### ISSUE TITLE
Deleting 3 Files Takes Up to 12 Seconds

### ISSUE THREAD

**Issue by ghost** [hydroshare/hydroshare#4065]
Steps to reproduce:

1. Create a new resource
2. Upload a tiny text file, maybe 113 bytes
3. Create external content with "add content from the web"
4. Create a folder named "Test"
5. Enter the folder
6. Create external content with "add content from the web"
7. Return to root folder with the up arrow browser
8. Delete the folder and two files
9. Observe wait time

**Comment by cuahsimarko** [comment]
Beta took about 14 seconds for the operation to take place then the page reloads and the spinner continues for another few seconds. Prod takes around 12 seconds, plus or minus. If you create multiple folders and content within them you generally cause an infinitely spinning progress wheel. Operation may or may not complete.

**Comment by cuahsimarko** [comment]
Sometimes creating and deleting just 1-2 files can result in an infinitely spinning pinwheel on macOS / Chrome

**Comment by martinseul** [comment]
@ndebuhr can you check this with the 1.42 release and comment

**Comment by Castronova** [comment]
@martinseul Is this still an issue or has it been resolved?

**Comment by devincowan** [comment]
@martinseul @Castronova I just reproduced this on production v1.54
