### ISSUE TITLE
Creating Multiple Folders with Content Set Infinite Spinning Pinwheel

### ISSUE THREAD

**Issue by cuahsimarko** [hydroshare/hydroshare#4066]
Chrome Browser, HydroShare Production.

Create multiple folders with external content. Delete them. After some time, the operation seems to complete, but pinwheel continues to spin. Unknown if there are additional latent issues at this point.

**Comment by horsburgh** [comment]
I don't think this has anything to do with external content or the number of folders. I created a single folder and then just deleted it without putting anything in it. After deleting the folder, I hover the cursor over the file browser toolbar or file path area and the spinny wheel next to the cursor appears as if something is still happening. The delete of the folder appears to be complete.

**Comment by dtarb** [comment]
In discussion with @pkdash he volunteered to investigate, and may be able to fix, but if it turns out to be systemic in many places may ask @Maurier for input on more general strategy for resolving.

**Comment by devincowan** [comment]
Will take a gander!
