### ISSUE TITLE
Stable Migrations Are Essential

### ISSUE THREAD

**Issue by ironfroggy** [hydroshare/hydroshare#407]
The current setup with some migrations being automatically generated on different machines (as part of the `deploy-hs` script) is unstable. Having the development heads (either the develop or master branches) stand with missing migrations is unstable.

**1)** The missing migrations **must** be committed and merged
**2)** The `makemigrations` command must be a part of creating a new branch, not deployment (running them should be part of deployment, though)
**3)** A policy **must** be adopted that no branch or pull request be accepted for merge that does not provide a complete set of migrations. No branch should be accepted for which the `makemigrations` command would try to generate anything that isn't already included.

**Comment by alvacouch** [comment]
Agreed. Not conforming to this is why we are having so much trouble with migrations.

Alva L. Couch, Ph.D.
Senior Architect, CUAHSI Water Data Center
http://wdc.cuahsi.org
+1 339 221 5400 x 203

**Comment by dtarb** [comment]
I've edited the policies wiki document https://github.com/hydroshare/hydroshare/wiki/Policies-&-Procedures to include this statement.  Please feel free to clarify aspects of it that may not be right or complete.  I noticed much deprecated content in this policy document.  I cleaned up some of it, but not all.  I'll create a separate ticket for wiki clean up to work on.

**Comment by selimnairb** [comment]
@ironfroggy Can you clarify what you mean by "merge" in point 1.  Do you mean taking migrations committed to a feature branch and merging them into develop, and/or also squashing migrations once they are merged into develop?

**Comment by ironfroggy** [comment]
I mean the feature branch being merged into develop.

**Comment by ironfroggy** [comment]
@mjstealey is this resolved by your recent migration resets
