### ISSUE TITLE
Names with Apostrophe Handling

### ISSUE THREAD

**Issue by cuahsimarko** [hydroshare/hydroshare#4070]
My last name O'Brien displays improperly on a resource

![image](https://user-images.githubusercontent.com/45397838/101547031-a78f2600-3977-11eb-862d-268522c4a7ac.png)

**Comment by cuahsimarko** [comment]
Just discovered this is a problem with the user sign-up process and profile edit, not the RLP

**Comment by cuahsimarko** [comment]
Adding an author via RLP gives expected results:

![image](https://user-images.githubusercontent.com/45397838/103699980-c29e8700-4f71-11eb-9e3c-52f8055ddecb.png)

**Comment by cuahsimarko** [comment]
Related to https://github.com/hydroshare/hydroshare/issues/3612

**Comment by eclark-cuahsi** [comment]
Adding @Castronova and @horsburgh for review as this issue pertains to the Resource Landing Page.

**Comment by pkdash** [comment]
Has been fixed as per test on prod.
