### ISSUE TITLE
Add Search By Aggregation Type to SOLR Search

### ISSUE THREAD

**Issue by danames** [hydroshare/hydroshare#4072]
We need the ability to search by aggregation type in SOLR. This needs to be added to API and hs_restclient.

**Comment by Castronova** [comment]
related to #4073

**Comment by cuahsimarko** [comment]
@danames Is this handled by what we discussed about https://dev-hs-6.cuahsi.org/ and the upcoming release? Also, sounds like hs_restclient is working again.

**Comment by danames** [comment]
My testing showed that a REST search such as this one works for finding Discoverable resources by aggregation type:

`https://dev-hs-6.cuahsi.org/discoverapi/?filter={"type":["Geographic%20Raster"]}`

This does not work through hs_restclient but does work through the REST interface directly. It would be good to have it in the client as well.

**Comment by cuahsimarko** [comment]
Does hs_restclient have its own GitHub Repo / Issues area?

**Comment by danames** [comment]
The repo is here: https://github.com/hydroshare/hs_restclient.  This has been the primary access method to HydroShare via Python so we should probably be keeping it up though I don't know who is managing it now/lately.
