### ISSUE TITLE
Cannot delete spatial coverage from a resource when it is a box coverage

### ISSUE THREAD

**Issue by horsburgh** [hydroshare/hydroshare#4087]
Once a spatial coverage for a resource is set to a box, it cannot be deleted. This is problematic as the spatial coverage gets automatically set when some types of aggregations are added to a resource, but the user may intentionally NOT want to have a spatial or temporal coverage. I tried going into edit mode and just deleting the box/point coordinates, but HydroShare throws an error when I click the "save" button indicating that the metadata element cannot be updated.

Oddly, when I change the box coverage to a point coverage and refresh the page, a garbage can icon appears that allows me to delete the spatial coverage.  The same garbage can icon needs to be added to enable deleting spatial coverage when it is a box coverage.

**Comment by cuahsimarko** [comment]
Related to https://github.com/hydroshare/hydroshare/issues/4009

**Comment by soumyapurohit** [comment]
@horsburgh 
Hi, I am trying to fix this issue. Can you point to a resource that I can use to reproduce the issue?
Thanks!

**Comment by horsburgh** [comment]
Hi @soumyapurohit - here's some steps to reproduce this. You can just create a new resource that will show this:

1. Create a new resource
2. Set the spatial coverage by clicking on the box icon at the top of the google map and drawing a box coverage.
3. Click the "Save Changes" button to apply the spatial coverage
4. Exit edit view by clicking the view resource button at the top of the page (left pointing arrow button)
5. Click on the edit resource button (the pencil)
6. Delete the latitude and longitude values from the text boxes
7. Click the "Save Changes" button
8. HydroShare throws an error that says "Error! Metadata failed to update.

I see that @cuahsimarko just mentioned this in #4009
