### ISSUE TITLE
Resource legends are out-of-sync between Discover and My Resources

### ISSUE THREAD

**Issue by hydrocheck** [hydroshare/hydroshare#4089]
The updated legend in Discover is not reflected in My Resources.  For example, the "Script Resource" is missing in My Resources, and the "Pending publication" capitalization differs between the two.
<img width="1149" alt="discover" src="https://user-images.githubusercontent.com/43424907/104078822-fab1fe00-51ed-11eb-9c16-6e5e9610b71e.png">
<img width="952" alt="my-resources" src="https://user-images.githubusercontent.com/43424907/104078824-fd145800-51ed-11eb-9c20-35663e766463.png">

**Comment by martinseul** [comment]
Script  Resources are obsolet need to be removed from legend on discover

**Comment by ClaraCogswell** [comment]
What is the status of updating the legend?

**Comment by horsburgh** [comment]
We should probably fix this comprehensively. There are also legends at the bottom of the group and community resource listings that need to be fixed. I'm not sure how modular those are, but if we could fix it once as part of the group/community work and then copy to the other pages, it would be great.

**Comment by eclark-cuahsi** [comment]
@ClaraCogswell and @Maurier -- this issue was duplicated by #4357 which has now been completed and closed. Can this issue be closed as well? Thanks!

**Comment by ClaraCogswell** [comment]
It can be closed as far as I am concerned!

**Comment by eclark-cuahsi** [comment]
Looks like the inconsistent capitalization on 'Pending publication' and 'Not shareable' still persists. This is also now noted in #4443.

**Comment by devincowan** [comment]
Closing because it looks like #4443 covers this now
