### ISSUE TITLE
My Resources page does not consistently load

### ISSUE THREAD

**Issue by hydrocheck** [hydroshare/hydroshare#4091]
After 10 seconds of attempted loading, the my-resources page will bring up a Django error.  Even on a gigabit internet connection, this is relatively repeatable for a setup of ~200 resources and ~30 GB total resource quota usage.  It feels like a timeout as the page slowly loads.

<img width="1509" alt="my-resources-loading" src="https://user-images.githubusercontent.com/43424907/104078974-c25eef80-51ee-11eb-9236-f45cbb6f1c0a.png">

**Comment by dtarb** [comment]
@martinseul @hydrocheck is this still an issue.  @pkdash and I were reviewing bugs.  Loading My Resources is slow - granted - but we do not get a Django error on my page that has 200+ resources.

**Comment by devincowan** [comment]
@dtarb @martinseul I don't get a timeout over a gigabit connection but loading 185 resources on production takes ~10sec which does feel like a long time.
Here is a performance profile:
https://share.firefox.dev/3EV5AwU
I don't have much experience reading these but there is jank slowing things up in our JS--specifically it looks like jQuery spends a lot of time building the table for the resources...

**Comment by dtarb** [comment]
@devincowan I've put this on the agenda for a brief discussion on the call today.  It would be good for you, @Maurier, @sblack-usu, @alvacouch and @pkdash to put heads together and assess whether there is low hanging fruit to improve these performance issues.

**Comment by devincowan** [comment]
it is a good point that @alvacouch and others made that while there are some [slowdowns with the JS](https://share.firefox.dev/3KtD0Uw) our biggest issue is the delay in response before js even gets to work. Sounds like we might be able to make gains with the postgres queries/[annotations](https://github.com/hydroshare/hydroshare/blob/d633226430fd5a4f93d6aa137cb95ec7bbb088ad/hs_core/views/utils.py#L558)

**Comment by pkdash** [comment]
@devincowan  A long time ago (six months or so) I did some testing where I noticed there were about 14 queries per resource. So if we are listing 200 resources that would be 2800 queries.  At that time I did some code change for the purpose of testing and I was able to reduce the number of queries from 14 to  6 per resource. But I noticed only minor improvement to page load time.

**Comment by pkdash** [comment]
Thanks @devincowan. We should get at least 30%-40% improvement in page load time for my resources. I am also applying the same optimization to resource listing in profile page.

**Comment by devincowan** [comment]
I'm reopening this issue because I've noticed that the queries on My Resources page is still scaling linear O(n)
