### ISSUE TITLE
enable nginx heartbeat queries for outer and inner proxies

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#4095]
In determining what is causing the site to fall down, it is necessary to be able to query the status of the NGINX outer and inner server statuses. This should be done in http, so that the servers can be queried directly instead of via the proxy chain.

**Comment by martinseul** [comment]
@alvacouch is this ticket still relevant or can it be closed?

**Comment by alvacouch** [comment]
Done.
