### ISSUE TITLE
profile page email editing does not save changes

### ISSUE THREAD

**Issue by martinseul** [hydroshare/hydroshare#4097]
A user pointed to a problem with the profile page. 

Editing the email address and saving does not save the changes. This seems to be a regression.

@hyi @sblack-usu could you coordinate and take a look at it?

**Comment by sblack-usu** [comment]
I verified I could change my email as well.  A notification at the top tells me to click the verification email.  The email address does not update until I do so.  If I attempt with an email that is already in use, I get a notification at the top telling me the email is in use already.  Are you having trouble changing your email address @martinseul ?

**Comment by horsburgh** [comment]
Closing this issue given that neither @hyi  or @sblack-usu could duplicate it.
