### ISSUE TITLE
Put resource versioning into async task framework

### ISSUE THREAD

**Issue by hyi** [hydroshare/hydroshare#4109]
Put resource versioning into async task framework, while trying to fix the issue #4028.

**Comment by martinseul** [comment]
@hyi, is this bug part of the async functionality if so can this be closed

**Comment by hyi** [comment]
Deployed, so closing.

**Comment by aaraney** [comment]
@hyi can you ref the pr(s) that resolved this?

**Comment by hyi** [comment]
@aaraney Here is the PR https://github.com/hydroshare/hydroshare/pull/4116 that resolved this.
