### ISSUE TITLE
Clicking Confirmation to Delete a Resource a Second Time Fails

### ISSUE THREAD

**Issue by cuahsimarko** [hydroshare/hydroshare#4118]
To Recreate:

- Delete resource
- While still processing, click Delete a second time

on beta, there is a debug screen. On Prod there is a message:

![image](https://user-images.githubusercontent.com/45397838/106502019-d4504d00-6491-11eb-9722-a8c9c317196f.png)

In the frontend, disable the Delete button after being activated by click, tab/spacebar or return/enter keypress

**Comment by hyi** [comment]
@cuahsimarko I did this in my PR https://github.com/hydroshare/hydroshare/pull/4116 to disable resource versioning button after it is clicked, so can take care of this issue in the same way. Feel free to assign it to me if you want me to replicate the same logic for versioning to handle the delete case.

**Comment by cuahsimarko** [comment]
Sounds great! For the button disable, if you can avoid jQuery, please do. I'm happy to help via email if it saves you any time. VueJS might give you an option or a plain JS document.getElementById is always reliable and simple.

**Comment by martinseul** [comment]
@hyi, is this bug part of the async delete functionality

**Comment by hyi** [comment]
@martinseul Yes, it is part of the async delete functionality. @cuahsimarko You can test it out once the next release is out and see if this issue is fixed and can be closed.

**Comment by hyi** [comment]
This has been fixed as part of moving resource deletion to async. Closing.
