### ISSUE TITLE
Discover does not filter when dashes are part of the search term

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#4131]
Many model my watershed resources use the keyword “model-my-watershed” as this was part of the design of HydroShare Model My Watershed interoperability.  However "model-my-watershed" and model-my-watershed (with and without quotes) does not filter to these resources.

**Comment by martinseul** [comment]
@cuahsimarko, could you please take a look

**Comment by cuahsimarko** [comment]
Related to or duplicated by https://github.com/hydroshare/hydroshare/issues/3293

**Comment by cuahsimarko** [comment]
@martinseul this is a known limitation and is congifured in SOLR/Haystack and associated Indexing code. Alva can update this.

**Comment by dtarb** [comment]
@pkdash I tested this on https://cuahsi-dev-2.hydroshare.org/ where the PR is deployed and it appears to work correctly.

**Comment by ClaraCogswell** [comment]
Is this ready for closure?

**Comment by martinseul** [comment]
not yet, in general tickets should be closed by the developer once the PR is approved, the code is merged and the PR is tagged in a release. If an issue is found on beta during QA the issue will be reopened.
