### ISSUE TITLE
GeoServer Not Automatically Updating for Removed Content

### ISSUE THREAD

**Issue by jcalhoon96** [hydroshare/hydroshare#4133]
When using the new OGC web services feature through GeoServer, if the contents of the resource change or are removed then the resource needs to be made private and then public again before the changes will carry over to GeoServer. GeoServer seems to update automatically when new data is added but not when data is removed.

Here is the public resource https://www.hydroshare.org/resource/ff3cdc42641f468b823593354e96be87/ . 
![image](https://user-images.githubusercontent.com/59626843/108248945-ae71ac00-7111-11eb-9613-01c82e2e8d3b.png)

Checking the resource on www.geoserver.hydroshare.org provides the following information, which is accurate to the current resource.
![image](https://user-images.githubusercontent.com/59626843/108249323-2c35b780-7112-11eb-8f12-8f66569cfc4f.png)

Adding a new shapefile to the resource while it is still public (Utah Lake shapefile added)
![image](https://user-images.githubusercontent.com/59626843/108249881-d6adda80-7112-11eb-8ded-b0a21fb98852.png)

Rechecking the resource on www.geoserver.hydroshare.org and the new shapefile is present.
![image](https://user-images.githubusercontent.com/59626843/108260962-3199fe80-7120-11eb-9b70-4378d241ccd0.png)

Now remove the added shapefile (Utah Lake), save the resource, and return to GeoServer. The Utah Lake shapefile is still there.
![image](https://user-images.githubusercontent.com/59626843/108262476-36f84880-7122-11eb-9cd6-9b01deae4bd7.png)

Changing the resource to private and then back to public will fix this issue.
![image](https://user-images.githubusercontent.com/59626843/108265311-d4a14700-7125-11eb-894c-8bfac65fbb19.png)

**Comment by kjlippold** [comment]
HydroShare isn't sending update requests to GeoServer when files are deleted. There was already a signal for this action, so it just needed to be set up to trigger the GeoServer update task.

PR with the fix: https://github.com/hydroshare/hydroshare/pull/4290/commits/d1e4e600a6c05f1024ad02a459d07e13479b0532
