### ISSUE TITLE
Inactive user in sharing permissions causes resource to return 403 for all requests

### ISSUE THREAD

**Issue by sblack-usu** [hydroshare/hydroshare#4134]
If a user is given access permissions for a resource and later the user is inactivated, it causes a 403 to be returned for all users, (anonymous, owner, and even admin).  This is caused by the page permission processor checking for users who can undo share resource with user access and returning a 403 when a user with the access is inactive.

https://github.com/hydroshare/hydroshare/blob/develop/hs_core/models.py#L265-L281

```python
    if request.user.is_authenticated():
        for owner in owners:
            owner.can_undo = request.user.uaccess.can_undo_share_resource_with_user(cm, owner)

        for viewer in viewers:
            viewer.can_undo = request.user.uaccess.can_undo_share_resource_with_user(cm, viewer)

        for editor in editors:
            editor.can_undo = request.user.uaccess.can_undo_share_resource_with_user(cm, editor)

        for view_grp in view_groups:
            view_grp.can_undo = request.user.uaccess.can_undo_share_resource_with_group(cm,
                                                                                        view_grp)

        for edit_grp in edit_groups:
            edit_grp.can_undo = request.user.uaccess.can_undo_share_resource_with_group(cm,
                                                                                        edit_grp)
```

[Permission Denied for the inactive user](https://github.com/hydroshare/hydroshare/blob/9514f2eed3439553b046126ae3dbdd8290b817a5/hs_access_control/models/user.py#L2185)

While I haven't verified this, it looks like the same problem will occur if a group is given access to a resource and later inactivated.
[Permission Denied for the inactive group](https://github.com/hydroshare/hydroshare/blob/9514f2eed3439553b046126ae3dbdd8290b817a5/hs_access_control/models/user.py#L2277)

**Comment by alvacouch** [comment]
@dtarb @martinseul It looks like the root of all evil is throwing an exception and stopping all processing when a user is inactive. The fix seems to be to simply return False for requests instead. This indicates that the permission to undo is not granted, but that the request itself is not in error. The same fix would apply to inactive groups. 

The original logic behind throwing an exception was that something was seriously wrong and that the user should not have even tried this. This logic does not seem to apply to when the user in question is inactive.

Fixing the code is simple. Fixing the tests is another issue. This is deeply tested code.

**Comment by alvacouch** [comment]
Addressed in recent PR.
