### ISSUE TITLE
Clicking the license link during a resource download opens in the same tab

### ISSUE THREAD

**Issue by hydrocheck** [hydroshare/hydroshare#4146]
This is possibly disruptive to the download flow, and could seemingly benefit from a shift to opening in a new tab.

![008](https://user-images.githubusercontent.com/43424907/108944017-e607b900-7627-11eb-87ef-4c9aeb2c4970.png)

**Comment by dtarb** [comment]
In discussing with Pabitra he said this was very easy so I asked him to just do it, even though on backlog.
