### ISSUE TITLE
The multi-select "Preview" consistently opens up a blank tab and does nothing

### ISSUE THREAD

**Issue by hydrocheck** [hydroshare/hydroshare#4147]
![009-01](https://user-images.githubusercontent.com/43424907/108944042-f9b31f80-7627-11eb-81c1-7165992ad2be.png)
![009-02](https://user-images.githubusercontent.com/43424907/108944044-fae44c80-7627-11eb-8317-2d842b7ec1d6.png)

**Comment by pkdash** [comment]
This has been fixed in 1.50 - tested on prod. So closing.
