### ISSUE TITLE
The "All required fields are completed" publication message repeatedly arises

### ISSUE THREAD

**Issue by hydrocheck** [hydroshare/hydroshare#4149]
1. Add a file to a resource that is otherwise publishable
2. Observe the publication message
3. View, then edit the same resource
4. Add a file and observe the same _the resource is now publishable_ message
   5. This is a bit misleading, as adding the 10th file to a resource, for example, does not actually change it's publishability

![011](https://user-images.githubusercontent.com/43424907/108944106-22d3b000-7628-11eb-9e99-083c6bba9ac4.png)

**Comment by pkdash** [comment]
This has been fixed in 1.50 release - tested on prod. So closing.
