### ISSUE TITLE
Previewing folders generates a Django error page - SessionException

### ISSUE THREAD

**Issue by hydrocheck** [hydroshare/hydroshare#4157]
![020-01](https://user-images.githubusercontent.com/43424907/108944469-ce7d0000-7628-11eb-958c-2cb17b9d4b5e.png)
![020-02](https://user-images.githubusercontent.com/43424907/108944475-d046c380-7628-11eb-8a08-1b63bc5beb58.png)

**Comment by horsburgh** [comment]
I think this is a bug. Does the "Preview" item work at all for anything in the file browser?

**Comment by pkdash** [comment]
This has been fixed in 1.50 - tested on prod. So closing.
