### ISSUE TITLE
public resource without content

### ISSUE THREAD

**Issue by martinseul** [hydroshare/hydroshare#4164]
Started with a public resource with multiple geographic features copy of https://www.hydroshare.org/resource/1c8ffe88d6ec46bca853fd836bd2948e/ when I delete the folders one by one I can delete all files in the content manager and the resource is still public, this is not an allowed state as all public resources need content.

**Comment by Castronova** [comment]
I tested this by cloning your resource and deleting all its contents. At the top of the resource landing page it indicated that the resource was still "public" even though all its data was removed. However when I exited edit mode, the status was changed to private as expected.
