### ISSUE TITLE
Delete of a discoverable resource corrupts SOLR

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#4166]
It was recently "discovered" that if you delete a discoverable or public resource, SOLR gets corrupted, because the Haystack mechanism for removing the resource fails. The fix is to make the resource undiscoverable before deleting it.

**Comment by devincowan** [comment]
Unsuccessful attempt to reproduce this on HS v 2.6.1. My steps:

1. Create a new resource and make it discoverable
2. Verify that I can find it in Discover UI
3. Delete the resource
4. Verify that I can't find the resource in Discover UI (queries on all relevant fields)
