### ISSUE TITLE
Incomplete refactor of bag.url for new iRODS BagIt creation workflow

### ISSUE THREAD

**Issue by selimnairb** [hydroshare/hydroshare#417]
There remain several references to bag.url in templates and views that need to be converted to IrodsStorage.url(pk):
1. [resource_api](https://github.com/hydroshare/hydroshare/blob/develop/hs_core/views/resource_api.py#L566)
2. [ref_ts.templates.pages.res.html](https://github.com/hydroshare/hydroshare/blob/develop/ref_ts/templates/pages/res.html#L83)
3. [resource_aggregation.templates.pages.resourceaggregation.html:45](https://github.com/hydroshare/hydroshare/blob/develop/resource_aggregation/templates/pages/resourceaggregation.html#L45)
4. [resource_aggregation.templates.pages.resourceaggregation.html:52](https://github.com/hydroshare/hydroshare/blob/develop/resource_aggregation/templates/pages/resourceaggregation.html#L52)

**Comment by hyi** [comment]
@selimnairb I am reassigning this to you as we discussed. I think you are at the best position to make bag url changes accordingly across the board in conjunction with your url improvement work in your api bagit branch. Let me know if you need me to do anything, though.

**Comment by selimnairb** [comment]
I fixed this for [resource_api](https://github.com/hydroshare/hydroshare/blob/develop/hs_core/views/resource_api.py#L566), but this code doesn't appear to be called yet, so I couldn't really test it.

**Comment by selimnairb** [comment]
@danames Could you have someone in your group look at: [ref_ts.templates.pages.res.html](https://github.com/hydroshare/hydroshare/blob/develop/ref_ts/templates/pages/res.html#L83)

**Comment by selimnairb** [comment]
@pkdash Could you fix this for the following? 

3. [resource_aggregation.templates.pages.resourceaggregation.html:45](https://github.com/hydroshare/hydroshare/blob/develop/resource_aggregation/templates/pages/resourceaggregation.html#L45)

4. [resource_aggregation.templates.pages.resourceaggregation.html:52](https://github.com/hydroshare/hydroshare/blob/develop/resource_aggregation/templates/pages/resourceaggregation.html#L52)

**Comment by selimnairb** [comment]
@pkdash @danames Pinging on this issue...  Setting for 1.6.1 milestone ...

**Comment by mjstealey** [comment]
@selimnairb - is this still an issue?

**Comment by hyi** [comment]
@zhiyuli I am putting this on your plate for further investigation to see what remains to be done.

**Comment by zhiyuli** [comment]
Old Reference Time Series Type issue. Closing
