### ISSUE TITLE
Navbar CSS and JS

### ISSUE THREAD

**Issue by cuahsimarko** [hydroshare/hydroshare#4171]
Now that the navbar has been modularized, the CSS needs to be more explicitly defined and less susceptible to inheritance, such as bootstrap versions, hydroshare_core.css, <style> tags across any number of Django templates as well as other {% includes %} and inline styles. Making navbar more self-sufficient in this regard can clean up other code and lock-in the desired navbar, while making future edits easier.

JavaScript should be consolidated and aligned with a uniform VueJS strategy across base.html, {% includes %} {% extends %}, globally scoped JS and <script> includes.

**Comment by eclark-cuahsi** [comment]
Discussed with @martinseul and we are closing this issue.
