### ISSUE TITLE
Discovering composite resources 

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#4179]
It has recently come to my attention that most of the discovery values for a resource are now blank, because all resources have been migrated to composite form!  This is probably why discovery functions so poorly in other issues. Much of the metadata currently associated with discovery has been moved into composite file types.  Thus, the searchable fields for discovery need to be re-engineered for these new data types. 

The problem with the new format is that there are many "hidden fields" that are not readily accessible to users. For example, there are `abstract`, `method`, etc for **files**.  So, I'm between a rock and a hard place on exposing these in discovery: 

1. Not exposing them lacks precision; there may be resources that the user will not see. 
2. Exposing them in discovery without exposing them on the resource home page confuses users who might have no idea why this particular resource came up in discovery.

**Comment by horsburgh** [comment]
@alvacouch - even though other resource types have been migrated to composite resources, all resources, regardless of type had the standard Dublin Core metadata at the resource level. That metadata was preserved in any migrations to composite. So, primary focus for discovery would first be all of the resource-level metadata, followed by aggregation-level metadata - if we can enable that.

Number 1 is only a problem if we create the expectation that discovery should work beyond resource-level metadata.

All metadata for composite resources - both resource-level and aggregation-level are exposed on the resource landing page, so I don't think 2 is a problem except for users who may not know that they need to click on content files to see aggregation-level metadata.

**Comment by alvacouch** [comment]
@horsburgh I have already checked that Dublin core metadata is working. The aggregation metadata, however, leaves much to be desired. I have harvested the concept of "variable" from several of the underlying aggregation types. I am also working on a mystery, which is how the file "keywords" become resource-level Dublin-core "subjects" in harvesting. I know this happens because I recently tested it.

**Comment by alvacouch** [comment]
@Castronova I am actively working on this and have scheduled a discussion of the issues involved in design for the stakeholder call tomorrow.
