### ISSUE TITLE
Fix Invalid JSON in Schema.org

### ISSUE THREAD

**Issue by horsburgh** [hydroshare/hydroshare#4184]
The DataONE group has reviewed our Schema.org implementation and has found some errors caused by invalid JSON. This resource is an example:

https://www.hydroshare.org/resource/8161a96a08474d12bba219852409be61/

In this resource, there is a custom license that has been entered by the HydroShare user. The text of that license makes the JSON-LD invalid because it contains unescaped line breaks (should be "\n") in the license text. This may also be an issue for other fields where the user can enter free text (e.g., Abstract). I'm assuming the sources, related resources, and funding agency information entries on the landing page do not allow line breaks and so would not have this issue.

**Comment by sblack-usu** [comment]
>I'm assuming the sources, related resources, and funding agency information entries on the landing page do not allow line breaks and so would not have this issue.
I don't think we can make that assumption. You may not be able to enter a newline through the web UI, but I'm not seeing anything restricting it through the API and the database.

**Comment by hyi** [comment]
@sblack-usu Good point. I just made a commit to escape funding agency name and relation value as well just on the safe side.
