### ISSUE TITLE
Support a search filter by Country

### ISSUE THREAD

**Issue by amabdallah** [hydroshare/hydroshare#4186]
Simple question, show me a map for all the data in HydroShare in the USA (cluster points are fine) or any other selected country (e.g., Eygpt) if any. The discover filters don't seem to support this search. 

I typed "United States" in the search bar but it seems to exclude so much data from the US and there is a dataset for "Western Sahar." So the search seems to probably work if the author has a text=United states". 

I was looking to take a screenshot of the map showing CUAHSI/HydroShare as a repository for water/environmental data in the US as a data source along with other national sources such as USGS, EPA, BOR, etc. In a general example, a user could be interested in any data in their country. 

![image](https://user-images.githubusercontent.com/3268971/112905791-4024ef80-90a8-11eb-9657-8d41a5492e2f.png)

**Comment by amabdallah** [comment]
A potential simple solution would be in adding a Spatial Coverage Filter. So the user would draw a box around the area of their interest to limit the search to that boundary. The Country filter can be tricky if users do not provide it as metadata. Trying to intersect data sites with countries on the fly or in the backend, may take a lot of time to build. 
 
I guess, the country could be less interesting compared to a watershed-based search. For example, **show me all the data within the Colorado River Basin**. It is probably easier to use the API, in that case, to query datasets within a given polygon. I'm not sure if this feature is supported. Would that polygon be in GeoJSON?
![image](https://user-images.githubusercontent.com/3268971/112906548-934b7200-90a9-11eb-8d6d-f190b7ddf65a.png)

**Comment by martinseul** [comment]
Adel,

thank you for your suggestion and we are looking into extending the ability for users to search spatially. It's a bit tricky as you said as the quality of spatial information depends on the publisher and can vary. 
We do have some ability to search via the API (https://www.hydroshare.org/hsapi/ ) where you can specify a location or an extend unfortunately not via geojson. 
I've added your ideas to our log of ideas for enhancements and will close this ticket, you can always reopen it of you have additional comments or ideas. 
Thanks again
Martin
