### ISSUE TITLE
check_irods_files Identifies too many resources

### ISSUE THREAD

**Issue by cbcunc** [hydroshare/hydroshare#4191]
@alvacouch The check_irods_files management command misidentifies resources as not in sync between iRODS and Django as a result of including meta.xml and resmap.xml files in results. The command may also end in a non-zero exit code when detecting any inconsistencies between iRODS and Django. Thus when the command is used in a Jenkins job, it always appears to fail. We need this command to work for disaster recovery purposes which need to be completed relatively soon. It would also be good if there were options for the command to simply return a list of resources in iRODS but not Django and vice versa. In order to use the output for disaster recovery automation, there is significant noise in the output to have to parse. Not sure what the right output should be because not sure yet if upcoming bag ingestion semantics will allow for granularity of what files in a bag a re-ingested. Possibly check with @sblack-usu, @horsburgh @dtarb.

**Comment by sblack-usu** [comment]
I can look into this and try to work it out. There is a check for aggregation XML files, but it doesn't look like it's working.  https://github.com/hydroshare/hydroshare/blob/develop/hs_core/management/utils.py#L261
