### ISSUE TITLE
Update local-dev to build indexes dymamically instead of inside the prebuilt docker image

### ISSUE THREAD

**Issue by sblack-usu** [hydroshare/hydroshare#4198]
Currently anytime solr indexes are changed a new docker image has to be built.  The solr indexes are not a heavy lift and we should have the ability to update them dynamically just like hsctl. Update local-dev-first-start-only.sh to build the schema dynamically.  Once this is done the prebuilt image will be irrelevant and the repository may be removed.

https://github.com/hydroshare/hs-solr/

The other Docker images in local-dev.yml can likely be updated in a similar manner.

**Comment by alvacouch** [comment]
I think this will help normal mortals update SOLR.
