### ISSUE TITLE
Consolidating the OGC Web Services WMS and WCS URL endpoints to match the WFS endpoint

### ISSUE THREAD

**Issue by jcalhoon96** [hydroshare/hydroshare#4199]
When using the the current WCS URL in QGIS, the result will pull every resource that contains an available WCS endpoint. regardless of the resource ID used. The URL change will fix this issue. The WMS URL change makes no difference for the final output but is being doing to keep the URL endpoints uniform. 

The current code for the web service endpoints as used in the hydroshare/models.py at line 588 is

                  `wms_url = (
                        f'{settings.HSWS_GEOSERVER_URL}/wms?'
                        f'service=WMS&'
                        f'version=1.3.0&'
                        f'request=GetCapabilities&'
                        f'namespace=HS-{self.short_id}'
                    )
                else:
                    wms_url = None

               if 'GeographicFeature' in resource_data_types:
                    wfs_url = (
                        f'{settings.HSWS_GEOSERVER_URL}/HS-{self.short_id}/wfs?'
                        f'request=GetCapabilities'
                    )
                else:
                    wfs_url = None

                if 'GeographicRaster' in resource_data_types:
                    wcs_url = (
                        f'{settings.HSWS_GEOSERVER_URL}/wcs?'
                        f'service=WCS&'
                        f'version=1.1.0&'
                        f'request=GetCapabilities&'
                        f'namespace=HS-{self.short_id}'
                    )
                else:
                    wcs_url = None`

**Comment by martinseul** [comment]
closing is part of 1.44
