### ISSUE TITLE
Clarify delete file warning

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#42]
The wording on the warning about deleting the resource file needs to be changed. 

I suggest.
“Confirm file deletion.
This will delete the file from the resource.  Consider saving a copy if it is important to you.”

![capture](https://cloud.githubusercontent.com/assets/3456833/5604085/55a43e54-9363-11e4-920f-0ca79b7fc04c.JPG)

It is not true to say that a copy is not retained by HydroShare.  Right now, even after deleting a file I can export the previous version of the resource to retrieve the file.  This functionality may change in the future, but copies may be kept deep somewhere in our backups.  We need to be careful not to promise things that may not be true.
![capture](https://cloud.githubusercontent.com/assets/3456833/5604091/80ba1e60-9363-11e4-90c9-5ad45fabc61f.JPG)

**Comment by hyi** [comment]
Fixed and changed wording exactly as suggested. Fix pushed into github AGU branch, to be merged into master and reflected in alpha. Closing issue for now for later verification.

**Comment by hyi** [comment]
Reopen the issue and attach a "Ready to test" label as Dave suggested.

**Comment by dtarb** [comment]
Thanks for this change.  Closing.
