### ISSUE TITLE
Copying citation includes a bunch of unnecessary spaces and line breaks

### ISSUE THREAD

**Issue by horsburgh** [hydroshare/hydroshare#4200]
If you click the button to copy the citation on a resource's landing page, it copies the citation to the clipboard, but includes a bunch of leading spaces and line breaks as well as some trailing spaces and line breaks. The result is that when you paste it somewhere, you have to go back and delete the cruft. Not sure why they are there, but they shouldn't be. Example after pasting into Microsoft Word:

![image](https://user-images.githubusercontent.com/3485902/114226978-96f4b980-9931-11eb-8883-15ef1925fbbf.png)

**Comment by sblack-usu** [comment]
Here is the relevant code, it's a bit of a mindbender, but a trim() on the target textContent should resolve the issue.  https://github.com/hydroshare/hydroshare/blob/develop/theme/static/js/copyToClipboard.js#L12
