### ISSUE TITLE
Resource types in filtering should be labeled the same as resource types in resource creation

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#421]
The filtering interface uses the following resource type labels
![untitled](https://cloud.githubusercontent.com/assets/3456833/7886981/fde9dd90-05ea-11e5-9647-69ab8f077e53.png)

However in creating a resource the following labels are used
![untitled](https://cloud.githubusercontent.com/assets/3456833/7887021/43f3076c-05eb-11e5-8715-8399863d6a7d.png)

These should be consistent.  The filter labels should be changed to the same as the creation labels.

**Comment by ironfroggy** [comment]
Does not apply to new My Resource page
