### ISSUE TITLE
A required state field for user profiles may not make sense for some countries

### ISSUE THREAD

**Issue by hydrocheck** [hydroshare/hydroshare#4232]
If you go to the profile page, you'll note that state is a required field.  It may benefit usability to remove the requirement.

https://www.quora.com/Is-there-any-country-without-states

<img width="621" alt="006-02" src="https://user-images.githubusercontent.com/43424907/118430129-5b23e100-b6a1-11eb-9b09-4288646ff6c0.png">

<img width="339" alt="006" src="https://user-images.githubusercontent.com/43424907/118429986-041e0c00-b6a1-11eb-9f06-85904cb7b96e.png">

**Comment by dtarb** [comment]
I would prefer to go with "Country" and "State/Region"  

I think that Nation and subnational division are highly unnatural.  Country is what people think of.  Within country entities are states within the US and regions or provinces elsewhere.  I think "State/Region" captures what we need concisely without adding the word province or other similar words.  Region is sufficiently inclusive.

**Comment by martinseul** [comment]
I agree with Dave.

**Comment by devincowan** [comment]
Thanks, works for me! I've reverted to "State/Region"
