### ISSUE TITLE
Country codes are not considered in profile phone number validation, so ambiguous phone numbers are possible

### ISSUE THREAD

**Issue by hydrocheck** [hydroshare/hydroshare#4235]
I believe it's possible to have ambiguous phone numbers, given the current HS phone number validation strategy.  This arises if we don't know if the user specified a country code or not (seemingly the case).  For example: 3655410945 could be interpreted as a valid Budapest, Hungary number (+36 30 901 820) or a valid Toronto, Canada number (+1) 363 090 1820

https://github.com/google/libphonenumber
https://libphonenumber.appspot.com/

**Comment by eclark-cuahsi** [comment]
@Castronova I believe this is an issue related to the User Profile.

**Comment by devincowan** [comment]
related to https://github.com/hydroshare/hydroshare/issues/2872

**Comment by devincowan** [comment]
@martinseul how do we feel about the assumption that phone number should conform to the user's selected "country" in their profile?

**Comment by martinseul** [comment]
ideally yes, but phone numbers are less important and likely to change so I'd be fine with a validation for us phone numbers and free text for the rest

**Comment by devincowan** [comment]
My implementation will force phone number to conform to the expected format based on the "country" in the user profile.
I just wasn't sure if we were concerned about the edge case of someone having a phone number in a country not matching their profile. Seems like it would be a pretty rare edge case.
