### ISSUE TITLE
Metadata editing inconsistency for published resources

### ISSUE THREAD

**Issue by hydrocheck** [hydroshare/hydroshare#4236]
Based on the specification in https://github.com/hydroshare/hydroshare/issues/2559, spatial and temporal metadata should probably be editable and deletable post-publication.  This metadata is editable, like unpublished resources.  However, it is not deletable, like unpublished resources.

**Comment by dtarb** [comment]
@horsburgh please evaluate if a change is needed.  This is being assigned to you as a trial of our new approach to working with issues among Tony, Emily, Martin and me.

**Comment by horsburgh** [comment]
I think this is an oversight that needs to be fixed. Given that we have made the spatial and temporal coverage metadata editable after publication, they should be both editable and deleteable.

**Comment by pkdash** [comment]
This has been fixed - tested by @horsburgh  on prod.
