### ISSUE TITLE
"mp_file_types" charcter limit error when setting file types in Model Program aggregation

### ISSUE THREAD

**Issue by hydrocheck** [hydroshare/hydroshare#4251]
https://beta.hydroshare.org/resource/213a2ec4fcf249d8b178b116de83c32d/ "Aggregations" aggregation.

Updating the content file types in the aggregation metadata (seemingly any file to any file type) raises a rather cryptic mp_file_types error.

<img width="1918" alt="004" src="https://user-images.githubusercontent.com/43424907/119352416-a9238080-bc6f-11eb-9609-01aac3dc9ef8.png">

**Comment by imanmaghami** [comment]
I was able to reproduce the same error when the sum of the characters of the uploaded content files names + the selected file types characters (e.g., Computational Engine) for all uploaded content files exceeded 255 characters.

**Comment by eclark-cuahsi** [comment]
@horsburgh and @goodalljl I believe this falls under Resource Model -> Model Instance aggregation. Can you please review and determine if this is a bug or an enhancement and label accordingly. Thank you.
