### ISSUE TITLE
Button label accuracy in JSON schema hide/show for model instance/program aggregations

### ISSUE THREAD

**Issue by hydrocheck** [hydroshare/hydroshare#4252]
After "Show Model..." to see the JSON schema, it's not clear how to hide the JSON.  It looks like the standard mechanism for that is clicking "Show..." again, but changing it to "Hide..." would make that more clear.

<img width="1131" alt="006" src="https://user-images.githubusercontent.com/43424907/119352465-b93b6000-bc6f-11eb-91b0-01a9f76fc031.png">

**Comment by eclark-cuahsi** [comment]
@horsburgh and @goodalljl I believe this falls under Resource Model -> Model Instance aggregation. Labeling as an enhancement as it seems to pertain to styling.

**Comment by pkdash** [comment]
@horsburgh The text of the button to show/hide metadata schema has been changed to indicate that the same button can be used a toggle to show/hide the schema (you can test this on prod) as shown here. 

![image](https://user-images.githubusercontent.com/2523434/217856452-ddb73344-cf78-4682-8368-c8f0c0033d08.png)

Wondering if we can close this issue.

**Comment by horsburgh** [comment]
Assuming this is in production, it can be closed.
