### ISSUE TITLE
Celery needs an upgrade

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#4255]
In trying to get asynchronous SOLR updates running, I found that our current celery instance is really messed up. 

1. Workers run as root. Fortunately we haven't asked them to create files, which would create havoc. 
2. Logging is messed up enough that simply trying to log a message will stop a celery scheduled task.
3. When celery tasks abort, there is no logged message to that effect.  
4. Logged messages go nowhere at all. 
5. Our version is too old for there to be any online documentation on how to fix it. 
6. The newest version is specific to Python 3. 

From these factors, I conclude that a complete redeployment of the current version (5.1) -- several versions ahead of what we are running (2.1) -- is in order. 

3rd party file exchange depends upon this upgrade. The file receiver is a celery task!

The name of the celery container is also silly. "defaultworker" contains no information that celery is involved.

**Comment by dtarb** [comment]
Alva indicates he has done this.
