### ISSUE TITLE
Error deleting file in Reference time series

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#426]
I clicked on the button to delete a file in a reference time series resource and received the following error.  Now I recognize that deleting a file may not make sense, but then the issue is that the delete button should not be shown.  @danames I'm assigning this to you since you are the champion for Ref Time series.  Please re-assign to the person on your team to work on this.

Environment:

Request Method: GET
Request URL: http://dev.hydroshare.org/hsapi/_internal/1b96e6bf7d0b43dbbcda9c562c48c0d8/delete-resource-file/12/

Django Version: 1.7.8
Python Version: 2.7.6
Installed Applications:
(u'mezzanine.boot',
 u'django.contrib.auth',
 u'django.contrib.contenttypes',
 u'django.contrib.redirects',
 u'django.contrib.sessions',
 u'django.contrib.sites',
 u'django.contrib.sitemaps',
 u'django.contrib.gis',
 u'inplaceeditform',
 u'django_nose',
 u'django_irods',
 u'theme',
 u'theme.blog_mods',
 u'mezzanine.conf',
 u'mezzanine.core',
 u'mezzanine.generic',
 u'mezzanine.blog',
 u'mezzanine.forms',
 u'mezzanine.pages',
 u'mezzanine.galleries',
 u'crispy_forms',
 u'mezzanine.accounts',
 u'mezzanine.mobile',
 u'autocomplete_light',
 u'jquery_ui',
 u'rest_framework',
 u'ga_ows',
 u'ga_resources',
 u'hs_core',
 u'hs_metrics',
 u'irods_browser_app',
 u'django_docker_processes',
 u'hs_geo_raster_resource',
 u'djcelery',
 u'ref_ts',
 u'hs_app_timeseries',
 u'widget_tweaks',
 u'hs_app_netCDF',
 u'hs_model_program',
 u'hs_modelinstance',
 u'hs_tools_resource',
 u'hs_swat_modelinstance',
 u'debug_toolbar',
 u'django_extensions',
 u'filebrowser_safe',
 u'grappelli_safe',
 u'django.contrib.admin',
 u'django.contrib.staticfiles',
 u'django.contrib.comments')
Installed Middleware:
(u'django.contrib.sessions.middleware.SessionMiddleware',
 u'django.middleware.locale.LocaleMiddleware',
 u'django.contrib.auth.middleware.AuthenticationMiddleware',
 u'django.middleware.common.CommonMiddleware',
 u'django.middleware.csrf.CsrfViewMiddleware',
 u'django.contrib.messages.middleware.MessageMiddleware',
 u'mezzanine.core.request.CurrentRequestMiddleware',
 u'mezzanine.core.middleware.RedirectFallbackMiddleware',
 u'mezzanine.core.middleware.TemplateForDeviceMiddleware',
 u'mezzanine.core.middleware.TemplateForHostMiddleware',
 u'mezzanine.core.middleware.AdminLoginInterfaceSelectorMiddleware',
 u'mezzanine.core.middleware.SitePermissionMiddleware',
 u'mezzanine.pages.middleware.PageMiddleware',
 u'ga_resources.middleware.PagePermissionsViewableMiddleware',
 u'debug_toolbar.middleware.DebugToolbarMiddleware')

Traceback:
File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py" in get_response
  111.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/home/docker/hydroshare/hs_core/views/__init__.py" in delete_file
  222.     hydroshare.delete_resource_file(shortkey, f, user)
File "/home/docker/hydroshare/hs_core/hydroshare/resource.py" in delete_resource_file
  719.         raise ObjectDoesNotExist(filename_or_id)

Exception Type: ObjectDoesNotExist at /hsapi/_internal/1b96e6bf7d0b43dbbcda9c562c48c0d8/delete-resource-file/12/
Exception Value: 12

**Comment by danames** [comment]
Closing this issue as the new redesign of referenced time series will make this irrelevant. See #502.
