### ISSUE TITLE
GeoServer Services need to be updated when data are added to an existing resource

### ISSUE THREAD

**Issue by danames** [hydroshare/hydroshare#4260]
GeoServer Services need to be updated when data are added to an existing resource. When you add data to an existing resource the new data are not automatically registered in GeoServer. The resource has to be made private then public again. This should

**Comment by eclark-cuahsi** [comment]
Adding @Castronova as well as Product Category owner for Linked Data Services

**Comment by martinseul** [comment]
adding and update here from the email conversation:
Chris requested a new server from ACIS and worked with Ken to set up a new geoserver instance and configured it to be tied to beta. I went through testing and it behaves correctly (https://geoserver-beta-test.hydroshare.org/geoserver/web/) . Now we need to plan role out, which requires a registration of all spatial resources with the new server, Ken needs to provide input here. as well as configuration changes that Chris can do.

**Comment by eclark-cuahsi** [comment]
Moving from Selected Next for Development per discussion on 4/21. @martinseul to follow up with Dan.

**Comment by martinseul** [comment]
as far as I understand this is working as expected now. The main outstanding issue is https://github.com/hydroshare/hydroshare/issues/4610 to fix nested shapefiles, closing this. we can reopen if needed.
