### ISSUE TITLE
counts between solr and django seem to disagree

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#4264]
**Description of the bug**
The counts as generated from resource listing and the counts of resources in discover differ for the various kinds of resources. 

Steps to reproduce the bug:
1. List resources in REST API. 
2. Count discoverable, public, published resources. 
3. Go to discover
4. Count the same resources in facets. 
5. The number differ

**Expected behavior**
The numbers should be the same.

**Comment by eclark-cuahsi** [comment]
Adding @martinseul for review of Discover Page issues

**Comment by devincowan** [comment]
believe resolved in 1.53
