### ISSUE TITLE
Update model schema template json files

### ISSUE THREAD

**Issue by pkdash** [hydroshare/hydroshare#4266]
Iman reported the issue with the current template files.

He suggested some changes such as not accepting negative values for some metadata elements where it makes sense (e.g., Watershed Area metadata in the SWAT JSON schema), which requires adding a new keyword "minimum" and set its value to "0" which specifies a minimum acceptable value of "0" for such cases. There are some typos n the current sample schemas for SWAT and MODFLOW. 

Iman has provided 2 updated template files to replace the current ones.

**Comment by eclark-cuahsi** [comment]
Adding @horsburgh as this falls under the Resource Model category.
