### ISSUE TITLE
Remove "includesModelOutput" and "executedByModelProgram" metadata from the "modelSpecificMetadata" in a meta.xml file for a model instance aggregation

### ISSUE THREAD

**Issue by imanmaghami** [hydroshare/hydroshare#4270]
modelSpecificMetadata is Metadata specified based on a JSON schema file but in a meta.xml file it not only includes the aforementioned JSON-based metadata but also includes the two terms, includesModelOutput and executedByModelProgram, which are not obviously based on a JSON (shown with orange box in the attached screenshot):

![image](https://user-images.githubusercontent.com/33031286/121798067-23ea1680-cbf2-11eb-8d68-1931e556d4e3.png)

**Comment by eclark-cuahsi** [comment]
Adding @horsburgh and @goodalljl as this falls under the Resource Model and Model Aggregation category.
