### ISSUE TITLE
Current MODFLOW JSON Schema provided by HydroShare has a serious issue

### ISSUE THREAD

**Issue by imanmaghami** [hydroshare/hydroshare#4271]
Even if the metadata values for the model properties studyArea, and outputControlPackage are provided by the user, these metadata and their values are not shown in the meta.xml file as well as in the HydroShare beta UI (in view mode). But, if the user goes back to edit mode they can see the values for the two metadata are there!

**Comment by eclark-cuahsi** [comment]
Adding @horsburgh and @goodalljl as this falls under the Resource Model and Model Aggregation category.
