### ISSUE TITLE
Putting an invalid character in spatial coverage gets it stuck on saving changes without reporting an error

### ISSUE THREAD

**Issue by imanmaghami** [hydroshare/hydroshare#4272]
Putting an invalid character in spatial coverage gets it stuck on saving changes without reporting an error. 
![image](https://user-images.githubusercontent.com/33031286/121798176-cd310c80-cbf2-11eb-9fa1-a0ed2bfef0b8.png)

**Comment by imanmaghami** [comment]
Reported by Kevin Chen (@kevinc0223)

**Comment by eclark-cuahsi** [comment]
Adding @Castronova  and @horsburgh for review as this pertains to the Pages and General Components/ Resource Landing Page categories.
