### ISSUE TITLE
Putting in symbols in the metadata fields messes up the value in the xml file by adding some stuff to the sides

### ISSUE THREAD

**Issue by imanmaghami** [hydroshare/hydroshare#4273]
Putting in symbols in the textboxes messes up the value in the xml file by adding some stuff to the sides. It seems to apply to all metadata fields where they can be inputted and occurs in both MODFLOW and SWAT schema.

![image (6)](https://user-images.githubusercontent.com/33031286/121799484-716a8180-cbfa-11eb-9efe-0d0c700a7469.png)

**Comment by imanmaghami** [comment]
Reported by Kevin Chen (@kevinc0223)

**Comment by eclark-cuahsi** [comment]
Adding @Castronova and @horsburgh for review as this pertains to the Pages and General Components/ Resource Landing Page categories. Is this a bug?
