### ISSUE TITLE
Improving the error message when model instance metadata schema is invalid

### ISSUE THREAD

**Issue by imanmaghami** [hydroshare/hydroshare#4279]
When an uploaded JSON schema is invalid, the error message shown can be improved and be more specific. I present two examples here:

1- If a comma is missing after one of the schema fields the following error is shown:

"Error! metadata failed to update [{"schema_name":Not a valid JSON string"}]"

Is it possible to tell the user which line is problematic? If not, can HydroShare use a more informative error message (and add a hyperlink to Model Instance Metadata Schema help page, once it is created)?:

"Error! metadata failed to update [{"mi_json_schema_file":Not a valid JSON string"}]. Please follow the instructions provided by **Model Instance Metadata Schema help page** when creating a JSON schema” 

2- I intentionally put a few errors in a schema and got a very long error message which can potentially be confusing (see the screenshot below). In addition to a link to Model Instance Metadata Schema help page (as also stated above), can HydroShare find a way to make this error easier to understand by the user? 

![image](https://user-images.githubusercontent.com/33031286/121948591-695b3080-cd25-11eb-887b-e051f52e2fd5.png)

**Comment by eclark-cuahsi** [comment]
adding @horsburgh as this pertains to the Resource Model Category.
