### ISSUE TITLE
.OVA File Link Not Working

### ISSUE THREAD

**Issue by kevinc0223** [hydroshare/hydroshare#4291]
**Description of the bug**
There is a link for a .OVA file in the README.md. However, this link does not go to a website that can be reached.

Steps to reproduce the bug:
1. Go to HydroShare GitHub
2. Scroll down to the README.md
3. Under the "Install" section there is a "Simplified Installation Instructions" with the first step being to "download the latest .OVA file here"
4. When clicked, it gives a "This site can't be reached error

**Expected behavior**
To open to a valid webpage

**Additional information**
Screenshots:
<img width="504" alt="Screenshot 2021-06-30 222959" src="https://user-images.githubusercontent.com/72314515/124055913-c1b35300-d9f2-11eb-87a4-353f3da161f0.png">

<img width="439" alt="bug" src="https://user-images.githubusercontent.com/72314515/124056167-35556000-d9f3-11eb-819f-6e50fc676acb.png">

**Comment by eclark-cuahsi** [comment]
This will be addressed with PR4281. @martinseul I'm assigning this to you per our discussion. Thanks.

**Comment by martinseul** [comment]
The developer setup using a OVA file has been deprecated and is superseded by a new setup. The setup process outlined on the landing [page ]((https://github.com/hydroshare/hydroshare))for the repository  has been updated with the new instructions.  [PR# ](https://github.com/hydroshare/hydroshare/pull/4281)
