### ISSUE TITLE
Cannot edit geographic feature aggregation metadata

### ISSUE THREAD

**Issue by horsburgh** [hydroshare/hydroshare#4302]
**Description of the bug**

I cannot see or edit the aggregation level metadata for a geographic feature aggregation (shapefile) within a resource. This is a regression - this used to work fine. Here is a screenshot of the error that I receive.

![image](https://user-images.githubusercontent.com/3485902/127062210-34557fb3-2085-47e9-99f4-612481c9011e.png)

Steps to reproduce the bug:
1. Create a new resource
2. Set title, abstract and keyword (I don't think this step is really needed)
3. Add a shapefile to the resource
4. Click on the shapefile in the file browser panel to select it
5. The error is displayed in the aggregation metadata panel on the right

**Expected behavior**

I should be able to see and edit the metadata for the geographic feature aggregation within the right panel of the file browser panel.

**Additional information**
Add any other context about the problem here such as screenshots, software versions, and browser information.

Testing using Chrome on my Macbook Pro. This was reported by another HydroShare user who was using Firefox on Windows 10.

**Comment by sblack-usu** [comment]
This error was introduced with the [model program/instance merge](https://github.com/hydroshare/hydroshare/blame/develop/hs_file_types/views.py#L1218).

That line previousl did not pass in a user parameter and the geofeature metadata method for get_html_forms does not have a user parameter defined.  The other aggregations included a `**kwargs` parameter with the merge.  It looks like GeoFeature was missed.

This is a very minor change to include `**kwargs` in the parameter for get_html_forms on the GeoFeatureFileMetaData class.
