### ISSUE TITLE
API endpoint /scimeta/custom currently requires edit permissions to GET

### ISSUE THREAD

**Issue by sblack-usu** [hydroshare/hydroshare#4309]
**Description of the bug**
[update_key_value_metadata_public](https://github.com/hydroshare/hydroshare/blob/develop/hs_core/views/__init__.py#L390) handles both the POST and GET.  The authorization scope for POST is correct and requires edit permissions.  The authorization scope for GET also requires edit permissions but it should only require view permissions.

Steps to reproduce the bug:
1. curl https://www.hydroshare.org/hsapi/resource/0825db8e3bed4b18b77f214b5630f3d7/scimeta/custom/
2. Observe a 403 for viewing additional metadata on a public resource.

**Expected behavior**
GET /scimeta/custom should require view permissions, not edit permissions.

**Comment by sblack-usu** [comment]
@horsburgh - I believe this is a programming error but I'd like you to confirm that viewing additional metadata via the API should only require VIEW permissions and not EDIT permisssions.

**Comment by horsburgh** [comment]
@sblack-usu - I'm with you. I think viewing metadata via the API should only require VIEW permissions. I realize that this question is only about the "additional metadata" elements, but I think is generally true of the all of the metadata.
