### ISSUE TITLE
Add more language to site

### ISSUE THREAD

**Issue by kieutuandungtlu** [hydroshare/hydroshare#4319]
I want to develop a site with 2 languages, a default one, my native language and an optional English. I plan to have my domains as such:

www.mydomain.com/vi/
www.mydomain.com/en/

How I can develop it in Hydroshare?

**Comment by sblack-usu** [comment]
HydroShare does not host websites, it is a repository for uploading and sharing hydrology data.

**Comment by eclark-cuahsi** [comment]
Hi @kieutuandungtlu, I'm going to close this issue HydroShare does not host websites, per Scott's comment above. Please feel free to reach out to help@cuahsi.org if you have any additional questions about using HydroShare.
