### ISSUE TITLE
Inconsistencies in authors and creator field formats in /hsapi/resource/ endpoint

### ISSUE THREAD

**Issue by aaraney** [hydroshare/hydroshare#4344]
There are formatting Inconsistencies in the `authors` and `creator` fields when querying the `/hsapi/resource/` endpoint. Notice that in one case the authors field contains a list of strings following the `first last` naming convention, likewise in this record the `creator` field also follows this convention. Conversely, in the following resource record, the `authors` and `creator` fields appear to follow a `last, first` naming convention. Although I could not find a network request to `/hsapi/resource/ ` when navigating to `/my-resources/`, the inconsistencies are also apparent in the Resource table listing, specifically the first author field. 

Note, for confidentiality, Ive dropped the top level `json` fields below besides `results`.

```json
{
  ...
  "results": [
    {
      "resource_type": "CompositeResource",
      "resource_id": "7344a8dcaff24d029354e596c1f82782",
      "resource_title": "Example resource SI 2019",
      "abstract": "This is an example resource for the summer institute 2019.",
      "authors": [
        "Austin Raney"
      ],
      "creator": "Austin Raney",
      "doi": null,
      "public": false,
      "discoverable": false,
      "shareable": true,
      "immutable": false,
      "published": false,
      "date_created": "2019-06-12T13:23:30.742252Z",
      "date_last_updated": "2021-09-20T16:51:20.462212Z",
      "bag_url": "http://www.hydroshare.org/django_irods/rest_download/bags/7344a8dcaff24d029354e596c1f82782.zip?url_download=False&zipped=False&aggregation=False",
      "coverages": [
        {
          "type": "period",
          "value": {
            "start": "1994-01-01",
            "end": "1994-01-01"
          }
        },
        {
          "type": "box",
          "value": {
            "northlimit": 22.6308,
            "projection": "WGS 84 EPSG:4326",
            "units": "Decimal degrees",
            "southlimit": 18.4968,
            "eastlimit": -154.3841,
            "westlimit": -160.888
          }
        }
      ],
      "science_metadata_url": "http://www.hydroshare.org/hsapi/resource/7344a8dcaff24d029354e596c1f82782/scimeta/",
      "resource_map_url": "http://www.hydroshare.org/hsapi/resource/7344a8dcaff24d029354e596c1f82782/map/",
      "resource_url": "http://www.hydroshare.org/resource/7344a8dcaff24d029354e596c1f82782/",
      "content_types": []
    },
    {
      "resource_type": "CompositeResource",
      "resource_id": "f637db4efd404211bf088af01fc59da9",
      "resource_title": "NY Test Case NWM 2.0 Perturbed Bottom Width",
      "abstract": "In a rush bother aaraney@crimson.ua.edu if this abstract has not been updated",
      "authors": [
        "Raney, Austin"
      ],
      "creator": "Raney, Austin",
      "doi": null,
      "public": true,
      "discoverable": true,
      "shareable": true,
      "immutable": false,
      "published": false,
      "date_created": "2019-07-05T00:50:17.049297Z",
      "date_last_updated": "2019-07-05T00:52:39.853212Z",
      "bag_url": "http://www.hydroshare.org/django_irods/rest_download/bags/f637db4efd404211bf088af01fc59da9.zip?url_download=False&zipped=False&aggregation=False",
      "coverages": [
        {
          "type": "point",
          "value": {
            "units": "Decimal degrees",
            "east": -74.1865,
            "north": 44.0389,
            "projection": "WGS 84 EPSG:4326"
          }
        }
      ],
      "science_metadata_url": "http://www.hydroshare.org/hsapi/resource/f637db4efd404211bf088af01fc59da9/scimeta/",
      "resource_map_url": "http://www.hydroshare.org/hsapi/resource/f637db4efd404211bf088af01fc59da9/map/",
      "resource_url": "http://www.hydroshare.org/resource/f637db4efd404211bf088af01fc59da9/",
      "content_types": []
    }
  ]
}
```

For scale, I went ahead and pulled all discoverable resources from HydroShare using `hsclient` (see below code). Of the 5166 resources, 5149 (net 17) have non `NA` creator field. Within the 5149 resources, 1928 resources contain a `,` in the `creator` field, 3221 do not contain a comma in the `creator` field. 

```python
import pandas as pd
from hsclient import HydroShare

client = HydroShare()
client.sign_in()

response = list(client.search())

df = pd.DataFrame([r.dict() for r in response])

# get count of resources with an NA `creator` field
df['creator'].isna().value_counts()

# create subset without NA `creator`s
df_nona = df.dropna(subset=['creator'])

# records where comma exists in creator field
df_nona[df_nona['creator'].str.contains(",")]

# records where comma DOES NOT exists in creator field
df_nona[~df_nona['creator'].str.contains(",")]

```

<details>
<summary><b>Additional information</b></summary>

**HydroShare Version**: 1.46
**Browser**: Firefox 92.0 (64-bit)
</details>

**Comment by sblack-usu** [comment]
Did you create those two resources in different ways (API for one, Webpage for the other?)

**Comment by aaraney** [comment]
> Did you create those two resources in different ways (API for one, Webpage for the other?)

They were both created via the webpage.

**Comment by devincowan** [comment]
@aaraney I think it's because these Creator and Author names are mutable
They initially populate from the HS User Profile (with a comma)
But they can later be changed on the resource. See video:

https://user-images.githubusercontent.com/17934193/165389283-ef1ab0e8-a871-4034-9092-f08e0f82c4d5.mov

I'm told this is by design, so that the Author/Creator info on a given resource can be modified to fit a particular publication or because a user might have different affiliations on different resources (say published at different times during their career).

**Comment by devincowan** [comment]
@aaraney sorry, initial video got clipped. just edited it. LMK if this explanation fits what you observed and I will close

**Comment by aaraney** [comment]
Thanks for the explanation and demo, @devincowan! I concur with your example that this is likely what is happening. Given that of the 5149 resources I checked, 1928 resources contain a comma in the creator field and 3221 do not contain a comma, I suspect that at some point in time the behavior was the creator field did not include a comma by default. Either way, its a mild annoyance, but thanks for digging into the db and figuring out _why_ this is defined behavior!

**Comment by devincowan** [comment]
Good point @aaraney I suspect the same thing. In fact, looking at the JSON you provided I optimistically thought we might be able to pin the change in default behavior to Jun/Jul 2019 but when I looked at the `date_created` I didn't see a consistent point where the format changed. Suppose it doesn't matter much at this point...
I guess one could use the [https://www.hydroshare.org/hsapi/userDetails/](https://www.hydroshare.org/hsapi/#operations-tag-userDetails) endpoint to union and get consistent name format if needed, though that might be frustrating...
