### ISSUE TITLE
Users cannot leave groups

### ISSUE THREAD

**Issue by Castronova** [hydroshare/hydroshare#4349]
**Describe the feature you'd like and what it will do**

Once a user is admitted to a group there is no way for them to leave. Owners of the group can "expel" group members, but currently there is no way for a member to leave on their own accord. 

On the group page, there should be a button that allows group members to "leave" the group.

**Why is this feature important?**

This is necessary to allow users to leave groups that are no longer relevant and/or active. 

**Is your feature request related to a problem? Please describe.**

Users (myself included) cannot leave old/defunct groups the we are members of.

**Additional context**
1. Go to any group that you are a member of
2. Try to leave the group
3. Notice that these is no feature that allows you to do so.

**Comment by horsburgh** [comment]
@Castronova - There's a little hand icon at the top right of the group page that enables users to leave.

![image](https://user-images.githubusercontent.com/3485902/134714951-65d6e4f9-11d7-4986-8e60-1267913238bd.png)

I realize that this isn't super obvious and so I've turned this into a big button in the revised groups/communities functionality mockups.

**Comment by Castronova** [comment]
Thanks @horsburgh. I was messing with this yesterday and could not figure out how to leave a group. It's not very obvious, but the functionality does exist...thanks for pointing it out :) 

I'm closing this issue.
