### ISSUE TITLE
set "spatial coverage" as required meta for raster  

### ISSUE THREAD

**Issue by gantian127** [hydroshare/hydroshare#435]
The geo-spatial raster resource type needs to have the "spatial coverage" as the required meta before the resource is set as public.

**Comment by dtarb** [comment]
I am not sure what behavior you are expecting, I loaded Honduras.tif. All coverage fields were filled as NA.  It is possible to make the resource public without filling in spatial coverage.

**Comment by gantian127** [comment]
@dtarb This function won't check the extended metadata of "spatial reference". It checks the Dublin core metadata of spatial coverage as box. I just created one resource on dev site and it works. If you test the function in the same way but it doesn't work as expected, please let me know with the resource link. Thanks.
