### ISSUE TITLE
Legend incorrect in discover, my resources, and help

### ISSUE THREAD

**Issue by ClaraCogswell** [hydroshare/hydroshare#4357]
**The legend of Hydroshare symbols is out of date**
The legends that appear under My resources, in Discover, and in the help pages are different, contain outdated resource types, and are missing content types. It's missing the "mappable"/"has geographic coverage" icon we introduced in discover. I know we're already aware of this issue but I'd like to track it's progress here so that I know where we are on it. 

@horsburgh 

I've created a mock up: 
![New Legend](https://user-images.githubusercontent.com/90924476/134977412-2edf9753-d74f-4dbc-bc2f-db26e32ec7cd.png)

If we think this is a good layout or we want to make changes or there is anything wrong with it, go ahead and let me know here in this thread. Once we agree on an updated legend I will add it to the help page changes, and once we deploy it on prod I will try to simultaneously update help.

**Comment by ClaraCogswell** [comment]
![Legend4](https://user-images.githubusercontent.com/90924476/136265457-9bd07ca6-7a92-4154-b193-24e199b971b1.png)
New legend

**Comment by Maurier** [comment]
@ClaraCogswell This work has now been merged into development. Changes will need to be made in the help pages as you describe.

**Comment by ClaraCogswell** [comment]
Thank you!
