### ISSUE TITLE
Using original names for images in group, community, and profile pages creates filename collision problem. 

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#4363]
**Description of the bug**
Group, community, and profile images are uploaded with their original filenames. If two users upload images with the same name, they will collide. 

**Expected behavior**
Image filenames should be made unique through hashing.  This is a trivial patch.

**Comment by hyi** [comment]
@alvacouch I verified this has been fixed on production, so I am closing it, but feel free if you notice any further issues.
