### ISSUE TITLE
Remove deprecated resource types from Web App Connector

### ISSUE THREAD

**Issue by sblack-usu** [hydroshare/hydroshare#4393]
**Description of the bug**
The Web App Connector still includes deprecated resource types.  Remove them while looking over the web app connector model for other places to clean up

Steps to reproduce the bug:
1. Create Web App Connector Resource
2. Observe the long list of resource types

**Expected behavior**
The Web App Connector should only have two resource types, composite and collections.  We might not even want collections, that would be a good question to investigate.

**Comment by dtarb** [comment]
Assigned to @pkdash as part of resource consolidation work.
