### ISSUE TITLE
Metadata Ingestion  issue with geographic rasters in Hydroshare

### ISSUE THREAD

**Issue by ClaraCogswell** [hydroshare/hydroshare#4398]
**Description of the bug**
A user has added a large number of geographic rasters to a resource, but hydroshare has not extracted any Metadata from them, and she is unable to make the resource public to share her data. 

Steps to reproduce the bug:
1. Go to https://www.hydroshare.org/resource/8efb0f7e743f4a11a4da8b045a37165b/
2. go to the contents section and try to view metadata.
3. See error

**Expected behavior**
Normally Hydrishare extracts data from the geotiff file and populates the metadata. 

**Additional information**

**Comment by martinseul** [comment]
same as Geographic Raster failed validation creates an aggregation without metadata  https://github.com/hydroshare/hydroshare/issues/4405, 
closing
