### ISSUE TITLE
Decide and clarify on public/private information

### ISSUE THREAD

**Issue by ironfroggy** [hydroshare/hydroshare#44]
Two parts here:
- [x] What information in a profile is public versus private?
- [x] Clarify in the profile editing screen what is public versus private so the user knows when deciding to check the Public checkbox

A point of clarification:
- [x] If the user can fill out a profile with information they mark as private, then why are they entering that information? If no one would see it, maybe there is no reason to be entering it?

**Comment by dtarb** [comment]
Good point.  It is not required for users to provide information so lets put a statement on the page that "Information entered here may be publicly visible" and leave it for users to provide it or not as they wish. (I also do not think that our original mockup said anything about keeping info private, but someone added it sometime)

I would like to have the following information required for each user
- Name
- Email
- Organization 
- User type

Organization is not required now, but I think we should have users at least tell us the organization they work for, belong to or represent.  They could enter something like "Home" or "Private" if they are acting in a personal capacity - and that is fine too.

User type is needed for our demographic reporting.  One of the allowable types is "Unspecified" if they really insist on not telling.

All other information is optional.  

Given this it may be easiest to collect Organization and User type on the sign up page and the rest on the profile page.  

There were release 1 mockups developed for the  sign up and profile editing that provide additional guidance if it is needed.  These are in Alfresco at Documents >  System Design > User Interface > Release 1 Mockups.

Specifically see "User profile pages" and "account creation page"

These could be updated if needed

**Comment by rayi113** [comment]
HydroShare Profile Issues in GitHub: #44, #46, #47, #48, #49, #68

**Comment by horsburgh** [comment]
I believe that our simplified information model for users has got this straight. I'm assigning to Mauriel to make sure the front end implementation is correct.

**Comment by mauriel133** [comment]
@horsburgh, @dtarb, @ironfroggy we need to make a decision on public vs private so that I can apply it to the new profile edit page.

**Comment by horsburgh** [comment]
I think we resolved this on the phone call. Everything the user enters into the user profile is public. The warning at the top that you were going to make more colorful/noticeable states this.

However, to address @selimnairb 's concern, we need to add an item "Unspecified" to the country list, and I think we need to make State optional.

**Comment by mauriel133** [comment]
This implementation can be tested at https://park.hydroshare.org

**Comment by mauriel133** [comment]
This has been implemented and deployed. Please confirm and close.

**Comment by horsburgh** [comment]
Agreed. Users can set "Unspecified" as valid values where they want to protect privacy. Closing.
