### ISSUE TITLE
Data not listed under Content, but available from "Download content as zipped Archiv"

### ISSUE THREAD

**Issue by kratzert** [hydroshare/hydroshare#4414]
Hi all,

I was contacted by someone, who wanted to download the data from one of my publications that I stored on HydroShare. He said that he only sees the README.md file. Going to the [hydroshare repository](https://www.hydroshare.org/resource/83ea5312635e44dc824eeb99eda12f06/) I could validate his observation but also saw that the storage size is given with `Storage: The size of this resource is 895.7 MB`. I checked some of my other repositories on hydroshare and there, the data was shown as before under "Content". I am pretty sure that the data for the repository linked above worked before, as it was already downloaded 14k times and nobody did contact me until now.

I then tested what happens if I click on the "Download all contents as zipped archive" button.

![Screenshot from 2021-11-08 09-37-23](https://user-images.githubusercontent.com/13069767/140711367-cc339ecb-3865-4bbb-ae48-13d07730dc7a.png)

To my surprise, the downloaded archive was > 800MB in file size in did indeed contain all of the original data (readme + model simulations stored in a zip archive). So it seems the data is still there, just not listed under "Content". 

**Expected behavior**
All files in the data repository are listed under "Content" and thus are downloadable separately.

**Comment by sblack-usu** [comment]
The debug page shows the DB entry is missing for that file.  https://www.hydroshare.org/debug/resource/83ea5312635e44dc824eeb99eda12f06/

I also checked beta, the resource renders correctly with the file.  The check_irods_files management command should remedy the problem but I'm not sure why beta has the db entry while production does not.  Some investigation is needed before running the management command.

**Comment by kratzert** [comment]
Thanks for looking at it. If there is any additional info you need from my side, lmk. I am pretty sure that it did work not a long time ago.

**Comment by sblack-usu** [comment]
I misread the debug message. The file is in the db, it is NOT in iRODS.  @hyi - could you check iRODS to see if you can figure out what happened to the file?  I saved a copy of the resource from beta in case we need to restore it.

I do not see any modifications on the django side.

**Comment by hyi** [comment]
@sblack-usu I looked into iRODS in both data zone and user zone including the iRODS vaults and trash, but don't see this zip file anywhere in production iRODS. @cbcunc it'd be good if you could look into this as well to see if you could see any hints for this missing zip file in iRODS.

**Comment by sblack-usu** [comment]
It appears the file went missing sometime between Sunday (11/7) and Monday (11/8).  We know this because the file is still in the data copy from Sunday night and the issue was reported Monday.

I found this in the logs several times.  I don't think it's related to this issue since it was back at the end of September.  Pasting it here in case I need it later.
```
[30/Sep/2021 03:25:41] ERROR [django.request:135] Internal Server Error: /django_irods/download/83ea5312635e44dc824eeb99eda12f06/data/contents/Kratzert_et_al_2019_HESSD_LSTM_4_REGIONAL_MODELING.zip/
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/contrib/sessions/backends/base.py", line 202, in _get_session
    return self._session_cache
AttributeError: 'SessionStore' object has no attribute '_session_cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 213, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 189, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/postgresql/base.py", line 176, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  sorry, too many clients already
```

**Comment by sblack-usu** [comment]
I'm not seeing anything in the access logs indicating a transform on the resource with an API call, both internal and through hsapi.

**Comment by cbcunc** [comment]
File was not in Sunday data copy:
```
-bash-4.2$ ls /projects/hydroshare/hsdata/dev/data-copy/83ea5312635e44dc824eeb99eda12f06/data/contents/
README.md
-bash-4.2$
```

**Comment by sblack-usu** [comment]
The bag was generated March 1, 2021.  Because the file is in the bag, we know the file wasn't missing at least up until then.

**Comment by sblack-usu** [comment]
I have restored the file to the resource from the file that was in the bag.  The file shows up in the resource now and I was able to download the file and unzip it.  The resource appears to be restored.  I was not able to determine what caused this specific issue but am running a sweeper to check other resources for the same symptoms.  If we see more resources with this problem, it will help us find and fix the root issue.

**Comment by martinseul** [comment]
@kratzert Hi Frederik, thanks for pointing the issue out to us, we looked into and think we solved the issue and closed the ticket. Please let us know if you encounter additional issues or the problem persists.

Thanks
Martin

**Comment by kratzert** [comment]
Hi @martinseul (and others, especially @sblack-usu )

thanks for being responsive and solving this issue that quickly. The data is again visible for me on HydroShare and for all of my other repositories I do not see any problem. No further problem/issue from my side.

Thanks again for your time/work, really appreciated.
