### ISSUE TITLE
The landing page for a resource that is private should display versioning relationships.

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#4415]
**Description of the bug**
There may be situations where, with versioned resources we have
V1 is private
V2 is public
V3 is private
V4 is public
Currently it is not possible to follow links from V4 back to V2.  We need to have the newer and older version links on the limited access page displayed for private resources, so that when a user gets to V4 they would have a way to go back to V2.

Steps to reproduce the bug:
Create a chain of resources with access settings as above and attempt to get from V4 to V2.

**Expected behavior**
Add versioning links to the private landing page to enable traversal of versioning chains.

![image](https://user-images.githubusercontent.com/3456833/140762307-406adbe0-c721-43c6-8605-761324d1326c.png)

This issue was split off from #3936

**Comment by hyi** [comment]
@dtarb I tested on production and verified this issue has been fixed.I am closing it, but feel free to test it yourself and reopen it if you still see any issues.
