### ISSUE TITLE
Increase length of text field for derived from reference (and perhaps other references)

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#4418]
**Description of the bug**
It is not possible to fit a desired reference in derived from.  For example a user had to write 
Derived from:  
Newman, A.J., et al., 2015. Development of a large-sample watershed-scale hydrometeorological dataset for the contiguous USA: dataset characteristics and assessment of regional variability in hydrologic model performance. HESS, 19, 209-223, http://doi.org/10.5194/hess-19-209-2015

where the following would have been preferred and is recommended by the journal
Newman, A. J., Clark, M. P., Sampson, K., Wood, A., Hay, L. E., Bock, A., Viger, R. J., Blodgett, D., Brekke, L., Arnold, J. R., Hopson, T., and Duan, Q.: Development of a large-sample watershed-scale hydrometeorological data set for the contiguous USA: data set characteristics and assessment of regional variability in hydrologic model performance, Hydrol. Earth Syst. Sci., 19, 209–223, https://doi.org/10.5194/hess-19-209-2015, 2015.

Steps to reproduce the bug:
1. Attempt to add a source reference to a resource
2. Paste in the above text to see that it does not fit

**Expected behavior**
Reasonable length references should be accommodated.

**Additional information**
While I referred here to the derived from reference, this problem of limited length fields is pervasive and should be fixed in as many places as possible.

**Comment by pkdash** [comment]
@dtarb This should be fixed as part of my current work on issue #3261.

**Comment by pkdash** [comment]
@dtarb I did test this issue on production and it seems to have been fixed - so closing this issue.
