### ISSUE TITLE
/hsapi/userDetails return 404 not found for valid users

### ISSUE THREAD

**Issue by aaraney** [hydroshare/hydroshare#4424]
@aaraney Thanks for the quick fix. We just tested it and ran into a new error for the following users
christinabandaragoda
jbeaulieu
paulfloury
linnea
rstrauch
gantian
stella
jpally
zzoo
kortney09
branhoff
scicommsadie
sohsaid
tonycastronova
gokulanand
github_zyli2004
uillinois_zhiyul
zhiyuli
uillinois_zhiyul@illinois.edu
laurencejnote
nicoleta
bechir
marti_nogues
ashlingj
maram
lgraup
motasem
kevinc0223
claracogswell
kristina_roller

![image](https://user-images.githubusercontent.com/10070599/142462900-944ec071-ccca-4ab9-854e-9b6cc8f98206.png)

_Originally posted by @zhiyuli in https://github.com/hydroshare/hsclient/issues/33#issuecomment-973066258_

**Comment by aaraney** [comment]
For context, @zhiyuli found an issue with a method in `hsclient` that exposes the `/hsapi/userDetails` endpoint. In his testing, he also found that some valid users (see above) return `404` responses.

**Comment by sblack-usu** [comment]
Just looking at the first one and the username doesn't match because they are case-sensitive.  https://www.hydroshare.org/user/259/

christinabandaragoda -> ChristinaBandaragoda

We may be able to make the usernames case-insensitive, provided we currently don't have any username conflicts with that change.  We will also need to know if that is change we that others support.

**Comment by sblack-usu** [comment]
Immediately after writing the above response, I tried logging in with my account, and logging in currently isn't case-sensitive.  I'll take a look at that code and if I'm satisfied then I'll go ahead and make the userDetails endpoint case-insensitive.

**Comment by sblack-usu** [comment]
haha, 3 years ago I implemented the backend to allow usernames to be case-insensitive.  https://github.com/hydroshare/hydroshare/issues/2781

I'll go ahead and update the userDetails endpoint.

**Comment by aaraney** [comment]
Awesome! Thanks for weighing in on this @sblack-usu! Given that you've refed #4424 here, I will go ahead and close this.

**Comment by sblack-usu** [comment]
let's keep it open.  I'll use it to make sure it gets deployed
