### ISSUE TITLE
Constrain ResourceFile to one per file

### ISSUE THREAD

**Issue by sblack-usu** [hydroshare/hydroshare#4432]
**Description of the bug**
ResourceFile currently allows more than one entry to be made for a single file.  This causes bugs in the code when dealing with the file as the code usually expects only one entry.

Steps to reproduce the bug:
I don't know what action causes multiple ResourceFile entries to be created for a single file.  It likely has to do with an interrupted process.  The management command to identify resources with this issue will meet these criteria.

**Expected behavior**
There should only be one ResourceFile per file.  This constraint should be on the db model.

**Comment by martinseul** [comment]
@sblack-usu how important is this to be fixed and what are the next steps?

**Comment by sblack-usu** [comment]
It has been a year since this issue was created and I am not aware of any reported user issues since.  I still think this should be tightened up.  I'd start by writing a management command to identify duplicate ResourceFile entries (as well as any blank/null or file missing entries).  Once they are identified, tighten up the model to prevent these entries at the db level. https://github.com/hydroshare/hydroshare/blob/develop/hs_core/models.py#L2784-L2787 and cleanup those entries during a release.

**Comment by devincowan** [comment]
related to https://github.com/hydroshare/hydroshare/issues/1744

**Comment by devincowan** [comment]
Ran [fix_resourcefile_duplicates](https://github.com/hydroshare/hydroshare/blob/4432-resource-file-duplicates/hs_core/management/commands/fix_resourcefile_duplicates.py). Looks like we have ~4300 files with two or more ResorceFile objects in the db
