### ISSUE TITLE
You do not have permission should say an Owner not Authors

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#4434]
**Description of the bug**
When a resource is Discoverable, users without specific access rights see a message "You do not have permission to see these content files.  Please contact the Authors if you wish to obtain access".

This is incorrect as Authors can not change permissions on a resource, only Owners (or certain editors) can.

Change the message to
"You do not have permission to see these content files.  Please contact **an Owner** if you wish to obtain access."

**Comment by pkdash** [comment]
This has been fixed in 1.51.1 - so closing.
