### ISSUE TITLE
HydroShare Slogan Ideas

### ISSUE THREAD

**Issue by aaraney** [hydroshare/hydroshare#4441]
@ClaraCogswell and I are seeking a HydroShare slogan! Below are some ideas, but we would love to hear more. Please add them below. A vote for a slogan will be taken at the next HydroShare Teleconference (Jan 5. 2022).

The below enumeration is only for identification. The enumeration does not relate to any slogan favoritism.

1. HydroShare:  A CUAHSI Water Data Service
2. HydroShare: create, share, publish
3. HydroShare by Hydrologists For Hydrologists
4. HydroShare: Sharing Hydrologic Data  
1. HydroShare: Create, publish, discover
1. HydroShare: Data: collaborate, publish
5. HydroShare: Create, discover, share
6. HydroShare: collaborate, publish, discover
7. HydroShare: Create, publish, share
8. HydroShare: Collaborate, create, publish
9. HydroShare: Collaborate, create, discover
10. HydroShare: Working together to accelerate hydrologic knowledge production
11. HydroShare: Build research impact

**Comment by aaraney** [comment]
@hydroshare/developers 
@hydroshare/extension-developers 
@hydroshare/infrastructure-admins 
@hydroshare/infrastructure-customers 
@hydroshare/irodssharedev

**Comment by danames** [comment]
Don't repeat "share" or "hydrology" since those are implicit in "HydroShare".

**Comment by aaraney** [comment]
If you would rather contribute outside of GitHub, here is a [google doc](https://docs.google.com/document/d/1pIA2a0YbPMB1piDnpabbHK55DBYaZ2MHPVpM05R7KsM/edit?usp=sharing)!

**Comment by sblack-usu** [comment]
HydroShare: Discover, collaborate, publish

**Comment by dtarb** [comment]
Here is a bunch in my priority order (to the degree I can decide)

- Working together to create knowledge by sharing
- Sharing hydrologic data [concise and says it all.  But it does repeat the share and hydro which may be a drawback]
- Sharing hydrologic data and models
- Community data and model sharing [The word community is nice if we can weave it in]
- Share your data and models with colleagues (Was in an earlier postcard see below)
- Share and collaborate (was also in earlier postcard)
- Share your data and models with the community
- Share and discover data and models (was in an earlier CUAHSI postcard)
- A community collaboration platform
- Community collaboration platform
- A hydrologic information system for community collaboration
- A hydrologic science collaboration platform

You'll note that I do repeat hydrology and share a fair bit.  I disagree with the sentiment to not repeat them as they are implicit.

**Comment by horsburgh** [comment]
HydroShare: Do more with your research.

Implies that we all can and should do more with the products of our research. Thus, it embeds a core value. Implies that HydroShare supports this with functionality that is more than what we have had before. Doesn't constrain us to just data or just repository functions as HydroShare and linked systems are more. Enables us to keep innovating.

**Comment by danames** [comment]
+1 for the general idea of @horsburgh which I would characterize as "don't try to be so specific about exactly what HydroShare does, but rather give the bigger vision statement in the tagline!"

So that vision statement could be:

"Do more with your research"
"Make your research matter"
"Do more with your research through collaboration"
"Collaborative Water Research"
"Collaboration makes the world a better place"

**Comment by aaraney** [comment]
Yes, good catch, @martinseul. Sorry, I should have closed this earlier.
