### ISSUE TITLE
Inconsistent capitalization is used across legend items in My Resources and Discover

### ISSUE THREAD

**Issue by hydrocheck** [hydroshare/hydroshare#4443]
Recommendation is to change "Pending publication" to "Pending Publication", so that title case is consistently used
<img width="1125" alt="003" src="https://user-images.githubusercontent.com/43424907/147899776-284c764f-0164-44d8-b9b9-58dc49c0291a.png">

**Comment by eclark-cuahsi** [comment]
This was noted in #4089 as well. "Not shareable" should also be changed to "Not Shareable" to follow the same title case capitalization.
