### ISSUE TITLE
Copying creates incorrect versioning chain

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#4450]
**Description of the bug**
If you copy a resource that has a previous version then incorrect version chains result.

Our versioning model supposed to be
A -> B -> C where -> indicates isReplacedBy
And 
A <- B <- C where <- indicates isVersionOf

Steps to reproduce the bug:
1. Create a new resource (I did this for A https://www.hydroshare.org/resource/8dbd221006f34c918f48c72a51d6d9e3/)
2.  Create a new version of the resource (I did this for B https://www.hydroshare.org/resource/c20a95d1df7648188d66eca727f2a05a/)
3.  Make B and A public.  
4.  As a separate user create a copy of B.  I did this for C https://www.hydroshare.org/resource/9c4074af5f0b44c1ade1c0da7393c481/.  On C it indicates a relationship that this resource isVersionOf A.  This now means that there are two new versions of resource A. 

A ->B
A ->C

**Expected behavior**
The copy command should not copy the relationship isVersionOf when making a copy of this resource.

See #4397 where versioning is being fixed.  

@horsburgh may want to weigh in
@hyi please address this as part of #4397 work.

**Comment by hyi** [comment]
@dtarb I verified that this issue has been fixed on production. I am closing it, but feel free to reopen it if you still see any issues with it.
