### ISSUE TITLE
Pending Group Request from Inactive Account

### ISSUE THREAD

**Issue by Castronova** [hydroshare/hydroshare#4456]
**Description of the bug**

Below is a summary of the issue and discussion from an email between Dave T, Tony C, and Martin S.

(Dave)
I clicked on the user name [of a pending request in the HS group 156 landing page] to see more, which I do before considering accepting and get “Sorry an error occurred”. I then logged in as admin and see that the account is not active.  Did someone block this account, or did the group join request somehow get sent without the account being activated.
 
In any event, we may need to work out something sensible to do to avoid the “Sorry an error occurred” in a situation like this.  A state like this is a bug, albeit perhaps not a high priority one.

(Tony)
I’m not sure how someone could’ve requested to join a HydroShare group without activating their account. That is, unless someone deactivated their account after they made the group request. I have not made any changes/modifications to user accounts in the HydroShare Admin interface. I’m going to move this conversation into GitHub so we can include some of the devs in our discussion.

Steps to reproduce the bug:
1. Go to https://www.hydroshare.org/group/156
2. Select Members/Pending
3. Click on Maryam Bagheri to view the user profile
4. 
![image](https://user-images.githubusercontent.com/4822372/149961219-df750abe-e78d-4218-baf9-54f1452aeb67.png)

**Comment by dtarb** [comment]
There is a deactivate account link in user profile. Perhaps the user decided against using HydroShare and de-activated their account.  I suggest that fixing this bug should just involve messaging.  Rather than "an error occurred" the message should be "This user account has been de-activated."

**Comment by pkdash** [comment]
@dtarb and @Castronova If the user account is not active, I think we should not be displaying a pending request from that user.

**Comment by devincowan** [comment]
@dtarb @Castronova: we can either:
1. set group requests from deactivated users to `GroupMembershipRequest.redeemed=True` as @sblack-usu suggested on #4484 
2. Or we can leave the requests open in the database but filter them based on `user_to_join_group.is_active`

The second option would ensure that re-activated accounts would still have their group requests, so those users would not have to re-request. But it has the downside that the un-redeemed request is still sitting in the db perhaps in perpetuity.

I don't know how frequently we re-activate accounts? I'm guessing it is rare and if so, we should mark the requests redeemed in the db.

**Comment by Castronova** [comment]
@devincowan Regarding option 1, would this mean that a user would be able to:

1.  request access to the group
2. deactivate their account
3. upon reactivation, they would now be a member of the group even through they were never formally admitted.

If so, I can see this being a potential issue.

**Comment by devincowan** [comment]
@Castronova **NO** a user would not be able to gain membership to a group after reactivation without approval.
Rather the flow would be:
1. request access to the group
2. request is pending with the group owner
3. deactivate their account
4. request is still pending in the db, but it does not show in the UI as an active request
5. upon reactivation, _the request is still pending with the group owner_
