### ISSUE TITLE
Do not update last changed date when a new version is created

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#4472]
**Description of the bug**
If I create a new version of a resource (with say a 2020 date on it) in 2022 the last updated date for the original resource is changed to the present time.  This is incorrect as the last updated date is what is used in the citation of the original resource and should remain unchanged.

Steps to reproduce the bug:
1. Go to a resource that was last updated previously (e.g. https://www.hydroshare.org/resource/1a64f1c4cbcc4a2b919c943fc5ec111f/)
2. Click on Create a new version 
3. From the new version (e.g. https://www.hydroshare.org/resource/3244cea9618b4048ab0937cf9468a821/) click back to the previous version
4. See that the older version now has a last updated date that is the time the new version was created

**Expected behavior**
When a new version of a resource is created, the last updated date of an old version should not be changed.

**Comment by hyi** [comment]
@dtarb I have tested on the newly released production and verified last changed date did not get changed after a new version is created, so I am closing this issue.
