### ISSUE TITLE
My Resources Page: Minor style fix on my resources search box

### ISSUE THREAD

**Issue by mauriel133** [hydroshare/hydroshare#448]
As implemented in http://dev.hydroshare.org/my-resources/, the search box in my resources page seems to have two borders.

**Comment by mauriel133** [comment]
Adding multiple search items also overflow the search box and the entire page.

**Comment by ironfroggy** [comment]
Someone has to enter a lot of search items to trigger this. @dtarb how do you want me to prioritize this against other work?

**Comment by ironfroggy** [comment]
Does the linked PR close this ticket?

**Comment by mauriel133** [comment]
It takes care of the border style, but not the overflow issue. I think we should keep it open.

**Comment by dtarb** [comment]
@mauriel133 is this something you can/will address, or do you need help.

**Comment by mauriel133** [comment]
I need help from the person who implemented it.

**Comment by ironfroggy** [comment]
@mauriel133 can you be more specific? what sort of help do you need?

**Comment by mauriel133** [comment]
When an item is picked from the autocomplete it gets added to a container within the search box. The cursor on the search box is also moved to the right to make room for the item. But this results in the search box overflowing and layout errors in general. Possible solutions

1 - Make the search box expand when necessary.
2 - Have the container displayed always below the search box and have it expand as more items are added. 

Could you tell me where the code with the current implementation is right now?

**Comment by ironfroggy** [comment]
This is all implemented in my-resources.html right now.

I wanted to keep the search items as a prefix to th etyped terms in the
search bar, as if they were part of what you've got typed in. This is
possible to keep, but is going to be harder to support for multiple rows. I
think you should move them below the search bar as suggested.

On Thu, Jun 4, 2015 at 3:48 PM, Maurier Ramirez <notifications@github.com>
wrote:

> When an item is picked from the autocomplete it gets added to a container
> within the search box. The cursor on the search box is also moved to the
> right to make room for the item. But this results in the search box
> overflowing and layout errors in general. Possible solutions
>
> 1 - Make the search box expand when necessary.
> 2 - Have the container displayed always below the search box and have it
> expand as more items are added.
>
> Could you tell me where the code with the current implementation is right
> now?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hydroshare/hydroshare/issues/448#issuecomment-109029298>
> .
>



-- 


*Calvin Spealman*Lead Front-end Developer

calvin@caktusgroup.com <calvin@caktusgroup.com>
www.caktusgroup.com

**Comment by mauriel133** [comment]
Alright, I'll take care of that.

**Comment by mauriel133** [comment]
This is no longer an issue since the addition of the new My Resources page. Can we close it?

**Comment by horsburgh** [comment]
Yes. I'm going to close it since it is not an issue with the new implementation of the My Resources page.
