### ISSUE TITLE
Cannot redeem group memebership requests with inactive users

### ISSUE THREAD

**Issue by sblack-usu** [hydroshare/hydroshare#4484]
**Description of the bug**
When a user requests access to a group and then deletes (inactivates) their account, the group membership request cannot be redeemed.

Steps to reproduce the bug:
1. Create a test user
2. Request to join a group with the test user
3. Deactivate the test user account
4. As a group owner, attempt to accept/reject the group membership request from the test user
5. Observe the request reappears after a refresh

**Expected behavior**
Requests from inactive users should be removed.

**Additional information**
Here is the method which fails to redeem a user request from an inactive user.  https://github.com/hydroshare/hydroshare/blob/develop/hs_access_control/models/user.py#L151

I believe this request would get to this method call which would raise a PermissionDenied exception as the user_to_join_group is inactive.  https://github.com/hydroshare/hydroshare/blob/develop/hs_access_control/models/user.py#L205

If the user is inactive, the GroupMembershipRequest.redeemed field should be set to True and saved without any group/user permission changes.

**Comment by dtarb** [comment]
This is essentially the same as #4456, but the additional code location information Scott added here is good.
