### ISSUE TITLE
update "How to cite" messaging

### ISSUE THREAD

**Issue by martinseul** [hydroshare/hydroshare#4498]
The messaging on the resource landing page "how to cite" need updating.  

![image](https://user-images.githubusercontent.com/5427742/154575429-dc0b1850-65ae-4344-8917-708de427f990.png)

the reminder text is incorrect as you can edit parts of the resource.

**Comment by aaraney** [comment]
related to #4505 and #4507

**Comment by devincowan** [comment]
Updating to bring in line with our other messaging
![image](https://user-images.githubusercontent.com/17934193/160883844-c075a053-d583-4930-a545-6b1956cf9d6a.png)
