### ISSUE TITLE
Multiple alternative names

### ISSUE THREAD

**Issue by ironfroggy** [hydroshare/hydroshare#45]

**Comment by rayi113** [comment]
HydroShare Profile Issues in GitHub: #44, #46, #47, #48, #49, #68

**Comment by horsburgh** [comment]
@ironfroggy - can you provide a little more description here?  Are you suggesting that users should be able to add multiple names to their user profile?

**Comment by dtarb** [comment]
I think I am the culprit for suggesting that we need to have a way to accommodate someone who has a name like "William Arthur Philip Louis Windsor", so not only one middle name.  Someone must have solved this problem somewhere, so if we can find an existing solution, it is preferable.

**Comment by ironfroggy** [comment]
Handling the multitude of human naming, especially being both inclusive of and sensitive to very non-western structured names, I'm in the camp that the best option is to give the person as much flexibility and as few assumptions as possible. Rather trying to break down the structure of the name (into first, last, maybe middle, maybe an honorific, maybe a suffix?) consider the things you want to do with that name.

Really what we're usually after is to list a Full Name in certain official capacities, and to refer to the person in a shorter fashion with a Given Name. So, just ask for those. Give a Full Name field and a Given name field. Let them fill those out however it makes sense for them. Help them a bit, if you wish, by auto-filling the Given Name with the first part entered in the Full Name field, but let them edit it to whatever is correct.

And don't validate anything you absolutely don't have to. They know more about their name than you do.

**Comment by dtarb** [comment]
The things we want to do with names are:

* Be part of the identification of a user
* As a display label for identifying owner, author, contributor etc
* As a name in a formal citation

This has to be a somewhat solved problem with systems like Endnote, Bibtex, Procite, LinkedIn.  We should be adopting something existing and simple if at all possible.

**Comment by horsburgh** [comment]
@ironfroggy and @dtarb - just a quick note Dave's final bullet. Citations are typically listed with full last names but with any other names listed as initials. Our implementation needs to support this.  For example:

Horsburgh, J., A.Jones (2015). Water Temperature in the Little Bear River at Mendon Road near Mendon, UT, HydroShare, http://www.hydroshare.org/resource/1a25b11fa1354773b6edb9495e754f4e

Actually, in looking at this citation that I just copied from HydroShare, there is no space between the Amber's initial and last name.  I'll create a new issue for that. Should be an easy fix.

**Comment by mauriel133** [comment]
The new profile page implements First Name, Middle Name and Last name fields. Are these sufficient to address this problem?

**Comment by horsburgh** [comment]
@mauriel133 - as I told you last week, I think you are more qualified to weigh in on this question than I am given that your name doesn't meet typical American patterns. I'm satisfied with what we have now because it meets what I think our immediate needs are.

**Comment by mauriel133** [comment]
Implementation includes First Name, Middle Name and Last Name. This should be sufficient to accommodate all users. Can be tested at https://park.hydroshare.org

**Comment by mauriel133** [comment]
Implemented with revamp of profile page. Please confirm and close.

**Comment by horsburgh** [comment]
The result of going with First Name, Middle Name, and Last Name came after a lot of discussion. This has been implemented. Closing.
