### ISSUE TITLE
Migrate Script Resources to Composite Resource

### ISSUE THREAD

**Issue by pkdash** [hydroshare/hydroshare#4530]
This is needed before we can delete this deprecated resource type  as required in #3129 

**Migration Rules:**
Migrate resource type specific metadata to resource level as extended metadata. No aggregation needs to be created as part of the migration:

**Here is an example of script resource specific metadata:**

Programming Language: Python
Programming Language Version: Python 3
Script Version: 1.0
Script Dependencies: 
Release Date: 05/22/2000
Script Repository: https://github.com/john/watershed

We will store all the above metadata as key/value using the extended metadata of the composite resource.
In addition, the following metadata also will be stored as extended metadata in composition resource.
Type: Script

NOTE: There are 29 script resources currently (3/10/2022) in hydroshare.

**Comment by dtarb** [comment]
@sblack-usu here is the google doc of Pabitra and my discussion of this https://docs.google.com/document/d/1Lc8VCkMf5FJPnZ15GtpJQgkbxlZ5gPTqR8pbCDYl9YU/edit
