### ISSUE TITLE
Non-users see resource info instead of redirect to login

### ISSUE THREAD

**Issue by devincowan** [hydroshare/hydroshare#4537]
**Description of the bug**
If not logged in, a user visiting published, public OR DISCOVERABLE resources is NOT redirected to login.
Instead, user is shown all of the resource info except for the content (they can see Related Resources, Comments, How to Cite, authors, etc).
For example, try viewing this on a private/logged out browser: https://www.hydroshare.org/resource/844209cb8da943d5bec4cfa76f68920e/

**Expected behavior**
When not logged in, a user should be redirected to the login page unless the resource they are trying to view is PUBLISHED.

Related to #3429

**Comment by devincowan** [comment]
@dtarb this is the opposite problem from your original issue #3429.
Here browsers not logged into HS are NOT redirected to login when navigating to a resource that is public or discoverable.
Instead, they can see many of the details about the resource (not just the title and owner)

**Comment by horsburgh** [comment]
Doesn't public mean public? Shouldn't unauthenticated users be able to see the details of a public or discoverable resource? Isn't this by design?

**Comment by devincowan** [comment]
@horsburgh indeed, it was my thinking that public meant _public_ as in even unauthenticated users should be able to see the details of a public/discoverable resource. However today in discussion with the development team, I learned this is not the case (unless I misunderstood).

**Comment by sblack-usu** [comment]
I think there is a misunderstanding.  Unauthenticated users should be able to view a resource.

**Comment by devincowan** [comment]
Thanks for the correction Scott. I guess I crossed the wires.

**Comment by dtarb** [comment]
See https://github.com/hydroshare/hydroshare/issues/3429#issuecomment-1064024149
