### ISSUE TITLE
Update PostGIS

### ISSUE THREAD

**Issue by cbcunc** [hydroshare/hydroshare#4540]
### Abtract

This issue requests an upgrade of the PostGreSQL version used for Hydroshare's Django database server to the latest agreeable version.

### Action Items

- [ ] Agreement should be reached in the Monday morning HS developer conference call concerning the latest agreeable version of PostGreSQL {see [Version](#version)}.
- [ ] Consider in the developer call moving the project to the organization level instead of the repository level {see [Project Board](#project-board)}.
- [ ] Revise the PostGIS image Dockerfile {see [Dockerfile](#dockerfile)}.
- [ ] Harmonize the image pull to originate from the Hydoshare Docker Hub organization {see [Image](#image)}.

### Project Board
This issue was opened in [hydroshare/hydroshare](https://github.com/hydroshare/hydroshare) instead of [hydroshare/hs_postgres])https://github.com/hydroshare/hs_postgres) in order to track it on the [HS Issue Management Board](https://github.com/hydroshare/hydroshare/projects/15) project.

### Version
Hydroshare beta and production currently run on PostgreSQL 9.4.7. The 9.4 series had its final release on February 13, 2020 (https://www.postgresql.org/support/versioning/) and is unsupported. The latest available version as of the time of this issue creation is 14.2. Hydroshare has been run successfully in an on-demand cloud-based development environment with PostGreSQL 13.1.

### Targets
PostGreSQL runs in a docker container (name: postgis) on VMWare VMs on a RENCI internal network (edc.renci.org) as non-routable IPs:

- Production: db1-hydroshare.edc.renci.org
- Beta: db1-beta-hydroshare.edc.renci.org

Staging and development versions of Hydroshare use local containers or local PostGresSQL instances {see `POSTGIS_HOST` in [local_settings.py](https://github.com/hydroshare/hydroshare/blob/develop/hydroshare/local_settings.template)}.

### Dockerfile
On both VMs, the Dockerfile used as the build source for the container's image is taken from [hydroshare/hs_postgres](https://github.com/hydroshare/hs_postgres).

### Image
On beta, the image is pulled from the Hydoshare organization (https://hub.docker.com/repository/docker/hydroshare/hs_postgres). On production, the image is pulled from the personal repository of the original image author ((https://hub.docker.com/r/mjstealey/hs_postgres).

### Deployment

Saving work on issue... to be continued...

**Comment by devincowan** [comment]
closing as complete via #4738 and creation of https://github.com/hydroshare/hs_postgis
