### ISSUE TITLE
As a developer, I want to manage our postgres versions and preserve config

### ISSUE THREAD

**Issue by mfergus1** [hydroshare/hydroshare#4548]
Currently, the postgis container image is built from an existing hydroshare image. Currently, there is no way to build the existing image from scratch, which will allow future upgrade texting, and preserve/use the pg.development.sql seed as well as the configuration logic stores in hydroshare/conf_postgres. 

Anticipated deliverables: 
- local-dev.yml (dockercompose) includes build instructions for Dockerfile-postgis 
- Dockerfile-postgis updated to source from postgis/postgis:9.5-2.4 * 

Possible issues: 
- postgis versions in docker start at 9.5 and we are at a 9.4 version

**Comment by martinseul** [comment]
is related to https://github.com/hydroshare/hydroshare/issues/4540 closing
