### ISSUE TITLE
My Resources Page: Own/Edit/Shared with me Checkboxes

### ISSUE THREAD

**Issue by ironfroggy** [hydroshare/hydroshare#455]
I would also like to see Own, Can Edit, Can View and Public as check box filters on the left as you originally proposed in your 3/11/15 email.  (In general going back through that thread would be good).  Note that there may be multiple Owners, Authors or Contributors.  Note also that filtering on owner is different from the "Resources I Own" filter on the left as it allows finding resources owned by someone else.  
![capture](https://cloud.githubusercontent.com/assets/3456833/7671108/a71bf30e-fc7b-11e4-9171-cc5e421c3b10.PNG)
Public needs to be added to the list above.

Follow up from #376

**Comment by mauriel133** [comment]
I think the filters above should have the number of resources meeting each criteria in parenthesis. Something like this
- [ ]  Own (4)
- [ ]  Can Edit (9)
- [ ]  Can View (35)

**Comment by ironfroggy** [comment]
This would be great, but we'll need to watch until filter and discovery perform much much better, before doing three extra versions of the current filter for each checkbox to get a count.

**Comment by ironfroggy** [comment]
This means:
- Finishing the base model refactoring
- Refactor the Metadata fields as planned
- Investigating access control / SOLR combination feasibility

**Comment by horsburgh** [comment]
Based on our latest document, the following Filters are needed, with implementation as check boxes and numbers as described above:

* Owned by me
* Editable by me
* Shared with me

In a second round, we can add the following as filters that will require additional backend functionality to support:

* Favorites
* Following
* Recent

When the first three are complete, I suggest creating separate issues for the other three.

**Comment by mauriel133** [comment]
First four filters have been implemented and working on www.

**Comment by dtarb** [comment]
Good enough!
