### ISSUE TITLE
Moving files or aggregations can leave resource in inaccessible state

### ISSUE THREAD

**Issue by martinseul** [hydroshare/hydroshare#4553]
**Description of the bug**
we have had regular issues reported from user (Abby Lute) moving files around using the content browser. After initiating a move the resource becomes inaccessible and needs to be manually fixed by a developer. 

**Scott** comment: An aggregation was moved but a file associated with the aggregation was not moved with it.  The process likely got interrupted before finishing?  The files are over 1GB, so mix that in with moving several files at once as the reasons for this occurring.  It is hard to tell beyond that.

**Expected behavior**
A user should be able to move files or aggregations within the content folder without issue.

**Comment by hyi** [comment]
The plan for fixing this issue is to add file/folder/aggregation move operation into async framework so that the move operation will not be interrupted. I'll work on adding the move operation into async framework for resolving this issue.

**Comment by devincowan** [comment]
resolved in PR #4598
