### ISSUE TITLE
My Resources Page: Sort Resource List by Attribute Column

### ISSUE THREAD

**Issue by ironfroggy** [hydroshare/hydroshare#456]
I would also like the ability to sort on the columns displayed.  By clicking on the column header the list displayed should be re-ordered similar to the way Windows explorer works on a PC or Finder works on a Mac in list mode. 

Follow up from #376 

- [ ] Dates must sort by date value, not alphabetically.

**Comment by ironfroggy** [comment]
This should be done when base models issues are fixed, because we can't do SQL sorting across models without a common model base.

**Comment by mauriel133** [comment]
This has been implemented in the front end using javascript and it's working on www.

**Comment by dtarb** [comment]
Wonderful!  Except, the Date column sorts the Date alphabetically using the Month first, so August is before January.  It would be more intuitive if date was ordered by date.

**Comment by ironfroggy** [comment]
@dtarb is there a separate ticket for that?

**Comment by dtarb** [comment]
@ironfroggy lump or split.  I did not create a new issue and I did not close this issue because for me sorting by date, is, well, sorting properly by date, and date is one of the attributes, so I left this open as not yet done.  But I am totally fine if you want to close this and create a separate ticket.

**Comment by ironfroggy** [comment]
I'll leave this open and add a final checklist item to the description owing to the remaining fix needed.

**Comment by mauriel133** [comment]
The date column sorting issue has now been addressed. This issue can be closed.

**Comment by horsburgh** [comment]
Agreed. Closing.
