### ISSUE TITLE
Sharable link does not follow existing Editor role conventions

### ISSUE THREAD

**Issue by hydrocheck** [hydroshare/hydroshare#4561]
**Description of the bug**
> Editors can edit resource metadata and add and delete resource content files. If the resource is Shareable editors can use manage access to extend editing or viewing access to other users.
> -Hydroshare Resource Sharing Interface

According to this definition, it should probably be possible for Editors to create and distribute a private sharing link, for Sharable resources.

Steps to reproduce the bug:
1. Create a resource
2. Make the resource sharable
3. Add an Editor
4. Login as the Editor and notice the lack of private sharing link option

**Expected behavior**
Editors can create and distribute private sharing links, or the definition of Editor is refined, around access management for Sharable resources.

**Comment by martinseul** [comment]
after discussing this we decided on a policy as outlined [here ](https://docs.google.com/document/d/1d_m_ZfoF-kvELhpBhsRdfK8orrwaAO6ZYMBD1ADy7Gc/edit#heading=h.maxeeqwagsxo) that allows link sharing only at the owner level
