### ISSUE TITLE
www.hydroshare.org - Need to update development status

### ISSUE THREAD

**Issue by horsburgh** [hydroshare/hydroshare#457]
The development status listed on the support page says we are at 1.4.  Need to update.

http://www.hydroshare.org/help/

**Comment by rayi113** [comment]
This has been updated:
![hs_dev_status](https://cloud.githubusercontent.com/assets/2846017/8035407/696f368e-0dbe-11e5-902d-fc7842292820.png)

**Comment by dtarb** [comment]
This is out of date again as the current footer indicates 1.5.2 but this says 1.5.1.  I suggest revising this text to point to development activity on github without a number that gets out of sync with each release.

**Comment by hyi** [comment]
@horsburgh verified it is working on the newly deployed www and dev - now it retrieves version number directly from github API without any manual intervention. Could you verify and close it if it indeed works as it should?

**Comment by dtarb** [comment]
Working, at least at 1.6.0
