### ISSUE TITLE
cache busting to prevent broken JS and styles on clients

### ISSUE THREAD

**Issue by devincowan** [hydroshare/hydroshare#4571]
**Describe the feature you'd like and what it will do**
While looking into #4570 I noticed we perhaps don't have any frontend build pipeline.

**Why is this feature important?**
We might consider using a build process on the frontend to increase performance (by minimizing js and css and by setting long retention periods) and also to prevent js/html/css cache issues.

**Is your feature request related to a problem? Please describe.**
Related to #4570

**Comment by sblack-usu** [comment]
#3621 tackled this at one point but was later removed.  I'm not sure why.

**Comment by devincowan** [comment]
yes looks like django Freshly was creating issues [#3675](https://github.com/hydroshare/hydroshare/issues/3675)
it was removed in [#3678](https://github.com/hydroshare/hydroshare/pull/3678) and looks like the Freshly folks are no longer supporting
We could explore a different solution. I've only ever used build tools to accomplish this but the idea of a Django package is nice.
Looks like even our old version of Django has a native way to handle this that might work:
[manifeststaticfilesstorage](https://docs.djangoproject.com/en/1.10/ref/contrib/staticfiles/#manifeststaticfilesstorage)
@sblack-usu @martinseul is this something you would like me to experiment with?

**Comment by devincowan** [comment]
we could consider [pipline](https://django-pipeline.readthedocs.io) for minification, but requires django > 1.11

**Comment by devincowan** [comment]
we found issues with this during 1.56 deploy, so reopeneing
