### ISSUE TITLE
Hydroshare footer youtube link incorrect

### ISSUE THREAD

**Issue by martinseul** [hydroshare/hydroshare#4580]
**Description of the bug**
clicking on the you tube link on the Hydroshare footer sends you to a index page
![image](https://user-images.githubusercontent.com/5427742/161587224-cb33ba06-7816-499b-84b1-21545847175b.png)

**Expected behavior**
the link should send you to a CUAHSI page, I would think it would be https://www.youtube.com/user/CUAHSI

**Additional information**
@ClaraCogswell if this is not the right page to show please update

**Comment by martinseul** [comment]
@devincowan could you please look into this should be very easy.

**Comment by ClaraCogswell** [comment]
this is the correct place for it to link out to, the cuahsi youtube

**Comment by devincowan** [comment]
@ClaraCogswell you meant this right?
https://www.youtube.com/user/CUAHSI

**Comment by ClaraCogswell** [comment]
yes!

**Comment by devincowan** [comment]
@ClaraCogswell this parameter is set in Mezzanine, should be located here:
https://www.hydroshare.org/admin/theme/siteconfiguration/1/change/#id_youtube_link
I don't think I have admin priv for mezzanine on production (or if I do, I didn't know it), but I think you do?

**Comment by ClaraCogswell** [comment]
I do! In that case I can fix it


Clara Cogswell (she/her)

Community Support Hydrologist, CUAHSI 

www.cuahsi.org<http://www.cuahsi.org/>  

Sign for CUAHSI news here<https://docs.google.com/forms/d/e/1FAIpQLSfGq_mSXeoCZh0dViLKG6M2GMUBblNEwjg9xeoQA3O7Ny_C8A/viewform?c=0&w=1>! 

________________________________
