### ISSUE TITLE
Profile phone numbers out of order

### ISSUE THREAD

**Issue by Castronova** [hydroshare/hydroshare#459]
When editing my user profile, I noticed that phone2 comes before phone1.
![screen shot 2015-06-03 at 1 24 33 pm](https://cloud.githubusercontent.com/assets/4822372/7969414/ef214a3e-09f3-11e5-8d6a-49c36be245bb.png)

**Comment by horsburgh** [comment]
This will be resolved when @mauriel133 has the new profile editing page going.

**Comment by dtarb** [comment]
Ordering is correct in www now.
