### ISSUE TITLE
Improvements to NetCDF aggregation spatial coverage

### ISSUE THREAD

**Issue by pkdash** [hydroshare/hydroshare#4592]
**Describe the feature you'd like and what it will do**
The following changes are needed:

- There are use cases where a netCDF file does not have to have spatial coverage so we should enable a resource to be made public without spatial coverage in netcdf aggregation.
- There are two coverage elements spatial reference and spatial coverage.  Spatial reference (CF convention) is the coordinate system of the data.  Spatial coverage (ACDD convention) is the WG84 coverage that HS uses.  If spatial reference is in the file, HS should compute spatial coverage from it.  There are cases where spatial reference from the netCDF file is not recognized by HS (which uses GDAL) and thus spatial coverage is not computed.  HS should not allow editing of spatial reference (Need a way to provide users guidance on fixing the spatial reference element in the file.  But suggest do not do this in HS rather provide a JN to do it in a compute platform).
- For resource without spatial reference or with incomplete or incorrect spatial reference, allow users to specify spatial coverage using HS interface.  However, HS won't write spatial coverage to netcdf file as part of updating the nectdf file. 
- In the case where spatial coverage is computed from spatial reference, user should not be allowed to edit spatial coverage. 
- User should not be allowed to edit spatial reference using HS interface.
- HS should extract spatial coverage from netcdf file if available and spatial reference is missing in the file.

**Why is this feature important?**
Currently a resource can't be made public if spatial reference or spatial coverage is missing in one of the netcdf aggregations in the resource. Since there are use cases where a netcdf file doesn't need to have spatial coverage information, spatial reference and spatial coverage need to be made optional so that resource can be made public. 

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...].

**Additional context**
NetCDF CF Convention: http://cfconventions.org/Data/cf-conventions/cf-conventions-1.9/cf-conventions.html
NetCDF ACDD Convention: https://wiki.esipfed.org/Attribute_Convention_for_Data_Discovery_1-3

**Comment by pkdash** [comment]
@dtarb, @horsburgh and @Castronova Let me know if the changes listed above related to netcdf aggregation coverage metadata  seem reasonable. Here is a google doc that contains some additional notes about these changes:
https://docs.google.com/document/d/1wzofoyZREzucFrv_yYAYwTJqAnZdWLBHLb_0xA_JEdE/edit?pli=1

**Comment by dtarb** [comment]
See #2995 and address together
