### ISSUE TITLE
Add new grant to list in footer

### ISSUE THREAD

**Issue by Maurier** [hydroshare/hydroshare#4596]
**Describe the feature you'd like and what it will do**
As a request from @ClaraCogswell, the grant `1849458` needs to be added to the list of grants in the footer. This also needs to be updated for the footer used in the help pages.

**Comment by sblack-usu** [comment]
In HydroShare this can be done by anyone with an admin account, screenshot is here.
<img width="1680" alt="Screen Shot 2022-07-18 at 8 36 08 AM" src="https://user-images.githubusercontent.com/35820390/179548595-76667a4a-c2a1-4b06-8882-4ab368fde604.png">

For help, just update the same footer.html file that is updated for the hydroShare version number with each release.

**Comment by ClaraCogswell** [comment]
Good to know, I'll do it in the futute

**Comment by ClaraCogswell** [comment]
Shall I move into merged?
