### ISSUE TITLE
User Type as a field on profiles

### ISSUE THREAD

**Issue by ironfroggy** [hydroshare/hydroshare#46]
University Faculty, 
University Professional or Research Staff, 
Post-Doctoral Fellow, 
University Graduate Student, 
University Undergraduate Student, 
Commercial/Professional, 
Government Official, 
School Student Kindergarten to 12th Grad, 
School Teacher Kindergarten to 12th Grade, 
Other,
Unspecified.  
When a user is initially created the default is "Unspecified".  "When a user selects Other, there should be a Text field to specify Other

**Comment by rayi113** [comment]
HydroShare Profile Issues in GitHub: #44, #46, #47, #48, #49, #68

**Comment by mauriel133** [comment]
Can be tested at https://park.hydroshare.org

**Comment by mauriel133** [comment]
Implemented with revamp of profile page. Please confirm and close.

**Comment by horsburgh** [comment]
Just tested on www. "Usertype" is there and it is listed as a Required element. By default it is set to "Unspecified". I was able to edit and save my profile without changing this. "Unspecified" is a valid value, and by setting it as a default we may run the risk of having people never change it.

Could we have it be like "Organization" where it is not set when a user signs up, but they have to select a value from the drop down list upon editing their profile the first time? If they select "Unspecified", fine, but at least they are making the choice and not us. 

Same with "Country" and "State/Province".

**Comment by mauriel133** [comment]
@horsburgh, is this still an issue?

**Comment by horsburgh** [comment]
I think this has been addressed.
