### ISSUE TITLE
Resource Access Style Expand Button

### ISSUE THREAD

**Issue by Castronova** [hydroshare/hydroshare#460]
The resource access panel that appears on landing pages has a **(+)** sign which enables the user to expand the panel.  However when the panel is expanded, the same **(+)** sign is used to collapse it.  This should be changed to another icon such as **(-)**.

![screen shot 2015-06-03 at 1 27 42 pm](https://cloud.githubusercontent.com/assets/4822372/7969496/739d14dc-09f4-11e5-8c79-b56189c781a0.png)

![screen shot 2015-06-03 at 1 27 48 pm](https://cloud.githubusercontent.com/assets/4822372/7969501/7d610b7c-09f4-11e5-8a5b-32707a72df48.png)

**Comment by mauriel133** [comment]
This issue has been taken care of by the new access control interface being developed [#447] and can be closed.

**Comment by horsburgh** [comment]
Agreed. Closing this issue.
