### ISSUE TITLE
Embed "How to" videos on the resource landing page to ease access

### ISSUE THREAD

**Issue by ClaraCogswell** [hydroshare/hydroshare#4604]
**Describe the feature you'd like and what it will do**
This feature would create a minimal and unobtrusive but accessible link to the HydroShare how to videos

**Why is this feature important?**
This feature provides an accessible help option for those who either have trouble finding the help pages, or are visual learners and would prefer to watch short videos. 

**Is your feature request related to a problem? Please describe.**
There is a problem with people being a=unaware of HydroShare's capabilities and unable to find help documentation. one way to combat this would be to add links to videos on the landing page

**Additional context**
youtube videos are here: https://www.youtube.com/playlist?list=PLPG5Ed5L1SY664Lj7dQFBnVMTOrjO0cqa

**Comment by martinseul** [comment]
@ClaraCogswell we typically assign developers once it has been prioritized and is schedule to be worked on not when the issue is created so I removed assignments for now. It would also help if we can get a list of videos and the appropriate pages/UI elements to link to so we can keep track.

**Comment by ClaraCogswell** [comment]
I'll compile a list of relevant videos and placements and we can discuss on Wednesday

**Comment by ClaraCogswell** [comment]
![Mockuplandingpage](https://user-images.githubusercontent.com/90924476/166805501-0d44974c-3c1e-4551-88b8-b58f17551fd1.png)


Video Links: 
Upload files: https://help.hydroshare.org/hydroshare-resources/content-types/time-series/
Change Sharing status: https://www.youtube.com/watch?v=_zfeUpyk0to&list=PLPG5Ed5L1SY664Lj7dQFBnVMTOrjO0cqa&index=7

Will make: 
All about publication
Authors and owners
Open with

Let me know if any other aspects of the page need videos or could use a button

**Comment by ClaraCogswell** [comment]
That icon is just a mockup that I took form powerpoint, we'll likely need to make our own little video icon or use the youtube logo.

**Comment by martinseul** [comment]
agree to the icon change and I like the youtube icon idea this would be easily recognized. One think to consider is if we want to add a direct link to the appropriate page in the help documentation as we had mentioned through an icon we'd be adding more icons to the page. 
In general we have an inconsistent way of providing information to users. we have 

- this Info button
 ![image](https://user-images.githubusercontent.com/5427742/167167798-fb7e4e50-39e5-4a08-a27c-33f383d4c646.png) 
- this not collapsible banner 

-  ![image](https://user-images.githubusercontent.com/5427742/167168022-35016c1f-282c-4e10-bdcf-6a5c5d4b0f8e.png) in yellow this collapsible banner in yellow or blue 

![image](https://user-images.githubusercontent.com/5427742/167168155-874bd1ac-a5f7-4dce-bce8-e85ef6f8afdb.png)
- this banner in green:
![image](https://user-images.githubusercontent.com/5427742/167168754-61e37598-c55a-46b8-b213-e8b8b8a0eafa.png)

- this embedded text 
![image](https://user-images.githubusercontent.com/5427742/167168236-8a091d6e-ba31-44b2-b7c9-6f71b463086b.png)

- maybe add another button for youtube videos 

this is might not be the right time but there is a need to look at the notification/messaging approach to remove clutter. @Maurier are there options in vue to consolidate natifications?

**Comment by ClaraCogswell** [comment]
All of the videos required for this have now been completed. They should be up on youtube in the next day or so.

**Comment by ClaraCogswell** [comment]
All videos are now up on the youtube channel

All about publication: https://youtu.be/vlVnWN5aUOk

Authors and owners: https://youtu.be/5rYQjvnRXlI

Open with: https://youtu.be/DNHmDDRH9nY

How to upload files: https://youtu.be/wTPGJY9-k18

How to change sharing status: https://youtu.be/_zfeUpyk0to

**Comment by ClaraCogswell** [comment]
what is still required for this is an icon for the videos, we have been discussing whether we want to create our own icon or use the youtube logo. 
@horsburgh do you know what was entailed in using the youtube logo at the bottom of the page?

**Comment by devincowan** [comment]
@ClaraCogswell here are some guidelines
https://www.youtube.com/howyoutubeworks/resources/brand-resources/#logos-icons-and-colors

**Comment by horsburgh** [comment]
@ClaraCogswell - I think @Maurier should be able to set us up with an icon to use for this.

**Comment by Maurier** [comment]
Noted. I'll work on this some time this week.

**Comment by ClaraCogswell** [comment]
I don't think so. The content they point to cannot be influenced by the user, they can only view the videos, so only one icon should be needed

**Comment by Maurier** [comment]
Right, but the topics in these videos is about features for which one would need edit permissions on a resource in order to use.

**Comment by ClaraCogswell** [comment]
That makes sense to me. They can appear in edit mode


Clara Cogswell (she/her)

Community Support Hydrologist, CUAHSI 

www.cuahsi.org<http://www.cuahsi.org/>  

Sign for CUAHSI news here<https://docs.google.com/forms/d/e/1FAIpQLSfGq_mSXeoCZh0dViLKG6M2GMUBblNEwjg9xeoQA3O7Ny_C8A/viewform?c=0&w=1>! 

________________________________
