### ISSUE TITLE
Deprecated resource types need to be removed from Contributions tab in profile

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#4641]
The profile page contributions tab depicts the following

![image](https://user-images.githubusercontent.com/3456833/172024892-19230976-d544-4557-91a3-c8b9103b2da2.png)

All resource types except Composite, Collection and Web App are deprecated.  The following changes are needed
- Rename "Composite resource" to "Resource"
- Change filters to identify resources that hold valid aggregation types
- Change "Web App" to 'Web App Connector"
- Remove the Composite resource icon on the right side of the resource listing item and instead depict the included content aggregations.

**Comment by pkdash** [comment]
@dtarb and @devincowan I am fixing this as part of issue #4853

**Comment by pkdash** [comment]
This has been fixed in release 2.1
