### ISSUE TITLE
HISTimeSeries files output to the hydroshare directory

### ISSUE THREAD

**Issue by mjstealey** [hydroshare/hydroshare#466]
HISTimeSeries files are winding up in the main hydroshare directory.
This should not occur.

Example from www.hydroshare.org:
```bash
hydrobuild@www hydroshare]$ ls
backup-db                dockerPurge.sh             hs_app_netCDF             hydroshare            restore-db
backup-media-linux       docs                       hs_app_timeseries         init                  restore-media-linux
deploy-hs                dublincore                 hs_core                   __init__.py           run-tests
django_docker_processes  fig.yml                    hs_docker_base            irods_browser_app     scripts
django_irods             fig.yml.dev                hs_geo_raster_resource    jquery_ui             theme
docker-compose.yml       fig.yml.prod               hs_metrics                LICENSE.txt           uwsgi.ini
docker-compose.yml.dev   ga_ows                     hs_modelinstance          manage.py             visualization-7-DVNI1.png
docker-compose.yml.prod  ga_resources               hs_model_program          pg.development.sql
Dockerfile               HISTimeSeries.csv          hs_rhessys_inst_resource  README.md
Dockerfile.irods         HISTimeSeries-wml_1.xml    hs_swat_modelinstance     ref_ts
Dockerfile.local         HISTimeSeries-wml_2_0.xml  hs_tools_resource         resource_aggregation
```

**Comment by zhiyuli** [comment]
@pkdash  @selimnairb @jsadler2  @mjstealey 
A Refts resource is referencing (or say a copy of ) an external non-hydroshare resource. Each time users refresh a Refts resource landing page, the backend retrieves again the data and creates new files, temporarily stores them on hydroshare server, updates existing Refts resource files and finally deletes these temporary files.

We tried using tempfile.mkdtemp() to create a dynamic dir for temporary storage (like /tmp/tmpcnC6ln). However when we pass these file handles to hydroshare.add_resource_files(), it will break down.

If we just store the new files in current folder (the source code folder),  it works. We  are guessing the  hydroshare.add_resource_files() may not support file with absolute path???  
Any suggestion?

Thanks
Drew

The code looks like this:

tempdir = tempfile.mkdtemp()
csv_name = 'new_res_file'
csv_name = tempdir + "/" + csv_name
with open(csv_name, 'wb') as csv_file:
     csv_file.write (...)
csv_file = open(csv_name, 'r')
files = [csv_file, wml2_file, vis_file]
for f in files:
        hydroshare.add_resource_files(res.short_id, f)

**Comment by dtarb** [comment]
I question the workflow associated with this model where every time a page is refreshed the dataset is downloaded and files regenerated.  This needs rethinking.  A reference resource is by definition a link to data kept somewhere else.  It seems to me it should not need files stored locally.  If files are stored in HydroShare then it is a resource held by HydroShare and should be characterized as such.

**Comment by valentinedwv** [comment]
If the files are small, can you map the to memory

**Comment by selimnairb** [comment]
@zhiyuli What do you mean by "However when we pass these file handles to hydroshare.add_resource_files(), it will break down."?  Could you describe the failure in more detail?

You might also try storing them in redis if they are less than 512MB.  You can set a time to live so that data are periodically re-fetched: http://redis.io/topics/data-types-intro#redis-expires-keys-with-limited-time-to-live

I believe we already have redis installed in our stack.

**Comment by zhiyuli** [comment]
I got this error when adding a list of files with absolute paths
(/tmp/tmpbUXKVX/*.*) to a resource :
hydroshare.add_resource_files(res.short_id, *files)

Looks like irods trying to create a similar folder structure but failed...
[image: Inline image 2]

**Comment by selimnairb** [comment]
@zhiyuli Sorry, we can't see your screenshot.  Could you describe the error?

**Comment by zhiyuli** [comment]
@selimnairb 
Hi Brian,
This is the error message. 
P.S. Should I reply this thread in my email or on github website?
Thanks
Drew

SessionException at /hsapi/_internal/create-ref-time-series/

(SessionException(...), 'Error processing IRODS request: 3. stderr follows:\n\nERROR: mkdirUtil: mkColl of /tmp/tmphbOOCC error. status = -130000 SYS_INVALID_INPUT_PARAM\n')

Request Method: 	POST
Request URL: 	http://127.0.0.1:8000/hsapi/_internal/create-ref-time-series/
Django Version: 	1.7.8
Exception Type: 	SessionException
Exception Value: 	

(SessionException(...), 'Error processing IRODS request: 3. stderr follows:\n\nERROR: mkdirUtil: mkColl of /tmp/tmphbOOCC error. status = -130000 SYS_INVALID_INPUT_PARAM\n')

Exception Location: 	/home/docker/hydroshare/django_irods/icommands.py in run, line 171
Python Executable: 	/usr/bin/python
Python Version: 	2.7.6
Python Path: 	

['/home/docker/hydroshare',
 '/usr/local/lib/python2.7/dist-packages/netCDF4-1.1.1-py2.7-linux-x86_64.egg',
 '/usr/lib/python2.7/dist-packages',
 '/home/docker/src/python-irodsclient',
 '/home/docker/hydroshare',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages/PILcompat',
 '/home/docker/hydroshare',
 '/home/docker/pycharm-debug',
 '/usr/local/lib/python2.7/dist-packages/IPython/extensions']

Server time: 	Mon, 15 Jun 2015 14:58:38 +0000

![image](https://cloud.githubusercontent.com/assets/10070599/8162991/b4a49048-133d-11e5-9f70-1f76591dbcf6.png)

**Comment by selimnairb** [comment]
@hyi Any ideas what this iRODS error might be?

**Comment by danames** [comment]
David T. We make a local copy temporarily to speed up graphing and
download. It's just a caching mechanism. Maybe we need to make a more
site-wide useful caching system, but I'm not sure what other resources need
it.

**Comment by selimnairb** [comment]
@danames We should refactor this to cache globally using redis (which should already be configured for use in our environment), or something like it.  As it stands now, if we bring up multiple Django instances running on distinct VMs (which we will likely need to do at some point to scale out), hs_timeseries may break if the cached file is not available under the same name on all instances.

**Comment by hyi** [comment]
@zhiyuli @selimnairb This error means iRODS cannot create a directory/collection in /tmp due to permission. Since we are using that irods proxy user to store files in iRODS, you can only store files under the home directory of that irods proxy user. If you need to add a temporary file as part of the resource via Add_resource_file() call, the file needs to be stored as part of the resource in irods proxy user's home directory/resource_id/data/contents hierarchy. If you only want to create a temporary directory in Django server, you can create it in /tmp directory, then delete it, but it will not become part of the resource which is stored on iRODS server side.

**Comment by zhiyuli** [comment]
@hyi  Sorry, I don't quite understand how the proxy user works...We want to create a temporary directory on Django server to store some files (/tmp/*.*). After uploading these files to irods (/resource_id/data/contents/*.*), we will remove this folder and files on django server. Can we do that?

Thanks
Drew

**Comment by selimnairb** [comment]
@zhiyuli As I mentioned before, this is not a good idea as eventually it will break when we bring up additional Django servers to serve HydroShare.  In the short term, if you must store temp files locally, you should use the [tempfile](https://docs.python.org/2.7/library/tempfile.html) module rather than assuming you can write to /tmp.  

I suggest that you push the code in question to a branch and issue a pull request so that we can do a proper code review.

**Comment by hyi** [comment]
@zhiyuli Yes, you can do that, and @gantian127 might have done something similar to netcdf resource when creating the header.txt file although I am not sure whether this is indeed the case. Try to do UploadedFile(file=tmpfile, name=filename) then pass in this UploadedFile as parameter to add_resource_files() to see whether this fixes your issue.

**Comment by zhiyuli** [comment]
merged to dev. closing
