### ISSUE TITLE
Reduce tab sprawl for Apps

### ISSUE THREAD

**Issue by hydrocheck** [hydroshare/hydroshare#4660]
Clicking on "Apps" from the main menu opens a new tab, then each app on that page opens it's own new tab.  So, for example, opening any app creates three browser tabs.  Historically, clicking on "Apps" in Hydroshare did not open a new tab (before and after this click, you're still in Hydroshare) - so this proposal is effectively reverting a change (unknown regression?).  The new tab for clicking an individual app seems reasonable.

When implementing the link change, it would be ideal for environments to stay together (e.g., beta.hydroshare.org "Apps" goes to hydroshare.org/apps/, not beta.hydroshare.org/apps/)

**Comment by devincowan** [comment]
Looks like navbar **Apps** is hard linked to production Hydroshare:
[navbar.html](https://github.com/hydroshare/hydroshare/blob/develop/theme/templates/includes/navbar.html#L294)
So it is possible that the 2nd tab will only be an issue observed on Beta?

**Comment by devincowan** [comment]
I stand corrected. At least as of v1.56, selecting navbar "Apps" does indeed open a new tab even on production
