### ISSUE TITLE
Logging in for private resource viewing does not redirect to the desired resource

### ISSUE THREAD

**Issue by hydrocheck** [hydroshare/hydroshare#4661]
Using the new private resource access workflow, logging in does not redirect to the desired resource.  This is a regression compared to previous behavior.  Creating a new account suffers from the same issue (seemingly due to the email verification workflow breaking the "?next=" query parameter workflow).  Aside - I would suggest adding an article to "Log in or create account" so that it becomes "Log in or create an account" to improve the flow a little.

https://user-images.githubusercontent.com/43424907/173349327-9b82ee21-414b-4499-8262-8435a029bdbd.mov

**Comment by devincowan** [comment]
#4662 resolves the "Login" redirect issue. @hydrocheck is correct: our email verification workflow prevents redirect after "Signup"
