### ISSUE TITLE
Download doesn't wait for rights statement confirmation

### ISSUE THREAD

**Issue by devincowan** [hydroshare/hydroshare#4665]
**Description of the bug**
If a resource has "Require agreement to rights statement before downloading" checked, when a user attempts to download a bagit zip, a modal is shown with the rights statement. However, the download proceeds even without the user accepting the statement. 

Steps to reproduce the bug:
1. Create a resource with some files
2. Check the "Require agreement to rights..." checkbox
3. In the file browser, select the "Download all content as zipped bagit..."
4. The modal will show but the download will also start before acceptance
5. This is also true for collection resources as shown in the video below

**Expected behavior**
Download should wait for the rights statement to be confirmed

**Additional information**
Firefox 101, HS v1.055.2

https://user-images.githubusercontent.com/17934193/173404691-09efd43d-ebb1-4d8c-ba33-9b8bd1b15c9d.mov

**Comment by dtarb** [comment]
I tested this for a composite resource - [this one](https://www.hydroshare.org/resource/12a852cadcc2446aa128ca5201f9a7af/) - (which is the default resource type) and was not able to actually download without agreeing to the modal dialog.  However I did experiences a glitch in that the download bag results in a spinner icon starting up until the license agreement is accepted and this persists if the license agreement modal is cancelled.  This seems to be a javascript frontend issue.

**Comment by devincowan** [comment]
Thanks for checking @dtarb. For a _composite resource_, this issue **only happens if one doesn't refresh the page** (remain in edit mode) after checking the "Require agreement to rights..." and before initiating zipped download. --at least this is the behavior on Firefox for v1.57.1

For a _collection resource_, I am able to download the zipped contents even after "requiring agreement" and subsequently refreshing the page. This is true for both the owner of the collection, as well as other users if the collection is made public.

And I agree that the "download bag" spinner has a bug

**Comment by dtarb** [comment]
@devincowan I see.  It would be good to fix these quirky bugs.  The case could be made that if a user has edit permissions on a resource they are either the owner or the owner has given them access, so downloading with out checking the box is not really a problem, but there should be consistency.  If the modal opens download should not start before it is agreed to.  For owners, it seems redundant to open the modal (though it does little harm).  For editors, a case could be made either way.  I am happy for you to think this through and fix so we do not have inconsistencies.
