### ISSUE TITLE
If a resource type is included for a tool, the resource breaks

### ISSUE THREAD

**Issue by jsadler2** [hydroshare/hydroshare#467]
I made a tool and included RefTimeSeries as one of the relevant resource types. When I click a RefTimeSeries resource it gives me this :/
![capture](https://cloud.githubusercontent.com/assets/6943441/7994432/a1580ac2-0aca-11e5-9891-a364c2735e4c.PNG)

**Comment by pkdash** [comment]
@jsadler2 It is not possible to navigate from metadata element to its container object then to the resource  that uses that metadata container object. We used to be able to that pre 1.5 release. I think you can get the url like this:
 ```url = res_type.content_object.url_bases.first()```

**Comment by jsadler2** [comment]
Okay. I'll try that out thanks @pkdash

**Comment by zhiyuli** [comment]
already merged. closing
