### ISSUE TITLE
Error! Metadata updated failed. - Application Resource

### ISSUE THREAD

**Issue by jsadler2** [hydroshare/hydroshare#468]
When I edit any of the metadata elements, general or resource specific, I get "Error! Metadata updated failed." when I click save. However, the changes seem to be saved all the same.

**Comment by dtarb** [comment]
Closing as this appears stale.  It seems like several app resources have been successfully created and edited.  I am able to create an app and edit metadata without error so I presume this is resolved.  @jsadler2 if this is still an issue, please reopen or post another with specific details.
