### ISSUE TITLE
Web App Connector URL patterns for aggregation and file need encoding of pattern key values

### ISSUE THREAD

**Issue by pkdash** [hydroshare/hydroshare#4693]
**Description of the bug**
URL patterns used at aggregation and file level using keys such as `${HS_FILE_NAME}, ${HS_AGG_PATH}, ${HS_MAIN_FILE}, and ${HS_FILE_PATH}` currently the values used for these keys are not being encoded.
**Example**:
App Aggregation URL Pattern: `https://www.hydrolearn.org/${HS_RES_ID}?aggr-path=${HS_AGG_PATH}`

Aggregation path: `folder with space/netcdf_valid.nc`

For the above pattern and aggregation path, HydroShare generates this: `https://www.hydrolearn.org/49a9db8fc3c74e93b68b9b7d9546d76e?aggr-path=folder with space/netcdf_valid.nc`

It should be:
`https://www.hydrolearn.org/49a9db8fc3c74e93b68b9b7d9546d76e?aggr-path=folder%20with%20space/netcdf_valid.nc`

Steps to reproduce the bug:
1. Use Chrome browser for this testing. However, the bug is not browser specific. Chrome will allow us to see the raw url that it receives. Browser like Firefox, decodes url when it receives it. 
2. Create resource. In that resource create a folder with name "fileset folder". Note the folder name needs to have a space. Upload a file to that folder. Make that folder a fileset aggregation.
3. Create a Web App Connector (name the app as 'Test Web App'). Edit the metadata for the web app to associate it with fileset aggregation. For app aggregation url, enter (Note the domain name is not a real domain name - we are interested to see how hydroshare generates this url to open the app): 
     https://mywebapp.org/${HS_RES_ID}/${HS_AGGR_PATH}
4. Save the web app metadata.
5. Also add the app to open with list.
6. View the resource in view mode. Right click on the folder (fileset folder) and you should see the option 'Test Web App'. Click the Test Web App option. This should open a new tab in your browser. Verify the url displayed in the new browser tab is as below (resource id has been shown as a placeholder and you should see the real resource id):

      https://mywebapp.org/[res id]/fileset folder
 
8. Note the last part of the url ('fileset folder') contains a space which means the url is not properly encoded.

**Expected behavior**
In this particular test case the url should be: https://mywebapp.org/[res id]/fileset%20folder

**Additional information**
Add any other context about the problem here such as screenshots, software versions, and browser information.

**Comment by dtarb** [comment]
This supersedes #3513.  Once this issue is closed, also close #3513 with a note that the creators can re-open if there are any remaining problems.

**Comment by Castronova** [comment]
@pkdash This is going to be tricky to test since the CUAHSI JupyterHub is connected to HydroShare.org both through OAuth and using the hsapi. I haven't determined how to test this yet, aside from deploying a new JupyterHub with Oauth and `nbfetch` hardcoded to https://cuahsi-dev-2.hydroshare.org/. This will take some time.

```
hs = HydroShare(auth=auth)
```

Any thoughts are welcomed.

**Comment by pkdash** [comment]
@Castronova Though it's not going to be an ideal test case, I think the following testing procedure should be enough:
 1. Use hydroshare.org to launch CUAHSI JupyterHub app for a given resource. Note the launching url that opens up in another tab.
 2. Do the same on cuahsi-dev-2.hydroshare.org for the same resource. Compare the app launch url with that you got in step 1. They should be same.

**Comment by pkdash** [comment]
@Castronova I need help in testing the CUAHSI BinderHub web app. When I tried to test this app, I am getting this error:
![image](https://user-images.githubusercontent.com/2523434/183090984-63dc65cb-017b-4526-8726-c6ac4b19d9e5.png)

Here are the steps to test this web app:
1. Use an existing resource in www that contains a notebook file.  Make sure the same resource and notebook file exist at cuahsi-dev-2.hydroshare.org
2. On www launch this web app from the notebook file and verify the web app works.
3. Then launch the web app from the same file and resource on dev-2. Verify the web app works. When  you launch the web app from dev-2, your app will take the app url generated by dev-2, and use that to work with the same resource on www. 
4. Repeat the above 3 steps by using a notebook file that has spaces in filename. If you don't have a notebook file that has spaces in filename already in a resource, you need to upload such a file to the same resource on www and dev-2. Verify that the web app works when the notebook filename has spaces.
