### ISSUE TITLE
(BUG) Author order changed after clicking the view botton

### ISSUE THREAD

**Issue by JianWangUSU** [hydroshare/hydroshare#4695]
See screenshots below. It works fine when I only have 5 authors, but this time I have 12 authors. I use "drag and drop" to rearrange the author order in the editing mode, but after clicking the view button, the order changed. Tested in Chrome and MS Edge multiple times.

![1](https://user-images.githubusercontent.com/49882529/178112886-f8011d59-3d88-4f6e-ad26-c17ea12ba92c.png)
![2](https://user-images.githubusercontent.com/49882529/178112887-6b2148f3-5f0c-4e31-9af9-a33dab1a5790.png)

**Comment by JianWangUSU** [comment]
Update: Now the author's order at the beginning and in the "How to Cite" section are different.

Link:   https://www.hydroshare.org/resource/59175cf99a58462f901cdf56ec79ddbe/


![Capture](https://user-images.githubusercontent.com/49882529/178155660-82b19641-a0b2-4c06-8a85-e4387c7c023c.PNG)

**Comment by devincowan** [comment]
When I open [the resource](https://www.hydroshare.org/resource/59175cf99a58462f901cdf56ec79ddbe/) right now, the order of the two sections matches:
<img width="727" alt="image" src="https://user-images.githubusercontent.com/17934193/178271375-1ad80a16-2478-433e-8708-c38baa52e8ff.png">

<img width="713" alt="image" src="https://user-images.githubusercontent.com/17934193/178271435-12c194bd-a390-4e22-a03b-83601727386b.png">

[v1.56.1](https://github.com/hydroshare/hydroshare/tree/1.56.1), firefox and chrome

**Comment by dtarb** [comment]
The particular resource mentioned here is fixed, because I fixed it manually (at @JianWangUSU s request) by deleting authors then adding them in the order needed, and because they need to publish this resource in a hurry.  But the systemic problem that leads to the occurrence of this remains.

**Comment by devincowan** [comment]
Thanks @dtarb that's what I suspected, good to have confirmation. I'm looking into this...
Related to #4679 which is slated for fix in [1.57](https://github.com/hydroshare/hydroshare/tree/rc-1.57)

**Comment by dtarb** [comment]
Owner order is not a concept that we have to date attributed meaning to.  What is the reason for there needing to be an order in owners.

**Comment by JianWangUSU** [comment]
> Owner order is not a concept that we have to date attributed meaning to. What is the reason for there needing to be an order in owners.

I got it. Thanks.

**Comment by JianWangUSU** [comment]
We have published all related resources. Thanks for your help again.
