### ISSUE TITLE
Working image types, outside of the allowlisted file extensions, throws a generic error

### ISSUE THREAD

**Issue by hydrocheck** [hydroshare/hydroshare#4701]
**Description of the bug**
When using an image that appears to work, but falls outside the allowlisted file extensions (e.g., .webp), the error handling is unusual.  The error thrown is "Error! Metadata failed to update "Could not parse the error message"", rather than the usual "Error! Failed to update metadata element 'toolicon'. ['Supported icon image types are png, gif, jpeg, ico, and svg']." thrown (e.g., by icon URL "google.com/index.html").  

Steps to reproduce the bug:
1. Create a resource of type Web App Connector
2. Set "Icon URL or File" to "https://upload.wikimedia.org/wikipedia/commons/a/a1/Johnrogershousemay2020.webp"
3. Save and observe the generic error

**Expected behavior**
A more actionable and descriptive error is thrown, like the "Error! Failed to update metadata element 'toolicon'. ['Supported icon image types are png, gif, jpeg, ico, and svg']." thrown in other cases.

https://user-images.githubusercontent.com/43424907/178643646-f4740b26-6bba-4788-a623-2549b8658084.mov

**Comment by devincowan** [comment]
reopening this issue.
rc2.1 (89dc601dead967653ac54ddc9160e1140e800f1e) local dev env gives the correct error message:
![image](https://user-images.githubusercontent.com/17934193/204823245-2b6d814a-ebf0-4316-b02e-70fc54d36898.png)

But rc2.1 deployed to beta however gives:
![image](https://user-images.githubusercontent.com/17934193/204823515-2e08e770-3f5a-47b0-91e2-c31a79fb9974.png)

**Comment by devincowan** [comment]
re-opening, needs another look
