### ISSUE TITLE
[Help pages] Update title of grid card

### ISSUE THREAD

**Issue by Maurier** [hydroshare/hydroshare#4704]
We have a grid card that reads "Creating and Managing Resources", but the heading on the page itself reads “Uploading and Publishing Data and Models”.

@ClaraCogswell has requested that the card title be updated to "Uploading and Publishing Data".

**Comment by horsburgh** [comment]
The only concern with this is that HydroShare users can upload and publish more than just data. I know the word "resource" may not resonate with everyone, bit it is more inclusive.

I suggest "Uploading and Publishing Resources"

**Comment by dtarb** [comment]
I am happy with the compromise.  You could also consider "Uploading and Publishing" without saying what.
