### ISSUE TITLE
Update Schema.org implementation for funding element

### ISSUE THREAD

**Issue by horsburgh** [hydroshare/hydroshare#4709]
**Describe the feature you'd like and what it will do**

With Release 14.0, Schema.org adopted a more expressive way we can use to implement funding agency information in JSON-LD.

**Why is this feature important?**
A short description of the importance of this feature and what it will help you achieve.

Our existing implementation needs to be updated to be consistent with the latest Schema.org release. This will ensure funding agency information is more accurately exposed as metadata in HydroShare's Schema.org implementation.

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...].

N/A

**Additional context**

The implementation should look like this:

```json
{
  "@context": "https://schema.org",
  "@type": "Dataset",
  "@id": "https://doi.org/datadoihere",
  "funding": {
    "@type": "Grant",
    "identifier": "1931297",
    "funder": {
      "@type": "Organization",
      "name": "National Science Foundation",
      "identifier": "https://www.nsf.gov/awardsearch/showAward?AWD_ID=1931297"
     }
   }
}
```
For details see https://schema.org/funding and https://schema.org/Grant. The funding property should be implemented as an array of grants as there can be multiple. The only drawback here is that the only type currently available for funding values is "Grant", but I don't see that as a huge problem.

**Comment by horsburgh** [comment]
Thanks @hyi - I had meant to post this issue a while ago, but I was just reminded about it because Schema.org was mentioned at a meeting I'm sitting in. At some point, we may want to do a more comprehensive review of our implementation, but this element is one that I was watching pretty closely because it was a bit awkward in our early implementations.

**Comment by ClaraCogswell** [comment]
Does this go on the HS project board?

**Comment by hyi** [comment]
I added this issue to the HS project board in select next for development category.

**Comment by hyi** [comment]
@horsburgh Here are the changes I made:
- Changed @context from the following:
  ```
  "@context": {
        "@vocab": "https://schema.org/"
    },
  ```
  to:
  ```
  "@context": "https://schema.org",
  ```
- Funding elements are updated with one test example as shown below:
```
  "funding": [
    
        {
            "@type": "Grant",
            "identifier": "235689",
            "funder": {
                "@type": "Organization",
                "name": "National Science Foundation",
                "identifier": "https://www.nsf.gov/awardsearch/showAward?AWD_ID=235689"
            }
        },
        
        {
            "@type": "Grant",
            "identifier": "1931297",
            "funder": {
                "@type": "Organization",
                "name": "National Science Foundation",
                "identifier": "https://www.nsf.gov/awardsearch/showAward?AWD_ID=1931297"
            }
        }
        
    ],
```
Want to check with you to see if they look good. Also, do you want to double check before I create a PR to have the changes merged to beta so you can test on beta if needed? Note that I will have to manually remove a debug flag check in order for you to test since schema.org json-ld embedding is only made available for production only. Also doing so will make those resources on beta indexed in google search. Since only two changes as shown above are involved, so if you think the changes look good, perhaps we don't need to test before deployment to production, but let me know if you want to take a look before deployment and I can certainly set up beta for you to take a look after this is deployed for testing.

**Comment by horsburgh** [comment]
@hyi - I made an omission here, but otherwise your implementation looks good to me. 

Grants can have a "name" property that is the title or name of the grant - in HydroShare's metadata this is the "Award Title". I omitted that in my original example, we need to include it as follows:

```JSON
{
  "@context": "https://schema.org",
  "@type": "Dataset",
  "@id": "https://doi.org/datadoihere",
  "funding": {
    "@type": "Grant",
    "identifier": "1931297",
    "name": "Collaborative Research: Elements: Advancing Data Science and Analytics for Water (DSAW)",
    "funder": {
      "@type": "Organization",
      "name": "National Science Foundation",
      "identifier": "https://www.nsf.gov/awardsearch/showAward?AWD_ID=1931297"
     }
   }
}
```

I definitely don't want resources on beta to get indexed by Google, so is there at least a way we can extract the full JSON-LD to run it through Google's structure data testing tool just to verify everything?

**Comment by hyi** [comment]
@horsburgh Thanks for the feedback. Have just pushed a commit to the PR to add award title to the name field of funding element in schema.org implementation. I also took the generated schema.org script for my test resource landing page and used google's structure data testing tool to validate it. It seems to validate without issues. See the screenshot below. Let me know if there is anything else we need to do for testing before deployment of this schema.org implementation update.
![schema_org_validator](https://user-images.githubusercontent.com/476302/183493439-995aa2d7-128d-46d7-8ee1-9c58df076b47.png)

**Comment by horsburgh** [comment]
@hyi - that's it for now. It's a pretty straightforward change. I think we should move forward.
