### ISSUE TITLE
Website on model resource should be a link

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#471]
On a model resource (e.g. see http://www.hydroshare.org/resource/2cddae40e9594c21b947fdbbe4225439/) under resource specific the website URL should be a link

**Comment by horsburgh** [comment]
I checked this one and it has been fixed on dev.hydroshare.org.  However, while testing I noticed that the "Software Repository" text box instructions state that I should input a URL for the source code repository.  I did so, but it wasn't converted to a link after saving my edits. @mauriel133 - Can you fix that too really quickly and then we can close this issue?

**Comment by mauriel133** [comment]
This fix has been merged into develop now.

**Comment by dtarb** [comment]
Checked on Alpha.
