### ISSUE TITLE
Add unzip to folder functionality in conjunction with unzip to current folder functionality

### ISSUE THREAD

**Issue by hyi** [hydroshare/hydroshare#4714]
With [This PR](https://github.com/hydroshare/hydroshare/pull/4549) to address issue #4152, unzip in HydroShare will always unzip to the current folder where zip file is located without creating an extra folder for unzipped files/folders. This issue is to add an unzip to folder functionality in parallel to unzip to current folder functionality to server different unzipping user needs.

**Comment by ClaraCogswell** [comment]
@martinseul will ask about this on Monday
