### ISSUE TITLE
Filtering refinements

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#472]
Enhance the filtering to support partial text in fields searched and make filtering more intuitive.

As presently implemented entering a word or part of it in the title or abstract identifies a resource properly, but entering a word in a creator or contributor that is not the beginning does not.  Specifically if I type tarboton in the search box. I get nothing found. I type d in the search box and get an option to pick author David Tarboton which returns the 3 resources for which I am first author. I type a in the search box and I get a list to choose from that includes author Alan Snow but not Author Tarboton, or David Tarboton. It seems that there is no way to search only on the last name only of an author or contributor.

**Comment by ironfroggy** [comment]
@dtarb Is this ticket still valid for the new My Resources page?

**Comment by dtarb** [comment]
This appears to be resolved in the new deploy, so closing.
