### ISSUE TITLE
Version message at top of resource incorrect at top of landing page

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#4728]
When there is a newer version of a resource the message at the top is supposed to state "A newer version of this resource is available that replaces this version" as below.
![image](https://user-images.githubusercontent.com/3456833/183246365-153484d1-6bdb-427e-9a30-b732436660ca.png)

However for this resource https://www.hydroshare.org/resource/e0cbe52ad4524c07bb5b7ff8c373a343/ the message is incorrect
![image](https://user-images.githubusercontent.com/3456833/183246402-145b339d-4442-41b5-819d-ae1541a0e382.png)

Versioning was worked on in #4633  and #4637.  Look first at those changes to see if they introduced this bug.

**Comment by devincowan** [comment]
Resources that I've found impacted:
https://www.hydroshare.org/resource/0f02af18e5344ae7a65dfa7fe1444f34/
https://www.hydroshare.org/resource/e0cbe52ad4524c07bb5b7ff8c373a343/
https://www.hydroshare.org/resource/bfdfd782ffc74c42b0347690ae543961/

From my initial investigation, it seems like this occurs when someone creates a new version of a resource and publishes that new version _before_ the celery [create_new_version_resource_task](https://github.com/hydroshare/hydroshare/blob/develop/hs_core/tasks.py#L475) is actually fully completed.

working on a fix...

**Comment by devincowan** [comment]
scratch that. what causes this is [update_relation_meta](https://github.com/hydroshare/hydroshare/blob/develop/hs_core/models.py#L3749) which was added in https://github.com/hydroshare/hydroshare/pull/4442. This method updates all of the relation metadata on page load. Which is fine. Except that it has the same bug that caused https://github.com/hydroshare/hydroshare/issues/4633. So my fix will be the same as in PR https://github.com/hydroshare/hydroshare/pull/4637
