### ISSUE TITLE
Policy and strategy for supporting evolving browsers

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#473]
1. [ ] Firefox
2. [ ] Internet Explorer
3. [ ] Chrome
4. [ ] Safari

**Comment by ironfroggy** [comment]
A browser support table has to be more specific than some browser names. Firefox releases a new version every six weeks, Chrome is on a similar schedule releasing 7 new versions in 2015 alone. Internet Explorer had a traditionally longer cycle, but has released 10 and 11 to fanfare, while some organizations are still stuck (very sadly) with the extremely crippled (and security vulnerable) 8 and 9. Meanwhile, they're releasing a completely new browser to replace Internet Explorer entirely in a few months. Safari, Chrome, and Firefox all have both desktop and mobile versions, with slightly different versions that track in parallel.

Current versions of major browsers:
- Chrome 43
- Firefox 38
- Safari 8
- Internet Explorer 11

A increasingly popular rule of thumb is to support the most recent two versions of each supported vendor, but in any policy you adopt you have to be clear about the versions you support and how you track the changing landscape of new browsers being released.

**Comment by dtarb** [comment]
I am happy to go with the rule of thumb of the most recent two versions of each of the above 4 vendors.  I'd prefer to the maximal extent possible not to have a lot of browser specific conditionals.  If we can keep the code simple so that the same code works across all browsers that is preferable.

**Comment by ironfroggy** [comment]
@mauriel133 has this testing been done on the current My Resources page?

**Comment by mauriel133** [comment]
I have conducted filtering tests in the latest versions for Chrome, Firefox and Safari. The issues we found were fixed before the deployment of the new My Resources page.

I will test next for Internet Explorer.

**Comment by dtarb** [comment]
Title repurposed to reflect that we still need to address support for browsers, but that this is a back burner issue at present.

**Comment by cuahsimarko** [comment]
I am more accustomed to seeing this type of ticket in Jira/Trello and not GH Issues. The challenge with HydroShare is that it is cross-organizational (and technically open source, though we don't have any/many contributors in that regard as far as I know) and coordinating that Trello would be more meta/overhead work than value provided. I like our current way of working, sometimes chaotic but efficient and workable. Still vote to move this ticket out to a google doc or something.

**Comment by cuahsimarko** [comment]
Design, Customer Support, Customer Documentation, QA Testing Frameworks and Infrastructure ....

**Comment by dtarb** [comment]
Closing.  This has drifted from the original problem which was that 4 years ago something did not work on some type of browser.  I am closing.  We can manage the browser support and other items mentioned elsewhere.
