### ISSUE TITLE
is_active call generates 1 db query for every creator

### ISSUE THREAD

**Issue by devincowan** [hydroshare/hydroshare#4732]
**Describe the feature you'd like and what it will do**
Load time on My Resources page is bottlenecked by queries at the template level. One query that we can address is `is_active`
https://github.com/hydroshare/hydroshare/blob/develop/hs_core/templates/pages/my-resources.html#L264
this hits the db for every additional creator (who is also a hydroshare user) on a resource. 

@pkdash suggested "we make 'is_active' a model field in Creator class and set it via signal when User object gets updated" as a potential refactoring

**Is your feature request related to a problem? Please describe.**
My Resources page load is SLOW

**Additional context**
Related to #2368

**Comment by pkdash** [comment]
@devincowan FYI: I have started working on this.
