### ISSUE TITLE
Resource is broken (with error page) after zipping, bagging, and unzipping operations

### ISSUE THREAD

**Issue by hydrocheck** [hydroshare/hydroshare#4753]
**Description of the bug**
After testing of zipping, bagging, and unzipping operations, a resource became unusual.  These operations weren't automated or otherwise executed in a non-human way.

Steps to reproduce the bug:
1.  Upload a zip
3. Create a zip in the content browser
4. Unzip both files
5. Create a BagIt
6. Unzip the BagIt
7. Unzip the BagIt again, with overwrites

<img width="1440" alt="Bildschirmfoto 2022-08-29 um 11 57 27 PM" src="https://user-images.githubusercontent.com/43424907/187346185-76ff23e0-939e-4264-a1e1-5e1ce48e99b2.png">
https://beta.hydroshare.org/resource/e007cf2132364c5990ba3246001a403d/

**Expected behavior**
Resource remains in-tact.

**Additional information**
Chrome 104.0.5112.101

**Comment by hyi** [comment]
@ndebuhr Can you explain what Step 2 "Create a zip in the content browser" means? How can I create a zip in the content browser? Do you mean using "Download zipped" from the content browser to download a zip file, then adding the downloaded zip file to the same resource?

**Comment by devincowan** [comment]
@hyi update for you on this issue: @pkdash created a fix and I have approved it (PR #4756)
