### ISSUE TITLE
Add content length header to django_irods download view response

### ISSUE THREAD

**Issue by selimnairb** [hydroshare/hydroshare#476]
django_irods.views.download() should set the Content-Length header.  This probably entails getting file stat from an iRODS icommand.  This will allow user agents to provide feedback on file download progress.

Assigning to @hyi for now.

**Comment by hyi** [comment]
@selimnairb could you test it out on dev and close if working there?

**Comment by hyi** [comment]
tested on dev and it works as expected. Closing.
