### ISSUE TITLE
Set specific MIME type for django_irods download view responses

### ISSUE THREAD

**Issue by selimnairb** [hydroshare/hydroshare#477]
django_irods.views.download() should set a specific mime type for its responses, defaulting to 'application/octet-stream' if no mime type was found.  The built-in Python library *mimetypes* can be used to do this, for example:

    mime_type = mimetypes.guess_type(filename)
    if mime_type[0] is None:
        mime_type = 'application/octet-stream'
    else:
        mime_type = mime_type[0]

**Comment by hyi** [comment]
Test it on dev and it works, so closing.
