### ISSUE TITLE
Group invitations not working

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#4770]
**Description of the bug**
I tried to invite dcowan (and then I tested this with demo) to the HydroShare developers group.  After issuing invitations I saw the message "invitation issued" but invitations never appeared on the invitation pending list.

Steps to reproduce the bug:
1. Go to a group where you are the owner and can invite people.
2. In the members tab click on Invite people
3. Type the username of the person you want to invite and click send invitation
4. See the message "An invitation has been sent"
![image](https://user-images.githubusercontent.com/3456833/189507367-05076bf1-591a-466d-bfaa-3fda6fc37bad.png)
5. Refresh the group page.  No pending invitations appear
![image](https://user-images.githubusercontent.com/3456833/189507396-ad46d712-4140-4c19-b14d-a2a83776457b.png)

**Expected behavior**
- The invited group member should appear on the list of pending invitations.
- The invited group member should receive an email with a link to accept the invitation

**Comment by devincowan** [comment]
![image](https://user-images.githubusercontent.com/17934193/189933060-d1c4fcd9-e5c3-4fcf-a3ce-ae30ef17cebc.png)
Seemed to work when I _requested_ membership to "Developers"

Also, the workflow was successful when I created a new group and invited someone (they were emailed and added to the pending list).

I reproduced this issue when the "Require explanation when requesting membership" box is enabled/checked for the group. So this was introduced sometime after 1.55. I will fix it.
