### ISSUE TITLE
Geoserver is not working

### ISSUE THREAD

**Issue by jorgessanchez7** [hydroshare/hydroshare#4772]
The hydroshare geoserver is not working (see: https://geoserver.hydroshare.org/). Therefore the wms and wfs services for the different resources are not available.

See:
https://geoserver.hydroshare.org/geoserver/HS-77951ba9bcf04ac5bc68ae3be2acfd90/wms?request=GetCapabilities
https://geoserver.hydroshare.org/geoserver/HS-77951ba9bcf04ac5bc68ae3be2acfd90/wfs?request=GetCapabilities
https://geoserver.hydroshare.org/geoserver/HS-dd069299816c4f1b82cd1fb2d59ec0ab/wms?request=GetCapabilities
https://geoserver.hydroshare.org/geoserver/HS-dd069299816c4f1b82cd1fb2d59ec0ab/wfs?request=GetCapabilities
https://geoserver.hydroshare.org/geoserver/HS-9b6a7f2197ec403895bacebdca4d0074/wms?request=GetCapabilities
https://geoserver.hydroshare.org/geoserver/HS-9b6a7f2197ec403895bacebdca4d0074/wfs?request=GetCapabilities
https://geoserver.hydroshare.org/geoserver/HS-11765271903a45d483416ce57bf8c710/wms?request=GetCapabilities
https://geoserver.hydroshare.org/geoserver/HS-11765271903a45d483416ce57bf8c710/wfs?request=GetCapabilities

**Comment by martinseul** [comment]
Hi Jorge, we have an issue with our internal service (geoserver) we use for serving up the WMS, WFS services as one of our servers was compromised. We're working on fixing the issue (rebuilding te servers) and think will have it fixed later this week. I did add a notification to the website as well to keep people informed. Sorry for the inconvenience.

**Comment by martinseul** [comment]
Hi Jorge,

sorry it took us longer than expected to get the service back online, we were able to setup the server on friday and register all resources, and finish testing today all seems to be workng OK, please let us know if you still encounter issues.

**Comment by martinseul** [comment]
completed
