### ISSUE TITLE
hsapi/userDetails/ endpoint does not accept usernames and emails in OpenAPI interface

### ISSUE THREAD

**Issue by sblack-usu** [hydroshare/hydroshare#4793]
**Description of the bug**

Steps to reproduce the bug:
1. Go to hydroshare.org/hsapi
2. Click on /userDetails/{user_identiier}/
3. See that user_identifier requires an integer

**Expected behavior**
The userDetails endpoint should accept usernames and emails in addition to the identifiers.  The endpoint actually accepts usernames and emails if you hit the endpoint outside of the OpenAPI interface (hsclient uses it).

**Additional information**
[Relevant lines](https://github.com/hydroshare/hydroshare/blob/develop/hs_rest_api/urls.py#L206-L207)
<img width="1422" alt="image" src="https://user-images.githubusercontent.com/35820390/195150588-8491baf1-3fb7-448d-9b72-172eddffcb20.png">

**Comment by devincowan** [comment]
@sblack-usu are you sure that hsclient uses this endpoint with username/email?

I'm looking at
https://github.com/hydroshare/hsclient/blob/master/hsclient/hydroshare.py#L1038
which just uses the userid

At any rate, I'm updating the HS openapi for this endpoint. I was just curious if I'm missing something on the hsclient side...thanks
