### ISSUE TITLE
Option to delete your account

### ISSUE THREAD

**Issue by ironfroggy** [hydroshare/hydroshare#48]

**Comment by mauriel133** [comment]
We decided to leave the resources in HydroShare, but notify the user so when the account is being deactivated.  

@horsburgh, should we implement this checkbox that the user must check before deactivating the account?

**Comment by horsburgh** [comment]
Given that we are not actually deleting the account, but rather just disabling it, I'm assuming that the disabled user account will remain the owner of any resources they leave behind. I don't think we actually need the check box. The confirmation message we already have tells the user that if they disable their account without first deleting their resources, the resources will still be available. So, we may still want to examine this process in the future, but I think it's OK for now.

**Comment by mauriel133** [comment]
Can be tested at https://park.hydroshare.org

**Comment by mauriel133** [comment]
Implemented with revamp of profile page. Please confirm and close.

**Comment by horsburgh** [comment]
I just tested this on www. You can now deactivate your account, but per our current policy I don't think the account is actually deleted. Closing for now.
