### ISSUE TITLE
Geoconnex schema:name missing from some collection contexts

### ISSUE THREAD

**Issue by devincowan** [hydroshare/hydroshare#4801]
The issue is that the Geoconnex API returns a schema context that doesn't always match the actual features.
HS should gracefully handle when there is a mismatch between the schema and the features.

**Comment by devincowan** [comment]
add padding when fit map to features so they aren't on the map border
<img width="920" alt="image" src="https://user-images.githubusercontent.com/17934193/200329573-70c9932e-cb9b-440f-8f4e-21510c24edfd.png">

**Comment by ksonda** [comment]
@devincowan I figured I'd put in here that we've updated this service so that it can now be queried by polygon according to this standard via GET or POST (see [example 9](https://portal.ogc.org/files/96288#simple-cql-JSON)), and in general should be much faster, including the /pws endpoint

**Comment by devincowan** [comment]
@ksonda that is SUPERB! I will give it a try, thanks

**Comment by ksonda** [comment]
ALso note the json response to any query from this service also now includes fields ```"numberMatched": 187474,

"numberReturned": 200,```

to help with iteration via `offset` and `limit` query parameters after a first query

**Comment by ksonda** [comment]
@devincowan I'm noticing that there seem to be issues in the hydroshare geoconnex system for many of collections. The only ones that seem to work are HUCs, dams and aquifers.

**Comment by devincowan** [comment]
@ksonda thanks I see this now too
Requests for jsonld to Geoconnex api used to return a context with a "schema:name" for these features, but looks like that's no longer the case. For example:
https://reference.geoconnex.us/collections/mainstems/items?f=jsonld&lang=en-US&limit=1&skipGeometry=true&offset=0

For the mainstems collection, we used to get a context with 
```
{
      "schema": "https://schema.org/",
      "name_at_outlet": "schema:name"
}
```
Loosely related to https://github.com/internetofwater/geoconnex.us/issues/178

**Comment by ksonda** [comment]
There may be a quick fix but there me be an issue upstream and geopython/pygeoapi. Let me check

Are there any other properties you defintiely need than schema:name?

**Comment by devincowan** [comment]
we really only rely on `uri` and `name` at this point

**Comment by ksonda** [comment]
so this would explain why gages wouldnt work, but, for example, counties doesn't work either. 

https://reference.geoconnex.us/collections/counties/items?f=jsonld&lang=en-US&limit=1&skipGeometry=true&offset=0

which gets you 

```json
{
    "@context": [
        {
            "schema": "https://schema.org/",
            "type": "@type",
            "features": "schema:itemListElement",
            "FeatureCollection": "schema:itemList"
        },
        {
            "schema": "https://schema.org/",
            "name": "schema:name",
            "census_profile": {
                "@id": "schema:subjectOf",
                "@type": "@id"
            }
        }
    ],
    "type": "FeatureCollection",
    "features": [
        {
            "@id": "https://geoconnex.us/ref/counties/01001",
            "type": "schema:Place"
        }
    ],
    "numberMatched": 3233,
    "numberReturned": 1,
```

vs. huc 2 which works

```json
{
    "@context": [
        {
            "schema": "https://schema.org/",
            "type": "@type",
            "features": "schema:itemListElement",
            "FeatureCollection": "schema:itemList"
        },
        {
            "schema": "https://schema.org/",
            "name": "schema:name",
            "gnis_url": {
                "@id": "schema:subjectOf",
                "@type": "@id"
            }
        }
    ],
    "type": "FeatureCollection",
    "features": [
        {
            "@id": "https://geoconnex.us/ref/hu02/01",
            "type": "schema:Place"
        }
    ],
    "numberMatched": 22,
    "numberReturned": 1,
```

**Comment by devincowan** [comment]
thanks @ksonda appreciate you checking on these -- I have it on my list to add browser tests so that we catch these sooner ;)

Sounds like the Counties issue could be on our end. Appears to work for me, when the HS resource has a defined Spatial Coverage:
<img width="1446" alt="image" src="https://user-images.githubusercontent.com/17934193/223858072-bffd35c9-5d90-446a-855b-4ed90ab85fde.png">

With no Spatial Coverage, the query returns too many features (we limit it to 1000):
<img width="493" alt="image" src="https://user-images.githubusercontent.com/17934193/223857836-4f646f53-bc84-4f8b-9add-c8c374035b3a.png">

**Comment by ksonda** [comment]
I understand the too many thing.

![image](https://user-images.githubusercontent.com/44071350/223859483-2e5147be-fa1e-4fa5-b055-574965e15fc4.png)
 I didn't consider it could be a browser thing though (this is vivaldi...which...lol yeah you probably dont need to go out of your way for)

**Comment by devincowan** [comment]
I thought maybe it could be something particular about counties in that Denver area that I didn't account for in how we do the mapping etc. But seems to work for me on Chrome/Firefox

<img width="1406" alt="image" src="https://user-images.githubusercontent.com/17934193/223860480-f2175e86-ebec-484d-b487-2c166cdce5c1.png">

@ksonda if you get a chance, maybe shoot me a snapshot of your console after this error occurs?

**Comment by devincowan** [comment]
I'm going to use this issue #4801 as the current "bug" in production
Moved "Geoconnex phase 2" -> https://github.com/hydroshare/hydroshare/issues/5003

**Comment by ksonda** [comment]
mk so in vivaldi it looks like a CORS setting issue ![image](https://user-images.githubusercontent.com/44071350/224078202-e708077b-92dd-4e99-bfc8-8350491c75c3.png)

Although it "works" for HUC6 in this example, there's no request, so it's like it was cached since I did it already maybe?
![image](https://user-images.githubusercontent.com/44071350/224082654-32ab6544-4370-45ec-980c-dd1f1def5e99.png)
 

However, there's also maybe some kind of upstream problem with how you decide what to use for name.  Note the context for the [mainstems/items?f=jsonld](https://reference.geoconnex.us/collections/mainstems/items?f=jsonld) now looks like 
```json{
    "@context": [
        {
            "schema": "https://schema.org/",
            "type": "@type",
            "features": "schema:itemListElement",
            "FeatureCollection": "schema:itemList"
        },
        {
            "schema": "https://schema.org/",
            "name_at_outlet": "schema:name"
        }
    ],
    "type": "FeatureCollection",
    "features": [
        {
            "@id": "https://geoconnex.us/ref/mainstems/1",
            "type": "schema:Place"
        },
```

I see in the console that the request being passed is https://reference.geoconnex.us/collections/mainstems/items?f=json&limit=1000&properties=uri,NAME&bbox=-104.5047,39.428,-105.4825,39.9774 

So it looks like you've just hardcoded somewhere what the field for name is and it's become outdated.

**Comment by devincowan** [comment]
thanks @ksonda you're right that we cache a lot of the features in browser store (I'm going to test, given the api's improved performance, we might not need to anymore) -- the problem you're seeing with the seemingly hardcoded urls is actually because the jsonld is also cached browser side (so it is still sending requests based on your old schemas with the caps "NAME"). I have a fix to remove the jsonld caching ready for deploy it should hit prod in a couple hours

**Comment by ksonda** [comment]
also remember /collections/pws works now

**Comment by devincowan** [comment]
100% thanks @ksonda

**Comment by devincowan** [comment]
@ksonda I think there is an issue with the pws
https://reference.geoconnex.us/collections/pws/items?f=jsonld&limit=1
```
{
    "@context": [
        {
            "schema": "https://schema.org/",
            "type": "@type",
            "features": "schema:itemListElement",
            "FeatureCollection": "schema:itemList"
        },
        {
            "name": "https://schema.org/name"
        },
        {
            "state_uri": "https://schema.org/geoWithin"
        },
...
```
Note `"name": "https://schema.org/name"`

https://reference.geoconnex.us/collections/pws/items?f=json&limit=1
```
{
    "type": "FeatureCollection",
    "features": [
        {
            "type": "Feature",
            "properties": {
                "city_served": null,
                "is_wholesaler_ind": true,
                "pred_05": 565.429228066911,
                "contribution_date": "2022-11-01",
                "fid": 1088,
                "primacy_type": "Tribal",
                "pred_50": 657.523011362528,
                "service_area_type": "['Residential Area']",
                "pws_name": "MASHANTUCKET PEQUOT WATER SYSTEM",
                "primary_source_code": "GU",
                "pred_95": 764.616487812842,
                "primary_water_source": "Groundwater under influence of surface water",
                "state_code": "01",
                "tier": "3",
                "source_url": "https://www.hydroshare.org/resource/9ebc0a0b43b843b9835830ffffdd971e/data/contents/temm.gpkg",
                "sdwis_link": "https://enviro.epa.gov/enviro/sdw_report_v3.first_table?pws_id=010106001&state=01&source=0&population=0",
                "county_served": null,
                "centroid_lat": 41.444031,
                "data_source": "Modeled",
                "place_uri": "https://geoconnex.us/ref/places/",
                "population_served_count": 37807.0,
                "centroid_lon": -71.995973,
                "contact_email": "jess@gosimplelab.com",
                "wholesaler": "Is a wholesaler",
                "service_connections_count": 119.0,
                "centroid_quality": "ECHO: ZIP CODE CENTROID",
                "source_date": "2022-11-01",
                "uri": "https://geoconnex.us/ref/pws/010106001",
                "primacy_agency_code": "01",
                "owner_type_code": "N",
                "geometry_source_detail": "Modeled",
                "state_uri": null,
                "boundary_type": "Unknown Service Area - Using EPA ECHO facility location with buffered radius to represent PWS"
            },
...
```
There is a `"pws_name": "MASHANTUCKET PEQUOT WATER SYSTEM",` but there **IS NO "name" field**

**Comment by ksonda** [comment]
I'm pushing a fix to the context now. should be up in 5-10 mins

**Comment by ksonda** [comment]
it's done

**Comment by devincowan** [comment]
thanks @ksonda! ZIPPY FAST!
So this is probably my lack of knowledge. Looks like there are two different name mappings for the PWS features, in 2 separate contexts:
![image](https://user-images.githubusercontent.com/17934193/224192704-734deefa-0e4b-4f96-86ae-a7378a6931c0.png)
https://reference.geoconnex.us/collections/pws/items?f=jsonld&limit=1

But of course when we query there is only the `pws_name`
https://reference.geoconnex.us/collections/pws/items?f=json&limit=1

How do we know which context will hold the correct name field for the features?

**Comment by ksonda** [comment]
Hmm we’ll I’m this case it’s extraneous and I should remove that from the context. But there are legitimate cases where multiple fields might have the same context mapping, such as if a thing has multiple names.

One approach here would be to look at /collections/pws/queryables and pick the first one that is there that shows up in the context as schema:name.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by devincowan** [comment]
PR https://github.com/hydroshare/hydroshare/pull/5005 releasing today as hotfix 2.4.1
@ksonda sorry this one got delayed for a variety of reasons...
