### ISSUE TITLE
Incorrect Last Modified dates in My Resources listing 

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#4815]
**Description of the bug**
On my My Resources page, I see a listing that has the last Modified date for many of the resources listed as very recent (Yesterday or today).  I know that I did not touch these recently, and if I enter in to the landing page of one of the resources I see the last updated date, the correct date

My Resources listing
![image](https://user-images.githubusercontent.com/3456833/198836284-ab5f850a-0769-4937-a372-e79ec3c6039f.png)

Landing page
![image](https://user-images.githubusercontent.com/3456833/198836330-68e82c71-365f-42d1-89b9-ab0ec094b702.png)

Steps to reproduce the bug:
1. Go to My resources page.  Check last updated date
2. Click on one of the resources listed
3. See that the Last updated date is not the same as was in the my resources page

**Expected behavior**
The Last Modified date in the My Resources listing should be the same as the Last updated date on the landing page.  We should also settle on a consistent terminology, either Last Updated or Last Modified.  I suggest Last Modified as a modification may not always be an update.

**Comment by pkdash** [comment]
This has been fixed as part of release 2.1
