### ISSUE TITLE
Geoconnex related geospatial features and traditional Coverage create visibility issues

### ISSUE THREAD

**Issue by hydrocheck** [hydroshare/hydroshare#4820]
When only Geoconnex features are defined (no traditional coverage), the Related Geospatial Features map shows those Geoconnex features nicely (with respect to map bounds/zoom).  However, when both Geoconnex features and traditional coverage are defined, the Related Geospatial Features map changes to only show the traditional Coverage box/point.  Clicking "Recenter" brings both into view, but this (or just the Geoconnex) should seemingly be the default.

https://user-images.githubusercontent.com/43424907/200202589-9698847a-08de-41e5-a7d4-818b605b5fe6.mov

**Comment by devincowan** [comment]
Wasn't able to reproduce in Firefox
But I do see it in Chrome now:
https://www.hydroshare.org/resource/ba4b37dc06844eff9ead22cf801044bf/
