### ISSUE TITLE
Message 'Metadata complete' should be displayed only once

### ISSUE THREAD

**Issue by pkdash** [hydroshare/hydroshare#484]
This message gets displayed every time you update a metadata element when the resource has all required metadata. The message should only be displayed once when resource has all the required metadata the first time.

**Comment by horsburgh** [comment]
@mauriel133 and @pkdash - has this been resolved?

**Comment by pkdash** [comment]
No

**Comment by horsburgh** [comment]
I just tried to test this on beta.hydroshare.org. I deleted the Abstract element for an existing resource and then tried to click "Save Changes" and got the following error:

![image](https://cloud.githubusercontent.com/assets/3485902/20996470/1c43ec3a-bcbb-11e6-9977-7b46d9de05ed.png)

Shouldn't I be able to delete the Abstract and then save the resource?

Then, I tried by creating a new resource. I created a title, an abstract and then added a keyword. I get the message that the metadata are sufficient to be made public or publish. Then I add another keyword and the message appears again.

This one has not been fixed.

**Comment by pkdash** [comment]
Deleting of title and abstract are not allowed as they are required elements. Deleting of core metadata works only for keywords (there has to be one keyword), contributors, creators (there has to be one creator), key/value metadata, relation and source elements.

**Comment by horsburgh** [comment]
@pkdash - OK. Can we just change the message that goes with deleting the Abstract to something like:

"The Abstract is a required metadata element. Please add an Abstract to your resource."

**Comment by pkdash** [comment]
This issue wrongly got listed to test for AGU release. No work has been done to address it yet. Related work I did was to address #1073. Based on what I have done to address #1073, this issue would be easier to address.

**Comment by pkdash** [comment]
@horsburgh 
This is how I am planning to resolve this issue:
- The alert message "Resource Status: This resource can be published or made public" will appear only if the resource has not been set to public and it meets the requirement to be set to public.
- This alert message will appear only onetime when you update/add metadata and the system recognizes that the resource meets the requirements for the resource to be set public or publish. This restriction of displaying the alert onetime is limited to page being not refreshed. 
  - User creates a generic resource with one file. Then starts adding the title. No status alert message at this point. User adds the abstract. No status alert. User adds a keyword. User will see the status alert. User updates the title or abstract or ads another keyword - no status alert. User refreshes the page for the same resource. Trying to update any metadata element will show the alert. However, repeated updates will not show the alert. User set the resource to public which refreshes the page. At this point any metadata update will not show the status alert.  User set the resource to private or discoverable which reloads the page. Any metadata editing for the first time after the page reload will show the status alert.

**Comment by horsburgh** [comment]
@pkdash - this seems reasonable.

**Comment by pkdash** [comment]
This has been addressed. So closing.
