### ISSUE TITLE
REST API: Add ability to ingest resource from fully formed BagIt archive

### ISSUE THREAD

**Issue by selimnairb** [hydroshare/hydroshare#486]
Create new REST API end point, POST /hsapi/resourceFromBag/, that creates a resource based on a fully formed BagIt archive.  If the ID of the resource encoded in the bag does not exist, the resource will be created with that ID.  If the ID already exists, then a new ID should be generated for the resource.

**Comment by horsburgh** [comment]
The original createResource function was supposed to do this, but we had a lot of discussion about that.  So, just to clarify - there will be two methods right: 1) create a new blank resources to which you can add content; and 2) create a new resource from a fully formed bag?

**Comment by selimnairb** [comment]
@horsburgh Yes.

**Comment by hyi** [comment]
@jbradberry Putting it on your plate for now, this is related to https://github.com/hydroshare/hydroshare/issues/640.

**Comment by sblack-usu** [comment]
We do not have a specific use case for an API endpoint for ingestion.  There currently exists a management command for this functionality.  The code for the management command can be reused to create an API endpoint if the need arises.
