### ISSUE TITLE
REST API: Add resource landing page URL to resource system metadata

### ISSUE THREAD

**Issue by selimnairb** [hydroshare/hydroshare#487]
The resource metadata should include the URL to the resource landing page.  As it stands now, when creating a new resource via the REST API, only the resource ID is returned.  If the user agent wishes to redirect the user to landing page for a resource, newly created or already existing, the user agent needs to guess at the URL pattern HydroShare uses to form resource landing page URLs; this format may change, so there should be a programmatic way to get this URL from the API.  This will improve the addressability of the REST API, which is in general desirable.

**Comment by dtarb** [comment]
Does this issue pertain to the URL in the code.  The resourcemetadata.xml file does include the full path.

**Comment by horsburgh** [comment]
Yeah - it's in the very first RDF element.  So, you could get it easily by retrieving the resourcemetadata.xml file.

**Comment by pkdash** [comment]
@horsburgh and @alvacouch Should this be closed?
