### ISSUE TITLE
Maintenance page 301 on beta during data update after HS v2.0

### ISSUE THREAD

**Issue by devincowan** [hydroshare/hydroshare#4873]
**Description of the bug**
Maintenance page 301 on beta during data update after HS v2.0
![image](https://user-images.githubusercontent.com/17934193/205162069-5739ec54-855c-48f7-bbca-e6c3fc2fe557.png)

Believe due to static/static path changes
This happens during data update on beta
(but maintenance jenkins job is functional)

**Comment by pkdash** [comment]
@devincowan Looks like this line needs to be fixed:
https://github.com/hydroshare/hydroshare/blob/develop/nginx/run-nginx#L33

**Comment by devincowan** [comment]
thanks @pkdash you're right

**Comment by devincowan** [comment]
actually I just checked ^^^ is not the problem
maint jenkins job uses `./hs_proxy maint on`
whereas the beta deploy job uses `cd /home/hydro/hydroshare; ./hsctl maint_on`
