### ISSUE TITLE
Speedup solr indexing

### ISSUE THREAD

**Issue by pkdash** [hydroshare/hydroshare#4886]
It seems the same db queries are run multiple times when indexing a single resource.  The number of queries is about 100. The response time to update metadata for a private (no indexing) vs a discoverable (solr indexing occurs) resource is noticeable. It should be possible to substantially reduce the number of db queries used for indexing a resource which should improve metadata update response for discoverable resources as well reduce time taken to run a full re-index of all discoverable resources when deploying hydroshare.

**Comment by devincowan** [comment]
+1
