### ISSUE TITLE
Rephrase "Error! Metadata updated failed."

### ISSUE THREAD

**Issue by jsadler2** [hydroshare/hydroshare#490]
"Error! Metadata updated failed." is the message when a metadata element fails to update. It should be rephrased. "Error! Metadata failed to update." or "Error! Metadata update failed." would be better

**Comment by dtarb** [comment]
Relates to #474 too.

**Comment by mauriel133** [comment]
Oh, I started working on this before noticing that Hong already took care of it. Sorry.

**Comment by hyi** [comment]
@mauriel133 Yeah, at yesterday's team call, this issue was brought up and was asked to be incorporated into the NFIE hotfix release, so I just simply corrected the typo in my branch which is slated for the NFIE hotfix release.

**Comment by hyi** [comment]
ready for testing on park.hydroshare.org

**Comment by dtarb** [comment]
Tested and satisfied with behavior on park.
