### ISSUE TITLE
tool/app permission bug

### ISSUE THREAD

**Issue by zhiyuli** [hydroshare/hydroshare#492]
A tool/app associated with a res should display on that res' landing page only if the tool/app is public or the current user owns this tool.

**Comment by dtarb** [comment]
There are also in between cases.  If a tool is not public, but has been shared with a user or a group the user is part of then that tool should be accessible to the user.  Basically access to tools should follow the same rules as access to other resources in terms of sharing.

**Comment by zhiyuli** [comment]
closed.
