### ISSUE TITLE
Edit permission too powerful & single user removal problem

### ISSUE THREAD

**Issue by zhiyuli** [hydroshare/hydroshare#494]
On www.hydroshare.org:

1) A user which has been given "Edit" permission (middle level) is able to grant himself or others owner privileges (top level), including taking off the original owner.

2) If there is only on user on the Edit (middle) or View (Low) permisson list, there is no way to take that user off

Drew and Jeff

**Comment by zhiyuli** [comment]
@dtarb 
No.1 is the same as #481 ;  No.2 is a new issue.

**Comment by dtarb** [comment]
These have been resolved with the 1.6.0 and 1.6.1 deploy.
