### ISSUE TITLE
Error while approving resource for publication

### ISSUE THREAD

**Issue by ClaraCogswell** [hydroshare/hydroshare#4956]
**Description of the bug**
while attempting to approve a resource for publication I got the following error:  "This resource does not have a pending metadata review for you to approve."
![Screen Shot 2023-01-20 at 8 51 00 AM](https://user-images.githubusercontent.com/90924476/213713439-63954a04-1acc-4666-818c-fc75a7a836ea.png)

Steps to reproduce the bug:
1. Go to https://www.hydroshare.org/resource/0be7f3c7b2044fba8f19bfb8e806f1c2/

**Expected behavior**
should just approve the resource when I hit accept

**Additional information**
Add any other context about the problem here such as screenshots, software versions, and browser information.

**Comment by devincowan** [comment]
Making some notes here...
This resource had a review started on 1/18/23 but Help didn't receive the email for review until 1/20/23 (notably, after 2.2 deploy, email was sent ~midnight)
Checked the logs on both workers, didn't find anything of consequence, except:

> grep 0be7f3c7b2044fba8f19bfb8e806f1c2/submit-for-review/ access.log
152.54.2.89 - - [20/Jan/2023:05:32:40 +0000] "GET /hsapi/_internal/0be7f3c7b2044fba8f19bfb8e806f1c2/submit-for-review/ HTTP/1.0" 302 0 "https://www.hydroshare.org/resource/0be7f3c7b2044fba8f19bfb8e806f1c2/"
^^^the UTC time corresponds to the time that the metadata request was emailed to Help, as we would expect.

I see in the logs that there are a lot of changes to the resource AFTER it was submitted for review. I'm going to check to ensure that we are handling immutability correctly. Related to https://github.com/hydroshare/hydroshare/issues/4946

The res is in a published state, but the request was never sent to Crossref (or at least there is no record in crossref).

I noted that the 1/18/23 metadata review started date is a bug that needs fixing
https://github.com/hydroshare/hydroshare/blob/2.2/hs_core/views/__init__.py#L2115
the dates should be deleted on rejection AND approval, I will fix that. But this is not what caused the problem.

We should also probably set review_pending=false here:
https://github.com/hydroshare/hydroshare/blob/2.2/hs_core/views/__init__.py#L1192
as we do here:
https://github.com/hydroshare/hydroshare/blob/2.2/hs_core/views/__init__.py#L2100
but that isn't what caused this issue either.

```
>>> from hs_core.models import BaseResource
>>> res = BaseResource.objects.get(short_id='0be7f3c7b2044fba8f19bfb8e806f1c2')
>>> res
<BaseResource: Data for clogging enhancement in rock fractures>
>>> res.doi
'https://doi.org/10.4211/hs.0be7f3c7b2044fba8f19bfb8e806f1c2pending'
>>> res.raccess.review_pending
False
>>> res.metadata.dates.all().filter(type='review_started')
<QuerySet [<Date: review_started 2023-01-18 18:55:48.735034+00:00>]>
>>> res.raccess.published
False
```

**Comment by devincowan** [comment]
Seems there are a few other resources that are in this "state" that I will look into:
```
>>> for res in BaseResource.objects.filter(raccess__published=False, doi__contains='pending').all():
     print(f"{res.short_id}: {res.title}, {res.raccess.published_or_review_pending}")

d2d2aa2b02d94f10bde859aa2584a423: Blue Nile SWAT models setup using QSWAT Workflow v1.5.8 and QSWAT GUI, False
6923878ec11c4138a12cee1365d3fb8a: Conditioning digital elevation models for use in the evaluation of river networks and height above the nearest drainage for flood inundation mapping, False
4cda7a99dff04474867e336a9ccb7425: api-sd2, False
0be7f3c7b2044fba8f19bfb8e806f1c2: Data for clogging enhancement in rock fractures, False
```
https://www.hydroshare.org/resource/d2d2aa2b02d94f10bde859aa2584a423/
https://www.hydroshare.org/resource/6923878ec11c4138a12cee1365d3fb8a/
https://www.hydroshare.org/resource/4cda7a99dff04474867e336a9ccb7425/

Interesting to see that one of these res hasn't been edited since 2019
![image](https://user-images.githubusercontent.com/17934193/213777993-3009b33d-0b76-432e-920b-79ee552bf567.png)
So this means we have resources lingering with "pending publication status" that have been pending for YEARS...?

**Comment by devincowan** [comment]
```
deposit_res_metadata_with_crossref(res)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/hydroshare/hs_core/hydroshare/resource.py", line 995, in deposit_res_metadata_with_crossref
    files = {'file': (xml_file_name, res.get_crossref_deposit_xml())}
  File "/hydroshare/hs_core/models.py", line 3782, in get_crossref_deposit_xml
    ROOT = etree.Element('{%s}doi_batch' % ns, version="4.3.6", nsmap={None: ns},
AttributeError: module 'defusedxml.ElementTree' has no attribute 'Element'
```

**Comment by devincowan** [comment]
closing via https://github.com/hydroshare/hydroshare/pull/4959
