### ISSUE TITLE
Create diagram documenting system architecture

### ISSUE THREAD

**Issue by selimnairb** [hydroshare/hydroshare#496]
We need a diagram that documents the current (and planned?) architecture, i.e. which services are running in which containers, and how those containers and services are linked.

**Comment by dtarb** [comment]
I agree that a diagram is important and want to promote getting started on this asap.  Is there a technology that is best for us to work together on this.  There are some visio diagrams in Alfresco that @pkdash may be able to update.  Another option is Google Drawings.  There is one at https://docs.google.com/drawings/d/1i43SLJLxiIyrXbzionoGZyOgDS8kdw0CswtyIBWWIxg/edit that addresses the HydroShare class inheritance issues (From March 2015).  Then there are multiple powerpoint diagrams - but these are mostly too high level and Powerpoint is not ideal for working collaboratively on diagrams.

**Comment by gantian127** [comment]
@mjstealey @selimnairb would you please close this issue if you think it is fixed? Thanks
