### ISSUE TITLE
Revise email forwarding to prevent noise to hydroshare@cuahsi.org

### ISSUE THREAD

**Issue by devincowan** [hydroshare/hydroshare#4961]
Members of the hydroshare@cuahsi.org email list are receiving a large volume of email replies from Zendesk (help@cuahsi.org).
This is because HS sends emails to [help@cuahsi.org](mailto:help@cuahsi.org) with return address of [hydroshare@cuahsi.org](mailto:hydroshare@cuahsi.org)
Then Zendesk sends an auto-reply along the lines of "Thanks for submitting this issue... blah blah" back to [hydroshare@cuahsi.org](mailto:hydroshare@cuahsi.org) which gets distributed to members.

We should evaluate:
1. Can we turn off the auto-reply in zendesk, specifically for tickets/emails originating from hydroshare@cuahsi.org? If we can disable those auto-replies specifically for a single origination email, this would be a good solution.
2. If that is not possible, should we remove instances in the codebase where we send emails from `hydroshare@cuahsi.org` to `help@cuahsi.org`? An example below:

https://github.com/hydroshare/hydroshare/blob/2.2.1/hs_core/tasks.py#L198

**Comment by devincowan** [comment]
Sounds like @ClaraCogswell or @martinseul will have to look into option `#1` above.
If that is not possible, I will evaluate implementing `#2` or something similar...

**Comment by martinseul** [comment]
there is email forwarding for hydroshare@cuahsi.org to Chris and Dave. Is this still necessary or can we consolidate the forwarding to just help@cuahsi.org

**Comment by devincowan** [comment]
there are 4 places where our application sends emails from hydroshare@cuahsi.org to help@cuahsi.org:

1. [manage_task_hourly](https://github.com/hydroshare/hydroshare/blob/2.3/hs_core/tasks.py#L150) this is the hourly celery job that checks on pending publications and resubmits to Crossref as needed
2. [nightly_metadata_review](https://github.com/hydroshare/hydroshare/blob/2.3/hs_core/tasks.py#L238) this task checks for resources that have been under review for more than 24hrs
3. [send_over_quota_emails](https://github.com/hydroshare/hydroshare/blob/2.3/hs_core/tasks.py#L295) this task send our quota usage report
4. [task failure](https://github.com/hydroshare/hydroshare/blob/master/hs_core/tasks.py#L90) this sends an email when any of our tasks raise an exception

**Comment by devincowan** [comment]
@martinseul looks like there should be a way to change the trigger in Zendesk so that Zendesk auto-response is not sent for requests originating from hydroshare@cuahsi.org
See:
https://support.zendesk.com/hc/en-us/articles/4408828984346-About-the-Support-default-triggers#ariaid-title3
We would just add a conditional on the trigger in Zendesk
This accomplishes [#1 in the OP](https://github.com/hydroshare/hydroshare/issues/4961#issue-1553430529)

---

If that doesn't work, I would propose that we 

- either choose a different reply-to email (other than `hydroshare@cuahsi.org`) for the [4 functions above](https://github.com/hydroshare/hydroshare/issues/4961#issuecomment-1409053958)
- or choose a different email (other than `help@cuahsi.org` to send notifications to for the [4 functions above](https://github.com/hydroshare/hydroshare/issues/4961#issuecomment-1409053958)

**Comment by devincowan** [comment]
sounds like @martinseul is looking into this at the `hydroshare@cuahsi.org` Outlook mailbox level

**Comment by devincowan** [comment]
sounds like this has been resolved. closing
