### ISSUE TITLE
Resources with Organization as Author should show this author in My Resources

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#4987]
**Description of the bug**
The My Resources Listing for a resource owned by an organization, lists Author as None.  It should list the Organization Author.
![image](https://user-images.githubusercontent.com/3456833/217813270-e98f233f-f251-49d0-ae77-de17afbed612.png)

Steps to reproduce the bug:
1. Go to a resources such as https://www.hydroshare.org/resource/5057577e8573433d8045b59db91b2550/
2. Add to My Resources

![image](https://user-images.githubusercontent.com/3456833/217813530-3c18b0d6-f917-47e9-b0ce-f09b967159ca.png)

4. Go to My Resources
5. See error (My resources listing omits author)

**Expected behavior**
The Organization Author should be listed under author.

**Comment by devincowan** [comment]
adding some additional info
Here is the template: https://github.com/hydroshare/hydroshare/blob/2.3/theme/templates/includes/my-resources-trows.html#L60

We modified the template tag in [1.58](https://github.com/hydroshare/hydroshare/releases/tag/1.58), diff:
https://github.com/hydroshare/hydroshare/pull/4717/files#diff-37be798db1c0fc3349b2c258a83c19825d4a3bd707870dc4f1cc4ef3e8a07bf2R97
as part of work on https://github.com/hydroshare/hydroshare/issues/2368
