### ISSUE TITLE
Unusual activity in DOI resolutions 

### ISSUE THREAD

**Issue by ClaraCogswell** [hydroshare/hydroshare#4988]
**Description of the bug**
Typically HydroShare's most resolved DOIs are resolved ~60 times in 30 days. This has been the trend of previous crossref reporting. This month we received the following:

Below are the top 10 successfully resolved DOIs for this month. This list represents the most popular DOIs, as measured by the number of times each DOI was successfully resolved.
Top 10 DOIs	Successful Resolutions to DOI
[10.4211/HS.BC4300176D58468DAA693C2C3CD469AF](https://doi.org/10.4211/HS.BC4300176D58468DAA693C2C3CD469AF)	1633
10.4211/HS.[FE747D3511D84DF7BB2856E2C7E37C27](https://www.hydroshare.org/resource/fe747d3511d84df7bb2856e2c7e37c27/)	1624
10.4211/HS.[B7515F219C7A40439C9C2B44183192C4](https://www.hydroshare.org/resource/b7515f219c7a40439c9c2b44183192c4/)	1558
10.4211/HS.[8379C2859E194C1EB7428DBF60B8E4C1](https://www.hydroshare.org/resource/8379c2859e194c1eb7428dbf60b8e4c1/)	1340
10.4211/HS.[1300844AD3C647F3AB9C6C221F8747AE](https://www.hydroshare.org/resource/1300844ad3c647f3ab9c6c221f8747ae/)	1233
10.4211/HS.4478FC64E802496D86BADEFFFE809AB4	1120
10.4211/HS.81F35710FCE149E2B24CAD6C604497B8	1060
10.4211/HS.A8735826B8FE434CA570711A9B9ACB49	985
10.4211/HS.FC5C05D5EA3A42AE870BEDDC9F5B10AA	962
10.4211/HS.4BADD579D48E412E98A6D242F6F6AD91	920

I would like to know if this is genuine activity and of where this activity is coming from. 
**Expected behavior**
Here is last month for reference: 
![image](https://user-images.githubusercontent.com/90924476/218534640-6a3ba195-122e-4c95-9951-b94c3f061e74.png)

**Comment by devincowan** [comment]
there is certainly something odd going on here...

Taking a look on the active worker:
```
$ grep -c "bc4300176d58468daa693c2c3cd469af.*200" access.log
40
```
But these would just be recent hits to this resource, so...

Checking the activity log that gets exported daily by Jenkins calling the [stats command](https://github.com/hydroshare/hydroshare/blob/2.3/hs_tracking/management/commands/stats.py#L40)
```
$ grep -c "http_code=200.*bc4300176d58468daa693c2c3cd469af" activity.log
2040

So it is actually feasible that there were 1633 resolutions (which surprises me). What I want to know now is what user_agent these were, looking at that.

**Comment by martinseul** [comment]
@cbcunc could you please take a look when you're back,

**Comment by devincowan** [comment]
as @cbcunc pointed out, I was being a dunce -- yes indeed all the requests to the inner proxy are made by the outer proxy (thus a renci ip) :)
I just checked the logs on the outer proxy
```
root@4a5fb210773f:/var/log/nginx# grep -rl "bc4300176d58468daa693c2c3cd469af.*200" .
./access.log
root@4a5fb210773f:/var/log/nginx# grep -c "bc4300176d58468daa693c2c3cd469af.*200" access.log
80
root@4a5fb210773f:/var/log/nginx# grep -c "bc4300176d58468daa693c2c3cd469af.*200.*bot" access.log
13
root@4a5fb210773f:/var/log/nginx# grep -rl "fe747d3511d84df7bb2856e2c7.*200" .
./access.log
root@4a5fb210773f:/var/log/nginx# grep -c "fe747d3511d84df7bb2856e2c7.*200" access.log
46
root@4a5fb210773f:/var/log/nginx# grep -c "fe747d3511d84df7bb2856e2c7.*200.*bot" access.log
11
```
the "bot" searches were because I noticed that many of the requests were made by `EarthCube_DataBot/1.0` as well as 
https://moz.com/help/moz-procedures/crawlers/dotbot
https://ahrefs.com/robot/
among others

Then I realized oops, log rotation, the old logs are compressed :)
```
$ gunzip access.log-20230201.gz
$ grep -c "bc4300176d58468daa693c2c3cd469af.*200" access.log-20230201
2989
```
Now we are getting somewhere...

```
grep "bc4300176d58468daa693c2c3cd469af.*200" access.log-20230201 | grep -o '\([0-9]\{1,3\}\.\)\{3\}[0-9]\{1,3\}' | grep -v 127.0.0.1 | grep -v 1.2.3.4 | grep -v '^192\.168' | sort | uniq -c | sort -rnb
```
Gives:
    141 52.210.169.103
    133 52.212.102.189
    123 54.229.26.162
    122 3.250.88.164
    121 34.243.59.241
    119 3.249.158.131
    108 176.34.222.242
    106 3.253.21.150
    100 54.246.179.21
     ...

All of the ips that made more than 100 requests to this resource are AWS data centers in Ireland
https://whatismyipaddress.com/ip/52.210.169.103

**Comment by devincowan** [comment]
@ClaraCogswell unless @cbcunc has a different interpretation, I'd have a hard time saying what/who is making these requests. Majority are coming from AWS centers in Ireland but maybe just VPN/proxy so who knows.

**Comment by ClaraCogswell** [comment]
Update: DOI resolutions back to normal this month
