### ISSUE TITLE
Resource failing to load

### ISSUE THREAD

**Issue by ClaraCogswell** [hydroshare/hydroshare#4993]
**Description of the bug**
The following resource: https://www.hydroshare.org/resource/4eac370d12e142b5aa718e5deb57da39/
will not load and results in an error message. Depositor says there is 500 kb of data in the resource.

Steps to reproduce the bug:
1. Go to https://www.hydroshare.org/resource/4eac370d12e142b5aa718e5deb57da39/

**Comment by devincowan** [comment]
```
>>> res
<BaseResource: Mt. Fuji hydrogeochemical and microbiological dataset>
>>> res.short_id
'4eac370d12e142b5aa718e5deb57da39'
>>> res.metadata.relations.all()
<QuerySet [<Relation: relation Mount Fuji>, <Relation: isDescribedBy Schilling, O. S., Nagaosa, K., Schilling, T. U., Brennwald, M. S., Sohrin, R., Tomonaga, Y., Kipfer, R., Brunner, P., & Kato, K. (2023). Revisiting Mt. Fuji’s groundwater origins helium, vanadium and environmental DNA tracers. Nat. Water 1, doi: 10.1038/s44221-022-00001-4>]>
>>> rel = res.metadata.relations.last()
>>> rel
<Relation: relation Mount Fuji>
```
Looks like this resource somehow has an AbtractRelation that isn't further inherited.

SOURCE_TYPES empty
https://github.com/hydroshare/hydroshare/blob/master/hs_core/models.py#L999

So this template tag fails:
https://github.com/hydroshare/hydroshare/blob/master/hs_core/models.py#L1017

Not sure how the owner managed to add an Abstract relation -- shouldnt be possible through UI maybe via API will check.
But for now we can
1. add exception handling for the [type_description](https://github.com/hydroshare/hydroshare/blob/master/hs_core/models.py#L1016) or maybe migrate the abstract relation to a different relation type

**Comment by devincowan** [comment]
Resolved for this particular resource by running
```
>>> from hs_core.models import Relation
>>> Relation.objects.filter(type='relation').all()
<QuerySet [<Relation: relation Mount Fuji>]>
>>> rel = Relation.objects.filter(type='relation').first()
>>> rel.delete()
(1, {'hs_core.Relation': 1})
```
No other resources are impacted.
I believe that this resource was created during a brief gap before we did some migrations of relations, and during that time it was possible to create a generic "relation" via the UI/API
I'm going to ensure that it's no longer possible and then close this issue.
