### ISSUE TITLE
Owners of published resources can edit metadata through the API

### ISSUE THREAD

**Issue by sblack-usu** [hydroshare/hydroshare#5006]
**Description of the bug**
Owners of a published resources currently can edit metadata through the metadata ingestion API endpoints.

**Expected behavior**
Published resources allow some metadata to be edited and not others.  We currently do not need to allow users to modify a published resource through the API so we can go ahead and block published resource editing through this endpoint.

**Additional information**
https://github.com/hydroshare/hydroshare/blob/develop/hs_rest_api2/views/metadata.py#L20

**Comment by devincowan** [comment]
PR https://github.com/hydroshare/hydroshare/pull/5007 as part of hotfix 2.4.1
