### ISSUE TITLE
update signal processor to prevent unnecessary recursion

### ISSUE THREAD

**Issue by devincowan** [hydroshare/hydroshare#5017]
Related to #5015 
I just dropped a breakpoint in [handle_save](https://github.com/hydroshare/hydroshare/blob/2.4/hs_core/hydro_realtime_signal_processor.py#L20) and was surprised that **updating the title of a resource**, a simple change, results in 6 calls to `handle_save`!

1. <Title: Untitled Resourceaaaa>
2. <BaseResource: Untitled Resourceaaaa>
3. <CompositeResource: Untitled Resourceaaaaa>
4. <Date: modified 2023-03-21T13:15:33.646070+00:00>
5. <BaseResource: Untitled Resourceaaaaa>
6. <Variable: Variable object (920)>

1 and 4 are sensical enough. I can potentially see why we need 2 to update the resource index even though we update the Title metadata in 1. I don't understand why we need 3, but I can be convinced easily. 5 is perplexing...seems like a duplicate -- for a simple title change we index the BaseResource to  _twice!?_ oh but I do see that `handle_save` calls itself recursively so that prob what's going on. And then 6 I believe this is an hs_tracking Variable which doesn't get indexed so I guess it's okay.

I feel like some of these calls can obviously be async as @sblack-usu suggested. But might we run into race conditions etc if we are saving the updated date (4) and the BaseResource (2, 5)? Think the answer is "NO" because we are just talking about updating the indexes async, so I would think there wouldn't be a problem (vs for instance, actually saving to the Django db).

_Originally posted by @devincowan in https://github.com/hydroshare/hydroshare/issues/5015#issuecomment-1477839803_
            
Seems like we might want to revise our signal processor, [custom haystack processor](https://django-haystack.readthedocs.io/en/v2.4.1/signal_processors.html#custom-signalprocessors)
We are thinking there could be significant performance gain if we trigger (async?) indexing not for all saved objects but just for `Raccess` and `Date` metadata objects with `type=modified`

**Comment by sblack-usu** [comment]
I'm excited to see the performance gains from this!  It looks promising.

**Comment by pkdash** [comment]
@devincowan 

> Also worth noting that a simple view (not edit/save) of the resource landing page triggers ~5 calls the the handle_save method of our signal processor

The fix I made for #5015 should result in no indexing for resource view landing page.

**Comment by sblack-usu** [comment]
I was curious about the signal processor and it was straightforward to implement. If we go with it, we should have @alvacouch take a look.
