### ISSUE TITLE
Geoconnex facility is slow

### ISSUE THREAD

**Issue by ksonda** [hydroshare/hydroshare#5019]
**Description of the bug**
When using the geoconnex interface, geometries are slow to load. 

ALSO: public water systems still arent there

**Additional information**
I believe this is because of some way the geoconnex requests are being made in an interative or recursive fashion. Many more requests than necessary are being made
![image](https://user-images.githubusercontent.com/44071350/226972284-0c34b20a-9e70-443a-a760-435bd1465207.png)

**Comment by devincowan** [comment]
thanks @ksonda you're right that I need to update the requests

Regarding PWS, I haven't enabled it because there is still an extraneous name field in the collection:
https://github.com/hydroshare/hydroshare/issues/4801#issuecomment-1463035910
> thanks @ksonda! ZIPPY FAST! So this is probably my lack of knowledge. Looks like there are two different name mappings for the PWS features, in 2 separate contexts: ![image](https://user-images.githubusercontent.com/17934193/224192704-734deefa-0e4b-4f96-86ae-a7378a6931c0.png) https://reference.geoconnex.us/collections/pws/items?f=jsonld&limit=1
> 
> But of course when we query there is only the `pws_name` https://reference.geoconnex.us/collections/pws/items?f=json&limit=1
> 
> How do we know which context will hold the correct name field for the features?

**Comment by ksonda** [comment]
ok for pws there's only one possibiltiy now

**Comment by devincowan** [comment]
that did the trick thanks @ksonda 
we can handle multiple names as long as they map to fields that exist.
I'll make sure the pws fix goes out in our next release

**Comment by devincowan** [comment]
release in 2.4.2
