### ISSUE TITLE
Refactoring HISRefTimeSeries - Downloadable files on the fly

### ISSUE THREAD

**Issue by zhiyuli** [hydroshare/hydroshare#502]
@dtarb @danames @pkdash @hyi @mjstealey @selimnairb 
With the design change we have settled on as a team, the HISRefTimeSeries resource will no longer store resource files in IRODS, making it a truer "reference" type resource. However, this raises a challenge. How can we make files available for download that are only stored temporarily (in Django)? We can easily store these in the 'tmp' folder, however, we do not know how to make them available for download as they would be outside the publicly accessible virtual directory. Also, how long should these files be retained in the system? How can we know the user has finished downloading the file?

**Comment by zhiyuli** [comment]
@hyi  I have a question. Can I create a bag in IRODS that has not res files but does contain the resourcemetadata.xml? I am asking this because in this HIS Time Series new design, we will not store res files.  But I find I need to store metadata in xml in order to retrieve them when using HS rest api on tethys side.

@selimnairb  I find current rest api python wrapper has a func for retrieving system metadata: resource_md = hs.getSystemMetadata('e62a438bec384087b6c00ddcd1b6475a')
Where do you extract this metadata? from django db or irods xml files? 
Also, one attribute of system metadata the api returns is: science_metadata_url': u'http://dev.hydroshare.org/hsapi/scimeta/8b51ea59f5ab4239b742981204649d18/ 
same question: what is the science_metadata_url pointing to? data from django db or irods xml files? 

Thanks
Drew

**Comment by hyi** [comment]
@zhiyuli If I understand your question correctly, the answer is yes. You mean a resource with no file added, just like when you create a resource without browsing any file, right? Yes, you need a resourcemetadata.xml even for a resource without files for standard dublin core system metadata.

**Comment by selimnairb** [comment]
@zhiyuli /hsapi/sysmeta gets metadata from the Django database.  See [SystemMetadataRetreive](https://github.com/hydroshare/hydroshare/blob/master/hs_core/views/resource_rest_api.py#L318).

Likewise /hsapi/scimeta gets science metadata from the Django database.  See [here](https://github.com/hydroshare/hydroshare/blob/master/hs_core/views/resource_rest_api.py#L392) and [here](https://github.com/hydroshare/hydroshare/blob/master/hs_core/hydroshare/resource.py#L58)

**Comment by zhiyuli** [comment]
closed.
