### ISSUE TITLE
add a select for "subject areas"

### ISSUE THREAD

**Issue by devincowan** [hydroshare/hydroshare#5022]
**Describe the feature you'd like and what it will do**
Currently, subject areas is free text.
Should be a typeahead -- noninvasive.
@martinseul suggested that we should populate a list similar to
https://has.arizona.edu/research-focus-areas

Related to https://github.com/hydroshare/hydroshare/issues/4733

**Comment by devincowan** [comment]
@martinseul who might be best to review our list of [proposed subject areas](https://github.com/hydroshare/hydroshare/blob/5022-subject-areas/hs_dictionary/management/commands/subject_areas.txt)?

**Comment by dtarb** [comment]
I'm going to punt on this.  I can not do everything.  Sorry if this comes off snarky, but it is late at night.  We used to have the concept of product owners as people who owned different areas of the product.  The document may be dated but look at [this](https://docs.google.com/document/d/18T1Sq390jm7vbH3Xg6nAZuGpD0lV9KxVoGDcTJGfQCM/edit?usp=sharing).  Product owner for user profile was either @ClaraCogswell or @Castronova .  Part of the reason for punting on this is that I do not fully appreciate what we are trying to achieve by having a type ahead list for this.  It would not be high on my priorities, or even an issue in our list of bugs and backlog to address.  We have much bigger issues to address like the scalability problem of not being able to add to a collection.

**Comment by ClaraCogswell** [comment]
I'll take it. Devin this list looks good, as long as we also make it clear that they can enter something that is not in the type ahead. I've gotten questions about this before "do I have to use something from the list my thing is not on the list", so we should have a little note somewhere that says it is free text entry, the type ahead is just for convenience/search efficiency but there is not actually a controlled vocab being enforced (unless there is but I thought I remembered that not being hte case).

**Comment by horsburgh** [comment]
My $0.02 - I'm with Clara. The list looks mostly fine as a type-ahead list of suggestions. There's some really long and specific ones in there, though, that don't seem that broadly useful. We don't want to force people to select specific terms from this list unless they want to.

**Comment by devincowan** [comment]
Thanks @dtarb for the product owners list -- I hadn't seen this, sorry for the hassle. I agree we have bigger fish to fry, so I'll try not to linger here.
@ClaraCogswell noted -- adding a note to make it obvious that free text is permissible.
And @horsburgh thanks for the cents!

**Comment by martinseul** [comment]
Improving the profile data and the ability to report on users is important to CUAHSI and the additional lift for adding the subject type ahead while fixing the regression we discovered for the institutions is a small lift so IMHO worth the effort. 
I agree on looking at the product owners to help distribute work. The list is a bit outdated as you mentioned and we should revisit, maybe a topic for the HS governance discussion.

**Comment by devincowan** [comment]
I noticed there are potential edge cases in existing profile Subject Areas that will break the current migration (for example, if a user has a subj area like: "{ this , , will ,, fail{ to parse []}}}"

Re-opening and will update the migration so that it handles appropriately
