### ISSUE TITLE
Adding content to a collection

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#5030]
Is there anything that can be done to speed up "loading" when switching a collection resource to edit mode to add a resource.  I have a need to add content to https://www.hydroshare.org/resource/b6c4fcad40c64c4cb4dd7d4a25d0db6e/ but switched to edit mode and sat for about 15 min, during which time I wrote this issue and did many other things, then gave up.  Loading never completed, so I could never add what I wanted to.

![image](https://user-images.githubusercontent.com/3456833/228696299-fd3e9a58-813e-402b-8e28-872e98572557.png)

**Comment by devincowan** [comment]
@dtarb I just gave it a try and the delay, if existent, was imperceptible:
https://user-images.githubusercontent.com/17934193/228846941-193c03e7-e336-41fc-8f9b-56c7207add60.mov
if you try again, can you do so with your browser console open and see if there are any errors etc when it stalls "loading"

**Comment by dtarb** [comment]
I get
![image](https://user-images.githubusercontent.com/3456833/228861839-9f686fe8-c563-41a8-a951-7b66ae6fecf0.png)

The red error at the bottom took about a minute to appear.

**Comment by dtarb** [comment]
I am using Chrome.  I cleared all cache within the last week and this was the first time I tried to do this since then.  I can try again, and try another browser but I am pretty sure I'll get the same problem.  My sense is that the front end is trying to load too many resources for me to choose to load and that is holding things up.  It may be because I have more resources than you, but more broadly resource selection is a challenge.

**Comment by dtarb** [comment]
Just tried on Edge after complete cache clean out and reset and received the following errors
![image](https://user-images.githubusercontent.com/3456833/229553681-5a01db4b-6a52-4da0-ae34-cf27b38f0009.png)

**Comment by devincowan** [comment]
Thanks @dtarb you're spot-on, I did a rough timing test this morning and this issue does seem to scale with # of resources.

**Comment by devincowan** [comment]
Taking a closer look here, I see that Pabitra [did some work as recently as May 2022](https://github.com/hydroshare/hydroshare/issues/3554) on the `get_collectable_resources` function. @pkdash, the queries here (https://github.com/hydroshare/hydroshare/blob/2.4/hs_collection_resource/utils.py#L131) look fairly optimized to me--do you see room for further improvement or do you think we need to revise the whole workflow?

**Comment by devincowan** [comment]
@dtarb we can make some improvements without impact to the UI. My tests indicate this should be adequate to speed things enough that it wont time out.

However, it will still be slow. If we can compromise by removing the "My permission" column, that will save 1-3 db queries per resource in the list. Removing the "Owner" column would reduce 1 query per resource which would also help.

I'm guessing altering these columns is off the table, but thought I would put it forward in case we feel they aren't necessary.
![image](https://user-images.githubusercontent.com/17934193/230200661-51ce26cb-c5f9-4897-95dc-c4706d0a4ad9.png)

**Comment by dtarb** [comment]
I think we can remove My Permission.  I also think type and sharing status are not that helpful.  This is really just a resource selection mechanism and these to not seem needed for the user to find the resource they want to add.  

I think that the listing of collectable resources should be identical to the listing of resources on the "My Resources" page - which, while slow to load, does not time out.  Could similar (identical) queries be used to produce the collectable list for adding a resource.

**Comment by devincowan** [comment]
@dtarb I like your idea of using a similar approach as the My Resources page.
We improved loading time on that page in two ways: async requests and loading each "filter" individually.

The [Collectable Resources list load is already async](https://github.com/hydroshare/hydroshare/blob/master/theme/static/js/collection-resource.js#L532), so there's no low-hanging fruit there.

Adding filters to the Collectable Resources modal, similar to those for the My Resources Page:
![image](https://user-images.githubusercontent.com/17934193/230911646-1f04b970-191d-4d50-a393-83d75478f7aa.png)
would potentially help and might improve UX. That would take me a bit longer maybe we can discuss today whether it's worth the effort or if we should just settle for removing "My Permission" from the modal along with the [query/template improvements I already added](https://github.com/hydroshare/hydroshare/pull/5038/files#diff-6922cf14aeef23445bd891c75597aad54f86e2480c1d2a13b30d4948121c634dR29).

**Comment by devincowan** [comment]
related to the following issues for Django cache:
- https://github.com/hydroshare/hydroshare/issues/4683
- https://github.com/hydroshare/hydroshare/issues/4953
- https://github.com/hydroshare/hydroshare/issues/4935

I'm going to add these issues into our "selected next for dev"

**Comment by devincowan** [comment]
@dtarb a hopeful fix has been deployed to beta
if you get a chance, I'm curious how things load for you now:
https://beta.hydroshare.org/resource/b6c4fcad40c64c4cb4dd7d4a25d0db6e/

**Comment by devincowan** [comment]
Great! this is included in 2.5 release
