### ISSUE TITLE
New users are unclear about why/whether they need an iRODS account

### ISSUE THREAD

**Issue by horsburgh** [hydroshare/hydroshare#5061]
**Describe the feature you'd like and what it will do**

A user that is new to HydroShare let us know that the yellow area with the message about creating an iRODS account shows up when he creates his account. But, he doesn't know why he would need to do so, or what it would be used for.  The messaging around this could be changed to provide additional information about why a user would want to create an iRODS account.

![image](https://user-images.githubusercontent.com/3485902/235470130-c302eb21-8583-49db-8ed8-ffcd2b10033a.png)

**Why is this feature important?**

New users may be confused by this message and not know what they should do. Most users will not need or use an iRODS account.

**Is your feature request related to a problem? Please describe.**

This issue was reported by a new user.

**Additional context**

NA

**Comment by martinseul** [comment]
@ClaraCogswell would you please review and update the documentation where needed.

**Comment by ClaraCogswell** [comment]
I can, iRods is cross listed a few places but I can add an FAQ? Or we can change that pop up that confused the user to say "In order to upload large files (Greater than XGB, create an iRODS account"

**Comment by horsburgh** [comment]
This is on the user profile page. I think just making the wording clear where this is displayed about why they would need an iRODS account would be sufficient. I suggest the following wording (similar to Clara's):

> You have not created an associated iRODS account in the HydroShare user zone (users.hydroshare.org). You only need to do this if you want to use iRODS to upload large files (greater than XGB) to HydroShare.  For more information, click here.

Link the "click here" to documentation, and fill in the "XGB". I'm not sure what the practical limit is. 1 GB? 2 GB?

**Comment by ClaraCogswell** [comment]
Let compromise for brevity, as we know the more words there are the less people read, and the more cluttered the page:

"You have not created an associated iRODS account in the HydroShare user zone (users.hydroshare.org), In order to upload large files (Greater than XGB), create an iRODS account"

And link to docs.
