### ISSUE TITLE
License drop down is active to any user on a published resource

### ISSUE THREAD

**Issue by ClaraCogswell** [hydroshare/hydroshare#5077]
**Description of the bug**
Any user can change the license of this published resource: https://www.hydroshare.org/resource/90951d952b034e7aa592898ab6d264eb/
though the changes do not save, the user is given the option to select "save changes"

Steps to reproduce the bug:
1. Go to 'https://www.hydroshare.org/resource/90951d952b034e7aa592898ab6d264eb/
2. scroll down to license
3. select the license drop down

**Expected behavior**
No user should be able to interact with the license drop down of a published resource

**Additional information**
Add any other context about the problem here such as screenshots, software versions, and browser information.

**Comment by devincowan** [comment]
released as 2.5.4
