### ISSUE TITLE
Geoserver.hydroshare.org is down

### ISSUE THREAD

**Issue by danames** [hydroshare/hydroshare#5084]
**Description of the bug**
As of May 17, 2023 at 12:24 PM Mountain, it appears that geoserver.hydroshare.org is down. Just checking if this can be rebooted or what needs to be done. 

Steps to reproduce the bug:

**Expected behavior**

**Additional information**
Add any other context about the problem here such as screenshots, software versions, and browser information.

**Comment by devincowan** [comment]
I just created a new resource to test on production
https://www.hydroshare.org/resource/f7dc437483f143c4b9d89a406e0c419f/

**Comment by sblack-usu** [comment]
As @devincowan mentions, geoserver is indeed up and running.  I think there is confusion around the url.  We can avoid confusion in the future by rediriecting geoserver.hydroshare.org to https://geoserver.hydroshare.org/geoserver/web/

**Comment by danames** [comment]
OK with some investigation it seems to be this is due to my specific resource, https://www.hydroshare.org/resource/e9b3b818dd9845e3a062197ac6f98b79/ A quick consult with @martinseul and we noted that the spatial data are in subfolders which isn't currently supported in HydroShare. I will close this issue - but we should figure out how to prioritize the subfolder issue.
