### ISSUE TITLE
Create Reference Generic URI

### ISSUE THREAD

**Issue by mjstealey** [hydroshare/hydroshare#51]
### Extends generic resource by:

- uses base generic resource metadata
- no file upload is expected
- single field needed to hold URL
- landing page should reference something like "click this link" to view

**Comment by mjstealey** [comment]
BYU - Initiated work as branch [51-URI-resource-phase-1](https://github.com/hydroshare/hydroshare/tree/51-URI-resource-phase-1)

**Comment by zhiyuli** [comment]
tested on alpha (1.5.3). closed
