### ISSUE TITLE
Duplicated environment variable

### ISSUE THREAD

**Issue by Maurier** [hydroshare/hydroshare#5107]
**Description of the bug**
The environment variable `IRODS_ZONE` is repeated in the configuration below.
https://github.com/hydroshare/hydroshare/blob/develop/local-dev.yml#L24

Steps to reproduce the bug:
1. Open a command line window and navigate to your main `/hydroshare` folder.
2. Run `./loal-dev-first-start-only.sh`
3. Notice that the script errors out and references this variable.

**Expected behavior**
The script runs as expected.

**Comment by devincowan** [comment]
@Maurier FYI Scott already fixed in https://github.com/hydroshare/hydroshare/pull/5054
