### ISSUE TITLE
"How to cite" youtube link broken

### ISSUE THREAD

**Issue by devincowan** [hydroshare/hydroshare#5113]
**Description of the bug**
<img width="513" alt="image" src="https://github.com/hydroshare/hydroshare/assets/17934193/32a74023-2068-4ec7-a2c9-a1e6f316ea61">
Resource landing page has a broken link 
https://github.com/hydroshare/hydroshare/blob/2.6.1/theme/templates/resource-landing-page/citation.html#L9
that points at
https://www.youtube.com/watch?v=jSeveop01Hk
which doesn't exist

Steps to reproduce the bug:

**Expected behavior**
Upload a youtube video and fix the link

**Additional information**
2.6.1

**Comment by ClaraCogswell** [comment]
I have created the needed video, and it will be uploaded to Youtube shortly, will provide link when complete

**Comment by ClaraCogswell** [comment]
https://youtu.be/A1q1MKhO6CE
