### ISSUE TITLE
Sitemap.xml contains private resources

### ISSUE THREAD

**Issue by martinseul** [hydroshare/hydroshare#5125]
**Description of the bug**

The sitemap.xml refers to the list of resources in a file [here ](https://www.hydroshare.org/sitemap-resources.xml ) by design this should only contain published, public and discoverable  resources but does also contain private resources e.g.[https://www.hydroshare.org/resource/e2fdf99cbb0c4275b32afd3c16ae6863/](https://www.hydroshare.org/resource/e2fdf99cbb0c4275b32afd3c16ae6863/). 

A fix need to be applied to remove all references to private resources.

**Comment by devincowan** [comment]
I also see that our `robots.txt` lists an incorrect sitemap:
![image](https://github.com/hydroshare/hydroshare/assets/17934193/ecb2667b-5a51-4397-8ec5-18683d48cc23)
