### ISSUE TITLE
geoAnalytics contains non-conforming access control mechanisms

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#513]
The GeoAnalytics interface (ga_\*) is 
a) hopelessly out of date 
b) unused except for utility functions
c) not compliant with access control conventions (Page\*Mixin rather than Resource\*Mixin)

It would be good to delete that code from the project.

We would have to start over anyway, were we to eventually want to use it.

**Comment by ironfroggy** [comment]
Can someone confirm this code should be removed? @hyi perhaps you know?

**Comment by hyi** [comment]
I am planning to clean it up as detailed in issue #949. I am consolidating them into one by closing this one and use #949 to keep track of the work on this issue.
