### ISSUE TITLE
Inconsistency in terminology: "Extended Metadata" at the aggregation level VS "Additional Metadata" at the resouce level

### ISSUE THREAD

**Issue by imanmaghami** [hydroshare/hydroshare#5131]
As mentioned by @dtarb, at the resource level HydroShare uses the term “Additional Metadata”, but in an aggregation, the term used is “Extended Metadata”.  HydroShare should be conisstent with terminology.

**Comment by pkdash** [comment]
@imanmaghami and @dtarb Which one should we use for consistency?

**Comment by dtarb** [comment]
I vote for "Additional", but that is just one vote.

**Comment by imanmaghami** [comment]
I also vote for "Additional" as "Extended" somehow might imply metadata extended by the model instance metadata schema.

**Comment by horsburgh** [comment]
+1 for "Additional"

**Comment by devincowan** [comment]
@ClaraCogswell Pabitra made a fix for this that will go in 2.8 release on 8/8/2023.
There are [sundry mentions of "Extended Metadata" on help.hydroshare.org](https://help.hydroshare.org/search/?q=extended), can we plan to update those as well?

**Comment by ClaraCogswell** [comment]
yes, I will update all instances of "extended metadata" to "additional metadata"

**Comment by ClaraCogswell** [comment]
There are 66 instances all on separate pages so it will take me some time to get through all of them just because they are so spread out. I will try to have this done in the next two weeks. I will update when it is done.

**Comment by devincowan** [comment]
Maybe there is a bulk find/replace method that will help? Thanks Clara!

**Comment by ClaraCogswell** [comment]
There is not but I wish there was. I'll get started on it
