### ISSUE TITLE
Optimize resource copy/version creation

### ISSUE THREAD

**Issue by pkdash** [hydroshare/hydroshare#5149]
During my recent work on optimizing folder delete, I came across opportunity to optimize code for creating a copy or a new version of a resource. The current code makes number of DB queries that are very dependent on the number of files in the resource. For each file it makes at least 3 queries. This is not a problem if the resource does not have a large number of files.  Copying a resource with large number of files using the REST endpoint is going to cause a time out error.

**Comment by devincowan** [comment]
Resolved in https://github.com/hydroshare/hydroshare/pull/5150, Slated for 2.8 release
