### ISSUE TITLE
metadata editing mode err for specific resource type 

### ISSUE THREAD

**Issue by gantian127** [hydroshare/hydroshare#515]
I pulled the latest code from 'develop' branch. After I created a new netCDF or Raster resource, I click on the editing metadata button, it shows the following error (The error won't appear for generic resource ).  This seems to be caused by the code update in hs_core. The page_processors.py for each specific resource type may need to be updated.

![l olbgoqrbcuq xs gl 34](https://cloud.githubusercontent.com/assets/5016511/8535448/15e1e3da-2403-11e5-9206-07ba53e0ac5a.png)

**Comment by hyi** [comment]
@gantian127 Could you test it on dev.hydroshare.org and close it if it works there?

**Comment by hyi** [comment]
tested on dev using raster and metadata editing works as expected. Closing.
