### ISSUE TITLE
Keywords look like buttons

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#516]
Based on Rick Hooper's review of HydroShare he was puzzled by the appearance of what are keywords below Subject on the landing page.  They look like buttons, and change color when hovered over reinforcing that they may be buttons, but clicking on them does nothing.  I suggest changing to a comma separated list of words as plain text.

**Comment by horsburgh** [comment]
They don't do anything now, but they may eventually - e.g., click on a keyword to execute a search to pull up a list of resources that are tagged with the same keyword. I would suggest leaving for now.

**Comment by mjstealey** [comment]
no longer change when hovered over
