### ISSUE TITLE
Folder Rename timeout for directory containing ~500 files

### ISSUE THREAD

**Issue by devincowan** [hydroshare/hydroshare#5170]
**Description of the bug**
Related to https://github.com/cznethub/dsp/issues/110
Related to https://github.com/hydroshare/hydroshare/issues/5158

Steps to reproduce the bug:
Make a copy of https://www.hydroshare.org/resource/61611563a45b4d678b1947ae3be7da42/
Attempt to rename one of the folders containing 500+ files

**Expected behavior**
Either we should prevent the timeout or we should return a more meaningful explanation.

**Additional information**
HS v 2.7.1

**Comment by pkdash** [comment]
@devincowan Most likely, this code block is causing the timeout error when there are many files in a folder:
https://github.com/hydroshare/hydroshare/blob/develop/hs_core/views/utils.py#L891
