### ISSUE TITLE
File missing on iRODS causes file list endpoint to break

### ISSUE THREAD

**Issue by pkdash** [hydroshare/hydroshare#5175]
**Description of the bug**
If a file is registered in DB but missing in iRODS, the file list endpoint (**hsapi/resource/{id}/files**) generates a 500 (internal server error)

Steps to reproduce the bug:

**Expected behavior**
If a file is missing in iRODS, the file list endpoint still should be able to list all files that are available both in DB and iRODS. 

**Additional information**
Add any other context about the problem here such as screenshots, software versions, and browser information.

**Comment by devincowan** [comment]
released as 2.8.1
