### ISSUE TITLE
Look at portal.lternet.edu for ideas on improving resource landing page

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#518]
Based on review of HydroShare with Rick Hooper he noted a number of places where retrieving information from HydroShare resources and their landing pages was unclear, and possibly better done at portal.lternet.edu
- There is a metadata link that expands the metadata.  This seemed more user friendly than our resourcemetadata.xml retrieved as part of the bag with no easy visualization tools.
- There is Matlab, R, SAS and SPSS code for analyzing the data.  I just tested one R script and it is slick in that it includes data download.  This could be a nice enhancement to our multidimensional, raster, time series and referenced time series resources, drawing on the new WaterML R functionality.

**Comment by selimnairb** [comment]
We could do something similar to adding R scripts, but using https://jupyter.org to host R and Python scripts that could be run in the browser.  @swainn Is there a plan to add a Jupyter-based Tethys tool?

**Comment by swainn** [comment]
There are no plans for integrating jupyter into Tethys at this point, but there is also nothing restricting an app developer from incorporating it into an app for a specific use case. If it becomes a tool that is need frequently in multiple apps, then I would consider creating a tool/gizmo for it. @selimnairb what capabilities do you see jupyter being used for? Plotting via R scripts?

**Comment by selimnairb** [comment]
@swainn Yes, plotting (R, Python, perhaps other tools supported by Jupyter), but also to provide a general scripting environment for transforming HydroShare resources (e.g. time series QA/QC).

**Comment by hyi** [comment]
@mauriel133 I am putting this on your plate as it involves resource landing page. @pkdash or me can help to implement backend support if needed.

**Comment by martinseul** [comment]
not relevant anymore
