### ISSUE TITLE
Migrate iRODS quota microservice to Python API

### ISSUE THREAD

**Issue by cbcunc** [hydroshare/hydroshare#5195]
**Describe the feature you'd like and what it will do**
Migrate the iRODS quota microservice to the Python API.

**Why is this feature important?**
Needed to migrate iRODS to 4.3.1

**Is your feature request related to a problem? Please describe.**
@devincowan Would you please reference your issues here?

**Additional context**
iRODS team offered to help. Need a 4.3 test server. Need a 4.3.1 timeline.

**Comment by devincowan** [comment]
apologies @cbcunc, the long list (hundreds) of quota discrepancies that I saw on Beta was much shorter (only 3 users). So I ruffled everyone's feathers unnecessarily.

**Comment by cbcunc** [comment]
https://github.com/hydroshare/hsrules

**Comment by devincowan** [comment]
Closing as no longer needed.
Quota [updates released as 2.14](https://github.com/hydroshare/hydroshare/issues/5228) move the HS datazone away from microservices.
