### ISSUE TITLE
Complete profile not working on beta

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#5212]
Testing beta.hydroshare.org with new login system, after logging in I clicked on Complete Profile on the home page and got

https://beta.hydroshare.org/user/

![image](https://github.com/hydroshare/hydroshare/assets/3456833/aa0a20ab-8e32-4f38-a0ce-eb416a597f07)

**Comment by devincowan** [comment]
Thanks @dtarb I added the setting
