### ISSUE TITLE
Valid region not valid on beta with new single sign on

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#5213]
I went to my profile while testing single sign on in beta and get the following
![image](https://github.com/hydroshare/hydroshare/assets/3456833/0991ff56-dce4-4151-85dc-88d78e3e35b6)
But Utah is a valid region and on the drop down

**Comment by devincowan** [comment]
@dtarb I'm looking into the region validity. My guess is that you maybe had leading or trailing blank "Utah " but I will investigate.

Re phone number, we standardized the format with country code (triggered based off of country) in this issue:
https://github.com/hydroshare/hydroshare/issues/4235

**Comment by devincowan** [comment]
Verified with Scott that this is not related to Keycloak. Independent issue.

**Comment by dtarb** [comment]
OK.  I fixed my profile by reselecting Utah in the drop down and formatting my phone number as now required.  Closing.
