### ISSUE TITLE
User account deletion doesn't remove resources from SOLR index

### ISSUE THREAD

**Issue by devincowan** [hydroshare/hydroshare#5217]
**Description of the bug**
Deleting a user in mezzanine also cascades to delete the user's resources. However it looks like the resources are not removed from the SOLR index. They still show up in discover.

Steps to reproduce the bug:
1. make a new user account
2. add a resource and make it discoverable
3. login as admin user and delete the account that you created in step 1 (via the mezzanine admin panel)
4. See that the resource listing persists on the Discover search page

**Expected behavior**
User account deletion should remove the user's resources from the SOLR index

**Additional information**
HS v 2.9.2

**Comment by devincowan** [comment]
for some reason we can't remove a resource from SOLR that has already been removed from django:
https://github.com/hydroshare/hydroshare/blob/develop/hs_core/management/commands/solr_update.py#L142
we should figure out why

**Comment by sblack-usu** [comment]
I think we could probably figure out how to delete solr indexes that aren't in Django.  The remove method takes the django model instance or a string.  If you pass in the django model instance then it creates a string identifier from that looks like `<app.label>.<object_name>.<pk>`.  I don't see why we couldn't create that string manually and pass it into the remove method.

It is also possible to override the identifier method.  We could probably update the identifier method to just use the short_id. https://django-haystack.readthedocs.io/en/master/settings.html#haystack-identifier-method
