### ISSUE TITLE
NSF-PAR dataset entry to pull required metadata fields from published HydroShare DOI

### ISSUE THREAD

**Issue by jordansread** [hydroshare/hydroshare#5225]
As part of adhering to [NSF's EAR data policy](https://www.nsf.gov/geo/geo-data-policies/ear/ear-data-policy-jul2023.pdf), 

> PIs and co-PIs are also expected to provide updates to the general public by reporting on data and sample management activities within the Project Outcomes Report and by indexing research products within the NSF Public Access Repository ([NSF-PAR](https://par.nsf.gov/)). The Project Outcomes Report and NSF-PAR entries can be viewed on the public-facing award page.

I heard from NSF EAR POs that one simple step in helping the community adhere to this policy is to have their DOI-fetch populate the required metadata when adding a new dataset publication to their awards (detailed instructions for doing so are [here](https://resources.research.gov/common/attachment/Desktop/How_to_Add_Datasets_to_NSF-PAR.pdf)). I searched PAR and it doesn't seem like HydroShare DOIs show up. I wonder if this has something to do with DOIs coming from CrossRef instead of DataCite?

#### I tried drafting the process to submit a dataset to see how this would work out. 
[10.4211/hs.6e102de63a7943e1900aa8c6a8d412ac
](https://www.hydroshare.org/resource/6e102de63a7943e1900aa8c6a8d412ac/) is a HydroShare-published dataset and [10.5066/P9CEMS0M](https://www.sciencebase.gov/catalog/item/60341c3ed34eb12031172aa6) is a ScienceBase-published dataset. 

#### The HydroShare dataset populates NSF-PAR metadata as this: 
(only the title shows up)
<img width="1012" alt="image" src="https://github.com/hydroshare/hydroshare/assets/2349007/9c0f1ad6-f1aa-4775-b29e-c58eb1f0fb61">

#### The ScienceBase dataset populates NSF-PAR metadata as this: 
(all required fields are populated)
<img width="1020" alt="image" src="https://github.com/hydroshare/hydroshare/assets/2349007/71b386d7-9d32-4f71-ba13-e1b03a7ae4c3">

**Comment by horsburgh** [comment]
From a repository perspective, I think resolving this to work better is important. This may be related to how HydroShare deposits metadata with the DOI registration system. Getting metadata back using a DOI relies on the metadata having been deposited correctly/completely with the DOI registration system in the first place. If the title is coming back but no other metadata are coming back, it could mean that the DOI registration system has incomplete metadata.

**Comment by devincowan** [comment]
I agree this is important.
Looks to me like we aren't submitting some of the info at all and some of the metadata is improperly submitting:
https://github.com/hydroshare/hydroshare/blob/2.9.3/hs_core/models.py#L3913-L3966

**Comment by horsburgh** [comment]
This came up in the CZNet PI meeting today. HydroShare has registered a bunch of DOIs for published resources. We know that HydroShare has not deposited a complete metadata record with the DOI registration service up to this point in time. I think it's really important that we fix this for all future published resources. However, I think we should also fix this for ALL published resources. It's up to us to maintain the deposit metadata that goes with DOI registrations. Also, that deposit metadata is something that needs to be actively maintained. 

Now that NSF's Public Access Repository (PAR) allows metadata retrieval using a DOI, I think we are going to hear from people about this when they are trying to fill out their annual and final reports to NSF.

**Comment by jordansread** [comment]
It would be great if this statement (or a better one, you wordsmiths!) could be true ahead of our proposal submission on Dec 1:
> Registering a published HydroShare resource in NSF’s Public Access Repository populates required metadata automatically and only takes a few seconds to submit.

**Comment by devincowan** [comment]
@martinseul see:
https://www.crossref.org/blog/using-the-crossref-rest-api.-part-7-with-chorus/

> Every night we query the Crossref API to send us metadata for all article or conference proceeding records for our member publishers that have funder metadata matching the funders monitored by CHORUS.

> CHORUS monitors these DOIs for public accessibility on publisher websites; inclusion in agency search tools; deposit in a growing list of funder repositories (e.g.,[US DOE PAGES](https://www.osti.gov/pages/),[NSF PAR](https://par.nsf.gov/), and [USGS Publications Warehouse](https://pubs.er.usgs.gov/) and [NIH PubMed Central](https://www.ncbi.nlm.nih.gov/pmc/)); and for associated ORCID researcher records. CHORUS also uses the reuse license metadata to identify when an article is expected to be made publicly accessible.

Sounds to me like CHORUS might be querying Crossref metadata and depositing with NSF-PAR

**Comment by martinseul** [comment]
Thanks @devincowan , yes that seems to be an option for us to to tie into the system without using Data cite. One thing to confirm is that the type of data we publish is harvested as we don't publish Articles or conference proceedings. We could try to in a first step augment the metadata we send to crossref to include the data needed to tie into NSF-PAR and in a second step add a more complete set of metadata beyond the minimum requirements.

**Comment by horsburgh** [comment]
@martinseul - why do this in two steps? If we are going to fix the deposit metadata that is being sent to Crossref when a DOI is registered, why not just do the job once? PAR is just one potential consumer of the deposit metadata.

Also @devincowan - I read that text in the article about CHORUS as 'CHORUS monitors DOIs for deposit in a growing list of funder repositories' - e.g., they are monitoring whether the DOI has been deposited. I don't think they are doing the deposits. Maybe I'm reading that wrong, but I think deposit into PAR (i.e., registration of a DOI in PAR) is up to the authors. It would be nice if someone was doing the work to register all Crossref DOIs with NSF's PAR, but I doubt that's the case.

**Comment by martinseul** [comment]
one reason is that Jordan wants this to be done quickly so doing it in 2 steps helps with that as this would cover the initial need, if it's easy and quick  I'd be open to combine the two. We also have to extend this to be tied to the editing of resources as users could add funding sources after the initial deposit, this functionality does not exist yet.

**Comment by martinseul** [comment]
O looked at the metadata in crossref and collected some relevant information 

- Funder: the documentation to a add a funder is _[here](https://www.crossref.org/documentation/funder-registry/funding-data-overview/)_ as well as [here ](https://www.crossref.org/documentation/funder-registry/funding-data-deposits/)and ties to a Open Funder List that they recommend using
- datasets need to be submitted as a collection which we do, more info on that [here](https://www.crossref.org/documentation/schema-library/markup-guide-record-types/datasets/)
- we currently use version 4.3.6 latest version is 5.3.1 so we might want to move to a newer version.

The steps I see we  need to implement

1. Mapping metadata Hydroshare to crossref
2. Update the inital data deposit to include the mapped metadata
3. implement a update event to redeposit to crossref the xml if any of the fields we deposit is updated
4. develop a management script to migrate existing published resources to include all mapped fields
5. Confirm that CHORUS actually pics up the new metadata records and registers them with NSF-PAR as we're depositing a data collection not a an article or conference proceeding.

I do think the long term goal should be to move to Data Cite as this seems more appropriate for the majority of data we publish.

**Comment by devincowan** [comment]
@horsburgh sounds like you are willing to help on 
> 1. Mapping metadata Hydroshare to crossref

@pkdash suggested that I confirm with you that **I haven't started on that mapping process**

**Comment by horsburgh** [comment]
@devincowan - yes, I put this on my list. I have not done any work on this yet either other than sorting out where the Crossref deposit metadata schema is located. Do you guys have any preference on what the mapping should look like? Maybe an example deposit XML document for a resource? Could also do a GitHub gist or something like what I did for the Schem.org mapping a while ago: https://gist.github.com/horsburgh/29c44a4b526603bc174605189d0001e3

**Comment by devincowan** [comment]
@horsburgh an example deposit XML seems like it might be the most straightforward and simple.

**Comment by horsburgh** [comment]
See new GitHub repo here: [https://github.com/hydroshare/hs_doi_deposit_metadata](https://github.com/hydroshare/hs_doi_deposit_metadata) that I'm hoping can be a place where we document HydroShare's DOI registration and deposit metadata mapping - regardless of whether HydroShare sticks with Crossref or eventually switches to Datacite.

My draft take on mapping HydroShare's metadata more completely to what Crossref provides is [here](https://github.com/hydroshare/hs_doi_deposit_metadata/blob/main/docs/HydroShare_Crossref_Deposit_Metadata.md), and an example XML metadata deposit document that validates with their validation service is [here](https://github.com/hydroshare/hs_doi_deposit_metadata/blob/main/examples/HydroShare_Crossref_Deposit_Metadata_Example.xml).

**Comment by devincowan** [comment]
Reopening because our work in https://github.com/hydroshare/hydroshare/pull/5274 improved our crossref deposit, but the issue of NSF-PAR deposit still remains.

I was incorrect [when I suggested](https://github.com/hydroshare/hydroshare/issues/5225#issuecomment-1789483994) that CHORUS might deposit our Crossref DOIs into NSF-PAR, from @martinseul research, it sounds like automated transfer from Crossref to NSF-PAR isn't possible (though @jordansread suggested that DataCite might accomplish this?)

At any rate, right now with Crossref, the best we can do is include something like the following in the email that is sent to resource owner at the time of publication:

> We recommend that you index your new DOI within the NSF Public Access Repository ([NSF-PAR](https://par.nsf.gov/)). This is a manual process. Once registered, entries can be viewed on the public-facing award page.

Please suggest more appropriate language! Thanks...

**Comment by devincowan** [comment]
Discussed on todays Hydroshare developer call. We decided to hold off for now on any recommendations about NSF-PAR deposit. After we release the. [Crossref PR](https://github.com/hydroshare/hydroshare/pull/5274), @dtarb has offered to do some testing with NSF-PAR deposit and we will revisit this issue at that time.

**Comment by jordansread** [comment]
I started at https://nsfpar.research.gov/input-form using the [10.4211/hs.6e102de63a7943e1900aa8c6a8d412ac](https://www.hydroshare.org/resource/6e102de63a7943e1900aa8c6a8d412ac/) dataset


<img width="1033" alt="image" src="https://github.com/hydroshare/hydroshare/assets/2349007/b331aa4f-3717-43e8-bd9b-a495f1f3c1e1">

And it doesn't appear "HydroShare" is coming through as the publisher (a required field). But significant progress since the last time. 

then I tried [10.4211/hs.42ee6fcbf9f64bf882c579df948176e2](https://www.hydroshare.org/resource/42ee6fcbf9f64bf882c579df948176e2/) and same result, no publisher coming through. I tried the ScienceBase DOI from my initial post and that one still comes through with U.S. Geological Survey as publisher.

**Comment by devincowan** [comment]
Thank you for checking @jordansread!

@pkdash Here is a look at the XML submission:
```
  <body>
    <database>
      <database_metadata language="en">
        <titles>
          <title>HydroShare Resources</title>
        </titles>
        <publisher>
          <publisher_name>HydroShare</publisher_name>
        </publisher>
      </database_metadata>
      <dataset dataset_type="record">
...
```
https://doi.crossref.org/servlet/submissionAdmin?sf=content&submissionID=1609800818

So the `<publisher>` element is in line with Jeff's schema:
https://github.com/hydroshare/hs_doi_deposit_metadata/blob/main/docs/HydroShare_Crossref_Deposit_Metadata.md#database

And I checked that it matches the Crossref schema
https://data.crossref.org/reports/help/schema_doc/5.3.1/crossref5_3_1_xsd.html#publisher

So I'm wondering if this is a limitation of the way that PAR pulls the info from Crossref.

**Comment by martinseul** [comment]
I wonder if the publisher should be CUAHSI and not HydroShare, as we're the organization minting the DOI and Hydroshare is a tool to host the data.

**Comment by martinseul** [comment]
to add to this the actual crossref record for the DOI prefix is [here](https://doi.crossref.org/getPrefixPublisher/?prefix=10.4211) and returns this:
<xml>
<script/>
<publisher>
<publisher_name>Consortium of Universities for the Advancement of Hydrologic Science, Inc. (CUAHSI)</publisher_name>
<prefix_name>Consortium of Universities for the Advancement of Hydrologic Science, Inc.</prefix_name>
<publisher_location>Cambridge, MA, United States</publisher_location>
<member_id>2730</member_id>
<member_type>Member Publisher</member_type>
<annual_fee>275</annual_fee>
<date_joined>2009-05-18</date_joined>
<other_prefixes>
<prefix>10.4211</prefix>
</other_prefixes>
</publisher>
</xml>

So I suggest changing the publisher to match the entry in the crossref registration.  There is a depositor list as well [here](https://www.crossref.org/06members/51depositor.html) and our metadata in crossref seems to be incomplete I did reach out to support to see if we can fix this.

**Comment by devincowan** [comment]
Are their any potential unintended consequences of updating the `publisher` for all of our Crossref records?

Even with this update to the publisher metadata as @martinseul recommended, I don't think we would expect the NSF-PAR input-form to populate the publisher from Crossref -- there must be something else going on there...

**Comment by martinseul** [comment]
right these are probably 2 separate issues. If we agree to change the publisher in HS to align with the DOI minting organization or change the entry in crossref to refer to Hydroshare this would require a new issue for that task. Why the publisher does not appear correctly is the issue we'd track here.

**Comment by devincowan** [comment]
I created a [separate issue](https://github.com/hydroshare/hydroshare/issues/5381) for changing the Publisher from HydroShare -> CUAHSI.

The reason that the `publisher` doesn't populate into NSF-PAR is because PAR only accommodates the DataCite schema, and the publisher in that schema looks like this:
https://datacite-metadata-schema.readthedocs.io/en/4.5/properties/publisher/#publisher

**Comment by devincowan** [comment]
Looks like we have carried this as far as possible. Additional metadata can be pulled once we resolve https://github.com/hydroshare/hydroshare/issues/5385

**Comment by cbcunc** [comment]
https://support.datacite.org/docs/datacite-or-crossref
