### ISSUE TITLE
Management command for published resources

### ISSUE THREAD

**Issue by devincowan** [hydroshare/hydroshare#5230]
**Describe the feature you'd like and what it will do**
We should have a management command to report on resources published within a timeframe.
Consider also adding to our metrics system

**Additional context**
HS 2.9.2

**Comment by ClaraCogswell** [comment]
Ideally will include: DOI, title, date of publication, funder information

**Comment by devincowan** [comment]
I missed @ClaraCogswell's request for all of the funder info, so re-opening.
