### ISSUE TITLE
Duration to delete directory increases exponentially based on # of files

### ISSUE THREAD

**Issue by devincowan** [hydroshare/hydroshare#5235]
@pkdash and I noticed that irods irm on dir with 30 tiny files takes up to 1min

@cbcunc and I isolated the issue to the current microservices

Likely resolved by:
https://github.com/hydroshare/hydroshare/issues/5195
(but creating this issue in case there are interim patches that can be made)

**Comment by devincowan** [comment]
related to https://github.com/hydroshare/hydroshare-quota/issues/5

**Comment by cbcunc** [comment]
Attempt at fix in https://github.com/hydroshare/hydroshare-quota/pull/9

**Comment by devincowan** [comment]
resolved by Quota [updates released as 2.14](https://github.com/hydroshare/hydroshare/issues/5228) move the HS datazone away from microservices.
