### ISSUE TITLE
Plan for prioritizing and completing unit tests

### ISSUE THREAD

**Issue by selimnairb** [hydroshare/hydroshare#524]
Tests that do not pass have been disabled.  We need to determine which tests to retain, and which tests are yet to be written.  Then, we should:
1. Remove tests not to be retained
2. Prioritize tests to be finished and new tests to be written
3. Finish/write needed tests

**Comment by pkdash** [comment]
Once the base concrete resource class work and new access control work gets merged to develop, I should be able start working on hs_core unit tests and time series resource unit tests.  Other resource type developers can also then start working on unit tests for their resource types.

**Comment by pkdash** [comment]
We have already addressed this issue. I am closing this one even though there are still tests to be written in particular for views in hs_core.
