### ISSUE TITLE
Case insensitive SSO user profiles might allow for username clash

### ISSUE THREAD

**Issue by devincowan** [hydroshare/hydroshare#5269]
**Description of the bug**
What if we have 2 users in HS:
ClaraCogs
claraCogs
Whichever of them logs into CUAHSI SSO first will generate a
claracogs
user in SSO
Then when the 2nd user tries to log in, they wouldn't be able to

Steps to reproduce the bug:
I haven't tested this, just making a note that it could be an issue

**Additional information**
HS v2.11

**Comment by sblack-usu** [comment]
This is a non-issue thanks to the [CaseInsensitiveMezzanineBackend](https://github.com/hydroshare/hydroshare/blob/develop/theme/backends.py#L45)
