### ISSUE TITLE
Abstract should retain line break formatting

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#529]
If In enter an abstract like this
![p1](https://cloud.githubusercontent.com/assets/3456833/8639496/2a9ac8ce-2899-11e5-9560-135ca998951f.PNG)

it should not all run together like this
![capture](https://cloud.githubusercontent.com/assets/3456833/8639499/36fa874e-2899-11e5-99f6-73983b80e72d.PNG)

**Comment by horsburgh** [comment]
I don't disagree with the issue, and it might be nice to support Markdown formatting in the Abstract.  But, if you need a lot of structure in your Abstract, we should really be considering whether this is a resource of a different type (and hence that structure should be split out into separate elements in the metadata).

**Comment by hyi** [comment]
I fixed this abstract line break issue before, which got lost along the way. will reinstate my previous fix to make line break work for abstract.

**Comment by dtarb** [comment]
@horsburgh how would you suggest I present the content attempting to be presented in this resource.

**Comment by horsburgh** [comment]
@dtarb - If you just want it to be a generic resource, overloading the Abstract might be OK.  But, do we need a "script" resource type that has specific metadata elements for the things that you are trying to break out in the Abstract field?

**Comment by dtarb** [comment]
I worry that requiring the development of a new resource type is a heavy lift for just wanting to list out separate paragraphs to describe what is in a resource.  I'd also like a reasonable intermediate solution before scripts are completed.  A capability with all resources to be able to add custom/extended metadata fields, maybe an alternative solution.  I know that these have been discussed at various points, but not implemented yet.

The short term solution is reinstating @hyi 's previous fix that got lost.

**Comment by hyi** [comment]
@mjstealey while trying to test verify this fix on dev.hydroshare.org, I found the linebreaks in abstract are still not retained on dev, although the same code pulled from develop branch in my local development environment retains linebreaks in abstract. Is dev deployed with nginx? It looks like the Django linebreaks filter that converts newlines into HTML does not work in our deployed VM but it does work in the local develop environment where DEBUG is set to TRUE. Any ideas on why this could happen?

**Comment by mjstealey** [comment]
This short answer to this is:
```sh
[hydrobuild@dev pages]$ git status
# On branch 532-jenkins-automated-testing
```
The longer answer:

- While at the Hydroinformatics conference we changed the branch that dev was building to be `532-jenkins-automated-testing` instead of `develop` to more efficiently test our work in real-time.
We apparently forgot to change this back to develop and have been re-deploying branch 532 instead of develop this week.
Sorry about that…

Have updated and issued a rebuild via Jenkins so you should be able to check your work on dev again shortly.

**Comment by hyi** [comment]
@mjstealey Thanks! Now it works on dev in the same way as it does in my local dev env. However, I accidentally found a minor issue when editing the same abstract again, so made a follow-up fix to it and just created a pull request with one line change. Once merged, fix to this issue should be ready for testing.

**Comment by danames** [comment]
Ultimately it would be very useful to support basic mark up on the abstract
and let users use it however they want - i.e. to make lists, emphasize
points with bold or underline, and possibly even link to external resources
in a free form way that is not constrained by specific metadata fields or
options. At a bare minimum we should honor their line breaks.

**Comment by hyi** [comment]
tested on dev and line break in abstract is now working. Set it as Ready for testing.

**Comment by dtarb** [comment]
tested on dev and closing
