### ISSUE TITLE
"Liked by 0" message on ratings

### ISSUE THREAD

**Issue by mauriel133** [hydroshare/hydroshare#530]
On the Rating section of the resource landing page, seeing that a resource is liked by no one is a little discouraging. I think when the number of likes is 0 the message should be changed to "Be the first to +1 this resource" or something similar.

**Comment by mauriel133** [comment]
![ss](https://cloud.githubusercontent.com/assets/2448568/9046538/37040852-39f9-11e5-8d76-890d55044773.png)

Would this work?

**Comment by danames** [comment]
I like that text. Friendly and positive.

**Comment by mauriel133** [comment]
This fix has been merged and appears to be working in develop.

**Comment by dtarb** [comment]
Checked on alpha
