### ISSUE TITLE
The WMS link of my Resource opens a HTTP Status 404 – Not Found Error

### ISSUE THREAD

**Issue by jersjar7** [hydroshare/hydroshare#5308]
**Description of the bug**
I have problems with any resource that I create. When I open the WMS link of the resource "App Datasets", I get an "HTTP Status 404 – Not Found" Error.
Also, in my "NWM Streams" resource, I added a new file named "midpoint_wgs84" and when I open the WMS link, it doesn't consider it as a layer/

Steps to reproduce the bug:
I'm the Author: Jerson Jaramillo Garcia
1. Go to 'App Datasets'
2. Click on 'The WMS link'
3. See error

**Expected behavior**
I need the links to display the data correctly so I can pull that information into a mobile app that I'm working on.

I appreciate your prompt help!!!

**Comment by devincowan** [comment]
@jersjar7 I'm taking a look at [your resource ](https://www.hydroshare.org/resource/1aa3370de73d4dc384bc1ae88ae0e618/). I see that your shapefile uses EPSG:3395. We discovered in issue https://github.com/hydroshare/hydroshare/issues/5273 that the 3395 CRS isn't working right now with our geoserver.

I reprojected into EPSG4326 and created a test resource here:
https://beta.hydroshare.org/resource/687add4b3c5c49ada2ecd24e09e251a9/

You can see that, once reprojected, the WMS link works:
https://geoserver-beta.hydroshare.org/geoserver/HS-687add4b3c5c49ada2ecd24e09e251a9/wms?request=GetCapabilities
(don't use this link in your app, it will get wiped away in a couple weeks. It is on our beta system)

So I'm going to close this issue in favor of #5273 but the quick fix for you is to upload your vector data in a different CRS.
