### ISSUE TITLE
If no downloads within a year, should we "offboard" a resource's zipped bagit archive

### ISSUE THREAD

**Issue by devincowan** [hydroshare/hydroshare#5310]
As we contemplate changing our storage backend and aim to turn on quota enforcement, it would be good to contemplate how much of our storage is being used by "cold" files that no one is accessing. Zipped bagit archives could be removed after some interval of inactivity (I propose a year)--in this case "inactivity" would mean no recent downloads.

**Comment by sblack-usu** [comment]
The storage systems themselves ensure data integrity/durability.  Amazon claims [99.999999999% durability](https://docs.aws.amazon.com/AmazonS3/latest/userguide/DataDurability.html).  Checksums may also be used in data transfers for [object integrity](https://docs.aws.amazon.com/AmazonS3/latest/userguide/checking-object-integrity.html).

@devincowan - do you have stats on how much storage the bags use?  How much storage would we save if implemented today?

**Comment by devincowan** [comment]
Sorry for the confusion @ClaraCogswell and @horsburgh. Jeff's interpretation was indeed my intent, I updated the issue name and description to make it more clear.

And Scott has a good point, we should crunch some stats. I will do that

**Comment by devincowan** [comment]
I took a look and realized that we only track **number of download**, not date of last download. Offboarding stale bags is not going to be possible unless we add download date to our data models.

I added a management script that calculates the bagit storage size for "old" resources with "old" being defined by `resource_last_modified` date. (using this to infer how recently a bag might've been used is admittedly very poor indeed but it is the best inference I can see without changing our data model to track download date). I did this because I'm still curious how much space is taken up by bags. If we want, we could include this management script in a minor release to production and I could run it to get a (very rough) feel for how much space is being used by bags.

**Comment by devincowan** [comment]
looks like [78GB worth of bags for resources that haven't been updated in the last year](https://new-hs-ci.hydroshare.org/view/02-Deployment/job/Production-Deployment/job/prod-hsctl-command/265/console).

[Command for ALL resources (included recently updated)](https://new-hs-ci.hydroshare.org/view/02-Deployment/job/Production-Deployment/job/prod-hsctl-command/266/console)
