### ISSUE TITLE
Title not editable on public resource

### ISSUE THREAD

**Issue by ClaraCogswell** [hydroshare/hydroshare#5312]
**Description of the bug**
Title does not become editable in edit mode on public resource

Steps to reproduce the bug:
1. Go to (https://www.hydroshare.org/resource/bd2b1ec6ac94441db3acdfddb97c1bfa/)
2. Click on edit with admin permissions 
3. Scroll down to title

**Expected behavior**
title should be editable on public resources

**Additional information**
this resource was rejected for publication

**Comment by devincowan** [comment]
resolved in hotfix 2.12.1
