### ISSUE TITLE
Include publisher in XML metadata to Crossref

### ISSUE THREAD

**Issue by devincowan** [hydroshare/hydroshare#5319]
https://github.com/hydroshare/hs_doi_deposit_metadata/blob/main/docs/HydroShare_Crossref_Deposit_Metadata.md
we need to add 
```
<publisher><publisher_name>HydroShare</publisher_name></publisher>
```
to [get_deposit_xml](https://github.com/hydroshare/hydroshare/blob/2.12/hs_core/models.py#L3931)

**Comment by devincowan** [comment]
related to https://github.com/hydroshare/hydroshare/issues/5225

**Comment by pkdash** [comment]
@devincowan Can we close this now>

**Comment by devincowan** [comment]
This has been merged to develop but not released yet.
I would like to release this along with other PRs in develop as [2.12.1](https://github.com/hydroshare/hydroshare/issues/5317) release
