### ISSUE TITLE
create a distribution list (email) for Hydroshare developers and set as default for notifications where appropriate

### ISSUE THREAD

**Issue by devincowan** [hydroshare/hydroshare#5328]
This would be to avoid overloading "support/help" with inappropriate emails.
Something like "dev at cuahsi dot org"
I'm thinking it would include:
@devincowan 
@sblack-usu 
@pkdash 
@cbcunc 
@martinseul

**Comment by martinseul** [comment]
the distribution list has been created _**dev@cuahsi.org**_ with members outlined above.

**Comment by devincowan** [comment]
Thanks Martin, I will wire up the emails where appropriate.
