### ISSUE TITLE
Test THREDDS Server with NFIE iRODS and FUSE

### ISSUE THREAD

**Issue by rayi113** [hydroshare/hydroshare#534]

**Comment by rayi113** [comment]
Have test THREDDS server successfully running on top of iRODS FUSE pointing at nfiehydroZone
Dependencies: Relies on iRODS FUSE bundled with iRODS version 4.1.5 that will come out in the next 1-2 months.  Have iRODS engineering build if folks want to try it sooner.

**Comment by gantian127** [comment]
@rayi113 would you please close this issue, if you think it is fixed? Thanks
