### ISSUE TITLE
Author identifiers don't show (view mode) on the resource landing page

### ISSUE THREAD

**Issue by devincowan** [hydroshare/hydroshare#5340]
### Update 20240209:
Our models are fine. But in "view" mode, the resource landing page fails to display the author identifiers.

---

### Previous non-issue:

**Description**
This could be a non-issue but we need to check and implement tests where missing.
We maintain author identifiers on two separate models:
https://github.com/hydroshare/hydroshare/blob/2.12.3/hs_core/models.py#L472
https://github.com/hydroshare/hydroshare/blob/2.12.3/theme/models.py#L383

This results in odd behavior. Depending on how the identifiers are added into hydroshare, they might not show up in a user's profile. For example:
This user profile: https://www.hydroshare.org/user/6671/
Does not show any author identifiers in the UI. But when we look in the db:
```
>>> from hs_core.models import BaseResource
>>> res = BaseResource.objects.get(short_id='db248589a52a41c4a6f387bbefbab3a9')
>>> res.metadata.creators.all()
<QuerySet [<Creator: Sharma, Abhinav>, <Creator: Castro-Bolinaga, Celso>]>
>>> u = res.metadata.creators.first()
<Creator: Sharma, Abhinav>
>>> u.identifiers
{'ORCID': 'https://orcid.org/my-orcid?orcid=0000-0002-5995-9297'}
```
This is because the profile template uses the user.userprofile.identifiers
https://github.com/hydroshare/hydroshare/blob/2.12.3/theme/templates/accounts/profile.html#L12
But this user probably had the identifiers added via the Party model (for example maybe an owner added them as an author on the resource, and then edited their author identifiers).

Here we can see the Party identifier exists. But the user.userprofile identifier does not:
```
>>> from hs_core.models import BaseResource
>>> res = BaseResource.objects.get(short_id='db248589a52a41c4a6f387bbefbab3a9')
>>> u = res.metadata.creators.first()
>>> u
<Creator: Sharma, Abhinav>
>>> u.identifiers
{'ORCID': 'https://orcid.org/my-orcid?orcid=0000-0002-5995-9297'}
>>> u.userprofile.identifiers
Traceback (most recent call last):
  File "<console>", line 1, in <module>
AttributeError: 'Creator' object has no attribute 'userprofile'
>>> u.hydroshare_user_id
6671
>>> from hs_core.models import User
>>> user = User.objects.filter(pk=u.hydroshare_user_id).first()
>>> user.userprofile.identifiers
{}
```
I think this is fine and likely intentional. The issue is that we must be careful which set of identifiers we are using.
Particularly this is true when we are including the identifiers in DOI request at publication time to crossref.

**Expected behavior**
We should check to ensure that we are consistently using each of the identifier sets at the proper times

**Additional information**
hs v 2.12.3

**Comment by devincowan** [comment]
Showing 2 identifiers (ResearchGate and ORCID) on a resource author
<img width="1170" alt="image" src="https://github.com/hydroshare/hydroshare/assets/17934193/f1b29994-0662-4270-99ce-ec776dfea50f">

But only a single identifier on the same user's profile:
<img width="663" alt="image" src="https://github.com/hydroshare/hydroshare/assets/17934193/1d8fbf80-4fa1-4a1a-b832-fb620b13ed0e">

**Comment by pkdash** [comment]
@devincowan Since a creator/contributor (Party model) may not be a hydroshare user, we have the identifiers in 2 places and currently they are independent from each other. We use the identifiers from the Party model for crossref deposit. We can consider using the identifiers from the user profile  when the associated Party model missing that information.

**Comment by devincowan** [comment]
Thanks @pkdash yep all checks out. I left this issue open last night until I had a chance to ensure that Crossref deposit was using the Party model. Having verified that, I'm closing this issue.

**Comment by horsburgh** [comment]
It should also be noted that the Author/Creator information in a resource's metadata is created at the time the user adds an author to that resource. There may be particular reasons why a resource owner wants to have the author metadata show up in a certain way on the resource, so we shouldn't change it when a user's profile changes. This is why the two are decoupled - in addition to what @pkdash said about an author potentially not being a HydroShare user. 

Here we adopted a model similar to what journals do. When you publish a paper, your author and affiliation information is what it is when the paper is published. It doesn't change if you change jobs, etc. The user's HydroShare profile may change over time, but that doesn't mean that the the author information for every resource they have participated in as an author should be changed every time they modify their profile.

Now - there may be some discussion about the addition of identifiers like ORCID and Google Scholar profile, etc. whose purpose is to disambiguate people and link people to published items, but the rest of the author information should be set by the creator of the resource and shouldn't change unless someone with edit privileges on that resource specifically changes it. And, I would vote to leave published resources as they are.

**Comment by devincowan** [comment]
Thanks @horsburgh  and @pkdash my confusion came from the fact that we don't properly display author identifiers in the Hydroshare UI. I'm going to update this issue's title to reflect that.
