### ISSUE TITLE
Move DNS

### ISSUE THREAD

**Issue by cbcunc** [hydroshare/hydroshare#5350]
Ask ACIS how to move DNS

**Comment by cbcunc** [comment]
Name of ACIS contact: Doug Taber.

**Comment by martinseul** [comment]
Please see below:
First Name: Martin
Last Name: Seul
Company Name: CUAHSI
Job Title: Technical Director
Address: 1167 Mass Ave, Suite 419
City: Arlington
State/Province: MA
ZIP/Postal Code: 02476
Country: USA
Phone Number: (339) 221 5400
Fax Number
Email Address: mseul@cuahsi.org

**Comment by cbcunc** [comment]
Contacts have been updated. New registrant needs verification. Either @dtarb or @martinseul should be getting an email?

**Comment by cbcunc** [comment]
New DNS zone created in GCP. Currently being populated.

**Comment by martinseul** [comment]
I did and confirmed

**Comment by cbcunc** [comment]
The DNS entries have been copied from NameCheap to Cloud DNS. It had to be done by hand because NameCheap does not export zone files. Quit a few outdated entries were dropped. Some were suspect and kept out of safety in case the have to do with NameCheap CPanel. The is one problematic entry: the DKIM TXT record. Many people have troubles with this on Cloud DNS. It is longer (414 bytes) than supported by most DNS (255 bytes). It also contains embedded spaces. The common wisdom is to surround with double quotes and divide into two fields. Cloud DNS woudn't accept this. I'm including these resources for research:

https://support.google.com/a/answer/11613097
https://www.mail-tester.com/spf-dkim-check
https://mxtoolbox.com/SuperTool.aspx?action=txt%3adefault._domainkey.hydroshare.org.hydroshare.org&run=toolpage
https://stackoverflow.com/questions/36688278/unable-to-setup-dkim-txt-value-as-dns-record/60291063#comment105060549_36951590

**Comment by martinseul** [comment]
I successfully tied the hydroshare.org domain into the CUAHSI office 365 infrastructure, created 3 distribution lists dev@hydroshare.org, support@hydroshare.org, team@hydroshare.org and they forward to dev@cuahsi.org so we don't miss any mails send but I did not recreate the lists.
