### ISSUE TITLE
Consider a public key login for the iRODS userzone management scripts

### ISSUE THREAD

**Issue by cbcunc** [hydroshare/hydroshare#5354]
**Describe the feature you'd like and what it will do**

Currently, HS uses the following two key pairs in hydroshare/localsettings.py:

```
LINUX_ADMIN_USER_FOR_HS_USER_ZONE
LINUX_ADMIN_USER_PWD_FOR_HS_USER_ZONE
```

HS shells into the userzone ICAT with this user/pwd to run the` hydroshare/irods/create_user.sh` and `hydroshare/irods/delete_user.sh` scripts to create and delete iRODS users in the userzone.

Consider changing this to a public key login.

**Why is this feature important?**
A short description of the importance of this feature and what it will help you achieve.

In GCP, password authentication is disabled by default. This was changed in the GCP userzone to allow a password login so HS would continue to work. However, this is not really desirable.

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...].

It is not ideal to sed `/etc/ssh/sshd_config` in the userzone to allow password logins.

**Additional context**

**Comment by cbcunc** [comment]
I need to move this up in the queue as the number of failed login attempts on GCP due to this are very very high.

**Comment by devincowan** [comment]
https://docs.paramiko.org/en/3.4/api/keys.html

**Comment by devincowan** [comment]
@cbcunc perhaps something like https://github.com/hydroshare/hydroshare/pull/5403
This would require that you place `/home/hsuserproxy/.ssh/key.pem`
