### ISSUE TITLE
Hydroshare modifies files in root hydroshare code directory

### ISSUE THREAD

**Issue by devincowan** [hydroshare/hydroshare#5380]
Issues deploying HS to GKE because the Django application writes to the root code directory

**Comment by devincowan** [comment]
As Scott suggested, perhaps use https://pypi.org/project/watchdog/ or run the tests against a read only filesystem

**Comment by hydrocheck** [comment]
Well captured thanks. I'm not sure what we're writing/modifying or where.

**Comment by devincowan** [comment]
Let's see what tests fail here...
http://ci.hydroshare.org:8080/job/hydroshare-pull-requests/7330/console

**Comment by devincowan** [comment]
Okay here are lists of files that are modified in hydroshare base dir

1. [During build](https://github.com/hydroshare/hydroshare/pull/5419/commits/444dc577000532b42914fc295980f1f355f1b820#diff-67836a8205ffb662ec3bdefc82c5c0dcd53f8c53893d8dbe636c761e86a4545c)
2. [During startup](https://github.com/hydroshare/hydroshare/pull/5419/commits/444dc577000532b42914fc295980f1f355f1b820#diff-ed762195d152d0133c45449a63c92ead629860ed4e89dcb6cf4be4b7a10b6ff9)
3. [During tests](https://github.com/hydroshare/hydroshare/pull/5419/commits/444dc577000532b42914fc295980f1f355f1b820#diff-f924b87aa702ad2d0c4ae8d449aa03bb61b44666031c80b77f4437b57b8f6221)

We only care about files modified during startup and tests...?

**Comment by sblack-usu** [comment]
I used watchmedo to monitor `/home/hydro/hydroshare` on beta1 during a `hsctl restart`. I used a venv to install watchmedo and had to increase the max_user_watches with intoify https://unix.stackexchange.com/questions/13751/kernel-inotify-watch-limit-reached
```bash
watchmedo shell-command --recursive --verbose /home/hydro/hydroshare/ >> restart.log
```
[hsctl_restart.log](https://github.com/hydroshare/hydroshare/files/14746777/hsctl_restart.log)

**Comment by sblack-usu** [comment]
3244 total offenses

1355 - hs_discover/node_modules
58 - all other hs_discover

343 - nginx

That is only the beginning. Some of this chatter may be only from hsctl deployments and may not be relevant to a kubernetes deployment.

**Comment by sblack-usu** [comment]
301 offenses from __pycache__. We should be able to solve those with [PYTHONPYCACHEPREFIX](https://docs.python.org/3/using/cmdline.html#envvar-PYTHONPYCACHEPREFIX)

**Comment by sblack-usu** [comment]
The major offender is a `chown -R hydro-service:storage-hydro /hydroshare` in `init_hydroshare`. We should be able to filter out all of that chatter. The gcp deployment is not using that.

**Comment by devincowan** [comment]
Thanks @sblack-usu 
This hs_discover PR
https://github.com/hydroshare/hydroshare/pull/5427
should take care of all the modified files within `/home/hydro/hydroshare/hs_discover/node_modules`
But some of the others not related to npm build, but related to python collection of static files etc (for example `modified directory /home/hydro/hydroshare/hs_discover/static`) might be problematic still...

**Comment by sblack-usu** [comment]
I think we have too much noise on beta1 that are related to deployment and not operation.  I wonder if we should get watchdog going for the gcp deploy and run the QA tests to identify offenses coming only from operations.

**Comment by devincowan** [comment]
@sblack-usu that's a pretty good idea -- a lot of what we are seeing is likely not applicable to the gcp deployment

Another approach:
had some time while my son was playing to make an action so that we can run QA tests against beta on-demand
https://github.com/CUAHSI/QA-AutomationEngine/actions/runs/8424865959/job/23069719023
I think running these while sniffing the /hydroshare dir on beta will be our best bet at catching modifications conducted during HS user interactions

(or doing the same targeting the GCP deploy if we can figure out how to get watchdog running in the gcp pod...)

**Comment by sblack-usu** [comment]
Awesome @devincowan ! I think running the QA tests while watchdog is listening is the way to go and running them ourselves (thanks to your action) will be easier to do on beta than gcp.  We can wait until QA testing is done and then work on this.

**Comment by devincowan** [comment]
looks like the QA tests aren't failing due to anything particular about my GH action -- they fail when I try to run them locally as well. Might just be that some of the dependencies aren't pinned. We will have to ask Neal

**Comment by sblack-usu** [comment]
The static directory is mounted to /home/hydro/hydroshare/static.  This directory needs to be moved out of the code directory.

**Comment by sblack-usu** [comment]
After running all the QA tests and monitoring the code file system, here are the recommendations I can make.  Fortuntely, the HydroShare application processes are not writing these files. There are 3 cases where files get written to the code directory.
1. [Static files directory](https://docs.djangoproject.com/en/5.0/howto/static-files/) (Used for user/group profile pictures, etc)
2.[ Pyc files ](https://docs.python.org/3/using/cmdline.html#envvar-PYTHONPYCACHEPREFIX)(compiled python files)
3. [logs](https://docs.djangoproject.com/en/3.2/topics/logging/) (django application logs)

There is also the node_moduels/ directory for discover, but I understand that shouldn't be an issue any longer as the image is built before code deploy.

All 3 of these can be configured to write the files to a different location. I'm not going to make any changes directly to the RENCI deployments because it likely does not translate directly to the GCP deploy. The links show how we can configure these files to write to a different directory.
