### ISSUE TITLE
Groups photo icon fails to update

### ISSUE THREAD

**Issue by ClaraCogswell** [hydroshare/hydroshare#5382]
**Description of the bug**
When uploading a photo to be the icon of a group, the upload it possible but the changes are not reflected when the changes are saved. 

Steps to reproduce the bug:
1. Go to [https://www.hydroshare.org/group/250]
2. Click on 'Owner settings 
3. Scroll down to add a photo
4. attempt upload, see failure

**Expected behavior**
should upload the photo and display it on the landing page. 

**Additional information**
Bug noticed by Dan Ames

**Comment by devincowan** [comment]
Tested locally, works as expected
![image](https://github.com/hydroshare/hydroshare/assets/17934193/9a9e1a36-1bb3-4d2a-b269-cd36397eb740)

Looking into explanation...

**Comment by devincowan** [comment]
From what I can tell, group images (along with community images) were broken when we upgraded our STATIC settings in 2.0 release
https://github.com/hydroshare/hydroshare/issues/4738

**Comment by devincowan** [comment]
scratch that, this is an undocumented issue with [sorl-thumbnail](https://sorl-thumbnail.readthedocs.io/en/latest/requirements.html#image-library) due to Pillow version.

Dropping Pillow back to 9.3.0
https://github.com/hydroshare/hs_docker_base/commit/7a6c5814f1117bb935b3c2569b93167470ec140b
