### ISSUE TITLE
Word wrap in Group Purpose text

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#5393]
**Description of the bug**
I created a Group in HydroShare.  There is a problem with the word wrap in the purpose text as displayed
![image](https://github.com/hydroshare/hydroshare/assets/3456833/11353694-f76c-4dc1-b995-1c71b2b48e3c)

**Comment by devincowan** [comment]
verified resolved by 2.13.4 release
https://www.hydroshare.org/group/255
