### ISSUE TITLE
Add "Published" date in resource header

### ISSUE THREAD

**Issue by devincowan** [hydroshare/hydroshare#5410]
![image](https://github.com/hydroshare/hydroshare/assets/17934193/6c60fd53-eaa2-48c9-845e-21ee9586c446)
Add "Published" date in the left header, for published resources

In the special case that the last updated date is after the publication date, we add "(metadata update)"

**Additional context**
hs v 2.13.3

**Comment by dtarb** [comment]
Here are my suggestions for the implementation of this
![image](https://github.com/hydroshare/hydroshare/assets/3456833/0b53d5c8-ee8d-4cd7-82d4-8cdb3767b6fb)
