### ISSUE TITLE
Use Keycloak password for the API

### ISSUE THREAD

**Issue by sblack-usu** [hydroshare/hydroshare#5415]
**Describe the feature you'd like and what it will do**
With the introduction of Keycloak users now manage two different passwords, their application password in Keycloak and their API password in Django. New users have to manually create an API password. Existing users have an API password that matches their Keycloak password (until they change their Keycloak password).  I'd like to update HydroShare with an authentication middleware for the REST API to authentication against Keycloak and effectively merge these passwords.

**Why is this feature important?**
We can dissolve all the confusion around the separation of a application and api passwords by only using the keycloak password.

**Is your feature request related to a problem? Please describe.**
New users have to create an API password manually. Existing users have to manage their API password separately from their Application password, which creates confusion.

**Additional context**
Such middleware already exists that we can use for examples. https://github.com/urbanplatform/django-keycloak-auth/blob/master/src/django_keycloak/middleware.py#L38

**Comment by sblack-usu** [comment]
@ClaraCogswell - we were able to figure out a way to use the keycloak password for API basic authentication. This means we no longer need the concept of an API password and API authentication will behave as it did before the introduction of Keycloak.

**Comment by devincowan** [comment]
resolved via https://github.com/hydroshare/hydroshare/pull/5416 will go out with [2.13.5](https://github.com/hydroshare/hydroshare/issues/5398)
