### ISSUE TITLE
Export Discoverable Collection Ids

### ISSUE THREAD

**Issue by sblack-usu** [hydroshare/hydroshare#5432]
**Describe the feature you'd like and what it will do**
Keep a mongo collection up to date with the current set of discoverable resources. This will be used for managing discoverable HydroShare resources in an external collections up to date. Applications such as CZNet and I-GUIDE may listen to the changestream of the resulting collection to know when to refresh the resource metadata in their discovery collection.

**Why is this feature important?**
We will be using this feature for creating an external Discovery Application that allows a completely separate deployment of discovery.

**Comment by devincowan** [comment]
resolved by https://github.com/hydroshare/hydroshare/pull/5467
