### ISSUE TITLE
Create "Model Package" button for Model Instance resource types

### ISSUE THREAD

**Issue by mohamedmorsy** [hydroshare/hydroshare#545]
Create this button beside the download button "Download All Content as Zipped Bagit Archive" to download all the Model Instance resource content beside the Model Program resource content that is used for executing this Model Instance resource as one package.

**Comment by jsadler2** [comment]
This likely involves
1. Check if the model instance is "executed by" a model program. If so, show a "download model package" button
2. When button is clicked get the two resource bags via the rest api getResource method
3. Zip them together
4. Download

**Comment by goodalljl** [comment]
@mohamedmorsy This has been open for a while. Should we put it on the blackburner or is it still something you would like to work on?

**Comment by mohamedmorsy** [comment]
@goodalljl I think we should put it on the blackburner for now.

**Comment by Castronova** [comment]
@goodalljl close or act on if needed

**Comment by imanmaghami** [comment]
@goodalljl Do we still need to have this "Model Package" button given that in the new model design, the model program aggregation and the model instance aggregation(s) being linked to it must sit in the same composite resource? 

In the new design, the user can use "Download All Content as Zipped Bagit Archive", and download all the model instance aggregation(s) and model program aggregation(s) included in the composite resource. I think the typical practice would be that the users include only one model program and associated model instances in the same composite resource (although they are not prevented from putting several model aggregations in the same composite resource or putting model instance aggregations that are not to linked to any model program or are linked to different model programs). 

Overall, I think this probably makes having a "Model Package" button less needed compared to the previous design where the model instance and model program used to live in separate resources. Again, "Download All Content as Zipped Bagit Archive" in the new design would not act the same as "Model Package" button feature request and if you think it is something that we should have, we can keep this issue and add the "Model Package" button later on.

**Comment by goodalljl** [comment]
No we don’t need it for the reasons you described. Please close it. Thanks!
