### ISSUE TITLE
Adjust The Model Program "ModelWebpage" metadata element 

### ISSUE THREAD

**Issue by mohamedmorsy** [hydroshare/hydroshare#547]
Adjust The Model Program "ModelWebpage" metadata element (Website in "Resource specific" landing page) to be URL link:

![image](https://cloud.githubusercontent.com/assets/5543781/8945416/3ac680e4-3555-11e5-8b83-f1f433db41e2.png)

**Comment by Castronova** [comment]
This also applies to *user manual* and all other files.

**Comment by mohamedmorsy** [comment]
@Castronova Could we change also the metadata term "modelProgramURL" to modelProgramIdentifier" to be homogeneous with the metadata term "hydroShareIdentifier". Also this should be changed in https://www.hydroshare.org/terms/ModelProgramURL/#ModelProgramURL.

**Comment by Castronova** [comment]
@mohamedmorsy The **modelProgramURL** corresponds with the **program_website** variable in the models.py, so I'm not sure that it should be renamed to **modelProgramIdentifier**.  However, I agree that all of the hsterms for the Model Program must match the image above.
