### ISSUE TITLE
Link the SWAT Model Instance resource type with the Model Program resource type

### ISSUE THREAD

**Issue by mohamedmorsy** [hydroshare/hydroshare#548]

**Comment by Castronova** [comment]
Getting an error when implementing model_program foreign key relationship, see: http://stackoverflow.com/questions/26955319/django-reverse-accessor-clashes 

Should SwatModelInstance be deriving from ModelInstance?  This might solve the problem,

**Comment by Castronova** [comment]
fixed using **related_name**: `model_program_fk = models.ForeignKey('hs_model_program.ModelProgramResource', null=True, blank=True,related_name='swatmodelinstance')`

Still having trouble saving foreign keys in the swat_model_instance.

**Comment by Castronova** [comment]
Implemented model program foreign key relationship in swat model instance.  Modified the fk definition in model instance. 1833dbda7df4c753369a9f37615298283d7aa853

Foreign Key relationship fails when saving.
