### ISSUE TITLE
Unable to download FEMA Harvey Flood Depth file

### ISSUE THREAD

**Issue by dbaolsu** [hydroshare/hydroshare#5566]
I'm not able to download the file 'Harvey_Depths_3m_Final.gdb' from https://www.hydroshare.org/resource/e8768f4cb4d5478a96d2b1cbd00d9e85/
It terminated at around 30% of the download.

**Comment by devincowan** [comment]
Thanks for letting us know @dbaolsu 
Confirming that I also attempted just now and it failed around 30% as well.

**Comment by sblack-usu** [comment]
I attempted yesterday as well and was able to download the full file. I extracted the zip and confirmed the contents inside.

**Comment by devincowan** [comment]
Good to know that Scott succeeded. I tried again today and got to ~75% before it failed.

**Comment by devincowan** [comment]
Perhaps related to recent infra migration. I am researching...

**Comment by devincowan** [comment]
In my attempts, here is the sequence
request to https://www.hydroshare.org/resource/e8768f4cb4d5478a96d2b1cbd00d9e85/data/contents/Harvey_Depths_3m_Final.gdb.zip gets 301 redirect
```
HTTP/3 301 
server: gunicorn
date: Fri, 02 Aug 2024 14:50:02 GMT
content-type: text/html; charset=utf-8
location: /resource/e8768f4cb4d5478a96d2b1cbd00d9e85/data/contents/Harvey_Depths_3m_Final.gdb.zip/
content-length: 0
vary: Origin, Accept-Language
content-language: en
via: 1.1 google
alt-svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
```
Then https://www.hydroshare.org/resource/e8768f4cb4d5478a96d2b1cbd00d9e85/data/contents/Harvey_Depths_3m_Final.gdb.zip/ returns a 302
```
HTTP/3 302 
server: gunicorn
date: Fri, 02 Aug 2024 14:50:02 GMT
content-type: text/html; charset=utf-8
location: /django_irods/rest_download/e8768f4cb4d5478a96d2b1cbd00d9e85/data/contents/Harvey_Depths_3m_Final.gdb.zip/?url_download=False&zipped=False&aggregation=False
vary: Accept, Origin, Accept-Language, Cookie
allow: OPTIONS, GET
content-length: 0
content-language: en
via: 1.1 google
alt-svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
```
Then request to https://www.hydroshare.org/django_irods/rest_download/e8768f4cb4d5478a96d2b1cbd00d9e85/data/contents/Harvey_Depths_3m_Final.gdb.zip/?url_download=False&zipped=False&aggregation=False
```
HTTP/3 200 
server: gunicorn
date: Fri, 02 Aug 2024 14:50:08 GMT
content-type: application/zip
content-disposition: attachment; filename="Harvey_Depths_3m_Final.gdb.zip"
content-length: 39191039562
vary: Accept, Origin, Accept-Language, Cookie
allow: OPTIONS, GET
content-language: en
via: 1.1 google
alt-svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
```
made it to 27GB for me
<img width="1790" alt="image" src="https://github.com/user-attachments/assets/f37b1b55-e213-4664-a10d-2f32710ac160">

**Comment by sblack-usu** [comment]
Downloads are accomplished with an iget, redirect to stdout and packaging that in the fileresponse.
https://github.com/hydroshare/hydroshare/blob/d9fb3d3fe964949c8e0e76884c4cb15bba6f5fe3/django_irods/views.py#L323C5-L335

This makes me think a timeout, rather than disk space, is the issue. The timeout could be in the iget or it could be somewhere with serving the response.

**Comment by devincowan** [comment]
@sblack-usu when we run 
```
    proc = session.run_safe('iget', None, irods_output_path, *options)
    response = FileResponse(proc.stdout, content_type=mtype)
```
The entire content of the file doesn't have to be held in memory, right?

I'm just checking. It doesn't look like the HS container has exceeded memory limits at any rate...
![image](https://github.com/user-attachments/assets/33ebba46-ca05-4c6e-ad0a-e61759127753)

**Comment by sblack-usu** [comment]
I'm not familiar enough with FileResponse to confidently answer that. It doesn't appear to read the whole file into memory. It looks like a streaming response, so I wouldn't think it is consuming much memory and your investigation supports that.

**Comment by devincowan** [comment]
I discovered that my failed download attempts were potentially due to space limitations on my local machine.
In this case my browser (Firefox) was failing with an ambiguous NS_BIND error and it was difficult for me to see that it was actually due to my disk filling up.

@dbaolsu can you confirm that this isn't the case for you (that you have adequate space on your system)?

**Comment by dbaolsu** [comment]
Hi all,
Thanks for looking into this issue. I confirm that this is not due to space limitations. I tried it again, but it still failed.
However, I successfully downloaded it from the TACC UTexas website, as listed in the second reference on https://www.hydroshare.org/resource/165e2c3e335d40949dbf501c97827837

**Comment by devincowan** [comment]
Thanks @dbaolsu we are continuing to investigate.

**Comment by devincowan** [comment]
One potential option is to enable range headers
https://devdoc.net/web/developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Ranges.html
so that if download fails, at lease it can be resumed
