### ISSUE TITLE
Add Hint for "more options" in content manager

### ISSUE THREAD

**Issue by martinseul** [hydroshare/hydroshare#5585]
**Describe the feature you'd like and what it will do**
Users are often unaware that there are more options available if you "rightclick" on a file in the content browser. This feature would add a hint on "mouseover" to tell people that they can right click to see "more options"

**Why is this feature important?**
this will improve usability and help users awareness

**Is your feature request related to a problem? Please describe.**
users don't know that there are more options

**Comment by MSDrao** [comment]
This is how the "more options" appear when you hover over the content files. @ClaraCogswell @dtarb 
![Image](https://github.com/user-attachments/assets/dfb46dc8-dd5d-40c8-a28f-0eac08d0f403)

**Comment by ClaraCogswell** [comment]
This looks good to me

**Comment by dtarb** [comment]
Perfect.Thanks.
