### ISSUE TITLE
Allow multiple file selection in iRODS browser

### ISSUE THREAD

**Issue by ironfroggy** [hydroshare/hydroshare#560]
Allow selecting multiple files to create a new resource with from an iRODS connection.

**Comment by selimnairb** [comment]
Also allow for recursive inclusion of the contents of selected directories.

**Comment by dtarb** [comment]
Recursive inclusion of contents of directories, means we will need to allow directory structures in resources and develop the capability to view/manage them on the interface.  All useful things, but they do extend the scope.

**Comment by dtarb** [comment]
Tested on Alpha.
