### ISSUE TITLE
Cannot upload file to resource that exists on iRODS and and not the hydroshare database

### ISSUE THREAD

**Issue by sblack-usu** [hydroshare/hydroshare#5605]
**Description of the bug**
Somehow hydrosahre can get in a state where the file exists on irods but a reference to the file does not exist in the database. The user does not see the file and tries to upload the file again, which causes the failure.

Steps to reproduce the bug:
1. Get the database and irods in this state
2. Upload the file
3. See error

**Expected behavior**
The hydroshare resource should be able to detect missing file references and self heal.

**Additional information**
This could probably be done with s simple check on file listing as the irods directory is listed as well as the database is queried every time. Instead of filtering out files that are on irods but not in our database, add the file(s) to the database.

**Comment by devincowan** [comment]
@sblack-usu Reopening because while [5613](https://github.com/hydroshare/hydroshare/pull/5613) resolved the error upon attempting an upload, it doesn't seem like the resource "self heals" when there is a file in irods that isn't in Django.

**Comment by sblack-usu** [comment]
@devincowan - Can I get your reproduction steps? I just tried this on beta and it is working.
```
>>> from hs_core.models import BaseResource
>>> res = BaseResource.objects.get(short_id="1aedbe999c8045cabba3bf470b1e9ee9")
>>> res.files.count()
1
>>> istorage = res.get_irods_storage()
>>> import os
>>> src = os.path.join(res.file_path, 'Screenshot_2024-11-01_at_9.27.55AM.png')
>>> dst = os.path.join(res.file_path, 'Screenshot_2024-11-01_copy.png')
>>> istorage.listdir(res.file_path)
([], ['Screenshot_2024-11-01_at_9.27.55AM.png'], ['51776'])
>>> istorage.copyFiles(src, dst)
>>> istorage.listdir(res.file_path)
([], ['Screenshot_2024-11-01_at_9.27.55AM.png', 'Screenshot_2024-11-01_copy.png'], ['51776', '51776'])
>>> res.files.count()
2
```
I did a refresh on the resource landing page just before the doing the last `res.files.count()`. Keep in mind that if you delete a ResourceFile through python it also deletes the file on irods. Just mentioning that because I made that mistake initially.

**Comment by devincowan** [comment]
Nice @sblack-usu yes you're right, I had deleted from the python shell. Thanks for verifying!
