### ISSUE TITLE
Avoid display of unsecure content

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#563]
On internet explorer the following message appears which suggests that there is unsecure content on the hydroshare pages.  We should avoid this if possible
![untitled](https://cloud.githubusercontent.com/assets/3456833/9288847/b6478774-4318-11e5-9ae8-19ce1ddc198e.png)

**Comment by hyi** [comment]
@dtarb I have tested www.hydroshare.org with IE version 11 and this unsecure content issue does not occur any more with https secure HydroShare server. Could you test it again and close if the issue goes away now?

**Comment by dtarb** [comment]
On Internet Explorer 11 for me I still get the warning message above just going to http://www.hydroshare.org. I do not know how to figure out what content is triggering this, but since it happens on every page the hunch is that it is something in the header or footer.

**Comment by ironfroggy** [comment]
@dtarb you should be getting redirected to the HTTPS version. Does that happen for you when visiting via http://www.hydroshare.org/?

**Comment by rayi113** [comment]
@dtarb @ironfroggy I found this text on http://answers.microsoft.com/en-us/ie/forum/ie9-windows_7/turn-off-only-secure-content-is-displayed/4e0213cd-653f-42eb-8b52-96aa5ed15068?auth=1 at the bottom:

"...It turns out that the unsecure content is from another website. You can see which one is by pressing F12 and then select console and refresh the page. You will than see the http:// sites that violate the SSL connection. Add them to trusted sites too (don't forget to uncheck require server verification (https) for all sites in this zone)"

The above process identified these sites as the culprit:
HTTPS security is compromised by http://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic

http://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic

**Comment by hyi** [comment]
@dtarb which IE version did you use? I am using IE v11 and when I enter http://www.hydroshare.org, it is redirected automatically to https://www.hydroshare.org and I don't get the unsecure content info at all.

**Comment by dtarb** [comment]
Version 11.0.22.  Yes I am getting redirected to https.  The unsecure content warning appears if I start directly from https, or start from http and am redirected.  It looks like @rayi113 has tracked down the cause.  We may need to figure out whether there is a secure equivalent for the google fonts we are using, or whether we should change the style to remove the dependency on this font.  I know this is quite a small thing, and hate it to be consuming time, but I do not think it is reasonable to expect all our users to change their security settings to add trusted sites.

![untitled](https://cloud.githubusercontent.com/assets/3456833/9526286/b013011c-4ca5-11e5-9799-0b91e0420c74.png)

**Comment by rayi113** [comment]
@hyi @dtarb It looks like one can substitute in https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic   (i.e. https vresion of http://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic) and it still works.  It looks like it's in theme/templates/base.html

**Comment by hyi** [comment]
@rayi113 @dtarb After checking following recommended security settings for my IE browser, I can reproduce this issue. I made the change following @rayi113's suggestion with changing http to https for google api font url in base.html, and tested the change on sandbox to make sure this change indeed fixed this issue. Created a PR which once merged in, should fix this issue.

**Comment by mjstealey** [comment]
Question - does this cause any issue going the other way?

Right now you're testing on a site using https, however the development environment does not have to use https, so how does having https references effect the development environment running on http?

There was a similar issue with the recaptcha link and I wound up just switching case based on a [pre-flight](https://github.com/hydroshare/hydroshare/blob/develop/hsctl#L95) check for SSL.

Reference: https://github.com/hydroshare/hydroshare/blob/develop/hsctl#L23

USE_SSL = false --> HTTP_RECAPTCHA
USE_SSL = true --> HTTPS_RECAPTCHA

**Comment by ironfroggy** [comment]
If we get warnings as developers we can ignore them.

If we want to avoid that you can use schema-less URLs like //google.com/path/to/fonts omitting either http: or https: entirely.

**Comment by hyi** [comment]
@mjstealey I did test in my local dev with USE_SSL set to false, and I don't see warnings using IE going to the dev server. I am not sure how to self-generate hs_certs, so I did not test in my local dev with USE_SSL set to True. Could you make this simple change in base.html and see whether you see any issues in our local development environment? If you see any issues, I can try to go with what @ironfroggy suggested and test to see whether that could resolve issues on both local dev and production env.

**Comment by mjstealey** [comment]
@hyi - If you're using the hydrodev VM you'd just need to set both USE_NGINX and USE_SSL to true.

The self-signed certs for hydrodev are already there and will be installed on a `./hsctl restart`

**Comment by hyi** [comment]
@mjstealey Just tested it our in my local dev env with both USE_NGINX and USE_SSL set to True. I got an expected certificate invalid message, and after confirming exceptions, it takes me to hydroshare website without additional warnings. So it appears this change will not break anything in both local dev env and production env.

**Comment by hyi** [comment]
@mjstealey I did test it out both from firefox web browser within the VM and from IE outside the VM using bridged network, so it should cover both use cases.

**Comment by hyi** [comment]
@dtarb I tested dev.hydroshare.org on IE and don't see the warning any more. Marking it as ready for testing.

**Comment by dtarb** [comment]
Tested on dev and satisfied issue seems resolved.
