### ISSUE TITLE
Allow resource owners to change resource discoverable property from resource landing page

### ISSUE THREAD

**Issue by pkdash** [hydroshare/hydroshare#564]
If resource discoverable property is set to true, anyone can view resource metadata but not the content files. On the resource landing page this functionality can be implemented similar to how we do the public/private setting for the resource.

**Comment by ironfroggy** [comment]
If you suggest having two different toggles, for "Public / Private" and "Discoverable / Not Discoverable"? I think this pair of toggles would be confusing. Are all combinations valid? Does it make sense to allow a Discoverable Private state for a resource?

**Comment by pkdash** [comment]
I assume if a resource is 'public' it is automatically 'discoverable'. The only time a resource owner would set a resource to be 'discoverable' if the resource is 'private'. May be @horsburgh  can explain the use case for this feature.

**Comment by dtarb** [comment]
The use case for discoverable but private is where the user wants to advertise the existence of the resource, but only allow access based on request/negotiation.  

Only 3 of the 4 combinations are allowed.  Public + not discoverable is not allowed.

We might consider a single toggle with three options for the interface
 * Private.  Internally this would be private +  not discoverable
 * Discoverable (metadata is public but data protected).  Internally this is private + discoverable.  For the purposes of HydroShare data is only the content files in iRODS.  Everything else, including all information in Django tables, is metadata and thus public.
 * Public.  Internally this would be public + discoverable.

**Comment by pkdash** [comment]
Thanks @dtarb for explaining the use case.

**Comment by dtarb** [comment]
This is actually an editing function available only to users with privileges over the resource.  Perhaps all editing functions should be moved to the editing page and the landing page be identical for anyone with access to the resource.

**Comment by horsburgh** [comment]
I would like to move to a model where any and all editing is done in edit view and not on the main resource landing page.

**Comment by mauriel133** [comment]
Are we moving all editing functions to the edit page. If so, should I move these as well?:
- Add file
- Sign in iRODS...
- Delete file icon

**Comment by mauriel133** [comment]
@pkdash, all is left to do in this issue is to make discoverable resources appear in "My Resources" page and make them accessible. The template should respond to the property and render the corresponding data and metadata. Could you help me get this done?

**Comment by pkdash** [comment]
@mauriel133 Sure.

**Comment by mauriel133** [comment]
When a resource is created and all the required information has been filled in, there is a message that says "sufficient to make public". Does this mean that a resource should be private by default after creation?

**Comment by dtarb** [comment]
Working in 1.6.  Closing.
