### ISSUE TITLE
Zombie TaskNotification and rapid pings to hsapi/_internal/get_task

### ISSUE THREAD

**Issue by devincowan** [hydroshare/hydroshare#5648]
We only clear old tasks once per week
https://github.com/hydroshare/hydroshare/blob/2.15.9/hs_core/tasks.py#L1236-L1241
we should do it more often

Also
https://github.com/hydroshare/hydroshare/blob/2.15.9/theme/templates/includes/navbar.html#L618
we ping every second, let's make it 10

**Comment by devincowan** [comment]
from @sblack-usu :
```
We could consider making more frequent pings with younger tasks and increase the length of time between pings as the task becomes older. But I think just knocking it down from 1 second to 10 seconds would be a good start to solving this.
```

**Comment by sblack-usu** [comment]
Bump this to 10 seconds https://github.com/hydroshare/hydroshare/blob/develop/theme/templates/includes/navbar.html#L497

**Comment by devincowan** [comment]
related to 
https://github.com/hydroshare/hydroshare/issues/5558
and
https://github.com/hydroshare/hydroshare/issues/5159

**Comment by devincowan** [comment]
this went out as https://github.com/hydroshare/hydroshare/releases/tag/2.15.9.1
