### ISSUE TITLE
REST API fails when uploading NetcdfResource type

### ISSUE THREAD

**Issue by shawncrawley** [hydroshare/hydroshare#569]
When running the following, the api gets back a 500 Internal Server error. @selimnairb and I troubleshooted a bit and found out that it was the resource type 'rtype = "NetcdfResource" that caused it to fail. When using "GenericResource" it worked fine. Here is the code:

```
from hs_restclient import HydroShare, HydroShareAuthBasic
auth = HydroShareAuthBasic(username='whoever', password='******')
hs = HydroShare(auth=auth, hostname='dev.hydroshare.org', use_https=True)
abstract = 'My abstract'
title = 'My resource'
keywords = ('my keyword 1', 'my keyword 2')
rtype = 'NetcdfResource'
fpath = '/home/alan/Downloads/-nfiehydroZone-home-public-usgs-national-2015-08-19-national_2015-08-19.nc'
resource_id = hs.createResource(rtype, title, resource_file=fpath, keywords=keywords, abstract=abstract)
```

I have emailed @selimnairb the netCDF file.

**Comment by selimnairb** [comment]
@shawncrawley Can you test your previously failing code on alpha.hydroshare.org?  If it's working, please close this issue.  Thanks.

**Comment by shawncrawley** [comment]
@selimnairb It still fails with a 500 Internal Server Error. The "Generic"
is still working like a charm, though.

**Comment by selimnairb** [comment]
@shawncrawley I just tested this on alpha.hydroshare.org and am able to create a NetCDF resource.  Here is my code:

    from hs_restclient import HydroShare, HydroShareAuthBasic
    auth = HydroShareAuthBasic(username='whoever', password='******')
    hs = HydroShare(auth=auth, hostname='alpha.hydroshare.org', use_https=True)
    abstract = 'My abstract'
    title = 'My resource'
    keywords = ('my keyword 1', 'my keyword 2')
    rtype = 'NetcdfResource'
    fpath = '-nfiehydroZone-home-public-usgs-national-2015-08-19-national_2015-08-19.nc'
resource_id = hs.createResource(rtype, title, resource_file=fpath, keywords=keywords, abstract=abstract)

**Comment by shawncrawley** [comment]
@selimnairb It works for me when I upload the same resource that you are -
the 9MB one. However when I try to upload the 213MB file, it actually
returns a 400 Bad Request error. The weird part is that when I check
hydroshare, the file is there and appears to have been uploaded correctly.
I'm not sure what to make of that.

**Comment by selimnairb** [comment]
@shawncrawley This is running against alpha?  Can you create a resource with the same file, without error, when going through the HTML interface?

**Comment by shawncrawley** [comment]
@selimnairb Yes, it is running against alpha. And yes, I was able to create
a resource of the same file, without error, when going through the HTML
interface. But yeah, I still get a 400 Bad Request error through the REST
API but the file still appears in HydroShare as if no error were received.

**Comment by selimnairb** [comment]
@shawncrawley Can you verify whether this is still happening, in particular against dev?

**Comment by shawncrawley** [comment]
@slimnairb The tests were done against dev.hydroshare.org as requested. It
seems nothing has changed. I tested every combination of a 9MB or 213MB
file with a Generic or NetCDF resource type. All worked perfectly except
the 213MB NetCDF combination, which still "worked" (uploaded and was
accessible on HydroShare) but once again had the 400 Bad Request Error
returned. Sorry to bear bad news.

**Comment by selimnairb** [comment]
@shawncrawley thanks for testing. I'll look at this after the 1.6.0 deploy.

**Comment by pkdash** [comment]
@shawncrawley Should this be closed?
