### ISSUE TITLE
User Access to Hydroshare "terms" page

### ISSUE THREAD

**Issue by mohamedmorsy** [hydroshare/hydroshare#574]
This page was created to resolve the URLs of the core metadata term "type", and the hsterms namespace in metadata xml document (resourcemetadata.xml) (related to #171). It could be great if this page could be also accessed by the user through the website under the following path:

SUPPORT/Get started  using Hydroshare/What is a resource?

By this access the user can understand more about the different resource types and their specific metadata. This page contains the definition of each resource type and the related specific metadata terms.

**Comment by pkdash** [comment]
@mohamedmorsy See if this can be closed.
