### ISSUE TITLE
SWAT Model Instance creating failure

### ISSUE THREAD

**Issue by yirugi** [hydroshare/hydroshare#575]
+ When I tried to create new SWAT Model Instance resource with input file, it produced this error message :

Failed to Create Resource:column hs_swat_modelinstance_modelinput.warm_up_period does not exist LINE 1: ...swat_modelinstance_modelinput"."content_type_id", "hs_swat_m... ^

+ It was possible to create the resource without input file, but it also failed to show the resource information.
https://alpha.hydroshare.org/resource/0788a00a979747618f769737ce2029f8/

ProgrammingError at /resource/0788a00a979747618f769737ce2029f8/
column hs_swat_modelinstance_modelinput.warm_up_period does not exist
LINE 1: ...swat_modelinstance_modelinput"."content_type_id", "hs_swat_m...

**Comment by selimnairb** [comment]
@yirugi What HydroShare instance are you using, alpha.hydroshare.org?  This sounds like migrations are out of sync.

**Comment by vmmerwade** [comment]
I also get the same error message as yirugi when I try to create SWAT Model Instance Resource. "Failed to Create Resource:column hs_swat_modelinstance_modelinput.warm_up_period does not exist LINE 1: ...swat_modelinstance_modelinput"."content_type_id", "hs_swat_m... ^ "

**Comment by selimnairb** [comment]
@yirugi @vmmerwade  What HydroShare instance are you using, alpha.hydroshare.org?

**Comment by mohamedmorsy** [comment]
@selimnairb Yes, I got the same error by using alpha.hydroshare.org to create SWAT Model Instance. There is a problem with the migrations and Michael is working on that.

**Comment by vmmerwade** [comment]
i tried this on alpha.hydroshare.org

**Comment by mjstealey** [comment]
Code has been update on https://alpha.hydroshare.org, please retry.

**Comment by yirugi** [comment]
I think the problem is solved now.

**Comment by mohamedmorsy** [comment]
I created the following SWAT Model Instance resource on alpha:

 http://alpha.hydroshare.org/resource/066e210f70124b87ad840c245adb8313

Everything works as expected. Thanks Michael @mjstealey

**Comment by mjstealey** [comment]
Fixed
