### ISSUE TITLE
Temporal frame drop box limited to 10 years for Model Instance Resource

### ISSUE THREAD

**Issue by vmmerwade** [hydroshare/hydroshare#579]
When I try to assign the start date for a model, the combo box only shows 2005-2015. I cannot select 2000 from this menu. When i select 2005, then the box gets populated from 1995 - 2005. I wonder if it is possible to also have the user type the year. Same with end year combo box.

**Comment by mohamedmorsy** [comment]
This bug is general bug for all of the resource types

**Comment by hyi** [comment]
@vmmerwade it is ready for testing on dev.hydroshare.org. I have tested and it is working properly now. Could you test and close the issue if it works now? Pay special attention to selecting a year less than 1900 when testing to make sure it works properly.

**Comment by hyi** [comment]
I tested again and it works as expected on dev. Closing.
