### ISSUE TITLE
Update Bootstrap

### ISSUE THREAD

**Issue by mauriel133** [hydroshare/hydroshare#591]
I need to update bootstrap to the latest version. The one we are using is too far behind. For this I will need to update JQuery aswell. I'm testing the newer versions in my local environment and everything seems to work fine. 

Would there be any reason not to go ahead with these changes?

**Comment by mjstealey** [comment]
@mauriel133 - This should be fine.
Do you have a specific version or set of files these should be installed from?

If you could put together the install instructions as they would pertain to Ubuntu trusty we could incorporate these as part of the Dockerfile that generates the base image.

**Comment by mauriel133** [comment]
I am not familiar with package installation in Ubuntu, but I tested Bootstrap v3.3.5 and JQuery 1.11.3 by replacing the files in the static folder and updating the references in base.html, 400.html, 503.html, etc.

**Comment by mjstealey** [comment]
@mauriel133 

At the start the hydroshare/static directory is empty and only gets populated by the `collectstatic` call when deploying using the `hsctl` script. So swapping out what is in the that static directory is not the way to go, rather we need to source the module's static directory where these are being initially sourced from prior to being collected.

Try the following and let me know how it goes:

1. Bootstrap - Add bootstrap install into Dockerfile. This should install v3.3.5

- From
```vim
36 # Install test coverage module
37 RUN pip install coverage
38 
39 WORKDIR /home/docker/hydroshare
```
- To
```vim
36 # Install test coverage module
37 RUN pip install coverage
38 RUN npm install bootstrap
39 
40 WORKDIR /home/docker/hydroshare
```

2. JQuery - http://jquery.com/download/

- Not sure as to the best way to do this other than pull it in next to the files that are using it and see what gets collected.
- Once this is worked out you can add the file to a commit and it should then persist.

**Comment by ironfroggy** [comment]
You should be able to include jquery from NPM just like bootstrap.

But, if there are multiple NPM dependencies, they should really be put in a `package.json` defining all them. And they need to be pinned to specific versions, or future updates are going to break Hydroshare unexpectedly.

**Comment by mjstealey** [comment]
updated
