### ISSUE TITLE
SOLR / Haystack / Sphinx

### ISSUE THREAD

**Issue by mjstealey** [hydroshare/hydroshare#594]
Add Haystack and Sphinx to the base image
Add SOLR as a new docker container

**Comment by mjstealey** [comment]
@alvacouch - initial addition of haystack, sphinx and solr in branch: https://github.com/hydroshare/hydroshare/tree/594-solr-haystack-sphinx

Reference for docker SOLR: https://hub.docker.com/r/makuk66/docker-solr/

Right now SOLR is empty, but the admin interface is exposed on port 8983. 
Once you get started I can iterate on automating the initial population mechanisms to get things were we need to be.

**Comment by ironfroggy** [comment]
Haystack should handle all of the population for us when the indexes are defined.

**Comment by ironfroggy** [comment]
Why was this closed? @xuezhaokun is actively working on the first iteration, with my assistance.

**Comment by mjstealey** [comment]
merged into develop - follow on tasks should be added as new issues
