### ISSUE TITLE
Implement functions that allow SWATShare users to import SWAT model instance resources from HydroShare

### ISSUE THREAD

**Issue by lanzh** [hydroshare/hydroshare#595]

**Comment by yirugi** [comment]
- SWATShare users can import SWAT model instance on HydroShare on 'upload' and 'edit' tab.
- HydroShare REST API : 'getResourceList', 'getResource' 
- Authenticating is processed via BASIC auth.
- crossdomain problem (requiring crossdomain.xml file on HydroShare for FLEX), has been solved by using proxy page on MygeoHub (SWATShare side).

**Comment by goodalljl** [comment]
@yirugi Should this issue be put on the backburner? Or is it still an active thing you are working on?

**Comment by yirugi** [comment]
All of the work has been done. I'll close this. Thanks.
