### ISSUE TITLE
Implement functions that allow SWATShare users to export a model as a SWAT model instance resource in HydroShare

### ISSUE THREAD

**Issue by lanzh** [hydroshare/hydroshare#596]

**Comment by yirugi** [comment]
- SWATShare users can export their model instance resources to HydroShare on Model Info Dialog on View tab.
- HydroShare REST API used : 'createResource', 'addResourceFile'
- Authenticating is processed via BASIC auth.

**Comment by yirugi** [comment]
[ Implementation required ]
- Currently, SWAT models are exported as 'Generic Resource' since HydroShare REST API does not support modifying SWAT model instance specific metadata yet.
- REST API that adds / edits SWAT model instance resource specific metadata is required.

**Comment by selimnairb** [comment]
Duplicates #626, closing.
