### ISSUE TITLE
Develop SWATShare component which can be launched using the Hydroshare app URL convention

### ISSUE THREAD

**Issue by lanzh** [hydroshare/hydroshare#597]
The goal is to harmonize the URL and parameters for launching SWAT and launching other apps (ie the SWAT parameter editor app). It was decided that the default app resource in HydroShare will include the following parameters: usr, src, res_id.

**Comment by yirugi** [comment]
This feature has been implemented.

+ Three parameters
 - res_id : resource id
 - src : "hs" (HydroShare)
 - usr : username (currently, not using it)

ex) https://mygeohub.org/groups/water-hub/swatshare?res_id=a36f1cc4c0c64a1fabd33b882dc9b34e&src=hs

**Comment by pkdash** [comment]
@lanzh Should this be closed?

**Comment by goodalljl** [comment]
@yirugi It looks like you are assigned this issue. @pkdash tagged it as "Close me!" Can you please take a look at see if this issue should be closed?

**Comment by yirugi** [comment]
Hi @goodalljl , yes, this can be closed.
Thanks!

**Comment by goodalljl** [comment]
Thanks, @yirugi !
