### ISSUE TITLE
New feature needed in REST API: GetResourceFileList()

### ISSUE THREAD

**Issue by zhiyuli** [hydroshare/hydroshare#601]
This new function should return all resource file names for a resource

**Comment by horsburgh** [comment]
@zhiyuli - the getResourceMap() function should be used for this purpose. The resource map contains the list of all files in the resource (and any relationships that may exist between them). I'm not sure what the implementation status of the getResourceMap() function is.

**Comment by selimnairb** [comment]
@horsburgh I'd like for us to reconsider this.  A REST end point that returns the names/paths of files within a resource as a simple JSON list requires much less work from third-party developers than downloading and then parsing the resource map XML.  In general, I think that we should both provide direct access to the resource map XML, and, for certain compelling use cases (such as a simple file listing) provide easier access to a subset of the data contained in the resource map XML.  Based on recent conversations with @dtarb and others, I think there would be wide support for this approach.  Thoughts?

**Comment by danames** [comment]
+1

**Comment by horsburgh** [comment]
If it simplifies things for some applications, then, sure, write the method.  Seems like it shouldn't be that hard to get the list of files out of the resource map document though.

**Comment by selimnairb** [comment]
@dtarb You mentioned that this might be something @pkdash has time to do; @pkdash can you do this in the near future?

**Comment by selimnairb** [comment]
Need to add support for this end point to hs_restclient before closing this issue.
