### ISSUE TITLE
Generic Resource: 7GB file fails to upload

### ISSUE THREAD

**Issue by rayi113** [hydroshare/hydroshare#603]
As a test in release 1.5.3 I tried uploading a 7GB file and it failed without any error messages.  I choose the 7GB file with resource type "Generic" selected, type in a Title, then select "Create Resource."  The browser shows the %complete in the lower left.  It begins uploading with reasonable speed (~2% per second), It completes to 100%, but then the message changes to "Waiting for www.hydroshare.org..."  This "Waiting for www.hydroshare.org..." message goes away, but the web page remains on the Create Resource page without ever changing (i.e. not the correct behavior upon successful upload of a new Generic resource file).  I then navigated to Resources - Owned by me, and the 7GB file is not there.  I immediately tried uploading a 1.5GB file and it worked fine.  The stated file limit is 10GB, so something is broken.

**Comment by hyi** [comment]
@rayi113 @mjstealey @selimnairb @ironfroggy I downloaded a 7GB file as test file from NFIE zone to my local machine and used that file to test resource creation in my local development environment hoping to debug and pinpoint where it fails in the resource creation process. However, the resource is created successfully with 7GB file transferred to iRODS without issues. It took a long time for Django server to upload the 7GB file, but it succeeded eventually. My local linux development machine only has 6GB memory with 2GB memory free at the time when the file was uploaded, with much less memory than www server, so the memory is not an issue. I am not using nginx and ssl in my local dev env, though, so not sure whether that could be the culprit. I am trying to avoid using www server for debugging, so if this issue can be reproduced in another vm with similar configuration as www, I could try to do some debugging there (e.g., add some logging trying to see where it fails, but the fact that it works through without issues in my local dev env makes me think adding logging might not be useful). Any suggestions on how to debug and find out more on this tricky issue?

**Comment by ironfroggy** [comment]
Do we have any logs from the production server failures of large uploads?

On Tue, Sep 15, 2015 at 11:32 AM, Hong Yi <notifications@github.com> wrote:

> @rayi113 <https://github.com/rayi113> @mjstealey
> <https://github.com/mjstealey> @selimnairb <https://github.com/selimnairb>
> @ironfroggy <https://github.com/ironfroggy> I downloaded a 7GB file as
> test file from NFIE zone to my local machine and used that file to test
> resource creation in my local development environment hoping to debug and
> pinpoint where it fails in the resource creation process. However, the
> resource is created successfully with 7GB file transferred to iRODS without
> issues. It took a long time for Django server to upload the 7GB file, but
> it succeeded eventually. My local linux development machine only has 6GB
> memory with 2GB memory free at the time when the file was uploaded, with
> much less memory than www server, so the memory is not an issue. I am not
> using nginx and ssl in my local dev env, though, so not sure whether that
> could b e the culprit. I am trying to avoid using www server for debugging,
> so if this issue can be reproduced in another vm with similar configuration
> as www, I could try to do some debugging there (e.g., add some logging
> trying to see where it fails, but the fact that it works through without
> issues in my local dev env makes me think adding logging might not be
> useful). Any suggestions on how to debug and find out more on this tricky
> issue?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hydroshare/hydroshare/issues/603#issuecomment-140433714>
> .
>



-- 


*Calvin Spealman*Lead Front-end Developer

calvin@caktusgroup.com <calvin@caktusgroup.com>
www.caktusgroup.com

**Comment by rayi113** [comment]
@rayi113 @mjstealey @selimnairb @ironfroggy RE: I am trying to avoid using www server for debugging, so if this issue can be reproduced in another vm with similar configuration as www, I could try to do some debugging there...  Sounds good.  I defer to @mjstealey  to point to another VM you can use with similar configuration as www.

**Comment by ironfroggy** [comment]
@rayi113 this issue was filed because a large upload already failed on production. Shouldn't we have logs from that failure?

**Comment by mjstealey** [comment]
nginx error log for www

```bash
2015/09/03 17:21:05 [error] 7#7: *693 readv() failed (104: Connection reset by peer) while reading upstream, client: 152.54.9.147, server: www.hydroshare.org, request: "POST /hsapi/_internal/create-resource/do/ HTTP/1.1", upstream: "uwsgi://172.17.0.24:8001", host: "www.hydroshare.org", referrer: "https://www.hydroshare.org/hsapi/_internal/create-resource/"
2015/09/09 15:43:42 [error] 7#7: *24945 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 128.187.97.27, server: www.hydroshare.org, request: "POST /hsapi/_internal/create-ref-time-series/ HTTP/1.1", upstream: "uwsgi://172.17.0.24:8001", host: "www.hydroshare.org", referrer: "https://www.hydroshare.org/hsapi/_internal/create-resource/do/"
2015/09/09 15:59:16 [error] 7#7: *25226 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 128.187.97.27, server: www.hydroshare.org, request: "POST /hsapi/_internal/create-ref-time-series/ HTTP/1.1", upstream: "uwsgi://172.17.0.24:8001", host: "www.hydroshare.org", referrer: "https://www.hydroshare.org/hsapi/_internal/create-resource/do/"
2015/09/09 16:00:59 [error] 7#7: *25226 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 128.187.97.27, server: www.hydroshare.org, request: "POST /hsapi/_internal/create-ref-time-series/ HTTP/1.1", upstream: "uwsgi://172.17.0.24:8001", host: "www.hydroshare.org", referrer: "https://www.hydroshare.org/hsapi/_internal/create-resource/do/"
2015/09/09 16:02:43 [error] 7#7: *25289 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 128.187.97.27, server: www.hydroshare.org, request: "POST /hsapi/_internal/create-ref-time-series/ HTTP/1.1", upstream: "uwsgi://172.17.0.24:8001", host: "www.hydroshare.org", referrer: "https://www.hydroshare.org/hsapi/_internal/create-resource/do/"
2015/09/09 16:05:34 [error] 7#7: *25322 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 128.187.97.27, server: www.hydroshare.org, request: "POST /hsapi/_internal/create-ref-time-series/ HTTP/1.1", upstream: "uwsgi://172.17.0.24:8001", host: "www.hydroshare.org", referrer: "https://www.hydroshare.org/hsapi/_internal/create-resource/do/"
2015/09/09 16:09:04 [error] 7#7: *25374 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 128.187.97.27, server: www.hydroshare.org, request: "GET / HTTP/1.1", upstream: "uwsgi://172.17.0.24:8001", host: "www.hydroshare.org"
2015/09/09 16:10:22 [error] 7#7: *25390 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 128.187.97.27, server: www.hydroshare.org, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://172.17.0.24:8001", host: "www.hydroshare.org"
2015/09/09 16:10:22 [error] 7#7: *25391 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 128.187.97.27, server: www.hydroshare.org, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://172.17.0.24:8001", host: "www.hydroshare.org"
2015/09/09 16:10:23 [error] 7#7: *25396 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 128.187.97.27, server: www.hydroshare.org, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://172.17.0.24:8001", host: "www.hydroshare.org"
2015/09/12 21:52:03 [error] 7#7: *44620 open() "/home/docker/hydroshare/hydroshare/static/media/dhl/info.php" failed (2: No such file or directory), client: 94.23.77.182, server: www.hydroshare.org, request: "GET /media/dhl/info.php HTTP/1.1", host: "www.hydroshare.org"
2015/09/15 17:30:01 [error] 7#7: *57519 readv() failed (104: Connection reset by peer) while reading upstream, client: 152.54.9.147, server: www.hydroshare.org, request: "POST /hsapi/_internal/create-resource/do/ HTTP/1.1", upstream: "uwsgi://172.17.0.24:8001", host: "www.hydroshare.org", referrer: "https://www.hydroshare.org/hsapi/_internal/create-resource/"
2015/09/15 17:35:12 [error] 7#7: *57538 readv() failed (104: Connection reset by peer) while reading upstream, client: 152.54.9.147, server: www.hydroshare.org, request: "POST /hsapi/_internal/create-resource/do/ HTTP/1.1", upstream: "uwsgi://172.17.0.24:8001", host: "www.hydroshare.org", referrer: "https://www.hydroshare.org/hsapi/_internal/create-resource/"
```

Suspect the 1st and last 2 lines to be large file timeouts (internal Renci IP address range)

**Comment by ironfroggy** [comment]
These kind of errors are really hard to distinguish from latent network issues, and that may be just what these are. 7GB is a lot to transfer and a lot can go wrong with the TCP connection during that time. Honestly I think the only real solution is to properly implement chunked uploading that can be fault tolerant and resume on failure. I don't think this kind of direct single-shot HTTP upload should be used for any files of nearly this size.

**Comment by rayi113** [comment]
I was doing experimentation with greatly reducing tcp_keepalive_time, probes, and intvl on both www and data with no success.  I was also looking at: https://www.nginx.com/blog/http-keepalives-and-web-performance/

**Comment by rayi113** [comment]
Michael tried changing the following values on nginx with no success in uploading 7GB test file:

proxy_connect_timeout  600s;
proxy_send_timeout  600s;
proxy_read_timeout  600s;
fastcgi_send_timeout 600s;
fastcgi_read_timeout 600s;

(see http://stackoverflow.com/questions/18740635/nginx-upstream-timed-out-110-connection-timed-out-while-reading-response-hea) 

Recommend next step is to implement chunked solution that @ironfroggy suggests.

**Comment by hyi** [comment]
Agreed with @rayi113's recommendation to implement what @ironfroggy suggested to resolve this large file upload failure issue. @ironfroggy should we use celery task to implement fault tolerance and resume-on-failure functionality when uploading files? If not, what specific approach do you recommend?

**Comment by mjstealey** [comment]
There is also this: http://wiki.nginx.org/HttpUploadModule

Would require a rebuild of nginx, but looks to implement some interesting features (large file upload, resumable upload, progress, etc.)

**Comment by ironfroggy** [comment]
@hyi A chunked upload would not utilize celery in any way, that I am aware.

It requires two parts.

First,

Either an expansion to the API or new backend views to accept partial file chunks to append on the server until the file is complete, and to indicate a file is complete. This needs to provide a temporary location for files while uploading, in iRODS, add chunks that are uploaded, and initiate the resource creation from the files once uploaded.

Second,

The upload form needs to be customized to utilize this new API to use new HTML5 File APIs to upload in smaller chunks and express errors and resume options to the user.

I think that some work that already exists in terms of how files are uplaoded and moved around for iRODS will actually make this change fairly straight forward. There are some questions in terms of clean up: what happens if an upload is abandoned part-way through?

**Comment by selimnairb** [comment]
Test result from 2 GB file:

```
Environment:


Request Method: POST
Request URL: https://dev.hydroshare.org/hsapi/_internal/create-resource/do/

Django Version: 1.8.9
Python Version: 2.7.6
Installed Applications:
(u'mezzanine.boot',
 u'autocomplete_light',
 u'django.contrib.auth',
 u'oauth2_provider',
 u'corsheaders',
 u'django.contrib.contenttypes',
 u'django.contrib.redirects',
 u'django.contrib.sessions',
 u'django.contrib.sites',
 u'django.contrib.sitemaps',
 u'django.contrib.gis',
 u'inplaceeditform',
 u'django_nose',
 u'django_irods',
 u'theme',
 u'theme.blog_mods',
 u'mezzanine.conf',
 u'mezzanine.core',
 u'mezzanine.generic',
 u'mezzanine.blog',
 u'mezzanine.forms',
 u'mezzanine.pages',
 u'mezzanine.galleries',
 u'crispy_forms',
 u'mezzanine.accounts',
 u'mezzanine.mobile',
 u'haystack',
 u'jquery_ui',
 u'rest_framework',
 u'ga_ows',
 u'ga_resources',
 u'hs_core',
 u'hs_access_control',
 u'hs_labels',
 u'hs_metrics',
 u'irods_browser_app',
 u'django_docker_processes',
 u'hs_geo_raster_resource',
 u'ref_ts',
 u'hs_app_timeseries',
 u'widget_tweaks',
 u'hs_app_netCDF',
 u'hs_model_program',
 u'hs_modelinstance',
 u'hs_tools_resource',
 u'hs_swat_modelinstance',
 u'hs_geographic_feature_resource',
 u'hs_script_resource',
 u'hs_sitemap',
 u'debug_toolbar',
 u'django_extensions',
 u'filebrowser_safe',
 u'grappelli_safe',
 u'django.contrib.admin',
 u'django.contrib.staticfiles',
 u'django_comments')
Installed Middleware:
(u'django.contrib.sessions.middleware.SessionMiddleware',
 u'django.middleware.locale.LocaleMiddleware',
 u'django.contrib.auth.middleware.AuthenticationMiddleware',
 u'corsheaders.middleware.CorsMiddleware',
 u'django.middleware.common.CommonMiddleware',
 u'django.middleware.csrf.CsrfViewMiddleware',
 u'django.contrib.messages.middleware.MessageMiddleware',
 u'mezzanine.core.request.CurrentRequestMiddleware',
 u'mezzanine.core.middleware.RedirectFallbackMiddleware',
 u'mezzanine.core.middleware.TemplateForDeviceMiddleware',
 u'mezzanine.core.middleware.TemplateForHostMiddleware',
 u'mezzanine.core.middleware.AdminLoginInterfaceSelectorMiddleware',
 u'mezzanine.core.middleware.SitePermissionMiddleware',
 u'mezzanine.pages.middleware.PageMiddleware',
 u'ga_resources.middleware.PagePermissionsViewableMiddleware',
 u'debug_toolbar.middleware.DebugToolbarMiddleware')


Traceback:
File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py" in get_response
  132.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py" in _wrapped_view
  22.                 return view_func(request, *args, **kwargs)
File "./hs_core/views/__init__.py" in create_resource
  592.             content=res_title
File "./hs_core/hydroshare/resource.py" in create_resource
  438.             add_resource_files(resource.short_id, *files)
File "./hs_core/hydroshare/resource.py" in add_resource_files
  711.         ret.append(utils.add_file_to_resource(resource, f))
File "./hs_core/hydroshare/utils.py" in add_file_to_resource
  440.                                       resource_file=File(f) if not isinstance(f, UploadedFile) else f)
File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py" in manager_method
  127.                 return getattr(self.get_queryset(), name)(*args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py" in create
  348.         obj.save(force_insert=True, using=self.db)
File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py" in save
  734.                        force_update=force_update, update_fields=update_fields)
File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py" in save_base
  762.             updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py" in _save_table
  846.             result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py" in _do_insert
  885.                                using=using, raw=raw)
File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py" in manager_method
  127.                 return getattr(self.get_queryset(), name)(*args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py" in _insert
  920.         return query.get_compiler(using=using).execute_sql(return_id)
File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py" in execute_sql
  973.             for sql, params in self.as_sql():
File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py" in as_sql
  931.                 for obj in self.query.objs
File "/usr/local/lib/python2.7/dist-packages/django/db/models/fields/files.py" in pre_save
  314.             file.save(file.name, file, save=False)
File "/usr/local/lib/python2.7/dist-packages/django/db/models/fields/files.py" in save
  93.             self.name = self.storage.save(name, content, max_length=self.field.max_length)
File "/usr/local/lib/python2.7/dist-packages/django/core/files/storage.py" in save
  63.         name = self._save(name, content)
File "./django_irods/storage.py" in _save
  148.                 f.write(chunk)

Exception Type: IOError at /hsapi/_internal/create-resource/do/
Exception Value: [Errno 5] Input/output error
```

**Comment by mjstealey** [comment]
The biggest hurdle in this may be the docker space allocation getting in the way.
Would like to look at using an NSF mount as the temporary landing zone for servicing large file uploads.
Whether all files do this, or only files over a certain threshold would need to be determined.

Additional ideas are appreciated.

```python
Environment:


Request Method: POST
Request URL: http://beta.hydroshare.org/hsapi/_internal/create-resource/do/

Django Version: 1.8.9
Python Version: 2.7.6
Installed Applications:
(u'mezzanine.boot',
 u'autocomplete_light',
 u'django.contrib.auth',
 u'oauth2_provider',
 u'corsheaders',
 u'django.contrib.contenttypes',
 u'django.contrib.redirects',
 u'django.contrib.sessions',
 u'django.contrib.sites',
 u'django.contrib.sitemaps',
 u'django.contrib.gis',
 u'inplaceeditform',
 u'django_nose',
 u'django_irods',
 u'theme',
 u'theme.blog_mods',
 u'mezzanine.conf',
 u'mezzanine.core',
 u'mezzanine.generic',
 u'mezzanine.blog',
 u'mezzanine.forms',
 u'mezzanine.pages',
 u'mezzanine.galleries',
 u'crispy_forms',
 u'mezzanine.accounts',
 u'mezzanine.mobile',
 u'haystack',
 u'jquery_ui',
 u'rest_framework',
 u'ga_ows',
 u'ga_resources',
 u'hs_core',
 u'hs_access_control',
 u'hs_labels',
 u'hs_metrics',
 u'irods_browser_app',
 u'django_docker_processes',
 u'hs_geo_raster_resource',
 u'ref_ts',
 u'hs_app_timeseries',
 u'widget_tweaks',
 u'hs_app_netCDF',
 u'hs_model_program',
 u'hs_modelinstance',
 u'hs_tools_resource',
 u'hs_swat_modelinstance',
 u'hs_geographic_feature_resource',
 u'hs_script_resource',
 u'hs_sitemap',
 u'debug_toolbar',
 u'django_extensions',
 u'filebrowser_safe',
 u'grappelli_safe',
 u'django.contrib.admin',
 u'django.contrib.staticfiles',
 u'django_comments')
Installed Middleware:
(u'django.contrib.sessions.middleware.SessionMiddleware',
 u'django.middleware.locale.LocaleMiddleware',
 u'django.contrib.auth.middleware.AuthenticationMiddleware',
 u'corsheaders.middleware.CorsMiddleware',
 u'django.middleware.common.CommonMiddleware',
 u'django.middleware.csrf.CsrfViewMiddleware',
 u'django.contrib.messages.middleware.MessageMiddleware',
 u'mezzanine.core.request.CurrentRequestMiddleware',
 u'mezzanine.core.middleware.RedirectFallbackMiddleware',
 u'mezzanine.core.middleware.TemplateForDeviceMiddleware',
 u'mezzanine.core.middleware.TemplateForHostMiddleware',
 u'mezzanine.core.middleware.AdminLoginInterfaceSelectorMiddleware',
 u'mezzanine.core.middleware.SitePermissionMiddleware',
 u'mezzanine.pages.middleware.PageMiddleware',
 u'ga_resources.middleware.PagePermissionsViewableMiddleware',
 u'debug_toolbar.middleware.DebugToolbarMiddleware')


Traceback:
File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py" in get_response
  132.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py" in _wrapped_view
  22.                 return view_func(request, *args, **kwargs)
File "/home/docker/hydroshare/hs_core/views/__init__.py" in create_resource
  592.             content=res_title
File "/home/docker/hydroshare/hs_core/hydroshare/resource.py" in create_resource
  438.             add_resource_files(resource.short_id, *files)
File "/home/docker/hydroshare/hs_core/hydroshare/resource.py" in add_resource_files
  711.         ret.append(utils.add_file_to_resource(resource, f))
File "/home/docker/hydroshare/hs_core/hydroshare/utils.py" in add_file_to_resource
  440.                                       resource_file=File(f) if not isinstance(f, UploadedFile) else f)
File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py" in manager_method
  127.                 return getattr(self.get_queryset(), name)(*args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py" in create
  348.         obj.save(force_insert=True, using=self.db)
File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py" in save
  734.                        force_update=force_update, update_fields=update_fields)
File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py" in save_base
  762.             updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py" in _save_table
  846.             result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py" in _do_insert
  885.                                using=using, raw=raw)
File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py" in manager_method
  127.                 return getattr(self.get_queryset(), name)(*args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py" in _insert
  920.         return query.get_compiler(using=using).execute_sql(return_id)
File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py" in execute_sql
  973.             for sql, params in self.as_sql():
File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py" in as_sql
  931.                 for obj in self.query.objs
File "/usr/local/lib/python2.7/dist-packages/django/db/models/fields/files.py" in pre_save
  314.             file.save(file.name, file, save=False)
File "/usr/local/lib/python2.7/dist-packages/django/db/models/fields/files.py" in save
  93.             self.name = self.storage.save(name, content, max_length=self.field.max_length)
File "/usr/local/lib/python2.7/dist-packages/django/core/files/storage.py" in save
  63.         name = self._save(name, content)
File "/home/docker/hydroshare/django_irods/storage.py" in _save
  148.                 f.write(chunk)

Exception Type: IOError at /hsapi/_internal/create-resource/do/
Exception Value: [Errno 28] No space left on device
```

**Comment by rayi113** [comment]
mv  /var to /var_old; make a symbolic link between (new) /var and somewhere on /projects/hydroshare.., then recursively copy /var_old to the new symbolic /var (preserving owner, permissions, etc) that is linked to the physical /projects/hydroshare..

**Comment by mjstealey** [comment]
> mv /var to /var_old; make a symbolic link between (new) /var and somewhere on /projects/hydroshare

Given that this is Docker, and will need to be implemented across multiple machines (production plus testing boxes), I'm unsure if we want all of `/var` to be sym-linked.

Doing something abstractly like this for say `/tmp/upload` and `/tmp/download` per VM might interesting. I'd think as long as we keep the user UID and GID consistent across the NFS mount and the Docker container we should be alright using a runtime volume mount.

Will need testing.

**Comment by rayi113** [comment]
Suggest changing "File size is limited to 10 GB per file"  to  "File size is limited to 1 GB per file" until large file size issue is resolved since somewhere between 1 GB and 2 GB seems to be what is consistently reliable.  Also, the "File size is limited to <n> GB per file" appears at 4 different places in the code; suggest this be referenced in 1 place in the code for all 4 places:
hs_core/templates/pages/create-resource.html 
hs_modelinstance/templates/pages/create-swat-model-instance.html 
hs_modelinstance/templates/pages/create-ueb-snow-model-instance.html 
hs_modelinstance/templates/pages/create-rhessys-model-instance.html

**Comment by danames** [comment]
I agree with @rayi113 on this. Let's limit to 1 GB and only have it
mentioned in one place so that it is easier to change in the future.

**Comment by hyi** [comment]
As the first step to tackle this issue, I will try to implement chunked file uploading with the ability to resume if the upload is interrupted using django-chunked-upload https://github.com/juliomalegria/django-chunked-upload. Other things to be looked at related to this issue include docker space allocation, nginx server optimization for serving large files such as multiple worker connections, buffer size, etc., which @mjstealey is looking into, and leveraging iRODS user file space idea as presented by @rayi113, which I am also looking into aimed at addressing this issue as well as other use cases.

**Comment by selimnairb** [comment]
Or we could cap uploads at 1 GB, and let users use the iRODS user space to upload larger files (which I believe we are already doing).  We could also integrate with Dropbox and other providers for importing larger files.  In short, we have a lot of functionality to complete, and less and less time on the project to do it in.  Thoughts?

**Comment by hyi** [comment]
After some further investigation, I agree with @selimnairb priority wise to put off implementation on chunked file uploading with resume ability a bit further after iRODS user file space is implemented in HydroShare. It turns out, according to iPlant/CyVerse Wiki, that CyVerse DE (Discovery Environment) caps file upload to 2GB per file via web browser, and recommends to use Cyberduck iRODS desktop client for larger files. Can we increase our cap from 1GB to 2GB also? I remember we used to be able to do 2GB file upload successfully, so I am thinking once docker space gets cleaned up and we may have to clean it up regularly if needed, 2GB file upload may be manageable in HydroShare? @mjstealey @selimnairb @rayi113 @dtarb I will focus my effort on iRODS user file space implementation first before implementing chunked file uploading with resume ability.

**Comment by dtarb** [comment]
I agree with this approach.

**Comment by hyi** [comment]
@rayi113 wondering whether this issue can be closed now that iRODS user file space has been implemented.

**Comment by mjstealey** [comment]
separate large file discussion has been created
