### ISSUE TITLE
Need spaces between initials and names in citations

### ISSUE THREAD

**Issue by horsburgh** [hydroshare/hydroshare#605]
When there are multiple authors/creators of a resource that are listed in the citation, there is no space between the initials and last names of the 2nd, 3rd, 4th, etc. authors.  See the following for an example:

Tarboton, D., P.Dash, T.Gichamo (2015). Utah Energy Balance (UEB) Snowmelt Model Input Data Preparation Script, HydroShare, http://www.hydroshare.org/resource/cfb8d71b7f1f4e75a44f5e634f4730d4

**Comment by pkdash** [comment]
@horsburgh See if this can be closed.

**Comment by horsburgh** [comment]
Looks good on www.hydroshare.org.
