### ISSUE TITLE
Outgoing mail broken for local dev, blocks testing of user registration

### ISSUE THREAD

**Issue by ironfroggy** [hydroshare/hydroshare#606]

**Comment by mjstealey** [comment]
Developers should configure their own environment using the information outlined here: https://github.com/hydroshare/hydroshare/wiki/hydroshare_email_using_gmail

The *.hydroshare.org VMs have their own email server that is specified via the local_settings.py file located on each VM separately. These configuration files are not made publicly available as part of the code on github for security reasons.

**Comment by ironfroggy** [comment]
I think there is a larger issue involved of developer setups and VM deployments still requiring far too many manual steps. Any deployment that requires manual steps is prone to errors.

- Why is the local_settings.py checked into the repo if you have to use a local version? Usually these would not exist, so they initial setup *requires* they be put in place before anything will run. This helps catch mistakes early.
- If there has to be settings that should exist only on a particular machine or machines, they can be kept on that machine by default.

If I didn't have to make a completely new clone and setup on riverdev, this would not have been a problem. With this setup, there aren't even really "deployments" in any traditional sense. We just have developers checking out developer setups on some VMs.

**Comment by mjstealey** [comment]
There are scripts for all of this: https://github.com/hydroshare/hydroshare/tree/develop/scripts

Other developers using the public VMs are deploying via Jenkins and using the aforementioned scripts to keep the data backup and deployments relative to the machine being deployed to.

Happy to walk you through this if you are still confused or having issues on the deploy.

**Comment by ironfroggy** [comment]
@mjstealey is the process to deploy via Jenkins documented? I was never given access to Jenkins, only SSH access to the machine and told to check out the repo and deploy manually. If I had been given the proper information and setup that others are enjoying, it would have saved considerable time and frustration.

**Comment by mjstealey** [comment]
Presently myself, @pkdash, @selimnairb, and @hyi are admins on the Jenkins box, any one of us could set you up with a user level account.

The process is not documented formally, however there are plenty of example jobs running that can be used as a template or starting point for a new job, and then tweaked to suit your needs.

Depending on what needs to be done, the slave VM may need to be configured independently of Jenkins to place it in a known state before you run the job for the first time. There are still some brittle portions of the workflow that can break the slave VM and put it in a non-recoverable state from the Jenkins point of view, and maintenance would need to be done directly on the VM at that point.

**Comment by ironfroggy** [comment]
I'd like to add to this issue that not all GMail accounts have app-specific passwords enabled, so this doens't work for all of us. There are fallback behaviors we could put in place by default, like the console backend https://docs.djangoproject.com/en/1.8/topics/email/#console-backend

**Comment by mjstealey** [comment]
> There are fallback behaviors we could put in place by default, like the console backend https://docs.djangoproject.com/en/1.8/topics/email/#console-backend

I'm happy to put anything other than the production smtp credentials there.
If you have something that will work for all, then by all means please modify / PR it and we'll bring it in.

**Comment by mjstealey** [comment]
Update to **local_settings.py** to default to console as email backend.

Since Django is running in a daemonized docker container the user will need to attach back to the container to see the output.

Example:

```bash
$ docker attach hydroshare_hydroshare_1
...
```
Fill out new user info in your local development browser and click join
```bash
...
Content-Type: multipart/alternative;
 boundary="===============1573799015647134470=="
MIME-Version: 1.0
Subject: Activate your account in HydroShare
From: webmaster@localhost
To: mjstealey@gmail.com
Date: Mon, 04 Jan 2016 19:58:40 -0000
Message-ID: <20160104195840.40.17919@26223243c15c>

--===============1573799015647134470==
MIME-Version: 1.0
Content-Type: text/plain; charset="utf-8"
Content-Transfer-Encoding: 7bit



Welcome to HydroShare. This email address was used to request an account on www.hydroshare.org.
If you originated the request, please use the link below to verify your email address and activate your account.
http://192.168.56.101:8000/accounts/verify/2/489-94521b86ec6110b4fb48/?next=/
If you did not originate this request you may ignore this email.
The HydroShare Team


--===============1573799015647134470==
MIME-Version: 1.0
Content-Type: text/html; charset="utf-8"
Content-Transfer-Encoding: 7bit



<p>Welcome to HydroShare. This email address was used to request an account on www.hydroshare.org.</p>
<p>If you originated the request, please use the link below to verify your email address and activate your account.</p>
<p><a href="http://192.168.56.101:8000/accounts/verify/2/489-94521b86ec6110b4fb48/?next=/">http://192.168.56.101:8000/accounts/verify/2/489-94521b86ec6110b4fb48/?next=/</a></p>
<p>If you did not originate this request you may ignore this email.</p>
<p>The HydroShare Team</p>


--===============1573799015647134470==--

-------------------------------------------------------------------------------
```

**Comment by mjstealey** [comment]
Email defaults to console output which can be viewed by attaching to the running hydroshare container.
`$ docker attach --sig-proxy=false hydroshare_hydroshare_1`

Developer deployment to VM has been implemented as a **Developer Build** option found here: http://ci.hydroshare.org:8080/view/4.%20Developer%20Builds/

- presently in testing phase with @mauriel133 
- plan to distribute to all during next team call
