### ISSUE TITLE
Metadata term "dcterms:isDerivedFrom " is not part of Dublin Core terms

### ISSUE THREAD

**Issue by mohamedmorsy** [hydroshare/hydroshare#609]
While reviewing the RDF structure in resourcemetadata.xml file, we found that "isDerivedFrom" is listed as Dublin Core metadata term in Hydroshare, but it is not part of the Dublin Core terms listed on the website. For example, in the following resource metadata XML file:

http://www.hydroshare.org/resource/b7822782896143ca8712395f6814c44b

This resource has the following "source" metadata:
```
<dc:source>
     <rdf:Description>
             <dcterms:isDerivedFrom rdf:resource="http://ned.usgs.gov/"/>
      </rdf:Description>
</dc:source>
```
The "dcterms:isDerivedFrom" should be modified to "hsterms:isDerivedFrom"

**Comment by pkdash** [comment]
@horsburgh Do we need to make this change?

**Comment by horsburgh** [comment]
@pkdash - It would be technically correct to make this change because @mohamedmorsy is correct - this term is not in the dcterms namespace.

**Comment by pkdash** [comment]
@horsburgh Will make this change then.

**Comment by pkdash** [comment]
@horsburgh I am working on this issue now. Want to know if we care to update the existing sciencemetadata xml file. That would require a custom migration script.

**Comment by horsburgh** [comment]
@pkdash - do you have any idea how many resources this affects?

**Comment by pkdash** [comment]
@horsburgh I have no idea how many resources will be affected. My guess would be maximum 10. I have already included custom migration to update the xml file for those resources.

**Comment by pkdash** [comment]
@horsburgh In fact I know the number of resources that would need migration in order to update the xml file. When I deployed to test the custom migration it migrated 26 resources.

**Comment by horsburgh** [comment]
@pkdash - OK.  Sounds like you've got this covered. I think fixing it is the right thing to do.

**Comment by pkdash** [comment]
@mohamedmorsy See if this can be closed.
