### ISSUE TITLE
Executed By Foreign Key Filtering

### ISSUE THREAD

**Issue by Castronova** [hydroshare/hydroshare#610]
Currently the *ExecutedBy* field in model instance resources is chosen from a listbox that is populated with all known model programs.  Instead this list should be filtered to show only **public** resources or those in which the current user has permission to access.  

In model instance / swat model instance, forms.py

change 
`mp_resource = users.get_resource_list(type=['ModelProgramResource'])`

to

`mp_resource = users.get_resource_list(public=True, type=['ModelProgramResource'])`

**Comment by mohamedmorsy** [comment]
@Castronova I am not sure but do we have to add "Unspecified" to this list? So when "unspecified" is chosen the resource permission could change to public.

**Comment by Castronova** [comment]
Pabitra's suggestion:
in page_processor.py pass in  `request.user`
`mp_resource = users.get_resource_list(user=request.user, type=['ModelProgramResource'])`

**Comment by mohamedmorsy** [comment]
@Castronova Would you please close this issue?
