### ISSUE TITLE
River Geometry Resource Refinements

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#619]
Updating thinking from #12 I suggest river geometry be represented at follows (capturing ideas from email thread's with Maidment)
1.  Build on geographic feature resource type #7 to establish a river geometry resource type or river geometry enhancement (but perhaps not new resource type) that is a special case of geographic feature that includes flow connectivity.  This should accommodate NHDPlus v2 / NFIE GEO geometry.  Decide on what is admissible in terms of lines and polygons to accommodate water bodies.
2.  Build further on river geometry resource to add a hydraulic parameters table as depicted below.
   ![rivergeometry](https://cloud.githubusercontent.com/assets/3456833/9994084/cd33bfd8-6038-11e5-8883-2582800d54df.png)

**Comment by hyi** [comment]
@dtarb Can you assign someone to work on this issue and set the milestone as well? For bookkeeping, I am assigning this initially to you and set the milestone to 1.8 to start with.

**Comment by dtarb** [comment]
I'll need to discuss this with David Maidment and @XingZheng.  I'll be meeting with Maidment next week and making a plan for this will be on the agenda.

**Comment by dtarb** [comment]
Assigning @danames and @zhiyuli.  This involves simply the ability to save as part of geographic feature an additional lookup table.  I do not think this requires a new resource type.  It is one of the items described in BYU workplan.

**Comment by dtarb** [comment]
Closing - no specific plans for river geometry
