### ISSUE TITLE
Implement new resource creation workflow as decided in all-hands meeting

### ISSUE THREAD

**Issue by hyi** [hydroshare/hydroshare#62]
Implement new resource creation workflow as decided in all-hands meeting at Logan to have resources created immediately after a resource type is selected with optional file upload and title input. Details below copied from Jeff H.'s note from all-hands meeting:
----------
**What is the state of HydroShare at each step in the resource creation sequence?** 
1. User Clicks “create new” to create a new resource
2. The Select Resource page appears.  Nothing exists at this point.
3. The user selects a resource type. Nothing exists yet.
4. The user creates a title for the resource (NOTE: this should be optional and doesn’t exist yet - pre populate this field with “Untitled resource”)
5. Optionally, the user clicks choose files and selects one or more files. Nothing exists yet.
6. The user clicks the “Describe Resource” button - this button should really be titled “Create Resource”.  
* This submits the form
* Creates the resource container (the bag) on disk in HydroShare
* Creates a title for the resource of “Untitled Resource” if it wasn’t specified
* Creates a permanent and persistent internal HydroShare identifier
* The resource container (the bag) is named on disk using the identifier
* At this point whatever files that were specified on the form are written to the resource container at the right location in the bag.
* The resource metadata and resource map are created with default values - defaults or whatever elements can be extracted from the files that were given.
* The user is then taken to the resource landing page where they can edit the default metadata directly on the landing page.  This way we only edit resource metadata in one place.
Since the landing page has individually editable elements, each edit is saved individually as the user edits it.
7. NOTE:  Individual metadata edits SHOULD NOT create an entirely new version of the resource.  This is a separate discussion that needs to be dealt with.
8. NOTE:  There are issues with reference time series
* The first page might have to change depending on which resource type is selected.
* OR - specific resource types may have to have a page between the initial resource creation page and the resource landing page

**What is required for a resource to exist?**
1. A resource container on disk (the bag and the bagit files)
2. An internally persistent and unique identifier - by which the bag is named.
3. A selected resource type.
4. resourcemetadata.xml - this file must exist, even if it has empty or default values
5. resourcemap.xml - this file must exist, even if it has empty or default values

**What is required for a resource to be shared with another hydroshare user or group?**
1. No additional metadata is required in addition to what is required for resource creation.
2. The user must choose to share with the other user or group.

**What is required for a resource to be shared publicly - e.g, the Resource becomes publicly available and discoverable in HydroShare?**
1. We think HydroShare should be default private.  All resources are initially private by default.
2. When a user chooses to make a resource public, the metadata are validated for completeness - e.g., the required elements are checked. This is necessary for a resource to be cataloged for discovery
3. If valid, the resource is made public and discoverable.

**What is required for a resource to be published**
1. Publication is initialized by the owner of the resource (i.e., the owner makes a choice to do so)
2. The owner must agree to a publication agreement - allows HydroShare to be the publisher?
3. Selection of a license under which the resource will be published by the user - e.g., Creative Commons (which versions should we make available?)
4. Fully validated metadata 
* Need to define “valid”
* Need to program a validator
5. Assigned permanent external identifier (DOI)

**Comment by pkdash** [comment]
Not all of the requirements have been implemented yet. We may have to break issue#62 to a number of sub-issues.

**Comment by rayi113** [comment]
HydroShare Resource Creation Workflows Issues in GitHub: #37, #62, #81

**Comment by dtarb** [comment]
Implemented in Alpha for v 1.3 deployment
