### ISSUE TITLE
Remove Hydroshare Author Group

### ISSUE THREAD

**Issue by ironfroggy** [hydroshare/hydroshare#624]
This group serves no purpose, but has broken code and local envrionments multiple times when misconfigured.

**Comment by hyi** [comment]
@pkdash I am assigning this to you since I think this will be addressed when group functionality is deployed.

**Comment by pkdash** [comment]
@hyi This won't be fixed when we deploy group functionality. This problem with default group is related to mezzanine page permission. Not sure how to fix that.

**Comment by hyi** [comment]
@pkdash OK. I am reassigning it to myself then with a low priority to investigate further after group functionality is deployed.

**Comment by Lizabrazil** [comment]
@alvacouch Can i close this out? Is it still relevant?

**Comment by cuahsimarko** [comment]
My understanding is this is not actionable, as the component is required by Mezzanine and removing Mezzanine requires hundreds of work hours to properly test and refactor.
