### ISSUE TITLE
Enable/Ensure creation of arbitrary resource types using REST API

### ISSUE THREAD

**Issue by selimnairb** [hydroshare/hydroshare#626]
Currently, users cannot create derived model resources (e.g. SWAT model instance) using the REST API.

**Comment by selimnairb** [comment]
@vmmerwade I am able to create a SWATModelInstanceResource resource as follows.  First, I downloaded [this](https://www.hydroshare.org/resource/c96993478a59442ca9e1c167fe57bf3a/) resource, and unzip the bag contents.  Then use the following code:

    from hs_restclient import HydroShare, HydroShareAuthBasic
    auth = HydroShareAuthBasic(username='MYUSER', password='MYPASSWORD')
    hs = HydroShare(hostname='my.hydroshare.host.edu', port=8000, auth=auth)
    abstract = 'My abstract'
    title = 'A SWAT model'
    keywords = ('my keyword 1', 'my keyword 2')
    fpath = '/PATH/TO/c96993478a59442ca9e1c167fe57bf3a/data/contents/CedarCreek.zip'
    rtype = 'SWATModelInstanceResource'
    resource_id = hs.createResource(rtype, title, resource_file=fpath, keywords=keywords, abstract=abstract)

Are you able to do something like the above to create a SWATModelInstanceResource?  I realize that the above only creates the resource and not all the metadata, and that they API doesn't (yet) allow you to create the metadata (starting to work on that).  However I wanted to make sure that you were at least able to create the resource.

**Comment by yirugi** [comment]
We are using REST API to create SWATModelInstanceResource resources, and it is working now.
And yes, we need to manually put some metadata, but it seems they do not provide the modifying resource-specific metadata API yet.

**Comment by selimnairb** [comment]
@yirugi Thanks for clarifying.  Since you can create the resource, I will close this issue.  We can address the metadata modification in another issue.  Just out of curiosity, how are you setting the metadata now (e.g. using the HydroShare web interface)?

**Comment by yirugi** [comment]
@selimnairb  For now, SWATShare exports GenericResource resource type instead of SWATModelInstaceResouce, since it cannot be published without those metadata.

**Comment by selimnairb** [comment]
@yirugi According to the [design document](https://github.com/hydroshare/hydroshare/blob/master/docs/DesignDocs/API/index.md#hydroshareupdatesciencemetadatapid-sciencemetadata----pid) for the API, you would need to update the SWAT-specific science metadata by calling updateScienceMetadat and passing in the new science metadata in XML format.  You would do this after creating a SWATModelInstanceResource.  Once you've create a SWAT model instance and updated the metadata, you would make the resource public as per [here](http://hs-restclient.readthedocs.org/en/latest/).

I anticipate implementing the updateScienceMetadata end point for the 1.6.3 release.  You can track the progress [here](https://github.com/hydroshare/hydroshare/issues/723).

**Comment by yirugi** [comment]
@selimnairb I'm waiting for the implementation as well. Thank you for the issue number!
