### ISSUE TITLE
Fix resource URL scheme

### ISSUE THREAD

**Issue by selimnairb** [hydroshare/hydroshare#63]
Resource URLs are currently of the form: 
    http://www.hydroshare.org/my-resource-slug/
where "my-resource-slug" is based on the title of the resource, and the URL is immutable.  This has numerous problems, including: 
 - resources without titles will get stuck with a URL of .../untitled-resource-N/
 - users can create URLs at the base of the hydroshare.org namespace (which could result in e.g. hydroshare.org/mike-rotch)

Based on 1/14/2015 developer's call, resource URLs should be of the form:
    http://www.hydroshare.org/resource/GUID
where GUID is the global unique identifier for the resource.

**Comment by horsburgh** [comment]
We also discussed this at the Logan meeting last week and agreed upon the following patterns:

http://hydroshare.org/resource/{id} ---> Goes to a resource’s landing page
http://hydroshare.org/user/{id} ---> Goes to a user’s profile page
http://hydrohare.org/group/{id} ---> Goes to a group’s profile page

**Comment by rayi113** [comment]
HydroShare Resource Creation URL Issues in GitHub: #41, #63

**Comment by danames** [comment]
Also what if two resources have the identical title?

**Comment by horsburgh** [comment]
Shouldn't matter since the title would not be used in the URL.

**Comment by danames** [comment]
I'm looking at alpha.hydroshare.org and the resource landing pages do use
the title, so it is critical to change this to the new pattern before the
next release..

For example these links work but shouldn't...

http://alpha.hydroshare.org/ponies/
http://alpha.hydroshare.org/random-dmv-form/

**Comment by horsburgh** [comment]
Yeah - I think that's what inspired this issue originally.

**Comment by hyi** [comment]
Same fix to issue [#41] applies to this issue as well.

**Comment by dtarb** [comment]
Implemented for Alpha
