### ISSUE TITLE
Initial Search Facets for Data Discovery

### ISSUE THREAD

**Issue by horsburgh** [hydroshare/hydroshare#630]
As part of a recent discussion about potential resource filtering and data discovery functionality for HydroShare, we decided that we needed to create an ***initial*** list of prioritized search facets to support data discovery and/or filtering of resources. This initial list doesn't have to be the final set of functionality for HydroShare, but needs to give us a place to start in developing and testing the underlying metadata index(es) and front end functionality.  To start the conversation, I suggest the following lists of potential facets.  **These need to be pared down/prioritized for implementation, so I suggest starting with the first list.**

**Simple facets that may be easier to implement first:**
* Resource Type
* Author
* Owner
* Organization (i.e., author organization)
* Subject keywords
* Sharing status (public, discoverable, private)
* File/resource size
* Creation date
* Last modified date

**More advanced facets that may require interpretation of existing metadata fields:**
* Spatial extent (spatial coverage - e.g., resources with coverage within or intersecting a bounding box)
* Time period (temporal coverage - e.g., resources with coverage within or intersecting a time period)
* Keywords within the Abstract (text search for keywords in the Abstract)
* Keywords in Title (text search for keywords in the Title)
* Resources near a particular place (e.g., search for a City, place name, or watershed and find nearby resources)

**Potential social facets:**
* Highly rated/liked/+1'd resources
* Highly commented on resources
* Resources I have +1'd
* Resources I have commented on
* Favorite resources (resources I have marked as "starred" or "favorite" or something like that)
* Resources "similar" to a particular resource (show me similar resources)

**Potential facets related to access control:**
* Resources owned by me
* Resources shared with me
* Resources viewable by me

**Potential facets related to group access control:**
* Resources shared with a group
* Resources viewable by a group (not sure this one makes sense)

**Resource specific facets:**
* Variable name (measured or simulated variable)

**Comment by alvacouch** [comment]
Superseded by much discussion in other places.
