### ISSUE TITLE
Model Program Version 2

### ISSUE THREAD

**Issue by Castronova** [hydroshare/hydroshare#632]
Implement the revised metadata terms:

| Term | Type | Description |  
| --- | --- | --- |
| modelVersion |	Text |	Model version and/or build number |
| modelProgramLanguage |	Text | 	The programming language(s) that the model was written in| 
| modelOperatingSystem |	Text 	| Compatible operating systems to setup and run the model| 
| modelReleaseDate | 	Date | 	The date that this version of the model was released| 
| modelReleaseNotes |	Text/Uploaded file 	| Notes regarding the software release| 
| modelWebsite | 	URL |	A URL to the website maintained by the model developers| 
| modelCodeRepository| 	URL | 	A URL to the source code repository | 
| modelDocumentation |	Single or multiple uploaded files | 	Documentation for the model (user manuals, theoretical manuals, reports, notes, etc.)| 
| modelSoftware | Single or multiple uploaded files | 	Uploaded archive containing model software (source code, executable, etc.)| 

* Also addresses #547

**Comment by gantian127** [comment]
@Castronova would you please close this issue if you think it is fixed? Thanks.
