### ISSUE TITLE
RefTS has problems with new base model

### ISSUE THREAD

**Issue by zhiyuli** [hydroshare/hydroshare#635]
@ironfroggy @pkdash 
I merged dev into branch 502-HISTimeSeries-new-design, and changed the RefTS class definition in /refts/models.py to fit new base model as follows: 

```
class RefTimeSeries(BaseResource):
    objects = ResourceManager()
    class Meta:
        verbose_name = "HIS Referenced Time Series"
        proxy = True
    @property
    def metadata(self):
        md = RefTSMetadata()
        return self._get_metadata(md) 
    @classmethod
    def get_supported_upload_file_types(cls):
        # no file types are supported
        return ()
    @classmethod
    def can_have_multiple_files(cls):
        # resource can't have any files
        return False
```

When creating a new RefTS res, I got an exception at line 56 of /hydroshare/hs_core/hydroshare/utils.py.

```
Line 55: content = res.get_content_model()
Line 56: assert content, (res, res.content_model)
```

Debugging shows: after Line 55, the value of "content" is None

**Comment by ironfroggy** [comment]
You need to provide the resource type as a parameter to `ResourceManager()` like `ResourceManager("RefTimeSeries")` where the parameter is the value of the new `resource_type` field that identifies actual types of each resource created.

**Comment by zhiyuli** [comment]
@ironfroggy  I changed to this just now: objects = ResourceManager("RefTimeSeries"), but got the same exception.  "content" is None

**Comment by zhiyuli** [comment]
@ironfroggy  @pkdash 
Looks like this piece of code can cause a None content:
/hs_core/models.py,  Lines 1638 to 1644

def new_get_content_model(self):
    from hs_core.hydroshare.utils import get_resource_types
    content_model = self.content_model
    if content_model.endswith('resource'):
        rt = [rt for rt in get_resource_types() if rt._meta.model_name == content_model][0]
        return rt.objects.get(id=self.id)
    return old_get_content_model(self)

Does it mean all resource class names should be ended with "resource"?

**Comment by ironfroggy** [comment]
@zhiyuli this is because the order of inheritance required made it impossible to override this method and we had to monkey patch it. We want to add specific behavior for resources different from all other Mezzanine pages, in order to load the resource of the right content type. I didn't intend to enforce a rule about this, but it seems like a fair course of action and consistent with all previously existing resource types.

**Comment by zhiyuli** [comment]
closed. old ticket. already merged several months ago
