### ISSUE TITLE
Normal users cannot edit geographic feature resources when merged new base model and access control

### ISSUE THREAD

**Issue by zhiyuli** [hydroshare/hydroshare#636]
Normal users can create a geographic feature res, but cannot edit it (no edit button shows up on landing page).
Admin user can create and then edit geographic res.

**Comment by mauriel133** [comment]
I'm not able to reproduce this issue. Are you experiencing this error only with Geographic Raster resources?

**Comment by zhiyuli** [comment]
@mauriel133  It is Geographic Feature (ESRI Shapefile) Res Type. This new res type is not in dev branch yet.

**Comment by zhiyuli** [comment]
already fixed in 1.6.1
closed
