### ISSUE TITLE
hs_swat_modelinstance.ExecutedB uses a URL to express relationship with another resource

### ISSUE THREAD

**Issue by selimnairb** [hydroshare/hydroshare#637]
hs_swat_modelinstance.ExecutedBy is incorrectly specified in that it uses a URL to express a relationship between two HydroShare resources, rather than using a foreign key reference.  Using a URL in this way can lead to unexpected behavior if in the future the hostnames of HydroShare instances change, and is an anti-pattern to be avoided.  In this case the error can easily be fixed by using hs_modelinstance.ExecutedBy, removing hs_swat_modelinstance.ExecutedBy.  (In general SWATModelInstance metadata should use ModelInstanceMetadata where appropriate instead of duplicating code.)

**Comment by mohamedmorsy** [comment]
Same as #548

**Comment by mohamedmorsy** [comment]
This has been addressed on issue #548
