### ISSUE TITLE
How to remove a user from the Manage Access box?

### ISSUE THREAD

**Issue by zhiyuli** [hydroshare/hydroshare#638]
I can add a user into this box, but how to remove a user?

![image](https://cloud.githubusercontent.com/assets/10070599/10196977/c182e396-6752-11e5-8045-cb473081a8dc.png)

**Comment by horsburgh** [comment]
This will be addressed with the new manage access panel that @mauriel133 has built. His goal is to finish that up this week.

**Comment by ironfroggy** [comment]
Ctrl click on a selected user to remove them?

On Wed, Sep 30, 2015 at 11:18 AM, Jeff Horsburgh <notifications@github.com>
wrote:

> This will be addressed with the new manage access panel that @mauriel133
> <https://github.com/mauriel133> has built. His goal is to finish that up
> this week.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hydroshare/hydroshare/issues/638#issuecomment-144443790>
> .
>



-- 


*Calvin Spealman*Lead Front-end Developer

calvin@caktusgroup.com <calvin@caktusgroup.com>
www.caktusgroup.com

**Comment by horsburgh** [comment]
Hopefully @mauriel133 can respond if there's a way to do it currently.

@mauriel133 demo'd the new access control panel again yesterday in our local programmer meeting.  He's consolidated to one box where you can add or remove specific users and explicitly set which permissions they have.  In the new interface, removal will be done by clicking on a delete button next to the permission that has been set.

**Comment by dtarb** [comment]
The new interface deployed at 1.6.1 resolves this.
