### ISSUE TITLE
View Resource Owner - 'NoneType' object has no attribute 'lower'

### ISSUE THREAD

**Issue by mjstealey** [hydroshare/hydroshare#64]
When attempting to view resource owner profile infromation from the resource listing page under the Owner column link, it errors with type: 'NoneType' object has no attribute 'lower'

using alpha.hydroshare.org as an example: http://alpha.hydroshare.org/user/admin/

![screen shot 2015-01-14 at 4 23 48 pm](https://cloud.githubusercontent.com/assets/5332509/5747913/c270e66e-9c09-11e4-8943-3e79c4f6a44e.png)

**Comment by hyi** [comment]
mark this issue as "Fix pushed to github." Now the fix has been merged into develop branch. Once it makes its way into alpha, will mark it as ready for testing.

**Comment by dtarb** [comment]
In my testing this appears to be resolved, but I do not know exactly what Michael did to generate this error, so leave it for @mjstealey to test and close.
