### ISSUE TITLE
Geographic feature clarify structure of zip files required.

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#646]
I have a folder containing shapefile components.  I zipped this folder and tried to load it.  This did not load.  I was returned to the Create Resources page without any error message.  If it is required that shapefile components not be in a folder, then this needs to be documented and the system needs to generate an error message.

**Comment by zhiyuli** [comment]
@dtarb 
Good point! Current implementation requires the shapefiles not be in a folder. We need to change it. Most users have their shapefiles stored in folders and then zip up the folder directly since shapefiles are multiple files. Thanks.

**Comment by dtarb** [comment]
This was fixed a while ago.
