### ISSUE TITLE
Extensible metadata

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#647]
There is quite a bit of functionality that requires the ability to add extensible metadata items to resources. This relates to model program resources where we need optional attributes to indicate replicated, and related to how to cite, see #488.  This also relates to geographic features and River geometry #619, where one approach is to represent river geometry using extensions of geometric features (and thus save having to build a whole new resource type).  Very early in the project we had a Dublin Core module, that in addition to the base Dublin Core metadata we wanted, allowed adding of optional named Dublin core metadata elements.  I think that for extensible metadata we need to be able to add from a designated subset of named elements, that may be chosen from the earlier Dublin core list, as well as allow resource type specific named elements and general user named elements (perhaps as a key-value pair).    

@ironfroggy what is the best approach to implement this in the refactored base class model?
@horsburgh how does this fit with the resource data model and science metadata xml representation?
Xing Zheng, @danames , @zhiyuli would this work for extending geographic features to represent River Geometry?

**Comment by XingZheng** [comment]
I think this will work. We can add a special metadata namelist for river geometry data besides the general metadata elements for geographic features.

**Comment by horsburgh** [comment]
@dtarb - the specification for the science metadata has a section in it about extensible metadata elements.  So, we anticipated it in the design, but I'm not sure about how hard it will be to support it given our current implementation. @pkdash may be able to weigh in on details.

One important note - I would not rely on extensible/optional metadata elements for things that you know you will need for every resource. For example, the attribute that will determine how a citation gets created on the resource landing page can't be optional.  If be base the behavior of the page on an attribute, it needs to be there for all resources.

**Comment by pkdash** [comment]
Current implementation allows any resource type to define any number of extensible metadata terms. However, it seems that we now have a need to allow the user to add arbitrary metadata terms using key/value data structure which is not supported in the current implementation. This can be addressed as part of the metadata refactoring task.

**Comment by ironfroggy** [comment]
It is not clear to me, unfamiliar with the family of data you're concerned with, how consistent the structure and type of these extended metadata entries would be. Are they all plain text? Do some of them require being validated as dates? As time stamps or integrals or more complex types?

What about ambiguous names of metadata entries that might have different meanings for different resource types?

The less validation and strictness, the easier the solution, of course. If this is just a list of named, human-entered fields on a resource then it can be accomplished easily with a single `hstore` field. If it needs more complex types, we can still build this but we need to know and define those required types upfront.

What is most interesting to me about the second option, once we build it, is what of the current metadata would then fit into this generic implementation?

**Comment by dtarb** [comment]
I think the majority is plain text so the hstore approach is likely sufficient.  I do not think all the needs are worked out, and those that are worked out are in quite old documents that we need to refresh ourselves on.

**Comment by pkdash** [comment]
@dtarb I am trying to address this issue using HStore (key/value). Is there a list of allowed key terms somewhere? I assume these extra (arbitrary) metadata are not going to be part of the metadata xml document which makes the implementation much easier.

**Comment by dtarb** [comment]
The short answer is that the list should start with

- Funding agency
- Grant number
- Grant title
- Grant principal investigator

These meet the credit attribution use case.

As a longer answer I would like @horsburgh to add to this list based on work in ODM2.  Many of the terms in ODM2 are applicable to resources as a whole and it would be good to leverage the value from this work.  I would also like to consider extending the credit attribution functionality to be able to associate creators or contributors with roles.  In the above both the grant principal investigator and funding agency could already be included as creators or contributors, since an organization can fill these roles.  This suggests extending funding agency and grant PI to be able to hold all the elements that a person in our party model can support.  This may be more complex than easily done with key values, but should be considered for reach functionality.

Slide 20 in [Katz presentation](http://www.slideshare.net/danielskatz/metrics-citation-for-software-and-data) lists the roles associated with creators or contributors.  Can we use key-values to somehow optionally indicate these roles, such as

- Contributor A has role X
- Contributor B has role Y

A list of roles based on slide 20 is 

- Study conception
- Method development
- Computation
- Formal analysis
- Perform experiment
- Collect data
- Create
- Edit 
- Review 
- Supervise
- Administer
- Acquire funds

Definitions for each of the above based on the slide could be added to our metadata.

**Comment by horsburgh** [comment]
@pkdash and @dtarb - I don't mean to throw a wrench in things, but I think that there's a lot of users that are going to want things like funding agency, grant number, grant title, PIs, etc. to be written to the resourcemetadata.xml so they go with the resource wherever it goes. Is there a reason why we wouldn't write the extensible metadata elements to resourcemetadata.xml?

**Comment by dtarb** [comment]
I agree that this content should go to resourcemetadata.xml.  This is part of the resource data model and @horsburgh I appreciate you guiding the implementation to make sure that the extensibility to include these different fields is consistent with RDM.   Whether it goes only in resourcemetadata.xml seems to be an implementation detail that likely relates to how content editing is implemented in Django.

**Comment by pkdash** [comment]
@horsburgh and @dtarb The arbitrary key/value data can be written to the metadata xml document with more coding. For each possible predefined key we need to know/define/store how that is going to be represented in xml document. With introduction of HStore to hold key/value pairs, we will have 2 different data models to store metadata unless we refactor the existing metadata models to use HStore. Having 2 different data models will make the code logic bit complex in managing the metadata if we use them for the same purpose (e,g writing the key/value data to xml document).   As it relates to funding agency, I have implemented it using how all other metadata models have been defined and funding agency information is written to the xml document.

**Comment by horsburgh** [comment]
@dtarb - what you describe above in the attributions for creators and contributors is much more than what can/should be done with key/value pairs. Key/value pairs are simple - there is an attribute that has a name (the key) and a value. What you are suggesting is new attributes that apply to creators and contributors and not the resource. It is suggesting a more formal model of roles and attribution for creators and contributors.

And, with the funding agency credit, theres a somewhat hierarchical structure. For example, if a user adds a funding credit to a resource, that credit can include funding agency name, grant number, grant title, and grant PI(s). These are not arbitrary key/value pairs. At least the funding agency name would be required, so there's some validation that needs to be done - which would be more difficult to do using key/value pairs. Plus - we would want funding agency credits to appear in a set location on the page, which is business logic that would be harder to implement based on key/value pairs.

I think for things that we know are going to be used often, require validation, and have associated business logic - we need to model them as such and include them explicitly in our metadata model. This means we need to be careful what we add. I think key/value pairs should be used to store ONLY arbitrary attributes that a user wants to add to a resource. Arbitrary key/value pairs would apply to the resource as a whole, and I don't think we should validate them or have business logic that depends on attributes stored as key/value pairs.

**Comment by pkdash** [comment]
@horsburgh That's a good description of the limitation of key/value data structure. As it relates to validation of key/value if there is a need we can easily implement what keys are permitted. In HStore all key/value pairs are strings ONLY.

**Comment by dtarb** [comment]
@horsburgh this thread started with a general expression for the need for extensible metadata.  I do not want to be prescriptive that the implementation of this functionality has to be with key values, or HStore.  I am open to the best solution for a model that represents funding agency credit in a simple, clean and general way.

**Comment by horsburgh** [comment]
@dtarb - we've accomplished two of three.  We've done simple and clean. And, we can add any additional metadata elements in the same way - so, the approach is general. But, it is not without development effort. Pabitra had to add the elements to the back end and Mauriel had to expose them on the front end for both display and edit.

**Comment by dtarb** [comment]
Great.  Rick will be on the call on Thursday to discuss a use case related to collections, and if you can show how this is going to work for funding agency credit, I think it will go down well.

**Comment by pkdash** [comment]
@dtarb and @horsburgh Can a creator/contributor have multiple roles for a given resource?

**Comment by dtarb** [comment]
Yes.  As an example, referring to the roles above, person A may conceive the study, develop the methods and create (write) the resource, while person B may collect data and edit the resource.  Person A could be named as a creator filling the roles listed for them and person B a contributor filling the roles for them.

**Comment by horsburgh** [comment]
@dtarb - I think you might want to move the credit and attribution for creators and contributors to a new issue. I don't think it fits under this "extensible metadata" issue anymore.

**Comment by pkdash** [comment]
@dtarb  and @horsburgh If we still have a need for storing **arbitrary** key/value metadata at the resource level (these are not intended to be written to the resource metadata xml document), then I can work with either Mauriel or Drew to implement the front-end code. I have already implemented the backend code for this.

**Comment by dtarb** [comment]
I'll let @horsburgh weigh in, but I think that if metadata is being added to a resource, it should be written to the resource metadata xml file.  The Resource Data Model is a design that preserves the full content of the resource in the bag for archival purposes.  It should be possible to reload the bag and get the complete content of the resource back.  Ultimately we need a function that does this, I think, so if metadata is being added, it goes in the xml.

**Comment by horsburgh** [comment]
I agree with @dtarb - if users go through the trouble of creating metadata, it should be part of the metadata record and should go with the resource wherever it goes. It should get written to the resourcemetadata.xml file. @pkdash - do you have an idea about how to encode it in the RDF/XML, or do we need to create an example?

**Comment by pkdash** [comment]
@horsburgh The reason for not writing the key/value metadata to xml document is I don't know how one would encode it. I guess this could be a possibility:

     <hsterms:additionalMetadata>
        <rdf:Description>
            <hsterms:key>key one</hsterms:key>
            <hsterms:value>value one</hsterms:value>
         </rdf:Description> 
    </hsterms:additionalMetadata>
    <hsterms:additionalMetadata>
        <rdf:Description>
            <hsterms:key>key two</hsterms:key>
            <hsterms:value>value two</hsterms:value>
         </rdf:Description> 
    </hsterms:additionalMetadata>

**Comment by horsburgh** [comment]
@pkdash - I spent some time studying some options, but I didn't come up with something better. What you have suggested would work. It would be nice if we could use a more compact form, but since we can't anticipate all of the arbitrary terms (keys) that users might want, we can't put them in a namespace. So I suggest we try what you've suggested.

I would probably go with something like "extendedMetadata" instead of "additionalMetadata", but that's a subtle difference.

**Comment by pkdash** [comment]
@horsburgh I will then implement writing key/value metadata to xml document.

**Comment by alvacouch** [comment]
@pkdash A general comment. The way this is implemented in PR #1177 might not be the most powerful way. I looked at it as a general client of the library and asked myself whether it would do what I want. I decided that I want more similarity to the main metadata elements. 

I would suggest looking at the object Reference type for HSTORE. I am concerned that we are redoing work that is already done for AbstractResource. If we can create a set of primitive value types (subclasses of AbstractResource), then we can use HSTORE references to refer to them, and create many things of each type. This allows us to use type validation, among other things

.

**Comment by pkdash** [comment]
@alvacouch Not sure I fully understand your suggestion. Are you suggesting that we store all metadata using HSTORE? May be should have a call to discuss this.

**Comment by alvacouch** [comment]
See PR #1177 for concrete suggestions. No time today to discuss. Happy to discuss Monday.

**Comment by hyi** [comment]
@pkdash Can this issue be closed now?

**Comment by pkdash** [comment]
@hyi This issue is a broader issue that needs to be still addressed. However, the arbitrary key/value metadata using HStore has been implemented and can be tested now on beta. @dtarb You can test this feature at beta and then may close this issue.

**Comment by dtarb** [comment]
If there is no extended metadata the extended metadata tab should not be displayed when not in edit mode.

**Comment by pkdash** [comment]
@dtarb Should this be closed?
