### ISSUE TITLE
Discoverable resources should have metadata accessible to all logged in users.

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#649]
@zhiyuli reported this as a problem for the present staging park implementation.  

I can see your "Discoverable" resources without signing in. But once I sign in with my account, I cannot see your "Discoverable" resources any more. I think a signed-n user should see "Discoverable" res because, at least, signed-in user should have higher permissions than anonymous users.

**Comment by pkdash** [comment]
@dtarb This should have been resolved. Please check and close this issue.

**Comment by dtarb** [comment]
Appears resolved.
