### ISSUE TITLE
Manual migration appears to be adding resource metadata content that it should not.

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#655]
If you look at 0ae62cfb9f3347d29c8211564f8db515 on www.hydroshare.org you notice that the author does not have an organization specified.  If you look at the same resource on riverdev.hydroshare.org you notice that the author now has an organization "Brigham Young University" specified.  While this may be perceived as an improvement, it is not because the organization associated with a party who is an author of a resource does not have to be the same as their current affiliation as listed in HydroShare.  For example a resource may be created and an organization listed as X.  This is the authorship record for that resource.  Now the user changes organization.  The organization listed with the authorship record does not change, because that is where they were when the resource was created.  This is similar to the recording of affiliations on papers when people move around.  The author record is separate from profile information.  It can get copied in to a resource at the time a resource is created, to save it having to be manually filled out, but after that point it is a separate record and should not be changed by a migration process.  It should only be changed by manual editing where the user is presumed to have the right knowledge to change it correctly.

**Comment by selimnairb** [comment]
@dtarb The creator as listed in resourcemetadata.xml was:

    <dc:creator>
      <rdf:Description rdf:about="http://www.hydroshare.org/user/102/">
        <hsterms:name>Sarva Pulla</hsterms:name>
        <hsterms:creatorOrder>1</hsterms:creatorOrder>
        <hsterms:email>sarva@byu.edu</hsterms:email>
      </rdf:Description>
    </dc:creator>

In this case, using the organization from the user profile seems to be correct, no?

**Comment by dtarb** [comment]
In this case it is correct, and in this case it appears to be a test resource, but the general principle is that when a resource is loaded from a bag the content from the bag (and the bag only) should be replicated in the new resource, except for known deficiencies we are fixing like a missing type element.

**Comment by selimnairb** [comment]
@dtarb You are right, and it is generally the case that the bag content has the last say.  The resource creator is a bit of a special case, wherein data from the user profile is used to populate this field on resource creation.  In this case, it's not clear to me that the metadata from the bag should win, as they may be out of date from the current user profile.  This also might apply to non-owner creators who are HydroShare users.

**Comment by selimnairb** [comment]
@dtarb As the ingest code stands now, when the first resource creator is a HydroShare user, the metadata for the owner will come from that user's current HydroShare profile, not from the science metadata in the resourcemetadata.xml from the bag contents.  For the the non-owner creators (i.e. all but the first creator by order), the metadata elements will come from the science metadata in the resourcemetadata.xml from the bag contents.  Is this correct?  If not, what is the correct behavior?

**Comment by dtarb** [comment]
@selimnairb I think that when we are importing from a zipped bag the assumption is that it was a properly formed resource in HydroShare so all science metadata should come from the resourcemetadata.xml from the bag contents. We are assuming that we want to preserve the contents as they were saved in the bag.  I do not think we need to try take any guesses about ownership, or other profile information by trying to match the first creator to a HydroShare user.  Just record information in the bag.  

Now because owner information is not in the bag we need to assign HydroShare admin as a temporary owner and then as the second phase of the migration read ownership from the old system and transfer it to the new system (automatically if at all possible).

**Comment by selimnairb** [comment]
@dtarb We are not guessing who the user is.  From resourcemetadata.xml for [this](https://www.hydroshare.org/resource/b7822782896143ca8712395f6814c44b/) resource:

    <rdf:Description rdf:about="http://www.hydroshare.org/user/2/">
	<hsterms:name>David Tarboton</hsterms:name>
	<hsterms:creatorOrder>1</hsterms:creatorOrder>
	<hsterms:organization>Utah State University</hsterms:organization>
	<hsterms:email>dtarb@usu.edu</hsterms:email>
    </rdf:Description>

This is the user ID: http://www.hydroshare.org/user/2/ or "2".  When we call create_resource, all we can only pass in is "2" for the user (i.e. its primary key).  Create resource then fetches user "2"'s profile, and fills in the metadata for this creator/owner for this resource using the information from the profile.

The trouble arises when you have changed user profile information, say your e-mail address.  This change, currently, does not cascade to the metadata for resources in which you are a creator (because we are duplicating the information between the profile and the resource metadata, which allows creators who are not HydroShare users).  The real question is, on bag ingest, if the user information for a known HydroShare user differs between what is stored in resourcemetadata.xml and the user profile, which one should we use?  In other words, should use the most up-to-date information, namely, what is in the user profile at the time of ingest, or should we just use what is in the bag?  I am leaning toward using the information from the profile; what if the user changed e-mail addresses and is not longer reachable via the old address?

**Comment by dtarb** [comment]
Email is the one exception of a field that may go stale.  For all other information we prefer to keep things like organization what they were at the time they were set in the resource, as the old organization still gets credit for the resource, even if the person moves to a new organization.  With email, if the person remains a HydroShare user we will support the functionality to send them a message, so I think it is better to leave the email as it was written the time the resource is created.  This is not unlike the publication of papers.  Your address/email with a published paper does not get updated when you move.  Rather it records the information about you at the time the paper was published.

**Comment by selimnairb** [comment]
@dtarb Okay, I will update the ingest code so that after resource creation, we overwrite the owner's creator information for the resource with what was in the bag, rather than what is in the user profile.

**Comment by dtarb** [comment]
Closing since our manual migration is done and the resource that triggered this is deleted.
