### ISSUE TITLE
Delete resource warning message needs changing

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#66]
Following is the warning that is given when a resource is deleted.
![capture](https://cloud.githubusercontent.com/assets/3456833/5759769/f3392178-9c9d-11e4-947f-b4a25c9e686f.JPG)

It should not be labeled "Submit Resource for Publication"

I suggest: "Delete Resource".  
"This is a permanent action that will delete the resource entirely.  Keep a copy if you still need this information."

Do not say anything about a copy not being retained by HydroShare.  We are not sure this will be true given backups.

**Comment by hyi** [comment]
FIx pushed to github, pull request created to be merged into develop.

**Comment by dtarb** [comment]
Verified in test VM.  Closing.
