### ISSUE TITLE
The text that shows (on resource landing page) what access permission a user has for a resource is not always correct

### ISSUE THREAD

**Issue by pkdash** [hydroshare/hydroshare#668]
If I create a resource and then remove myself from resource ownership, it still shows "You are the owner of this resource" on the resource landing page. If I have edit or view permission for a resource, it supposed to show "You have been given specific permission to edit this resource." or "You have been given specific permission to view this resource." However, it doesn't show that.

**Comment by dtarb** [comment]
Tested and seems to be working satisfactorily in version 1.6.1.
