### ISSUE TITLE
Remove 1.6.0 Migration Scripts

### ISSUE THREAD

**Issue by ironfroggy** [hydroshare/hydroshare#669]
Just a reminder about cleaning these out of the repository after they are no longer used.

**Comment by mjstealey** [comment]
It may be useful to keep these files either in the hydroshare repository, or a separate repository as the basis for the reflector work.

In the past it has been proposed to have the ability to ingest resources directly from iRODS (side door). There is some need to define what this means exactly, but it wouldn't be too far fetched to think that recreating a full hydroshare site directly from a set of iRODS resources is also a possibility. Obviously much thought and work would be required for this, but the existing migration work is a basis for such an idea.

**Comment by hyi** [comment]
I second @mjstealey's comment. These migration scripts may not be needed after this migration process, but will serve as useful reference and can be adapted for other uses in the future. Perhaps a separate repository makes more sense due to its reference nature, but we need to save them somewhere to be referenced in the future.

**Comment by dtarb** [comment]
Yes agreed we need to save them.  We have discussed in the past whether the point of reference for data that is repeated between the XML files in iRODS and Django is iRODS or Django, and for some of it, it is iRODS, so the capability to re-populate the Django content from iRODS will likely be needed.

**Comment by ironfroggy** [comment]
Is there a ticket for the side loading of resources that can be referenced?

**Comment by dtarb** [comment]
@ironfroggy probably not.  Not everything in the design is in tickets.  This was discussed extensively with @alvacouch during Oct 14 to Jan 15 related to the model for working with iRODS.

**Comment by mjstealey** [comment]
removed from develop branch
