### ISSUE TITLE
Non-printable characters can be entered into the abstract field for a resource

### ISSUE THREAD

**Issue by selimnairb** [hydroshare/hydroshare#673]
There is (or was if you are reading this after migration from HS 1.5.3 to 1.6.0; this was fixed by hand in the database dump file) a resource:

    https://www.hydroshare.org/resource/a3beccbf7ba149bab3bb0b2902086a64/

That included a non-printable character in the abstract field.  The character appeared in this part of the abstract:

    Proximity raster layers were derived from features including roads, power lines, and rivers then 
    overlain with 10  10 m raster terrain datasets including slope and potential irradiance to produce a high 
    resolution map showing solar energy potential from
    “poor” to “excellent” for high potential counties across the southwestern United States.

Where between "10  10 m " was a character with ASCII value of 0x01:

000afbf0: 206f 7665 726c 6169 6e20 7769 7468 2031   overlain with 1
000afc00: 3020 **01**20 3130 206d 2072 6173 7465 7220  0 **.** 10 m raster 
000afc10: 7465 7272 6169 6e20 6461 7461 7365 7473  terrain datasets

(see bold values)

It seems that somewhere along the line (Mezzanine?, Django?, elsewhere?), non-printable characters are being allowed and eventually stored in the database.  This probably has to do with users using non-US character encodings.

The storing of non-printable characters causes failure of the serialization of the abstract (a.k.a. resource description) to XML+RDF, and thus a failure in bag creation:

```
for resource in GenericResource.objects.all():
  ...:        create_bag_files(resource)
  ...:

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-5-208fbd288b1b> in <module>()
      1 for resource in GenericResource.objects.all():
----> 2        create_bag_files(resource)
      3

/home/docker/hydroshare/hs_core/hydroshare/hs_bagit.pyc in create_bag_files(resource)
    74    from_file_name = '{path}/resourcemetadata.xml'.format(path=bagit_path)
    75    with open(from_file_name, 'w') as out:
---> 76        out.write(resource.metadata.get_xml())
    77
    78    to_file_name = '{res_id}/data/resourcemetadata.xml'.format(res_id=resource.short_id)

/home/docker/hydroshare/hs_core/models.pyc in get_xml(self, pretty_print)
  1766            dc_des_rdf_Desciption = etree.SubElement(dc_description, '{%s}Description' % self.NAMESPACES['rdf'])
  1767            dcterms_abstract = etree.SubElement(dc_des_rdf_Desciption, '{%s}abstract' % self.NAMESPACES['dcterms'])
-> 1768            dcterms_abstract.text = self.description.abstract
  1769
  1770        # use all creators associated with this metadata object to

/usr/local/lib/python2.7/dist-packages/lxml/etree.so in lxml.etree._Element.text.__set__ (src/lxml/lxml.etree.c:46289)()

/usr/local/lib/python2.7/dist-packages/lxml/etree.so in lxml.etree._setNodeText (src/lxml/lxml.etree.c:20947)()

/usr/local/lib/python2.7/dist-packages/lxml/etree.so in lxml.etree._createTextNode (src/lxml/lxml.etree.c:20823)()

/usr/local/lib/python2.7/dist-packages/lxml/etree.so in lxml.etree._utf8 (src/lxml/lxml.etree.c:27119)()

ValueError: All strings must be XML compatible: Unicode or ASCII, no NULL bytes or control characters

In [6]:

In [6]: print resource.short_id
a3beccbf7ba149bab3bb0b2902086a64
```

This should be fixed as soon as possible so that we don't allow additional "zombie" resources to be created.

**Comment by pkdash** [comment]
@selimnairb I assume this can be an issue with the resource title or any other text type metadata fields also.

**Comment by pkdash** [comment]
@selimnairb and @ironfroggy Should I be then filtering out non printing characters before saving to the database using something like this for filtering:

     my_str = ''.join(c for c in my_str if c in string.printable)

**Comment by ironfroggy** [comment]
@pkdash I do not recommend that *at all* as it will strip out all non-ASCII printable characters, like 99% of valid unicode and all non-english characters. That is not what you want and is not correct.

@selimnairb What yous how in the hexdump is inconsistent and I don't know why.

```
 000afc00: 3020 0120 3130 206d 2072 6173 7465 7220 0 . 10 m raster 
```

Shows `01` in the hexdump but `.` on the right, which is an ANSI 0x46 FULL STOP, which is just a period. Thsi actually seems more likely as some notation may use a period as a dot notation multiplier.

**Comment by ironfroggy** [comment]
It seems less likely that this was ever a non-printable character in the first place and more that an original encoding was handled incorrectly, because this clearly looks like a simple period character.

**Comment by hyi** [comment]
I am closing this issue since I agree with Calvin's assessment above that this was not a non-printable character issue in the first place but rather the original encoding was not handled correctly. ```--encoding UNICODE``` parameter was only added some time back in hsctl script for ```createdb``` call, so it is most likely some wrong encoding had crept into our database. Closing this for now, and we can always reopen it if this issue crops up again.
