### ISSUE TITLE
Add REST API call to ingest file already in iRODS

### ISSUE THREAD

**Issue by selimnairb** [hydroshare/hydroshare#684]
Add REST API call to ingest file already in iRODS, in the same zone as HydroShare, but potentially residing on another resource server.

**Comment by hyi** [comment]
@jbradberry I am putting this on your plate since it is REST API related. I can help with iRODS part of things when we get to this issue. We will see whether a use case exists that can drive implementation of this issue.

**Comment by dtarb** [comment]
@alvacouch this seems to be part of 3rd party storage inasmuch as iRODS is here a 3rd party place to get files from.  We can ingest files from iRODS, but not sure if this can be done from the API.  If it can - close.  If not please coordinate with Scott on getting to be part of API.

**Comment by alvacouch** [comment]
Made irrelevant by strategic changes to IRODS use.
