### ISSUE TITLE
Jenkins CI/CD with build.hydroshare.org

### ISSUE THREAD

**Issue by mjstealey** [hydroshare/hydroshare#688]
- [x] Set up new HydroShare dedicated CI VM (ci.hydroshare.org)
    - Have run into many issues with jenkins.renci.org being in the edc cluster.
- [x] Create hydrobuild user across
    - [x] HydroShare VMs
    - [x] Jenkins
    - [x] Github
    - [x] Gmail
- [ ] Automate build / test on
    - [x] PR creation or update
    - [ ] New commits
- [ ] Provide feedback to PR / Issue with hooks from
    - [x] Jenkins - build pass/fail, testing pass/fail
    - [ ] Code Climate
    - [ ] Waffle

**Comment by hydrobuild** [comment]
Test message from Jenkins

**Comment by hydrobuild** [comment]
ci.hydroshare.org - setup testing

**Comment by mjstealey** [comment]
completed - follow on tasks to be added as new issues
