### ISSUE TITLE
Metadata refactor

### ISSUE THREAD

**Issue by selimnairb** [hydroshare/hydroshare#690]
Currently, there is a lot of copy and paste duplication of code for implementing metadata schema and serialization between resource types.  To improve code maintenance and reliability and easy the ability to add new content types, we should push as much code as possible into base classes.  

We are limited in our ability to do so because CoreMetaData objects do not have direct references to AbstractMetaDataElement.  Our proposed solution is to add explicit Foreign Key from CoreMetaData to AbstractMetaData (not a generic foreign key).This works well for metadata elements that are singular.  For elements that can be repeated we will also need a Foreign Key from AbstractMetaData to CoreMetaData.  We can do this in a two step migration process.  First add the new Foreign Keys, then remove the generic relations.  

Once we push get_xml() and other functionality into AbstractMetaData and CoreMetaData,
we may be able to move the functionality of CoreMetaData into BaseResource, which will
remove a set of joins that currently need to be performed.  We would have to do this
after we remove connection from BaseResource to Mezzanine.

Proposed next steps:
1. Finish hs_geo_feature and merge into develop
2. Apply new abstractions from hs_geo_feature to all resources
   - This will help us to identify any metadata usage patterns that these new abstractions
     did not consider
3. Implement Foreign Keys from CoreMetaData (and descendents) to AbstractMetaData (and descendants), and migrate.
4. Remove generic relations from existing metadata class, and migrate
5. Explore use of HSStore fields for simple metadata elements

@ironfroggy @hyi @pkdash Please feel free to correct and clarify.

**Comment by pkdash** [comment]
Is 'AbstractMetaData' is a new class and different from 'AbstractMetaDataElement' class? Is it possible to define a foreign key that points to an abstract model class(foreign key from CoreMetaData to AbstractMetaData)? Is the relationship between BaseResource and CoreMetaData be defined using a foreign key?

**Comment by ironfroggy** [comment]
i think it was just a typo @pkdash

**Comment by hyi** [comment]
@pkdash I am assigning this to you, feel free to close or continue to work on metadata refactoring if you think there are still work to be done outlined in this issue.
