### ISSUE TITLE
Make content file required for resource to be public

### ISSUE THREAD

**Issue by pkdash** [hydroshare/hydroshare#693]
In addition to the required metadata elements, a resource must have content files where applicable before it can be made public.

**Comment by hyi** [comment]
Should this at-least-one-content-file requirement be enforced for all resource types (i.e., not only for timeseries resources) before the resources can be made public?

**Comment by pkdash** [comment]
I am not sure about the ref timeseries. Does it need any content file?

**Comment by horsburgh** [comment]
Any resource types that by definition reference content stored elsewhere (including referenced time series) would not require content files for making them public.

**Comment by pkdash** [comment]
@horsburgh Do we also need to apply content file(s) requirement for making a resource discoverable?

**Comment by pkdash** [comment]
@horsburgh Also I assume we have to make a resource private in the event of user deleting content files of a resource that is public.

**Comment by horsburgh** [comment]
Hmmmm...  I'm not sure.  I think we could go either way on this one @pkdash.  We have specified that a private resource can be discoverable.  In that case users can find a private resource without having access to the content files.  So, a discoverable resource to which content files have not yet been added seems somewhat analogous.  And, there are referenced resources that will not have content files that should be discoverable.  So, we could just decide that resources do not have to have content files to be discoverable, which would then apply across all resource types.  

What do others think?

**Comment by dtarb** [comment]
I think that the completeness rules for public and discoverable should be the same.  So the only resources for which files are not required to be discoverable or public are reference resources which do not have files as part of their content.

**Comment by pkdash** [comment]
This has been resolved.
