### ISSUE TITLE
Allowing Change of Email

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#695]
This supercedes #49 which I am closing.  The recommended email (per Caktus report) is:
- On registration, user verifies one email address and this is marked both as Verified and Primary.
- User can add any number of Secondary email addresses to their account, each of which is initially marked Unverified until they verify through a link to that e-mail address.
- User may change their Primary e-mail address at any time to any of their already Verified Secondary email addresses.
- User may remove any Secondary email address.
- User may not remove the current Primary email address.

**Comment by hyi** [comment]
@mauriel133 I am initially assigning this to you since you are the champion for profile pages. Feel free to reassign it to me if needed.

**Comment by dtarb** [comment]
Closing.  Email changing is working (and has been for a long time now).
