### ISSUE TITLE
Manage access should not allow permissions to be set for stale inactive accounts

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#700]
I noticed when enabling access to a resource that two accounts came up for one person.  Looking into it I found that one was an inactive account (the user had lost the confirmation email and created another account).  One account was active for the email that had been validated, one was inactive.  Manage access should not allow granting access to inactive accounts, and should not offer these accounts and options for a user to select.  Going further, we should purge inactive accounts after an expiry period (e.g. 24 hours) if the validation email has not been clicked.  This frees up the email address for a user to try again later and not be blocked because and account with that email exists.

**Comment by hyi** [comment]
@alvacouch Has this issue been resolved?

**Comment by mjstealey** [comment]
fixed and deployed
