### ISSUE TITLE
HydroShare about pages

### ISSUE THREAD

**Issue by mjstealey** [hydroshare/hydroshare#702]
Create framework for Laura to add content for various semi-static pages related to HydroShare.

![screen shot 2015-11-05 at 11 11 16 am](https://cloud.githubusercontent.com/assets/5804626/10974019/03d5b742-83ae-11e5-92ef-b52b18d97766.png)

**Comment by hyi** [comment]
@mjstealey Not sure whether this has any connection to the help page VM you set up for the team to collectively edit help pages, and not sure whether this is still in active state now.

**Comment by mjstealey** [comment]
implemented as pages.hydroshare.org and should be re-evaluated from there
