### ISSUE TITLE
Downloading public resource bag without logging in wrongly requires authentication

### ISSUE THREAD

**Issue by hyi** [hydroshare/hydroshare#703]
This problem happens on www.hydroshare.org (release 1.6.1 newly deployed today) but works fine on the pre-release 1.6.1 deploy on beta.hydroshare.org (deployed yesterday afternoon). The only additional code brought in since yesterday afternoon after pre-release 1.6.1 was deployed on beta is the oauth-server branch which was merged into develop prior to 1.6.1 release deploy on www. So this problem appears to be caused by oauth-server code which also includes some oauth-related REST API code from @selimnairb. @ironfroggy @robline @selimnairb, any idea on what is going on with this issue? This needs to be patched as a hotfix to release 1.6.1 if it can be resolved quickly.

**Comment by mjstealey** [comment]
This is also evident on https://alpha.hydroshare.org.
alpha is presently a parallel deploy of the same tag (1.6.1) that was used for www.

**Comment by hyi** [comment]
![image](https://cloud.githubusercontent.com/assets/476302/10923992/e9a46c18-8251-11e5-9203-04ed96c2e080.png)

**Comment by dtarb** [comment]
And can we figure out an automated test for this so it is caught before deploy in the future.

**Comment by hyi** [comment]
@dtarb Just created an issue to add unit test for bag downloading https://github.com/hydroshare/hydroshare/issues/706

**Comment by mjstealey** [comment]
> Just created an issue to add unit test for bag downloading #706

This error seen here requires a functional test definition, not a unit test.
Some workflows should be drawn up around the use cases here prior to implementation.

**Comment by dtarb** [comment]
Thanks.  I confirmed it worked, at least for one file.
