### ISSUE TITLE
Resource creation file validation peculiarity

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#707]
There is an unusual case that occurs in resource creation when files come from local disk and iRODS.  Multidimensional (netCDF) resources are supposed to only have one nc file.  However in creating one I selected a nc file from local disk.  I then realized that I actually wanted to load a file from iRODS so selected a file from iRODS.  I was unable to unselect the selection of the file from local disk and when I pushed create resource button the system loaded both files resulting in an improperly formed resource containing two nc files.

**Comment by cuahsimarko** [comment]
Unable to reproduce: added local file, selected iRODS file, was able to use the trash can and remove local file.

![image](https://user-images.githubusercontent.com/45397838/56606663-be330e80-65d4-11e9-8e2a-d14a6dfbde23.png)
@dtarb can you confirm this is no longer an issue?

**Comment by dtarb** [comment]
Given that we are migrating away from multidimensional resources, even if this is still an issue, we do not need to address.  Closing.
