### ISSUE TITLE
HISTimeSeries new design phase 2

### ISSUE THREAD

**Issue by zhiyuli** [hydroshare/hydroshare#708]
This issue is the second phase of RefTS new design (#502). Will focus on the following problems: 

1)  remove outdated/redundant code; reformat non-standard code

2) bag problem: In Phase 1, RefTS only stores metadata (referenced url and etc.) in Django database and will download the most recent data (WaterML) on the fly when the user clicks download button. No metadata or resource files are stored on IRODs. Is this acceptable? @dtarb @danames @horsburgh @jsadler2  

3) in Phase 1, the whole "Content" section (resource file list) in generic resource template has been overridden to implement "download the most recent data" feature. However it broke the access control rules that the original "Content" section applied. Need to find out how to override a sub-section without breaking access control.

4) fix all broken testing code

**Comment by dtarb** [comment]
I think you still need a resourcemetadata.xml file in iRODS.  I think that this will then trigger a resourcemap.xml that gives the existence of the resourcemetadata.xml file and other bagit, manifest and tagmanifest files.  This may seem like a lot, but most of this is being automatically generated and I think it is required for consistency and machine readability across all our resources.

**Comment by zhiyuli** [comment]
@dtarb @danames Also I think the requirement for a "generic referenced resource type" becomes more clear...it is different from "regular data resource type". The user does not need to upload any physical files. What is needed is just a link (URL). The HIS Time Series resource type and the App/Tool resource type are two specific cases and should inherit "generic referenced resource type". Maybe in the future we will have referenced netcdf res. type, referenced webservice res. type...

**Comment by hyi** [comment]
Should RefTimeSeries resource type have all standard science metadata elements that all resource types have? If so, I think it can be viewed as a specific resource type (just like other resource types) with perhaps the reference URL encoded in Source metadata element, but does not have content files (although download needs special processing if on-the-fly download from referenced source needs to be implemented).

**Comment by dtarb** [comment]
@hyi yes it should have the same standard science metadata as generic resources, so is just a hopefully simple small extension of the base resource type.  Downloading of the bag does not need to do on the fly downloading of content from the referenced source.  However tools that operate on the resource may support downloading.  How this is implemented is up to the reference resource tool developer.  It may be a loosely coupled Tethys app (as @zhiyuli and @danames are pursuing), or it may be implemented as part of the resource model code (as @gantian127 is doing for netCDF).  The particular choice depends on the implementation and functionality.

And @zhiyuli yes we would like to have other types of referenced resources that for example point to OpenDap services for NetCDF, OGC WFS services for geographic features, OGC WCS services for geographic rasters, models hosted elsewhere (to address #488 for @goodalljl and @mohamedmorsy) and so on.

**Comment by zhiyuli** [comment]
closed. already merged to release 1.7.0 months ago
