### ISSUE TITLE
Allow full set of files associated with shapefiles in geographic feature

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#710]
I encountered a shapefile that had a .cpg file.  This will not load.  See http://webhelp.esri.com/arcgisdesktop/9.3/index.cfm?TopicName=Shapefile_file_extensions.  This is a legitimate shapefile component.  It would be better to see if there is a more recent authoritative source for all these extensions, as the link above is 2008, and there may have been others since.

**Comment by dtarb** [comment]
Clarification.  This limitation appears to only occur when the .CPG caps extension occurs (which was the case for the example I encountered)
![capture](https://cloud.githubusercontent.com/assets/3456833/10948745/5ee87880-82ec-11e5-8ffa-fbe02dad95dc.PNG)

**Comment by zhiyuli** [comment]
@dtarb The cpg file is already allowed to upload. I can confirm it in the code:
    
    def get_supported_upload_file_types(cls):
        # See Shapefile format: http://resources.arcgis.com/en/help/main/10.2/index.html#//005600000003000000
        return (".zip", ".shp", ".shx", ".dbf", ".prj", ".sbx", ".sbn", ".cpg", ".xml", ".fbn", ".fbx", ".ain",
                ".aih", ".atx", ".ixs", ".mxs")

So I am guessing it is a different problem. Can you send me your shapefiles?
Thanks

**Comment by mjstealey** [comment]
> The cpg file is already allowed to upload

Is your code case sensitive by chance? (.cpg vs .CPG)

**Comment by zhiyuli** [comment]
@mjstealey I think you are right. Thanks. I will look into this.

**Comment by zhiyuli** [comment]
@dtarb @pkdash @hyi @mauriel133 

I just find this issue also exists in GeoRaster and NetCDF. Upper case file extension causes check failure.
![image](https://cloud.githubusercontent.com/assets/10070599/10956509/7a5f0f0c-8319-11e5-80de-5e02bd29cc58.png)

**Comment by zhiyuli** [comment]
merged and tested on dev
