### ISSUE TITLE
User with edit permissions can remove ownership from a user in the case where there are multiple owners

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#716]
The following sequence demonstrates this:

- User A creates a resource
- User A assigns user C as Owner
- User A assigns user B as editor
- User B logs in and edits the resource
- User B enters manage access
- User B changes access level of user A to can view.  (This is an bug as user B should not be able to demote user A who is an owner)
- User A now only has view permissions so is no longer able to edit the resource (this was validated as user A)
- User B deletes user A as Can View.  Now user A has no permissions on this resource and was effectively removed from it by user B who only had edit permissions.

@alvacouch, @pkdash  please check this.

**Comment by alvacouch** [comment]
Discussed with Pabitra and Dave via email. Suggested fix is to use the Owner privilege to override the offending privileges when authorized, using the "unshare" function. Then assert the appropriate protection. Later, we can put this inside "share_resource_with_user" but that will require significant changes to test suite, etc.

**Comment by alvacouch** [comment]
Actually, I need further information to suggest a fix.  Could be a bug in access or a bug in the UI use of access.  It is most likely a bug in both. The key issue is that one should not be able to demote an owner as a non-owner. This should be stopped in the API itself, so that even if the UI allows it, the API won't. Then we work on the code that considers it possible and stop that.

**Comment by pkdash** [comment]
I think it is a bug in the access control API. The API allows to demote any privilege of a user by a grantor as long as the grantor has a privilege which is => privilege the grantor is granting. It doesn't consider what privilege the user has currently before demoting.

**Comment by gantian127** [comment]
@pkdash would you please close this issue if you think it is fixed? Thanks

**Comment by pkdash** [comment]
@gantian127  Since this issue was opened by @dtarb I shouldn't be closing this. Though I have fixed it in the backend code, not sure how the UI is using the modified backend code. May be @mauriel133 can comment on this.

**Comment by dtarb** [comment]
Seems to be working properly on www.
