### ISSUE TITLE
Manage access interface shows ability to delete owner for editors where there are multiple owners.

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#717]
The following sequence illustrates this bug, which is a manage access appearance bug (not an actual access control bug)

1.	User A creates a resource
2.	User A assigns user C as Owner
3.	User A assigns user B as editor
4.	User B logs in and edits the resource
5.	User B enters manage access.  At this point the interface displays an X next to each owner giving the impression that they can be deleted.  
6.	User B clicks the X from user A's access.
7.	User A's entry in manage access disappears giving the impression that their access has been removed.  However after close and refresh user A is back on the list indicating that access was not removed.  However User B should not have been presented with the X to suggest they can delete users with owner settings.

**Comment by mauriel133** [comment]
I've made changes accordingly that disables parts of the interface for granting access that the current user doesn't have.

**Comment by alvacouch** [comment]
We need to change the API to avoid the ability to make the change.

**Comment by pkdash** [comment]
I plan to make API change.

**Comment by mauriel133** [comment]
Is this still an issue?

**Comment by dtarb** [comment]
This is fixed.
