### ISSUE TITLE
Resources listing does not persist filter when advancing to next page

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#720]
A user (me) has 21 resources owned.  If I click on owned by me on the resources listing, I see the bottom indicate.  Results 1-20 of 21.  However if I click on either the >> or >>| buttons to advance to see the next page (that should only be one resource) I get to a page that shows 21 to 40 of 104.  The filtering by owner has been lost.

**Comment by pkdash** [comment]
The same problem exists for 'editable by me'.

**Comment by pkdash** [comment]
@dtarb I think this issue has been resolved with the implementation of the new 'my resources' page. Please close this issue if this has been resolved.

**Comment by dtarb** [comment]
Not sure how MyResources now handles paging.  With 24 resources it is just one list.  I'll close.  If there are further problems a new issue can be created.
