### ISSUE TITLE
Implement updateScienceMetadata REST end point

### ISSUE THREAD

**Issue by selimnairb** [hydroshare/hydroshare#723]
Implement [updateScienceMetadata](https://github.com/hydroshare/hydroshare/blob/master/docs/DesignDocs/API/index.md#hydroshareupdatesciencemetadatapid-sciencemetadata----pid) REST end point.

**Comment by selimnairb** [comment]
Also fix GET /hsapi/scimeta to return properly serialized XML+RDF.  The current implementation returns an escaped string rather than raw UTF-8 XML:

    "
    <?xml version=\"1.0\"?>\n
    <!DOCTYPE rdf:RDF PUBLIC \"-//DUBLIN CORE//DCMES DTD     2002/07/31//EN\"\n\"http://dublincore.org/documents/2002/07/31/dcmes-xml/dcmes-xml-dtd.dtd\">\n
    <rdf:RDF 
    xmlns:dcterms=\"http://purl.org/dc/terms/\" 

This makes for unnecessary awkward handling by user agents.

**Comment by selimnairb** [comment]
This is part of #299

**Comment by Castronova** [comment]
@sblack-usu  close or act on if needed

**Comment by sblack-usu** [comment]
This is covered with [bag ingestion](https://github.com/hydroshare/hydroshare/pull/3928).
