### ISSUE TITLE
Refactor resource access permission checks

### ISSUE THREAD

**Issue by selimnairb** [hydroshare/hydroshare#729]
All resource access control decisions should be evaluated using a single function, that being hs_core.views.utils.authorize().  For example, this method should be used in place a manual calls in (here)[https://github.com/hydroshare/hydroshare/blob/master/hs_core/page_processors.py#L48], and (here)[https://github.com/hydroshare/hydroshare/blob/master/hs_core/page_processors.py#L73].

Also, we need to write extensive unit tests to test all combinations of hs_core.views.utils.authorize().

**Comment by mjstealey** [comment]
@selimnairb - is this still an issue?

**Comment by pkdash** [comment]
@mjstealey I think it is still an issue.

**Comment by pkdash** [comment]
This has been resolved. Closing.
