### ISSUE TITLE
When editing the spatial coverage information, the invalid value can be saved as metadata

### ISSUE THREAD

**Issue by gantian127** [hydroshare/hydroshare#733]
I just test to enter an invalid value for spatial coverage metadata as "Box" (See graph below). Although there is no bounding box shown in the map, the value can still be saved as metadata in the system.

![graph](https://cloud.githubusercontent.com/assets/5016511/11132835/ee7935ae-8957-11e5-809c-d4997938d93f.png)

**Comment by gantian127** [comment]
Logic to check the bounding box:
1 North lat and South lat should be in [-90,90], North lat > South lat
2 East lon and West lon should be in [-180,180], East lon > West lon

**Comment by hyi** [comment]
@pkdash assigning to you for initial investigation.

**Comment by pkdash** [comment]
@gantian127 See if this can be closed.

**Comment by pkdash** [comment]
@gantian127 Should this be closed?

**Comment by gantian127** [comment]
@pkdash I just tested on www site. It seems that when I enter 0 value in any of the fields, the system won't save the value. 
![image](https://cloud.githubusercontent.com/assets/5016511/16999402/ff531e7e-4e7a-11e6-93e2-9b88a67d8c5c.png)

**Comment by pkdash** [comment]
@gantian127 What's the status of this issue?

**Comment by gantian127** [comment]
@pkdash I think this issue still exists. When I type lat=0 and lon=20. It shows the error below:
![image](https://user-images.githubusercontent.com/5016511/28475702-9093043a-6e0a-11e7-9025-dcfa2b8fe113.png)

**Comment by aphelionz** [comment]
@pkdash @gantian127 assigning this to myself to fix

**Comment by pkdash** [comment]
Thanks @aphelionz

**Comment by Castronova** [comment]
This has been resolved.
