### ISSUE TITLE
Browsing for files to add to resources

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#74]
When browsing to add multiple files to a resource, the file names selected should be listed when there is more than one file.

![capture](https://cloud.githubusercontent.com/assets/3456833/5793070/fc16087a-9f03-11e4-8290-900e1cac735e.JPG)
List files selected rather than just indicating 2 files selected.  

If a user browses again the files they select should be added to the list, rather than the list being replaced.

A user should be able to delete files from the files selected.

**Comment by aphelionz** [comment]
@hyi @dtarb @mauriel133 Where are we at on this one?

**Comment by hyi** [comment]
@aphelionz This is an enhancement low priority issue, I don't think it has been worked at yet.

**Comment by aphelionz** [comment]
@hyi thank you

**Comment by ChristinaB** [comment]
Nice work!  
I suggest adding a small bit of help text near the Create Resource button such as "When you click Create Resource, the files will be uploaded to the HydroShare server. [Click here to learn more about next steps to share and formally publish your data.  
](https://pages.hydroshare.org/sharing-and-privacy/formally-publishing-resources/)

Also, add a Create Resource button on the upper right was mentioned in the call. Two buttons? Or one?

**Comment by dtarb** [comment]
Work on this issue has generated changes to the Create Resource page.  On the new create resource page (deployed on beta) I find the following aspects non intuitive
1. Below where it says "Select a resource type" there is a single button "Composite".  Nothing about that button indicates that if I click on it I will get a drop down list.  Can there be some sort of drop down indicator (inverted triangle is common) to encourage clicking this drop down.
2. In the "add your files" box it says "or click to upload".  But it is not clear to me "where" I should click.  I find that clicking on the grey area gives me the dialog to upload, but it would be better if there was an indication in the grey area that I should click there.

@mauriel133

**Comment by dtarb** [comment]
tested on beta.  OK
