### ISSUE TITLE
Profile page followup improvements

### ISSUE THREAD

**Issue by Maurier** [hydroshare/hydroshare#741]
- [x] We need to have the list of resources sorted by time (coming from the back end) to populate the recent activity list.
- [ ] Get a list of recent comments made by the profile user as well to add to the recent activity list.

Feel free to add any suggestions.

**Comment by cuahsimarko** [comment]
@Lizabrazil @Maurier do we still want the recent comments? Alva/Manish are working on Recent Activity now...

**Comment by horsburgh** [comment]
Sure, but I think we should likely be doing less on the profile page and more on the dashboard page. Hence - I think we should close this issue and open any appropriate issues related to recent comments on the dashboard. I'm not sure we need to display recent comments on the dashboard, but we probably should be notifying resource owners about comments that have been posted and then notifying comment posters when another comment/response has been posted.

**Comment by Lizabrazil** [comment]
Agreed, let's close this and reassess the ability to add notifications  potentially on the dashboard. Just from my intuition, I would think a user would only want to know when others comment on their resources, and not as much about the comments that they made to other resources.
