### ISSUE TITLE
Create Workflow Resource Type

### ISSUE THREAD

**Issue by mohamedmorsy** [hydroshare/hydroshare#748]

**Comment by hyi** [comment]
Adding functionality of workflow execution triggered by an execute button from this Workflow resource type landing page.

**Comment by goodalljl** [comment]
@mohamedmorsy Checking on status of this. There hasn't been much activity recently and I don't think it is a high priority item, so I moved it to backburner. Let me know if you feel differently.

**Comment by cuahsimarko** [comment]
Workflow Resource Type not on roadmap.
