### ISSUE TITLE
SWAT Model - Deleting certain resource specific data on one resource also deletes them on all other SWAT Model resources

### ISSUE THREAD

**Issue by shawncrawley** [hydroshare/hydroshare#754]
Deleting certain resource specific data on one resource also deletes them on all other resources. I'll give a real example, which is how I found the bug. The following was done on both playground and dev: 
I created a SWAT Model resource (swat 1) and added all seven of the Model Parameter options as seen below.

"swat 1":
![Screenshot 1](http://www.zimagez.com/miniature/screenshot2015-12-0219-00-33.php)
Then I created a second SWAT Model resource (swat 2) and added only the last four Model Parameter options as seen below.

"swat 2":
![Screenshot 2](http://www.zimagez.com/miniature/screenshot2015-12-0219-04-34.php)
Then, I went back to update "swat 1" by removing from this resource the same four Model Parameter options that I had just added on "swat 2" as seen below.

"swat 1":
![Screenshot 3](http://www.zimagez.com/miniature/screenshot2015-12-0219-07-27.php)
Oddly, when checking back on "swat 2" there were no longer any Model Parameters associated with this resource. Remeber, the same 4 parameters I deleted from "swat 1" were the only parameters associated "swat 2". So when deleting them from "swat 1" they were also deleted from "swat 2."

I actually found this issue because I found it first in the WebApp resource type that I have been working on. I had copied code from the models.py of the hs_swat_modelinstance relating to the ModelParameter and ModelObjectives classes. The common denominator between these classes and the class from my app that mirrors their code is that they all implement a ManytoManyField relationship in their database. Also, based on the behavior of the bug, it seems likely that the erroneous code is in the overridden "update" function since the problem happens when updating the metadata. I, too, will continue to try to find the root of the problem and fix it, but I thought I should let you all know since in the case of the SWAT Model, the buggy code is already pushed live.

**Comment by shawncrawley** [comment]
It was a very simple fix, but I'll give an in-depth explanation for those who care.
 
##### Explanation of the root problem
If I understand it correctly, with **`models.ManytoManyField(AssociatedClass, **kwargs)`** Called within another class, InitialClass, the created instances of the AssociatedClass are shared between all of the instances of the class that declares the association (InitialClass). 
The **`create()`** function actually creates instances of the AssociatedClass and makes them available to all future instances of InitialClass, but does not associate InitialClass objects to AssociatedClass objects. 
The **`add()`** function must be called to actually make the association between the two. 
On the other hand, the **`delete()`** function will delete the instances of the AssociatedClass object, thus disassociating them and making them unavailable to all existing instances of InitialClass. 

##### Explanation of the solution
This is what was happening in the code under the **`update()`** function for both ModelParameter and ModelObjectives classes with `swat_model_parameters.model_parameters.all().delete()' and `model_objective.swat_model_objectives.all().delete()`, respectively.
The function that actually disassociates the instances, rather than deleting the AssociatedClass objects is `clear()`. This clears ALL associations, and is thus called without use of the `.all()` filter (use `remove()` to remove a single association). 

### To the point solution
So if you change the above code to **`swat_model_parameters.model_parameters.clear()`** (replace line 165) and **`model_objective.swat_model_objectives.clear()`** (replace line 72) it should work as expected.

**Comment by gantian127** [comment]
@pkdash would you please close this issue, if you think it has been fixed? Thanks
