### ISSUE TITLE
Near Real-time Search Index Updates

### ISSUE THREAD

**Issue by ironfroggy** [hydroshare/hydroshare#755]
As a near-term solution the indexes in Solr for Haystack will be updated nightly. As a long term solution we must update the index selectively and on-demand as changes are made to resources.

**Comment by ironfroggy** [comment]
Haystack uses Signal Processors to trigger updates when objects are changed, like on the `post_save` signal that is triggered when the saving of an object is complete. [1] These work out of the box for most uses, but I think we're going to find some customization is necessary because of the complicated nature of metadata in Hydroshare (more on that below). In addition, indexing can be costly and extend the time to complete an HTTP request that updates models, as the triggered index update can take more time than the database updates. Haystack provides a helper, `haystack-celery` [2], that can shift that load into celery tasks that are run in the background. Celery is already installed and configured in the project, but it doesn't seem to actually be *used* so I think we need a preliminary task to clean that up and confirm its working in all environments. [3]

[1] http://django-haystack.readthedocs.org/en/latest/signal_processors.html
[2] https://github.com/django-haystack/celery-haystack
[3] https://github.com/hydroshare/hydroshare/issues/756

**Comment by hyi** [comment]
@alvacouch As we briefly discussed during all hands meeting, this could be probably done by directly calling haystack API without using celery for a specific index update. So I am re-assigning this to you (if you ask @xuezhaokun to work on it, you can then assign it to @xuezhaokun) for initial investigation. If your initial investigation indicates celery is still needed for performance concerns, you can reassign it to me with more detailed info on what tasks are needed for haystack-celery to run tasks in the background.

**Comment by alvacouch** [comment]
See #1164, which supersedes this issue.
