### ISSUE TITLE
apps.hydroshare.org landing page meaningful content

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#758]
The apps.hydroshare.org landing page should have meaningful content on it or redirect to https://apps.hydroshare.org/apps/.  Even though the direct link from hydroshare is to the /apps page, browsers are likely to end up at the top page too so it needs to be properly handled.

**Comment by hyi** [comment]
@dtarb Can you check to see if the current behaviour is acceptable or not? It appears to be redirected to https://apps.hydroshare.org/apps after asking for authorization.

**Comment by dtarb** [comment]
Redirect is working.
