### ISSUE TITLE
The "Sign into IRODS" button needs to be explained (or removed)

### ISSUE THREAD

**Issue by danames** [hydroshare/hydroshare#759]
When  you are creating a new resource, there is a large green button instructing one to sign into iRODS. This is not part of the simple resource creation workflow and is a bit of an extra option. But it is sitting there glowing green at me making me feel like I really need to click it in order to properly create a resource. 

I suggest we comment out this function for the AGU release and then come up with a better way to explain that optional functionality to users and reactivate it later.

**Comment by dtarb** [comment]
Let's not remove.  It is useful functionality.  Lets figure out a clean clear label and explanatory text.

**Comment by danames** [comment]
It's interesting functionality, but I have this feeling that 98% of the target audience won't know what to do it and won't have an iRODS account. So let's reduce it's presence? Maybe just blue hypertext that says, 

"If you have a resource on an iRODS server, you can add browse to it by logging in here."

**Comment by dtarb** [comment]
Please suggest a specific color, label and perhaps adjacent text and then I think this is a simple interface change that could easily be made, by @hyi or @pkdash.  Maybe 98% of the target audience now will not be able to use this, but this is an important part of the strategy to work with big data "off the desktop" which is one of the capabilities I am talking about in presentations.

**Comment by danames** [comment]
If you want to load a resource from an iRODS into HydroShare, you may do so by logging into your iRODS server here.

"here" should be blue and underlined and will be the link to log into the iRODS server.

**Comment by hyi** [comment]
@danames I have changed irods sign-in as you suggested and deployed it to sandbox.hydroshare.org. Please take a look and see whether it looks fine to you now. @dtarb Please take a look as well on sandbox. If you both think it looks fine now, I will create a PR for code review.

**Comment by danames** [comment]
That works for me. Thanks Hong.

**Comment by hyi** [comment]
@dtarb Can you take a look at sandbox also and let me know whether irods sign-in and browse appearance change looks OK to you or not?

**Comment by dtarb** [comment]
Looks good.  I suggest some small changes:
"If you want to load a **file** from an iRODS server into HydroShare, please do so by logging into **the** iRODS server here." Period at end.  I like punctuation.

**Comment by dtarb** [comment]
Actually the above should read "files" as you can load more than one file for some resource types.

**Comment by hyi** [comment]
@dtarb Have made the correction as you suggested above. Check out sandbox and see whether it looks good to you now.

**Comment by danames** [comment]
Looks good to me. Thanks Hong.

**Comment by dtarb** [comment]
+1

**Comment by hyi** [comment]
@danames @dtarb The fix has been merged and build on dev.hydroshare.org. You can test it out and close this issue if things are working on dev.

**Comment by danames** [comment]
Just tested on dev.hydroshare.org. The new text and link look good. Closing this issue.
