### ISSUE TITLE
Only allow user editing of some geographic raster metadata

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#76]
The following geographic raster metadata fields should be user editable
- coverage place/area name
- name
- variable
- units
- method
- comment

The following geographic raster metadata fields should be read from the geographic raster file and never be user editable.  User editing of these would result in an inconsistency between the file and the metadata which should be avoided.
- rows
- columns
- cellDataType
- bandcount

The following geographic raster metadata fields should be read from the geographic raster file and not editable from the landing page.  
- Coverage projection
- Coverage units
- Coverage northlimit
- Coverage eastlimit
- Coverage southlimit
- Coverage westlimit
- CellSizeXValue
- CellSizeYValue
- CellSizeUnit
- noDataValue
However if this metadata is missing or incorrect there is a need for a user to be able to enter or correct this information.  A separate tool should be developed "Edit raster file metadata" that opens an editing interface where these fields may be entered or adjusted.  Then upon save this metadata should be written back to the file.

**Comment by hyi** [comment]
Editing for the selected extended metadata elements for raster resource type is implemented as indicated in this issue (i.e., noDataValue and all subelements of BandInformation are editable), which is pushed to my 82-raster-resource-new-workflow feature branch. The only issue is with coverage northlimit, southlimit, westlimit, and eastlimit, which are currently editable as implemented in hs_core as standard science metadata elements. To make these fields non-editable for raster resource type, Pabitra's input is needed in terms of whether we should make these fields non-editable like coordinate projection and units at the core metadata level, or provide some attribute settings that allow a specific resource type to override the default behavior to make these fields non-editable for the specific resource type.

**Comment by hyi** [comment]
Removed ready for testing label - more work is needed to make noDataValue not editable when it is extracted from the uploaded file, and only editable when no value is extracted.

**Comment by hyi** [comment]
finished additional work needed for making noDataValue not editable when it is extracteed from the uploaded file and only editable when no value is extracted. Fix pushed into github and a pull request has been created to merge into develop. One issue remains to make Coverage northlimit, southlimit, westlimit and eastlimit not editable for Raster resource type, which needs further discussion with Pabitra to get this taken care of by core metadata that allows specific resource type to set individual fields/forms for core metadata elements editable or not.

**Comment by hyi** [comment]
Tested it on alpha and metadata editing is working now except for Coverage metadata editing. Adding ready for testing label. Coverage metadata editing is captured in another issue #225, so suggest to close this issue if other metadata editing (except for Coverage) works.

**Comment by dtarb** [comment]
See following Alfresco document for details on editable fields for raster resource https://my.alfresco.com/share/s/DeXkAhEgS8GjrgTWOSpp0w

**Comment by dtarb** [comment]
Working satisfactorily on www.hydroshare.org
