### ISSUE TITLE
If you try to create a user with a user name that is already taken then you get a hard crash

### ISSUE THREAD

**Issue by danames** [hydroshare/hydroshare#760]
Worse yet, it seems that the email to confirm the user is sent to the new address. So I might have an opportunity to hijack someone else's account by simply creating a new user with the same user name someone else has already use. I haven't tried this hack, but maybe we just need to avoid it by giving a clean error message for when a user name is re-used. 

CAN THIS BE FIXED BY AGU?

This will really be bad for our novice AGU users when the first thing they do is try to create a user account "david" and find that they get a hard crash since "david" is already taken and then complain that they crashed the system in the first 30 seconds...

What are our options?

**Comment by dtarb** [comment]
@danames Can you check the behavior on www.hydroshare.org (the 1.6.2. deploy).  It seems it was acceptable a while back, but may have regressed.  If it is acceptable now, we need to strive to keep the www behavior.

**Comment by danames** [comment]
I just tested on www.

Creating an account with the same email address gives this error:

* email needs to be unique

and shows the sign up form again.

However if you use the same user name you don't get a hard crash (like on Beta) but you get an error that says:

"Error:
An error has occurred"

It's not a useful error, but it's not as bad on www as on beta. But this is a concern since what we see on Beta is supposed to be a staging of what is going to be on www when we deploy it...

**Comment by hyi** [comment]
Debug is set to True on beta while set to False on www to give more useful error message for diagnosis on beta. I am in the middle of doing resource id preservation testing on beta, after I am done with it, I will set Debug to False on beta and compare the behavior on beta with www for this issue to check whether there is any regression issue has been introduced in the latest code base.

**Comment by dtarb** [comment]
It would be better if the "An error has occurred" said "That username is already in use, please select another", but this enhancement while desirable, is not a show stopper for 1.6.3 deploy.  @pkdash is this a message that could be easily added.

**Comment by hyi** [comment]
@danames @dtarb Have changed DEBUG setting to be false on beta and tested this issue out. Beta now exhibits exactly same behaviour as www, so confirmed no regression has occurred since 1.6.2 release.

**Comment by danames** [comment]
Excellent
