### ISSUE TITLE
Resource Publication - Draft Data Publication Agreement

### ISSUE THREAD

**Issue by horsburgh** [hydroshare/hydroshare#761]
Need text for a data publication agreement that users agree to when they choose to publish a resource.  Assigned to @dtarb but need contribution from @alvacouch.

See #15 for the main resource publication issue.

**Comment by hyi** [comment]
@dtarb @alvacouch @horsburgh Is it possible to draft the text for data publication agreement used in HydroShare now? I am currently using a place holder text for publication agreement asking users to agree before they can publish the resource, but it'd be great if I could have some draft agreement text to use before deploying to a VM for your testing.

**Comment by horsburgh** [comment]
@dtarb and @alvacouch - it also came up on the teleconference last week that we might want to consider running the text of that document past a lawyer to make sure our bases are covered.  Here's some text I took from the iUTAH Data Publisher's Agreement and modified to perhaps get us started on this. Feel free to modify at will.

https://docs.google.com/document/d/15knK4NOl0HLXkxRNmZfPDo_VqskvBT1iGUwH7cID1ek/edit#

**Comment by danames** [comment]
Instead of certifying that they are the creator, I think we should have
them certify that they are either the creator of the data OR that they have
permission from the creator of the data to publish it OR that the data are
in the public domain. Otherwise this looks really good to me. - Dan

**Comment by dtarb** [comment]
I have edited the HydroShare publication agreement at the Google Doc link @horsburgh provided above.  This addresses Dan's suggestion and a number of other changes to align it better with the [CUAHSI user agreement](http://hiscentral.cuahsi.org/agreement/CUAHSI user agreement 2014 final.pdf).  I will be asking Rick Hooper to have CUAHSI committees review this and address the question whether CUAHSI wants to run this past a lawyer.  In the interim @hyi please use the agreement as written to implement the services.

**Comment by dtarb** [comment]
I have added a Mezzanine Rich Text page https://www.hydroshare.org/publication-agreement/ with this content, so all that should be needed is links to it and adding it to the footer.  However this is on www.hydroshare.org as I did not know how to administratively add and push this through the development process so @hyi please fix any missteps I made (and let me know a better way to do this)

**Comment by horsburgh** [comment]
@dtarb - I think this should be something users agree to at the time of publication. It applies to each resource. Agreeing to it should be part of publishing a resource, like agreeing to a license agreement when installing software.

An alternative would be to have them agree to it once when they create their account. But, it is something that they should specifically agree to and not something they should be expected to find a link for in the footer of the pages.  But, it's probably also a good idea for it to be there as a reminder, etc.

**Comment by dtarb** [comment]
Yes I agree.  Users should click to agree to the publication agreement every time they formally publish a resource AND it should be added to the footer for all to see any time they want.

**Comment by hyi** [comment]
@dtarb @horsburgh @alvacouch @danames Here is a screen capture images of the publication dialog I have implemented to ask users to accept publication agreement before they can publish a resource in Hydroshare:
![publication_dialog](https://cloud.githubusercontent.com/assets/476302/12554912/af8c2f5c-c34c-11e5-99a7-ac3cf00636ac.png)
The users can click on the hyperlink which takes them to the rich text publication agreement page @dtarb created on www.hydroshare.org on a new separate tab on the browser, and the users have to click on the checkbox to agree to the agreement before "Publish" button is enabled to allow them to publish a resource. Please let me know whether this dialog for users to agree to publication agreement is sufficient and let me know any suggestions to change it for the better.

**Comment by dtarb** [comment]
I think that the entire publication agreement should be given in this box that pops up.  It is not that long and is more direct than asking them to click somewhere else (where they may not).

**Comment by hyi** [comment]
Putting the entire publication agreement in the pop up box makes the publication agreement info duplicate in two places which means if we have to change the wording, we have to remember to change it in both places to keep things in sync. Also, the entire publication agreement is pretty long for a pop up box which could obscure the important instructional messages we want users to know in the popup box. Users have to check the checkbox to agree to it anyway, and they are instructed to review it in bold strong text, if they don't want to review it but just want to go ahead to check the checkbox, I would assume they would do the same even when we put the entire agreement in the same pop up box although I agree it would probably force users to scan through some text of the agreement if we put the entire text in the popup box. Although I prefer to put it as a link as is currently implemented, but I can put the entire agreement in the popup box if that is what is decided meaning we have to bear the undesirable consequence that we have to maintain the agreement info in two different places.

**Comment by horsburgh** [comment]
@hyi - I would put it on the pop up in a fixed height, scrollable text box. This is how many software installation programs work, even though the license agreement may be VERY long.

**Comment by dtarb** [comment]
A clever programmer could figure out how to have the text in one place appear in two places to keep it in sync.

**Comment by hyi** [comment]
![publication_dialog](https://cloud.githubusercontent.com/assets/476302/12567381/c5d97388-c38c-11e5-935c-31cea72f653b.png)
@dtarb @horsburgh See the screen capture above for an updated publication dialog. I managed to directly use https://www.hydroshare.org/publication-agreement page created by @dtarb in this modal dialog without duplicating the publication agreement text so that the text could be maintained in one place. As you can see, it only shows the needed content portion of the page without header and footers. Let me know any further suggestions you have.

**Comment by dtarb** [comment]
Please change the words as follows.

Above box
_Please confirm that you accept the HydroShare Publication Agreement shown below.  Publication is **final** and once a resource has been published changes will require you create a new version of the resource._

In box include the header "HydroShare Publication Agreement"

Below box
_I accept the HydroShare Publication Agreement._

**Comment by horsburgh** [comment]
@hyi - I like @dtarb 's edits.  Otherwise, looks great.

**Comment by hyi** [comment]
![publication_dialog](https://cloud.githubusercontent.com/assets/476302/12582815/5c396e52-c40d-11e5-8454-7c998554fc07.png)
@dtarb @horsburgh Let me know if the dialog above looks good. To add the header "HydroShare Publication Agreement" into the box, I have to reduce the font of the header on publication agreement page on www from header 1 to header 2 to make it look good in the box which looks acceptable/good on the page as well.

**Comment by dtarb** [comment]
This looks good.  I suggest, if possible, to have the text in the publication agreement part wrap to a narrower column the same width as the box so a user reading it has to scroll in only one direction (up and down) and not scroll both up and down and left to right.  Make it easy for them to read.

**Comment by hyi** [comment]
@dtarb Good point. After spending some time tweaking the styles, I finally got rid of the horizontal scroll without affecting other display. See the screen capture below and let me know if you have any other suggestions. 
![selection_001](https://cloud.githubusercontent.com/assets/476302/12589498/1dd72932-c42c-11e5-9f46-289b3b6a31f4.png)

**Comment by dtarb** [comment]
I guess it is sort of passable.  It still shows the horizontal bar at the bottom that does not look very attractive, but at this point there seem to be more important things to do that to worry about this.

**Comment by hyi** [comment]
![publication_dialog](https://cloud.githubusercontent.com/assets/476302/12617717/dc106960-c4de-11e5-9e31-f66924037417.png)
@dtarb Agreed the disabled horizontal scroll bar should be removed. Managed to achieve this. See whether above screen capture looks good now.
