### ISSUE TITLE
Resource Publication - Map resource science metadata to Crossref deposit metadata

### ISSUE THREAD

**Issue by horsburgh** [hydroshare/hydroshare#762]
In order to register a DOI with Crossref for resource publication, HydroShare must create a deposit XML document for submission to the Crossref API.  So, we need to map the HydroShare science metadata elements to the required Crossref elements so the deposit XML can be automatically generated. 

* Crossref deposit metadata schema is here: http://help.crossref.org/deposit_schema
* Required, recommended, and optional metadata elements are at: http://help.crossref.org/elements
* Specifically for the "Database" content type: http://help.crossref.org/elements$Database

This issue is required for completion of #15.

**Comment by hyi** [comment]
@horsburgh @dtarb First and foremost question we need to address in order to map hydroshare metadata to crossref deplosit metadata schema is content type. Which content type (Journal, Book, Conference Proceedings, Dissertation, Report-paper, Standard, Database options in crossref) should we use for HydroShare? Needs to decide on content type first since required elements for different content types are different.

**Comment by hyi** [comment]
@horsburgh @dtarb Looks like "Database" content type is most appropriate for HydroShare. Is "Database" content type what we should use for HydroShare? Need confirmation. Thanks.

**Comment by horsburgh** [comment]
@hyi and @dtarb - in my initial investigations I was leaning toward the "Database" content type.  The other options didn't seem appropriate.  And, keep in mind, this is for their meta-database, not ours.  So, "Database" may not seem, appropriate for all HydroShare resource types, but neither are the others, so I would use "Database".

**Comment by hyi** [comment]
@horsburgh agreed. Will use "Database" for my initial implementation.

**Comment by dtarb** [comment]
I am happy with @horsburgh 's recommendation.  Do we know what this field is used for? It seems like others (DataOne?) may have had to deal with this for data too.

**Comment by hyi** [comment]
@horsburgh @dtarb I have coded to create crossref deposit xml file programmatically for a HydroShare test resource and the generated deposit xml file passed crossref metadata quality check with no error, so the generated deposit xml file is good to go for real deposit to crossref for DOI assignment. I am pasting the generated deposit xml file here for your perusal so that you can point out anything I did not map correctly or you want to add any more optional elements into this deposit xml file:
```
<?xml version="1.0" encoding="UTF-8"?>
<doi_batch xmlns="http://www.crossref.org/schema/4.3.6" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="4.3.6" xsi:schemaLocation="http://www.crossref.org/schema/4.3.6 http://www.crossref.org/schemas/crossref4.3.6.xsd">
  <head>
    <doi_batch_id>6f33d027c0444a248ddd9a7661235974</doi_batch_id>
    <timestamp>20160121170045</timestamp>
    <depositor>
      <depositor_name>HydroShare</depositor_name>
      <email_address>support@hydroshare.org</email_address>
    </depositor>
    <registrant>HydroShare</registrant>
  </head>
  <body>
    <database>
      <database_metadata language="en">
        <titles>
          <title>HydroShare Resources</title>
        </titles>
      </database_metadata>
      <dataset dataset_type="collection">
        <titles>
          <title>Test resource publication deposit xml with crossref</title>
        </titles>
        <doi_data>
          <doi>http://dx.doi.org/10.4211/hs.6f33d027c0444a248ddd9a7661235974</doi>
          <resource>http://localhost:8000/resource/6f33d027c0444a248ddd9a7661235974</resource>
        </doi_data>
      </dataset>
    </database>
  </body>
</doi_batch>
```

**Comment by horsburgh** [comment]
@hyi - a couple of questions:

1. Should the registrant and depositor name be HydroShare or CUAHSI?
2. What is the difference between the two title elements?  It looks like one is the title of a "Database" (i.e., perhaps the full set of registered HydroShare resources?) and one is the title of a "Dataset" (i.e., the resource you are currently registering).  Is that correct?
3. Is "Test resource publication deposit xml with crossref" the title of the resource you are testing registration on?

**Comment by hyi** [comment]
@horsburgh The answers to questions No. 2 and No. 3 are yes. I have the same question for question No. 1, currently I am using HydroShare although I did try to choose between HydroShare or CUAHSI. Let me know if I need to change to CUAHSI as the registrant and depositor including the email address we can use for depositor if we choose CUAHSI.

**Comment by horsburgh** [comment]
@hyi - perhaps we should do CUAHSI as the registrant and HydroShare as the depositor?

**Comment by hyi** [comment]
@horsburgh Sounds good. Will make the change accordingly unless I hear objections from others.

**Comment by horsburgh** [comment]
@hyi - In looking at the example XML file for a dataset at http://www.crossref.org/help/samples/dataset.xml, the DOI in the "doi" element is not URL encoded.  In your example it is.  Should it be?

**Comment by dtarb** [comment]
@hyi in the example above there is "localhost".  I assume that in a real deployment this will be replaced by www.hydroshare.org.

**Comment by hyi** [comment]
@dtarb Yes, in the real deployment localhost will be replaced by www.hydroshare.org. It is the resource URL in HydroShare the DOI will point back to as the response once DOI is registered and in effect.

**Comment by hyi** [comment]
@horsburgh good catch. I changed "doi" element to be 10.4211/hs.<resource_uuid> and also validated the deposit xml file to make sure it is still valid. I also changed registrant to be CUAHSI. See the updated sample deposit xml for a sample HydroShare resource above. I do want to point out that registrant element indicates the organization that owns the information being registered, according to http://www.crossref.org/help/schema_doc/4.3.5/4.3.5.html#database. So changing registrant to CUAHSI means CUAHSI owns all published HydroShare resources. Let me know if there is anything else I need to change to the deposit xml as shown in the xml sample above.

**Comment by horsburgh** [comment]
@hyi - this is a good point, and one that I hope is taken care of in the publication agreement.  In my opinion (not being a lawyer of course) we should make sure that the publication agreement grants to CUAHSI and the HydroShare team the right to publish the resource in HydroShare.  I think this constitutes effectively adding CUAHSI as an "owner" for published resources. This doesn't preclude CUAHSI from sharing ownership of course (i.e., the owners of the published resource will remain owners).

**Comment by dtarb** [comment]
Is it possible for our DOI's to have a readable short pattern, e.g.
10.4211/hs.2016.1, 10.4211/hs.2016.2 etc rather than
10.4211/hs.6f33d027c0444a248ddd9a7661235974
Sometimes DOIs are read from publication citations and typed in, and the GUID pattern makes this difficult.  It also takes up a whole lot of space in the citation line each time a resource is cited.

**Comment by horsburgh** [comment]
@dtarb - yes it's possible. We are in charge of constructing the DOI that gets deposited into Crossref and we must assure that each DOI is unique. But then we have to create and maintain an entirely separate identifier system for resources when we already have a unique identifier for resources.

**Comment by dtarb** [comment]
I think it is worth it, but would like to hear from @hyi, @ironfroggy, and @pkdash how hard it is.

**Comment by pkdash** [comment]
@ironfroggy and @hyi Do you see any issue with using the resource id (which I think an auto incremented sequential number) field to generate the DOI and store that in the resource doi field for a published resource?

**Comment by horsburgh** [comment]
@pkdash - One potential issue is that if the database has to be regenerated and those auto-incremented IDs don't end up being the same or get out of sequence, etc. that might cause some issues.  I think it would be better to use something explicit, but I don't have a feel for how likely this is to be a problem.

**Comment by pkdash** [comment]
@horsburgh You are right. In case of all resources getting migrated to a blank database, the IDs will get regenerated which likely to be different from the original. That would be a problem.

**Comment by hyi** [comment]
@pkdash @ironfroggy @dtarb @horsburgh Agreed that using primary key IDs to identify resources in DOI field is potentially problematic. Another option is to use <date>.<seq_no> in doi field, and generate <seq_no> dynamically each time a new resource is to be published by computing the largest sequence no in DOI field in our database and then increase it by one for the new DOI field. Not a good option, but put it on the table for discussion.

**Comment by pkdash** [comment]
As long as we handle any race condition for computing the next value for doi, it should work.

**Comment by hyi** [comment]
@pkdash Good point. Handling race condition in this case may be complicated and problematic. @ironfroggy any suggestions for a better alternative than using resource uuid in the DOI field?

**Comment by ironfroggy** [comment]
I don't think you should ever plan to "regenerate the database" in such a way that you change IDs which would break *lots* of things like all the foreign keys. If the database were ever lost the plan should be restoration form a full backup, which would restore the tables and rows with those existing IDs.

You should expect to and plan to rely on them.

**Comment by hyi** [comment]
@ironfroggy Agreed we should not change IDs in the database in normal situations. But we did have to erase database and regenerate them a couple of times in the past due to migration issues, with the second time caused by base resource model refactoring and access control additions in which we have to regenerate database from existing bags. If we can guarantee this will not happen again, that would be great, but I am not sure whether we are there or not, which prompted the concern to use primary key id in the doi field.

**Comment by ironfroggy** [comment]
If you plan on relying on any identifiers being relied on by outside sources, then you can never do that again. As long as that would break things, and it always will, then it is better to embrace that expectation.
