### ISSUE TITLE
My Resources Page: Limit the List of Resources to My Resources

### ISSUE THREAD

**Issue by horsburgh** [hydroshare/hydroshare#765]
In the transition to integrating the new Search/Discovery page, the My Resources page needs to be modified so that the list of resources the user sees contains only resources that meet the following criteria:
- Resources the user owns
- Resources that have been shared with the user (under any permission) by another HydroShare user
- Resources that the user specifically chose to add to their list of My Resources

Eventually, the full list will be:
- [x] **Owned by me**:  Restricts the list to resources owned by the current user.
- [x] **Editable by me**: Restricts the list to resources for which the user has edit permissions.
- [x] **Shared with me**: Restricts the list to resources that are not owned by the user but that have been shared with the user.
- [x] **Favorites**: Restricts the list to resources that have been “Favorited” by the user.  These resources may be owned by the user or not.
- [x] **Following**: Restricts the list to resources that the user has followed.
- [x] **Recent**: Restricts the list to resources that have been modified within a recent time period (e.g., last 5 days, or just sorts and groups resource by last modified date)
- [x] **Labels**: Restricts the list to resources that have been tagged with one or more selected labels.

**Comment by horsburgh** [comment]
This has been completed.  The only two filters we have not implemented are "Following" and "Recent".

**Comment by Maurier** [comment]
@horsburgh  This has been implemented now. Please confirm and close.

**Comment by horsburgh** [comment]
Done on production.
