### ISSUE TITLE
My Resources Page: Add Ability to Filter by Resource Type, Author, and Subject

### ISSUE THREAD

**Issue by horsburgh** [hydroshare/hydroshare#766]
On the My Resources page it is currently somewhat unclear how to use the filtering functionality. This can be improved by providing a simple drop down on the search box that has some commonly used filters to help users construct the the right syntax for the filter in the Search box.

﻿
![untitled](https://cloud.githubusercontent.com/assets/3485902/11601665/d972684c-9a91-11e5-9928-7ad9648ba3c7.png)

**Comment by mauriel133** [comment]
Implemented and working on www.

**Comment by dtarb** [comment]
Super!
