### ISSUE TITLE
Discovery:  Create Ability to Add a Discovered Resource to My Resources

### ISSUE THREAD

**Issue by horsburgh** [hydroshare/hydroshare#767]
When a user discovers a resource they are interested in and want to keep track of there needs to be an option on the list of discovered resources and/or on the landing page for a resources to add it to the users list of My Resources.

**Comment by pkdash** [comment]
I assume these are resources that either public or discoverable and the user doesn't have explicit access permission.

**Comment by horsburgh** [comment]
Correct @pkdash.

**Comment by horsburgh** [comment]
@alvacouch - This has been implemented on www.hydroshare.org by adding an "Add to My Resources" button to the landing page for each resource.  This seems to be working.  I can also click on the resource again, go to it's landing page, and remove it from My Resources by clicking on a red version of the same button.  

Unless we want to do batch "Add to My Resources" on the discover page by allowing users to select many discovered resources at once and then added them all at once, I suggest we close this issue.

**Comment by alvacouch** [comment]
We were planning on enabling batch from the discovery page, but Zhaokun is away until 18 Jan.

**Comment by horsburgh** [comment]
OK.  I will leave this open then.

**Comment by horsburgh** [comment]
I'm going to close this one as the original intent of the issue has been addressed by functionality that is already working and we haven't seen demand for the batch function.
