### ISSUE TITLE
My Resources Page: Implement Marking Favorite Resources

### ISSUE THREAD

**Issue by horsburgh** [hydroshare/hydroshare#768]
A user should be able to mark a resource as a favorite. This would make that resource appear in the list of the user's favorite resources.  This should be implemented in two places:

1. There should be a button on the resource landing page that a user can click to add a resource to their list of favorites
2.  There should be a button at the top of the My Resources page that would add whatever resources are selected in the list to the user's list of favorite resources.

![untitled](https://cloud.githubusercontent.com/assets/3485902/11601835/52644cb0-9a93-11e5-97df-5b356ae6fc2c.png)

Also, "Favorites" needs to be implemented as a filter in the list on the left of the My Resources Page.

**Comment by mauriel133** [comment]
Wouldn't the button in the landing page overlap with the functionality of the current button to add to My Resources.

**Comment by horsburgh** [comment]
@mauriel133 - "Add to My Resources" and "Add to My Favorites" are not the same action.  
* "Add to My Resources" is implemented now and I believe has the desired functionality.
* "Add to Favorites" would be an additional star button on the resource landing page that would add the resource to My Resources, but would also apply the "Favorite" tag so it would show up when you click on that filter.

We may also need another filter on the My Resources page that enables a user to see everything that they have added to their My Resources list using the "Add to My Resources" mechanism (e.g., resources they don't own, that they don't have editing permissions on, that have not specifically been shared with them, and that are not in their favorites - but that they have for some reason added to their list by clicking on the "Add to My Resources" button).  Right now you can't isolate these - they only show up when you have no filters applied.  If you (or others) agree - I will add this as a separate issue.

**Comment by hyi** [comment]
@horsburgh @mauriel133 I believe this has been implemented. Can you verify and see if this issue can be closed?

**Comment by horsburgh** [comment]
Implemented and working on www.hydroshare.org.  Closing.
