### ISSUE TITLE
My Resources Page: Implement Resource Labels

### ISSUE THREAD

**Issue by horsburgh** [hydroshare/hydroshare#769]
The My Resources page will enable users to organize resources using labels. The following is needed to implement this:

- [x] Implement a label button on the My Resources page with a drop down from which labels can be selected for a selected resource
- [x] Implement the ability for the user to create new labels that show up in the drop down list
- [x] Implement the labels as a facet in the filter panel of the My Resources page.

![untitled](https://cloud.githubusercontent.com/assets/3485902/11601970/1f271c6e-9a94-11e5-948e-ce5f4e4ba2ad.png)

**Comment by pkdash** [comment]
Are the 'labels' user specific?

**Comment by horsburgh** [comment]
Yes - labels are user specific.  They are not the same as the keywords in the science metadata for a resource. They are effectively an organizational tool for users - think "virtual folders".

**Comment by mauriel133** [comment]
Implemented and working on www.

**Comment by dtarb** [comment]
Great!
