### ISSUE TITLE
My Resources Page: Restyle Resource Listing and Add Resource Selection

### ISSUE THREAD

**Issue by horsburgh** [hydroshare/hydroshare#770]
The listing of resources on the My Resources page needs some love. The following are needed:

- [x] Users need to be able to select resources on which they want to perform actions. This could be done by either adding a check box to the left column for each resource or by using a distinct selection color when a user clicks or shift-clicks on a resource.
- [x] It would be helpful to have some sort of visual clue as to what the resource type is (e.g., a thumbnail or icon or something like that
- [x] Add sharing status as a column in the table
- [x] Implement an intuitive scrolling (preferred) or paging mechanism for long lists

Other attributes that might be useful in the resource listing include:

* First author
* Date created
* Statistics (e.g., number of views, downloads, etc.)

These could be implemented at a later date as part of a separate issue.

**Comment by mauriel133** [comment]
>First author
Date created
Statistics (e.g., number of views, downloads, etc.)

Should I implement some of those attributes as a table column?

**Comment by horsburgh** [comment]
@mauriel133 - as soon as the other parts of this issue have been deployed, let's close this issue and create a new issue for these enhancements.  Statistics implies that we are actually tracking information about resources. Do we have any of that information available yet that you could put in a table column (e.g., views, downloads, etc.)?

**Comment by mauriel133** [comment]
The only thing I'm aware of is number of +1s. Not sure what the state of other statistics is right now. The previous items in the list have been implemented and merged into develop.

**Comment by horsburgh** [comment]
I'll create a new issue and close this one.
