### ISSUE TITLE
My Resources Page:  Additional Toolbar Functionality

### ISSUE THREAD

**Issue by horsburgh** [hydroshare/hydroshare#771]
The following are suggested as global operations on whichever resources are selected in a user's list:

- [x] Delete - delete all of the selected resources
- [ ] Share - apply the same access control settings to a selected list of resources

**Comment by Castronova** [comment]
@horsburgh  close or act on if needed

**Comment by horsburgh** [comment]
@dtarb - I am closing this one. Your issue #2514 indicates that you have received multiple requests for the bulk changing of access control, so if we do act on it, we can use that issue.
