### ISSUE TITLE
Resource type icons

### ISSUE THREAD

**Issue by mauriel133** [hydroshare/hydroshare#773]
I will be adding resource type icons where necessary in the site. These are the ones I've come up with so far. Let me know your suggestions.

# Preview
#### Generic:
![generic96x96](https://cloud.githubusercontent.com/assets/2448568/11610713/d9c2af6e-9b68-11e5-85b3-521057b46dcb.png)

### Geographic Raster:
![geographic96x96](https://cloud.githubusercontent.com/assets/2448568/11610715/d9cd4a0a-9b68-11e5-9945-3f27c15d9061.png)

#### Time Series:
![timeseries96x96](https://cloud.githubusercontent.com/assets/2448568/11610752/da29c172-9b68-11e5-9b34-764161c1eaac.png)

#### HIS Referenced Time Series:
![his96x96](https://cloud.githubusercontent.com/assets/2448568/11610723/d9dddfd2-9b68-11e5-955b-d448b5fc8c0d.png)

#### Model Instance:
![modelinstance96x96](https://cloud.githubusercontent.com/assets/2448568/11610728/d9ece02c-9b68-11e5-852b-760aab614898.png)

#### SWAT Model Instance:
![swat96x96](https://cloud.githubusercontent.com/assets/2448568/11610745/da18ed8e-9b68-11e5-923c-36186ed9978a.png)

#### Model Program:
![modelprogram9696](https://cloud.githubusercontent.com/assets/2448568/11610736/d9fdcaa4-9b68-11e5-9f90-1f62b4d638cc.png)

#### Multidimensional:
![multidimensional96x96](https://cloud.githubusercontent.com/assets/2448568/11614809/e8bb58fc-9c0a-11e5-8c01-57a0e541e727.png)

**Comment by ironfroggy** [comment]
I think overall these look great, but I'm not sure what value is added by
the little dog ear on the top left. It doesn't help to distinguish any of
the icons and gives you less space for the artwork within it, especially on
the smallest sizes. And i'm pretty sure even the smallest here is larger
than will be needed in most places, so if removing the dog ear could help
compress this maybe its worth a try?

On Sat, Dec 5, 2015 at 6:04 PM, Maurier Ramirez <notifications@github.com>
wrote:

> I will be adding resource type icons where necessary in the site. These
> are the ones I've come up with so far. Let me know your suggestions.
>
> Generic
> [image: generic48x48]
> <https://cloud.githubusercontent.com/assets/2448568/11610707/d9ae6acc-9b68-11e5-8174-ce26bb77ec88.png>
> [image: generic72x72]
> <https://cloud.githubusercontent.com/assets/2448568/11610708/d9bb2848-9b68-11e5-85e1-807433b7953d.png>
> [image: generic96x96]
> <https://cloud.githubusercontent.com/assets/2448568/11610713/d9c2af6e-9b68-11e5-85b3-521057b46dcb.png>
> [image: generic144x144]
> <https://cloud.githubusercontent.com/assets/2448568/11610709/d9c0143e-9b68-11e5-83f3-d4eb63185c1c.png>
> [image: generic192x192]
> <https://cloud.githubusercontent.com/assets/2448568/11610711/d9c1c586-9b68-11e5-8848-7dae2119070f.png>
> [image: generic512x512]
> <https://cloud.githubusercontent.com/assets/2448568/11610710/d9c068d0-9b68-11e5-9792-6df7d699cf5b.png>
>
> Geographic Raster
> [image: geographic48x48]
> <https://cloud.githubusercontent.com/assets/2448568/11610712/d9c2b248-9b68-11e5-8efd-d6a0e4c0bf59.png>
> [image: geographic72x72]
> <https://cloud.githubusercontent.com/assets/2448568/11610714/d9c9aeea-9b68-11e5-9ada-234a53c26915.png>
> [image: geographic96x96]
> <https://cloud.githubusercontent.com/assets/2448568/11610715/d9cd4a0a-9b68-11e5-9945-3f27c15d9061.png>
> [image: geographic144x144]
> <https://cloud.githubusercontent.com/assets/2448568/11610716/d9cdc4e4-9b68-11e5-9840-8ba55188b8f4.png>
> [image: geographic192x192]
> <https://cloud.githubusercontent.com/assets/2448568/11610717/d9ce6746-9b68-11e5-97e5-cc28ef99269d.png>
> [image: geographic512x512]
> <https://cloud.githubusercontent.com/assets/2448568/11610718/d9cf6e16-9b68-11e5-86cc-0847555e2f33.png>
>
> Time Series
> [image: timeseries48x48]
> <https://cloud.githubusercontent.com/assets/2448568/11610749/da1e2c22-9b68-11e5-80d1-cc69bdf8f3bf.png>
> [image: timeseries72x72]
> <https://cloud.githubusercontent.com/assets/2448568/11610750/da2298d4-9b68-11e5-9971-6514198b601b.png>
> [image: timeseries96x96]
> <https://cloud.githubusercontent.com/assets/2448568/11610752/da29c172-9b68-11e5-9b34-764161c1eaac.png>
> [image: timeseries144x144]
> <https://cloud.githubusercontent.com/assets/2448568/11610751/da295962-9b68-11e5-930b-0963cc512de8.png>
> [image: timeseries192x192]
> <https://cloud.githubusercontent.com/assets/2448568/11610753/da2bada2-9b68-11e5-9552-ec6bf8977690.png>
> [image: timeseries512x512]
> <https://cloud.githubusercontent.com/assets/2448568/11610754/da2e8428-9b68-11e5-9426-2cec9e97a581.png>
>
> HIS Referenced Time Series
> [image: his48x48]
> <https://cloud.githubusercontent.com/assets/2448568/11610719/d9d23952-9b68-11e5-8123-1e4825d96577.png>
> [image: his72x72]
> <https://cloud.githubusercontent.com/assets/2448568/11610720/d9da24e6-9b68-11e5-894c-fad85b53bcd6.png>
> [image: his96x96]
> <https://cloud.githubusercontent.com/assets/2448568/11610723/d9dddfd2-9b68-11e5-955b-d448b5fc8c0d.png>
> [image: his144x144]
> <https://cloud.githubusercontent.com/assets/2448568/11610722/d9dd7ec0-9b68-11e5-928a-9a5444ce56a2.png>
> [image: his192x192]
> <https://cloud.githubusercontent.com/assets/2448568/11610724/d9dee5a8-9b68-11e5-86c2-e3e24e740760.png>
> [image: his512x512]
> <https://cloud.githubusercontent.com/assets/2448568/11610721/d9dbee02-9b68-11e5-9f1c-956ab357eb66.png>
>
> Model Instance
> [image: modelinstance48x48]
> <https://cloud.githubusercontent.com/assets/2448568/11610725/d9e2f4c2-9b68-11e5-82c6-383dd4f3b9a4.png>
> [image: modelinstance72x72]
> <https://cloud.githubusercontent.com/assets/2448568/11610730/d9ecf8e6-9b68-11e5-8370-a6fc9aaeb9c5.png>
> [image: modelinstance96x96]
> <https://cloud.githubusercontent.com/assets/2448568/11610728/d9ece02c-9b68-11e5-852b-760aab614898.png>
> [image: modelinstance144x144]
> <https://cloud.githubusercontent.com/assets/2448568/11610729/d9ecf58a-9b68-11e5-999e-e1d3f6a5c2da.png>
> [image: modelinstance192x192]
> <https://cloud.githubusercontent.com/assets/2448568/11610726/d9ea9dee-9b68-11e5-830f-fa3dc19dbd47.png>
> [image: modelinstance512x512]
> <https://cloud.githubusercontent.com/assets/2448568/11610727/d9eb8470-9b68-11e5-94ae-ff501be945cf.png>
>
> SWAT Model Instance
> [image: swat48x48]
> <https://cloud.githubusercontent.com/assets/2448568/11610741/da0b6c68-9b68-11e5-88d0-e7888ccf9f46.png>
> [image: swat72x72]
> <https://cloud.githubusercontent.com/assets/2448568/11610744/da15c618-9b68-11e5-956d-d62921bdb408.png>
> [image: swat96x96]
> <https://cloud.githubusercontent.com/assets/2448568/11610745/da18ed8e-9b68-11e5-923c-36186ed9978a.png>
> [image: swat144x144]
> <https://cloud.githubusercontent.com/assets/2448568/11610746/da19c196-9b68-11e5-955d-ab66907af8f1.png>
> [image: swat192x192]
> <https://cloud.githubusercontent.com/assets/2448568/11610748/da1cde9e-9b68-11e5-86a7-e631b10ccda2.png>
> [image: swat512x512]
> <https://cloud.githubusercontent.com/assets/2448568/11610747/da1bae52-9b68-11e5-9ad1-4e9ad3213fa6.png>
>
> Model Program
> [image: modelprogram48x48]
> <https://cloud.githubusercontent.com/assets/2448568/11610731/d9ef8bc4-9b68-11e5-9b42-7ab2c87a0171.png>
> [image: modelprogram72x72]
> <https://cloud.githubusercontent.com/assets/2448568/11610732/d9f9d14c-9b68-11e5-86df-64729d1fecb2.png>
> [image: modelprogram144x144]
> <https://cloud.githubusercontent.com/assets/2448568/11610733/d9fa50b8-9b68-11e5-9144-5d11f3a74fa1.png>
> [image: modelprogram192x192]
> <https://cloud.githubusercontent.com/assets/2448568/11610735/d9fd4930-9b68-11e5-84d4-3b9ff590a5ec.png>
> [image: modelprogram512x512]
> <https://cloud.githubusercontent.com/assets/2448568/11610734/d9fc2ed8-9b68-11e5-9af4-dc3f03210c2f.png>
> [image: modelprogram9696]
> <https://cloud.githubusercontent.com/assets/2448568/11610736/d9fdcaa4-9b68-11e5-9f90-1f62b4d638cc.png>
>
> Multidimensional (NetCDF)
> [image: multidimensional48x48]
> <https://cloud.githubusercontent.com/assets/2448568/11610737/d9fe86ec-9b68-11e5-975f-222c6b4b834a.png>
> [image: multidimensional72x72]
> <https://cloud.githubusercontent.com/assets/2448568/11610738/da0794da-9b68-11e5-88f2-c51115ea7a3e.png>
> [image: multidimensional96x96]
> <https://cloud.githubusercontent.com/assets/2448568/11610740/da0aa7ba-9b68-11e5-8e86-f42cb0c9b336.png>
> [image: multidimensional144x144]
> <https://cloud.githubusercontent.com/assets/2448568/11610739/da08977c-9b68-11e5-936f-23e77db120da.png>
> [image: multidimensional192x192]
> <https://cloud.githubusercontent.com/assets/2448568/11610743/da0f0e4a-9b68-11e5-973a-c398c50fe794.png>
> [image: multidimensional512x512]
> <https://cloud.githubusercontent.com/assets/2448568/11610742/da0e725a-9b68-11e5-8682-f75c263997f1.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hydroshare/hydroshare/issues/773>.
>



-- 


*Calvin Spealman*Lead Front-end Developer

calvin@caktusgroup.com <calvin@caktusgroup.com>
www.caktusgroup.com

**Comment by horsburgh** [comment]
@mauriel133 - I agree with Calvin.  These look great.  Is it possible to get rid of the dog ear and make them more square than rectangular?

**Comment by danames** [comment]
Nice work @mauriel133. For NetCDF, consider a stack of grids rather than
just a stack of white boxes. Also for model program, consider replacing the
checkmarks with line numbers or a combination of hashtags and line numbers.
I agree with Calvin and Jeff re the dogeared corner. Looks cool, but
probably isn't necessary. Great work though. - Dan

**Comment by mauriel133** [comment]
Jeff, it is possible. I did these ones myself in photoshop. I will implement all the suggestions above today.

**Comment by mauriel133** [comment]
These are the icons I came up with after the feedback. Please let me know your suggestions. I want to update the icons tonight so they are ready before AGU.

Multidimensional:
![multidimensional48x48](https://cloud.githubusercontent.com/assets/2448568/11769920/cb7c1506-a1af-11e5-9bd9-14fdf3e1cca9.png)
Time Series:
![timeseries48x48](https://cloud.githubusercontent.com/assets/2448568/11769925/cb7f2106-a1af-11e5-8480-113a48895873.png)
Web App:
![webapp48x48](https://cloud.githubusercontent.com/assets/2448568/11769945/51059eae-a1b0-11e5-893b-0a7213fe2641.png)
Generic:
![generic48x48](https://cloud.githubusercontent.com/assets/2448568/11769924/cb7eb0b8-a1af-11e5-8d84-e81c6f355559.png)
Geographic Feature:
![geographicfeature48x48](https://cloud.githubusercontent.com/assets/2448568/11769922/cb7dbd3e-a1af-11e5-9b0b-2167460dfa20.png)
Geographic Raster:
![geographicraster48x48](https://cloud.githubusercontent.com/assets/2448568/11769923/cb7dd814-a1af-11e5-8530-bf0c936fe4be.png)
HIS Referenced Time Series:
![his48x48](https://cloud.githubusercontent.com/assets/2448568/11769928/cb8d9a24-a1af-11e5-843f-240b777ab812.png)
Model Instance:
![modelinstance48x48](https://cloud.githubusercontent.com/assets/2448568/11769926/cb8e167a-a1af-11e5-93dc-8b546660bafa.png)
Model Program:
![modelprogram48x48 pmg](https://cloud.githubusercontent.com/assets/2448568/11769927/cb903482-a1af-11e5-8ef1-c32d8e011070.png)

**Comment by horsburgh** [comment]
I think they look awesome. Thanks @mauriel133

**Comment by zhiyuli** [comment]
@mauriel133  Nice work! I like them!

**Comment by mohamedmorsy** [comment]
@mauriel133 are you going to keep the same one for the SWAT Model Instance? As I do not see the icon in the list.

**Comment by mauriel133** [comment]
All icons implemented now. Closing.
