### ISSUE TITLE
Why do we click "My Resources" to see a list of all resources? 

### ISSUE THREAD

**Issue by danames** [hydroshare/hydroshare#775]
When you click "My Resources" it takes you to a page that is called "Resources" that seems to show a list of ALL public resources. This seems wrong.

**Comment by mauriel133** [comment]
I'm addressing this issue in the revamp of this page that I am working on.

**Comment by dtarb** [comment]
The plan, and we hope it happens this week, is for Mauriel's revamp to get deployed that will be truly "My Resources" and for Alva and Zhaokun's "Discover" page to come between "My Resources" and "Apps" for discovery of other resources that can then be marked for putting on the "My Resources" page through a button on the Resource Landing Page.  I hope it all happens.

**Comment by horsburgh** [comment]
The "My Resources" link is viewable by unauthenticated users.  So, the default behavior for when unauthenticated users click on the "My Resources" link would be to take them to the "Sign in" page.

**Comment by hyi** [comment]
@horsburgh @danames @dtarb I can easily add a login required check for my resources page from admin, which would take unauthenticated users to "Sign in" page automatically. However, I think we should allow unauthenticated users to be able to view public resources, right? If so, how this work with "My resources" page? Should it just display public resources for unauthenticated users?

**Comment by horsburgh** [comment]
@hyi  - When the discovery page is completed, My Resources will be specific to the user.  So, there will be no viewing of resources on a My Resources page for unauthenticated users. Unauthenticated users can view public resources from the Discovery page.  

When we make this next round of updates, users will have to sign in to use the My Resources page.

**Comment by hyi** [comment]
@horsburgh OK. Got it. Once discovery page is integrated, I can easily change My Resources page to be login-required which will take unauthenticated users to the sign in page.

**Comment by dtarb** [comment]
Done in pre-release beta.
