### ISSUE TITLE
OpenDAP service improvements

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#779]
The OpenDap service for multidimensional resources needs a bit of loving attention.  I suggest the following

 - Remove the statement "Tested on Netscape 5.61 and Internet Explorer 5.00 from the top.  These are embarrassingly obsolete browsers.
 - Host the service on a more proper URL.  I suggest thredds.hydroshare.org (not hydrotest41.renci.org)
 - Host the service on a standard port avoiding the 8080 port in the URL.
 - Expose on the resource landing page links to some of the other THREDDS services supported (like subsetting)

**Comment by rayi113** [comment]
Item #1: I changed Tested on Netscape 5.61 and Internet Explorer 5.00 to all dashes.
Item #2: Done - http://thredds.hydroshare.org/ points to http://hydrotest41.renci.org/
Item #3: Done via port forwarding in iptables
