### ISSUE TITLE
Downloads. Reference to Hydroshare lost

### ISSUE THREAD

**Issue by valentinedwv** [hydroshare/hydroshare#78]
When I download a file, what I get is the file. This loses the any reference to the hydroshare.

IMHO, default download should be a bag/package with the metadata.

**Comment by dtarb** [comment]
If you click on Export All for a resource you get the entire bag.  If you click on download on a file, you get just the file.  So both options are there.  When a resource has multiple files a user may want to just download one file and this functionality supports this use.

Now perhaps the semantics could be changed to make it more apparent that Export All gives the bag and Download gives individual files.  Lets get the functionality in place first.

**Comment by valentinedwv** [comment]
Worked on the NFIE file.

Suggest the first option should be to Download the resource.
Change "Export All"  to "download resource"
    Show a list of files in the resource with a label "Downloads a package with these files from this resource"

Below this have an Section: labeled "Download Individual Files"

**Comment by dtarb** [comment]
I like these suggestions for renaming and labeling the buttons.

Dave

**Comment by dtarb** [comment]
A better solution implemented in Alpha.
