### ISSUE TITLE
Discover page improvements

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#783]
Based on review of the implementation presently on beta I have the following suggestions

1.  Author and Creator are equivalent.  So only filter by one of them.  Perhaps one of them is Owner mislabeled.  I suggest the following people filters

  - Filter by Author 
  - Filter by Owner

2.  Use singular/plural consistently.  I suggest singular (i.e. Author, not Authors) as even though a resource can have multiple authors the filter check operates on one.  

3.  Lowercase the "by" and capitalize the filter term (e.g. "Author")

4.  Remove the underscore in the filter term "Resource Type"

5.  The facet Language was low on our priority.  If we are going to use this, we need a way to spell it out, i.e. English rather than eng.

See #630 where search facets were prioritized.

**Comment by mjstealey** [comment]
Is the list of discovered items hard set to only return 20?
Example, from beta: https://beta.hydroshare.org/search/?q=GenericResource

Though there are 76 Generic Resource types found, the discovery page only displays 20 of them. Unsure if there is a paging mechanism that I'm missing, but I didn't see one present.

**Comment by xuezhaokun** [comment]
I did a filter in the query to simplify the faceted results. I only show
the resources with faceted results count greater than 2.

Zhaokun

On Wed, Dec 9, 2015 at 3:23 PM, Michael J. Stealey <notifications@github.com
> wrote:

> Is the list of discovered items hard set to only return 20?
> Example, from beta: https://beta.hydroshare.org/search/?q=GenericResource
>
> Though there are 76 Generic Resource types found, the discovery page only
> displays 20 of them. Unsure if there is a paging mechanism that I'm
> missing, but I didn't see one present.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hydroshare/hydroshare/issues/783#issuecomment-163381632>
> .
>



-- 
Best,
Zhaokun

**Comment by xuezhaokun** [comment]
I think I can try to do the filtering stuff from the front-end instead of doing it in the query. I will take a look whether that works better.
Thanks for pointing out!

**Comment by horsburgh** [comment]
On the My Resources page, we are trying out scrolling the resource list rather than paging.  We're still open to feedback on that, but now that you will be able to sort on each of the columns in the list I think this will work. I think we should be consistent with how the lists behave on both the My Resources and the Discover page.

**Comment by dtarb** [comment]
There may inconsistency in the filtering due to confusion over Owner vs Author.  I changed the author of two resources to be the same name other than the owner and deleted the owner as an author.  The new name does not show up under the Filter by author facet, unless we have to wait for the solr refresh.

**Comment by xuezhaokun** [comment]
There is a pagination setting for showing the results. The default set is
20 items per page. There is a 'Previous | Next' option can let users view
items on the other pages.

On Wed, Dec 9, 2015 at 3:23 PM, Michael J. Stealey <notifications@github.com
> wrote:

> Is the list of discovered items hard set to only return 20?
> Example, from beta: https://beta.hydroshare.org/search/?q=GenericResource
>
> Though there are 76 Generic Resource types found, the discovery page only
> displays 20 of them. Unsure if there is a paging mechanism that I'm
> missing, but I didn't see one present.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hydroshare/hydroshare/issues/783#issuecomment-163381632>
> .
>



-- 
Best,
Zhaokun

**Comment by gantian127** [comment]
@dtarb @xuezhaokun would you please close this issue if you think it is fixed? Thanks

**Comment by dtarb** [comment]
I suggest the following

1.  Show filter facets with count > 0.  I find it confusing to see a resource with an author that is not on the facet list.  Also if the only occurrence of the resource is on one of the Next pages then when looking at the first page a user has no way of knowing there is anything by that author to select.

2.  I would prefer the color bar at the top to be removed, and the color coding of the counts to go from dark (high) to light (low).

![untitled](https://cloud.githubusercontent.com/assets/3456833/12051016/7c79e092-aeba-11e5-80b8-464d6066d344.png)

**Comment by alvacouch** [comment]
I believe these have been addressed by current discovery fixes.
