### ISSUE TITLE
Clicking the button to add data from iRODS shows a form that needs some text edits.

### ISSUE THREAD

**Issue by danames** [hydroshare/hydroshare#785]
Click to add a new resource
Click the new "here" button to add a resource from iRODS
The form that is displayed needs some text edits:
- [x] Top text: Change "Sign in" to "Sign in to an iRODS Server"
- [x] Change "Password" to "iRODS Password" so that they know not to use their HydroShare password here
- [x] Change "Username" to "iRODS Username" for the same reason
- [x] Move "Host" to above "Port"

**Comment by hyi** [comment]
@danames This has been fixed and merged to develop, and beta has been updated with the latest develop. So you can test it out on beta and close the issue if it works as expected.

**Comment by dtarb** [comment]
Verified on pre-release beta.
