### ISSUE TITLE
Thredds service link layout update

### ISSUE THREAD

**Issue by gantian127** [hydroshare/hydroshare#787]
The Thredds service links will be shown on the resource landing page as a new section when the resource is set as a "public" resource. 
The suggested section is shown as below. This can be refined with a better layout.
![16608891-c87e-4214-a6ed-b10a5a024300](https://cloud.githubusercontent.com/assets/5016511/11699139/58a67898-9e88-11e5-9fec-649a8f1160e7.png)

**Comment by dtarb** [comment]
Satisfactorily implemented on resource specific tab in landing page.
