### ISSUE TITLE
My Resources page improvements

### ISSUE THREAD

**Issue by mauriel133** [hydroshare/hydroshare#798]
Issues found:

- [x]  For a resource for which a user has been given view permission, the “Add to my resources’ button is shown. This button should only appear if a user has not been given any permission at all.
- [x] The ‘Shared with me’ filter shows one occurrence, but when selected the table shows “no matching records found”
- [x] Getting different filtering results depending on the order that filtering options are checked.
- [x] If I create a resource and give someone else view permissions on it, the resource no longer appears as part of My Resources. @pkdash, as I tested, this issue appears to originate when the list is created and not in the front end. Can you look into it?

**Comment by mauriel133** [comment]
@pkdash, it seems that the 'is_mine' flag comes back as False for users who have view permissions on the resource. This flag needs to be set to True for users who have any kind of permission on the resource as those are included by default on My Resources page.

**Comment by mauriel133** [comment]
@horsburgh, @dtarb, @pkdash, if a user has some permission in a resource should they still see a button to add to or remove from My Resources page in the resource landing page?

**Comment by pkdash** [comment]
@mauriel133 If a user has any of these permission (owner, edit, view) then that resource by default is in my resources. That means flagging a resource as 'mine' should be allowed for a resource that either public or discoverable and the user has no explicit permission for that resource (owner, edit or view).

**Comment by mauriel133** [comment]
Thanks. I used the other access level flags to hide the button when any of them is true.

**Comment by dtarb** [comment]
I am OK with whatever is easiest right now.  A case could be made that a user may not want their my resources page cluttered with resources that have been shared with them, so should be able to unflag the resource as being in "My Resources". This could be supported by having the flag present, but default to "mine" when a resource is shared with them.  If this is done, then there is a need for a user to be able to then find again resources they may have unflagged.  This probably needs careful thinking through so I am fine with "mine" and "owner", "edit", "view" being separate at present.

**Comment by pkdash** [comment]
@mauriel133 I have been working to resolve the sub-issue (4th checkbox).

**Comment by mauriel133** [comment]
The fourth issue is now fixed as well as part of @pkdash's bug fix.

**Comment by mauriel133** [comment]
All issues confirmed working.
