### ISSUE TITLE
no icon showing up for web app resource type.

### ISSUE THREAD

**Issue by zhiyuli** [hydroshare/hydroshare#800]
@mauriel133 @pkdash @shawncrawley @hyi 
Just tried to create a web app resource on beta and found no icon showing up for it.
We just merged web app type yesterday (Friday), so maybe there is no particular icon designed for it. If possible, can we just give it a default icon (or anything) filling that blank for now? 

![image](https://cloud.githubusercontent.com/assets/10070599/11763784/a6b3826c-a0d4-11e5-8593-9e49ecea988a.png)

**Comment by mauriel133** [comment]
I will upload new icons soon. I will add this one with the rest. Thanks.

**Comment by zhiyuli** [comment]
@mauriel133 
verified on www.
