### ISSUE TITLE
In Firefox label and star icons have gray background that does not look attractive

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#802]
In the pre-release beta deploy in Firefox the My Resources graphics have a gray background.
![p1](https://cloud.githubusercontent.com/assets/3456833/11763984/a2825b34-a0dc-11e5-96b9-3068fd7048cf.PNG)

**Comment by mauriel133** [comment]
Changed the style to accommodate for this browser.

**Comment by dtarb** [comment]
Verified fixed.  Thanks!
