### ISSUE TITLE
Labels creation quirk with keyboard enter

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#803]
If I create a new label name by clicking Create New Label on the My Resources page, then entering text then hitting "Enter" on my keyboard (which seems the instinctive thing to do), rather than push the create button I get a page showing {"status": "success", "action": "CREATE", "label_type": "SAVEDLABEL", "resource_id": null} that makes it appear something has gone wrong.  Back, followed by refresh reveals that the label was created.

**Comment by mauriel133** [comment]
I fixed this error and made the textbox auto focus when the form appears. Pressing the Enter key now works as expected. Also added a check for empty string.

**Comment by dtarb** [comment]
Verified fixed.  Thanks!
