### ISSUE TITLE
Comments and replies fail if there are too many (it seems) in current beta deploy

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#804]
In the resource https://beta.hydroshare.org/resource/101f746de3ca4896a6d0f05206483766/ @zhiyuli and I got into a discussion over no data.  My attempt to reply to his second comment generates the following error

Exception Type: IntegrityError at /comment/
Exception Value: duplicate key value violates unique constraint "django_comments_pkey"
DETAIL:  Key (id)=(15) already exists.

Full traceback below.

Environment:

Request Method: POST
Request URL: https://beta.hydroshare.org/comment/

Django Version: 1.7.8
Python Version: 2.7.6
Installed Applications:
(u'mezzanine.boot',
 u'django.contrib.auth',
 u'oauth2_provider',
 u'corsheaders',
 u'django.contrib.contenttypes',
 u'django.contrib.redirects',
 u'django.contrib.sessions',
 u'django.contrib.sites',
 u'django.contrib.sitemaps',
 u'django.contrib.gis',
 u'inplaceeditform',
 u'django_nose',
 u'django_irods',
 u'theme',
 u'theme.blog_mods',
 u'mezzanine.conf',
 u'mezzanine.core',
 u'mezzanine.generic',
 u'mezzanine.blog',
 u'mezzanine.forms',
 u'mezzanine.pages',
 u'mezzanine.galleries',
 u'crispy_forms',
 u'mezzanine.accounts',
 u'mezzanine.mobile',
 u'autocomplete_light',
 u'haystack',
 u'jquery_ui',
 u'rest_framework',
 u'ga_ows',
 u'ga_resources',
 u'hs_core',
 u'hs_access_control',
 u'hs_labels',
 u'hs_metrics',
 u'irods_browser_app',
 u'django_docker_processes',
 u'hs_geo_raster_resource',
 u'djcelery',
 u'ref_ts',
 u'hs_app_timeseries',
 u'widget_tweaks',
 u'hs_app_netCDF',
 u'hs_model_program',
 u'hs_modelinstance',
 u'hs_tools_resource',
 u'hs_swat_modelinstance',
 u'hs_geographic_feature_resource',
 u'debug_toolbar',
 u'django_extensions',
 u'filebrowser_safe',
 u'grappelli_safe',
 u'django.contrib.admin',
 u'django.contrib.staticfiles',
 u'django.contrib.comments')
Installed Middleware:
(u'django.contrib.sessions.middleware.SessionMiddleware',
 u'django.middleware.locale.LocaleMiddleware',
 u'django.contrib.auth.middleware.AuthenticationMiddleware',
 u'corsheaders.middleware.CorsMiddleware',
 u'django.middleware.common.CommonMiddleware',
 u'django.middleware.csrf.CsrfViewMiddleware',
 u'django.contrib.messages.middleware.MessageMiddleware',
 u'mezzanine.core.request.CurrentRequestMiddleware',
 u'mezzanine.core.middleware.RedirectFallbackMiddleware',
 u'mezzanine.core.middleware.TemplateForDeviceMiddleware',
 u'mezzanine.core.middleware.TemplateForHostMiddleware',
 u'mezzanine.core.middleware.AdminLoginInterfaceSelectorMiddleware',
 u'mezzanine.core.middleware.SitePermissionMiddleware',
 u'mezzanine.pages.middleware.PageMiddleware',
 u'ga_resources.middleware.PagePermissionsViewableMiddleware',
 u'debug_toolbar.middleware.DebugToolbarMiddleware')

Traceback:
File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py" in get_response
  111.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "./theme/views.py" in comment
  82.         comment = form.save(request)
File "./theme/forms.py" in save
  185.         comment.save()
File "/usr/local/lib/python2.7/dist-packages/mezzanine/generic/models.py" in save
  56.         super(ThreadedComment, self).save(*args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/django/contrib/comments/models.py" in save
  88.         super(Comment, self).save(*args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py" in save
  589.                        force_update=force_update, update_fields=update_fields)
File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py" in save_base
  616.                 self._save_parents(cls, using, update_fields)
File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py" in _save_parents
  641.             self._save_table(cls=parent, using=using, update_fields=update_fields)
File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py" in _save_table
  698.             result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py" in _do_insert
  731.                                using=using, raw=raw)
File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py" in manager_method
  92.                 return getattr(self.get_queryset(), name)(*args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py" in _insert
  921.         return query.get_compiler(using=using).execute_sql(return_id)
File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py" in execute_sql
  921.                 cursor.execute(sql, params)
File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py" in execute
  81.             return super(CursorDebugWrapper, self).execute(sql, params)
File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py" in execute
  65.                 return self.cursor.execute(sql, params)
File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py" in __exit__
  94.                 six.reraise(dj_exc_type, dj_exc_value, traceback)
File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py" in execute
  65.                 return self.cursor.execute(sql, params)

Exception Type: IntegrityError at /comment/
Exception Value: duplicate key value violates unique constraint "django_comments_pkey"
DETAIL:  Key (id)=(15) already exists.

**Comment by hyi** [comment]
@dtarb I tried to reply to @zhiyuli second comment two times in an effort to reproduce this issue, but my comments were posted successfully without issues both times. @dtarb Can you still reproduce this issue on beta? I cannot reproduce this issue so far.

**Comment by hyi** [comment]
@dtarb and I have used the same account trying to figure out what is going on with this issue. I did initially see the issue, but after clearing the browser cache, I don't see the issue any more. @dtarb cannot reproduce this issue either even without clearing browser cache. Not sure what is going on, since the primary id is auto-generated, and should not clash with an existing id. Anyway, it appears we both cannot reproduce this issue any more. @dtarb perhaps it is better to close this issue for now since we cannot reproduce it any more?

**Comment by dtarb** [comment]
OK closing.

**Comment by zhiyuli** [comment]
Try to reply a comment on www but got an error.
https://www.hydroshare.org/resource/f88ad2b366524813a9103f0bab226a34

![image](https://cloud.githubusercontent.com/assets/10070599/12054164/eb0f48d0-aedd-11e5-83b8-b92b87dc2d27.png)

![image](https://cloud.githubusercontent.com/assets/10070599/12054168/fd6c7976-aedd-11e5-8bc4-45e2ee18ada5.png)

**Comment by hyi** [comment]
@dtarb I suggest to close this issue since it was filed 5 months ago that only happened on beta. I believe this issue has been covered by the new comments-related issues. I'll defer to you on what you want to do with this issue.
