### ISSUE TITLE
Confusing initial visit to the discover landing page

### ISSUE THREAD

**Issue by danames** [hydroshare/hydroshare#805]
When you click the Discover page, it starts with showing no resources. The empty table with headers and the color bar and the "Clear All" button seem out of place or daunting. I suggest the following changes for when a user first lands on the Discover landing page:

- [ ] Do not show the table headers "Title Type, First Author," etc.
- [ ] Do not show the "Clear All" button
- [ ] Do not show the color gradient bar
- [ ] Provide some instruction to the user on what they should do next, for example "Enter a search term to find resources on HydroShare:"

After the user enters some term in the box and some resources are found, then show the table headers, "Clear All" button, etc.

**Comment by xuezhaokun** [comment]
Thanks for the suggestions! Just made improvements on these items.
