### ISSUE TITLE
Users should agree to a data publication agreement

### ISSUE THREAD

**Issue by horsburgh** [hydroshare/hydroshare#81]
Related to the new resource creation workflow described in #62 - the default is now that resources are by default private. When a user chooses to make a resource public OR when a user decides to formally publish a resource, they should agree to a data publication agreement where they certify that they have the right to make their content public and that they are not violating any copyright agreements.  This might also be a good point to have them choose a license under which they are releasing their content.

This came up on the call today where the example we ran through the resource creation workflow was uploading a published paper to HydroShare.  If uploaded content is protected by copyright agreements, we may have liability issues if we don't ask users to certify that they are not uploading protected content.

**Comment by rayi113** [comment]
HydroShare Resource Creation Workflows Issues in GitHub: #37, #62, #81

**Comment by dtarb** [comment]
We have a terms of use http://beta.hydroshare.org/terms-of-use/, but I agree we should set up a separate page that addresses publication.  I suggest the following work to do this.
1.  @rayi113 please come up with draft text for this - looking at examples from the systems involved with the data and software publication and citation workshop you have been involved with (and perhaps DataOne/SEAD).  It can be short and simple.
2.  Then run this by the PI's and CUAHSI (Rick Hooper) for approval.
3.  Then get this added as another page linked in the HydroShare footer (assign to a programmer to do it.)
4.  Then program a pop up that a user has to click agree when a resource is made public that agrees to this text.

**Comment by horsburgh** [comment]
This is now part of the resource publication issue #15.  So, I'm going to close this one.
