### ISSUE TITLE
simplify API for user flagging

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#812]
The current pattern in user labeling is an API call like 
    u.ulabels.favorite_resource(r) 
It would probably be better to make the flag a parameter, e.g., 
    u.ulabels.flag_resource(r, FlagCodes.FAVORITE) 
This requires only one set of calls for both flags. 

Since the flagging system hasn't been in use for long, we could do this more easily now than later...

**Comment by alvacouch** [comment]
Included in pull request #820

**Comment by hyi** [comment]
@alvacouch Has this issue been resolved by PR #820? If so, can this issue be closed?

**Comment by alvacouch** [comment]
Previously addressed.
