### ISSUE TITLE
WebApp Resource type should not store resource id's in its metadata database

### ISSUE THREAD

**Issue by shawncrawley** [hydroshare/hydroshare#827]
The WebApp is storing its own resource ID in the RequestURL class database object. This was a work-around that allows other resource's to check the publicity of the created WebApp before displaying the WebApp's button under the "Related Tools" tab. We need to find a different way to do this.

**Comment by hyi** [comment]
@shawncrawley I am a bit confused after I saw you assigned this issue to me as I thought you need to address this issue for WebApp Resources by referring to suggestions from @ironfroggy and @selimnairb to the PR for merging this WebApp resource type initially. I agree you don't need to store the resource ID, but you should be able to retrieve the resource object directly. See suggestion from @ironfroggy about what you need to do to achieve this. You can always ask questions along the way if any, but I think you should address this as part of the WebApp resource improvement, so I am assigning this issue back to you.

**Comment by danames** [comment]
Hong et al. The issue here is that we need to retrieve the permissions for
the current web app so that we know whether or not to show it to a certain
user. We were self-storing the resource id for the current web app as a way
to then check the permissions. Can you please tell us the better more
correct way to find out the permissions on the current web app? I.e. we
need to know if the current user has permission to see the app so the app
knows whether or not to display itself. I hope that makes sense. Thanks, Dan

**Comment by shawncrawley** [comment]
@hyi If I understand correctly, the fix to this issue is no small task and has to do with possible flaws in HydroShare's core infrastructure. As I feel completely inadequate and am likely unauthorized to make core infrastructure changes, I do not feel this is an appropriate issue for me to resolve. I assigned the issue to you in hopes that you would know who is the more adequate candidate to re-assign the issue to.

**Comment by shawncrawley** [comment]
@ironfroggy You seemed to have the best idea of how this issue could be addressed. You provided the following as an example in the #772 PR discussion:

`res = BaseResource.objects.get(object_id=metadata.id)`

I still do not completely understand how to begin to investigate and implement your above example, as I have little understanding of the hs_core components. So any additional direction would be greatly appreciated.

**Comment by hyi** [comment]
@danames @shawncrawley If I understand this correctly, I think it all comes down whether you can retrieve the resource object from its metadata object. It looks to me like @ironfroggy's suggestion of using something along the line of "res=BaseResource.objects.get(object_id=metadata.id) is a good starting point to try out whether you can retrieve the resource object from a metadata object, i.e., you pass in metadata.id, then use the filtering suggested by @ironfroggy to retrieve the resource object. After you know the resource object, and you know a specific user object or user id, you can call access control API to find out the permission or privilege of the user over the resource, something along the line of user.uaccess.API_funcs().., resource.raccess.API_funcs().... You can refer to hs_core/views/__init__.py for some examples on how to use access control API functions. @shawncrawley I suggest you give @ironfroggy's suggestion a try to see whether that works for you to retrieve a resource object from a metadata id. If it indeed works, then there is no change needed at the core level; if it does not work, then there might be changes needed to allow such reverse retrieval at the hs_core model level related to the metadata refactoring that was discussed a while ago. In the latter case, I suggest you assign this issue to @pkdash first to get metadata investigation going first if this indeed requires some level of metadata refactoring to establish relationship from metadata to resources.
