### ISSUE TITLE
WebApp Resource type should not have the "Download Bagit" link on its landing page

### ISSUE THREAD

**Issue by shawncrawley** [hydroshare/hydroshare#828]

**Comment by shawncrawley** [comment]
This issue would likely need to be resolved by adding a new django block to the genericresource.html in hs_core/templates/pages. @hyi @mauriel133 I noticed both of you have contributed the most to this file. Is this an issue that I can assign to one of you?

**Comment by mauriel133** [comment]
Yes, I can implement this.

**Comment by mauriel133** [comment]
Should I hide the entire content section for this type of resources?

**Comment by shawncrawley** [comment]
Yes, that would be perfect
