### ISSUE TITLE
subclassing QuerySet to integrate resources, access control, and labels

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#831]
I have looked at how the new "my resources" page uses access control and labeling, and how the rest of the system uses these features. I conclude that there is a way to make this much easier to code. We need to be able to write complex filter chains combining access control, resource type, labels, and other things.

This came up when trying to combine queries for labels and access control. The basic question is "which one comes first?" This is an unanswerable question. It depends upon use. So far, we have had to make that decision on a case by case basis, leading to lots of routines that put one thing or another first. There is an easier way. 

So, here is a simple proposal: 
- subclass QuerySet to HSResourceQuerySet
- provide methods for filtering by labels, access control issues, etc. 
- Thus, glue together the various concepts of filtering that we have. 
- Deprecate some of the current approaches that are less flexible. 

I am willing to do this. It is not even much code. 

How this would work: 
- We start any query with a generic hydroshare.get_resources() that specifies all resources amd exposes HSResourceQuerySet methods. 

> resources = HydroShare.get_resources() 
- Then we filter down as follows: 
  - resources.hs_accessible_to(user) : select those resources accessible to a specific user
  - resources.hs_labeled_with(user, ['foo', 'bar']): those resources that are labeled either with foo or bar. 
  - resources.hs_flagged_as(user, FlagCodes.FAVORITE)
  - resources.hs_public_or_discoverable(): the obvious. 
  - resources.hs_with_types(['GenericResource']) : logical or. 
  - etc.

These can be combined, e.g., 

> HydroShare.get_resources().hs_public_or_discoverable()\
>     .hs_owned_by(user).hs_labeled_with(user, ['foo', 'bar'])

In the architecture so far, we have been avoiding the idea of thinking in Django like terms. The answer to how to integrate labeling and access control lies in the way other people have integrated these kinds of features into Django. Subclassing the QuerySet object is a rather common thing. We can use this trick to make our code much more readable.

**Comment by alvacouch** [comment]
Update: I have prototyped this in my personal playground (with empty resource class to speed testing) and prognosis is excellent. The whole pattern above is practical. I had to override the Manager class as well, according to the "Custom Manager" pattern documented in Django. 

I had a little difficulty with recursive imports; looking at stackoverflow, *everyone who tries this does!*

After playing with this -- even for a short while -- I think that *all queries* in hs_labels and hs_access_control should be replaced by this pattern -- the result is much more usable and will simplify writing views. All that would remain in hs_access_control and hs_labels are the model modification routines. This is a lot simpler to accomplish than it might seem, because much of this replacement could be accomplished by automatic editing, e.g., replacing user.uaccess.get_resources_*(arguments) with BaseResource.objects.with_*(user, arguments) .... !

I do not know how to do this for system classes, e.g., User.objects.filter(.....). I modified BaseResource and thus all of the proxy classes. Thus, the routines like user.uaccess.get_users*() and user.ulabels.get_users*() are not replaced.

**Comment by ironfroggy** [comment]
This definitely sounds like the right direction with positive outcomes. I'd love to see what you have in progress. Can you share some of your work, even incomplete, so we can follow along and maybe you can get some early feedback on the pattern you're implementing?

**Comment by cuahsimarko** [comment]
@alvacouch should we revisit this and consider raising priority slightly if it will be useful in all resource views for performance/cleaner code?

**Comment by Castronova** [comment]
@alvacouch is this still relevant? If not, please close.

**Comment by alvacouch** [comment]
We've done without it enough that it is not a priority.
