### ISSUE TITLE
update pg.development.sql

### ISSUE THREAD

**Issue by mjstealey** [hydroshare/hydroshare#836]
Summary:

- [x] delete stale content types
- [x] add hs_tool_* permissions into Hydrosphare Author group
- [x] change "Resources" to "My Resources"
- [x] add Discover page link
- [x] add Apps page link (linked to https://appsdev.hydroshare.org/apps)
- [x] change "Support" to "Help"
- [x] reorder top page links to be: My Resources, Discover, Apps, Help

**Comment by ironfroggy** [comment]
Do you ever anticipate moving this initial setup out of this SQL file and into proper Django migrations? An initially migrated database should work out of the box, and the dependency on this SQL file signals some lacking in those migrations we could try to address.

**Comment by mjstealey** [comment]
Ultimately yes, I would love to ditch the database as it can mask migrations issues from the user.

What's required however wouldn't be more migrations files but rather fixtures files for the initial data that populate the pages and links normally set up from the mezzanine admin page that get saved as database objects. Once the fixtures are established we would also need to add a "manage.py loaddata" call on initial stand up. 

The production deploy would still of course be a big SQL file, but for development I think we could eliminate `pg.development.sql` if we want to.

**Comment by ironfroggy** [comment]
I would actually consider fixtures a lesser options to migrations. They
come from a time long before Django even had migrations, and given that
there are both schema and data migrations, i think its safe to consider
them largely deprecated. Where they really fail is that fixtures are
entirely unaware of migrations, and break when the schema changes with no
way to update them.

On Thu, Dec 17, 2015 at 8:52 AM, Michael J. Stealey <
notifications@github.com> wrote:

> Ultimately yes, I would love to ditch the database as it can mask
> migrations issues from the user.
>
> What's required however wouldn't be more migrations files but rather
> fixtures files for the initial data that populate the pages and links
> normally set up from the mezzanine admin page that get saved as database
> objects. Once the fixtures are established we would also need to add a
> "manage.py loaddata" call on initial stand up.
>
> The production deploy would still of course be a big SQL file, but for
> development I think we could eliminate pg.development.sql if we want to.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hydroshare/hydroshare/issues/836#issuecomment-165457905>
> .
>



-- 


*Calvin Spealman*Lead Front-end Developer

calvin@caktusgroup.com <calvin@caktusgroup.com>
www.caktusgroup.com

**Comment by mjstealey** [comment]
Interesting, I wasn't aware of data migrations in Django. Looks like a hybrid between a normal migrations file and Python functions.

I'll look into implementing this over the holiday break. Though in them meantime I'd like to being in the updated sql file to keep the develop branch up to date with what is deployed.

Also look like we could benefit from a Django update based on the new features since 1.8: https://docs.djangoproject.com/en/1.9/topics/migrations/

I believe we still have some functions to update prior to doing this as some of the warnings we get during install are about functional deprivation that we have in use.

**Comment by mjstealey** [comment]
@ironfroggy - new issue #838 created to address deprecation of pg.development.sql

**Comment by mjstealey** [comment]
merged with develop
Subsequent issue #838 created to implement data migration suggestions made by @ironfroggy
