### ISSUE TITLE
Create Tools Resource Type

### ISSUE THREAD

**Issue by shaunjl** [hydroshare/hydroshare#84]
## Purpose

* designed to link the resource to an external tool that will use the HS external API to expand on the resource through visualization, etc. 

## Extends generic resource by:

* uses base generic resource metadata 
* extends resource metadata with 
    * URI that can take post requests
    * Costs / Fees
    * tool license
    * tool version number
    * list of resource types that can use the tool

**Comment by zhiyuli** [comment]
closed
