### ISSUE TITLE
Sign in to iRODS button on resource editing page needs made consistent with resource creation

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#840]
I suggest removing the green button "Sign in to iRODS" on the resource editing page and replacing it with the less prominent statement: "If you want to load files from an iRODS server into HydroShare, please do so by logging into the iRODS server here."

**Comment by gantian127** [comment]
@dtarb would you please close this issue if you think it has been fixed? Thanks

**Comment by dtarb** [comment]
This has not yet been fixed.  

![untitled](https://cloud.githubusercontent.com/assets/3456833/12051068/7aa371c4-aebb-11e5-959c-1c8a19dedeae.png)

**Comment by hyi** [comment]
tested on dev and it works now. @dtarb can you test on dev and close the issue if it works now?

**Comment by dtarb** [comment]
I looked at dev.  The layout seems awkward.  I would be happy to close the issue, if changing is hard, but if it is possible to avoid sticking the new statement in between the download all button and learn more about bagit statement that it refers to, it would be better.  Is there a way to put the new text just below the Add file button, perhaps using a table construct.

**Comment by hyi** [comment]
@dtarb @mauriel133 I have improved content section layout in resource landing page shown as screen capture below:
In non-edit mode:
![viewcontentsection](https://cloud.githubusercontent.com/assets/476302/12119298/e7c3e662-b398-11e5-935f-5000474a7c47.png)
In edit mode but before signing into iRODS for adding files:
![editcontentsection_1](https://cloud.githubusercontent.com/assets/476302/12119318/020abc1c-b399-11e5-9142-1745c1fe6387.png)
In edit mode but after signing into IRODS for adding files:
![editcontentsection_2](https://cloud.githubusercontent.com/assets/476302/12119323/0eb455b8-b399-11e5-983d-f44b12b9a7ef.png)

@dtarb Please let me know whether they look good now, and if not, please let me know how you want to further improve it. After you approve the layout, I will create a PR for @mauriel133 to code review.

**Comment by mjstealey** [comment]
@hyi - Would it make sense to always display both the **Add file** and **Add file from iRODS** buttons, with a small note next to the **Add file from iRODS** button that simply states "Requires additional iRODS sign-in"?

Perhaps the button could be a non-green color if the user isn't signed into an iRODS account, and then turn green once signed in.

Also, showing the "Signed in as xxx" is nice, but we may also want to display which iRODS server they are logged into as they may have access to multiple iRODS servers.

**Comment by hyi** [comment]
@mjstealey Add file from iRODS button is not displayed at all when a user is not signed into iRODS and will only show up after the user clicks "here" hyperlink and signed into an iRODS zone successfully. Let me know if the layout makes sense now. Thanks.

**Comment by hyi** [comment]
@mjstealey OK. I understand your comment now. I will defer to @dtarb and others regarding which workflow they prefer, but I prefer not to show the Add file from iRODS until they signed in first.

**Comment by mjstealey** [comment]
@hyi - I can see value in both approaches, but do think that the current blurb of "*If you want to add files from an iRODS server into HydroShare, please do so by logging into the iRODS server here.*" is a bit verbose.

It'd be nice to see the iRODS option with less verbosity.

**Comment by hyi** [comment]
@mjstealey - Agreed. @dtarb @danames If you can help to make the blurb of "If you want to add files from an iRODS server into HydroShare, please do so by logging into the iRODS server here." more concise, it'd be great.

**Comment by dtarb** [comment]
@hyi the layout is improved.  No changes are needed for the non-edit mode.
For the edit mode before signing into iRODS it is fine and no changes are needed.
For the edit mode after signing into iRODS it does not make sense to still have the statement "if you want to add files from iRODS... so I suggest suppress that statement and just put the statement "Signed in as ..." next to the Add file from iRODS button.  To save space you could move the button up.

This does also beg the question as to how to sign out of iRODS if already signed in.  A sign out of iRODS link could be provided if this is easy, that if clicked would revert back to the not signed into iRODS layout.

![capture](https://cloud.githubusercontent.com/assets/3456833/12120042/399cd5c8-b38c-11e5-9ebe-3f088b86ecec.PNG)

**Comment by dtarb** [comment]
The iRODS wording can be shortened to "To add files from an iRODS server, log in to iRODS" with the words "log in to iRODS" the hyperlink.

**Comment by hyi** [comment]
@dtarb Layout changes have been made exactly according to your suggestions here. Have created a PR and asked @mauriel133 and/or @ironfroggy to do code review to have it merged/deployed.

**Comment by dtarb** [comment]
Thanks.  I'll close once I can see a deployment (e.g. on dev)

**Comment by hyi** [comment]
@dtarb The fix to this issue has been deployed to dev and works as expected according to my testing. Please test it on dev and see if you can close this issue.

**Comment by dtarb** [comment]
Looks good.
