### ISSUE TITLE
Creating a new resource - The list of resource types should be alphabetized!

### ISSUE THREAD

**Issue by danames** [hydroshare/hydroshare#841]

**Comment by mohamedmorsy** [comment]
It would be great if we can do two groups inside the list: one for the data resources and the other for the model resources. Then underneath each group we can arrange the resource types alphabetically

**Comment by danames** [comment]
Good idea, @mohamedmorsy. Let's start with just alphabetizing what is there, and then maybe we can find a better way. For example, there could eventually be two drop down lists, one for data and one for models...

**Comment by mauriel133** [comment]
This has been implemented and deployed. Please confirm and close.

**Comment by horsburgh** [comment]
Well - the list isn't really alphabetized, but the groups of resources have been created, and I think the list is OK as is.  I'm going to close.
