### ISSUE TITLE
Web App Resource: On the "Web Apps" tab, show the icons for the web apps that can be launched

### ISSUE THREAD

**Issue by danames** [hydroshare/hydroshare#842]
We should show the user icons to launch apps from resources. 

- [ ] When the user creates a Web App resource in HydroShare, they should have the option to 1) upload an icon of a specified size, or 2) link to an icon on an existing web page, or 3) if it is a Tethys app, we should be able to grab the icon dynamically from Tethys and propose it to the user as a potential icon to use.
- [ ] On the landing page for a resource, when the user clicks the "Web Apps" tab, they should see the available associated web apps with their name and icon.

**Comment by shawncrawley** [comment]
@mauriel133 Do you have higher resolution image files for the resource-icons? I would like to use the webapp png, but a larger size than 48x48.

**Comment by mauriel133** [comment]
I do. I will post it here soon.

**Comment by shawncrawley** [comment]
@mauriel133 Sorry to bother you again, but I'm just waiting on that higher-resolution webapp image.

**Comment by mauriel133** [comment]
I will post it here tonight.

**Comment by mauriel133** [comment]
Here is the high resolution web app icon.

![webapp512x512](https://cloud.githubusercontent.com/assets/2448568/12130510/3d4e1704-b3c8-11e5-8cf0-1b8efdee6601.png)
