### ISSUE TITLE
The Web Site Name for HydroShare should be spelled with an upper case "S"

### ISSUE THREAD

**Issue by danames** [hydroshare/hydroshare#843]
Open HydroShare in Chrome and look at the name of the web site in the tab that appears. It is spelled "Hydroshare". I believe we should be consistent with the uppercase "S". Or a lowercase "s" if that is what is preferred, but I believe the current design protocol is uppercase "S".

**Comment by mjstealey** [comment]
Putting the big "S" back into HydroShare - verified on dev.hydroshare.org

<img width="710" alt="screen shot 2016-01-04 at 12 33 39 pm" src="https://cloud.githubusercontent.com/assets/5332509/12095852/84343d22-b2df-11e5-81d0-c3e4be9ac91d.png">
