### ISSUE TITLE
'resource_type' filter on resourceList REST API

### ISSUE THREAD

**Issue by yirugi** [hydroshare/hydroshare#845]
It seems that the 'resource_type' filter is not working for getting resource list. (/resourceList/)

Here's an example.
https://www.hydroshare.org/hsapi/resourceList/?page=2&resource_type=GenericResource

I get the other resource types, such as TimeSeriesResource.

**Comment by selimnairb** [comment]
@yirugi The correct syntax to filter by type is:
```
https://www.hydroshare.org/hsapi/resourceList/?type=GenericResource
```
However this was broken.  This has been addressed in #876.

**Comment by yirugi** [comment]
@selimnairb I tried the link you provided, but it produced error message.

**Comment by selimnairb** [comment]
@yirugi Sorry.  This code has been merged into our development branch, but hasn't yet been deployed to www.hydroshare.org.  @mjstealey Do you know when this will be deployed?

**Comment by mjstealey** [comment]
@selimnairb, @yirugi - This is working as expected on our development server

https://dev.hydroshare.org/hsapi/resourceList/?type=GenericResource

It is a nightly build server, so there are not any resources on it currently.

**Comment by mjstealey** [comment]
> Do you know when this will be deployed?

This will be a discussion topic during todays team call.
Only pre-requisite seen before next update to www is the migrations issue denoted in #892

**Comment by selimnairb** [comment]
@yirugi This has been deployed to www.hydroshare.org.  Can you verify and close the issue if it has been resolved?  Thanks.

**Comment by yirugi** [comment]
I've confirm that this has been solved.
