### ISSUE TITLE
Unable to create shape file resource

### ISSUE THREAD

**Issue by rphooper** [hydroshare/hydroshare#848]
I get an error (not specific) when either uploading multiple files creating a shape file resource or when uploading a zip file with all the files. 
[canadwscmda_p_1m_v6-0_shp.zip](https://github.com/hydroshare/hydroshare/files/70758/canadwscmda_p_1m_v6-0_shp.zip)

**Comment by dtarb** [comment]
I was able to reproduce this error when not specifying a title.  However if I enter a title, the resource is created.  This suggests checking the code related to assigning a title when a user does not initially input one.

**Comment by rphooper** [comment]
But I did give the resource a title (“Canadian Watersheds”). I still get an error when uploading this zip file. The error simply states “Sorry, an error occurred.”

**Comment by dtarb** [comment]
I tried again and right now am getting an error all the time, so something wrong is happening.

**Comment by mjstealey** [comment]
Using Rick's file I was able to create a shapefile resource: https://www.hydroshare.org/resource/6ba5d65099d34be3aef233cf82d6d1cb/

Will need to look at server logs and see if anything out of the ordinary occurred to explain the error that you've been encountering.

**Comment by mjstealey** [comment]
Attaching 12/23/2015 of system.log from www for debugging purposes.

[system-log-12-23-2015-only.txt](https://github.com/hydroshare/hydroshare/files/70903/system-log-12-23-2015-only.txt)

**Comment by danames** [comment]
Thanks for sending the logs, Michael.

Drew, seems we have received a bug for Christmas! Please take a look and
let me know what you find out!

- Dan

**Comment by zhiyuli** [comment]
i was able to create four resources on my local vm using Rick's file:
zip with title, zip without title, unzip with title, unzip without title.

from the log Michael sent, i can see some errors occurred at
create-resource phase but the traceback records didn't point to a specific
location in the feature app. Need some help from the team interpreting the
log deeply or reproducing the error locally.

Thanks
Drew

**Comment by hyi** [comment]
@zhiyuli @rphooper Can you check on www.hydroshare.org and see if this issue has been resolved? If so, you can close this issue.

**Comment by rphooper** [comment]
Works as expected. Closing issue.
