### ISSUE TITLE
Create a new resource instance for a MODFLOW model program

### ISSUE THREAD

**Issue by danames** [hydroshare/hydroshare#849]
As per Rick Hooper email of 12/23/2015. This could (should?) be created using the existing model program resource type. However someone needs to determine which version of MODFLOW to include and needs to upload it with all it's requisite executable components, etc.

**Comment by mohamedmorsy** [comment]
@danames @goodalljl  We already could share MODFLOW (the engine) through HydroShare using the available version of the Model Program resource. There is a metadata term for the program version which allows the user to upload different versions of the model. I think, we do not need to create a new resource type for that. But I agree that maybe we need to create a specific Model Instance resource type for the MODFLOW instances which will be inherited from the Model Instance resource type ( related to the issue #850 ) and have extended metadata terms.

**Comment by danames** [comment]
Thanks Mohamed. I originally titled this issue "Create a new resource type"
but I changed it to "Create a new resource instance". Maybe that is still
the wrong wording. Basically someone needs to go into HydroShare as a user
and upload MODFLOW using your existing Model Program resource type...

**Comment by mohamedmorsy** [comment]
This already implemented on HydroShare as MODFLOW Model Instance.
