### ISSUE TITLE
SOLR - update_index - deleted resources can desync the database and solr index and generate an error

### ISSUE THREAD

**Issue by mjstealey** [hydroshare/hydroshare#851]
Oddly the search for *2015* appears to fail...

- Valid: https://www.hydroshare.org/search/?q=2013
- Valid: https://www.hydroshare.org/search/?q=2014
- **Error:** https://www.hydroshare.org/search/?q=2015 (resolved by rebuild_index)
- Valid: https://www.hydroshare.org/search/?q=2016

Update - 12/29 - Based on Ray's note of being the current year, the search term *dec* also fails

- Valid: https://www.hydroshare.org/search/?q=oct
- Valid: https://www.hydroshare.org/search/?q=nov
- **Error:**  https://www.hydroshare.org/search/?q=dec (resolved by rebuild_index)
- Valid: https://www.hydroshare.org/search/?q=jan

Will be curious to check this again on 1/1/2016 to see if the error shifts to the new month and year.

Other search oddities - apparently *GenericResource* is invalid as well:

- Valid: https://www.hydroshare.org/search/?q=RasterResource
- **Error**: https://www.hydroshare.org/search/?q=GenericResource (resolved by rebuild_index)
- Valid: https://www.hydroshare.org/search/?q=NetcdfResource
- Valid: https://www.hydroshare.org/search/?q=ToolResource

**Comment by rayi113** [comment]
Noting that 2015 s is the current year.  Further debug on Friday Jan 1 2016 to see if 2015 works and 2016 fails?  Also, should add check to see if entered year is greater than the current year.

**Comment by mjstealey** [comment]
> Also, should add check to see if entered year is greater than the current year.

We probably do not want to exclude any search terms as they could be relevant to other data entered by the user. A future year for example could refer to an abstract note for future appearance/publication or even a value of something other than a date. (i.e. After taking 2020 samples of XXX it was discovered that...)

**Comment by mjstealey** [comment]
> Noting that 2015 s is the current year. Further debug on Friday Jan 1 2016 to see if 2015 works and 2016 fails? Also, should add check to see if entered year is greater than the current year.

Still see the same error pattern as before, so it doesn't seem to be associated with the current month or current year.

**Comment by mjstealey** [comment]
@rayi113, @hyi, Out of curiosity I issued a rebuild_index call directly on www and that seemed to resolve our issue. I'm wondering if our current update_index is not sufficient in all cases, but rather a periodic rebuild_index is needed... Thoughts?

**Comment by hyi** [comment]
@mjstealey @rayi113 I am not sure why rebuild_index is needed to fix this issue. Perhaps some scheduled update_index call failed to some degree, which leads solr index in a somewhat not completely correct state, and rebuild_index kinds of reset solr index to an initial correct state. Not sure, perhaps @alvacouch @xuezhaokun @ironfroggy can have better explanations.

**Comment by mjstealey** [comment]
@hyi, @rayi113, I'm not up on solr / haystack enough to know when it's best to use rebuild_index vs update_index... rebuild_index strikes me as kind of a nuclear option when all else fails based on the warning it gives.

```bash
WARNING: This will irreparably remove EVERYTHING from your search index in connection 'default'.
Your choices after this are to restore from backups or rebuild via the `rebuild_index` command.
Are you sure you wish to continue? [y/N]
```

**Comment by mjstealey** [comment]
@hyi - Adding snippet from hipchat with @ironfroggy for reference

<img width="552" alt="screen shot 2016-01-06 at 4 36 23 pm" src="https://cloud.githubusercontent.com/assets/5332509/12155544/bc738f52-b493-11e5-98bb-119688de9846.png">

**Comment by mjstealey** [comment]
@alvacouch, @y-lu - This is the issue referred to on the 1/6/16 team call. As noted a `rebuild_index` did the trick. Had a brief discussion with @ironfroggy which is summarized above ^^^

**Comment by hyi** [comment]
@xuezhaokun @alvacouch Can you evaluate and see whether this issue has been resolved by your real-time solr index update upon resource deletion? If it has been resolved, you can close this issue unless there is more work to be done.

**Comment by mjstealey** [comment]
fixed on www
