### ISSUE TITLE
Add comment sender name to Email notification

### ISSUE THREAD

**Issue by zhiyuli** [hydroshare/hydroshare#852]
Got an email notification saying I have a new comment on one of my resources. The email includes the comment content but no sender's name. I had to login HydroShare to find it out.

![image](https://cloud.githubusercontent.com/assets/10070599/12054062/a3a51598-aedc-11e5-9814-facffab3ad6c.png)

Having something like the HipChat's email notification would be awesome.

![image](https://cloud.githubusercontent.com/assets/10070599/12054067/bac15340-aedc-11e5-888c-61f420d7350d.png)

**Comment by hyi** [comment]
@zhiyuli The fix is merged and deployed to dev. You can test on dev and close the issue if it is working as expected now.

**Comment by zhiyuli** [comment]
@hyi I just tested it on dev and it worked well. I am closing this issue now. Thanks!
