### ISSUE TITLE
Author names in citations to accommodate organizations, multiple first names and spaces in last names

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#855]
I created a resource for which the author is the U.S. Army Corps of Engineers.  See https://www.hydroshare.org/resource/77c54c01ab99439abb263ea0e11b18c3/.  

The citation is stated as
Engineers, U.A. (2016). HEC-HMS Version 4.1, http://www.hec.usace.army.mil/software/hec-hms/, last accessed 1/4/2016.

This should rather be U.S. Army Corps of Engineers (2016). HEC-HMS Version 4.1, http://www.hec.usace.army.mil/software/hec-hms/, last accessed 1/4/2016.

The full text "U.S. Army Corps of Engineers" is to be treated as a last name.

This is a problem that is handled by citation management systems (e.g. Endnote, Zotero) so we should adopt a solution from them if possible.  Endnote (the only one I am really familiar with) uses a convention of placing a comma at the end of the last name.  So for example
U.S. Army Corps of Engineers,
gets parsed correctly but
U.S. Army Corps of Engineers
gets parsed as 
Engineers, U.S.A.C.O 

Use cases to accommodate.
1.  Organization name
"U.S. Army Corps of Engineers"
"National Research Council"
1.  Space in Last Name
   "Sen Gupta" as in Avirup Sen Gupta should be presented Sen Gupta, A. or A. Sen Gupta but not A. S. Gupta.
2.  More than two first names
   William Arthur Philip Louis Windsor should be W. A. P. L. Windsor, not W. A. Windsor

In Endnote these would all be accommodated using the comma convention as
U.S. Army Corps of Engineers,
National Research Council,
Sen Gupta, Avirup
William Arthur Philip Louis Windsor

**Comment by dtarb** [comment]
Refer to #488 for additional background.

**Comment by horsburgh** [comment]
Putting an organization name in the "LastName" field with a trailing comma seems a bit hokey to me.  How would users ever know how to do that?  Why not just implement the ability to enter an organization name that is parsed correctly?  For example, add a radio button?

* The author is a person
* The author is an organization

And then based on which one they pick you parse the input correctly?  The "Name" field is a single string in the Resource Metadata, so it shouldn't matter whether you are storing a person name or an organization name.  We may want to model the whole "Creator" element a little differently for an organization, but if we do this correctly, the ability to create resources with organizations as authors would be a new feature that shouldn't affect the way any of the existing resources are stored.

For example, we might change this (which is the way we have it now for a person as an author):

    <dc:creator>
          <rdf:Description rdf:about="http://www.hydroshare.org/user/10/">
            <hsterms:name>Jeff Horsburgh</hsterms:name>
            <hsterms:creatorOrder>1</hsterms:creatorOrder>
            <hsterms:organization>Utah State University</hsterms:organization>
            <hsterms:email>jeff.horsburgh@usu.edu</hsterms:email>
            <hsterms:address>8200 Old Main Hill, Logan, UT 84322-8200</hsterms:address>
            <hsterms:phone rdf:resource="tel:(435) 797-2946"/>
            <hsterms:homepage rdf:resource="http://jeffh.usu.edu/"/>
          </rdf:Description>
    </dc:creator>

To something like this for an organization:

    <dc:creator>
        <rdf:Description>
          <hsterms:name>Utah State University</hsterms:name>
          <hsterms:creatorOrder>1</hsterms:creatorOrder>
          <hsterms:address>8200 Old Main Hill, Logan, UT 84322-8200</hsterms:address>
          <hsterms:phone rdf:resource="tel:(435) 797-????"/>
          <hsterms:homepage rdf:resource="http://www.usu.edu/"/>
        </rdf:Description>
    </dc:creator>

Or this slightly different variation that stores only "Organization" and not "Name":

    <dc:creator>
        <rdf:Description>
          <hsterms:creatorOrder>1</hsterms:creatorOrder>
          <hsterms:organization>Utah State University</hsterms:organization>
          <hsterms:address>8200 Old Main Hill, Logan, UT 84322-8200</hsterms:address>
          <hsterms:phone rdf:resource="tel:(435) 797-????"/>
          <hsterms:homepage rdf:resource="http://www.usu.edu/"/>
        </rdf:Description>
    </dc:creator>

**Comment by dtarb** [comment]
I was just pointing out how Endnote does it.  Any solution that works is OK.  Don't forget the multiple word last name "Sen Gupta" case.

**Comment by horsburgh** [comment]
I see that this issue is slated for Release 1.9.0. Organizations as an Author is something we really need for our iUTAH datasets, so I'm hoping it can receive some attention.  This issue is the same as or at least related to #1360 and #1310.

I think the "enhancement" tag is incorrect. One can add an organization as the Author but it gets abbreviated like a person's name and is displayed incorrectly. I think it's a bug - or at least an oversight.

**Comment by pkdash** [comment]
@horsburgh I will be helping @mohamedmorsy to implement for release 1.9.0.

**Comment by horsburgh** [comment]
@pkdash and @mohamedmorsy  - thanks. Glad this is going to get some love.

**Comment by jsadler2** [comment]
@pkdash @mauriel133 we have partially solved the problem. A user can now add an organization as an author and/or an author with multiple first and/or last names. Here is a screen shot of the modified dialog box: 
![image](https://cloud.githubusercontent.com/assets/6943441/20283665/eb6f5986-aa87-11e6-8941-01f4c388614b.png)

**Comment by jsadler2** [comment]
@pkdash @mauriel133 the problem we face now is that this is not consistent with the way the name field is stored in the HydroShare DB for creators (one name field) (see attached)
![image](https://cloud.githubusercontent.com/assets/6943441/20283779/62e08cd8-aa88-11e6-96b5-66a1ca8210ff.png)

Do you have any suggestions? How can we make the manually added authors/organizations whose first names and last names are separated by a comma work with the names in the DB as creators that have nothing to distinguish first from last names? Our [latest code is on branch 855](https://github.com/hydroshare/hydroshare/commit/a45b15c2dc81d12c01ea29512e78067b0e149883) if you would like to take a look.

**Comment by pkdash** [comment]
@jsadler2 For the existing person names for which we don't have comma to separate first names from last names we should assume the last word in the name is the last name.  If this assumption is not correct for some names,  the resource editor needs to edit the name by putting a comma in the name to separate first names from last names. @dtarb your thoughts on this.

**Comment by dtarb** [comment]
I suggest what I put at the beginning, i.e. the Endnote rule

The first comma in the string indicates the end of the last name.  Any later comma's are irrelevant
If there are no commas then the last word is the last name
So for example
U.S. Army Corps of Engineers,
gets parsed as
Lastname = "U.S. Army Corps of Engineers"
Firstname = ""
Citation would be 
U.S. Army Corps of Engineers

William Arthur Philip Louis Windsor  gets parsed as
Lastname = "Windsor"
there are 4 first names
Citation would be
Windsor, W.A.P.L

Sen Gupta, Avirup gets parsed as
Lastname = "Sen Gupta"
Firstname = "Avirup"
Citation would be
Sen Gupta, A. 

With this approach there would be no need for separating whether the party is a person or organization.  The same rules apply to both.

I would also suggest that for a creator that is an organization that name can be left blank in which case the organization is required and the entire organization string gets interpreted as the lastname.

As you implement these there should be no automatic changing of content already in databases.  I think that owners or editors should go back and fix their resources as needed.

**Comment by mohamedmorsy** [comment]
@dtarb exactly we did your suggestion for enhancing the citation. The only thing we added to your suggestion is the choice between person and organization. In the author form, there is a field for organization. We have these choices (Person Or Organization) to manage this field i.e. if the author is person the organization field will appear, while if the user is organization the organization filed will disappear. We did that for not have redundant information as if the author is organization, the name and organization field will be the same. Also we added placeholder to the name field to guide the user for entering the name correctly with the comma separation if it is for a person and without comma if it is for an organization (see below):

![image](https://cloud.githubusercontent.com/assets/5543781/20308046/4381232e-ab10-11e6-867f-7c77d8884077.png)


For example, if we have the author as an organization, "U.S. Army Corps of Engineers," the author form looks like the following:

![image](https://cloud.githubusercontent.com/assets/5543781/20308074/60618bd2-ab10-11e6-92b3-4bdaa3ee83cd.png)

The generated citation looks like the following:

![image](https://cloud.githubusercontent.com/assets/5543781/20308096/794000b6-ab10-11e6-9c49-c38a91ac3458.png)

If we have the author as a person, William Arthur Philip Louis Windsor, the author looks like the following:

![image](https://cloud.githubusercontent.com/assets/5543781/20308163/a994005a-ab10-11e6-97c1-102720ce4930.png)

The generated citation looks like the following:

![image](https://cloud.githubusercontent.com/assets/5543781/20308187/bff6bec8-ab10-11e6-9b52-a697736cdcf6.png)

@pkdash We still have the issues that @jsadler2 stated and it would be great if we get suggestions or help on solving these issues.

**Comment by dtarb** [comment]
I do not understand the issue that @jsadler2 stated.  I'll discuss with @pkdash 

I think it is a bit too complicated  to require the radio button to flip between organization and name.  I suggest if the author is an organization, just put the organization name in organization and leave name blank.

I think a bit more guidance than the placeholder in the name field is needed.  I suggest some text above the name field:

> Names may be entered Lastname comma Othernames or Othernames Lastname.  Examples
> John William Peter Stuart
> Stuart, John William Peter 
> To indicate multiword Lastnames place the last name first followed by a comma, e.g. "de Vries, Peter John"

**Comment by horsburgh** [comment]
I think when this form opens there should be a radio button asking if the author is a person or an organization (default would be person, and the Name field would be shown). When the user selects "Person", the user should be able to specify an existing HydroShare user as the author or a type in a person's name. If "Organization" is selected, the user should be able to select an existing HydroShare group as the author or type in an Organization name. Also - if the user selects "Organization", I think the "Name" field should either be disabled or disappear.

Seems like these changes wouldn't be too difficult to implement, and having the switches would enable the right lists of users or groups to show up based on the user's choice.

But, I don't think these radio buttons need to take up anywhere near the amount of space that is currently allocated to them. I do think the switches are needed because users will be confused about whether the Organization name should go in "Name" or "Organization" if you leave them both active, and since the citation is automatically generated, the right information needs to go in the right place.

**Comment by horsburgh** [comment]
Also - if you do put a bunch of text to clarify how to enter information, I suggest doing it as hover text or a link because putting that much text above a single field on the form will really clutter things up.

**Comment by jsadler2** [comment]
I've made some progress on this. There are still some things to do:

- [ ] Write unit tests
- [ ] Automatically populate form when a HydroShare Group is selected

There are somethings we need feedback on:
- @dtarb @horsburgh How should we deal with organization/person combinations. Right now, if an organization is the first author (by 'organization' I mean that the 'name' field is null but the 'organization' field is not) the organization is listed in the citation but none of the people. If a person ('name' is not null) is first author the organization author(s) is/are not included in the citation. Is that a good approach? Should we even allow other authors if an 'organization' is the author? That may get a little tricky since it's actually the same table in the db and there is no hard distinction.
- @mauriel133 [get_user_info_ajax_submit](https://github.com/hydroshare/hydroshare/blob/develop/theme/static/js/resourceLandingAjax.js#L443) is the function that I think we need to pattern getting the group info when adding a group as an author. Anyway you could help us implement that?

**Comment by dtarb** [comment]
If the author is a person whether or not their organization field is filled out does not matter for the citation.  The citation just lists their name (as is common bibliographic practice).

I think we should allow people/organization combinations.  

I am puzzled by  your statement that if an organization is the first author, none of the people are listed.  If creator/author records have been written for the resource they should be in the citation list.  Following is an example.

![capture](https://cloud.githubusercontent.com/assets/3456833/20579695/7cf962d4-b18b-11e6-87d6-4952fef3ede9.JPG)

Auto populate of the form when a group is selected can be lower priority in favor of getting this done.

**Comment by mohamedmorsy** [comment]
@dtarb @horsburgh @goodalljl @jsadler2  the latest citation work has been deployed on testservices.hydroshare.org for test purposes.

**Comment by horsburgh** [comment]
@mohamedmorsy and @jsadler2 - I just did a quick test. I added a new organization as an author to this resource:

https://testservices.hydroshare.org/resource/1a25b11fa1354773b6edb9495e754f4e/

The new organization shows up in the citation and in the list of authors on the Authorship tab, but it doesn't show up in the list of authors at the top of the page.

**Comment by mohamedmorsy** [comment]
This has been fixed in the latest commit. I will update
testservices.hydroshare.org and let you know to check again. Thanks for
looking at this.

**Comment by mohamedmorsy** [comment]
@horsburgh bug fixed and testservices.hydroshare.org is up to date now. Please check again.

**Comment by horsburgh** [comment]
@mohamedmorsy and @jsadler2 - I just tried again and it looks good. I added and removed multiple authors and groups to this resource:

https://testservices.hydroshare.org/resource/5d952304c16d4955bdc36acf4e83d56e/

Everything worked as I expected it to. One question - are you planning on having functionality to add an existing HydroShare user group as an author?

**Comment by mohamedmorsy** [comment]
@horsburgh yes we are planning to do that but we need @mauriel133  help. We can do this like a new issue after the AGU release.

**Comment by horsburgh** [comment]
OK sounds good.

**Comment by jsadler2** [comment]
The pull request has been completed for this. Closing.
