### ISSUE TITLE
Expand website notification about email confirmation

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#864]
Please expand the website notification message that appears in HydroShare after a user has requested a new account to state: "A verification email has been sent with a link for activating your account.  If you do not receive this email please check your spam folder as sometimes the confirmation email gets flagged as spam.  If you entered an incorrect email address, please request an account again."

This is to encourage users who do not get the email to look in their spam folders as some email systems seem to direct the email from support at hydroshare.org to spam.

**Comment by hyi** [comment]
@dtarb This has been merged and deployed on dev. Could you verify on dev and close if it is working as expected?

**Comment by dtarb** [comment]
Thank you.
