### ISSUE TITLE
"NFIE snapshot" resource type

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#872]
As discussed in the call on Wed 1/6, we need a "NFIE snapshot" resource type that encapsulates the idea of a NFIE regional flood forecast and gives it a real resource type so that visualizations can then be written for it. This will allow us to disambiguate between NFIE data instances, and will allow us to expose all of NFIE data as a collection rather than a simple resource. This in turn enables the actual use case for NFIE data, which is to download one snapshot and use it to solve a problem.

**Comment by dtarb** [comment]
Closing this.  Publication of NWM data is being handled separately and this issue is moot at this point.
