### ISSUE TITLE
Clarify wording on Create Resource page

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#88]
The current (Sandbox - see below) Create Resource Labeling needs to be changed

The title and URL for this page should be "Create Resource"
The bullets should read
- Files you upload here will be grouped together into a "Resource"
- File size is limited to 10 GB per file
Delete the 3rd and 4th bullet

![untitled](https://cloud.githubusercontent.com/assets/3456833/5913930/6b3d6452-a5ba-11e4-87e1-a0786107737d.png)

**Comment by pkdash** [comment]
This has been fixed in the latest '62-resource-creation-new-workflow' branch. Initial testing can be done on the sandbox server (once deployed).

**Comment by dtarb** [comment]
Tested and approved
