### ISSUE TITLE
print names of resource objects

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#890]
I would like to make a simple change to BaseResource that will enhance debugging and testing. 
The method __unicode__ is responsible for converting an object to a printable format in print statements, so that adding this code

```
def __unicode__(self): 
    return self.metadata.title
```

to baseResource will cause a BaseResource r to be printed (via print(r)) as  

```
<BaseResource: my title> 
```

This would make it much easier to debug test cases and log messages. We could put the short id into the __unicode__ to make it even more useful. 

I am using this hack on my branches and finding it useful.

**Comment by cuahsimarko** [comment]
I think this is related https://docs.djangoproject.com/en/1.10/topics/python3/

**Comment by Castronova** [comment]
@alvacouch close or act on if needed

**Comment by alvacouch** [comment]
Done in prior pull requests.
