### ISSUE TITLE
access control changes for handling publication, groups

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#893]
As discussed with @dtarb and @horsburgh the following changes are needed to access control for handling publication and groups: 
1. _Honor immutable flag system-wide_ and squash CHANGE privilege to VIEW for immutable    resources. Leave OWNER privilege alone. Thus in listings, OWNERs remain owners but all else is downgraded to VIEW.  
2. _Limit active privilege to that of the last assigner._ _Last privilege assigned is binding_ instead of minimum privilege over all assigners. This is partly so that the UI can more easily depict provenance.
   
   a. Disallow sharing at same privilege as already held by assignee 
       (This prevents malicious downgrading of privilege by non-owners; e.g., malicious user first assigns CHANGE redundantly, then gains undo privilege and downgrades to VIEW(!)) 
   b. Owners can reduce or eliminate privilege. 
   c. Everyone else can increase privilege if they have that privilege themselves, but cannot reduce privilege. 
3. Allow unsharing of privilege by explicitly assigning PrivilegeCodes.NONE to a user. 
   (Thus the series of assignments -- in time order -- will represent the complete provenance of changes in access.)
1. Deprecate undo_share_*_with_* and enhance unshare_*_with_* instead to handle all use cases. 

These require data migrations in order to correctly depict privilege afterward.

**Comment by alvacouch** [comment]
@pkdash @mauriel133 @dtarb @horsburgh Part of this issue is already addressed by #867 .

At this point, the following issues remain: 
   1. An issue of **semantics:** eliminate multiple sharing grants to same user and resource. At any time, there is exactly one privilege grantor. That grantor or an owner can unshare. (branch 893 - a ...) 
   2. An issue of **performance**: make that interpretation of semantics run very fast. (branch 893 - b ...) 

To avoid a really complex pull request (like the one that got us to this state for #867), I plan to split these changes among two pull requests rather than one. The first pull request (893 - a) will change semantics at the cost of some performance -- the resulting queries will run slightly -- but tolerably -- slower than before. The second pull request (893 - b) will address the performance issue. 

Note that since I am changing semantics, we will need to adapt all uses of `share_*`, `can_share_*`, and `get_*_unshare_users` to the new semantics. In particular: 

1. `undo_*`, `can_undo_*`,  and `get_*_undo_users` go away completely. 
2. `share_*_with_*` prohibits some new behaviors, e.g., downgrading privilege or setting privilege to what it is now. 
2. `unshare_*_with_*` changes prohibits some new behaviors, e.g., one can only unshare if one is an owner or one is the last grantor of the privilege. Previous grantors cannot unshare what they shared anymore. (Unless they become the last grantor via an unshare of a previous grantor). 
3. `get_*_unshare_users` and `can_unshare_*`change return values.

**Comment by pkdash** [comment]
@alvacouch and @dtarb Since we are planning to make further changes to access control, here is a thought for your consideration:

I have looked and used the access control code probably the most. Based on my understanding of the current implementation, I feel the complexity in code (e.g. complex database queries) can be reduced quite a bit if we keep the record for provenance  in a log/history table rather than in the active table (e.g. UserResourcePrivilege). That means the active table should have only one record of access permission for a given user (or group) and resource at any time. Then we don't have to worry about multiple grantors, mutiple permissions for a given user and resource at all. That I think would make the code for some of the access control api much simpler without breaking the access rules.

**Comment by alvacouch** [comment]
This is exactly the plan. However, we need to be able to query the provenance table. So the first PR will be to query into the provenance table directly, and the second PR will be to create the clean access table.

**Comment by alvacouch** [comment]
@pkdash @dtarb It's really up to you whether I combine these or submit the PRs separately. This is the way I must develop in order to ensure that everything works. Development is a two step process. The first step is to change semantics, make sure that works, and then make things faster. 

I can easily combine these into one PR, but the result will be more confusing to review.

**Comment by pkdash** [comment]
@alvacouch Would prefer 2 PRs then.

**Comment by alvacouch** [comment]
This has been handled in PR #1710  and previous ones.
