### ISSUE TITLE
My Resources Page: Enhancements to the Resource Listing

### ISSUE THREAD

**Issue by horsburgh** [hydroshare/hydroshare#897]
Additional columns to consider for the resource listing on the My Resources page:
- [x] First Author
- [x] Date Created
- [ ] Statistics (e.g., views downloads, etc.)

This is a new enhancement/feature request, so let us know if you think these are good ideas.

**Comment by dtarb** [comment]
Yes I generally like these.  Just as we are able to list multiple owners, we should also consider listing multiple authors (not only the first author).

Also I would advocate consistency between the MyResources and Discovery page listings.  Right now Discovery uses First Author and MyResources uses Owner.  Potentially this gives both to both.  I do worry about the table getting too wide, so we need to be cautious to not add to much.  It will come down to how well it can be laid out.  Also adding statistics will require making sure this capability is part of our use tracking (or adding it).

**Comment by mauriel133** [comment]
I think the table has enough space to accommodate these columns. Although, I'm not sure if we are tracking statistics at this point. @pkdash do you know if any statistics are available?

If we are going for consistency on both pages, should we list owners or authors?

**Comment by dtarb** [comment]
I suggest a column "First Author", not "Owner" on both Discover and My Resources for consistency.

**Comment by mauriel133** [comment]
'First Author' and 'Date Created' columns have been added. Statistics not in the scope for now.

**Comment by horsburgh** [comment]
@Castronova - are we tracking any statistics on individual resources that would be useful for closing out this issue? For example, number of views or number of downloads? If we are not tracking anything now that @Maurier could add to the My Resources page, we should just close this issue and call it done for now.

**Comment by Maurier** [comment]
@Castronova Are we tracking the statistics discussed here at this point?

**Comment by horsburgh** [comment]
These statistics are for the My Resources page. We are now tracking and displaying view and downloads for each individual resource on its landing page:

![image](https://user-images.githubusercontent.com/3485902/55814786-72e51000-5aac-11e9-8905-94f7b0a94829.png)

So, could we not add these to the table on the My Resources page to complete this issue?

**Comment by Maurier** [comment]
> So, could we not add these to the table on the My Resources page to complete this issue?

@horsburgh I could add these to the table. Could you confirm if this is what we want?

**Comment by pkdash** [comment]
@Maurier We are displaying resource download and view counts already on resource landing page. So you can easily get those on my resources page by using ```res.download_count``` and ```res.view_count```. However, these two model fields need to be selected as part of the query, otherwise it will slow down page loading.

**Comment by horsburgh** [comment]
@Maurier - that was the original intent of the last item in my original issue posting above. I still think it would be useful to have these on the My Resources page, but we do risk cluttering the table of resources. I don't want to have to scroll horizontally to see these statistics. Do you think you can reasonably add them without (1) slowing down the page load and (2) messing up the table?

**Comment by pkdash** [comment]
@Maurier I can point you to one liner change in backend to fetch these two extra fields (download_count, view_count) if you decide to use those in my resources page. Once you make this backend change, it should not slow down page load.

**Comment by Lizabrazil** [comment]
Is this the right issue to address the miscalculated Views and Downloads? I've had a user who has already noticed that we are not counting these accurately, as we are counting the creator's views and edits to the resource in the cumulative count. @alvacouch I think we chatted and you have the backend to fix this issue? Or maybe you said you were working on it in the future?

**Comment by Lizabrazil** [comment]
I do not think this should be pushed to the My Resources page too until we are calculating it accurately.

**Comment by Castronova** [comment]
Stale
