### ISSUE TITLE
JENKINS CI - Developer Deployment Usage

### ISSUE THREAD

**Issue by mjstealey** [hydroshare/hydroshare#898]
**Do not close this ticket. It is for tracking purposes.**

Reserve a VM for deploying your code using [Jenkins](http://ci.hydroshare.org:8080/view/4.%20Developer%20Builds/job/branch-builder/), complete this prior to deploying your work:

Check the VM you want to use, add your Github name and reserve until date (Uncheck the box when you are done with the VM)
- [x] ~~park.hydroshare.org~~: (under reconstruction)
- [x] ~~new-playground.hydroshare.org~~: (under reconstruction)
- [x] **new-riverdev.hydroshare.org**: dedicated to @devincowan (under reconstruction--iRods issues)
- [x] **new-testservices.hydroshare.org**: ( @pkdash using for resource type rename in UI testing)  
- [x]  **cuahsi-dev-1.hydroshare.org** dedicated to @alvacouch 
- [x]  **cuahsi-dev-2.hydroshare.org** dedicated to @alvacouch 
- [ ] ~~dev-hs-1.cuahsi.org~~ Scott Black/UNDOCUMENTED
- [ ] ~~dev-hs-2.cuahsi.org~~: Alva/SOLR bug fix
- [ ] ~~dev-hs-3.cuahsi.org~~:  Manesh/development of file interface to 3rd party storage
- [ ] ~~dev-hs-4.cuahsi.org~~:  Alva and Zhaokun using this. UNKNOWN STATUS
- [ ] ~~dev-hs-5.cuahsi.org~~: Dan Palmer - Testing
- [ ] ~~dev-hs-6.cuahsi.org~~: Scott Black
- [ ] ~~dev-hs-7.cuahsi.org~~: 
- [ ] ~~dev-hs-8.cuahsi.org~~: (Available)
- [ ] ~~dev-hs-9.cuahsi.org~~v*: UNKNOWN/REBUILDING

Need an account on [http://ci.hydroshare.org:8080/](http://ci.hydroshare.org:8080/)?
1. Sign up [here](http://ci.hydroshare.org:8080/signup)
2. ~~Send a note to [Michael Stealey](mailto:stealey@renci.org) with your account username to get permission to deploy.~~

**Comment by cuahsimarko** [comment]
@cbcunc Ok to close this or does it serve an ongoing purpose?

**Comment by dtarb** [comment]
This is the developers system for reserving and coordinating who is using the various staging machines.  This serves an ongoing purpose.  Notice that as of 2/6/19 there are two machines reserved till dates of 2/10/19 and 2/28/19.

**Comment by cuahsimarko** [comment]
dev-hs-1 through dev-hs-6 are wrong. There is a dev-hs-7, which I'm using. Drew is using 6. Mark Henderson is no longer using 2, but someone else is...

**Comment by cuahsimarko** [comment]
As this is not a source code issue I hope it could be moved to a different team/organizational/project documentation area or process.

**Comment by dtarb** [comment]
I am fine moving this some place else, but am not in favor of closing this until that other place is up and running and working for the developers.  Both @Maurier and @hyi have current machines checked out using this process that has served the team well since 2016.  I

**Comment by martinseul** [comment]
still being used

**Comment by devincowan** [comment]
AFAIK @cbcunc has started decommissioning these
