### ISSUE TITLE
Direct link to private resource should redirect to login when user is not logged in

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#899]
An attempt to open a HydroShare URL for a private resource should redirect to login, or at a minimum tell the user that login is required when a user is not logged in.

Use case.  A user emails a resource link to another user.  The 2nd user clicks on the link, but gets at present a 403 forbidden error.  It would be more friendly to post a message saying "To access this resource you need to log in" and after a suitable delay redirect the user to the login page while remembering the page the user is trying to get to, so that once logged in they end up on the right landing page.

**Comment by hyi** [comment]
@dtarb With the implementation of 403 forbidden page improvement as your mockup screen capture where a sign in link is provided with detailed prompt information, I think this issue can be closed since it has been address as part of that issue #697

**Comment by dtarb** [comment]
Thanks.  Closing.
