### ISSUE TITLE
Remove all references to 'dublincore' submodule in hs_core

### ISSUE THREAD

**Issue by pkdash** [hydroshare/hydroshare#90]

**Comment by dtarb** [comment]
@pkdash has this been addressed.  Close if you are happy.

**Comment by pkdash** [comment]
This cleanup yet to be done.

**Comment by dtarb** [comment]
How to test whether this is done?  @ironfroggy or @mjstealey please close this issue if you think it is done, otherwise indicate what is still outstanding.

**Comment by pkdash** [comment]
@dtarb Recently I realized that my cleanup work for removing dependency on 'dublincore' submodule did not completely remove all references. I need to fix that. But I think we don't have time to do that for release 1.5. Since 'dublincore' is taken out of the list of installed apps in the settings.py file, if we are able to create and edit each of the supported resource types and don't see any error related to this submodule then that would be a good test in the absence of unit tests.

**Comment by dtarb** [comment]
@pkdash OK.  I'll put this on the 1.5.1 (NFIE) milestone then.

**Comment by ironfroggy** [comment]
The actual submodule must be removed, so that any remaining references will
cause an error if they are overlooked.

On Sat, May 9, 2015 at 5:55 PM, David Tarboton <notifications@github.com>
wrote:

> @pkdash <https://github.com/pkdash> OK. I'll put this on the 1.5.1 (NFIE)
> milestone then.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hydroshare/hydroshare/issues/90#issuecomment-100552446>
> .
>



-- 


*Calvin Spealman*Lead Front-end Developer

calvin@caktusgroup.com <calvin@caktusgroup.com>
www.caktusgroup.com

**Comment by pkdash** [comment]
@mjstealey Not sure how to remove the submodule 'dublincore' from the project. Is this something you can do?

**Comment by pkdash** [comment]
@mjstealey Can you remove the 'dublincore' submodule from hydroshare codebase?

**Comment by hyi** [comment]
@pkdash dublincore submodule is removed on dev and things appear to work as expected. Could you test and close this issue if nothing breaks?

**Comment by hyi** [comment]
@pkdash could you check and close this issue if it is resolved?

**Comment by hyi** [comment]
Closing this issue since dublincore submodule is removed from the code base. @pkdash you can reopen it if you observe any issue with it.
