### ISSUE TITLE
Use icon to indicate sharing status on My Resources

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#909]
The current alpha deploy has a new column Sharing status in My Resources.  Our column real estate is precious, and I did not see this listed in the issue #897 where additional columns were discussed.  I'd prefer not to take up so much space with this, and suggest instead an icon, e.g. a green open padlock for public, a red closed lock for private and an orange half open lock for discoverable.  This would make space for some of the items, notably Authors, discussed in #897 to be added.

**Comment by mauriel133** [comment]
It was listed as part #770. Should I include the newly implemented shareable flag as an icon as well?

**Comment by dtarb** [comment]
I think that  icons about the same size as the star and label is about right for Shareable and Public/Discoverable/Private.  I think we need to be a bit careful about not having too many columns and having columns that are the most important.  Things like Public/Discoverable/Private and Shareable, I do not think have to be that prominent in a users display.  They are important for us now since we have worked hard on them, but ideally they should just blend in to the use of the system naturally without being overbearing.  Things like the Authors are more important.

**Comment by hyi** [comment]
@mauriel133 @horsburgh @dtarb Now that resource publication is being implemented, we'd need a icon for published flag as well.

**Comment by horsburgh** [comment]
I have been to websites before with tabular displays where the user is allowed to specify which columns show up in the table. Thus, they can customize their view to what suits them best.  However, I think that while nice, this functionality is probably much less important than some of the other things that remain unimplemented in HydroShare.

**Comment by dtarb** [comment]
My Resources is really nice on www as it is (without scrolling) so I agree with Jeff that there are other priorities (like the user profile editing and getting the content for the user data model in line with specifications) that should be higher.  At some point coming back to customizing the columns would certainly be appealing.

**Comment by mauriel133** [comment]
I've small icons to indicate sharing status (including publication). Can be tested at https://riverdev.hydroshare.org/

**Comment by horsburgh** [comment]
@mauriel133 - I'm not sure if it's just me, but those icons look a little fuzzy. Is that something that can be fixed in a couple of minutes?

**Comment by mauriel133** [comment]
Yes, I will fix them.

**Comment by mauriel133** [comment]
I cleaned them up now.

**Comment by mauriel133** [comment]
The icons have been implemented and deployed.

**Comment by hyi** [comment]
It has been deployed. Closing.
