### ISSUE TITLE
Make generic resource landing page template easily extensible

### ISSUE THREAD

**Issue by pkdash** [hydroshare/hydroshare#92]
Add more template blocks to genericresource.html which can be then easily replaced by other resource types for their landing page requirements if needed.

**Comment by dtarb** [comment]
@pkdash has this been addressed with recent work.  Close if you think so.

**Comment by pkdash** [comment]
This has not been addressed yet.

**Comment by dtarb** [comment]
@pkdash has this now been addressed.  Should it be added to a milestone?

**Comment by pkdash** [comment]
@dtarb This has not been addressed. This never got to the priority list. I have also not yet seen from any resource type developer the need for this template to be more extensible. It seems like we don't have an immediate need to implement this. We can push it to may be release 1.7 or later.

**Comment by dtarb** [comment]
@pkdash this is an enhancement that you suggested.  What would be it's benefit.  If no one is crying out for it, should be just decide not to implement and close out, rather than indefinitely pushing down the road?

**Comment by pkdash** [comment]
@dtarb Closing it. When there comes a need for it we can create this issue again for implementation.
