### ISSUE TITLE
REST interface to groups is outdated

### ISSUE THREAD

**Issue by alvacouch** [hydroshare/hydroshare#920]
Several routines in hs_core/hydroshare/users.py refer erroneously to the old definition of groups and are thus inconsistent with other routines _in the same file_ that refer to new group access control. 
These are documented as being used in the REST interface.

**Comment by selimnairb** [comment]
@alvacouch You have self-assigned this issue.  If you are intending to fix these inconsistency in the REST interface, that is fine.  If so, please develop some simple unit tests to test that the behavior is correct; we have recently added REST API tests to the main code base, which you can find [here](https://github.com/hydroshare/hydroshare/tree/develop/hs_core/tests/api/rest).  

If you would like me to take a look at it, please provide more details on the offending methods.  Thanks.

**Comment by pkdash** [comment]
We need a cleanup of the internal api. Similar to hs_core/hydroshare/users.py there are issues with hs_core/hydroshare/resource.py.

**Comment by Castronova** [comment]
@alvacouch close or act on if needed

**Comment by alvacouch** [comment]
Obsolete due to update of REST API.
