### ISSUE TITLE
REST API code clean-up

### ISSUE THREAD

**Issue by selimnairb** [hydroshare/hydroshare#927]
There is some clean-up that needs to be done to the REST API code.  This issue is a running list.

- [x] Make sure that all Mixins appear before the base class (this is not the case [here](https://github.com/hydroshare/hydroshare/blob/develop/hs_core/views/resource_rest_api.py#L95) for example)
- [x] Make hsapi/scimeta return XML instead of JSON
- [x] Add resource landing page URL to system metadata returned
- [x] Add missing unit tests
- [x] Upgrade to a version of django-rest-framework that is compatible with Django 1.8

**Comment by selimnairb** [comment]
@pkdash @alvacouch Can you add any recently discovered REST API code clean-up issues to this list?  Thanks.

**Comment by selimnairb** [comment]
@alvacouch Please add items for your recently discovered REST API code inconsistencies so that I an others my track them.  Please also indicate what of these items are you implementing by referencing this issue in your commits.  Thanks.

**Comment by pkdash** [comment]
@selimnairb I see there are some 'TODO' comments in ```resource_rest_api.py``` that may need to be fixed. Apart from that I don't see any issue with the REST API as it relates to code cleanup of the existing REST API code. However, there is quite a bit of cleanup needs to be done to the internal api as per this issue #931.
