### ISSUE TITLE
Unable to add discoverable resource to My Resources

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#928]
This may be a design decision, but it warrants reconsideration.  I am unable to add a discoverable resource to My Resources.  There is no green add to My Resources on the landing page interface.  The case in point is this resource https://www.hydroshare.org/resource/285a5b5714c549ac8bba269b79863c0a/

@horsburgh @mauriel133 @alvacouch could you please comment on whether we think a user **should** be able to put a discoverable resource in their My Resources.  If not, we can close this issue.  If yes, then this is an interface (and perhaps backend) issue to fix.

**Comment by mjstealey** [comment]
@dtarb - That resource is already shared with you and is already part of your my-resources page... Do you really want to see the green icon for a resources that is already part or your My Resources?

A user that has not had that resource shared with them will have the icon / option available. (image attached)

![screen shot 2016-01-30 at 9 59 27 am](https://cloud.githubusercontent.com/assets/5332509/12696415/70a44e42-c738-11e5-858d-9bda632bf0b4.png)

**Comment by dtarb** [comment]
OK.  My mistake.  I'll close this.
