### ISSUE TITLE
Fuse mount iRODS resources as /mnt/irods_fuse

### ISSUE THREAD

**Issue by mjstealey** [hydroshare/hydroshare#930]
Fuse mount iRODS resources as /mnt/irods_fuse
- [ ] Create mount when USE_NGINX = true
- [ ] Serve files from /mnt/irods_fuse using Nginx instead of from uWSGI

**Comment by selimnairb** [comment]
What is the motivation for doing this?  (to get around filesize limitations?)  If it's just performance, we should test to see if serving from a FUSE-mounted volume is actually more performant (e.g. lower latency, higher bandwidth).

**Comment by mjstealey** [comment]
> we should test to see if serving from a FUSE-mounted volume is actually more performant

Exactly the reason this is being done.

**Comment by dtarb** [comment]
There is also functionality associated with editing resource files (e.g. operating on a netCDF or TIFF file) that in the present implementation would require copying the file to Django, doing the work, then copying it back to iRODS that taxes Django file storage and bandwidth that we hope FUSE may get around.

**Comment by ironfroggy** [comment]
FUSE iRODS is still going to require that network transfer, however, it will be more performant if the FUSE iRODS plugin is smart about how much of the file it caches and if the work that needs to be done only needs to access part of a file. If the work being done on the Hydroshare side requires consuming the entire file, then this won't be any different and still requires a copy back and forth. Worth testing of course!

**Comment by dtarb** [comment]
With FUSE the problem is delegated to iRODS, so part of the consideration is whether the abstraction it provides is better than what we can do ourselves and have to maintain ourselves.  Given the scale of the iRODS effort compared to us delegating the problem is attractive, but we await full evaluation of performance impacts.

**Comment by mjstealey** [comment]
nginx work to be picked up in new issue
