### ISSUE TITLE
Cleanup hs_core internal api

### ISSUE THREAD

**Issue by pkdash** [hydroshare/hydroshare#931]
This involves cleaning code (primarily deleting dead code) in the following files:
hs_core\hydroshare\discovery.py
hs_core\hydroshare\hs_bagit.py
hs_core\hydroshare\resource.py
hs_core\hydroshare\social.py
hs_core\hydroshare\utils.py
hs_core\views\discovery_api.py
hs_core\views\resource_api.py
hs_core\views\utils.py
hs_core\forms.py

**Comment by ironfroggy** [comment]
@pkdash can you detail at all

1) what sort of cleanup are you expecting to be done in these?
2) where is this list and this directive for clean up coming from?

**Comment by pkdash** [comment]
@ironfroggy The cleanup would include things like:

- Correcting implementation of some of the functions which we are currently not being used but most likely to be used (based on the api specification)
- Removing dead code
- Cleaning up dockstring 

I am not sure I understand your question 2).

**Comment by pkdash** [comment]
@alvacouch, @hyi and @dtarb I plan to work on this issue over next couple of days. Primarily I will be removing dead code. Let me know if you have any concerns.

**Comment by pkdash** [comment]
This cleanup has been done. So closing.
