### ISSUE TITLE
Log In issue on hydroshare.org and www.hydroshare.org

### ISSUE THREAD

**Issue by yirugi** [hydroshare/hydroshare#934]
It seems that login session is different between hydroshare.org and www.hydroshare.org .
Even though I logged in to www.hydroshare.org, I'm not logged in on hydroshare.org, and vice versa.

This causes a problem on implementing SSO service. The SSO client side cannot decide which domain users are logged in, so users may see the login page again even though they already did.

**Comment by yirugi** [comment]
If a user enters 'hydroshare.org' , it is reformatted to 'www.hydroshare.org'.
But, if a user enters 'https://hydroshare.org', it cannot be reformatted.

**Comment by hyi** [comment]
@yirugi It appears this issue has been fixed. Please verify and close this issue if it has been fixed.
