### ISSUE TITLE
sign-up page is not accessible (404 error) in development environment

### ISSUE THREAD

**Issue by ahmetartu** [hydroshare/hydroshare#935]
I wanted to create a user for testing purposes in development version. I managed to create a user in previous development version but now it fails in the new version. 

I pulled the current source base using `git pull`. and then ran the docker instances via `docker compose -d`. I'm able to access to all pages including main page, my resources etc. flawlessly, but now I got the 404 (Page not found error) when I clicked on "Sign up now" button on the main page. I attached the docker instance via `docker attach --sig-proxy=false hydroshare_hydroshare_1` to track the error and saw the following message:

`[03/Feb/2016 19:55:36] "GET /sign-up/ HTTP/1.1" 404 1577`

and the screenshot looks like that:

![screenshot_hydroshare-signup](https://cloud.githubusercontent.com/assets/3846596/12795459/d61373c6-ca7f-11e5-9755-7ba1145a7450.png)

Thanks...

**Comment by mjstealey** [comment]
@ahmetartu - For convenience we've put together a control script for HydroShare since it has many moving parts.

It is the `hsctl` script in the main hydroshare directory.

```bash
$ ./hsctl --help
*** HydroShare Control script ***
usage: ./hsctl loaddb          # loads database specified in hydroshare-config.yaml into running container
usage: ./hsctl managepy [args] # use the arguments in a manage.py [args] call from the hydroshare container
usage: ./hsctl maint_off       # removes maintenance page (only if USE_NGINX = true)
usage: ./hsctl maint_on        # displays maintenance page (only if USE_NGINX = true)
usage: ./hsctl rebuild         # deletes hydroshare container contents only and deploys using exsiting database
usage: ./hsctl rebuild --db    # deletes all database and container contents and deploys from scratch
usage: ./hsctl rebuild_index   # rebuild solr index in a non-interactive way
usage: ./hsctl reset_all       # remove all data, containers and images that were previously deployed
usage: ./hsctl restart         # restarts the hydroshare container without rebuilding
usage: ./hsctl start           # attempts to start all containers
usage: ./hsctl stop            # stops all running containers
usage: ./hsctl update_index    # update solr index in a non-interactive way to be run as a cron job
```

If you've just installed the code and are running for the first time, or want a fresh start, you'd want to use `hsctl rebuild --db`.

After that a `hsctl rebuild` call will rebuild the primary containers but keep your database intact.
A `hsctl restart` call would simply restart the primary hydroshare container.

[Reference](https://github.com/hydroshare/hydroshare/wiki/running-hydroshare)

**Comment by ahmetartu** [comment]
Thanks Michael, I ran the following commands in order:

$ `git pull` # for fetching the latest code snapshot
$ `./hsctl rebuild`
$ `./hsctl restart`
$ `docker attach --sig-proxy=false hydroshare_hydroshare_1`

However, still getting the 404 error when I clicked on "Sign up" button

`[04/Feb/2016 20:30:21] "GET /sign-up/ HTTP/1.1" 404 1577`

Any further ideas?

**Comment by mjstealey** [comment]
> Any further ideas?

Use `./hsctl rebuild --db` so that the included development database is loaded and populates your base pages. 
It also includes a single admin user: user: **admin**, pass: **default**

**Comment by ahmetartu** [comment]
After passing `--db` option to `./hsctl rebuild`, it worked! Thanks Michael...
