### ISSUE TITLE
Quirky behavior of scrolling in MyResources page.

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#936]
When I go to the My Resources page I get two vertical scroll bars.  One just for the resource listing box and one for the whole page.  However if I resize my browser window to be wider or narrower (it works both ways) the internal scroll bar disappears and all resources are shown.

I would actually prefer to always get the display without the internal scroll bar.

**Comment by horsburgh** [comment]
Closing this because we will address it in #908
