### ISSUE TITLE
Navigation:  Apps Link Should Open a new Window

### ISSUE THREAD

**Issue by horsburgh** [hydroshare/hydroshare#939]
The link to the "Apps" page in the main navigation should open a new browser window or tab.  It's possible to go layers deep in the "Apps" stuff and then have a hard time getting back to hydroshare.org.

**Comment by mauriel133** [comment]
@mjstealey, is there a way to set this link to open in a new tab through the admin interface?

**Comment by mjstealey** [comment]
@mauriel133, Not directly, but some work arounds mentioned here: https://groups.google.com/forum/#!msg/mezzanine-users/iAFF3twUajg/idEIsNsjBQAJ

**Comment by mauriel133** [comment]
I can add the target property to the link on page load as they did there, will that be ok?

**Comment by mjstealey** [comment]
I'd think that would be fine so long as the Apps link is the only one that is affected.

**Comment by danames** [comment]
I agree with this suggestion.

**Comment by mjstealey** [comment]
@mauriel133 - Tested this on riverdev and all worked as expected, so the PR was merged. 
Just deployed the same codebase on www and not seeing the expected behavior.

Ideas?

**Comment by mauriel133** [comment]
It worked for me after clearing my browser's cache.

*Maurier Ramírez*
Computer Scientist
Utah Water Research Laboratory
Utah State University
8200 Old Main Hill
Logan, UT 84322-8200
Phone: (435) 932-0727

**Comment by mjstealey** [comment]
> It worked for me after clearing my browser's cache.

Check the edit to the [original post](https://github.com/hydroshare/hydroshare/issues/939#issuecomment-182511252)

**Comment by mauriel133** [comment]
Oh, good catch!

**Comment by mauriel133** [comment]
This issue has been fixed. Please confirm and close.

**Comment by horsburgh** [comment]
Working on dev.hydroshare.org, but not on www.hydroshare.org. The production instance still opens it in the same window. I cleared my browser cache and tested in chrome and firefox.

**Comment by mauriel133** [comment]
@mjstealey, maybe the change got reverted with the last release.

**Comment by mjstealey** [comment]
> maybe the change got reverted with the last release

Yep. It was a manual change last time (and now again this time). Opened a ticket for me to automate this.

**Comment by mauriel133** [comment]
@mjstealey, has this been automated now? If so I will close this issue.

**Comment by mjstealey** [comment]
Closing
