### ISSUE TITLE
Resource Landing Page: Need "Described By" as a term for RelationType

### ISSUE THREAD

**Issue by horsburgh** [hydroshare/hydroshare#940]
When adding a related resource on the edit page for a resource, a user has asked for a term "Described By" in the "Relation type" field on the "Add relation" form.

Also - some descriptive text above the "Add Relation" button would be helpful for users.  Something like what follows:

"Click the button below to add a relationship to another resource, external website, or document. You can express the type of relationship and then enter a URL to the resource or website. If the related resource does not have a URL, you can paste in a full text citation."

**Comment by mauriel133** [comment]
This relation type has been implemented.

**Comment by hyi** [comment]
Verified this has been implemented. Closing.
