### ISSUE TITLE
Resource Metadata Editing:  Enhance Metadata Editing with Descriptive Text

### ISSUE THREAD

**Issue by horsburgh** [hydroshare/hydroshare#942]
Some of the items on the resource metadata editing page are not self explanatory.  Need some tooltip text on items that describe what they are or some text next to them on the page that describes what should be entered.  Examples include:

* Manage access
* Related resources

**Comment by mauriel133** [comment]
Could you provide the help text to go along these functions?

**Comment by horsburgh** [comment]
For "Manage access" use the following:

Use this button to share your resource with specific HydroShare users. You can give other users the ability to view or edit this resource. You can also add additional owners who will have full permissions.

For "Related resources", you have already implemented text below the button, so we should be good there.

For the "Add source" button on the "Related Resources" tab use the following:

"If this resource was derived from another resource, click the button above to create a link to the source resource from which this resource was derived. If the source resource is a HydroShare resource, you should paste in the URL to the source resource in HydroShare. If the source resource is something outside of HydroShare, you can paste in a URL or a full text citation to the external resource."

**Comment by mauriel133** [comment]
These help text can sometimes be too long. Do you think an icon that shows the help text when hovered would be better? Something like what we have next to Select a licence dropdown.
![capture](https://cloud.githubusercontent.com/assets/2448568/13366850/22352b32-dc9b-11e5-82d7-ab0195f17aaa.PNG)

**Comment by horsburgh** [comment]
Yes I think that could work.

**Comment by mauriel133** [comment]
Is there more descriptive text to be added?

**Comment by horsburgh** [comment]
@mauriel133 - I think what you have is fine. What did you end up doing with the info icon on the manage access button when you moved it up to the toolbar at the top?

**Comment by mauriel133** [comment]
It's gone, but the icon has a hover text that reads "Manage who has access". Should I add it there or some other place?

**Comment by horsburgh** [comment]
Would it be lame to add it as the tooltip text when you hover over the button?

**Comment by mauriel133** [comment]
Like that?
![capture](https://cloud.githubusercontent.com/assets/2448568/14368660/68a07cdc-fcdc-11e5-9560-0c5c31101e8c.PNG)

**Comment by mauriel133** [comment]
I could instead add this message to the manage access interface window that pops up.

**Comment by horsburgh** [comment]
Why not both?

**Comment by hyi** [comment]
@mauriel133 Is this already done? Can this issue be closed?

**Comment by mauriel133** [comment]
This has been implemented and can be closed.

**Comment by horsburgh** [comment]
This is implemented on www.hydroshare.org. Closing.
