### ISSUE TITLE
Clean up ga_resources and ga_ows apps

### ISSUE THREAD

**Issue by hyi** [hydroshare/hydroshare#949]
A few utility functions from ga_resources and ga_ows apps are used throughout HydroShare codebase, but most functionalities in these two apps are not complete and not used. These few utility functions being used should be moved to hs_core app as part of HydroShare utility base with these two apps removed from HydroShare project as part of code base clean up work.

**Comment by hyi** [comment]
This is a subset of issue #958. I am assigning this to myself to look specifically on cleaning up ga_resources and ga_ows, but it'll be a low priority on my plate. If anyone else wants to look into this, please reassign.

**Comment by pkdash** [comment]
@hyi I think you can close this issue.
