### ISSUE TITLE
My Resources page date sorting ignores time

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#950]
When resources are sorted by last modified, the time should be considered.  If the most recent is first most recent should take into account time.  In the below 4:05 is after 4:04 so more recent and should be listed first.

![untitled](https://cloud.githubusercontent.com/assets/3456833/12922046/29a7615a-cf0d-11e5-89bd-3b85b9aa93e3.png)

**Comment by mauriel133** [comment]
@dtarb, can you verify that the issue has been solved?

**Comment by dtarb** [comment]
Tested and closing.  However we may not be done yet.  In looking at this I noticed that sorting by Owner uses the "First" name.  Is this what we want.  Filing another issue.
