### ISSUE TITLE
Retrieving password

### ISSUE THREAD

**Issue by wzell-usgs** [hydroshare/hydroshare#961]
When I try to retrieve a password for a previously-registered (or perhaps partially registered) email, I am told 'invalid user/email.' However, if I try to register a new account with that email I am told that the email is not unique (i.e., appears to be logged somewhere in the system).

![screen shot 2016-02-11 at 11 51 49 am](https://cloud.githubusercontent.com/assets/16402586/12983172/04ba87aa-d0b6-11e5-9a82-7ac66409b2b9.png)

**Comment by mjstealey** [comment]
@wzell-usgs - response sent via email

**Comment by mjstealey** [comment]
Resolved via email

**Comment by dtarb** [comment]
There is still a systemic problem here that needs to be addressed.  An account can be in one of two states:

A.  Active after a user has validated their email.
B.  Pending.  After a user has requested an account an email to validate their account is sent to the email provided, but the user has not yet clicked on the link in that email.
 
1.  If a user requests an account and provides an email for which an account is active they should be presented the following message:

> An account already exists for this email address.  If you have lost your password, [reset your password](url).

2.  If a user attempts to log in to an account that is pending (they enter correct username/email and password pair, account has been requested but validation email not clicked) they should be presented with a page that says: 

> This account has not been validated.  Check your spam folder for the verification email sent to you.  [Resend the validation email](url).

3. If a uses requests an account and provides an email for which an account is pending they should be presented the following message.

> An account with this email address has been requested but not validated.  Check your spam folder for the verification email sent to you.  [Resend the validation email](url).

4.  If a user requests a password reset for an email address of an account that is pending they should be presented the following message.

> An account with this email address has been requested but not validated so the password cannot be reset.  Check your spam folder for the verification email sent to you.  [Resend the validation email](url).

5.  If a user requests an account and provides a username for an account that is active, but an email that is unique they should be presented with the message: 
> The username you requested has already been taken by a different user, please enter a different username.

**Comment by mjstealey** [comment]
Initial user issue is resolved, subsequent work opened as new issue [#966]
