### ISSUE TITLE
Account Creation - Active/Pending workflow

### ISSUE THREAD

**Issue by mjstealey** [hydroshare/hydroshare#966]
An account can be in one of two states:
1.  **Active** after a user has validated their email.
2.  **Pending**  After a user has requested an account an email to validate their account is sent to the email provided, but the user has not yet clicked on the link in that email. 
   - [x] Embedded link should automatically expire after 24 hours freeing the requested credentials to be used again if desired.
   - [ ] If a user requests an account and provides an email for which an account is active they should be presented the following message:
   
   > An account already exists for this email address.  If you have lost your password, [reset your password](url).
   - [ ] If a user attempts to log in to an account that is pending (they enter correct username/email and password pair, account has been requested but validation email not clicked) they should be presented with a page that says: 
   
   > This account has not been validated.  Check your spam folder for the verification email sent to you.  [Resend the validation email](url).
   - [ ] If a uses requests an account and provides an email for which an account is pending they should be presented the following message.
   
   > An account with this email address has been requested but not validated.  Check your spam folder for the verification email sent to you.  [Resend the validation email](url).
   - [ ] If a user requests a password reset for an email address of an account that is pending they should be presented the following message.
   
   > An account with this email address has been requested but not validated so the password cannot be reset.  Check your spam folder for the verification email sent to you.  [Resend the validation email](url).
   - [ ] If a user requests an account and provides a username for an account that is active, but an email that is unique they should be presented with the message: 
   
   > The username you requested has already been taken by a different user, please enter a different username.

**Comment by dtarb** [comment]
Superceded by #2478 and resolved in 1.15 deploy so closing.
