### ISSUE TITLE
Improvements and optimizations on modal windows

### ISSUE THREAD

**Issue by Maurier** [hydroshare/hydroshare#967]
As suggested by @pkdash , in resource landing page, Instead of generating a modal window for every item we can use just one and pass the corresponding variables.

This will help avoid scalebility problems with the HTML.

**Comment by cuahsimarko** [comment]
I was thinking the same thing for anywhere we list resources, such as Groups. Let's talk. Also, is there a use-case for Signals or some sort of push notification?

**Comment by Maurier** [comment]
I want to point out that we have starting with these optimizations with the rewriting being done as part of #3186

**Comment by Castronova** [comment]
Stale
