### ISSUE TITLE
Hide manage access panel for published resources

### ISSUE THREAD

**Issue by hyi** [hydroshare/hydroshare#968]
Need to hide manage access panel for published resources disallowing users from changing access controls for published resources.

**Comment by horsburgh** [comment]
@hyi - the manage access panel was on the edit page.  @mauriel133 may have moved it to the main landing page in response to earlier requests from @dtarb that would have allowed granting new permissions for published resources (which we are no longer doing).  If that is the case, I suggest just moving it back to the edit page where it was before so it will be inaccessible when you disable editing for published resources.

**Comment by mauriel133** [comment]
It is in the landing page because of the shareable flag which grants view users the ability to grant view permissions when the flag is true.

**Comment by hyi** [comment]
@mauriel133 @pkdash While working on this, I found "Save changes" button does not show up for title, abstract, subject editing any more on edit mode due to the latest resource landing page refactoring merge. While working on trying to fix this issue, I found there has always been a reference error for shareable_ajax_submit not found, then I search in the code base and indeed did not find shareable_ajax_submit defined although it is referenced in line here: https://github.com/hydroshare/hydroshare/blob/develop/hs_core/templates/pages/genericresource.html#L235. Should we remove this line? Is shareable_ajax_submit defined anywhere?

**Comment by hyi** [comment]
@mauriel133 @pkdash It looks like a js file, resoruceLandingPageAjax.js, was not posted to the resource landing page refactoring branch, hence is missing. See https://github.com/hydroshare/hydroshare/blob/develop/hs_core/templates/pages/genericresource.html#L571 where this JS is referenced, but is not part of the code base. This missing js file may include that shareable_ajax_submit() js function, so @mauriel133, it might just be a matter of adding some missing files from your local env to fix this issue. I will create a separate issue about this and assign it to @mauriel133. After that issue was fixed, I can work on this issue to hide access control panel which might just be as simple as setting shareable flag to be false for published resources.

**Comment by horsburgh** [comment]
@mauriel133 - Thanks for reminding me.  I remember now why we exposed the manage access panel outside of the editing page.  So, yes - as you all have discovered, it needs to be disabled when the resource is published.  Sorry for any confusion.

**Comment by hyi** [comment]
The fix to this issue has been merged. Closing this issue.
