### ISSUE TITLE
Save changes button not visible on edit mode after resource landing page refactoring

### ISSUE THREAD

**Issue by hyi** [hydroshare/hydroshare#969]
Save changes button does not show up on edit mode for editing of title, abstract, subject, etc after resource landing page refactoring. It might just be an issue of some missing files such as resourceLandingAjax.js which is referenced here https://github.com/hydroshare/hydroshare/blob/develop/hs_core/templates/pages/genericresource.html#L571 but not present in the branch.

**Comment by mauriel133** [comment]
The directory \hydroshare\hydroshare\static is missing in the develop branch. Is this intended?

**Comment by mjstealey** [comment]
> The directory \hydroshare\hydroshare\static is missing in the develop branch. Is this intended

It gets generated on the collectstatic call when all static files from all apps are collected and placed there. In some situations such as creating a copy of www the `/hydorshare/hydroshare/static` directory will be made and pre-populated with the contents of the media files (profile photos, etc.).

**Comment by hyi** [comment]
Fix merged into develop and it is working now. Closing.
