### ISSUE TITLE
Export resource citation information in RIS format

### ISSUE THREAD

**Issue by pkdash** [hydroshare/hydroshare#97]
Refer to Section#7 of https://my.alfresco.com/share/hydroshare.org/page/site/HydroShare/document-details?nodeRef=workspace://SpacesStore/eab512e6-89df-48b8-a98a-2923083f6660 for requirements.

**Comment by dtarb** [comment]
Someone suggested to me to also support machine readability of citations by systems such as zotero.  See https://www.zotero.org/support/dev/exposing_metadata

**Comment by aphelionz** [comment]
@pkdash @mjstealey @dtarb @hyi This one?

**Comment by dtarb** [comment]
This is a nice wish list item, but I'll close for sanity.
