### ISSUE TITLE
SEO Plan

### ISSUE THREAD

**Issue by ironfroggy** [hydroshare/hydroshare#970]
This tickets lays out problems and planned solutions for poor SEO performance on the site. Implementation tickets will be created resulting from the information gathered here.

Problems:
- There is no clear click path from the front page to *any* discoverable resources
- Existing google results appear to have been crawled from previous versions of the site and no longer work
- Some existing google results only work if you're logged in
- The home page links to the discovery page, but it does not show anything until you enter search terms.
- User pages do not list *any* resources without loading them via Javascript, so search engines will have trouble seeing those links, and likely won't see or crawl them at all.

Proposed Solutions:
- Change default behavior of discovery page to "show all" until filtering query is entered or filters are selected
- Add a Site Map that lists all discoverable resources alphabetically by category. This would be mostly for search engine crawlers to find.
- Have the Site Map link categories to discovery searches of those results
- Change profile rendering to render contribution tab server side

**Comment by selimnairb** [comment]
Could we use the HTML view of the (resource list)[https://www.hydroshare.org/hsapi/resourceList/] REST API end point?  The listing for each resource lacks a link to the landing page for each resource, but this could easily be added.  Once we've done this, we can link to the resource list from the home page, at which point search engines should have a click path to each resource, no?

**Comment by ironfroggy** [comment]
We still need this to be linked from the page, usually in all pages in the footer, and be well presentable to human users that stumble on it. I think we'd want it to match the site styling.

**Comment by dtarb** [comment]
Lets get started on the planned solutions.  Having the discover page "show all" will need a bit of coordination with @alvacouch and @xuezhaokun, and will require some sort of paging option for when we have a lot of discoverable resources.   There are also plans for a geographic map on the discover page that need to be worked out.

When you say list by category this is unclear.  We have no thing called "category" for each resource.  We have "resource type".  We have subject.  These are user provided keywords and there may be multiple for each resource.  Are the second and third points really the same thing.  The site map lists "resource type" that then when you click on lists all the resources of that type.

The placement of the site map should be added to our page map diagram https://docs.google.com/drawings/d/1WBGON5o7zDxSWaNytCMkIV1ewfSCQ0ccqXIz0w3ZOs0/edit.

**Comment by ironfroggy** [comment]
@dtarb I should be able to handle the required changes to the discovery page, but will check in with Alva about it. There is already pagination there that I see.

When I referred to categories I specifically used a generic term. There are different ways to cut up resources into categories on Hydroshare and exactly which the sitemap uses isn't as important. I'll probably just go by resource type and possibly include keywords as well.

**Comment by hyi** [comment]
@alvacouch assigned to you for initial follow up on the current status and what remains to be done next for this issue.

**Comment by pkdash** [comment]
@alvacouch Is this issue still relevant?

**Comment by dtarb** [comment]
I am going to close this, I think we have better things to focus on in the time remaining.
