### ISSUE TITLE
Add author and contributor to include capability identify existing HydroShare user and then automatically fill out content

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#975]
A user wrote: I tried to fill in author information, for example David Tarboton was a contributor.  I attempted to add his HydroShare URL, but could not find that information anywhere when searching his resources.  My expectation would be that if I added a resource where a HydroShare user is a author or collaborator, they would automatically be notified. Is this assumption true?   Where does someone find their user URL

**Comment by mauriel133** [comment]
An auto-fill has been implemented for existing HydroShare users. As described in the paragraph above, are we also implementing notifications when I user is added to a resource as a collaborator?

**Comment by horsburgh** [comment]
@mauriel133 - does the auto-fill automatically populate the user's HydroShare profile URL in the author/contributor metadata for the resource? If so, the HydroShare URL part of this is solved. 

So, the question then is whether we want to notify users any time they are added to a resource as an author or contributor. And, at what point do we send them that notification (e.g., immediately when they are added or only when the resource is shared/made public, etc.). Adding a user as an author/contributor doesn't automatically give them view access, so this might be problematic for private resources.

**Comment by mauriel133** [comment]
@horsburgh, adding an existing author/contributor populates the user's HydroShare profile URL field.

**Comment by dtarb** [comment]
The access control and notification implications have not been addressed, so right now auto-fill is simply a convenience for the person editing the resource and does not involve the user being added as an author or contributor, just as would be the case if their information was typed in.  However I think we should set the following policy and implement the following enhancements.

- If a user is added as an author or contributor, they are given at minimum view permissions.  These permissions can not be removed as long as they are on the author/contributor list.  (Rationale for this is that if you are named as an author/contributor you should at least be able to see the resource)
- A user receives a notification saying they have been added as an author/contributor to a resource.  (Right now our only notification mechanism is email).  If they are removed, they get a notification saying they have been removed.
- If a resource is formally published (with DOI) then authors/contributors receive a notification.
- If a comment is posted on a resource the authors (not contributors) receive a notification.
- There do not need to be any other notifications to the authors/contributors regarding any other changes to the resource permissions, files, metadata,  or anything else.

Note that I am setting this only as medium priority, so other high priority issues come first.

**Comment by mauriel133** [comment]
@hyi, I have not worked much with the notification system. Would you be better fit to implement @dtarb's bullet points above?

**Comment by hyi** [comment]
@mauriel133 I can take care of implementing the email notifications as described by @dtarb above. However, this is a medium priority item, and I will not plan to spend time implementing this until I get quota and other high priority items implemented first. In the meantime, @pkdash can implement this also if he has time. Otherwise, I'll implement this after I get other high priority items implemented first.

**Comment by cuahsimarko** [comment]
@hyi are you working this?

**Comment by hyi** [comment]
@cuahsimarko I have not worked on this, but can start to work on this after I get iRODS user zone oauth implemented and deployed. @dtarb I assume I just need to implement what you suggested above regarding the access control and notification mechanisms for authors and contributors for this issue.

**Comment by dtarb** [comment]
The automatic filling in has been implemented for a while.  The notifications part of this suggestion would need implementing.  But given how long this has sat, I would prefer a decision on implementing these front facing notification improvements to be deliberate on the part of CUAHSI.  This will involve additional emails that get sent to users.  Do we want to do this?  Do we have a mechanism for users to turn this off.

**Comment by eclark-cuahsi** [comment]
Closing per backlog review on 6/9. Overlaps with #976
