### ISSUE TITLE
Re-work resource file list display to handle large amounts of files

### ISSUE THREAD

**Issue by selimnairb** [hydroshare/hydroshare#977]
Currently, all resource content (i.e. resource files) is loaded when the resource landing page loads.  This works fine for resources with a small amount of content.  However, some resource types (e.g. the RHESSys model instance) can have hundreds or thousands of resource files.  The resource landing pages needs to be reworked to maintain fast load times an not overwhelm the user with a large listing of content files.  A hierarchical view of resource content that is loaded on demand would be one way to do this, but I am open to others.

**Comment by selimnairb** [comment]
To accomplish this, we will need:

1 [ ] New REST API call */hsapi/resource/UUID/directory_listing/PATH* that returns a simple list of the *ils* output on */bags/UUID/data/contents/PATH*
2 [ ] Front end JS code to display top-level files and directories (i.e. non-recursive contents of /bags/UUID/data/contents/) giving the user an option to navigate to any directory at the current level.  Directory listing for each level of the hierarchy will be fetched as needed.

@hyi and @selimnairb Will work on 1, @mauriel133 will work on 2.

**Comment by selimnairb** [comment]
Based on comments from the group today, this interface needs to be extended to allow the following use cases:
  - Creating a new folder at an arbitrary location in a directory hierarchy
  - Uploading a resource file to a folder at an arbitrary location in a directory hierarchy
  - Moving a file to an arbitrary location in a directory hierarchy

**Comment by alvacouch** [comment]
See 
https://docs.google.com/document/d/1RHiwpJ1IoyAZzmC6yHykg9vE618M67la5ZZfyKaiDRU/edit?usp=sharing

for a backend interface to folders **that already exists**. It is not in the code base now because there was not a plan for immediate use. It is completely implemented and tested as part of the labeling subsystem. 

It lives in my private repo. I can put it in a HydroShare branch if you want. 

It has a fairly unique feature that makes it interoperate with GitHub, google, and iRODS rather well: 

* folders spring into existence when referenced. 
* folders are objects of the second class. They have no existence other than holding contents. 

This makes the interface less stateful than a regular folder interface, which makes it somewhat easier to write code to manipulate it,. I can easily make folders objects of the first class, but the current code might make implementation easier.

**Comment by alvacouch** [comment]
The version of hs_labels with folders is a few commits behind the deployed version. . 
A little simplification (but not much) is needed. An hour or two.....

**Comment by alvacouch** [comment]
A working version of hs_labels is in my private working repository gitthub.com/HydroShare/hs_labels/hs_labels/
But alas, this won't help you.... this implements folders for resources, rather than folders inside resources. It is probably easier to use iRODS features inside a resource.

**Comment by mauriel133** [comment]
@selimnairb, here is a basic implementation of what I'm going with. Let me know when the back end is ready so I can bring it together.

![capture](https://cloud.githubusercontent.com/assets/2448568/13827223/f3b76c80-eb80-11e5-82d9-94c9b36e8769.PNG)

**Comment by zhiyuli** [comment]
It looks great !!! Look forward to seeing it on www

one minor comment: is it a potential issue that we allow multiple folders
to have same name?

**Comment by mauriel133** [comment]
That won't happen since we'll be showing the physical hierarchy once @selimnairb is done implementing the methods, this is just me trying out the interface so I used the same names for the folders.

**Comment by hyi** [comment]
@dtarb @mauriel133 now that Brian does not work on HydroShare any more, what should we do with this issue?

**Comment by dtarb** [comment]
@mauriel133 can you please let @alvacouch know what back end API functions you think are needed to implement folders.  @alvacouch once you hear from @mauriel133 can you assess what it will take to have our landing pages be able to manage folders within resources.  Management likely involves all the usual operations like create, delete, move files between them etc.

**Comment by mauriel133** [comment]
@hyi, how are we storing the files?  I'm looking at this that plugin takes care of navigating the hierarchy if we can get access to the entire file: https://www.abeautifulsite.net/jquery-file-tree

I could easily further improve this to add folder creation and uploading to a specific folder.

**Comment by hyi** [comment]
@mauriel133 We store the files in iRODS. All files for an individual resource are stored under a root named with resource uuid with folder structure as shown below:
![resource_bag_1](https://cloud.githubusercontent.com/assets/476302/17518468/04df8b84-5e16-11e6-9a1b-4263594c5336.png)
Under data directory, the structure is shown below:
![resource-data](https://cloud.githubusercontent.com/assets/476302/17518481/13d8ff26-5e16-11e6-8c15-63dd3ef7e3ae.png)
Then all resource contents are stored under this content directory. Currently, all resource content files are stored under this content directory without sub-folders. Do we want to add folder structures when content files are being first uploaded when creating the resource? If not and we want to keep the current behavior just to store all uploaded content files into the same content directory in iRODS backend, then the initial folder structure will be the "content" directory that includes all content files without subfolders. ```listdir()``` function in django_irods https://github.com/hydroshare/django_irods/blob/master/storage.py#L224 can be called to return you a list that includes a sub-directory list and a file list under a specified parent path. If you can implement the front end that allow users to create subfolders under ```content``` directory and drag/arrange files into different subfolders, and also allow users to navigate to subfolders and arrange subfolders, you can query the backend functions to list all files and folders under a folder, and after the user confirms the file operation, such as create a sub-folder, or move a content file to a sub-folder, or else, a corresponding backend function can be called to rearrange files and folders in iRODS backend. If you can get front end done with needed backend functions mocked for now, I can easily provide/fill-in all needed iRODS backend functions to hook up to your front end. How does this sound?

**Comment by dtarb** [comment]
I think that as far as the interface is concerned the bagit structure and data and contents folders should not be exposed to the user.  I think that what we are looking at here is for users to be able to organize their content that is in the content folder into subfolders using any structure that they deem fit for the organization of the data.

**Comment by hyi** [comment]
Agreed with @dtarb

**Comment by hyi** [comment]
@dtarb @horsburgh @mauriel133 What Brian initially stated in this issue to work on is essentially to create hierarchical view of resource content that is loaded on demand to avoid overwhelming resource landing page load for a resource with hundreds of files. It assumes resource (i.e., RHESSyS) zip already unzipped with folder structures preserved (which is yet to be done in HydroShare) and does not involve manipulation of folder structures from resource landing page. I suggest we focus on hierarchical view of resource content loaded and perhaps downloaded on demand without bothering with file folder structure editing/manipulation at all, which will simplify @mauriel133's front-end work without requiring any backend work, so I can focus on working on unzipping file with preserved folder structure during resource creation phase. What do you think?@dtarb @horsburgh @mauriel133 @goodalljl

**Comment by pkdash** [comment]
I agree that we initially implement view of the resource folder hierarchy on the resource landing page. Then we can move to folder and file management.

**Comment by dtarb** [comment]
It surprises me how hard this is.  I'll write up what I think the functionality should be from a complete perspective, then we can decide to perhaps only implement part or implement in phases.

Is surprises me that unzipping is so much work.  It should be a single command.  It strikes me that if we were working with an NFS or FUSE interface to iRODS then it would be just one command.  It is this sort of use that has had me pushing for NFS or FUSE for so long.  I think that iPlant realized this need too, which is why they pushed for FUSE.  I worry that by not using NFS or FUSE we have to basically rebuild in our iRODS interface all the basic functionality of a file system, and that is hampering us.

**Comment by hyi** [comment]
@dtarb You are right on the point that it is not hard to unzip or zip files, which just takes one command or one function. The hard part is the user interface UIUX to best serve use cases including how to handle performance issue for big file unzipping and zipping in conjunction with web server timeout limitations. We need to use celery task to do unzipping and zipping asynchronously for large files and need to handle asynchronous process well on the front-end interface.

**Comment by dtarb** [comment]
@horsburgh @mauriel133 @hyi @pkdash 
See https://docs.google.com/document/d/1HMnrX1HKNk8MMqLzfQzRr2O-Vj8ICQMx5mn2rTmuoOs/edit# where I have drafted functional requirements for folders within resources, as a follow up to the teleconference 8/10/16 where we discussed this.  My sense is that this is more than what @horsburgh wanted to implement with folders, so I am open to trimming where possible, or implementing in phases so we can get basic functionality quickly.

**Comment by dtarb** [comment]
@danames @shawncrawley @zhiyuli  could you please also take a look at the Folders functionality requirements as I think that some of it will impinge on what apps can do, and there are comments about business rules for the files comprising a shapefile in a folder within a resource with other content.

**Comment by horsburgh** [comment]
@mauriel133 - based on the feedback from the call last week, I told you that I would note a couple of outcomes. We decided that in phase 1 of folders we wanted to make sure to support the following:

* [ ] List view
* [ ] Icon view
* [ ] Download of selected files/folders (selection is zipped and then downloaded as a single zipped file)
* [ ] Sorting of icons and list by name, type, size, and last modified (if last modified is easily available)

**Comment by mjstealey** [comment]
#1491 - PR for folder work

**Comment by dtarb** [comment]
With 1.8.0 this is deployed so closing.
