### ISSUE TITLE
Update resource landing page to display file upload unzip status

### ISSUE THREAD

**Issue by selimnairb** [hydroshare/hydroshare#978]
It is now possible to request that a resource file be unzipped on resource creation (though this option is currently disabled and not exposed to the user).  This unzipping is done asynchronously via a Celery task.  As the file is unzipping, status information is written to the resource stored in the Django database.  This status information should be displayed to the user on the resource landing page (somewhere near the "Content" section).  If there is any error during unzipping, this error should be displayed as well.  See #924 for more details.

**Comment by mjstealey** [comment]
RHYSSes specific, no one to take over this work
