### ISSUE TITLE
SEO: Include crawlable resource list in profile page w/o JS

### ISSUE THREAD

**Issue by ironfroggy** [hydroshare/hydroshare#981]
Current profile page requires Javascript to render the list of resources for a user. We need to include at least a basic list in the rendered version, so search engines crawling it without Javascript will see those resources and link profiles to resources.

Part of #970

**Comment by hyi** [comment]
@mauriel133 I am putting this on your plate for initial investigation.

**Comment by mauriel133** [comment]
The HTML with link for each resource is actually rendered, but the tab is inaccessible without bootstrap.js. Wouldn't search browsers still find it in the HTML?

**Comment by cuahsimarko** [comment]
We should have a quick chat about heapanalytics (coding style in VueJS)

**Comment by Castronova** [comment]
Stale.
