### ISSUE TITLE
Landing page cannot display resource-specific metadata on latest dev branch

### ISSUE THREAD

**Issue by zhiyuli** [hydroshare/hydroshare#984]
I checked out latest dev branch and accidentally found Ref Time Series can not display resource-specific metadata. Then I created a Raster, a Geog. Feature and a Model Program (I didn't try other res types yet). They are having the same issue. We guess this may be related to the recent refactoring of landing page. @mauriel133 

![image](https://cloud.githubusercontent.com/assets/10070599/13087155/c747b144-d4a3-11e5-8820-b06f296fc613.png)

**Comment by mauriel133** [comment]
@mjstealey, it seems that  django does not process blocks in included templates. Do you know a workaround for this? Otherwise I can just move the code back to genericresource.html.

http://stackoverflow.com/questions/9633387/django-using-blocks-in-included-templates

**Comment by mjstealey** [comment]
> Do you know a workaround for this?

@ironfroggy would be better equipped to answer this question.

**Comment by hyi** [comment]
@mauriel133 I suggest just to move the code snippet that includes ```block extended_metadata``` and ```block extra_section``` from content-tabs.html back into genericresource.html for specific resource types to extend the block content to get it work first for now with comment indicating the reason for future reference.

**Comment by mauriel133** [comment]
@zhiyuli, can you verify if the issue is solved?

**Comment by zhiyuli** [comment]
tested on www. closed
