### ISSUE TITLE
web app resource URL appending issue

### ISSUE THREAD

**Issue by yanliu-chn** [hydroshare/hydroshare#993]
When I create a web app resource in hs, I need to give a URL for hs to invoke. My URL looks like:
http://gwdev8.cigi.illinois.edu:8080/home/apps.php?app=taudem

When I open a DEM resource, and open it with the web app, the full URL becomes an invalid URL:
http://gwdev8.cigi.illinois.edu:8080/home/apps.php?app=taudem/?res_id=8defcfa0edd848daaf0ef25271fc6703&usr=yanliu&src=hs

So it'd be good to parse the URL configured by the app creator and merge the URL parameters with the hs params in order to fix this issue.

**Comment by danames** [comment]
@zhiyu - is this a relatively easy fix?

**Comment by zhiyuli** [comment]
@yanliu-chn @danames 
how about this:
we let user input a url/string containing some pre-defined key words. like:
 http://gwdev8.cigi.illinois.edu:8080/home/apps.php?app=taudem&res-id=_HYDROSHARE_RESOURCE_ID_

Here _HYDROSHARE_RESOURCE_ID_ is a key word, we will replace it with real res id.

So the user can input any url/string, and we just search for keywords and replace them with real values.

**Comment by danames** [comment]
This seems like a workable solution. We could extend it with additional
"url template terms" later as needed.

**Comment by yanliu-chn** [comment]
Hi Drew,

It's a good solution. This solution would allow app contributor to specify their own parameter names instead of res-id defined in HS. It also allows HS to define parameters that web apps need, including data resource id, user id, and possibly authentication information, too.

Here is something in my mind from app contributor point of view:
- define "variable" form in programming fashion, e.g., ${HS_RES_ID} instead of _HS_RES_ID_
- HS should list which variables are allowed. These variables include general ones (the existing ones), resource specific ones (e.g., metadata attributes associated with that particular resource (e.g., raster)), access control variables (what if the web app consumes the data resource files and as a result, pushes back additional files to the resources? the app then needs some way to write the resource with appropriate permission). Which variables to allow needs a design.
- HS should check the validity of the URL before saving the app.

**Comment by danames** [comment]
Yan for clarification, are you suggesting the URL template should be like
this:

http://my.url.com/mypage.php?myvariable=abc&myid=${HS_RES_ID}&mynewparam=${HS_XXX
}

Then our app resource code will replace the ${...} with the appropriate
metadata or variable from HydroShare?

I think this is a fine solution.

Can we discuss a list of optional template parameters?

how about:

${HS_RES_ID}                        required....
${HS_RES_NAME}                 could be handy?
${HS_HOST}                           this will tell us if we are launching
from www. or playground. etc.

others?

**Comment by yanliu-chn** [comment]
Yes. ${...} is easier to parse using regex. 

I do not know enough of HS about which attributes of a resource are defined. I know with res_id, I can go back to HS rest api to pull more info about the resource. HS_HOST may not be needed because the URL is invoked in user's browser and if the web app does not pass this back to HS, there is no way for HS to know if an app is invoked on this host. HS_RES_TYPE may be more useful than HS_RES_NAME.

Also, for the parameters available for web app URL config, the value of them must not contain special characters in a URL such as :, &, /, ?, = ... Otherwise, URL instantiation will produce invalid URL too. This is a constraint when deciding which param should be allowed in app url.

**Comment by zhiyuli** [comment]
closed. tested on www
