### ISSUE TITLE
HTML Title element sometimes not set

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#995]
The following illustrates a resource that displays "Untitled" in the browser tab that I think comes from the HTML title element, but the resource does have a title.  This seems to occur if the Title is populated automatically from a netCDF file.  
![untitled](https://cloud.githubusercontent.com/assets/3456833/13206188/3608080c-d8b6-11e5-98d4-d67c78f02f99.png)

**Comment by pkdash** [comment]
@dtarb See if this can be closed.

**Comment by dtarb** [comment]
Looks good on Dev, I hope it propagates through to www.

**Comment by dtarb** [comment]
Re-opening as this did not propagate through to www.
![untitled](https://cloud.githubusercontent.com/assets/3456833/14625954/b23a6670-05a4-11e6-9945-33b40d1837e4.png)

**Comment by pkdash** [comment]
@dtarb I assume this is a resource previously existed before the fix  was made. Could write a migration script to fix it for all the old resources.

**Comment by dtarb** [comment]
Yes.  Depending on how hard this is, it may not be worth it for old resources.  However a related issue is that this shows up as "Untitiled" in Discover, which does need fixing.  @alvacouch and @xuezhaokun could comment on whether this will still be a problem in the new Discover they are working on, but it seems that there is a basic data model problem in that the same information seems to be stored in two places, putting burden on developers to keep in sync.

![capture](https://cloud.githubusercontent.com/assets/3456833/14637921/c90c779c-05f1-11e6-91f5-7fcbba8f4612.JPG)

**Comment by pkdash** [comment]
The title problem in discovery page can be fixed by using resource.metadata.title in place of resource. title

**Comment by dtarb** [comment]
Since Discover pull request #1108 under review can you please make sure this gets into the Discovery deploy

**Comment by xuezhaokun** [comment]
@dtarb I think I got it fixed in pull request #1108 by replacing resource.title with resource.metadata.title

**Comment by pkdash** [comment]
@dtarb Should this be closed?

**Comment by dtarb** [comment]
Seems to be fixed.
