### ISSUE TITLE
THREDDS Server not opening

### ISSUE THREAD

**Issue by dtarb** [hydroshare/hydroshare#996]
The following error occurs with a netCDF resource when trying to launch the THREDDS OpenDap service.

![untitled](https://cloud.githubusercontent.com/assets/3456833/13206213/8e871a4a-d8b6-11e5-9ae0-4e748d4a4ae2.png)

**Comment by rayi113** [comment]
Hong modified her cron job script to restart tomcat if necessary.  It will take some more time to discern why tomcat stopped in the first place.  But that said, it should be working now, and this solution will allow it remain working until we migrate to the hyrax-based solution.

**Comment by hyi** [comment]
This should not be an issue any more since we went with the new THREDDS Server implementation.
